
// vim: et:ts=4:sw=4

= LA_pack primer
:doctype: book
:toc:
:toclevels: 4

:Author: Dr. JГјrgen Sauermann, GNU APL
:page-width: 120em
:iconsdir: /usr/share/asciidoc/icons
:icons:

== Abstract

GNU APL implements the APL functions monadic вҢ№ (aka. *Matrix Inverse*) and
dyadic вҢ№ (aka. *Matrix Divide*) by means of _LApack functions_. These LApack
functions were originally written in FORTRAN, but then manually translated
from FORTRAN to Cpp by the author. In this translation, features of the
LApack functions that were not needed for вҢ№ were removed to simplify the Cpp
code as much as possible.

== Monadic вҢ№: Matrix Inverse

Monadic *вҢ№* is the special case of dyadic *AвҢ№B* where A is the unit matrix:

----
      Let AвҶҗ(вҶ‘вҚҙB) вҲҳ.= (вҶ‘вҚҙB). Then вҢ№B вҶҗвҶ’ AвҚҙB.
----

*Bif_F12_DOMINO::eval_B(Value_P B) const*, implements
monadic *вҢ№*. It simply constructs a unit matrix *I* of proper
size and then returns *Bif_F12_DOMINO::eval_AB(I, B)*, i.e. the result of
the implementation of dyadic *AвҢ№B*. See below.

== Dyadic AвҢ№B: Matrix Divide

In APL, *AвҢ№B* for an N-column matrix *A* is defined in terms of each column
of *A*:

----
      Let  XвҶҗAвҢ№B. Then  X[;J] вҶҗвҶ’ A[;J]вҢ№B for all (scalar) columns JвҲҲвҚіВҜ1вҶ‘вҚҙA.
----

In other words, computing *AвҢ№B* for a matrix *A* boils down to computing
*AвҢ№B* for (column-) vectors (which are the columns of *A*). For every such
column vector a of *A*, the result is a column vector *x* of *X*:

   B вҲҳ x вүЎ a   вҶҗвҶ’   x вүЎ a вҢ№ B   вҶҗвҶ’   x вүЎ a вҲҳ BвҒ»В№

NOTE: GNU APL has a dyadic function *AвҲҳB* вҶҗвҶ’ *A +.Г— B*. Usage statistics of
APL show that the vast majority of inner products is the matrix multiplication
aka. *A +.Г— B*. The GNU APL function *AвҲҳB* is an optimized version of this
important special case *A +.Г— B* of the more general inner product *A f.g B*.

Because *B* is the same for all columns a of *A* (and their corresponding
result columns *x* of *X*), the result *X* of *XвҶҗAвҢ№B* is computed in two steps:

. compute *BвҒ»В№*
. compute *XвҶҗAвҲҳBвҒ»В№*

The second step *XвҶҗAвҲҳBвҒ»В№* is simple, therefore only the first step,
the computation of *BвҒ»В№* is of concern here.

BTW, the iteration over the columns of *A* in the second step above occurs
near the end of function *LA_pack::gelsy()* in function *trsm()*.

To compute *BвҒ»В№*, matrix *B* is factorized into two matrices *Q* and *R*
which have the following properties:

* *Q* is orthogonal (Hermitian for complex *B*). That is: *QвҒ»В№ вүЎ вҚү+Q*,
* *R* is upper triangular, i.e. *Rбөўвұј = 0* for all *i > j*,
* *B = QвҲҳR*,

Once *Q* and *R* are found, *BвҒ»В№* can be computed easily with:

----
      BвҒ»В№ = (QвҲҳR)вҒ»В№ = RвҒ»В№вҲҳQвҒ»В№ = RвҒ»В№вҲҳвҚү+Q.
----

The inverse of an upper triangular matrix (such as *RвҒ»В№*) is far easier
to compute than the inverse of a general matrix (such as *BвҒ»В№*). See below.
What remains is therefore the computation of a QR factorization of an
arbitrary matrix *B*.

=== Inversion of an orthogonal Q

The inversion of an orthogonal matrix *Q* means transposition of *Q* (and,
in the complex case, conjugation of the complex items).
However, unlike in APL where *вҚүQ* is a new value computed from *Q*, this
transposition is never computed in Cpp or in FORTRAN. Instead, where *вҚүQ* is
needed, the items of matrix *Q* are simply accessed with the row and column
interchanged. IOW, with a little bit of care regarding what are rows and what
are columns *вҚүQ* is no-op. In GNU APL three typedefs are used to distinguish
rows and columns throughout the code:

----
   In LApack.hh:

   typedef int Crow;   // row number
   typedef int Ccol;   // column number
   typedef int Cdia;   // diagonal item (row == column)
----

The translation from FORTRAN to Cpp is somewhat tricky for two reasons:

. FORTRAN indices run from 1..N while Cpp indices run from 0..N-1
. FORTRAN matrices are stored in column-major order (i.e. adjacent items
  in memory belong to the same column) while Cpp matrices are stored in
  row-major order (i.e. adjacent items in memory belong to the same row).

=== Inverting an upper triangular matrix R

Suppose *R = opвӮҒ вҲҳ opвӮӮ вҲҳ ... вҲҳ opвӮҷ вҲҳ ID* where every *opвӮ–* adds a multiple
of some row of R to some other row of R. Then, as we learn in school,
*RвҒ»В№ = ID вҲҳ opвӮҒ вҲҳ opвӮӮ вҲҳ ... вҲҳ opвӮҷ*. In other words, if the operations
*opвӮҒ*, *opвӮӮ*, ..., *opвӮҷ* turn a matrix *R* into the identity matrix, then
the same operations (in the same order) turn the identity matrix into
the inverse *RвҒ»В№* of *R*:

----
    в”¬ в•”в•җв•җв•җв•җв•җRв•җв•җв•җв•җв•җв•Өв•җв•җв•җв•җAUGв•җв•җв•җв•җв•—     в•”в•җв•җв•җв•җIDв•җв•җв•җв•җв•җв•Өв•җв•җв•җRвҒ»В№в•җв•җв•җв•җв•җв•— в”¬
    в”Ӯ в•‘           в”Ӯ 1         в•‘     в•‘ 1         в”Ӯ           в•‘ в”Ӯ
    в”Ӯ в•‘           в”Ӯ   1   0   в•‘     в•‘   1   0   в”Ӯ           в•‘ в”Ӯ
    N в•‘           в”Ӯ     1     в•‘  вҶ’  в•‘     1     в”Ӯ           в•‘ N
    в”Ӯ в•‘           в”Ӯ   0   1   в•‘     в•‘   0   1   в”Ӯ           в•‘ в”Ӯ
    в”Ӯ в•‘           в”Ӯ         1 в•‘     в•‘         1 в”Ӯ           в•‘ в”Ӯ
    в”ҙ в•ҡв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•§в•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•қ     в•ҡв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•§в•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•қ в”ҙ
    в”ң в”Җв”Җв”Җв”Җв”ҖNв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”ҖNв”Җв”Җв”Җв”Җв”Җв”Ө     в”ңв”Җв”Җв”Җв”Җв”ҖNв”Җв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”ҖNв”Җв”Җв”Җв”Җв”Җв”Ө
----

The operations that turn an upper triangular matrix *R* into the identity
matrix ID are fairly simple:

. *R* is upper triangular. Therefore the last row of *R*, say row *n*,
  has only one nonzero element *rвӮҷвӮҷ* on its diagonal. For every row above
  that last row, say row *k* (i.e. with k < n), do:
.. Let *rвӮ–вӮҷ* be the last element in row *k*. Subtract a multiple of the last
   row from row *k* so that rвӮ–вӮҷ becomes *0*.
.. That multiple is *rвӮ–вӮҷГ·rвӮҷвӮҷ*.
.. Since all other elements of the last row are *0*, this only sets *rвӮ–вӮҷ* to
   *0* but does not change any other element of row *k*.
.. After repeating this step for every k < n the entire last column of the
   matrix *R* is *0*, except for the element *rвӮҷвӮҷ* on the diagonal.
. Repeat the same step for the second-last, third-last, ... first column of
  the matrix. In every iteration one column of *R* is set to 0 above the
  diagonal. After the last *k=1* the matrix is diagonal (i.e. all elements
  above *and* below the diagonal are *0*).
. Finally, subtract a multiple of every row from itself so that the
  diagonal item becomes *1.0*.
.. That multiple for diagonal element rвӮ–вӮ– of row k is (1-rвӮ–вӮ–)Г·rвӮ–вӮ–.
.. After repeating that step for every *k вүӨ n* *R* is the unit matrix.
. Notice that every operation above subtracts a multiple of some row from some
  other (or the same) row.

The algorithm above defines the sequence *opвӮҒ вҲҳ opвӮӮ вҲҳ ... вҲҳ opвӮҷ* above,
where *n* is the number of columns in *R*. In practice (in LApack and
consequently also in GNU APL) these operations are not performed on *R* first
and then on the identity matrix afterwords but rather in parallel:

. Start with a matrix *R, AUG* where *AUGвҶҗ(вҚҙR)вҶ‘(вҚівҶ‘вҚҙR)вҲҳ.=вҚівҶ‘вҚҙR)*. That is, *AUG*
  is initially the unit matrix with the same shape as *R*. The matrix *AUG*
  (or sometimes the matrix *R,AUG*) is commonly known as the _augmented matrix_.
. The operations described above are then simultaneously applied to the
  left half (i.e. to *R*) and to the right half (i.e. to *AUG*) until the left
  half *R* of *R,AUG* has become the unit matrix. At that point, the right
  half *AUG* has become the desired inverse *RвҒ»В№* of *R*.
. All this happens in functions *LA_pack::invert_UTM()* and 
  *LA_pack::invert_QUTM()*. The term *QUTM* stands for **Q**uadratic **U**pper
  **T**riangular **M**atrix and takes advantage of the fact that the inversion
  of a non-quadratic upper triangular MГ—N matrix is essentially the inversion
  of its upper NГ—N sub-matrix. The rows N+1..M are all zero and become zero
  columns in the inverse.

=== QR factorization

==== Householder matrix

For the moment we consider only real matrices; the complex case is almost
identical, except that *вҚүX* becomes *вҚү+X* in the complex case. *вҚү+X* is
called the _conjugate transpose_ of *X* which is the same as the "normal"
transpose if *X* is real.

Let *B* be an arbitrary MГ—N matrix.

Let *VвҶҗ1вҶ“B[;1]*, i.e. V is the first column of *B* except the
diagonal item *B[1;1]*.

Let *LвҶҗ+/VГ—V*, i.e. *L* is (the square of) the Euclidean length of *V*.

The Householder matrix *H=H(B)* for matrix *B* is then defined as:

----
              2
      H = I - в”Җ Г— V вҲҳ.Г— V.
              L
----

That is:

----
             вҺ§ 1.0 - 2Г—V[i]Г—V[i]Г·L     if i=j, and
H = (H)бөўвұј =  вҺЁ
             вҺ© - 2Г—V[i]Г—V[j]Г·L         otherwise.
----

It follows immediately that:

. *H* is _Hermitian_ (aka. _symmetric_ if *H* is real). I.e. *H = вҚү+H*,
. *H* is _unitary_ (aka. _orthogonal_ if *H* is real). I.e. *HвҒ»В№ = вҚү+H*, and
. *H* is _involutary_. I.e. *H* = *HвҒ»В№*

These really nice properties of *H*:

. make the computation of the transposition *вҚүH* essentially a no-op, and
. ensures that the composition *H = HвӮҒ вҲҳ HвӮӮ вҲҳ ... вҲҳ HвӮҷ* of several Householder
  matrices is also Hermitian (complex case) or orthogonal (real case).

In the following let:

* *B* be an arbitrary real or complex matrix,
* vector *B1* be the first column of *B*, and
* scalar *B11* be the first item of column vector *B1* (= the first item
  on the diagonal of B).

In the LApack code *B1* is usually a variable named (lowercase) *x* and *B11*
a scalar variable named (uppercase) *ALPHA* (or *вҚә* in comments).
That is, matrix B looks like this:

----
      LApack matrix B        APL matrix B
      в•”в•җв•җв•җв•Өв•җв•җв•җв•җв•җв•җв•җв•җв•җв•—      в•”в•җв•җв•җв•җв•җв•Өв•җв•җв•җв•җв•җв•җв•җв•җв•җв•—
      в•‘ вҚә в”Ӯ         в•‘      в•‘ B11 в”Ӯ         в•‘
      в•ҹв”Җв”Җв”Җв”Ө         в•‘      в•ҹв”Җв”Җв”Җв”Җв”Җв”Ө         в•‘
      в•‘   в”Ӯ         в•‘      в•‘     в”Ӯ         в•‘
      в•‘   в”Ӯ         в•‘  вҶҗвҶ’  в•‘     в”Ӯ         в•‘
      в•‘ x в”Ӯ         в•‘      в•‘ B1  в”Ӯ         в•‘
      в•‘   в”Ӯ         в•‘      в•‘     в”Ӯ         в•‘
      в•‘   в”Ӯ         в•‘      в•‘     в”Ӯ         в•‘
      в•ҡв•җв•җв•җв•§в•җв•җв•җв•җв•җв•җв•җв•җв•җв•қ      в•ҡв•җв•җв•җв•җв•җв•§в•җв•җв•җв•җв•җв•җв•җв•җв•җв•қ
----

There are subtle but noteworthy differences between the APL code discussed
below and the LApack FORTRAN or Cpp code:

* In the original FORTRAN code of LApack, the vector *x* _excludes_ the
  diagonal element *вҚә* and *вҚә* is passed as a separate function argument or
  result.
* In the GNU APL Cpp translation of that code, the vector *x* also
 _excludes_ the diagonal element *вҚә*. However, *вҚә* is not passed as a separate
  function argument like in FORTRAN. Instead Cpp takes advantage of the fact
  that our matrices are stored in FORTRAN order which makes *вҚә вҶҗвҶ’ x[-1]* and
  therefore a function that already knows *x* can easily recover *вҚә* from *x*.
* In the APL code below, the vector *B1* (which corresponds to *x*)
  _includes_ the scalar *B11* (which corresponds to *вҚә*).


Instead of a strict mathematical proof we use APL as a tool of thought.

Let *V* be a real or complex vector. The following APL function named
*Householder* simply implements the definition of a Householder matrix
given above:

----
вҲҮHвҶҗHouseholder V;I;L
 вҚқ
 вҚқвҚқ return the Householder matrix (aka. elementary reflector) for vector V
 вҚқ
 IвҶҗIвҲҳ.=IвҶҗвҚівҚҙV        вҚқ I:  the (вҚҙV)Г—(вҚҙV) identity matrix,
 LвҶҗ+/VГ—+V           вҚқ L:  в•‘Vв•‘ВІ i.e. the square of the norm of vector V
 HвҶҗI-(2Г·L)Г—VвҲҳ.Г—+V   вҚқ H:  the Householder matrix for vector V
вҲҮ
----

Next we define a somewhat random matrix *B* that shall prove our claims
by example (aka. _incomplete induction_):

----
      MNвҶҗ(M N)вҶҗ4 3                 вҚқ choose a matrix size (MвүҘN)
      вҺ•RLвҶҗ+/вҺ•TS в—Ҡ BвҶҗ?(2, MN)вҚҙ18    вҚқ prepare for random B
      BвҶҗ+вҢҝ9 0J9Г—[1]B               вҚқ some complex MГ—N random matrix B
      B11вҶҗвҶ‘B1вҶҗB[;1]                вҚқ vector B1 is column 1 of matrix B, and scalar B11 its first item
----

With these prerequisites we can "prove" the following:

*Proposition:* Let

----
      L11вҶҗГ—B11             вҚқ B11 normalized to length 1 (= Вұ1 for real B11)
      LB1вҶҗ(+/B1Г—+B1)вӢҶ0.5   вҚқ scalar LB1 is в•‘B1в•‘ i.e. the length of B1

      H1вҶҗHouseholder V1вҶҗ1вҶ“B1 + L11Г—MвҶ‘LB1  вҚқ a Householder matrix (from V1)
      H2вҶҗHouseholder V2вҶҗ1вҶ“B1 - L11Г—MвҶ‘LB1  вҚқ another Householder matrix (from V2)
----

Then the first columns of matrices *BвҲҳH1* and of *BвҲҳH2* are 0 below the
top-left item *B11* of *B*.

*Proofs* (by APL examples *B*):

----
     вҲҮ
[0]   HвҶҗHouseholder V;I;L
[1]   вҚқ
[2]   вҚқвҚқ return the Householder matrix (aka. elementary reflector) for vector V
[3]   вҚқ
[4]   IвҶҗIвҲҳ.=IвҶҗвҚівҚҙV        вҚқ I: the (вҚҙV)Г—(вҚҙV) identity matrix,
[5]   LвҶҗ+/VГ—+V           вҚқ L: в•‘Vв•‘ВІ i.e. the square of the norm of vector V
[6]   HвҶҗI-(2Г·L)Г—VвҲҳ.Г—+V   вҚқ H: the Householder matrix for vector V
     вҲҮ

      LB1вҶҗ(+/B1Г—+B1)вӢҶ0.5   вҚқ scalar LB1 is в•‘B1в•‘ i.e. the length of B1
      L11вҶҗГ—B11             вҚқ B11 normalized to length 1 (= Вұ1 for real B11)
      H1вҶҗHouseholder 1вҶ“B1+L11Г—MвҶ‘LB1
      H2вҶҗHouseholder 1вҶ“B1-L11Г—MвҶ‘LB1

      H1 = вҚү+H1             вҚқ H1 is Hermitian
1 1 1 1
1 1 1 1
1 1 1 1
1 1 1 1

      (вҢ№H1) = вҚү+H1           вҚқ H1 is Unitary
1 1 1 1
1 1 1 1
1 1 1 1
1 1 1 1

      H1 = вҢ№H1              вҚқ H1 is Involutary
1 1 1 1
1 1 1 1
1 1 1 1
1 1 1 1

      B
 27J117  54J72   18J27
 81J117  18J117 126J144
117J81  117J108   9J54
135J27  117J18  117J90

      2вҚ•H1 вҲҳ B   вҚқ notice the zeros in first column
 ВҜ61.12JВҜ264.83 ВҜ33.28JВҜ233.03  ВҜ8.67JВҜ203.23
    .00J.00     ВҜ52.41J25.80    86.09J69.90
    .00J.00      19.00J47.42   ВҜ54.44JВҜ1.31
    .00J.00       6.71J1.84     39.43J65.25

      2вҚ•H2 вҲҳ B   вҚқ notice zeros in the first column
 61.12J264.83  33.28J233.03   8.67J203.23
   .00J.00    ВҜ19.79JВҜ30.51  73.02JВҜ12.81
   .00J.00     29.70JВҜ16.77 ВҜ95.79JВҜ74.13
   .00J.00     ВҜ8.43JВҜ59.27 ВҜ25.25J16.46
----

=== Repeated Application of Reflectors

Once we know how to set the first column of some arbitrary matrix *B*
to *0* (below the diagonal) we can now turn the entire matrix into an
upper triangular form:

. Set *BвӮҒ = B* and find a reflector *HвӮҒ* that sets the items below the first
  column of *BвӮҒ* to *0*.
. Repeat that step for *BвӮӮ = 1 1вҶ“BвӮҒ, BвӮғ = 1 1вҶ“BвӮӮ, ... BвӮҷ = 1 1вҶ“BвӮҷвӮӢвӮҒ* which,
  in the end, computes a sequence of reflectors *HвӮҒ, HвӮӮ, ... HвӮҷ*.
  In this process:
... the matrices BвӮ– become smaller and smaller,
... the reflectors HвӮ– become shorter and shorter, and
... the upper triangular result matrix result becomes more and more complete.


After all, say *n*, steps matrix *B* looks like this:

----
     Initial B         B after 1 step     B after 2 steps      B after n steps
     в•”в•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•—   в•”в•җв•җв•Өв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•—   в•”в•җв•җв•Өв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•—     в•”в•җв•җв•Өв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•—
     в•‘             в•‘   в•‘вҚәвӮҒв”Ӯ    R1     в•‘   в•‘вҚәвӮҒв”Ӯ    R1     в•‘     в•‘вҚәвӮҒв”Ӯ    R1     в•‘
     в•‘             в•‘   в•ҹв”Җв”Җв”Ө           в•‘   в•ҹв”Җв”Җв”јв”Җв”Җв”җ  R2    в•‘     в•ҹв”Җв”Җв”јв”Җв”Җв”җ  R2    в•‘
     в•‘             в•‘   в•‘  в”Ӯ           в•‘   в•‘  в”ӮвҚәвӮӮв”Ӯ        в•‘     в•‘  в”ӮвҚәвӮӮв”Ӯ   ...  в•‘
     в•‘     B=BвӮҒ    в•‘ вҶ’ в•‘  в”Ӯ           в•‘ вҶ’ в•‘  в”ңв”Җв”Җв”Ө        в•‘ ... в•‘  в”ңв”Җв”Җв”Ө        в•‘
     в•‘             в•‘   в•‘HвӮҒв”Ӯ           в•‘   в•‘HвӮҒв”Ӯ  в”Ӯ        в•‘     в•‘HвӮҒв”Ӯ  в”Ӯ ...    в•‘
     в•‘             в•‘   в•‘  в”Ӯ           в•‘   в•‘  в”ӮHвӮӮв”Ӯ        в•‘     в•‘  в”ӮHвӮӮв”Ӯ     в”Ңв”Җв”Җв•ў
     в•‘             в•‘   в•‘  в”Ӯ           в•‘   в•‘  в”Ӯ  в”Ӯ        в•‘     в•‘  в”Ӯ  в”Ӯ     в”ӮвҚәвӮҷв•‘
     в•ҡв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•қ   в•ҡв•җв•җв•§в•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•қ   в•ҡв•җв•җв•§в•җв•җв•§в•җв•җв•җв•җв•җв•җв•җв•җв•қ     в•ҡв•җв•җв•§в•җв•җв•§в•җв•җв•җв•җв•җв•§в•җв•җв•қ
----

NOTE: For lack of space we show *вҚәвӮҒ ... вҚәвӮҷ* on the diagonal above, but in
reality the diagonal is *RвӮҒвӮҒ, RвӮӮвӮӮ, ... RвӮҷвӮҷ*. The sequence *вҚәвӮҒ ... вҚәвӮҷ*  is
stored in *tau* as will be explained below. 

Now:

. *R* is upper triangular (where the items below the diagonal are *0* by
  definition and therefore need not be stored in *B*)
. *H вҶҗ HвӮҒ вҲҳ HвӮӮ вҲҳ ... вҲҳ HвӮҷ* is unitary or orthogonal since it is the
  product of *n* unitary or orthogonal matrices *HвӮ–* respectively.

The iteration above takes place in function *LA_pack::laqp2()* which starts
with matrix *B* and ends with *R* in the upper half (including the diagonal),
*Q* in the lower half, and the diagonal factors *вҚәвӮҒ ... вҚәвӮҷ* stored in
variable *tau*.

At this point the lower half and *tau* are not the matrix *Q* itself but the
reflectors that turn the identity matrix into *Q*. For this reason we usually
refer to lower half as *HR* and not as *QR* in the GNU APL Cpp code.

=== Numerical considerations

In mathematics we compute with exact numbers and would be finished at this
point. On real computers we work with approximations of exact numbers which
may cause problems with the accuracy of the result.

Let *вҚә* and *ОІ* be numbers. For the sake of explanation assume *вҚә>0* and *ОІ>0*.
Due to rounding, *вҚә* and *ОІ* only determine two ranges in which the exact
вҚә and *ОІ* lie:

----
      вҚә - eвӮҒ вүӨ exact вҚә вүӨ вҚә + eвӮҒ and
      ОІ - eвӮӮ вүӨ exact ОІ вүӨ ОІ + eвӮӮ
----

The (usually small) numbers *eвӮҒ* and *eвӮӮ* define the _absolute error_ of *вҚә*
and *ОІ* while the quotients *eвӮҒГ·вҚә* and *eвӮӮГ·ОІ* define the _relative_error_
of *вҚә* and *ОІ* respectively.

Now, adding or subtracting the inequalities above gives:

----
               вҚә - eвӮҒ вүӨ exact вҚә вүӨ вҚә + eвӮҒ
            Вұ  ОІ - eвӮӮ вүӨ exact ОІ вүӨ ОІ + eвӮӮ
      в•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җ
      (вҚәВұОІ) - (eвӮҒ+eвӮӮ) вүӨ exact вҚәВұОІ вүӨ (вҚәВұОІ) + (eвӮҒ+eвӮӮ) 
----

This means that the absolute error of the sum or difference *(вҚәВұОІ)* is the
sum of the absolute errors of *вҚә* and *ОІ*. This is no problem as long as
*(вҚәВұОІ)* does not come too close to *0*. If it does, however, then the
absolute error remains small, but the relative error is now:

----
      eвӮҒ + eвӮӮ
      в”Җв”Җв”Җв”Җв”Җв”Җв”Җ вҶ’ вҲһ  as (вҚә Вұ ОІ) вҶ’ 0
       вҚә Вұ ОІ 
----

That is, for *(вҚә-ОІ)* the relative error can become huge if *вҚә*вүҲ*ОІ*.
In LApack these issues are addressed in 3 ways:

. If the input matrices are very large or very small (in terms of their norm)
  then they (and their result) are scaled up or down so that their
  coefficients land in a range that is not subject to major rounding error.
  See function *LA_pack::gelsy()* vs. *LA_pack::scaled_gelsy()*.
. As we have seen above, for any matrix *B* there are actually two reflectors
  *H1* and *H2* each of which bring the first column off *B* below the
  diagonal to *0). LA_pack then chooses the one that produces the largest
  difference *V1* or *V2* above.
. Some functions, in particular *LA_pack::larfg()* take additional measures
  to minimize the errors caused by too small arguments.
. Column pivoting, instead of processing the columns in normal order (different
  from B[;1], B[;2], ... B[N]) to avoid small coefficients in the subsequent
  matrices.

Column pivoting works like this:

. In every iteration above:
.. Compute the norms of the columns,
.. Find the column *k* with the largest norm (called "the pivot")
.. If *kвү 1* (i.e. the first column does not have the largest norm already)
   then exchange columns *1* and *k* before proceeding.
.. In the context of solving equations, the pivoting is essentially a renaming
   of the variables *xвӮҒ, xвӮӮ, ..., xвӮҷ*. This renaming is later undone (see the
   end of *scaled_gelsy()*) before the result is returned to APL.


=== Memory Layout

At the time when FORTRAN was popular, memories were small. The LApack FORTRAN
code addressed this in two ways:

=== Blocked execution

Blocked operation means that the processing of matrices that may not fit
into the core memory of a computer were processed in chunks. Some FORTRAN
functions therefore had a "blocked" version (for large matrices) and an
"unblocked" version (for small matrices and for the chunks of large matrices).

These days memory is large and therefore blocking was removed entirely. Only
the unblocked FORTRAN functions survived in the GNU APL code.

=== In-place computation

Another heavily used trick to reduce memory consumption is in-place
computation. Instead of passing the argument of a function in one variable and
storing the result in a another variable, the same variable was used for the
largest input variable and the result. For example, function *laqp2()*
computes the QR factorization of an arbitrary matrix *B* and the result is
stored at the same memory location. However, the result *QR* is split in two
pieces along the diagonal, taking advantage of the fact that *Q* is symmetric
(so its upper half can be derived directly from its lower half, and that *R*
is upper triangular (so its lower half is implicitly *0* and therefore
not of interest):

----
      Input matrix B       Results Q and R
      в•”в•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•—     в•”в•җв•җв•җв•җв•Өв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•—
      в•‘              в•‘     в•‘RвӮҒвӮҒ в”Ӯ           в•‘
      в•‘              в•‘     в•ҹв”Җв”Җв”Җв”Җв”јв”Җв”Җв”Җв”җ       в•‘
      в•‘              в•‘     в•‘    в”ӮRвӮӮвӮӮв”Ӯ  Rбөўвұј  в•‘
      в•‘     Bбөўвұј      в•‘  вҶ’  в•‘    в””в”Җв”Җв”Җв”ҳ       в•‘
      в•‘              в•‘     в•‘         ...    в•‘
      в•‘              в•‘     в•‘  Q         в”Ңв”Җв”Җв”Җв•ў
      в•‘              в•‘     в•‘            в”ӮRвӮҷвӮҷв•‘
      в•ҡв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•қ     в•ҡв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•§в•җв•җв•җв•қ
----

Unfortunately in this scheme the matrices of *Q* and *R* now compete for the
former diagonal of input *B*. This is solved by storing in the diagonal of *Q*
in a separate vector (named *tau* in the LApack code):

----
      в•”в•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•—           в•”в•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•—  
      в•‘              в•‘           в•‘              в•‘
      в•ҷв”Җв”Җв”Җв”җ     Rбөўвұј  в•‘           в•ҹв”Җв”Җв”Җв”җ     Rбөўвұј  в•‘
          в”Ӯ          в•‘           в•‘   в”Ӯ          в•‘
          в””в”Җв”Җв”Җв”җ      в•‘           в•‘   в””в”Җв”Җв”Җв”җ      в•‘
      в•”в•җв•җв•җв••   в”Ӯ      в•‘     вҶ’     в•‘       в”Ӯ      в•‘ 
      в•‘вҚәвӮҒ в”Ӯ   в””в”Җв”Җв”Җв”җ  в•‘           в•‘ Hбөўвұј   в””в”Җв”Җв”Җв”җ  в•‘
      в•ҹв”Җв”Җв”Җв”јв”Җв”Җв”Җв”җ   в”Ӯ  в•‘           в•‘           в”Ӯ  в•‘
      в•‘   в”ӮвҚәвӮӮ в”Ӯ   в•ҳв•җв•җв•қ           в•ҡв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•§в•җв•җв•қ
      в•‘   в””в”Җв”Җв”Җв”јв”Җв”Җв”Җв”җ              
      в•‘       в”Ӯ...в”Ӯ         
      в•‘  Hбөўвұј  в””в”Җв”Җв”Җв”јв”Җв”Җв•–          в•”в•җв•җв•җв•Өв•җв•җв•җв•Өв•җв•җв•җв•Өв•җв•җв•җв•— 
      в•‘           в”ӮвҚәвӮҷв•‘     tau: в•‘вҚәвӮҒ в”ӮвҚәвӮӮ в”Ӯ...в”ӮвҚәвӮҷ в•‘
      в•ҡв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•җв•§в•җв•җв•қ          в•ҡв•җв•җв•җв•§в•җв•җв•җв•§в•җв•җв•җв•§в•җв•җв•җв•қ 
----

Another issue to understand LApack is that functions *laqp2()* and friends
do *not* return the matrices *Q* and *R* of the factorization *B = QвҲҳR*
directly. Instead of *Q* it returns a matrix *H* with the Householder
reflectors for the different columns. The matrix *Q* can then be obtained
by applying these reflectors to the *nГ—n* unit matrix *ID(n)*:

----
      Q вҶҗвҶ’ HвҲҳID(n)
----

This avoids one intermediate matrix multiplication. Instead of *QвҶҗHвҲҳI*
followed by some other *ZвҶҗQвҲҳR*, LApack leaves *H* for the moment and later
computes *ZвҶҗHвҲҳR* directly. In addition LApack avoids the computation of
the Householder matrices used in the APL examples above for demonstration
purposes. Instead of full kГ—k reflector matrices it uses the reflector
vectors, typically called *v*, and computes the elements *Hбөўвұј* of each
reflector as needed. The lifetime of each *Hбөўвұј* is usually short,
therefore it makes little sense to store it in a large matrix.

=== LApack function names

The names of LApack functions look somewhat scary at first glance. For example
the name of function *zungqr()* may not be too obvious. However these names
follow a naming scheme that roughly looks as follows:

----
   в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җ data type (iвҶҗвҶ’integer, dвҶҗвҶ’double, zвҶҗвҶ’complex)
   в”Ӯв”Ңв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җ matrix type (un вҶҗвҶ’ unitary, or вҶҗвҶ’ orthogonal, ge вҶҗвҶ’ general, etc.)
   в”Ӯв”Ӯв”Ӯв”Ңв”¬в”¬в”Җв”Җв”Җв”Җ function type (gqr вҶҗвҶ’ generate QR factorization)
   в”Ӯв”Ӯв”Ӯв”Ӯв”Ӯв”Ӯ     function variant (blocked/unblocked, etc.
   в”Ӯв”Ӯв”Ӯв”Ӯв”Ӯв”Ӯ
   zungqr()
----

With this naming scheme function *zungqr()* for complex matrices becomes
*dorqr2()* for real matrices.

In FORTRAN every complex function (like *zungqr()* has a real counterpart
*dorqr2()* for real matrices. In fact there are even more variants because
there are different precisions (like 32-bit *float* and 64-bit *double*
in Cpp) and each has its own FORTRAN function. That made a lot of sense
in the FORTRAN days where it made a considerable difference in performance.

A closer look at these functions revealed, however, that the difference
between data types are actually rather small. The GNU APL version of these
functions make the data type a template parameter so that every group of
FORTRAN functions becomes a single template function in Cpp. In our example:

----
      FORTRAN:

          dorgqr   QR-factorize real matrix
          zungqr   QR-factorize complex matrix

      becomes C++

          template<T>  ungqr()
----

where the template argument *<T>* is either *<DD>* for real or *<ZZ>* for
complex numbers. The use of Cpp templates cuts the number of functions
needed roughly in half,

=== Call Tree

With all this in mind, *AвҢ№B* aka. *Bif_F12_DOMINO::eval_AB* becomes simple.
We look at its call tree, which is roughly this:

----
   Bif_F12_DOMINO::eval_AB()
   в”Ӯ
   в””в”Җв”Җв”Җ LA_pack::divide_matrix()
        в”Ӯ
        в””в”Җв”Җв”Җ LA_pack::gelsy<T>()
             в”Ӯ
             в””в”Җв”Җв”Җ LA_pack::scaled_gelsy()
                  в”Ӯ
                  в”ңв”Җв”Җв”Җ LA_pack::laqp2<T>()
                  в”Ӯ    в”Ӯ
                  в”Ӯ    в”ңв”Җв”Җв”Җ LA_pack::larfg<T>()
                  в”Ӯ    в””в”Җв”Җв”Җ LA_pack::larf<T>()
                  в”Ӯ
                  в”ңв”Җв”Җв”Җ LA_pack::estimate_rank()
                  в”Ӯ
                  в”ңв”Җв”Җв”Җ LA_pack::trsm<T>()
                  в”Ӯ
                  в””в”Җв”Җв”Җ LA_pack::unm2r<T>()
                       в”Ӯ
                       в”ңв”Җв”Җв”Җ LA_pack::larf<T>()
                       в”ңв”Җв”Җв”Җ ...
                       в””в”Җв”Җв”Җ LA_pack::larf<T>()
----

In this call tree:

* *eval_AB()* performs the APL argument checking (matching shapes of *A*
  and *B*) and determines if *A* or *B* contain complex items. It also converts
  scalars and vectors *A* and *B* into 1Г—1 and 1Г—N matrices respectively;
* *divide_matrix()* translates the ravels of APL matrices *A* and *B* into
  (transposed) FORTRAN matrices;
* *gelsy<T>()* scales (and later unscales) FORTRAN matrices *A* and *B* with
   very small or very large items so that subsequent operations are
   safe in regard to rounding errors. In almost all real life cases
   *A* and *B* will not need any scaling.
* *scaled_gelsy()* computes *ZвҶҗAвҢ№B* for the now properly scaled *A* and *B*
* *laqp2()* computes a QR factorization *B=QвҲҳR* of *B*. In the result:
** *Q* is orthogonal (for real *A* and *B*) or Hermitian (for complex
   *A* or *B*). *Q* is easy to invert since *QвҒ»В№ вҶҗвҶ’ вҚү+Q*, and
** *R* is upper triangular (so that *RвҲҳX=C* is simple to solve).
* In the QR factorization: for every column of *B*:
** *larfg<T>()* generates one reflector (i.e. for one column of *B*)
** *larf<T>()* applies that reflector to a sub-matrix of *B*;
* *estimate_rank()* checks that the system *A=BвҲҳX* of linear equations is
   not under-determined and raises a DOMAIN ERROR if it is. In contrast,
   over-determination (more equations than variables) is accepted and
   produces a least-square solution for *A=X=BвҲҳX*
* *trsm<T>()* computes *RвҒ»В№* for the upper triangular factor *R*
  of *B=QвҲҳR* that was computed above
* *unm2r<T>()* applies *RвҒ»В№* to *A*


== вҢ№ with axis: QR factorization

The first non-trivial computation in monadic *вҢ№B* and in dyadic *AвҢ№B*
is a _QR-factorization_ of matrix *B*. A QR factorization of a matrix B is
a pair *(Q R)* of matrices with the following properties:

. *Q* is orthogonal (Hermitian if B is complex),
. *R* is upper triangular, and
. *B вүЎ Q вҲҳ R* within the limits of вҺ•CT.

The same matrix *B* may have different QR factorizations with the above
properties. And different factorization algorithms may produce different
pairs *(Q R)* for the same matrix *B*.

Often the orthogonal *Q* and/or the upper triangular *R* of a factorization
*B=QвҲҳR* is more valuable than the final result *BвҒ»В№=RвҒ»В№вҲҳQвҒ»В№* of *вҢ№B* or
*AвҢ№B*. For this reason GNU APL provides *вҢ№[X]* which returns the matrices
*Q* and *R* before applying them (i.e. to solve *AвҲҳX=B*). As a matter of
convenience for the programmer, GNU APL not only computes the pair *(Q R)*,
but a triple *(Q R Rinv)* where *Rinv вүЎ вҢ№R*.

One could, of course, compute *Rinv* from *R* in APL with *RinvвҶҗвҢ№R*.
However, *вҢ№R* in APL cannot easily take advantage of the fact that *вҢ№R* is
upper triangular, which makes it more efficient to use an inversion algorithm
that is tailored to the upper triangular case of *вҢ№R* as opposed to the
general *B* case. Also, computing *RinvвҶҗвҢ№R* after returning *(Q R)* would
factorize R a second time for no reason.

GNU APL has implemented two different algorithms for the QR-factorization
of a matrix *B*, which produce slightly different results.

. The first algorithm is based on a factorization algorithm published by
  *Garry Helzer* in *APL Quote Quad, Volume 9, Issue 3, 1979*, and
. the second algorithm is, like monadic and dyadic *вҢ№*, based on LApack
  function *laqp2()* but with column pivoting disabled.

The algorithm to be used is selected with axis argument *X* as follows:

. Integer scalar 1 selects Garry Helzer's algorithm,
. Integer scalar 2 selects the *laqp2()* algorithm, and
. (obsolete) a small real scalar like вҺ•CT also selects Garry Helzer's
  algorithm. This is for backward compatibility with older GNU APL
  versions (that always used Garry Helzer's algorithm).

=== Quadratic B

The simplest cases are those where *B* is quadratic, i.e. *вҚҙB вҶҗвҶ’ N N*. In
those cases *Q*, *R*, and *Ri* have the same shape as *B*. The same *B* can
have different QR factorizations, therefore the ravels of the results
usually differ between different algorithms. For example,

----
      MNвҶҗ4 4 в—Ҡ BвҶҗ?MNвҚҙ9                 вҚқ B quadratic (M=N)
      Q_R_RiвҶҗ(Q R Ri)вҶҗ вҢ№[1]B           вҚқ Helzer algorithm
      вҚқ 8 вҺ•CRВЁ(вҠӮB), 2вҚ•ВЁQ R Ri          вҚқ Argument B and results Q R Ri
      вҚқ or alternatively from the nested variable
      8 вҺ•CRВЁ(вҠӮB), 2вҚ•ВЁQ_R_Ri            вҚқ Argument B and results Q R Ri
 в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ 
 вҶ“4 4 9 5в”Ӯ  вҶ“ .34  .19 ВҜ.68  .62в”Ӯ  вҶ“ 11.70 9.23 11.36 13.50в”Ӯ  вҶ“ .09 ВҜ.17  .17  .59в”Ӯ 
 в”Ӯ6 1 6 7в”Ӯ  в”Ӯ .51 ВҜ.82  .20  .18в”Ӯ  в”Ӯ   .00 4.57 ВҜ2.16 ВҜ1.00в”Ӯ  в”Ӯ .00  .22 ВҜ.06 ВҜ.05в”Ӯ 
 в”Ӯ7 8 1 6в”Ӯ  в”Ӯ .60  .54  .57  .14в”Ӯ  в”Ӯ   .00  .00 ВҜ8.08 ВҜ2.29в”Ӯ  в”Ӯ .00  .00 ВҜ.12  .18в”Ӯ 
 в”Ӯ6 5 9 9в”Ӯ  в”Ӯ .51  .06 ВҜ.41 ВҜ.75в”Ӯ  в”Ӯ   .00  .00   .00 ВҜ1.60в”Ӯ  в”Ӯ .00  .00  .00 ВҜ.62в”Ӯ 
 в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ 

      8 вҺ•CRВЁ вҚҙВЁB Q R Ri                вҚқ Shapes of argument B and results
 в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ 
 в”Ӯ4 4в”Ӯ  в”Ӯ4 4в”Ӯ  в”Ӯ4 4в”Ӯ  в”Ӯ4 4в”Ӯ 
 в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ 

      8 вҺ•CR B=QвҲҳR                      вҚқ Q R is a factorization of B
в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ
вҶ“1 1 1 1в”Ӯ
в”Ӯ1 1 1 1в”Ӯ
в”Ӯ1 1 1 1в”Ӯ
в”Ӯ1 1 1 1в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ

      8 вҺ•CRВЁ (QвҲҳвҚүQ) ((вҚүQ)вҲҳQ)           вҚқ Q is orthogonal
 в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ 
 вҶ“1 0 0 0в”Ӯ  вҶ“1 0 0 0в”Ӯ 
 в”Ӯ0 1 0 0в”Ӯ  в”Ӯ0 1 0 0в”Ӯ 
 в”Ӯ0 0 1 0в”Ӯ  в”Ӯ0 0 1 0в”Ӯ 
 в”Ӯ0 0 0 1в”Ӯ  в”Ӯ0 0 0 1в”Ӯ 
 в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ 

      8 вҺ•CRВЁ (RвҲҳRi) (RiвҲҳR)             вҚқ Ri is the inverse of R
 в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ 
 вҶ“1 0 0 0в”Ӯ  вҶ“1 0 0 0в”Ӯ 
 в”Ӯ0 1 0 0в”Ӯ  в”Ӯ0 1 0 0в”Ӯ 
 в”Ӯ0 0 1 0в”Ӯ  в”Ӯ0 0 1 0в”Ӯ 
 в”Ӯ0 0 0 1в”Ӯ  в”Ӯ0 0 0 1в”Ӯ 
 в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ 

      
      MNвҶҗ4 4 в—Ҡ BвҶҗ?MNвҚҙ9                 вҚқ B quadratic (M=N)
      Q_R_RiвҶҗ(Q R Ri) вҶҗ вҢ№[2]B          вҚқ LApack algorithm
      8 вҺ•CRВЁ(вҠӮB), 2вҚ•ВЁQ_R_Ri            вҚқ Argument B and results Q R Ri
 в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ 
 вҶ“2 5 5 7в”Ӯ  вҶ“ ВҜ.22  .41  .64  .61в”Ӯ  вҶ“ ВҜ9.22 ВҜ12.91 ВҜ5.10 ВҜ11.50в”Ӯ  вҶ“ ВҜ.11 ВҜ.26  .16  .22в”Ӯ 
 в”Ӯ8 9 2 8в”Ӯ  в”Ӯ ВҜ.87 ВҜ.41 ВҜ.21  .18в”Ӯ  в”Ӯ   .00   5.33  4.17   7.24в”Ӯ  в”Ӯ  .00  .19 ВҜ.23 ВҜ.43в”Ӯ 
 в”Ӯ4 8 5 5в”Ӯ  в”Ӯ ВҜ.43  .45  .27 ВҜ.73в”Ӯ  в”Ӯ   .00    .00  3.41  ВҜ1.40в”Ӯ  в”Ӯ  .00  .00  .29  .10в”Ӯ 
 в”Ӯ1 5 1 8в”Ӯ  в”Ӯ ВҜ.11  .68 ВҜ.69  .23в”Ӯ  в”Ӯ   .00    .00   .00   3.92в”Ӯ  в”Ӯ  .00  .00  .00  .25в”Ӯ 
 в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ 

      8 вҺ•CRВЁ вҚҙВЁB Q R Ri                вҚқ Shapes of argument B and results
 в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ 
 в”Ӯ4 4в”Ӯ  в”Ӯ4 4в”Ӯ  в”Ӯ4 4в”Ӯ  в”Ӯ4 4в”Ӯ 
 в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ 

      8 вҺ•CR B=QвҲҳR                      вҚқ Q R is a factorization of B
в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ
вҶ“1 1 1 1в”Ӯ
в”Ӯ1 1 1 1в”Ӯ
в”Ӯ1 1 1 1в”Ӯ
в”Ӯ1 1 1 1в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ

      8 вҺ•CRВЁ (QвҲҳвҚүQ) ((вҚүQ)вҲҳQ)           вҚқ Q is orthogonal
 в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ 
 вҶ“1 0 0 0в”Ӯ  вҶ“1 0 0 0в”Ӯ 
 в”Ӯ0 1 0 0в”Ӯ  в”Ӯ0 1 0 0в”Ӯ 
 в”Ӯ0 0 1 0в”Ӯ  в”Ӯ0 0 1 0в”Ӯ 
 в”Ӯ0 0 0 1в”Ӯ  в”Ӯ0 0 0 1в”Ӯ 
 в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ 

      8 вҺ•CRВЁ (RвҲҳRi) (RiвҲҳR)             вҚқ Ri is the inverse of R
 в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ 
 вҶ“1 0 0 0в”Ӯ  вҶ“1 0 0 0в”Ӯ 
 в”Ӯ0 1 0 0в”Ӯ  в”Ӯ0 1 0 0в”Ӯ 
 в”Ӯ0 0 1 0в”Ӯ  в”Ӯ0 0 1 0в”Ӯ 
 в”Ӯ0 0 0 1в”Ӯ  в”Ӯ0 0 0 1в”Ӯ 
 в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ 
----

Notice the differences between the Helzer and the LAack algorithm
in the *8 вҺ•CRВЁ2вҚ•ВЁQ R Ri* lines above.

=== Under-determined B

If *B* is under-determined, i.e. *вҚҙB вҶҗвҶ’ M N* with *M < N*,
then matters become a little more complicated. Due to conformity
constraints (LENGTH ERROR), only *(MMвҶҗвҚҙRi)вҶ‘R* can be multiplied
from the left or from the right, but not *R* itself:

----
      вҺ•LC
      MMвҶҗ2/вҶ‘(M N)вҶҗMNвҶҗ2 4 в—Ҡ BвҶҗ?MNвҚҙ9     вҚқ Helzer, B under-determined (M<N)
      Q_R_RiвҶҗ(Q R Ri) вҶҗ вҢ№[1]B          вҚқ Helzer algorithm

      8 вҺ•CRВЁ(вҠӮB), 2вҚ•ВЁQ_R_Ri            вҚқ Argument B and results Q R Ri
 в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ 
 вҶ“2 5 3 5в”Ӯ  вҶ“ .89  .45в”Ӯ  вҶ“ 2.24 5.81  4.02 4.92в”Ӯ  вҶ“ .45  5.81в”Ӯ 
 в”Ӯ1 3 3 1в”Ӯ  в”Ӯ .45 ВҜ.89в”Ӯ  в”Ӯ  .00 ВҜ.45 ВҜ1.34 1.34в”Ӯ  в”Ӯ .00 ВҜ2.24в”Ӯ 
 в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ 

      8 вҺ•CRВЁ вҚҙВЁB Q R Ri                вҚқ Shapes of argument B and results
 в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ 
 в”Ӯ2 4в”Ӯ  в”Ӯ2 2в”Ӯ  в”Ӯ2 4в”Ӯ  в”Ӯ2 2в”Ӯ 
 в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ 

      8 вҺ•CR B=QвҲҳR                      вҚқ Q R is a factorization of B
в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ
вҶ“1 1 1 1в”Ӯ
в”Ӯ1 1 1 1в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ

      8 вҺ•CRВЁ (QвҲҳвҚүQ) ((вҚүQ)вҲҳQ)           вҚқ Q is orthogonal
 в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ 
 вҶ“1 0в”Ӯ  вҶ“1 0в”Ӯ 
 в”Ӯ0 1в”Ӯ  в”Ӯ0 1в”Ӯ 
 в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ 

      8 вҺ•CRВЁ ((MMвҶ‘R)вҲҳRi) (RiвҲҳ(MMвҶ‘R))   вҚқ Ri is the inverse of R
 в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ 
 вҶ“1 0в”Ӯ  вҶ“1 0в”Ӯ 
 в”Ӯ0 1в”Ӯ  в”Ӯ0 1в”Ӯ 
 в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ 
----

=== Over-determined B

The most complicated cases are those where *B* is over-determined,
i.e. *вҚҙB вҶҗвҶ’ M N* with *M > N*. The conformity constraints are similar
to those of the under-determined cases.

----
      NNвҶҗ2/1вҶ“(M N)вҶҗMNвҶҗ4 2 в—Ҡ BвҶҗ?MNвҚҙ9    вҚқ B over-determined (M>N)
      Q_R_RiвҶҗ(Q R Ri) вҶҗ вҢ№[1]B          вҚқ Helzer algorithm

      8 вҺ•CRВЁ(вҠӮB), 2вҚ•ВЁQ R Ri            вҚқ Argument B and results Q R Ri
 в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ 
 вҶ“9 3в”Ӯ  вҶ“ .65  .31 ВҜ.54  .44в”Ӯ  вҶ“ 13.82  6.51в”Ӯ  вҶ“ .07  .12в”Ӯ 
 в”Ӯ7 3в”Ӯ  в”Ӯ .51  .08 ВҜ.04 ВҜ.86в”Ӯ  в”Ӯ   .00 ВҜ3.95в”Ӯ  в”Ӯ .00 ВҜ.25в”Ӯ 
 в”Ӯ6 2в”Ӯ  в”Ӯ .43  .21  .84  .24в”Ӯ  в”Ӯ   .00   .00в”Ӯ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ 
 в”Ӯ5 6в”Ӯ  в”Ӯ .36 ВҜ.92  .01  .13в”Ӯ  в”Ӯ   .00   .00в”Ӯ              
 в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ              

      8 вҺ•CRВЁ вҚҙВЁB Q R Ri                вҚқ Shapes of argument B and results
 в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ 
 в”Ӯ4 2в”Ӯ  в”Ӯ4 4в”Ӯ  в”Ӯ4 2в”Ӯ  в”Ӯ2 2в”Ӯ 
 в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ 

      8 вҺ•CR B=QвҲҳR                      вҚқ Q R is a factorization of B
в”ҢвҶ’в”Җв”Җв”җ
вҶ“1 1в”Ӯ
в”Ӯ1 1в”Ӯ
в”Ӯ1 1в”Ӯ
в”Ӯ1 1в”Ӯ
в””в”Җв”Җв”Җв”ҳ

      8 вҺ•CRВЁ (QвҲҳвҚүQ) ((вҚүQ)вҲҳQ)           вҚқ Q is orthogonal
 в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ 
 вҶ“1 0 0 0в”Ӯ  вҶ“1 0 0 0в”Ӯ 
 в”Ӯ0 1 0 0в”Ӯ  в”Ӯ0 1 0 0в”Ӯ 
 в”Ӯ0 0 1 0в”Ӯ  в”Ӯ0 0 1 0в”Ӯ 
 в”Ӯ0 0 0 1в”Ӯ  в”Ӯ0 0 0 1в”Ӯ 
 в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ 

      8 вҺ•CRВЁ ((NNвҶ‘R)вҲҳRi) (RiвҲҳ(NNвҶ‘R))   вҚқ Ri is the inverse of R
 в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ 
 вҶ“1 0в”Ӯ  вҶ“1 0в”Ӯ 
 в”Ӯ0 1в”Ӯ  в”Ӯ0 1в”Ӯ 
 в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ 


      NNвҶҗ2/1вҶ“(M N)вҶҗMNвҶҗ4 2 в—Ҡ BвҶҗ?MNвҚҙ9    вҚқ B over-determined (M>N)
      Q_R_RiвҶҗ(Q R Ri) вҶҗ вҢ№[2]B          вҚқ LApack algorithm

      8 вҺ•CRВЁ(вҠӮB), 2вҚ•ВЁQ_R_Ri            вҚқ Argument B and results Q R Ri
 в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ 
 вҶ“5 3в”Ӯ  вҶ“ ВҜ.48  .09в”Ӯ  вҶ“ ВҜ10.34 ВҜ5.51в”Ӯ  вҶ“ ВҜ.10 ВҜ.14в”Ӯ 
 в”Ӯ8 3в”Ӯ  в”Ӯ ВҜ.77 ВҜ.34в”Ӯ  в”Ӯ    .00  3.69в”Ӯ  в”Ӯ  .00  .27в”Ӯ 
 в”Ӯ3 1в”Ӯ  в”Ӯ ВҜ.29 ВҜ.16в”Ӯ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ 
 в”Ӯ3 5в”Ӯ  в”Ӯ ВҜ.29  .92в”Ӯ                                
 в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ                                

      8 вҺ•CRВЁ вҚҙВЁB Q R Ri                вҚқ Shapes of argument B and results
 в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ 
 в”Ӯ4 2в”Ӯ  в”Ӯ4 2в”Ӯ  в”Ӯ2 2в”Ӯ  в”Ӯ2 2в”Ӯ 
 в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ 
      8 вҺ•CR B=QвҲҳR                      вҚқ Q R is a factorization of B
в”ҢвҶ’в”Җв”Җв”җ
вҶ“1 1в”Ӯ
в”Ӯ1 1в”Ӯ
в”Ӯ1 1в”Ӯ
в”Ӯ1 1в”Ӯ
в””в”Җв”Җв”Җв”ҳ

      8 вҺ•CRВЁ (2вҚ•QвҲҳвҚүQ) ((вҚүQ)вҲҳQ)         вҚқ Q is orthogonal ?
 в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ 
 вҶ“ .24  .34  .13  .22в”Ӯ  вҶ“1 0в”Ӯ 
 в”Ӯ .34  .71  .28 ВҜ.09в”Ӯ  в”Ӯ0 1в”Ӯ 
 в”Ӯ .13  .28  .11 ВҜ.07в”Ӯ  в””в”Җв”Җв”Җв”ҳ 
 в”Ӯ .22 ВҜ.09 ВҜ.07  .93в”Ӯ        
 в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ        

      8 вҺ•CRВЁ ((NNвҶ‘R)вҲҳRi) (RiвҲҳ(NNвҶ‘R))   вҚқ Ri is the inverse of NNвҶ‘R
 в”ҢвҶ’в”Җв”Җв”җ  в”ҢвҶ’в”Җв”Җв”җ 
 вҶ“1 0в”Ӯ  вҶ“1 0в”Ӯ 
 в”Ӯ0 1в”Ӯ  в”Ӯ0 1в”Ӯ 
 в””в”Җв”Җв”Җв”ҳ  в””в”Җв”Җв”Җв”ҳ 
----

Note that above *Q* is orthogonal in the Helzer case but not in the LApack
case. This is most likely caused by the fact that in an over-determined *B*
the LApack functions compute a least-square solution instead of an exact one.
Note also the different *вҚҙQ* in both cases.

== Impact of вҺ•CT

All вҢ№-functions use *вҺ•CT* although in different ways.

=== вҺ•CT in the Helzer Algorithm

To quote Garry Helzer:

_For this reason, whenever it is necessary to check an array for zeros below,
the check is always made relative to another array and with a specified
tolerance._

In GNU APL this comparison of small items with exact 0.0 can be
controlled with вҺ•CT. The original Helzer algorithm used two APL functions
*CPR* (for compare) and *TOL* (tolerance) to check for zeros:

----
      O ^.= (I+V) CPR L TOL DCT
----

which have been inlined in GNU APL, see *Bif_F12_DOMINO::significant()*.

NOTE: the Helzer Algorithm in GNU APL, i.e. *вҢ№[1]B*, does not use any
of the LApack functions.

=== вҺ•CT in the LApack functions

The LApack based functions *AвҢ№B* and *вҢ№B* in GNU APL use the Cpp function
*LApack::estimate_rank()* to compute the effective rank of the right
argument *B*. Matrices with fewer rows than columns are _under-determined_
and always yield a RANK ERROR. However a matrix can be under-determined even
if the number of rows is suffiently large. This is the case if the rows are
not linearly independent. Put differently, a large number of rows alone
does not guarantee a sufficient matrix rank because a linear dependent row
is as good as no row.

Function *estimate_rank()* has no corresponding FORTRAN function in LApack,
but used to be a somewhat lengthy section of *LApack::gelsy()*. That section
was modularized into *estimate_rank()* in order to improve the readability
of the GNU APL Cpp code.

Function *estimate_rank()* iteratively computes two values *smin* (an upper
bound for the smallest singular value of *B*) and *smax* (a lower bound for
the largest singular value of *B*), and considers matrix *B* as rank-deficient
if:

----
      smax * вҺ•CT > smin
----

If that happens then GNU APL raises a *DOMAIN ERROR*. It means that the
matrix *B* (i.e. of *AвҢ№B*, *вҢ№B*) is either truly rank-deficient,
or at least close to a rank-deficient matrix. Decreasing *вҺ•CT* may
or may not solve that problem.

In such cases the precision of the result is rather questionable and
the DOMAIN ERROR indicates that problem rather than continuing with
the computation and producing an unreliable result.

