#!/bin/bash

# vim: et:ts=4:sw=4

# Usage:  new_project.bash [-f|--force] [config-file]
#
# This file creates an initial directory structure in the current directoy
# that is intended to be used as a starting point for a new Django application.
#
# The --f or --force option causes any existing project with the given project
# name to be removed without notice. Otherwise, if the project already exists,
# then the user is consulted before removing an existing project.
#
# This script 'new_project.bash' is accompanied with a configuraion file named
# 'preferences'. The preferences file contains a number of settings that
# control the behaviour of the new_project.bash script. All changes desired by
# the user should be made in the preferences file and not, except for fixing
# bugs in new_project.bash. The most important drtting in preferences is the
# name of the top-level virtual environment (bash variables VENV and VENX).
#
# One can have multiple config files in the same directory with different
# virtual environment names and suffixes; every such name or suffix will
# then create a different virtual environment (containing a Django project)
# in the current directory.
#
# This file is also accompanied with a file named 'COPYING'. This script
# 'new_project.bash is Copyright (C) 2025 by Dr. Jürgen Sauermann and
# released under the GNU GENERAL PUBLIC LICENSE Version 3 (or GPLv3 for short).
# The COPYING file is a copy of the GPLv3 license, which applies to the files
# 'new_project.bash' and 'preferences' in this directory, but NOT to the
# files created by running 'new_project.bash'. Those files (i.e. those
# generated by executing the 'new_project.bash' script and then located below
# the current directory) files are supposedly Copyright (C) by the authors of
# the Dango Tutorial, published at https://docs.djangoproject.com by the
# Django Software Foundation.
#

# process command line arguments (-f, --force, and preferences
#
remove_existing_project=ask
if [ "$1" = "-f" -o "$1" = "--force" ]; then
   remove_existing_project=yes
    shift 1
fi
echo "remove existing project: $remove_existing_project"

shopt -s expand_aliases
alias STARTCAT='cat << ENDCAT > "${listing_dest}"'
alias python=python3

# $# is the number of arguments (excluding $0)
if   [ $# -eq 0 ]; then     preferences="./preferences"
elif [ $# -eq 1 ]; then     preferences=$1
else
    echo "$0: Too many ($#) arguments."
    echo "Try $0 [-f|--force] [config-file]."
    exit 1
fi

if [ ! -f "$preferences" ]; then
    echo "*** Error opening file $preferences."
    exit 2
fi

source "$preferences"

if [ -e "$abs_VENV" ]; then     # VENV containing the project exists already
{
    if [ "$remove_existing_project" = "ask" ]; then
        echo "CAUTION: directory $VENV already exist!"
        while true; do
            echo -n "Remove it? Say Yes or No (case matters): "
            read yes_no
            if [ "$yes_no"  = "No" ];       then echo "OK, done." ; exit 3
            elif [ "$yes_no"  = "Yes" ];    then break
            else    echo "Bad answer. say Yes or No (case matters)."
            fi
        done
        unset yes_no
    fi
    rm -Rf "$abs_VENV"
}
fi

# Tests that shall be performed in this script. These tests may be useful
# to locate faults in this script. Normally only a small subset of all test
# is performed (none if all bugs have been fixed).
#
# The tests are grouped into test sets to simplify their selection.
#
test_set=3 ; case $test_set in

    0)  # no tests
        TEST_01=no  ; TEST_02=no  ; TEST_03=no  ; TEST_04=no  ; TEST_05=no
        TEST_06=no  ; TEST_07=no  ; TEST_08=no  ; TEST_09=no  ; TEST_10=no
        TEST_11=no  ; TEST_12=no  ; TEST_13=no  ; TEST_14=no  ;;

    1)  # all tests
        TEST_01=yes ; TEST_02=yes ; TEST_03=yes ; TEST_04=yes ; TEST_05=yes
        TEST_06=yes ; TEST_07=yes ; TEST_08=yes ; TEST_09=yes ; TEST_10=yes
        TEST_11=yes ; TEST_12=yes ; TEST_13=yes ; TEST_14=yes ;;

    2)  # some tests
        TEST_01=no  ; TEST_02=no  ; TEST_03=yes ; TEST_04=no  ; TEST_05=no
        TEST_06=no  ; TEST_07=no  ; TEST_08=no  ; TEST_09=no  ; TEST_10=no
        TEST_11=no  ; TEST_12=no  ; TEST_13=no  ; TEST_14=yes ;;

    *)  # some more tests
        TEST_01=no  ; TEST_02=no  ; TEST_03=yes ; TEST_04=no  ; TEST_05=no
        TEST_06=no  ; TEST_07=no  ; TEST_08=no  ; TEST_09=no  ; TEST_10=no
        TEST_11=no  ; TEST_12=no  ; TEST_13=yes ; TEST_14=yes ;;
esac

MANAGE="$abs_VENV/manage.py"

# start a web server (of type $1) for the Django project
#
start_web_server()
{
    local Web_server_type="$1" ;
    case "$Web_server_type" in
        "manage_py_runserver")
            echo "starting web server (method: $Web_server)"
            $MANAGE runserver &
            sleep 2
        ;;

        "mod_wsgi_express")
            echo "starting web server (method: $Web_server)"
            mod_wsgi-express start-server "$SITE/wsgi.py" &
            sleep 2
        ;;

        "extern")
            # extern web server is supposed to be running already.
            echo "NOT starting web server (method: $Web_server)"
        ;;

        *)  echo
            echo "*** Configuration error: The bash variable 'Web_server'"
            echo "    in file $preferences is $Web_server_type, but should"
            echo "    be one of 'manage_py_runserver', 'mod_wsgi_express',"
            echo "    or 'extern'."
            exit 4
        ;;
    esac
}

# stop all web servers (if any) of type $1
#
stop_web_server()
{
    local Web_server_type="$1"
    local AWK='{printf("%c%s",32,$2);}'
    local PIDS=""
    case "$Web_server_type" in

        "manage_py_runserver")
            echo "stopping stale web server (if any, method: $Web_server)"
            PIDS=$(ps -ef | grep -F "manage.py" | grep -F "runserver"   \
                          | grep -F $USER       | awk $AWK)
        ;;

        "mod_wsgi_express")
            echo "stopping stale web server (if any, method: $Web_server)"
            ps -ef  | grep -F "mod_wsgi-express"   \
                    | grep -F $USER                \
                    | awk '{ printf(" %s", $2); }' \
                    > /tmp/web_server_pids
            PIDS=$(ps -ef | grep -F "mod_wsgi-express" | grep -v "grep"   \
                          | grep -F $USER              | awk $AWK)
        ;;

        *)
            # web server is "extern". Do nothing (leave it running)
            echo "NOT stopping stale web server (method: $Web_server)"
        ;;
    esac
    if [ -n "$PIDS" ]; then
        echo "Killing old web server PIDs: $PIDS"
        kill $PIDS 2> /dev/null
        sleep 1
    fi
}

# add a question. The question is the mandatory string "$1", followed
# by the (optional) choices "$2" ... $N that can be voted for,
#
add_question()
{
    # construct a (multi-line) command string 'cmd' that will be
    # piped into $MANAGE shell (aka. $abs_VENV/manage.py).
    #
    local cmd=$'from django.utils import timezone\n'
    local question="$1"     # extract the question, and
    shift                   # drop the question. $* are now the choices
    cmd+="q = Question(question_text='Question ${question}?', "
    cmd+=$'pub_date=timezone.now())\n'
    cmd+=$'q.save()\n'  # q.save() creates an ID for q

    while [ $# -gt 0 ]; do
        local choice="$1" ; shift
        cmd+="q.choice_set.create(choice_text='$choice'"$', votes=0)\n'
    done
    cmd+=$'q.save()\n'  # save again with choices (if any) added.

    $MANAGE shell <<< "$cmd"
}

# show one or more pages
#
show_pages()
{
    # kill old web server (if any)
    #
    stop_web_server $Web_server
    pushd $abs_VENV > /dev/null
        start_web_server $Web_server
        sleep 3
        local pages="$1"
        echo "    running $BROWSER for $pages..."
        for page in "$pages"; do
            [ "$page" = "/" ] && page=""    # replace // with /
            "$BROWSER" 127.0.0.1:8000/"$page"
        done
    popd > /dev/null
}

# print $1 in a 1-line box
#
print_boxed()
{
  local str=$1              # the string to be printed
  local NW="╓─" N="─" NE="─╖" W="║ " E=" ║" SW="╙─" S="─" SE="─╜"   # border

  N=${str//?/$N}            # horizontal line with length as ${#str}
  S=${str//?/$S}            # horizontal line with length as ${#str}
  echo "    $NW$N$NE"       # northwest, north, northeast
  echo "    $W${str}$E"     # west, str, east
  echo "    $SW$S$SE"       # southwest, south, southeast
}

# preparation for make_listing
#
start_listing()
{
  listing_number="$1"       # listing number(s) in the tutorial
  listing_page="$2"         # page number(s) in the tutorial
  listing_dest="$3"         # absolute path to some file in the project
}

# create a snapshot of file $listing_dest (after it was modified or created).
# the snapshot is stored in file $out.
#
make_listing()
{
  [ "$DO_LISTING" != "yes" ] && return

  local out="${ROOT}/Listing-$listing_number"   # filename for the listing
  if [ ${listing_dest:0:4} != "/tmp" ]; then
     local VENV_len=${#abs_VENV}
     local suffix="__${listing_dest: $VENV_len + 1}"
     out+=$(tr / : <<< $suffix)
  fi
  string="Listing: $listing_number"
  [ -n "$listing_page" ] && string+=" (on Page $listing_page)"
  string+=" of file: ${listing_dest:${#abs_VENV}+1}"
  print_boxed "$string" > $out
  cat $listing_dest    >> $out
}

# return the lasl quistion id in the SQL database of the project as $?
#
lasl_SQL_ID()
{
  local database="${abs_VENV}/db.sqlite3"
  local table="${APPL}_question"        # e.g. "polls_appl_question"
  local sql_cmd="SELECT id FROM ${table};"
  local last_id=$(sqlite3 -cmd "$sql_cmd" "$database" <<< ".exit" | tail -n 1)
  return $last_id
}

######## End of bash function declarations ########

# kill all old web servers (except, of course, 'extern')
#
stop_web_server "manage_py_runserver"
stop_web_server "mod_wsgi_express"

# 2.3 Writing your first Django app, part 1
# 2.3.1 Creating a project...

# remove any old VENV and create a new one...
#
rm -Rf $abs_VENV

# create an empty directory structure for a new VENV
#
mkdir $abs_VENV

# maybe install django. For unprivileged users it typically lands below the
# user's ~/.local/lib/python3.10/site-packages/ directory.
#
if [ ! -x django-admin ]
then
    python -m pip install Django
fi

echo "
Python version: $(python --version)
Python path:    $(which python)
Python3 path:   $(which python3)
Django version: $(django-admin --version)
Django path:    $(python -c 'import django; print(django.__path__)')
"

django-admin startproject $SITE $VENV
# echo "────────────────────"
# tree $abs_VENV
# echo "────────────────────"

# add a username and password for the SQLite database
#
#sed_ADDR="/django.db.backends.sqlite3/"
#sed_CMD="a \        'USER' : 'eedjsa', 'PASSWORD' : 'priv4te',"
#sed -i "$sed_ADDR $sed_CMD" $abs_SITE/settings.py


if [ $TEST_01 = yes ] ; then
    # this test works only here, since the URI mapping(s)
    # will be changed later on
    #
    show_pages "/"
fi
###############################################################################
cd $abs_VENV
$MANAGE startapp $APPL
echo "────────────────────"
tree $abs_VENV
echo "────────────────────"

# Listing 8, part 1, p. 18
#
start_listing 08 18 "$abs_APPL/views.py" ; STARTCAT

from django.http import HttpResponse

def index(request):
    return HttpResponse("""
        <H1>Hello</H1>
        Hello, world. You're at the ${APPL} index.
                        """)
ENDCAT
make_listing # ══════════════════════════════════════════════════

# Listing 9, part 1, p. 20
#
start_listing 09 30 "$abs_APPL/urls.py" ; STARTCAT
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
              ]
ENDCAT
make_listing # ══════════════════════════════════════════════════

# Listing 10, part 1, p. 20
#
start_listing 10 20 "$abs_SITE/urls.py" ; STARTCAT

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('${APPL}/', include('${APPL}.urls')),
    path('admin/', admin.site.urls),
              ]

ENDCAT
make_listing # ══════════════════════════════════════════════════

if [ $TEST_02 = yes ] ; then
    show_pages "${APPL}"
fi

echo "
        ╔══════════════╗
        ║ Part 1 done. ║
        ╚══════════════╝
"
$MANAGE migrate

# Listing 11, part 2, p. 23
#
start_listing 12 23 "$abs_SITE/settings.py"
make_listing # ══════════════════════════════════════════════════

# create DB model. We combine two sections in the tutorial:
# Listing 13, Part 2, p. 28,
# Listing 14, Part 2, p. 29,
start_listing 13-14 28-28 "$abs_APPL/models.py" ; STARTCAT

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

ENDCAT
make_listing # ══════════════════════════════════════════════════

# activate DB model. That is, insert APPL_CONFIG in variable INSTALLED_APPS
# in file settings.py of the site.
#
start_listing 12 24 "$abs_SITE/settings.py"
sed_ADDR="/INSTALLED_APPS/"
sed_CMD="a \    '${APPL}.apps.$APPL_CONFIG',"
sed -i "$sed_ADDR $sed_CMD" $abs_SITE/settings.py

if [ "$Web_server" = "mod_wsgi_express" ];
then
    sed_CMD="a \    'mod_wsgi.server',"
    sed -i "$sed_ADDR $sed_CMD" $abs_SITE/settings.py
fi

make_listing # ══════════════════════════════════════════════════

$MANAGE makemigrations ${APPL}

$MANAGE sqlmigrate $APPL 0001

$MANAGE migrate

if [ $TEST_03 = "yes" ] ; then
    $MANAGE shell << ENDCAT
from django.utils import timezone

print("all():\t%s" % Question.objects.all())
q = Question(question_text='What is new?', pub_date=timezone.now())
q.save()
print("id:\t%s"     % q.id)
print("text:\t%s"   % q.question_text)
print("pub:\t%s"    % q.pub_date)
print("all():\t%s"  % Question.objects.all())

print("filter:\t%s" % Question.objects.filter(id=1))
# print("error:\t%s" % Question.objects.get(id=2))

ENDCAT
fi

# create and possibly test the super user
#
export DJANGO_SUPERUSER_PASSWORD=private_42
$MANAGE createsuperuser --noinput --username eedjsa --email mail@juergen-sauermann.de

if [ $TEST_04 = yes ] ; then
    show_pages "admin"
fi

# Listing 15, part 2, p.33
#
start_listing 15 33 "$abs_APPL/admin.py" ; STARTCAT

from django.contrib import admin

from .models import Question

admin.site.register(Question)

ENDCAT
make_listing # ══════════════════════════════════════════════════

if [ $TEST_05 = yes ] ; then
    show_pages "admin"
fi

# 2.5.1 Overview
# 2.5.2 Writing more views

# Listing 16, Part 3, p. 36...
#
start_listing 16 36 "$abs_APPL/views.py" ; STARTCAT

# Listing 16, Part 3, p. 36...
#
def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

ENDCAT
make_listing # ══════════════════════════════════════════════════

echo "
        ╔══════════════╗
        ║ Part 2 done. ║
        ╚══════════════╝
"

# 2.5 Writing your first Django app, part 3

# Listing 17, Part 3, p. 37...
#
start_listing 17 37 "$abs_APPL/urls.py" ; STARTCAT

from django.urls import path
from . import views

urlpatterns = [
    path("",                           views.index,   name="index"  ),
    path("<int:question_id>/",         views.detail,  name="detail" ),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/",    views.vote,    name="vote"   ),
              ]
ENDCAT
make_listing # ══════════════════════════════════════════════════

if [ $TEST_06 = yes ] ; then
    show_pages "$APPL/34 $APPL/34/results $APPL/34/vote"
fi

if [ $TEST_07 = yes ] ; then
    add_question "16"
    add_question "17"
    show_pages "${APPL}"
fi

# Listing 18, part 3 p. 38
#
start_listing 18 38 "$abs_APPL/views.py" ; STARTCAT

from django.http import HttpResponse
from .models import Question

def index(request):
    latest_questions_list = Question.objects.order_by("-pub_date")[:5]
    sepa = ", %c" % 10
    output = sepa.join([q.question_text for q in latest_questions_list])
    return HttpResponse(output)

# Leave the rest of the views (detail, results, vote) unchanged

# rest of Listing 16, part 3, p. 36...
#
def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

ENDCAT
make_listing # ══════════════════════════════════════════════════

mkdir -p $abs_TMPL
start_listing 19 38 "$abs_TMPL/index.html" ; STARTCAT

<HTML>
  <BODY>
    {% if latest_question_list %}
    <ul>
      {% for question in latest_question_list %}
      <li>
        <a href="/$APPL/{{ question.id }}/">{{ question.question_text }}</a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>No polls are available.</p>
    {% endif %}
  </BODY>
</HTML>

ENDCAT
make_listing # ══════════════════════════════════════════════════


start_listing 21ff 40 "$abs_APPL/views.py" ; STARTCAT

from django.http import HttpResponse
from django.template import loader
from .models import Question

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = { "latest_question_list" : latest_question_list}
    template = loader.get_template("${APPL}/index.html")
    return HttpResponse(template.render(context, request))

# rest of Listing 16, part 3, p. 36...
#
def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

ENDCAT
make_listing # ══════════════════════════════════════════════════

if [ $TEST_08 = yes ] ; then
    add_question "8.1"
    add_question "8.2"
    show_pages "${APPL}"
fi

# Listing 23, p. 41
#
start_listing 23 41 "$abs_TMPL/detail.html" ; STARTCAT

{{ question }}

ENDCAT
make_listing # ══════════════════════════════════════════════════

# Listing 24, p. 40/41
#
start_listing 24 40/41 "$abs_TMPL/view.py" ; STARTCAT

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.template import loader
from .models import Question

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = { "latest_question_list" : latest_question_list}
    template = loader.get_template("${APPL}/index.html")
    return HttpResponse(template.render(context, request))

# rest of Listing 16, part 3, p. 36...
#
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "$APPL/detail.html", {"question": question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

ENDCAT
make_listing # ══════════════════════════════════════════════════

if [ $TEST_09 = yes ] ; then
    add_question "9.1"
    add_question "9.2"
    show_pages "${APPL}/1 ${APPL}/42"
fi

# Listings 25 ff., Part 3, p. 42... (2.5.6 Removing hardcoded URLs in templates)
# replaces $APPL path with {% url ... }
#
start_listing 25ff 42 "$abs_TMPL/index.html" ; STARTCAT

<HTML>
  <BODY>
    {% if latest_question_list %}
    <ul>
      {% for question in latest_question_list %}
      <li>
        <a href="{% url 'detail' question.id %}">{{ question.question_text }}
        </a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>No polls are available.</p>
    {% endif %}
  </BODY>
</HTML>

ENDCAT
make_listing # ══════════════════════════════════════════════════

if [ $TEST_10 = yes ] ; then
    add_question "10.1"
    add_question "10.2"
    show_pages "${APPL}"
fi

# Listings 26, Part 3, p. 43/44...
# Add app_name = $APPL to the URLs
#
start_listing 26 43/44 "$abs_APPL/urls.py" ; STARTCAT

from django.urls import path
from . import views

app_name = "$APPL"
urlpatterns = [
    path("",                           views.index,   name="index"  ),
    path("<int:question_id>/",         views.detail,  name="detail" ),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/",    views.vote,    name="vote"   ),
              ]

ENDCAT
make_listing # ══════════════════════════════════════════════════

# Listings 27/28, Part 3, p. 44...
# change the <li> item to use $APPL:detail instead of detail
#
start_listing 27-28 44 "$abs_TMPL/index.html" ; STARTCAT

<HTML>
  <BODY>
    {% if latest_question_list %}
    <ul>
      {% for question in latest_question_list %}
      <li>
        <a href="{% url '$APPL:detail' question.id %}">
                        {{ question.question_text }}
        </a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>No polls are available.</p>
    {% endif %}
  </BODY>
</HTML>

ENDCAT
make_listing # ══════════════════════════════════════════════════

if [ $TEST_11 = yes ] ; then
    add_question "11.1"
    add_question "11.2"
    show_pages "${APPL}"
fi

echo "
        ╔══════════════╗
        ║ Part 3 done. ║
        ╚══════════════╝
"

# 2.6 Writing your first Django app, part 4
# 2.6.1 Write a minimal form

# Listings 29, Part 4, p. 44...
# add a <form> element
#
start_listing 29 44 "$abs_TMPL/detail.html" ; STARTCAT

<form action="{% url '$APPL:vote' question.id %}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
      <input type="radio" name="choice" id="choice{{ forloop.counter }}"
             value="{{ choice.id }}">
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}
      </label><br>
    {% endfor %}
  </fieldset>
  <input type="submit" value="Vote">
</form>

ENDCAT
make_listing # ══════════════════════════════════════════════════

# Listings 30, Part 4, p. 45...
# replace dummy vote() with real one.
#
start_listing 30 45 "$abs_APPL/urls.py" ; STARTCAT

from django.urls import path
from . import views

from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Choice, Question

app_name = "$APPL"
urlpatterns = [
    path("",                           views.index,   name="index"  ),
    path("<int:question_id>/",         views.detail,  name="detail" ),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/",    views.vote,    name="vote"   ),
              ]

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "$APPL/detail.html",
            { "question": question,
              "error_message": "You didn't select a choice.",
            },
                     )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("$APPL:results",
                                            args=(question.id,)))

ENDCAT
make_listing # ══════════════════════════════════════════════════

# Listings 31, Part 4, p. 45/46...
#
start_listing 31 45/46 "$abs_APPL/views.py" ; STARTCAT

from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.template import loader
from .models import Choice, Question

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = { "latest_question_list" : latest_question_list}
    template = loader.get_template("${APPL}/index.html")
    return HttpResponse(template.render(context, request))

# rest of Listing 16, part 3, p. 36...
#
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "$APPL/detail.html", {"question": question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    """vote for a choice in the question with ID question_id,
       and return the result as a HTTP response. Also, complain
       if no choice was selected.
    """
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        render_context = { "question": question,
                           "error_message": "You didn't select a choice.",
                         }
        return render(request, "$APPL/detail.html", render_context)
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("$APPL:results",
                                            args=(question.id,)))

ENDCAT
make_listing # ══════════════════════════════════════════════════

if [ $TEST_12 = yes ] ; then
    # the questions below are those in the unnamed listing in Part 2, p. 29..31
    #
    add_question "12.1" "Not much" "The sky" "Just hacking again"
    add_question "12.2" "Choice 1" "Choice 2" "Choice 3"
    show_pages "${APPL}"
fi

# Listings 32, p. 47...
#
start_listing 32 47 "$abs_APPL/views.py" ; STARTCAT

from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .models import Choice, Question

# rest of Listing 31, p. 45/45...
#
def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = { "latest_question_list" : latest_question_list}
    template = loader.get_template("${APPL}/index.html")
    return HttpResponse(template.render(context, request))

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "$APPL/detail.html", {"question": question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "$APPL/results.html", {"question": question})

def vote(request, question_id):
    """vote for a choice in the question with ID question_id,
       and return the result as a HTTP response. Also, complain
       if no choice was selected.
    """
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        render_context = { "question": question,
                           "error_message": "You didn't select a choice.",
                         }
        return render(request, "$APPL/detail.html", render_context)
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("$APPL:results",
                                            args=(question.id,)))

ENDCAT
make_listing # ══════════════════════════════════════════════════


# Listings 33, p. 47...
#
start_listing 33 47 "$abs_TMPL/results.html" ; STARTCAT

<HTML>
  <BODY>
    <h1>Poll results for {{ question.question_text }}</h1>
    <ul>
    {% for choice in question.choice_set.all %}
      <li> Choice '{{ choice.choice_text }}' got
           {{ choice.votes }} vote{{ choice.votes|pluralize }}
      </li>
    {% endfor %}
    </ul>
    <a href="{% url '$APPL:detail' question.id %}">Vote again?</a>
  </BODY>
</HTML>

ENDCAT
make_listing # ══════════════════════════════════════════════════

if [ $TEST_13 = yes ] ; then
    # the questions below are those in the unnamed listing in Part 2, p. 29..31
    #
    add_question "13.1" "Not much" "The sky" "Just hacking again"
    add_question "13.2" "Choice 1" "Choice 2" "Choice 3"
    lasl_SQL_ID ; last_id="$?"
    show_pages "${APPL}/$last_id/"
fi

# 2.6.2 Use generic views: Less code is better...
#
# Listings 34, p. 48...
#
start_listing 34 48 "$abs_APPL/urls.py" ; STARTCAT

from django.urls import path

from . import views

app_name = "$APPL"
urlpatterns = [
    path("",                  views.IndexView.as_view(),   name="index"),
    path("<int:pk>/",         views.DetailView.as_view(),  name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote,            name="vote"),
              ]

ENDCAT
make_listing # ══════════════════════════════════════════════════


# Listings 35, p. 49...
#
start_listing 35 49 "$abs_APPL/views.py" ; STARTCAT

from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = "$APPL/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = "$APPL/detail.html"

class ResultsView(generic.DetailView):
    model = Question
    template_name = "$APPL/results.html"

def vote(request, question_id):
    """vote for a choice in the question with ID question_id,
       and return the result as a HTTP response. Also, complain
       if no choice was selected.
    """
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        render_context = { "question": question,
                           "error_message": "You didn't select a choice.",
                         }
        return render(request, "$APPL/detail.html", render_context)
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("$APPL:results",
                                            args=(question.id,)))

ENDCAT
make_listing # ══════════════════════════════════════════════════

if [ $TEST_14 = yes ] ; then
    # the questions below are those in the unnamed listing in Part 2, p. 29..31
    #
    add_question "14.1" "Not much" "The sky" "Just hacking again"
    add_question "14.2" "Choice 1" "Choice 2" "Choice 3"
    lasl_SQL_ID ; last_id="$?"
    show_pages "${APPL}/$last_id/"
fi

echo "
        ╔══════════════╗
        ║ Part 4 done. ║
        ╚══════════════╝
"

# 2.7 Writing your first Django app, part 5...

##############################################################################
##############################################################################
echo "
        ╔══════════════════════╗
        ║ new project created. ║
        ╚══════════════════════╝

"
exit 0
