= LA_pack primer
// vim: et:ts=4:sw=4

:Author: J√ľrgen Sauermann, GNU APL
:page-width: 120em
:toc:
:toclevels: 4
:iconsdir: /usr/share/asciidoc/icons
:icons:

== Abstract
GNU APL implements the APL functions monadic ‚ĆĻ (aka. *Matrix Inverse*) and
 dyadic ‚ĆĻ (aka. *Matrix Divide*) by means of _LApack functions_. These LApack
functions were originally written in FORTRAN, but then manually translated
from FORTRAN to Cpp by the author. In this translation, features of the
LApack functions that were not needed for ‚ĆĻ were removed in order to simplify
the Cpp code as much as possible.

== Monadic ‚ĆĻ: Matrix Inverse

Monadic *‚ĆĻ* is the special case of dyadic *A‚ĆĻB* where A is the unit matrix:

----
      Let A‚Üź(‚ÜĎ‚ćīB) ‚ąė.= (‚ÜĎ‚ćīB). Then ‚ĆĻB ‚Üź‚Üí A‚ćīB.
----

*Bif_F12_DOMINO::eval_B(Value_P B) const*, i.e. the implementation
of monadic ‚ĆĻ, simply constructs a unit matrix *I* of proper size and then
returns *eval_AB(I, B)*, i.e. the result of the implementation of
dyadic *A‚ĆĻB*.


== Dyadic A‚ĆĻB: Matrix Divide

In APL, *A‚ĆĻB* for a N-column matrix *A* is defined im terms of each column
of *A*:

----
      If  X‚ÜźA‚ĆĻB  then  X[;J] ‚Üź‚Üí A[;J]‚ĆĻB for all (scalar) columns J‚ąą‚ć≥¬Į1‚ÜĎ‚ćīA.
----

In other words, computing *A‚ĆĻB* for a matrix *A* boils down to computing
*A‚ĆĻB* for (column-) vectors (which are the columns of *A*). For every such
column vector a of *A*, the result is a column vector *x* of *X*:

   B ‚ąė x ‚Č° a   ‚Üź‚Üí   x ‚Č° a ‚ĆĻ B   ‚Üź‚Üí   x ‚Č° a ‚ąė B‚ĀĽ¬Ļ

NOTE: In GNU APL: *A +.√ó B ‚Üź‚Üí A ‚ąė B*. The vast majority of inner products
in real-life APL programs is used for matrix multiplication aka. *A +.√óB*.
The GNU APL function *A‚ąėB* is an optimized version of the special case
*A +.√ó B* of the more general inner product *A f.g B*.

Since *B* is the same for all columns a of *A* (and their corresponding result
columns *x* of *X*), is the result *X* of *X‚ÜźA‚ĆĻB* computed in two steps:

. compute *B‚ĀĽ¬Ļ*
. compute *X‚ÜźA‚ąėB‚ĀĽ¬Ļ*

The second step *X‚ÜźA‚ąėB‚ĀĽ¬Ļ* is simple, therefore only the first step,
the computation of *B‚ĀĽ¬Ļ* is of concern here.

BTW. the iteration over the columns of *A* in the second step above occurs
near the end of function *LA_pack::gelsy()* in function *trsm<T>()*.

In order to compute *B‚ĀĽ¬Ļ*, matrix *B* is factorized into two matrices *Q*
and *R* which have the following properties:

* *Q* is orthogonal (resp. Hermitian for complex *B*). That is: *Q‚ĀĽ¬Ļ ‚Č° \+‚ćČQ*,
* *R* is upper triangular, i.e. *RŠĶĘ‚Īľ = 0* for all *i > j*,
* *B = Q‚ąėR*,

Once *Q* and *R* are found, *B‚ĀĽ¬Ļ* can be computed easily with:

----
      B‚ĀĽ¬Ļ = (Q‚ąėR)‚ĀĽ¬Ļ = R‚ĀĽ¬Ļ‚ąėQ‚ĀĽ¬Ļ = R‚ĀĽ¬Ļ‚ąė‚ćČQ.
----

The inverse of an upper triangular matrix (such as R‚ĀĽ¬Ļ) is far easier
to compute than the inverse of a general matrix (such as B‚ĀĽ¬Ļ). See below.
What remains is therefore the computation of a QR factorization of an
arbitrary matrix B.

=== Inversion of an orthogonal Q

The inversion of an orthogonal *Q* matrix *Q* means transposition of *Q*.
However, unlike in APL where *‚ćČQ* is a new value computed from *Q*, this
transposition is never computed in Cpp or in FORTRAN. Instead, where *‚ćČQ* is
needed, the matrix *Q* is simply accessed with the row and column interchanged.
IOW, with a little care as to what are rows and what are columns is ‚ćČQ
no-op. In GNU APL three typedefs are used to distinguish rows and columns:

----
   In LApack.hh:

   typedef int Crow;   // row number
   typedef int Ccol;   // column number
   typedef int Cdia;   // diagonal item (row == column)
----

The translation from FORTRAN to Cpp is somewhat tricky for two reasons:

. FORTRAN indices run from 1..N while Cpp indices run from 0..N-1
. FORTRAN matrices are stored in column-major order (i.e. adjacent items
  in memory belong to the same column) while Cpp matrices are stored in
  row-major order (i.e. adjacent items in memory belong to the same row).

=== Inverting an upper trianguar matrix R

Suppose *R = op‚āĀ ‚ąė op‚āā ‚ąė ... ‚ąė op‚āô ‚ąė ID* where every *op‚āĖ* adds a multiple of
some row of R to some other row of R. Then, as we learn in school,
*R‚ĀĽ¬Ļ = ID ‚ąė op‚āĀ ‚ąė op‚āā ‚ąė ... ‚ąė op‚āô*. In other words, if the operations
*op‚āĀ*, *op‚āā*, ..., *op‚āô* turn a matrix *R* into the identity matrix, then
the same operations (in the same order) turn the the identity matrix into
the inverse *R‚ĀĽ¬Ļ* of *R*.

The operations that turn an upper trianguar matrix *R* into the identity matrix
ID are fairly simple:

. *R* is upper triangular. Therefore the last row of *R*, say row *n*,
  has only one nonzero element *r‚āô‚āô* on its diagonal. For every row above
  that last row, say row *k* (i.e. with k < n), do:
.. Let *r‚āĖ‚āô* be the last element in row *k*. Subtract a multiple of the last
   row from row *k* so that r‚āĖ‚āô becomes *0*.
.. That multiple is *r‚āĖ‚āô√∑r‚āô‚āô*.
.. Since all other elements of the last row are *0*, this only sets *r‚āĖ‚āô* to
  *0* but does not change any other element of row *k*.
.. After repeating this step for every k < n was the entire last column of the
   matrix *R* is *0*, except for the element *r‚āô‚āô* on the diagonal.
. Repeat the same step for the second-last, third-last, ... first column of
  the matrix. In every iteration one column of *R* is set to 0 above the
  diagonal. After the last *k=1* the matrix is diagonal (i.e. all elements
  above *and* below the diagonal are *0*).
. Finally, subtract a multiple of every row from itself so that the
  diagonal item becomes *1.0*.
.. That multiple for diagonal element r‚āĖ‚āĖ of row k is (1-r‚āĖ‚āĖ)√∑r‚āĖ‚āĖ.
.. After repeating that step for every *k ‚Č§ n* is *R* the unit matrix.
. Notice that every operation above subtracts a multiple of some row from some
  other (or the same) row.

The algorithm above defines the sequence *op‚āĀ ‚ąė op‚āā ‚ąė ... ‚ąė op‚āô* above,
 where *n* is the number of columns in *R*. In practice (and in LApack and
consequently also in GNU APL) these operations are not performed on *R* first
 and the on the identity matrix afterwords but rather in parallel:

. Start with a matrix *R, AUG* where *AUG‚Üź(‚ćīR)‚ÜĎ(‚ć≥‚ÜĎ‚ćīR)‚ąė.=‚ć≥‚ÜĎ‚ćīR)*. That is, *AUG*
  is initially the unit matrix with the same shale as *R*. The matrix *AUG*
  (or sometimes the matrix *R,AUG*) is commonly known as the _augmented matrix_.
. The operations described above are then simultaneously applied to the
  left half (i.e. to *R*) and to the right half (i.e. to *AUG*) until the left
  half *R* of *R,AUG* has become the unit matrix. At that point, the right
  half *AUG* has become the desired inverse *R‚ĀĽ¬Ļ* of *R*.
. All this happens in functions *LA_pack::invert_UTM()* and 
  *LA_pack::invert_QUTM()*. The term *QUTM* stands for **Q**uadratic **U**pper
  **T**riangular **M**atrix and takes advantage of the fact that the inversion
  of a non-quadratic upper triangular M√óN matrix is essentially the inversion
  of its upper N√óN submatrix. The rows N+1..M are all zero and become zero
  columns in the inverse.

=== QR factorization

==== Householder matrix

For the moment we consider only real matrices; the complex case is almost
identical, except that *‚ćČX* becomes *\+‚ćČX* in the complex case. *\+‚ćČX* is
called the _conjugate transpose_ of *X* which is the same as the "normal"
transpose if *X* is real.

Let *B* be an arbitrary M√óN matrix.

Let *V‚Üź1‚ÜďB[;1]*, i.e. V is the first column of *B* except the
diagonal item *B[1;1]*.

Let *L‚Üź+/V√óV*, i.e. *L* is (the square of) the Euclidean length of *V*.

The Householder matrix *H=H(B)* for matrix *B* is then defined as:

----
              2
      H = I - ‚ĒÄ √ó V ‚ąė.√ó V.
              L
----

That is:

----
             ‚éß 1.0 - 2√óV[i]√óV[i]     if i=j , and
H = (h)ŠĶĘ‚Īľ =  ‚é®
             ‚é© - 2√óV[i]√óV[j]         otherwise.
----

It follows immediately that:

. *H* is _Hermitian_ (aka. _symmetric_ if *H* is real). I.e. *H = +‚ćČH*,
. *H* is _unitary_ (aka. _orthogonal_ if *H* is real). I.e. *H‚ĀĽ¬Ļ = ‚ćČH*, and
. *H* is _involutary_. I.e. *H* = *H‚ĀĽ¬Ļ*

These really nice properties of *H*:

. make the computation of the transposition *‚ćČH* essentially a no-op, and
. ensures that the composition *H = H‚āĀ ‚ąė H‚āā ‚ąė ... ‚ąė H‚āô* of several Householder
  matrices is also Hermitian (complex case) resp. orthogonal (real case).

In the following let:

* *B* be an arbitrary real or complex matrix,
* vector *B1* be the first column of *B*, and
* scalar *B11* be the first item of column vector *B1* (= the first item
  on the diagonal of B).

In the LApack code is *B1* usually a variable named (lowercase) *x* and *B11*
a scalar variable named (uppercase) *ALPHA* (or *‚ćļ* in comments).
That is, matrix B looks like this:

----
      LApack matrix B        APL matrix B
      ‚ēĒ‚ēź‚ēź‚ēź‚ē§‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēó      ‚ēĒ‚ēź‚ēź‚ēź‚ēź‚ēź‚ē§‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēó
      ‚ēĎ ‚ćļ ‚Ēā         ‚ēĎ      ‚ēĎ B11 ‚Ēā         ‚ēĎ
      ‚ēü‚ĒÄ‚ĒÄ‚ĒÄ‚Ē§         ‚ēĎ      ‚ēü‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ‚Ē§         ‚ēĎ
      ‚ēĎ   ‚Ēā         ‚ēĎ      ‚ēĎ     ‚Ēā         ‚ēĎ
      ‚ēĎ   ‚Ēā         ‚ēĎ  ‚Üź‚Üí  ‚ēĎ     ‚Ēā         ‚ēĎ
      ‚ēĎ x ‚Ēā         ‚ēĎ      ‚ēĎ B1  ‚Ēā         ‚ēĎ
      ‚ēĎ   ‚Ēā         ‚ēĎ      ‚ēĎ     ‚Ēā         ‚ēĎ
      ‚ēĎ   ‚Ēā         ‚ēĎ      ‚ēĎ     ‚Ēā         ‚ēĎ
      ‚ēö‚ēź‚ēź‚ēź‚ēß‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēĚ      ‚ēö‚ēź‚ēź‚ēź‚ēź‚ēź‚ēß‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēĚ
----

There is a subtle but noteworthy differences between the APL code discussed
below and the LApack FORTRAN or Cpp code:

* In the original FORTRAN code of LApack, the vector *x* _excludes_ the
  diagonal element *‚ćļ* and *‚ćļ* is passed as a separate function argument or
  result.
* In the GNU APL Cpp translation of that code, the vector *x* also
 _excludes_ the diagonal element *‚ćļ*. However, *‚ćļ* is not passed as a separate
  function argument like in FORTRAN. Instead Cpp takes advantage of the fact
  that our matrices are stored in FORTRAN order which makes *‚ćļ ‚Üź‚Üí x[-1]* and
  therefore a function that already knows *x* can easily recover *‚ćļ* from *x*.
* In the APL code below, the vector *B1* (which corresponds to *x*)
  _includes_ the scalar *B11* (which corresponds to *‚ćļ*).


Instead of a strict mathematical proof we use APL as a tool of thought.

Let *V* be a real or complex vector. The following APL function named
*Householder* simply implements the definition of a Householder matrix
given above:

----
‚ąáH‚ÜźHouseholder V;I;L
 ‚ćĚ
 ‚ćĚ return the Householder matrix (aka. elementary reflector) for vector V
 ‚ćĚ
 I‚ÜźI‚ąė.=I‚Üź‚ć≥‚ćīV        ‚ćĚ I:  the (‚ćīV)√ó(‚ćīV) identity matrix,
 L‚Üź+/‚ą£V√ó+V          ‚ćĚ L:  ‚ēĎV‚ēĎ¬≤ i.e. the square of the norm of vector V
 H‚ÜźI-(2√∑L)√óV‚ąė.√ó+V   ‚ćĚ H:  the Householder matrix for vector V
‚ąá
----

Next we define a somewhat random matrix *B* that shall prove our claims
by example (aka. _incomplete induction_):

----
      MN‚Üź(M N)‚Üź4 3)                ‚ćĚ choose a matrix size (M‚Č•N)
      ‚éēRL‚Üź+/‚éēTS ‚óä B‚Üź?(2, MN)‚ćī18    ‚ćĚ prepare for random B
      B‚Üź+‚ĆŅ9 0J9√ó[1]B               ‚ćĚ some complex M√óN random matrix B
      B11‚Üź‚ÜĎB1‚ÜźB[;1]                ‚ćĚ B1 is column 1 of B, B11 its first item
----

With these prerequisites we can "prove" the following

*Proposition:* Let

----
      L11‚Üź√óB11             ‚ćĚ B11 normalized to length 1 (= ¬Ī1 for real B11)
      LB1‚Üź(+/B1√ó+B1)‚čÜ0.5   ‚ćĚ scalar LB1 is ‚ēĎB1‚ēĎ i.e. the length of B1

      H1‚ÜźHouseholder V1‚ÜźB1 + L11√óM‚ÜĎLB1   ‚ćĚ a Householder matrix (from V1)
      H2‚ÜźHouseholder V2‚ÜźB1 - L11√óM‚ÜĎLB1   ‚ćĚ another Householder matrix (from V2)
----

*Proofs* (by APL examples *B*):

----
      ‚ąáH‚ÜźHouseholder V;I;L
       ‚ćĚ
       ‚ćĚ return the Householder matrix (aka. elementary reflector) for vector V
       ‚ćĚ
       I‚ÜźI‚ÜźI‚ąė.=I‚Üź‚ć≥‚ćīV      ‚ćĚ I: the (‚ćīV)√ó(‚ćīV) identity matrix,
       L‚Üź+/‚ą£V√óV           ‚ćĚ L: ‚ēĎV‚ēĎ¬≤ i.e. the square of the norm of vector V
       H‚ÜźI-(2√∑L)√óV‚ąė.√ó+V   ‚ćĚ H: the Householder matrix for vector V
      ‚ąá

      LB1‚Üź(+/B1√ó+B1)‚čÜ0.5   ‚ćĚ scalar LB1 is ‚ēĎB1‚ēĎ i.e. the length of B1
      L11‚Üź√óB11             ‚ćĚ B11 normalized to length 1 (= ¬Ī1 for real B11)
      H1‚ÜźHouseholder B1+L11√óM‚ÜĎLB1
      H2‚ÜźHouseholder B1-L11√óM‚ÜĎLB1

      H = +‚ćČH               ‚ćĚ H is Hermitian
1 1 1
1 1 1
1 1 1

      (‚ĆĻH) = ‚ćČH             ‚ćĚ H is unitary
1 1 1
1 1 1
1 1 1

      H = ‚ĆĻH                ‚ćĚ H is involutary
1 1 1
1 1 1
1 1 1

      B
 27J117  54J72   18J27
 81J117  18J117 126J144
117J81  117J108   9J54
135J27  117J18  117J90

      2‚ćēH1 ‚ąė B   ‚ćĚ notice the first column
 ¬Į61.12J¬Į264.83 ¬Į33.28J¬Į233.03  ¬Į8.67J¬Į203.23
    .00J.00     ¬Į52.41J25.80    86.09J69.90
    .00J.00      19.00J47.42   ¬Į54.44J¬Į1.31
    .00J.00       6.71J1.84     39.43J65.25

      2‚ćēH2 ‚ąė B   ‚ćĚ notice the first column
 61.12J264.83  33.28J233.03   8.67J203.23
   .00J.00    ¬Į19.79J¬Į30.51  73.02J¬Į12.81
   .00J.00     29.70J¬Į16.77 ¬Į95.79J¬Į74.13
   .00J.00     ¬Į8.43J¬Į59.27 ¬Į25.25J16.46
----

=== Repeated Application of Reflectors

Once we know how to set the first column of some arbitrary matrix *B*
to *0* (below the diagonal) we can now turn the entire matrix into an
upper triangular form:

. Set B‚āĀ = B and find a reflector H‚āĀ that sets the items below the first
   column of B to 0.
. Repeat that step for B‚āā = 1 1‚ÜďB‚āĀ, B‚āÉ = 1 1‚ÜďB‚āā, ... B‚āô = 1 1‚ÜďB‚āô ‚āĀ which
  computes reflectors a sequence H‚āĀ, H‚āā, ... H‚āô. The matrices B‚āĖ and H‚āĖ become
  smaller and smaller in this process.

After n steps matrix B looks like this:

----

      ‚ēĒ‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēó   ‚ēĒ‚ēź‚ēź‚ē§‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēó   ‚ēĒ‚ēź‚ēź‚ē§‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēó     ‚ēĒ‚ēź‚ēź‚ē§‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēó
      ‚ēĎ             ‚ēĎ   ‚ēĎ‚ćļ‚āĀ‚Ēā    R1     ‚ēĎ   ‚ēĎ‚ćļ‚āĀ‚Ēā    R1     ‚ēĎ     ‚ēĎ‚ćļ‚āĀ‚Ēā    R1     ‚ēĎ
      ‚ēĎ             ‚ēĎ   ‚ēü‚ĒÄ‚ĒÄ‚Ē§           ‚ēĎ   ‚ēü‚ĒÄ‚ĒÄ‚Ēľ‚ĒÄ‚ĒÄ‚Ēź  R2    ‚ēĎ     ‚ēü‚ĒÄ‚ĒÄ‚Ēľ‚ĒÄ‚ĒÄ‚Ēź  R2    ‚ēĎ
      ‚ēĎ             ‚ēĎ   ‚ēĎ  ‚Ēā           ‚ēĎ   ‚ēĎ  ‚Ēā‚ćļ‚āā‚Ēā        ‚ēĎ     ‚ēĎ  ‚Ēā‚ćļ‚āā‚Ēā   ...  ‚ēĎ
      ‚ēĎ     B=B‚āĀ    ‚ēĎ ‚Üí ‚ēĎ  ‚Ēā           ‚ēĎ ‚Üí ‚ēĎ  ‚Ēú‚ĒÄ‚ĒÄ‚Ē§        ‚ēĎ ... ‚ēĎ  ‚Ēú‚ĒÄ‚ĒÄ‚Ē§        ‚ēĎ
      ‚ēĎ             ‚ēĎ   ‚ēĎH‚āĀ‚Ēā           ‚ēĎ   ‚ēĎH‚āĀ‚Ēā  ‚Ēā        ‚ēĎ     ‚ēĎH‚āĀ‚Ēā  ‚Ēā ...    ‚ēĎ
      ‚ēĎ             ‚ēĎ   ‚ēĎ  ‚Ēā           ‚ēĎ   ‚ēĎ  ‚ĒāH‚āā‚Ēā        ‚ēĎ     ‚ēĎ  ‚ĒāH‚āā‚Ēā     ‚ĒĆ‚ĒÄ‚ĒÄ‚ēĘ
      ‚ēĎ             ‚ēĎ   ‚ēĎ  ‚Ēā           ‚ēĎ   ‚ēĎ  ‚Ēā  ‚Ēā        ‚ēĎ     ‚ēĎ  ‚Ēā  ‚Ēā     ‚Ēā‚ćļ‚āô‚ēĎ
      ‚ēö‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēĚ   ‚ēö‚ēź‚ēź‚ēß‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēĚ   ‚ēö‚ēź‚ēź‚ēß‚ēź‚ēź‚ēß‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēĚ     ‚ēö‚ēź‚ēź‚ēß‚ēź‚ēź‚ēß‚ēź‚ēź‚ēź‚ēź‚ēź‚ēß‚ēź‚ēź‚ēĚ
----

NOTE: For lack of space we show *‚ćļ‚āĀ ... ‚ćļ‚āô* on the diagonal above, but in
reality the diagonal is *R‚āĀ‚āĀ, R‚āā‚āā, ... R‚āô‚āô*. The sequence *‚ćļ‚āĀ ... ‚ćļ‚āô*  is
stored in *tau* as explained above. 

Now:

. R is upper triangular (where the items below the diagonal are 0 by
  definition and therefore need not be stored in B)
. *H ‚Üź H‚āĀ ‚ąė H‚āā ‚ąė ... ‚ąė H‚āô* is unitary resp. orthogonal since it is the
  product of n unitary resp. orthogonal matrices *H‚āĖ*.

The iteration above takes place in function *LA_pack::laqp2()* which starts
with matrix *B* and ends with *R* in the upper half (including the diagonal),
*Q* in the lower half, and the diagonal factors *‚ćļ‚āĀ ... ‚ćļ‚āô* stored in
variable *tau*.

At this point the lower half and *tau* are not the matrix *Q* itself but the
reflectors that turn the identity matrix into *Q*. For this reason we usually
refer to lower half as *HR* and not as *QR* in the GNU APL Cpp code.

=== Numerical considerations

In mathematics we compute with exact numbers and would be finished at this
point. On real computers we work with approximation of exact numbers which may
cause problems with the accuracy of the result.

Let *‚ćļ* and *ő≤* be numbers. For the sake of explanation assume *‚ćļ>0* and *ő≤>0*.
Due to rounding, do *‚ćļ* and *ő≤* only determine two ranges in which the exact
‚ćļ and *ő≤* lie:

----
      ‚ćļ - e‚āĀ ‚Č§ exact ‚ćļ ‚Č§ ‚ćļ + e‚āĀ and
      ő≤ - e‚āā ‚Č§ exact ő≤ ‚Č§ ő≤ + e‚āā
----

The (usually small) numbers *e‚āĀ* resp, *e‚āā* define the _absolute error_ of *‚ćļ*
resp. *ő≤* while the quotients *e‚āĀ√∑‚ćļ* resp. *e‚āā√∑ő≤* define the _relative_error_
of *‚ćļ* resp. *ő≤*.

Now, adding or subtracting the inequalities above gives:

----
               ‚ćļ - e‚āĀ ‚Č§ exact ‚ćļ ‚Č§ ‚ćļ + e‚āĀ
            ¬Ī  ő≤ - e‚āā ‚Č§ exact ő≤ ‚Č§ ő≤ + e‚āā
      ‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź
      (‚ćļ¬Īő≤) - (e‚āĀ+e‚āā) ‚Č§ exact ‚ćļ¬Īő≤ ‚Č§ (‚ćļ¬Īő≤) + (e‚āĀ+e‚āā) 
----

This means that the absolute error of the sum or difference *(‚ćļ¬Īő≤)* is the
sum of the absolute errors of *‚ćļ* and *ő≤*. This is no problem as long as
*(‚ćļ¬Īő≤)*  does not come too close to *0*. If it does, however, then the
absolute error remains small, but the relative error is now:

----
      e‚āĀ + e‚āā
      ‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ ‚Üí ‚ąě  as (‚ćļ ¬Ī ő≤) ‚Üí 0
       ‚ćļ ¬Ī ő≤ 
----

That is, for *(‚ćļ-ő≤)* can the relative error become huge if *‚ćļ*‚Čą*ő≤*.
In LApack these issues are addressed in 3 ways:

. If the input matrices are very large or very small (in terms of their norm)
  then they (and their result) are scaled up or down so that their
  coefficients land in a range that is not subject to major rounding error.
  See function *LA_pack::gelsy()* vs. *LA_pack::scaled_gelsy()*.
. As we have seen above, for any matrix *B* there are actually two reflectors
  *H1* and *H2* each of which bring the first column off *B* below the
  diagonal to *0). LA_pack then chooses the one that produces the largest
  difference *V1* resp.  *V2* above.
. Some functions, in particular *LA_pack::larfg()* take additional measures
  to minimize the errors caused by too small arguments.
. Column pivoting. instead of processing the columns in the order different
  from B[;1], B[;2], ... B[N] as to avoid small coefficients in the subsequent
  matrices.

The column pivoting works like this:

. In every iteration above:
.. Compute the norms of the columns,
.. Find the column *k* with the largest norm (called "the pivot")
.. If *k‚Č†1* (i.e. the first column does not have the largest norm already)
   then exchange columns *1* and *k* before proceeding.
.. In the context of solving equations, the pivoting is essentially a renaming
   of the variables *x‚āĀ, x‚āā, ..., x‚āô*. This renaming is later undone (see the
   end of *scaled_gelsy()*) before the result is returned to APL.


=== Memory Layout

At the time when FORTRAN was popular, memories were small. The LApack FORTRAN
code addressed this in two ways:

=== Blocked execution

Blocked operation means that the processing of matrices that may not fit
 into the core memory of a computer were processed in chunks. Some FORTRAN
functions therefore had a "blocked" version (for large matrices) and an
"unblocked" version (for small matrices and for the chunks of large matrices).

These days memory is large and therefore blocking was removed entirely. Only
the unblocked FORTRAN functions survived in the GNU APL code.

=== In-place computation

Another heavily used trick to reduce memory consumption is in-place
computation. Instead of passing the argument of a function in one variable and
storing the result in a another variable, the same variable was used for the
largest input variable and the result. For example, function *laqp2()*
comnputes the QR factorization of an arbitrary matrix *B* and the result is
stored at the same memory location. However, the result *QR* is split in two
pieces along the diagonal, taking advantage of the fact that *Q* is symmetric
(so its upper half can be derived directly from its lower half, and that *R*
is upper triangular (so its lower half is implicitly *0* and therefore
not of interest):

----
      Input matrix B       Result Q and R
      ‚ēĒ‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēó     ‚ēĒ‚ēź‚ēź‚ēź‚ēź‚ē§‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēó
      ‚ēĎ              ‚ēĎ     ‚ēĎR‚āĀ‚āĀ ‚Ēā           ‚ēĎ
      ‚ēĎ              ‚ēĎ     ‚ēü‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ‚Ēľ‚ĒÄ‚ĒÄ‚ĒÄ‚Ēź       ‚ēĎ
      ‚ēĎ              ‚ēĎ     ‚ēĎ    ‚ĒāR‚āā‚āā‚Ēā   R   ‚ēĎ
      ‚ēĎ              ‚ēĎ  ‚Üí  ‚ēĎ    ‚ĒĒ‚ĒÄ‚ĒÄ‚ĒÄ‚Ēė       ‚ēĎ
      ‚ēĎ              ‚ēĎ     ‚ēĎ         ...    ‚ēĎ
      ‚ēĎ              ‚ēĎ     ‚ēĎ  Q         ‚ĒĆ‚ĒÄ‚ĒÄ‚ĒÄ‚ēĘ
      ‚ēĎ              ‚ēĎ     ‚ēĎ            ‚ĒāR‚āô‚āô‚ēĎ
      ‚ēö‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēĚ     ‚ēö‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēß‚ēź‚ēź‚ēź‚ēĚ
----

Unfortunately in this scheme the matrices of *Q* and *R* now compete for the
former diagonal of input *B*. This is solved by storing in the diagonal of *Q*
in a separate vector (named *tau* in the LApack code):

----
      ‚ēĒ‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēó           ‚ēĒ‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēó  
      ‚ēĎ              ‚ēĎ           ‚ēĎ              ‚ēĎ
      ‚ēô‚ĒÄ‚ĒÄ‚ĒÄ‚Ēź     RŠĶĘ‚Īľ  ‚ēĎ           ‚ēü‚ĒÄ‚ĒÄ‚ĒÄ‚Ēź     RŠĶĘ‚Īľ  ‚ēĎ
          ‚Ēā          ‚ēĎ           ‚ēĎ   ‚Ēā          ‚ēĎ
          ‚ĒĒ‚ĒÄ‚ĒÄ‚ĒÄ‚Ēź      ‚ēĎ           ‚ēĎ   ‚ĒĒ‚ĒÄ‚ĒÄ‚ĒÄ‚Ēź      ‚ēĎ
      ‚ēĒ‚ēź‚ēź‚ēź‚ēē   ‚Ēā      ‚ēĎ     ‚Üí     ‚ēĎ       ‚Ēā      ‚ēĎ 
      ‚ēĎ‚ćļ‚āĀ ‚Ēā   ‚ĒĒ‚ĒÄ‚ĒÄ‚ĒÄ‚Ēź  ‚ēĎ           ‚ēĎ HŠĶĘ‚Īľ   ‚ĒĒ‚ĒÄ‚ĒÄ‚ĒÄ‚Ēź  ‚ēĎ
      ‚ēü‚ĒÄ‚ĒÄ‚ĒÄ‚Ēľ‚ĒÄ‚ĒÄ‚ĒÄ‚Ēź   ‚Ēā  ‚ēĎ           ‚ēĎ           ‚Ēā  ‚ēĎ
      ‚ēĎ   ‚Ēā‚ćļ‚āā ‚Ēā   ‚ēė‚ēź‚ēź‚ēĚ           ‚ēö‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēß‚ēź‚ēź‚ēĚ
      ‚ēĎ   ‚ĒĒ‚ĒÄ‚ĒÄ‚ĒÄ‚Ēľ‚ĒÄ‚ĒÄ‚ĒÄ‚Ēź              
      ‚ēĎ       ‚Ēā...‚Ēā         
      ‚ēĎ  HŠĶĘ‚Īľ  ‚ĒĒ‚ĒÄ‚ĒÄ‚ĒÄ‚Ēľ‚ĒÄ‚ĒÄ‚ēĖ          ‚ēĒ‚ēź‚ēź‚ēź‚ē§‚ēź‚ēź‚ēź‚ē§‚ēź‚ēź‚ēź‚ē§‚ēź‚ēź‚ēź‚ēó 
      ‚ēĎ           ‚Ēā‚ćļ‚āô‚ēĎ     tau: ‚ēĎ‚ćļ‚āĀ ‚Ēā‚ćļ‚āā ‚Ēā...‚Ēā‚ćļ‚āô ‚ēĎ
      ‚ēö‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēź‚ēß‚ēź‚ēź‚ēĚ          ‚ēö‚ēź‚ēź‚ēź‚ēß‚ēź‚ēź‚ēź‚ēß‚ēź‚ēź‚ēź‚ēß‚ēź‚ēź‚ēź‚ēĚ 
----

Another issue to understand LApack is that functions *laqp2()* and friends
do *not* return the matrices *Q* and *R* of the factorization *B = Q‚ąėR*
directly. Instead of *Q* it returns a matrix *H* with the Householder
reflectors for the different columns. The matrix *Q* can then be obtained
by applying these reflectors to the *n√ón* unit matrix *ID(n)*:

----
      Q ‚Üź‚Üí H‚ąėID(n)
----

This avoids one intermediate matrix multiplication. Instead of *Q‚ÜźH‚ąėI*
followed by some other *Z‚ÜźQ‚ąėR*, LApack leaves *H* for the moment and later
computes *Z‚čÜH‚ąėR* directly. In addition LApack avoids the computation of
the householder matrices used in the APL examples above for demonstration
purposes. Instead of full k√ók reflector matrices it uses the reflector
vectors, typically called *v*, and computes the elements *HŠĶĘ‚Īľ* of each
reflector as needed. The lifetime of each *HŠĶĘ‚Īľ* is usually short,
therefore it makes little sense to store it in a large matrix.

=== LApack function names

The names of LApack functions look somewhat acary at first glance. For example
the name of function *zungqr()* may not be too obvious. However these names
follow a naming scheme that rougly looks as follows:

----
   ‚ĒĆ‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ data type (i‚Üź‚Üíinteger, d‚Üź‚Üídouble, z‚Üź‚Üícomplex)
   ‚Ēā‚ĒĆ‚Ē¨‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ matrix type (un ‚Üź‚Üí unitary, or ‚Üź‚Üí orthogonal, ge ‚Üź‚Üí general, etc.)
   ‚Ēā‚Ēā‚Ēā‚ĒĆ‚Ē¨‚Ē¨‚ĒÄ‚ĒÄ‚ĒÄ‚ĒÄ function type (gqr ‚Üź‚Üí generate QR factorization)
   ‚Ēā‚Ēā‚Ēā‚Ēā‚Ēā‚Ēā     function variant (blocked/unblocked etc.
   ‚Ēā‚Ēā‚Ēā‚Ēā‚Ēā‚Ēā
   zungqr()
----
 
With this nameing scheme function *zungqr()* for complex matrices becomes
*dorqr2()* for real matrices.

In FORTRAN every complex function (like *zungqr()* has a real counterpart
*dorqr2()* for real matrices. In fact there are even more variants because
there are different precisions (like 32-bit *float* and 64-bit *double*
in Cpp) and each has its own FORTRAN functions. That made a lot of sense
in the FORTRAN days where it made a considerable diference in performance.

A closer look at these functions revealed, however, that the difference
between data types are actually rather small. The GNU APL version of these
functions make the data type a template parameter so that every group of
FORTRAN functions becomes a single template function in Cpp. In our example:

----
      FORTRAN:

          dorgqr   QR-factorize real matrix
          zungqr   QR-factorize complex matrix

      becomes C++

          template<T>  ungqr()
----

where the template argument *<T>* is either *<DD>* for real or *<ZZ>* for
complex numbers. The use of Cpp templates cuts the number of functions
needed roughly in half,

=== Call Tree

With all thee in mind, *A‚ĆĻB* aka. *Bif_F12_DOMINO::eval_AB* becomes simple.
We look at its call tree, which is roughly this:

----
   Bif_F12_DOMINO::eval_AB()
   ‚Ēā
   ‚ĒĒ‚ĒÄ‚ĒÄ‚ĒÄ LA_pack::divide_matrix()
        ‚Ēā
        ‚ĒĒ‚ĒÄ‚ĒÄ‚ĒÄ LA_pack::gelsy<T>()
             ‚Ēā
             ‚ĒĒ‚ĒÄ‚ĒÄ‚ĒÄ LA_pack::scaled_gelsy()
                  ‚Ēā
                  ‚Ēú‚ĒÄ‚ĒÄ‚ĒÄ LA_pack::laqp2<T>()
                  ‚Ēā    ‚Ēā
                  ‚Ēā    ‚Ēú‚ĒÄ‚ĒÄ‚ĒÄ LA_pack::larfg<T>()
                  ‚Ēā    ‚ĒĒ‚ĒÄ‚ĒÄ‚ĒÄ LA_pack::larf<T>()
                  ‚Ēā
                  ‚Ēú‚ĒÄ‚ĒÄ‚ĒÄ LA_pack::estimate_rank()
                  ‚Ēā
                  ‚Ēú‚ĒÄ‚ĒÄ‚ĒÄ LA_pack::trsm<T>()
                  ‚Ēā
                  ‚ĒĒ‚ĒÄ‚ĒÄ‚ĒÄ LA_pack::unm2r<T>()
                       ‚Ēā
                       ‚Ēú‚ĒÄ‚ĒÄ‚ĒÄ LA_pack::larf<T>()
                       ‚Ēú‚ĒÄ‚ĒÄ‚ĒÄ ...
                       ‚ĒĒ‚ĒÄ‚ĒÄ‚ĒÄ LA_pack::larf<T>()
----

In this call tree:

* *eval_AB()* performs the APL argument checking (matching shapes of *A*
  and *B*) and figures if *A* or *B* contain complex items. It also treats
  scalars resp. vectors *A* and *B* as 1√ó1 resp. 1√óN matrices
* *divide_matrix()* translates the ravels of APL matrices *A* and *B* into
  (transposed) FORTRAN matrices
* *gelsy<T>()* scales (and later unscales) FORTRAN matrices *A* and *B* with
   very small or very large items so that subsequent operations are
   safe in regard to rounding errors. In almost all real life cases
   *A* and *B* will not need any scaling.
* *scaled_gelsy()* computes *Z‚ÜźA‚ĆĻB* for the now properly scaled *A* and *B*
* *laqp2()* computes a QR factorization *B=Q‚ąėR* of *B*. In the result:
** *Q* is orthogonal (for real *A* and *B*) or Hermitian (for complex
   *A* or *B*). *Q* is easy to invert since *Q‚ĀĽ¬Ļ ‚Üź‚Üí +‚ćČQ*, and
** *R* is upper triangular (so that *R‚ąėX=C* is simple to solve)
* In the QR factorization: for every column of *B*:
** *larfg<T>()* generates one reflector (i.e. for one column of *B*)
** *larf<T>()*  applies that reflector to a  submatrix of *B*
* *estimate_rank()* checks that the system *A=B‚ąėX* of linear equations is
   not under-determined and raises a DOMAIN ERROR if it is. In contrast,
   over-determination (more equations than variables) is accepted and
   produces a least-square solution for *A=X=B‚ąėX*
* *trsm<T>()* computes *R‚ĀĽ¬Ļ* for the upper triangular factor *R*
  of *B=Q‚ąėR* that was computed above
* *unm2r<T>()* applies *R‚ĀĽ¬Ļ* to *A*


== ‚ĆĻ with axis: QR factorization

Often the orthogonal *Q* and/or the upper triangular *R* of a factorization
*B=Q‚ąėR* is more valuable than the final result *B‚ĀĽ¬Ļ=R‚ĀĽ¬Ļ‚ąėQ‚ĀĽ¬Ļ* of *‚ĆĻB* or
*A‚ĆĻB*. For this reason GNU APL provides *‚ĆĻ[X]* as to obtain the matrices
*Q*  and *R* without applying them (i.e. in order to solve *A‚ąėX=B*).

The result of *‚ĆĻ[X] B* is a triple

----
      (Q R Rinv) ‚Üź ‚ĆĻ[X] B
----

where:

* *Q* is orthogonal (resp. Hermitian), i.e. *Q‚ĀĽ¬Ļ = +‚ćČQ*
* *R* is upper triangular, i.e. *R[i;j] = 0* for all *i > j*, and
* *Rinv* is *R‚ĀĽ¬Ļ* as a matter of convenience for the programmer.

GNU APL currently provides two different implementations with slightly
different properties:

. The implementation used by default is a direct translation from an APL
  algorithm to Cpp. The APL algorithm was published by *Garry Helzer* in
  *APL Quote Quad, Volume 9, Issue 3, 1979*. The GNU APL Cpp function
  that implements the Helzer algorithm is *Bif_F12_DOMINO::householder()*.
. The other implemnation uses the LApack function *geqp3()*, which is,
  in GNU APL, function *laqp2()* with the column pivoting removed.
. The selection as to which algorith shall be used is controlled by macro
  *QR_HELZER* at the beginning of file *LApack.hh*.

In theory a purely LApack based QR factorization should have a slightly
better performance and/or numerical stability. This is because LApack has
put a considerable effort into numerical border cases (while the Helzer
algorithm merely sets near-0 matrix items to 0). Reusing that effort
could be beneficial for QR factorization as well.

There are some subtle differences between the the Helzer algorithm and the
LApack based version:

. Both compute a factorization *B=Q‚ąėR* as required. If the matrix *B* is
  quadratic, i.e. *‚ćīB ‚Üź‚Üí N N*, then they produce essentially the same
  result. However, let *‚ćīB ‚Üź‚Üí M N* with *M‚Č†N*. Then:
.. The Helzer algorithm computes a matrix *Q* with *Q‚ąė‚ćČQ ‚Üź‚Üí ID(n)* and
  *(Q‚ąė‚ćČQ) ‚Üź‚Üí ID(n)*.
.. The Lapack algorithm computes a matrix *Q* with *(‚ćČQ)‚ąėQ ‚Üź‚Üí ID(n)* but
   _not_ *(Q‚ąė‚ćČQ) ‚Üź‚Üí ID(n)*.
. These differences are apparently caused caused by differen rsult shapes
  and zero-padding:
.. *‚ćīQ ‚Üź‚Üí M M* for Helzer and *‚ćīQ ‚Üź‚Üí M N* for LApack,
.. *‚ćīR ‚Üź‚Üí M N* for Helzer and *‚ćīQ ‚Üź‚Üí N N* for LApack. The additional
   items in Helzer are 0 (since *R* is upper triangualar.
.. As a consequence, *‚ćīRinv ‚Üź‚Üí N M* for Helzer and *‚ćīQ ‚Üź‚Üí N N* for LApack.
. Apart from that are the matrix items that are present in both cases the
  same.

In the non-quadratic case one can simply *M N‚ÜĎQ* and *N N‚ÜĎR* to convert the
the Helzer *Q* and *R* into the LApack *Q* and *R*, but not vice versa.

