GNUAPL: src/APL_types.hh File Reference
APL_types.hh File Reference
#include <complex>
#include <memory>
#include <math.h>
#include <stdint.h>
#include "Common.hh"
#include "Unicode.hh"
Classes
struct AP_num3
three AP numbers that uniquely identify a processor
struct Function_PC2
two Function_PCs indication a token range in a user defined function body
struct labVal
A label in a defined function.
struct _twc
The end and the state of an abstract iterator along one axis (to / weight / current)
struct _ftwc
The range and the state of an abstract iterator along one axis (from / to / weight / current)
struct ravel_comp_len
the ravel (of an APL value) and a comparison lenght (= number of consecutive cells to be compared)
Namespaces
APL_types
Macros
#define APL_Float_is_class 0
#define complex_exponent(x) exp(x)
#define complex_power(x, y) pow((x), (y))
#define complex_sqrt(x) sqrt(x)
#define release_APL_Float(x)
Typedefs
typedef int16_t sRank
The (signed) rank of an APL value.
typedef sRank sAxis
typedef uint32_t uRank
The (unsigned) rank of an APL value.
typedef uRank uAxis
typedef uint16_t AxesBitmap
A bitmap for axes (in fun[X] arguments) normalized to ⎕IO←0.
typedef int64_t ShapeItem
One dimension length (axis length) of an APL shape.
typedef int SI_level
The SI level, 0 = global (oldest), caller at level N called function at N+1.
typedef Unicode APL_Char
One APL character value.
typedef int64_t APL_Integer
One APL integer value.
typedef long long long_long
long long for sprintf() and friends
typedef unsigned long unsigned_long
unsigned long for sprintf() and friends
typedef const Function * Function_P
typedef double APL_Float_Base
One (real) APL floating point value.
typedef APL_Float_Base APL_Float
typedef complex< APL_Float > APL_Complex
One APL complex value.
typedef int64_t APL_time_us
APL time = microseconds since Jan. 1. 1970 00:00:00 UTC.
typedef int32_t APL_types::Depth
Enumerations
enum CellType {
CT_NONE = 0,
CT_BASE = 0x01,
CT_CHAR = 0x02,
CT_POINTER = 0x04,
CT_CELLREF = 0x08,
CT_INT = 0x10,
CT_FLOAT = 0x20,
CT_COMPLEX = 0x40,
CT_NUMERIC = CT_INT | CT_FLOAT | CT_COMPLEX,
CT_SIMPLE = CT_CHAR | CT_NUMERIC,
CT_MASK = CT_CHAR | CT_NUMERIC | CT_POINTER | CT_CELLREF,
CTS_BIT = 0x0001000,
CTS_X8 = 0x0002000,
CTS_S8 = 0x0004000,
CTS_U8 = 0x0008000,
CTS_X16 = 0x0010000,
CTS_S16 = 0x0020000,
CTS_U16 = 0x0040000,
CTS_X32 = 0x0080000,
CTS_S32 = 0x0100000,
CTS_U32 = 0x0200000,
CTS_X64 = 0x0400000,
CTS_S64 = 0x0800000,
CTS_U64 = 0x1000000,
CTS_MASK = 0x1FFF000
}
The possible cell types (in the ravel of an APL value)
enum Col_flags {
has_j = 0x0100,
real_has_E = 0x0200,
imag_has_E = 0x0400
}
flags of a line to be printed. These flags extend CellType
enum ListCategory {
LIST_NONE = 0,
LIST_VARS = 0x01,
LIST_FUNS = 0x02,
LIST_OPERS = 0x04,
LIST_LABELS = 0x08,
LIST_ERASED = 0x10,
LIST_INVALID = 0x20,
LIST_UNUSED = 0x40,
LIST_NAMES,
LIST_ALL = 0xFFFFFFFF
}
What to list, used by)SYMBOLS,)VARS, and)FUNS.
enum ValueFlags {
VF_NONE = 0x0000,
VF_complete = 0x0400,
VF_marked = 0x0800,
VF_temp = 0x1000,
VF_member = 0x2000,
VF_packed = 0x4000
}
possible properties of a Value.
enum VH_event {
VHE_None = 0,
VHE_Create,
VHE_Unroll,
VHE_Check,
VHE_SetFlag,
VHE_ClearFlag,
VHE_Erase,
VHE_Destruct,
VHE_Error,
VHE_PtrNew,
VHE_PtrNew0,
VHE_PtrCopy1,
VHE_PtrCopy2,
VHE_PtrCopy3,
VHE_PtrClr,
VHE_PtrDel,
VHE_PtrDel0,
VHE_TokCopy1,
VHE_TokMove1,
VHE_TokMove2,
VHE_Completed,
VHE_Stale,
VHE_Visit
}
events for APL values
enum Bitmask {
BIT_0 = 1 << 0,
BIT_1 = 1 << 1,
BIT_2 = 1 << 2,
BIT_3 = 1 << 3,
BIT_4 = 1 << 4,
BIT_5 = 1 << 5,
BIT_6 = 1 << 6,
BIT_7 = 1 << 7,
BIT_8 = 1 << 8,
BIT_9 = 1 << 9,
BIT_10 = 1 << 10,
BIT_11 = 1 << 11,
BIT_12 = 1 << 12,
BIT_13 = 1 << 13,
BIT_14 = 1 << 14,
BIT_15 = 1 << 15,
BIT_16 = 1 << 16,
BIT_17 = 1 << 17,
BIT_18 = 1 << 18,
BIT_19 = 1 << 19,
BIT_20 = 1 << 20,
BIT_21 = 1 << 21,
BIT_22 = 1 << 22,
BIT_23 = 1 << 23,
BIT_24 = 1 << 24,
BIT_25 = 1 << 25,
BIT_26 = 1 << 26,
BIT_27 = 1 << 27,
BIT_28 = 1 << 28,
BIT_29 = 1 << 29,
BIT_30 = 1 << 30,
BIT_31 = 1 << 31
}
The bits in an int.
enum Function_Line {
Function_Retry = -2,
Function_Line_0 = 0,
Function_Line_1 = 1,
Function_Line_10 = 10
}
the line number of an APL function line (0 being the line to return from the function).
enum ParseMode {
PM_FUNCTION = 0,
PM_STATEMENT_LIST = 1,
PM_EXECUTE = 2
}
What is being parsed (function, immediate execution statements, or ⍎expr)
enum PrintStyle {
PST_NONE = 0,
PST_CS_NONE = 0x00000000,
PST_CS_ASCII = 0x00000001,
PST_CS_THIN = 0x00000002,
PST_CS_THICK = 0x00000003,
PST_CS_DOUBLE = 0x00000004,
PST_CS_MASK = 0x0000000F,
PST_CS_INNER = PST_CS_MASK,
PST_CS_OUTER = PST_CS_MASK << 4,
PST_SCALED = 0x00000100,
PST_NO_EXPO_0 = 0x00000200,
PST_NO_FRACT_0 = 0x00000400,
PST_EMPTY_LAST = 0x00000800,
PST_EMPTY_NLAST = 0x00001000,
PST_MATRIX = 0x00010000,
PST_INPUT = 0x00020000,
PST_PACKED = 0x00040000,
PST_NARS = 0x00080000,
PST_QUOTE_CHARS = 0x00100000,
PST_PRETTY = 0x00200000,
PR_APL = PST_MATRIX,
PR_APL_MIN,
PR_APL_FUN = PST_INPUT,
PR_Quad = PST_INPUT,
PR_QUOTE_Quad = PST_NONE,
PR_BOXED_CHAR,
PR_BOXED_GRAPHIC,
PR_BOXED_GRAPHIC1,
PR_BOXED_GRAPHIC2,
PR_BOXED_GRAPHIC3,
PR_NARS = PR_BOXED_GRAPHIC | PST_NARS,
PR_NARS1 = PR_BOXED_GRAPHIC1 | PST_NARS,
PR_NARS2 = PR_BOXED_GRAPHIC2 | PST_NARS
}
Different ways of printing APL values.
enum Function_PC {
Function_PC_0 = 0,
Function_PC_done = -1,
Function_PC_invalid = -1
}
an offset into the body of a user-defined function. If we consider the APL interpreter as a high-level machine that executes token in user defined functions then this offset is the "program counter" of the high-level machine.
enum Fun_signature {
SIG_NONE = 0,
SIG_Z = 0x01,
SIG_A = 0x02,
SIG_LO = 0x04,
SIG_FUN = 0x08,
SIG_RO = 0x10,
SIG_X = 0x20,
SIG_B = 0x40,
SIG_FUN_X = SIG_FUN | SIG_X,
SIG_OP1 = SIG_LO | SIG_FUN,
SIG_OP1_X = SIG_OP1 | SIG_X,
SIG_OP2 = SIG_OP1 | SIG_RO,
SIG_LORO = SIG_LO | SIG_RO,
SIG_NIL = SIG_NONE,
SIG_MON = SIG_B,
SIG_DYA = SIG_A | SIG_B,
SIG_F0 = SIG_FUN | SIG_NIL,
SIG_Z_F0 = SIG_Z | SIG_F0,
SIG_F1_B = SIG_MON | SIG_FUN,
SIG_F1_X_B = SIG_MON | SIG_FUN_X,
SIG_LO_OP1_B = SIG_MON | SIG_OP1,
SIG_LO_OP1_X_B = SIG_MON | SIG_OP1_X,
SIG_LO_OP2_RO_B = SIG_MON | SIG_OP2,
SIG_Z_F1_B = SIG_Z | SIG_F1_B,
SIG_Z_F1_X_B = SIG_Z | SIG_F1_X_B,
SIG_Z_LO_OP1_B = SIG_Z | SIG_LO_OP1_B,
SIG_Z_LO_OP1_X_B = SIG_Z | SIG_LO_OP1_X_B,
SIG_Z_LO_OP2_RO_B = SIG_Z | SIG_LO_OP2_RO_B,
SIG_A_F2_B = SIG_DYA | SIG_FUN,
SIG_A_F2_X_B = SIG_DYA | SIG_FUN_X,
SIG_A_LO_OP1_B = SIG_DYA | SIG_OP1,
SIG_A_LO_OP1_X_B = SIG_DYA | SIG_OP1_X,
SIG_A_LO_OP2_RO_B = SIG_DYA | SIG_OP2,
SIG_Z_A_F2_B = SIG_Z | SIG_A_F2_B,
SIG_Z_A_F2_X_B = SIG_Z | SIG_A_F2_X_B,
SIG_Z_A_LO_OP1_B = SIG_Z | SIG_A_LO_OP1_B,
SIG_Z_A_LO_OP1_X_B = SIG_Z | SIG_A_LO_OP1_X_B,
SIG_Z_A_LO_OP2_RO_B = SIG_Z | SIG_A_LO_OP2_RO_B
}
signature of a user defined function
enum SI_mode {
SIM_none = 0x00,
SIM_debug = 0x01,
SIM_statements = 0x02,
SIM_name_list = 0x04,
SIM_SI = SIM_none,
SIM_SIS = SIM_statements,
SIM_SINL = SIM_name_list,
SIM_SI_dbg = SIM_debug,
SIM_SIS_dbg = SIM_debug | SIM_statements
}
the mode that distinguishes different SI commands (SI, SIS, SINL, ]SI, ]SIS)
enum CoreCount {
CCNT_UNKNOWN = -1,
CCNT_0 = 0,
CCNT_1 = 1,
CCNT_UNKNOWN = -1,
CCNT_MIN = 1
}
the number of cores/tasks to be used
enum CoreNumber {
CNUM_INVALID = -1,
CNUM_MASTER = 0,
CNUM_WORKER1 = 1
}
the cores/tasks to be used
enum CPU_Number { CPU_0 = 0 }
the CPUs reported by the OS
enum CPU_count { CPU_CNT_1 = 1 }
the number of CPUs available
enum Assign_state {
ASS_none = 0,
ASS_arrow_seen = 1,
ASS_var_seen = 2
}
the state of an assignment
enum Cause {
NO_CAUSE = 0,
CAUSE_SHUTDOWN = 1,
CAUSE_ERASED = 2
}
the cause for something
enum CDR_type {
CDR_BOOL1 = 0,
CDR_INT32 = 1,
CDR_FLT64 = 2,
CDR_CPLX128 = 3,
CDR_CHAR8 = 4,
CDR_CHAR32 = 5,
CDR_PROG64 = 6,
CDR_NEST32 = 7
}
the CDR data types
enum Comp_result {
COMP_LT = -1,
COMP_EQ = 0,
COMP_GT = 1
}
the result of a comparison cell_1.compare(cell_2)
enum Sort_order {
SORT_DESCENDING = 0,
SORT_ASCENDING = 1
}
the order of a comparison
enum Symbol_Event {
SEV_CREATED = 1,
SEV_PUSHED = 2,
SEV_POPED = 3,
SEV_ASSIGNED = 4,
SEV_ERASED = 5
}
events for a symbol
enum AP_num {
NO_AP = -1,
AP_NULL = 0,
AP_GENERAL = 0,
AP_INTERPRETER = 1000,
AP_FIRST_USER = 1001
}
Auxiliary processor numbers.
enum { APL_PATH_MAX = 4096 }
longest filename
Functions
void Hswap (APL_Integer &i1, APL_Integer &i2)
ostream & print_flags (ostream &out, ValueFlags flags)
Macro Definition Documentation
APL_Float_is_class
#define APL_Float_is_class 0
Definition at line 39 of file APL_types.hh.
complex_exponent
#define complex_exponent (x) exp(x)
Definition at line 93 of file APL_types.hh.
complex_power
#define complex_power (x, y) pow((x), (y))
Definition at line 94 of file APL_types.hh.
complex_sqrt
#define complex_sqrt (x) sqrt(x)
Definition at line 95 of file APL_types.hh.
release_APL_Float
#define release_APL_Float (x)
Definition at line 96 of file APL_types.hh.
Referenced by FloatCell::dfval(), FloatCell::FloatCell(), and Hswap().
Typedef Documentation
APL_Char
typedef Unicode APL_Char
One APL character value.
Definition at line 63 of file APL_types.hh.
APL_Complex
typedef complex<APL_Float> APL_Complex
One APL complex value.
Definition at line 102 of file APL_types.hh.
APL_Float
typedef APL_Float_Base APL_Float
Definition at line 91 of file APL_types.hh.
APL_Float_Base
typedef double APL_Float_Base
One (real) APL floating point value.
Definition at line 90 of file APL_types.hh.
APL_Integer
typedef int64_t APL_Integer
One APL integer value.
Definition at line 66 of file APL_types.hh.
APL_time_us
typedef int64_t APL_time_us
APL time = microseconds since Jan. 1. 1970 00:00:00 UTC.
Definition at line 105 of file APL_types.hh.
AxesBitmap
typedef uint16_t AxesBitmap
A bitmap for axes (in fun[X] arguments) normalized to ⎕IO←0.
Definition at line 54 of file APL_types.hh.
Function_P
typedef const Function* Function_P
Definition at line 74 of file APL_types.hh.
long_long
typedef long long long_long
long long for sprintf() and friends
Definition at line 69 of file APL_types.hh.
sAxis
typedef sRank sAxis
Definition at line 47 of file APL_types.hh.
ShapeItem
typedef int64_t ShapeItem
One dimension length (axis length) of an APL shape.
Definition at line 57 of file APL_types.hh.
SI_level
typedef int SI_level
The SI level, 0 = global (oldest), caller at level N called function at N+1.
Definition at line 60 of file APL_types.hh.
sRank
typedef int16_t sRank
The (signed) rank of an APL value.
Definition at line 46 of file APL_types.hh.
uAxis
typedef uRank uAxis
Definition at line 51 of file APL_types.hh.
unsigned_long
typedef unsigned long unsigned_long
unsigned long for sprintf() and friends
Definition at line 72 of file APL_types.hh.
uRank
typedef uint32_t uRank
The (unsigned) rank of an APL value.
Definition at line 50 of file APL_types.hh.
Enumeration Type Documentation
anonymous enum
anonymous enum
longest filename
Enumerator
APL_PATH_MAX
Definition at line 513 of file APL_types.hh.
AP_num
enum AP_num
Auxiliary processor numbers.
Enumerator
NO_AP
invalid AP
AP_NULL
invalid AP for structs using memset(0)
AP_GENERAL
AP for generic offers.
AP_INTERPRETER
the AP for the APL interpreters
AP_FIRST_USER
the first AP for APL users
Definition at line 503 of file APL_types.hh.
Assign_state
enum Assign_state
the state of an assignment
Enumerator
ASS_none
no assignment (right of ←)
ASS_arrow_seen
← seen but no variable yet
ASS_var_seen
var and ← seen
Definition at line 449 of file APL_types.hh.
Bitmask
enum Bitmask
The bits in an int.
Enumerator
BIT_0
< dito.
BIT_1
< dito.
BIT_2
< dito.
BIT_3
< dito.
BIT_4
< dito.
BIT_5
< dito.
BIT_6
< dito.
BIT_7
< dito.
BIT_8
< dito.
BIT_9
< dito.
BIT_10
< dito.
BIT_11
< dito.
BIT_12
< dito.
BIT_13
< dito.
BIT_14
< dito.
BIT_15
< dito.
BIT_16
< dito.
BIT_17
< dito.
BIT_18
< dito.
BIT_19
< dito.
BIT_20
< dito.
BIT_21
< dito.
BIT_22
< dito.
BIT_23
< dito.
BIT_24
< dito.
BIT_25
< dito.
BIT_26
< dito.
BIT_27
< dito.
BIT_28
< dito.
BIT_29
< dito.
BIT_30
< dito.
BIT_31
< dito.
Definition at line 216 of file APL_types.hh.
Cause
enum Cause
the cause for something
Enumerator
NO_CAUSE
CAUSE_SHUTDOWN
CAUSE_ERASED
Definition at line 457 of file APL_types.hh.
CDR_type
enum CDR_type
the CDR data types
Enumerator
CDR_BOOL1
1 bit boolean
CDR_INT32
32 bit integer
CDR_FLT64
64 bit double
CDR_CPLX128
2*64 bit complex
CDR_CHAR8
8 bit char
CDR_CHAR32
32 bit char
CDR_PROG64
2*32 bit progression vector
CDR_NEST32
32 bit pointer to nested value
Definition at line 465 of file APL_types.hh.
CellType
enum CellType
The possible cell types (in the ravel of an APL value)
Enumerator
CT_NONE
CT_BASE
CT_CHAR
CT_POINTER
CT_CELLREF
CT_INT
CT_FLOAT
CT_COMPLEX
CT_NUMERIC
CT_SIMPLE
CT_MASK
CTS_BIT
1-bit integer
CTS_X8
signed or unsigned 8-bit integer or char
CTS_S8
signed 8-bit integer or char
CTS_U8
unsigned 8-bit integer or char
CTS_X16
signed or unsigned 16-bit integer or char
CTS_S16
signed 16-bit integer or char
CTS_U16
unsigned 16-bit integer or char
CTS_X32
signed or unsigned 32-bit integer or char
CTS_S32
signed 32-bit integer or char
CTS_U32
unsigned 32-bit integer or char
CTS_X64
signed or unsigned 64-bit integer
CTS_S64
signed 64-bit integer
CTS_U64
unsigned 64-bit integer
CTS_MASK
Definition at line 116 of file APL_types.hh.
Col_flags
enum Col_flags
flags of a line to be printed. These flags extend CellType
Enumerator
has_j
real_has_E
imag_has_E
Definition at line 149 of file APL_types.hh.
Comp_result
enum Comp_result
the result of a comparison cell_1.compare(cell_2)
Enumerator
COMP_LT
less than: cell_1 < cell_2
COMP_EQ
equal: cell_1 = cell_2
COMP_GT
greater than: cell_1 > cell_2
Definition at line 478 of file APL_types.hh.
CoreCount
enum CoreCount
the number of cores/tasks to be used
Enumerator
CCNT_UNKNOWN
unknown core count
CCNT_0
< no core
CCNT_1
one core ...
CCNT_UNKNOWN
CCNT_MIN
Definition at line 421 of file APL_types.hh.
CoreNumber
enum CoreNumber
the cores/tasks to be used
Enumerator
CNUM_INVALID
invalid core
CNUM_MASTER
the interpreter core
CNUM_WORKER1
the first worker core ...
Definition at line 429 of file APL_types.hh.
CPU_count
enum CPU_count
the number of CPUs available
Enumerator
CPU_CNT_1
one CPU
Definition at line 443 of file APL_types.hh.
CPU_Number
enum CPU_Number
the CPUs reported by the OS
Enumerator
CPU_0
the first (only) CPU
Definition at line 437 of file APL_types.hh.
Fun_signature
enum Fun_signature
signature of a user defined function
Enumerator
SIG_NONE
SIG_Z
function has a result
SIG_A
function has a left argument
SIG_LO
operator left operand
SIG_FUN
function (always set)
SIG_RO
operator right operand
SIG_X
RO has an axis.
SIG_B
function has a right argument
SIG_FUN_X
function with axis
SIG_OP1
monadic operator
SIG_OP1_X
monadic operator with axis
SIG_OP2
dyadic operator
SIG_LORO
monadic or dyadic operator
SIG_NIL
niladic function
SIG_MON
monadic function or operator
SIG_DYA
dyadic function or operator
SIG_F0
dito
SIG_Z_F0
dito
SIG_F1_B
dito
SIG_F1_X_B
dito
SIG_LO_OP1_B
dito
SIG_LO_OP1_X_B
dito
SIG_LO_OP2_RO_B
dito
SIG_Z_F1_B
dito
SIG_Z_F1_X_B
dito
SIG_Z_LO_OP1_B
dito
SIG_Z_LO_OP1_X_B
dito
SIG_Z_LO_OP2_RO_B
dito
SIG_A_F2_B
dito
SIG_A_F2_X_B
dito
SIG_A_LO_OP1_B
dito
SIG_A_LO_OP1_X_B
dito
SIG_A_LO_OP2_RO_B
dito
SIG_Z_A_F2_B
dito
SIG_Z_A_F2_X_B
dito
SIG_Z_A_LO_OP1_B
dito
SIG_Z_A_LO_OP1_X_B
dito
SIG_Z_A_LO_OP2_RO_B
dito
Definition at line 342 of file APL_types.hh.
Function_Line
enum Function_Line
the line number of an APL function line (0 being the line to return from the function).
Enumerator
Function_Retry
Function_Line_0
Function_Line_1
Function_Line_10
Definition at line 254 of file APL_types.hh.
Function_PC
enum Function_PC
an offset into the body of a user-defined function. If we consider the APL interpreter as a high-level machine that executes token in user defined functions then this offset is the "program counter" of the high-level machine.
Enumerator
Function_PC_0
the first token in a function
Function_PC_done
goto 0
Function_PC_invalid
dito
Definition at line 334 of file APL_types.hh.
ListCategory
enum ListCategory
What to list, used by)SYMBOLS,)VARS, and)FUNS.
Enumerator
LIST_NONE
list nothing
LIST_VARS
list variables for)VARS
LIST_FUNS
list functions for)FNS
LIST_OPERS
list operators for)OPS
LIST_LABELS
list labels
LIST_ERASED
list erased symbols
LIST_INVALID
list invalid symbols
LIST_UNUSED
list unused symbols
LIST_NAMES
list names for)NMS
LIST_ALL
list everything
Definition at line 157 of file APL_types.hh.
ParseMode
enum ParseMode
What is being parsed (function, immediate execution statements, or ⍎expr)
Enumerator
PM_FUNCTION
function execution
PM_STATEMENT_LIST
immediate execution
PM_EXECUTE
execute (⍎)
Definition at line 263 of file APL_types.hh.
PrintStyle
enum PrintStyle
Different ways of printing APL values.
Enumerator
PST_NONE
nothing
PST_CS_NONE
ASCII chars (- | and +)
PST_CS_ASCII
ASCII chars (- | and +)
PST_CS_THIN
thin lines
PST_CS_THICK
thick lines
PST_CS_DOUBLE
double lines
PST_CS_MASK
mask for line style
PST_CS_INNER
mask for inner line style
PST_CS_OUTER
mask for outer line style
PST_SCALED
use exponential form
PST_NO_EXPO_0
remove E0
PST_NO_FRACT_0
remove trailing fractional 0s
PST_EMPTY_LAST
last axis is empty
PST_EMPTY_NLAST
some non-last axis is empty
PST_MATRIX
multi line output
PST_INPUT
use '' for chars and () for nested
PST_PACKED
4 byte/char
PST_NARS
NARS APL ⎕FMT style.
PST_QUOTE_CHARS
quote chars and strings
PST_PRETTY
print control characters nicely
PR_APL
normal APL output
PR_APL_MIN
normal APL output w/o E0 and ...0
PR_APL_FUN
⎕CR function
PR_Quad
⎕ output
PR_QUOTE_Quad
⍞ output
PR_BOXED_CHAR
2 ⎕CR (ASCII chars)
PR_BOXED_GRAPHIC
3/4 ⎕CR (graphic characters)
PR_BOXED_GRAPHIC1
7/8 ⎕CR (graphic characters)
PR_BOXED_GRAPHIC2
DISPLAY graphic in double box.
PR_BOXED_GRAPHIC3
29 ⎕CR (quoted chars)
PR_NARS
NARS APL style.
PR_NARS1
NARS APL style,.
PR_NARS2
NARS APL style,.
Definition at line 271 of file APL_types.hh.
SI_mode
enum SI_mode
the mode that distinguishes different SI commands (SI, SIS, SINL, ]SI, ]SIS)
Enumerator
SIM_none
)SI
SIM_debug
]SI and ]SIS
SIM_statements
)SIS and ]SIS
SIM_name_list
)SINL
SIM_SI
SIM_SIS
SIM_SINL
SIM_SI_dbg
SIM_SIS_dbg
Definition at line 407 of file APL_types.hh.
Sort_order
enum Sort_order
the order of a comparison
Enumerator
SORT_DESCENDING
sort descending
SORT_ASCENDING
sort asscending
Definition at line 486 of file APL_types.hh.
Symbol_Event
enum Symbol_Event
events for a symbol
Enumerator
SEV_CREATED
SEV_PUSHED
SEV_POPED
SEV_ASSIGNED
SEV_ERASED
Definition at line 493 of file APL_types.hh.
ValueFlags
enum ValueFlags
possible properties of a Value.
Enumerator
VF_NONE
no flags
VF_complete
CHECK called.
VF_marked
marked to detect stale
VF_temp
computed value
VF_member
used for member access
VF_packed
packed homogenious ravel
Definition at line 174 of file APL_types.hh.
VH_event
enum VH_event
events for APL values
Enumerator
VHE_None
no event
VHE_Create
value created (shape is complete, ravel is not)
VHE_Unroll
rollback creation
VHE_Check
check function called (if enabled)
VHE_SetFlag
set a value flag
VHE_ClearFlag
clear a value flag
VHE_Erase
erase the value
VHE_Destruct
destruct the value
VHE_Error
some APL error has occurred
VHE_PtrNew
new Value_P created
VHE_PtrNew0
new Value_P with 0-pointer created
VHE_PtrCopy1
Value_P copied with constructor(Value_P)
VHE_PtrCopy2
Value_P copied with constructor(Value_P, loc)
VHE_PtrCopy3
Value_P copied with operator =()
VHE_PtrClr
Value_P cleared.
VHE_PtrDel
Value_P deleted.
VHE_PtrDel0
Value_P deleted (with 0 pointer)
VHE_TokCopy1
token with Value_P copied
VHE_TokMove1
token with Value_P moved
VHE_TokMove2
token with Value_P moved
VHE_Completed
incomplete ravel set to 42424242
VHE_Stale
stale value erased
VHE_Visit
test point
Definition at line 188 of file APL_types.hh.
Function Documentation
Hswap()
void Hswap (APL_Integer & i1, APL_Integer & i2) inline
Definition at line 78 of file APL_types.hh.
References release_APL_Float.
Referenced by Heapsort< T >::make_heap(), Executable::reverse_all_token(), and Heapsort< T >::sort().
print_flags()
ostream& print_flags (ostream & out, ValueFlags flags)
Definition at line 287 of file Common.cc.
References VF_complete, and VF_marked.
Referenced by operator<<(), and Symbol::push_value().