GNUAPL: src/APL_Float_as_class.hh File Reference
APL_Float_as_class.hh File Reference
Classes
class APL_Float_Base
the essential data of an APL_Float, so that it can be used in a union
class APL_Float
a non-rational APL floating point value
Macros
#define wrap1(type, fun)
#define wrap2(type, fun)
double fun(double, double) -> APL_Float fun(const APL_Float_Base &, const APL_Float_Base &)
#define op_wrap2(type, oper)
double operator(double, double) -> APL_Float operator (const APL_Float_Base &, const APL_Float_Base &)
#define assop_wrap1(op)
double operator(double, double) -> APL_Float_Base & operator (const APL_Float_Base &, const APL_Float_Base &)
Functions
bool isnormal (const APL_Float &val)
isnormal() for APL_Float
double abs (const APL_Float_Base &d)
double acos (const APL_Float_Base &d)
double asin (const APL_Float_Base &d)
double asinh (const APL_Float_Base &d)
double atan (const APL_Float_Base &d)
double ceil (const APL_Float_Base &d)
double cos (const APL_Float_Base &d)
double cosh (const APL_Float_Base &d)
double acosh (const APL_Float_Base &d)
double exp (const APL_Float_Base &d)
double floor (const APL_Float_Base &d)
double isfinite (const APL_Float_Base &d)
double log (const APL_Float_Base &d)
double round (const APL_Float_Base &d)
double sqrt (const APL_Float_Base &d)
double sin (const APL_Float_Base &d)
double sinh (const APL_Float_Base &d)
double tan (const APL_Float_Base &d)
double tgamma (const APL_Float_Base &d)
double tanh (const APL_Float_Base &d)
double atan2 (const APL_Float_Base &d, const APL_Float_Base &e)
double atan2 (const APL_Float_Base &d, double e)
double atan2 (double d, const APL_Float_Base &e)
double fmod (const APL_Float_Base &d, const APL_Float_Base &e)
double fmod (const APL_Float_Base &d, double e)
double fmod (double d, const APL_Float_Base &e)
double pow (const APL_Float_Base &d, const APL_Float_Base &e)
double pow (const APL_Float_Base &d, double e)
double pow (double d, const APL_Float_Base &e)
APL_Float operator- (const APL_Float_Base &d)
double operator+ (const APL_Float_Base &d, const APL_Float_Base &e)
double operator+ (const APL_Float_Base &d, double e)
double operator+ (const APL_Float_Base &d, APL_Integer e)
double operator+ (const APL_Float_Base &d, uint64_t e)
double operator+ (double d, const APL_Float_Base &e)
double operator+ (APL_Integer d, const APL_Float_Base &e)
double operator+ (int d, const APL_Float_Base &e)
double operator- (const APL_Float_Base &d, const APL_Float_Base &e)
double operator- (const APL_Float_Base &d, double e)
double operator- (const APL_Float_Base &d, APL_Integer e)
double operator- (const APL_Float_Base &d, uint64_t e)
double operator- (double d, const APL_Float_Base &e)
double operator- (APL_Integer d, const APL_Float_Base &e)
double operator- (int d, const APL_Float_Base &e)
double operator* (const APL_Float_Base &d, const APL_Float_Base &e)
double operator* (const APL_Float_Base &d, double e)
double operator* (const APL_Float_Base &d, APL_Integer e)
double operator* (const APL_Float_Base &d, uint64_t e)
double operator* (double d, const APL_Float_Base &e)
double operator* (APL_Integer d, const APL_Float_Base &e)
double operator* (int d, const APL_Float_Base &e)
double operator/ (const APL_Float_Base &d, const APL_Float_Base &e)
double operator/ (const APL_Float_Base &d, double e)
double operator/ (const APL_Float_Base &d, APL_Integer e)
double operator/ (const APL_Float_Base &d, uint64_t e)
double operator/ (double d, const APL_Float_Base &e)
double operator/ (APL_Integer d, const APL_Float_Base &e)
double operator/ (int d, const APL_Float_Base &e)
bool operator< (const APL_Float_Base &d, const APL_Float_Base &e)
bool operator< (const APL_Float_Base &d, double e)
bool operator< (const APL_Float_Base &d, APL_Integer e)
bool operator< (const APL_Float_Base &d, uint64_t e)
bool operator< (double d, const APL_Float_Base &e)
bool operator< (APL_Integer d, const APL_Float_Base &e)
bool operator< (int d, const APL_Float_Base &e)
bool operator> (const APL_Float_Base &d, const APL_Float_Base &e)
bool operator> (const APL_Float_Base &d, double e)
bool operator> (const APL_Float_Base &d, APL_Integer e)
bool operator> (const APL_Float_Base &d, uint64_t e)
bool operator> (double d, const APL_Float_Base &e)
bool operator> (APL_Integer d, const APL_Float_Base &e)
bool operator> (int d, const APL_Float_Base &e)
bool operator<= (const APL_Float_Base &d, const APL_Float_Base &e)
bool operator<= (const APL_Float_Base &d, double e)
bool operator<= (const APL_Float_Base &d, APL_Integer e)
bool operator<= (const APL_Float_Base &d, uint64_t e)
bool operator<= (double d, const APL_Float_Base &e)
bool operator<= (APL_Integer d, const APL_Float_Base &e)
bool operator<= (int d, const APL_Float_Base &e)
bool operator>= (const APL_Float_Base &d, const APL_Float_Base &e)
bool operator>= (const APL_Float_Base &d, double e)
bool operator>= (const APL_Float_Base &d, APL_Integer e)
bool operator>= (const APL_Float_Base &d, uint64_t e)
bool operator>= (double d, const APL_Float_Base &e)
bool operator>= (APL_Integer d, const APL_Float_Base &e)
bool operator>= (int d, const APL_Float_Base &e)
bool operator== (const APL_Float_Base &d, const APL_Float_Base &e)
bool operator== (const APL_Float_Base &d, double e)
bool operator== (const APL_Float_Base &d, APL_Integer e)
bool operator== (const APL_Float_Base &d, uint64_t e)
bool operator== (double d, const APL_Float_Base &e)
bool operator== (APL_Integer d, const APL_Float_Base &e)
bool operator== (int d, const APL_Float_Base &e)
bool operator!= (const APL_Float_Base &d, const APL_Float_Base &e)
bool operator!= (const APL_Float_Base &d, double e)
bool operator!= (const APL_Float_Base &d, APL_Integer e)
bool operator!= (const APL_Float_Base &d, uint64_t e)
bool operator!= (double d, const APL_Float_Base &e)
bool operator!= (APL_Integer d, const APL_Float_Base &e)
bool operator!= (int d, const APL_Float_Base &e)
APL_Float_Base & operator+= (APL_Float_Base &d, const APL_Float_Base &e)
APL_Float_Base & operator+= (APL_Float_Base &d, double e)
APL_Float_Base & operator-= (APL_Float_Base &d, const APL_Float_Base &e)
APL_Float_Base & operator-= (APL_Float_Base &d, double e)
APL_Float_Base & operator*= (APL_Float_Base &d, const APL_Float_Base &e)
APL_Float_Base & operator*= (APL_Float_Base &d, double e)
APL_Float_Base & operator/= (APL_Float_Base &d, const APL_Float_Base &e)
APL_Float_Base & operator/= (APL_Float_Base &d, double e)
complex< APL_Float > complex_sqrt (complex< APL_Float > x)
complex< APL_Float > complex_exponent (complex< APL_Float > x)
complex< APL_Float > complex_power (complex< APL_Float > x, complex< APL_Float > y)
Macro Definition Documentation
assop_wrap1
#define assop_wrap1 (op)
Value:
inline APL_Float_Base & operator op ## =(APL_Float_Base & d,           \
                                         const APL_Float_Base & e)     \
   { return d._set(d._get() op e._get()); }                            \
inline APL_Float_Base & operator op ## =(APL_Float_Base & d, double e) \
   { return d._set(d._get() op e); }
double operator(double, double) -> APL_Float_Base & operator (const APL_Float_Base &, const APL_Float_Base &)
Definition at line 218 of file APL_Float_as_class.hh.
op_wrap2
#define op_wrap2 (type, oper)
Value:
inline type operator oper(const APL_Float_Base & d,                     \
                          const APL_Float_Base & e)                     \
   { return type(double(d._get()) oper                                  \
                 double(e._get())); }                                   \
inline type operator oper(const APL_Float_Base & d, double e)           \
   { return type(double(d._get()) oper e); }                            \
inline type operator oper(const APL_Float_Base & d, APL_Integer e)      \
   { return type(double(d._get()) oper e); }                            \
inline type operator oper(const APL_Float_Base & d, uint64_t e)         \
   { return type(double(d._get()) oper e); }                            \
inline type operator oper(double d, const APL_Float_Base & e)           \
   { return type(d oper double(e._get())); }                            \
inline type operator oper(APL_Integer d, const APL_Float_Base & e)      \
   { return type(d oper double(e._get())); }                            \
inline type operator oper(int d, const APL_Float_Base & e)              \
   { return type(d oper double(e._get())); }
double operator(double, double) -> APL_Float operator (const APL_Float_Base &, const APL_Float_Base &)
Definition at line 198 of file APL_Float_as_class.hh.
wrap1
#define wrap1 (type, fun)
Value:
inline type fun(const APL_Float_Base & d)                               \
   { return type(fun(double(d._get()))); }
Definition at line 181 of file APL_Float_as_class.hh.
wrap2
#define wrap2 (type, fun)
Value:
inline type fun(const APL_Float_Base & d, const APL_Float_Base & e)     \
   { return type(fun(double(d._get()),                                  \
                     double(e._get()))); }                              \
inline type fun(const APL_Float_Base & d, double e)                     \
   { return type(fun(double(d._get()), e)); }                           \
inline type fun(double d, const APL_Float_Base & e)                     \
   { return type(fun(d, double(e._get()))); }
double fun(double, double) -> APL_Float fun(const APL_Float_Base &, const APL_Float_Base &)
Definition at line 187 of file APL_Float_as_class.hh.
Function Documentation
abs()
double abs (const APL_Float_Base & d) inline
Definition at line 226 of file APL_Float_as_class.hh.
Referenced by ComplexCell::bif_direction(), ComplexCell::bif_magnitude(), NumericCell::cpx_gcd(), and Bif_F12_DOMINO::Matrix< cplx >::significant().
acos()
double acos (const APL_Float_Base & d) inline
Definition at line 227 of file APL_Float_as_class.hh.
Referenced by RealCell::do_bif_circle_fun().
acosh()
double acosh (const APL_Float_Base & d) inline
Definition at line 234 of file APL_Float_as_class.hh.
Referenced by RealCell::do_bif_circle_fun().
asin()
double asin (const APL_Float_Base & d) inline
Definition at line 228 of file APL_Float_as_class.hh.
Referenced by RealCell::do_bif_circle_fun().
asinh()
double asinh (const APL_Float_Base & d) inline
Definition at line 229 of file APL_Float_as_class.hh.
Referenced by RealCell::do_bif_circle_fun().
atan()
double atan (const APL_Float_Base & d) inline
Definition at line 230 of file APL_Float_as_class.hh.
Referenced by RealCell::do_bif_circle_fun().
atan2() [1/3]
double atan2 (const APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 248 of file APL_Float_as_class.hh.
Referenced by ComplexCell::do_bif_circle_fun(), and Plot_window_properties::valXYZ2pixelXY().
atan2() [2/3]
double atan2 (const APL_Float_Base & d, double e) inline
Definition at line 248 of file APL_Float_as_class.hh.
atan2() [3/3]
double atan2 (double d, const APL_Float_Base & e) inline
Definition at line 248 of file APL_Float_as_class.hh.
ceil()
double ceil (const APL_Float_Base & d) inline
Definition at line 231 of file APL_Float_as_class.hh.
Referenced by ComplexCell::bif_ceiling(), IntCell::bif_residue(), ComplexCell::bif_within_quad_CT(), FloatCell::bif_within_quad_CT(), and Plot_window_properties::update().
complex_exponent()
complex<APL_Float> complex_exponent (complex< APL_Float > x) inline
Definition at line 286 of file APL_Float_as_class.hh.
References exp().
Referenced by ComplexCell::bif_exponential(), and ComplexCell::gamma().
complex_power()
complex<APL_Float> complex_power (complex< APL_Float > x, complex< APL_Float > y) inline
Definition at line 294 of file APL_Float_as_class.hh.
References pow().
Referenced by IntCell::bif_power(), ComplexCell::bif_power(), FloatCell::bif_power(), and ComplexCell::gamma().
complex_sqrt()
complex<APL_Float> complex_sqrt (complex< APL_Float > x) inline
Definition at line 278 of file APL_Float_as_class.hh.
References sqrt().
Referenced by ComplexCell::do_bif_circle_fun(), and ComplexCell::gamma().
cos()
double cos (const APL_Float_Base & d) inline
Definition at line 232 of file APL_Float_as_class.hh.
Referenced by Quad_FFT::blackman_harris_window(), Quad_FFT::blackman_nuttall_window(), Quad_FFT::blackman_window(), RealCell::do_bif_circle_fun(), ComplexCell::do_bif_circle_fun(), Quad_FFT::flat_top(), Quad_FFT::hamming_window(), Quad_FFT::hann_window(), Tokenizer::tokenize_number(), and Plot_window_properties::valXYZ2pixelXY().
cosh()
double cosh (const APL_Float_Base & d) inline
Definition at line 233 of file APL_Float_as_class.hh.
Referenced by RealCell::do_bif_circle_fun(), and ComplexCell::do_bif_circle_fun().
exp()
double exp (const APL_Float_Base & d) inline
Definition at line 235 of file APL_Float_as_class.hh.
Referenced by IntCell::bif_exponential(), FloatCell::bif_exponential(), and complex_exponent().
floor()
double floor (const APL_Float_Base & d) inline
Definition at line 236 of file APL_Float_as_class.hh.
Referenced by ComplexCell::bif_floor(), IntCell::bif_residue(), ComplexCell::bif_within_quad_CT(), FloatCell::bif_within_quad_CT(), p_modulo_q(), and Plot_window_properties::update().
fmod() [1/3]
double fmod (double d, const APL_Float_Base & e) inline
Definition at line 249 of file APL_Float_as_class.hh.
fmod() [2/3]
double fmod (const APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 249 of file APL_Float_as_class.hh.
Referenced by NumericCell::flt_gcd().
fmod() [3/3]
double fmod (const APL_Float_Base & d, double e) inline
Definition at line 249 of file APL_Float_as_class.hh.
isfinite()
double isfinite (const APL_Float_Base & d) inline
Definition at line 237 of file APL_Float_as_class.hh.
Referenced by FloatCell::bif_divide(), RealCell::bif_logarithm(), ComplexCell::bif_logarithm(), ComplexCell::bif_multiply(), FloatCell::bif_multiply(), IntCell::bif_power(), ComplexCell::bif_power(), FloatCell::bif_power(), ComplexCell::bif_reciprocal(), FloatCell::bif_reciprocal(), ComplexCell::gamma(), Bif_F12_DOMINO::invert_upper_triangle_matrix(), ComplexCell::is_finite(), FloatCell::is_finite(), p_modulo_q(), Bif_F12_DOMINO::QR_factorization(), and NumericCell::real_binomial().
isnormal()
bool isnormal (const APL_Float & val) inline
isnormal() for APL_Float
Definition at line 155 of file APL_Float_as_class.hh.
References APL_Float_Base::_get().
Referenced by FloatCell::bif_residue(), and UCS_string::UCS_string().
log()
double log (const APL_Float_Base & d) inline
Definition at line 238 of file APL_Float_as_class.hh.
Referenced by RealCell::bif_logarithm(), ComplexCell::bif_logarithm(), ComplexCell::bif_nat_log(), IntCell::bif_nat_log(), FloatCell::bif_nat_log(), ComplexCell::do_bif_circle_fun(), and Svar_record_P::Svar_record_P().
operator!=() [1/7]
bool operator!= (double d, const APL_Float_Base & e) inline
Definition at line 268 of file APL_Float_as_class.hh.
operator!=() [2/7]
bool operator!= (const APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 268 of file APL_Float_as_class.hh.
operator!=() [3/7]
bool operator!= (const APL_Float_Base & d, double e) inline
Definition at line 268 of file APL_Float_as_class.hh.
operator!=() [4/7]
bool operator!= (const APL_Float_Base & d, APL_Integer e) inline
Definition at line 268 of file APL_Float_as_class.hh.
operator!=() [5/7]
bool operator!= (const APL_Float_Base & d, uint64_t e) inline
Definition at line 268 of file APL_Float_as_class.hh.
operator!=() [6/7]
bool operator!= (APL_Integer d, const APL_Float_Base & e) inline
Definition at line 268 of file APL_Float_as_class.hh.
operator!=() [7/7]
bool operator!= (int d, const APL_Float_Base & e) inline
Definition at line 268 of file APL_Float_as_class.hh.
operator*() [1/7]
double operator* (double d, const APL_Float_Base & e) inline
Definition at line 259 of file APL_Float_as_class.hh.
operator*() [2/7]
double operator* (const APL_Float_Base & d, uint64_t e) inline
Definition at line 259 of file APL_Float_as_class.hh.
operator*() [3/7]
double operator* (const APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 259 of file APL_Float_as_class.hh.
operator*() [4/7]
double operator* (const APL_Float_Base & d, double e) inline
Definition at line 259 of file APL_Float_as_class.hh.
operator*() [5/7]
double operator* (const APL_Float_Base & d, APL_Integer e) inline
Definition at line 259 of file APL_Float_as_class.hh.
operator*() [6/7]
double operator* (APL_Integer d, const APL_Float_Base & e) inline
Definition at line 259 of file APL_Float_as_class.hh.
operator*() [7/7]
double operator* (int d, const APL_Float_Base & e) inline
Definition at line 259 of file APL_Float_as_class.hh.
operator*=() [1/2]
APL_Float_Base& operator*= (APL_Float_Base & d, double e) inline
Definition at line 273 of file APL_Float_as_class.hh.
operator*=() [2/2]
APL_Float_Base& operator*= (APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 273 of file APL_Float_as_class.hh.
operator+() [1/7]
double operator+ (const APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 257 of file APL_Float_as_class.hh.
operator+() [2/7]
double operator+ (const APL_Float_Base & d, double e) inline
Definition at line 257 of file APL_Float_as_class.hh.
operator+() [3/7]
double operator+ (const APL_Float_Base & d, APL_Integer e) inline
Definition at line 257 of file APL_Float_as_class.hh.
operator+() [4/7]
double operator+ (const APL_Float_Base & d, uint64_t e) inline
Definition at line 257 of file APL_Float_as_class.hh.
operator+() [5/7]
double operator+ (double d, const APL_Float_Base & e) inline
Definition at line 257 of file APL_Float_as_class.hh.
operator+() [6/7]
double operator+ (APL_Integer d, const APL_Float_Base & e) inline
Definition at line 257 of file APL_Float_as_class.hh.
operator+() [7/7]
double operator+ (int d, const APL_Float_Base & e) inline
Definition at line 257 of file APL_Float_as_class.hh.
operator+=() [1/2]
APL_Float_Base& operator+= (APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 271 of file APL_Float_as_class.hh.
operator+=() [2/2]
APL_Float_Base& operator+= (APL_Float_Base & d, double e) inline
Definition at line 271 of file APL_Float_as_class.hh.
operator-() [1/8]
APL_Float operator- (const APL_Float_Base & d) inline
Definition at line 253 of file APL_Float_as_class.hh.
operator-() [2/8]
double operator- (const APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 258 of file APL_Float_as_class.hh.
operator-() [3/8]
double operator- (const APL_Float_Base & d, double e) inline
Definition at line 258 of file APL_Float_as_class.hh.
operator-() [4/8]
double operator- (const APL_Float_Base & d, APL_Integer e) inline
Definition at line 258 of file APL_Float_as_class.hh.
operator-() [5/8]
double operator- (const APL_Float_Base & d, uint64_t e) inline
Definition at line 258 of file APL_Float_as_class.hh.
operator-() [6/8]
double operator- (double d, const APL_Float_Base & e) inline
Definition at line 258 of file APL_Float_as_class.hh.
operator-() [7/8]
double operator- (APL_Integer d, const APL_Float_Base & e) inline
Definition at line 258 of file APL_Float_as_class.hh.
operator-() [8/8]
double operator- (int d, const APL_Float_Base & e) inline
Definition at line 258 of file APL_Float_as_class.hh.
operator-=() [1/2]
APL_Float_Base& operator-= (APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 272 of file APL_Float_as_class.hh.
operator-=() [2/2]
APL_Float_Base& operator-= (APL_Float_Base & d, double e) inline
Definition at line 272 of file APL_Float_as_class.hh.
operator/() [1/7]
double operator/ (const APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 260 of file APL_Float_as_class.hh.
operator/() [2/7]
double operator/ (int d, const APL_Float_Base & e) inline
Definition at line 260 of file APL_Float_as_class.hh.
operator/() [3/7]
double operator/ (const APL_Float_Base & d, APL_Integer e) inline
Definition at line 260 of file APL_Float_as_class.hh.
operator/() [4/7]
double operator/ (const APL_Float_Base & d, double e) inline
Definition at line 260 of file APL_Float_as_class.hh.
operator/() [5/7]
double operator/ (const APL_Float_Base & d, uint64_t e) inline
Definition at line 260 of file APL_Float_as_class.hh.
operator/() [6/7]
double operator/ (double d, const APL_Float_Base & e) inline
Definition at line 260 of file APL_Float_as_class.hh.
operator/() [7/7]
double operator/ (APL_Integer d, const APL_Float_Base & e) inline
Definition at line 260 of file APL_Float_as_class.hh.
operator/=() [1/2]
APL_Float_Base& operator/= (APL_Float_Base & d, double e) inline
Definition at line 274 of file APL_Float_as_class.hh.
operator/=() [2/2]
APL_Float_Base& operator/= (APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 274 of file APL_Float_as_class.hh.
operator<() [1/7]
bool operator< (double d, const APL_Float_Base & e) inline
Definition at line 263 of file APL_Float_as_class.hh.
operator<() [2/7]
bool operator< (APL_Integer d, const APL_Float_Base & e) inline
Definition at line 263 of file APL_Float_as_class.hh.
operator<() [3/7]
bool operator< (int d, const APL_Float_Base & e) inline
Definition at line 263 of file APL_Float_as_class.hh.
operator<() [4/7]
bool operator< (const APL_Float_Base & d, uint64_t e) inline
Definition at line 263 of file APL_Float_as_class.hh.
operator<() [5/7]
bool operator< (const APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 263 of file APL_Float_as_class.hh.
operator<() [6/7]
bool operator< (const APL_Float_Base & d, double e) inline
Definition at line 263 of file APL_Float_as_class.hh.
operator<() [7/7]
bool operator< (const APL_Float_Base & d, APL_Integer e) inline
Definition at line 263 of file APL_Float_as_class.hh.
operator<=() [1/7]
bool operator<= (const APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 265 of file APL_Float_as_class.hh.
operator<=() [2/7]
bool operator<= (const APL_Float_Base & d, APL_Integer e) inline
Definition at line 265 of file APL_Float_as_class.hh.
operator<=() [3/7]
bool operator<= (int d, const APL_Float_Base & e) inline
Definition at line 265 of file APL_Float_as_class.hh.
operator<=() [4/7]
bool operator<= (const APL_Float_Base & d, double e) inline
Definition at line 265 of file APL_Float_as_class.hh.
operator<=() [5/7]
bool operator<= (APL_Integer d, const APL_Float_Base & e) inline
Definition at line 265 of file APL_Float_as_class.hh.
operator<=() [6/7]
bool operator<= (const APL_Float_Base & d, uint64_t e) inline
Definition at line 265 of file APL_Float_as_class.hh.
operator<=() [7/7]
bool operator<= (double d, const APL_Float_Base & e) inline
Definition at line 265 of file APL_Float_as_class.hh.
operator==() [1/7]
bool operator== (APL_Integer d, const APL_Float_Base & e) inline
Definition at line 267 of file APL_Float_as_class.hh.
operator==() [2/7]
bool operator== (const APL_Float_Base & d, APL_Integer e) inline
Definition at line 267 of file APL_Float_as_class.hh.
operator==() [3/7]
bool operator== (double d, const APL_Float_Base & e) inline
Definition at line 267 of file APL_Float_as_class.hh.
operator==() [4/7]
bool operator== (const APL_Float_Base & d, uint64_t e) inline
Definition at line 267 of file APL_Float_as_class.hh.
operator==() [5/7]
bool operator== (int d, const APL_Float_Base & e) inline
Definition at line 267 of file APL_Float_as_class.hh.
operator==() [6/7]
bool operator== (const APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 267 of file APL_Float_as_class.hh.
operator==() [7/7]
bool operator== (const APL_Float_Base & d, double e) inline
Definition at line 267 of file APL_Float_as_class.hh.
operator>() [1/7]
bool operator> (double d, const APL_Float_Base & e) inline
Definition at line 264 of file APL_Float_as_class.hh.
operator>() [2/7]
bool operator> (const APL_Float_Base & d, APL_Integer e) inline
Definition at line 264 of file APL_Float_as_class.hh.
operator>() [3/7]
bool operator> (const APL_Float_Base & d, double e) inline
Definition at line 264 of file APL_Float_as_class.hh.
operator>() [4/7]
bool operator> (APL_Integer d, const APL_Float_Base & e) inline
Definition at line 264 of file APL_Float_as_class.hh.
operator>() [5/7]
bool operator> (const APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 264 of file APL_Float_as_class.hh.
operator>() [6/7]
bool operator> (int d, const APL_Float_Base & e) inline
Definition at line 264 of file APL_Float_as_class.hh.
operator>() [7/7]
bool operator> (const APL_Float_Base & d, uint64_t e) inline
Definition at line 264 of file APL_Float_as_class.hh.
operator>=() [1/7]
bool operator>= (APL_Integer d, const APL_Float_Base & e) inline
Definition at line 266 of file APL_Float_as_class.hh.
operator>=() [2/7]
bool operator>= (const APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 266 of file APL_Float_as_class.hh.
operator>=() [3/7]
bool operator>= (const APL_Float_Base & d, uint64_t e) inline
Definition at line 266 of file APL_Float_as_class.hh.
operator>=() [4/7]
bool operator>= (double d, const APL_Float_Base & e) inline
Definition at line 266 of file APL_Float_as_class.hh.
operator>=() [5/7]
bool operator>= (const APL_Float_Base & d, double e) inline
Definition at line 266 of file APL_Float_as_class.hh.
operator>=() [6/7]
bool operator>= (const APL_Float_Base & d, APL_Integer e) inline
Definition at line 266 of file APL_Float_as_class.hh.
operator>=() [7/7]
bool operator>= (int d, const APL_Float_Base & e) inline
Definition at line 266 of file APL_Float_as_class.hh.
pow() [1/3]
double pow (const APL_Float_Base & d, double e) inline
Definition at line 250 of file APL_Float_as_class.hh.
pow() [2/3]
double pow (double d, const APL_Float_Base & e) inline
Definition at line 250 of file APL_Float_as_class.hh.
pow() [3/3]
double pow (const APL_Float_Base & d, const APL_Float_Base & e) inline
Definition at line 250 of file APL_Float_as_class.hh.
Referenced by IntCell::bif_power(), FloatCell::bif_power(), complex_power(), UCS_string::from_double_fixed_prec(), and Plot_window_properties::round_up_125().
round()
double round (const APL_Float_Base & d) inline
Definition at line 239 of file APL_Float_as_class.hh.
Referenced by ComplexCell::bif_near_int64_t(), NumericCell::cpx_gcd(), and ComplexCell::get_near_int().
sin()
double sin (const APL_Float_Base & d) inline
Definition at line 241 of file APL_Float_as_class.hh.
Referenced by RealCell::do_bif_circle_fun(), ComplexCell::do_bif_circle_fun(), ComplexCell::gamma(), Tokenizer::tokenize_number(), and Plot_window_properties::valXYZ2pixelXY().
sinh()
double sinh (const APL_Float_Base & d) inline
Definition at line 242 of file APL_Float_as_class.hh.
Referenced by RealCell::do_bif_circle_fun(), and ComplexCell::do_bif_circle_fun().
sqrt()
double sqrt (const APL_Float_Base & d) inline
Definition at line 240 of file APL_Float_as_class.hh.
Referenced by ABS(), Bif_F12_DOMINO::Matrix< cplx >::col1_norm(), complex_sqrt(), Pixel_XY::distance(), RealCell::do_bif_circle_fun(), ComplexCell::do_bif_circle_fun(), Bif_F12_DOMINO::householder(), laic1_max(), laic1_min(), laqp2(), larfg(), Matrix< T >::max_norm(), Vector< T >::norm(), Statistics_record::print(), Statistics_record::save_record(), and Plot_window_properties::update().
tan()
double tan (const APL_Float_Base & d) inline
Definition at line 243 of file APL_Float_as_class.hh.
Referenced by RealCell::do_bif_circle_fun(), and ComplexCell::do_bif_circle_fun().
tanh()
double tanh (const APL_Float_Base & d) inline
Definition at line 245 of file APL_Float_as_class.hh.
Referenced by RealCell::do_bif_circle_fun(), and ComplexCell::do_bif_circle_fun().
tgamma()
double tgamma (const APL_Float_Base & d) inline
Definition at line 244 of file APL_Float_as_class.hh.
Referenced by FloatCell::bif_factorial(), and NumericCell::real_binomial().