GNUAPL: src/Assert.cc File Reference
Assert.cc File Reference
#include <string.h>
#include "Assert.hh"
#include "Backtrace.hh"
#include "Common.hh"
#include "Output.hh"
#include "IO_Files.hh"
#include "Workspace.hh"
Functions
void do_Assert (const char *cond, const char *fun, const char *file, int line)
the complaint function
Variables
static bool asserting = false
prevent recursive do_Assert() calls.
Function Documentation
do_Assert()
void do_Assert (const char * cond, const char * fun, const char * file, int line)
the complaint function
Definition at line 35 of file Assert.cc.
References IO_Files::assert_error(), asserting, BACKTRACE, E_ASSERTION_FAILED, Error, get_CERR(), Workspace::get_error(), Workspace::list_SI(), LOC, Log, SIM_SIS_dbg, and voidP().
Variable Documentation
asserting
bool asserting = false static
prevent recursive do_Assert() calls.
Definition at line 31 of file Assert.cc.
Referenced by do_Assert().