GNUAPL: src/Assert.hh File Reference
Assert.hh File Reference
#include "Common.hh"
Macros
#define NeverReach(X) do_Assert(X, __FUNCTION__, __FILE__, __LINE__)
#define Assert_fatal(x)
normal assertion
Functions
void do_Assert (const char *cond, const char *fun, const char *file, int line)
the complaint function
Macro Definition Documentation
Assert_fatal
#define Assert_fatal (x)
Value:
if (!(x)) {\
   cerr << endl << endl << "FATAL error at " << __FILE__ << ":" << __LINE__ \
        << endl;   exit(2); }
normal assertion
assertion being fatal if wrong
Definition at line 90 of file Assert.hh.
Referenced by run_generic().
NeverReach
#define NeverReach (X) do_Assert(X, __FUNCTION__, __FILE__, __LINE__)
Definition at line 85 of file Assert.hh.
Referenced by Function::canonical(), LvalCell::CDR_size(), PointerCell::CDR_size(), Cell::CDR_size(), and Cell::get_checked_near_int().
Function Documentation
do_Assert()
void do_Assert (const char * cond, const char * fun, const char * file, int line)
the complaint function
Definition at line 35 of file Assert.cc.
References IO_Files::assert_error(), asserting, BACKTRACE, E_ASSERTION_FAILED, Error, get_CERR(), Workspace::get_error(), Workspace::list_SI(), LOC, Log, SIM_SIS_dbg, and voidP().