GNU APL: Quad_XML Class Reference
Quad_XML Class Reference
The class implementing ⎕XML.
#include <Quad_XML.hh>
Public Member Functions
Quad_XML ()
Constructor.
Public Member Functions inherited from QuadFunction
QuadFunction (TokenTag tag)
Constructor.
virtual bool has_alpha () const
overloaded Function::has_alpha()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B().
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB().
virtual bool has_result () const
overloaded Function::has_result()
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
virtual bool has_result () const
overloaded Function::has_result()
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Static Public Member Functions
static UCS_string skip_pos_prefix (const UCS_string &ucs)
return ucs with leading _NNN (position) skipped.
static int split_name (Unicode *category, ShapeItem *position, UCS_string *name, const Value &src)
split src, e.g. "_2_name" into integer 2, Unicode '_', and UCS_string 'name'. Null pointers if not relevant.
Static Public Attributes
static Quad_XML * fun = &Quad_XML::_fun
Built-in function.
static Quad_XML _fun
Built-in function.
Protected Types
enum tree_flags {
tf_none = 0x0000 ,
tf_with_pos = 0x0001 ,
tf_with_decl = 0x0002 ,
tf_fullpath = 0x0004 ,
tf_tagname = 0x0010 ,
tf_decl = 0x0020 ,
tf_text = 0x0040 ,
tf_sub = 0x0080 ,
tf_all = 0x00F0 ,
tf_flat = 0x0100 ,
tf_delta = tf_decl | tf_text
}
display details for tree() functions
Protected Member Functions
Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB()
Token eval_B (Value_P B) const
overloaded Function::eval_B()
Token convert_file (const Value &B) const
return XML file (-name in B) converted to APL structured value
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Static Protected Member Functions
static Value_P APL_to_XML (const Value &B)
convert APL associative array to XML string
static void add_sorted_entities (vector< const UCS_string * > &entities, const Value &B)
return the entities in B, sorted by their position prefix
static Value_P XML_to_APL (const Value &B)
convert XML string to APL associative array
static Value_P path_split (const Value &B)
"M1" M2" ... "Mn" ← "M1.M2...Mn"
static Value_P name_split (const Value &B)
(POS CATEGORY TAG_NAME) ← MEMBER_NAME
static Value_P name_unsplit (const Value &B)
MEMBER_NAME ← POS CATEGORY TAG_NAME.
static Token all_members (const Value &B, int flags)
return all XML nodes as member names
static Token next_member (const Value &A, const Value &B)
iterator: return the next member after A in structured value B
static Value_P tree (const Value &B, int flags)
return a tree-view of the members in B according to flags
static void tree (const Value &B, UCS_string &z, UCS_string &prefix, const UCS_string &name_prefix, int flags)
return a sub-tree-view of the members in B at level
static void all_members (UCS_string_vector &result, const Value &B, const UCS_string &name_prefix, int flags)
return all member names according to flags
Additional Inherited Members
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
The class implementing ⎕XML.
The system function ⎕XML
Definition at line 201 of file Quad_XML.hh.
Member Enumeration Documentation
tree_flags
enum Quad_XML::tree_flags protected
display details for tree() functions
Enumerator
tf_none
show position prefix in member names
tf_with_pos
show position prefix in member names
tf_with_decl
∆-nodes (∆text, ∆decl. etc)
tf_fullpath
display full path
tf_tagname
display ⍙ nodes
tf_decl
display ∆ nodes ≠ ∆text
tf_text
display ∆text nodes
tf_sub
display _NAME nodes
tf_all
display all node categories
tf_delta
do not recurse
Definition at line 255 of file Quad_XML.hh.
Constructor & Destructor Documentation
Quad_XML()
Quad_XML::Quad_XML () inline
Constructor.
Definition at line 205 of file Quad_XML.hh.
Member Function Documentation
add_sorted_entities()
void Quad_XML::add_sorted_entities (vector< const UCS_string * > & entities, const Value & B) static protected
return the entities in B, sorted by their position prefix
Definition at line 275 of file Quad_XML.cc.
References add_sorted_entities(), UCS_string::append(), UCS_string::append_UTF8(), XML_node::denormalize_attribute_value(), UCS_string::size(), and split_name().
Referenced by add_sorted_entities(), and APL_to_XML().
all_members() [1/2]
Token Quad_XML::all_members (const Value & B, int flags) static protected
return all XML nodes as member names
Definition at line 1609 of file Quad_XML.cc.
References all_members(), and Value_P_Base::get().
Referenced by all_members(), and eval_AB().
all_members() [2/2]
void Quad_XML::all_members (UCS_string_vector & result, const Value & B, const UCS_string & name_prefix, int flags) static protected
return all member names according to flags
Definition at line 1634 of file Quad_XML.cc.
References all_members(), UCS_string::append(), Cell::get_pointer_value(), Cell::is_pointer_cell(), Value::is_structured(), tf_decl, tf_delta, tf_sub, tf_tagname, and tf_text.
APL_to_XML()
Value_P Quad_XML::APL_to_XML (const Value & B) static protected
convert APL associative array to XML string
Definition at line 253 of file Quad_XML.cc.
References add_sorted_entities(), and UCS_string::size().
Referenced by eval_B().
convert_file()
Token Quad_XML::convert_file (const Value & B) const protected
return XML file (-name in B) converted to APL structured value
Definition at line 1264 of file Quad_XML.cc.
References UTF8_string::c_str(), and eval_B().
Referenced by eval_AB().
eval_AB()
Token Quad_XML::eval_AB (Value_P A, Value_P B) const protected virtual
overloaded Function::eval_AB()
Reimplemented from QuadFunction.
Definition at line 1164 of file Quad_XML.cc.
References all_members(), convert_file(), eval_B(), name_split(), name_unsplit(), next_member(), path_split(), tf_all, tf_decl, tf_fullpath, tf_none, tf_sub, tf_tagname, tf_text, tf_with_decl, tf_with_pos, and tree().
eval_B()
Token Quad_XML::eval_B (Value_P B) const protected virtual
overloaded Function::eval_B()
Reimplemented from QuadFunction.
Definition at line 236 of file Quad_XML.cc.
References APL_to_XML(), and XML_to_APL().
Referenced by convert_file(), and eval_AB().
name_split()
Value_P Quad_XML::name_split (const Value & B) static protected
(POS CATEGORY TAG_NAME) ← MEMBER_NAME
Definition at line 1378 of file Quad_XML.cc.
References Value_P_Base::get(), and split_name().
Referenced by eval_AB().
name_unsplit()
Value_P Quad_XML::name_unsplit (const Value & B) static protected
MEMBER_NAME ← POS CATEGORY TAG_NAME.
Definition at line 1399 of file Quad_XML.cc.
References UCS_string::append_number(), Value::element_count(), Value_P_Base::get(), Cell::get_char_value(), Value::get_cravel(), Cell::get_int_value(), Workspace::get_IO(), Cell::get_pointer_value(), Value::get_rank(), and Cell::is_character_cell().
Referenced by eval_AB().
next_member()
Token Quad_XML::next_member (const Value & A, const Value & B) static protected
iterator: return the next member after A in structured value B
Definition at line 1700 of file Quad_XML.cc.
References Value::element_count(), Value_P_Base::get(), Value::get_cravel(), Value::get_member_data(), Cell::get_pointer_value(), Cell::is_pointer_cell(), Value::is_structured(), path_split(), Value::sorted_members(), and split_name().
Referenced by eval_AB().
path_split()
Value_P Quad_XML::path_split (const Value & B) static protected
"M1" M2" ... "Mn" ← "M1.M2...Mn"
Definition at line 1324 of file Quad_XML.cc.
References UCS_string::back(), UCS_string::drop(), Value_P_Base::get(), UCS_string::pop_back(), and UCS_string::size().
Referenced by eval_AB(), and next_member().
skip_pos_prefix()
UCS_string Quad_XML::skip_pos_prefix (const UCS_string & ucs) static
return ucs with leading _NNN (position) skipped.
Definition at line 1153 of file Quad_XML.cc.
References UCS_string::size().
Referenced by tree().
split_name()
int Quad_XML::split_name (Unicode * category, ShapeItem * position, UCS_string * name, const Value & src) static
split src, e.g. "_2_name" into integer 2, Unicode '_', and UCS_string 'name'. Null pointers if not relevant.
Definition at line 1459 of file Quad_XML.cc.
References Cell::get_char_value().
Referenced by add_sorted_entities(), name_split(), next_member(), and Value::sorted_members().
tree() [1/2]
Value_P Quad_XML::tree (const Value & B, int flags) static protected
return a tree-view of the members in B according to flags
Definition at line 1442 of file Quad_XML.cc.
References tree().
Referenced by eval_AB(), and tree().
tree() [2/2]
void Quad_XML::tree (const Value & B, UCS_string & z, UCS_string & prefix, const UCS_string & name_prefix, int flags) static protected
return a sub-tree-view of the members in B at level
Definition at line 1510 of file Quad_XML.cc.
References UCS_string::back(), Cell::get_pointer_value(), Cell::is_pointer_cell(), UCS_string::pop_back(), UCS_string::size(), skip_pos_prefix(), tf_fullpath, tf_with_decl, tf_with_pos, and tree().
XML_to_APL()
Value_P Quad_XML::XML_to_APL (const Value & B) static protected
convert XML string to APL associative array
Definition at line 388 of file Quad_XML.cc.
References XML_node::collect(), Value_P_Base::get(), Workspace::get_IO(), XML_node::get_next(), XML_node::get_taglen(), XML_node::is_XML_char(), XML_node::translate(), and XML_node::unlink().
Referenced by eval_B().
Member Data Documentation
_fun
Quad_XML Quad_XML::_fun static
Built-in function.
Definition at line 210 of file Quad_XML.hh.
fun
Quad_XML * Quad_XML::fun = &Quad_XML::_fun static
Built-in function.
Definition at line 209 of file Quad_XML.hh.
The documentation for this class was generated from the following files:
src/Quad_XML.hh
src/Quad_XML.cc