GNU APL: IndexIterator Class Reference
IndexIterator Class Reference abstract
Base class for ElidedIndexIterator and TrueIndexIterator.
#include <IndexIterator.hh>
Public Member Functions
IndexIterator (ShapeItem w, ShapeItem cnt)
constructor: IndexIterator with weight w
void operator++ ()
go the the next index
bool more () const
return true if more indices are coming
virtual ShapeItem get_ivalue () const =0
return the current index
virtual ShapeItem get_pos (ShapeItem p) const =0
return the current index
ostream & print (ostream &out) const
print this iterator (for debugging purposes).
IndexIterator * get_upper () const
return the next higher IndexIterator
void set_upper (IndexIterator *up)
set the next higher IndexIterator
ShapeItem get_index_count () const
get the number of indices.
Protected Attributes
const ShapeItem weight
the weight of this IndexIterator
const ShapeItem count
number of index elements
IndexIterator * upper
The next higher iterator.
ShapeItem pos
The current value.
Detailed Description
Base class for ElidedIndexIterator and TrueIndexIterator.
An iterator for one dimension of indices. When the iterator reached its end, it wraps around and increments its upper IndexIterator (if any).
This way, multi-dimensional iterators can be created.
Definition at line 32 of file IndexIterator.hh.
Constructor & Destructor Documentation
IndexIterator()
IndexIterator::IndexIterator (ShapeItem w, ShapeItem cnt) inline
constructor: IndexIterator with weight w
Definition at line 36 of file IndexIterator.hh.
~IndexIterator()
virtual IndexIterator::~IndexIterator () inline virtual
Definition at line 43 of file IndexIterator.hh.
Member Function Documentation
get_index_count()
ShapeItem IndexIterator::get_index_count () const inline
get the number of indices.
Definition at line 67 of file IndexIterator.hh.
References count.
Referenced by operator++(), and print().
get_ivalue()
virtual ShapeItem IndexIterator::get_ivalue () const pure virtual
return the current index
Implemented in ElidedIndexIterator, and TrueIndexIterator.
Referenced by print().
get_pos()
virtual ShapeItem IndexIterator::get_pos (ShapeItem p) const pure virtual
return the current index
Implemented in ElidedIndexIterator, and TrueIndexIterator.
Referenced by print().
get_upper()
IndexIterator * IndexIterator::get_upper () const inline
return the next higher IndexIterator
Definition at line 61 of file IndexIterator.hh.
References upper.
Referenced by MultiIndexIterator::operator++(), and MultiIndexIterator::~MultiIndexIterator().
more()
bool IndexIterator::more () const inline
return true if more indices are coming
Definition at line 49 of file IndexIterator.hh.
References count, and pos.
Referenced by MultiIndexIterator::more().
operator++()
void IndexIterator::operator++ ()
go the the next index
Definition at line 29 of file IndexIterator.cc.
References get_index_count(), pos, and upper.
print()
ostream & IndexIterator::print (ostream & out) const
print this iterator (for debugging purposes).
Definition at line 49 of file IndexIterator.cc.
References get_index_count(), get_ivalue(), get_pos(), and upper.
set_upper()
void IndexIterator::set_upper (IndexIterator * up) inline
set the next higher IndexIterator
Definition at line 64 of file IndexIterator.hh.
References upper.
Referenced by MultiIndexIterator::MultiIndexIterator().
Member Data Documentation
count
const ShapeItem IndexIterator::count protected
number of index elements
Definition at line 74 of file IndexIterator.hh.
Referenced by get_index_count(), TrueIndexIterator::get_ivalue(), ElidedIndexIterator::get_pos(), TrueIndexIterator::get_pos(), more(), and TrueIndexIterator::TrueIndexIterator().
pos
ShapeItem IndexIterator::pos protected
The current value.
Definition at line 80 of file IndexIterator.hh.
Referenced by ElidedIndexIterator::get_ivalue(), TrueIndexIterator::get_ivalue(), more(), and operator++().
upper
IndexIterator* IndexIterator::upper protected
The next higher iterator.
Definition at line 77 of file IndexIterator.hh.
Referenced by get_upper(), operator++(), print(), and set_upper().
weight
const ShapeItem IndexIterator::weight protected
the weight of this IndexIterator
Definition at line 71 of file IndexIterator.hh.
Referenced by ElidedIndexIterator::get_ivalue().
The documentation for this class was generated from the following files:
src/IndexIterator.hh
src/IndexIterator.cc