GNU APL: Quad_RVAL Class Reference
Quad_RVAL Class Reference
a random APL value
#include <Quad_RVAL.hh>
Public Member Functions
Quad_RVAL ()
Constructor.
Public Member Functions inherited from QuadFunction
QuadFunction (TokenTag tag)
Constructor.
virtual bool has_alpha () const
overloaded Function::has_alpha()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B().
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB().
virtual bool has_result () const
overloaded Function::has_result()
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
virtual bool has_result () const
overloaded Function::has_result()
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Static Public Attributes
static Quad_RVAL * fun = &Quad_RVAL::_fun
Built-in function.
static Quad_RVAL _fun
Built-in function.
Protected Member Functions
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B()
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Static Protected Member Functions
static Value_P do_eval_AB (int A, const Value &B)
do eval_AB(A, B);
static Value_P do_eval_B (const Value &B, int depth)
do eval_B(B);
static Value_P generator_state (const Value &B)
set or return the state of the random generator
static Value_P result_rank (const Value &B)
set or return the desired rank of random numbers
static Value_P result_shape (const Value &B)
set or return the desired ranks of random numbers
static Value_P result_type (const Value &B)
set or return the desired types of random numbers
static Value_P result_maxdepth (const Value &B)
set or return the desired max. depth of random numbers
static int choose_integer (const vector< int > &dist)
choose an integer value at random according to distribution dist
static void random_character (Value &Z)
initialize cell with a random character
static void random_integer (Value &Z)
initialize cell with a random integer
static void random_float (Value &Z)
initialize cell with a random float
static void random_complex (Value &Z)
initialize cell with a random complex number
static void random_nested (Value &Z, const Value &B, int depth)
initialize cell with a random nested value
static uint64_t rand17 ()
return a 17-bit random number
Static Protected Attributes
static size_t N
the number of bytes in the state of the random number generator
static vector< int > desired_ranks
the desired rank of random values
static Shape desired_shape
the desired rank of random values
static vector< int > desired_types
the desired types (or a distribution of types) of random values
static int desired_maxdepth
the desiredlimit on the depths of the random values
static char state [256]
the state buffer of the random number generator
static struct random_data rdata
the state of the random number generator
Additional Inherited Members
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
a random APL value
Definition at line 31 of file Quad_RVAL.hh.
Constructor & Destructor Documentation
Quad_RVAL()
Quad_RVAL::Quad_RVAL ()
Constructor.
Definition at line 48 of file Quad_RVAL.cc.
References Shape::add_shape_item(), desired_maxdepth, desired_ranks, desired_shape, desired_types, Shape::get_rank(), N, rdata, and state.
Member Function Documentation
choose_integer()
int Quad_RVAL::choose_integer (const vector< int > & dist) static protected
choose an integer value at random according to distribution dist
Definition at line 450 of file Quad_RVAL.cc.
References rand17().
Referenced by do_eval_B().
do_eval_AB()
Value_P Quad_RVAL::do_eval_AB (int A, const Value & B) static protected
do eval_AB(A, B);
Definition at line 215 of file Quad_RVAL.cc.
References generator_state(), result_maxdepth(), result_rank(), result_shape(), and result_type().
Referenced by do_eval_B(), and eval_AB().
do_eval_B()
Value_P Quad_RVAL::do_eval_B (const Value & B, int depth) static protected
do eval_B(B);
Definition at line 69 of file Quad_RVAL.cc.
References Shape::add_shape_item(), choose_integer(), desired_maxdepth, desired_ranks, desired_shape, desired_types, do_eval_AB(), Cell::get_int_value(), Cell::get_pointer_value(), Shape::get_shape_item(), Cell::is_pointer_cell(), random_character(), random_complex(), random_float(), random_integer(), and random_nested().
Referenced by eval_B(), and random_nested().
eval_AB()
Token Quad_RVAL::eval_AB (Value_P A, Value_P B) const protected virtual
overloaded Function::eval_AB()
Reimplemented from QuadFunction.
Definition at line 195 of file Quad_RVAL.cc.
References do_eval_AB().
eval_B()
virtual Token Quad_RVAL::eval_B (Value_P B) const inline protected virtual
overloaded Function::eval_B()
Reimplemented from QuadFunction.
Definition at line 45 of file Quad_RVAL.hh.
References do_eval_B().
generator_state()
Value_P Quad_RVAL::generator_state (const Value & B) static protected
set or return the state of the random generator
Definition at line 233 of file Quad_RVAL.cc.
References N, rdata, and state.
Referenced by do_eval_AB().
rand17()
uint64_t Quad_RVAL::rand17 () static protected
return a 17-bit random number
Definition at line 539 of file Quad_RVAL.cc.
References rdata.
Referenced by choose_integer(), random_character(), random_complex(), random_float(), and random_integer().
random_character()
void Quad_RVAL::random_character (Value & Z) static protected
initialize cell with a random character
Definition at line 479 of file Quad_RVAL.cc.
References Value::next_ravel_Char(), and rand17().
Referenced by do_eval_B().
random_complex()
void Quad_RVAL::random_complex (Value & Z) static protected
initialize cell with a random complex number
Definition at line 509 of file Quad_RVAL.cc.
References Value::next_ravel_Complex(), and rand17().
Referenced by do_eval_B().
random_float()
void Quad_RVAL::random_float (Value & Z) static protected
initialize cell with a random float
Definition at line 496 of file Quad_RVAL.cc.
References Value::next_ravel_Float(), and rand17().
Referenced by do_eval_B().
random_integer()
void Quad_RVAL::random_integer (Value & Z) static protected
initialize cell with a random integer
Definition at line 486 of file Quad_RVAL.cc.
References Value::next_ravel_Int(), and rand17().
Referenced by do_eval_B().
random_nested()
void Quad_RVAL::random_nested (Value & Z, const Value & B, int depth) static protected
initialize cell with a random nested value
Definition at line 528 of file Quad_RVAL.cc.
References do_eval_B(), Value_P_Base::get(), and Value::next_ravel_Pointer().
Referenced by do_eval_B().
result_maxdepth()
Value_P Quad_RVAL::result_maxdepth (const Value & B) static protected
set or return the desired max. depth of random numbers
Definition at line 428 of file Quad_RVAL.cc.
References desired_maxdepth.
Referenced by do_eval_AB().
result_rank()
Value_P Quad_RVAL::result_rank (const Value & B) static protected
set or return the desired rank of random numbers
Definition at line 278 of file Quad_RVAL.cc.
References desired_ranks.
Referenced by do_eval_AB().
result_shape()
Value_P Quad_RVAL::result_shape (const Value & B) static protected
set or return the desired ranks of random numbers
Definition at line 326 of file Quad_RVAL.cc.
References Shape::add_shape_item(), desired_shape, Shape::get_rank(), and Shape::get_shape_item().
Referenced by do_eval_AB().
result_type()
Value_P Quad_RVAL::result_type (const Value & B) static protected
set or return the desired types of random numbers
Definition at line 367 of file Quad_RVAL.cc.
References desired_types.
Referenced by do_eval_AB().
Member Data Documentation
_fun
Quad_RVAL Quad_RVAL::_fun static
Built-in function.
Definition at line 38 of file Quad_RVAL.hh.
desired_maxdepth
int Quad_RVAL::desired_maxdepth static protected
the desiredlimit on the depths of the random values
Definition at line 104 of file Quad_RVAL.hh.
Referenced by do_eval_B(), Quad_RVAL(), and result_maxdepth().
desired_ranks
vector< int > Quad_RVAL::desired_ranks static protected
the desired rank of random values
Definition at line 95 of file Quad_RVAL.hh.
Referenced by do_eval_B(), Quad_RVAL(), and result_rank().
desired_shape
Shape Quad_RVAL::desired_shape static protected
the desired rank of random values
Definition at line 98 of file Quad_RVAL.hh.
Referenced by do_eval_B(), Quad_RVAL(), and result_shape().
desired_types
vector< int > Quad_RVAL::desired_types static protected
the desired types (or a distribution of types) of random values
Definition at line 101 of file Quad_RVAL.hh.
Referenced by do_eval_B(), Quad_RVAL(), and result_type().
fun
Quad_RVAL * Quad_RVAL::fun = &Quad_RVAL::_fun static
Built-in function.
Definition at line 37 of file Quad_RVAL.hh.
N
size_t Quad_RVAL::N static protected
the number of bytes in the state of the random number generator
Definition at line 92 of file Quad_RVAL.hh.
Referenced by generator_state(), and Quad_RVAL().
rdata
random_data Quad_RVAL::rdata static protected
the state of the random number generator
Definition at line 111 of file Quad_RVAL.hh.
Referenced by generator_state(), Quad_RVAL(), and rand17().
state
char Quad_RVAL::state static protected
the state buffer of the random number generator
Definition at line 107 of file Quad_RVAL.hh.
Referenced by generator_state(), and Quad_RVAL().
The documentation for this class was generated from the following files:
src/Quad_RVAL.hh
src/Quad_RVAL.cc