GNU APL: Parser Class Reference
Parser Class Reference
A parser for APL code.
#include <Parser.hh>
Public Member Functions
Parser (ParseMode pm, const char *loc, bool mac)
constructor
ErrorCode parse (const UCS_string &input, Token_string &tos) const
Parse UCS_string input into token string tos.
ErrorCode parse (const Token_string &input, Token_string &tos) const
Parse token string input into token string tos.
Static Public Member Functions
static void remove_void_token (Token_string &tos)
remove VOID token from tos (compacting tos)
static ErrorCode match_par_bra (Token_string &tos, bool backwards)
compute distances between matching (), [], and {}
Static Protected Member Functions
static ErrorCode parse_statement (Token_string &tos)
Parse token string tos (a statement without diamonds).
static int find_opening_bracket (const Token_string &tos, int pos)
find opening bracket; throw error if not found
static int find_closing_bracket (const Token_string &tos, int pos)
find closing bracket; throw error if not found
static int find_opening_parent (const Token_string &tos, int pos)
find opening paranthesis; throw error if not found.
static int find_closing_parent (const Token_string &tos, int pos)
find closing paranthesis; throw error if not found.
static void collect_constants (Token_string &tos)
Collect consecutive smaller APL values or value token into vectors.
static void mark_lsymb (Token_string &tos)
mark next symbol left of ← on the same level as LSYMB
static bool collect_groups (Token_string &tos)
Collect groups.
static void remove_nongrouping_parantheses (Token_string &tos)
Replace (X) by X and ((..) by (..) in string. (X is a single token)
static void replace_bitwise_functions (Token_string &tos)
Replace ∧∧, ∨∨, ⍲⍲, and ⍱⍱ by their bitwise variant.
static bool check_if_value (const Token_string &tos, int pos)
check if tos[pos] is the end of a value or of a function
static void create_value (Token_string &tos, int pos, int len)
Create one APL value from len values.
static void create_scalar_value (Token &tok)
Create one scalar APL value from a token.
static void create_vector_value (Token_string &tos, int pos, int len)
Create one vector APL value from value_count single values.
Protected Attributes
const ParseMode pmode
the parsing mode of this parser
const bool macro
tokenize macro code
const char * create_loc
where this parser was constructed
Detailed Description
A parser for APL code.
Functions related to parsing of input lines and defined functions.
Definition at line 30 of file Parser.hh.
Constructor & Destructor Documentation
Parser()
Parser::Parser (ParseMode pm, const char * loc, bool mac) inline
constructor
Definition at line 34 of file Parser.hh.
Member Function Documentation
check_if_value()
bool Parser::check_if_value (const Token_string & tos, int pos) static protected
check if tos[pos] is the end of a value or of a function
Definition at line 534 of file Parser.cc.
References check_if_value(), and find_opening_bracket().
Referenced by check_if_value().
collect_constants()
void Parser::collect_constants (Token_string & tos) static protected
Collect consecutive smaller APL values or value token into vectors.
Definition at line 205 of file Parser.cc.
References create_value(), and Token_string::print().
Referenced by parse_statement().
collect_groups()
bool Parser::collect_groups (Token_string & tos) static protected
Collect groups.
Definition at line 275 of file Parser.cc.
References create_value(), and Token_string::print().
Referenced by parse_statement().
create_scalar_value()
void Parser::create_scalar_value (Token & tok) static protected
Create one scalar APL value from a token.
Definition at line 675 of file Parser.cc.
References Token::get_char_val(), Token::get_cpx_imag(), Token::get_cpx_real(), Token::get_flt_val(), Token::get_int_val(), Token::get_tag(), and Token::move_1().
Referenced by create_value().
create_value()
void Parser::create_value (Token_string & tos, int pos, int len) static protected
Create one APL value from len values.
Definition at line 654 of file Parser.cc.
References create_scalar_value(), create_value(), create_vector_value(), and Token_string::print().
Referenced by collect_constants(), collect_groups(), and create_value().
create_vector_value()
void Parser::create_vector_value (Token_string & tos, int pos, int len) static protected
Create one vector APL value from value_count single values.
Definition at line 726 of file Parser.cc.
References Token::clear(), Value_P_Base::get(), Token::get_apl_val(), Token::get_char_val(), Token::get_cpx_imag(), Token::get_cpx_real(), Token::get_flt_val(), Token::get_int_val(), Token::get_tag(), and Token_string::print().
Referenced by create_value().
find_closing_bracket()
int Parser::find_closing_bracket (const Token_string & tos, int pos) static protected
find closing bracket; throw error if not found
Definition at line 334 of file Parser.cc.
find_closing_parent()
int Parser::find_closing_parent (const Token_string & tos, int pos) static protected
find closing paranthesis; throw error if not found.
Definition at line 380 of file Parser.cc.
Referenced by remove_nongrouping_parantheses().
find_opening_bracket()
int Parser::find_opening_bracket (const Token_string & tos, int pos) static protected
find opening bracket; throw error if not found
Definition at line 357 of file Parser.cc.
Referenced by check_if_value().
find_opening_parent()
int Parser::find_opening_parent (const Token_string & tos, int pos) static protected
find opening paranthesis; throw error if not found.
Definition at line 403 of file Parser.cc.
mark_lsymb()
void Parser::mark_lsymb (Token_string & tos) static protected
mark next symbol left of ← on the same level as LSYMB
in tos, (re-) mark the symbols left of ← as left symbols
Definition at line 781 of file Parser.cc.
Referenced by parse_statement().
match_par_bra()
ErrorCode Parser::match_par_bra (Token_string & tos, bool backwards) static
compute distances between matching (), [], and {}
Definition at line 595 of file Parser.cc.
Referenced by parse_statement(), and Executable::setup_lambdas().
parse() [1/2]
ErrorCode Parser::parse (const Token_string & input, Token_string & tos) const
Parse token string input into token string tos.
Definition at line 66 of file Parser.cc.
References Token::get_tag(), parse(), parse_statement(), and Token_string::print().
parse() [2/2]
ErrorCode Parser::parse (const UCS_string & input, Token_string & tos) const
Parse UCS_string input into token string tos.
Definition at line 42 of file Parser.cc.
References macro, parse(), parse_statement(), pmode, and Tokenizer::tokenize().
Referenced by parse().
parse_statement()
ErrorCode Parser::parse_statement (Token_string & tos) static protected
Parse token string tos (a statement without diamonds).
Definition at line 123 of file Parser.cc.
References collect_constants(), collect_groups(), mark_lsymb(), match_par_bra(), Token_string::print(), remove_nongrouping_parantheses(), remove_void_token(), and replace_bitwise_functions().
Referenced by parse().
remove_nongrouping_parantheses()
void Parser::remove_nongrouping_parantheses (Token_string & tos) static protected
Replace (X) by X and ((..) by (..) in string. (X is a single token)
Definition at line 426 of file Parser.cc.
References find_closing_parent().
Referenced by parse_statement().
remove_void_token()
void Parser::remove_void_token (Token_string & tos) static
remove VOID token from tos (compacting tos)
Definition at line 580 of file Parser.cc.
Referenced by parse_statement(), and Executable::setup_lambdas().
replace_bitwise_functions()
void Parser::replace_bitwise_functions (Token_string & tos) static protected
Replace ∧∧, ∨∨, ⍲⍲, and ⍱⍱ by their bitwise variant.
Definition at line 487 of file Parser.cc.
References Bif_F2_EQUAL_B::_fun, Bif_F2_UNEQ_B::_fun, Bif_F2_AND_B::_fun, Bif_F2_OR_B::_fun, Bif_F2_NOR_B::_fun, and Bif_F2_NAND_B::_fun.
Referenced by parse_statement().
Member Data Documentation
create_loc
const char* Parser::create_loc protected
where this parser was constructed
Definition at line 102 of file Parser.hh.
macro
const bool Parser::macro protected
tokenize macro code
Definition at line 99 of file Parser.hh.
Referenced by parse().
pmode
const ParseMode Parser::pmode protected
the parsing mode of this parser
Definition at line 96 of file Parser.hh.
Referenced by parse().
The documentation for this class was generated from the following files:
src/Parser.hh
src/Parser.cc