GNU APL: ZZ Class Reference
ZZ Class Reference
a complex number
#include <LApack.hh>
Public Member Functions
ZZ ()
0J0
ZZ (APL_Float r)
rJ0
ZZ (APL_Float r, APL_Float i)
rJi
APL_Float real () const
return the real part of this
void set_real (APL_Float x)
set the real part of this
APL_Float imag () const
return the imag part of this
void set_imag (APL_Float x)
set the imag part of this
void conjugate ()
conjugate this
bool operator!= (APL_Float dd) const
return true if this is real and not equal to dd
bool operator== (APL_Float dd) const
return true if this is real and equal to dd
ZZ operator+ (const ZZ &zz) const
add r zz to this
ZZ operator- (const ZZ &zz) const
subtract zz from this
ZZ operator- () const
negate this
ZZ operator* (const ZZ &zz) const
multiply zz and this
ZZ operator/ (APL_Float d) const
divide this by d
ZZ operator/ (const ZZ &zz) const
divide this by zz
Protected Attributes
APL_Float _r
the real part
APL_Float _i
the imaginary part
Detailed Description
a complex number
Definition at line 81 of file LApack.hh.
Constructor & Destructor Documentation
ZZ() [1/3]
ZZ::ZZ () inline
0J0
Definition at line 85 of file LApack.hh.
Referenced by operator*(), operator+(), operator-(), and operator/().
ZZ() [2/3]
ZZ::ZZ (APL_Float r) inline
rJ0
Definition at line 91 of file LApack.hh.
ZZ() [3/3]
ZZ::ZZ (APL_Float r, APL_Float i) inline
rJi
Definition at line 97 of file LApack.hh.
Member Function Documentation
conjugate()
void ZZ::conjugate () inline
conjugate this
Definition at line 115 of file LApack.hh.
References _i.
Referenced by Vector< T >::conjugate(), and DZ::conjugate().
imag()
APL_Float ZZ::imag () const inline
return the imag part of this
Definition at line 109 of file LApack.hh.
References _i.
Referenced by DZ::CONJ(), DZ::get_imag(), and DZ::inv().
operator!=()
bool ZZ::operator!= (APL_Float dd) const inline
return true if this is real and not equal to dd
Definition at line 118 of file LApack.hh.
References _i, and _r.
operator*()
ZZ ZZ::operator* (const ZZ & zz) const inline
multiply zz and this
Definition at line 136 of file LApack.hh.
References _i, _r, and ZZ().
operator+()
ZZ ZZ::operator+ (const ZZ & zz) const inline
add r zz to this
Definition at line 124 of file LApack.hh.
References _i, _r, and ZZ().
operator-() [1/2]
ZZ ZZ::operator- () const inline
negate this
Definition at line 132 of file LApack.hh.
References _i, _r, and ZZ().
operator-() [2/2]
ZZ ZZ::operator- (const ZZ & zz) const inline
subtract zz from this
Definition at line 128 of file LApack.hh.
References _i, _r, and ZZ().
operator/() [1/2]
ZZ ZZ::operator/ (APL_Float d) const inline
divide this by d
Definition at line 141 of file LApack.hh.
References _i, _r, and ZZ().
operator/() [2/2]
ZZ ZZ::operator/ (const ZZ & zz) const inline
divide this by zz
Definition at line 145 of file LApack.hh.
References _i, _r, and ZZ().
operator==()
bool ZZ::operator== (APL_Float dd) const inline
return true if this is real and equal to dd
Definition at line 121 of file LApack.hh.
References _i, and _r.
real()
APL_Float ZZ::real () const inline
return the real part of this
Definition at line 103 of file LApack.hh.
References _r.
Referenced by DZ::CONJ(), DZ::get_real(), and DZ::inv().
set_imag()
void ZZ::set_imag (APL_Float x) inline
set the imag part of this
Definition at line 112 of file LApack.hh.
References _i.
set_real()
void ZZ::set_real (APL_Float x) inline
set the real part of this
Definition at line 106 of file LApack.hh.
References _r.
Member Data Documentation
_i
APL_Float ZZ::_i protected
the imaginary part
Definition at line 157 of file LApack.hh.
Referenced by conjugate(), imag(), operator!=(), operator*(), operator+(), operator-(), operator/(), operator==(), and set_imag().
_r
APL_Float ZZ::_r protected
the real part
Definition at line 154 of file LApack.hh.
Referenced by operator!=(), operator*(), operator+(), operator-(), operator/(), operator==(), real(), and set_real().
The documentation for this class was generated from the following file:
src/LApack.hh