GNU APL: FloatCell Class Reference
FloatCell Class Reference
A Cell containing a single floating point (or rational) value.
#include <FloatCell.hh>
Public Member Functions
FloatCell (APL_Float r)
Construct an floating point cell from a double r.
virtual void init_other (void *other, Value &cell_owner, const char *loc) const
overloaded Cell::init_other
APL_Float dfval () const
return the value of this cell as a double (even if the value is rational)
virtual bool is_float_cell () const
Overloaded Cell::is_float_cell().
virtual bool is_finite () const
Overloaded Cell::is_finite().
virtual bool greater (const Cell &other) const
Overloaded Cell::greater().
virtual bool equal (const Cell &other, double qct) const
Overloaded Cell::equal().
virtual ErrorCode bif_add (Cell *Z, const Cell *A) const
Overloaded Cell::bif_add().
virtual ErrorCode bif_ceiling (Cell *Z) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_conjugate (Cell *Z) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_direction (Cell *Z) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_divide (Cell *Z, const Cell *A) const
Overloaded Cell::bif_divide().
virtual ErrorCode bif_exponential (Cell *Z) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_factorial (Cell *Z) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_floor (Cell *Z) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_magnitude (Cell *Z) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_multiply (Cell *Z, const Cell *A) const
Overloaded Cell::bif_multiply().
virtual ErrorCode bif_power (Cell *Z, const Cell *A) const
Overloaded Cell::bif_power().
virtual ErrorCode bif_nat_log (Cell *Z) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_negative (Cell *Z) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_pi_times (Cell *Z) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_pi_times_inverse (Cell *Z) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_reciprocal (Cell *Z) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_roll (Cell *Z) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual Comp_result compare (const Cell &other) const
compare this with other, throw DOMAIN ERROR on illegal comparisons
virtual ErrorCode bif_maximum (Cell *Z, const Cell *A) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_minimum (Cell *Z, const Cell *A) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_residue (Cell *Z, const Cell *A) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_subtract (Cell *Z, const Cell *A) const
Overloaded Cell::bif_subtract().
virtual PrintBuffer character_representation (const PrintContext &pctx) const
the Quad_CR representation of this cell.
virtual bool need_scaling (const PrintContext &pctx) const
return true iff this cell needs scaling (exponential format) in pctx.
virtual ErrorCode bif_add_inverse (Cell *Z, const Cell *A) const
overloaded Cell::bif_add_inverse()
virtual ErrorCode bif_multiply_inverse (Cell *Z, const Cell *A) const
overloaded Cell::bif_multiply_inverse()
Public Member Functions inherited from Cell
Cell ()
Construct an un-initialized Cell.
void init (const Cell &other, Value &this_owner, const char *loc)
init this Cell from a (possibly deep) copy of other
virtual void init_other (void *other, Value &other_owner, const char *loc) const
init (uninitialized) Cell other from this initialized cell
void init_from_value (Value *value, Value &cell_owner, const char *loc)
init this Cell from value. If value is a scalar then its first element is used (and value is erased). Otherwise a PointerCell is created.
virtual bool greater (const Cell &other) const
Return true if this cell is greater than other, with:
virtual bool equal (const Cell &other, double qct) const
return true if this cell is equal to other
Value_P to_value (const char *loc) const
return pointer value of a PointerCell or create a scalar with a copy of this cell.
void init_type (const Cell &other, Value &cell_owner, const char *loc)
init this cell to be the type of other
virtual Unicode get_char_value () const
Return the character value of a cell.
virtual int get_byte_value () const
Return the byte value (-128..255 incl) of a cell.
virtual APL_Integer get_int_value () const
Return the integer value of a cell.
virtual APL_Float get_real_value () const
Return the real part of a cell.
virtual APL_Float get_imag_value () const
Return the imaginary part of a cell.
virtual APL_Complex get_complex_value () const
Return the complex value of a cell.
virtual Value_P get_pointer_value () const
Return the APL value of a cell (Asserts for non-pointer cells)
virtual Cell * get_lval_value () const
Return the APL value of a cell (Asserts for non-lval cells)
virtual PrintBuffer character_representation (const PrintContext &pctx) const
the Quad_CR representation of this cell
virtual bool need_scaling (const PrintContext &pctx) const
return true if this cell needs scaling (exponential format) in pctx
virtual bool get_near_bool () const
Return value if it is close to boolean, or else throw DOMAIN_ERROR.
virtual APL_Integer get_near_int () const
Return value if it is close to int, or else throw DOMAIN_ERROR.
virtual APL_Integer get_checked_near_int () const
Return value if it is (known to be) close to int, or else Assert()
virtual bool is_near_zero () const
return true iff value is numeric and close to 0
virtual bool is_near_one () const
return true iff value is numeric and close to 1
bool is_near_bool () const
return true iff value is numeric and close to 0 or 1
virtual bool is_near_int () const
True iff value is numeric and close to an int.
virtual bool is_near_int64_t () const
True iff value is numeric and close to an int.
virtual bool is_near_real () const
return true iff value is numeric and close to a real number
virtual int CDR_size () const
return the minimum number of data bytes to store this cell in CDR format. The actual number of data bytes can be bigger if other cells need more bytes,
virtual void release (const char *loc)
Release content pointed to (complex, APL value)
virtual bool is_integer_cell () const
Return true iff this cell is an integer cell.
bool is_simple_cell () const
Return true iff this cell is a numeric cor character cell.
virtual bool is_float_cell () const
Return true iff this cell is a floating point cell.
virtual bool is_character_cell () const
Return true iff this cell is a character cell.
virtual bool is_pointer_cell () const
Return true iff this cell is a pointer (to a sub-array) cell.
virtual bool is_lval_cell () const
Return true iff this cell is a pointer to a cell.
virtual bool is_picked_lval_cell () const
Return true iff this cell is a pointer to a cell from pick()
virtual bool is_complex_cell () const
Return true iff this cell is a complex number cell.
virtual bool is_numeric () const
Return true iff this cell is an integer, float, or complex cell.
virtual bool is_real_cell () const
Return true iff this cell is an integer or float cell.
virtual bool is_finite () const
Return true unless this cell contains infinity or NaN.
virtual bool is_example_field () const
Return true iff this cell is an example field character cell.
virtual bool is_member_anchor () const
Return true iff this is a PointerCell which pouints to a member value.
virtual CellType get_cell_type () const
return the type of this cell
virtual CellType get_cell_subtype () const
return the subtype of this cell. The subtype is the set of containers that can store the cell (only for Int and Char cells).
virtual const char * get_classname () const
return the name of the class
virtual ErrorCode bif_ceiling (Cell *Z) const
round the value of this Cell up and store the result in Z
virtual ErrorCode bif_conjugate (Cell *Z) const
conjugate the value of this Cell and store the result in Z
virtual ErrorCode bif_direction (Cell *Z) const
store the direction (sign) of this Cell in Z
virtual ErrorCode bif_exponential (Cell *Z) const
store e to the power of the value of this Cell in Z
virtual ErrorCode bif_factorial (Cell *Z) const
store the factorial (N!) of the value of this Cell in Z
virtual ErrorCode bif_floor (Cell *Z) const
Round the value of this Cell down and store the result in Z.
virtual ErrorCode bif_magnitude (Cell *Z) const
store the absolute value of this Cell in Z
virtual ErrorCode bif_nat_log (Cell *Z) const
store the base e logarithm of the value of this Cell in Z
virtual ErrorCode bif_negative (Cell *Z) const
store the negative of the value of this Cell in Z
virtual ErrorCode bif_not (Cell *Z) const
store the logical complement of the value of this Cell in Z
virtual ErrorCode bif_not_bitwise (Cell *Z) const
store the bitwise complement of the value of this Cell in Z
virtual ErrorCode bif_near_int64_t (Cell *Z) const
store the nearby integer of the value of this Cell in Z
virtual ErrorCode bif_within_quad_CT (Cell *Z) const
store the nearby integer of the value of this Cell in Z
virtual ErrorCode bif_pi_times (Cell *Z) const
store pi times the value of this Cell in Z
virtual ErrorCode bif_pi_times_inverse (Cell *Z) const
store pi times the value of this Cell in Z
virtual ErrorCode bif_reciprocal (Cell *Z) const
store the reciprocal of the value of this Cell in Z
virtual ErrorCode bif_roll (Cell *Z) const
store a random number between 1 and the value of this Cell in Z
virtual ErrorCode bif_add (Cell *Z, const Cell *A) const
store the sum of A and this cell in Z
virtual ErrorCode bif_and (Cell *Z, const Cell *A) const
store the logical and of A and this cell in Z
virtual ErrorCode bif_and_bitwise (Cell *Z, const Cell *A) const
store the bitwise and of A and this cell in Z
virtual ErrorCode bif_binomial (Cell *Z, const Cell *A) const
store the binomial (n over k) of A and this cell in Z
virtual ErrorCode bif_subtract (Cell *Z, const Cell *A) const
store the difference between A and this cell in Z
virtual ErrorCode bif_divide (Cell *Z, const Cell *A) const
store the quotient between A and this cell in Z
virtual Comp_result compare (const Cell &other) const
compare this with other, throw DOMAIN ERROR on illegal comparisons
ErrorCode bif_equal (Cell *Z, const Cell *A) const
store 1 in Z if A == the value of this cell in Z, else 0
virtual ErrorCode bif_equal_bitwise (Cell *Z, const Cell *A) const
bitwise comparison of *this and A
virtual ErrorCode bif_not_equal_bitwise (Cell *Z, const Cell *A) const
bitwise comparison of *this and A
ErrorCode bif_not_equal (Cell *Z, const Cell *A) const
store 1 in Z if A != the value of this cell in Z, else 0
ErrorCode bif_greater_than (Cell *Z, const Cell *A) const
store 1 in Z if A > the value of this cell in Z, else 0
ErrorCode bif_less_eq (Cell *Z, const Cell *A) const
store 1 in Z if A <= the value of this cell in Z, else 0
ErrorCode bif_less_than (Cell *Z, const Cell *A) const
store 1 in Z if A < the value of this cell in Z, else 0
ErrorCode bif_greater_eq (Cell *Z, const Cell *A) const
store 1 in Z if A is >= the value of this cell in Z, else 0
virtual ErrorCode bif_logarithm (Cell *Z, const Cell *A) const
store the base A logarithm of this cell in Z
virtual ErrorCode bif_maximum (Cell *Z, const Cell *A) const
store the larger of A and of this cell in Z
virtual ErrorCode bif_minimum (Cell *Z, const Cell *A) const
store the smaller of A and of this cell in Z
virtual ErrorCode bif_multiply (Cell *Z, const Cell *A) const
store the product of A and this cell in Z
virtual ErrorCode bif_nand (Cell *Z, const Cell *A) const
store the logical nand of A and this cell in Z
virtual ErrorCode bif_nand_bitwise (Cell *Z, const Cell *A) const
store the bitwise nand of A and this cell in Z
virtual ErrorCode bif_nor (Cell *Z, const Cell *A) const
store the logical NOR of A and this cell in Z
virtual ErrorCode bif_nor_bitwise (Cell *Z, const Cell *A) const
store the bitwise NOR of A and this cell in Z
virtual ErrorCode bif_or (Cell *Z, const Cell *A) const
store the logical OR of A and this cell in Z
virtual ErrorCode bif_or_bitwise (Cell *Z, const Cell *A) const
store the bitwise or of A and this cell in Z
virtual ErrorCode bif_power (Cell *Z, const Cell *A) const
store A to the power of this cell in Z
virtual ErrorCode bif_residue (Cell *Z, const Cell *A) const
store A modulo this cell in Z
virtual ErrorCode bif_circle_fun (Cell *Z, const Cell *A) const
store a circle function (according to A) of this cell in Z
virtual ErrorCode bif_circle_fun_inverse (Cell *Z, const Cell *A) const
store a circle function (according to A) of this cell in Z
virtual ErrorCode bif_add_inverse (Cell *Z, const Cell *A) const
the inverse of bif_add
virtual ErrorCode bif_multiply_inverse (Cell *Z, const Cell *A) const
the inverse of bif_bif_multiply
void * operator new (std::size_t, void *)
placement new
const void * get_u0 () const
raw pointer to the primary value (for 27 ⎕CR)
const void * get_u1 () const
raw pointer to the secondary value (for 28 ⎕CR)
Static Public Member Functions
static bool is_big (APL_Float val, int quad_pp)
return true if the integer part of val is longer than ⎕PP
static bool need_scaling (APL_Float val, int quad_pp)
Return true iff the (fixed point) floating point number num shall be printed in scaled form (like 1.2E6).
static void map_FC (UCS_string &ucs)
replace normal chars by special chars specified in ⎕FC
static APL_Integer gcd (APL_Integer m, APL_Integer n)
greatest common divisor, Knuth Vol. 1 p. 14
Static Public Member Functions inherited from NumericCell
static ErrorCode zV (Cell *Z, APL_Float flt)
initialize the (un-initialized) Cell *Z to (if possible) an IntCell or else to a FloatCell with value flt.
static ErrorCode zV (Cell *Z, APL_Complex cpx)
initialize the (un-initialized) Cell *Z to (if possible) an IntCell, a FloatCell, or a ComplexCell with value cpx.
static ErrorCode zV (Cell *Z, APL_Float real, APL_Float imag)
initialize the (un-initialized) Cell *Z to (if possible) an IntCell, a FloatCell, or a ComplexCell with value cpx.
Static Public Member Functions inherited from Cell
static bool A_greater_B (const Cell *const &A, const Cell *const &B, const void *unused_comp_arg)
like greater() but static
static bool same_half_plane (APL_Complex A, APL_Complex B)
ISO p.15: return true if A and B are on the same half-plane.
static bool tolerantly_equal (APL_Float A, APL_Float B, double qct)
ISO p.19: return true if real A is tolerantly equal to real B within C.
static bool tolerantly_equal (APL_Complex A, APL_Complex B, double qct)
ISO p. 19: return true if complex A and B are tolerantly equal within real qct.
static bool integral_within (APL_Float A, double qct)
ISO p. 19: A is integral (close to a Gaussian Integer) within qct.
static bool sum_overflow (APL_Integer z, APL_Integer a, APL_Integer b)
return true if z = a + b had an overflow.
static bool diff_overflow (APL_Integer z, APL_Integer a, APL_Integer b)
return true if z = a - b had an overflow.
static bool prod_overflow (int64_t a, int64_t b)
return true if multiplying a and b will (probably) overflow. For some huge a or b the result may incorrectly return true. a or b the result may incorrectly return true.
static void copy (Cell *&dst, const Cell *&src, ShapeItem count, Value &cell_owner)
copy (deep) count cells from src to dest)
static void copy (Value &val, const Cell *&src, ShapeItem count)
copy (deep) count cells from src to val (which is under construction))
static bool is_near_int (APL_Float value)
true iff value is close to an int (within +- qct)
static bool is_near_int64_t (APL_Float value)
true iff value is close to an int64_t (i.e. fots into an int64_t
static bool is_near_zero (APL_Float value)
true iff value is close to 0 (within +- qct)
static APL_Integer near_int (APL_Float value)
return value if it is close to int, or else throw DOMAIN_ERROR
static bool greater_cp (const ShapeItem &a, const ShapeItem &b, const void *cells)
compare cells[a] and cells[b] ascendingly
static bool smaller_cp (const ShapeItem &a, const ShapeItem &b, const void *cells)
compare cells[a] and cells[b] descendingly
static bool compare_stable (const Cell *const &A, const Cell *const &B, const void *comp_arg)
a stable compare function to be used with Heapsort. Equal cells are compared by their address. Return true iff A > B or A = B and &A > &B.
static bool compare_ptr (const Cell *const &A, const Cell *const &B, const void *comp_arg)
a stable compare function to be used with Heapsort. The cell contents are ignored and only the cell addresses are being compared. Return true iff &A > &B.
static ShapeItem * sorted_indices (const Cell *ravel, ShapeItem length, Sort_order order, ShapeItem comp_len)
return length indices i1, i2, ... iN so that ravel[i1] < ravel[i2] < ... < ravel[iN]. The indices are 0-based and the caller must delete[] the result. Returns 0 on error (= WS FULL).
static const char * get_cell_type_name (CellType ct)
the name of ct
Protected Member Functions
virtual CellType get_cell_type () const
Overloaded Cell::get_cell_type().
virtual APL_Float get_real_value () const
Overloaded Cell::get_real_value().
virtual APL_Float get_imag_value () const
Overloaded Cell::get_imag_value().
virtual APL_Complex get_complex_value () const
Overloaded Cell::get_complex_value()
virtual bool get_near_bool () const
Overloaded Cell::get_near_bool().
virtual APL_Integer get_near_int () const
Overloaded Cell::get_near_int().
virtual APL_Integer get_checked_near_int () const
Overloaded Cell::get_checked_near_int().
virtual bool is_near_int () const
Overloaded Cell::is_near_int().
virtual bool is_near_int64_t () const
Overloaded Cell::is_near_int64_t().
virtual ErrorCode bif_near_int64_t (Cell *Z) const
overloaded Cell::bif_near_int()
virtual ErrorCode bif_within_quad_CT (Cell *Z) const
overloaded Cell::bif_within_quad_CT()
virtual bool is_near_zero () const
Overloaded Cell::is_near_zero().
virtual bool is_near_one () const
Overloaded Cell::is_near_one().
virtual bool is_near_real () const
Overloaded Cell::is_near_real().
virtual const char * get_classname () const
Overloaded Cell::get_classname().
virtual int CDR_size () const
Overloaded Cell::CDR_size()
virtual const FloatCell & cFloatCell () const
downcast to const FloatCell
virtual FloatCell & vFloatCell ()
downcast to FloatCell
Protected Member Functions inherited from RealCell
virtual bool is_real_cell () const
overloaded Cell::is_real_cell().
virtual ErrorCode bif_circle_fun (Cell *Z, const Cell *A) const
overloaded Cell::bif_circle_fun().
virtual ErrorCode bif_circle_fun_inverse (Cell *Z, const Cell *A) const
overloaded Cell::bif_circle_fun_inverse().
ErrorCode do_bif_circle_fun (Cell *Z, int fun) const
compute circle function fun
virtual ErrorCode bif_logarithm (Cell *Z, const Cell *A) const
overloaded Cell::bif_logarithm().
virtual const char * get_classname () const
overloaded Cell::get_classname().
Protected Member Functions inherited from NumericCell
virtual bool is_numeric () const
overloaded Cell::is_numeric()
virtual ErrorCode bif_not (Cell *Z) const
overloaded Cell::bif_not()
virtual ErrorCode bif_not_bitwise (Cell *Z) const
overloaded Cell::bif_not_bitwise()
virtual ErrorCode bif_and (Cell *Z, const Cell *A) const
overloaded Cell::bif_and()
virtual ErrorCode bif_and_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_and_bitwise()
virtual ErrorCode bif_equal_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_equal_bitwise()
virtual ErrorCode bif_not_equal_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_not_equal_bitwise()
virtual ErrorCode bif_binomial (Cell *Z, const Cell *A) const
overloaded Cell::bif_binomial()
virtual ErrorCode bif_nand (Cell *Z, const Cell *A) const
overloaded Cell::bif_nand()
virtual ErrorCode bif_nand_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_nand_bitwise()
virtual ErrorCode bif_nor (Cell *Z, const Cell *A) const
overloaded Cell::bif_nor()
virtual ErrorCode bif_nor_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_nor_bitwise()
virtual ErrorCode bif_or (Cell *Z, const Cell *A) const
overloaded Cell::bif_or()
virtual ErrorCode bif_or_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_or_bitwise()
virtual const char * get_classname () const
overloaded Cell::get_classname()
ErrorCode complex_binomial (Cell *Z, const Cell *A) const
N over K for complex A and/or B.
ErrorCode real_binomial (Cell *Z, const Cell *A) const
N over K for non-integer A and/or B.
Static Protected Member Functions
static ErrorCode zF (Cell *Z, APL_Float flt)
initialize the (un-initialized) Cell *Z to APL_Float flt
Static Protected Member Functions inherited from NumericCell
static ErrorCode K33_binomial (Cell *Z, APL_Integer N, APL_Integer K, bool negate)
compute binomial funtion for integers a and b
static ErrorCode int_gcd (APL_Integer &z, APL_Integer a, APL_Integer b)
return the greatest common divisor of integers a and b
static ErrorCode flt_gcd (APL_Float &z, APL_Float a, APL_Float b, double qct)
return the greatest common divisor of real a and b
static ErrorCode integer_binomial (Cell *Z, APL_Integer N, APL_Integer K, bool negate)
N over K for positive integers N and K.
static ErrorCode cpx_gcd (APL_Complex &z, APL_Complex a, APL_Complex b, double qct)
return the greatest common divisor of complex a and b
static APL_Complex cpx_max_real (APL_Complex a)
multiply a by 1, -1, i, or -i so that a.real is maximal
Friends
class ComplexCell
class IntCell
class NumericCell
class RealCell
class Value
Additional Inherited Members
Protected Attributes inherited from Cell
SomeValue value
the primary value of this cell
Detailed Description
A Cell containing a single floating point (or rational) value.
A cell containing a single APL floating point value. This class overloads certain functions in class Cell with floating point number specific implementations.
The actual APL floating point value is either rational (and then defined by value.numerator ÷ value.fval.denominator, or not (and then value.fval.denominator is 0 and value.fval.u1.flt contains the double value)
Definition at line 39 of file FloatCell.hh.
Constructor & Destructor Documentation
FloatCell()
FloatCell::FloatCell (APL_Float r) inline
Construct an floating point cell from a double r.
Definition at line 49 of file FloatCell.hh.
References Cell::SomeValue::_fval::denominator, Cell::SomeValue::_fval::_flt_num::flt, Cell::SomeValue::fval, Cell::SomeValue::_fval::u1, and Cell::value.
Member Function Documentation
bif_add()
ErrorCode FloatCell::bif_add (Cell * Z, const Cell * A) const virtual
Overloaded Cell::bif_add().
Reimplemented from Cell.
Definition at line 396 of file FloatCell.cc.
References gcd(), get_real_value(), Cell::prod_overflow(), Cell::sum_overflow(), zF(), and IntCell::zI().
bif_add_inverse()
ErrorCode FloatCell::bif_add_inverse (Cell * Z, const Cell * A) const virtual
overloaded Cell::bif_add_inverse()
Reimplemented from Cell.
Definition at line 443 of file FloatCell.cc.
bif_ceiling()
ErrorCode FloatCell::bif_ceiling (Cell * Z) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 265 of file FloatCell.cc.
References dfval(), Workspace::get_CT(), zF(), and IntCell::zI().
bif_conjugate()
ErrorCode FloatCell::bif_conjugate (Cell * Z) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 160 of file FloatCell.cc.
References dfval(), and zF().
bif_direction()
ErrorCode FloatCell::bif_direction (Cell * Z) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 178 of file FloatCell.cc.
References dfval(), IntCell::z0(), IntCell::z1(), IntCell::z_1(), zF(), and IntCell::zI().
bif_divide()
ErrorCode FloatCell::bif_divide (Cell * Z, const Cell * A) const virtual
Overloaded Cell::bif_divide().
Reimplemented from Cell.
Definition at line 557 of file FloatCell.cc.
References bif_multiply(), dfval(), IntCell::z1(), ComplexCell::zC(), and zF().
bif_exponential()
ErrorCode FloatCell::bif_exponential (Cell * Z) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 366 of file FloatCell.cc.
References dfval(), and zF().
bif_factorial()
ErrorCode FloatCell::bif_factorial (Cell * Z) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 149 of file FloatCell.cc.
References dfval(), and zF().
Referenced by ComplexCell::bif_factorial().
bif_floor()
ErrorCode FloatCell::bif_floor (Cell * Z) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 299 of file FloatCell.cc.
References dfval(), Workspace::get_CT(), zF(), and IntCell::zI().
bif_magnitude()
ErrorCode FloatCell::bif_magnitude (Cell * Z) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 198 of file FloatCell.cc.
References dfval(), and zF().
bif_maximum()
ErrorCode FloatCell::bif_maximum (Cell * Z, const Cell * A) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 767 of file FloatCell.cc.
References dfval(), Cell::is_integer_cell(), zF(), and IntCell::zI().
bif_minimum()
ErrorCode FloatCell::bif_minimum (Cell * Z, const Cell * A) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 790 of file FloatCell.cc.
References dfval(), Cell::is_integer_cell(), zF(), and IntCell::zI().
bif_multiply()
ErrorCode FloatCell::bif_multiply (Cell * Z, const Cell * A) const virtual
Overloaded Cell::bif_multiply().
Reimplemented from Cell.
Definition at line 499 of file FloatCell.cc.
References dfval(), gcd(), Cell::prod_overflow(), ComplexCell::zC(), zF(), and IntCell::zI().
Referenced by bif_divide().
bif_multiply_inverse()
ErrorCode FloatCell::bif_multiply_inverse (Cell * Z, const Cell * A) const virtual
overloaded Cell::bif_multiply_inverse()
Reimplemented from Cell.
Definition at line 551 of file FloatCell.cc.
bif_nat_log()
ErrorCode FloatCell::bif_nat_log (Cell * Z) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 374 of file FloatCell.cc.
References dfval(), ComplexCell::zC(), and zF().
bif_near_int64_t()
ErrorCode FloatCell::bif_near_int64_t (Cell * Z) const protected virtual
overloaded Cell::bif_near_int()
Reimplemented from Cell.
Definition at line 123 of file FloatCell.cc.
References get_near_int(), is_near_int64_t(), and IntCell::zI().
bif_negative()
ErrorCode FloatCell::bif_negative (Cell * Z) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 167 of file FloatCell.cc.
References dfval(), and zF().
bif_pi_times()
ErrorCode FloatCell::bif_pi_times (Cell * Z) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 253 of file FloatCell.cc.
References dfval(), and zF().
bif_pi_times_inverse()
ErrorCode FloatCell::bif_pi_times_inverse (Cell * Z) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 259 of file FloatCell.cc.
References dfval(), and zF().
bif_power()
ErrorCode FloatCell::bif_power (Cell * Z, const Cell * A) const virtual
Overloaded Cell::bif_power().
Reimplemented from Cell.
Definition at line 603 of file FloatCell.cc.
References dfval(), IntCell::z0(), IntCell::z1(), ComplexCell::zC(), and zF().
bif_reciprocal()
ErrorCode FloatCell::bif_reciprocal (Cell * Z) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 213 of file FloatCell.cc.
References dfval(), zF(), and IntCell::zI().
bif_residue()
ErrorCode FloatCell::bif_residue (Cell * Z, const Cell * A) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 725 of file FloatCell.cc.
References dfval(), get_real_value(), IntCell::z0(), and zF().
Referenced by IntCell::bif_residue(), and Bif_F12_ENCODE::encode_Flt().
bif_roll()
ErrorCode FloatCell::bif_roll (Cell * Z) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 241 of file FloatCell.cc.
References get_checked_near_int(), Workspace::get_IO(), Workspace::get_RL(), is_near_int(), and IntCell::zI().
bif_subtract()
ErrorCode FloatCell::bif_subtract (Cell * Z, const Cell * A) const virtual
Overloaded Cell::bif_subtract().
Reimplemented from Cell.
Definition at line 449 of file FloatCell.cc.
References Cell::diff_overflow(), gcd(), get_real_value(), Cell::prod_overflow(), ComplexCell::zC(), zF(), and IntCell::zI().
bif_within_quad_CT()
ErrorCode FloatCell::bif_within_quad_CT (Cell * Z) const protected virtual
overloaded Cell::bif_within_quad_CT()
Reimplemented from Cell.
Definition at line 131 of file FloatCell.cc.
References dfval(), Workspace::get_CT(), and zF().
CDR_size()
virtual int FloatCell::CDR_size () const inline protected virtual
Overloaded Cell::CDR_size()
Reimplemented from Cell.
Definition at line 331 of file FloatCell.hh.
cFloatCell()
virtual const FloatCell & FloatCell::cFloatCell () const inline protected virtual
downcast to const FloatCell
Definition at line 334 of file FloatCell.hh.
character_representation()
PrintBuffer FloatCell::character_representation (const PrintContext & pctx) const virtual
the Quad_CR representation of this cell.
Reimplemented from Cell.
Definition at line 816 of file FloatCell.cc.
References UCS_string::append(), ColInfo::denom_len, dfval(), ColInfo::flags, ColInfo::fract_len, UCS_string::from_uint(), PrintContext::get_scaled(), ColInfo::int_len, ColInfo::real_len, and UCS_string::size().
Referenced by ComplexCell::character_representation(), and IntCell::character_representation().
compare()
Comp_result FloatCell::compare (const Cell & other) const virtual
compare this with other, throw DOMAIN ERROR on illegal comparisons
Reimplemented from Cell.
Definition at line 97 of file FloatCell.cc.
References Cell::compare(), dfval(), equal(), Workspace::get_CT(), Cell::get_int_value(), Cell::get_real_value(), Cell::is_character_cell(), Cell::is_complex_cell(), Cell::is_float_cell(), Cell::is_integer_cell(), and Cell::is_pointer_cell().
Referenced by greater().
dfval()
APL_Float FloatCell::dfval () const inline
return the value of this cell as a double (even if the value is rational)
Definition at line 105 of file FloatCell.hh.
References Cell::SomeValue::_fval::_flt_num::flt, Cell::SomeValue::fval, Cell::SomeValue::_fval::u1, and Cell::value.
Referenced by bif_ceiling(), bif_conjugate(), bif_direction(), bif_divide(), bif_exponential(), bif_factorial(), bif_floor(), bif_magnitude(), bif_maximum(), bif_minimum(), bif_multiply(), bif_nat_log(), bif_negative(), bif_pi_times(), bif_pi_times_inverse(), bif_power(), bif_reciprocal(), bif_residue(), bif_within_quad_CT(), character_representation(), compare(), get_checked_near_int(), get_complex_value(), get_near_bool(), get_near_int(), get_real_value(), init_other(), is_finite(), is_near_int(), is_near_int64_t(), is_near_one(), is_near_zero(), and need_scaling().
equal()
bool FloatCell::equal (const Cell & other, double qct) const virtual
Overloaded Cell::equal().
Reimplemented from Cell.
Definition at line 40 of file FloatCell.cc.
References get_real_value(), and Cell::tolerantly_equal().
Referenced by compare().
gcd()
static APL_Integer FloatCell::gcd (APL_Integer m, APL_Integer n) inline static
greatest common divisor, Knuth Vol. 1 p. 14
Definition at line 219 of file FloatCell.hh.
Referenced by bif_add(), IntCell::bif_divide(), bif_multiply(), bif_subtract(), and NumericCell::int_gcd().
get_cell_type()
virtual CellType FloatCell::get_cell_type () const inline protected virtual
Overloaded Cell::get_cell_type().
Reimplemented from Cell.
Definition at line 272 of file FloatCell.hh.
get_checked_near_int()
virtual APL_Integer FloatCell::get_checked_near_int () const inline protected virtual
Overloaded Cell::get_checked_near_int().
Reimplemented from Cell.
Definition at line 293 of file FloatCell.hh.
References dfval().
Referenced by bif_roll().
get_classname()
virtual const char * FloatCell::get_classname () const inline protected virtual
Overloaded Cell::get_classname().
Reimplemented from RealCell.
Definition at line 328 of file FloatCell.hh.
get_complex_value()
virtual APL_Complex FloatCell::get_complex_value () const inline protected virtual
Overloaded Cell::get_complex_value()
Reimplemented from Cell.
Definition at line 282 of file FloatCell.hh.
References dfval().
get_imag_value()
virtual APL_Float FloatCell::get_imag_value () const inline protected virtual
Overloaded Cell::get_imag_value().
Reimplemented from Cell.
Definition at line 279 of file FloatCell.hh.
get_near_bool()
bool FloatCell::get_near_bool () const protected virtual
Overloaded Cell::get_near_bool().
Reimplemented from Cell.
Definition at line 81 of file FloatCell.cc.
References dfval().
get_near_int()
virtual APL_Integer FloatCell::get_near_int () const inline protected virtual
Overloaded Cell::get_near_int().
Reimplemented from Cell.
Definition at line 289 of file FloatCell.hh.
References dfval(), and Cell::near_int().
Referenced by bif_near_int64_t().
get_real_value()
virtual APL_Float FloatCell::get_real_value () const inline protected virtual
Overloaded Cell::get_real_value().
Reimplemented from Cell.
Definition at line 276 of file FloatCell.hh.
References dfval().
Referenced by bif_add(), bif_residue(), bif_subtract(), equal(), and greater().
greater()
bool FloatCell::greater (const Cell & other) const virtual
Overloaded Cell::greater().
Reimplemented from Cell.
Definition at line 48 of file FloatCell.cc.
References compare(), Cell::get_cell_type(), Cell::get_int_value(), Cell::get_real_value(), and get_real_value().
init_other()
virtual void FloatCell::init_other (void * other, Value & cell_owner, const char * loc) const inline virtual
overloaded Cell::init_other
Reimplemented from Cell.
Definition at line 100 of file FloatCell.hh.
References dfval().
is_big()
bool FloatCell::is_big (APL_Float val, int quad_pp) static
return true if the integer part of val is longer than ⎕PP
Definition at line 881 of file FloatCell.cc.
Referenced by need_scaling().
is_finite()
virtual bool FloatCell::is_finite () const inline virtual
Overloaded Cell::is_finite().
Reimplemented from Cell.
Definition at line 120 of file FloatCell.hh.
References dfval().
is_float_cell()
virtual bool FloatCell::is_float_cell () const inline virtual
Overloaded Cell::is_float_cell().
Reimplemented from Cell.
Definition at line 117 of file FloatCell.hh.
is_near_int()
virtual bool FloatCell::is_near_int () const inline protected virtual
Overloaded Cell::is_near_int().
Reimplemented from Cell.
Definition at line 300 of file FloatCell.hh.
References dfval(), and Cell::is_near_int().
Referenced by bif_roll().
is_near_int64_t()
virtual bool FloatCell::is_near_int64_t () const inline protected virtual
Overloaded Cell::is_near_int64_t().
Reimplemented from Cell.
Definition at line 304 of file FloatCell.hh.
References dfval(), and Cell::is_near_int64_t().
Referenced by bif_near_int64_t().
is_near_one()
virtual bool FloatCell::is_near_one () const inline protected virtual
Overloaded Cell::is_near_one().
Reimplemented from Cell.
Definition at line 319 of file FloatCell.hh.
References dfval().
is_near_real()
virtual bool FloatCell::is_near_real () const inline protected virtual
Overloaded Cell::is_near_real().
Reimplemented from Cell.
Definition at line 324 of file FloatCell.hh.
is_near_zero()
virtual bool FloatCell::is_near_zero () const inline protected virtual
Overloaded Cell::is_near_zero().
Reimplemented from Cell.
Definition at line 314 of file FloatCell.hh.
References dfval().
map_FC()
void FloatCell::map_FC (UCS_string & ucs) static
replace normal chars by special chars specified in ⎕FC
Definition at line 931 of file FloatCell.cc.
References Workspace::get_FC(), and UCS_string::size().
Referenced by UCS_string::UCS_string().
need_scaling() [1/2]
bool FloatCell::need_scaling (APL_Float val, int quad_pp) static
Return true iff the (fixed point) floating point number num shall be printed in scaled form (like 1.2E6).
Definition at line 909 of file FloatCell.cc.
References is_big().
need_scaling() [2/2]
virtual bool FloatCell::need_scaling (const PrintContext & pctx) const inline virtual
return true iff this cell needs scaling (exponential format) in pctx.
Reimplemented from Cell.
Definition at line 199 of file FloatCell.hh.
References dfval(), PrintContext::get_PP(), and need_scaling().
Referenced by ComplexCell::need_scaling(), and need_scaling().
vFloatCell()
virtual FloatCell & FloatCell::vFloatCell () inline protected virtual
downcast to FloatCell
Definition at line 337 of file FloatCell.hh.
zF()
static ErrorCode FloatCell::zF (Cell * Z, APL_Float flt) inline static protected
initialize the (un-initialized) Cell *Z to APL_Float flt
Definition at line 261 of file FloatCell.hh.
Referenced by bif_add(), IntCell::bif_add(), NumericCell::bif_and(), bif_ceiling(), bif_conjugate(), bif_direction(), bif_divide(), IntCell::bif_divide(), bif_exponential(), IntCell::bif_exponential(), bif_factorial(), IntCell::bif_factorial(), bif_floor(), RealCell::bif_logarithm(), ComplexCell::bif_magnitude(), bif_magnitude(), ComplexCell::bif_maximum(), bif_maximum(), ComplexCell::bif_minimum(), bif_minimum(), bif_multiply(), IntCell::bif_multiply(), bif_nat_log(), IntCell::bif_nat_log(), ComplexCell::bif_near_int64_t(), bif_negative(), NumericCell::bif_or(), bif_pi_times(), IntCell::bif_pi_times(), bif_pi_times_inverse(), IntCell::bif_pi_times_inverse(), bif_power(), IntCell::bif_power(), ComplexCell::bif_reciprocal(), bif_reciprocal(), IntCell::bif_reciprocal(), bif_residue(), IntCell::bif_residue(), bif_subtract(), IntCell::bif_subtract(), bif_within_quad_CT(), RealCell::do_bif_circle_fun(), NumericCell::integer_binomial(), and NumericCell::real_binomial().
Friends And Related Function Documentation
ComplexCell
friend class ComplexCell friend
Definition at line 41 of file FloatCell.hh.
IntCell
friend class IntCell friend
Definition at line 42 of file FloatCell.hh.
NumericCell
friend class NumericCell friend
Definition at line 43 of file FloatCell.hh.
RealCell
friend class RealCell friend
Definition at line 44 of file FloatCell.hh.
Value
friend class Value friend
Definition at line 45 of file FloatCell.hh.
The documentation for this class was generated from the following files:
src/FloatCell.hh
src/FloatCell.cc