GNU APL: Avec Class Reference
Avec Class Reference
Static helper functions related to ⎕AV, character clasification, etc.
#include <Avec.hh>
Classes
struct Character_definition
Various character attributes.
struct Unicode_to_IBM_codepoint
a Unicode and its position in the ⎕AV of IBM APL2
Public Types
enum CHT_Index {
Invalid_CHT = -1 ,
MAX_AV
}
The valid indices in the Atomic Vector of the APL interpreter. Only char_def() entries are used, char_uni() entries are ignored entirely.
Static Public Member Functions
static void init ()
initialize the static tables of this class and check them
static Unicode unicode (CHT_Index av)
Return the UNICODE of char table entry av.
static uint32_t get_av_pos (CHT_Index av)
Return the UNICODE of char table entry av.
static Token uni_to_token (Unicode &av, const char *loc)
Return a token containing av.
static bool is_symbol_char (Unicode av)
Return true iff av is a valid char in a user defined symbol.
static bool is_white (Unicode av)
return true iff av is a whitespace char (ASCII 0..32 (including))
static bool is_single_quote (Unicode av)
return true iff av is one of the single quote characters ' ‘ or ’
static bool is_diamond (Unicode av)
return true iff av is one of the various diamond characters
static bool is_control (Unicode av)
return true iff av is a control char (ASCII 0..32 (excluding))
static bool is_comment (Unicode av)
return true iff av is a comment char (⍝ or #)
static bool is_first_symbol_char (Unicode uni)
Return true iff av is a valid char in a user defined symbol.
static bool is_digit (Unicode uni)
Return true iff av is a digit (i.e. 0 ≤ av ≤ 9)
static bool is_hex_digit (Unicode uni)
Return true iff av is a digit (i.e. 0 ≤ av ≤ 9)
static bool is_digit_or_space (Unicode uni)
Return true iff av is a digit or a space.
static bool is_number (Unicode uni)
return true iff av is a number char (digit, .)
static Unicode make_standard (Unicode uni)
map possibly non-standard APL character to its standard character
static bool is_known_char (Unicode uni)
return true if unicode is defined by a char_def() or char_uni() macro
static bool is_quad (Unicode uni)
return true if unicode uni is a quad (⎕ or ▯)
static int digit_value (Unicode uni, bool hex)
return the value (0..9 if decimal, or 0..15 if hex) for uni, or -1 if uni is not a decimal or hex digit.
static bool need_UCS (Unicode uni)
return true if unicode uni needs ⎕UCS in 2 ⎕TF or)OUT
static bool no_space_after (Unicode uni)
return true iff a token printed after av never needs a space
static bool no_space_before (Unicode av)
return true iff a token printed before av never needs a space
static Unicode subscript (uint32_t i)
return the subscript char for digit i (i = 0..9)
static Unicode superscript (uint32_t i)
return the superscript char for digit i (i = 0..9)
static uint32_t find_av_pos (Unicode av)
Find av in character_table. Return AV position if found or MAX_AV.
static CHT_Index find_char (Unicode av)
Find av in character_table. Return position or Invalid_CHT.
static CHT_Index map_alternative_char (Unicode alt_av)
Find return position of alt_av, or Invalid_AV if not found.
static const Unicode * IBM_quad_AV ()
a pointer to 256 Unicode characters that are exactly the APL2 character set (⎕AV) shown in lrm Appendix A page 470. The ⎕AV of GNU APL is similar, but contains characters like ≢ that are not in IBM's ⎕AV IBM's ⎕AV is used in the)IN command
static unsigned char unicode_to_cp (Unicode uni)
search uni in inverse_ibm_av and return its position in the IBM ⎕AV (= its code in .ATF files). Return 0xB0 if not found.
static void print_inverse_IBM_quad_AV ()
recompute inverse_ibm_av from ibm_av and print it
Protected Types
enum CharacterFlag {
FLG_NONE = 0x0000 ,
FLG_SYMBOL = 0x0001 ,
FLG_DIGIT = 0x0002 ,
FLG_NO_SPACE_AFTER = 0x0004 ,
FLG_NO_SPACE_BEFORE = 0x0008 ,
FLG_NO_SPACE = FLG_NO_SPACE_AFTER | FLG_NO_SPACE_BEFORE ,
FLG_NUMERIC = FLG_DIGIT | FLG_SYMBOL
}
Some flags helping to classify characters.
Static Protected Member Functions
static int show_error_pos (int i, int line, bool cond, int def_line)
print an error position on cerr, and then Assert(0);
static void check_av_table ()
check that the character table that is used in this class is correct
static void check_file (const char *filename)
check that all characters in the UTF-8 encoded file are known (through char_def() or char_uni() macros)
static int compare_uni (const void *u1, const void *u2)
compare the unicodes of two entries ua and u2 in inverse_IBM_quad_AV
Static Protected Attributes
static const Character_definition character_table [MAX_AV]
a table defining the properties of every character in ⎕AV. Only characters defined with char_def() (i.e. not those defined with char_uni()) are in this table.
static Unicode_to_IBM_codepoint inverse_ibm_av []
Unicode_to_IBM_codepoint table sorted by Unicode (for bsearch())
Detailed Description
Static helper functions related to ⎕AV, character clasification, etc.
class Avec is a collection of static functions related to the Atomic Vector of the APL interpreter
Definition at line 33 of file Avec.hh.
Member Enumeration Documentation
CharacterFlag
enum Avec::CharacterFlag protected
Some flags helping to classify characters.
Enumerator
FLG_NONE
no flag
FLG_SYMBOL
valid char in a user defined name
FLG_DIGIT
0-9
FLG_NO_SPACE_AFTER
never need a space after this char
FLG_NO_SPACE_BEFORE
never need a space before this char
FLG_NUMERIC
0-9, A-Z, a-z, ∆, ⍙
Definition at line 159 of file Avec.hh.
CHT_Index
enum Avec::CHT_Index
The valid indices in the Atomic Vector of the APL interpreter. Only char_def() entries are used, char_uni() entries are ignored entirely.
Definition at line 41 of file Avec.hh.
Member Function Documentation
compare_uni()
int Avec::compare_uni (const void * u1, const void * u2) static protected
compare the unicodes of two entries ua and u2 in inverse_IBM_quad_AV
compare the unicodes of two chars in the IBM ⎕AV
Definition at line 630 of file Avec.cc.
References Avec::Unicode_to_IBM_codepoint::uni.
Referenced by unicode_to_cp().
digit_value()
int Avec::digit_value (Unicode uni, bool hex) static
return the value (0..9 if decimal, or 0..15 if hex) for uni, or -1 if uni is not a decimal or hex digit.
Definition at line 338 of file Avec.cc.
Referenced by XML_node::normalize_attribute_value().
find_av_pos()
uint32_t Avec::find_av_pos (Unicode av) static
Find av in character_table. Return AV position if found or MAX_AV.
Definition at line 245 of file Avec.cc.
References Avec::Character_definition::av_pos, character_table, and find_char().
Referenced by Quad_AF::eval_B().
find_char()
Avec::CHT_Index Avec::find_char (Unicode av) static
Find av in character_table. Return position or Invalid_CHT.
Definition at line 255 of file Avec.cc.
References character_table, and Avec::Character_definition::unicode.
Referenced by find_av_pos(), Value::is_apl_char_vector(), is_symbol_char(), need_UCS(), no_space_after(), no_space_before(), uni_to_token(), and XML_Saving_Archive::xml_allowed().
get_av_pos()
uint32_t Avec::get_av_pos (CHT_Index av) static
Return the UNICODE of char table entry av.
Definition at line 208 of file Avec.cc.
References Avec::Character_definition::av_pos, and character_table.
Referenced by Quad_AV::Quad_AV().
IBM_quad_AV()
const Unicode * Avec::IBM_quad_AV () static
a pointer to 256 Unicode characters that are exactly the APL2 character set (⎕AV) shown in lrm Appendix A page 470. The ⎕AV of GNU APL is similar, but contains characters like ≢ that are not in IBM's ⎕AV IBM's ⎕AV is used in the)IN command
Definition at line 498 of file Avec.cc.
Referenced by Command::transfer_context::add(), and Quad_FIO::eval_B().
init()
void Avec::init () static
initialize the static tables of this class and check them
Definition at line 195 of file Avec.cc.
Referenced by Parallel::init(), and init_apl().
is_comment()
static bool Avec::is_comment (Unicode av) inline static
return true iff av is a comment char (⍝ or #)
Definition at line 82 of file Avec.hh.
Referenced by Quad_PLOT::parse_attributes().
is_control()
static bool Avec::is_control (Unicode av) inline static
return true iff av is a control char (ASCII 0..32 (excluding))
Definition at line 78 of file Avec.hh.
Referenced by need_UCS().
is_diamond()
static bool Avec::is_diamond (Unicode av) inline static
return true iff av is one of the various diamond characters
Definition at line 73 of file Avec.hh.
Referenced by Executable::statement_text().
is_digit()
static bool Avec::is_digit (Unicode uni) inline static
Return true iff av is a digit (i.e. 0 ≤ av ≤ 9)
Definition at line 89 of file Avec.hh.
Referenced by Command::cmd_COPY(), Command::cmd_COPY_ONCE(), Command::cmd_DUMP(), Command::cmd_SAVE(), DiffOut::different(), Tokenizer::do_tokenize(), Doxy::Doxy(), Format_sub::insert_fract_commas(), Format_sub::insert_int_commas(), Bif_F12_FORMAT::is_control_char(), is_digit_or_space(), is_first_symbol_char(), is_hex_digit(), Command::is_lib_ref(), is_number(), Command::open_LIB_dir(), Nabla::parse_lineno(), Nabla::parse_oper(), Command::resolve_lib_wsname(), File_or_String::scanf_long_long(), Plot_window_properties::set_attribute(), Bif_F12_FORMAT::split_example_into_columns(), Quad_TF::tf1_inv(), and Tokenizer::tokenize_real().
is_digit_or_space()
static bool Avec::is_digit_or_space (Unicode uni) inline static
Return true iff av is a digit or a space.
Definition at line 99 of file Avec.hh.
References is_digit(), and is_white().
is_first_symbol_char()
bool Avec::is_first_symbol_char (Unicode uni) static
Return true iff av is a valid char in a user defined symbol.
Definition at line 374 of file Avec.cc.
References is_digit(), and is_symbol_char().
Referenced by InputFile::check_filter(), Command::cmd_HELP(), TabExpansion::expand_tab(), Quad_NC::get_NC(), Nabla::start(), and Quad_TF::tf1_inv().
is_hex_digit()
static bool Avec::is_hex_digit (Unicode uni) inline static
Return true iff av is a digit (i.e. 0 ≤ av ≤ 9)
Definition at line 93 of file Avec.hh.
References is_digit().
Referenced by Tokenizer::tokenize_real().
is_known_char()
bool Avec::is_known_char (Unicode uni) static
return true if unicode is defined by a char_def() or char_uni() macro
Definition at line 320 of file Avec.cc.
is_number()
static bool Avec::is_number (Unicode uni) inline static
return true iff av is a number char (digit, .)
Definition at line 103 of file Avec.hh.
References is_digit().
is_quad()
static bool Avec::is_quad (Unicode uni) inline static
return true if unicode uni is a quad (⎕ or ▯)
Definition at line 113 of file Avec.hh.
Referenced by Command::transfer_context::chars_1TF(), InputFile::check_filter(), Tokenizer::do_tokenize(), Quad_AT::eval_AB(), Executable::Executable(), NamedObject::get_NC(), Quad_NC::get_NC(), Workspace::get_quad(), Quad_TF::is_inverse(), Workspace::lookup_existing_name(), Workspace::lookup_existing_symbol(), SymbolTable::lookup_symbol(), Command::transfer_context::numeric_1TF(), XML_Loading_Archive::read_Token(), Quad_TF::tf1_inv(), and UCS_string_vector::UCS_string_vector().
is_single_quote()
static bool Avec::is_single_quote (Unicode av) inline static
return true iff av is one of the single quote characters ' ‘ or ’
Definition at line 67 of file Avec.hh.
Referenced by Tokenizer::tokenize_string1().
is_symbol_char()
bool Avec::is_symbol_char (Unicode av) static
Return true iff av is a valid char in a user defined symbol.
Definition at line 366 of file Avec.cc.
References character_table, find_char(), and FLG_SYMBOL.
Referenced by Command::cmd_USERCMD(), Quad_SVO::eval_AB(), Quad_EX::eval_B(), Executable::Executable(), Quad_NC::get_NC(), Workspace::get_quad(), UCS_string::is_comment_or_label(), is_first_symbol_char(), Quad_TF::is_inverse(), Command::lib_common(), Quad_TF::tf1_inv(), Tokenizer::tokenize_symbol(), and UCS_string_vector::UCS_string_vector().
is_white()
static bool Avec::is_white (Unicode av) inline static
return true iff av is a whitespace char (ASCII 0..32 (including))
Definition at line 63 of file Avec.hh.
Referenced by UCS_string::atoi(), Doxy::Doxy(), Quad_EX::eval_B(), UCS_string::has_black(), is_digit_or_space(), Nabla::parse_oper(), UCS_string::split_ws(), and Nabla::start().
make_standard()
Unicode Avec::make_standard (Unicode uni) static
map possibly non-standard APL character to its standard character
Definition at line 313 of file Avec.cc.
References character_table, map_alternative_char(), and Avec::Character_definition::unicode.
Referenced by Command::cmd_HELP().
map_alternative_char()
Avec::CHT_Index Avec::map_alternative_char (Unicode alt_av) static
Find return position of alt_av, or Invalid_AV if not found.
Definition at line 273 of file Avec.cc.
Referenced by make_standard(), uni_to_token(), and XML_Saving_Archive::xml_allowed().
need_UCS()
bool Avec::need_UCS (Unicode uni) static
return true if unicode uni needs ⎕UCS in 2 ⎕TF or)OUT
Definition at line 353 of file Avec.cc.
References find_char(), is_control(), and unicode_to_cp().
Referenced by Quad_TF::tf2_all_char_ravel(), and Quad_TF::tf2_char_vec().
no_space_after()
bool Avec::no_space_after (Unicode uni) static
return true iff a token printed after av never needs a space
Definition at line 380 of file Avec.cc.
References character_table, find_char(), and FLG_NO_SPACE_AFTER.
Referenced by Token::error_info().
no_space_before()
bool Avec::no_space_before (Unicode av) static
return true iff a token printed before av never needs a space
Definition at line 388 of file Avec.cc.
References character_table, find_char(), and FLG_NO_SPACE_BEFORE.
Referenced by Token::error_info().
print_inverse_IBM_quad_AV()
void Avec::print_inverse_IBM_quad_AV () static
recompute inverse_ibm_av from ibm_av and print it
Definition at line 572 of file Avec.cc.
References Avec::Unicode_to_IBM_codepoint::cp, inverse_ibm_av, and Avec::Unicode_to_IBM_codepoint::uni.
Referenced by Command::transfer_context::add().
show_error_pos()
int Avec::show_error_pos (int i, int line, bool cond, int def_line) static protected
print an error position on cerr, and then Assert(0);
Definition at line 56 of file Avec.cc.
subscript()
Unicode Avec::subscript (uint32_t i) static
return the subscript char for digit i (i = 0..9)
Definition at line 396 of file Avec.cc.
superscript()
Unicode Avec::superscript (uint32_t i) static
return the superscript char for digit i (i = 0..9)
Definition at line 416 of file Avec.cc.
uni_to_token()
Token Avec::uni_to_token (Unicode & av, const char * loc) static
Return a token containing av.
Definition at line 216 of file Avec.cc.
References character_table, find_char(), map_alternative_char(), and Avec::Character_definition::unicode.
Referenced by Tokenizer::do_tokenize(), and Tokenizer::tokenize_function().
unicode()
Unicode Avec::unicode (CHT_Index av) static
Return the UNICODE of char table entry av.
Definition at line 200 of file Avec.cc.
References character_table, and Avec::Character_definition::unicode.
unicode_to_cp()
unsigned char Avec::unicode_to_cp (Unicode uni) static
search uni in inverse_ibm_av and return its position in the IBM ⎕AV (= its code in .ATF files). Return 0xB0 if not found.
Definition at line 637 of file Avec.cc.
References compare_uni(), and inverse_ibm_av.
Referenced by need_UCS(), and Symbol::write_OUT().
Member Data Documentation
character_table
const Avec::Character_definition Avec::character_table static protected
Initial value:
=
{
#define char_def(name, _uni, tag, flags, av_pos)
#define char_uni(_name, _uni, _tag, _flags)
}
a table defining the properties of every character in ⎕AV. Only characters defined with char_def() (i.e. not those defined with char_uni()) are in this table.
Definition at line 184 of file Avec.hh.
Referenced by find_av_pos(), find_char(), get_av_pos(), is_symbol_char(), make_standard(), no_space_after(), no_space_before(), uni_to_token(), and unicode().
inverse_ibm_av
Avec::Unicode_to_IBM_codepoint Avec::inverse_ibm_av static protected
Unicode_to_IBM_codepoint table sorted by Unicode (for bsearch())
Definition at line 187 of file Avec.hh.
Referenced by print_inverse_IBM_quad_AV(), and unicode_to_cp().
The documentation for this class was generated from the following files:
src/Avec.hh
src/Avec.cc