GNU APL: MATCH_OR_MAKE_c Class Reference
MATCH_OR_MAKE_c Class Reference
APserver request: match offered shared variable or make a new offer.
#include <Svar_signals.hh>
Public Member Functions
MATCH_OR_MAKE_c (int s, Sig_item_string _varname, Sig_item_u32 _to_proc, Sig_item_u32 _to_parent, Sig_item_u32 _to_grand, Sig_item_u32 _from_proc, Sig_item_u32 _from_parent, Sig_item_u32 _from_grand)
contructor that creates the signal and sends it on TCP socket s
MATCH_OR_MAKE_c (const uint8_t *&buffer)
construct (deserialize) this item from a (received) buffer id has already been load()ed.
virtual void store (string &buffer) const
store (aka. serialize) this signal into a buffer
virtual ostream & print (ostream &out) const
print this signal on out.
virtual Signal_id get_sigID () const
a unique number for this signal
virtual const char * get_sigName () const
the name of this signal
virtual string get__MATCH_OR_MAKE__varname () const
return item varname of this signal
virtual uint32_t get__MATCH_OR_MAKE__to_proc () const
return item to_proc of this signal
virtual uint32_t get__MATCH_OR_MAKE__to_parent () const
return item to_parent of this signal
virtual uint32_t get__MATCH_OR_MAKE__to_grand () const
return item to_grand of this signal
virtual uint32_t get__MATCH_OR_MAKE__from_proc () const
return item from_proc of this signal
virtual uint32_t get__MATCH_OR_MAKE__from_parent () const
return item from_parent of this signal
virtual uint32_t get__MATCH_OR_MAKE__from_grand () const
return item from_grand of this signal
Public Member Functions inherited from Signal_base
virtual ~Signal_base ()
destructor
virtual void store (string &buffer) const =0
store (encode) the signal into buffer
virtual ostream & print (ostream &out) const =0
print the signal
virtual Signal_id get_sigID () const =0
return the ID of the signal
virtual const char * get_sigName () const =0
return the name of the ID of the signal
void bad_get (const char *signal, const char *member) const
get function for an item that is not defined for the signal
virtual uint64_t get__MAKE_OFFER__key () const
APserver request: ⎕SVO access functions for signal MAKE_OFFER...
virtual uint64_t get__RETRACT_OFFER__key () const
APserver request: ⎕SVR access functions for signal RETRACT_OFFER...
virtual uint64_t get__RETRACT_VAR__key () const
APserver request: ⎕SVR access functions for signal RETRACT_VAR...
virtual uint64_t get__SET_STATE__key () const
APserver request: set state of shared var key access functions for signal SET_STATE...
virtual uint8_t get__SET_STATE__new_state () const
< dito
virtual string get__SET_STATE__sloc () const
< dito
virtual uint64_t get__SET_CONTROL__key () const
APserver request: set control of shared var key access functions for signal SET_CONTROL...
virtual uint8_t get__SET_CONTROL__new_control () const
< dito
virtual uint64_t get__GET_VALUE__key () const
APserver request: X←SVAR access functions for signal GET_VALUE...
virtual uint64_t get__VALUE_IS__key () const
APserver result for: X←SVAR access functions for signal VALUE_IS...
virtual uint32_t get__VALUE_IS__error () const
< dito
virtual string get__VALUE_IS__error_loc () const
< dito
virtual string get__VALUE_IS__cdr_value () const
< dito
virtual uint64_t get__ASSIGN_VALUE__key () const
APserver request: SVAR←X access functions for signal ASSIGN_VALUE...
virtual string get__ASSIGN_VALUE__cdr_value () const
< dito
virtual uint64_t get__SVAR_ASSIGNED__key () const
APserver result for: SVAR←X access functions for signal SVAR_ASSIGNED...
virtual uint32_t get__SVAR_ASSIGNED__error () const
< dito
virtual string get__SVAR_ASSIGNED__error_loc () const
< dito
virtual uint64_t get__MAY_USE__key () const
APserver request: Can svar key be referenced ? access functions for signal MAY_USE...
virtual int32_t get__MAY_USE__attempt () const
< dito
virtual uint64_t get__MAY_SET__key () const
APserver request: Can svar key be assigned ? access functions for signal MAY_SET...
virtual int32_t get__MAY_SET__attempt () const
< dito
virtual uint64_t get__READ_SVAR_RECORD__key () const
APserver request: read SVAR database record from APserver.
virtual string get__SVAR_RECORD_IS__record () const
APserver result (record) for: read SVAR database record from APserver access functions for signal SVAR_RECORD_IS...
virtual uint32_t get__IS_REGISTERED_ID__proc () const
APserver request: is ID registered ? access functions for signal IS_REGISTERED_ID...
virtual uint32_t get__IS_REGISTERED_ID__parent () const
< dito
virtual uint32_t get__IS_REGISTERED_ID__grand () const
< dito
virtual uint8_t get__YES_NO__yes () const
APserver result: yes (1) or no (0) access functions for signal YES_NO...
virtual uint32_t get__REGISTER_PROCESSOR__proc () const
APserver request: register processor proc in APserver access functions for signal REGISTER_PROCESSOR...
virtual uint32_t get__REGISTER_PROCESSOR__parent () const
< dito
virtual uint32_t get__REGISTER_PROCESSOR__grand () const
< dito
virtual uint8_t get__REGISTER_PROCESSOR__evconn () const
< dito
virtual string get__REGISTER_PROCESSOR__progname () const
< dito
virtual string get__MATCH_OR_MAKE__varname () const
APserver request: match offered shared variable or make a new offer access functions for signal MATCH_OR_MAKE...
virtual uint32_t get__MATCH_OR_MAKE__to_proc () const
< dito
virtual uint32_t get__MATCH_OR_MAKE__to_parent () const
< dito
virtual uint32_t get__MATCH_OR_MAKE__to_grand () const
< dito
virtual uint32_t get__MATCH_OR_MAKE__from_proc () const
< dito
virtual uint32_t get__MATCH_OR_MAKE__from_parent () const
< dito
virtual uint32_t get__MATCH_OR_MAKE__from_grand () const
< dito
virtual uint64_t get__MATCH_OR_MAKE_RESULT__key () const
APserver result for: match or make access functions for signal MATCH_OR_MAKE_RESULT...
virtual uint64_t get__FIND_OFFERING_ID__key () const
APserver request: find processor ID that offers key access functions for signal FIND_OFFERING_ID...
virtual uint32_t get__OFFERING_ID_IS__proc () const
APserver result for: find processor ID that offers key access functions for signal OFFERING_ID_IS...
virtual uint32_t get__OFFERING_ID_IS__parent () const
< dito
virtual uint32_t get__OFFERING_ID_IS__grand () const
< dito
virtual uint32_t get__GET_OFFERING_PROCS__offered_to_proc () const
APserver request: get offering processors (⎕SVQ) access functions for signal GET_OFFERING_PROCS...
virtual string get__OFFERING_PROCS_ARE__offering_procs () const
APserver result for: get offering processors (⎕SVQ) access functions for signal OFFERING_PROCS_ARE...
virtual uint32_t get__GET_OFFERED_VARS__offered_to_proc () const
APserver request: get offered variables (⎕SVQ) access functions for signal GET_OFFERED_VARS...
virtual uint32_t get__GET_OFFERED_VARS__accepted_by_proc () const
< dito
virtual string get__OFFERED_VARS_ARE__offered_vars () const
APserver result for: get offered variables (⎕SVQ) access functions for signal OFFERED_VARS_ARE...
virtual uint64_t get__FIND_PAIRING_KEY__key () const
APserver request: find pairing key (CTL vs. DAT or Cnnn vs. Dnnn) for AP210 access functions for signal FIND_PAIRING_KEY...
virtual uint64_t get__PAIRING_KEY_IS__pairing_key () const
APserver result for: find pairing key access functions for signal PAIRING_KEY_IS...
virtual uint32_t get__GET_EVENTS__proc () const
APserver result for: find pairing key (CTL vs. DAT or Cnnn vs. Dnnn) for AP210 get events for one processor (first shared var with an event) access functions for signal GET_EVENTS...
virtual uint32_t get__GET_EVENTS__parent () const
< dito
virtual uint32_t get__GET_EVENTS__grand () const
< dito
virtual uint32_t get__CLEAR_ALL_EVENTS__proc () const
APserver request: clear all events for one processor access functions for signal CLEAR_ALL_EVENTS...
virtual uint32_t get__CLEAR_ALL_EVENTS__parent () const
< dito
virtual uint32_t get__CLEAR_ALL_EVENTS__grand () const
< dito
virtual uint64_t get__EVENTS_ARE__key () const
APserver result for: clear all events for one processor (first cleared svar access functions for signal EVENTS_ARE...
virtual uint32_t get__EVENTS_ARE__events () const
< dito
virtual uint64_t get__ADD_EVENT__key () const
APserver request: add an event for key access functions for signal ADD_EVENT...
virtual uint32_t get__ADD_EVENT__proc () const
< dito
virtual uint32_t get__ADD_EVENT__parent () const
< dito
virtual uint32_t get__ADD_EVENT__grand () const
< dito
virtual uint32_t get__ADD_EVENT__event () const
< dito
virtual uint64_t get__ASSIGN_WSWS_VAR__key () const
APserver request: ws-ws SVAR←X access functions for signal ASSIGN_WSWS_VAR...
virtual string get__ASSIGN_WSWS_VAR__cdr_value () const
< dito
virtual uint64_t get__READ_WSWS_VAR__key () const
APserver request: X←ws-ws SVAR access functions for signal READ_WSWS_VAR...
virtual string get__WSWS_VALUE_IS__cdr_value () const
APserver result for: X←ws-ws SVAR access functions for signal WSWS_VALUE_IS...
virtual string get__SVAR_DB_PRINTED__printout () const
APserver request: print the entire database (for command ]SVARS) access functions for signal PRINT_SVAR_DB...
Protected Attributes
Sig_item_string varname
varname
Sig_item_u32 to_proc
to_proc
Sig_item_u32 to_parent
to_parent
Sig_item_u32 to_grand
to_grand
Sig_item_u32 from_proc
from_proc
Sig_item_u32 from_parent
from_parent
Sig_item_u32 from_grand
from_grand
Additional Inherited Members
Static Public Member Functions inherited from Signal_base
static Signal_base * recv_TCP (int tcp_sock, char *buffer, int bufsize, char *&del, ostream *debug, const char **loc)
receive a signal (TCP)
Protected Member Functions inherited from Signal_base
ssize_t send_TCP (int tcp_sock) const
send this signal on TCP (or AF_UNIX) socket tcp_sock
Detailed Description
APserver request: match offered shared variable or make a new offer.
The class for signal MATCH_OR_MAKE
Definition at line 1628 of file Svar_signals.hh.
Constructor & Destructor Documentation
MATCH_OR_MAKE_c() [1/2]
MATCH_OR_MAKE_c::MATCH_OR_MAKE_c (int s, Sig_item_string _varname, Sig_item_u32 _to_proc, Sig_item_u32 _to_parent, Sig_item_u32 _to_grand, Sig_item_u32 _from_proc, Sig_item_u32 _from_parent, Sig_item_u32 _from_grand) inline
contructor that creates the signal and sends it on TCP socket s
Definition at line 1633 of file Svar_signals.hh.
References Signal_base::send_TCP().
MATCH_OR_MAKE_c() [2/2]
MATCH_OR_MAKE_c::MATCH_OR_MAKE_c (const uint8_t *& buffer) inline
construct (deserialize) this item from a (received) buffer id has already been load()ed.
Definition at line 1652 of file Svar_signals.hh.
Member Function Documentation
get__MATCH_OR_MAKE__from_grand()
virtual uint32_t MATCH_OR_MAKE_c::get__MATCH_OR_MAKE__from_grand () const inline virtual
return item from_grand of this signal
Reimplemented from Signal_base.
Definition at line 1715 of file Svar_signals.hh.
References from_grand, and Sig_item_int< T, bytes >::get_svalue().
get__MATCH_OR_MAKE__from_parent()
virtual uint32_t MATCH_OR_MAKE_c::get__MATCH_OR_MAKE__from_parent () const inline virtual
return item from_parent of this signal
Reimplemented from Signal_base.
Definition at line 1712 of file Svar_signals.hh.
References from_parent, and Sig_item_int< T, bytes >::get_svalue().
get__MATCH_OR_MAKE__from_proc()
virtual uint32_t MATCH_OR_MAKE_c::get__MATCH_OR_MAKE__from_proc () const inline virtual
return item from_proc of this signal
Reimplemented from Signal_base.
Definition at line 1709 of file Svar_signals.hh.
References from_proc, and Sig_item_int< T, bytes >::get_svalue().
get__MATCH_OR_MAKE__to_grand()
virtual uint32_t MATCH_OR_MAKE_c::get__MATCH_OR_MAKE__to_grand () const inline virtual
return item to_grand of this signal
Reimplemented from Signal_base.
Definition at line 1706 of file Svar_signals.hh.
References Sig_item_int< T, bytes >::get_svalue(), and to_grand.
get__MATCH_OR_MAKE__to_parent()
virtual uint32_t MATCH_OR_MAKE_c::get__MATCH_OR_MAKE__to_parent () const inline virtual
return item to_parent of this signal
Reimplemented from Signal_base.
Definition at line 1703 of file Svar_signals.hh.
References Sig_item_int< T, bytes >::get_svalue(), and to_parent.
get__MATCH_OR_MAKE__to_proc()
virtual uint32_t MATCH_OR_MAKE_c::get__MATCH_OR_MAKE__to_proc () const inline virtual
return item to_proc of this signal
Reimplemented from Signal_base.
Definition at line 1700 of file Svar_signals.hh.
References Sig_item_int< T, bytes >::get_svalue(), and to_proc.
get__MATCH_OR_MAKE__varname()
virtual string MATCH_OR_MAKE_c::get__MATCH_OR_MAKE__varname () const inline virtual
return item varname of this signal
Reimplemented from Signal_base.
Definition at line 1697 of file Svar_signals.hh.
References Sig_item_string::get_svalue(), and varname.
get_sigID()
virtual Signal_id MATCH_OR_MAKE_c::get_sigID () const inline virtual
a unique number for this signal
Implements Signal_base.
Definition at line 1691 of file Svar_signals.hh.
get_sigName()
virtual const char * MATCH_OR_MAKE_c::get_sigName () const inline virtual
the name of this signal
Implements Signal_base.
Definition at line 1694 of file Svar_signals.hh.
print()
virtual ostream & MATCH_OR_MAKE_c::print (ostream & out) const inline virtual
print this signal on out.
Implements Signal_base.
Definition at line 1677 of file Svar_signals.hh.
References from_grand, from_parent, from_proc, Sig_item_int< T, bytes >::print(), Sig_item_string::print(), to_grand, to_parent, to_proc, and varname.
store()
virtual void MATCH_OR_MAKE_c::store (string & buffer) const inline virtual
store (aka. serialize) this signal into a buffer
Implements Signal_base.
Definition at line 1663 of file Svar_signals.hh.
References from_grand, from_parent, from_proc, Sig_item_int< T, bytes >::store(), Sig_item_string::store(), to_grand, to_parent, to_proc, and varname.
Member Data Documentation
from_grand
Sig_item_u32 MATCH_OR_MAKE_c::from_grand protected
from_grand
Definition at line 1725 of file Svar_signals.hh.
Referenced by get__MATCH_OR_MAKE__from_grand(), print(), and store().
from_parent
Sig_item_u32 MATCH_OR_MAKE_c::from_parent protected
from_parent
Definition at line 1724 of file Svar_signals.hh.
Referenced by get__MATCH_OR_MAKE__from_parent(), print(), and store().
from_proc
Sig_item_u32 MATCH_OR_MAKE_c::from_proc protected
from_proc
Definition at line 1723 of file Svar_signals.hh.
Referenced by get__MATCH_OR_MAKE__from_proc(), print(), and store().
to_grand
Sig_item_u32 MATCH_OR_MAKE_c::to_grand protected
to_grand
Definition at line 1722 of file Svar_signals.hh.
Referenced by get__MATCH_OR_MAKE__to_grand(), print(), and store().
to_parent
Sig_item_u32 MATCH_OR_MAKE_c::to_parent protected
to_parent
Definition at line 1721 of file Svar_signals.hh.
Referenced by get__MATCH_OR_MAKE__to_parent(), print(), and store().
to_proc
Sig_item_u32 MATCH_OR_MAKE_c::to_proc protected
to_proc
Definition at line 1720 of file Svar_signals.hh.
Referenced by get__MATCH_OR_MAKE__to_proc(), print(), and store().
varname
Sig_item_string MATCH_OR_MAKE_c::varname protected
varname
Definition at line 1719 of file Svar_signals.hh.
Referenced by get__MATCH_OR_MAKE__varname(), print(), and store().
The documentation for this class was generated from the following file:
src/Svar_signals.hh