GNU APL: Plot_data_row Class Reference
Plot_data_row Class Reference
#include <Plot_data.hh>
Public Member Functions
Plot_data_row (const double *pX, const double *pY, const double *pZ, uint32_t idx, uint32_t len)
~Plot_data_row ()
destructor
uint32_t get_N () const
return the number of data points
double get_X (uint32_t n) const
return the n-th X coordinate
double get_Y (uint32_t n) const
return the n-th Y coordinate
double get_Z (uint32_t n) const
return the n-th Z coordinate
double get_min_X () const
return the smallest value in X
double get_max_X () const
return the largest value in X
double get_min_Y () const
return the smallest value in Y
double get_max_Y () const
return the largest value in Y
double get_min_Z () const
return the smallest value in Z
double get_max_Z () const
return the largest value in Y
Protected Attributes
const double * X
the X coordinates (optional, 0 if none)
const double * Y
the Y coordinates
const double * Z
the Z coordinates (optional, 0 if none)
const uint32_t row_num
the row number
const uint32_t N
the row length
double min_X
the smallest value in X
double max_X
the largest value in X
double min_Y
the smallest value in Y
double max_Y
the largest value in Y
double min_Z
the smallest value in Z
double max_Z
the largest value in Z
Detailed Description
data for one plot line, aka. data row. The [plot line consists of N data points with coordinate vectors X, Y, and Z.
Definition at line 66 of file Plot_data.hh.
Constructor & Destructor Documentation
Plot_data_row()
Plot_data_row::Plot_data_row (const double * pX, const double * pY, const double * pZ, uint32_t idx, uint32_t len) inline
constructor. Always called from Quad_PLOT::setup_data() which allocates it with std::new(void *, size_t). For efficiency, all data points in all rows are put into the same double * and our ~Plot_data_row() destructor is responsible for deleting it (when row 0 is destructed).
Definition at line 74 of file Plot_data.hh.
References get_X(), get_Y(), get_Z(), max_X, max_Y, max_Z, min_X, min_Y, min_Z, and N.
~Plot_data_row()
Plot_data_row::~Plot_data_row () inline
destructor
Definition at line 99 of file Plot_data.hh.
References row_num, and X.
Member Function Documentation
get_max_X()
double Plot_data_row::get_max_X () const inline
return the largest value in X
Definition at line 127 of file Plot_data.hh.
References max_X.
Referenced by Plot_data::add_row().
get_max_Y()
double Plot_data_row::get_max_Y () const inline
return the largest value in Y
Definition at line 135 of file Plot_data.hh.
References max_Y.
Referenced by Plot_data::add_row().
get_max_Z()
double Plot_data_row::get_max_Z () const inline
return the largest value in Y
Definition at line 143 of file Plot_data.hh.
References max_Z.
Referenced by Plot_data::add_row().
get_min_X()
double Plot_data_row::get_min_X () const inline
return the smallest value in X
Definition at line 123 of file Plot_data.hh.
References min_X.
Referenced by Plot_data::add_row().
get_min_Y()
double Plot_data_row::get_min_Y () const inline
return the smallest value in Y
Definition at line 131 of file Plot_data.hh.
References min_Y.
Referenced by Plot_data::add_row().
get_min_Z()
double Plot_data_row::get_min_Z () const inline
return the smallest value in Z
Definition at line 139 of file Plot_data.hh.
References min_Z.
Referenced by Plot_data::add_row().
get_N()
uint32_t Plot_data_row::get_N () const inline
return the number of data points
Definition at line 107 of file Plot_data.hh.
References N.
get_X()
double Plot_data_row::get_X (uint32_t n) const inline
return the n-th X coordinate
Definition at line 111 of file Plot_data.hh.
References X.
Referenced by Plot_data::get_X(), Plot_data::get_XY(), and Plot_data_row().
get_Y()
double Plot_data_row::get_Y (uint32_t n) const inline
return the n-th Y coordinate
Definition at line 115 of file Plot_data.hh.
References Y.
Referenced by Plot_data::get_XY(), Plot_data::get_Y(), and Plot_data_row().
get_Z()
double Plot_data_row::get_Z (uint32_t n) const inline
return the n-th Z coordinate
Definition at line 119 of file Plot_data.hh.
References row_num, and Z.
Referenced by Plot_data::get_Z(), and Plot_data_row().
Member Data Documentation
max_X
double Plot_data_row::max_X protected
the largest value in X
Definition at line 166 of file Plot_data.hh.
Referenced by get_max_X(), and Plot_data_row().
max_Y
double Plot_data_row::max_Y protected
the largest value in Y
Definition at line 172 of file Plot_data.hh.
Referenced by get_max_Y(), and Plot_data_row().
max_Z
double Plot_data_row::max_Z protected
the largest value in Z
Definition at line 178 of file Plot_data.hh.
Referenced by get_max_Z(), and Plot_data_row().
min_X
double Plot_data_row::min_X protected
the smallest value in X
Definition at line 163 of file Plot_data.hh.
Referenced by get_min_X(), and Plot_data_row().
min_Y
double Plot_data_row::min_Y protected
the smallest value in Y
Definition at line 169 of file Plot_data.hh.
Referenced by get_min_Y(), and Plot_data_row().
min_Z
double Plot_data_row::min_Z protected
the smallest value in Z
Definition at line 175 of file Plot_data.hh.
Referenced by get_min_Z(), and Plot_data_row().
N
const uint32_t Plot_data_row::N protected
the row length
Definition at line 160 of file Plot_data.hh.
Referenced by get_N(), and Plot_data_row().
row_num
const uint32_t Plot_data_row::row_num protected
the row number
Definition at line 157 of file Plot_data.hh.
Referenced by get_Z(), and ~Plot_data_row().
X
const double* Plot_data_row::X protected
the X coordinates (optional, 0 if none)
Definition at line 148 of file Plot_data.hh.
Referenced by get_X(), and ~Plot_data_row().
Y
const double* Plot_data_row::Y protected
the Y coordinates
Definition at line 151 of file Plot_data.hh.
Referenced by get_Y().
Z
const double* Plot_data_row::Z protected
the Z coordinates (optional, 0 if none)
Definition at line 154 of file Plot_data.hh.
Referenced by get_Z().
The documentation for this class was generated from the following file:
src/Plot_data.hh