GNU APL: Quad_PLOT Class Reference
Quad_PLOT Class Reference
The class implementing ⎕PLOT.
#include <Quad_PLOT.hh>
Public Member Functions
Quad_PLOT ()
Constructor.
Public Member Functions inherited from QuadFunction
QuadFunction (TokenTag tag)
Constructor.
virtual bool has_alpha () const
overloaded Function::has_alpha()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B().
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB().
virtual bool has_result () const
overloaded Function::has_result()
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
virtual bool has_result () const
overloaded Function::has_result()
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Static Public Attributes
static Quad_PLOT * fun = &Quad_PLOT::_fun
Built-in function.
static Quad_PLOT _fun
Built-in function.
static sem_t * plot_window_sema = &__plot_window_sema
a semaphore blocking until the plot window has been EXPOSED
static sem_t * plot_threads_sema = &__plot_threads_sema
a semaphore protecting plot_threads
static std::vector< pthread_t > plot_threads
an array of threads (one per plot window) handling X events from the window
Protected Member Functions
~Quad_PLOT ()
Destructor.
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B()
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Static Protected Member Functions
static void help ()
print attribute help text
static Value_P do_plot_data (Plot_window_properties *w_props, const Plot_data *data)
plot the data (creating a new plot window in X)
static Plot_data * setup_data (const Value &B)
initialize the data to be plotted
static Plot_data * setup_data_3D (const Value &B)
initialize the data to be plotted for a 3D plot
static Plot_data * setup_data_2D (const Value &B)
initialize the data to be plotted for a 2D plot (except case 2b.)
static Plot_data * setup_data_2D_2b (const Value &B)
initialize the data to be plotted for a 2D plot (case 2b.)
static ErrorCode parse_attributes (const Value &A, Plot_window_properties *w_props)
parse the (all-optional) attributes in A
Static Protected Attributes
static int verbosity = 0
whether to print some debug info during plotting
Additional Inherited Members
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
The class implementing ⎕PLOT.
Definition at line 44 of file Quad_PLOT.hh.
Constructor & Destructor Documentation
Quad_PLOT()
Quad_PLOT::Quad_PLOT ()
Constructor.
Definition at line 198 of file Quad_PLOT.cc.
References plot_threads_sema, plot_window_sema, and verbosity.
~Quad_PLOT()
Quad_PLOT::~Quad_PLOT () protected
Destructor.
Definition at line 206 of file Quad_PLOT.cc.
References plot_threads_sema.
Member Function Documentation
do_plot_data()
Value_P Quad_PLOT::do_plot_data (Plot_window_properties * w_props, const Plot_data * data) static protected
plot the data (creating a new plot window in X)
Definition at line 739 of file Quad_PLOT.cc.
References Plot_window_properties::get_max_X(), Plot_window_properties::get_max_Y(), Plot_window_properties::get_max_Z(), Plot_window_properties::get_min_X(), Plot_window_properties::get_min_Y(), Plot_window_properties::get_min_Z(), plot_main(), plot_threads, plot_threads_sema, plot_window_sema, Plot_window_properties::print(), Plot_window_properties::set_verbosity(), and verbosity.
Referenced by eval_AB(), and eval_B().
eval_AB()
Token Quad_PLOT::eval_AB (Value_P A, Value_P B) const protected virtual
overloaded Function::eval_AB()
Reimplemented from QuadFunction.
Definition at line 212 of file Quad_PLOT.cc.
References do_plot_data(), parse_attributes(), setup_data(), Plot_window_properties::update(), and verbosity.
eval_B()
Token Quad_PLOT::eval_B (Value_P B) const protected virtual
overloaded Function::eval_B()
Reimplemented from QuadFunction.
Definition at line 315 of file Quad_PLOT.cc.
References do_plot_data(), help(), plot_stop(), plot_threads, plot_threads_sema, setup_data(), and verbosity.
help()
void Quad_PLOT::help () static protected
print attribute help text
Definition at line 798 of file Quad_PLOT.cc.
Referenced by eval_B().
parse_attributes()
ErrorCode Quad_PLOT::parse_attributes (const Value & A, Plot_window_properties * w_props) static protected
parse the (all-optional) attributes in A
Definition at line 250 of file Quad_PLOT.cc.
References UTF8_string::c_str(), Value_P_Base::get(), Workspace::get_IO(), Cell::get_pointer_value(), Value::get_UCS_ravel(), Value::is_char_string(), Avec::is_comment(), Cell::is_pointer_cell(), UCS_string::remove_leading_and_trailing_whitespaces(), Plot_window_properties::set_attribute(), and UCS_string::size().
Referenced by eval_AB().
setup_data()
Plot_data * Quad_PLOT::setup_data (const Value & B) static protected
initialize the data to be plotted
check data. We expect B to be either:
1a. a numeric vector (for a single plot line), or 1b. a numeric matrix (for one plot line for each row of the matrix), or 2a. a scalar of a nested numeric vector (for a single plot line), or 2b. a vector of nested numeric vectors (for one plot line per item)
a 3-dimensional real vector for surface plots
Definition at line 431 of file Quad_PLOT.cc.
References Value::get_cfirst(), Value::get_rank(), Cell::is_pointer_cell(), setup_data_2D(), setup_data_2D_2b(), and setup_data_3D().
Referenced by eval_AB(), and eval_B().
setup_data_2D()
Plot_data * Quad_PLOT::setup_data_2D (const Value & B) static protected
initialize the data to be plotted for a 2D plot (except case 2b.)
initialize the data for a 2D plot. B is the right argument of ⎕PLOT B or A ⎕PLOT B and contains the plot coordinates of the plot points as simple numeric values. Every B[line;] is one plot line.
A complex number xJy means 2D plot coordinates (x, y) while a real number x means 2D plot coordinates (N, y) where N is the position of x in B[d;];
The third dimension Z is set to Y although not used.
Definition at line 455 of file Quad_PLOT.cc.
References Plot_data::add_row(), Cell::get_imag_value(), Workspace::get_IO(), Cell::get_real_value(), and Cell::is_complex_cell().
Referenced by setup_data().
setup_data_2D_2b()
Plot_data * Quad_PLOT::setup_data_2D_2b (const Value & B) static protected
initialize the data to be plotted for a 2D plot (case 2b.)
initialize the data for a 2D plot. B is the right argument of ⎕PLOT B or A ⎕PLOT B and contains the plot lines as nested values. Every ⊃B[line] is one plot line.
The third dimension Z is set to Y although not used.
Definition at line 516 of file Quad_PLOT.cc.
References Plot_data::add_row(), Value::element_count(), Value::get_cravel(), Cell::get_imag_value(), Workspace::get_IO(), Value::get_rank(), Cell::get_real_value(), Cell::is_complex_cell(), and Cell::is_numeric().
Referenced by setup_data().
setup_data_3D()
Plot_data * Quad_PLOT::setup_data_3D (const Value & B) static protected
initialize the data to be plotted for a 3D plot
initialize the data for a 3D (surface-) plot. B is the right argument of ⎕PLOT B or A ⎕PLOT B and can be:
A single nested array Y. In this case the X and Z coordintes are derived from ⍴Y and run from X=0...cols and from Z=0 to rows. The double * data contains only the values from Y (height).
The double * Y contains the values from for Y (height):
Y ↓ ┌───────────────┐ │ Y-coordinates │ └───────────────┘ │← data_points →│
Two nested arrays X and Y. In this case the Z coordinate is derived from ⍴Y and run from Z=0 to rows.
The double * X contains the values from X, followed by the values for Y (height):
X Y Z ↓ ↓
┌───────────────┬───────────────┐ │ X-coordinates │ Y-coordinates │ └───────────────┴───────────────┘ │← data_points →│← data_points →│
B← (⊂X) (⊂Y) (⊂Z). This indicates a 3D aka, surface plot. All coordinates come from B and the double * X contains Y and Z like this:
X Y Z ↓ ↓ ↓ ┌───────────────┬───────────────┬───────────────┐ │ X-coordinates │ Y-coordinates │ Z-coordinates │ └───────────────┴───────────────┴───────────────┘ │← data_points →│← data_points →│← data_points →│
Definition at line 587 of file Quad_PLOT.cc.
References Plot_data::add_row(), Cell::get_real_value(), Cell::is_integer_cell(), Cell::is_real_cell(), and Plot_data::surface.
Referenced by setup_data().
Member Data Documentation
_fun
Quad_PLOT Quad_PLOT::_fun static
Built-in function.
Definition at line 51 of file Quad_PLOT.hh.
fun
Quad_PLOT * Quad_PLOT::fun = &Quad_PLOT::_fun static
Built-in function.
Definition at line 50 of file Quad_PLOT.hh.
plot_threads
vector< pthread_t > Quad_PLOT::plot_threads static
an array of threads (one per plot window) handling X events from the window
Quad_PLOT::plot_threads contains one thread per (open) plot window. The thread handles the X main loop for the window. The thread also monitors its presence in plot_threads so that removing a thread from plot_threads causes the thread to close its plot window and then to exit.
Definition at line 61 of file Quad_PLOT.hh.
Referenced by do_plot_data(), eval_B(), and plot_main().
plot_threads_sema
sem_t * Quad_PLOT::plot_threads_sema = &__plot_threads_sema static
a semaphore protecting plot_threads
Definition at line 57 of file Quad_PLOT.hh.
Referenced by do_plot_data(), eval_B(), plot_main(), Quad_PLOT(), and ~Quad_PLOT().
plot_window_sema
sem_t * Quad_PLOT::plot_window_sema = &__plot_window_sema static
a semaphore blocking until the plot window has been EXPOSED
Definition at line 54 of file Quad_PLOT.hh.
Referenced by do_plot_data(), plot_main(), and Quad_PLOT().
verbosity
int Quad_PLOT::verbosity = 0 static protected
whether to print some debug info during plotting
Definition at line 97 of file Quad_PLOT.hh.
Referenced by do_plot_data(), eval_AB(), eval_B(), and Quad_PLOT().
The documentation for this class was generated from the following files:
src/Quad_PLOT.hh
src/Quad_PLOT.cc