GNU APL: CDR_string Class Reference
CDR_string Class Reference
a string containing a CDR record
#include <CDR_string.hh>
Public Member Functions
CDR_string ()
Constructor: An uninitialized CDR structure.
CDR_string (const uint8_t *data, int len)
Constructor: CDR structure from uint8_t * and length.
const uint8_t * get_items () const
return the bytes of this CDR
const CDR_header & header () const
return the header of this CDR
int get_ptr () const
return the tag of this CDR
CDR_type get_type () const
return the CDR type of this CDR
int get_rank () const
return the rank of this CDR
const uint8_t * ravel () const
return the ravel of this CDR
bool is_integer () const
return true if this CDR is bool or integer
bool is_character () const
return true if this CDR is character
int check () const
return non-zero if this CDR is malformed
void debug (ostream &out, const char *loc=0) const
print properties
Protected Member Functions
uint32_t get_4 (unsigned int offset) const
return 4 bytes of the header (the header is always big endian)
Detailed Description
a string containing a CDR record
Definition at line 63 of file CDR_string.hh.
Constructor & Destructor Documentation
CDR_string() [1/2]
CDR_string::CDR_string () inline
Constructor: An uninitialized CDR structure.
Definition at line 67 of file CDR_string.hh.
CDR_string() [2/2]
CDR_string::CDR_string (const uint8_t * data, int len) inline
Constructor: CDR structure from uint8_t * and length.
Definition at line 71 of file CDR_string.hh.
Member Function Documentation
check()
int CDR_string::check () const inline
return non-zero if this CDR is malformed
Definition at line 106 of file CDR_string.hh.
References get_4(), CDR_header::get_nb(), CDR_header::get_nelm(), get_ptr(), get_rank(), get_type(), and header().
Referenced by debug().
debug()
void CDR_string::debug (ostream & out, const char * loc = 0) const inline
print properties
Definition at line 119 of file CDR_string.hh.
References check().
get_4()
uint32_t CDR_string::get_4 (unsigned int offset) const inline protected
return 4 bytes of the header (the header is always big endian)
Definition at line 133 of file CDR_string.hh.
References CDR_header::get_be32().
Referenced by check(), and get_ptr().
get_items()
const uint8_t * CDR_string::get_items () const inline
return the bytes of this CDR
Definition at line 75 of file CDR_string.hh.
Referenced by Symbol::assign_shared_variable(), and CDR::from_CDR().
get_ptr()
int CDR_string::get_ptr () const inline
return the tag of this CDR
Definition at line 83 of file CDR_string.hh.
References get_4().
Referenced by check().
get_rank()
int CDR_string::get_rank () const inline
return the rank of this CDR
Definition at line 90 of file CDR_string.hh.
References header(), and CDR_header::rank.
Referenced by check(), and ravel().
get_type()
CDR_type CDR_string::get_type () const inline
return the CDR type of this CDR
Definition at line 86 of file CDR_string.hh.
References header().
Referenced by check(), is_character(), and is_integer().
header()
const CDR_header & CDR_string::header () const inline
return the header of this CDR
Definition at line 79 of file CDR_string.hh.
Referenced by check(), get_rank(), and get_type().
is_character()
bool CDR_string::is_character () const inline
return true if this CDR is character
Definition at line 102 of file CDR_string.hh.
References get_type().
is_integer()
bool CDR_string::is_integer () const inline
return true if this CDR is bool or integer
Definition at line 98 of file CDR_string.hh.
References get_type().
ravel()
const uint8_t * CDR_string::ravel () const inline
return the ravel of this CDR
Definition at line 94 of file CDR_string.hh.
References get_rank().
The documentation for this class was generated from the following file:
src/CDR_string.hh