GNU APL: CIN_ostream Class Reference
CIN_ostream Class Reference
an ostream for stdin echo and a few editing capabilities
#include <Output.hh>
Public Member Functions
void set_cursor (int y, int x)
set cursor to y:x (upper left corner is 0:0, negative y: from bottom)
ostream & clear_EOL ()
clear to end of line
bool can_clear_EOS () const
clear to end of screen supported ?
ostream & clear_EOS ()
clear to end of line
Detailed Description
an ostream for stdin echo and a few editing capabilities
Definition at line 219 of file Output.hh.
Constructor & Destructor Documentation
CIN_ostream()
CIN_ostream::CIN_ostream () inline
Definition at line 222 of file Output.hh.
Member Function Documentation
can_clear_EOS()
bool CIN_ostream::can_clear_EOS () const inline
clear to end of screen supported ?
Definition at line 234 of file Output.hh.
References Output::clear_EOS.
Referenced by LineEditContext::adjust_allocated_height(), and LineEditContext::refresh_from_cursor().
clear_EOL()
ostream & CIN_ostream::clear_EOL () inline
clear to end of line
Definition at line 230 of file Output.hh.
References Output::clear_EOL.
Referenced by LineEditContext::adjust_allocated_height(), and LineEditContext::refresh_from_cursor().
clear_EOS()
ostream & CIN_ostream::clear_EOS () inline
clear to end of line
Definition at line 238 of file Output.hh.
References Output::clear_EOS.
Referenced by LineEditContext::adjust_allocated_height(), and LineEditContext::refresh_from_cursor().
set_cursor()
void CIN_ostream::set_cursor (int y, int x)
set cursor to y:x (upper left corner is 0:0, negative y: from bottom)
Definition at line 218 of file Output.cc.
References UserPreferences::raw_cin.
Referenced by LineEditContext::adjust_allocated_height(), LineEditContext::refresh_all(), LineEditContext::refresh_from_cursor(), and LineEditContext::set_cursor().
The documentation for this class was generated from the following files:
src/Output.hh
src/Output.cc