GNU APL: VH_entry Class Reference
VH_entry Class Reference
a ringbuffer of events related to the manipulation of values
#include <ValueHistory.hh>
Public Member Functions
VH_entry ()
Constructor: empty (invalid) event.
VH_entry (const Value *val, VH_event ev, int ia, const char *loc)
Constructor: event for val.
Static Public Member Functions
static void init ()
init the event history
static void print_history (ostream &out, const Value &value, const char *loc)
print the history of value
Static Public Attributes
static VH_entry history [VALUEHISTORY_SIZE+1]
ring buffer of events
static int idx = 0
next event in history (which is a ring buffer)
Protected Member Functions
void print (int &flags, ostream &out, const Value &val, const VH_entry *previous) const
print the event
Protected Attributes
const Value * val
the Value (if any) to which this event belongs. APL errors thrown do not have one.
VH_event event
the event number
int iarg
integer arg (the meaning depends on event)
const char * loc
the caller (source location) of the VH_entry constructor
const char * testcase_file
the testcase file (if any) where the value was created
int testcase_line
the line number in the testcase file
Detailed Description
a ringbuffer of events related to the manipulation of values
Definition at line 32 of file ValueHistory.hh.
Constructor & Destructor Documentation
VH_entry() [1/2]
VH_entry::VH_entry () inline
Constructor: empty (invalid) event.
Definition at line 36 of file ValueHistory.hh.
VH_entry() [2/2]
VH_entry::VH_entry (const Value * val, VH_event ev, int ia, const char * loc)
Constructor: event for val.
Definition at line 37 of file ValueHistory.cc.
References InputFile::current_filename(), InputFile::current_line_no(), testcase_file, and testcase_line.
Member Function Documentation
init()
void VH_entry::init () static
init the event history
Definition at line 49 of file ValueHistory.cc.
References history.
print()
void VH_entry::print (int & flags, ostream & out, const Value & val, const VH_entry * previous) const protected
print the event
Definition at line 135 of file ValueHistory.cc.
References Error::error_name(), event, iarg, loc, testcase_file, and testcase_line.
Referenced by print_history().
print_history()
void VH_entry::print_history (ostream & out, const Value & value, const char * loc) static
print the history of value
Definition at line 67 of file ValueHistory.cc.
References event, history, idx, loc, print(), and val.
Referenced by Symbol::assign(), Command::cmd_CHECK(), and Value::print_stale_info().
Member Data Documentation
event
VH_event VH_entry::event protected
the event number
Definition at line 64 of file ValueHistory.hh.
Referenced by print(), and print_history().
history
VH_entry VH_entry::history static
ring buffer of events
Definition at line 49 of file ValueHistory.hh.
Referenced by init(), and print_history().
iarg
int VH_entry::iarg protected
integer arg (the meaning depends on event)
Definition at line 67 of file ValueHistory.hh.
Referenced by print().
idx
int VH_entry::idx = 0 static
next event in history (which is a ring buffer)
Definition at line 52 of file ValueHistory.hh.
Referenced by print_history().
loc
const char* VH_entry::loc protected
the caller (source location) of the VH_entry constructor
Definition at line 70 of file ValueHistory.hh.
Referenced by print(), and print_history().
testcase_file
const char* VH_entry::testcase_file protected
the testcase file (if any) where the value was created
Definition at line 73 of file ValueHistory.hh.
Referenced by print(), and VH_entry().
testcase_line
int VH_entry::testcase_line protected
the line number in the testcase file
Definition at line 76 of file ValueHistory.hh.
Referenced by print(), and VH_entry().
val
const Value* VH_entry::val protected
the Value (if any) to which this event belongs. APL errors thrown do not have one.
Definition at line 61 of file ValueHistory.hh.
Referenced by print_history().
The documentation for this class was generated from the following files:
src/ValueHistory.hh
src/ValueHistory.cc