GNU APL: Quad_JSON Class Reference
Quad_JSON Class Reference
The class implementing ⎕JSON.
#include <Quad_JSON.hh>
Public Member Functions
Quad_JSON ()
Constructor.
Public Member Functions inherited from QuadFunction
QuadFunction (TokenTag tag)
Constructor.
virtual bool has_alpha () const
overloaded Function::has_alpha()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B().
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB().
virtual bool has_result () const
overloaded Function::has_result()
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
virtual bool has_result () const
overloaded Function::has_result()
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Static Public Attributes
static Quad_JSON * fun = &Quad_JSON::_fun
Built-in function.
static Quad_JSON _fun
Built-in function.
Protected Member Functions
Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_B()
Token eval_B (Value_P B) const
overloaded Function::eval_B()
Token convert_file (const Value &B) const
return JSON file (-name in B) converted to APL structured value
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Static Protected Member Functions
static Value_P APL_to_JSON (const Value &B, bool sorted)
convert APL value to JSON string
static void APL_to_JSON_string (UCS_string &result, const Value &B, bool level, bool sorted)
append APL value to JSON string result
static void APL_to_JSON_string (UCS_string &result, const Cell &B, bool level, bool sorted)
append Cell value to JSON string result
static Value_P JSON_to_APL (const Value &B)
convert JSON string to APL associative array
static size_t skip_string (const UCS_string &ucs_B, ShapeItem &b)
skip the string literal that starts at ucs_B[b]. Return the content length an increment b. at start: ucs_B[b] = the left " of the string at return: ucs_B[b] = the right " of the string
static size_t number_len (const UCS_string &ucs_B, ShapeItem b)
return the length-1 of the number(-token) starting at b in ucs_B
static void parse_value (Value &Z, const UCS_string &ucs_B, const std::vector< ShapeItem > &tokens_B, size_t &token0)
parse a JSON value (false, null, true, object, array, number, or string) and increment along the way.
static void parse_array (Value &Z, const UCS_string &ucs_B, const std::vector< ShapeItem > &tokens_B, size_t &token0)
parse a JSON array: [ value (, value)* ] and increment token0 along the way.
static void parse_object (Value &Z, const UCS_string &ucs_B, const std::vector< ShapeItem > &tokens_B, size_t &token0)
parse a JSON object: { member (, member)* } and increment token0
static void parse_object_member (Value &Z, const UCS_string &ucs_B, const std::vector< ShapeItem > &tokens_B, size_t &token0)
parse a JSON object member: "name" : value , ; and increment token0 along the way.
static void parse_number (Value &Z, const UCS_string &ucs_B, ShapeItem b)
parse a JSON number
static void parse_string (Value &Z, const UCS_string &ucs_B, ShapeItem b)
parse a JSON string
static Unicode decode_UUUU (const UCS_string &ucs_B, ShapeItem b)
decode a \uUUUU sequence, return non-Unicode_0 on success and increment b, b, or else return Unicode_0 and leave b as is.
static bool is_high_surrogate (Unicode uni)
return true iff uni is a high surrogate Unicode (0xD8xx)
static bool is_low_surrogate (Unicode uni)
return true iff uni is a low surrogate Unicode (0xDCxx)
static void parse_literal (Value &Z, const UCS_string &ucs_B, ShapeItem b, const char *expected_literal)
parse a JSON literal (false, null, or true)
static size_t comma_count (const UCS_string &ucs_B, const std::vector< ShapeItem > &tokens_B, size_t &token0)
return the number of name-separators or value-separators at the top-level of the object or array starting at token0 and increment token0 along the way.
Additional Inherited Members
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
The class implementing ⎕JSON.
The system function ⎕JSON
Definition at line 31 of file Quad_JSON.hh.
Constructor & Destructor Documentation
Quad_JSON()
Quad_JSON::Quad_JSON () inline
Constructor.
Definition at line 35 of file Quad_JSON.hh.
Member Function Documentation
APL_to_JSON()
Value_P Quad_JSON::APL_to_JSON (const Value & B, bool sorted) static protected
convert APL value to JSON string
Definition at line 136 of file Quad_JSON.cc.
References APL_to_JSON_string(), and UCS_string::size().
Referenced by eval_AB().
APL_to_JSON_string() [1/2]
void Quad_JSON::APL_to_JSON_string (UCS_string & result, const Cell & B, bool level, bool sorted) static protected
append Cell value to JSON string result
Definition at line 148 of file Quad_JSON.cc.
References APL_to_JSON_string(), UCS_string::append(), UCS_string::append_UTF8(), UCS_string::compare(), Value_P_Base::get(), Cell::get_cell_type(), Cell::get_cell_type_name(), Value::get_cfirst(), Cell::get_imag_value(), Cell::get_int_value(), Cell::get_pointer_value(), Cell::get_real_value(), Value::is_char_vector(), Cell::is_complex_cell(), Cell::is_float_cell(), Cell::is_integer_cell(), Cell::is_pointer_cell(), and Value::is_scalar().
APL_to_JSON_string() [2/2]
void Quad_JSON::APL_to_JSON_string (UCS_string & result, const Value & B, bool level, bool sorted) static protected
append APL value to JSON string result
Definition at line 213 of file Quad_JSON.cc.
References APL_to_JSON_string(), UCS_string::append(), UCS_string::append_UTF8(), UCS_string::back(), Cell::get_pointer_value(), and UCS_string::size().
Referenced by APL_to_JSON(), and APL_to_JSON_string().
comma_count()
size_t Quad_JSON::comma_count (const UCS_string & ucs_B, const std::vector< ShapeItem > & tokens_B, size_t & token0) static protected
return the number of name-separators or value-separators at the top-level of the object or array starting at token0 and increment token0 along the way.
Definition at line 905 of file Quad_JSON.cc.
References UCS_string::back(), UCS_string::pop_back(), and UCS_string::size().
Referenced by parse_array(), and parse_object().
convert_file()
Token Quad_JSON::convert_file (const Value & B) const protected
return JSON file (-name in B) converted to APL structured value
Definition at line 74 of file Quad_JSON.cc.
References UTF8_string::c_str(), and eval_B().
Referenced by eval_AB().
decode_UUUU()
Unicode Quad_JSON::decode_UUUU (const UCS_string & ucs_B, ShapeItem b) static protected
decode a \uUUUU sequence, return non-Unicode_0 on success and increment b, b, or else return Unicode_0 and leave b as is.
Definition at line 861 of file Quad_JSON.cc.
Referenced by parse_string(), and skip_string().
eval_AB()
Token Quad_JSON::eval_AB (Value_P A, Value_P B) const protected virtual
overloaded Function::eval_B()
Reimplemented from QuadFunction.
Definition at line 40 of file Quad_JSON.cc.
References APL_to_JSON(), convert_file(), and eval_B().
eval_B()
Token Quad_JSON::eval_B (Value_P B) const protected virtual
overloaded Function::eval_B()
Reimplemented from QuadFunction.
Definition at line 126 of file Quad_JSON.cc.
References JSON_to_APL().
Referenced by convert_file(), and eval_AB().
is_high_surrogate()
static bool Quad_JSON::is_high_surrogate (Unicode uni) inline static protected
return true iff uni is a high surrogate Unicode (0xD8xx)
Definition at line 109 of file Quad_JSON.hh.
Referenced by parse_string(), and skip_string().
is_low_surrogate()
static bool Quad_JSON::is_low_surrogate (Unicode uni) inline static protected
return true iff uni is a low surrogate Unicode (0xDCxx)
Definition at line 113 of file Quad_JSON.hh.
Referenced by parse_string().
JSON_to_APL()
Value_P Quad_JSON::JSON_to_APL (const Value & B) static protected
convert JSON string to APL associative array
Definition at line 410 of file Quad_JSON.cc.
References number_len(), parse_value(), UCS_string::size(), and skip_string().
Referenced by eval_B().
number_len()
size_t Quad_JSON::number_len (const UCS_string & ucs_B, ShapeItem b) inline static protected
return the length-1 of the number(-token) starting at b in ucs_B
Definition at line 381 of file Quad_JSON.cc.
Referenced by JSON_to_APL().
parse_array()
void Quad_JSON::parse_array (Value & Z, const UCS_string & ucs_B, const std::vector< ShapeItem > & tokens_B, size_t & token0) static protected
parse a JSON array: [ value (, value)* ] and increment token0 along the way.
Definition at line 535 of file Quad_JSON.cc.
References comma_count(), Value_P_Base::get(), Value::next_ravel_Pointer(), Value::next_ravel_Value(), and parse_value().
Referenced by parse_value().
parse_literal()
void Quad_JSON::parse_literal (Value & Z, const UCS_string & ucs_B, ShapeItem b, const char * expected_literal) static protected
parse a JSON literal (false, null, or true)
Definition at line 877 of file Quad_JSON.cc.
References Value_P_Base::get(), and Value::next_ravel_Pointer().
Referenced by parse_value().
parse_number()
void Quad_JSON::parse_number (Value & Z, const UCS_string & ucs_B, ShapeItem b) static protected
parse a JSON number
Definition at line 717 of file Quad_JSON.cc.
References Value::next_ravel_Float(), and Value::next_ravel_Int().
Referenced by parse_value().
parse_object()
void Quad_JSON::parse_object (Value & Z, const UCS_string & ucs_B, const std::vector< ShapeItem > & tokens_B, size_t & token0) static protected
parse a JSON object: { member (, member)* } and increment token0
Definition at line 593 of file Quad_JSON.cc.
References comma_count(), Value_P_Base::get(), Value::next_ravel_Pointer(), and parse_object_member().
Referenced by parse_value().
parse_object_member()
void Quad_JSON::parse_object_member (Value & Z, const UCS_string & ucs_B, const std::vector< ShapeItem > & tokens_B, size_t & token0) static protected
parse a JSON object member: "name" : value , ; and increment token0 along the way.
Definition at line 636 of file Quad_JSON.cc.
References Value::get_member_data(), Value::get_new_member(), Cell::init(), and parse_value().
Referenced by parse_object().
parse_string()
void Quad_JSON::parse_string (Value & Z, const UCS_string & ucs_B, ShapeItem b) static protected
parse a JSON string
Definition at line 803 of file Quad_JSON.cc.
References decode_UUUU(), Value_P_Base::get(), is_high_surrogate(), is_low_surrogate(), Value::next_ravel_Pointer(), and skip_string().
Referenced by parse_value().
parse_value()
void Quad_JSON::parse_value (Value & Z, const UCS_string & ucs_B, const std::vector< ShapeItem > & tokens_B, size_t & token0) static protected
parse a JSON value (false, null, true, object, array, number, or string) and increment along the way.
Definition at line 490 of file Quad_JSON.cc.
References parse_array(), parse_literal(), parse_number(), parse_object(), and parse_string().
Referenced by JSON_to_APL(), parse_array(), and parse_object_member().
skip_string()
size_t Quad_JSON::skip_string (const UCS_string & ucs_B, ShapeItem & b) static protected
skip the string literal that starts at ucs_B[b]. Return the content length an increment b. at start: ucs_B[b] = the left " of the string at return: ucs_B[b] = the right " of the string
Definition at line 320 of file Quad_JSON.cc.
References decode_UUUU(), is_high_surrogate(), and UCS_string::size().
Referenced by JSON_to_APL(), and parse_string().
Member Data Documentation
_fun
Quad_JSON Quad_JSON::_fun static
Built-in function.
Definition at line 40 of file Quad_JSON.hh.
fun
Quad_JSON * Quad_JSON::fun = &Quad_JSON::_fun static
Built-in function.
Definition at line 39 of file Quad_JSON.hh.
The documentation for this class was generated from the following files:
src/Quad_JSON.hh
src/Quad_JSON.cc