GNU APL: Command Class Reference
Command Class Reference
The class implementing all APL commands.
#include <Command.hh>
Classes
struct transfer_context
a helper struct for the)IN command
struct user_command
one user defined command
struct val_val
a helper for finding sub-values with two parents
Static Public Member Functions
static void process_line ()
process a single line entered by the user (in immediate execution mode)
static void process_line (UCS_string &line)
process line which contains a command or statements
static bool do_APL_command (ostream &out, UCS_string &line)
process line which contains an APL command. Return true iff the command was user-defined (and then the function for that command is stored in line and shall be executed)).
static void do_APL_expression (UCS_string &line)
process line which contains APL statements
static void finish_context ()
finish the current SI->top() and pop it when done
static bool parse_from_to (UCS_string &from, UCS_string &to, const UCS_string &user_input)
parse user-suplied argument (of)VARS,)OPS, or)NMS commands) into strings from and to
static bool is_lib_ref (const UCS_string &lib)
return true if lib looks like a library reference (a 1-digit number or a path containing . or / chars
static void cmd_OFF (int exit_val)
clean-up and exit from APL interpreter
static void cmd_PUSHFILE ()
clean-up and exit from APL interpreter
static int get_boxing_format ()
return the current boxing format
static ShapeItem get_APL_expression_count ()
return the number of APL expressions entered in immediate execution mode
static void cmd_CHECK (ostream &out)
check workspace integrity (stale Value and IndexExpr objects, etc)
static bool is_directory (dirent *entry, const UTF8_string &path)
return true if entry is a directory
static void clear_copy_once_table ()
clear the copy_once_table.
Static Public Attributes
static int boxing_format = 0
format for ]BOXING
Static Protected Member Functions
static void cmd_BOXING (ostream &out, const UCS_string &arg)
)BOXING command
static void cmd_CONTINUE (ostream &out)
)SAVE active WS as CONTINUE and)OFF
static void cmd_COPY (ostream &out, UCS_string_vector &args, bool protection)
)COPY: copy a workspace file
static void cmd_COPY_ONCE (ostream &out, UCS_string_vector &args)
)COPY_ONCE: copy a workspace file, nut at most once
static void cmd_DOXY (ostream &out, UCS_string_vector &args)
]DOXY: create doxygen-like documentation of the current workspace
static void cmd_DROP (ostream &out, const UCS_string_vector &args)
)DROP: delete a workspace file
static void cmd_DUMP (ostream &out, const UCS_string_vector &args, bool html, bool silent)
)DUMP: dump a workspace file (.apl)
static void cmd_ERASE (ostream &out, UCS_string_vector &args)
)ERASE: erase symbols
static void cmd_HELP (ostream &out, const UCS_string &arg)
show list of commands
static void primitive_help (ostream &out, const char *arg, int arity, const char *prim, const char *name, const char *title, const char *descr)
show help for APL primitives
static void cmd_HISTORY (ostream &out, const UCS_string &arg)
show or clear input history
static void cmd_HOST (ostream &out, const UCS_string &arg)
)HOST: execute OS command
static void cmd_IN (ostream &out, UCS_string_vector &args, bool protect)
)IN: import a workspace file
static void cmd_KEYB (ostream &out)
show US keyboard layout
static void cmd_LOAD (ostream &out, UCS_string_vector &args, UCS_string &quad_lx, bool silent)
)LOAD: load a workspace file
static void cmd_PSTAT (ostream &out, const UCS_string &arg)
show performance counters
static DIR * open_LIB_dir (UTF8_string &path, ostream &out, const UCS_string_vector &args)
open directory arg and follow symlinks
static void lib_common (ostream &out, const UCS_string_vector &args, int variant)
list library: common helper
static void cmd_LIB1 (ostream &out, const UCS_string_vector &args)
list content of workspace and wslib directories:)LIB [N]
static void cmd_LIB2 (ostream &out, const UCS_string_vector &args)
list content of workspace and wslib directories: ]LIB [N]
static void cmd_LOG (ostream &out, const UCS_string &arg)
control logging facilities
static void cmd_LIBS (ostream &out, const UCS_string_vector &lib_ref)
list paths of workspace and wslib directories
static void cmd_MORE (ostream &out)
print more error info
static void cmd_OUT (ostream &out, UCS_string_vector &args)
)OUT: export a workspace file
static void cmd_SAVE (ostream &out, const UCS_string_vector &args)
)SAVE: save a workspace file (.xml)
static void cmd_USERCMD (ostream &out, const UCS_string &arg, UCS_string_vector &args)
create a user defined command
static void cmd_XTERM (ostream &out, const UCS_string &args)
enable and disable colors
static UCS_string_vector split_arg (const UCS_string &arg)
split whitespace separated arguments into individual arguments
static void do_USERCMD (ostream &out, UCS_string &line, const UCS_string &line1, const UCS_string &cmd, UCS_string_vector &args, int uidx)
execute a user defined command
static bool check_name_conflict (ostream &out, const UCS_string &cnew, const UCS_string cold)
check if a command name conflicts with an existing command
static bool check_redefinition (ostream &out, const UCS_string &cnew, const UCS_string fnew, const int mnew)
check if a command is being redefined
static bool check_params (ostream &out, const char *command, int argc, const char *args)
check the number of parameters in a command
static bool resolve_lib_wsname (ostream &out, const UCS_string_vector &args, LibRef &lib, UCS_string &wsname)
resolve an optional lib followed by a WS name
static void log_control (const UCS_string &args)
parse the argument of the ]LOG command and set logging accordingly
Static Protected Attributes
static ShapeItem APL_expression_count = 0
the number of APL expressions entered in immediate execution mode
static UCS_string_vector copy_once_table
workspaces that shall not be copied twice
Detailed Description
The class implementing all APL commands.
Some command related functions, including the main input loop of the APL interpreter.
Definition at line 39 of file Command.hh.
Member Function Documentation
check_name_conflict()
bool Command::check_name_conflict (ostream & out, const UCS_string & cnew, const UCS_string cold) static protected
check if a command name conflicts with an existing command
Definition at line 1954 of file Command.cc.
References UCS_string::size().
check_params()
bool Command::check_params (ostream & out, const char * command, int argc, const char * args) static protected
check the number of parameters in a command
Definition at line 185 of file Command.cc.
References UCS_string::size().
check_redefinition()
bool Command::check_redefinition (ostream & out, const UCS_string & cnew, const UCS_string fnew, const int mnew) static protected
check if a command is being redefined
Definition at line 1976 of file Command.cc.
References Workspace::get_user_commands().
Referenced by cmd_USERCMD().
clear_copy_once_table()
void Command::clear_copy_once_table () static
clear the copy_once_table.
Definition at line 891 of file Command.cc.
References copy_once_table.
Referenced by Workspace::clear_WS().
cmd_BOXING()
void Command::cmd_BOXING (ostream & out, const UCS_string & arg) static protected
)BOXING command
Definition at line 604 of file Command.cc.
References UCS_string::atoi(), boxing_format, UCS_string::size(), and UCS_string::starts_iwith().
cmd_CHECK()
void Command::cmd_CHECK (ostream & out) static
check workspace integrity (stale Value and IndexExpr objects, etc)
Definition at line 656 of file Command.cc.
References IO_Files::apl_error(), Value::check_all_Cells(), Command::val_val::child, Workspace::cleanup_expunged(), Command::val_val::compare_val_val(), Command::val_val::compare_val_val1(), Value_P_Base::get(), DynamicObject::get_all_values(), Value::get_cravel(), Cell::get_pointer_value(), Cell::is_pointer_cell(), Value::nz_element_count(), Command::val_val::parent, VH_entry::print_history(), IndexExpr::print_stale(), Value::print_stale(), and UCS_string::sort().
Referenced by XML_Saving_Archive::save().
cmd_CONTINUE()
void Command::cmd_CONTINUE (ostream & out) static protected
)SAVE active WS as CONTINUE and)OFF
Definition at line 786 of file Command.cc.
References cmd_OFF(), Workspace::save_WS(), and Workspace::wsid().
cmd_COPY()
void Command::cmd_COPY (ostream & out, UCS_string_vector & args, bool protection) static protected
)COPY: copy a workspace file
Definition at line 795 of file Command.cc.
References Workspace::copy_WS(), UCS_string_vector::erase(), and Avec::is_digit().
cmd_COPY_ONCE()
EH_NO_PARAM Command::cmd_COPY_ONCE (ostream & out, UCS_string_vector & args) static protected
)COPY_ONCE: copy a workspace file, nut at most once
Definition at line 822 of file Command.cc.
References UCS_string::append(), UCS_string_vector::contains(), copy_once_table, Workspace::copy_WS(), UCS_string_vector::erase(), Avec::is_digit(), UCS_string_vector::print_table(), and UCS_string::size().
cmd_DOXY()
void Command::cmd_DOXY (ostream & out, UCS_string_vector & args) static protected
]DOXY: create doxygen-like documentation of the current workspace
Definition at line 901 of file Command.cc.
References Doxy::gen(), Doxy::get_errors(), and Doxy::get_root_dir().
cmd_DROP()
void Command::cmd_DROP (ostream & out, const UCS_string_vector & args) static protected
)DROP: delete a workspace file
Definition at line 926 of file Command.cc.
References UTF8_string::c_str(), and LibPaths::get_lib_filename().
cmd_DUMP()
void Command::cmd_DUMP (ostream & out, const UCS_string_vector & args, bool html, bool silent) static protected
)DUMP: dump a workspace file (.apl)
Definition at line 955 of file Command.cc.
References UCS_string::compare(), Workspace::dump_WS(), UCS_string::erase(), Workspace::get_WS_name(), Avec::is_digit(), UCS_string::remove_leading_whitespaces(), and resolve_lib_wsname().
cmd_ERASE()
void Command::cmd_ERASE (ostream & out, UCS_string_vector & args) static protected
)ERASE: erase symbols
Definition at line 1000 of file Command.cc.
References Workspace::erase_symbols().
cmd_HELP()
void Command::cmd_HELP (ostream & out, const UCS_string & arg) static protected
show list of commands
< where the second column starts
Definition at line 1153 of file Command.cc.
References UTF8_string::c_str(), Symbol::get_apl_value(), UserFunction::get_func_ufun(), Symbol::get_function(), ValueStackItem::get_label(), ValueStackItem::get_NC(), NativeFunction::get_so_path(), Workspace::get_user_commands(), UserFunction::help(), Symbol::is_erased(), Avec::is_first_symbol_char(), NativeFunction::is_valid(), Workspace::lookup_existing_symbol(), Avec::make_standard(), UCS_string::size(), and Symbol::top_of_stack().
cmd_HISTORY()
void Command::cmd_HISTORY (ostream & out, const UCS_string & arg) static protected
show or clear input history
Definition at line 1353 of file Command.cc.
References LineInput::clear_history(), LineInput::print_history(), UCS_string::size(), and UCS_string::starts_iwith().
cmd_HOST()
void Command::cmd_HOST (ostream & out, const UCS_string & arg) static protected
)HOST: execute OS command
Definition at line 1361 of file Command.cc.
References UTF8_string::c_str(), and UserPreferences::safe_mode.
cmd_IN()
void Command::cmd_IN (ostream & out, UCS_string_vector & args, bool protect) static protected
)IN: import a workspace file
Definition at line 1402 of file Command.cc.
References UTF8_string::c_str(), LibPaths::get_lib_filename(), Command::transfer_context::is_ebcdic, Workspace::more_error(), Command::transfer_context::process_record(), and Command::transfer_context::recnum.
cmd_KEYB()
void Command::cmd_KEYB (ostream & out) static protected
show US keyboard layout
Definition at line 1006 of file Command.cc.
References UTF8_string::c_str(), and UserPreferences::keyboard_layout_file.
cmd_LIB1()
void Command::cmd_LIB1 (ostream & out, const UCS_string_vector & args) static protected
list content of workspace and wslib directories:)LIB [N]
Definition at line 1817 of file Command.cc.
References lib_common().
cmd_LIB2()
void Command::cmd_LIB2 (ostream & out, const UCS_string_vector & args) static protected
list content of workspace and wslib directories: ]LIB [N]
Definition at line 1830 of file Command.cc.
References lib_common().
cmd_LIBS()
void Command::cmd_LIBS (ostream & out, const UCS_string_vector & lib_ref) static protected
list paths of workspace and wslib directories
Definition at line 1486 of file Command.cc.
References UTF8_string::c_str(), LibPaths::LibDir::CSRC_CMD, LibPaths::LibDir::CSRC_ENV, LibPaths::LibDir::CSRC_NONE, LibPaths::LibDir::CSRC_PREF_HOME, LibPaths::LibDir::CSRC_PREF_SYS, LibPaths::LibDir::CSRC_PWD, LibPaths::get_APL_lib_root(), LibPaths::get_cfg_src(), LibPaths::get_lib_dir(), LibPaths::set_APL_lib_root(), LibPaths::set_lib_dir(), and UCS_string::size().
cmd_LOAD()
void Command::cmd_LOAD (ostream & out, UCS_string_vector & args, UCS_string & quad_lx, bool silent) static protected
)LOAD: load a workspace file
Definition at line 1470 of file Command.cc.
References Workspace::load_WS(), and resolve_lib_wsname().
cmd_LOG()
void Command::cmd_LOG (ostream & out, const UCS_string & arg) static protected
control logging facilities
Definition at line 1843 of file Command.cc.
References log_control().
cmd_MORE()
void Command::cmd_MORE (ostream & out) static protected
print more error info
Definition at line 1868 of file Command.cc.
References Workspace::more_error().
cmd_OFF()
void Command::cmd_OFF (int exit_val) static
clean-up and exit from APL interpreter
Definition at line 1881 of file Command.cc.
References Quad_WA::initial_rlimit, UserPreferences::session_start, and UserPreferences::silent.
Referenced by cmd_CONTINUE(), IO_Files::diff_error(), do_APL_expression(), Nabla::edit(), IO_Files::end_of_current_file(), IO_Files::get_file_line(), InputMux::get_line(), and signal_SEGV_handler().
cmd_OUT()
void Command::cmd_OUT (ostream & out, UCS_string_vector & args) static protected
)OUT: export a workspace file
Definition at line 1929 of file Command.cc.
References UTF8_string::c_str(), UCS_string_vector::erase(), LibPaths::get_lib_filename(), and Workspace::write_OUT().
cmd_PSTAT()
void Command::cmd_PSTAT (ostream & out, const UCS_string & arg) static protected
show performance counters
Definition at line 1052 of file Command.cc.
References UCS_string::atoi(), Performance::print(), Performance::reset_all(), Performance::save_data(), UCS_string::size(), and UCS_string::starts_iwith().
cmd_PUSHFILE()
void Command::cmd_PUSHFILE () static
clean-up and exit from APL interpreter
Definition at line 1914 of file Command.cc.
References InputFile::files_todo, and InputFile::set_pushed_IE().
cmd_SAVE()
void Command::cmd_SAVE (ostream & out, const UCS_string_vector & args) static protected
)SAVE: save a workspace file (.xml)
Definition at line 2001 of file Command.cc.
References UCS_string::compare(), UCS_string::erase(), Workspace::get_WS_name(), Avec::is_digit(), UCS_string::remove_leading_whitespaces(), resolve_lib_wsname(), and Workspace::save_WS().
cmd_USERCMD()
void Command::cmd_USERCMD (ostream & out, const UCS_string & arg, UCS_string_vector & args) static protected
create a user defined command
Definition at line 2067 of file Command.cc.
References UCS_string::back(), check_redefinition(), UCS_string::contains(), Workspace::get_user_commands(), Avec::is_symbol_char(), Command::user_command::prefix, and UCS_string::size().
cmd_XTERM()
void Command::cmd_XTERM (ostream & out, const UCS_string & args) static protected
enable and disable colors
Definition at line 565 of file Command.cc.
References Output::color_enabled(), UCS_string::size(), UCS_string::starts_iwith(), and Output::toggle_color().
do_APL_command()
bool Command::do_APL_command (ostream & out, UCS_string & line) static
process line which contains an APL command. Return true iff the command was user-defined (and then the function for that command is stored in line and shall be executed)).
Definition at line 143 of file Command.cc.
References UCS_string::copy_black(), do_USERCMD(), Workspace::get_user_commands(), Workspace::more_error(), UCS_string::size(), split_arg(), and UCS_string::starts_iwith().
Referenced by Bif_F1_EXECUTE::execute_command(), and process_line().
do_APL_expression()
void Command::do_APL_expression (UCS_string & line) static
process line which contains APL statements
Definition at line 258 of file Command.cc.
References cmd_OFF(), Error::error_name(), StateIndicator::escape(), finish_context(), StatementList::fix(), Executable::get_body(), Error::get_error_code(), Error::get_error_line_2(), Error::get_error_line_3(), StateIndicator::get_parse_mode(), Workspace::more_error(), Workspace::pop_SI(), Error::print(), Workspace::push_SI(), and Workspace::SI_top().
Referenced by process_line().
do_USERCMD()
void Command::do_USERCMD (ostream & out, UCS_string & line, const UCS_string & line1, const UCS_string & cmd, UCS_string_vector & args, int uidx) static protected
execute a user defined command
Definition at line 2243 of file Command.cc.
References UCS_string::append(), UCS_string::append_quoted(), and Workspace::get_user_commands().
Referenced by do_APL_command().
finish_context()
void Command::finish_context () static
finish the current SI->top() and pop it when done
Definition at line 333 of file Command.cc.
References Prefix::at0(), Quad_FIO::benchmark_cycles_from, Quad_EC::eoc(), StateIndicator::escape(), Executable::execute_body(), Token::get_Class(), Workspace::get_error(), UserFunction_header::get_error(), StateIndicator::get_executable(), Token::get_int_val(), StateIndicator::get_parent(), StateIndicator::get_parse_mode(), StateIndicator::get_prefix(), Workspace::get_pushed_Command(), StateIndicator::get_safe_execution(), Token::get_tag(), StateIndicator::goon(), StateIndicator::is_safe_execution_start(), Workspace::pop_SI(), Error::print(), process_line(), Workspace::push_Command(), StateIndicator::retry(), Workspace::SI_top(), Workspace::SI_top_fun(), Token_loc::tok, Prefix::tos(), and Token::~Token().
Referenced by do_APL_expression().
get_APL_expression_count()
static ShapeItem Command::get_APL_expression_count () inline static
return the number of APL expressions entered in immediate execution mode
Definition at line 79 of file Command.hh.
References APL_expression_count.
Referenced by Quad_AI::get_apl_value().
get_boxing_format()
static int Command::get_boxing_format () inline static
return the current boxing format
Definition at line 75 of file Command.hh.
References boxing_format.
Referenced by StateIndicator::statement_result().
is_directory()
bool Command::is_directory (dirent * entry, const UTF8_string & path) static
return true if entry is a directory
Definition at line 1634 of file Command.cc.
References UTF8_string::append_UTF8(), and UTF8_string::c_str().
Referenced by lib_common(), and TabExpansion::read_matching_filenames().
is_lib_ref()
bool Command::is_lib_ref (const UCS_string & lib) static
return true if lib looks like a library reference (a 1-digit number or a path containing . or / chars
Definition at line 2701 of file Command.cc.
References Avec::is_digit(), and UCS_string::size().
lib_common()
void Command::lib_common (ostream & out, const UCS_string_vector & args, int variant) static protected
list library: common helper
Definition at line 1651 of file Command.cc.
References UCS_string::append(), UCS_string_vector::compute_column_width(), UTF8_string::ends_with(), is_directory(), Avec::is_symbol_char(), UCS_string::lexical_before(), open_LIB_dir(), parse_from_to(), UCS_string::size(), and UCS_string_vector::sort().
Referenced by cmd_LIB1(), and cmd_LIB2().
open_LIB_dir()
DIR * Command::open_LIB_dir (UTF8_string & path, ostream & out, const UCS_string_vector & args) static protected
open directory arg and follow symlinks
Definition at line 1570 of file Command.cc.
References UTF8_string::append_UTF8(), UTF8_string::c_str(), LibPaths::get_lib_dir(), Avec::is_digit(), and UCS_string::size().
Referenced by lib_common().
parse_from_to()
bool Command::parse_from_to (UCS_string & from, UCS_string & to, const UCS_string & user_input) static
parse user-suplied argument (of)VARS,)OPS, or)NMS commands) into strings from and to
Definition at line 2640 of file Command.cc.
References UCS_string::append(), UCS_string::back(), and UCS_string::size().
Referenced by lib_common(), and SymbolTable::list().
primitive_help()
void Command::primitive_help (ostream & out, const char * arg, int arity, const char * prim, const char * name, const char * title, const char * descr) static protected
show help for APL primitives
Definition at line 1104 of file Command.cc.
process_line() [1/2]
void Command::process_line () static
process a single line entered by the user (in immediate execution mode)
start or end of multi-line
Definition at line 66 of file Command.cc.
References UCS_string::append(), UCS_string::append_ASCII(), UCS_string::do_escape(), UCS_string::ends_with(), LineInput::get_history(), StateIndicator::get_line(), Workspace::get_prompt(), UCS_string::pop_back(), UCS_string::prepend(), process_line(), and UCS_string::size().
Referenced by finish_context(), IO_Files::get_file_line(), Workspace::immediate_execution(), init_apl(), and process_line().
process_line() [2/2]
void Command::process_line (UCS_string & line) static
process line which contains a command or statements
Definition at line 110 of file Command.cc.
References APL_expression_count, do_APL_command(), do_APL_expression(), Nabla::edit_function(), UCS_string::remove_leading_whitespaces(), and UCS_string::size().
resolve_lib_wsname()
bool Command::resolve_lib_wsname (ostream & out, const UCS_string_vector & args, LibRef & lib, UCS_string & wsname) static protected
resolve an optional lib followed by a WS name
Definition at line 2043 of file Command.cc.
References Avec::is_digit().
Referenced by cmd_DUMP(), cmd_LOAD(), and cmd_SAVE().
split_arg()
UCS_string_vector Command::split_arg (const UCS_string & arg) static protected
split whitespace separated arguments into individual arguments
Definition at line 590 of file Command.cc.
References UCS_string::copy_black(), and UCS_string::size().
Referenced by do_APL_command().
Member Data Documentation
APL_expression_count
ShapeItem Command::APL_expression_count = 0 static protected
the number of APL expressions entered in immediate execution mode
Definition at line 293 of file Command.hh.
Referenced by get_APL_expression_count(), and process_line().
boxing_format
int Command::boxing_format = 0 static
format for ]BOXING
Definition at line 117 of file Command.hh.
Referenced by Quad_PS::assign(), Quad_PS::assign_indexed(), cmd_BOXING(), and get_boxing_format().
copy_once_table
UCS_string_vector Command::copy_once_table static protected
workspaces that shall not be copied twice
Definition at line 296 of file Command.hh.
Referenced by clear_copy_once_table(), and cmd_COPY_ONCE().
The documentation for this class was generated from the following files:
src/Command.hh
src/Command.cc
src/Command.def