GNU APL: MultiIndexIterator Class Reference
MultiIndexIterator Class Reference
A multi-dimensional index iterator.
#include <IndexIterator.hh>
Public Member Functions
MultiIndexIterator (const Shape &shape, const IndexExpr &IDX)
constructor from IndexExpr for value with rank/shape
~MultiIndexIterator ()
destructor
ShapeItem operator++ (int)
get the current index (offset into a ravel) and increment iterators
bool more () const
return true if more indices are coming
Protected Attributes
IndexIterator * highest_it
the iterator for the highest dimension
IndexIterator * lowest_it
the iterator for the lowest dimension
bool empty
true if one of the iterators has length 0
Detailed Description
A multi-dimensional index iterator.
a multi-dimensional index iterator, consisting of several one-dimensional iterators.
Definition at line 130 of file IndexIterator.hh.
Constructor & Destructor Documentation
MultiIndexIterator()
MultiIndexIterator::MultiIndexIterator (const Shape & shape, const IndexExpr & IDX)
constructor from IndexExpr for value with rank/shape
Definition at line 81 of file IndexIterator.cc.
References empty, IndexExpr::get_rank(), Shape::get_rank(), Shape::get_shape_item(), highest_it, lowest_it, IndexExpr::quad_io, IndexIterator::set_upper(), and IndexExpr::values.
~MultiIndexIterator()
MultiIndexIterator::~MultiIndexIterator ()
destructor
Definition at line 141 of file IndexIterator.cc.
References IndexIterator::get_upper(), and lowest_it.
Member Function Documentation
more()
bool MultiIndexIterator::more () const inline
return true if more indices are coming
Definition at line 143 of file IndexIterator.hh.
References highest_it, and IndexIterator::more().
Referenced by Symbol::assign_indexed(), Value::index(), and operator++().
operator++()
ShapeItem MultiIndexIterator::operator++ (int)
get the current index (offset into a ravel) and increment iterators
Definition at line 155 of file IndexIterator.cc.
References IndexIterator::get_upper(), lowest_it, and more().
Member Data Documentation
empty
bool MultiIndexIterator::empty protected
true if one of the iterators has length 0
Definition at line 154 of file IndexIterator.hh.
Referenced by MultiIndexIterator().
highest_it
IndexIterator* MultiIndexIterator::highest_it protected
the iterator for the highest dimension
Definition at line 148 of file IndexIterator.hh.
Referenced by more(), and MultiIndexIterator().
lowest_it
IndexIterator* MultiIndexIterator::lowest_it protected
the iterator for the lowest dimension
Definition at line 151 of file IndexIterator.hh.
Referenced by MultiIndexIterator(), operator++(), and ~MultiIndexIterator().
The documentation for this class was generated from the following files:
src/IndexIterator.hh
src/IndexIterator.cc