GNU APL: SystemSymTab Class Reference
SystemSymTab Class Reference
The table containing all system defined symbols (aka. distinguished names)
#include <SymbolTable.hh>
Public Member Functions
void clear (ostream &out)
clear this symbol table (remove all user-defined symbols)
void clear_slot (ostream &out, int hash)
clear one slot (hash) in this symbol table
void add_function (const UCS_string &name, Id id, QuadFunction *function)
add function to the symbol table
void add_variable (const UCS_string &name, Id id, SystemVariable *variable)
add variable to the symbol table
void add_variable (const UCS_string &name, Id id, Symbol *variable)
don't add ⍺ and friends
Public Member Functions inherited from SymbolTableBase< SystemName, 256 - 1 >
SymbolTableBase ()
Construct an empty SymbolTable.
SystemName * lookup_existing_symbol (const UCS_string &name)
return a Symbol with name name in this SymbolTable.
const SystemName * lookup_existing_symbol (const UCS_string &name) const
return a Symbol with name name in this SymbolTable.
UCS_string find_lambda_name (const UserFunction *lambda)
return the name to which lambda ia assigned (empty if not found)
void add_symbol (SystemName *sym)
add sym to the symbol table. The caller has checked that new_name does not yet exist in the symbol table
Protected Member Functions
void add_fun_or_var (const UCS_string &name, Id id, QuadFunction *function, SystemVariable *variable)
add a function or variable
Protected Attributes
int max_name_len
the length of the longest name
Protected Attributes inherited from SymbolTableBase< SystemName, 256 - 1 >
SystemName * symbol_table [SYMBOL_COUNT]
Hash table for all symbols.
Additional Inherited Members
Public Types inherited from SymbolTableBase< SystemName, 256 - 1 >
enum
Static Public Member Functions inherited from SymbolTableBase< SystemName, 256 - 1 >
static uint32_t compute_hash (const UCS_string &name)
compute a 16-bit hash for name
Detailed Description
The table containing all system defined symbols (aka. distinguished names)
Definition at line 230 of file SymbolTable.hh.
Constructor & Destructor Documentation
SystemSymTab()
SystemSymTab::SystemSymTab () inline
Definition at line 234 of file SymbolTable.hh.
Member Function Documentation
add_fun_or_var()
void SystemSymTab::add_fun_or_var (const UCS_string & name, Id id, QuadFunction * function, SystemVariable * variable) protected
add a function or variable
Definition at line 534 of file SymbolTable.cc.
References SymbolTableBase< SystemName, 256 - 1 >::add_symbol(), SymbolTableBase< SystemName, 256 - 1 >::lookup_existing_symbol(), max_name_len, and UCS_string::size().
Referenced by add_function(), and add_variable().
add_function()
void SystemSymTab::add_function (const UCS_string & name, Id id, QuadFunction * function) inline
add function to the symbol table
Definition at line 245 of file SymbolTable.hh.
References add_fun_or_var().
add_variable() [1/2]
void SystemSymTab::add_variable (const UCS_string & name, Id id, Symbol * variable) inline
don't add ⍺ and friends
Definition at line 254 of file SymbolTable.hh.
add_variable() [2/2]
void SystemSymTab::add_variable (const UCS_string & name, Id id, SystemVariable * variable) inline
add variable to the symbol table
Definition at line 249 of file SymbolTable.hh.
References add_fun_or_var().
clear()
void SystemSymTab::clear (ostream & out)
clear this symbol table (remove all user-defined symbols)
Definition at line 507 of file SymbolTable.cc.
References clear_slot(), and Workspace::SI_entry_count().
clear_slot()
void SystemSymTab::clear_slot (ostream & out, int hash)
clear one slot (hash) in this symbol table
Definition at line 517 of file SymbolTable.cc.
References SystemName::next, and SymbolTableBase< SystemName, 256 - 1 >::symbol_table.
Referenced by clear().
Member Data Documentation
max_name_len
int SystemSymTab::max_name_len protected
the length of the longest name
Definition at line 263 of file SymbolTable.hh.
Referenced by add_fun_or_var().
The documentation for this class was generated from the following files:
src/SymbolTable.hh
src/SymbolTable.cc