GNU APL: ProcessorID Class Reference
ProcessorID Class Reference
One APL processor.
#include <ProcessorID.hh>
Static Public Member Functions
static bool init (bool log_startup)
initialize our own process ID, return non-0 on error. proc_id == 0 uses the next free ID > 1000; otherwise proc_id is used. do_sv defines if an APnnn process for incoming ⎕SVO offers shall be forked.
static const AP_num3 & get_id ()
return the own id, parent, and grand-parent
static AP_num get_own_ID ()
return the processor ID of this apl interpreter
static AP_num get_parent_ID ()
return the processor ID of the parent of this apl interpreter
static int read_network_profile ()
read the network profile file from its default location
static void disconnect ()
disconnect from APnnn process
Static Protected Member Functions
static int read_network_profile (const char *filename)
read the network profile file from file file
static const char * read_svopid (FILE *file, SvoPid &svopid, int &line)
read one SvoPid entry from file
static const char * read_procauth (FILE *file, ProcAuth &procauth, int &line)
read one ProcAuth entry from file
Static Protected Attributes
static AP_num3 id
the processor, parent, and grandparent of this apl interpreter
static Network_Profile network_profile
the network profile currently used
Detailed Description
One APL processor.
One APL processor. APL interpreters have numbers > 1000 while auxiliary processors have numbers < 1000
Definition at line 111 of file ProcessorID.hh.
Member Function Documentation
disconnect()
void ProcessorID::disconnect () static
disconnect from APnnn process
Definition at line 347 of file ProcessorID.cc.
References Svar_DB::DB_tcp_error().
get_id()
static const AP_num3 & ProcessorID::get_id () inline static
return the own id, parent, and grand-parent
Definition at line 121 of file ProcessorID.hh.
References id.
Referenced by Quad_SVE::get_apl_value(), Svar_record::get_control(), Svar_record::may_set(), Svar_record::may_use(), Symbol::resolve_shared_variable(), Svar_record::retract(), Svar_record::set_control(), Svar_record::set_state(), and Quad_SVO::share_one_variable().
get_own_ID()
static AP_num ProcessorID::get_own_ID () inline static
return the processor ID of this apl interpreter
Definition at line 124 of file ProcessorID.hh.
Referenced by Quad_AI::get_apl_value(), Quad_SVQ::get_processors(), Quad_SVQ::get_variables(), Quad_SVO::share_one_variable(), and Quad_SVx::start_AP().
get_parent_ID()
static AP_num ProcessorID::get_parent_ID () inline static
return the processor ID of the parent of this apl interpreter
Definition at line 127 of file ProcessorID.hh.
Referenced by Quad_SVO::share_one_variable(), and Quad_SVx::start_AP().
init()
bool ProcessorID::init (bool log_startup) static
initialize our own process ID, return non-0 on error. proc_id == 0 uses the next free ID > 1000; otherwise proc_id is used. do_sv defines if an APnnn process for incoming ⎕SVO offers shall be forked.
Definition at line 41 of file ProcessorID.cc.
References Svar_DB::get_DB_tcp(), Svar_DB::is_registered_id(), UserPreferences::requested_id, UserPreferences::requested_par, UserPreferences::system_do_svars, and UserPreferences::user_do_svars.
read_network_profile() [1/2]
int ProcessorID::read_network_profile () static
read the network profile file from its default location
Definition at line 251 of file ProcessorID.cc.
References LibPaths::get_APL_bin_path(), and read_network_profile().
Referenced by read_network_profile().
read_network_profile() [2/2]
int ProcessorID::read_network_profile (const char * filename) static protected
read the network profile file from file file
Definition at line 268 of file ProcessorID.cc.
References Network_Profile::clear(), ProcAuth::id, network_profile, Network_Profile::proc_auths, read_procauth(), read_svopid(), Network_Profile::svo_pids, and SvoPid::svopid.
read_procauth()
const char * ProcessorID::read_procauth (FILE * file, ProcAuth & procauth, int & line) static protected
read one ProcAuth entry from file
Definition at line 202 of file ProcessorID.cc.
References ProcAuth::rsvopid.
Referenced by read_network_profile().
read_svopid()
const char * ProcessorID::read_svopid (FILE * file, SvoPid & svopid, int & line) static protected
read one SvoPid entry from file
Definition at line 114 of file ProcessorID.cc.
References SvoPid::id, SvoPid::ip_addr, and SvoPid::user.
Referenced by read_network_profile().
Member Data Documentation
id
AP_num3 ProcessorID::id static protected
the processor, parent, and grandparent of this apl interpreter
Definition at line 147 of file ProcessorID.hh.
Referenced by get_id().
network_profile
Network_Profile ProcessorID::network_profile static protected
the network profile currently used
Definition at line 150 of file ProcessorID.hh.
Referenced by read_network_profile().
The documentation for this class was generated from the following files:
src/ProcessorID.hh
src/ProcessorID.cc