GNU APL: StatementList Class Reference
StatementList Class Reference
The token of an statement list cmd ◊ cmd ... ◊ cmd.
#include <Executable.hh>
Static Public Member Functions
static StatementList * fix (const UCS_string &data, const char *loc)
compute body token from text data
Protected Member Functions
StatementList (const UCS_string txt, const char *loc)
constructor
virtual UCS_string get_name () const
overloaded Executable::get_name()
Protected Member Functions inherited from Executable
void setup_lambdas ()
extract all lambda expressions from body and store them in lambdas
ShapeItem setup_one_lambda (ShapeItem b, ShapeItem end, int lambda_num)
extract one lambda expressions from body and store it in lambdas
Fun_signature compute_lambda_body (Token_string &rev_lambda_body, ShapeItem b, ShapeItem bend)
body[b ... bend] is a lambda. Move these token from this body to the body of the lambda and clear them in this body.
UCS_string extract_lambda_text (Fun_signature signature, int skip) const
extract the skip'th { ... } from the function text
ErrorCode parse_body_line (Function_Line line, const UCS_string &ucs, bool trace, bool tolerant, const char *loc, bool macro)
parse the body line number line of this function
ErrorCode parse_body_line (Function_Line line, const Token_string &tos, bool trace, bool tolerant, const char *loc)
parse the body line number line of this function
Friends
class XML_Loading_Archive
Additional Inherited Members
Public Member Functions inherited from Executable
Executable (const UCS_string &ucs, bool multi_line, ParseMode pm, const char *loc)
constructor
Executable (Fun_signature sig, int lambda_num, const UCS_string &lambda_text, const char *loc)
constructor for lambdas
virtual ~Executable ()
destructor: release values held by the body
ParseMode get_parse_mode () const
the parse mode of this Executable
void clear_body ()
delete values in body and (maybe) remove lambdas
virtual UCS_string get_name () const =0
return the name of this function, or ◊ or ⍎
virtual bool cannot_suspend () const
return true iff this Executable cannot be suspended
virtual Symbol * get_sym_Z () const
return the result symbol iff this is a user defined function or operator that returns a value
virtual const UserFunction * get_exec_ufun () const
return a UserFunction * (if this is one) or else 0.
virtual bool pushes_sym (const Symbol *sym) const
return true if this Executable localizes Symbol sym
virtual UserFunction * get_exec_ufun ()
return a UserFunction * (if this is one) or else 0.
virtual Function_Line get_line (Function_PC pc) const
get the line number for pc
virtual ostream & print (ostream &out) const
print this user defined executable to out
void print_token (ostream &out) const
print this user defined executable to out
void print_text (ostream &out) const
print the text of this user defined executable to out
Token execute_body () const
execute the body of this executable
const Token_string & get_body () const
return the body of this executable
const int get_text_size () const
return number of function lines (including header line 0)
const UCS_string & get_text (int l) const
return function line n (0 = header line)
void clear_text (int l)
clear the text of line n (0 = header line)
void set_text (int l, const UCS_string &new_line)
set the text of line n (0 = header line)
UCS_string statement_text (Function_PC pc) const
return the text of statement at pc
virtual Function_PC line_start (Function_Line line) const
return the first PC of the line
virtual void adjust_line_starts ()
adjust line starts before calling Parser::remove_void_token(body)
void set_error_info (Error &error, Function_PC2 range) const
compute lines 2 and 3 in error
Function_PC get_statement_start (int pc) const
return the start of the statement to which pc belongs
void unmark_all_values () const
clear marked flag in all body token
int show_owners (const char *prefix, ostream &out, const Value &value) const
print all owners of value
const char * get_loc () const
say where this SI entry was allocated
void increment_refcount (const char *loc)
increment the reference counter
void decrement_refcount (const char *loc)
decrement the reference counter
Static Protected Member Functions inherited from Executable
static void reverse_statement_token (Token_string &tos)
reverse the token order in every statement of tos
static void reverse_all_token (Token_string &tos)
reverse the token order of the entire Token_string
Protected Attributes inherited from Executable
const char * alloc_loc
where this SI entry was allocated
const ParseMode pmode
the mode this Executable
UCS_string_vector text
the program text from which body was created
Token_string body
The token to be executed. They are organized line by line and statement by statement, but the token within a statement reversed due to the right-to-left execution of APL.
int refcount
reference counter (for lambdas)
Detailed Description
The token of an statement list cmd ◊ cmd ... ◊ cmd.
The token of an statement list (cmd ◊ cmd ... ◊ cmd)
Definition at line 230 of file Executable.hh.
Constructor & Destructor Documentation
StatementList()
StatementList::StatementList (const UCS_string txt, const char * loc) inline protected
constructor
Definition at line 240 of file Executable.hh.
Member Function Documentation
fix()
StatementList * StatementList::fix (const UCS_string & data, const char * loc) static
compute body token from text data
Definition at line 927 of file Executable.cc.
References Executable::body, Workspace::get_error(), Executable::parse_body_line(), Executable::print(), and Executable::setup_lambdas().
Referenced by Command::do_APL_expression(), and XML_Loading_Archive::read_Statement().
get_name()
virtual UCS_string StatementList::get_name () const inline protected virtual
overloaded Executable::get_name()
Implements Executable.
Definition at line 245 of file Executable.hh.
Friends And Related Function Documentation
XML_Loading_Archive
friend class XML_Loading_Archive friend
Definition at line 232 of file Executable.hh.
The documentation for this class was generated from the following files:
src/Executable.hh
src/Executable.cc