GNU APL: Performance Class Reference
Performance Class Reference
A class containing performance counters for several functions.
#include <Performance.hh>
Static Public Member Functions
static Statistics * get_statistics (Pfstat_ID id)
return statistics object for ID id
static int get_statistics_type (Pfstat_ID id)
return statistics type of ID id
static void print (Pfstat_ID which, ostream &out)
print all counters
static void save_data (ostream &out, ostream &out_file)
write all counters to .def file
static void reset_all ()
reset all counters
Detailed Description
A class containing performance counters for several functions.
Performance (cycle-) counters at different levels
Definition at line 314 of file Performance.hh.
Member Function Documentation
get_statistics()
Statistics * Performance::get_statistics (Pfstat_ID id) static
return statistics object for ID id
Definition at line 53 of file Performance.cc.
Referenced by Quad_FIO::eval_XB(), and print().
get_statistics_type()
int Performance::get_statistics_type (Pfstat_ID id) static
return statistics type of ID id
Definition at line 74 of file Performance.cc.
Referenced by Quad_FIO::eval_XB().
print()
void Performance::print (Pfstat_ID which, ostream & out) static
print all counters
Definition at line 110 of file Performance.cc.
References Statistics_record::average(), get_statistics(), Statistics::print(), and Statistics_record::print5().
Referenced by Command::cmd_PSTAT().
reset_all()
void Performance::reset_all () static
reset all counters
Definition at line 248 of file Performance.cc.
Referenced by Command::cmd_PSTAT().
save_data()
void Performance::save_data (ostream & out, ostream & out_file) static
write all counters to .def file
Definition at line 238 of file Performance.cc.
Referenced by Command::cmd_PSTAT().
The documentation for this class was generated from the following files:
src/Performance.hh
src/Performance.cc