GNU APL: UCS_string_vector Class Reference
UCS_string_vector Class Reference
a vector of UCS_strings.
#include <UCS_string_vector.hh>
Public Member Functions
UCS_string_vector ()
constructor: empty string vector
UCS_string_vector (const Value &val, bool surrogate)
constructor: from APL character matrix (removes trailing blanks)
bool contains (const UCS_string &ucs) const
return true iff one of the strings is equal to ucs
void sort ()
sort the strings in this vector alphabetically
void compute_column_width (int tab_size, std::vector< int > &result)
compute columns width so that items align nicely (for)VARS,)FNS, etc.)
void erase (size_t pos)
replacement for erase(std::vector::iterator position)
void insert (size_t pos, const UCS_string &value)
replacement for insert(std::vector::iterator position, value)
std::ostream & print_table (std::ostream &out, size_t column_count) const
print items of this vector in a table with column_count columns
Protected Member Functions
ShapeItem max_width (size_t col, size_t column_count) const
return the size of the longest UCS_string in this vector.
Private Member Functions
std::vector< UCS_string >::iterator erase (std::vector< UCS_string >::iterator position)
prevent the inadvertent use of iterator nonsense
std::vector< UCS_string >::iterator insert (std::vector< UCS_string >::iterator position, const UCS_string &value)
prevent the inadvertent use of iterator nonsense
Detailed Description
a vector of UCS_strings.
Definition at line 30 of file UCS_string_vector.hh.
Constructor & Destructor Documentation
UCS_string_vector() [1/2]
UCS_string_vector::UCS_string_vector () inline
constructor: empty string vector
Definition at line 34 of file UCS_string_vector.hh.
UCS_string_vector() [2/2]
UCS_string_vector::UCS_string_vector (const Value & val, bool surrogate)
constructor: from APL character matrix (removes trailing blanks)
Definition at line 30 of file UCS_string_vector.cc.
References UCS_string::append(), Cell::get_char_value(), Value::get_cols(), Value::get_cravel(), Value::get_rows(), Avec::is_quad(), and Avec::is_symbol_char().
Member Function Documentation
compute_column_width()
void UCS_string_vector::compute_column_width (int tab_size, std::vector< int > & result)
compute columns width so that items align nicely (for)VARS,)FNS, etc.)
Definition at line 117 of file UCS_string_vector.cc.
References Workspace::get_PW().
Referenced by Command::lib_common(), and SymbolTable::list().
contains()
bool UCS_string_vector::contains (const UCS_string & ucs) const inline
return true iff one of the strings is equal to ucs
Definition at line 40 of file UCS_string_vector.hh.
Referenced by Command::transfer_context::array_2TF(), Command::transfer_context::chars_1TF(), Command::cmd_COPY_ONCE(), Command::transfer_context::function_2TF(), Command::transfer_context::numeric_1TF(), and XML_Loading_Archive::read_Symbol().
erase()
void UCS_string_vector::erase (size_t pos) inline
replacement for erase(std::vector::iterator position)
Definition at line 58 of file UCS_string_vector.hh.
Referenced by Command::cmd_COPY(), Command::cmd_COPY_ONCE(), Command::cmd_OUT(), and Quad_GTK::eval_B().
insert()
void UCS_string_vector::insert (size_t pos, const UCS_string & value) inline
replacement for insert(std::vector::iterator position, value)
Definition at line 62 of file UCS_string_vector.hh.
Referenced by PrintBuffer::add_frame(), PrintBuffer::add_outer_frame(), and PrintBuffer::pad_height_above().
max_width()
ShapeItem UCS_string_vector::max_width (size_t col, size_t column_count) const protected
return the size of the longest UCS_string in this vector.
Definition at line 196 of file UCS_string_vector.cc.
Referenced by print_table().
print_table()
std::ostream & UCS_string_vector::print_table (std::ostream & out, size_t column_count) const
print items of this vector in a table with column_count columns
Definition at line 210 of file UCS_string_vector.cc.
References max_width(), and UCS_string::size().
Referenced by Command::cmd_COPY_ONCE().
sort()
void UCS_string_vector::sort () inline
sort the strings in this vector alphabetically
Definition at line 47 of file UCS_string_vector.hh.
References UCS_string::compare_names(), and UCS_string::sort().
Referenced by TabExpansion::expand_distinguished_name(), TabExpansion::expand_help_topics(), Command::lib_common(), and SymbolTable::list().
The documentation for this class was generated from the following files:
src/UCS_string_vector.hh
src/UCS_string_vector.cc