GNU APL: Plot_window_properties Class Reference
Plot_window_properties Class Reference
properties of the entire plot window (from A in A ⎕PLOT B)
#include <Plot_window_properties.hh>
Public Types
enum Plot_Range_type {
NO_RANGE = 0 ,
PLOT_RANGE_MIN = 1 ,
PLOT_RANGE_MAX = 2 ,
PLOT_RANGE_MIN_MAX = PLOT_RANGE_MIN | PLOT_RANGE_MAX
}
the kind of range
Public Member Functions
Plot_window_properties (const Plot_data *data, int verbosity)
constructor
~Plot_window_properties ()
destructor
bool update (int verbosity)
update derived properties after changing primary ones, return true on error
void set_window_size (Pixel_X width, Pixel_Y height)
handle window resize event
bool rangeX_min_valid () const
return true iff a rangeX_min property was specified
bool rangeX_max_valid () const
return true iff a rangeX_max property was specified
bool rangeY_min_valid () const
return true iff a rangeY_min property was specified
bool rangeY_max_valid () const
return true iff a rangeY_max property was specified
bool rangeZ_min_valid () const
return true iff a rangeZ_min property was specified
bool rangeZ_max_valid () const
return true iff a rangeZ_max property was specified
Plot_line_properties *const *const get_line_properties () const
an array of plot line properties
Pixel_X valX2pixel (double val_X) const
convert
val_X to the X coordinate of the pixel in the plot area
Pixel_Y valY2pixel (double val_Y) const
convert
val_Y to the Y coordinate of the pixel in the plot area
Pixel_Z valZ2pixel (double val_Z) const
convert
val_Z to the relative Z vector (q. quadrant)
Pixel_XY valXYZ2pixelXY (double val_X, double val_Y, double val_Z) const
convert values val_X, val_Y, and val_Z, to the X and Y coordinate of the pixel below the Z=0 plane of the plot area
Pixel_XY get_origin (bool surface) const
return the pixel position of the point where the X, Y, and possibly Z-axis cross.
int print (ostream &out) const
print the properties (for debugging purposes)
const char * set_attribute (const char *att_and_val)
for e.g. att_and_val = "pa_width: 600" set pa_width to 600. Return error string on error.
const char * set_attribute (const UCS_string &att, const Cell &val)
for e.g. A.pa_width ← 600" set pa_width to 600. Return error string on error.
Pixel_X get_window_width () const
return the width of the plot window
Pixel_Y get_window_height () const
return the height of the plot window
double get_min_X () const
return the smallest X value
double get_max_X () const
return the largest X value
double get_min_Y () const
return the smallest Y value
double get_max_Y () const
return the largest Y value
double get_min_Z () const
return the smallest Z value
double get_max_Z () const
return the largest Z value
double get_scale_X () const
return the X value → X pixels scaling factor
double get_scale_Y () const
return the Y value → Y pixels scaling factor
double get_scale_Z () const
return the Z value → Z pixels scaling factor
double get_value_per_tile_X () const
return the X-value difference for one tile (= between two X grid lines)
double get_value_per_tile_Y () const
return the Y-value difference for one tile (= between two Y grid lines)
double get_value_per_tile_Z () const
return the Z-value difference for one tile (= between two Z grid lines)
Pixel_X get_gridX_last () const
return the last index of the X grid
Pixel_Y get_gridY_last () const
return the last index of the Y grid
Pixel_Y get_gridZ_last () const
return the last index of the Y grid
int get_verbosity () const
return the verbosity when plotting
void set_verbosity (int verb)
set the verbosity when plotting
const Plot_data & get_plot_data () const
return the date to be plotted
const vector< level_color > & get_gradient () const
return the 3D color gradient
uint32_t get_color (double alpha) const
for level 0.0 <= alpha <= 1.0: return the color for alpha according to gradient
uint32_t get_line_count () const
return the number of plot lines
Protected Member Functions
bool can_be_set (uint16_t line, uint16_t propnum)
return true unless property propnum was already set in plot line line
Static Protected Member Functions
static double round_up_125 (double val)
round val up to the next higher 1/2/5×10^N
Protected Attributes
const int line_count
the number of plot lines
const Plot_data & plot_data
the date to be plotted
Pixel_X window_width
the width of the plot window
Pixel_Y window_height
the height of the plot window
double min_X
the smallest X value
double max_X
the largest X value
double min_Y
the smallest Y value
double max_Y
the largest Y value
double min_Z
the smallest Z value
double max_Z
the largest Z value
double scale_X
the X value → X pixels scaling factor
double scale_Y
the Y value → Y pixels scaling factor
double scale_Z
the Z value → Z pixels scaling factor
double tile_X
the number of pixels between X grid lines
double tile_Y
the number of pixels between Y grid lines
double tile_Z
the number of pixels between Z grid lines
int gridX_last
the last index of the X grid
int gridY_last
the last index of the Y grid
int gridZ_last
the last index of the Y grid
int verbosity
the verbosity when plotting
Plot_Range_type rangeX_type
the kind of X range
Plot_Range_type rangeY_type
the kind of Y range
Plot_Range_type rangeZ_type
the kind of Z range
Plot_line_properties ** line_properties
array containing the data for the plot lines
vector< level_color > gradient
some levels with colors (for surface plots)
vector< uint16_t > properties_set
a list of properties that have been set alreay (to protect items from being overridden in set_all_XXX() functions
Detailed Description
properties of the entire plot window (from A in A ⎕PLOT B)
Definition at line 29 of file Plot_window_properties.hh.
Member Enumeration Documentation
Plot_Range_type
enum Plot_window_properties::Plot_Range_type
the kind of range
Enumerator
NO_RANGE
no plot range provided
PLOT_RANGE_MIN
min value provided
PLOT_RANGE_MAX
max value provided
PLOT_RANGE_MIN_MAX
min. and max.
Definition at line 33 of file Plot_window_properties.hh.
Constructor & Destructor Documentation
Plot_window_properties()
Plot_window_properties::Plot_window_properties (const Plot_data * data, int verbosity)
constructor
Definition at line 27 of file Plot_window_properties.cc.
References line_count, line_properties, max_X, max_Y, max_Z, min_X, min_Y, min_Z, Plot_data::surface, update(), and verbosity.
~Plot_window_properties()
Plot_window_properties::~Plot_window_properties ()
destructor
Definition at line 75 of file Plot_window_properties.cc.
References plot_data.
Member Function Documentation
can_be_set()
bool Plot_window_properties::can_be_set (uint16_t line, uint16_t propnum) protected
return true unless property propnum was already set in plot line line
Definition at line 366 of file Plot_window_properties.cc.
References properties_set.
get_color()
uint32_t Plot_window_properties::get_color (double alpha) const
for level 0.0 <= alpha <= 1.0: return the color for alpha according to gradient
Definition at line 454 of file Plot_window_properties.cc.
References gradient.
Referenced by draw_triangle().
get_gradient()
const vector< level_color > & Plot_window_properties::get_gradient () const inline
return the 3D color gradient
Definition at line 208 of file Plot_window_properties.hh.
References gradient.
Referenced by draw_surface_lines(), and draw_triangle().
get_gridX_last()
Pixel_X Plot_window_properties::get_gridX_last () const inline
return the last index of the X grid
Definition at line 190 of file Plot_window_properties.hh.
References gridX_last.
Referenced by draw_X_grid(), and draw_Z_grid().
get_gridY_last()
Pixel_Y Plot_window_properties::get_gridY_last () const inline
return the last index of the Y grid
Definition at line 193 of file Plot_window_properties.hh.
References gridY_last.
Referenced by draw_Y_grid(), and draw_Z_grid().
get_gridZ_last()
Pixel_Y Plot_window_properties::get_gridZ_last () const inline
return the last index of the Y grid
Definition at line 196 of file Plot_window_properties.hh.
References gridZ_last.
Referenced by draw_Z_grid().
get_line_count()
uint32_t Plot_window_properties::get_line_count () const inline
return the number of plot lines
Definition at line 216 of file Plot_window_properties.hh.
References line_count.
Referenced by draw_legend().
get_line_properties()
Plot_line_properties *const *const Plot_window_properties::get_line_properties () const inline
an array of plot line properties
Definition at line 107 of file Plot_window_properties.hh.
References line_properties.
Referenced by draw_legend(), draw_plot_lines(), and draw_surface_lines().
get_max_X()
double Plot_window_properties::get_max_X () const inline
return the largest X value
Definition at line 157 of file Plot_window_properties.hh.
References max_X.
Referenced by Quad_PLOT::do_plot_data(), draw_Y_grid(), and draw_Z_grid().
get_max_Y()
double Plot_window_properties::get_max_Y () const inline
return the largest Y value
Definition at line 163 of file Plot_window_properties.hh.
References max_Y.
Referenced by Quad_PLOT::do_plot_data(), draw_surface_lines(), draw_X_grid(), draw_Y_grid(), and draw_Z_grid().
get_max_Z()
double Plot_window_properties::get_max_Z () const inline
return the largest Z value
Definition at line 169 of file Plot_window_properties.hh.
References max_Z.
Referenced by Quad_PLOT::do_plot_data().
get_min_X()
double Plot_window_properties::get_min_X () const inline
return the smallest X value
Definition at line 154 of file Plot_window_properties.hh.
References min_X.
Referenced by Quad_PLOT::do_plot_data(), draw_plot_lines(), draw_X_grid(), draw_Y_grid(), draw_Z_grid(), get_origin(), and valXYZ2pixelXY().
get_min_Y()
double Plot_window_properties::get_min_Y () const inline
return the smallest Y value
Definition at line 160 of file Plot_window_properties.hh.
References min_Y.
Referenced by Quad_PLOT::do_plot_data(), draw_plot_lines(), draw_surface_lines(), draw_X_grid(), draw_Y_grid(), draw_Z_grid(), get_origin(), and valXYZ2pixelXY().
get_min_Z()
double Plot_window_properties::get_min_Z () const inline
return the smallest Z value
Definition at line 166 of file Plot_window_properties.hh.
References min_Z.
Referenced by Quad_PLOT::do_plot_data(), draw_Y_grid(), draw_Z_grid(), get_origin(), and valXYZ2pixelXY().
get_origin()
Pixel_XY Plot_window_properties::get_origin (bool surface) const inline
return the pixel position of the point where the X, Y, and possibly Z-axis cross.
Definition at line 128 of file Plot_window_properties.hh.
References get_min_X(), get_min_Y(), get_min_Z(), valX2pixel(), valXYZ2pixelXY(), and valY2pixel().
Referenced by draw_legend(), draw_X_grid(), draw_Y_grid(), and draw_Z_grid().
get_plot_data()
const Plot_data & Plot_window_properties::get_plot_data () const inline
return the date to be plotted
Definition at line 205 of file Plot_window_properties.hh.
References plot_data.
Referenced by do_plot(), draw_plot_lines(), draw_surface_lines(), and plot_main().
get_scale_X()
double Plot_window_properties::get_scale_X () const inline
return the X value → X pixels scaling factor
Definition at line 172 of file Plot_window_properties.hh.
References scale_X.
get_scale_Y()
double Plot_window_properties::get_scale_Y () const inline
return the Y value → Y pixels scaling factor
Definition at line 175 of file Plot_window_properties.hh.
References scale_Y.
get_scale_Z()
double Plot_window_properties::get_scale_Z () const inline
return the Z value → Z pixels scaling factor
Definition at line 178 of file Plot_window_properties.hh.
References scale_Z.
get_value_per_tile_X()
double Plot_window_properties::get_value_per_tile_X () const inline
return the X-value difference for one tile (= between two X grid lines)
Definition at line 181 of file Plot_window_properties.hh.
References tile_X.
Referenced by draw_X_grid().
get_value_per_tile_Y()
double Plot_window_properties::get_value_per_tile_Y () const inline
return the Y-value difference for one tile (= between two Y grid lines)
Definition at line 184 of file Plot_window_properties.hh.
References tile_Y.
Referenced by draw_Y_grid().
get_value_per_tile_Z()
double Plot_window_properties::get_value_per_tile_Z () const inline
return the Z-value difference for one tile (= between two Z grid lines)
Definition at line 187 of file Plot_window_properties.hh.
References tile_Z.
Referenced by draw_Z_grid().
get_verbosity()
int Plot_window_properties::get_verbosity () const inline
return the verbosity when plotting
Definition at line 199 of file Plot_window_properties.hh.
References verbosity.
Referenced by draw_surface_lines(), and plot_main().
get_window_height()
Pixel_Y Plot_window_properties::get_window_height () const inline
return the height of the plot window
Definition at line 151 of file Plot_window_properties.hh.
References window_height.
Referenced by do_plot(), and plot_main().
get_window_width()
Pixel_X Plot_window_properties::get_window_width () const inline
return the width of the plot window
Definition at line 148 of file Plot_window_properties.hh.
References window_width.
Referenced by do_plot(), and plot_main().
print()
int Plot_window_properties::print (ostream & out) const
print the properties (for debugging purposes)
Definition at line 235 of file Plot_window_properties.cc.
References Plot_data::Color_to_str(), gradient, and line_properties.
Referenced by Quad_PLOT::do_plot_data().
rangeX_max_valid()
bool Plot_window_properties::rangeX_max_valid () const inline
return true iff a rangeX_max property was specified
Definition at line 87 of file Plot_window_properties.hh.
References PLOT_RANGE_MAX, and rangeX_type.
Referenced by update().
rangeX_min_valid()
bool Plot_window_properties::rangeX_min_valid () const inline
return true iff a rangeX_min property was specified
Definition at line 83 of file Plot_window_properties.hh.
References PLOT_RANGE_MIN, and rangeX_type.
Referenced by update().
rangeY_max_valid()
bool Plot_window_properties::rangeY_max_valid () const inline
return true iff a rangeY_max property was specified
Definition at line 95 of file Plot_window_properties.hh.
References PLOT_RANGE_MAX, and rangeY_type.
Referenced by update().
rangeY_min_valid()
bool Plot_window_properties::rangeY_min_valid () const inline
return true iff a rangeY_min property was specified
Definition at line 91 of file Plot_window_properties.hh.
References PLOT_RANGE_MIN, and rangeY_type.
Referenced by update().
rangeZ_max_valid()
bool Plot_window_properties::rangeZ_max_valid () const inline
return true iff a rangeZ_max property was specified
Definition at line 103 of file Plot_window_properties.hh.
References PLOT_RANGE_MAX, and rangeZ_type.
Referenced by update().
rangeZ_min_valid()
bool Plot_window_properties::rangeZ_min_valid () const inline
return true iff a rangeZ_min property was specified
Definition at line 99 of file Plot_window_properties.hh.
References PLOT_RANGE_MIN, and rangeZ_type.
Referenced by update().
round_up_125()
double Plot_window_properties::round_up_125 (double val) static protected
round val up to the next higher 1/2/5×10^N
Definition at line 426 of file Plot_window_properties.cc.
Referenced by update().
set_attribute() [1/2]
const char * Plot_window_properties::set_attribute (const char * att_and_val)
for e.g. att_and_val = "pa_width: 600" set pa_width to 600. Return error string on error.
Definition at line 259 of file Plot_window_properties.cc.
References Plot_data::Color_from_str(), Workspace::get_IO(), gradient, level_color::level, and line_count.
Referenced by Quad_PLOT::parse_attributes(), and set_attribute().
set_attribute() [2/2]
const char * Plot_window_properties::set_attribute (const UCS_string & att, const Cell & val)
for e.g. A.pa_width ← 600" set pa_width to 600. Return error string on error.
Definition at line 377 of file Plot_window_properties.cc.
References UTF8_string::c_str(), Cell::get_int_value(), Cell::get_pointer_value(), Avec::is_digit(), Cell::is_integer_cell(), Cell::is_pointer_cell(), set_attribute(), and UCS_string::size().
set_verbosity()
void Plot_window_properties::set_verbosity (int verb) inline
set the verbosity when plotting
Definition at line 202 of file Plot_window_properties.hh.
References verbosity.
Referenced by Quad_PLOT::do_plot_data().
set_window_size()
void Plot_window_properties::set_window_size (Pixel_X width, Pixel_Y height)
handle window resize event
Definition at line 85 of file Plot_window_properties.cc.
References update().
Referenced by draw_callback(), and plot_main().
update()
bool Plot_window_properties::update (int verbosity)
update derived properties after changing primary ones, return true on error
Definition at line 96 of file Plot_window_properties.cc.
References Plot_data::get_max_X(), Plot_data::get_max_Y(), Plot_data::get_max_Z(), Plot_data::get_min_X(), Plot_data::get_min_Y(), Plot_data::get_min_Z(), gridX_last, gridY_last, gridZ_last, max_X, max_Y, max_Z, min_X, min_Y, min_Z, plot_data, rangeX_max_valid(), rangeX_min_valid(), rangeY_max_valid(), rangeY_min_valid(), rangeZ_max_valid(), rangeZ_min_valid(), round_up_125(), scale_X, scale_Y, scale_Z, tile_X, tile_Y, tile_Z, verbosity, window_height, and window_width.
Referenced by Quad_PLOT::eval_AB(), Plot_window_properties(), and set_window_size().
valX2pixel()
Pixel_X Plot_window_properties::valX2pixel (double val_X) const inline
convert
val_X to the X coordinate of the pixel in the plot area
Definition at line 111 of file Plot_window_properties.hh.
References scale_X.
Referenced by draw_plot_lines(), draw_X_grid(), draw_Y_grid(), draw_Z_grid(), get_origin(), and valXYZ2pixelXY().
valXYZ2pixelXY()
Pixel_XY Plot_window_properties::valXYZ2pixelXY (double val_X, double val_Y, double val_Z) const
convert values val_X, val_Y, and val_Z, to the X and Y coordinate of the pixel below the Z=0 plane of the plot area
Definition at line 500 of file Plot_window_properties.cc.
References get_min_X(), get_min_Y(), get_min_Z(), valX2pixel(), valY2pixel(), and valZ2pixel().
Referenced by draw_surface_lines(), draw_Y_grid(), draw_Z_grid(), and get_origin().
valY2pixel()
Pixel_Y Plot_window_properties::valY2pixel (double val_Y) const inline
convert
val_Y to the Y coordinate of the pixel in the plot area
Definition at line 115 of file Plot_window_properties.hh.
References scale_Y.
Referenced by draw_plot_lines(), draw_X_grid(), draw_Y_grid(), draw_Z_grid(), get_origin(), and valXYZ2pixelXY().
valZ2pixel()
Pixel_Z Plot_window_properties::valZ2pixel (double val_Z) const inline
convert
val_Z to the relative Z vector (q. quadrant)
Definition at line 119 of file Plot_window_properties.hh.
References scale_Z.
Referenced by valXYZ2pixelXY().
Member Data Documentation
gradient
vector<level_color> Plot_window_properties::gradient protected
some levels with colors (for surface plots)
Definition at line 295 of file Plot_window_properties.hh.
Referenced by get_color(), get_gradient(), print(), and set_attribute().
gridX_last
int Plot_window_properties::gridX_last protected
the last index of the X grid
Definition at line 271 of file Plot_window_properties.hh.
Referenced by get_gridX_last(), and update().
gridY_last
int Plot_window_properties::gridY_last protected
the last index of the Y grid
Definition at line 274 of file Plot_window_properties.hh.
Referenced by get_gridY_last(), and update().
gridZ_last
int Plot_window_properties::gridZ_last protected
the last index of the Y grid
Definition at line 277 of file Plot_window_properties.hh.
Referenced by get_gridZ_last(), and update().
line_count
const int Plot_window_properties::line_count protected
the number of plot lines
Definition at line 221 of file Plot_window_properties.hh.
Referenced by get_line_count(), Plot_window_properties(), and set_attribute().
line_properties
Plot_line_properties* * Plot_window_properties::line_properties protected
array containing the data for the plot lines
Definition at line 292 of file Plot_window_properties.hh.
Referenced by get_line_properties(), Plot_window_properties(), and print().
max_X
double Plot_window_properties::max_X protected
the largest X value
Definition at line 238 of file Plot_window_properties.hh.
Referenced by get_max_X(), Plot_window_properties(), and update().
max_Y
double Plot_window_properties::max_Y protected
the largest Y value
Definition at line 244 of file Plot_window_properties.hh.
Referenced by get_max_Y(), Plot_window_properties(), and update().
max_Z
double Plot_window_properties::max_Z protected
the largest Z value
Definition at line 250 of file Plot_window_properties.hh.
Referenced by get_max_Z(), Plot_window_properties(), and update().
min_X
double Plot_window_properties::min_X protected
the smallest X value
Definition at line 235 of file Plot_window_properties.hh.
Referenced by get_min_X(), Plot_window_properties(), and update().
min_Y
double Plot_window_properties::min_Y protected
the smallest Y value
Definition at line 241 of file Plot_window_properties.hh.
Referenced by get_min_Y(), Plot_window_properties(), and update().
min_Z
double Plot_window_properties::min_Z protected
the smallest Z value
Definition at line 247 of file Plot_window_properties.hh.
Referenced by get_min_Z(), Plot_window_properties(), and update().
plot_data
const Plot_data& Plot_window_properties::plot_data protected
the date to be plotted
Definition at line 224 of file Plot_window_properties.hh.
Referenced by get_plot_data(), update(), and ~Plot_window_properties().
properties_set
vector<uint16_t> Plot_window_properties::properties_set protected
a list of properties that have been set alreay (to protect items from being overridden in set_all_XXX() functions
Definition at line 306 of file Plot_window_properties.hh.
Referenced by can_be_set().
rangeX_type
Plot_Range_type Plot_window_properties::rangeX_type protected
the kind of X range
Definition at line 283 of file Plot_window_properties.hh.
Referenced by rangeX_max_valid(), and rangeX_min_valid().
rangeY_type
Plot_Range_type Plot_window_properties::rangeY_type protected
the kind of Y range
Definition at line 286 of file Plot_window_properties.hh.
Referenced by rangeY_max_valid(), and rangeY_min_valid().
rangeZ_type
Plot_Range_type Plot_window_properties::rangeZ_type protected
the kind of Z range
Definition at line 289 of file Plot_window_properties.hh.
Referenced by rangeZ_max_valid(), and rangeZ_min_valid().
scale_X
double Plot_window_properties::scale_X protected
the X value → X pixels scaling factor
Definition at line 253 of file Plot_window_properties.hh.
Referenced by get_scale_X(), update(), and valX2pixel().
scale_Y
double Plot_window_properties::scale_Y protected
the Y value → Y pixels scaling factor
Definition at line 256 of file Plot_window_properties.hh.
Referenced by get_scale_Y(), update(), and valY2pixel().
scale_Z
double Plot_window_properties::scale_Z protected
the Z value → Z pixels scaling factor
Definition at line 259 of file Plot_window_properties.hh.
Referenced by get_scale_Z(), update(), and valZ2pixel().
tile_X
double Plot_window_properties::tile_X protected
the number of pixels between X grid lines
Definition at line 262 of file Plot_window_properties.hh.
Referenced by get_value_per_tile_X(), and update().
tile_Y
double Plot_window_properties::tile_Y protected
the number of pixels between Y grid lines
Definition at line 265 of file Plot_window_properties.hh.
Referenced by get_value_per_tile_Y(), and update().
tile_Z
double Plot_window_properties::tile_Z protected
the number of pixels between Z grid lines
Definition at line 268 of file Plot_window_properties.hh.
Referenced by get_value_per_tile_Z(), and update().
verbosity
int Plot_window_properties::verbosity protected
the verbosity when plotting
Definition at line 280 of file Plot_window_properties.hh.
Referenced by get_verbosity(), Plot_window_properties(), set_verbosity(), and update().
window_height
Pixel_Y Plot_window_properties::window_height protected
the height of the plot window
Definition at line 232 of file Plot_window_properties.hh.
Referenced by get_window_height(), and update().
window_width
Pixel_X Plot_window_properties::window_width protected
the width of the plot window
Definition at line 230 of file Plot_window_properties.hh.
Referenced by get_window_width(), and update().
The documentation for this class was generated from the following files:
src/Plot_window_properties.hh
src/Plot_window_properties.cc