GNU APL: Quad_GTK Class Reference
Quad_GTK Class Reference
The class implementing ⎕GTK.
#include <Quad_GTK.hh>
Classes
struct window_entry
the context for a GTL window
Public Member Functions
Quad_GTK ()
Constructor.
Public Member Functions inherited from QuadFunction
QuadFunction (TokenTag tag)
Constructor.
virtual bool has_alpha () const
overloaded Function::has_alpha()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B().
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB().
virtual bool has_result () const
overloaded Function::has_result()
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
virtual bool has_result () const
overloaded Function::has_result()
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Static Public Member Functions
static void clear ()
close all open windows
Static Public Attributes
static Quad_GTK * fun = &Quad_GTK::_fun
Built-in function.
static Quad_GTK _fun
Built-in function.
Protected Types
enum Gtype {
gtype_V = 0 ,
gtype_S = 1 ,
gtype_I = 2 ,
gtype_F = 3
}
the type of a function parameter or return value
Protected Member Functions
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB()
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
overloaded Function::eval_AXB()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B()
virtual Token eval_XB (Value_P X, Value_P B) const
overloaded Function::eval_XB()
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Static Protected Member Functions
static int resolve_window (const Value *X, UTF8_string &window_id)
X is supposed to be something like 4,"win_id". Store win_id in window_id and return the window number (4 in this example)
static Fnum resolve_fun_name (UTF8_string &window_id, const Value *B)
B is a function name (-suffix).
static int write_TL0 (int fd, int tag)
write a TLV with an empty V (thus L=0)
static int write_TLV (int fd, int tag, const UTF8_string &value)
write a TLV
static int open_window (const UCS_string &gui_filename, const UCS_string *css_filename)
open the GTH window described by gui_filename and optional css_filename
static Value_P window_list ()
return the handles of currently open windows
static Value_P close_window (int fd)
close the window with file descriptor fd
static void poll_all ()
poll all fds and insert events into event_queue until no more events are pending
static Value_P poll_response (int fd, int tag)
poll for a TLV on fd with a specific (reponse-) tag
static Value_P read_fd (int fd, int tag)
Static Protected Attributes
static std::vector< window_entry > open_windows
the currently open GTK windows
static UCS_string_vector event_queue
event queue for events from the GTK windows
Additional Inherited Members
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
The class implementing ⎕GTK.
Definition at line 32 of file Quad_GTK.hh.
Member Enumeration Documentation
Gtype
enum Quad_GTK::Gtype protected
the type of a function parameter or return value
Enumerator
gtype_V
void
gtype_S
string
gtype_I
integer
gtype_F
float
Definition at line 48 of file Quad_GTK.hh.
Constructor & Destructor Documentation
Quad_GTK()
Quad_GTK::Quad_GTK () inline
Constructor.
Definition at line 36 of file Quad_GTK.hh.
Member Function Documentation
clear()
void Quad_GTK::clear () static
close all open windows
Definition at line 540 of file Quad_GTK.cc.
References close_window(), and open_windows.
Referenced by Workspace::clear_WS().
close_window()
Value_P Quad_GTK::close_window (int fd) static protected
close the window with file descriptor fd
Definition at line 546 of file Quad_GTK.cc.
References Quad_FIO::close_handle(), Quad_GTK::window_entry::fd, open_windows, and write_TL0().
Referenced by clear(), and eval_AB().
eval_AB()
Token Quad_GTK::eval_AB (Value_P A, Value_P B) const protected virtual
overloaded Function::eval_AB()
Reimplemented from QuadFunction.
Definition at line 42 of file Quad_GTK.cc.
References close_window(), open_window(), and write_TL0().
eval_AXB()
Token Quad_GTK::eval_AXB (Value_P A, Value_P X, Value_P B) const protected virtual
overloaded Function::eval_AXB()
Reimplemented from Function.
Definition at line 196 of file Quad_GTK.cc.
References UCS_string::append(), fun, Value_P_Base::get(), Cell::get_pointer_value(), gtype_V, Cell::is_pointer_cell(), poll_response(), resolve_fun_name(), resolve_window(), and write_TLV().
eval_B()
Token Quad_GTK::eval_B (Value_P B) const protected virtual
overloaded Function::eval_B()
Reimplemented from QuadFunction.
Definition at line 107 of file Quad_GTK.cc.
References UCS_string::append(), UCS_string_vector::erase(), event_queue, Value_P_Base::get(), open_window(), poll_all(), UCS_string::size(), and window_list().
eval_XB()
Token Quad_GTK::eval_XB (Value_P X, Value_P B) const protected virtual
overloaded Function::eval_XB()
Reimplemented from Function.
Definition at line 277 of file Quad_GTK.cc.
References fun, Value_P_Base::get(), gtype_V, poll_response(), resolve_fun_name(), resolve_window(), write_TL0(), and write_TLV().
open_window()
int Quad_GTK::open_window (const UCS_string & gui_filename, const UCS_string * css_filename) static protected
open the GTH window described by gui_filename and optional css_filename
Definition at line 616 of file Quad_GTK.cc.
References UTF8_string::c_str(), Quad_FIO::close_handle(), Quad_FIO::do_FIO_57(), LibPaths::get_APL_bin_path(), open_windows, and write_TL0().
Referenced by eval_AB(), and eval_B().
poll_all()
void Quad_GTK::poll_all () static protected
poll all fds and insert events into event_queue until no more events are pending
Definition at line 398 of file Quad_GTK.cc.
References open_windows, and read_fd().
Referenced by eval_B().
poll_response()
Value_P Quad_GTK::poll_response (int fd, int tag) static protected
poll for a TLV on fd with a specific (reponse-) tag
Definition at line 431 of file Quad_GTK.cc.
References read_fd(), and Function::tag.
Referenced by eval_AXB(), and eval_XB().
read_fd()
Value_P Quad_GTK::read_fd (int fd, int tag) static protected
read a TLV with a given tag (or any TLV if tag == -1) on a fd that is ready for reading. If the TLV is an event (i.e. unexpected) then insert it into event_queue and return 0; otherwise the TLV is a response that is returned.
Definition at line 319 of file Quad_GTK.cc.
References event_queue, UCS_string::size(), and Function::tag.
Referenced by poll_all(), and poll_response().
resolve_fun_name()
Quad_GTK::Fnum Quad_GTK::resolve_fun_name (UTF8_string & window_id, const Value * B) static protected
B is a function name (-suffix).
Definition at line 511 of file Quad_GTK.cc.
References UTF8_string::c_str().
Referenced by eval_AXB(), and eval_XB().
resolve_window()
int Quad_GTK::resolve_window (const Value * X, UTF8_string & window_id) static protected
X is supposed to be something like 4,"win_id". Store win_id in window_id and return the window number (4 in this example)
Definition at line 478 of file Quad_GTK.cc.
References Value::element_count(), Value::get_cfirst(), Cell::get_char_value(), Value::get_cravel(), Cell::get_int_value(), Value::get_rank(), and open_windows.
Referenced by eval_AXB(), and eval_XB().
window_list()
Value_P Quad_GTK::window_list () static protected
return the handles of currently open windows
Definition at line 463 of file Quad_GTK.cc.
References open_windows.
Referenced by eval_B().
write_TL0()
int Quad_GTK::write_TL0 (int fd, int tag) static protected
write a TLV with an empty V (thus L=0)
Definition at line 569 of file Quad_GTK.cc.
References Function::tag.
Referenced by close_window(), eval_AB(), eval_XB(), and open_window().
write_TLV()
int Quad_GTK::write_TLV (int fd, int tag, const UTF8_string & value) static protected
write a TLV
Definition at line 592 of file Quad_GTK.cc.
References Function::tag.
Referenced by eval_AXB(), and eval_XB().
Member Data Documentation
_fun
Quad_GTK Quad_GTK::_fun static
Built-in function.
Definition at line 41 of file Quad_GTK.hh.
event_queue
UCS_string_vector Quad_GTK::event_queue static protected
event queue for events from the GTK windows
Definition at line 117 of file Quad_GTK.hh.
Referenced by eval_B(), and read_fd().
fun
Quad_GTK * Quad_GTK::fun = &Quad_GTK::_fun static
Built-in function.
Definition at line 40 of file Quad_GTK.hh.
Referenced by eval_AXB(), and eval_XB().
open_windows
std::vector< Quad_GTK::window_entry > Quad_GTK::open_windows static protected
the currently open GTK windows
Definition at line 114 of file Quad_GTK.hh.
Referenced by clear(), close_window(), open_window(), poll_all(), resolve_window(), and window_list().
The documentation for this class was generated from the following files:
src/Quad_GTK.hh
src/Quad_GTK.cc