GNU APL: File_or_String Class Reference
File_or_String Class Reference
a Unicode source from either a file or a UCS_string
Public Member Functions
File_or_String (FILE *f)
constructor: from file
File_or_String (const UCS_string *u)
constructor: from string
ShapeItem get_count () const
return the number of characters
Unicode get_next ()
get the next character
void unget (Unicode uni)
unget uni. At most one Unicode (= lookahead char) can be ungotten.
int scanf_long_long (const char *fmt, long long *val)
scan a long long in a string or in a file. Return either 0 or 1 for the number of successful conversions.
int scanf_double (const char *fmt, APL_Float *val)
scan a double in string or file. Return either 0 or 1 for the number of successful conversions.
Protected Attributes
FILE * file
UTF8-encoded source file (or 0 for string input)
const UCS_string * string
UCS_string source (or 0 for file source)
ShapeItem sidx
next character in string
Unicode next
ungotten char
ShapeItem out_len
number of chars consumed thus far
Detailed Description
a Unicode source from either a file or a UCS_string
Definition at line 537 of file Quad_FIO.cc.
Constructor & Destructor Documentation
File_or_String() [1/2]
File_or_String::File_or_String (FILE * f) inline
constructor: from file
Definition at line 541 of file Quad_FIO.cc.
References sidx.
File_or_String() [2/2]
File_or_String::File_or_String (const UCS_string * u) inline
constructor: from string
Definition at line 549 of file Quad_FIO.cc.
Member Function Documentation
get_count()
ShapeItem File_or_String::get_count () const inline
return the number of characters
Definition at line 558 of file Quad_FIO.cc.
References file, out_len, and sidx.
Referenced by Quad_FIO::do_scanf().
get_next()
Unicode File_or_String::get_next () inline
get the next character
Definition at line 565 of file Quad_FIO.cc.
References Quad_FIO::fget_utf8(), file, next, out_len, sidx, UCS_string::size(), and string.
Referenced by Quad_FIO::do_scanf(), scanf_double(), and scanf_long_long().
scanf_double()
int File_or_String::scanf_double (const char * fmt, APL_Float * val) inline
scan a double in string or file. Return either 0 or 1 for the number of successful conversions.
Definition at line 644 of file Quad_FIO.cc.
References file, get_next(), next, and unget().
Referenced by Quad_FIO::do_scanf().
scanf_long_long()
int File_or_String::scanf_long_long (const char * fmt, long long * val) inline
scan a long long in a string or in a file. Return either 0 or 1 for the number of successful conversions.
Definition at line 599 of file Quad_FIO.cc.
References file, get_next(), Avec::is_digit(), next, and unget().
Referenced by Quad_FIO::do_scanf().
unget()
void File_or_String::unget (Unicode uni) inline
unget uni. At most one Unicode (= lookahead char) can be ungotten.
Definition at line 591 of file Quad_FIO.cc.
References next.
Referenced by Quad_FIO::do_scanf(), scanf_double(), and scanf_long_long().
Member Data Documentation
file
FILE* File_or_String::file protected
UTF8-encoded source file (or 0 for string input)
Definition at line 685 of file Quad_FIO.cc.
Referenced by get_count(), get_next(), scanf_double(), and scanf_long_long().
next
Unicode File_or_String::next protected
ungotten char
Definition at line 694 of file Quad_FIO.cc.
Referenced by get_next(), scanf_double(), scanf_long_long(), and unget().
out_len
ShapeItem File_or_String::out_len protected
number of chars consumed thus far
Definition at line 697 of file Quad_FIO.cc.
Referenced by get_count(), and get_next().
sidx
ShapeItem File_or_String::sidx protected
next character in string
Definition at line 691 of file Quad_FIO.cc.
Referenced by File_or_String(), get_count(), and get_next().
string
const UCS_string* File_or_String::string protected
UCS_string source (or 0 for file source)
Definition at line 688 of file Quad_FIO.cc.
Referenced by get_next().
The documentation for this class was generated from the following file:
src/Quad_FIO.cc