GNU APL: Shape Class Reference
Shape Class Reference
the shape of an APL value
#include <Shape.hh>
Public Member Functions
Shape ()
constructor: shape of a scalar.
Shape (ShapeItem len)
constructor: shape of a vector of length len
Shape (ShapeItem rows, ShapeItem cols)
constructor: shape of a matrix with rows rows and cols columns
Shape (ShapeItem height, ShapeItem rows, ShapeItem cols)
constructor: shape of a cube
Shape (uRank rk, const ShapeItem *sh)
constructor: arbitrary shape
Shape (const Shape &other)
constructor: shape of another shape
Shape (const Value &A, int qio_A)
constructor: shape defined by the ravel of an APL value A throw RANK or LENGTH error where needed. Negative values are allowed in order to support e.g. ¯4 ↑ B
Shape abs () const
return a shape like this, but with negative elements made positive
Shape high_shape (uRank cnt) const
return a shape with the upper cnt dimensions of this shape
Shape low_shape (uRank cnt) const
return a shape with the lower cnt dimensions of this shape
Shape operator+ (const Shape &lower) const
catenate two shapes, this shape provides the higher dimensions while lower provides the lower dimensions of the shape returned
bool operator== (const Shape &other) const
return true iff this shape equals other
bool operator!= (const Shape &other) const
return true iff this shape is different from other
uRank get_rank () const
return the rank
ShapeItem get_shape_item (sAxis r) const
return the length of dimension r
ShapeItem get_transposed_shape_item (sAxis r) const
return the length of dimension r
ShapeItem get_first_shape_item () const
return the length of the first axis, or 1 for scalars
ShapeItem get_last_shape_item () const
return the length of the last axis, or 1 for scalars
ShapeItem get_cols () const
return the length of the last axis, or 1 for scalars
ShapeItem get_rows () const
return the product of all but the the last dimension, or 1 for scalars
void set_shape_item (sAxis r, ShapeItem sh)
modify dimension r
void recompute_volume ()
recompute volume (after changing a dimension of len 0)
void increment_shape_item (sRank r)
increment length of axis r by 1
void set_last_shape_item (ShapeItem sh)
set last dimension to sh
void add_shape_item (ShapeItem len)
add a dimension of length len at the end
void expand_rank (sRank new_rank)
possibly increase rank by prepending axes of length 1
void expand (const Shape &B)
possibly expand rank and increase axes so that B fits into this shape
Shape insert_axis (sAxis axis, ShapeItem len) const
return a shape like this, but with a new dimension of length len inserted so that Shape[axis] == len in the returned shape.
Shape without_axis (sAxis axis) const
return a shape like this, but with axis axis removed
Shape without_first_axis () const
return a shape like this, but with the first axis (↑⍴) removed
Shape without_last_axis () const
return a shape like this, but with the last axis (¯1↑⍴) removed
ShapeItem get_volume () const
return the number of ravel elements (1 for scalars,i else product of shapes)
ShapeItem get_nz_volume () const
return the number of ravel elements, but at least 1 (for empty values and scalars) else product of shapes)
bool contains_axis (sAxis ax) const
return true iff one of the shape elements is (axis) ax
bool contains (const Shape &value) const
return true iff the items of value are at most the items of this
Shape get_weights () const
return ⌽ ×\ ⍴ ⌽ this
void check_same (const Shape &B, ErrorCode rank_err, ErrorCode len_err, const char *loc) const
throw an APL error if this shape differs from shape B
bool is_empty () const
return true iff this shape is empty (some dimension is 0).
bool is_permutation () const
return reue iff this shape is a permutation of 0, 1, ... rank-1
ShapeItem ravel_pos (const Shape &idx) const
return the position of idx in the ravel.
Shape offset_to_index (ShapeItem offset, int quad_io) const
the inverse of ravel_pos()
Protected Attributes
sRank rho_rho
the rank (number of valid shape items)
ShapeItem rho [MAX_RANK]
the shape
ShapeItem volume
+/rho
Detailed Description
the shape of an APL value
Definition at line 31 of file Shape.hh.
Constructor & Destructor Documentation
Shape() [1/7]
Shape::Shape () inline
constructor: shape of a scalar.
Definition at line 35 of file Shape.hh.
References rho.
Referenced by high_shape(), and low_shape().
Shape() [2/7]
Shape::Shape (ShapeItem len) inline
constructor: shape of a vector of length len
Definition at line 41 of file Shape.hh.
References rho.
Shape() [3/7]
Shape::Shape (ShapeItem rows, ShapeItem cols) inline
constructor: shape of a matrix with rows rows and cols columns
Definition at line 47 of file Shape.hh.
References rho.
Shape() [4/7]
Shape::Shape (ShapeItem height, ShapeItem rows, ShapeItem cols) inline
constructor: shape of a cube
Definition at line 53 of file Shape.hh.
References rho.
Shape() [5/7]
Shape::Shape (uRank rk, const ShapeItem * sh) inline
constructor: arbitrary shape
Definition at line 59 of file Shape.hh.
References add_shape_item().
Shape() [6/7]
Shape::Shape (const Shape & other) inline
constructor: shape of another shape
Definition at line 65 of file Shape.hh.
References rho.
Shape() [7/7]
Shape::Shape (const Value & A, int qio_A)
constructor: shape defined by the ravel of an APL value A throw RANK or LENGTH error where needed. Negative values are allowed in order to support e.g. ¯4 ↑ B
Definition at line 25 of file Shape.cc.
References add_shape_item().
Member Function Documentation
abs()
Shape Shape::abs () const
return a shape like this, but with negative elements made positive
Definition at line 41 of file Shape.cc.
References add_shape_item(), rho, and rho_rho.
Referenced by Bif_F12_TAKE::do_take().
add_shape_item()
void Shape::add_shape_item (ShapeItem len) inline
add a dimension of length len at the end
Definition at line 162 of file Shape.hh.
References rho, rho_rho, and volume.
Referenced by abs(), Symbol::assign_indexed(), Bif_COMMA::catenate(), Bif_F12_PICK::disclose_with_axis(), Quad_CR::do_CR30(), Quad_CR::do_CR5_6(), Quad_RVAL::do_eval_B(), Bif_F12_TRANSPOSE::do_eval_B(), Quad_CR::do_eval_B(), Bif_F12_PARTITION::enclose_with_axes(), Bif_F12_DOMINO::eval_AB(), Bif_F12_TAKE::eval_AB(), Bif_F12_DROP::eval_AB(), Quad_SVC::eval_AB(), Quad_SVO::eval_AB(), Quad_AT::eval_AB(), Bif_F2_FIND::eval_AB(), Bif_F12_FORMAT::eval_B(), Quad_SVC::eval_B(), Quad_SVO::eval_B(), Quad_SVR::eval_B(), Quad_SVS::eval_B(), Quad_EX::eval_B(), Quad_NC::eval_B(), Bif_F12_DOMINO::eval_fill_AB(), Quad_FIO::eval_XB(), Bif_SCAN::expand(), Bif_F12_FORMAT::format_by_example(), Bif_F12_FORMAT::format_by_specification(), CDR::from_CDR(), Command::transfer_context::get_nrs(), ArrayIterator::get_shape_offsets(), Value::index(), insert_axis(), operator+(), Bif_F12_TRANSPOSE::permute(), Quad_RVAL::Quad_RVAL(), Bif_COMMA::ravel_axis(), XML_Loading_Archive::read_Value(), Bif_REDUCE::reduce_n_wise(), Bif_REDUCE::replicate(), Quad_RVAL::result_shape(), Shape(), Quad_TF::tf1_inv(), Value::to_shape(), Bif_F12_TRANSPOSE::transpose_diag(), without_axis(), without_first_axis(), and without_last_axis().
check_same()
void Shape::check_same (const Shape & B, ErrorCode rank_err, ErrorCode len_err, const char * loc) const
throw an APL error if this shape differs from shape B
Definition at line 147 of file Shape.cc.
References get_rank(), and get_shape_item().
contains()
bool Shape::contains (const Shape & value) const inline
return true iff the items of value are at most the items of this
Definition at line 218 of file Shape.hh.
References rho, and rho_rho.
contains_axis()
bool Shape::contains_axis (sAxis ax) const inline
return true iff one of the shape elements is (axis) ax
Definition at line 214 of file Shape.hh.
References rho, and rho_rho.
expand()
void Shape::expand (const Shape & B)
possibly expand rank and increase axes so that B fits into this shape
Definition at line 66 of file Shape.cc.
References expand_rank(), rho, rho_rho, and volume.
expand_rank()
void Shape::expand_rank (sRank new_rank) inline
possibly increase rank by prepending axes of length 1
Definition at line 167 of file Shape.hh.
References rho, and rho_rho.
Referenced by Quad_CR::do_CR30(), expand(), and TakeDropIterator::TakeDropIterator().
get_cols()
ShapeItem Shape::get_cols () const inline
return the length of the last axis, or 1 for scalars
Definition at line 132 of file Shape.hh.
References rho, and rho_rho.
Referenced by Bif_F12_FORMAT::format_by_specification(), and Value::get_cols().
get_first_shape_item()
ShapeItem Shape::get_first_shape_item () const inline
return the length of the first axis, or 1 for scalars
Definition at line 124 of file Shape.hh.
References rho, and rho_rho.
Referenced by Value::get_first_shape_item(), and Bif_COMMA::ravel_axis().
get_last_shape_item()
ShapeItem Shape::get_last_shape_item () const inline
return the length of the last axis, or 1 for scalars
Definition at line 128 of file Shape.hh.
References rho, and rho_rho.
Referenced by PrintBuffer::add_frame(), Bif_REDUCE::do_reduce(), Value::get_last_shape_item(), and Bif_COMMA::ravel_axis().
get_nz_volume()
ShapeItem Shape::get_nz_volume () const inline
return the number of ravel elements, but at least 1 (for empty values and scalars) else product of shapes)
Definition at line 210 of file Shape.hh.
References volume.
Referenced by Value::nz_element_count(), and Value::Value().
get_rank()
uRank Shape::get_rank () const inline
return the rank
Definition at line 112 of file Shape.hh.
References rho_rho.
Referenced by PrintBuffer::add_frame(), UCS_string::append_shape(), Symbol::assign_indexed(), TakeDropIterator::axis_proto(), PointerCell::character_representation(), IndexExpr::check_index_range(), check_same(), CollatingCache::CollatingCache(), ScalarFunction::conforming_shape(), Bif_F12_PICK::disclose_with_axis(), Quad_CR::do_CR30(), Quad_CR::do_CR5_6(), Bif_OPER2_RANK::do_LyXB(), Bif_F12_PARTITION::enclose_with_axes(), Bif_F12_TAKE::eval_AB(), Bif_F12_DROP::eval_AB(), Bif_F12_TRANSPOSE::eval_AB(), Bif_F12_RHO::eval_AB(), Quad_RE::eval_AXB(), Bif_F12_INTERVAL_INDEX::eval_B(), NonscalarFunction_default_identity::eval_identity_fun(), Bif_SCAN::expand(), Quad_FFT::fill_window(), Quad_CR::Picker::get(), Value::get_rank(), high_shape(), insert_axis(), Bif_F12_TRANSPOSE::inverse_permutation(), is_permutation(), Value::is_scalar(), low_shape(), MultiIndexIterator::MultiIndexIterator(), Command::transfer_context::numeric_1TF(), TakeDropIterator::operator++(), PrintBuffer::pb_empty(), Bif_F12_TRANSPOSE::permute(), Quad_RVAL::Quad_RVAL(), Bif_COMMA::ravel_axis(), ravel_pos(), Bif_REDUCE::replicate(), Quad_RVAL::result_shape(), PrintBuffer::separator_rows(), Shape3::Shape3(), StateIndicator::statement_result(), TakeDropIterator::TakeDropIterator(), Quad_TF::tf2_shape(), and Value::Value().
get_rows()
ShapeItem Shape::get_rows () const inline
return the product of all but the the last dimension, or 1 for scalars
Definition at line 136 of file Shape.hh.
References rho, rho_rho, and volume.
Referenced by Bif_F12_FORMAT::format_by_specification(), and Value::get_rows().
get_shape_item()
ShapeItem Shape::get_shape_item (sAxis r) const inline
return the length of dimension r
Definition at line 116 of file Shape.hh.
References rho, and rho_rho.
Referenced by PrintBuffer::add_frame(), Bif_COMMA::append_scalar(), UCS_string::append_shape(), ArrayIterator::ArrayIterator(), PointerCell::character_representation(), IndexExpr::check_index_range(), check_same(), CollatingCache::CollatingCache(), CollatingCacheEntry::compare_axis(), Bif_F2_FIND::contained(), Bif_F12_PICK::disclose_with_axis(), Quad_CR::do_CR30(), Quad_RVAL::do_eval_B(), Bif_OPER2_RANK::do_LyXB(), Bif_F12_PARTITION::enclose_with_axes(), Bif_F12_DROP::eval_AB(), Bif_F12_TRANSPOSE::eval_AB(), Bif_F12_RHO::eval_AB(), Bif_F2_FIND::eval_AB(), Bif_F12_INDEX_OF::eval_B(), Bif_F12_INTERVAL_INDEX::eval_B(), NonscalarFunction_default_identity::eval_identity_fun(), ScalarFunction::eval_scalar_AXB(), Bif_SCAN::expand(), Quad_FFT::fill_window(), Value::get_shape_item(), insert_axis(), Bif_F12_TRANSPOSE::inverse_permutation(), is_permutation(), MultiIndexIterator::MultiIndexIterator(), PrintBuffer::pb_empty(), Bif_F12_TRANSPOSE::permute(), Bif_F12_PICK::pick_offset(), Bif_COMMA::prepend_scalar(), Bif_COMMA::ravel_axis(), ravel_pos(), Bif_REDUCE::reduce_n_wise(), Bif_REDUCE::replicate(), Quad_RVAL::result_shape(), PrintBuffer::separator_rows(), Shape3::Shape3(), StateIndicator::statement_result(), Quad_TF::tf2_shape(), and Value::Value().
get_transposed_shape_item()
ShapeItem Shape::get_transposed_shape_item (sAxis r) const inline
return the length of dimension r
Definition at line 120 of file Shape.hh.
References rho, and rho_rho.
Referenced by TakeDropIterator::operator++(), and TakeDropIterator::TakeDropIterator().
get_volume()
ShapeItem Shape::get_volume () const inline
return the number of ravel elements (1 for scalars,i else product of shapes)
Definition at line 205 of file Shape.hh.
References volume.
Referenced by ScalarFunction::conforming_shape(), Bif_F12_PICK::disclose(), Bif_OPER2_RANK::do_ALyXB(), Quad_CR::do_CR30(), Bif_OPER2_RANK::do_LyXB(), ScalarFunction::do_scalar_AB(), Value::element_count(), Bif_F12_DROP::eval_AB(), Bif_F12_DECODE::eval_AB(), Bif_F12_RHO::eval_AB(), Bif_OPER1_EACH::eval_ALB(), Bif_OPER2_INNER::eval_ALRB(), Quad_RE::eval_AXB(), Bif_F12_FORMAT::eval_B(), NonscalarFunction_default_identity::eval_identity_fun(), Bif_F12_WITHOUT::eval_identity_fun(), Bif_F12_FORMAT::format_by_specification(), CDR::from_CDR(), Value::init_ravel(), Command::transfer_context::numeric_1TF(), PrintBuffer::pb_empty(), Value::set_shape(), StateIndicator::statement_result(), Quad_TF::tf1_inv(), and Quad_TF::tf2_reduce_RHO().
get_weights()
Shape Shape::get_weights () const inline
return ⌽ ×\ ⍴ ⌽ this
Definition at line 224 of file Shape.hh.
References rho, rho_rho, and volume.
high_shape()
Shape Shape::high_shape (uRank cnt) const inline
return a shape with the upper cnt dimensions of this shape
Definition at line 89 of file Shape.hh.
References get_rank(), rho, and Shape().
increment_shape_item()
void Shape::increment_shape_item (sRank r) inline
increment length of axis r by 1
Definition at line 154 of file Shape.hh.
References rho, and set_shape_item().
Referenced by Bif_REDUCE::reduce_n_wise().
insert_axis()
Shape Shape::insert_axis (sAxis axis, ShapeItem len) const
return a shape like this, but with a new dimension of length len inserted so that Shape[axis] == len in the returned shape.
Definition at line 83 of file Shape.cc.
References add_shape_item(), get_rank(), and get_shape_item().
is_empty()
bool Shape::is_empty () const inline
return true iff this shape is empty (some dimension is 0).
Definition at line 242 of file Shape.hh.
References rho, and rho_rho.
Referenced by Bif_OPER2_RANK::do_ALyXB(), Bif_OPER2_RANK::do_LyXB(), Bif_F12_TAKE::do_take(), Bif_F12_PARTITION::enclose_with_axes(), Bif_F12_DROP::eval_AB(), Value::is_empty(), Bif_REDUCE::reduce_n_wise(), and Bif_F12_TRANSPOSE::transpose().
is_permutation()
bool Shape::is_permutation () const
return reue iff this shape is a permutation of 0, 1, ... rank-1
Definition at line 160 of file Shape.cc.
References get_rank(), and get_shape_item().
Referenced by Bif_F12_TRANSPOSE::eval_AB().
low_shape()
Shape Shape::low_shape (uRank cnt) const inline
return a shape with the lower cnt dimensions of this shape
Definition at line 93 of file Shape.hh.
References get_rank(), rho, and Shape().
offset_to_index()
Shape Shape::offset_to_index (ShapeItem offset, int quad_io) const
the inverse of ravel_pos()
Definition at line 125 of file Shape.cc.
References rho, and rho_rho.
operator!=()
bool Shape::operator!= (const Shape & other) const inline
return true iff this shape is different from other
Definition at line 108 of file Shape.hh.
operator+()
Shape Shape::operator+ (const Shape & lower) const inline
catenate two shapes, this shape provides the higher dimensions while lower provides the lower dimensions of the shape returned
Definition at line 99 of file Shape.hh.
References add_shape_item(), rho, and rho_rho.
operator==()
bool Shape::operator== (const Shape & other) const
return true iff this shape equals other
Definition at line 55 of file Shape.cc.
References rho, and rho_rho.
ravel_pos()
ShapeItem Shape::ravel_pos (const Shape & idx) const
return the position of idx in the ravel.
Definition at line 110 of file Shape.cc.
References get_rank(), and get_shape_item().
recompute_volume()
void Shape::recompute_volume () inline
recompute volume (after changing a dimension of len 0)
Definition at line 150 of file Shape.hh.
References rho, rho_rho, and volume.
Referenced by set_shape_item().
set_last_shape_item()
void Shape::set_last_shape_item (ShapeItem sh) inline
set last dimension to sh
Definition at line 158 of file Shape.hh.
References rho_rho, and set_shape_item().
Referenced by Bif_F12_FORMAT::eval_B(), Bif_F12_FORMAT::format_by_example(), and Bif_F12_FORMAT::format_by_specification().
set_shape_item()
void Shape::set_shape_item (sAxis r, ShapeItem sh) inline
modify dimension r
Definition at line 144 of file Shape.hh.
References recompute_volume(), rho, rho_rho, and volume.
Referenced by Bif_COMMA::append_scalar(), PointerCell::character_representation(), CollatingCache::CollatingCache(), Quad_CR::do_CR13(), Quad_CR::do_CR5_6(), Value::double_ravel(), Bif_F12_TAKE::eval_AXB(), Bif_F12_DROP::eval_AXB(), Bif_F12_TAKE::eval_XB(), Bif_SCAN::expand(), increment_shape_item(), Bif_F12_PARTITION::partition(), Bif_COMMA::prepend_scalar(), Bif_REDUCE::reduce_n_wise(), Bif_REDUCE::replicate(), set_last_shape_item(), Value::set_shape_item(), and StateIndicator::statement_result().
without_axis()
Shape Shape::without_axis (sAxis axis) const inline
return a shape like this, but with axis axis removed
Definition at line 183 of file Shape.hh.
References add_shape_item(), rho, and rho_rho.
Referenced by NonscalarFunction_default_identity::eval_identity_fun().
without_first_axis()
Shape Shape::without_first_axis () const inline
return a shape like this, but with the first axis (↑⍴) removed
Definition at line 190 of file Shape.hh.
References add_shape_item(), rho, and rho_rho.
without_last_axis()
Shape Shape::without_last_axis () const inline
return a shape like this, but with the last axis (¯1↑⍴) removed
Definition at line 197 of file Shape.hh.
References add_shape_item(), rho, and rho_rho.
Referenced by Bif_F12_FORMAT::format_by_specification().
Member Data Documentation
rho
ShapeItem Shape::rho[MAX_RANK] protected
the shape
Definition at line 259 of file Shape.hh.
Referenced by abs(), add_shape_item(), contains(), contains_axis(), expand(), expand_rank(), get_cols(), get_first_shape_item(), get_last_shape_item(), get_rows(), get_shape_item(), get_transposed_shape_item(), get_weights(), Shape3::h(), high_shape(), increment_shape_item(), is_empty(), Shape3::l(), low_shape(), Shape3::m(), offset_to_index(), operator+(), operator==(), recompute_volume(), set_shape_item(), Shape(), Shape3::Shape3(), without_axis(), without_first_axis(), and without_last_axis().
rho_rho
sRank Shape::rho_rho protected
the rank (number of valid shape items)
Definition at line 256 of file Shape.hh.
Referenced by abs(), add_shape_item(), contains(), contains_axis(), expand(), expand_rank(), get_cols(), get_first_shape_item(), get_last_shape_item(), get_rank(), get_rows(), get_shape_item(), get_transposed_shape_item(), get_weights(), is_empty(), offset_to_index(), operator+(), operator==(), recompute_volume(), set_last_shape_item(), set_shape_item(), without_axis(), without_first_axis(), and without_last_axis().
volume
ShapeItem Shape::volume protected
+/rho
Definition at line 262 of file Shape.hh.
Referenced by add_shape_item(), expand(), get_nz_volume(), get_rows(), get_volume(), get_weights(), recompute_volume(), and set_shape_item().
The documentation for this class was generated from the following files:
src/Shape.hh
src/Shape.cc