GNU APL: Parallel Class Reference
Parallel Class Reference
Parallel APL execution.
#include <Parallel.hh>
Public Types
typedef _Atomic_word parallel_lock_t
a lock coordinating parallel access to shared objects
Static Public Member Functions
static void acquire_lock (volatile parallel_lock_t &lock)
acquire lock
static void release_lock (volatile parallel_lock_t &lock)
release lock
static void init (bool logit)
initialize
Static Public Attributes
static bool run_parallel = false
true if parallel execution is enabled
static sem_t * print_sema = &__print_sema
a semaphore to protect printing from different threads
static sem_t * pthread_create_sema = &__pthread_create_sema
a semaphore to tell when a thread has started
Static Protected Member Functions
static void * worker_main (void *)
return the core number for idx
static void init_all_CPUs (bool logit)
initialize all_CPUs (which then determines the max. core count)
Static Protected Attributes
static bool init_done = false
true after init() has been called
Detailed Description
Parallel APL execution.
_Atomic_word class coordinating the different cores working in parallel on the same ravel(s)
Definition at line 254 of file Parallel.hh.
Member Typedef Documentation
parallel_lock_t
typedef _Atomic_word Parallel::parallel_lock_t
a lock coordinating parallel access to shared objects
Definition at line 264 of file Parallel.hh.
Member Function Documentation
acquire_lock()
static void Parallel::acquire_lock (volatile parallel_lock_t & lock) inline static
acquire lock
Definition at line 268 of file Parallel.hh.
init()
void Parallel::init (bool logit) static
initialize
Definition at line 46 of file Parallel.cc.
References CPU_pool::add_CPU(), Thread_context::bind_to_cpu(), CPU_pool::change_core_count(), Thread_context::get_context(), CPU_pool::get_count(), CPU_pool::get_CPU(), Avec::init(), init_done, Thread_context::init_parallel(), Thread_context::init_sequential(), Thread_context::print_all(), print_sema, pthread_create_sema, Thread_context::set_active_core_count(), Thread_context::thread, and worker_main().
release_lock()
static void Parallel::release_lock (volatile parallel_lock_t & lock) inline static
release lock
Definition at line 278 of file Parallel.hh.
worker_main()
void * Parallel::worker_main (void * arg) static protected
return the core number for idx
the main() function of the worker threads
Definition at line 356 of file Parallel.cc.
Referenced by init().
Member Data Documentation
init_done
bool Parallel::init_done = false static protected
true after init() has been called
Definition at line 318 of file Parallel.hh.
Referenced by init().
print_sema
sem_t * Parallel::print_sema = &__print_sema static
a semaphore to protect printing from different threads
Definition at line 304 of file Parallel.hh.
Referenced by init().
pthread_create_sema
sem_t * Parallel::pthread_create_sema = &__pthread_create_sema static
a semaphore to tell when a thread has started
Definition at line 307 of file Parallel.hh.
Referenced by init().
run_parallel
bool Parallel::run_parallel = false static
true if parallel execution is enabled
Definition at line 298 of file Parallel.hh.
Referenced by CPU_pool::change_core_count(), ScalarFunction::do_scalar_AB(), ScalarFunction::do_scalar_B(), Bif_OPER2_INNER::scalar_inner_product(), and Bif_OPER2_OUTER::scalar_outer_product().
The documentation for this class was generated from the following files:
src/Parallel.hh
src/Parallel.cc