GNU APL: Token Class Reference
Token Class Reference
One atom of an APL function or expression.
#include <Token.hh>
Classes
union sval
the optional value of the token.
Public Member Functions
Token ()
Construct a VOID token. VOID token are used for two purposes: (1) to fill positions when e.g. 3 tokens were replaced by 2 tokens during parsing, and (2) as return values of user defined functions that do not return values.
Token (const Token &other)
copy constructor
Token (const Token &other, const char *loc)
copy constructor with location
void copy_1 (const Token &src, const char *loc)
copy src into this token. leaving APL value pointer in src (if any) and add events as needed
void move_1 (Token &src, const char *loc)
move mutable src into this token. clears APL value pointer in src (if any) and add events as needed
void move_2 (const Token &src, const char *loc)
move const src into this token. clears APL value pointer in src (if any) and add events as needed
Token (TokenTag tg)
Construct a token without a value.
Token (TokenTag tg, Function_P fun)
Construct a token for a Function.
Token (TokenTag tg, Function_Line line)
Construct a token for a line number.
Token (TokenTag tg, ErrorCode ec)
Construct a token for an error code.
Token (TokenTag tg, Symbol *sp)
Construct a token for a Symbol.
Token (TokenTag tg, Unicode uni)
Construct a token with tag tg for a UNICODE character. The tag is defined in Avec.def. This token in temporary in the sense that get_ValueType() can be anything rather than TV_CHAR. The value for the token (if any) will be added later (after parsing it).
Token (TokenTag tg, int64_t ival)
Construct a token for a single integer value.
Token (TokenTag tg, APL_Float flt)
Construct a token for a single floating point value.
Token (TokenTag tg, APL_Float r, APL_Float i)
Construct a token for a single complex value.
Token (TokenTag tg, Value_P vp)
Construct a token for an APL value.
Token (TokenTag tg, IndexExpr &idx)
Construct a token for an index.
~Token ()
destructor
void Hswap (Token &other)
swap this and other
TokenValueType get_ValueType () const
return the TokenValueType of this token.
TokenClass get_Class () const
return the TokenClass of this token.
Id get_Id () const
return the Id of this token.
const TokenTag get_tag () const
return the tag of this token
Unicode get_char_val () const
return the Unicode value of this token
int64_t get_int_val () const
return the integer value of this token
int64_t get_int_val2 () const
return the second integer value of this token
ErrorCode get_ErrorCode () const
return the error code value of this token
void set_int_val (int64_t val)
set the integer value of this token
void set_int_val2 (int64_t val)
set the second integer value of this token
APL_Float get_flt_val () const
return the float value of this token
APL_Float get_cpx_real () const
return the complex real value of this token
APL_Float get_cpx_imag () const
return the complex imag value of this token
Symbol * get_sym_ptr () const
return the Symbol * value of this token
Function_Line get_fun_line () const
return the Function_Line value of this token
bool is_void () const
return true iff this token has no value
bool is_apl_val () const
return true iff this token is an apl value
Value_P get_apl_val () const
return the Value_P value of this token. The token could be TOK_NO_VALUE; in that case VALUE_ERROR is thrown.
Value_P * get_apl_valp () const
return the address of the Value_P value of this token.
void clear (const char *loc)
clear this token, properly clearing Value token
Value_P get_nonzero_axes () const
return the axis specification of this token (expect non-zero axes)
Value_P get_axes () const
return the axis specification of this token
void set_apl_val (Value_P val)
set the Value_P value of this token
IndexExpr & get_index_val () const
return the IndexExpr value of this token
bool is_function () const
return true if this token is a function (or operator)
Function_P get_function () const
return the Function_P value of this token
int value_use_count () const
return value usage counter
void extract_apl_val (const char *loc)
clear the Value_P value (if any) of this token, updating its refcount as needed
Value * extract_and_keep (const char *loc)
clear the Value_P (if any) without updating its refcount. Return the old Value * that was overridden
void ChangeTag (TokenTag new_tag)
change the tag (within the same TokenValueType)
ostream & print_function (ostream &out) const
helper function to print a function.
ostream & print_value (ostream &out) const
helper function to print an APL value
void show_trace (ostream &out, const UCS_string &fun_name, Function_Line line) const
show trace output for this token
UCS_string canonical (PrintStyle style) const
the Quad_CR representation of the token.
UCS_string tag_name () const
the tag in readable form (TOK_...)
int error_info (UCS_string &out) const
print the token to out in the format used by print_error_info(). return the number of characters printed.
void copy_N (const Token &src)
copy src to this token, updating ref counts for APL values
Static Public Member Functions
static const char * short_class_name (TokenClass cls)
return a brief token class name for debugging purposes
static const char * class_name (TokenClass tc)
the name of tc
Protected Member Functions
ostream & print_quad (ostream &out) const
helper function to print Quad-function (system function or variable).
Protected Attributes
TokenTag tag
The tag indicating the type of this token.
sval value
The value of this token.
Detailed Description
One atom of an APL function or expression.
A Token, consisting of a tag and a value. The tag (actually already (tag & TV_MASK) identifies the type of the value.
Definition at line 45 of file Token.hh.
Constructor & Destructor Documentation
Token() [1/14]
Token::Token () inline
Construct a VOID token. VOID token are used for two purposes: (1) to fill positions when e.g. 3 tokens were replaced by 2 tokens during parsing, and (2) as return values of user defined functions that do not return values.
Definition at line 52 of file Token.hh.
References Token::sval::int_vals, and value.
Referenced by clear().
Token() [2/14]
Token::Token (const Token & other)
copy constructor
Definition at line 31 of file Token.cc.
References copy_1().
Token() [3/14]
Token::Token (const Token & other, const char * loc)
copy constructor with location
Definition at line 37 of file Token.cc.
References copy_1().
Token() [4/14]
Token::Token (TokenTag tg) inline
Construct a token without a value.
Definition at line 74 of file Token.hh.
References get_ValueType(), Token::sval::int_vals, and value.
Token() [5/14]
Token::Token (TokenTag tg, Function_P fun) inline
Construct a token for a Function.
Definition at line 78 of file Token.hh.
References Token::sval::function, get_ValueType(), and value.
Token() [6/14]
Token::Token (TokenTag tg, Function_Line line) inline
Construct a token for a line number.
Definition at line 82 of file Token.hh.
References Token::sval::fun_line, and value.
Token() [7/14]
Token::Token (TokenTag tg, ErrorCode ec) inline
Construct a token for an error code.
Definition at line 86 of file Token.hh.
References Token::sval::int_vals, and value.
Token() [8/14]
Token::Token (TokenTag tg, Symbol * sp) inline
Construct a token for a Symbol.
Definition at line 90 of file Token.hh.
References get_ValueType(), Token::sval::sym_ptr, and value.
Token() [9/14]
Token::Token (TokenTag tg, Unicode uni) inline
Construct a token with tag tg for a UNICODE character. The tag is defined in Avec.def. This token in temporary in the sense that get_ValueType() can be anything rather than TV_CHAR. The value for the token (if any) will be added later (after parsing it).
Definition at line 97 of file Token.hh.
References Token::sval::char_val, and value.
Token() [10/14]
Token::Token (TokenTag tg, int64_t ival) inline
Construct a token for a single integer value.
Definition at line 101 of file Token.hh.
References Token::sval::int_vals, and value.
Token() [11/14]
Token::Token (TokenTag tg, APL_Float flt) inline
Construct a token for a single floating point value.
Definition at line 105 of file Token.hh.
References Token::sval::float_vals, and value.
Token() [12/14]
Token::Token (TokenTag tg, APL_Float r, APL_Float i) inline
Construct a token for a single complex value.
Definition at line 109 of file Token.hh.
References Token::sval::float_vals, and value.
Token() [13/14]
Token::Token (TokenTag tg, Value_P vp) inline
Construct a token for an APL value.
Definition at line 117 of file Token.hh.
References Token::sval::apl_val, get_ValueType(), and value.
Token() [14/14]
Token::Token (TokenTag tg, IndexExpr & idx)
Construct a token for an index.
Definition at line 43 of file Token.cc.
References Token::sval::apl_val, IndexExpr::extract_axis(), IndexExpr::get_rank(), Token::sval::index_val, tag, and value.
~Token()
Token::~Token () inline
destructor
Definition at line 126 of file Token.hh.
References extract_apl_val().
Referenced by Command::finish_context().
Member Function Documentation
canonical()
UCS_string Token::canonical (PrintStyle style) const
the Quad_CR representation of the token.
Definition at line 560 of file Token.cc.
References UCS_string::append(), get_apl_val(), get_Class(), get_function(), get_Id(), ID::get_name_UCS(), PrintBuffer::get_row_count(), get_sym_ptr(), get_tag(), PrintBuffer::l1(), and tag.
Referenced by error_info().
ChangeTag()
void Token::ChangeTag (TokenTag new_tag)
change the tag (within the same TokenValueType)
Definition at line 253 of file Token.cc.
References tag.
Referenced by Quad_FIO::eval_LXB().
class_name()
const char * Token::class_name (TokenClass tc) static
the name of tc
Definition at line 721 of file Token.cc.
Referenced by Prefix::print_stack(), and Prefix::reduce_statements().
clear()
void Token::clear (const char * loc) inline
clear this token, properly clearing Value token
Definition at line 216 of file Token.hh.
References Token::sval::apl_val, is_apl_val(), Value_P_Base::reset(), Token(), and value.
Referenced by copy_1(), Parser::create_vector_value(), DerivedFunction::destroy_derived(), move_1(), move_2(), Prefix::reduce_statements(), and Prefix::reset().
copy_1()
void Token::copy_1 (const Token & src, const char * loc)
copy src into this token. leaving APL value pointer in src (if any) and add events as needed
Definition at line 790 of file Token.cc.
References Token::sval::apl_val, clear(), copy_N(), Value_P_Base::get(), is_apl_val(), value, and value_use_count().
Referenced by Token_loc::copy(), Prefix::pop_args_push_result(), and Token().
copy_N()
void Token::copy_N (const Token & src) inline
copy src to this token, updating ref counts for APL values
Definition at line 766 of file Token.cc.
References Token::sval::_apl_val(), Token::sval::char_val, Token::sval::float_vals, Token::sval::fun_line, Token::sval::function, get_ValueType(), Token::sval::index_val, Token::sval::int_vals, Token::sval::sym_ptr, tag, and value.
Referenced by copy_1(), move_1(), and move_2().
error_info()
int Token::error_info (UCS_string & out) const
print the token to out in the format used by print_error_info(). return the number of characters printed.
Definition at line 650 of file Token.cc.
References UCS_string::append(), UCS_string::back(), canonical(), Avec::no_space_after(), Avec::no_space_before(), UCS_string::remove_pad(), and UCS_string::size().
extract_and_keep()
Value * Token::extract_and_keep (const char * loc)
clear the Value_P (if any) without updating its refcount. Return the old Value * that was overridden
Definition at line 275 of file Token.cc.
References Token::sval::apl_val, Value_P_Base::clear_pointer(), Value_P_Base::get(), is_apl_val(), and value.
extract_apl_val()
void Token::extract_apl_val (const char * loc)
clear the Value_P value (if any) of this token, updating its refcount as needed
Definition at line 269 of file Token.cc.
References Token::sval::apl_val, is_apl_val(), Value_P_Base::reset(), and value.
Referenced by Prefix::clean_up(), Quad_TF::tf2_reduce_parentheses(), and ~Token().
get_apl_val()
Value_P Token::get_apl_val () const inline
return the Value_P value of this token. The token could be TOK_NO_VALUE; in that case VALUE_ERROR is thrown.
Definition at line 208 of file Token.hh.
References Token::sval::_apl_val(), is_apl_val(), and value.
Referenced by canonical(), Parser::create_vector_value(), Quad_CR::do_CR37(), Bif_OPER1_EACH::do_eval_LB(), Bif_OPER2_RANK::do_LyXB(), Bif_REDUCE::do_reduce(), ScalarFunction::do_scalar_AB(), XML_Saving_Archive::emit_token_val(), Bif_F12_PARTITION::enclose_with_axes(), Quad_EC::eoc(), DerivedFunction::eval_AB(), Bif_F12_UNION::eval_AB(), Bif_OPER1_EACH::eval_ALB(), UserFunction::eval_ALB(), Bif_OPER2_INNER::eval_ALRB(), Bif_OPER2_OUTER::eval_ALRB(), Bif_OPER2_POWER::eval_ALRB(), UserFunction::eval_ALRB(), UserFunction::eval_ALRXB(), UserFunction::eval_ALXB(), DerivedFunction::eval_B(), Bif_OPER2_POWER::eval_form_1(), Bif_OPER2_POWER::eval_form_2(), UserFunction::eval_LB(), Bif_OPER2_POWER::eval_LRB(), UserFunction::eval_LRB(), UserFunction::eval_LRXB(), Quad_FIO::eval_LXB(), UserFunction::eval_LXB(), DerivedFunction::eval_XB(), ScalarFunction::expand_nested(), Bif_OPER2_INNER::fill(), DerivedFunction::get_bound_LO_value(), Value::glue(), Bif_REDUCE::reduce_n_wise(), Prefix::replace_AB(), Bif_SCAN::scan(), Executable::show_owners(), Prefix::show_owners(), show_trace(), StateIndicator::statement_result(), Prefix::syntax_error(), Quad_TF::tf2_inverse(), Quad_TF::tf2_reduce_parentheses(), DerivedFunction::unmark_all_values(), Executable::unmark_all_values(), Prefix::unmark_all_values(), and Symbol::write_OUT().
get_apl_valp()
Value_P * Token::get_apl_valp () const inline
return the address of the Value_P value of this token.
Definition at line 212 of file Token.hh.
References Token::sval::_apl_val(), is_apl_val(), and value.
Referenced by Prefix::locate_L(), Prefix::locate_R(), and Prefix::locate_X().
get_axes()
Value_P Token::get_axes () const inline
return the axis specification of this token
Definition at line 228 of file Token.hh.
References Token::sval::_apl_val(), get_tag(), and value.
get_char_val()
Unicode Token::get_char_val () const inline
return the Unicode value of this token
Definition at line 153 of file Token.hh.
References Token::sval::char_val, get_ValueType(), and value.
Referenced by Parser::create_scalar_value(), Parser::create_vector_value(), Tokenizer::do_tokenize(), and XML_Saving_Archive::emit_token_val().
get_Class()
TokenClass Token::get_Class () const inline
return the TokenClass of this token.
Definition at line 141 of file Token.hh.
References tag.
Referenced by Doxy::add_fun_to_call_graph(), canonical(), Prefix::clean_up(), Bif_OPER1_EACH::do_eval_LB(), Bif_REDUCE::do_reduce(), Tokenizer::do_tokenize(), Quad_AT::eval_AB(), Bif_OPER1_EACH::eval_ALB(), Bif_OPER2_OUTER::eval_ALRB(), Bif_F12_SORT_ASC::eval_B(), Bif_F12_SORT_DES::eval_B(), Bif_OPER2_POWER::eval_form_1(), Bif_OPER2_POWER::eval_form_2(), Quad_INP::eval_XB(), Bif_OPER2_INNER::fill(), Command::finish_context(), NamedObject::get_NC(), Quad_NC::get_NC(), Prefix::is_value_bracket(), Prefix::locate_R(), Workspace::lookup_existing_name(), Workspace::lookup_existing_symbol(), Prefix::MM_is_FM(), Executable::parse_body_line(), Prefix::print_stack(), Prefix::reduce_statements(), Prefix::replace_AB(), Prefix::set_action(), Prefix::syntax_error(), Quad_TF::tf2_inverse(), and Prefix::value_expected().
get_cpx_imag()
APL_Float Token::get_cpx_imag () const inline
return the complex imag value of this token
Definition at line 187 of file Token.hh.
References Token::sval::float_vals, get_ValueType(), and value.
Referenced by Parser::create_scalar_value(), Parser::create_vector_value(), XML_Saving_Archive::emit_token_val(), Command::transfer_context::numeric_1TF(), and Quad_TF::tf1_inv().
get_cpx_real()
APL_Float Token::get_cpx_real () const inline
return the complex real value of this token
Definition at line 183 of file Token.hh.
References Token::sval::float_vals, get_ValueType(), and value.
Referenced by Parser::create_scalar_value(), Parser::create_vector_value(), XML_Saving_Archive::emit_token_val(), Command::transfer_context::numeric_1TF(), and Quad_TF::tf1_inv().
get_ErrorCode()
ErrorCode Token::get_ErrorCode () const inline
return the error code value of this token
Definition at line 165 of file Token.hh.
References get_tag(), get_ValueType(), Token::sval::int_vals, and value.
Referenced by Bif_REDUCE::do_reduce().
get_flt_val()
APL_Float Token::get_flt_val () const inline
return the float value of this token
Definition at line 179 of file Token.hh.
References Token::sval::float_vals, get_ValueType(), and value.
Referenced by Parser::create_scalar_value(), Parser::create_vector_value(), XML_Saving_Archive::emit_token_val(), Command::transfer_context::numeric_1TF(), Token_string::print(), and Quad_TF::tf1_inv().
get_fun_line()
Function_Line Token::get_fun_line () const inline
return the Function_Line value of this token
Definition at line 195 of file Token.hh.
References Token::sval::fun_line, get_ValueType(), and value.
Referenced by XML_Saving_Archive::emit_token_val().
get_function()
Function_P Token::get_function () const inline
return the Function_P value of this token
Definition at line 244 of file Token.hh.
References Token::sval::function, is_function(), and value.
Referenced by canonical(), Bif_OPER2_RANK::do_ALyXB(), Bif_OPER1_EACH::do_eval_LB(), Bif_OPER2_RANK::do_LyXB(), XML_Saving_Archive::emit_token_val(), Quad_AT::eval_AB(), Bif_OPER1_COMMUTE::eval_ALB(), Bif_OPER1_EACH::eval_ALB(), NativeFunction::eval_ALB(), UserFunction::eval_ALB(), Bif_OPER2_INNER::eval_ALRB(), Bif_OPER2_OUTER::eval_ALRB(), NativeFunction::eval_ALRB(), UserFunction::eval_ALRB(), NativeFunction::eval_ALRXB(), UserFunction::eval_ALRXB(), Bif_OPER1_COMMUTE::eval_ALXB(), NativeFunction::eval_ALXB(), Quad_FIO::eval_ALXB(), UserFunction::eval_ALXB(), Quad_FIO::eval_AXB(), Bif_OPER2_POWER::eval_form_1(), Bif_OPER2_POWER::eval_form_2(), Bif_OPER1_COMMUTE::eval_LB(), NativeFunction::eval_LB(), UserFunction::eval_LB(), NativeFunction::eval_LRB(), UserFunction::eval_LRB(), NativeFunction::eval_LRXB(), UserFunction::eval_LRXB(), Bif_OPER1_COMMUTE::eval_LXB(), NativeFunction::eval_LXB(), Quad_FIO::eval_LXB(), UserFunction::eval_LXB(), Quad_FIO::eval_XB(), XML_Loading_Archive::find_lambda(), Prefix::get_dyadic_fun(), DerivedFunction::get_LO(), Prefix::get_monadic_fun(), DerivedFunction::get_RO(), DerivedFunction::has_result(), Prefix::locate_L(), Workspace::lookup_existing_name(), DerivedFunction::may_push_SI(), Prefix::MM_is_FM(), DerivedFunction::print(), print_function(), DerivedFunction::print_properties(), UserFunction::print_val_or_fun(), Bif_REDUCE::reduce(), Bif_REDUCE::reduce_n_wise(), Bif_SCAN::scan(), Prefix::syntax_error(), Executable::unmark_all_values(), and Prefix::uses_function().
get_Id()
Id Token::get_Id () const inline
return the Id of this token.
Definition at line 145 of file Token.hh.
References tag.
Referenced by canonical(), Tokenizer::do_tokenize(), print_function(), print_quad(), and print_value().
get_index_val()
IndexExpr & Token::get_index_val () const inline
return the IndexExpr value of this token
Definition at line 236 of file Token.hh.
References get_ValueType(), Token::sval::index_val, and value.
Referenced by Prefix::clean_up(), and XML_Saving_Archive::emit_token_val().
get_int_val()
int64_t Token::get_int_val () const inline
return the integer value of this token
Definition at line 157 of file Token.hh.
References get_ValueType(), Token::sval::int_vals, and value.
Referenced by Parser::create_scalar_value(), Parser::create_vector_value(), XML_Saving_Archive::emit_token_val(), Quad_EC::eoc(), Command::finish_context(), Command::transfer_context::numeric_1TF(), show_trace(), and Quad_TF::tf1_inv().
get_int_val2()
int64_t Token::get_int_val2 () const inline
return the second integer value of this token
Definition at line 161 of file Token.hh.
References Token::sval::int_vals, and value.
Referenced by Prefix::value_expected().
get_nonzero_axes()
Value_P Token::get_nonzero_axes () const inline
return the axis specification of this token (expect non-zero axes)
Definition at line 223 of file Token.hh.
References Token::sval::_apl_val(), Token::sval::apl_val, get_tag(), and value.
get_sym_ptr()
Symbol * Token::get_sym_ptr () const inline
return the Symbol * value of this token
Definition at line 191 of file Token.hh.
References get_ValueType(), Token::sval::sym_ptr, and value.
Referenced by Doxy::add_fun_to_call_graph(), canonical(), Command::transfer_context::chars_1TF(), XML_Saving_Archive::emit_token_val(), Quad_AT::eval_AB(), XML_Loading_Archive::find_lambda(), Quad_NC::get_NC(), Prefix::is_value_bracket(), Workspace::lookup_existing_name(), Workspace::lookup_existing_symbol(), Prefix::MM_is_FM(), Command::transfer_context::numeric_1TF(), Executable::parse_body_line(), Prefix::reduce_statements(), StateIndicator::uses_function(), and Prefix::value_expected().
get_tag()
const TokenTag Token::get_tag () const inline
return the tag of this token
Definition at line 149 of file Token.hh.
References tag.
Referenced by canonical(), Executable::compute_lambda_body(), Parser::create_scalar_value(), Parser::create_vector_value(), Bif_OPER1_EACH::do_eval_LB(), Bif_REDUCE::do_reduce(), Tokenizer::do_tokenize(), Quad_EC::eoc(), DerivedFunction::eval_AB(), Quad_INP::eval_AB(), Bif_OPER1_EACH::eval_ALB(), Bif_OPER2_INNER::eval_ALRB(), Bif_OPER2_OUTER::eval_ALRB(), Quad_FIO::eval_ALXB(), DerivedFunction::eval_AXB(), DerivedFunction::eval_B(), Bif_OPER2_POWER::eval_form_1(), Bif_OPER2_POWER::eval_form_2(), Quad_FIO::eval_LXB(), DerivedFunction::eval_XB(), Quad_INP::eval_XB(), Command::finish_context(), get_axes(), get_ErrorCode(), get_nonzero_axes(), DerivedFunction::get_RO(), Value::glue(), Command::transfer_context::numeric_1TF(), Parser::parse(), Executable::parse_body_line(), DerivedFunction::print(), DerivedFunction::print_properties(), Prefix::reduce_statements(), Prefix::replace_AB(), XML_Saving_Archive::save_token_loc(), Prefix::set_action(), show_trace(), StateIndicator::statement_result(), tag_name(), Quad_TF::tf1_inv(), Quad_TF::tf2_reduce_parentheses(), Tokenizer::tokenize_function(), and StateIndicator::uses_function().
get_ValueType()
TokenValueType Token::get_ValueType () const inline
return the TokenValueType of this token.
Definition at line 137 of file Token.hh.
References tag.
Referenced by Command::transfer_context::chars_1TF(), Prefix::clean_up(), copy_N(), XML_Saving_Archive::emit_token_val(), Bif_OPER2_POWER::eval_ALRB(), Bif_OPER2_POWER::eval_LRB(), XML_Loading_Archive::find_lambda(), get_char_val(), get_cpx_imag(), get_cpx_real(), Prefix::get_dyadic_fun(), get_ErrorCode(), get_flt_val(), get_fun_line(), get_index_val(), get_int_val(), Prefix::get_monadic_fun(), get_sym_ptr(), is_apl_val(), is_function(), is_void(), Command::transfer_context::numeric_1TF(), Token_string::print(), set_apl_val(), set_int_val(), Executable::show_owners(), Prefix::show_owners(), StateIndicator::statement_result(), Token(), Executable::unmark_all_values(), Prefix::unmark_all_values(), Prefix::uses_function(), and Prefix::value_expected().
Hswap()
void Token::Hswap (Token & other) inline
swap this and other
Definition at line 130 of file Token.hh.
References Hswap(), Token::sval::int_vals, tag, and value.
Referenced by Hswap(), and Token_string::reverse_from_to().
is_apl_val()
bool Token::is_apl_val () const inline
return true iff this token is an apl value
Definition at line 203 of file Token.hh.
References get_ValueType().
Referenced by clear(), copy_1(), extract_and_keep(), extract_apl_val(), get_apl_val(), get_apl_valp(), DerivedFunction::get_bound_LO_value(), move_1(), move_2(), UserFunction::print_val_or_fun(), Bif_SCAN::scan(), DerivedFunction::unmark_all_values(), and value_use_count().
is_function()
bool Token::is_function () const inline
return true if this token is a function (or operator)
Definition at line 240 of file Token.hh.
References get_ValueType().
Referenced by DerivedFunction::eval_AB(), UserFunction::eval_ALB(), Bif_OPER2_INNER::eval_ALRB(), Bif_OPER2_OUTER::eval_ALRB(), UserFunction::eval_ALRB(), UserFunction::eval_ALRXB(), UserFunction::eval_ALXB(), Quad_FIO::eval_AXB(), DerivedFunction::eval_B(), Bif_OPER1_COMMUTE::eval_LB(), UserFunction::eval_LB(), UserFunction::eval_LRB(), UserFunction::eval_LRXB(), UserFunction::eval_LXB(), DerivedFunction::eval_XB(), Quad_FIO::eval_XB(), get_function(), DerivedFunction::has_result(), DerivedFunction::may_push_SI(), DerivedFunction::print(), DerivedFunction::print_properties(), UserFunction::print_val_or_fun(), Bif_REDUCE::reduce(), Bif_REDUCE::reduce_n_wise(), and Bif_SCAN::scan().
is_void()
bool Token::is_void () const inline
return true iff this token has no value
Definition at line 199 of file Token.hh.
References get_ValueType().
Referenced by UserFunction::print_val_or_fun().
move_1()
void Token::move_1 (Token & src, const char * loc)
move mutable src into this token. clears APL value pointer in src (if any) and add events as needed
Definition at line 810 of file Token.cc.
References Token::sval::apl_val, clear(), copy_N(), Value_P_Base::get(), is_apl_val(), value, and value_use_count().
Referenced by Executable::compute_lambda_body(), Parser::create_scalar_value(), Prefix::reduce_statements(), Symbol::resolve(), Quad_TF::tf2_glue(), and Quad_TF::tf2_reduce_parentheses().
move_2()
void Token::move_2 (const Token & src, const char * loc)
move const src into this token. clears APL value pointer in src (if any) and add events as needed
Definition at line 827 of file Token.cc.
References Token::sval::apl_val, clear(), copy_N(), Value_P_Base::get(), is_apl_val(), value, and value_use_count().
Referenced by Quad_EC::eoc(), Symbol::resolve(), and Quad_Quad::resolve().
print_function()
ostream & Token::print_function (ostream & out) const
helper function to print a function.
Definition at line 285 of file Token.cc.
References get_function(), get_Id(), print_quad(), and tag.
print_quad()
ostream & Token::print_quad (ostream & out) const protected
helper function to print Quad-function (system function or variable).
Definition at line 554 of file Token.cc.
References get_Id().
Referenced by print_function(), and print_value().
print_value()
ostream & Token::print_value (ostream & out) const
helper function to print an APL value
Definition at line 404 of file Token.cc.
References Token::sval::apl_val, Token::sval::char_val, Cell::character_representation(), Value::element_count(), Token::sval::float_vals, Value_P_Base::get(), Value::get_cravel(), get_Id(), Value::get_rank(), Value::get_shape_item(), Token::sval::int_vals, Symbol::print(), print_quad(), Token::sval::sym_ptr, tag, and value.
set_apl_val()
void Token::set_apl_val (Value_P val) inline
set the Value_P value of this token
Definition at line 232 of file Token.hh.
References Token::sval::_apl_val(), get_ValueType(), and value.
set_int_val()
void Token::set_int_val (int64_t val) inline
set the integer value of this token
Definition at line 171 of file Token.hh.
References get_ValueType(), Token::sval::int_vals, and value.
set_int_val2()
void Token::set_int_val2 (int64_t val) inline
set the second integer value of this token
Definition at line 175 of file Token.hh.
References Token::sval::int_vals, and value.
short_class_name()
const char * Token::short_class_name (TokenClass cls) static
return a brief token class name for debugging purposes
Definition at line 668 of file Token.cc.
show_trace()
void Token::show_trace (ostream & out, const UCS_string & fun_name, Function_Line line) const
show trace output for this token
Definition at line 480 of file Token.cc.
References UCS_string::append_number(), UCS_string::append_UTF8(), Value::element_count(), get_apl_val(), Value::get_cfirst(), get_int_val(), PrintBuffer::get_line(), Workspace::get_PrintContext(), Value::get_rank(), PrintBuffer::get_row_count(), PrintContext::get_style(), get_tag(), Cell::is_simple_cell(), UCS_string::no_pad(), PrintContext::set_style(), and UCS_string::size().
Referenced by StateIndicator::statement_result().
tag_name()
UCS_string Token::tag_name () const
the tag in readable form (TOK_...)
Definition at line 634 of file Token.cc.
References get_tag().
Referenced by Tokenizer::do_tokenize().
value_use_count()
int Token::value_use_count () const
return value usage counter
Definition at line 261 of file Token.cc.
References Token::sval::apl_val, Value::get_owner_count(), is_apl_val(), and value.
Referenced by copy_1(), move_1(), and move_2().
Member Data Documentation
tag
TokenTag Token::tag protected
The tag indicating the type of this token.
Definition at line 310 of file Token.hh.
Referenced by canonical(), ChangeTag(), copy_N(), get_Class(), get_Id(), get_tag(), get_ValueType(), Hswap(), print_function(), print_value(), and Token().
value
sval Token::value protected
The value of this token.
Definition at line 313 of file Token.hh.
Referenced by clear(), copy_1(), copy_N(), extract_and_keep(), extract_apl_val(), get_apl_val(), get_apl_valp(), get_axes(), get_char_val(), get_cpx_imag(), get_cpx_real(), get_ErrorCode(), get_flt_val(), get_fun_line(), get_function(), get_index_val(), get_int_val(), get_int_val2(), get_nonzero_axes(), get_sym_ptr(), Hswap(), move_1(), move_2(), print_value(), set_apl_val(), set_int_val(), set_int_val2(), Token(), and value_use_count().
The documentation for this class was generated from the following files:
src/Token.hh
src/Token.cc