GNU APL: DerivedFunctionCache Class Reference
DerivedFunctionCache Class Reference
a small cache for storing a few DerivedFunction objects
#include <DerivedFunction.hh>
Public Member Functions
DerivedFunctionCache ()
constructor: create empty FunOper cache
~DerivedFunctionCache ()
destructor
const DerivedFunction * at (size_t i) const
return the i'th derived function
const DerivedFunction & operator[] (size_t i) const
return the i'th derived function
void unmark_all_values () const
clear the marked bit in values bound to derived functions (if any).
size_t size () const
return the number of items in the cache
void reset ()
reset (clear) the cache
DerivedFunction * get (const char *loc)
return the last cache entry and increment idx. To be used with placement new.
Protected Attributes
uint8_t cache [sizeof(DerivedFunction) *MAX_FUN_OPER]
a cache for derived functions
size_t idx
the number of elements in cache
Detailed Description
a small cache for storing a few DerivedFunction objects
Definition at line 143 of file DerivedFunction.hh.
Constructor & Destructor Documentation
DerivedFunctionCache()
DerivedFunctionCache::DerivedFunctionCache ()
constructor: create empty FunOper cache
Definition at line 316 of file DerivedFunction.cc.
References cache.
~DerivedFunctionCache()
DerivedFunctionCache::~DerivedFunctionCache ()
destructor
Definition at line 328 of file DerivedFunction.cc.
References cache, and reset().
Member Function Documentation
at()
const DerivedFunction * DerivedFunctionCache::at (size_t i) const inline
return the i'th derived function
Definition at line 153 of file DerivedFunction.hh.
References cache.
Referenced by operator[](), and unmark_all_values().
get()
DerivedFunction * DerivedFunctionCache::get (const char * loc)
return the last cache entry and increment idx. To be used with placement new.
Definition at line 360 of file DerivedFunction.cc.
References cache, and idx.
Referenced by XML_Loading_Archive::read_Derived(), and reset().
operator[]()
const DerivedFunction & DerivedFunctionCache::operator[] (size_t i) const inline
return the i'th derived function
Definition at line 160 of file DerivedFunction.hh.
References at(), and idx.
reset()
void DerivedFunctionCache::reset ()
reset (clear) the cache
Definition at line 341 of file DerivedFunction.cc.
References cache, DerivedFunction::destroy_derived(), get(), and idx.
Referenced by StateIndicator::statement_result(), ~DerivedFunctionCache(), and StateIndicator::~StateIndicator().
size()
size_t DerivedFunctionCache::size () const inline
return the number of items in the cache
Definition at line 171 of file DerivedFunction.hh.
References idx.
Referenced by XML_Saving_Archive::save_Derived(), and unmark_all_values().
unmark_all_values()
void DerivedFunctionCache::unmark_all_values () const inline
clear the marked bit in values bound to derived functions (if any).
Definition at line 167 of file DerivedFunction.hh.
References at(), size(), and DerivedFunction::unmark_all_values().
Referenced by StateIndicator::unmark_all_values().
Member Data Documentation
cache
uint8_t DerivedFunctionCache::cache[sizeof(DerivedFunction) *MAX_FUN_OPER] protected
a cache for derived functions
Definition at line 183 of file DerivedFunction.hh.
Referenced by at(), DerivedFunctionCache(), get(), reset(), and ~DerivedFunctionCache().
idx
size_t DerivedFunctionCache::idx protected
the number of elements in cache
Definition at line 186 of file DerivedFunction.hh.
Referenced by get(), operator[](), reset(), and size().
The documentation for this class was generated from the following files:
src/DerivedFunction.hh
src/DerivedFunction.cc