GNU APL: Quad_RE::Flags Class Reference
Quad_RE::Flags Class Reference
libpcre flags
#include <Quad_RE.hh>
Public Member Functions
Flags (const UCS_string &flags_in)
constructor
int get_compflags () const
return the flags
bool get_error_on_no_match () const
return true if no match shall give an error
bool get_global () const
return global (return all matches and not only first match)
Result_type get_result_type () const
return the result type
Protected Attributes
int flags
the flags (see pcre.h)
bool error_on_no_match
make no match an error
bool global
dito.
Result_type result_type
dito.
Detailed Description
libpcre flags
Definition at line 68 of file Quad_RE.hh.
Constructor & Destructor Documentation
Flags()
Quad_RE::Flags::Flags (const UCS_string & flags_in)
constructor
Definition at line 33 of file Quad_RE.cc.
References error_on_no_match, flags, global, result_type, Quad_RE::RT_partition, Quad_RE::RT_pos_len, Quad_RE::RT_reduce, and UCS_string::size().
Member Function Documentation
get_compflags()
int Quad_RE::Flags::get_compflags () const inline
return the flags
Definition at line 75 of file Quad_RE.hh.
References flags.
Referenced by Quad_RE::eval_AXB().
get_error_on_no_match()
bool Quad_RE::Flags::get_error_on_no_match () const inline
return true if no match shall give an error
Definition at line 79 of file Quad_RE.hh.
References error_on_no_match.
Referenced by Quad_RE::index_result(), and Quad_RE::string_result().
get_global()
bool Quad_RE::Flags::get_global () const inline
return global (return all matches and not only first match)
Definition at line 83 of file Quad_RE.hh.
References global.
Referenced by Quad_RE::index_result(), Quad_RE::partition_result(), Quad_RE::regex_results(), and Quad_RE::string_result().
get_result_type()
Result_type Quad_RE::Flags::get_result_type () const inline
return the result type
Definition at line 87 of file Quad_RE.hh.
References result_type.
Referenced by Quad_RE::partition_result(), and Quad_RE::regex_results().
Member Data Documentation
error_on_no_match
bool Quad_RE::Flags::error_on_no_match protected
make no match an error
Definition at line 95 of file Quad_RE.hh.
Referenced by Flags(), and get_error_on_no_match().
flags
int Quad_RE::Flags::flags protected
the flags (see pcre.h)
Definition at line 92 of file Quad_RE.hh.
Referenced by Flags(), and get_compflags().
global
bool Quad_RE::Flags::global protected
dito.
Definition at line 98 of file Quad_RE.hh.
Referenced by Flags(), and get_global().
result_type
Result_type Quad_RE::Flags::result_type protected
dito.
Definition at line 101 of file Quad_RE.hh.
Referenced by Flags(), and get_result_type().
The documentation for this class was generated from the following files:
src/Quad_RE.hh
src/Quad_RE.cc