GNU APL: Bif_F2_LEQU Class Reference
Bif_F2_LEQU Class Reference
The class implementing ≤
#include <ScalarFunction.hh>
Public Member Functions
Bif_F2_LEQU ()
Constructor.
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
virtual bool has_result () const
overloaded Function::has_result()
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Static Public Attributes
static Bif_F2_LEQU * fun = &Bif_F2_LEQU ::_fun
Built-in function.
static Bif_F2_LEQU _fun
Built-in function.
Protected Member Functions
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB().
virtual prim_f2 get_scalar_f2 () const
overloaded Function::get_scalar_f2()
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
overloaded Function::eval_identity_fun();
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
overloaded Function::eval_AXB().
Protected Member Functions inherited from ScalarFunction
ScalarFunction (TokenTag tag, CellFunctionStatistics *stat_AB, CellFunctionStatistics *stat_B, ShapeItem thresh_AB, ShapeItem thresh_B)
Construct a ScalarFunction with Id id.
Token eval_scalar_B (Value_P B, prim_f1 fun) const
Evaluate a scalar function monadically.
Token eval_scalar_AB (Value_P A, Value_P B, prim_f2 fun) const
Evaluate a scalar function dyadically.
virtual prim_f2 get_scalar_f2 () const =0
overloaded Function::get_scalar_f2
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual bool has_result () const
overloaded Function::has_result()
virtual bool may_parallel () const
return true if this function can be parallelized
Value_P do_scalar_B (ErrorCode &ec, Value_P B, prim_f1 fun) const
compute the monadic scalar function fun along one ravel
Value_P do_scalar_AB (ErrorCode &ec, Value_P A, Value_P B, prim_f2 fun) const
compute the dyadic scalar function fun along one ravel
void expand_nested (Value *Z, const Cell *cell_A, const Cell *cell_B, prim_f2 fun) const
compute cell_A fun cell_B, scalar-extending PointerCells
Token eval_scalar_AXB (Value_P A, Value_P X, Value_P B, prim_f2 fun) const
Evaluate a scalar function dyadically with axis.
Value_P eval_scalar_AXB (Value_P A, AxesBitmap axes_in_X, Value_P B, prim_f2 fun, bool reversed) const
A helper function for eval_scalar_AXB().
Token do_eval_fill_AB (const Value_P A, const Value_P B) const
A helper function for eval_fill_AB().
Token do_eval_fill_B (const Value_P B) const
A helper function for eval_fill_B().
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Additional Inherited Members
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Static Protected Member Functions inherited from ScalarFunction
static Token eval_scalar_identity_fun (Value_P B, sAxis axis, const Cell &FI0)
Evaluate the identity function.
static const Shape * conforming_shape (ErrorCode &ec, const Shape &sh_A, const Shape &sh_B)
return the conforming shape of sh_A and sh_A, or set ec and return 0 if shapes cannot be conformed. RANK ERROR or LENGTH ERROR if the dont.
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Static Protected Attributes inherited from ScalarFunction
static Thread_context::PoolFunction PF_scalar_AB
parallel eval_scalar_AB
static Thread_context::PoolFunction PF_scalar_B
parallel eval_scalar_B
static const IntCell integer_0
0 (for eval_scalar_identity_fun)
static const IntCell integer_1
1 (for eval_scalar_identity_fun)
static const FloatCell float_min
-BIG_FLOAT (for eval_scalar_identity_fun)
static const FloatCell float_max
BIG_FLOAT (for eval_scalar_identity_fun)
Detailed Description
The class implementing ≤
Scalar function less or equal.
Definition at line 492 of file ScalarFunction.hh.
Constructor & Destructor Documentation
Bif_F2_LEQU()
Bif_F2_LEQU::Bif_F2_LEQU () inline
Constructor.
Definition at line 496 of file ScalarFunction.hh.
Member Function Documentation
eval_AB()
virtual Token Bif_F2_LEQU::eval_AB (Value_P A, Value_P B) const inline protected virtual
overloaded Function::eval_AB().
Reimplemented from Function.
Definition at line 505 of file ScalarFunction.hh.
References Cell::bif_less_eq(), and ScalarFunction::eval_scalar_AB().
eval_AXB()
virtual Token Bif_F2_LEQU::eval_AXB (Value_P A, Value_P X, Value_P B) const inline protected virtual
overloaded Function::eval_AXB().
Reimplemented from Function.
Definition at line 517 of file ScalarFunction.hh.
References Cell::bif_less_eq(), and ScalarFunction::eval_scalar_AXB().
eval_identity_fun()
virtual Token Bif_F2_LEQU::eval_identity_fun (Value_P B, sAxis axis) const inline protected virtual
overloaded Function::eval_identity_fun();
Reimplemented from Function.
Definition at line 513 of file ScalarFunction.hh.
References ScalarFunction::eval_scalar_identity_fun(), and ScalarFunction::integer_1.
get_scalar_f2()
virtual prim_f2 Bif_F2_LEQU::get_scalar_f2 () const inline protected virtual
overloaded Function::get_scalar_f2()
Implements ScalarFunction.
Definition at line 509 of file ScalarFunction.hh.
References Cell::bif_less_eq().
Member Data Documentation
_fun
Bif_F2_LEQU Bif_F2_LEQU::_fun static
Built-in function.
Definition at line 501 of file ScalarFunction.hh.
fun
Bif_F2_LEQU * Bif_F2_LEQU::fun = &Bif_F2_LEQU ::_fun static
Built-in function.
Definition at line 500 of file ScalarFunction.hh.
The documentation for this class was generated from the following files:
src/ScalarFunction.hh
src/ScalarFunction.cc