GNU APL: DLX_Root_Node Class Reference
DLX_Root_Node Class Reference
The root node of the constraints matrix.
Public Member Functions
DLX_Root_Node (ShapeItem rows, ShapeItem cols, ShapeItem max_sol, const Value &B)
constructor
void deep_check () const
check of all nodes
ostream & indent (ostream &out)
indent for current level
void cover (ShapeItem j)
cover columns j (see Knuth)
void uncover (ShapeItem j)
uncover columns j (see Knuth)
ShapeItem get_column_count () const
return the (decreasing) number of columns
void display (ostream &out) const
display the matrix
void solve ()
solve the constraints matrix
Token preset (const Cell *steps, ShapeItem count, const Cell *cB)
do some dance steps with the constraints matrix
ShapeItem get_solution_count () const
return the number of solutions found
ShapeItem get_pick_count () const
return the number of items picked
ShapeItem get_cover_count () const
return the number of columns covered
Public Member Functions inherited from DLX_Node
DLX_Node (bool hdr)
default constructor for node allocation
DLX_Node (bool hdr, ShapeItem R, ShapeItem C, DLX_Node *u, DLX_Node *d, DLX_Node *l, DLX_Node *r)
normal constructor
void operator= (const DLX_Node &other)
assignment
void insert_lr ()
(re-)insert this node horizontally (between left and right)
void insert_ud ()
(re-)insert this node vertically (between up and down)
void remove_lr ()
remove(unlink) this node horizontally
void remove_ud ()
remove(unlink) this node vertically
void check () const
check the consistency of the up, down, left, and right links
ostream & print_RC (ostream &out) const
print the row and columns of this node
void print (ostream &out) const
print this node
Public Attributes
std::vector< ShapeItem > all_solutions
all solutions as len rows... len rows ...
Public Attributes inherited from DLX_Node
const ShapeItem row
the row of this node
const ShapeItem col
the column of this node
DLX_Node * up
link to the next node above
DLX_Node * down
link to the next node below
DLX_Node * left
link to the next node on the left
DLX_Node * right
link to the next node on the right
const bool is_header
true if ths node is a header node (containing no data)
Protected Attributes
const ShapeItem max_solutions
the max. number of solutions to produce, 0 = all
const ShapeItem rows
the number of rows
const ShapeItem cols
the number of columns
std::vector< DLX_Header_Node > headers
the column headers
std::vector< DLX_Node > nodes
the '1's and '2's in the (sparse) matrix
ShapeItem primary_count
the number of primary columns
ShapeItem secondary_count
the number of primary columns
ShapeItem solution_count
the number of solutions found so far
ShapeItem level
the number of rows in the current partial solution (aka recursion depth)
ShapeItem pick_count
the total number of pick'ed elements
ShapeItem cover_count
the total number of covr operations
const Cell * first_0
the first 0 in the matrix (for figuring the format)
Additional Inherited Members
Public Types inherited from DLX_Node
enum Col_Type {
Col_INVALID = -1 ,
Col_NULL = 0 ,
Col_PRIMARY = 1 ,
Col_SECONDARY = 2 ,
Col_UNKNOWN = Col_NULL
}
the type of column
Static Public Member Functions inherited from DLX_Node
static Col_Type get_col_type (const Cell &cell)
return the type of column
Detailed Description
The root node of the constraints matrix.
Definition at line 198 of file Quad_DLX.cc.
Constructor & Destructor Documentation
DLX_Root_Node()
DLX_Root_Node::DLX_Root_Node (ShapeItem rows, ShapeItem cols, ShapeItem max_sol, const Value & B)
constructor
Definition at line 319 of file Quad_DLX.cc.
References DLX_Node::col, DLX_Node::Col_INVALID, DLX_Node::Col_PRIMARY, DLX_Header_Node::col_type, DLX_Node::Col_UNKNOWN, cols, first_0, Cell::get_char_value(), DLX_Node::get_col_type(), Cell::get_int_value(), Workspace::get_IO(), headers, Cell::is_character_cell(), Cell::is_integer_cell(), nodes, primary_count, DLX_Node::row, rows, secondary_count, and DLX_Node::up.
Member Function Documentation
cover()
void DLX_Root_Node::cover (ShapeItem j) inline
cover columns j (see Knuth)
Definition at line 216 of file Quad_DLX.cc.
References DLX_Node::Col_PRIMARY, cover_count, headers, and primary_count.
Referenced by preset(), and solve().
deep_check()
void DLX_Root_Node::deep_check () const
check of all nodes
Definition at line 504 of file Quad_DLX.cc.
References DLX_Node::check(), DLX_Header_Node::count, DLX_Node::right, and DLX_Node::row.
Referenced by solve().
display()
void DLX_Root_Node::display (ostream & out) const
display the matrix
Definition at line 432 of file Quad_DLX.cc.
References DLX_Node::col, DLX_Node::Col_PRIMARY, DLX_Header_Node::col_type, cols, DLX_Header_Node::count, DLX_Node::right, DLX_Node::row, and rows.
get_column_count()
ShapeItem DLX_Root_Node::get_column_count () const
return the (decreasing) number of columns
Definition at line 659 of file Quad_DLX.cc.
References DLX_Node::right.
Referenced by preset().
get_cover_count()
ShapeItem DLX_Root_Node::get_cover_count () const inline
return the number of columns covered
Definition at line 276 of file Quad_DLX.cc.
References cover_count.
Referenced by Quad_DLX::do_DLX().
get_pick_count()
ShapeItem DLX_Root_Node::get_pick_count () const inline
return the number of items picked
Definition at line 273 of file Quad_DLX.cc.
References pick_count.
Referenced by Quad_DLX::do_DLX().
get_solution_count()
ShapeItem DLX_Root_Node::get_solution_count () const inline
return the number of solutions found
Definition at line 270 of file Quad_DLX.cc.
References solution_count.
Referenced by Quad_DLX::do_DLX().
indent()
ostream & DLX_Root_Node::indent (ostream & out) inline
indent for current level
Definition at line 209 of file Quad_DLX.cc.
References level.
Referenced by solve().
preset()
Token DLX_Root_Node::preset (const Cell * steps, ShapeItem count, const Cell * cB)
do some dance steps with the constraints matrix
Definition at line 667 of file Quad_DLX.cc.
References DLX_Node::col, cols, cover(), DLX_Node::down, first_0, get_column_count(), Cell::get_int_value(), Workspace::get_IO(), DLX_Node::is_header, Cell::is_integer_cell(), nodes, DLX_Node::print_RC(), DLX_Node::right, DLX_Node::row, and rows.
Referenced by Quad_DLX::eval_AB().
solve()
void DLX_Root_Node::solve ()
solve the constraints matrix
Definition at line 523 of file Quad_DLX.cc.
References all_solutions, DLX_Node::col, DLX_Node::Col_PRIMARY, cols, cover(), deep_check(), DLX_Node::down, Workspace::get_IO(), headers, indent(), DLX_Node::left, level, max_solutions, pick_count, primary_count, DLX_Node::print_RC(), DLX_Node::right, DLX_Node::row, solution_count, and uncover().
Referenced by Quad_DLX::do_DLX().
uncover()
void DLX_Root_Node::uncover (ShapeItem j) inline
uncover columns j (see Knuth)
Definition at line 238 of file Quad_DLX.cc.
References DLX_Node::Col_PRIMARY, headers, and primary_count.
Referenced by solve().
Member Data Documentation
all_solutions
std::vector<ShapeItem> DLX_Root_Node::all_solutions
all solutions as len rows... len rows ...
Definition at line 279 of file Quad_DLX.cc.
Referenced by Quad_DLX::do_DLX(), and solve().
cols
const ShapeItem DLX_Root_Node::cols protected
the number of columns
Definition at line 289 of file Quad_DLX.cc.
Referenced by display(), DLX_Root_Node(), preset(), and solve().
cover_count
ShapeItem DLX_Root_Node::cover_count protected
the total number of covr operations
Definition at line 313 of file Quad_DLX.cc.
Referenced by cover(), and get_cover_count().
first_0
const Cell* DLX_Root_Node::first_0 protected
the first 0 in the matrix (for figuring the format)
Definition at line 316 of file Quad_DLX.cc.
Referenced by DLX_Root_Node(), and preset().
headers
std::vector<DLX_Header_Node> DLX_Root_Node::headers protected
the column headers
Definition at line 292 of file Quad_DLX.cc.
Referenced by cover(), DLX_Root_Node(), solve(), and uncover().
level
ShapeItem DLX_Root_Node::level protected
the number of rows in the current partial solution (aka recursion depth)
Definition at line 307 of file Quad_DLX.cc.
Referenced by indent(), and solve().
max_solutions
const ShapeItem DLX_Root_Node::max_solutions protected
the max. number of solutions to produce, 0 = all
Definition at line 283 of file Quad_DLX.cc.
Referenced by solve().
nodes
std::vector<DLX_Node> DLX_Root_Node::nodes protected
the '1's and '2's in the (sparse) matrix
Definition at line 295 of file Quad_DLX.cc.
Referenced by DLX_Root_Node(), and preset().
pick_count
ShapeItem DLX_Root_Node::pick_count protected
the total number of pick'ed elements
Definition at line 310 of file Quad_DLX.cc.
Referenced by get_pick_count(), and solve().
primary_count
ShapeItem DLX_Root_Node::primary_count protected
the number of primary columns
Definition at line 298 of file Quad_DLX.cc.
Referenced by cover(), DLX_Root_Node(), solve(), and uncover().
rows
const ShapeItem DLX_Root_Node::rows protected
the number of rows
Definition at line 286 of file Quad_DLX.cc.
Referenced by display(), DLX_Root_Node(), and preset().
secondary_count
ShapeItem DLX_Root_Node::secondary_count protected
the number of primary columns
Definition at line 301 of file Quad_DLX.cc.
Referenced by DLX_Root_Node().
solution_count
ShapeItem DLX_Root_Node::solution_count protected
the number of solutions found so far
Definition at line 304 of file Quad_DLX.cc.
Referenced by get_solution_count(), and solve().
The documentation for this class was generated from the following file:
src/Quad_DLX.cc