GNU APL: TabExpansion Class Reference
TabExpansion Class Reference
a class for doing interactivw Tab-expansion on input lines
#include <TabExpansion.hh>
Public Member Functions
TabExpansion (UCS_string &line)
constructor
ExpandResult expand_tab (UCS_string &line)
perform tab expansion
Protected Member Functions
ExpandResult expand_user_name (UCS_string &user)
tab-expand a user-defined name
ExpandResult expand_APL_command (UCS_string &user)
tab-expand an APL command
ExpandResult expand_distinguished_name (UCS_string &user)
tab-expand a system-defined name (⎕xxx)
ExpandResult expand_help_topics ()
show the names of all APL primitives and user defined functions
ExpandResult expand_help_topics (UCS_string &user)
tab-expand or show help for user defined functions
ExpandResult expand_command_arg (UCS_string &user, ExpandHint ehint, const char *shint, const UCS_string cmd, const UCS_string arg)
perform tab expansion for command arguments
ExpandResult expand_filename (UCS_string &user, ExpandHint ehint, const char *shint, const UCS_string cmd, UCS_string arg)
perform tab expansion for a filename
ExpandResult expand_wsname (UCS_string &line, const UCS_string cmd, LibRef lib, const UCS_string filename)
perform tab expansion for a workspace name
int compute_common_length (int len, const UCS_string_vector &matches)
compute the lenght of the common part in all matches
void read_matching_filenames (DIR *dir, UTF8_string dirname, UTF8_string prefix, ExpandHint ehint, UCS_string_vector &matches)
read filenames in dir and append matching filenames to matches
ExpandResult show_alternatives (UCS_string &user, int prefix_len, UCS_string_vector &matches)
show the different alternatives for tab expansions
Protected Attributes
const bool have_trailing_blank
true if the original line had a trailing blank
Detailed Description
a class for doing interactivw Tab-expansion on input lines
Definition at line 71 of file TabExpansion.hh.
Constructor & Destructor Documentation
TabExpansion()
TabExpansion::TabExpansion (UCS_string & line)
constructor
Definition at line 28 of file TabExpansion.cc.
Member Function Documentation
compute_common_length()
int TabExpansion::compute_common_length (int len, const UCS_string_vector & matches) protected
compute the lenght of the common part in all matches
Definition at line 627 of file TabExpansion.cc.
Referenced by expand_distinguished_name(), expand_help_topics(), and show_alternatives().
expand_APL_command()
ExpandResult TabExpansion::expand_APL_command (UCS_string & user) protected
tab-expand an APL command
Definition at line 91 of file TabExpansion.cc.
References UCS_string::append(), expand_command_arg(), have_trailing_blank, show_alternatives(), UCS_string::size(), and UCS_string::split_ws().
Referenced by expand_tab().
expand_command_arg()
ExpandResult TabExpansion::expand_command_arg (UCS_string & user, ExpandHint ehint, const char * shint, const UCS_string cmd, const UCS_string arg) protected
perform tab expansion for command arguments
Definition at line 172 of file TabExpansion.cc.
References expand_filename(), and expand_help_topics().
Referenced by expand_APL_command().
expand_distinguished_name()
ExpandResult TabExpansion::expand_distinguished_name (UCS_string & user) protected
tab-expand a system-defined name (⎕xxx)
Definition at line 346 of file TabExpansion.cc.
References UCS_string::append(), compute_common_length(), UCS_string::size(), and UCS_string_vector::sort().
Referenced by expand_tab().
expand_filename()
ExpandResult TabExpansion::expand_filename (UCS_string & user, ExpandHint ehint, const char * shint, const UCS_string cmd, UCS_string arg) protected
perform tab expansion for a filename
Definition at line 427 of file TabExpansion.cc.
References UCS_string::append(), UTF8_string::c_str(), UCS_string::drop(), UCS_string::erase(), expand_wsname(), have_trailing_blank, LibPaths::is_present(), read_matching_filenames(), show_alternatives(), and UCS_string::size().
Referenced by expand_command_arg().
expand_help_topics() [1/2]
ExpandResult TabExpansion::expand_help_topics () protected
show the names of all APL primitives and user defined functions
Definition at line 264 of file TabExpansion.cc.
References Workspace::get_all_symbols(), Symbol::get_name(), Workspace::get_PW(), Symbol::is_erased(), _help::prim, and UCS_string_vector::sort().
Referenced by expand_command_arg(), and expand_help_topics().
expand_help_topics() [2/2]
ExpandResult TabExpansion::expand_help_topics (UCS_string & user) protected
tab-expand or show help for user defined functions
Definition at line 201 of file TabExpansion.cc.
References compute_common_length(), expand_help_topics(), Workspace::get_all_symbols(), Symbol::get_name(), Symbol::is_erased(), UCS_string::remove_leading_whitespaces(), show_alternatives(), UCS_string::size(), UCS_string_vector::sort(), and UCS_string::starts_with().
expand_tab()
ExpandResult TabExpansion::expand_tab (UCS_string & line)
perform tab expansion
Definition at line 34 of file TabExpansion.cc.
References expand_APL_command(), expand_distinguished_name(), expand_user_name(), Avec::is_first_symbol_char(), UCS_string::remove_leading_and_trailing_whitespaces(), and UCS_string::size().
Referenced by LineEditContext::tab_expansion().
expand_user_name()
ExpandResult TabExpansion::expand_user_name (UCS_string & user) protected
tab-expand a user-defined name
Definition at line 53 of file TabExpansion.cc.
References Workspace::get_all_symbols(), Symbol::get_name(), Symbol::is_erased(), show_alternatives(), UCS_string::size(), and UCS_string::starts_with().
Referenced by expand_tab().
expand_wsname()
ExpandResult TabExpansion::expand_wsname (UCS_string & line, const UCS_string cmd, LibRef lib, const UCS_string filename) protected
perform tab expansion for a workspace name
Definition at line 566 of file TabExpansion.cc.
References UCS_string::append(), UCS_string::append_number(), UCS_string::append_UTF8(), UTF8_string::c_str(), LibPaths::get_lib_dir(), read_matching_filenames(), show_alternatives(), and UCS_string::size().
Referenced by expand_filename().
read_matching_filenames()
void TabExpansion::read_matching_filenames (DIR * dir, UTF8_string dirname, UTF8_string prefix, ExpandHint ehint, UCS_string_vector & matches) protected
read filenames in dir and append matching filenames to matches
Definition at line 642 of file TabExpansion.cc.
References UCS_string::append(), UTF8_string::c_str(), UTF8_string::ends_with(), and Command::is_directory().
Referenced by expand_filename(), and expand_wsname().
show_alternatives()
ExpandResult TabExpansion::show_alternatives (UCS_string & user, int prefix_len, UCS_string_vector & matches) protected
show the different alternatives for tab expansions
Definition at line 680 of file TabExpansion.cc.
References UCS_string::append(), compute_common_length(), and UCS_string::size().
Referenced by expand_APL_command(), expand_filename(), expand_help_topics(), expand_user_name(), and expand_wsname().
Member Data Documentation
have_trailing_blank
const bool TabExpansion::have_trailing_blank protected
true if the original line had a trailing blank
Definition at line 125 of file TabExpansion.hh.
Referenced by expand_APL_command(), and expand_filename().
The documentation for this class was generated from the following files:
src/TabExpansion.hh
src/TabExpansion.cc