GNU APL: Svar_DB Class Reference
Svar_DB Class Reference
Access to the shared variable database in APserver.
#include <Svar_DB.hh>
Public Member Functions
void open_shared_memory (const char *progname, bool logit, bool do_svars)
open (and possibly initialize) the shared variable database
Static Public Member Functions
static void init (const char *bin_path, const char *prog, int retry_max, bool logit, bool do_svars)
open (and possibly initialize) the shared variable database
static SV_key match_or_make (const uint32_t *UCS_varname, const AP_num3 &to, const Svar_partner &from)
match a new offer against the DB. Return: 0 on error, 1 if the new offer was inserted into the DB (sicne no match was found), or 2 if a pending offer was found. In the latter case, the pending offer was removed and its relevant data returned through the d_... args.
static bool is_registered_id (const AP_num3 &id)
return true if id is registered in APserver
static TCP_socket get_Svar_DB_tcp (const char *calling_function)
get TCP socket to APserver, complain if not connected
static void retract_var (SV_key key)
retract an offer, return previous coupling
static const uint32_t * get_svar_name (SV_key key)
return pointer to varname or 0 if key does not exist
static AP_num3 find_offering_id (SV_key key)
find ID of the procesdsor that has offered the variable with key key
static void get_offering_processors (AP_num to_proc, std::vector< AP_num > &processors)
add processors with pending offers to to_proc. Duplicates are OK and will be removed later
static void get_offered_variables (AP_num to_proc, AP_num from_proc, std::vector< uint32_t > &varnames)
return all variables shared between to_proc and from_proc
static SV_Coupling get_coupling (SV_key key)
return coupling of entry with key.
static Svar_Control get_control (SV_key key)
return the current control vector of this variable
static void set_control (SV_key key, Svar_Control ctl)
set the current control vector of this variable
static Svar_state get_state (SV_key key)
return the current state of this variable
static bool is_ws_to_ws (SV_key key)
true if key is shared between workspaces (as opposed to shared between a workspace and an AP
static bool may_set (SV_key key, int attempt)
return true iff setting the shared variable is allowed
static bool may_use (SV_key key, int attempt)
return true iff reading the shared variable is allowed
static void set_state (SV_key key, bool used, const char *loc)
set the current state of this variable
static SV_key find_pairing_key (SV_key key)
some shared variables names belong to a pair, like CTL and DAT in AP210. return the key of the other variable
static Svar_event clear_all_events (AP_num3 id)
clear all events, return the current event bitmap.
static SV_key get_events (Svar_event &events, AP_num3 proc)
return events for processor proc
static void add_event (SV_key key, AP_num3 id, Svar_event event)
set an event for proc (and maybe also for key)
static void print (ostream &out)
print the database
static TCP_socket connect_to_APserver (const char *bin_path, const char *prog, int retry_max, bool logit)
return a socket that is connect to APserver
static void disconnect ()
close TCP connection to APserver
static bool APserver_available ()
return true if the connection to APserver is up
static TCP_socket get_DB_tcp ()
return the fd towards APserver
static void DB_tcp_error (const char *op, int got, int expected)
print TCP error information
Static Protected Member Functions
static bool start_APserver (const char *server_sockname, const char *bin_dir, bool logit)
start an APserver process, return true on failure
Static Protected Attributes
static TCP_socket DB_tcp = NO_TCP_SOCKET
the TCP connection to APserver, NO_TCP_SOCKET if invalid
static uint16_t APserver_port = 16366
The TCP port of APserver.
Private Member Functions
Svar_DB ()
don't create...
Svar_DB (const Svar_DB &other)
don't copy...
Svar_DB & operator= (const Svar_DB &other)
don't copy...
Detailed Description
Access to the shared variable database in APserver.
Definition at line 69 of file Svar_DB.hh.
Member Function Documentation
add_event()
void Svar_DB::add_event (SV_key key, AP_num3 id, Svar_event event) static
set an event for proc (and maybe also for key)
Definition at line 534 of file Svar_DB.cc.
References get_Svar_DB_tcp().
APserver_available()
static bool Svar_DB::APserver_available () inline static
return true if the connection to APserver is up
Definition at line 179 of file Svar_DB.hh.
References DB_tcp.
Referenced by init(), and Svar_record_P::Svar_record_P().
clear_all_events()
Svar_event Svar_DB::clear_all_events (AP_num3 id) static
clear all events, return the current event bitmap.
Definition at line 439 of file Svar_DB.cc.
References Signal_base::get__EVENTS_ARE__events(), get_Svar_DB_tcp(), and Signal_base::recv_TCP().
Referenced by Quad_SVE::get_apl_value().
connect_to_APserver()
TCP_socket Svar_DB::connect_to_APserver (const char * bin_path, const char * prog, int retry_max, bool logit) static
return a socket that is connect to APserver
Definition at line 151 of file Svar_DB.cc.
References SockAddr::addr, APserver_port, SockAddr::inet, start_APserver(), and SockAddr::uNix.
Referenced by init().
DB_tcp_error()
void Svar_DB::DB_tcp_error (const char * op, int got, int expected) static
print TCP error information
Definition at line 306 of file Svar_DB.cc.
References DB_tcp.
Referenced by ProcessorID::disconnect().
disconnect()
static void Svar_DB::disconnect () inline static
close TCP connection to APserver
Definition at line 172 of file Svar_DB.hh.
References DB_tcp.
find_offering_id()
AP_num3 Svar_DB::find_offering_id (SV_key key) static
find ID of the procesdsor that has offered the variable with key key
Definition at line 552 of file Svar_DB.cc.
References Signal_base::get__OFFERING_ID_IS__grand(), Signal_base::get__OFFERING_ID_IS__parent(), Signal_base::get__OFFERING_ID_IS__proc(), get_Svar_DB_tcp(), and Signal_base::recv_TCP().
find_pairing_key()
SV_key Svar_DB::find_pairing_key (SV_key key) static
some shared variables names belong to a pair, like CTL and DAT in AP210. return the key of the other variable
Definition at line 667 of file Svar_DB.cc.
References Signal_base::get__PAIRING_KEY_IS__pairing_key(), get_DB_tcp(), and Signal_base::recv_TCP().
get_control()
static Svar_Control Svar_DB::get_control (SV_key key) inline static
return the current control vector of this variable
Definition at line 120 of file Svar_DB.hh.
get_coupling()
static SV_Coupling Svar_DB::get_coupling (SV_key key) inline static
return coupling of entry with key.
Definition at line 114 of file Svar_DB.hh.
get_DB_tcp()
static TCP_socket Svar_DB::get_DB_tcp () inline static
return the fd towards APserver
Definition at line 183 of file Svar_DB.hh.
References DB_tcp.
Referenced by Symbol::assign_shared_variable(), find_pairing_key(), get_Svar_DB_tcp(), ProcessorID::init(), print(), Symbol::resolve_shared_variable(), and Svar_record_P::Svar_record_P().
get_events()
SV_key Svar_DB::get_events (Svar_event & events, AP_num3 proc) static
return events for processor proc
Definition at line 407 of file Svar_DB.cc.
References Signal_base::get__EVENTS_ARE__events(), Signal_base::get__EVENTS_ARE__key(), get_Svar_DB_tcp(), and Signal_base::recv_TCP().
Referenced by Quad_SVE::get_apl_value().
get_offered_variables()
void Svar_DB::get_offered_variables (AP_num to_proc, AP_num from_proc, std::vector< uint32_t > & varnames) static
return all variables shared between to_proc and from_proc
Definition at line 604 of file Svar_DB.cc.
References Signal_base::get__OFFERED_VARS_ARE__offered_vars(), get_Svar_DB_tcp(), and Signal_base::recv_TCP().
Referenced by Quad_SVQ::get_variables().
get_offering_processors()
void Svar_DB::get_offering_processors (AP_num to_proc, std::vector< AP_num > & processors) static
add processors with pending offers to to_proc. Duplicates are OK and will be removed later
Definition at line 578 of file Svar_DB.cc.
References Signal_base::get__OFFERING_PROCS_ARE__offering_procs(), get_Svar_DB_tcp(), and Signal_base::recv_TCP().
Referenced by Quad_SVQ::get_processors().
get_state()
static Svar_state Svar_DB::get_state (SV_key key) inline static
return the current state of this variable
Definition at line 129 of file Svar_DB.hh.
get_Svar_DB_tcp()
TCP_socket Svar_DB::get_Svar_DB_tcp (const char * calling_function) static
get TCP socket to APserver, complain if not connected
Definition at line 654 of file Svar_DB.cc.
References get_DB_tcp().
Referenced by add_event(), clear_all_events(), find_offering_id(), get_events(), get_offered_variables(), get_offering_processors(), is_registered_id(), match_or_make(), may_set(), may_use(), retract_var(), set_control(), and set_state().
get_svar_name()
static const uint32_t * Svar_DB::get_svar_name (SV_key key) inline static
return pointer to varname or 0 if key does not exist
Definition at line 96 of file Svar_DB.hh.
init()
void Svar_DB::init (const char * bin_path, const char * prog, int retry_max, bool logit, bool do_svars) static
open (and possibly initialize) the shared variable database
Definition at line 350 of file Svar_DB.cc.
References APserver_available(), connect_to_APserver(), and DB_tcp.
is_registered_id()
bool Svar_DB::is_registered_id (const AP_num3 & id) static
return true if id is registered in APserver
Definition at line 630 of file Svar_DB.cc.
References Signal_base::get__YES_NO__yes(), get_Svar_DB_tcp(), and Signal_base::recv_TCP().
Referenced by ProcessorID::init(), and Quad_SVO::share_one_variable().
is_ws_to_ws()
static bool Svar_DB::is_ws_to_ws (SV_key key) inline static
true if key is shared between workspaces (as opposed to shared between a workspace and an AP
Definition at line 136 of file Svar_DB.hh.
match_or_make()
SV_key Svar_DB::match_or_make (const uint32_t * UCS_varname, const AP_num3 & to, const Svar_partner & from) static
match a new offer against the DB. Return: 0 on error, 1 if the new offer was inserted into the DB (sicne no match was found), or 2 if a pending offer was found. In the latter case, the pending offer was removed and its relevant data returned through the d_... args.
Definition at line 369 of file Svar_DB.cc.
References Signal_base::get__MATCH_OR_MAKE_RESULT__key(), get_Svar_DB_tcp(), Svar_partner::id, and Signal_base::recv_TCP().
Referenced by Quad_SVO::share_one_variable().
may_set()
bool Svar_DB::may_set (SV_key key, int attempt) static
return true iff setting the shared variable is allowed
Definition at line 487 of file Svar_DB.cc.
References Signal_base::get__YES_NO__yes(), get_Svar_DB_tcp(), and Signal_base::recv_TCP().
Referenced by Symbol::assign_shared_variable().
may_use()
bool Svar_DB::may_use (SV_key key, int attempt) static
return true iff reading the shared variable is allowed
Definition at line 511 of file Svar_DB.cc.
References Signal_base::get__YES_NO__yes(), get_Svar_DB_tcp(), and Signal_base::recv_TCP().
Referenced by Symbol::resolve_shared_variable().
print()
void Svar_DB::print (ostream & out) static
print the database
Definition at line 691 of file Svar_DB.cc.
References Signal_base::get__SVAR_DB_PRINTED__printout(), get_DB_tcp(), and Signal_base::recv_TCP().
retract_var()
void Svar_DB::retract_var (SV_key key) static
retract an offer, return previous coupling
Definition at line 543 of file Svar_DB.cc.
References get_Svar_DB_tcp().
Referenced by Symbol::unshare_var().
set_control()
void Svar_DB::set_control (SV_key key, Svar_Control ctl) static
set the current control vector of this variable
Definition at line 468 of file Svar_DB.cc.
References get_Svar_DB_tcp().
Referenced by Quad_SVC::eval_AB().
set_state()
void Svar_DB::set_state (SV_key key, bool used, const char * loc) static
set the current state of this variable
Definition at line 477 of file Svar_DB.cc.
References get_Svar_DB_tcp().
Referenced by Symbol::assign_shared_variable(), and Symbol::resolve_shared_variable().
start_APserver()
bool Svar_DB::start_APserver (const char * server_sockname, const char * bin_dir, bool logit) static protected
start an APserver process, return true on failure
Definition at line 67 of file Svar_DB.cc.
References APserver_port.
Referenced by connect_to_APserver().
Member Data Documentation
APserver_port
uint16_t Svar_DB::APserver_port = 16366 static protected
The TCP port of APserver.
Definition at line 198 of file Svar_DB.hh.
Referenced by connect_to_APserver(), and start_APserver().
DB_tcp
TCP_socket Svar_DB::DB_tcp = NO_TCP_SOCKET static protected
the TCP connection to APserver, NO_TCP_SOCKET if invalid
Definition at line 195 of file Svar_DB.hh.
Referenced by APserver_available(), DB_tcp_error(), disconnect(), get_DB_tcp(), and init().
The documentation for this class was generated from the following files:
src/Svar_DB.hh
src/Svar_DB.cc