GNU APL: Tokenizer Class Reference
Tokenizer Class Reference
The converter from APL input characters to APL tokens.
#include <Tokenizer.hh>
Public Member Functions
Tokenizer (ParseMode pm, const char *, bool mac)
Constructor.
ErrorCode tokenize (const UCS_string &input, Token_string &tos) const
tokenize UTF-8 string input into token string tos.
Static Public Member Functions
static Token tokenize_function (Unicode uni)
tokenize a primitive (1-character) function
Protected Member Functions
void do_tokenize (const UCS_string &input, Token_string &tos, size_t &rest_2) const
tokenize UCS string input into token string tos.
void tokenize_function (Unicode_source &src, Token_string &tos) const
tokenize a function
void tokenize_quad (Unicode_source &src, Token_string &tos) const
tokenize a Quad function or variable
void tokenize_string1 (Unicode_source &src, Token_string &tos, size_t &rest_2) const
tokenize a single quoted string
void tokenize_string2 (Unicode_source &src, Token_string &tos, size_t &rest_2) const
tokenize a double quoted string
void tokenize_number (Unicode_source &src, Token_string &tos, size_t &rest_2) const
tokenize a number (integer, floating point, or complex).
bool tokenize_real (Unicode_source &src, bool &need_float, APL_Float &flt_val, APL_Integer &int_val) const
tokenize a real number (integer or floating point).
void tokenize_symbol (Unicode_source &src, Token_string &tos) const
tokenize a symbol
Static Protected Member Functions
static int scan_real (const char *strg, APL_Float &result, int E_pos, int minus_pos)
a locale-independent sscanf()
Protected Attributes
const ParseMode pmode
the parsing mode of this parser
const bool macro
tokenize macro code
const char * loc
caller of this Tokenizer
Detailed Description
The converter from APL input characters to APL tokens.
Definition at line 95 of file Tokenizer.hh.
Constructor & Destructor Documentation
Tokenizer()
Tokenizer::Tokenizer (ParseMode pm, const char * , bool mac) inline
Constructor.
Definition at line 99 of file Tokenizer.hh.
Member Function Documentation
do_tokenize()
void Tokenizer::do_tokenize (const UCS_string & input, Token_string & tos, size_t & rest_2) const protected
tokenize UCS string input into token string tos.
convert UCS_string input into a Token_string tos. The tokenization stops at the end of input (= end of line), or when a comment (⍝ or #) is detected.
Definition at line 82 of file Tokenizer.cc.
References Error::error_name(), Bif_OPER2_OUTER::fun, Token::get_char_val(), Token::get_Class(), Token::get_Id(), Token::get_tag(), Workspace::get_v_Quad_QUOTE(), Avec::is_digit(), Avec::is_quad(), loc, pmode, Unicode_source::rest(), UCS_string::size(), Token::tag_name(), Error::throw_parse_error(), tokenize_function(), tokenize_number(), tokenize_quad(), tokenize_string1(), tokenize_string2(), tokenize_symbol(), and Avec::uni_to_token().
tokenize()
ErrorCode Tokenizer::tokenize (const UCS_string & input, Token_string & tos) const
tokenize UTF-8 string input into token string tos.
convert UCS_string input into a Token_string tos.
Definition at line 60 of file Tokenizer.cc.
References Error::get_error_code(), and Error::set_error_line_2().
Referenced by UserFunction_header::init_local_vars(), UserFunction_header::init_signature(), Command::transfer_context::numeric_1TF(), Parser::parse(), and Quad_TF::tf1_inv().
tokenize_function() [1/2]
Token Tokenizer::tokenize_function (Unicode uni) static
tokenize a primitive (1-character) function
Definition at line 354 of file Tokenizer.cc.
References Token::get_tag(), and Avec::uni_to_token().
Referenced by do_tokenize(), Quad_FIO::eval_AXB(), Quad_FIO::eval_XB(), and tokenize_function().
tokenize_function() [2/2]
void Tokenizer::tokenize_function (Unicode_source & src, Token_string & tos) const protected
tokenize a function
Definition at line 344 of file Tokenizer.cc.
References Unicode_source::get(), and tokenize_function().
tokenize_number()
void Tokenizer::tokenize_number (Unicode_source & src, Token_string & tos, size_t & rest_2) const protected
tokenize a number (integer, floating point, or complex).
Definition at line 609 of file Tokenizer.cc.
References loc, Unicode_source::rest(), Error::throw_parse_error(), and tokenize_real().
Referenced by do_tokenize().
tokenize_quad()
void Tokenizer::tokenize_quad (Unicode_source & src, Token_string & tos) const protected
tokenize a Quad function or variable
Definition at line 453 of file Tokenizer.cc.
References UCS_string::append(), Unicode_source::get(), Workspace::get_quad(), Unicode_source::rest(), and Unicode_source::skip().
Referenced by do_tokenize().
tokenize_real()
bool Tokenizer::tokenize_real (Unicode_source & src, bool & need_float, APL_Float & flt_val, APL_Integer & int_val) const protected
tokenize a real number (integer or floating point).
large integer
Definition at line 804 of file Tokenizer.cc.
References UTF8_string::append_UTF8(), UTF8_string::back(), UTF8_string::erase(), Avec::is_digit(), Avec::is_hex_digit(), UTF8_string::pop_back(), and UTF8_string::round_0_1().
Referenced by tokenize_number().
tokenize_string1()
void Tokenizer::tokenize_string1 (Unicode_source & src, Token_string & tos, size_t & rest_2) const protected
tokenize a single quoted string
tokenize a single quoted string. If the string is a single character, then we return a TOK_CHARACTER. Otherwise we return TOK_APL_VALUE1.
Definition at line 479 of file Tokenizer.cc.
References UCS_string::append(), Unicode_source::get(), Avec::is_single_quote(), loc, Unicode_source::rest(), UCS_string::size(), and Error::throw_parse_error().
Referenced by do_tokenize().
tokenize_string2()
void Tokenizer::tokenize_string2 (Unicode_source & src, Token_string & tos, size_t & rest_2) const protected
tokenize a double quoted string
tokenize a double quoted string. If the string is a single character, then we return a TOK_CHARACTER. Otherwise we return TOK_APL_VALUE1.
Definition at line 540 of file Tokenizer.cc.
References UCS_string::append(), Unicode_source::get(), loc, Unicode_source::rest(), and Error::throw_parse_error().
Referenced by do_tokenize().
tokenize_symbol()
void Tokenizer::tokenize_symbol (Unicode_source & src, Token_string & tos) const protected
tokenize a symbol
Definition at line 1010 of file Tokenizer.cc.
References UCS_string::append(), Quad_STOP::fun, Quad_TRACE::fun, Unicode_source::get(), Avec::is_symbol_char(), Workspace::lookup_symbol(), macro, Unicode_source::rest(), and UCS_string::size().
Referenced by do_tokenize().
Member Data Documentation
loc
const char* Tokenizer::loc protected
caller of this Tokenizer
Definition at line 152 of file Tokenizer.hh.
Referenced by do_tokenize(), tokenize_number(), tokenize_string1(), and tokenize_string2().
macro
const bool Tokenizer::macro protected
tokenize macro code
Definition at line 149 of file Tokenizer.hh.
Referenced by tokenize_symbol().
pmode
const ParseMode Tokenizer::pmode protected
the parsing mode of this parser
Definition at line 146 of file Tokenizer.hh.
Referenced by do_tokenize().
The documentation for this class was generated from the following files:
src/Tokenizer.hh
src/Tokenizer.cc