GNU APL: Thread_context Class Reference
Thread_context Class Reference
the context for one parallel execution thread
#include <Thread_context.hh>
Public Types
typedef void PoolFunction(Thread_context &ctx)
a function that is executed by the pool (i.e. in parallel)
Public Member Functions
Thread_context ()
constructor
~Thread_context ()
destructor
CoreNumber get_N () const
return the number of the core executing this context
void PF_fork ()
start parallel execution of work in a worker
void PF_join ()
end parallel execution of work in a worker
void bind_to_cpu (CPU_Number cpu, bool logit)
bind thread to core
void print (ostream &out) const
print this TaskTree node
void M_lock_pool ()
make all workers lock on pool_sema
Static Public Member Functions
static void M_fork (const char *jname)
start parallel execution of work at the master
static void M_join ()
end parallel execution of work at the master
static void print_all (ostream &out)
print all TaskTree nodes
static void print_mileages (ostream &out, const char *loc)
print all mileages nodes
static void init_parallel (CoreCount thread_count, bool logit)
initialize all thread contexts (set all but N and thread)
static void init_sequential (bool logit)
initialize all thread contexts (set all but N and thread)
static Thread_context * get_context (CoreNumber n)
return the context for core n
static Thread_context & get_master ()
return the context of the master
static void kill_pool ()
terminate all worker threads
static CoreCount get_active_core_count ()
number of currently used cores
static void set_active_core_count (CoreCount new_count)
set the number of currently used cores
static void cleanup ()
remove all thread contexts (when the APL interpreter exits)
static void cancel_all_monadic_jobs ()
cancel all monadic jobs in all thread contexts
static void cancel_all_dyadic_jobs ()
cancel all dyadic jobs in all thread contexts
Public Attributes
pthread_t thread
the thread executing this context
volatile char job_number
a counter controlling the start of parallel jobs
const char * job_name
return the name of this context
bool do_join
true if this context shall join (i.e. is not the master)
sem_t pool_sema
a semaphore to block this context
bool blocked
true if blocked on pool_sema
Parallel_job_list< PJob_scalar_B, false > joblist_B
a list of monadic PJobs created by this core
Parallel_job_list< PJob_scalar_AB, false > joblist_AB
a list of dyadic PJobs created by this core
Static Public Attributes
static PoolFunction * do_work
the next work to be done
static PoolFunction PF_no_work
a thread-function that should not be called
static PoolFunction PF_lock_unlock_pool
block/unblock on the pool semaphore
Protected Member Functions
void init_entry (CoreNumber n)
initialize thread_contexts[n]
Protected Attributes
CoreNumber N
thread number (0 = interpreter, 1... worker threads
CPU_Number CPU
the cpu core to which this thread is bound
Static Protected Attributes
static Thread_context * thread_contexts = 0
all thread contexts
static CoreCount thread_contexts_count = CCNT_0
the number of thread contexts
static volatile _Atomic_word busy_worker_count = 0
the number of unfinished workers (excluding master)
static CoreCount active_core_count = CCNT_1
the number of cores currently used
Detailed Description
the context for one parallel execution thread
Multi-core GNU APL uses a pool of threads numbered 0, 1, ... core_count()-1
(master-) thread 0 is the interpreter (which also performs parallel work), while (worker-) threads 1 ... are only activated when some parallel work is available.
The worker threads 1... are either working, or busy-waiting for work, or blocked on a semaphore:
   init
    ↓
 blocked ←→ busy-waiting ←→ working
The transitions
blocked ←→ busy-waiting
occur before and after the master thread waits for terminal input or when the number of cores is being changed (with ⎕SYL[26;2]). The workers are blocked while the master thread waits for terminal input. The reason for this is that a busy-waiting worker is consuming power for no reason (to the extent that the CPU fan turns on even though there is no useful work in sight).
The transitions
  busy-waiting ←→ working
occurs when the execution of APL primitives, primarily scalar functions, suggests to execute in parallel (i.e. if the vectors involved are sufficiently long).
Definition at line 64 of file Thread_context.hh.
Member Typedef Documentation
PoolFunction
typedef void Thread_context::PoolFunction(Thread_context &ctx)
a function that is executed by the pool (i.e. in parallel)
Definition at line 68 of file Thread_context.hh.
Constructor & Destructor Documentation
Thread_context()
Thread_context::Thread_context ()
constructor
Definition at line 40 of file Thread_context.cc.
~Thread_context()
Thread_context::~Thread_context ()
destructor
Definition at line 49 of file Thread_context.cc.
References N, and thread.
Member Function Documentation
cancel_all_dyadic_jobs()
static void Thread_context::cancel_all_dyadic_jobs () inline static
cancel all dyadic jobs in all thread contexts
Definition at line 208 of file Thread_context.hh.
References Parallel_job_list< T, has_destructor >::cancel_jobs(), get_active_core_count(), get_context(), and joblist_AB.
Referenced by ScalarFunction::eval_scalar_AB().
cancel_all_monadic_jobs()
static void Thread_context::cancel_all_monadic_jobs () inline static
cancel all monadic jobs in all thread contexts
Definition at line 201 of file Thread_context.hh.
References Parallel_job_list< T, has_destructor >::cancel_jobs(), get_active_core_count(), get_context(), and joblist_B.
Referenced by ScalarFunction::eval_scalar_B().
cleanup()
void Thread_context::cleanup () static
remove all thread contexts (when the APL interpreter exits)
Definition at line 68 of file Thread_context.cc.
References thread_contexts, and thread_contexts_count.
get_active_core_count()
static CoreCount Thread_context::get_active_core_count () inline static
number of currently used cores
Definition at line 156 of file Thread_context.hh.
References active_core_count.
Referenced by cancel_all_dyadic_jobs(), cancel_all_monadic_jobs(), CPU_pool::change_core_count(), ScalarFunction::do_scalar_AB(), ScalarFunction::do_scalar_B(), ScalarFunction::eval_scalar_AB(), ScalarFunction::eval_scalar_B(), Bif_OPER2_INNER::scalar_inner_product(), and Bif_OPER2_OUTER::scalar_outer_product().
get_context()
static Thread_context * Thread_context::get_context (CoreNumber n) inline static
return the context for core n
Definition at line 133 of file Thread_context.hh.
References thread_contexts.
Referenced by cancel_all_dyadic_jobs(), cancel_all_monadic_jobs(), CPU_pool::change_core_count(), ScalarFunction::do_scalar_AB(), ScalarFunction::do_scalar_B(), ScalarFunction::eval_scalar_AB(), ScalarFunction::eval_scalar_B(), and Parallel::init().
get_master()
static Thread_context & Thread_context::get_master () inline static
return the context of the master
Definition at line 137 of file Thread_context.hh.
References thread_contexts.
Referenced by CPU_pool::change_core_count(), ScalarFunction::do_scalar_AB(), ScalarFunction::do_scalar_B(), M_fork(), PF_fork(), PF_join(), Bif_OPER2_INNER::scalar_inner_product(), and Bif_OPER2_OUTER::scalar_outer_product().
get_N()
CoreNumber Thread_context::get_N () const inline
return the number of the core executing this context
Definition at line 78 of file Thread_context.hh.
References N.
Referenced by Bif_OPER2_INNER::PF_scalar_inner_product(), and Bif_OPER2_OUTER::PF_scalar_outer_product().
init_sequential()
void Thread_context::init_sequential (bool logit) static
initialize all thread contexts (set all but N and thread)
Definition at line 60 of file Thread_context.cc.
References N, thread_contexts, and thread_contexts_count.
Referenced by Parallel::init().
M_fork()
static void Thread_context::M_fork (const char * jname) inline static
start parallel execution of work at the master
Definition at line 82 of file Thread_context.hh.
References active_core_count, busy_worker_count, get_master(), job_name, and job_number.
Referenced by ScalarFunction::do_scalar_AB(), ScalarFunction::do_scalar_B(), M_lock_pool(), Bif_OPER2_INNER::scalar_inner_product(), and Bif_OPER2_OUTER::scalar_outer_product().
M_join()
static void Thread_context::M_join () inline static
end parallel execution of work at the master
Definition at line 97 of file Thread_context.hh.
References busy_worker_count.
Referenced by ScalarFunction::do_scalar_AB(), ScalarFunction::do_scalar_B(), Bif_OPER2_INNER::scalar_inner_product(), and Bif_OPER2_OUTER::scalar_outer_product().
M_lock_pool()
void Thread_context::M_lock_pool ()
make all workers lock on pool_sema
Definition at line 111 of file Thread_context.cc.
References do_work, M_fork(), and PF_lock_unlock_pool.
PF_fork()
void Thread_context::PF_fork () inline
start parallel execution of work in a worker
Definition at line 90 of file Thread_context.hh.
References get_master(), and job_number.
PF_join()
void Thread_context::PF_join () inline
end parallel execution of work in a worker
Definition at line 103 of file Thread_context.hh.
References busy_worker_count, get_master(), and job_number.
print()
void Thread_context::print (ostream & out) const
print this TaskTree node
Definition at line 93 of file Thread_context.cc.
References blocked, job_name, job_number, N, and thread.
Referenced by print_all().
print_all()
void Thread_context::print_all (ostream & out) static
print all TaskTree nodes
Definition at line 78 of file Thread_context.cc.
References active_core_count, busy_worker_count, print(), thread_contexts, and thread_contexts_count.
Referenced by CPU_pool::change_core_count(), Parallel::init(), and signal_SEGV_handler().
set_active_core_count()
void Thread_context::set_active_core_count (CoreCount new_count) static
set the number of currently used cores
Definition at line 141 of file Thread_context.cc.
References active_core_count.
Referenced by CPU_pool::change_core_count(), and Parallel::init().
Member Data Documentation
active_core_count
CoreCount Thread_context::active_core_count = CCNT_1 static protected
the number of cores currently used
Definition at line 225 of file Thread_context.hh.
Referenced by get_active_core_count(), M_fork(), print_all(), and set_active_core_count().
blocked
bool Thread_context::blocked
true if blocked on pool_sema
Definition at line 189 of file Thread_context.hh.
Referenced by print().
busy_worker_count
volatile _Atomic_word Thread_context::busy_worker_count = 0 static protected
the number of unfinished workers (excluding master)
Definition at line 222 of file Thread_context.hh.
Referenced by M_fork(), M_join(), PF_join(), and print_all().
CPU
CPU_Number Thread_context::CPU protected
the cpu core to which this thread is bound
Definition at line 170 of file Thread_context.hh.
do_join
bool Thread_context::do_join
true if this context shall join (i.e. is not the master)
Definition at line 183 of file Thread_context.hh.
do_work
Thread_context::PoolFunction * Thread_context::do_work static
Initial value:
=
    &Thread_context::PF_no_work
the next work to be done
Definition at line 147 of file Thread_context.hh.
Referenced by ScalarFunction::do_scalar_AB(), ScalarFunction::do_scalar_B(), M_lock_pool(), Bif_OPER2_INNER::scalar_inner_product(), and Bif_OPER2_OUTER::scalar_outer_product().
job_name
const char* Thread_context::job_name
return the name of this context
Definition at line 180 of file Thread_context.hh.
Referenced by M_fork(), and print().
job_number
volatile char Thread_context::job_number
a counter controlling the start of parallel jobs
Definition at line 177 of file Thread_context.hh.
Referenced by CPU_pool::change_core_count(), M_fork(), PF_fork(), PF_join(), and print().
joblist_AB
Parallel_job_list<PJob_scalar_AB, false> Thread_context::joblist_AB
a list of dyadic PJobs created by this core
Definition at line 195 of file Thread_context.hh.
Referenced by cancel_all_dyadic_jobs(), and ScalarFunction::do_scalar_AB().
joblist_B
Parallel_job_list<PJob_scalar_B, false> Thread_context::joblist_B
a list of monadic PJobs created by this core
Definition at line 192 of file Thread_context.hh.
Referenced by cancel_all_monadic_jobs(), and ScalarFunction::do_scalar_B().
N
CoreNumber Thread_context::N protected
thread number (0 = interpreter, 1... worker threads
Definition at line 164 of file Thread_context.hh.
Referenced by get_N(), init_sequential(), print(), and ~Thread_context().
PF_lock_unlock_pool
void Thread_context::PF_lock_unlock_pool static
block/unblock on the pool semaphore
Definition at line 153 of file Thread_context.hh.
Referenced by M_lock_pool().
PF_no_work
void Thread_context::PF_no_work static
a thread-function that should not be called
Definition at line 150 of file Thread_context.hh.
pool_sema
sem_t Thread_context::pool_sema
a semaphore to block this context
Definition at line 186 of file Thread_context.hh.
thread
pthread_t Thread_context::thread
the thread executing this context
Definition at line 174 of file Thread_context.hh.
Referenced by Parallel::init(), print(), and ~Thread_context().
thread_contexts
Thread_context * Thread_context::thread_contexts = 0 static protected
all thread contexts
Definition at line 216 of file Thread_context.hh.
Referenced by cleanup(), get_context(), get_master(), init_sequential(), and print_all().
thread_contexts_count
CoreCount Thread_context::thread_contexts_count = CCNT_0 static protected
the number of thread contexts
Definition at line 219 of file Thread_context.hh.
Referenced by cleanup(), init_sequential(), and print_all().
The documentation for this class was generated from the following files:
src/Thread_context.hh
src/Thread_context.cc