GNU APL: DiffOut Class Reference
DiffOut Class Reference
a filebuf that compares its output with a file.
#include <DiffOut.hh>
Public Member Functions
DiffOut (bool _errout)
constructor
void reset ()
discard all characters
int LF_to_CRLF (int on)
set LF → CRLF expansion mode
Protected Member Functions
virtual int overflow (int c)
overloaded filebuf::overflow()
bool different (const UTF8 *apl, const UTF8 *ref, size_t &pos)
return true iff 0-terminated strings apl and ref differ at pos
Protected Attributes
UTF8_string aplout
a buffer for one line of APL output
bool errout
true for error messages, false for normal APL output
bool expand_LF
expand LF to CRLF
Detailed Description
a filebuf that compares its output with a file.
Definition at line 35 of file DiffOut.hh.
Constructor & Destructor Documentation
DiffOut()
DiffOut::DiffOut (bool _errout) inline
constructor
Definition at line 39 of file DiffOut.hh.
References aplout.
Member Function Documentation
different()
bool DiffOut::different (const UTF8 * apl, const UTF8 * ref, size_t & pos) protected
return true iff 0-terminated strings apl and ref differ at pos
Definition at line 96 of file DiffOut.cc.
References Avec::is_digit(), and UTF8_string::toUni().
Referenced by overflow().
LF_to_CRLF()
int DiffOut::LF_to_CRLF (int on) inline
set LF → CRLF expansion mode
Definition at line 50 of file DiffOut.hh.
References expand_LF.
overflow()
int DiffOut::overflow (int c) protected virtual
overloaded filebuf::overflow()
Definition at line 32 of file DiffOut.cc.
References aplout, UTF8_string::c_str(), Output::COLM_OUTPUT, Output::COLM_UERROR, IO_Files::diff_error(), different(), errout, expand_LF, IO_Files::get_current_testreport(), InputFile::is_validating(), IO_Files::read_file_line(), and Output::set_color_mode().
reset()
void DiffOut::reset () inline
discard all characters
Definition at line 46 of file DiffOut.hh.
References aplout.
Referenced by Output::reset_dout().
Member Data Documentation
aplout
UTF8_string DiffOut::aplout protected
a buffer for one line of APL output
Definition at line 62 of file DiffOut.hh.
Referenced by DiffOut(), overflow(), and reset().
errout
bool DiffOut::errout protected
true for error messages, false for normal APL output
Definition at line 65 of file DiffOut.hh.
Referenced by overflow().
expand_LF
bool DiffOut::expand_LF protected
expand LF to CRLF
Definition at line 68 of file DiffOut.hh.
Referenced by LF_to_CRLF(), and overflow().
The documentation for this class was generated from the following files:
src/DiffOut.hh
src/DiffOut.cc