GNU APL: LibPaths Class Reference
LibPaths Class Reference
a class mapping library reference numbers to directories
#include <LibPaths.hh>
Classes
struct LibDir
one library directory
Static Public Member Functions
static void init (const char *argv0, bool logit)
initialize library paths based on the location of the APL binary
static const char * get_APL_bin_path ()
return the path (directory) of the APL interpreter binary
static const char * get_APL_bin_name ()
return the name (without directory) of the APL interpreter binary
static const char * get_APL_lib_root ()
return directory containing (file or directory) workspaces and wslib1
static void set_APL_lib_root (const char *new_root)
set library root to new_root
static void set_lib_dir (LibRef lib, const char *path, LibDir::CfgSrc src)
set library path (from config file)
static bool is_present (LibRef lib)
return true iff directory lib) is present
static UTF8_string get_lib_dir (LibRef lib)
return library path (from config file or from libroot)
static LibDir::CfgSrc get_cfg_src (LibRef lib)
return source that configured this entry
static UTF8_string get_lib_filename (LibRef lib, const UTF8_string &name, bool existing, const char *ext1, const char *ext2)
return full path for file name, possibly adding .ext1 or .ext2
Static Protected Member Functions
static void maybe_warn_ambiguous (int name_has_extension, const UTF8_string name, const char *ext1, const char *ext2)
maybe warn the user if two files that differ only by extension exist
static void compute_bin_path (const char *argv0, bool logit)
compute the location of the apl binary
static void search_APL_lib_root ()
set library root, searching from APL_bin_path
static bool is_lib_root (const char *dir)
return true if directory dir contains two (files or sub-directories) workspaces and wslib1
Static Protected Attributes
static char APL_bin_path [] = ""
the path (directory) of the APL interpreter binary
static const char * APL_bin_name = LibPaths::APL_bin_path
the name (without directory) of the APL interpreter binary
static char APL_lib_root [] = ""
a directory containing sub-directories workspaces and wslib1
static LibDir lib_dirs [LIB_MAX]
directories for each library reference as specified in file preferences
static bool root_from_env = false
true if APL_lib_root was computed from environment variable APL_LIB_ROOT
static bool root_from_pwd = false
true if APL_lib_root was not found ("." taken)
Detailed Description
a class mapping library reference numbers to directories
Definition at line 48 of file LibPaths.hh.
Member Function Documentation
compute_bin_path()
void LibPaths::compute_bin_path (const char * argv0, bool logit) static protected
compute the location of the apl binary
Definition at line 60 of file LibPaths.cc.
References APL_bin_name, APL_bin_path, and UTF8_string::c_str().
Referenced by init().
get_APL_bin_name()
static const char * LibPaths::get_APL_bin_name () inline static
return the name (without directory) of the APL interpreter binary
Definition at line 84 of file LibPaths.hh.
References APL_bin_name.
Referenced by Workspace::dump_WS().
get_APL_bin_path()
static const char * LibPaths::get_APL_bin_path () inline static
return the path (directory) of the APL interpreter binary
Definition at line 81 of file LibPaths.hh.
References APL_bin_path.
Referenced by Workspace::dump_WS(), Quad_SVQ::get_processors(), Quad_GTK::open_window(), ProcessorID::read_network_profile(), and Quad_SVx::start_AP().
get_APL_lib_root()
static const char * LibPaths::get_APL_lib_root () inline static
return directory containing (file or directory) workspaces and wslib1
Definition at line 87 of file LibPaths.hh.
References APL_lib_root.
Referenced by Command::cmd_LIBS().
get_cfg_src()
static LibDir::CfgSrc LibPaths::get_cfg_src (LibRef lib) inline static
return source that configured this entry
Definition at line 102 of file LibPaths.hh.
References LibPaths::LibDir::cfg_src, and lib_dirs.
Referenced by Command::cmd_LIBS().
get_lib_dir()
UTF8_string LibPaths::get_lib_dir (LibRef lib) static
return library path (from config file or from libroot)
Definition at line 216 of file LibPaths.cc.
References APL_lib_root, UTF8_string::append_UTF8(), LibPaths::LibDir::CSRC_CMD, LibPaths::LibDir::CSRC_ENV, LibPaths::LibDir::CSRC_NONE, LibPaths::LibDir::CSRC_PREF_HOME, LibPaths::LibDir::CSRC_PREF_SYS, LibPaths::LibDir::CSRC_PWD, LibPaths::LibDir::dir_path, and lib_dirs.
Referenced by Command::cmd_LIBS(), TabExpansion::expand_wsname(), get_lib_filename(), is_present(), and Command::open_LIB_dir().
get_lib_filename()
UTF8_string LibPaths::get_lib_filename (LibRef lib, const UTF8_string & name, bool existing, const char * ext1, const char * ext2) static
return full path for file name, possibly adding .ext1 or .ext2
Definition at line 265 of file LibPaths.cc.
References UTF8_string::append_ASCII(), UTF8_string::append_UTF8(), UTF8_string::c_str(), UTF8_string::ends_with(), get_lib_dir(), maybe_warn_ambiguous(), and UTF8_string::starts_with().
Referenced by Command::cmd_DROP(), Command::cmd_IN(), Command::cmd_OUT(), Workspace::copy_WS(), Workspace::dump_WS(), init_apl(), Workspace::load_WS(), and Workspace::save_WS().
init()
void LibPaths::init (const char * argv0, bool logit) static
initialize library paths based on the location of the APL binary
Definition at line 44 of file LibPaths.cc.
References LibPaths::LibDir::cfg_src, compute_bin_path(), LibPaths::LibDir::CSRC_ENV, LibPaths::LibDir::CSRC_NONE, LibPaths::LibDir::CSRC_PWD, lib_dirs, root_from_env, root_from_pwd, and search_APL_lib_root().
is_lib_root()
bool LibPaths::is_lib_root (const char * dir) static protected
return true if directory dir contains two (files or sub-directories) workspaces and wslib1
Definition at line 155 of file LibPaths.cc.
Referenced by search_APL_lib_root().
is_present()
bool LibPaths::is_present (LibRef lib) static
return true iff directory lib) is present
Definition at line 363 of file LibPaths.cc.
References UTF8_string::c_str(), and get_lib_dir().
Referenced by TabExpansion::expand_filename().
maybe_warn_ambiguous()
void LibPaths::maybe_warn_ambiguous (int name_has_extension, const UTF8_string name, const char * ext1, const char * ext2) static protected
maybe warn the user if two files that differ only by extension exist
Definition at line 247 of file LibPaths.cc.
References UTF8_string::append_ASCII(), and UTF8_string::c_str().
Referenced by get_lib_filename().
search_APL_lib_root()
void LibPaths::search_APL_lib_root () static protected
set library root, searching from APL_bin_path
Definition at line 169 of file LibPaths.cc.
References APL_lib_root, is_lib_root(), root_from_env, and root_from_pwd.
Referenced by init().
set_APL_lib_root()
void LibPaths::set_APL_lib_root (const char * new_root) static
set library root to new_root
Definition at line 203 of file LibPaths.cc.
References APL_lib_root.
Referenced by Command::cmd_LIBS().
set_lib_dir()
void LibPaths::set_lib_dir (LibRef lib, const char * path, LibDir::CfgSrc src) static
set library path (from config file)
Definition at line 209 of file LibPaths.cc.
References LibPaths::LibDir::cfg_src, LibPaths::LibDir::dir_path, and lib_dirs.
Referenced by Command::cmd_LIBS(), and UserPreferences::read_config_file().
Member Data Documentation
APL_bin_name
const char * LibPaths::APL_bin_name = LibPaths::APL_bin_path static protected
the name (without directory) of the APL interpreter binary
Definition at line 129 of file LibPaths.hh.
Referenced by compute_bin_path(), and get_APL_bin_name().
APL_bin_path
char LibPaths::APL_bin_path = "" static protected
the path (directory) of the APL interpreter binary
Definition at line 126 of file LibPaths.hh.
Referenced by compute_bin_path(), and get_APL_bin_path().
APL_lib_root
char LibPaths::APL_lib_root = "" static protected
a directory containing sub-directories workspaces and wslib1
Definition at line 132 of file LibPaths.hh.
Referenced by get_APL_lib_root(), get_lib_dir(), search_APL_lib_root(), and set_APL_lib_root().
lib_dirs
LibPaths::LibDir LibPaths::lib_dirs static protected
directories for each library reference as specified in file preferences
Definition at line 135 of file LibPaths.hh.
Referenced by get_cfg_src(), get_lib_dir(), init(), and set_lib_dir().
root_from_env
bool LibPaths::root_from_env = false static protected
true if APL_lib_root was computed from environment variable APL_LIB_ROOT
Definition at line 138 of file LibPaths.hh.
Referenced by init(), and search_APL_lib_root().
root_from_pwd
bool LibPaths::root_from_pwd = false static protected
true if APL_lib_root was not found ("." taken)
Definition at line 141 of file LibPaths.hh.
Referenced by init(), and search_APL_lib_root().
The documentation for this class was generated from the following files:
src/LibPaths.hh
src/LibPaths.cc