GNU APL: Bif_F12_DOMINO::Matrix< cplx > Class Template Reference
Bif_F12_DOMINO::Matrix< cplx > Class Template Reference
Matrix is a helper class that makes a plain double * look like a real (cplx = false) or complex (cplx = true) matrix.
#include <Bif_F12_DOMINO.hh>
Public Types
enum { dpi = cplx ? 2 : 1 }
Public Member Functions
Matrix (double *pdata, ShapeItem uM, ShapeItem uN)
constructor: M×N matrix with the default vertical item spacings dY
Matrix (double *pdata, ShapeItem uM, ShapeItem uN, ShapeItem udY)
constructor: M×1 matrix (aka. column vector) from a matrix column
void resize (ShapeItem M, ShapeItem N)
resize a (nulti-purpose) matrix to size M×N
double & real (ShapeItem y, ShapeItem x)
return the real part of A[x;y]
void init_identity (ShapeItem rows)
initialize this matrix to the identity matrix
void imbed (const Matrix< cplx > &S)
imbed matrix S into this matrix
void init_outer_product (const norm_result &scale, const Matrix< cplx > &src)
initialize this matrix to be the outer product of the first column of src with itself
void operator= (const Matrix< cplx > &other)
assign matrix other to this matrix
void init_inner_product (const Matrix< cplx > &src_A, const Matrix< cplx > &src_B)
set this matrix to A +.× B
void transpose (ShapeItem M)
transpose the upper left M×M submatrix of this matrix
double * drop_1_1 ()
return the elements of matrix 1 1↓this
const double & real (ShapeItem y, ShapeItem x) const
return the real part of A[x;y]
double & imag (ShapeItem y, ShapeItem x)
return the imaginary part of A[x;y]
const double & imag (ShapeItem y, ShapeItem x) const
return the imaginary part of A[x;y]
complex< double > get_Z (ShapeItem y, ShapeItem x) const
return the complex number at row y, column x of this matrix
void set_Z (ShapeItem y, ShapeItem x, complex< double > val)
set the complex number at row y, column x of this matrix
void sub_Z (ShapeItem y, ShapeItem x, complex< double > val)
subtract val from the matrix element at row y, column x.
void div_Z (ShapeItem y, ShapeItem x, complex< double > val)
divide the matrix element at row y, col x by val.
bool significant (double bmax, double eps) const
true if this matrix is significant with respect to bmax and eps
double abs2 (ShapeItem y, ShapeItem x) const
return the square of the length of the item at row x column y
void col1_norm (norm_result &result) const
return the lengts of the first column(-vector) in different forms
void debug (const char *name) const
print this matrix boxed with name
void debug (const char *name) const
print debug infos for this real matrix
void debug (const char *name) const
print debug infos for this complex matrix
void col1_norm (norm_result &result) const
compute norm variants of column 1 of this real marix
void col1_norm (norm_result &result) const
compute norm variants of column 1 of this complex marix
double abs2 (ShapeItem y, ShapeItem x) const
compute the square of the real item at row y, columns x
double abs2 (ShapeItem y, ShapeItem x) const
compute the square of the complex item at row y, columns x
void add_sub (double *V11, const double *W11)
increase real *W11 by +/- real *V11
void add_sub (double *V11, const double *W11)
increase complex *W11 by +/- complex *V11
void init_identity (ShapeItem rows)
increase complex *W11 by +/- *V11
void init_identity (ShapeItem rows)
initialize this complex matrix to the unit matrix
void imbed (const Matrix< false > &S)
insert S into this real matrix
void imbed (const Matrix< true > &S)
insert S into this complex matrix
void init_outer_product (const norm_result &scale, const Matrix< false > &src)
initialize this real matrix to be the outer product of the first column of the real matrix src with itself
void init_outer_product (const norm_result &scale, const Matrix< true > &src)
initialize this complex matrix to be the outer product of the first column of the complex matrix src with itself
void operator= (const Matrix< false > &src)
assign real matrix src to this real matrix
void operator= (const Matrix< true > &src)
assign complex matrix src to this complex matrix
void init_inner_product (const Matrix< false > &src_A, const Matrix< false > &src_B)
set this matrix to A +.× B
void init_inner_product (const Matrix< true > &src_A, const Matrix< true > &src_B)
set this matrix to A +.× B
void transpose (ShapeItem M)
transpose the upper left M×M submatrix of this real matrix
void transpose (ShapeItem M)
transpose the upper left M×M submatrix of this complex matrix
Static Public Member Functions
static void add_sub (double *V11, const double *W11)
add or subtract val to/from a so that the result has the largest length.
Public Attributes
const ShapeItem M
the number of matrix rows
const ShapeItem N
the number of matrix columns
const ShapeItem dY
the distance (in doubles) between A[i;j] and A[i+1;j]
Protected Attributes
double * data
the matrix elements
Detailed Description
template<bool cplx>
class Bif_F12_DOMINO::Matrix< cplx >
Matrix is a helper class that makes a plain double * look like a real (cplx = false) or complex (cplx = true) matrix.
Definition at line 105 of file Bif_F12_DOMINO.hh.
Member Enumeration Documentation
anonymous enum
template<bool cplx> anonymous enum
Definition at line 108 of file Bif_F12_DOMINO.hh.
Constructor & Destructor Documentation
Matrix() [1/2]
template<bool cplx> Bif_F12_DOMINO::Matrix< cplx >::Matrix (double * pdata, ShapeItem uM, ShapeItem uN) inline
constructor: M×N matrix with the default vertical item spacings dY
Definition at line 117 of file Bif_F12_DOMINO.hh.
Matrix() [2/2]
template<bool cplx> Bif_F12_DOMINO::Matrix< cplx >::Matrix (double * pdata, ShapeItem uM, ShapeItem uN, ShapeItem udY) inline
constructor: M×1 matrix (aka. column vector) from a matrix column
Definition at line 126 of file Bif_F12_DOMINO.hh.
Member Function Documentation
abs2() [1/2]
double Bif_F12_DOMINO::Matrix< false >::abs2 (ShapeItem y, ShapeItem x) const inline
compute the square of the real item at row y, columns x
Definition at line 336 of file Bif_F12_DOMINO.hh.
abs2() [2/2]
double Bif_F12_DOMINO::Matrix< true >::abs2 (ShapeItem y, ShapeItem x) const inline
compute the square of the complex item at row y, columns x
Definition at line 345 of file Bif_F12_DOMINO.hh.
add_sub() [1/2]
void Bif_F12_DOMINO::Matrix< false >::add_sub (double * V11, const double * W11) inline
increase real *W11 by +/- real *V11
Definition at line 354 of file Bif_F12_DOMINO.hh.
add_sub() [2/2]
void Bif_F12_DOMINO::Matrix< true >::add_sub (double * V11, const double * W11) inline
increase complex *W11 by +/- complex *V11
Definition at line 365 of file Bif_F12_DOMINO.hh.
col1_norm() [1/2]
void Bif_F12_DOMINO::Matrix< false >::col1_norm (norm_result & result) const inline
compute norm variants of column 1 of this real marix
Definition at line 287 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::norm_result::norm2_imag, Bif_F12_DOMINO::norm_result::norm2_real, Bif_F12_DOMINO::norm_result::norm__2_imag, Bif_F12_DOMINO::norm_result::norm__2_real, Bif_F12_DOMINO::norm_result::norm_imag, and Bif_F12_DOMINO::norm_result::norm_real.
col1_norm() [2/2]
void Bif_F12_DOMINO::Matrix< true >::col1_norm (norm_result & result) const inline
compute norm variants of column 1 of this complex marix
Definition at line 308 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::norm_result::norm2_imag, Bif_F12_DOMINO::norm_result::norm2_real, Bif_F12_DOMINO::norm_result::norm__2_imag, Bif_F12_DOMINO::norm_result::norm__2_real, Bif_F12_DOMINO::norm_result::norm_imag, and Bif_F12_DOMINO::norm_result::norm_real.
debug() [1/2]
void Bif_F12_DOMINO::Matrix< false >::debug (const char * name) const
print debug infos for this real matrix
Definition at line 222 of file Bif_F12_DOMINO.cc.
References Bif_F12_FORMAT::format_by_specification().
debug() [2/2]
void Bif_F12_DOMINO::Matrix< true >::debug (const char * name) const
print debug infos for this complex matrix
Definition at line 245 of file Bif_F12_DOMINO.cc.
References Bif_F12_FORMAT::format_by_specification().
div_Z()
template<bool cplx> void Bif_F12_DOMINO::Matrix< cplx >::div_Z (ShapeItem y, ShapeItem x, complex< double > val) inline
divide the matrix element at row y, col x by val.
Definition at line 227 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::data, Bif_F12_DOMINO::Matrix< cplx >::dY, Bif_F12_DOMINO::Matrix< cplx >::M, and Bif_F12_DOMINO::Matrix< cplx >::N.
Referenced by Bif_F12_DOMINO::invert_upper_triangle_matrix().
drop_1_1()
template<bool cplx> double * Bif_F12_DOMINO::Matrix< cplx >::drop_1_1 () inline
return the elements of matrix 1 1↓this
Definition at line 169 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::data, Bif_F12_DOMINO::Matrix< cplx >::dY, Bif_F12_DOMINO::Matrix< cplx >::M, and Bif_F12_DOMINO::Matrix< cplx >::N.
Referenced by Bif_F12_DOMINO::householder().
get_Z()
template<bool cplx> complex< double > Bif_F12_DOMINO::Matrix< cplx >::get_Z (ShapeItem y, ShapeItem x) const inline
return the complex number at row y, column x of this matrix
Definition at line 198 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::data, Bif_F12_DOMINO::Matrix< cplx >::dY, Bif_F12_DOMINO::Matrix< cplx >::M, and Bif_F12_DOMINO::Matrix< cplx >::N.
Referenced by Bif_F12_DOMINO::invert_upper_triangle_matrix().
imag() [1/2]
template<bool cplx> double & Bif_F12_DOMINO::Matrix< cplx >::imag (ShapeItem y, ShapeItem x) inline
return the imaginary part of A[x;y]
Definition at line 182 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::data, Bif_F12_DOMINO::Matrix< cplx >::dY, Bif_F12_DOMINO::Matrix< cplx >::M, and Bif_F12_DOMINO::Matrix< cplx >::N.
Referenced by Bif_F12_DOMINO::Matrix< cplx >::init_inner_product(), Bif_F12_DOMINO::Matrix< cplx >::init_outer_product(), Bif_F12_DOMINO::invert_upper_triangle_matrix(), and Bif_F12_DOMINO::Matrix< cplx >::operator=().
imag() [2/2]
template<bool cplx> const double & Bif_F12_DOMINO::Matrix< cplx >::imag (ShapeItem y, ShapeItem x) const inline
return the imaginary part of A[x;y]
Definition at line 190 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::data, Bif_F12_DOMINO::Matrix< cplx >::dY, Bif_F12_DOMINO::Matrix< cplx >::M, and Bif_F12_DOMINO::Matrix< cplx >::N.
imbed() [1/2]
void Bif_F12_DOMINO::Matrix< false >::imbed (const Matrix< false > & S) inline
insert S into this real matrix
Definition at line 410 of file Bif_F12_DOMINO.hh.
imbed() [2/2]
void Bif_F12_DOMINO::Matrix< true >::imbed (const Matrix< true > & S) inline
insert S into this complex matrix
Definition at line 434 of file Bif_F12_DOMINO.hh.
init_identity() [1/2]
void Bif_F12_DOMINO::Matrix< false >::init_identity (ShapeItem rows) inline
increase complex *W11 by +/- *V11
Definition at line 377 of file Bif_F12_DOMINO.hh.
init_identity() [2/2]
void Bif_F12_DOMINO::Matrix< true >::init_identity (ShapeItem rows) inline
initialize this complex matrix to the unit matrix
Definition at line 393 of file Bif_F12_DOMINO.hh.
init_inner_product() [1/2]
void Bif_F12_DOMINO::Matrix< false >::init_inner_product (const Matrix< false > & src_A, const Matrix< false > & src_B) inline
set this matrix to A +.× B
Definition at line 559 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::M, Bif_F12_DOMINO::Matrix< cplx >::N, and Bif_F12_DOMINO::Matrix< cplx >::real().
init_inner_product() [2/2]
void Bif_F12_DOMINO::Matrix< true >::init_inner_product (const Matrix< true > & src_A, const Matrix< true > & src_B) inline
set this matrix to A +.× B
Definition at line 580 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::imag(), Bif_F12_DOMINO::Matrix< cplx >::M, Bif_F12_DOMINO::Matrix< cplx >::N, and Bif_F12_DOMINO::Matrix< cplx >::real().
init_outer_product() [1/2]
void Bif_F12_DOMINO::Matrix< false >::init_outer_product (const norm_result & scale, const Matrix< false > & src) inline
initialize this real matrix to be the outer product of the first column of the real matrix src with itself
Definition at line 469 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::norm_result::norm__2_real, and Bif_F12_DOMINO::Matrix< cplx >::real().
init_outer_product() [2/2]
void Bif_F12_DOMINO::Matrix< true >::init_outer_product (const norm_result & scale, const Matrix< true > & src) inline
initialize this complex matrix to be the outer product of the first column of the complex matrix src with itself
Definition at line 495 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::imag(), Bif_F12_DOMINO::norm_result::norm__2_imag, Bif_F12_DOMINO::norm_result::norm__2_real, and Bif_F12_DOMINO::Matrix< cplx >::real().
operator=() [1/2]
void Bif_F12_DOMINO::Matrix< false >::operator= (const Matrix< false > & src) inline
assign real matrix src to this real matrix
Definition at line 531 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::M, Bif_F12_DOMINO::Matrix< cplx >::N, and Bif_F12_DOMINO::Matrix< cplx >::real().
operator=() [2/2]
void Bif_F12_DOMINO::Matrix< true >::operator= (const Matrix< true > & src) inline
assign complex matrix src to this complex matrix
Definition at line 544 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::imag(), Bif_F12_DOMINO::Matrix< cplx >::M, Bif_F12_DOMINO::Matrix< cplx >::N, and Bif_F12_DOMINO::Matrix< cplx >::real().
real() [1/2]
template<bool cplx> double & Bif_F12_DOMINO::Matrix< cplx >::real (ShapeItem y, ShapeItem x) inline
return the real part of A[x;y]
Definition at line 138 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::data, Bif_F12_DOMINO::Matrix< cplx >::dY, Bif_F12_DOMINO::Matrix< cplx >::M, and Bif_F12_DOMINO::Matrix< cplx >::N.
Referenced by Bif_F12_DOMINO::householder(), Bif_F12_DOMINO::Matrix< cplx >::init_inner_product(), Bif_F12_DOMINO::Matrix< cplx >::init_outer_product(), Bif_F12_DOMINO::invert_upper_triangle_matrix(), and Bif_F12_DOMINO::Matrix< cplx >::operator=().
real() [2/2]
template<bool cplx> const double & Bif_F12_DOMINO::Matrix< cplx >::real (ShapeItem y, ShapeItem x) const inline
return the real part of A[x;y]
Definition at line 174 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::data, Bif_F12_DOMINO::Matrix< cplx >::dY, Bif_F12_DOMINO::Matrix< cplx >::M, and Bif_F12_DOMINO::Matrix< cplx >::N.
resize()
template<bool cplx> void Bif_F12_DOMINO::Matrix< cplx >::resize (ShapeItem M, ShapeItem N) inline
resize a (nulti-purpose) matrix to size M×N
Definition at line 134 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::data, Bif_F12_DOMINO::Matrix< cplx >::M, and Bif_F12_DOMINO::Matrix< cplx >::N.
Referenced by Bif_F12_DOMINO::householder().
set_Z()
template<bool cplx> void Bif_F12_DOMINO::Matrix< cplx >::set_Z (ShapeItem y, ShapeItem x, complex< double > val) inline
set the complex number at row y, column x of this matrix
Definition at line 207 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::data, Bif_F12_DOMINO::Matrix< cplx >::dY, Bif_F12_DOMINO::Matrix< cplx >::M, and Bif_F12_DOMINO::Matrix< cplx >::N.
Referenced by Bif_F12_DOMINO::invert_upper_triangle_matrix().
significant()
template<bool cplx> bool Bif_F12_DOMINO::Matrix< cplx >::significant (double bmax, double eps) const inline
true if this matrix is significant with respect to bmax and eps
Definition at line 239 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::abs2(), and Bif_F12_DOMINO::Matrix< cplx >::M.
Referenced by Bif_F12_DOMINO::householder().
sub_Z()
template<bool cplx> void Bif_F12_DOMINO::Matrix< cplx >::sub_Z (ShapeItem y, ShapeItem x, complex< double > val) inline
subtract val from the matrix element at row y, column x.
Definition at line 217 of file Bif_F12_DOMINO.hh.
References Bif_F12_DOMINO::Matrix< cplx >::data, Bif_F12_DOMINO::Matrix< cplx >::dY, Bif_F12_DOMINO::Matrix< cplx >::M, and Bif_F12_DOMINO::Matrix< cplx >::N.
Referenced by Bif_F12_DOMINO::invert_upper_triangle_matrix().
transpose() [1/2]
void Bif_F12_DOMINO::Matrix< false >::transpose (ShapeItem M) inline
transpose the upper left M×M submatrix of this real matrix
Definition at line 608 of file Bif_F12_DOMINO.hh.
transpose() [2/2]
void Bif_F12_DOMINO::Matrix< true >::transpose (ShapeItem M) inline
transpose the upper left M×M submatrix of this complex matrix
Definition at line 620 of file Bif_F12_DOMINO.hh.
Member Data Documentation
data
template<bool cplx> double* Bif_F12_DOMINO::Matrix< cplx >::data protected
the matrix elements
Definition at line 269 of file Bif_F12_DOMINO.hh.
Referenced by Bif_F12_DOMINO::Matrix< cplx >::div_Z(), Bif_F12_DOMINO::Matrix< cplx >::drop_1_1(), Bif_F12_DOMINO::Matrix< cplx >::get_Z(), Bif_F12_DOMINO::Matrix< cplx >::imag(), Bif_F12_DOMINO::Matrix< cplx >::real(), Bif_F12_DOMINO::Matrix< cplx >::resize(), Bif_F12_DOMINO::Matrix< cplx >::set_Z(), and Bif_F12_DOMINO::Matrix< cplx >::sub_Z().
dY
template<bool cplx> const ShapeItem Bif_F12_DOMINO::Matrix< cplx >::dY
the distance (in doubles) between A[i;j] and A[i+1;j]
Definition at line 279 of file Bif_F12_DOMINO.hh.
Referenced by Bif_F12_DOMINO::Matrix< cplx >::div_Z(), Bif_F12_DOMINO::Matrix< cplx >::drop_1_1(), Bif_F12_DOMINO::Matrix< cplx >::get_Z(), Bif_F12_DOMINO::householder(), Bif_F12_DOMINO::Matrix< cplx >::imag(), Bif_F12_DOMINO::Matrix< cplx >::real(), Bif_F12_DOMINO::Matrix< cplx >::set_Z(), and Bif_F12_DOMINO::Matrix< cplx >::sub_Z().
M
template<bool cplx> const ShapeItem Bif_F12_DOMINO::Matrix< cplx >::M
the number of matrix rows
Definition at line 273 of file Bif_F12_DOMINO.hh.
Referenced by Bif_F12_DOMINO::Matrix< cplx >::div_Z(), Bif_F12_DOMINO::Matrix< cplx >::drop_1_1(), Bif_F12_DOMINO::Matrix< cplx >::get_Z(), Bif_F12_DOMINO::householder(), Bif_F12_DOMINO::Matrix< cplx >::imag(), Bif_F12_DOMINO::Matrix< cplx >::init_inner_product(), Bif_F12_DOMINO::Matrix< cplx >::operator=(), Bif_F12_DOMINO::Matrix< cplx >::real(), Bif_F12_DOMINO::Matrix< cplx >::resize(), Bif_F12_DOMINO::Matrix< cplx >::set_Z(), Bif_F12_DOMINO::Matrix< cplx >::significant(), and Bif_F12_DOMINO::Matrix< cplx >::sub_Z().
N
template<bool cplx> const ShapeItem Bif_F12_DOMINO::Matrix< cplx >::N
the number of matrix columns
Definition at line 276 of file Bif_F12_DOMINO.hh.
Referenced by Bif_F12_DOMINO::Matrix< cplx >::div_Z(), Bif_F12_DOMINO::Matrix< cplx >::drop_1_1(), Bif_F12_DOMINO::Matrix< cplx >::get_Z(), Bif_F12_DOMINO::householder(), Bif_F12_DOMINO::Matrix< cplx >::imag(), Bif_F12_DOMINO::Matrix< cplx >::init_inner_product(), Bif_F12_DOMINO::Matrix< cplx >::operator=(), Bif_F12_DOMINO::Matrix< cplx >::real(), Bif_F12_DOMINO::Matrix< cplx >::resize(), Bif_F12_DOMINO::Matrix< cplx >::set_Z(), and Bif_F12_DOMINO::Matrix< cplx >::sub_Z().
The documentation for this class was generated from the following file:
src/Bif_F12_DOMINO.hh