GNU APL: NamedObject Class Reference
NamedObject Class Reference
A user-defined variable or function.
#include <NamedObject.hh>
Public Member Functions
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Public Attributes
const Id id
the object's id
Detailed Description
A user-defined variable or function.
A named object is something with a name. The name can be user defined or system defined.
User define names are handled by class Symbol, while system defined names are handled by class Id.
User define names are used for (user-defined) variables, functions, or operators.
System names are used by system variables and functions (⎕xx) and for primitive functions and operators.
Definition at line 69 of file NamedObject.hh.
Constructor & Destructor Documentation
NamedObject()
NamedObject::NamedObject (Id i) inline
constructor from Id
Definition at line 73 of file NamedObject.hh.
Member Function Documentation
get_function()
virtual const Function * NamedObject::get_function () const inline virtual
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
Reimplemented in Function, and Symbol.
Definition at line 83 of file NamedObject.hh.
Referenced by Quad_CR::do_eval_B(), Quad_AT::eval_AB(), Quad_TF::tf1(), Quad_TF::tf2(), and Quad_TF::tf3().
get_Id()
Id NamedObject::get_Id () const inline
return the Id of this object (ID_USER_SYMBOL for user defined objects)
Definition at line 94 of file NamedObject.hh.
References id.
Referenced by SystemVariable::assign(), SystemVariable::assign_indexed(), SystemVariable::get_token(), Workspace::is_called(), PrimitiveFunction::print(), SystemVariable::print(), XML_Loading_Archive::read_Variable(), XML_Saving_Archive::save_Function(), XML_Saving_Archive::save_Function_name(), and Workspace::write_OUT().
get_name()
virtual UCS_string NamedObject::get_name () const inline virtual
return the name of the named object
Reimplemented in NativeFunction, Symbol, and UserFunction.
Definition at line 78 of file NamedObject.hh.
References ID::get_name_UCS().
Referenced by DerivedFunction::destroy_derived(), Quad_FX::do_quad_FX(), Function::eval_(), Function::eval_AB(), Function::eval_ALB(), Function::eval_ALRB(), Function::eval_B(), Function::eval_fill_AB(), Function::eval_identity_fun(), Function::eval_LB(), Function::eval_LRB(), get_NC(), Bif_REDUCE::reduce_n_wise(), and Bif_SCAN::scan().
get_NC()
NameClass NamedObject::get_NC () const
Get current NameClass of this name.
Definition at line 29 of file NamedObject.cc.
References Token::get_Class(), get_name(), Workspace::get_quad(), get_symbol(), and Avec::is_quad().
Referenced by Quad_CR::do_CR10(), Quad_NL::do_quad_NL(), Nabla::edit_header_line(), Quad_SVO::eval_AB(), Quad_SVO::eval_B(), Quad_NC::eval_B(), Symbol::get_function(), Quad_NC::get_NC(), Symbol::get_value(), Workspace::is_called(), Prefix::is_value_parenthesis(), Workspace::lookup_existing_name(), Prefix::MM_is_FM(), Symbol::pop(), Prefix::reduce_statements(), Nabla::start(), Quad_TF::tf1_inv(), Prefix::value_expected(), and Symbol::write_OUT().
get_symbol() [1/2]
virtual Symbol * NamedObject::get_symbol () inline virtual
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Reimplemented in Symbol.
Definition at line 87 of file NamedObject.hh.
Referenced by Quad_AT::eval_AB(), get_NC(), Quad_TF::tf1(), Quad_TF::tf1_inv(), Quad_TF::tf2(), Quad_TF::tf3(), and Workspace::write_OUT().
get_symbol() [2/2]
virtual const Symbol * NamedObject::get_symbol () const inline virtual
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Reimplemented in Symbol.
Definition at line 91 of file NamedObject.hh.
is_user_defined()
bool NamedObject::is_user_defined () const inline
return true, iff this object is user-defined
Definition at line 98 of file NamedObject.hh.
Referenced by SymbolTable::clear_slot(), Quad_CR::do_eval_B(), Quad_TF::tf1(), and Quad_TF::tf2().
Member Data Documentation
id
const Id NamedObject::id
the object's id
Definition at line 105 of file NamedObject.hh.
Referenced by get_Id().
The documentation for this class was generated from the following files:
src/NamedObject.hh
src/NamedObject.cc