GNU APL: ScalarFunction Class Reference
ScalarFunction Class Reference abstract
Base class for all scalar functions.
#include <ScalarFunction.hh>
Protected Member Functions
ScalarFunction (TokenTag tag, CellFunctionStatistics *stat_AB, CellFunctionStatistics *stat_B, ShapeItem thresh_AB, ShapeItem thresh_B)
Construct a ScalarFunction with Id id.
Token eval_scalar_B (Value_P B, prim_f1 fun) const
Evaluate a scalar function monadically.
Token eval_scalar_AB (Value_P A, Value_P B, prim_f2 fun) const
Evaluate a scalar function dyadically.
virtual prim_f2 get_scalar_f2 () const =0
overloaded Function::get_scalar_f2
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual bool has_result () const
overloaded Function::has_result()
virtual bool may_parallel () const
return true if this function can be parallelized
Value_P do_scalar_B (ErrorCode &ec, Value_P B, prim_f1 fun) const
compute the monadic scalar function fun along one ravel
Value_P do_scalar_AB (ErrorCode &ec, Value_P A, Value_P B, prim_f2 fun) const
compute the dyadic scalar function fun along one ravel
void expand_nested (Value *Z, const Cell *cell_A, const Cell *cell_B, prim_f2 fun) const
compute cell_A fun cell_B, scalar-extending PointerCells
Token eval_scalar_AXB (Value_P A, Value_P X, Value_P B, prim_f2 fun) const
Evaluate a scalar function dyadically with axis.
Value_P eval_scalar_AXB (Value_P A, AxesBitmap axes_in_X, Value_P B, prim_f2 fun, bool reversed) const
A helper function for eval_scalar_AXB().
Token do_eval_fill_AB (const Value_P A, const Value_P B) const
A helper function for eval_fill_AB().
Token do_eval_fill_B (const Value_P B) const
A helper function for eval_fill_B().
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Static Protected Member Functions
static Token eval_scalar_identity_fun (Value_P B, sAxis axis, const Cell &FI0)
Evaluate the identity function.
static const Shape * conforming_shape (ErrorCode &ec, const Shape &sh_A, const Shape &sh_B)
return the conforming shape of sh_A and sh_A, or set ec and return 0 if shapes cannot be conformed. RANK ERROR or LENGTH ERROR if the dont.
Static Protected Attributes
static Thread_context::PoolFunction PF_scalar_AB
parallel eval_scalar_AB
static Thread_context::PoolFunction PF_scalar_B
parallel eval_scalar_B
static const IntCell integer_0
0 (for eval_scalar_identity_fun)
static const IntCell integer_1
1 (for eval_scalar_identity_fun)
static const FloatCell float_min
-BIG_FLOAT (for eval_scalar_identity_fun)
static const FloatCell float_max
BIG_FLOAT (for eval_scalar_identity_fun)
Additional Inherited Members
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
virtual bool has_result () const
overloaded Function::has_result()
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
Base class for all scalar functions.
Definition at line 33 of file ScalarFunction.hh.
Constructor & Destructor Documentation
ScalarFunction()
ScalarFunction::ScalarFunction (TokenTag tag, CellFunctionStatistics * stat_AB, CellFunctionStatistics * stat_B, ShapeItem thresh_AB, ShapeItem thresh_B) inline protected
Construct a ScalarFunction with Id id.
Definition at line 41 of file ScalarFunction.hh.
References Function::set_dyadic_threshold(), and Function::set_monadic_threshold().
Member Function Documentation
conforming_shape()
const Shape * ScalarFunction::conforming_shape (ErrorCode & ec, const Shape & sh_A, const Shape & sh_B) static protected
return the conforming shape of sh_A and sh_A, or set ec and return 0 if shapes cannot be conformed. RANK ERROR or LENGTH ERROR if the dont.
Definition at line 909 of file ScalarFunction.cc.
References Shape::get_rank(), and Shape::get_volume().
Referenced by do_scalar_AB().
do_eval_fill_AB()
Token ScalarFunction::do_eval_fill_AB (const Value_P A, const Value_P B) const protected
A helper function for eval_fill_AB().
Definition at line 671 of file ScalarFunction.cc.
References do_eval_fill_B().
Referenced by do_scalar_AB(), and eval_fill_AB().
do_eval_fill_B()
Token ScalarFunction::do_eval_fill_B (const Value_P B) const protected
A helper function for eval_fill_B().
Definition at line 720 of file ScalarFunction.cc.
Referenced by do_eval_fill_AB(), do_scalar_AB(), eval_fill_B(), and eval_scalar_B().
do_scalar_AB()
Value_P ScalarFunction::do_scalar_AB (ErrorCode & ec, Value_P A, Value_P B, prim_f2 fun) const protected
compute the dyadic scalar function fun along one ravel
Definition at line 371 of file ScalarFunction.cc.
References PJob_scalar_AB::A_at(), Parallel_job_list< T, has_destructor >::add_job(), PJob_scalar_AB::B_at(), conforming_shape(), do_eval_fill_AB(), do_eval_fill_B(), Thread_context::do_work, PJob_scalar_AB::error, PJob_scalar_AB::fun, PJob_scalar_AB::fun2, Value_P_Base::get(), Thread_context::get_active_core_count(), Token::get_apl_val(), Thread_context::get_context(), Function::get_dyadic_threshold(), Thread_context::get_master(), Cell::get_pointer_value(), PrimitiveFunction::get_statistics_AB(), Shape::get_volume(), Cell::is_pointer_cell(), Thread_context::joblist_AB, PJob_scalar_AB::len_Z, Thread_context::M_fork(), Thread_context::M_join(), Parallel_job_list< T, has_destructor >::next_job(), PF_scalar_AB, Parallel::run_parallel, Parallel_job_list< T, has_destructor >::start(), PJob_scalar_AB::value_Z, PJob_scalar_AB::Z_at(), and PJob_scalar_AB::~PJob_scalar_AB().
Referenced by eval_scalar_AB().
do_scalar_B()
Value_P ScalarFunction::do_scalar_B (ErrorCode & ec, Value_P B, prim_f1 fun) const protected
compute the monadic scalar function fun along one ravel
Definition at line 153 of file ScalarFunction.cc.
References Parallel_job_list< T, has_destructor >::add_job(), PJob_scalar_B::B_at(), Thread_context::do_work, PJob_scalar_B::error, PJob_scalar_B::fun, PJob_scalar_B::fun1, Value_P_Base::get(), Thread_context::get_active_core_count(), Thread_context::get_context(), Thread_context::get_master(), Function::get_monadic_threshold(), Cell::get_pointer_value(), PrimitiveFunction::get_statistics_B(), Cell::is_pointer_cell(), Thread_context::joblist_B, PJob_scalar_B::len_Z, Thread_context::M_fork(), Thread_context::M_join(), may_parallel(), Parallel_job_list< T, has_destructor >::next_job(), PF_scalar_B, Parallel::run_parallel, Parallel_job_list< T, has_destructor >::start(), PJob_scalar_B::value_Z, PJob_scalar_B::Z_at(), and PJob_scalar_B::~PJob_scalar_B().
Referenced by eval_scalar_B().
eval_fill_AB()
virtual Token ScalarFunction::eval_fill_AB (Value_P A, Value_P B) const inline protected virtual
overloaded Function::eval_fill_AB()
Reimplemented from PrimitiveFunction.
Definition at line 61 of file ScalarFunction.hh.
References do_eval_fill_AB().
eval_fill_B()
virtual Token ScalarFunction::eval_fill_B (Value_P B) const inline protected virtual
overloaded Function::eval_fill_B()
Reimplemented from PrimitiveFunction.
Definition at line 65 of file ScalarFunction.hh.
References do_eval_fill_B().
eval_scalar_AB()
Token ScalarFunction::eval_scalar_AB (Value_P A, Value_P B, prim_f2 fun) const protected
Evaluate a scalar function dyadically.
Definition at line 349 of file ScalarFunction.cc.
References Thread_context::cancel_all_dyadic_jobs(), do_scalar_AB(), Thread_context::get_active_core_count(), and Thread_context::get_context().
Referenced by Bif_F12_BINOM::eval_AB(), Bif_F2_LESS::eval_AB(), Bif_F2_EQUAL::eval_AB(), Bif_F2_EQUAL_B::eval_AB(), Bif_F2_UNEQ_B::eval_AB(), Bif_F2_GREATER::eval_AB(), Bif_F2_AND::eval_AB(), Bif_F2_AND_B::eval_AB(), Bif_F2_OR::eval_AB(), Bif_F2_OR_B::eval_AB(), Bif_F2_LEQU::eval_AB(), Bif_F2_MEQU::eval_AB(), Bif_F2_UNEQU::eval_AB(), Bif_F2_NOR::eval_AB(), Bif_F2_NOR_B::eval_AB(), Bif_F2_NAND::eval_AB(), Bif_F2_NAND_B::eval_AB(), Bif_F12_POWER::eval_AB(), Bif_F12_PLUS::eval_AB(), Bif_F12_MINUS::eval_AB(), Bif_F12_TIMES::eval_AB(), Bif_F12_DIVIDE::eval_AB(), Bif_F12_CIRCLE::eval_AB(), Bif_F12_RND_UP::eval_AB(), Bif_F12_RND_DN::eval_AB(), Bif_F12_STILE::eval_AB(), Bif_F12_LOGA::eval_AB(), eval_scalar_AXB(), and expand_nested().
eval_scalar_AXB() [1/2]
Value_P ScalarFunction::eval_scalar_AXB (Value_P A, AxesBitmap axes_in_X, Value_P B, prim_f2 fun, bool reversed) const protected
A helper function for eval_scalar_AXB().
Definition at line 849 of file ScalarFunction.cc.
References expand_nested(), Value_P_Base::get(), Shape::get_shape_item(), and ArrayIterator::more().
eval_scalar_AXB() [2/2]
Token ScalarFunction::eval_scalar_AXB (Value_P A, Value_P X, Value_P B, prim_f2 fun) const protected
Evaluate a scalar function dyadically with axis.
Definition at line 782 of file ScalarFunction.cc.
References eval_scalar_AB(), eval_scalar_AXB(), and Workspace::get_IO().
Referenced by Bif_F12_BINOM::eval_AXB(), Bif_F2_LESS::eval_AXB(), Bif_F2_EQUAL::eval_AXB(), Bif_F2_EQUAL_B::eval_AXB(), Bif_F2_UNEQ_B::eval_AXB(), Bif_F2_GREATER::eval_AXB(), Bif_F2_AND::eval_AXB(), Bif_F2_AND_B::eval_AXB(), Bif_F2_OR::eval_AXB(), Bif_F2_OR_B::eval_AXB(), Bif_F2_LEQU::eval_AXB(), Bif_F2_MEQU::eval_AXB(), Bif_F2_UNEQU::eval_AXB(), Bif_F2_NOR::eval_AXB(), Bif_F2_NOR_B::eval_AXB(), Bif_F2_NAND::eval_AXB(), Bif_F2_NAND_B::eval_AXB(), Bif_F12_POWER::eval_AXB(), Bif_F12_PLUS::eval_AXB(), Bif_F12_MINUS::eval_AXB(), Bif_F12_TIMES::eval_AXB(), Bif_F12_DIVIDE::eval_AXB(), Bif_F12_RND_UP::eval_AXB(), Bif_F12_RND_DN::eval_AXB(), Bif_F12_STILE::eval_AXB(), Bif_F12_LOGA::eval_AXB(), and eval_scalar_AXB().
eval_scalar_B()
Token ScalarFunction::eval_scalar_B (Value_P B, prim_f1 fun) const protected
Evaluate a scalar function monadically.
Definition at line 128 of file ScalarFunction.cc.
References Thread_context::cancel_all_monadic_jobs(), do_eval_fill_B(), do_scalar_B(), Thread_context::get_active_core_count(), and Thread_context::get_context().
Referenced by Bif_F12_BINOM::eval_B(), Bif_F2_AND_B::eval_B(), Bif_F2_OR_B::eval_B(), Bif_F2_NOR_B::eval_B(), Bif_F12_POWER::eval_B(), Bif_F12_PLUS::eval_B(), Bif_F12_MINUS::eval_B(), Bif_F12_ROLL::eval_B(), Bif_F12_WITHOUT::eval_B(), Bif_F12_TIMES::eval_B(), Bif_F12_DIVIDE::eval_B(), Bif_F12_CIRCLE::eval_B(), Bif_F12_RND_UP::eval_B(), Bif_F12_RND_DN::eval_B(), Bif_F12_STILE::eval_B(), and Bif_F12_LOGA::eval_B().
eval_scalar_identity_fun()
Token ScalarFunction::eval_scalar_identity_fun (Value_P B, sAxis axis, const Cell & FI0) static protected
Evaluate the identity function.
Definition at line 751 of file ScalarFunction.cc.
Referenced by Bif_F12_BINOM::eval_identity_fun(), Bif_F2_LESS::eval_identity_fun(), Bif_F2_EQUAL::eval_identity_fun(), Bif_F2_EQUAL_B::eval_identity_fun(), Bif_F2_UNEQ_B::eval_identity_fun(), Bif_F2_GREATER::eval_identity_fun(), Bif_F2_AND::eval_identity_fun(), Bif_F2_AND_B::eval_identity_fun(), Bif_F2_OR::eval_identity_fun(), Bif_F2_OR_B::eval_identity_fun(), Bif_F2_LEQU::eval_identity_fun(), Bif_F2_MEQU::eval_identity_fun(), Bif_F2_UNEQU::eval_identity_fun(), Bif_F12_POWER::eval_identity_fun(), Bif_F12_PLUS::eval_identity_fun(), Bif_F12_MINUS::eval_identity_fun(), Bif_F12_TIMES::eval_identity_fun(), Bif_F12_DIVIDE::eval_identity_fun(), Bif_F12_RND_UP::eval_identity_fun(), Bif_F12_RND_DN::eval_identity_fun(), and Bif_F12_STILE::eval_identity_fun().
expand_nested()
void ScalarFunction::expand_nested (Value * Z, const Cell * cell_A, const Cell * cell_B, prim_f2 fun) const protected
compute cell_A fun cell_B, scalar-extending PointerCells
Definition at line 310 of file ScalarFunction.cc.
References eval_scalar_AB(), Value_P_Base::get(), Token::get_apl_val(), Cell::get_pointer_value(), Value::get_valid_item_count(), Value::get_wravel(), Cell::is_pointer_cell(), Value::next_ravel_0(), and Value::next_ravel_Pointer().
Referenced by eval_scalar_AXB().
get_scalar_f2()
virtual prim_f2 ScalarFunction::get_scalar_f2 () const protected pure virtual
overloaded Function::get_scalar_f2
Reimplemented from Function.
Implemented in Bif_F12_BINOM, Bif_F2_LESS, Bif_F2_EQUAL, Bif_F2_EQUAL_B, Bif_F2_UNEQ_B, Bif_F2_GREATER, Bif_F2_AND, Bif_F2_AND_B, Bif_F2_OR, Bif_F2_OR_B, Bif_F2_LEQU, Bif_F2_MEQU, Bif_F2_UNEQU, Bif_F2_FIND, Bif_F2_NOR, Bif_F2_NOR_B, Bif_F2_NAND, Bif_F2_NAND_B, Bif_F12_POWER, Bif_F12_PLUS, Bif_F12_MINUS, Bif_F12_ROLL, Bif_F12_WITHOUT, Bif_F12_TIMES, Bif_F12_DIVIDE, Bif_F12_CIRCLE, Bif_F12_RND_UP, Bif_F12_RND_DN, Bif_F12_STILE, and Bif_F12_LOGA.
has_result()
virtual bool ScalarFunction::has_result () const inline protected virtual
overloaded Function::has_result()
Reimplemented from PrimitiveFunction.
Definition at line 69 of file ScalarFunction.hh.
may_parallel()
virtual bool ScalarFunction::may_parallel () const inline protected virtual
return true if this function can be parallelized
Reimplemented in Bif_F2_FIND, Bif_F12_ROLL, and Bif_F12_WITHOUT.
Definition at line 72 of file ScalarFunction.hh.
Referenced by do_scalar_B().
Member Data Documentation
float_max
const FloatCell ScalarFunction::float_max static protected
BIG_FLOAT (for eval_scalar_identity_fun)
Definition at line 118 of file ScalarFunction.hh.
Referenced by Bif_F12_RND_DN::eval_identity_fun().
float_min
const FloatCell ScalarFunction::float_min static protected
-BIG_FLOAT (for eval_scalar_identity_fun)
Definition at line 115 of file ScalarFunction.hh.
Referenced by Bif_F12_RND_UP::eval_identity_fun().
integer_0
const IntCell ScalarFunction::integer_0 static protected
0 (for eval_scalar_identity_fun)
Definition at line 109 of file ScalarFunction.hh.
Referenced by Bif_F2_LESS::eval_identity_fun(), Bif_F2_GREATER::eval_identity_fun(), Bif_F2_OR::eval_identity_fun(), Bif_F2_OR_B::eval_identity_fun(), Bif_F2_UNEQU::eval_identity_fun(), Bif_F12_PLUS::eval_identity_fun(), Bif_F12_MINUS::eval_identity_fun(), and Bif_F12_STILE::eval_identity_fun().
integer_1
const IntCell ScalarFunction::integer_1 static protected
1 (for eval_scalar_identity_fun)
Definition at line 112 of file ScalarFunction.hh.
Referenced by Bif_F12_BINOM::eval_identity_fun(), Bif_F2_EQUAL::eval_identity_fun(), Bif_F2_EQUAL_B::eval_identity_fun(), Bif_F2_UNEQ_B::eval_identity_fun(), Bif_F2_AND::eval_identity_fun(), Bif_F2_AND_B::eval_identity_fun(), Bif_F2_LEQU::eval_identity_fun(), Bif_F2_MEQU::eval_identity_fun(), Bif_F12_POWER::eval_identity_fun(), Bif_F12_TIMES::eval_identity_fun(), and Bif_F12_DIVIDE::eval_identity_fun().
PF_scalar_AB
void ScalarFunction::PF_scalar_AB static protected
parallel eval_scalar_AB
Definition at line 103 of file ScalarFunction.hh.
Referenced by do_scalar_AB().
PF_scalar_B
void ScalarFunction::PF_scalar_B static protected
parallel eval_scalar_B
Definition at line 106 of file ScalarFunction.hh.
Referenced by do_scalar_B().
The documentation for this class was generated from the following files:
src/ScalarFunction.hh
src/ScalarFunction.cc