GNU APL: Sig_item_xint< T, bytes > Class Template Reference
Sig_item_xint< T, bytes > Class Template Reference
a hexadecimal integer signal item of size bytes
#include <Svar_signals.hh>
Public Member Functions
Sig_item_xint (T v)
construct an item with value v
Sig_item_xint (const uint8_t *&buffer)
construct (deserialize) this item from a (received) buffer
ostream & print (ostream &out) const
print the item
Public Member Functions inherited from Sig_item_int< T, bytes >
Sig_item_int (T v)
construct an item with value v
Sig_item_int (const uint8_t *&buffer)
construct (deserialize) this item from a (received) buffer
T get_svalue () const
return the value of the item
void store (string &buffer) const
store (aka. serialize) this item into a string
ostream & print (ostream &out) const
print the item
Additional Inherited Members
Static Public Member Functions inherited from Sig_item_int< T, bytes >
static uint64_t get_mask ()
return the mask of the item, e.g. 0x00FFFFFF for a 3-byte integer
Public Attributes inherited from Sig_item_int< T, bytes >
T value
the value of the item
Detailed Description
template<typename T, int bytes>
class Sig_item_xint< T, bytes >
a hexadecimal integer signal item of size bytes
Definition at line 136 of file Svar_signals.hh.
Constructor & Destructor Documentation
Sig_item_xint() [1/2]
template<typename T , int bytes> Sig_item_xint< T, bytes >::Sig_item_xint (T v) inline
construct an item with value v
Definition at line 140 of file Svar_signals.hh.
Sig_item_xint() [2/2]
template<typename T , int bytes> Sig_item_xint< T, bytes >::Sig_item_xint (const uint8_t *& buffer) inline
construct (deserialize) this item from a (received) buffer
Definition at line 143 of file Svar_signals.hh.
Member Function Documentation
print()
template<typename T , int bytes> ostream & Sig_item_xint< T, bytes >::print (ostream & out) const inline
print the item
Definition at line 146 of file Svar_signals.hh.
Referenced by MAKE_OFFER_c::print(), RETRACT_OFFER_c::print(), RETRACT_VAR_c::print(), SET_STATE_c::print(), SET_CONTROL_c::print(), GET_VALUE_c::print(), VALUE_IS_c::print(), ASSIGN_VALUE_c::print(), SVAR_ASSIGNED_c::print(), MAY_USE_c::print(), MAY_SET_c::print(), READ_SVAR_RECORD_c::print(), MATCH_OR_MAKE_RESULT_c::print(), FIND_OFFERING_ID_c::print(), FIND_PAIRING_KEY_c::print(), PAIRING_KEY_IS_c::print(), EVENTS_ARE_c::print(), ADD_EVENT_c::print(), ASSIGN_WSWS_VAR_c::print(), and READ_WSWS_VAR_c::print().
The documentation for this class was generated from the following file:
src/Svar_signals.hh