GNU APL: Cell Class Reference
Cell Class Reference
The base class for all Cells.
#include <Cell.hh>
Classes
union SomeValue
A union containing all possible cell values for the different Cell types.
Public Member Functions
Cell ()
Construct an un-initialized Cell.
void init (const Cell &other, Value &this_owner, const char *loc)
init this Cell from a (possibly deep) copy of other
virtual void init_other (void *other, Value &other_owner, const char *loc) const
init (uninitialized) Cell other from this initialized cell
void init_from_value (Value *value, Value &cell_owner, const char *loc)
init this Cell from value. If value is a scalar then its first element is used (and value is erased). Otherwise a PointerCell is created.
virtual bool greater (const Cell &other) const
Return true if this cell is greater than other, with:
virtual bool equal (const Cell &other, double qct) const
return true if this cell is equal to other
Value_P to_value (const char *loc) const
return pointer value of a PointerCell or create a scalar with a copy of this cell.
void init_type (const Cell &other, Value &cell_owner, const char *loc)
init this cell to be the type of other
virtual Unicode get_char_value () const
Return the character value of a cell.
virtual int get_byte_value () const
Return the byte value (-128..255 incl) of a cell.
virtual APL_Integer get_int_value () const
Return the integer value of a cell.
virtual APL_Float get_real_value () const
Return the real part of a cell.
virtual APL_Float get_imag_value () const
Return the imaginary part of a cell.
virtual APL_Complex get_complex_value () const
Return the complex value of a cell.
virtual Value_P get_pointer_value () const
Return the APL value of a cell (Asserts for non-pointer cells)
virtual Cell * get_lval_value () const
Return the APL value of a cell (Asserts for non-lval cells)
virtual PrintBuffer character_representation (const PrintContext &pctx) const
the Quad_CR representation of this cell
virtual bool need_scaling (const PrintContext &pctx) const
return true if this cell needs scaling (exponential format) in pctx
virtual bool get_near_bool () const
Return value if it is close to boolean, or else throw DOMAIN_ERROR.
virtual APL_Integer get_near_int () const
Return value if it is close to int, or else throw DOMAIN_ERROR.
virtual APL_Integer get_checked_near_int () const
Return value if it is (known to be) close to int, or else Assert()
virtual bool is_near_zero () const
return true iff value is numeric and close to 0
virtual bool is_near_one () const
return true iff value is numeric and close to 1
bool is_near_bool () const
return true iff value is numeric and close to 0 or 1
virtual bool is_near_int () const
True iff value is numeric and close to an int.
virtual bool is_near_int64_t () const
True iff value is numeric and close to an int.
virtual bool is_near_real () const
return true iff value is numeric and close to a real number
virtual int CDR_size () const
return the minimum number of data bytes to store this cell in CDR format. The actual number of data bytes can be bigger if other cells need more bytes,
virtual void release (const char *loc)
Release content pointed to (complex, APL value)
virtual bool is_integer_cell () const
Return true iff this cell is an integer cell.
bool is_simple_cell () const
Return true iff this cell is a numeric cor character cell.
virtual bool is_float_cell () const
Return true iff this cell is a floating point cell.
virtual bool is_character_cell () const
Return true iff this cell is a character cell.
virtual bool is_pointer_cell () const
Return true iff this cell is a pointer (to a sub-array) cell.
virtual bool is_lval_cell () const
Return true iff this cell is a pointer to a cell.
virtual bool is_picked_lval_cell () const
Return true iff this cell is a pointer to a cell from pick()
virtual bool is_complex_cell () const
Return true iff this cell is a complex number cell.
virtual bool is_numeric () const
Return true iff this cell is an integer, float, or complex cell.
virtual bool is_real_cell () const
Return true iff this cell is an integer or float cell.
virtual bool is_finite () const
Return true unless this cell contains infinity or NaN.
virtual bool is_example_field () const
Return true iff this cell is an example field character cell.
virtual bool is_member_anchor () const
Return true iff this is a PointerCell which pouints to a member value.
virtual CellType get_cell_type () const
return the type of this cell
virtual CellType get_cell_subtype () const
return the subtype of this cell. The subtype is the set of containers that can store the cell (only for Int and Char cells).
virtual const char * get_classname () const
return the name of the class
virtual ErrorCode bif_ceiling (Cell *Z) const
round the value of this Cell up and store the result in Z
virtual ErrorCode bif_conjugate (Cell *Z) const
conjugate the value of this Cell and store the result in Z
virtual ErrorCode bif_direction (Cell *Z) const
store the direction (sign) of this Cell in Z
virtual ErrorCode bif_exponential (Cell *Z) const
store e to the power of the value of this Cell in Z
virtual ErrorCode bif_factorial (Cell *Z) const
store the factorial (N!) of the value of this Cell in Z
virtual ErrorCode bif_floor (Cell *Z) const
Round the value of this Cell down and store the result in Z.
virtual ErrorCode bif_magnitude (Cell *Z) const
store the absolute value of this Cell in Z
virtual ErrorCode bif_nat_log (Cell *Z) const
store the base e logarithm of the value of this Cell in Z
virtual ErrorCode bif_negative (Cell *Z) const
store the negative of the value of this Cell in Z
virtual ErrorCode bif_not (Cell *Z) const
store the logical complement of the value of this Cell in Z
virtual ErrorCode bif_not_bitwise (Cell *Z) const
store the bitwise complement of the value of this Cell in Z
virtual ErrorCode bif_near_int64_t (Cell *Z) const
store the nearby integer of the value of this Cell in Z
virtual ErrorCode bif_within_quad_CT (Cell *Z) const
store the nearby integer of the value of this Cell in Z
virtual ErrorCode bif_pi_times (Cell *Z) const
store pi times the value of this Cell in Z
virtual ErrorCode bif_pi_times_inverse (Cell *Z) const
store pi times the value of this Cell in Z
virtual ErrorCode bif_reciprocal (Cell *Z) const
store the reciprocal of the value of this Cell in Z
virtual ErrorCode bif_roll (Cell *Z) const
store a random number between 1 and the value of this Cell in Z
virtual ErrorCode bif_add (Cell *Z, const Cell *A) const
store the sum of A and this cell in Z
virtual ErrorCode bif_and (Cell *Z, const Cell *A) const
store the logical and of A and this cell in Z
virtual ErrorCode bif_and_bitwise (Cell *Z, const Cell *A) const
store the bitwise and of A and this cell in Z
virtual ErrorCode bif_binomial (Cell *Z, const Cell *A) const
store the binomial (n over k) of A and this cell in Z
virtual ErrorCode bif_subtract (Cell *Z, const Cell *A) const
store the difference between A and this cell in Z
virtual ErrorCode bif_divide (Cell *Z, const Cell *A) const
store the quotient between A and this cell in Z
virtual Comp_result compare (const Cell &other) const
compare this with other, throw DOMAIN ERROR on illegal comparisons
ErrorCode bif_equal (Cell *Z, const Cell *A) const
store 1 in Z if A == the value of this cell in Z, else 0
virtual ErrorCode bif_equal_bitwise (Cell *Z, const Cell *A) const
bitwise comparison of *this and A
virtual ErrorCode bif_not_equal_bitwise (Cell *Z, const Cell *A) const
bitwise comparison of *this and A
ErrorCode bif_not_equal (Cell *Z, const Cell *A) const
store 1 in Z if A != the value of this cell in Z, else 0
ErrorCode bif_greater_than (Cell *Z, const Cell *A) const
store 1 in Z if A > the value of this cell in Z, else 0
ErrorCode bif_less_eq (Cell *Z, const Cell *A) const
store 1 in Z if A <= the value of this cell in Z, else 0
ErrorCode bif_less_than (Cell *Z, const Cell *A) const
store 1 in Z if A < the value of this cell in Z, else 0
ErrorCode bif_greater_eq (Cell *Z, const Cell *A) const
store 1 in Z if A is >= the value of this cell in Z, else 0
virtual ErrorCode bif_logarithm (Cell *Z, const Cell *A) const
store the base A logarithm of this cell in Z
virtual ErrorCode bif_maximum (Cell *Z, const Cell *A) const
store the larger of A and of this cell in Z
virtual ErrorCode bif_minimum (Cell *Z, const Cell *A) const
store the smaller of A and of this cell in Z
virtual ErrorCode bif_multiply (Cell *Z, const Cell *A) const
store the product of A and this cell in Z
virtual ErrorCode bif_nand (Cell *Z, const Cell *A) const
store the logical nand of A and this cell in Z
virtual ErrorCode bif_nand_bitwise (Cell *Z, const Cell *A) const
store the bitwise nand of A and this cell in Z
virtual ErrorCode bif_nor (Cell *Z, const Cell *A) const
store the logical NOR of A and this cell in Z
virtual ErrorCode bif_nor_bitwise (Cell *Z, const Cell *A) const
store the bitwise NOR of A and this cell in Z
virtual ErrorCode bif_or (Cell *Z, const Cell *A) const
store the logical OR of A and this cell in Z
virtual ErrorCode bif_or_bitwise (Cell *Z, const Cell *A) const
store the bitwise or of A and this cell in Z
virtual ErrorCode bif_power (Cell *Z, const Cell *A) const
store A to the power of this cell in Z
virtual ErrorCode bif_residue (Cell *Z, const Cell *A) const
store A modulo this cell in Z
virtual ErrorCode bif_circle_fun (Cell *Z, const Cell *A) const
store a circle function (according to A) of this cell in Z
virtual ErrorCode bif_circle_fun_inverse (Cell *Z, const Cell *A) const
store a circle function (according to A) of this cell in Z
virtual ErrorCode bif_add_inverse (Cell *Z, const Cell *A) const
the inverse of bif_add
virtual ErrorCode bif_multiply_inverse (Cell *Z, const Cell *A) const
the inverse of bif_bif_multiply
void * operator new (std::size_t, void *)
placement new
const void * get_u0 () const
raw pointer to the primary value (for 27 ⎕CR)
const void * get_u1 () const
raw pointer to the secondary value (for 28 ⎕CR)
Static Public Member Functions
static bool A_greater_B (const Cell *const &A, const Cell *const &B, const void *unused_comp_arg)
like greater() but static
static bool same_half_plane (APL_Complex A, APL_Complex B)
ISO p.15: return true if A and B are on the same half-plane.
static bool tolerantly_equal (APL_Float A, APL_Float B, double qct)
ISO p.19: return true if real A is tolerantly equal to real B within C.
static bool tolerantly_equal (APL_Complex A, APL_Complex B, double qct)
ISO p. 19: return true if complex A and B are tolerantly equal within real qct.
static bool integral_within (APL_Float A, double qct)
ISO p. 19: A is integral (close to a Gaussian Integer) within qct.
static bool sum_overflow (APL_Integer z, APL_Integer a, APL_Integer b)
return true if z = a + b had an overflow.
static bool diff_overflow (APL_Integer z, APL_Integer a, APL_Integer b)
return true if z = a - b had an overflow.
static bool prod_overflow (int64_t a, int64_t b)
return true if multiplying a and b will (probably) overflow. For some huge a or b the result may incorrectly return true. a or b the result may incorrectly return true.
static void copy (Cell *&dst, const Cell *&src, ShapeItem count, Value &cell_owner)
copy (deep) count cells from src to dest)
static void copy (Value &val, const Cell *&src, ShapeItem count)
copy (deep) count cells from src to val (which is under construction))
static bool is_near_int (APL_Float value)
true iff value is close to an int (within +- qct)
static bool is_near_int64_t (APL_Float value)
true iff value is close to an int64_t (i.e. fots into an int64_t
static bool is_near_zero (APL_Float value)
true iff value is close to 0 (within +- qct)
static APL_Integer near_int (APL_Float value)
return value if it is close to int, or else throw DOMAIN_ERROR
static bool greater_cp (const ShapeItem &a, const ShapeItem &b, const void *cells)
compare cells[a] and cells[b] ascendingly
static bool smaller_cp (const ShapeItem &a, const ShapeItem &b, const void *cells)
compare cells[a] and cells[b] descendingly
static bool compare_stable (const Cell *const &A, const Cell *const &B, const void *comp_arg)
a stable compare function to be used with Heapsort. Equal cells are compared by their address. Return true iff A > B or A = B and &A > &B.
static bool compare_ptr (const Cell *const &A, const Cell *const &B, const void *comp_arg)
a stable compare function to be used with Heapsort. The cell contents are ignored and only the cell addresses are being compared. Return true iff &A > &B.
static ShapeItem * sorted_indices (const Cell *ravel, ShapeItem length, Sort_order order, ShapeItem comp_len)
return length indices i1, i2, ... iN so that ravel[i1] < ravel[i2] < ... < ravel[iN]. The indices are 0-based and the caller must delete[] the result. Returns 0 on error (= WS FULL).
static const char * get_cell_type_name (CellType ct)
the name of ct
Protected Attributes
SomeValue value
the primary value of this cell
Private Member Functions
void * operator new (std::size_t)
Cell & operator= (const Cell &other)
Detailed Description
The base class for all Cells.
Base class for one item of an APL ravel. The item is one of the following:
A character scalar An integer scalar A floating point scalar A complex number scalar An APL array
The kind of item is defined by its class, which is derived from Cell.
Definition at line 51 of file Cell.hh.
Constructor & Destructor Documentation
Cell()
Cell::Cell () inline
Construct an un-initialized Cell.
Definition at line 55 of file Cell.hh.
Member Function Documentation
A_greater_B()
bool Cell::A_greater_B (const Cell *const & A, const Cell *const & B, const void * unused_comp_arg) static
like greater() but static
Definition at line 120 of file Cell.cc.
Referenced by Bif_F12_UNION::eval_B().
bif_add()
virtual ErrorCode Cell::bif_add (Cell * Z, const Cell * A) const inline virtual
store the sum of A and this cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 344 of file Cell.hh.
Referenced by ComplexCell::bif_residue(), Bif_F12_PLUS::eval_AB(), Bif_F12_PLUS::eval_AXB(), Bif_F12_PLUS::get_assoc(), and Bif_F12_PLUS::get_scalar_f2().
bif_add_inverse()
virtual ErrorCode Cell::bif_add_inverse (Cell * Z, const Cell * A) const inline virtual
the inverse of bif_add
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 462 of file Cell.hh.
Referenced by Bif_F12_PLUS::eval_AB(), and Bif_F12_PLUS::get_scalar_f2().
bif_and()
virtual ErrorCode Cell::bif_and (Cell * Z, const Cell * A) const inline virtual
store the logical and of A and this cell in Z
Reimplemented in NumericCell.
Definition at line 348 of file Cell.hh.
Referenced by Bif_F2_AND::eval_AB(), Bif_F2_AND::eval_AXB(), Bif_F2_AND::get_assoc(), and Bif_F2_AND::get_scalar_f2().
bif_and_bitwise()
virtual ErrorCode Cell::bif_and_bitwise (Cell * Z, const Cell * A) const inline virtual
store the bitwise and of A and this cell in Z
Reimplemented in CharCell, and NumericCell.
Definition at line 352 of file Cell.hh.
Referenced by Bif_F2_AND_B::eval_AB(), Bif_F2_AND_B::eval_AXB(), Bif_F2_AND_B::get_assoc(), and Bif_F2_AND_B::get_scalar_f2().
bif_binomial()
virtual ErrorCode Cell::bif_binomial (Cell * Z, const Cell * A) const inline virtual
store the binomial (n over k) of A and this cell in Z
Reimplemented in NumericCell.
Definition at line 356 of file Cell.hh.
Referenced by Bif_F12_BINOM::eval_AB(), Bif_F12_BINOM::eval_AXB(), and Bif_F12_BINOM::get_scalar_f2().
bif_ceiling()
virtual ErrorCode Cell::bif_ceiling (Cell * Z) const inline virtual
round the value of this Cell up and store the result in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 276 of file Cell.hh.
Referenced by Bif_F12_RND_UP::eval_B().
bif_circle_fun()
virtual ErrorCode Cell::bif_circle_fun (Cell * Z, const Cell * A) const inline virtual
store a circle function (according to A) of this cell in Z
Reimplemented in ComplexCell, and RealCell.
Definition at line 446 of file Cell.hh.
Referenced by Bif_F12_CIRCLE::eval_AB(), and Bif_F12_CIRCLE::get_scalar_f2().
bif_circle_fun_inverse()
virtual ErrorCode Cell::bif_circle_fun_inverse (Cell * Z, const Cell * A) const inline virtual
store a circle function (according to A) of this cell in Z
Reimplemented in ComplexCell, and RealCell.
Definition at line 450 of file Cell.hh.
Referenced by Bif_F12_CIRCLE::eval_AB(), and Bif_F12_CIRCLE::get_scalar_f2().
bif_conjugate()
virtual ErrorCode Cell::bif_conjugate (Cell * Z) const inline virtual
conjugate the value of this Cell and store the result in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 280 of file Cell.hh.
Referenced by Bif_F12_PLUS::eval_B().
bif_direction()
virtual ErrorCode Cell::bif_direction (Cell * Z) const inline virtual
store the direction (sign) of this Cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 284 of file Cell.hh.
Referenced by Bif_F12_TIMES::eval_B().
bif_divide()
virtual ErrorCode Cell::bif_divide (Cell * Z, const Cell * A) const inline virtual
store the quotient between A and this cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 364 of file Cell.hh.
Referenced by ComplexCell::bif_residue(), Bif_F12_DIVIDE::eval_AB(), Bif_F12_DIVIDE::eval_AXB(), and Bif_F12_DIVIDE::get_scalar_f2().
bif_equal()
ErrorCode Cell::bif_equal (Cell * Z, const Cell * A) const
store 1 in Z if A == the value of this cell in Z, else 0
Definition at line 255 of file Cell.cc.
References equal(), Workspace::get_CT(), is_character_cell(), IntCell::z0(), and IntCell::zI().
Referenced by ComplexCell::bif_residue(), Bif_F2_EQUAL::eval_AB(), Bif_F2_EQUAL::eval_AXB(), and Bif_F2_EQUAL::get_scalar_f2().
bif_equal_bitwise()
virtual ErrorCode Cell::bif_equal_bitwise (Cell * Z, const Cell * A) const inline virtual
bitwise comparison of *this and A
Reimplemented in CharCell, and NumericCell.
Definition at line 375 of file Cell.hh.
Referenced by Bif_F2_EQUAL_B::eval_AB(), Bif_F2_EQUAL_B::eval_AXB(), and Bif_F2_EQUAL_B::get_scalar_f2().
bif_exponential()
virtual ErrorCode Cell::bif_exponential (Cell * Z) const inline virtual
store e to the power of the value of this Cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 288 of file Cell.hh.
Referenced by Bif_F12_POWER::eval_B().
bif_factorial()
virtual ErrorCode Cell::bif_factorial (Cell * Z) const inline virtual
store the factorial (N!) of the value of this Cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 292 of file Cell.hh.
Referenced by Bif_F12_BINOM::eval_B().
bif_floor()
virtual ErrorCode Cell::bif_floor (Cell * Z) const inline virtual
Round the value of this Cell down and store the result in Z.
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 296 of file Cell.hh.
Referenced by ComplexCell::bif_residue(), and Bif_F12_RND_DN::eval_B().
bif_greater_eq()
ErrorCode Cell::bif_greater_eq (Cell * Z, const Cell * A) const
store 1 in Z if A is >= the value of this cell in Z, else 0
Definition at line 293 of file Cell.cc.
References IntCell::zI().
Referenced by Bif_F2_MEQU::eval_AB(), Bif_F2_MEQU::eval_AXB(), and Bif_F2_MEQU::get_scalar_f2().
bif_greater_than()
ErrorCode Cell::bif_greater_than (Cell * Z, const Cell * A) const
store 1 in Z if A > the value of this cell in Z, else 0
Definition at line 275 of file Cell.cc.
References IntCell::zI().
Referenced by Bif_F2_GREATER::eval_AB(), Bif_F2_GREATER::eval_AXB(), and Bif_F2_GREATER::get_scalar_f2().
bif_less_eq()
ErrorCode Cell::bif_less_eq (Cell * Z, const Cell * A) const
store 1 in Z if A <= the value of this cell in Z, else 0
Definition at line 281 of file Cell.cc.
References IntCell::zI().
Referenced by Bif_F2_LEQU::eval_AB(), Bif_F2_LEQU::eval_AXB(), and Bif_F2_LEQU::get_scalar_f2().
bif_less_than()
ErrorCode Cell::bif_less_than (Cell * Z, const Cell * A) const
store 1 in Z if A < the value of this cell in Z, else 0
Definition at line 287 of file Cell.cc.
References IntCell::zI().
Referenced by Bif_F2_LESS::eval_AB(), Bif_F2_LESS::eval_AXB(), and Bif_F2_LESS::get_scalar_f2().
bif_logarithm()
virtual ErrorCode Cell::bif_logarithm (Cell * Z, const Cell * A) const inline virtual
store the base A logarithm of this cell in Z
Reimplemented in ComplexCell, and RealCell.
Definition at line 398 of file Cell.hh.
Referenced by Bif_F12_LOGA::eval_AB(), Bif_F12_LOGA::eval_AXB(), and Bif_F12_LOGA::get_scalar_f2().
bif_magnitude()
virtual ErrorCode Cell::bif_magnitude (Cell * Z) const inline virtual
store the absolute value of this Cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 300 of file Cell.hh.
Referenced by Bif_F12_STILE::eval_B().
bif_maximum()
virtual ErrorCode Cell::bif_maximum (Cell * Z, const Cell * A) const inline virtual
store the larger of A and of this cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 402 of file Cell.hh.
Referenced by Bif_F12_RND_UP::eval_AB(), Bif_F12_RND_UP::eval_AXB(), Bif_F12_RND_UP::get_assoc(), and Bif_F12_RND_UP::get_scalar_f2().
bif_minimum()
virtual ErrorCode Cell::bif_minimum (Cell * Z, const Cell * A) const inline virtual
store the smaller of A and of this cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 406 of file Cell.hh.
Referenced by Bif_F12_RND_DN::eval_AB(), Bif_F12_RND_DN::eval_AXB(), Bif_F12_RND_DN::get_assoc(), and Bif_F12_RND_DN::get_scalar_f2().
bif_multiply()
virtual ErrorCode Cell::bif_multiply (Cell * Z, const Cell * A) const inline virtual
store the product of A and this cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 410 of file Cell.hh.
Referenced by ComplexCell::bif_residue(), Bif_F12_TIMES::eval_AB(), Bif_F12_TIMES::eval_AXB(), Bif_F12_TIMES::get_assoc(), and Bif_F12_TIMES::get_scalar_f2().
bif_multiply_inverse()
virtual ErrorCode Cell::bif_multiply_inverse (Cell * Z, const Cell * A) const inline virtual
the inverse of bif_bif_multiply
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 466 of file Cell.hh.
Referenced by Bif_F12_TIMES::eval_AB(), and Bif_F12_TIMES::get_scalar_f2().
bif_nand()
virtual ErrorCode Cell::bif_nand (Cell * Z, const Cell * A) const inline virtual
store the logical nand of A and this cell in Z
Reimplemented in NumericCell.
Definition at line 414 of file Cell.hh.
Referenced by Bif_F2_NAND::eval_AB(), Bif_F2_NAND::eval_AXB(), and Bif_F2_NAND::get_scalar_f2().
bif_nand_bitwise()
virtual ErrorCode Cell::bif_nand_bitwise (Cell * Z, const Cell * A) const inline virtual
store the bitwise nand of A and this cell in Z
Reimplemented in NumericCell.
Definition at line 418 of file Cell.hh.
Referenced by Bif_F2_NAND_B::eval_AB(), Bif_F2_NAND_B::eval_AXB(), and Bif_F2_NAND_B::get_scalar_f2().
bif_nat_log()
virtual ErrorCode Cell::bif_nat_log (Cell * Z) const inline virtual
store the base e logarithm of the value of this Cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 304 of file Cell.hh.
Referenced by Bif_F12_LOGA::eval_B().
bif_near_int64_t()
virtual ErrorCode Cell::bif_near_int64_t (Cell * Z) const inline virtual
store the nearby integer of the value of this Cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 320 of file Cell.hh.
Referenced by Bif_F2_OR_B::eval_B().
bif_negative()
virtual ErrorCode Cell::bif_negative (Cell * Z) const inline virtual
store the negative of the value of this Cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 308 of file Cell.hh.
Referenced by Bif_F12_MINUS::eval_B().
bif_nor()
virtual ErrorCode Cell::bif_nor (Cell * Z, const Cell * A) const inline virtual
store the logical NOR of A and this cell in Z
Reimplemented in NumericCell.
Definition at line 422 of file Cell.hh.
Referenced by Bif_F2_NOR::eval_AB(), Bif_F2_NOR::eval_AXB(), and Bif_F2_NOR::get_scalar_f2().
bif_nor_bitwise()
virtual ErrorCode Cell::bif_nor_bitwise (Cell * Z, const Cell * A) const inline virtual
store the bitwise NOR of A and this cell in Z
Reimplemented in NumericCell.
Definition at line 426 of file Cell.hh.
Referenced by Bif_F2_NOR_B::eval_AB(), Bif_F2_NOR_B::eval_AXB(), and Bif_F2_NOR_B::get_scalar_f2().
bif_not()
virtual ErrorCode Cell::bif_not (Cell * Z) const inline virtual
store the logical complement of the value of this Cell in Z
Reimplemented in NumericCell.
Definition at line 312 of file Cell.hh.
Referenced by Bif_F12_WITHOUT::eval_B().
bif_not_bitwise()
virtual ErrorCode Cell::bif_not_bitwise (Cell * Z) const inline virtual
store the bitwise complement of the value of this Cell in Z
Reimplemented in CharCell, and NumericCell.
Definition at line 316 of file Cell.hh.
Referenced by Bif_F2_NOR_B::eval_B().
bif_not_equal()
ErrorCode Cell::bif_not_equal (Cell * Z, const Cell * A) const
store 1 in Z if A != the value of this cell in Z, else 0
Definition at line 265 of file Cell.cc.
References equal(), Workspace::get_CT(), is_character_cell(), IntCell::z1(), and IntCell::zI().
Referenced by Bif_F2_UNEQU::eval_AB(), Bif_F2_UNEQU::eval_AXB(), and Bif_F2_UNEQU::get_scalar_f2().
bif_not_equal_bitwise()
virtual ErrorCode Cell::bif_not_equal_bitwise (Cell * Z, const Cell * A) const inline virtual
bitwise comparison of *this and A
Reimplemented in CharCell, and NumericCell.
Definition at line 379 of file Cell.hh.
Referenced by Bif_F2_UNEQ_B::eval_AB(), Bif_F2_UNEQ_B::eval_AXB(), and Bif_F2_UNEQ_B::get_scalar_f2().
bif_or()
virtual ErrorCode Cell::bif_or (Cell * Z, const Cell * A) const inline virtual
store the logical OR of A and this cell in Z
Reimplemented in NumericCell.
Definition at line 430 of file Cell.hh.
Referenced by Bif_F2_OR::eval_AB(), Bif_F2_OR::eval_AXB(), Bif_F2_OR::get_assoc(), and Bif_F2_OR::get_scalar_f2().
bif_or_bitwise()
virtual ErrorCode Cell::bif_or_bitwise (Cell * Z, const Cell * A) const inline virtual
store the bitwise or of A and this cell in Z
Reimplemented in CharCell, and NumericCell.
Definition at line 434 of file Cell.hh.
Referenced by Bif_F2_OR_B::eval_AB(), Bif_F2_OR_B::eval_AXB(), Bif_F2_OR_B::get_assoc(), and Bif_F2_OR_B::get_scalar_f2().
bif_pi_times()
virtual ErrorCode Cell::bif_pi_times (Cell * Z) const inline virtual
store pi times the value of this Cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 328 of file Cell.hh.
Referenced by Bif_F12_CIRCLE::eval_B().
bif_pi_times_inverse()
virtual ErrorCode Cell::bif_pi_times_inverse (Cell * Z) const inline virtual
store pi times the value of this Cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 332 of file Cell.hh.
Referenced by Bif_F12_CIRCLE::eval_B().
bif_power()
virtual ErrorCode Cell::bif_power (Cell * Z, const Cell * A) const inline virtual
store A to the power of this cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 438 of file Cell.hh.
Referenced by Bif_F12_POWER::eval_AB(), Bif_F12_POWER::eval_AXB(), and Bif_F12_POWER::get_scalar_f2().
bif_reciprocal()
virtual ErrorCode Cell::bif_reciprocal (Cell * Z) const inline virtual
store the reciprocal of the value of this Cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 336 of file Cell.hh.
Referenced by Bif_F12_DIVIDE::eval_B().
bif_residue()
virtual ErrorCode Cell::bif_residue (Cell * Z, const Cell * A) const inline virtual
store A modulo this cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 442 of file Cell.hh.
Referenced by Bif_F12_STILE::eval_AB(), Bif_F12_STILE::eval_AXB(), and Bif_F12_STILE::get_scalar_f2().
bif_roll()
virtual ErrorCode Cell::bif_roll (Cell * Z) const inline virtual
store a random number between 1 and the value of this Cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 340 of file Cell.hh.
Referenced by Bif_F12_ROLL::eval_B().
bif_subtract()
virtual ErrorCode Cell::bif_subtract (Cell * Z, const Cell * A) const inline virtual
store the difference between A and this cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 360 of file Cell.hh.
Referenced by ComplexCell::bif_residue(), Bif_F12_MINUS::eval_AB(), Bif_F12_MINUS::eval_AXB(), and Bif_F12_MINUS::get_scalar_f2().
bif_within_quad_CT()
virtual ErrorCode Cell::bif_within_quad_CT (Cell * Z) const inline virtual
store the nearby integer of the value of this Cell in Z
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 324 of file Cell.hh.
Referenced by Bif_F2_AND_B::eval_B().
CDR_size()
virtual int Cell::CDR_size () const inline virtual
return the minimum number of data bytes to store this cell in CDR format. The actual number of data bytes can be bigger if other cells need more bytes,
Reimplemented in CharCell, ComplexCell, FloatCell, IntCell, LvalCell, and PointerCell.
Definition at line 175 of file Cell.hh.
Referenced by Value::CDR_data_size().
character_representation()
virtual PrintBuffer Cell::character_representation (const PrintContext & pctx) const inline virtual
the Quad_CR representation of this cell
Reimplemented in CharCell, ComplexCell, FloatCell, IntCell, LvalCell, and PointerCell.
Definition at line 129 of file Cell.hh.
Referenced by LvalCell::character_representation(), PrintBuffer::do_PrintBuffer(), Token::print_value(), PrintBuffer::PrintBuffer(), and Quad_TF::tf2_ravel().
compare()
virtual Comp_result Cell::compare (const Cell & other) const inline virtual
compare this with other, throw DOMAIN ERROR on illegal comparisons
Reimplemented in CharCell, ComplexCell, FloatCell, IntCell, and PointerCell.
Definition at line 368 of file Cell.hh.
Referenced by Bif_F12_INDEX_OF::bs_cmp(), FloatCell::compare(), IntCell::compare(), Bif_F12_INTERVAL_INDEX::eval_AB(), Bif_F12_INTERVAL_INDEX::find_range(), greater_cp(), and smaller_cp().
compare_ptr()
bool Cell::compare_ptr (const Cell *const & A, const Cell *const & B, const void * comp_arg) static
a stable compare function to be used with Heapsort. The cell contents are ignored and only the cell addresses are being compared. Return true iff &A > &B.
Definition at line 135 of file Cell.cc.
Referenced by Bif_F2_INTER::eval_AB(), Bif_F12_UNION::eval_B(), and Bif_F12_WITHOUT::large_eval_AB().
compare_stable()
bool Cell::compare_stable (const Cell *const & A, const Cell *const & B, const void * comp_arg) static
a stable compare function to be used with Heapsort. Equal cells are compared by their address. Return true iff A > B or A = B and &A > &B.
Definition at line 127 of file Cell.cc.
Referenced by Bif_F2_INTER::eval_AB(), and Bif_F12_WITHOUT::large_eval_AB().
copy() [1/2]
static void Cell::copy (Cell *& dst, const Cell *& src, ShapeItem count, Value & cell_owner) inline static
copy (deep) count cells from src to dest)
Definition at line 497 of file Cell.hh.
References init_other().
Referenced by Bif_COMMA::append_scalar(), Bif_COMMA::catenate(), Bif_COMMA::laminate(), and Bif_COMMA::prepend_scalar().
copy() [2/2]
void Cell::copy (Value & val, const Cell *& src, ShapeItem count) static
copy (deep) count cells from src to val (which is under construction))
Definition at line 92 of file Cell.cc.
References Value::more(), and Value::next_ravel_Cell().
diff_overflow()
static bool Cell::diff_overflow (APL_Integer z, APL_Integer a, APL_Integer b) inline static
return true if z = a - b had an overflow.
Definition at line 477 of file Cell.hh.
Referenced by FloatCell::bif_subtract(), and IntCell::bif_subtract().
equal()
bool Cell::equal (const Cell & other, double qct) const virtual
return true if this cell is equal to other
Reimplemented in CharCell, ComplexCell, FloatCell, IntCell, and PointerCell.
Definition at line 111 of file Cell.cc.
References get_classname().
Referenced by Bif_F12_UNION::append_zone(), bif_equal(), bif_not_equal(), Bif_F2_FIND::contained(), IntCell::equal(), Bif_F2_INTER::eval_AB(), Quad_MAP::eval_AB(), Bif_F12_WITHOUT::eval_AB(), Bif_F12_INDEX_OF::find_B_in_A(), Bif_F12_INDEX_OF::find_B_in_sorted_A(), and Bif_F12_WITHOUT::large_eval_AB().
get_byte_value()
virtual int Cell::get_byte_value () const inline virtual
Return the byte value (-128..255 incl) of a cell.
Reimplemented in CharCell, and IntCell.
Definition at line 108 of file Cell.hh.
Referenced by Quad_CR::do_CR33(), Quad_CR::do_CR34(), and Quad_CR::do_CR5_6().
get_cell_subtype()
virtual CellType Cell::get_cell_subtype () const inline virtual
return the subtype of this cell. The subtype is the set of containers that can store the cell (only for Int and Char cells).
Reimplemented in CharCell, and IntCell.
Definition at line 269 of file Cell.hh.
References get_cell_type().
Referenced by Value::deep_cell_subtypes(), and Value::flat_cell_subtypes().
get_cell_type()
virtual CellType Cell::get_cell_type () const inline virtual
return the type of this cell
Reimplemented in CharCell, ComplexCell, FloatCell, IntCell, LvalCell, and PointerCell.
Definition at line 264 of file Cell.hh.
Referenced by Quad_JSON::APL_to_JSON_string(), Value::can_be_compared(), PointerCell::compare(), Value::deep_cell_types(), Quad_CR::do_CR26(), Quad_CR::do_CR27_28(), XML_Saving_Archive::emit_cell(), Bif_F12_ENCODE::eval_AB(), Value::flat_cell_types(), get_cell_subtype(), get_char_value(), get_pointer_value(), CharCell::greater(), ComplexCell::greater(), FloatCell::greater(), IntCell::greater(), and is_simple_cell().
get_cell_type_name()
const char * Cell::get_cell_type_name (CellType ct) static
the name of ct
Definition at line 317 of file Cell.cc.
Referenced by Quad_JSON::APL_to_JSON_string(), get_char_value(), and get_pointer_value().
get_char_value()
Unicode Cell::get_char_value () const virtual
Return the character value of a cell.
Reimplemented in CharCell.
Definition at line 142 of file Cell.cc.
References get_cell_type(), and get_cell_type_name().
Referenced by CharCell::compare(), DLX_Root_Node::DLX_Root_Node(), Quad_CR::do_CR10_item(), Quad_CR::do_CR16(), Quad_CR::do_CR27_28(), Quad_CR::do_CR38(), Quad_FX::do_quad_FX(), XML_Saving_Archive::emit_cell(), CharCell::equal(), Value::equal_string(), Quad_AF::eval_B(), Quad_EX::eval_B(), Quad_UCS::eval_B(), Quad_CR::figure_default(), CDR::fill(), Bif_F12_FORMAT::format_one_col_by_spec(), Value::get_CDR_type(), DLX_Node::get_col_type(), CharCell::greater(), Value::is_apl_char_vector(), Quad_XML::name_unsplit(), Quad_GTK::resolve_window(), Quad_XML::split_name(), Quad_TF::tf1(), Quad_TF::tf2_toggle_UCS(), UCS_string::UCS_string(), and UCS_string_vector::UCS_string_vector().
get_checked_near_int()
virtual APL_Integer Cell::get_checked_near_int () const inline virtual
Return value if it is (known to be) close to int, or else Assert()
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 145 of file Cell.hh.
Referenced by NumericCell::bif_and(), NumericCell::bif_binomial(), NumericCell::bif_or(), and Bif_COMMA::catenate_or_laminate().
get_classname()
virtual const char * Cell::get_classname () const inline virtual
return the name of the class
Reimplemented in CharCell, ComplexCell, FloatCell, IntCell, LvalCell, NumericCell, PointerCell, and RealCell.
Definition at line 273 of file Cell.hh.
Referenced by equal(), Quad_UCS::eval_B(), and greater().
get_complex_value()
virtual APL_Complex Cell::get_complex_value () const inline virtual
Return the complex value of a cell.
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 120 of file Cell.hh.
Referenced by NumericCell::bif_and(), RealCell::bif_logarithm(), NumericCell::bif_or(), Bif_F12_DECODE::decode_complex(), ComplexCell::do_bif_circle_fun(), and Bif_F12_ENCODE::encode_Cpx().
get_imag_value()
virtual APL_Float Cell::get_imag_value () const inline virtual
Return the imaginary part of a cell.
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 117 of file Cell.hh.
Referenced by Quad_JSON::APL_to_JSON_string(), Quad_CT::assign(), ComplexCell::compare(), NumericCell::complex_binomial(), Quad_CR::do_CR10_item(), Quad_FFT::do_window(), XML_Saving_Archive::emit_cell(), Quad_UCS::eval_B(), CDR::fill(), Bif_F12_FORMAT::format_one_col_by_spec(), Bif_F12_DOMINO::setup_complex_B(), Quad_PLOT::setup_data_2D(), Quad_PLOT::setup_data_2D_2b(), Quad_TF::tf1(), and Quad_TF::tf2_ravel().
get_int_value()
virtual APL_Integer Cell::get_int_value () const inline virtual
Return the integer value of a cell.
Reimplemented in IntCell.
Definition at line 111 of file Cell.hh.
Referenced by Quad_JSON::APL_to_JSON_string(), FloatCell::compare(), IntCell::compare(), Quad_IO::current(), Quad_PP::current(), Quad_PW::current(), DLX_Root_Node::DLX_Root_Node(), Quad_CR::do_CR10_item(), Quad_RVAL::do_eval_B(), Quad_FIO::do_sprintf(), XML_Saving_Archive::emit_cell(), Bif_F12_ENCODE::encode_Int(), IntCell::equal(), Quad_CR::figure_default(), CDR::fill(), Value::get_CDR_type(), DLX_Node::get_col_type(), Value::get_member_count(), Value::get_new_member(), FloatCell::greater(), IntCell::greater(), CollatingCache::greater_vec(), Quad_XML::name_unsplit(), DLX_Root_Node::preset(), Quad_GTK::resolve_window(), Plot_window_properties::set_attribute(), CollatingCache::smaller_vec(), Quad_TF::tf1(), and Quad_TF::tf2_toggle_UCS().
get_lval_value()
virtual Cell * Cell::get_lval_value () const inline virtual
Return the APL value of a cell (Asserts for non-lval cells)
Reimplemented in LvalCell.
Definition at line 126 of file Cell.hh.
Referenced by Bif_F12_PICK::compute_item_shape(), Bif_F12_PICK::disclose_item(), Quad_CR::do_CR27_28(), Bif_OPER1_EACH::do_eval_LB(), Value::enlist_left(), Bif_OPER1_EACH::eval_ALB(), Value::get_enlist_count(), and Bif_F12_PICK::pick().
get_near_bool()
virtual bool Cell::get_near_bool () const inline virtual
Return value if it is close to boolean, or else throw DOMAIN_ERROR.
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 137 of file Cell.hh.
Referenced by NumericCell::bif_nand(), NumericCell::bif_nor(), NumericCell::bif_not(), and NumericCell::bif_or().
get_near_int()
virtual APL_Integer Cell::get_near_int () const inline virtual
Return value if it is close to int, or else throw DOMAIN_ERROR.
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 141 of file Cell.hh.
Referenced by Stop_Trace::assign(), Quad_TZ::assign(), Quad_RL::assign(), Quad_SYL::assign_indexed(), Quad_FC::assign_indexed(), Quad_PS::assign_indexed(), Symbol::assign_indexed(), NumericCell::bif_and_bitwise(), NumericCell::bif_equal_bitwise(), NumericCell::bif_nand_bitwise(), NumericCell::bif_nor_bitwise(), NumericCell::bif_not_bitwise(), NumericCell::bif_not_equal_bitwise(), NumericCell::bif_or_bitwise(), Bif_F12_DECODE::decode_int(), Quad_CR::do_CR40(), Bif_F2_INDEX::eval_AB(), Bif_F2_INDEX::eval_AXB(), Bif_F12_INTERVAL_INDEX::eval_B(), Quad_AF::eval_B(), Quad_UCS::eval_B(), Quad_FIO::get_FILE(), Quad_FIO::get_file_entry(), Value::get_single_axis(), Value::get_sole_integer(), Value::index(), Bif_F12_PICK::pick_offset(), Value::to_bitmap(), and Value::to_shape().
get_pointer_value()
Value_P Cell::get_pointer_value () const virtual
Return the APL value of a cell (Asserts for non-pointer cells)
Reimplemented in PointerCell.
Definition at line 151 of file Cell.cc.
References get_cell_type(), and get_cell_type_name().
Referenced by Quad_XML::all_members(), Quad_JSON::APL_to_JSON_string(), Symbol::assign_indexed(), Value::can_be_compared(), Value::CDR_data_size(), Value::check_lval_consistency(), Command::cmd_CHECK(), PointerCell::compare(), Value::compute_depth(), Bif_F12_PICK::compute_item_shape(), Value::deep_cell_subtypes(), Value::deep_cell_types(), Bif_F12_PICK::disclose(), Bif_F12_PICK::disclose_item(), Quad_CR::do_CR10_structured(), Quad_CR::do_CR10_value(), Quad_CR::do_CR26(), Quad_CR::do_CR27_28(), Quad_CR::do_CR30(), Quad_CR::do_CR38(), Quad_CR::do_CR39(), Quad_RVAL::do_eval_B(), Bif_OPER1_EACH::do_eval_LB(), Quad_MAP::do_map(), PrintBuffer::do_PrintBuffer(), Quad_FX::do_quad_FX(), ScalarFunction::do_scalar_AB(), ScalarFunction::do_scalar_B(), Value::double_ravel(), XML_Saving_Archive::emit_cell(), Value::enlist_left(), Value::enlist_right(), PointerCell::equal(), Bif_F2_INDEX::eval_AB(), Bif_OPER1_EACH::eval_ALB(), Bif_OPER2_OUTER::eval_ALRB(), Bif_F2_INDEX::eval_AXB(), Quad_FIO::eval_AXB(), Quad_GTK::eval_AXB(), ScalarFunction::expand_nested(), CDR::fill(), Bif_F12_TAKE::first(), Bif_F12_FORMAT::format_one_col_by_spec(), Value::get_all_members_count(), Value::get_col_spacing(), Value::get_enlist_count(), Quad_INP::get_esc(), Value::get_lval_cellowner(), Value::get_member(), Value::get_member_count(), Value::get_member_data(), Value::index(), init_type(), Quad_XML::name_unsplit(), Quad_XML::next_member(), Quad_PLOT::parse_attributes(), Bif_F12_PICK::pick(), Bif_F12_PICK::pick_offset(), Value::print_member(), Value::prototype(), Quad_RE::regex_results(), XML_Saving_Archive::save(), Plot_window_properties::set_attribute(), Value::sorted_members(), Bif_OPER2_RANK::split_y123_B(), Quad_TF::tf2_ravel(), Quad_TF::tf2_toggle_UCS(), Quad_TF::tf2_var(), Value::to_type(), to_value(), Value::total_CDR_size_netto(), Quad_XML::tree(), UCS_string::UCS_string(), and Symbol::vector_assignment().
get_real_value()
virtual APL_Float Cell::get_real_value () const inline virtual
Return the real part of a cell.
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 114 of file Cell.hh.
Referenced by Quad_JSON::APL_to_JSON_string(), Quad_CT::assign(), Quad_TZ::assign(), NumericCell::bif_and(), NumericCell::bif_binomial(), RealCell::bif_logarithm(), NumericCell::bif_or(), Bif_COMMA::catenate_or_laminate(), ComplexCell::compare(), FloatCell::compare(), NumericCell::complex_binomial(), Quad_CT::current(), Bif_F12_DECODE::decode_real(), RealCell::do_bif_circle_fun(), Quad_CR::do_CR10_item(), Quad_FIO::do_sprintf(), Quad_FFT::do_window(), XML_Saving_Archive::emit_cell(), Bif_F12_ENCODE::encode_Flt(), CDR::fill(), Bif_F12_FORMAT::format_by_example(), Bif_F12_FORMAT::format_one_col_by_spec(), FloatCell::greater(), IntCell::greater(), NumericCell::real_binomial(), Bif_F12_DOMINO::setup_complex_B(), Quad_PLOT::setup_data_2D(), Quad_PLOT::setup_data_2D_2b(), Quad_PLOT::setup_data_3D(), Bif_F12_DOMINO::setup_real_B(), Quad_TF::tf1(), and Quad_TF::tf2_ravel().
get_u0()
const void * Cell::get_u0 () const inline
raw pointer to the primary value (for 27 ⎕CR)
Definition at line 526 of file Cell.hh.
References Cell::SomeValue::cval, and value.
Referenced by Quad_CR::do_CR27_28().
get_u1()
const void * Cell::get_u1 () const inline
raw pointer to the secondary value (for 28 ⎕CR)
Definition at line 529 of file Cell.hh.
References Cell::SomeValue::cval, and value.
Referenced by Quad_CR::do_CR27_28().
greater()
bool Cell::greater (const Cell & other) const virtual
Return true if this cell is greater than other, with:
PointerCell > NumericCell > CharCell 2a. NumericCells sorted by get_real_value(). then by get_imag_value() 2b. CharCells sorted by get_char_value() 2c. PointerCells sorted by rank, then by shape, then by ravel
Reimplemented in CharCell, ComplexCell, FloatCell, IntCell, LvalCell, and PointerCell.
Definition at line 102 of file Cell.cc.
References get_classname().
Referenced by Bif_F2_INTER::eval_AB(), and Bif_F12_WITHOUT::large_eval_AB().
greater_cp()
bool Cell::greater_cp (const ShapeItem & a, const ShapeItem & b, const void * cells) static
compare cells[a] and cells[b] ascendingly
Definition at line 207 of file Cell.cc.
References compare().
Referenced by sorted_indices().
init()
void Cell::init (const Cell & other, Value & this_owner, const char * loc) inline
init this Cell from a (possibly deep) copy of other
Definition at line 58 of file Cell.hh.
References init_other().
Referenced by Symbol::assign_indexed(), Quad_CR::do_CR38(), Quad_MAP::do_map(), Bif_REDUCE::do_reduce(), and Quad_JSON::parse_object_member().
init_from_value()
void Cell::init_from_value (Value * value, Value & cell_owner, const char * loc)
init this Cell from value. If value is a scalar then its first element is used (and value is erased). Otherwise a PointerCell is created.
Definition at line 44 of file Cell.cc.
References value.
Referenced by Symbol::assign_indexed(), and Bif_REDUCE::do_reduce().
init_other()
virtual void Cell::init_other (void * other, Value & other_owner, const char * loc) const inline virtual
init (uninitialized) Cell other from this initialized cell
Reimplemented in CharCell, ComplexCell, FloatCell, IntCell, LvalCell, and PointerCell.
Definition at line 62 of file Cell.hh.
Referenced by Value::clone(), copy(), and init().
init_type()
void Cell::init_type (const Cell & other, Value & cell_owner, const char * loc)
init this cell to be the type of other
Definition at line 74 of file Cell.cc.
References Value_P_Base::get(), get_pointer_value(), is_character_cell(), is_lval_cell(), and is_pointer_cell().
is_character_cell()
virtual bool Cell::is_character_cell () const inline virtual
Return true iff this cell is a character cell.
Reimplemented in CharCell.
Definition at line 194 of file Cell.hh.
Referenced by bif_equal(), bif_not_equal(), CharCell::compare(), ComplexCell::compare(), FloatCell::compare(), IntCell::compare(), Bif_F12_PICK::disclose_item(), DLX_Root_Node::DLX_Root_Node(), Quad_CR::do_CR10_item(), Quad_CR::do_CR38(), Quad_MAP::do_map(), Quad_FX::do_quad_FX(), CharCell::equal(), Quad_AF::eval_B(), Quad_EX::eval_B(), Quad_UCS::eval_B(), Quad_CR::figure_default(), Bif_F12_FORMAT::format_one_col_by_spec(), Value::get_CDR_type(), Value::get_col_spacing(), DLX_Node::get_col_type(), Value::get_member_count(), init_type(), Value::is_char_scalar(), Value::is_character_scalar(), Quad_XML::name_unsplit(), Value::prototype(), Quad_CR::short_ravel(), Quad_TF::tf1(), Quad_TF::tf2_toggle_UCS(), Quad_TF::tf2_value(), Value::to_type(), and UCS_string::UCS_string().
is_complex_cell()
virtual bool Cell::is_complex_cell () const inline virtual
Return true iff this cell is a complex number cell.
Reimplemented in ComplexCell.
Definition at line 210 of file Cell.hh.
Referenced by Quad_JSON::APL_to_JSON_string(), NumericCell::bif_and(), FloatCell::compare(), Quad_CR::do_CR10_item(), Quad_FFT::do_window(), Quad_UCS::eval_B(), Bif_F12_FORMAT::format_one_col_by_spec(), Value::get_CDR_type(), Bif_F12_DOMINO::setup_complex_B(), Quad_PLOT::setup_data_2D(), Quad_PLOT::setup_data_2D_2b(), Quad_CR::short_ravel(), and Quad_TF::tf2_ravel().
is_example_field()
virtual bool Cell::is_example_field () const inline virtual
Return true iff this cell is an example field character cell.
Reimplemented in CharCell.
Definition at line 226 of file Cell.hh.
is_finite()
virtual bool Cell::is_finite () const inline virtual
Return true unless this cell contains infinity or NaN.
Reimplemented in ComplexCell, and FloatCell.
Definition at line 222 of file Cell.hh.
Referenced by ComplexCell::bif_circle_fun(), RealCell::bif_circle_fun(), ComplexCell::bif_circle_fun_inverse(), and RealCell::bif_circle_fun_inverse().
is_float_cell()
virtual bool Cell::is_float_cell () const inline virtual
Return true iff this cell is a floating point cell.
Reimplemented in FloatCell.
Definition at line 190 of file Cell.hh.
Referenced by Quad_JSON::APL_to_JSON_string(), Quad_TZ::assign(), FloatCell::compare(), Quad_CR::do_CR10_item(), Quad_UCS::eval_B(), Value::get_CDR_type(), Bif_F12_DOMINO::setup_complex_B(), Bif_F12_DOMINO::setup_real_B(), and Quad_TF::tf2_ravel().
is_integer_cell()
virtual bool Cell::is_integer_cell () const inline virtual
Return true iff this cell is an integer cell.
Reimplemented in IntCell.
Definition at line 182 of file Cell.hh.
Referenced by Quad_JSON::APL_to_JSON_string(), Quad_TZ::assign(), FloatCell::bif_maximum(), FloatCell::bif_minimum(), FloatCell::compare(), IntCell::compare(), DLX_Root_Node::DLX_Root_Node(), Quad_CR::do_CR10_item(), Quad_CR::do_CR39(), Quad_FIO::do_sprintf(), IntCell::equal(), Quad_AF::eval_B(), Quad_UCS::eval_B(), Quad_CR::figure_default(), Value::get_CDR_type(), Value::get_member_count(), Value::get_new_member(), DLX_Root_Node::preset(), Value::prototype(), Plot_window_properties::set_attribute(), Bif_F12_DOMINO::setup_complex_B(), Quad_PLOT::setup_data_3D(), Bif_F12_DOMINO::setup_real_B(), Quad_CR::short_ravel(), Quad_TF::tf1(), and Quad_TF::tf2_toggle_UCS().
is_lval_cell()
virtual bool Cell::is_lval_cell () const inline virtual
Return true iff this cell is a pointer to a cell.
Reimplemented in LvalCell.
Definition at line 202 of file Cell.hh.
Referenced by Value::assign_cellrefs(), Value::check_Cells(), Value::check_lval_consistency(), Bif_F12_PICK::compute_item_shape(), Bif_F12_PICK::disclose_item(), Quad_CR::do_CR30(), Bif_OPER1_EACH::do_eval_LB(), Value::enlist_left(), Value::enlist_right(), Bif_OPER1_EACH::eval_ALB(), Bif_SCAN::expand(), Bif_F12_TAKE::first(), Value::get_enlist_count(), Value::get_lval_cellowner(), init_type(), Bif_F12_PICK::pick(), XML_Saving_Archive::save(), and Quad_TF::tf2_ravel().
is_member_anchor()
virtual bool Cell::is_member_anchor () const inline virtual
Return true iff this is a PointerCell which pouints to a member value.
Reimplemented in PointerCell.
Definition at line 230 of file Cell.hh.
Referenced by Quad_CR::do_CR10_structured().
is_near_bool()
bool Cell::is_near_bool () const inline
return true iff value is numeric and close to 0 or 1
Definition at line 157 of file Cell.hh.
References is_near_one(), and is_near_zero().
Referenced by NumericCell::bif_nand(), NumericCell::bif_nor(), NumericCell::bif_not(), NumericCell::bif_or(), and Quad_CR::do_CR40().
is_near_int() [1/2]
virtual bool Cell::is_near_int () const inline virtual
True iff value is numeric and close to an int.
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 161 of file Cell.hh.
Referenced by Quad_SYL::assign_indexed(), NumericCell::bif_and(), NumericCell::bif_binomial(), NumericCell::bif_or(), Bif_COMMA::catenate_or_laminate(), NumericCell::cpx_gcd(), Bif_F12_INTERVAL_INDEX::eval_B(), Value::get_single_axis(), Value::is_int_scalar(), ComplexCell::is_near_int(), FloatCell::is_near_int(), NumericCell::real_binomial(), Bif_OPER2_RANK::split_y123_B(), and Value::to_bitmap().
is_near_int() [2/2]
bool Cell::is_near_int (APL_Float value) static
true iff value is close to an int (within +- qct)
Definition at line 160 of file Cell.cc.
References value.
is_near_int64_t() [1/2]
virtual bool Cell::is_near_int64_t () const inline virtual
True iff value is numeric and close to an int.
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 165 of file Cell.hh.
Referenced by NumericCell::bif_and_bitwise(), NumericCell::bif_equal_bitwise(), NumericCell::bif_nand_bitwise(), NumericCell::bif_nor_bitwise(), NumericCell::bif_not_bitwise(), NumericCell::bif_not_equal_bitwise(), NumericCell::bif_or_bitwise(), NumericCell::integer_binomial(), ComplexCell::is_near_int64_t(), and FloatCell::is_near_int64_t().
is_near_int64_t() [2/2]
bool Cell::is_near_int64_t (APL_Float value) static
true iff value is close to an int64_t (i.e. fots into an int64_t
Definition at line 178 of file Cell.cc.
References value.
is_near_one()
virtual bool Cell::is_near_one () const inline virtual
return true iff value is numeric and close to 1
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 153 of file Cell.hh.
Referenced by NumericCell::bif_and(), and is_near_bool().
is_near_real()
virtual bool Cell::is_near_real () const inline virtual
return true iff value is numeric and close to a real number
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 169 of file Cell.hh.
Referenced by NumericCell::bif_and(), NumericCell::bif_binomial(), NumericCell::bif_or(), Value::can_be_compared(), Value::is_complex(), and Quad_TF::tf1().
is_near_zero() [1/2]
virtual bool Cell::is_near_zero () const inline virtual
return true iff value is numeric and close to 0
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 149 of file Cell.hh.
Referenced by NumericCell::bif_and(), NumericCell::bif_or(), IntCell::bif_residue(), NumericCell::cpx_gcd(), ComplexCell::do_bif_circle_fun(), Bif_F12_ENCODE::encode_Cpx(), Bif_F12_ENCODE::encode_Flt(), Quad_UCS::eval_B(), NumericCell::flt_gcd(), and is_near_bool().
is_near_zero() [2/2]
static bool Cell::is_near_zero (APL_Float value) inline static
true iff value is close to 0 (within +- qct)
Definition at line 511 of file Cell.hh.
References value.
is_numeric()
virtual bool Cell::is_numeric () const inline virtual
Return true iff this cell is an integer, float, or complex cell.
Reimplemented in NumericCell.
Definition at line 214 of file Cell.hh.
Referenced by Quad_CT::assign(), ComplexCell::compare(), IntCell::compare(), Quad_MAP::do_map(), IntCell::equal(), Bif_F12_FORMAT::format_one_col_by_spec(), Value::get_CDR_type(), DLX_Node::get_col_type(), Value::is_complex(), Value::is_numeric_scalar(), Quad_PLOT::setup_data_2D_2b(), and Quad_TF::tf1().
is_picked_lval_cell()
virtual bool Cell::is_picked_lval_cell () const inline virtual
Return true iff this cell is a pointer to a cell from pick()
Definition at line 206 of file Cell.hh.
is_pointer_cell()
virtual bool Cell::is_pointer_cell () const inline virtual
Return true iff this cell is a pointer (to a sub-array) cell.
Reimplemented in PointerCell.
Definition at line 198 of file Cell.hh.
Referenced by Quad_XML::all_members(), Quad_JSON::APL_to_JSON_string(), Symbol::assign_indexed(), Bif_F12_INDEX_OF::bs_cmp(), Value::can_be_compared(), Value::CDR_data_size(), Value::check_Cells(), Value::check_lval_consistency(), Command::cmd_CHECK(), ComplexCell::compare(), FloatCell::compare(), IntCell::compare(), Bif_F12_PICK::compute_item_shape(), Value::deep_cell_subtypes(), Value::deep_cell_types(), Bif_F12_PICK::disclose(), Bif_F12_PICK::disclose_item(), Quad_CR::do_CR10_item(), Quad_CR::do_CR10_structured(), Quad_CR::do_CR10_value(), Quad_CR::do_CR26(), Quad_CR::do_CR27_28(), Quad_CR::do_CR30(), Quad_CR::do_CR38(), Quad_CR::do_CR39(), Quad_RVAL::do_eval_B(), Bif_OPER1_EACH::do_eval_LB(), Quad_MAP::do_map(), PrintBuffer::do_PrintBuffer(), Quad_FX::do_quad_FX(), ScalarFunction::do_scalar_AB(), ScalarFunction::do_scalar_B(), Value::double_ravel(), Value::enlist_left(), Value::enlist_right(), PointerCell::equal(), Bif_F2_INDEX::eval_AB(), Bif_OPER1_EACH::eval_ALB(), Bif_OPER2_OUTER::eval_ALRB(), Bif_F2_INDEX::eval_AXB(), Quad_FIO::eval_AXB(), Quad_GTK::eval_AXB(), ScalarFunction::expand_nested(), CDR::fill(), Bif_F12_TAKE::first(), Bif_F12_FORMAT::format_one_col_by_spec(), Value::get_all_members_count(), Value::get_col_spacing(), Value::get_enlist_count(), Quad_INP::get_esc(), Value::get_lval_cellowner(), Value::get_member(), Value::get_member_count(), Value::get_member_data(), Value::index(), init_type(), Value::is_simple_scalar(), Quad_XML::next_member(), Quad_PLOT::parse_attributes(), Bif_F12_PICK::pick(), Bif_F12_PICK::pick_offset(), Value::print_member(), Value::prototype(), XML_Saving_Archive::save(), Plot_window_properties::set_attribute(), Quad_PLOT::setup_data(), Quad_CR::short_ravel(), Value::sorted_members(), Bif_OPER2_RANK::split_y123_B(), Quad_TF::tf2_ravel(), Quad_TF::tf2_toggle_UCS(), Quad_TF::tf2_var(), Value::to_type(), to_value(), Value::total_CDR_size_netto(), Quad_XML::tree(), UCS_string::UCS_string(), Value::used_members(), and Symbol::vector_assignment().
is_real_cell()
virtual bool Cell::is_real_cell () const inline virtual
Return true iff this cell is an integer or float cell.
Reimplemented in RealCell.
Definition at line 218 of file Cell.hh.
Referenced by Bif_F12_FORMAT::format_by_example(), Bif_F12_FORMAT::format_one_col_by_spec(), and Quad_PLOT::setup_data_3D().
is_simple_cell()
bool Cell::is_simple_cell () const inline
Return true iff this cell is a numeric cor character cell.
Definition at line 186 of file Cell.hh.
References get_cell_type().
Referenced by Value::CDR_data_size(), Bif_REDUCE::do_reduce(), CDR::fill(), Token::show_trace(), and Value::total_CDR_size_netto().
near_int()
APL_Integer Cell::near_int (APL_Float value) static
return value if it is close to int, or else throw DOMAIN_ERROR
Definition at line 192 of file Cell.cc.
References value.
Referenced by FloatCell::get_near_int(), and NumericCell::integer_binomial().
need_scaling()
virtual bool Cell::need_scaling (const PrintContext & pctx) const inline virtual
return true if this cell needs scaling (exponential format) in pctx
Reimplemented in ComplexCell, FloatCell, and IntCell.
Definition at line 133 of file Cell.hh.
Referenced by PrintBuffer::PrintBuffer().
operator new() [1/2]
void * Cell::operator new (std::size_t) private
Cells that are allocated with new() shall always be contained in APL values (using placement new() on the ravel of the value. We prevent the accidental use of non-placement new() by defining it but not implementing it.
operator new() [2/2]
void * Cell::operator new (std::size_t s, void * pos)
placement new
Definition at line 38 of file Cell.cc.
operator=()
Cell & Cell::operator= (const Cell & other) private
Cells shalle never be overriden with other Cells since they may require their desctuctor to be called (e.g. PointerCell) We prevent the accidental use of non-placement new() by defining it but not implementing it.
prod_overflow()
static bool Cell::prod_overflow (int64_t a, int64_t b) inline static
return true if multiplying a and b will (probably) overflow. For some huge a or b the result may incorrectly return true. a or b the result may incorrectly return true.
Definition at line 486 of file Cell.hh.
Referenced by FloatCell::bif_add(), FloatCell::bif_multiply(), and FloatCell::bif_subtract().
release()
virtual void Cell::release (const char * loc) inline virtual
Release content pointed to (complex, APL value)
Reimplemented in PointerCell.
Definition at line 179 of file Cell.hh.
Referenced by Value::assign_cellrefs(), Symbol::assign_indexed(), Bif_REDUCE::do_reduce(), Value::double_ravel(), Value::print_member(), and Value::~Value().
smaller_cp()
bool Cell::smaller_cp (const ShapeItem & a, const ShapeItem & b, const void * cells) static
compare cells[a] and cells[b] descendingly
Definition at line 227 of file Cell.cc.
References compare().
Referenced by sorted_indices().
sorted_indices()
ShapeItem * Cell::sorted_indices (const Cell * ravel, ShapeItem length, Sort_order order, ShapeItem comp_len) static
return length indices i1, i2, ... iN so that ravel[i1] < ravel[i2] < ... < ravel[iN]. The indices are 0-based and the caller must delete[] the result. Returns 0 on error (= WS FULL).
Definition at line 299 of file Cell.cc.
References greater_cp(), smaller_cp(), and UCS_string::sort().
Referenced by Bif_F12_INDEX_OF::eval_AB(), and Bif_F12_SORT::sort().
sum_overflow()
static bool Cell::sum_overflow (APL_Integer z, APL_Integer a, APL_Integer b) inline static
return true if z = a + b had an overflow.
Definition at line 470 of file Cell.hh.
Referenced by FloatCell::bif_add(), and IntCell::bif_add().
to_value()
Value_P Cell::to_value (const char * loc) const
return pointer value of a PointerCell or create a scalar with a copy of this cell.
Definition at line 57 of file Cell.cc.
References get_pointer_value(), and is_pointer_cell().
Referenced by Bif_OPER1_EACH::do_eval_LB(), Bif_REDUCE::do_reduce(), Bif_OPER1_EACH::eval_ALB(), and Quad_RE::eval_AXB().
Member Data Documentation
value
SomeValue Cell::value protected
the primary value of this cell
Definition at line 554 of file Cell.hh.
Referenced by CharCell::bif_and_bitwise(), ComplexCell::bif_ceiling(), IntCell::bif_ceiling(), IntCell::bif_conjugate(), IntCell::bif_direction(), CharCell::bif_equal_bitwise(), IntCell::bif_exponential(), IntCell::bif_factorial(), ComplexCell::bif_floor(), IntCell::bif_floor(), ComplexCell::bif_logarithm(), IntCell::bif_magnitude(), IntCell::bif_maximum(), IntCell::bif_minimum(), IntCell::bif_nat_log(), ComplexCell::bif_near_int64_t(), IntCell::bif_near_int64_t(), IntCell::bif_negative(), CharCell::bif_not_equal_bitwise(), CharCell::bif_or_bitwise(), ComplexCell::bif_pi_times(), IntCell::bif_pi_times(), ComplexCell::bif_pi_times_inverse(), IntCell::bif_pi_times_inverse(), ComplexCell::bif_reciprocal(), IntCell::bif_reciprocal(), IntCell::bif_residue(), IntCell::bif_roll(), ComplexCell::bif_within_quad_CT(), IntCell::bif_within_quad_CT(), ComplexCell::character_representation(), IntCell::character_representation(), LvalCell::character_representation(), CharCell::CharCell(), LvalCell::check_consistency(), CharCell::compare(), IntCell::compare(), ComplexCell::ComplexCell(), ComplexCell::cval(), FloatCell::dfval(), CharCell::equal(), IntCell::equal(), FloatCell::FloatCell(), CharCell::get_byte_value(), IntCell::get_byte_value(), LvalCell::get_cell_owner(), PointerCell::get_cell_owner(), CharCell::get_cell_subtype(), IntCell::get_cell_subtype(), CharCell::get_char_value(), ComplexCell::get_checked_near_int(), IntCell::get_checked_near_int(), IntCell::get_complex_value(), ComplexCell::get_imag_value(), IntCell::get_int_value(), LvalCell::get_lval_value(), ComplexCell::get_near_bool(), IntCell::get_near_bool(), ComplexCell::get_near_int(), IntCell::get_near_int(), PointerCell::get_pointer_value(), ComplexCell::get_real_value(), IntCell::get_real_value(), get_u0(), get_u1(), IntCell::Hswap(), init_from_value(), CharCell::init_other(), ComplexCell::init_other(), IntCell::init_other(), IntCell::IntCell(), CharCell::is_example_field(), ComplexCell::is_finite(), PointerCell::is_member_anchor(), ComplexCell::is_near_int(), is_near_int(), ComplexCell::is_near_int64_t(), is_near_int64_t(), ComplexCell::is_near_one(), IntCell::is_near_one(), ComplexCell::is_near_real(), ComplexCell::is_near_zero(), IntCell::is_near_zero(), is_near_zero(), PointerCell::isolate(), LvalCell::LvalCell(), ComplexCell::mag2(), near_int(), ComplexCell::need_scaling(), PointerCell::PointerCell(), PointerCell::release(), and IntCell::set_int_value().
The documentation for this class was generated from the following files:
src/Cell.hh
src/Cell.cc