GNU APL: Executable Class Reference
Executable Class Reference abstract
Base class for ExecuteList, StatementList, and UserFunction.
#include <Executable.hh>
Public Member Functions
Executable (const UCS_string &ucs, bool multi_line, ParseMode pm, const char *loc)
constructor
Executable (Fun_signature sig, int lambda_num, const UCS_string &lambda_text, const char *loc)
constructor for lambdas
virtual ~Executable ()
destructor: release values held by the body
ParseMode get_parse_mode () const
the parse mode of this Executable
void clear_body ()
delete values in body and (maybe) remove lambdas
virtual UCS_string get_name () const =0
return the name of this function, or ◊ or ⍎
virtual bool cannot_suspend () const
return true iff this Executable cannot be suspended
virtual Symbol * get_sym_Z () const
return the result symbol iff this is a user defined function or operator that returns a value
virtual const UserFunction * get_exec_ufun () const
return a UserFunction * (if this is one) or else 0.
virtual bool pushes_sym (const Symbol *sym) const
return true if this Executable localizes Symbol sym
virtual UserFunction * get_exec_ufun ()
return a UserFunction * (if this is one) or else 0.
virtual Function_Line get_line (Function_PC pc) const
get the line number for pc
virtual ostream & print (ostream &out) const
print this user defined executable to out
void print_token (ostream &out) const
print this user defined executable to out
void print_text (ostream &out) const
print the text of this user defined executable to out
Token execute_body () const
execute the body of this executable
const Token_string & get_body () const
return the body of this executable
const int get_text_size () const
return number of function lines (including header line 0)
const UCS_string & get_text (int l) const
return function line n (0 = header line)
void clear_text (int l)
clear the text of line n (0 = header line)
void set_text (int l, const UCS_string &new_line)
set the text of line n (0 = header line)
UCS_string statement_text (Function_PC pc) const
return the text of statement at pc
virtual Function_PC line_start (Function_Line line) const
return the first PC of the line
virtual void adjust_line_starts ()
adjust line starts before calling Parser::remove_void_token(body)
void set_error_info (Error &error, Function_PC2 range) const
compute lines 2 and 3 in error
Function_PC get_statement_start (int pc) const
return the start of the statement to which pc belongs
void unmark_all_values () const
clear marked flag in all body token
int show_owners (const char *prefix, ostream &out, const Value &value) const
print all owners of value
const char * get_loc () const
say where this SI entry was allocated
void increment_refcount (const char *loc)
increment the reference counter
void decrement_refcount (const char *loc)
decrement the reference counter
Protected Member Functions
void setup_lambdas ()
extract all lambda expressions from body and store them in lambdas
ShapeItem setup_one_lambda (ShapeItem b, ShapeItem end, int lambda_num)
extract one lambda expressions from body and store it in lambdas
Fun_signature compute_lambda_body (Token_string &rev_lambda_body, ShapeItem b, ShapeItem bend)
body[b ... bend] is a lambda. Move these token from this body to the body of the lambda and clear them in this body.
UCS_string extract_lambda_text (Fun_signature signature, int skip) const
extract the skip'th { ... } from the function text
ErrorCode parse_body_line (Function_Line line, const UCS_string &ucs, bool trace, bool tolerant, const char *loc, bool macro)
parse the body line number line of this function
ErrorCode parse_body_line (Function_Line line, const Token_string &tos, bool trace, bool tolerant, const char *loc)
parse the body line number line of this function
Static Protected Member Functions
static void reverse_statement_token (Token_string &tos)
reverse the token order in every statement of tos
static void reverse_all_token (Token_string &tos)
reverse the token order of the entire Token_string
Protected Attributes
const char * alloc_loc
where this SI entry was allocated
const ParseMode pmode
the mode this Executable
UCS_string_vector text
the program text from which body was created
Token_string body
The token to be executed. They are organized line by line and statement by statement, but the token within a statement reversed due to the right-to-left execution of APL.
int refcount
reference counter (for lambdas)
Detailed Description
Base class for ExecuteList, StatementList, and UserFunction.
A sequence of APL token. An executable is created for one of 3 purposes:
an APL expression for execute (⍎), or
the statements of one line in immediate execution, or
all lines of a user defined function.
Definition at line 40 of file Executable.hh.
Constructor & Destructor Documentation
Executable() [1/2]
Executable::Executable (const UCS_string & ucs, bool multi_line, ParseMode pm, const char * loc)
constructor
Definition at line 31 of file Executable.cc.
References UCS_string::append(), UCS_string::size(), and text.
Executable() [2/2]
Executable::Executable (Fun_signature sig, int lambda_num, const UCS_string & lambda_text, const char * loc)
constructor for lambdas
Definition at line 65 of file Executable.cc.
References UCS_string::append(), Avec::is_quad(), Avec::is_symbol_char(), UserFunction_header::lambda_header(), UCS_string::remove_trailing_whitespaces(), UCS_string::size(), and text.
~Executable()
Executable::~Executable () virtual
destructor: release values held by the body
Definition at line 104 of file Executable.cc.
References body, and clear_body().
Member Function Documentation
adjust_line_starts()
virtual void Executable::adjust_line_starts () inline virtual
adjust line starts before calling Parser::remove_void_token(body)
Reimplemented in UserFunction.
Definition at line 130 of file Executable.hh.
Referenced by setup_lambdas().
cannot_suspend()
virtual bool Executable::cannot_suspend () const inline virtual
return true iff this Executable cannot be suspended
Reimplemented in UserFunction.
Definition at line 65 of file Executable.hh.
clear_body()
void Executable::clear_body ()
delete values in body and (maybe) remove lambdas
Definition at line 116 of file Executable.cc.
References body, decrement_refcount(), UserFunction::get_func_ufun(), and UserFunction::is_lambda().
Referenced by UserFunction::parse_body(), and ~Executable().
clear_text()
void Executable::clear_text (int l) inline
clear the text of line n (0 = header line)
Definition at line 115 of file Executable.hh.
References text.
Referenced by UserFunction::transform_multi_line_strings(), and UserFunction::transform_multi_line_strings_3().
compute_lambda_body()
Fun_signature Executable::compute_lambda_body (Token_string & rev_lambda_body, ShapeItem b, ShapeItem bend) protected
body[b ... bend] is a lambda. Move these token from this body to the body of the lambda and clear them in this body.
Definition at line 628 of file Executable.cc.
References body, Token::get_tag(), and Token::move_1().
Referenced by setup_one_lambda().
decrement_refcount()
void Executable::decrement_refcount (const char * loc)
decrement the reference counter
Definition at line 841 of file Executable.cc.
References get_exec_ufun(), get_name(), UserFunction::is_lambda(), print_text(), and refcount.
Referenced by clear_body(), and UserFunction::destroy().
execute_body()
Token Executable::execute_body () const
execute the body of this executable
Definition at line 257 of file Executable.cc.
References Error::get_error_code(), StateIndicator::run(), and Workspace::SI_top().
Referenced by Command::finish_context().
extract_lambda_text()
UCS_string Executable::extract_lambda_text (Fun_signature signature, int skip) const protected
extract the skip'th { ... } from the function text
Definition at line 708 of file Executable.cc.
References UCS_string::append(), UCS_string::append_UTF8(), UCS_string::pop_back(), UCS_string::size(), and text.
Referenced by setup_one_lambda().
get_body()
const Token_string & Executable::get_body () const inline
return the body of this executable
Definition at line 103 of file Executable.hh.
References body.
Referenced by Doxy::add_fun_to_call_graph(), Command::do_APL_expression(), XML_Loading_Archive::find_lambda(), StateIndicator::print(), and StateIndicator::uses_function().
get_exec_ufun() [1/2]
virtual UserFunction * Executable::get_exec_ufun () inline virtual
return a UserFunction * (if this is one) or else 0.
Reimplemented in UserFunction.
Definition at line 82 of file Executable.hh.
get_exec_ufun() [2/2]
virtual const UserFunction * Executable::get_exec_ufun () const inline virtual
return a UserFunction * (if this is one) or else 0.
Reimplemented in UserFunction.
Definition at line 74 of file Executable.hh.
Referenced by decrement_refcount(), StateIndicator::goon(), increment_refcount(), StateIndicator::jump(), StateIndicator::list(), parse_body_line(), Workspace::pop_SI(), StateIndicator::print(), XML_Saving_Archive::save_SI_entry(), Doxy::SI_table(), StateIndicator::statement_result(), Error::update_error_info(), and StateIndicator::~StateIndicator().
get_line()
virtual Function_Line Executable::get_line (Function_PC pc) const inline virtual
get the line number for pc
Reimplemented in UserFunction.
Definition at line 86 of file Executable.hh.
Referenced by Quad_SI::eval_AB(), Quad_SI::eval_B(), StateIndicator::get_line(), XML_Saving_Archive::save_SI_entry(), StateIndicator::statement_result(), and statement_text().
get_loc()
const char * Executable::get_loc () const inline
say where this SI entry was allocated
Definition at line 146 of file Executable.hh.
References alloc_loc.
Referenced by StateIndicator::info().
get_name()
virtual UCS_string Executable::get_name () const pure virtual
return the name of this function, or ◊ or ⍎
Implemented in ExecuteList, StatementList, and UserFunction.
Referenced by decrement_refcount(), Quad_SI::eval_AB(), Quad_SI::eval_B(), StateIndicator::function_name(), Workspace::push_SI(), XML_Saving_Archive::save_SI_entry(), and show_owners().
get_parse_mode()
ParseMode Executable::get_parse_mode () const inline
the parse mode of this Executable
Definition at line 55 of file Executable.hh.
References pmode.
Referenced by Quad_SI::eval_AB(), Quad_SI::eval_B(), StateIndicator::get_parse_mode(), parse_body_line(), Workspace::pop_SI(), Workspace::push_SI(), and XML_Saving_Archive::save_SI_entry().
get_statement_start()
Function_PC Executable::get_statement_start (int pc) const
return the start of the statement to which pc belongs
Definition at line 445 of file Executable.cc.
References body.
Referenced by set_error_info().
get_sym_Z()
virtual Symbol * Executable::get_sym_Z () const inline virtual
return the result symbol iff this is a user defined function or operator that returns a value
Reimplemented in UserFunction.
Definition at line 70 of file Executable.hh.
get_text()
const UCS_string & Executable::get_text (int l) const inline
return function line n (0 = header line)
Definition at line 111 of file Executable.hh.
References text.
Referenced by Nabla::execute_escape(), UserFunction::fix(), Doxy::function_page(), Doxy::functions_table(), UserFunction::help(), StateIndicator::info(), UserFunction::parse_body(), StateIndicator::print(), XML_Saving_Archive::save_SI_entry(), Doxy::SI_table(), UserFunction::transform_multi_line_strings(), UserFunction::transform_multi_line_strings_3(), and UserFunction::UserFunction().
get_text_size()
const int Executable::get_text_size () const inline
return number of function lines (including header line 0)
Definition at line 107 of file Executable.hh.
References text.
Referenced by Nabla::execute_escape(), UserFunction::fix(), Doxy::function_page(), Doxy::functions_table(), UserFunction::help(), UserFunction::parse_body(), UserFunction::transform_multi_line_strings(), UserFunction::transform_multi_line_strings_3(), and UserFunction::UserFunction().
increment_refcount()
void Executable::increment_refcount (const char * loc)
increment the reference counter
Definition at line 829 of file Executable.cc.
References get_exec_ufun(), and refcount.
Referenced by XML_Loading_Archive::read_Function(), XML_Loading_Archive::read_lambda(), and setup_one_lambda().
line_start()
virtual Function_PC Executable::line_start (Function_Line line) const inline virtual
return the first PC of the line
Reimplemented in UserFunction.
Definition at line 126 of file Executable.hh.
Referenced by statement_text().
parse_body_line() [1/2]
ErrorCode Executable::parse_body_line (Function_Line line, const Token_string & tos, bool trace, bool tolerant, const char * loc) protected
parse the body line number line of this function
Definition at line 163 of file Executable.cc.
References UserFunction::add_label(), body, Token::get_Class(), get_exec_ufun(), get_parse_mode(), Token::get_sym_ptr(), Token::get_tag(), and Token_string::print().
parse_body_line() [2/2]
ErrorCode Executable::parse_body_line (Function_Line line, const UCS_string & ucs, bool trace, bool tolerant, const char * loc, bool macro) protected
parse the body line number line of this function
Definition at line 136 of file Executable.cc.
References get_parse_mode(), parse_body_line(), and Error::throw_parse_error().
Referenced by ExecuteList::fix(), StatementList::fix(), UserFunction::parse_body(), parse_body_line(), and UserFunction::UserFunction().
print()
virtual ostream & Executable::print (ostream & out) const inline virtual
print this user defined executable to out
Reimplemented in UserFunction.
Definition at line 90 of file Executable.hh.
References print_token().
Referenced by ExecuteList::fix(), and StatementList::fix().
print_text()
void Executable::print_text (ostream & out) const
print the text of this user defined executable to out
Definition at line 280 of file Executable.cc.
References text.
Referenced by decrement_refcount().
print_token()
void Executable::print_token (ostream & out) const
print this user defined executable to out
Definition at line 271 of file Executable.cc.
References body, and Token_string::print().
Referenced by print().
pushes_sym()
virtual bool Executable::pushes_sym (const Symbol * sym) const inline virtual
return true if this Executable localizes Symbol sym
Reimplemented in UserFunction.
Definition at line 78 of file Executable.hh.
Referenced by StateIndicator::nth_push().
reverse_all_token()
void Executable::reverse_all_token (Token_string & tos) static protected
reverse the token order of the entire Token_string
Definition at line 822 of file Executable.cc.
Referenced by setup_one_lambda().
reverse_statement_token()
void Executable::reverse_statement_token (Token_string & tos) static protected
reverse the token order in every statement of tos
Definition at line 802 of file Executable.cc.
References Token_string::reverse_from_to().
Referenced by setup_lambdas(), and setup_one_lambda().
set_error_info()
void Executable::set_error_info (Error & error, Function_PC2 range) const
compute lines 2 and 3 in error
Definition at line 340 of file Executable.cc.
References body, UTF8_string::c_str(), and get_statement_start().
Referenced by Error::update_error_info().
set_text()
void Executable::set_text (int l, const UCS_string & new_line) inline
set the text of line n (0 = header line)
Definition at line 119 of file Executable.hh.
References text.
Referenced by UserFunction::transform_multi_line_strings(), UserFunction::transform_multi_line_strings_3(), and UserFunction::UserFunction().
setup_lambdas()
void Executable::setup_lambdas () protected
extract all lambda expressions from body and store them in lambdas
Definition at line 512 of file Executable.cc.
References adjust_line_starts(), body, Parser::match_par_bra(), Parser::remove_void_token(), reverse_statement_token(), and setup_one_lambda().
Referenced by ExecuteList::fix(), StatementList::fix(), UserFunction::parse_body(), and UserFunction::UserFunction().
setup_one_lambda()
ShapeItem Executable::setup_one_lambda (ShapeItem b, ShapeItem end, int lambda_num) protected
extract one lambda expressions from body and store it in lambdas
Definition at line 572 of file Executable.cc.
References UCS_string::append(), body, compute_lambda_body(), extract_lambda_text(), Function::get_token(), increment_refcount(), UserFunction_header::lambda_header(), reverse_all_token(), and reverse_statement_token().
Referenced by setup_lambdas().
show_owners()
int Executable::show_owners (const char * prefix, ostream & out, const Value & value) const
print all owners of value
Definition at line 492 of file Executable.cc.
References body, Value_P_Base::get(), Token::get_apl_val(), get_name(), Token::get_ValueType(), and Value::is_or_contains().
Referenced by StateIndicator::show_owners(), and Symbol::show_owners().
statement_text()
UCS_string Executable::statement_text (Function_PC pc) const
return the text of statement at pc
Definition at line 286 of file Executable.cc.
References UCS_string::append(), UCS_string::back(), body, get_line(), Avec::is_diamond(), line_start(), UCS_string::pop_back(), UCS_string::size(), and text.
Referenced by Quad_SI::eval_AB(), Quad_SI::eval_B(), StateIndicator::list(), StateIndicator::print(), and Doxy::SI_table().
unmark_all_values()
void Executable::unmark_all_values () const
clear marked flag in all body token
Definition at line 468 of file Executable.cc.
References body, Token::get_apl_val(), UserFunction::get_func_ufun(), Token::get_function(), Token::get_ValueType(), UserFunction::is_lambda(), and unmark_all_values().
Referenced by unmark_all_values(), and StateIndicator::unmark_all_values().
Member Data Documentation
alloc_loc
const char* Executable::alloc_loc protected
where this SI entry was allocated
Definition at line 177 of file Executable.hh.
Referenced by get_loc().
body
Token_string Executable::body protected
The token to be executed. They are organized line by line and statement by statement, but the token within a statement reversed due to the right-to-left execution of APL.
Definition at line 197 of file Executable.hh.
Referenced by UserFunction::adjust_line_starts(), clear_body(), compute_lambda_body(), ExecuteList::fix(), StatementList::fix(), UserFunction::fix_lambda(), get_body(), UserFunction::get_name_and_line(), get_statement_start(), UserFunction::help(), UserFunction::parse_body(), parse_body_line(), UserFunction::pc_for_line(), UserFunction::print_properties(), print_token(), set_error_info(), setup_lambdas(), setup_one_lambda(), show_owners(), statement_text(), unmark_all_values(), and ~Executable().
pmode
const ParseMode Executable::pmode protected
the mode this Executable
Definition at line 189 of file Executable.hh.
Referenced by get_parse_mode().
refcount
int Executable::refcount protected
reference counter (for lambdas)
Definition at line 200 of file Executable.hh.
Referenced by decrement_refcount(), and increment_refcount().
text
UCS_string_vector Executable::text protected
the program text from which body was created
Definition at line 192 of file Executable.hh.
Referenced by UserFunction::canonical(), clear_text(), Executable(), extract_lambda_text(), UserFunction::fix(), UserFunction::fix_lambda(), get_text(), get_text_size(), UserFunction::line_prefix(), UserFunction::parse_body(), print_text(), set_text(), statement_text(), UserFunction::transform_multi_line_strings(), and UserFunction::transform_multi_line_strings_3().
The documentation for this class was generated from the following files:
src/Executable.hh
src/Executable.cc