GNU APL: UCS_string::iterator Class Reference
UCS_string::iterator Class Reference
an iterator for UCS_strings
#include <UCS_string.hh>
Public Member Functions
iterator (const UCS_string &ucs, int p)
constructor: start at position p
Unicode get (int off=0) const
return char at offset off from current position
Unicode next ()
return next char
bool more () const
return true iff there are more chars in the string
Protected Attributes
const UCS_string & s
the string
int pos
the current position in the string
Detailed Description
an iterator for UCS_strings
Definition at line 343 of file UCS_string.hh.
Constructor & Destructor Documentation
iterator()
UCS_string::iterator::iterator (const UCS_string & ucs, int p) inline
constructor: start at position p
Definition at line 347 of file UCS_string.hh.
Member Function Documentation
get()
Unicode UCS_string::iterator::get (int off = 0) const inline
return char at offset off from current position
Definition at line 353 of file UCS_string.hh.
References pos, s, and UCS_string::size().
more()
bool UCS_string::iterator::more () const inline
return true iff there are more chars in the string
Definition at line 361 of file UCS_string.hh.
References pos, s, and UCS_string::size().
next()
Unicode UCS_string::iterator::next () inline
return next char
Definition at line 357 of file UCS_string.hh.
References pos, s, and UCS_string::size().
Member Data Documentation
pos
int UCS_string::iterator::pos protected
the current position in the string
Definition at line 369 of file UCS_string.hh.
Referenced by get(), more(), and next().
s
const UCS_string& UCS_string::iterator::s protected
the string
Definition at line 366 of file UCS_string.hh.
Referenced by get(), more(), and next().
The documentation for this class was generated from the following file:
src/UCS_string.hh