GNU APL: Value Class Reference
Value Class Reference
An APL Value (essentially a Shape and a ravel)
#include <Value.hh>
Public Types
enum { PACKED_MINIMUM_LENGHT = 12 }
packing makes no sense for short booleans
Public Member Functions
virtual ~Value ()
destructor
bool is_scalar () const
return true iff this value is a scalar.
bool is_simple_scalar () const
return true iff this value is a simple (i.e. depth 0) scalar.
bool is_empty () const
return true iff this value is empty (some dimension is 0).
bool is_numeric_scalar () const
return true iff this value is a numeric scalar.
bool is_character_scalar () const
return true iff this value is a character scalar
bool is_scalar_or_vector () const
return true iff this value is a scalar or vector
bool is_vector () const
return true iff this value is a vector.
bool is_scalar_or_len1_vector () const
return true iff this value is a scalar or vector of length 1.
bool is_scalar_extensible () const
return true iff this value can be scalar-extended
int get_increment () const
return the increment for iterators of this value. The increment is used for scalar-extension of 1-element values
bool is_char_string () const
return true iff this value is a simple character scalar or vector.
bool is_char_vector () const
return true iff this value is a simple character vector.
bool is_apl_char_vector () const
return true iff this value is a simple character vector containing only APL characters (from ⎕AV)
bool is_char_array () const
return true iff all ravel elements of this value are characters
bool is_char_scalar () const
return true iff this value is a simple character scalar.
bool is_int_scalar () const
return true iff this value is a simple integer scalar.
ShapeItem element_count () const
return the number of elements (the product of the shapes).
ShapeItem nz_element_count () const
return the number of elements, but at least 1 (for the prototype).
uRank get_rank () const
return the rank of this value
const Shape & get_shape () const
return the shape of this value
ShapeItem get_shape_item (sRank r) const
return the r'th shape element of this value
ShapeItem get_first_shape_item () const
return the length of the last dimension of this value, i.e. ↑⍴this
ShapeItem get_last_shape_item () const
return the length of the last dimension of this value, i.e. ¯1↑⍴this
ShapeItem get_cols () const
return the length of the last axis, or 1 for scalars
ShapeItem get_rows () const
return the product of all but the the last axis, or 1 for scalars
void set_shape_item (sAxis r, ShapeItem sh)
set the length of axis r to sh.
void set_shape (const Shape &new_shape)
ShapeItem get_offset (const Cell *cell) const
return the position of cell in the ravel of this value.
const Cell * get_ravel_end () const
return the next byte after the ravel
APL_Integer get_sole_integer () const
return the integer of a value that is supposed to have (exactly) one
Function_Line get_line_number () const
return the first integer of a value (the line number of →Value).
bool is_simple () const
return true iff this value is simple (i.e. not nested).
bool is_one_dimensional () const
return true iff this value and its ravel items have rank < 2
bool is_int_array () const
return true iff this value is a (simple) integer array, allowing near-int values (but NOT necessatily values within ⎕CT of an integers).
bool is_int_vector () const
return true iff this value is a (simple) integer vector.
bool is_complex (bool check_numeric) const
return true, if this value has complex cells, false iff it has only real cells. Throw domain error for other cells (char, nested etc.) if check_numeric is true.
bool can_be_compared () const
return true if this value can be compared. This is the case when all cells (including nested ones) are not complex
bool equal_string (const UCS_string &ucs) const
optimized comparison function for strings
Value_P get_cellrefs (const char *loc)
return a value containing pointers to all ravel cells of this value. the result is non-nested and has the same shape as this
void assign_cellrefs (Value_P val)
assign val to the cell references in this value.
void check_lval_consistency () const
check that this left-value is consistent and return its cell owner. If quick then the first owner is returned, otherwise the entire value is checked.
Cell * get_member (const std::vector< const UCS_string * > &members, Value *&owner, bool create_if_needed, bool throw_error)
return member of this value, defined by members. The first name in members is the deepest, while the last name is the name of the variable containing the members (and is only used in error printouts).
const Cell * get_member_data (const UCS_string &member) const
return the Cell (if any) containing the data of structured value member member, or 0 if member not found.
Cell * get_member_data (const UCS_string &member)
return the Cell (if any) containing the data of structured value member member, or 0 if member not found.
void sorted_members (std::vector< ShapeItem > &result, const Unicode *filter) const
store the row numbers (starting at 0) so that this[rows] is sorted in result. Only used rows are returned.
void used_members (std::vector< ShapeItem > &result, bool sorted) const
store the row numbers (starting at 0) in result so that this[rows] is a (used) row, maybe sorted. in result. Only used rows are returned.
ShapeItem get_member_count () const
return the number of (valid) members, as per this[1;]
Cell * get_new_member (const UCS_string &new_member)
create a new member and return the Cell containing the data for it
void double_ravel (const char *loc)
double the ravel length of this value (by appending integer 0s).
const Cell & get_cravel (ShapeItem idx) const
return the (constant) idx'th element of the ravel.
const Cell & get_cfirst () const
return the first element of the ravel (which is always present). same as get_cproto(), but named differently to indicate its context.
const Cell & get_cproto () const
return the first element of the ravel (which is always present) same as get_first(), but named differently to indicate its context.
const Cell & get_cscalar () const
return the first element of the ravel of a scalar same as get_cfirst(), but named differently to indicate its context.
Cell & get_wravel (ShapeItem idx)
return the (writable) idx'th element of the ravel.
Cell & get_wfirst ()
return the first element of the ravel (which is always present) Same as get_wproto() and get_wscalar(), but named differently to indicate its context.
Cell & get_wscalar ()
return the first element of the ravel of a scalar value. Same as get_wfirst(), but named differently to indicate its context.
Cell & get_wproto ()
return the first element of the ravel (which is always present) same as wfirst(), but named differently to indicate its context.
void set_default (const Value &B, const char *loc)
set the prototype (according to B) if this value is empty.
void set_default (const Cell &cB, const char *loc)
set the prototype (according to B) if this value is empty.
void set_proto_Spc ()
set the prototype to ' ' if this value is empty.
void set_proto_Int ()
set the prototype to 0 if this value is empty.
void release (ShapeItem offset, const char *loc)
release ravel Cell z
ShapeItem get_enlist_count () const
Return the number of scalars in this value (enlist).
APL_types::Depth compute_depth () const
compute the depth of this value.
void enlist_left (Value &Z) const
store the scalars in this (left-)value into dest...
void enlist_right (Value &Z) const
store the scalars in this value into dest...
CellType flat_cell_types () const
compute the cell types contained in the top level of this value
CellType flat_cell_subtypes () const
compute the cell subtypes contained in the top level of this value
CellType deep_cell_types () const
compute the CellType contained in this value (recursively)
CellType deep_cell_subtypes () const
recursive set of Cell types in this value
ostream & print (ostream &out) const
print this value (line break at Workspace::get_PW())
ostream & print_member (ostream &out, UCS_string member) const
print this member value
ostream & print1 (ostream &out, PrintContext pctx) const
print this value (line break at print_width)
ostream & print_properties (ostream &out, int indent, bool help) const
print the properties (shape, flags etc) of this value
void debug (const char *info) const
debug-print this value
ostream & print_boxed (ostream &out, int indent) const
print this value in 4 ⎕CR style
Value_P index (const IndexExpr &IDX) const
return this indexed by (multi-dimensional) IDX.
AxesBitmap to_bitmap (const char *where, uRank rank_B) const
return a bitmap of integers in this value. Normalized to ⎕IO←0.
Value_P index (const Value *X) const
return this indexed by (one-dimensional) IDX.
int get_owner_count () const
return the number of Value_P pointing to this value
Value * get_lval_cellowner () const
return true iff this value is an lval (selective assignment) i.e. return true if at least one leaf value is an lval.
bool more () const
return true iff more ravel items (as per shape) need to be initialized. (the prototype of empty values may still be missing)
ShapeItem get_valid_item_count ()
return the number of (so far) initialized items
Cell * current_ravel ()
return the current ravel cell to be initialized (excluding prototype)
void next_ravel_Char (Unicode u)
initialize the next ravel cell with a character value
void next_ravel_Float (APL_Float f)
initialize the next ravel cell with a floating point value
void next_ravel_Number (APL_Float f)
initialize the next ravel cell with a floating point value, converting it to integer if possible
void next_ravel_Number (APL_Float real, APL_Float imag)
initialize the next ravel cell with a complex value if needed, or with (near-real) floating point value if possible.
void next_ravel_Number (APL_Complex cpx)
initialize the next ravel cell with a complex value if needed, or with (near-real) floating point value if possible.
void next_ravel_Cell (const Cell &other)
initialize the next ravel cell from another Cell
void next_ravel_Proto (const Cell &other)
initialize the next ravel cell from the type of another Cell
void next_ravel_Complex (APL_Complex cpx)
initialize the next ravel cell with a floating point value
void next_ravel_Complex (APL_Float real, APL_Float imag)
initialize the next ravel cell with a floating point value
void next_ravel_Int (APL_Integer i)
initialize the next ravel cell with an integer value
void next_ravel_0 ()
initialize the next ravel cell with integer 0
void next_ravel_1 ()
initialize the next ravel cell with integer 1
void next_ravel_Byte (uint8_t byte)
initialize the next ravel position with byte. NOTE that in this case ravel is a uint8_t * and not a Cell * !!!
void next_ravel_Lval (Cell *target, Value *target_owner)
initialize the next ravel cell with a pointer to another Cell
void next_ravel_Pointer (Value *val)
initialize the next ravel cell with an APL sub-value
void next_ravel_Pointer (Value *val, uint32_t magic)
initialize the next ravel cell with an APL sub-value
void next_ravel_Value (Value *val)
initialize the next ravel cell from either a APL scalar (if val is one) or from a non-scalar (producing as PointerCell
void set_ravel_Char (ShapeItem offset, Unicode uni)
set ravel[offset] to uni
void set_ravel_Int (ShapeItem offset, APL_Integer aint)
set ravel[offset] to aint
void set_ravel_Float (ShapeItem offset, APL_Float flt)
set ravel[offset] to flt
void set_ravel_Complex (ShapeItem offset, APL_Float real, APL_Float imag)
set ravel[offset] to Complex(real, imag)
void set_ravel_Cell (ShapeItem offset, const Cell &cell)
set ravel[offset] to cell.
void set_ravel_Pointer (ShapeItem offset, Value *val)
set ravel[offset] to b PointerCell(val), where val ≠ simple scalar.
void set_ravel_Value (ShapeItem offset, Value *value)
set ravel[offset] to value
bool NOTCHAR () const
return the NOTCHAR property of the value. NOTCHAR is false for simple char arrays and true if any element is numeric or nested. The NOTCHAR property of empty arrays is the NOTCHAR property of its prototype. see also lrm p. 138.
bool same_rank (const Value &other) const
return true iff this value has the same rank as other.
bool same_shape (const Value &other) const
return true iff this value has the same shape as other.
bool scalar_matching_shape (const Value &other) const
return true iff this value has the same shape as other or one of the values is a scalar
void flag_info (const char *loc, ValueFlags flag, const char *flag_name, bool set) const
print debug info about setting or clearing of flags to CERR
void SET_member () const
set the Value flag member
bool is_member () const
true if Value flag member is set
void SET_packed () const
set the Value flag packed
void CLEAR_packed () const
clear the Value flag packed
bool is_packed () const
true if Value flag packed is set
void SET_complete () const
set the Value flag complete
bool is_complete () const
true if Value flag complete is set
void SET_marked () const
set the Value flag marked
void CLEAR_marked () const
clear the Value flag marked
bool is_marked () const
true if Value flag marked is set
bool is_structured () const
return true if this variable is is_member() and a N×2 matrix with proper keys
void add_member (const UCS_string &member_name, Value *member_value)
add a member to a structured variable
ShapeItem get_all_members_count () const
return the (recursive) number of members in this value
void unmark () const
clear marked flag on this value and its nested sub-values
void rollback (ShapeItem items, const char *loc)
rollback initialization of this value
Value_P prototype (const char *loc) const
the prototype of this value
int32_t get_col_spacing (bool &numeric, ShapeItem col, bool framed) const
get the min spacing for this column and set/clear if there is/isn't a numeric item in the column. are/ain't numeric items in col.
ostream & list_one (ostream &out, bool show_owners) const
list a value
void check_value (const char *loc)
check that this value was completely initialized, and set VF_complete if so.
int total_CDR_size_brutto (CDR_type cdr_type) const
return the total CDR size (header + data + padding) for this value.
int total_CDR_size_netto (CDR_type cdr_type) const
return the total CDR size in bytes (header + data), not including any padding for this value.
int CDR_data_size (CDR_type cdr_type) const
return the CDR size in bytes for the data of value, not including the CDR header and padding
CDR_type get_CDR_type () const
return the CDR type for this value
UCS_string get_UCS_ravel () const
return the ravel of this value as UCS string, or throw DOMAIN error if the ravel contains non-char or nested cells.
void to_type (bool force_numeric)
recursively replace all numeric ravel elements with 0 and all characters with blank. See lrm p. 46.
void print_structure (ostream &out, int indent, ShapeItem idx) const
print address, shape, and flags of this value
ValueFlags get_flags () const
return the current flags
void print_stale_info (ostream &out, const DynamicObject *dob) const
print info related to a stale value
void explode ()
expand this (packed) Boolean value (in place)
const char * try_implode ()
try to implode (pack) this unpacked value. Return 0 on success or reason on error;
int check_Cells (ostream &out) const
check the cells of this value, return the number of errors.
void increment_pointer_cell_count ()
increment the PointerCell count
void decrement_pointer_cell_count ()
decrement the PointerCell count
ShapeItem get_pointer_cell_count () const
return the PointerCell count
void add_subcount (ShapeItem count)
increase nz_subcell_count by count
void increment_owner_count (const char *loc)
increment the number of (smart-) pointers to this value
void decrement_owner_count (const char *loc)
decrement the number of (smart-) pointers to this value and delete this value if no more pointers exist
Value_P clone (const char *loc) const
return a deep copy of this value
Public Member Functions inherited from DynamicObject
DynamicObject (const char *loc, DynamicObject *anchor)
constructor: a DynamicObject allocated at source location loc
DynamicObject (const char *loc)
a special constructor for the statically allocated anchors
DynamicObject * get_next ()
return the next DynamicObject in its list
const DynamicObject * get_next () const
return the next DynamicObject in its list
DynamicObject * get_prev ()
return the previous DynamicObject in its list
const DynamicObject * get_prev () const
return the previous DynamicObject in its list
void unlink ()
unlink this DynamicObject from its list
const IndexExpr * pIndexExpr () const
cast to IndexExpr *. Caller must check that this cast is valid.
IndexExpr * pIndexExpr ()
cast to IndexExpr *. Caller must check that this cast is valid.
void print (ostream &out) const
print this object
void print_new (ostream &out, const char *loc) const
print new object message
void print_chain (ostream &out) const
print the list of objects starting at this object
const char * where_allocated () const
where this value was allocated.
Static Public Member Functions
static sRank get_single_axis (const Value *val, sRank max_axis)
If this value is a single axis between ⎕IO and ⎕IO + max_axis then return that axis. Otherwise throw AXIS_ERROR.
static Shape to_shape (const Value *val)
convert the ravel of Value val to a shape (normalized to ⎕IO←0) An elided index, for example B[], throws an INDEX_ERROR.
static const Cell & cell_fetcher (ShapeItem offset, const Cell *ravel)
return the offset'th ravel cell (of an unpack'ed ravel)
static const Cell & packed_fetcher (ShapeItem offset, const Cell *ravel)
return the offset'th ravel cell (of an pack'ed ravel)
static void glue (Token &token, Token &token_A, Token &token_B, const char *loc)
glue two values.
static void glue_strand_strand (Token &result, Value_P A, Value_P B, const char *loc)
glue strands A and B
static void glue_strand_closed (Token &result, Value_P A, Value_P B, const char *loc)
glue strands A and strand B
static void glue_closed_strand (Token &result, Value_P A, Value_P B, const char *loc)
glue closed A and closed B
static void glue_closed_closed (Token &result, Value_P A, Value_P B, const char *loc)
glue closed A and closed B
static bool is_or_contains (const Value *val, const Value *sub)
returen true if sub == val or sub is contained in val
static void init ()
initialize value related variables and print some statistics.
static void mark_all_dynamic_values ()
mark all values, except static values
static int erase_stale (const char *loc)
erase stale values
static void erase_all (ostream &out)
erase all values (clean-up after)CLEAR)
static ostream & list_all (ostream &out, bool show_owners)
list all values
static int print_incomplete (ostream &out)
print incomplete Values, and return the number of incomplete Values.
static int print_stale (ostream &out)
print stale Values, and return the number of stale Values.
static int check_all_Cells (ostream &out)
check the cells of all values, return the number of bad Values.
static bool check_WS_FULL (const char *args, ShapeItem cell_count, const char *loc)
check if WS is FULL after allocating value with cell_count items
static void catch_Error (const Error &error, const char *args, const char *loc)
handler for catch(Error) in init_ravel() (never called)
static void catch_exception (const exception &ex, const char *args, const char *caller, const char *loc)
handler for catch(exception) in init_ravel() (never called)
static void catch_ANY (const char *args, const char *caller, const char *loc)
handler for catch(...) in init_ravel() (never called)
Static Public Member Functions inherited from DynamicObject
static const DynamicObject * get_all_values ()
return a pointer to all allocated Values
Public Attributes
const void * check_ptr
a "checksum" to detect deleted values
Static Public Attributes
static uint64_t total_ravel_count = 0
total nz_element_counts of all non-short values
static uint64_t value_count = 0
the number of values created
static uint64_t fast_new_count = 0
the number of fast (recycled) new() calls
static uint64_t slow_new_count = 0
the number of slow (malloc() based) new() calls
Protected Types
enum { deleted_values_MAX = 10000 }
max. number values that have been deleted
Protected Member Functions
Value (const char *loc)
constructor: scalar value (i.e. a value with rank 0).
Value (const Cell &cell, const char *loc)
constructor: a scalar value (i.e. a value with rank 0) from a cell
Value (ShapeItem sh, const char *loc)
constructor: a true vector (i.e. a value with rank 1) with shape sh
Value (const Shape &sh, const char *loc)
constructor: a general array with shape sh
Value (const Shape &sh, uint64_t *bits, const char *loc)
constructor: a packed array with shape sh. The caller has allocated the ravel (bits)
Value (const UCS_string &ucs, const char *loc)
constructor: a simple character vector from a UCS string. Rank is always 1, so that is_char_vector() will be true.
Value (const UTF8_string &utf, const char *loc)
constructor: a simple character vector from a UTF8 string
Value (const CDR_string &cdr, const char *loc)
constructor: a simple character vector from a CDR string
Value (const PrintBuffer &pb, const char *loc)
constructor: a character matrix from a PrintBuffer
Value (const char *loc, const Shape *sh)
constructor: a integer vector containing the items of a shape
Cell * next_ravel ()
return the next ravel cell to be initialized (excluding prototype)
uint8_t * next_ravel_byte ()
return the next (packed) byte position
void init_ravel ()
init the ravel of an APL value, return the ravel length
Value * get_pointer ()
explicit cast from Value & to Value *. Use with care
Protected Member Functions inherited from DynamicObject
const Value & rValue () const
downcast to const Value &. Caller must check that this cast is valid.
Value & rValue ()
down cast to Value &. Caller must check that this cast is valid.
Static Protected Member Functions
static void * operator new (size_t sz)
allocate space for a new Value. For performance reasons, a pool of deleted_values_MAX is kept and Value objects in that pool are reused before calling new().
static void operator delete (void *ptr)
free space for a new Value
Protected Attributes
Shape shape
the shape of this value (only the first rank values are valid.
const Cell &(* fetcher)(ShapeItem offset, const Cell *ravel)
mux between packed and non-packed ravel cells
int owner_count
number of Value_P objects pointing to this value
ShapeItem pointer_cell_count
the value that has a PointerCell pointing to this value (if any)
uint16_t flags
valueFlags for this value.
ShapeItem valid_ravel_items
number of initialized cells in the ravel
ShapeItem nz_subcell_count
the number of cells in nested sub-values
Cell * ravel
The ravel of this value.
Cell short_value [12]
the cells of a short (i.e. ⍴,value ≤ SHORT_VALUE_LENGTH_WANTED) value
Protected Attributes inherited from DynamicObject
const char * alloc_loc
where this value was allocated or deleted.
DynamicObject * next
the next DynamicObject (of all objects) in this's list
DynamicObject * prev
the previous DynamicObject (of all objects) in this's list
Static Protected Attributes
static _deleted_value * deleted_values = 0
a linked list of values that have been deleted
static int deleted_values_count = 0
number values that have been deleted
static uint64_t alloc_size = 0
the size of the next allocation
Static Protected Attributes inherited from DynamicObject
static DynamicObject all_values
the anchor for all dynamic Value instances
static DynamicObject all_index_exprs
the anchor for all dynamic IndexExpr instances
Private Member Functions
Value * operator& ()
restrict use of & (which is frequently a mistake)
Static Private Member Functions
static void * operator new[] (size_t sz)
prevent new[] of Value
static void operator delete[] (void *ptr)
prevent delete[] of Value
Friends
class Value_P
class Value_P_Base
class PointerCell
class PJob_scalar_AB
class PJob_scalar_B
Detailed Description
An APL Value (essentially a Shape and a ravel)
An APL value. It consists of a fixed header (rank, shape) and and a ravel (a sequence of cells). If the ravel is short, then it is contained in the value itself; otherwise the value uses a pointer to a loner ravel.
Definition at line 58 of file Value.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
packing makes no sense for short booleans
Definition at line 107 of file Value.hh.
anonymous enum
anonymous enum protected
max. number values that have been deleted
Definition at line 948 of file Value.hh.
Constructor & Destructor Documentation
Value() [1/10]
Value::Value (const char * loc) protected
constructor: scalar value (i.e. a value with rank 0).
Definition at line 258 of file Value.cc.
References init_ravel().
Value() [2/10]
Value::Value (const Cell & cell, const char * loc) protected
constructor: a scalar value (i.e. a value with rank 0) from a cell
Definition at line 267 of file Value.cc.
References check_value(), init_ravel(), and set_ravel_Cell().
Value() [3/10]
Value::Value (ShapeItem sh, const char * loc) protected
constructor: a true vector (i.e. a value with rank 1) with shape sh
Definition at line 279 of file Value.cc.
References init_ravel().
Value() [4/10]
Value::Value (const Shape & sh, const char * loc) protected
constructor: a general array with shape sh
Definition at line 289 of file Value.cc.
References init_ravel().
Value() [5/10]
Value::Value (const Shape & sh, uint64_t * bits, const char * loc) protected
constructor: a packed array with shape sh. The caller has allocated the ravel (bits)
Definition at line 299 of file Value.cc.
References check_ptr, Shape::get_nz_volume(), and ravel.
Value() [6/10]
Value::Value (const UCS_string & ucs, const char * loc) protected
constructor: a simple character vector from a UCS string. Rank is always 1, so that is_char_vector() will be true.
Definition at line 323 of file Value.cc.
References init_ravel(), next_ravel_Char(), set_proto_Spc(), and UCS_string::size().
Value() [7/10]
Value::Value (const UTF8_string & utf, const char * loc) protected
constructor: a simple character vector from a UTF8 string
Definition at line 337 of file Value.cc.
References init_ravel(), next_ravel_Char(), and set_proto_Spc().
Value() [8/10]
Value::Value (const CDR_string & cdr, const char * loc) protected
constructor: a simple character vector from a CDR string
Definition at line 351 of file Value.cc.
References init_ravel(), next_ravel_Char(), and set_proto_Spc().
Value() [9/10]
Value::Value (const PrintBuffer & pb, const char * loc) protected
constructor: a character matrix from a PrintBuffer
Definition at line 365 of file Value.cc.
References PrintBuffer::get_char(), PrintBuffer::get_column_count(), PrintBuffer::get_row_count(), init_ravel(), next_ravel_Char(), and set_proto_Spc().
Value() [10/10]
Value::Value (const char * loc, const Shape * sh) protected
constructor: a integer vector containing the items of a shape
Definition at line 385 of file Value.cc.
References Shape::get_rank(), Shape::get_shape_item(), get_wproto(), init_ravel(), next_ravel_Int(), and IntCell::z0().
~Value()
Value::~Value () virtual
destructor
Definition at line 401 of file Value.cc.
References check_ptr, flags, get_pointer_cell_count(), get_wfirst(), nz_element_count(), ravel, Cell::release(), short_value, total_ravel_count, DynamicObject::unlink(), and value_count.
Member Function Documentation
add_member()
void Value::add_member (const UCS_string & member_name, Value * member_value)
add a member to a structured variable
Definition at line 1124 of file Value.cc.
References get_member(), and is_structured().
Referenced by XML_node::add_member().
add_subcount()
void Value::add_subcount (ShapeItem count) inline
increase nz_subcell_count by count
Definition at line 842 of file Value.hh.
References nz_subcell_count.
Referenced by PointerCell::PointerCell(), and PointerCell::release().
assign_cellrefs()
void Value::assign_cellrefs (Value_P val)
assign val to the cell references in this value.
Definition at line 485 of file Value.cc.
References check_lval_consistency(), element_count(), Value_P_Base::get(), LvalCell::get_cell_owner(), LvalCell::get_lval_value(), get_wravel(), get_wscalar(), init(), Cell::is_lval_cell(), is_scalar(), nz_element_count(), Cell::release(), and value_count.
can_be_compared()
bool Value::can_be_compared () const
return true if this value can be compared. This is the case when all cells (including nested ones) are not complex
Definition at line 1477 of file Value.cc.
References Cell::get_cell_type(), get_cravel(), Cell::get_pointer_value(), Cell::is_near_real(), Cell::is_pointer_cell(), and nz_element_count().
catch_ANY()
void Value::catch_ANY (const char * args, const char * caller, const char * loc) static
handler for catch(...) in init_ravel() (never called)
Definition at line 249 of file Value.cc.
catch_Error()
void Value::catch_Error (const Error & error, const char * args, const char * loc) static
handler for catch(Error) in init_ravel() (never called)
Definition at line 216 of file Value.cc.
catch_exception()
void Value::catch_exception (const exception & ex, const char * args, const char * caller, const char * loc) static
handler for catch(exception) in init_ravel() (never called)
Definition at line 225 of file Value.cc.
References alloc_size, Quad_WA::initial_sbrk, Workspace::SI_entry_count(), total_ravel_count, and value_count.
CDR_data_size()
int Value::CDR_data_size (CDR_type cdr_type) const
return the CDR size in bytes for the data of value, not including the CDR header and padding
Definition at line 2164 of file Value.cc.
References Cell::CDR_size(), get_cravel(), Cell::get_pointer_value(), Cell::is_pointer_cell(), Cell::is_simple_cell(), and nz_element_count().
Referenced by Symbol::get_attributes(), and total_CDR_size_netto().
cell_fetcher()
static const Cell & Value::cell_fetcher (ShapeItem offset, const Cell * ravel) inline static
return the offset'th ravel cell (of an unpack'ed ravel)
Definition at line 440 of file Value.hh.
References ravel.
Referenced by explode(), and init_ravel().
check_all_Cells()
int Value::check_all_Cells (ostream & out) static
check the cells of all values, return the number of bad Values.
Definition at line 2787 of file Value.cc.
References DynamicObject::all_values, and DynamicObject::get_prev().
Referenced by Command::cmd_CHECK().
check_Cells()
int Value::check_Cells (ostream & out) const
check the cells of this value, return the number of errors.
Definition at line 2802 of file Value.cc.
References get_cravel(), get_pointer_cell_count(), Cell::is_lval_cell(), Cell::is_pointer_cell(), nz_element_count(), and pointer_cell_count.
check_lval_consistency()
void Value::check_lval_consistency () const
check that this left-value is consistent and return its cell owner. If quick then the first owner is returned, otherwise the entire value is checked.
Definition at line 580 of file Value.cc.
References LvalCell::check_consistency(), get_cravel(), Cell::get_pointer_value(), Cell::is_lval_cell(), Cell::is_pointer_cell(), and nz_element_count().
Referenced by assign_cellrefs().
check_value()
void Value::check_value (const char * loc)
check that this value was completely initialized, and set VF_complete if so.
Definition at line 2068 of file Value.cc.
References element_count(), get_cfirst(), get_shape(), nz_element_count(), print(), and valid_ravel_items.
Referenced by Value().
check_WS_FULL()
bool Value::check_WS_FULL (const char * args, ShapeItem cell_count, const char * loc) static
check if WS is FULL after allocating value with cell_count items
Definition at line 191 of file Value.cc.
References Workspace::SI_entry_count(), Quad_WA::total_memory, total_ravel_count, value_count, Quad_WA::WA_margin, and Quad_WA::WA_scale.
Referenced by Workspace::push_SI().
CLEAR_marked()
void Value::CLEAR_marked () const inline
clear the Value flag marked
Definition at line 679 of file Value.hh.
References flags.
CLEAR_packed()
void Value::CLEAR_packed () const inline
clear the Value flag packed
Definition at line 652 of file Value.hh.
References flags.
clone()
Value_P Value::clone (const char * loc) const
return a deep copy of this value
Definition at line 2526 of file Value.cc.
References flags, get_cproto(), get_cravel(), get_shape(), Cell::init_other(), and nz_element_count().
compute_depth()
APL_types::Depth Value::compute_depth () const
compute the depth of this value.
Definition at line 1558 of file Value.cc.
References get_cfirst(), get_cravel(), Cell::get_pointer_value(), is_scalar(), and nz_element_count().
Referenced by list_one(), print_properties(), and print_structure().
current_ravel()
Cell * Value::current_ravel () inline
return the current ravel cell to be initialized (excluding prototype)
Definition at line 487 of file Value.hh.
References more(), ravel, and valid_ravel_items.
debug()
void Value::debug (const char * info) const
debug-print this value
Definition at line 2445 of file Value.cc.
References PrintBuffer::debug(), and Workspace::get_PrintContext().
decrement_owner_count()
void Value::decrement_owner_count (const char * loc) inline
decrement the number of (smart-) pointers to this value and delete this value if no more pointers exist
Definition at line 856 of file Value.hh.
References check_ptr, and owner_count.
decrement_pointer_cell_count()
void Value::decrement_pointer_cell_count () inline
decrement the PointerCell count
Definition at line 834 of file Value.hh.
References pointer_cell_count.
Referenced by PointerCell::release().
deep_cell_subtypes()
CellType Value::deep_cell_subtypes () const
recursive set of Cell types in this value
Definition at line 1628 of file Value.cc.
References Cell::get_cell_subtype(), get_cravel(), Cell::get_pointer_value(), Cell::is_pointer_cell(), and nz_element_count().
deep_cell_types()
CellType Value::deep_cell_types () const
compute the CellType contained in this value (recursively)
Definition at line 1611 of file Value.cc.
References Cell::get_cell_type(), get_cravel(), Cell::get_pointer_value(), Cell::is_pointer_cell(), and nz_element_count().
Referenced by print_properties().
double_ravel()
void Value::double_ravel (const char * loc)
double the ravel length of this value (by appending integer 0s).
Definition at line 993 of file Value.cc.
References get_cols(), get_new_member(), Cell::get_pointer_value(), get_rank(), get_rows(), is_member(), Cell::is_pointer_cell(), ravel, Cell::release(), Shape::set_shape_item(), shape, short_value, valid_ravel_items, and IntCell::z0().
Referenced by get_new_member().
element_count()
ShapeItem Value::element_count () const inline
return the number of elements (the product of the shapes).
Definition at line 176 of file Value.hh.
References Shape::get_volume(), and shape.
Referenced by Stop_Trace::assign(), assign_cellrefs(), Quad_SYL::assign_indexed(), Quad_FC::assign_indexed(), Quad_PS::assign_indexed(), Symbol::assign_indexed(), check_value(), Quad_CR::do_CR36(), enlist_left(), enlist_right(), equal_string(), explode(), CDR::fill(), Symbol::get_attributes(), get_cellrefs(), get_col_spacing(), get_enlist_count(), get_increment(), get_sole_integer(), get_UCS_ravel(), index(), is_scalar_extensible(), is_simple(), more(), Quad_XML::name_unsplit(), Quad_XML::next_member(), NOTCHAR(), print(), Token::print_value(), Quad_GTK::resolve_window(), Quad_PLOT::setup_data_2D_2b(), Token::show_trace(), to_bitmap(), and to_shape().
enlist_left()
void Value::enlist_left (Value & Z) const
store the scalars in this (left-)value into dest...
Definition at line 1350 of file Value.cc.
References element_count(), get_cravel(), Cell::get_lval_value(), Cell::get_pointer_value(), Cell::is_lval_cell(), Cell::is_pointer_cell(), and next_ravel_Cell().
enlist_right()
void Value::enlist_right (Value & Z) const
store the scalars in this value into dest...
Definition at line 1328 of file Value.cc.
References element_count(), get_cravel(), Cell::get_pointer_value(), Cell::is_lval_cell(), Cell::is_pointer_cell(), and next_ravel_Cell().
equal_string()
bool Value::equal_string (const UCS_string & ucs) const
optimized comparison function for strings
Definition at line 1495 of file Value.cc.
References element_count(), get_cfirst(), Cell::get_char_value(), get_cravel(), get_rank(), and UCS_string::size().
erase_all()
void Value::erase_all (ostream & out) static
erase all values (clean-up after)CLEAR)
Definition at line 1183 of file Value.cc.
References DynamicObject::all_values, and DynamicObject::get_next().
erase_stale()
int Value::erase_stale (const char * loc) static
erase stale values
Definition at line 1197 of file Value.cc.
References DynamicObject::all_values, erase_stale(), DynamicObject::get_next(), list_one(), owner_count, DynamicObject::print_chain(), DynamicObject::rValue(), and DynamicObject::where_allocated().
Referenced by erase_stale().
explode()
void Value::explode ()
expand this (packed) Boolean value (in place)
Definition at line 2834 of file Value.cc.
References cell_fetcher(), element_count(), fetcher, is_packed(), ravel, and IntCell::set_int_value().
flag_info()
void Value::flag_info (const char * loc, ValueFlags flag, const char * flag_name, bool set) const
print debug info about setting or clearing of flags to CERR
Definition at line 1082 of file Value.cc.
References flags.
flat_cell_subtypes()
CellType Value::flat_cell_subtypes () const
compute the cell subtypes contained in the top level of this value
Definition at line 1600 of file Value.cc.
References Cell::get_cell_subtype(), get_cravel(), and nz_element_count().
flat_cell_types()
CellType Value::flat_cell_types () const
compute the cell types contained in the top level of this value
Definition at line 1589 of file Value.cc.
References Cell::get_cell_type(), get_cravel(), and nz_element_count().
get_all_members_count()
ShapeItem Value::get_all_members_count () const
return the (recursive) number of members in this value
Definition at line 710 of file Value.cc.
References get_all_members_count(), get_cravel(), Cell::get_pointer_value(), get_rows(), Cell::is_pointer_cell(), and is_structured().
Referenced by get_all_members_count(), and sorted_members().
get_CDR_type()
CDR_type Value::get_CDR_type () const
return the CDR type for this value
Definition at line 2207 of file Value.cc.
References get_cfirst(), Cell::get_char_value(), get_cravel(), Cell::get_int_value(), Cell::is_character_cell(), Cell::is_complex_cell(), Cell::is_float_cell(), Cell::is_integer_cell(), Cell::is_numeric(), and nz_element_count().
Referenced by CDR::fill(), and Symbol::get_attributes().
get_cellrefs()
Value_P Value::get_cellrefs (const char * loc)
return a value containing pointers to all ravel cells of this value. the result is non-nested and has the same shape as this
Definition at line 454 of file Value.cc.
References element_count(), get_shape(), get_wproto(), and get_wravel().
get_cfirst()
const Cell & Value::get_cfirst () const inline
return the first element of the ravel (which is always present). same as get_cproto(), but named differently to indicate its context.
Definition at line 333 of file Value.hh.
References get_cravel().
Referenced by Quad_JSON::APL_to_JSON_string(), Quad_SYL::assign_indexed(), Symbol::assign_indexed(), Bif_COMMA::catenate_or_laminate(), LvalCell::check_consistency(), check_value(), compute_depth(), Bif_OPER1_EACH::do_eval_LB(), equal_string(), get_CDR_type(), get_offset(), get_single_axis(), get_sole_integer(), index(), is_char_array(), is_char_scalar(), is_character_scalar(), is_int_scalar(), is_numeric_scalar(), is_one_dimensional(), is_simple(), is_simple_scalar(), NOTCHAR(), print(), print_properties(), print_structure(), prototype(), Quad_GTK::resolve_window(), XML_Saving_Archive::save_Ravel(), Quad_PLOT::setup_data(), Token::show_trace(), and unmark().
get_col_spacing()
int32_t Value::get_col_spacing (bool & numeric, ShapeItem col, bool framed) const
get the min spacing for this column and set/clear if there is/isn't a numeric item in the column. are/ain't numeric items in col.
lrp p.138: S←⍴⍴A + NOTCHAR (per column)
Definition at line 2593 of file Value.cc.
References element_count(), get_cravel(), get_last_shape_item(), Cell::get_pointer_value(), Cell::is_character_cell(), and Cell::is_pointer_cell().
get_cols()
ShapeItem Value::get_cols () const inline
return the length of the last axis, or 1 for scalars
Definition at line 204 of file Value.hh.
References Shape::get_cols(), and shape.
Referenced by double_ravel(), get_member(), get_member_count(), is_structured(), and UCS_string_vector::UCS_string_vector().
get_cproto()
const Cell & Value::get_cproto () const inline
return the first element of the ravel (which is always present) same as get_first(), but named differently to indicate its context.
Definition at line 338 of file Value.hh.
References get_cravel().
Referenced by clone().
get_cravel()
const Cell & Value::get_cravel (ShapeItem idx) const inline
return the (constant) idx'th element of the ravel.
Definition at line 325 of file Value.hh.
References fetcher, nz_element_count(), and ravel.
Referenced by Stop_Trace::assign(), Quad_FC::assign_indexed(), Quad_PS::assign_indexed(), Quad_SYL::assign_indexed(), can_be_compared(), CDR_data_size(), check_Cells(), check_lval_consistency(), clone(), Command::cmd_CHECK(), compute_depth(), deep_cell_subtypes(), deep_cell_types(), enlist_left(), enlist_right(), equal_string(), CDR::fill(), flat_cell_subtypes(), flat_cell_types(), get_all_members_count(), get_CDR_type(), get_cfirst(), get_col_spacing(), get_cproto(), get_cscalar(), get_enlist_count(), get_lval_cellowner(), get_member_count(), get_member_data(), get_UCS_ravel(), index(), is_apl_char_vector(), is_complex(), is_int_array(), is_structured(), Quad_XML::name_unsplit(), Quad_XML::next_member(), NOTCHAR(), ConstRavel_P::operator*(), ConstRavel_P::operator->(), print_member(), Token::print_value(), Quad_GTK::resolve_window(), Quad_PLOT::setup_data_2D_2b(), sorted_members(), Quad_TF::tf2_toggle_UCS(), to_bitmap(), to_shape(), total_CDR_size_netto(), UCS_string_vector::UCS_string_vector(), and used_members().
get_cscalar()
const Cell & Value::get_cscalar () const inline
return the first element of the ravel of a scalar same as get_cfirst(), but named differently to indicate its context.
Definition at line 343 of file Value.hh.
References get_cravel().
Referenced by Quad_FIO::get_FILE(), Quad_FIO::get_file_entry(), and index().
get_enlist_count()
ShapeItem Value::get_enlist_count () const
Return the number of scalars in this value (enlist).
Definition at line 1300 of file Value.cc.
References element_count(), get_cravel(), Cell::get_lval_value(), Cell::get_pointer_value(), Cell::is_lval_cell(), and Cell::is_pointer_cell().
get_first_shape_item()
ShapeItem Value::get_first_shape_item () const inline
return the length of the last dimension of this value, i.e. ↑⍴this
Definition at line 196 of file Value.hh.
References Shape::get_first_shape_item(), and shape.
get_flags()
ValueFlags Value::get_flags () const inline
return the current flags
Definition at line 796 of file Value.hh.
References flags.
Referenced by Symbol::pop(), print_properties(), print_stale_info(), print_structure(), and XML_Saving_Archive::save_shape().
get_increment()
int Value::get_increment () const inline
return the increment for iterators of this value. The increment is used for scalar-extension of 1-element values
Definition at line 148 of file Value.hh.
References element_count().
get_last_shape_item()
ShapeItem Value::get_last_shape_item () const inline
return the length of the last dimension of this value, i.e. ¯1↑⍴this
Definition at line 200 of file Value.hh.
References Shape::get_last_shape_item(), and shape.
Referenced by get_col_spacing().
get_line_number()
Function_Line Value::get_line_number () const inline
return the first integer of a value (the line number of →Value).
Definition at line 247 of file Value.hh.
References ravel.
get_lval_cellowner()
Value * Value::get_lval_cellowner () const
return true iff this value is an lval (selective assignment) i.e. return true if at least one leaf value is an lval.
Definition at line 1037 of file Value.cc.
References LvalCell::get_cell_owner(), get_cravel(), Cell::get_pointer_value(), Cell::is_lval_cell(), Cell::is_pointer_cell(), and nz_element_count().
Referenced by is_simple_scalar().
get_member()
Cell * Value::get_member (const std::vector< const UCS_string * > & members, Value *& owner, bool create_if_needed, bool throw_error)
return member of this value, defined by members. The first name in members is the deepest, while the last name is the name of the variable containing the members (and is only used in error printouts).
Definition at line 612 of file Value.cc.
References UCS_string::back(), Value_P_Base::get(), get_cols(), get_member_data(), get_new_member(), Cell::get_pointer_value(), get_rank(), is_member(), Cell::is_pointer_cell(), and more().
Referenced by add_member().
get_member_count()
ShapeItem Value::get_member_count () const
return the number of (valid) members, as per this[1;]
Definition at line 886 of file Value.cc.
References get_cols(), get_cravel(), Cell::get_int_value(), Cell::get_pointer_value(), get_rows(), Cell::is_character_cell(), Cell::is_integer_cell(), and Cell::is_pointer_cell().
get_member_data() [1/2]
Cell * Value::get_member_data (const UCS_string & member)
return the Cell (if any) containing the data of structured value member member, or 0 if member not found.
Definition at line 860 of file Value.cc.
References UCS_string::FNV_hash(), get_cravel(), Cell::get_pointer_value(), get_rows(), get_wravel(), and Cell::is_pointer_cell().
get_member_data() [2/2]
const Cell * Value::get_member_data (const UCS_string & member) const
return the Cell (if any) containing the data of structured value member member, or 0 if member not found.
Definition at line 839 of file Value.cc.
References UCS_string::FNV_hash(), get_cravel(), Cell::get_pointer_value(), get_rows(), and Cell::is_pointer_cell().
Referenced by get_member(), index(), Quad_XML::next_member(), and Quad_JSON::parse_object_member().
get_new_member()
Cell * Value::get_new_member (const UCS_string & new_member)
create a new member and return the Cell containing the data for it
Definition at line 946 of file Value.cc.
References double_ravel(), UCS_string::FNV_hash(), Value_P_Base::get(), Cell::get_int_value(), get_rows(), get_wravel(), and Cell::is_integer_cell().
Referenced by double_ravel(), get_member(), and Quad_JSON::parse_object_member().
get_offset()
ShapeItem Value::get_offset (const Cell * cell) const inline
return the position of cell in the ravel of this value.
Definition at line 232 of file Value.hh.
References get_cfirst().
Referenced by XML_Saving_Archive::emit_cell().
get_owner_count()
int Value::get_owner_count () const inline
return the number of Value_P pointing to this value
Definition at line 471 of file Value.hh.
References owner_count.
Referenced by Token::value_use_count().
get_pointer()
Value * Value::get_pointer () inline protected
explicit cast from Value & to Value *. Use with care
Definition at line 988 of file Value.hh.
get_pointer_cell_count()
ShapeItem Value::get_pointer_cell_count () const inline
return the PointerCell count
Definition at line 838 of file Value.hh.
References pointer_cell_count.
Referenced by check_Cells(), and ~Value().
get_rank()
uRank Value::get_rank () const inline
return the rank of this value
Definition at line 184 of file Value.hh.
References Shape::get_rank(), and shape.
Referenced by Symbol::assign_indexed(), Bif_F12_PICK::compute_item_shape(), Quad_CR::do_CR36(), double_ravel(), equal_string(), CDR::fill(), get_member(), get_sole_integer(), index(), is_apl_char_vector(), is_char_scalar(), is_char_string(), is_char_vector(), is_int_scalar(), is_int_vector(), is_one_dimensional(), is_scalar_or_vector(), is_structured(), is_vector(), Quad_XML::name_unsplit(), print(), print1(), print_properties(), Token::print_value(), Quad_GTK::resolve_window(), same_rank(), same_shape(), XML_Saving_Archive::save_shape(), Quad_PLOT::setup_data(), Quad_PLOT::setup_data_2D_2b(), Token::show_trace(), to_bitmap(), and total_CDR_size_netto().
get_ravel_end()
const Cell * Value::get_ravel_end () const inline
return the next byte after the ravel
Definition at line 236 of file Value.hh.
References nz_element_count(), and ravel.
get_rows()
ShapeItem Value::get_rows () const inline
return the product of all but the the last axis, or 1 for scalars
Definition at line 208 of file Value.hh.
References Shape::get_rows(), and shape.
Referenced by double_ravel(), get_all_members_count(), get_member_count(), get_member_data(), get_new_member(), index(), is_structured(), print_member(), sorted_members(), UCS_string_vector::UCS_string_vector(), and used_members().
get_shape()
const Shape & Value::get_shape () const inline
return the shape of this value
Definition at line 188 of file Value.hh.
References shape.
Referenced by check_value(), clone(), get_cellrefs(), index(), list_one(), print_properties(), and print_structure().
get_shape_item()
ShapeItem Value::get_shape_item (sRank r) const inline
return the r'th shape element of this value
Definition at line 192 of file Value.hh.
References Shape::get_shape_item(), and shape.
Referenced by Symbol::assign_indexed(), Bif_F12_PICK::compute_item_shape(), CDR::fill(), index(), is_apl_char_vector(), is_scalar_or_len1_vector(), print_properties(), Token::print_value(), same_shape(), and XML_Saving_Archive::save_shape().
get_single_axis()
sRank Value::get_single_axis (const Value * val, sRank max_axis) static
If this value is a single axis between ⎕IO and ⎕IO + max_axis then return that axis. Otherwise throw AXIS_ERROR.
Definition at line 1856 of file Value.cc.
References get_cfirst(), Workspace::get_IO(), Cell::get_near_int(), Cell::is_near_int(), and is_scalar_or_len1_vector().
Referenced by Bif_OPER1_REDUCE::eval_ALXB(), Bif_OPER1_REDUCE1::eval_ALXB(), Bif_F12_PARTITION::eval_AXB(), Bif_OPER1_REDUCE::eval_AXB(), Bif_OPER1_REDUCE1::eval_AXB(), Bif_OPER1_SCAN::eval_AXB(), Bif_OPER1_SCAN1::eval_AXB(), Bif_F12_ROTATE::eval_AXB(), Bif_F12_ROTATE1::eval_AXB(), Quad_FX::eval_AXB(), Bif_OPER1_REDUCE::eval_LXB(), Bif_OPER1_REDUCE1::eval_LXB(), Bif_OPER1_SCAN::eval_LXB(), Bif_OPER1_SCAN1::eval_LXB(), Bif_F12_ROTATE::eval_XB(), and Bif_F12_ROTATE1::eval_XB().
get_sole_integer()
APL_Integer Value::get_sole_integer () const inline
return the integer of a value that is supposed to have (exactly) one
Definition at line 240 of file Value.hh.
References element_count(), get_cfirst(), Cell::get_near_int(), and get_rank().
get_UCS_ravel()
UCS_string Value::get_UCS_ravel () const
return the ravel of this value as UCS string, or throw DOMAIN error if the ravel contains non-char or nested cells.
Definition at line 2472 of file Value.cc.
References UCS_string::append(), element_count(), and get_cravel().
Referenced by Quad_PLOT::parse_attributes().
get_valid_item_count()
ShapeItem Value::get_valid_item_count () inline
return the number of (so far) initialized items
Definition at line 484 of file Value.hh.
References valid_ravel_items.
Referenced by ScalarFunction::expand_nested().
get_wfirst()
Cell & Value::get_wfirst () inline
return the first element of the ravel (which is always present) Same as get_wproto() and get_wscalar(), but named differently to indicate its context.
Definition at line 353 of file Value.hh.
References get_wravel().
Referenced by ~Value().
get_wproto()
Cell & Value::get_wproto () inline
return the first element of the ravel (which is always present) same as wfirst(), but named differently to indicate its context.
Definition at line 363 of file Value.hh.
References get_wravel().
Referenced by get_cellrefs(), init_ravel(), and Value().
get_wravel()
Cell & Value::get_wravel (ShapeItem idx) inline
return the (writable) idx'th element of the ravel.
Definition at line 347 of file Value.hh.
References nz_element_count(), and ravel.
Referenced by assign_cellrefs(), Bif_F12_ENCODE::encode_Cpx(), Bif_F12_ENCODE::encode_Flt(), Bif_F12_ENCODE::encode_Int(), ScalarFunction::expand_nested(), get_cellrefs(), get_member_data(), get_new_member(), get_wfirst(), get_wproto(), get_wscalar(), XML_Loading_Archive::read_Cells(), and to_type().
get_wscalar()
Cell & Value::get_wscalar () inline
return the first element of the ravel of a scalar value. Same as get_wfirst(), but named differently to indicate its context.
Definition at line 358 of file Value.hh.
References get_wravel().
Referenced by assign_cellrefs().
glue()
void Value::glue (Token & token, Token & token_A, Token & token_B, const char * loc) static
glue two values.
Definition at line 1949 of file Value.cc.
References Token::get_apl_val(), Token::get_tag(), glue(), glue_closed_closed(), glue_closed_strand(), glue_strand_closed(), and glue_strand_strand().
Referenced by glue().
glue_closed_closed()
void Value::glue_closed_closed (Token & result, Value_P A, Value_P B, const char * loc) static
glue closed A and closed B
Definition at line 2048 of file Value.cc.
Referenced by glue().
glue_closed_strand()
void Value::glue_closed_strand (Token & result, Value_P A, Value_P B, const char * loc) static
glue closed A and closed B
Definition at line 2023 of file Value.cc.
Referenced by glue().
glue_strand_closed()
void Value::glue_strand_closed (Token & result, Value_P A, Value_P B, const char * loc) static
glue strands A and strand B
Definition at line 1999 of file Value.cc.
Referenced by glue().
glue_strand_strand()
void Value::glue_strand_strand (Token & result, Value_P A, Value_P B, const char * loc) static
glue strands A and B
Definition at line 1970 of file Value.cc.
Referenced by glue().
increment_owner_count()
void Value::increment_owner_count (const char * loc) inline
increment the number of (smart-) pointers to this value
Definition at line 846 of file Value.hh.
References check_ptr, and owner_count.
increment_pointer_cell_count()
void Value::increment_pointer_cell_count () inline
increment the PointerCell count
Definition at line 830 of file Value.hh.
References pointer_cell_count.
Referenced by PointerCell::PointerCell().
index() [1/2]
Value_P Value::index (const IndexExpr & IDX) const
return this indexed by (multi-dimensional) IDX.
Definition at line 1645 of file Value.cc.
References Shape::add_shape_item(), IndexExpr::check_index_range(), Value_P_Base::get(), get_cravel(), Workspace::get_IO(), IndexExpr::get_rank(), get_rank(), get_rows(), get_shape(), get_shape_item(), IndexExpr::is_axis(), is_member(), MultiIndexIterator::more(), and IndexExpr::values.
index() [2/2]
Value_P Value::index (const Value * X) const
return this indexed by (one-dimensional) IDX.
Definition at line 1765 of file Value.cc.
References element_count(), get_cfirst(), get_cravel(), get_cscalar(), Workspace::get_IO(), get_member_data(), Cell::get_near_int(), Cell::get_pointer_value(), get_rank(), get_rows(), get_shape(), is_member(), Cell::is_pointer_cell(), is_scalar(), and more().
init()
void Value::init () static
initialize value related variables and print some statistics.
Definition at line 1096 of file Value.cc.
Referenced by assign_cellrefs().
init_ravel()
void Value::init_ravel () inline protected
init the ravel of an APL value, return the ravel length
Definition at line 68 of file Value.cc.
References DynamicObject::alloc_loc, alloc_size, cell_fetcher(), check_ptr, fetcher, Workspace::get_IO(), Shape::get_volume(), get_wproto(), nz_subcell_count, owner_count, pointer_cell_count, ravel, Quad_SYL::ravel_count_limit, shape, short_value, total_ravel_count, value_count, Quad_SYL::value_count_limit, IntCell::z0(), and IntCell::zI().
Referenced by Value().
is_apl_char_vector()
bool Value::is_apl_char_vector () const
return true iff this value is a simple character vector containing only APL characters (from ⎕AV)
Definition at line 1406 of file Value.cc.
References Avec::find_char(), Cell::get_char_value(), get_cravel(), get_rank(), and get_shape_item().
is_char_array()
bool Value::is_char_array () const
return true iff all ravel elements of this value are characters
Definition at line 1423 of file Value.cc.
References get_cfirst(), and nz_element_count().
Referenced by is_char_string(), and is_char_vector().
is_char_scalar()
bool Value::is_char_scalar () const inline
return true iff this value is a simple character scalar.
Definition at line 168 of file Value.hh.
References get_cfirst(), get_rank(), and Cell::is_character_cell().
is_char_string()
bool Value::is_char_string () const inline
return true iff this value is a simple character scalar or vector.
Definition at line 153 of file Value.hh.
References get_rank(), and is_char_array().
Referenced by Quad_CR::do_CR10_structured(), Stop_Trace::locate_fun(), and Quad_PLOT::parse_attributes().
is_char_vector()
bool Value::is_char_vector () const inline
return true iff this value is a simple character vector.
Definition at line 157 of file Value.hh.
References get_rank(), and is_char_array().
Referenced by Quad_JSON::APL_to_JSON_string().
is_character_scalar()
bool Value::is_character_scalar () const inline
return true iff this value is a character scalar
Definition at line 127 of file Value.hh.
References get_cfirst(), Cell::is_character_cell(), and is_scalar().
is_complete()
bool Value::is_complete () const inline
true if Value flag complete is set
Definition at line 669 of file Value.hh.
References flags.
Referenced by list_one(), print_properties(), and set_shape().
is_complex()
bool Value::is_complex (bool check_numeric) const
return true, if this value has complex cells, false iff it has only real cells. Throw domain error for other cells (char, nested etc.) if check_numeric is true.
Definition at line 1458 of file Value.cc.
References get_cravel(), Cell::is_near_real(), Cell::is_numeric(), and nz_element_count().
is_empty()
bool Value::is_empty () const inline
return true iff this value is empty (some dimension is 0).
Definition at line 119 of file Value.hh.
References Shape::is_empty(), and shape.
Referenced by Quad_TF::tf2_toggle_UCS().
is_int_array()
bool Value::is_int_array () const
return true iff this value is a (simple) integer array, allowing near-int values (but NOT necessatily values within ⎕CT of an integers).
Definition at line 1446 of file Value.cc.
References get_cravel(), and nz_element_count().
Referenced by is_int_vector().
is_int_scalar()
bool Value::is_int_scalar () const inline
return true iff this value is a simple integer scalar.
Definition at line 172 of file Value.hh.
References get_cfirst(), get_rank(), and Cell::is_near_int().
Referenced by Quad_PS::assign_indexed(), and Quad_SYL::assign_indexed().
is_int_vector()
bool Value::is_int_vector () const inline
return true iff this value is a (simple) integer vector.
Definition at line 263 of file Value.hh.
References get_rank(), and is_int_array().
Referenced by Quad_PS::assign_indexed(), and Quad_SYL::assign_indexed().
is_marked()
bool Value::is_marked () const inline
true if Value flag marked is set
Definition at line 684 of file Value.hh.
References flags.
Referenced by list_one(), print_properties(), and XML_Saving_Archive::save().
is_member()
bool Value::is_member () const inline
true if Value flag member is set
Definition at line 642 of file Value.hh.
References flags.
Referenced by double_ravel(), get_member(), index(), PointerCell::is_member_anchor(), is_structured(), list_one(), print(), and print_properties().
is_numeric_scalar()
bool Value::is_numeric_scalar () const inline
return true iff this value is a numeric scalar.
Definition at line 123 of file Value.hh.
References get_cfirst(), Cell::is_numeric(), and is_scalar().
is_one_dimensional()
bool Value::is_one_dimensional () const
return true iff this value and its ravel items have rank < 2
Definition at line 1533 of file Value.cc.
References get_cfirst(), get_rank(), and nz_element_count().
is_or_contains()
bool Value::is_or_contains (const Value * val, const Value * sub) static
returen true if sub == val or sub is contained in val
Definition at line 1067 of file Value.cc.
References is_or_contains().
Referenced by is_or_contains(), Executable::show_owners(), Prefix::show_owners(), and Symbol::show_owners().
is_packed()
bool Value::is_packed () const inline
true if Value flag packed is set
Definition at line 657 of file Value.hh.
References flags.
Referenced by ConstCell_P::ConstCell_P(), explode(), list_one(), next_ravel_byte(), print_properties(), XML_Loading_Archive::read_Cells(), XML_Saving_Archive::save_Ravel(), try_implode(), and unmark().
is_scalar()
bool Value::is_scalar () const inline
return true iff this value is a scalar.
Definition at line 110 of file Value.hh.
References Shape::get_rank(), and shape.
Referenced by Quad_JSON::APL_to_JSON_string(), assign_cellrefs(), Symbol::assign_indexed(), compute_depth(), Bif_OPER1_EACH::do_eval_LB(), index(), is_character_scalar(), is_numeric_scalar(), is_scalar_or_len1_vector(), and is_simple_scalar().
is_scalar_extensible()
bool Value::is_scalar_extensible () const inline
return true iff this value can be scalar-extended
Definition at line 143 of file Value.hh.
References element_count().
Referenced by scalar_matching_shape().
is_scalar_or_len1_vector()
bool Value::is_scalar_or_len1_vector () const inline
return true iff this value is a scalar or vector of length 1.
Definition at line 139 of file Value.hh.
References get_shape_item(), is_scalar(), and is_vector().
Referenced by Bif_COMMA::catenate_or_laminate(), and get_single_axis().
is_scalar_or_vector()
bool Value::is_scalar_or_vector () const inline
return true iff this value is a scalar or vector
Definition at line 131 of file Value.hh.
References get_rank().
is_simple()
bool Value::is_simple () const
return true iff this value is simple (i.e. not nested).
Definition at line 1515 of file Value.cc.
References element_count(), flags, and get_cfirst().
is_simple_scalar()
bool Value::is_simple_scalar () const inline
return true iff this value is a simple (i.e. depth 0) scalar.
Definition at line 114 of file Value.hh.
References get_cfirst(), get_lval_cellowner(), Cell::is_pointer_cell(), and is_scalar().
Referenced by Bif_OPER1_EACH::do_eval_LB(), and PointerCell::PointerCell().
is_structured()
bool Value::is_structured () const
return true if this variable is is_member() and a N×2 matrix with proper keys
Definition at line 1103 of file Value.cc.
References get_cols(), get_cravel(), get_rank(), get_rows(), and is_member().
Referenced by add_member(), Quad_XML::all_members(), get_all_members_count(), Quad_XML::next_member(), sorted_members(), and used_members().
is_vector()
bool Value::is_vector () const inline
return true iff this value is a vector.
Definition at line 135 of file Value.hh.
References get_rank().
Referenced by is_scalar_or_len1_vector().
list_all()
ostream & Value::list_all (ostream & out, bool show_owners) static
list all values
Definition at line 1286 of file Value.cc.
References DynamicObject::all_values, and DynamicObject::get_prev().
list_one()
ostream & Value::list_one (ostream & out, bool show_owners) const
list a value
Definition at line 1253 of file Value.cc.
References compute_depth(), flags, get_shape(), is_complete(), is_marked(), is_member(), is_packed(), print(), and Workspace::show_owners().
Referenced by erase_stale().
mark_all_dynamic_values()
void Value::mark_all_dynamic_values () static
mark all values, except static values
Definition at line 1145 of file Value.cc.
References DynamicObject::all_values, and DynamicObject::get_prev().
Referenced by print_stale(), and XML_Saving_Archive::save().
more()
bool Value::more () const inline
return true iff more ravel items (as per shape) need to be initialized. (the prototype of empty values may still be missing)
Definition at line 480 of file Value.hh.
References element_count(), and valid_ravel_items.
Referenced by Cell::copy(), current_ravel(), get_member(), index(), next_ravel(), next_ravel_byte(), and rollback().
next_ravel()
Cell * Value::next_ravel () inline protected
return the next ravel cell to be initialized (excluding prototype)
Definition at line 896 of file Value.hh.
References more(), ravel, and valid_ravel_items.
next_ravel_byte()
uint8_t * Value::next_ravel_byte () inline protected
return the next (packed) byte position
Definition at line 900 of file Value.hh.
References is_packed(), more(), ravel, and valid_ravel_items.
NOTCHAR()
bool Value::NOTCHAR () const
return the NOTCHAR property of the value. NOTCHAR is false for simple char arrays and true if any element is numeric or nested. The NOTCHAR property of empty arrays is the NOTCHAR property of its prototype. see also lrm p. 138.
Definition at line 1432 of file Value.cc.
References element_count(), get_cfirst(), and get_cravel().
nz_element_count()
ShapeItem Value::nz_element_count () const inline
return the number of elements, but at least 1 (for the prototype).
Definition at line 180 of file Value.hh.
References Shape::get_nz_volume(), and shape.
Referenced by assign_cellrefs(), can_be_compared(), CDR_data_size(), check_Cells(), LvalCell::check_consistency(), check_lval_consistency(), check_value(), clone(), Command::cmd_CHECK(), compute_depth(), deep_cell_subtypes(), deep_cell_types(), flat_cell_subtypes(), flat_cell_types(), get_CDR_type(), get_cravel(), get_lval_cellowner(), get_ravel_end(), get_wravel(), is_char_array(), is_complex(), is_int_array(), is_one_dimensional(), PointerCell::PointerCell(), print_structure(), XML_Saving_Archive::save_Ravel(), set_shape(), Quad_TF::tf2_toggle_UCS(), to_type(), total_CDR_size_netto(), try_implode(), unmark(), and ~Value().
operator delete()
static void Value::operator delete (void * ptr) inline static protected
free space for a new Value
Definition at line 971 of file Value.hh.
References deleted_values, deleted_values_count, and DynamicObject::next.
operator new()
static void * Value::operator new (size_t sz) inline static protected
allocate space for a new Value. For performance reasons, a pool of deleted_values_MAX is kept and Value objects in that pool are reused before calling new().
Definition at line 955 of file Value.hh.
References deleted_values, deleted_values_count, fast_new_count, _deleted_value::next, and slow_new_count.
operator&()
Value * Value::operator& () inline private
restrict use of & (which is frequently a mistake)
Definition at line 998 of file Value.hh.
packed_fetcher()
static const Cell & Value::packed_fetcher (ShapeItem offset, const Cell * ravel) inline static
return the offset'th ravel cell (of an pack'ed ravel)
Definition at line 444 of file Value.hh.
References IntCell::boolean_FALSE, IntCell::boolean_TRUE, and ravel.
print()
ostream & Value::print (ostream & out) const
print this value (line break at Workspace::get_PW())
Definition at line 2270 of file Value.cc.
References element_count(), get_cfirst(), Workspace::get_PrintContext(), get_rank(), PrintContext::get_style(), is_member(), print_member(), and PrintContext::set_style().
Referenced by check_value(), and list_one().
print1()
ostream & Value::print1 (ostream & out, PrintContext pctx) const
print this value (line break at print_width)
Definition at line 2386 of file Value.cc.
References get_rank(), PrintContext::get_style(), and PrintContext::set_style().
print_boxed()
ostream & Value::print_boxed (ostream & out, int indent) const
print this value in 4 ⎕CR style
Definition at line 2453 of file Value.cc.
References Quad_CR::do_CR().
print_incomplete()
int Value::print_incomplete (ostream & out) static
print incomplete Values, and return the number of incomplete Values.
Definition at line 2642 of file Value.cc.
References DynamicObject::all_values, and DynamicObject::get_prev().
Referenced by IO_Files::end_of_current_file().
print_member()
ostream & Value::print_member (ostream & out, UCS_string member) const
print this member value
Definition at line 2299 of file Value.cc.
References UCS_string::append(), Bif_F12_PICK::disclose(), Quad_CR::do_CR35(), Value_P_Base::get(), get_cravel(), Cell::get_pointer_value(), get_rows(), Cell::is_pointer_cell(), Cell::release(), UCS_string::size(), and IntCell::z0().
Referenced by print().
print_properties()
ostream & Value::print_properties (ostream & out, int indent, bool help) const
print the properties (shape, flags etc) of this value
Definition at line 2405 of file Value.cc.
References compute_depth(), deep_cell_types(), get_cfirst(), get_flags(), get_rank(), get_shape(), get_shape_item(), is_complete(), is_marked(), is_member(), is_packed(), and DynamicObject::print().
Referenced by Symbol::print_verbose().
print_stale()
int Value::print_stale (ostream & out) static
print stale Values, and return the number of stale Values.
Definition at line 2683 of file Value.cc.
References DynamicObject::all_values, DynamicObject::get_prev(), mark_all_dynamic_values(), print_stale_info(), Macro::unmark_all_macros(), and Workspace::unmark_all_values().
Referenced by Command::cmd_CHECK(), and IO_Files::end_of_current_file().
print_stale_info()
void Value::print_stale_info (ostream & out, const DynamicObject * dob) const
print info related to a stale value
Definition at line 2766 of file Value.cc.
References Quad_CR::do_CR(), get_flags(), VH_entry::print_history(), print_structure(), DynamicObject::rValue(), and DynamicObject::where_allocated().
Referenced by print_stale().
print_structure()
void Value::print_structure (ostream & out, int indent, ShapeItem idx) const
print address, shape, and flags of this value
Definition at line 2503 of file Value.cc.
References compute_depth(), get_cfirst(), get_flags(), get_shape(), nz_element_count(), and DynamicObject::where_allocated().
Referenced by print_stale_info().
prototype()
Value_P Value::prototype (const char * loc) const
the prototype of this value
lrm p.46:
The type of an array is an array with the same structure, but with all numbers replaced with 0 and all characters replaced with ' '.
The prototype of an array is the type of the first element of the array.
type B ←→ ↑0⍴⊂B prototype B ←→ ↑0⍴⊂↑B
Since ↑B is a scalar the prototype of B is also a scalar.
Definition at line 2560 of file Value.cc.
References get_cfirst(), Cell::get_pointer_value(), Cell::is_character_cell(), Cell::is_integer_cell(), and Cell::is_pointer_cell().
rollback()
void Value::rollback (ShapeItem items, const char * loc)
rollback initialization of this value
Definition at line 1170 of file Value.cc.
References DynamicObject::alloc_loc, more(), and next_ravel_0().
same_rank()
bool Value::same_rank (const Value & other) const inline
return true iff this value has the same rank as other.
Definition at line 590 of file Value.hh.
References get_rank().
same_shape()
bool Value::same_shape (const Value & other) const inline
return true iff this value has the same shape as other.
Definition at line 594 of file Value.hh.
References get_rank(), and get_shape_item().
Referenced by scalar_matching_shape().
scalar_matching_shape()
bool Value::scalar_matching_shape (const Value & other) const inline
return true iff this value has the same shape as other or one of the values is a scalar
Definition at line 603 of file Value.hh.
References is_scalar_extensible(), and same_shape().
SET_complete()
void Value::SET_complete () const inline
set the Value flag complete
Definition at line 664 of file Value.hh.
References flags.
SET_marked()
void Value::SET_marked () const inline
set the Value flag marked
Definition at line 674 of file Value.hh.
References flags.
SET_member()
void Value::SET_member () const inline
set the Value flag member
Definition at line 637 of file Value.hh.
References flags.
SET_packed()
void Value::SET_packed () const inline
set the Value flag packed
Definition at line 647 of file Value.hh.
References flags.
set_shape()
void Value::set_shape (const Shape & new_shape) inline
reshape this value in place. This is generally dangerous and only permitted if:
this value has been initialized completely, and
the new shape has not more items than this value.
If this value is empty, then (due to its prototype) reshaping it to volume 1 is permitted.
The caller is responsible for ensuring that this value does not have multiple owners.
Definition at line 227 of file Value.hh.
References Shape::get_volume(), is_complete(), nz_element_count(), and shape.
set_shape_item()
void Value::set_shape_item (sAxis r, ShapeItem sh) inline
set the length of axis r to sh.
Definition at line 212 of file Value.hh.
References Shape::set_shape_item(), and shape.
sorted_members()
void Value::sorted_members (std::vector< ShapeItem > & result, const Unicode * filter) const
store the row numbers (starting at 0) so that this[rows] is sorted in result. Only used rows are returned.
Definition at line 776 of file Value.cc.
References get_all_members_count(), get_cravel(), Cell::get_pointer_value(), get_rows(), Cell::is_pointer_cell(), is_structured(), and Quad_XML::split_name().
Referenced by Quad_XML::next_member().
to_bitmap()
AxesBitmap Value::to_bitmap (const char * where, uRank rank_B) const
return a bitmap of integers in this value. Normalized to ⎕IO←0.
Definition at line 1893 of file Value.cc.
References element_count(), get_cravel(), Workspace::get_IO(), Cell::get_near_int(), get_rank(), and Cell::is_near_int().
to_shape()
Shape Value::to_shape (const Value * val) static
convert the ravel of Value val to a shape (normalized to ⎕IO←0) An elided index, for example B[], throws an INDEX_ERROR.
Definition at line 1874 of file Value.cc.
References Shape::add_shape_item(), element_count(), get_cravel(), Workspace::get_IO(), Cell::get_near_int(), and shape.
Referenced by Bif_F12_PARTITION::eval_XB(), and Bif_F12_PICK::eval_XB().
to_type()
void Value::to_type (bool force_numeric)
recursively replace all numeric ravel elements with 0 and all characters with blank. See lrm p. 46.
Definition at line 2483 of file Value.cc.
References Cell::get_pointer_value(), get_wravel(), Cell::is_character_cell(), Cell::is_pointer_cell(), nz_element_count(), set_ravel_Char(), and set_ravel_Int().
Referenced by Quad_TF::tf2_toggle_UCS().
total_CDR_size_brutto()
int Value::total_CDR_size_brutto (CDR_type cdr_type) const inline
return the total CDR size (header + data + padding) for this value.
Definition at line 761 of file Value.hh.
References total_CDR_size_netto().
Referenced by CDR::fill(), and Symbol::get_attributes().
total_CDR_size_netto()
int Value::total_CDR_size_netto (CDR_type cdr_type) const
return the total CDR size in bytes (header + data), not including any padding for this value.
Definition at line 2129 of file Value.cc.
References CDR_data_size(), get_cravel(), Cell::get_pointer_value(), get_rank(), Cell::is_pointer_cell(), Cell::is_simple_cell(), and nz_element_count().
Referenced by total_CDR_size_brutto().
try_implode()
const char * Value::try_implode ()
try to implode (pack) this unpacked value. Return 0 on success or reason on error;
Definition at line 2853 of file Value.cc.
References flags, is_packed(), nz_element_count(), pointer_cell_count, ravel, and short_value.
unmark()
void Value::unmark () const
clear marked flag on this value and its nested sub-values
Definition at line 1155 of file Value.cc.
References get_cfirst(), is_packed(), and nz_element_count().
Referenced by XML_Saving_Archive::save(), and Symbol::unmark_all_values().
used_members()
void Value::used_members (std::vector< ShapeItem > & result, bool sorted) const
store the row numbers (starting at 0) in result so that this[rows] is a (used) row, maybe sorted. in result. Only used rows are returned.
Definition at line 736 of file Value.cc.
References get_cravel(), get_rows(), Cell::is_pointer_cell(), and is_structured().
Friends And Related Function Documentation
PJob_scalar_AB
friend class PJob_scalar_AB friend
Definition at line 63 of file Value.hh.
PJob_scalar_B
friend class PJob_scalar_B friend
Definition at line 64 of file Value.hh.
PointerCell
friend class PointerCell friend
Definition at line 62 of file Value.hh.
Value_P
friend class Value_P friend
Definition at line 60 of file Value.hh.
Value_P_Base
friend class Value_P_Base friend
Definition at line 61 of file Value.hh.
Member Data Documentation
alloc_size
uint64_t Value::alloc_size = 0 static protected
the size of the next allocation
Definition at line 945 of file Value.hh.
Referenced by catch_exception(), and init_ravel().
check_ptr
const void* Value::check_ptr
a "checksum" to detect deleted values
Definition at line 827 of file Value.hh.
Referenced by decrement_owner_count(), increment_owner_count(), init_ravel(), Value(), and ~Value().
deleted_values
_deleted_value * Value::deleted_values = 0 static protected
a linked list of values that have been deleted
Definition at line 939 of file Value.hh.
Referenced by operator delete(), and operator new().
deleted_values_count
int Value::deleted_values_count = 0 static protected
number values that have been deleted
Definition at line 942 of file Value.hh.
Referenced by operator delete(), and operator new().
fast_new_count
uint64_t Value::fast_new_count = 0 static
the number of fast (recycled) new() calls
Definition at line 886 of file Value.hh.
Referenced by Quad_FIO::eval_B(), and operator new().
fetcher
const Cell &(* Value::fetcher) (ShapeItem offset, const Cell *ravel) protected
mux between packed and non-packed ravel cells
Definition at line 915 of file Value.hh.
Referenced by explode(), get_cravel(), and init_ravel().
flags
uint16_t Value::flags mutable protected
valueFlags for this value.
Definition at line 924 of file Value.hh.
Referenced by CLEAR_marked(), CLEAR_packed(), clone(), flag_info(), get_flags(), is_complete(), is_marked(), is_member(), is_packed(), is_simple(), list_one(), SET_complete(), SET_marked(), SET_member(), SET_packed(), try_implode(), and ~Value().
nz_subcell_count
ShapeItem Value::nz_subcell_count protected
the number of cells in nested sub-values
Definition at line 930 of file Value.hh.
Referenced by add_subcount(), and init_ravel().
owner_count
int Value::owner_count protected
number of Value_P objects pointing to this value
Definition at line 918 of file Value.hh.
Referenced by decrement_owner_count(), erase_stale(), get_owner_count(), increment_owner_count(), and init_ravel().
pointer_cell_count
ShapeItem Value::pointer_cell_count protected
the value that has a PointerCell pointing to this value (if any)
Definition at line 921 of file Value.hh.
Referenced by check_Cells(), decrement_pointer_cell_count(), get_pointer_cell_count(), increment_pointer_cell_count(), init_ravel(), and try_implode().
ravel
Cell* Value::ravel protected
The ravel of this value.
Definition at line 933 of file Value.hh.
Referenced by cell_fetcher(), current_ravel(), double_ravel(), explode(), get_cravel(), get_line_number(), get_ravel_end(), get_wravel(), init_ravel(), next_ravel(), next_ravel_byte(), packed_fetcher(), try_implode(), Value(), and ~Value().
shape
Shape Value::shape protected
the shape of this value (only the first rank values are valid.
Definition at line 912 of file Value.hh.
Referenced by double_ravel(), element_count(), get_cols(), get_first_shape_item(), get_last_shape_item(), get_rank(), get_rows(), get_shape(), get_shape_item(), init_ravel(), is_empty(), is_scalar(), nz_element_count(), set_shape(), set_shape_item(), and to_shape().
short_value
Cell Value::short_value[12] protected
the cells of a short (i.e. ⍴,value ≤ SHORT_VALUE_LENGTH_WANTED) value
Definition at line 936 of file Value.hh.
Referenced by double_ravel(), init_ravel(), try_implode(), and ~Value().
slow_new_count
uint64_t Value::slow_new_count = 0 static
the number of slow (malloc() based) new() calls
Definition at line 889 of file Value.hh.
Referenced by Quad_FIO::eval_B(), and operator new().
total_ravel_count
uint64_t Value::total_ravel_count = 0 static
total nz_element_counts of all non-short values
Definition at line 821 of file Value.hh.
Referenced by Quad_SYL::assign_indexed(), catch_exception(), check_WS_FULL(), Quad_WA::get_apl_value(), init_ravel(), and ~Value().
valid_ravel_items
ShapeItem Value::valid_ravel_items protected
number of initialized cells in the ravel
Definition at line 927 of file Value.hh.
Referenced by check_value(), current_ravel(), double_ravel(), get_valid_item_count(), more(), next_ravel(), and next_ravel_byte().
value_count
uint64_t Value::value_count = 0 static
the number of values created
Definition at line 824 of file Value.hh.
Referenced by assign_cellrefs(), Quad_SYL::assign_indexed(), catch_exception(), check_WS_FULL(), Quad_WA::get_apl_value(), init_ravel(), and ~Value().
The documentation for this class was generated from the following files:
src/Value.hh
src/Value.cc