GNU APL: ArrayIterator Class Reference
ArrayIterator Class Reference
An iterator counting along all axes of shape.
#include <ArrayIterator.hh>
Public Member Functions
ArrayIterator (const Shape &shape)
constructor from Shape
ArrayIterator (const Shape &shape, const Shape &perm)
constructor from Shape and axis permutation
bool more () const
return true iff this iterator has more items to come.
void operator++ ()
the work-horse of this iterator.
ShapeItem get_shape_offset (sAxis a) const
Get the current offset for axis r.
ShapeItem get_ravel_offset () const
Get the current total offset.
Shape get_shape_offsets ()
return the offsets of the axis_iterators as a shape
Protected Member Functions
const AxisIterator & get_iterator (sAxis a) const
return the iterator for axis a
AxisIterator & get_iterator (sAxis a)
return the iterator for axis a
Protected Attributes
const uRank rank
the number of valid axes (= iterators).
ShapeItem total_ravel_offset
the sum of the ravel offsets of all iterators
AxisIterator axis_iterators [MAX_RANK]
Detailed Description
An iterator counting along all axes of shape.
Definition at line 110 of file ArrayIterator.hh.
Constructor & Destructor Documentation
ArrayIterator() [1/2]
ArrayIterator::ArrayIterator (const Shape & shape) inline
constructor from Shape
Definition at line 114 of file ArrayIterator.hh.
References get_iterator(), Shape::get_shape_item(), and rank.
ArrayIterator() [2/2]
ArrayIterator::ArrayIterator (const Shape & shape, const Shape & perm) inline
constructor from Shape and axis permutation
Definition at line 137 of file ArrayIterator.hh.
References get_iterator(), Shape::get_shape_item(), and rank.
Member Function Documentation
get_iterator() [1/2]
AxisIterator & ArrayIterator::get_iterator (sAxis a) inline protected
return the iterator for axis a
Definition at line 213 of file ArrayIterator.hh.
References axis_iterators.
get_iterator() [2/2]
const AxisIterator & ArrayIterator::get_iterator (sAxis a) const inline protected
return the iterator for axis a
Definition at line 209 of file ArrayIterator.hh.
References axis_iterators.
Referenced by ArrayIterator(), get_shape_offset(), get_shape_offsets(), more(), and operator++().
get_ravel_offset()
ShapeItem ArrayIterator::get_ravel_offset () const inline
Get the current total offset.
Definition at line 195 of file ArrayIterator.hh.
References total_ravel_offset.
get_shape_offset()
ShapeItem ArrayIterator::get_shape_offset (sAxis a) const inline
Get the current offset for axis r.
Definition at line 191 of file ArrayIterator.hh.
References get_iterator(), and AxisIterator::get_shape_offset().
Referenced by get_shape_offsets().
get_shape_offsets()
Shape ArrayIterator::get_shape_offsets () inline
return the offsets of the axis_iterators as a shape
Definition at line 199 of file ArrayIterator.hh.
References Shape::add_shape_item(), get_iterator(), get_shape_offset(), and rank.
more()
bool ArrayIterator::more () const inline
return true iff this iterator has more items to come.
Definition at line 167 of file ArrayIterator.hh.
References get_iterator(), and AxisIterator::more().
Referenced by Bif_F2_FIND::contained(), Bif_F12_PARTITION::enclose_with_axes(), Bif_F2_FIND::eval_AB(), ScalarFunction::eval_scalar_AXB(), Bif_F12_TRANSPOSE::transpose(), and Bif_F12_TRANSPOSE::transpose_diag().
operator++()
void ArrayIterator::operator++ () inline
the work-horse of this iterator.
Definition at line 173 of file ArrayIterator.hh.
References get_iterator(), AxisIterator::get_total_weight(), AxisIterator::get_weight(), AxisIterator::next(), rank, and total_ravel_offset.
Member Data Documentation
axis_iterators
AxisIterator ArrayIterator::axis_iterators[MAX_RANK] protected
axis iterators. Shape: ⊏sh0:sh1:..:shN⊐ │ │ │ axis_iterators[0] ←→ get_shape_item(0), ─────┘ │ └── weight 1 axis_iterators[1] ←→ get_shape_item(1), ─────────┘ ...
Definition at line 227 of file ArrayIterator.hh.
Referenced by get_iterator().
rank
const uRank ArrayIterator::rank protected
the number of valid axes (= iterators).
Definition at line 217 of file ArrayIterator.hh.
Referenced by ArrayIterator(), get_shape_offsets(), and operator++().
total_ravel_offset
ShapeItem ArrayIterator::total_ravel_offset protected
the sum of the ravel offsets of all iterators
Definition at line 220 of file ArrayIterator.hh.
Referenced by get_ravel_offset(), and operator++().
The documentation for this class was generated from the following file:
src/ArrayIterator.hh