GNU APL: Statistics Class Reference
Statistics Class Reference abstract
Base class for different kinds of statistics.
#include <Performance.hh>
Public Member Functions
Statistics (Pfstat_ID _id)
constructor
virtual ~Statistics ()
destructor
virtual void print (ostream &out)=0
print statistics
virtual void save_data (ostream &outf, const char *perf_name)=0
write statistics to file
virtual void reset ()=0
reset this statistics
virtual const Statistics_record * get_first_record () const
return the statistics for the first passes
virtual const Statistics_record * get_record () const
return the statistics for the subsequent passes
const char * get_name () const
return the name of this statistics
Static Public Member Functions
static const char * get_name (Pfstat_ID id)
return the name of the statistics with ID id
Protected Attributes
const Pfstat_ID id
the ID of this statistics
Detailed Description
Base class for different kinds of statistics.
Definition at line 160 of file Performance.hh.
Constructor & Destructor Documentation
Statistics()
Statistics::Statistics (Pfstat_ID _id) inline
constructor
Definition at line 164 of file Performance.hh.
~Statistics()
Statistics::~Statistics () virtual
destructor
Definition at line 48 of file Performance.cc.
Member Function Documentation
get_first_record()
virtual const Statistics_record * Statistics::get_first_record () const inline virtual
return the statistics for the first passes
Reimplemented in CellFunctionStatistics.
Definition at line 181 of file Performance.hh.
Referenced by Quad_FIO::eval_XB().
get_name() [1/2]
const char * Statistics::get_name () const inline
return the name of this statistics
Definition at line 189 of file Performance.hh.
References get_name().
Referenced by Quad_FIO::eval_XB(), get_name(), FunctionStatistics::print(), and CellFunctionStatistics::print().
get_name() [2/2]
const char * Statistics::get_name (Pfstat_ID id) static
return the name of the statistics with ID id
Definition at line 91 of file Performance.cc.
get_record()
virtual const Statistics_record * Statistics::get_record () const inline virtual
return the statistics for the subsequent passes
Reimplemented in FunctionStatistics, and CellFunctionStatistics.
Definition at line 185 of file Performance.hh.
Referenced by Quad_FIO::eval_XB().
print()
virtual void Statistics::print (ostream & out) pure virtual
print statistics
Implemented in FunctionStatistics, and CellFunctionStatistics.
Referenced by Performance::print().
reset()
virtual void Statistics::reset () pure virtual
reset this statistics
Implemented in FunctionStatistics, and CellFunctionStatistics.
Referenced by Quad_FIO::eval_XB().
save_data()
virtual void Statistics::save_data (ostream & outf, const char * perf_name) pure virtual
write statistics to file
Implemented in FunctionStatistics, and CellFunctionStatistics.
Member Data Documentation
id
const Pfstat_ID Statistics::id protected
the ID of this statistics
Definition at line 197 of file Performance.hh.
The documentation for this class was generated from the following files:
src/Performance.hh
src/Performance.cc