GNU APL: Workspace Class Reference
Workspace Class Reference
An APL workspace.
#include <Workspace.hh>
Public Member Functions
Workspace ()
Construct an empty workspace.
Static Public Member Functions
static APL_Float get_CT ()
return the current ⎕CT
static APL_Char get_FC (int p)
return element pos of the current ⎕FC (pos should be 0..5)
static APL_Integer get_IO ()
return the current ⎕IO
static UCS_string get_LX ()
return the current ⎕LX
static PrintContext get_PrintContext (PrintStyle style)
return style and the current ⎕PP, and ⎕PW
static const UCS_string get_PR ()
return the current ⎕PR
static int get_PP ()
return the current ⎕PW
static int get_PW ()
return the current ⎕PW
static void set_PW (int PW, const char *loc)
set the current ⎕PW
static int SI_entry_count ()
the number of SI entries
static StateIndicator * SI_top ()
the top of the SI stack (the SI pushed last)
static std::vector< const Symbol * > get_all_symbols ()
copy all allocated symbols into table of size table_size
static Symbol * lookup_symbol (const UCS_string &symbol_name)
lookup an existing user defined symbol. If not found, create one (unless this would be a quad symbol)
static void add_wait (APL_time_us diff)
increase the wait time for user input as reported in ⎕AI
static Error * get_error ()
return information in SI_top()
static UCS_string & more_error ()
return reference to more info about last error
static void erase_symbols (ostream &out, const UCS_string_vector &symbols)
erase the symbols in symbols from the symbol table
static void list (ostream &out, ListCategory which, UCS_string from_to)
list all symbols (of category which) with names in from_to
static ostream & list_symbol (ostream &out, const UCS_string &buf)
list all symbols with names in buf
static void add_expunged_function (const UserFunction *ufun)
add ufun to list of that were ⎕EX'ed while on the SI stack
static const SymbolTable & get_symbol_table ()
return the symbol table of the current workspace.
static const UCS_string & get_prompt ()
return the APL prompt
static const UCS_string & get_WS_name ()
return the name of the current workspace.
static void set_WS_name (const UCS_string &new_name)
set the name of the current workspace.
static vector< Command::user_command > & get_user_commands ()
Return all user-defined commands.
static void push_SI (const Executable *fun, const char *loc)
Create a new SI-entry on the SI stack.
static void pop_SI (const char *loc)
Remove the current SI-entry from the SI stack.
static uint64_t get_RL (uint64_t mod)
return the Quad-RL (to be taken % mod)
static void clear_error (const char *loc)
clear ⎕EM and ⎕ET related errors (error entries on SI up to (including) the next user-defined function
static Token immediate_execution (bool exit_on_error)
create and execute one immediate execution context
static void clear_WS (ostream &out, bool silent)
clear the workspace
static void clear_SI (ostream &out)
clear the SI
static void list_SI (ostream &out, SI_mode mode)
print the SI on out
static StateIndicator * SI_top_fun ()
the topmost SI with parse mode PM_FUNCTION
static StateIndicator * SI_top_error (bool quad_LRX)
the topmost SI with an error, maybe require ⎕L, ⎕R, or ⎕X.
static const NamedObject * lookup_existing_name (const UCS_string &name)
lookup an existing name (user defined or ⎕xx, var or function). return 0 if not found.
static Symbol * lookup_existing_symbol (const UCS_string &symbol_name)
lookup an existing symbol (user defined or ⎕xx).
static UCS_string find_lambda_name (const UserFunction *lambda)
return the name to which lambda ia assigned (empty if not found)
static void save_WS (ostream &out, LibRef lib, const UCS_string &wsname, bool name_from_WSID)
save this workspace
static bool backup_existing_file (const char *filename)
backup an existing file filename, return true on error
static void dump_WS (ostream &out, LibRef lib, const UCS_string &wsname, bool html, bool silent)
dump this workspace
static void dump_commands (ostream &out)
dump the commands in this workspace
static void wsid (ostream &out, UCS_string arg, LibRef lib, bool silent)
set or inquire the workspace ID
static void load_DUMP (ostream &out, const UTF8_string &filename, int fd, LX_mode with_LX, bool silent, UCS_string_vector *object_filter)
load)DUMPed file from open file descriptor fd (closes fd)
static void load_WS (ostream &out, LibRef lib, const UCS_string &wsname, UCS_string &quad_lx, bool silent)
load lib_ws into the_workspace, maybe set ⎕LX of the new WS.
static void copy_WS (ostream &out, LibRef lib, const UCS_string &wsname, UCS_string_vector &objects, bool protection)
copy objects from another workspace
static Token get_quad (const UCS_string &ucs, int &len)
return a token for system function or variable ucs
static StateIndicator * oldest_exec (const Executable *exec)
return oldest SI entry that is running exex, or 0 if none
static bool is_called (const UCS_string &funname)
return true iff function funname is on the current call stack
static void write_OUT (FILE *out, uint64_t &seq, const UCS_string_vector &objects)
write symbols for)OUT command
static void unmark_all_values ()
clear the marked flag in all values known in this workspace
static int show_owners (ostream &out, const Value &value)
print all owners of value
static int cleanup_expunged (ostream &out, bool &erased)
maybe remove functions for which ⎕EX has failed
static Quad_Quad & get_v_Quad_Quad ()
static Quad_QUOTE & get_v_Quad_QUOTE ()
static void push_Command (const UCS_string &command)
push a command. This is done when ⍎Command is performed and the command would push the SI stack (i.e.)LOAD,)QLOAD,)CLEAR, or)SIC)
static const UCS_string & get_pushed_Command ()
return the pushed command
Protected Attributes
UCS_string WS_name
the name of the workspace
Quad_Quad v_Quad_Quad
Quad_QUOTE v_Quad_QUOTE
UCS_string prompt
the APL prompt (6 blanks by default)
std::vector< const UserFunction * > expunged_functions
user defined functions that were ⎕EX'ed while on the SI stack
UCS_string more_error_info
more info about last error
StateIndicator * top_SI
the SI stack. Initially top_SI is 0 (empty stack)
UCS_string pushed_command
)LOAD,)QLOAD,)CLEAR, or)SIC
std::vector< Command::user_command > user_commands
user defined commands
Protected Attributes inherited from Workspace_0
SymbolTable symbol_table
the symbol table for user-defined names of this workspace.
SystemSymTab distinguished_names
the symbol table for system names (aka. distinguished names) of this workspace.
Static Protected Attributes
static Workspace the_workspace
the current workspace (for objects that need one but don't have one).
Detailed Description
An APL workspace.
An APL workspace. This structure contains everyting (variables, functions, SI stack, etc.) belonging to a single APL workspace.
Definition at line 69 of file Workspace.hh.
Constructor & Destructor Documentation
Workspace()
Workspace::Workspace ()
Construct an empty workspace.
Definition at line 52 of file Workspace.cc.
References Quad_CR::_fun, Quad_EC::_fun, Quad_ES::_fun, Quad_CR::fun, Quad_EC::fun, and Quad_ES::fun.
Member Function Documentation
add_expunged_function()
static void Workspace::add_expunged_function (const UserFunction * ufun) inline static
add ufun to list of that were ⎕EX'ed while on the SI stack
Definition at line 156 of file Workspace.hh.
References expunged_functions, and the_workspace.
Referenced by Symbol::expunge().
add_wait()
static void Workspace::add_wait (APL_time_us diff) inline static
increase the wait time for user input as reported in ⎕AI
Definition at line 132 of file Workspace.hh.
References add_wait(), and the_workspace.
Referenced by add_wait(), and InputMux::get_line().
backup_existing_file()
bool Workspace::backup_existing_file (const char * filename) static
backup an existing file filename, return true on error
Definition at line 682 of file Workspace.cc.
References UTF8_string::append_ASCII(), and UTF8_string::c_str().
Referenced by dump_WS(), and save_WS().
cleanup_expunged()
int Workspace::cleanup_expunged (ostream & out, bool & erased) static
maybe remove functions for which ⎕EX has failed
Definition at line 521 of file Workspace.cc.
References expunged_functions, UserFunction::get_name(), SI_entry_count(), and the_workspace.
Referenced by Command::cmd_CHECK().
clear_error()
void Workspace::clear_error (const char * loc) static
clear ⎕EM and ⎕ET related errors (error entries on SI up to (including) the next user-defined function
Definition at line 196 of file Workspace.cc.
References UserFunction_header::get_error(), StateIndicator::get_parent(), SI_top(), and the_workspace.
Referenced by Quad_ES::event_simulate().
clear_SI()
void Workspace::clear_SI (ostream & out) static
clear the SI
Definition at line 604 of file Workspace.cc.
References StateIndicator::escape(), pop_SI(), and SI_top().
Referenced by clear_WS().
clear_WS()
void Workspace::clear_WS (ostream & out, bool silent) static
clear the workspace
Definition at line 547 of file Workspace.cc.
References Quad_FIO::clear(), Quad_GTK::clear(), SymbolTable::clear(), Command::clear_copy_once_table(), clear_SI(), get_user_commands(), more_error(), set_PW(), set_WS_name(), Workspace_0::symbol_table, and the_workspace.
Referenced by load_WS().
copy_WS()
void Workspace::copy_WS (ostream & out, LibRef lib, const UCS_string & wsname, UCS_string_vector & objects, bool protection) static
copy objects from another workspace
Definition at line 1035 of file Workspace.cc.
References UTF8_string::c_str(), LibPaths::get_lib_filename(), XML_Loading_Archive::is_open(), load_DUMP(), XML_Loading_Archive::read_vids(), XML_Loading_Archive::read_Workspace(), XML_Loading_Archive::set_protection(), and WS_name.
Referenced by Command::cmd_COPY(), and Command::cmd_COPY_ONCE().
dump_commands()
void Workspace::dump_commands (ostream & out) static
dump the commands in this workspace
Definition at line 944 of file Workspace.cc.
References get_user_commands().
Referenced by dump_WS().
dump_WS()
void Workspace::dump_WS (ostream & out, LibRef lib, const UCS_string & wsname, bool html, bool silent) static
dump this workspace
Definition at line 812 of file Workspace.cc.
References UserPreferences::backup_before_save, backup_existing_file(), UTF8_string::c_str(), UCS_string::compare(), YMDhmsu::day, SymbolTable::dump(), dump_commands(), LibPaths::get_APL_bin_name(), LibPaths::get_APL_bin_path(), LibPaths::get_lib_filename(), YMDhmsu::month, Workspace_0::symbol_table, the_workspace, WS_name, and YMDhmsu::year.
Referenced by Command::cmd_DUMP().
erase_symbols()
static void Workspace::erase_symbols (ostream & out, const UCS_string_vector & symbols) inline static
erase the symbols in symbols from the symbol table
Definition at line 144 of file Workspace.hh.
References SymbolTable::erase_symbols(), Workspace_0::symbol_table, and the_workspace.
Referenced by Command::cmd_ERASE().
find_lambda_name()
static UCS_string Workspace::find_lambda_name (const UserFunction * lambda) inline static
return the name to which lambda ia assigned (empty if not found)
Definition at line 219 of file Workspace.hh.
References SymbolTable::find_lambda_name(), Workspace_0::symbol_table, and the_workspace.
Referenced by UserFunction::get_name_and_line().
get_all_symbols()
static std::vector< const Symbol * > Workspace::get_all_symbols () inline static
copy all allocated symbols into table of size table_size
Definition at line 123 of file Workspace.hh.
References SymbolTable::get_all_symbols(), Workspace_0::symbol_table, and the_workspace.
Referenced by Quad_NL::do_quad_NL(), TabExpansion::expand_help_topics(), and TabExpansion::expand_user_name().
get_CT()
static APL_Float Workspace::get_CT () inline static
return the current ⎕CT
Definition at line 76 of file Workspace.hh.
References the_workspace.
Referenced by NumericCell::bif_and(), FloatCell::bif_ceiling(), Cell::bif_equal(), ComplexCell::bif_equal(), ComplexCell::bif_floor(), FloatCell::bif_floor(), Cell::bif_not_equal(), NumericCell::bif_or(), IntCell::bif_residue(), ComplexCell::bif_within_quad_CT(), FloatCell::bif_within_quad_CT(), ComplexCell::compare(), FloatCell::compare(), Bif_F12_INDEX_OF::eval_AB(), Bif_F12_ELEMENT::eval_AB(), Bif_F12_EQUIV::eval_AB(), Bif_F12_NEQUIV::eval_AB(), Bif_F12_ENCODE::eval_AB(), Bif_F2_INTER::eval_AB(), Quad_MAP::eval_AB(), Bif_F2_FIND::eval_AB(), Bif_F12_WITHOUT::eval_AB(), Bif_F12_DOMINO::eval_B(), Bif_F12_UNION::eval_B(), Bif_F12_ROLL::eval_B(), Bif_F12_DOMINO::householder(), and Bif_F12_WITHOUT::large_eval_AB().
get_error()
static Error * Workspace::get_error () inline static
return information in SI_top()
Definition at line 136 of file Workspace.hh.
References UserFunction_header::get_error(), and SI_top().
Referenced by Command::finish_context(), ExecuteList::fix(), StatementList::fix(), and Error::throw_define_error().
get_FC()
static APL_Char Workspace::get_FC (int p) inline static
return element pos of the current ⎕FC (pos should be 0..5)
Definition at line 80 of file Workspace.hh.
References the_workspace.
Referenced by Quad_FIO::do_sprintf(), Bif_F12_FORMAT::Format_LIFER::fill_data_fields(), Bif_F12_FORMAT::Format_LIFER::format_example(), Bif_F12_FORMAT::Format_LIFER::format_left_side(), Bif_F12_FORMAT::format_one_col_by_spec(), Bif_F12_FORMAT::Format_LIFER::format_right_side(), Quad_FIO::group_thousands(), Format_sub::insert_fract_commas(), Format_sub::insert_int_commas(), and FloatCell::map_FC().
get_IO()
static APL_Integer Workspace::get_IO () inline static
return the current ⎕IO
Definition at line 84 of file Workspace.hh.
References the_workspace.
Referenced by Quad_SYL::assign_indexed(), Quad_FC::assign_indexed(), Quad_PS::assign_indexed(), Symbol::assign_indexed(), ComplexCell::bif_roll(), FloatCell::bif_roll(), IntCell::bif_roll(), Bif_COMMA::catenate_or_laminate(), XML_node::collect(), Bif_F12_PICK::disclose_with_axis(), DLX_Root_Node::DLX_Root_Node(), Quad_DLX::do_DLX(), Quad_FX::do_quad_FX(), Bif_F12_INDEX_OF::eval_AB(), Bif_F12_INTERVAL_INDEX::eval_AB(), Bif_F12_PICK::eval_AB(), Bif_F2_INDEX::eval_AB(), Bif_F12_TRANSPOSE::eval_AB(), Quad_MAP::eval_AB(), Bif_F12_ROLL::eval_AB(), Bif_F12_TAKE::eval_AXB(), Bif_F12_DROP::eval_AXB(), Bif_F2_INDEX::eval_AXB(), Bif_F12_INDEX_OF::eval_B(), Bif_F12_INTERVAL_INDEX::eval_B(), ScalarFunction::eval_scalar_AXB(), CDR::from_CDR(), IndexExpr::get_axis(), Value::get_single_axis(), Value::index(), Value::init_ravel(), Bif_F12_TRANSPOSE::inverse_permutation(), XML_node::merge_range(), Quad_XML::name_unsplit(), Quad_PLOT::parse_attributes(), XML_node::parse_tag(), Plot_line_properties::Plot_line_properties(), DLX_Root_Node::preset(), push_SI(), Bif_COMMA::ravel_axis(), Bif_REDUCE::reduce(), Bif_REDUCE::reduce_n_wise(), Bif_SCAN::scan(), Plot_window_properties::set_attribute(), Quad_PLOT::setup_data_2D(), Quad_PLOT::setup_data_2D_2b(), DLX_Root_Node::solve(), Bif_F12_SORT::sort(), Bif_F12_SORT::sort_collating(), Value::to_bitmap(), Value::to_shape(), and Quad_XML::XML_to_APL().
get_LX()
static UCS_string Workspace::get_LX () inline static
return the current ⎕LX
Definition at line 88 of file Workspace.hh.
References the_workspace.
Referenced by IO_Files::get_file_line(), and load_WS().
get_PP()
static int Workspace::get_PP () inline static
return the current ⎕PW
Definition at line 103 of file Workspace.hh.
References the_workspace.
Referenced by Quad_QUOTE::assign().
get_PR()
static const UCS_string Workspace::get_PR () inline static
return the current ⎕PR
Definition at line 99 of file Workspace.hh.
References the_workspace.
Referenced by Quad_QUOTE::get_apl_value().
get_PrintContext()
static PrintContext Workspace::get_PrintContext (PrintStyle style) inline static
return style and the current ⎕PP, and ⎕PW
Definition at line 92 of file Workspace.hh.
References the_workspace.
Referenced by Value::debug(), Quad_CR::do_CR31_32(), Quad_CR::eval_AB(), Bif_F12_FORMAT::eval_B(), Bif_F12_FORMAT::monadic_format(), Value::print(), Token::show_trace(), and StateIndicator::statement_result().
get_prompt()
static const UCS_string & Workspace::get_prompt () inline static
return the APL prompt
Definition at line 164 of file Workspace.hh.
References prompt, and the_workspace.
Referenced by Command::process_line(), and Quad_Quad::resolve().
get_pushed_Command()
static const UCS_string & Workspace::get_pushed_Command () inline static
return the pushed command
Definition at line 290 of file Workspace.hh.
References pushed_command, and the_workspace.
Referenced by Command::finish_context().
get_PW()
static int Workspace::get_PW () inline static
return the current ⎕PW
Definition at line 107 of file Workspace.hh.
References the_workspace.
Referenced by PointerCell::character_representation(), UCS_string_vector::compute_column_width(), LineInput::edit_line(), TabExpansion::expand_help_topics(), and StateIndicator::statement_result().
get_quad()
Token Workspace::get_quad (const UCS_string & ucs, int & len) static
return a token for system function or variable ucs
Definition at line 335 of file Workspace.cc.
References UCS_string::append(), Workspace_0::distinguished_names, SystemName::get_function(), SystemVariable::get_token(), Function::get_token(), SystemName::get_variable(), Avec::is_quad(), Avec::is_symbol_char(), SymbolTableBase< T, SYMBOL_COUNT >::lookup_existing_symbol(), UCS_string::size(), the_workspace, and v_Quad_Quad.
Referenced by Command::transfer_context::chars_1TF(), Quad_AT::eval_AB(), NamedObject::get_NC(), Quad_NC::get_NC(), lookup_existing_name(), lookup_existing_symbol(), Command::transfer_context::numeric_1TF(), and Tokenizer::tokenize_quad().
get_RL()
uint64_t Workspace::get_RL (uint64_t mod) static
return the Quad-RL (to be taken % mod)
Definition at line 179 of file Workspace.cc.
References the_workspace.
Referenced by ComplexCell::bif_roll(), FloatCell::bif_roll(), IntCell::bif_roll(), and Bif_F12_ROLL::eval_AB().
get_symbol_table()
static const SymbolTable & Workspace::get_symbol_table () inline static
return the symbol table of the current workspace.
Definition at line 160 of file Workspace.hh.
References Workspace_0::symbol_table, and the_workspace.
Referenced by Doxy::gen(), XML_Saving_Archive::save(), and write_OUT().
get_user_commands()
static vector< Command::user_command > & Workspace::get_user_commands () inline static
Return all user-defined commands.
Definition at line 176 of file Workspace.hh.
References the_workspace, and user_commands.
Referenced by Command::check_redefinition(), clear_WS(), Command::cmd_HELP(), Command::cmd_USERCMD(), Command::do_APL_command(), Command::do_USERCMD(), dump_commands(), XML_Loading_Archive::read_Command(), and XML_Saving_Archive::save().
get_v_Quad_Quad()
static Quad_Quad & Workspace::get_v_Quad_Quad () inline static
returnQuad_Quad
Definition at line 280 of file Workspace.hh.
get_v_Quad_QUOTE()
static Quad_QUOTE & Workspace::get_v_Quad_QUOTE () inline static
returnQuad_QUOTE
Definition at line 281 of file Workspace.hh.
Referenced by Tokenizer::do_tokenize().
get_WS_name()
static const UCS_string & Workspace::get_WS_name () inline static
return the name of the current workspace.
Definition at line 168 of file Workspace.hh.
References the_workspace, and WS_name.
Referenced by Command::cmd_DUMP(), Command::cmd_SAVE(), Doxy::Doxy(), and XML_Saving_Archive::save().
immediate_execution()
Token Workspace::immediate_execution (bool exit_on_error) static
create and execute one immediate execution context
Definition at line 234 of file Workspace.cc.
References IO_Files::apl_error(), Error::error_name(), Error::get_error_code(), Error::get_print_loc(), Error::print_em(), Command::process_line(), SI_entry_count(), and the_workspace.
is_called()
bool Workspace::is_called (const UCS_string & funname) static
return true iff function funname is on the current call stack
Definition at line 383 of file Workspace.cc.
References Function::get_func_ufun(), Symbol::get_function(), NamedObject::get_Id(), NamedObject::get_NC(), StateIndicator::get_parent(), lookup_existing_symbol(), and SI_top().
Referenced by Symbol::cant_be_defined(), SymbolTable::erase_one_symbol(), and Nabla::open_existing_function().
list()
static void Workspace::list (ostream & out, ListCategory which, UCS_string from_to) inline static
list all symbols (of category which) with names in from_to
Definition at line 148 of file Workspace.hh.
References SymbolTable::list(), Workspace_0::symbol_table, and the_workspace.
list_SI()
void Workspace::list_SI (ostream & out, SI_mode mode) static
print the SI on out
Definition at line 615 of file Workspace.cc.
References StateIndicator::get_parent(), and SI_top().
Referenced by IO_Files::end_of_current_file().
list_symbol()
static ostream & Workspace::list_symbol (ostream & out, const UCS_string & buf) inline static
list all symbols with names in buf
Definition at line 152 of file Workspace.hh.
References SymbolTable::list_symbol(), Workspace_0::symbol_table, and the_workspace.
load_DUMP()
void Workspace::load_DUMP (ostream & out, const UTF8_string & filename, int fd, LX_mode with_LX, bool silent, UCS_string_vector * object_filter) static
load)DUMPed file from open file descriptor fd (closes fd)
Definition at line 732 of file Workspace.cc.
References InputFile::add_filter_object(), Bif_F1_EXECUTE::copy_pending, InputFile::files_todo, and InputFile::set_COPY().
Referenced by copy_WS(), and load_WS().
load_WS()
void Workspace::load_WS (ostream & out, LibRef lib, const UCS_string & wsname, UCS_string & quad_lx, bool silent) static
load lib_ws into the_workspace, maybe set ⎕LX of the new WS.
Definition at line 958 of file Workspace.cc.
References UTF8_string::c_str(), clear_WS(), LibPaths::get_lib_filename(), get_LX(), XML_Loading_Archive::is_open(), load_DUMP(), XML_Loading_Archive::read_Workspace(), the_workspace, WS_name, and wsid().
Referenced by Command::cmd_LOAD().
lookup_existing_name()
const NamedObject * Workspace::lookup_existing_name (const UCS_string & name) static
lookup an existing name (user defined or ⎕xx, var or function). return 0 if not found.
Definition at line 283 of file Workspace.cc.
References Token::get_Class(), Symbol::get_function(), Token::get_function(), NamedObject::get_NC(), get_quad(), Token::get_sym_ptr(), Avec::is_quad(), SymbolTableBase< T, SYMBOL_COUNT >::lookup_existing_symbol(), UCS_string::size(), Workspace_0::symbol_table, and the_workspace.
Referenced by Quad_CR::do_eval_B(), Quad_AT::eval_AB(), Quad_TF::tf1(), Quad_TF::tf1_inv(), Quad_TF::tf2(), Quad_TF::tf3(), and write_OUT().
lookup_existing_symbol()
Symbol * Workspace::lookup_existing_symbol (const UCS_string & symbol_name) static
lookup an existing symbol (user defined or ⎕xx).
Definition at line 317 of file Workspace.cc.
References Token::get_Class(), get_quad(), Token::get_sym_ptr(), Avec::is_quad(), SymbolTableBase< T, SYMBOL_COUNT >::lookup_existing_symbol(), UCS_string::size(), Workspace_0::symbol_table, and the_workspace.
Referenced by Command::cmd_HELP(), Quad_CR::do_CR10(), Quad_SVC::eval_AB(), Quad_AT::eval_AB(), Quad_SVC::eval_B(), Quad_SVO::eval_B(), Quad_SVR::eval_B(), Quad_SVS::eval_B(), Quad_EX::expunge(), Command::transfer_context::function_2TF(), Quad_NC::get_NC(), is_called(), SymbolTable::list_symbol(), Stop_Trace::locate_fun(), XML_Loading_Archive::read_Symbol(), XML_Loading_Archive::read_Token(), and write_OUT().
lookup_symbol()
static Symbol * Workspace::lookup_symbol (const UCS_string & symbol_name) inline static
lookup an existing user defined symbol. If not found, create one (unless this would be a quad symbol)
Definition at line 128 of file Workspace.hh.
References SymbolTable::lookup_symbol(), Workspace_0::symbol_table, and the_workspace.
Referenced by Command::transfer_context::chars_1TF(), Nabla::edit_header_line(), Quad_SVO::eval_AB(), NativeFunction::fix(), UserFunction::fix(), NativeFunction::NativeFunction(), Command::transfer_context::numeric_1TF(), XML_Loading_Archive::read_Function_name(), XML_Loading_Archive::read_Symbol(), XML_Loading_Archive::read_Token(), XML_Loading_Archive::read_UserFunction(), XML_Saving_Archive::save_Function_name(), XML_Saving_Archive::save_SI_entry(), Nabla::start(), Quad_TF::tf1_inv(), and Tokenizer::tokenize_symbol().
more_error()
static UCS_string & Workspace::more_error () inline static
return reference to more info about last error
Definition at line 140 of file Workspace.hh.
References more_error_info, and the_workspace.
Referenced by clear_WS(), Command::cmd_IN(), Command::cmd_MORE(), Command::do_APL_command(), Command::do_APL_expression(), Nabla::edit(), Nabla::edit_body_line(), Error::Error(), Nabla::Nabla(), NativeFunction::NativeFunction(), Error::print(), XML_Loading_Archive::read_Function(), and Nabla::throw_edit_error().
oldest_exec()
StateIndicator * Workspace::oldest_exec (const Executable * exec) static
return oldest SI entry that is running exex, or 0 if none
Definition at line 372 of file Workspace.cc.
References StateIndicator::get_parent(), and SI_top().
Referenced by SymbolTable::erase_one_symbol(), and Symbol::expunge().
pop_SI()
void Workspace::pop_SI (const char * loc) static
Remove the current SI-entry from the SI stack.
Definition at line 153 of file Workspace.cc.
References Executable::get_exec_ufun(), StateIndicator::get_executable(), StateIndicator::get_level(), UserFunction::get_name(), StateIndicator::get_parent(), Executable::get_parse_mode(), StateIndicator::get_parse_mode_name(), SI_top(), the_workspace, and top_SI.
Referenced by clear_SI(), Command::do_APL_expression(), Quad_ES::event_simulate(), and Command::finish_context().
push_Command()
static void Workspace::push_Command (const UCS_string & command) inline static
push a command. This is done when ⍎Command is performed and the command would push the SI stack (i.e.)LOAD,)QLOAD,)CLEAR, or)SIC)
Definition at line 286 of file Workspace.hh.
References pushed_command, and the_workspace.
Referenced by Bif_F1_EXECUTE::execute_command(), and Command::finish_context().
push_SI()
void Workspace::push_SI (const Executable * fun, const char * loc) static
Create a new SI-entry on the SI stack.
Definition at line 81 of file Workspace.cc.
References Value::check_WS_FULL(), StateIndicator::get_executable(), get_IO(), StateIndicator::get_level(), Executable::get_name(), Executable::get_parse_mode(), Quad_SYL::si_depth_limit, SI_entry_count(), SI_top(), the_workspace, and top_SI.
Referenced by Command::do_APL_expression(), UserFunction::eval_(), UserFunction::eval_AB(), UserFunction::eval_ALB(), UserFunction::eval_ALRB(), UserFunction::eval_ALRXB(), UserFunction::eval_ALXB(), UserFunction::eval_AXB(), Quad_EC::eval_B(), UserFunction::eval_B(), UserFunction::eval_LB(), UserFunction::eval_LRB(), UserFunction::eval_LRXB(), UserFunction::eval_LXB(), UserFunction::eval_XB(), Bif_F1_EXECUTE::execute_statement(), and XML_Loading_Archive::read_SI_entry().
save_WS()
void Workspace::save_WS (ostream & out, LibRef lib, const UCS_string & wsname, bool name_from_WSID) static
save this workspace
Definition at line 624 of file Workspace.cc.
References UserPreferences::backup_before_save, backup_existing_file(), UTF8_string::c_str(), UCS_string::compare(), LibPaths::get_lib_filename(), XML_Saving_Archive::save(), the_workspace, and WS_name.
Referenced by Command::cmd_CONTINUE(), and Command::cmd_SAVE().
set_PW()
static void Workspace::set_PW (int PW, const char * loc) inline static
set the current ⎕PW
Definition at line 111 of file Workspace.hh.
References the_workspace.
Referenced by clear_WS(), init_apl(), UserPreferences::parse_argv_2(), and signal_WINCH_handler().
set_WS_name()
static void Workspace::set_WS_name (const UCS_string & new_name) inline static
set the name of the current workspace.
Definition at line 172 of file Workspace.hh.
References the_workspace, and WS_name.
Referenced by clear_WS().
show_owners()
int Workspace::show_owners (ostream & out, const Value & value) static
print all owners of value
Definition at line 489 of file Workspace.cc.
References expunged_functions, StateIndicator::get_parent(), Symbol::show_owners(), SymbolTable::show_owners(), SI_top(), Workspace_0::symbol_table, the_workspace, v_Quad_Quad, and v_Quad_QUOTE.
Referenced by Value::list_one().
SI_entry_count()
static int Workspace::SI_entry_count () inline static
the number of SI entries
Definition at line 115 of file Workspace.hh.
References StateIndicator::get_level(), and SI_top().
Referenced by Quad_SYL::assign_indexed(), Value::catch_exception(), Value::check_WS_FULL(), cleanup_expunged(), SymbolTable::clear(), SystemSymTab::clear(), IO_Files::end_of_current_file(), Quad_SI::eval_AB(), Quad_SI::eval_B(), immediate_execution(), push_SI(), and XML_Saving_Archive::save().
SI_top()
static StateIndicator * Workspace::SI_top () inline static
the top of the SI stack (the SI pushed last)
Definition at line 119 of file Workspace.hh.
References the_workspace, and top_SI.
Referenced by Symbol::assign_named_lambda(), clear_error(), clear_SI(), Command::do_APL_expression(), Quad_EC::eoc(), Bif_F12_RHO::eval_AB(), Quad_SI::eval_AB(), Quad_FIO::eval_ALXB(), Bif_F12_COMMA::eval_B(), Bif_F12_COMMA1::eval_B(), Quad_FIO::eval_B(), Quad_EC::eval_B(), Quad_ES::eval_B(), Quad_SI::eval_B(), Quad_FIO::eval_LXB(), Quad_ES::event_simulate(), Executable::execute_body(), Bif_F1_EXECUTE::execute_statement(), StateIndicator::find_child(), XML_Loading_Archive::find_lambda(), Command::finish_context(), Quad_EM::get_apl_value(), Quad_ET::get_apl_value(), Quad_LC::get_apl_value(), get_error(), Symbol::get_SI_level(), is_called(), list_SI(), StateIndicator::nth_push(), oldest_exec(), pop_SI(), push_SI(), XML_Loading_Archive::read_SI_entry(), Prefix::reduce_statements(), XML_Saving_Archive::save(), show_owners(), SI_entry_count(), Doxy::SI_table(), SI_top_error(), SI_top_fun(), Error::throw_define_error(), Error::throw_symbol_error(), and unmark_all_values().
SI_top_error()
StateIndicator * Workspace::SI_top_error (bool quad_LRX) static
the topmost SI with an error, maybe require ⎕L, ⎕R, or ⎕X.
Definition at line 219 of file Workspace.cc.
References UserFunction_header::get_error(), StateIndicator::get_parent(), and SI_top().
Referenced by Quad_L::get_apl_value(), Quad_R::get_apl_value(), and Quad_X::get_apl_value().
SI_top_fun()
StateIndicator * Workspace::SI_top_fun () static
the topmost SI with parse mode PM_FUNCTION
Definition at line 208 of file Workspace.cc.
References StateIndicator::get_parent(), and SI_top().
Referenced by Quad_L::assign(), Quad_R::assign(), Quad_X::assign(), and Command::finish_context().
unmark_all_values()
void Workspace::unmark_all_values () static
clear the marked flag in all values known in this workspace
Definition at line 463 of file Workspace.cc.
References expunged_functions, StateIndicator::get_parent(), SI_top(), Workspace_0::symbol_table, the_workspace, Symbol::unmark_all_values(), SymbolTable::unmark_all_values(), v_Quad_Quad, and v_Quad_QUOTE.
Referenced by Value::print_stale(), and XML_Saving_Archive::save().
write_OUT()
void Workspace::write_OUT (FILE * out, uint64_t & seq, const UCS_string_vector & objects) static
write symbols for)OUT command
Definition at line 410 of file Workspace.cc.
References NamedObject::get_Id(), NamedObject::get_symbol(), get_symbol_table(), lookup_existing_name(), lookup_existing_symbol(), SymbolTable::write_all_symbols(), and Symbol::write_OUT().
Referenced by Command::cmd_OUT().
wsid()
void Workspace::wsid (ostream & out, UCS_string arg, LibRef lib, bool silent) static
set or inquire the workspace ID
Definition at line 1071 of file Workspace.cc.
References UCS_string::erase(), UCS_string::prepend(), UCS_string::remove_leading_and_trailing_whitespaces(), UCS_string::remove_leading_whitespaces(), UCS_string::size(), the_workspace, and WS_name.
Referenced by Command::cmd_CONTINUE(), and load_WS().
Member Data Documentation
expunged_functions
std::vector<const UserFunction *> Workspace::expunged_functions protected
user defined functions that were ⎕EX'ed while on the SI stack
Definition at line 309 of file Workspace.hh.
Referenced by add_expunged_function(), cleanup_expunged(), show_owners(), and unmark_all_values().
more_error_info
UCS_string Workspace::more_error_info protected
more info about last error
Definition at line 312 of file Workspace.hh.
Referenced by more_error().
prompt
UCS_string Workspace::prompt protected
the APL prompt (6 blanks by default)
Definition at line 306 of file Workspace.hh.
Referenced by get_prompt().
pushed_command
UCS_string Workspace::pushed_command protected
)LOAD,)QLOAD,)CLEAR, or)SIC
Definition at line 318 of file Workspace.hh.
Referenced by get_pushed_Command(), and push_Command().
the_workspace
Workspace Workspace::the_workspace static protected
the current workspace (for objects that need one but don't have one).
Definition at line 324 of file Workspace.hh.
Referenced by add_expunged_function(), add_wait(), cleanup_expunged(), clear_error(), clear_WS(), dump_WS(), erase_symbols(), find_lambda_name(), get_all_symbols(), get_CT(), get_FC(), get_IO(), get_LX(), get_PP(), get_PR(), get_PrintContext(), get_prompt(), get_pushed_Command(), get_PW(), get_quad(), get_RL(), get_symbol_table(), get_user_commands(), get_WS_name(), immediate_execution(), list(), list_symbol(), load_WS(), lookup_existing_name(), lookup_existing_symbol(), lookup_symbol(), more_error(), pop_SI(), push_Command(), push_SI(), save_WS(), set_PW(), set_WS_name(), show_owners(), SI_top(), unmark_all_values(), and wsid().
top_SI
StateIndicator* Workspace::top_SI protected
the SI stack. Initially top_SI is 0 (empty stack)
Definition at line 315 of file Workspace.hh.
Referenced by pop_SI(), push_SI(), and SI_top().
user_commands
std::vector<Command::user_command> Workspace::user_commands protected
user defined commands
Definition at line 321 of file Workspace.hh.
Referenced by get_user_commands().
v_Quad_Quad
Quad_Quad Workspace::v_Quad_Quad protected
Quad_Quad
Definition at line 301 of file Workspace.hh.
Referenced by get_quad(), show_owners(), and unmark_all_values().
v_Quad_QUOTE
Quad_QUOTE Workspace::v_Quad_QUOTE protected
Quad_QUOTE
Definition at line 302 of file Workspace.hh.
Referenced by show_owners(), and unmark_all_values().
WS_name
UCS_string Workspace::WS_name protected
the name of the workspace
Definition at line 295 of file Workspace.hh.
Referenced by copy_WS(), dump_WS(), get_WS_name(), load_WS(), save_WS(), set_WS_name(), and wsid().
The documentation for this class was generated from the following files:
src/Workspace.hh
src/Command.def
src/static_Objects.cc
src/StaticObjects.cc
src/Workspace.cc