GNU APL: Doxy Class Reference
Doxy Class Reference
implementation of the ]Doxy command.
#include <Doxy.hh>
Public Member Functions
Doxy (ostream &out, const UCS_string &root_dir)
Constructor: create (and remember) the root directory.
void gen ()
generate the entire documentation
void functions_table (const std::vector< const Symbol * > &functions, ofstream &page)
HTML-print a table containing all defined functions to page.
void variables_table (const std::vector< const Symbol * > &variables, ofstream &page)
HTML-print a table with all variables to 'page'.
void SI_table (ofstream &page)
HTML-print a table with the SI stack to 'page'.
int get_errors () const
return the number of errors that have occurred
const UTF8_string & get_root_dir () const
return the directory into which all documenattion files will be written
Protected Member Functions
void write_css ()
write a fixed CSS file
void bold_name (ostream &of, const UserFunction *ufun) const
(HTML-)print a function header with the name in bold to file of
void function_page (const UserFunction *ufun, const UCS_string &alias)
write the page for one defined function. If the define function is a named lambda, then lambda_owner is the Symbol to which the lambda was assigned.
void native_page (const Function *fun, const UCS_string &alias)
write the page for one native function.
void make_call_graph (const std::vector< const Symbol * > &all_funs)
create the call graph
void add_fun_to_call_graph (const Symbol *sym, const UserFunction *ufun)
add one symbol to the call graph. Note that one symbol can have different UserFunctions (at different SI levels).
void set_call_graph_root (Function_P fun)
make the call graph start from function ufun and set nodes to those nodes that are reachable from ufun
int write_call_graph (Function_P fun, const UCS_string &alias, bool caller)
write the call graph (if caller == false), or else the caller graph
void swap_caller_calee ()
swap callers and callees (reverse the direction of an edge)
int node_ID (Function_P fun)
return the index of ufun in nodes[] or -1 if not found
int gv_to_png (const char *gv_filename, const char *png_filename, bool cmapx)
convert a graphviz .gv file to a .png file using program 'dot'
Static Protected Member Functions
static UCS_string fun_anchor (const UCS_string &name)
return an HTML-anchor for function name (in the output files)
Protected Attributes
ostream & out
the command output channel (COUR or CERR)
UCS_string ws_name
the name of the workspace (for HTML output)
UTF8_string root_dir
the directory that shall contain all documentation files
std::vector< const Function * > nodes
the nodes for the current root.
std::vector< const Symbol * > all_functions
the nodes for all function symbols (independent of the current root).
UCS_string_vector aliases
the real names for the current root.
CallGraph call_graph
a directed graph telling which function calles which
int errors
the number of errors that have occurred
Detailed Description
implementation of the ]Doxy command.
Definition at line 77 of file Doxy.hh.
Constructor & Destructor Documentation
Doxy()
Doxy::Doxy (ostream & out, const UCS_string & root_dir)
Constructor: create (and remember) the root directory.
Definition at line 46 of file Doxy.cc.
References UTF8_string::append_ASCII(), UTF8_string::append_UTF8(), UTF8_string::c_str(), UCS_string::compare(), errors, Workspace::get_WS_name(), Avec::is_digit(), Avec::is_white(), out, root_dir, UCS_string::size(), write_css(), and ws_name.
Member Function Documentation
add_fun_to_call_graph()
void Doxy::add_fun_to_call_graph (const Symbol * sym, const UserFunction * ufun) protected
add one symbol to the call graph. Note that one symbol can have different UserFunctions (at different SI levels).
Definition at line 793 of file Doxy.cc.
References call_graph, Executable::get_body(), Token::get_Class(), UserFunction::get_func_ufun(), Symbol::get_function(), Symbol::get_name(), Token::get_sym_ptr(), Function::is_native(), UserFunction::localizes(), out, and Symbol::value_stack_size().
Referenced by make_call_graph().
bold_name()
void Doxy::bold_name (ostream & of, const UserFunction * ufun) const protected
(HTML-)print a function header with the name in bold to file of
Definition at line 754 of file Doxy.cc.
References UserFunction_header::A(), UserFunction_header::B(), UserFunction::get_header(), Symbol::get_name(), UserFunction_header::get_name(), UserFunction_header::LO(), UserFunction_header::RO(), and UserFunction_header::Z().
Referenced by functions_table().
fun_anchor()
UCS_string Doxy::fun_anchor (const UCS_string & name) static protected
return an HTML-anchor for function name (in the output files)
Definition at line 1114 of file Doxy.cc.
References UCS_string::append(), and UCS_string::append_ASCII().
Referenced by functions_table().
function_page()
void Doxy::function_page (const UserFunction * ufun, const UCS_string & alias) protected
write the page for one defined function. If the define function is a named lambda, then lambda_owner is the Symbol to which the lambda was assigned.
Definition at line 636 of file Doxy.cc.
References UTF8_string::append_ASCII(), UTF8_string::append_UTF8(), UTF8_string::c_str(), Executable::get_text(), Executable::get_text_size(), out, root_dir, set_call_graph_root(), swap_caller_calee(), UCS_string::to_HTML(), and write_call_graph().
Referenced by functions_table().
functions_table()
void Doxy::functions_table (const std::vector< const Symbol * > & functions, ofstream & page)
HTML-print a table containing all defined functions to page.
Definition at line 234 of file Doxy.cc.
References bold_name(), fun_anchor(), function_page(), UserFunction::get_func_ufun(), Symbol::get_function(), Symbol::get_name(), UserFunction::get_name(), Symbol::get_SI_level(), Executable::get_text(), Executable::get_text_size(), Function::is_native(), native_page(), UCS_string::remove_leading_and_trailing_whitespaces(), UCS_string::size(), UCS_string::to_HTML(), and Symbol::value_stack_size().
Referenced by gen().
gen()
void Doxy::gen ()
generate the entire documentation
Definition at line 125 of file Doxy.cc.
References all_functions, UTF8_string::append_ASCII(), UTF8_string::append_UTF8(), UTF8_string::c_str(), functions_table(), SymbolTable::get_all_symbols(), Symbol::get_name(), Workspace::get_symbol_table(), Symbol::is_erased(), make_call_graph(), out, root_dir, set_call_graph_root(), SI_table(), UCS_string::sort(), Symbol::value_stack_size(), variables_table(), write_call_graph(), and ws_name.
Referenced by Command::cmd_DOXY().
get_errors()
int Doxy::get_errors () const inline
return the number of errors that have occurred
Definition at line 98 of file Doxy.hh.
References errors.
Referenced by Command::cmd_DOXY().
get_root_dir()
const UTF8_string & Doxy::get_root_dir () const inline
return the directory into which all documenattion files will be written
Definition at line 102 of file Doxy.hh.
References root_dir.
Referenced by Command::cmd_DOXY().
gv_to_png()
int Doxy::gv_to_png (const char * gv_filename, const char * png_filename, bool cmapx) protected
convert a graphviz .gv file to a .png file using program 'dot'
Definition at line 1069 of file Doxy.cc.
References errors, and out.
Referenced by write_call_graph().
make_call_graph()
void Doxy::make_call_graph (const std::vector< const Symbol * > & all_funs) protected
create the call graph
Definition at line 776 of file Doxy.cc.
References add_fun_to_call_graph(), UserFunction::get_func_ufun(), Symbol::get_function(), and Symbol::value_stack_size().
Referenced by gen().
native_page()
void Doxy::native_page (const Function * fun, const UCS_string & alias) protected
write the page for one native function.
Definition at line 535 of file Doxy.cc.
References UTF8_string::append_ASCII(), UTF8_string::append_UTF8(), UTF8_string::c_str(), NativeFunction::f_eval_, NativeFunction::f_eval_AB, NativeFunction::f_eval_ALB, NativeFunction::f_eval_ALRB, NativeFunction::f_eval_ALRXB, NativeFunction::f_eval_ALXB, NativeFunction::f_eval_AXB, NativeFunction::f_eval_B, NativeFunction::f_eval_LB, NativeFunction::f_eval_LRB, NativeFunction::f_eval_LRXB, NativeFunction::f_eval_LXB, NativeFunction::f_eval_XB, NativeFunction::get_so_path(), NativeFunction::has_result(), out, root_dir, set_call_graph_root(), swap_caller_calee(), and write_call_graph().
Referenced by functions_table().
node_ID()
int Doxy::node_ID (Function_P fun) protected
return the index of ufun in nodes[] or -1 if not found
Definition at line 1047 of file Doxy.cc.
References nodes.
Referenced by write_call_graph().
set_call_graph_root()
void Doxy::set_call_graph_root (Function_P fun) protected
make the call graph start from function ufun and set nodes to those nodes that are reachable from ufun
Definition at line 857 of file Doxy.cc.
References aliases, all_functions, call_graph, fcall_edge::callee, fcall_edge::callee_name, fcall_edge::caller, fcall_edge::caller_name, Symbol::get_function(), nodes, out, and fcall_edge::value.
Referenced by function_page(), gen(), and native_page().
SI_table()
void Doxy::SI_table (ofstream & page)
HTML-print a table with the SI stack to 'page'.
Definition at line 432 of file Doxy.cc.
References Error::error_name(), UserFunction_header::get_error(), Prefix::get_error_PC(), Executable::get_exec_ufun(), StateIndicator::get_executable(), StateIndicator::get_level(), UserFunction::get_name_and_line(), StateIndicator::get_parent(), StateIndicator::get_parse_mode(), StateIndicator::get_parse_mode_name(), StateIndicator::get_prefix(), Executable::get_text(), UserFunction::print_local_vars(), Workspace::SI_top(), UCS_string::size(), Executable::statement_text(), and UCS_string::to_HTML().
Referenced by gen().
swap_caller_calee()
void Doxy::swap_caller_calee () protected
swap callers and callees (reverse the direction of an edge)
Definition at line 1056 of file Doxy.cc.
References call_graph, fcall_edge::callee, fcall_edge::callee_name, fcall_edge::caller, and fcall_edge::caller_name.
Referenced by function_page(), and native_page().
variables_table()
void Doxy::variables_table (const std::vector< const Symbol * > & variables, ofstream & page)
HTML-print a table with all variables to 'page'.
Definition at line 362 of file Doxy.cc.
References Bif_F12_ELEMENT::do_eval_B(), CellFunctionStatistics::first, Value_P_Base::get(), Symbol::get_name(), Symbol::get_SI_level(), Symbol::get_val_cptr(), and Symbol::value_stack_size().
Referenced by gen().
write_call_graph()
int Doxy::write_call_graph (Function_P fun, const UCS_string & alias, bool caller) protected
write the call graph (if caller == false), or else the caller graph
Definition at line 967 of file Doxy.cc.
References aliases, UTF8_string::append_ASCII(), UTF8_string::append_UTF8(), UTF8_string::c_str(), call_graph, fcall_edge::callee, fcall_edge::caller, gv_to_png(), node_ID(), nodes, out, root_dir, and fcall_edge::value.
Referenced by function_page(), gen(), and native_page().
write_css()
void Doxy::write_css () protected
write a fixed CSS file
Definition at line 89 of file Doxy.cc.
References UTF8_string::append_ASCII(), UTF8_string::c_str(), out, and root_dir.
Referenced by Doxy().
Member Data Documentation
aliases
UCS_string_vector Doxy::aliases protected
the real names for the current root.
Definition at line 163 of file Doxy.hh.
Referenced by set_call_graph_root(), and write_call_graph().
all_functions
std::vector<const Symbol *> Doxy::all_functions protected
the nodes for all function symbols (independent of the current root).
Definition at line 160 of file Doxy.hh.
Referenced by gen(), and set_call_graph_root().
call_graph
CallGraph Doxy::call_graph protected
a directed graph telling which function calles which
Definition at line 166 of file Doxy.hh.
Referenced by add_fun_to_call_graph(), set_call_graph_root(), swap_caller_calee(), and write_call_graph().
errors
int Doxy::errors protected
the number of errors that have occurred
Definition at line 169 of file Doxy.hh.
Referenced by Doxy(), get_errors(), and gv_to_png().
nodes
std::vector<const Function *> Doxy::nodes protected
the nodes for the current root.
Definition at line 157 of file Doxy.hh.
Referenced by node_ID(), set_call_graph_root(), and write_call_graph().
out
ostream& Doxy::out protected
the command output channel (COUR or CERR)
Definition at line 148 of file Doxy.hh.
Referenced by add_fun_to_call_graph(), Doxy(), function_page(), gen(), gv_to_png(), native_page(), set_call_graph_root(), write_call_graph(), and write_css().
root_dir
UTF8_string Doxy::root_dir protected
the directory that shall contain all documentation files
Definition at line 154 of file Doxy.hh.
Referenced by Doxy(), function_page(), gen(), get_root_dir(), native_page(), write_call_graph(), and write_css().
ws_name
UCS_string Doxy::ws_name protected
the name of the workspace (for HTML output)
Definition at line 151 of file Doxy.hh.
Referenced by Doxy(), and gen().
The documentation for this class was generated from the following files:
src/Doxy.hh
src/Doxy.cc