GNU APL: Backtrace Class Reference
Backtrace Class Reference
show the current function call stack.
#include <Backtrace.hh>
Classes
struct PC_src
a mapping from PCs to source lines.
Static Public Member Functions
static void show (const char *file, int line)
show the current function call stack.
static const char * caller (int offset)
show the current caller (only valid while being called)
Protected Types
enum _lines_status {
LINES_not_checked ,
LINES_outdated ,
LINES_valid
}
the status of file apl.lines
Static Protected Member Functions
static int demangle_line (char *result, size_t result_max, const char *buf)
demangle a line returned by backtrace_symbols()
static const char * find_src (int64_t pc)
find the source for PC pc
static void open_lines_file ()
open file apl.lines
static void show_item (int idx, char *s)
show one item in the backtrace
static int pc_cmp (const int64_t &key, const Backtrace::PC_src &pc2, const void *)
compare PCs (helper for binary search)
Static Protected Attributes
static _lines_status lines_status = Backtrace::LINES_not_checked
the status of file apl.lines
static std::vector< PC_src > pc_2_src
a mapping from PCs to source lines.
Detailed Description
show the current function call stack.
Definition at line 31 of file Backtrace.hh.
Member Enumeration Documentation
_lines_status
enum Backtrace::_lines_status protected
the status of file apl.lines
Enumerator
LINES_not_checked
status is unknown
LINES_outdated
file is outdated
LINES_valid
file is up-to-date
Definition at line 54 of file Backtrace.hh.
Member Function Documentation
caller()
const char * Backtrace::caller (int offset) static
show the current caller (only valid while being called)
Definition at line 406 of file Backtrace.cc.
References demangle_line().
demangle_line()
int Backtrace::demangle_line (char * result, size_t result_max, const char * buf) static protected
demangle a line returned by backtrace_symbols()
Definition at line 376 of file Backtrace.cc.
Referenced by caller().
find_src()
const char * Backtrace::find_src (int64_t pc) static protected
find the source for PC pc
Definition at line 61 of file Backtrace.cc.
References pc_2_src, and pc_cmp().
Referenced by show_item().
open_lines_file()
void Backtrace::open_lines_file () static protected
open file apl.lines
Definition at line 77 of file Backtrace.cc.
References LINES_not_checked, LINES_outdated, lines_status, LINES_valid, main(), Backtrace::PC_src::pc, pc_2_src, and Backtrace::PC_src::src_loc.
Referenced by show().
pc_cmp()
int Backtrace::pc_cmp (const int64_t & key, const Backtrace::PC_src & pc2, const void *) static protected
compare PCs (helper for binary search)
Definition at line 55 of file Backtrace.cc.
References Backtrace::PC_src::pc.
Referenced by find_src().
show()
void Backtrace::show (const char * file, int line) static
show the current function call stack.
Definition at line 316 of file Backtrace.cc.
References open_lines_file(), and show_item().
show_item()
void Backtrace::show_item (int idx, char * s) static protected
show one item in the backtrace
Definition at line 218 of file Backtrace.cc.
References find_src().
Referenced by show().
Member Data Documentation
lines_status
Backtrace::_lines_status Backtrace::lines_status = Backtrace::LINES_not_checked static protected
the status of file apl.lines
Definition at line 62 of file Backtrace.hh.
Referenced by open_lines_file().
pc_2_src
std::vector< Backtrace::PC_src > Backtrace::pc_2_src static protected
a mapping from PCs to source lines.
Definition at line 72 of file Backtrace.hh.
Referenced by find_src(), and open_lines_file().
The documentation for this class was generated from the following files:
src/Backtrace.hh
src/Backtrace.cc