GNU APL: InputMux Class Reference
InputMux Class Reference
a multiplexer selecting the input to the APL interpreter
#include <LineInput.hh>
Static Public Member Functions
static void get_line (LineInputMode mode, const UCS_string &prompt, UCS_string &line, bool &eof, LineHistory &hist)
get one line
static get_line_cb * install_get_line_callback (get_line_cb *new_callback)
install a get_line() replacement, return old one
Static Protected Attributes
static get_line_cb * get_line_callback = 0
the callback that was installed with install_get_line_callback(). It will be called instead of get_line() if non-0
Detailed Description
a multiplexer selecting the input to the APL interpreter
InputMux fetches one line from either an input file, or interactively from the user if no input file is present
Definition at line 287 of file LineInput.hh.
Member Function Documentation
get_line()
void InputMux::get_line (LineInputMode mode, const UCS_string & prompt, UCS_string & line, bool & eof, LineHistory & hist) static
get one line
Definition at line 758 of file LineInput.cc.
References Workspace::add_wait(), UCS_string::append_UTF8(), UTF8_string::c_str(), Command::cmd_OFF(), UserPreferences::control_Ds_to_exit, TakeDropIterator::done, UserPreferences::echo_CIN, UTF8_string::erase(), IO_Files::get_file_line(), get_line_callback, LineInput::get_terminal_line(), InputFile::increment_current_line_no(), InputFile::is_validating(), Thread_context::kill_pool(), CPU_pool::lock_pool(), UCS_string::pop_back(), InputFile::pushed_file(), UserPreferences::raw_cin, UserPreferences::silent, UCS_string::size(), and CPU_pool::unlock_pool().
install_get_line_callback()
static get_line_cb * InputMux::install_get_line_callback (get_line_cb * new_callback) inline static
install a get_line() replacement, return old one
Definition at line 295 of file LineInput.hh.
References get_line_callback.
Member Data Documentation
get_line_callback
get_line_cb * InputMux::get_line_callback = 0 static protected
the callback that was installed with install_get_line_callback(). It will be called instead of get_line() if non-0
Definition at line 305 of file LineInput.hh.
Referenced by get_line(), and install_get_line_callback().
The documentation for this class was generated from the following files:
src/LineInput.hh
src/LineInput.cc