GNU APL: Quad_TF Class Reference
Quad_TF Class Reference
The class implementing ⎕TF.
#include <Quad_TF.hh>
Public Member Functions
Quad_TF ()
Constructor.
virtual Token eval_AB (Value_P A, Value_P B) const
Overloaded Function::eval_AB().
Public Member Functions inherited from QuadFunction
QuadFunction (TokenTag tag)
Constructor.
virtual bool has_alpha () const
overloaded Function::has_alpha()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B().
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB().
virtual bool has_result () const
overloaded Function::has_result()
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
virtual bool has_result () const
overloaded Function::has_result()
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Static Public Member Functions
static bool is_inverse (const UCS_string &maybe_name)
return true if val contains an 1⎕TF or 2⎕TF record
static Value_P tf1 (const UCS_string &symbol_name)
return B in transfer format 1 (old APL format)
static Token tf2 (const UCS_string &symbol_name)
return B in transfer format 2 (new APL2 format)
static Value_P tf3 (const UCS_string &symbol_name)
return B in transfer format 3 (APL2 CDR format)
static void tf2_value (int level, UCS_string &ucs, const Value &value, ShapeItem nesting)
append ravel of value in tf2_format to ucs. Return true iff the value should be enclosed in parentheses when grouped.
static void tf2_fun_ucs (UCS_string &ucs, const UCS_string &fun_name, const Function &fun)
store B in transfer format 2 (new APL format) into ucs
static void tf2_char_vec (UCS_string &ucs, const UCS_string &vec)
store simple character vector vec in ucs, either as 'xxx' or as (UCS nn nnn ...)
static UCS_string no_UCS (const UCS_string &ucs)
undo ⎕UCS() created by tf2_char_vec
static UCS_string tf2_inverse (const UCS_string &ravel)
try inverse ⎕TF2 of ucs, set new_var_or_fun if successful
static Token tf2_var (const UCS_string &var_name, const Value &val)
return B in transfer format 2 (new APL format) for a variable
Static Public Attributes
static Quad_TF * fun = &Quad_TF::_fun
Built-in function.
static Quad_TF _fun
Built-in function.
Static Protected Member Functions
static void tf2_shape (UCS_string &ucs, const Shape &shape, ShapeItem nesting)
append shape in tf2_format to ucs.
static void tf2_ravel (int level, UCS_string &ucs, const ShapeItem len, const Cell *cells)
append ravel cells in tf2_format to ucs.
static void tf2_all_char_ravel (int level, UCS_string &ucs, const Value &value)
append the ravel of a simple character array (of any rank)
static Value_P tf1 (const UCS_string &var_name, Value_P B)
return B in transfer format 1 (old APL format) for variable B
static Value_P tf1 (const UCS_string &fun_name, const Function &B)
return B in transfer format 1 (old APL format) for function B
static Value_P tf1_inv (const UCS_string &ravel)
return inverse transfer format 1 (old APL format) for a variable
static void tf2_reduce (Token_string &tos)
simplify tos by removing UCS nnn etc.
static bool tf2_reduce_ENCLOSE (Token_string &tos)
replace pattern ⊂ B in tos with the single token (⊂B); return true iff done so.
static bool tf2_reduce_RHO (Token_string &tos)
replace pattern A ⍴ B in tos with the single token (A⍴B); return true iff done so.
static bool tf2_reduce_sequence (Token_string &tos)
replace pattern N - ⎕IO - ⍳ K in tos with N N+1 ... N+K-1; return true iff done so.
static bool tf2_reduce_sequence1 (Token_string &tos)
replace pattern N - M × ⎕IO - ⍳ K in tos with M × (N N+1 ... N+K-1); return true iff done so.
static bool tf2_reduce_parentheses (Token_string &tos)
replace pattern (B) in tos with B; return true iff done so.
static bool tf2_glue (Token_string &tos)
replace pattern value1 value2... in tos with the single token
static bool tf2_reduce_COMMA (Token_string &tos)
replace pattern , B in tos with single token (,B); return true iff done so.
static UCS_string tf2_fun (const UCS_string &fun_name, const Function &fun)
return B in transfer format 2 (new APL format) for a function
static bool tf2_reduce_ENCLOSE_ENCLOSE (Token_string &tos)
replace pattern ⊂ ⊂ B in tos with the single token (⊂⊂B)
static bool tf2_reduce_ENCLOSE1 (Token_string &tos)
replace pattern ⊂ B in tos with the single token (⊂B)
static void tf2_reduce_UCS (Token_string &tos)
replace ⎕UCS n... with the corresponding Unicodes,
static ShapeItem tf2_toggle_UCS (Value &val)
in-place exchange of IntCells and CharCells
Additional Inherited Members
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
The class implementing ⎕TF.
The system function Quad-TF (Transfer Form).
Definition at line 29 of file Quad_TF.hh.
Constructor & Destructor Documentation
Quad_TF()
Quad_TF::Quad_TF () inline
Constructor.
Definition at line 33 of file Quad_TF.hh.
Member Function Documentation
eval_AB()
Token Quad_TF::eval_AB (Value_P A, Value_P B) const virtual
Overloaded Function::eval_AB().
Reimplemented from QuadFunction.
Definition at line 41 of file Quad_TF.cc.
References is_inverse(), tf1(), tf1_inv(), tf2(), tf2_inverse(), and tf3().
is_inverse()
bool Quad_TF::is_inverse (const UCS_string & maybe_name) static
return true if val contains an 1⎕TF or 2⎕TF record
Definition at line 81 of file Quad_TF.cc.
References Avec::is_quad(), Avec::is_symbol_char(), and UCS_string::size().
Referenced by eval_AB().
no_UCS()
UCS_string Quad_TF::no_UCS (const UCS_string & ucs) static
undo ⎕UCS() created by tf2_char_vec
Definition at line 1430 of file Quad_TF.cc.
References UCS_string::append(), and UCS_string::size().
Referenced by tf2_inverse().
tf1() [1/3]
Value_P Quad_TF::tf1 (const UCS_string & fun_name, const Function & B) static protected
return B in transfer format 1 (old APL format) for function B
Definition at line 203 of file Quad_TF.cc.
References UCS_string::append(), UCS_string::append_number(), Function::canonical(), fun, and UCS_string::to_vector().
tf1() [2/3]
Value_P Quad_TF::tf1 (const UCS_string & symbol_name) static
return B in transfer format 1 (old APL format)
Definition at line 99 of file Quad_TF.cc.
References NamedObject::get_function(), NamedObject::get_symbol(), NamedObject::is_user_defined(), Workspace::lookup_existing_name(), and tf1().
Referenced by eval_AB(), and tf1().
tf1() [3/3]
Value_P Quad_TF::tf1 (const UCS_string & var_name, Value_P B) static protected
return B in transfer format 1 (old APL format) for variable B
Definition at line 127 of file Quad_TF.cc.
References UCS_string::append(), UCS_string::append_number(), Cell::get_char_value(), Cell::get_imag_value(), Cell::get_int_value(), Cell::get_real_value(), Cell::is_character_cell(), Cell::is_integer_cell(), Cell::is_near_real(), Cell::is_numeric(), and UCS_string::size().
tf1_inv()
Value_P Quad_TF::tf1_inv (const UCS_string & ravel) static protected
return inverse transfer format 1 (old APL format) for a variable
Definition at line 230 of file Quad_TF.cc.
References Shape::add_shape_item(), UCS_string::append(), Quad_FX::do_eval_B(), Value_P_Base::get(), Token::get_cpx_imag(), Token::get_cpx_real(), Token::get_flt_val(), Token::get_int_val(), NamedObject::get_NC(), NamedObject::get_symbol(), Token::get_tag(), Shape::get_volume(), Avec::is_digit(), Avec::is_first_symbol_char(), Avec::is_quad(), Symbol::is_readonly(), Avec::is_symbol_char(), Workspace::lookup_existing_name(), Workspace::lookup_symbol(), UCS_string::size(), Function::tag, and Tokenizer::tokenize().
Referenced by eval_AB().
tf2()
Token Quad_TF::tf2 (const UCS_string & symbol_name) static
return B in transfer format 2 (new APL2 format)
Definition at line 445 of file Quad_TF.cc.
References Symbol::get_apl_value(), NamedObject::get_function(), NamedObject::get_symbol(), NamedObject::is_user_defined(), Workspace::lookup_existing_name(), tf2_fun(), and tf2_var().
Referenced by eval_AB().
tf2_all_char_ravel()
void Quad_TF::tf2_all_char_ravel (int level, UCS_string & ucs, const Value & value) static protected
append the ravel of a simple character array (of any rank)
Definition at line 772 of file Quad_TF.cc.
References UCS_string::append(), UCS_string::append_number(), UCS_string::append_UTF8(), and Avec::need_UCS().
Referenced by tf2_value().
tf2_char_vec()
void Quad_TF::tf2_char_vec (UCS_string & ucs, const UCS_string & vec) static
store simple character vector vec in ucs, either as 'xxx' or as (UCS nn nnn ...)
Definition at line 1395 of file Quad_TF.cc.
References UCS_string::append(), UCS_string::append_number(), UCS_string::append_UTF8(), Avec::need_UCS(), and UCS_string::size().
Referenced by tf2_fun_ucs().
tf2_fun()
UCS_string Quad_TF::tf2_fun (const UCS_string & fun_name, const Function & fun) static protected
return B in transfer format 2 (new APL format) for a function
Definition at line 1353 of file Quad_TF.cc.
References fun, and tf2_fun_ucs().
Referenced by tf2().
tf2_fun_ucs()
void Quad_TF::tf2_fun_ucs (UCS_string & ucs, const UCS_string & fun_name, const Function & fun) static
store B in transfer format 2 (new APL format) into ucs
Definition at line 1362 of file Quad_TF.cc.
References UCS_string::append(), UCS_string::append_UTF8(), Function::canonical(), fun, Function::is_native(), tf2_char_vec(), and UCS_string::to_vector().
Referenced by tf2_fun(), and Symbol::write_OUT().
tf2_glue()
bool Quad_TF::tf2_glue (Token_string & tos) static protected
replace pattern value1 value2... in tos with the single token
Definition at line 1315 of file Quad_TF.cc.
References Token::move_1().
Referenced by tf2_reduce().
tf2_inverse()
UCS_string Quad_TF::tf2_inverse (const UCS_string & ravel) static
try inverse ⎕TF2 of ucs, set new_var_or_fun if successful
Definition at line 517 of file Quad_TF.cc.
References Quad_FX::do_eval_AB(), Quad_FX::do_quad_FX(), Value_P_Base::get(), Token::get_apl_val(), Token::get_Class(), Function::get_tag(), no_UCS(), Token_string::print(), and tf2_reduce().
Referenced by Command::transfer_context::array_2TF(), eval_AB(), and Command::transfer_context::function_2TF().
tf2_ravel()
void Quad_TF::tf2_ravel (int level, UCS_string & ucs, const ShapeItem len, const Cell * cells) static protected
append ravel cells in tf2_format to ucs.
Definition at line 717 of file Quad_TF.cc.
References UCS_string::append(), Cell::character_representation(), Cell::get_imag_value(), Cell::get_pointer_value(), Cell::get_real_value(), Cell::is_complex_cell(), Cell::is_float_cell(), Cell::is_lval_cell(), Cell::is_pointer_cell(), PrintBuffer::l1(), and tf2_value().
Referenced by tf2_value().
tf2_reduce()
void Quad_TF::tf2_reduce (Token_string & tos) static protected
simplify tos by removing UCS nnn etc.
Definition at line 814 of file Quad_TF.cc.
References Token_string::print(), tf2_glue(), tf2_reduce_COMMA(), tf2_reduce_ENCLOSE(), tf2_reduce_ENCLOSE1(), tf2_reduce_ENCLOSE_ENCLOSE(), tf2_reduce_parentheses(), tf2_reduce_RHO(), tf2_reduce_sequence(), tf2_reduce_sequence1(), and tf2_reduce_UCS().
Referenced by tf2_inverse().
tf2_reduce_COMMA()
bool Quad_TF::tf2_reduce_COMMA (Token_string & tos) static protected
replace pattern , B in tos with single token (,B); return true iff done so.
Definition at line 1115 of file Quad_TF.cc.
References Function::get_tag().
Referenced by tf2_reduce().
tf2_reduce_ENCLOSE()
bool Quad_TF::tf2_reduce_ENCLOSE (Token_string & tos) static protected
replace pattern ⊂ B in tos with the single token (⊂B); return true iff done so.
Definition at line 1067 of file Quad_TF.cc.
Referenced by tf2_reduce().
tf2_reduce_ENCLOSE1()
bool Quad_TF::tf2_reduce_ENCLOSE1 (Token_string & tos) static protected
replace pattern ⊂ B in tos with the single token (⊂B)
Definition at line 1216 of file Quad_TF.cc.
Referenced by tf2_reduce().
tf2_reduce_ENCLOSE_ENCLOSE()
bool Quad_TF::tf2_reduce_ENCLOSE_ENCLOSE (Token_string & tos) static protected
replace pattern ⊂ ⊂ B in tos with the single token (⊂⊂B)
Definition at line 1183 of file Quad_TF.cc.
Referenced by tf2_reduce().
tf2_reduce_parentheses()
bool Quad_TF::tf2_reduce_parentheses (Token_string & tos) static protected
replace pattern (B) in tos with B; return true iff done so.
Definition at line 1266 of file Quad_TF.cc.
References Token::extract_apl_val(), Token::get_apl_val(), Token::get_tag(), and Token::move_1().
Referenced by tf2_reduce().
tf2_reduce_RHO()
bool Quad_TF::tf2_reduce_RHO (Token_string & tos) static protected
replace pattern A ⍴ B in tos with the single token (A⍴B); return true iff done so.
Definition at line 900 of file Quad_TF.cc.
References Bif_F12_RHO::do_reshape(), and Shape::get_volume().
Referenced by tf2_reduce().
tf2_reduce_sequence()
bool Quad_TF::tf2_reduce_sequence (Token_string & tos) static protected
replace pattern N - ⎕IO - ⍳ K in tos with N N+1 ... N+K-1; return true iff done so.
Definition at line 955 of file Quad_TF.cc.
Referenced by tf2_reduce().
tf2_reduce_sequence1()
bool Quad_TF::tf2_reduce_sequence1 (Token_string & tos) static protected
replace pattern N - M × ⎕IO - ⍳ K in tos with M × (N N+1 ... N+K-1); return true iff done so.
Definition at line 1009 of file Quad_TF.cc.
Referenced by tf2_reduce().
tf2_reduce_UCS()
void Quad_TF::tf2_reduce_UCS (Token_string & tos) static protected
replace ⎕UCS n... with the corresponding Unicodes,
Definition at line 836 of file Quad_TF.cc.
References tf2_toggle_UCS().
Referenced by tf2_reduce().
tf2_shape()
void Quad_TF::tf2_shape (UCS_string & ucs, const Shape & shape, ShapeItem nesting) static protected
append shape in tf2_format to ucs.
Definition at line 652 of file Quad_TF.cc.
References UCS_string::append(), UCS_string::append_number(), Shape::get_rank(), and Shape::get_shape_item().
Referenced by tf2_value().
tf2_toggle_UCS()
ShapeItem Quad_TF::tf2_toggle_UCS (Value & val) static protected
in-place exchange of IntCells and CharCells
Definition at line 869 of file Quad_TF.cc.
References Cell::get_char_value(), Value::get_cravel(), Cell::get_int_value(), Cell::get_pointer_value(), Cell::is_character_cell(), Value::is_empty(), Cell::is_integer_cell(), Cell::is_pointer_cell(), Value::nz_element_count(), Value::set_ravel_Char(), Value::set_ravel_Int(), tf2_toggle_UCS(), and Value::to_type().
Referenced by tf2_reduce_UCS(), and tf2_toggle_UCS().
tf2_value()
void Quad_TF::tf2_value (int level, UCS_string & ucs, const Value & value, ShapeItem nesting) static
append ravel of value in tf2_format to ucs. Return true iff the value should be enclosed in parentheses when grouped.
Definition at line 672 of file Quad_TF.cc.
References UCS_string::append(), Cell::is_character_cell(), tf2_all_char_ravel(), tf2_ravel(), and tf2_shape().
Referenced by tf2_ravel(), and tf2_var().
tf2_var()
Token Quad_TF::tf2_var (const UCS_string & var_name, const Value & val) static
return B in transfer format 2 (new APL format) for a variable
the right hand side of VAR←VALUE
Definition at line 484 of file Quad_TF.cc.
References UCS_string::append(), Cell::get_pointer_value(), Cell::is_pointer_cell(), UCS_string::size(), and tf2_value().
Referenced by tf2(), and Symbol::write_OUT().
tf3()
Value_P Quad_TF::tf3 (const UCS_string & symbol_name) static
return B in transfer format 3 (APL2 CDR format)
Definition at line 1466 of file Quad_TF.cc.
References Value_P_Base::get(), Symbol::get_apl_value(), NamedObject::get_function(), NamedObject::get_symbol(), Workspace::lookup_existing_name(), and CDR::to_CDR().
Referenced by eval_AB().
Member Data Documentation
_fun
Quad_TF Quad_TF::_fun static
Built-in function.
Definition at line 39 of file Quad_TF.hh.
fun
Quad_TF * Quad_TF::fun = &Quad_TF::_fun static
Built-in function.
Definition at line 38 of file Quad_TF.hh.
Referenced by tf1(), tf2_fun(), and tf2_fun_ucs().
The documentation for this class was generated from the following files:
src/Quad_TF.hh
src/Quad_TF.cc