GNU APL: Macro Class Reference
Macro Class Reference
a system function or operator implemented as an internal defined function
#include <Macro.hh>
Public Types
enum Macro_num {
MAC_COUNT ,
MAC_NONE = -1
}
the unique number of a macro
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Member Functions
Macro (Macro_num num, const char *text)
constructor
virtual bool is_macro () const
overloaded Function::is_macro()
virtual int get_macnum () const
overloaded UserFunction::get_macnum()
Public Member Functions inherited from UserFunction
UserFunction (Fun_signature sig, int lambda_num, const UCS_string &text, Token_string &body)
constructor for a lambda
~UserFunction ()
Destructor.
virtual bool is_lambda () const
overloaded Function::is_lambda()
virtual bool is_defined () const
overloaded Function::is_defined()
virtual int get_macnum () const
return the macro number (if this function is one) or -1
virtual const UserFunction * get_exec_ufun () const
overloaded Executable::get_exec_ufun()
virtual const UserFunction * get_func_ufun () const
overloaded Function::get_func_ufun()
virtual UserFunction * get_exec_ufun ()
overloaded Executable::get_exec_ufun()
virtual int get_fun_valence () const
overloaded Function::get_fun_valence()
virtual int get_oper_valence () const
overloaded Function::get_oper_valence()
virtual bool has_result () const
overloaded Function::has_result()
virtual bool has_axis () const
overloaded Function::has_axis()
bool localizes (const Symbol *sym) const
return true if this function localizes sym
void pop_local_vars () const
pop all
void print_local_vars (ostream &out) const
print the local variables for command)SINL
ShapeItem local_var_count () const
return the number of local variables
const Symbol * get_local_var (ShapeItem idx) const
return the idx'th local variable
virtual bool is_operator () const
Overloaded Function::is_operator.
void add_label (Symbol *sym, Function_Line line)
add a label
virtual const int * get_exec_properties () const
return the execution properties (dyadic ⎕FX) of this defined function
virtual bool cannot_suspend () const
ovewrloaded Executable::cannot_suspend
void set_exec_properties (const int *props)
set execution properties (as per A ⎕FX)
virtual ostream & print (ostream &out) const
overloaded Executable::print()
virtual UCS_string get_name () const
return the name of this function
UCS_string get_name_and_line (Function_PC pc) const
return e.g. 'FOO[10]'
virtual void print_properties (ostream &out, int indent) const
Overloaded Function::print_properties()
void save (const char *workspace, const char *function)
)SAVE this function in the workspace named workspace (in the file system).
virtual void destroy ()
overloaded Function::destroy()
virtual bool pushes_sym (const Symbol *sym) const
overloaded Executable::pushes_sym() const
void help (ostream &out) const
print help for this function on out (for the)HELP command)
Function_PC pc_for_line (Function_Line line) const
return the pc of the first token in line l (valid line), or the pc of the last token in the function (invalid line)
virtual bool has_alpha () const
Overloaded Function::has_alpha()
virtual Symbol * get_sym_Z () const
overloaded Executable::get_sym_Z()
Function_Line get_line (Function_PC pc) const
overloaded Executable::get_line()
virtual Token eval_ () const
Overloaded Function::eval_()
virtual Token eval_B (Value_P B) const
Overloaded Function::eval_B()
virtual Token eval_XB (Value_P X, Value_P B) const
Overloaded Function::eval_XB()
virtual Token eval_AB (Value_P A, Value_P B) const
Overloaded Function::eval_AB()
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
Overloaded Function::eval_AXB()
virtual Token eval_LB (Token &LO, Value_P B) const
Overloaded Function::eval_LB.
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
Overloaded Function::eval_LXB()
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
Overloaded Function::eval_ALB.
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
Overloaded Function::eval_ALXB()
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
Overloaded Function::eval_LRB()
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
Overloaded Function::eval_LRXB()
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
Overloaded Function::eval_ALRB()
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
Overloaded Function::eval_ALRXB()
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Function_PC line_start (Function_Line line) const
overloaded Executable::line_start()
virtual void adjust_line_starts ()
overloaded Executable::adjust_line_starts
void set_locked_error_info (Error &error) const
compute lines 2 and 3 in error
const UTF8_string get_creator () const
return the entity that has created the function
void set_trace_stop (std::vector< Function_Line > &lines, bool stop)
set trace or stop vector
ErrorCode transform_multi_line_strings ()
transform a function body containing (old-style) multi-lines into a standard function body
ErrorCode transform_multi_line_strings_3 ()
transform a function body containing (new-style) multi-lines into a standard function body
void parse_body (const char *loc, bool tolerant, bool macro)
recompile the body
const std::vector< Function_Line > & get_stop_lines () const
return stop lines (from S∆fun ← lines)
const std::vector< Function_Line > & get_trace_lines () const
return trace lines (from S∆fun ← lines)
const UserFunction_header & get_header () const
return the header object (return value name, argument names, local vars, and function name) for this function
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Public Member Functions inherited from Executable
Executable (const UCS_string &ucs, bool multi_line, ParseMode pm, const char *loc)
constructor
Executable (Fun_signature sig, int lambda_num, const UCS_string &lambda_text, const char *loc)
constructor for lambdas
virtual ~Executable ()
destructor: release values held by the body
ParseMode get_parse_mode () const
the parse mode of this Executable
void clear_body ()
delete values in body and (maybe) remove lambdas
virtual UCS_string get_name () const =0
return the name of this function, or ◊ or ⍎
virtual bool cannot_suspend () const
return true iff this Executable cannot be suspended
virtual Symbol * get_sym_Z () const
return the result symbol iff this is a user defined function or operator that returns a value
virtual const UserFunction * get_exec_ufun () const
return a UserFunction * (if this is one) or else 0.
virtual bool pushes_sym (const Symbol *sym) const
return true if this Executable localizes Symbol sym
virtual UserFunction * get_exec_ufun ()
return a UserFunction * (if this is one) or else 0.
virtual Function_Line get_line (Function_PC pc) const
get the line number for pc
virtual ostream & print (ostream &out) const
print this user defined executable to out
void print_token (ostream &out) const
print this user defined executable to out
void print_text (ostream &out) const
print the text of this user defined executable to out
Token execute_body () const
execute the body of this executable
const Token_string & get_body () const
return the body of this executable
const int get_text_size () const
return number of function lines (including header line 0)
const UCS_string & get_text (int l) const
return function line n (0 = header line)
void clear_text (int l)
clear the text of line n (0 = header line)
void set_text (int l, const UCS_string &new_line)
set the text of line n (0 = header line)
UCS_string statement_text (Function_PC pc) const
return the text of statement at pc
virtual Function_PC line_start (Function_Line line) const
return the first PC of the line
virtual void adjust_line_starts ()
adjust line starts before calling Parser::remove_void_token(body)
void set_error_info (Error &error, Function_PC2 range) const
compute lines 2 and 3 in error
Function_PC get_statement_start (int pc) const
return the start of the statement to which pc belongs
void unmark_all_values () const
clear marked flag in all body token
int show_owners (const char *prefix, ostream &out, const Value &value) const
print all owners of value
const char * get_loc () const
say where this SI entry was allocated
void increment_refcount (const char *loc)
increment the reference counter
void decrement_refcount (const char *loc)
decrement the reference counter
Static Public Member Functions
static void unmark_all_macros ()
unmark all values used in the bodies of all macros
static Macro * get_macro (Macro_num num)
return the macro with macro_number num
Static Public Member Functions inherited from UserFunction
static UserFunction * load (const char *workspace, const char *function)
)LOAD this function into the workspace named workspace. Return a pounter to this newly created function (or 0 on error).
static void load (const char *workspace, const char *function, UserFunction *&fun)
Load this function into the workspace named workspace.
static UserFunction * fix (const UCS_string &text, int &err_line, bool keep_existing, const char *loc, const UTF8_string &creator, bool tolerant)
create a user defined function according to data of length len in workspace w.
static UserFunction * fix_lambda (Symbol &var, const UCS_string &text)
(re-)create a lambda
Static Public Attributes
static Macro * all_macros [MAC_COUNT]
a vector of all macros
Protected Attributes
const Macro_num macro_number
A (compile-time) unique number for this macro.
Protected Attributes inherited from UserFunction
UserFunction_header header
the header (line [0]) of the user-defined function
std::vector< Function_PC > line_starts
std::vector< Function_Line > stop_lines
stop lines (from S∆fun ← lines)
std::vector< Function_Line > trace_lines
trace lines (from S∆fun ← lines)
int exec_properties [4]
execution properties as per 3⎕AT
const UTF8_string creator
the entity (∇ editor, ⎕FX, or filename) that has created this function
int error_line
the line number where an error has occurred (-1 if none)
const char * error_info
information about an error (if any)
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Protected Attributes inherited from Executable
const char * alloc_loc
where this SI entry was allocated
const ParseMode pmode
the mode this Executable
UCS_string_vector text
the program text from which body was created
Token_string body
The token to be executed. They are organized line by line and statement by statement, but the token within a statement reversed due to the right-to-left execution of APL.
int refcount
reference counter (for lambdas)
Private Member Functions
~Macro ()
destructor (not supposed to be called)
Additional Inherited Members
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Member Functions inherited from UserFunction
UserFunction (const UCS_string txt, const char *loc, const UTF8_string &_creator, bool tolerant, bool macro)
constructor for a normal (i.e. non-lambda) user defined function
virtual bool may_push_SI () const
overladed Function::may_push_SI()
virtual Token eval_fill_B (Value_P B) const
Overloaded Function::eval_fill_B()
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Overloaded Function::eval_fill_AB()
int get_error_line () const
return the line number where an error has occurred (-1 if none)
const char * get_error_info () const
return information about an error (if any)
UCS_string line_prefix (Function_Line l) const
"[nn] " prefix
Protected Member Functions inherited from Executable
void setup_lambdas ()
extract all lambda expressions from body and store them in lambdas
ShapeItem setup_one_lambda (ShapeItem b, ShapeItem end, int lambda_num)
extract one lambda expressions from body and store it in lambdas
Fun_signature compute_lambda_body (Token_string &rev_lambda_body, ShapeItem b, ShapeItem bend)
body[b ... bend] is a lambda. Move these token from this body to the body of the lambda and clear them in this body.
UCS_string extract_lambda_text (Fun_signature signature, int skip) const
extract the skip'th { ... } from the function text
ErrorCode parse_body_line (Function_Line line, const UCS_string &ucs, bool trace, bool tolerant, const char *loc, bool macro)
parse the body line number line of this function
ErrorCode parse_body_line (Function_Line line, const Token_string &tos, bool trace, bool tolerant, const char *loc)
parse the body line number line of this function
Static Protected Member Functions inherited from UserFunction
static ostream & print_val_or_fun (ostream &out, Token &tok)
helper function to print token with Function or Value content
Static Protected Member Functions inherited from Executable
static void reverse_statement_token (Token_string &tos)
reverse the token order in every statement of tos
static void reverse_all_token (Token_string &tos)
reverse the token order of the entire Token_string
Detailed Description
a system function or operator implemented as an internal defined function
Definition at line 28 of file Macro.hh.
Member Enumeration Documentation
Macro_num
enum Macro::Macro_num
the unique number of a macro
Definition at line 32 of file Macro.hh.
Constructor & Destructor Documentation
Macro()
Macro::Macro (Macro_num num, const char * text)
constructor
Definition at line 29 of file Macro.cc.
References all_macros, UserFunction::error_info, UserFunction::error_line, and macro_number.
~Macro()
Macro::~Macro () private
destructor (not supposed to be called)
Definition at line 47 of file Macro.cc.
Member Function Documentation
get_macnum()
virtual int Macro::get_macnum () const inline virtual
overloaded UserFunction::get_macnum()
Reimplemented from UserFunction.
Definition at line 47 of file Macro.hh.
References macro_number.
get_macro()
Macro * Macro::get_macro (Macro_num num) static
return the macro with macro_number num
Definition at line 52 of file Macro.cc.
References all_macros.
Referenced by Bif_OPER2_RANK::do_ALyXB(), Quad_CR::do_eval_B(), Bif_OPER1_EACH::do_eval_LB(), Bif_OPER2_RANK::do_LyXB(), Quad_EA::eval_AB(), Quad_EB::eval_AB(), Quad_INP::eval_AB(), Bif_OPER1_EACH::eval_ALB(), Bif_OPER2_INNER::eval_ALRB(), Bif_OPER2_OUTER::eval_ALRB(), Bif_OPER2_POWER::eval_form_1(), Bif_OPER2_POWER::eval_form_2(), XML_Loading_Archive::read_Function(), XML_Loading_Archive::read_UserFunction(), Bif_REDUCE::reduce(), Bif_REDUCE::reduce_n_wise(), and Bif_SCAN::scan().
is_macro()
virtual bool Macro::is_macro () const inline virtual
overloaded Function::is_macro()
Reimplemented from Function.
Definition at line 44 of file Macro.hh.
unmark_all_macros()
void Macro::unmark_all_macros () static
unmark all values used in the bodies of all macros
Definition at line 60 of file Macro.cc.
Referenced by Value::print_stale().
Member Data Documentation
all_macros
Macro * Macro::all_macros static
a vector of all macros
Definition at line 60 of file Macro.hh.
Referenced by get_macro(), and Macro().
macro_number
const Macro_num Macro::macro_number protected
A (compile-time) unique number for this macro.
Definition at line 64 of file Macro.hh.
Referenced by get_macnum(), and Macro().
The documentation for this class was generated from the following files:
src/Macro.hh
src/Macro.cc