GNU APL: AxisIterator Class Reference
AxisIterator Class Reference
An iterator counting 0, 1, 2, ... ⍴[N-1] along one axis of length N.
#include <ArrayIterator.hh>
Public Member Functions
AxisIterator ()
default constructor for arrays. Initializes only the counters.
AxisIterator (ShapeItem len, ShapeItem weight, bool _wrap)
constructor for placement new. A weight of 0 indicates a scalar
bool next ()
bool more () const
true if more items coming
ShapeItem get_shape_offset () const
return the current shape offset (not weighted)
ShapeItem get_ravel_offset () const
return the current ravel offset (weighted)
ShapeItem get_weight () const
return the weight (ravel increment for one next() call of this iterator
ShapeItem get_total_weight () const
return the total weight (ravel increment for axis_length next() calls
bool is_scalar_iterator () const
true if this is an iterator for a scalar value.
Protected Attributes
ShapeItem axis_length
the length of the axis; the interator counts 0, 1, ... axis_length-1.
ShapeItem axis_weight
the weight (ravel increment) of this itertor (product of lower iterator weights). IMPORTANT: Scalars are flagged with an axis_weight of 0 here.
ShapeItem shape_offset
the current offset, 0, 1, ... axis_len (excluding)
ShapeItem ravel_offset
the current offset, 0, weight, ... weight*axis_len (excluding)
bool wrap
true iff this iterator shall wrap around at the end. In order for more() of the entire array to be fast, we wrap all iterators except the first at the end so that more() of the first iterator becomes false when iterating over entire array is done.
Detailed Description
An iterator counting 0, 1, 2, ... ⍴[N-1] along one axis of length N.
Definition at line 30 of file ArrayIterator.hh.
Constructor & Destructor Documentation
AxisIterator() [1/2]
AxisIterator::AxisIterator () inline
default constructor for arrays. Initializes only the counters.
Definition at line 34 of file ArrayIterator.hh.
AxisIterator() [2/2]
AxisIterator::AxisIterator (ShapeItem len, ShapeItem weight, bool _wrap) inline
constructor for placement new. A weight of 0 indicates a scalar
Definition at line 38 of file ArrayIterator.hh.
Member Function Documentation
get_ravel_offset()
ShapeItem AxisIterator::get_ravel_offset () const inline
return the current ravel offset (weighted)
Definition at line 73 of file ArrayIterator.hh.
References ravel_offset.
get_shape_offset()
ShapeItem AxisIterator::get_shape_offset () const inline
return the current shape offset (not weighted)
Definition at line 69 of file ArrayIterator.hh.
References shape_offset.
Referenced by ArrayIterator::get_shape_offset().
get_total_weight()
ShapeItem AxisIterator::get_total_weight () const inline
return the total weight (ravel increment for axis_length next() calls
Definition at line 81 of file ArrayIterator.hh.
References axis_length, and axis_weight.
Referenced by ArrayIterator::operator++().
get_weight()
ShapeItem AxisIterator::get_weight () const inline
return the weight (ravel increment for one next() call of this iterator
Definition at line 77 of file ArrayIterator.hh.
References axis_weight.
Referenced by ArrayIterator::operator++().
is_scalar_iterator()
bool AxisIterator::is_scalar_iterator () const inline
true if this is an iterator for a scalar value.
Definition at line 85 of file ArrayIterator.hh.
References axis_weight.
Referenced by more(), and next().
more()
bool AxisIterator::more () const inline
true if more items coming
Definition at line 64 of file ArrayIterator.hh.
References axis_length, is_scalar_iterator(), and shape_offset.
Referenced by ArrayIterator::more().
next()
bool AxisIterator::next () inline
increment the offset(s) and return:
true (= "carry") if the end of the axis was reached, or else false (= no more items) if the end was NOT reached
Definition at line 51 of file ArrayIterator.hh.
References axis_length, axis_weight, is_scalar_iterator(), ravel_offset, shape_offset, and wrap.
Referenced by ArrayIterator::operator++().
Member Data Documentation
axis_length
ShapeItem AxisIterator::axis_length protected
the length of the axis; the interator counts 0, 1, ... axis_length-1.
Definition at line 90 of file ArrayIterator.hh.
Referenced by get_total_weight(), more(), and next().
axis_weight
ShapeItem AxisIterator::axis_weight protected
the weight (ravel increment) of this itertor (product of lower iterator weights). IMPORTANT: Scalars are flagged with an axis_weight of 0 here.
Definition at line 94 of file ArrayIterator.hh.
Referenced by get_total_weight(), get_weight(), is_scalar_iterator(), and next().
ravel_offset
ShapeItem AxisIterator::ravel_offset protected
the current offset, 0, weight, ... weight*axis_len (excluding)
Definition at line 100 of file ArrayIterator.hh.
Referenced by get_ravel_offset(), and next().
shape_offset
ShapeItem AxisIterator::shape_offset protected
the current offset, 0, 1, ... axis_len (excluding)
Definition at line 97 of file ArrayIterator.hh.
Referenced by get_shape_offset(), more(), and next().
wrap
bool AxisIterator::wrap protected
true iff this iterator shall wrap around at the end. In order for more() of the entire array to be fast, we wrap all iterators except the first at the end so that more() of the first iterator becomes false when iterating over entire array is done.
Definition at line 106 of file ArrayIterator.hh.
Referenced by next().
The documentation for this class was generated from the following file:
src/ArrayIterator.hh