GNU APL: UCS_string Class Reference
UCS_string Class Reference
A string of Unicode characters (32-bit)
#include <UCS_string.hh>
Classes
class iterator
an iterator for UCS_strings
Public Member Functions
UCS_string ()
default constructor: empty string
UCS_string (Unicode uni)
constructor: one-element string
UCS_string (const Unicode *data, size_t len)
constructor: len Unicode characters, starting at data
UCS_string (size_t len, Unicode uni)
constructor: len times uni
UCS_string (const UCS_string &ucs)
constructor: copy of another UCS_string
UCS_string (const UCS_string &ucs, size_t pos, size_t len)
constructor: copy of another UCS_string ucs, starting at pos in ucs and length len
UCS_string (const UTF8_string &utf)
constructor: UCS_string from UTF8_string
UCS_string (const char *cstring)
constructor: UCS_string from 0-terminated C string. Do NOT use it for non-ASCII strings.
UCS_string (const PrintBuffer &pb, sRank rank, int quad_PW)
constructor: UCS_string from print buffer
UCS_string (APL_Float value, bool &scaled, const PrintContext &pctx)
constructor: UCS_string from a double with quad_pp valid digits. (eg. 3.33 has 3 digits), In standard APL format.
UCS_string (istream &in)
constructor: read one line from UTF8-encoded file.
UCS_string (const Value &value)
constructor: UCS_string from simple character vector value.
UCS_string (const Cell &cell)
constructor: UCS_string from a pointer Cell pointing to a character vector value (Asserts if not)
void create (const char *loc)
common part of all constructors
~UCS_string ()
destructor
template<typename T >
const T * raw () const
cast to an array of items with the same size as Unicode. This is for interfacing to libraries that have typedef'ed Unicodes differently.
UCS_string drop (int drop_count) const
return this string with the first drop_count characters removed
bool all_zeroes () const
return true if every character in this string is the digit '0'
Unicode back () const
return the last character in this string
int compute_chunk_length (int quad_PW, int col) const
compute the length of an output row
void copy_black (UCS_string &dest, int &idx) const
skip leading whitespaces starting at idx, append the following non-whitespaces (if any) to dest, and skip trailing whitespaces
uint32_t FNV_hash () const
return the FNV (Fowler-Noll-Vo) hash of this_string
ShapeItem LF_count () const
return the number of LF characters in this string
ShapeItem substr_pos (const UCS_string &sub) const
return the start position of sub in this string or -1 if sub is not contained in this string
bool has_black () const
return true if this string contains non-whitespace characters
bool starts_with (const char *prefix) const
return true if this starts with prefix (ASCII, case matters).
bool ends_with (const char *suffix) const
return true if this ends with suffix (ASCII, case matters).
bool starts_with (const UCS_string &prefix) const
return true if this starts with prefix (case sensitive).
bool starts_iwith (const char *prefix) const
return true if this starts with prefix (ASCII, case insensitive).
bool starts_iwith (const UCS_string &prefix) const
return true if this starts with prefix (case insensitive).
UCS_string no_pad () const
return a string like this, but with pad chars mapped to spaces
UCS_string reverse () const
return this string reversed (i.e. characters from back to front).
bool is_comment_or_label () const
return true if this string starts with # or ⍝ or x:
ShapeItem double_quote_count (bool in_quote2) const
return the number of unescaped and un-commented " in this string
ShapeItem double_quote_first () const
return the position of the first (leftmost) unescaped " in this string (if any), or else -1
ShapeItem double_quote_last () const
return the position of the last (rightmost) unescaped " in this string (if any), or else -1
int atoi () const
return integer value for a string starting with optional whitespaces, followed by digits.
UCS_string remove_pad () const
return a string like this, but with pad chars removed
size_t to_vector (UCS_string_vector &result) const
split this multi-line string into individual lines, removing the CR and NL chars in this string.
UCS_string un_escape (bool double_quoted, bool keep_LF) const
return this string with "escape sequences" replaced by their real characters ('' → ' if single quoted and \r, \n, \xNNN etc. otherwise.
UCS_string do_escape (bool double_quoted) const
the inverse of un_escape().
bool lexical_before (const UCS_string other) const
case-sensitive comparison: return true iff this comes before other
ostream & dump (ostream &out) const
dump this string to out (like U+nnn U+mmm ...)
UCS_string sort () const
sort the characters in this string by their Unicode
UCS_string unique () const
return the characters in this string (sorted and duplicates removed)
UCS_string to_HTML (int offset, bool preserve_ws) const
return this string HTML-escaped, starting at offset, and using for blanks
void remove_trailing_padchars ()
remove trailing pad characters
void remove_trailing_whitespaces ()
remove trailing blanks, tabs, etc
void remove_leading_whitespaces ()
remove leading blanks, tabs, etc
void remove_leading_and_trailing_whitespaces ()
remove leading and trailing whitespaces
void split_ws (UCS_string &rest)
this is a command with optional args. Remove leading and trailing whitespaces, append args to rest, and remove args from this.
Unicode & back ()
return the last character in this string
void map_pad ()
replace pad chars in this string by spaces
void pop_back ()
remove the last character in this string
void append (const UCS_string &other)
append UCS_string other to this string
void append_ASCII (const char *ascii)
append 0-terminated ASCII string str to this string. str is NOT interpreted as UTF8 string (use append_UTF8() instead of append_ASCII() if such interpretation is desired)
void append_UTF8 (const UTF8 *str)
append 0-terminated UTF8 string str to this UCS_string.
void append_UTF8 (const char *str)
same as app(const UTF8 * str)
void insert (ShapeItem pos, Unicode uni)
more intuitive insert() function
void prepend (Unicode uni)
prepend character uni
UCS_string operator+ (const UCS_string &other) const
return this string and other concatenated
UCS_string & operator<< (const char *str)
append C-string str
UCS_string & operator<< (ShapeItem num)
append number num
UCS_string & operator<< (Unicode uni)
append character uni
UCS_string & operator<< (const UCS_string &other)
append UCS_string other
Comp_result compare (const UCS_string &other) const
compare this with UCS_string other
void append_quoted (const UCS_string &other)
append other in quotes, doubling quoted in other
void append_number (ShapeItem num)
append number (in ASCII encoding like d) to this string
void append_hex (ShapeItem num, bool uppercase)
append number (in ASCII encoding like X or x) to this string
void append_shape (const Shape &shape)
append shape (in APL encoding tke left arg of ↑) this string
void append_members (const vector< const UCS_string * > &members, int m)
append members (like x.y.z) starting at members[m] and going backwards from the end of members to this string.
void append_float (APL_Float num)
append number (in ASCII encoding like lf) to this string
ShapeItem size () const
overload basic_string::size() so that it returns a signed length
UCS_string::iterator begin () const
an iterator set to the start of this string
void round_last_digit ()
round last digit and discard it. Note that this is always expected to be in floating point format and never in exponential format
bool contains (Unicode uni) const
return true if this string contains uni
void erase (ShapeItem pos)
erase 1 (!) character at pos
Static Public Member Functions
static bool greater_uni (const Unicode &u1, const Unicode &u2, const void *)
helper function for Heapsort<Unicode>::sort()
static UCS_string from_int (int64_t value)
convert a signed integer value to an UCS_string (like sprintf())
static UCS_string from_uint (uint64_t value)
convert an unsigned integer value to an UCS_string (like sprintf())
static UCS_string from_big (APL_Float &value)
convert the integer part of value to an UCS_string and remove it from value
static UCS_string from_double_to_expo (APL_Float value, int fract_digits)
convert the double value to an UCS_string scaled (exponential) format (with fract_digits fractional digits).
static UCS_string from_double_to_fixed (APL_Float value, int fract_digits)
convert the double value to an UCS_string in fixed point format (with fract_digits fractional digits).
static UCS_string from_double_expo_pp (APL_Float value, int quad_pp)
convert double value to an UCS_string with quad_pp significant digits in scaled (exponential) format
static UCS_string from_double_fixed_pp (APL_Float value, int quad_pp)
convert double value to an UCS_string with quad_pp significant digits in fixed point format
static ShapeItem get_total_count ()
return the total number of UCS_strings
static bool compare_names (const UCS_string &n1, const UCS_string &n2, const void *)
return true if n1 < n2
Static Protected Attributes
static ShapeItem total_count = 0
the total number of UCS_strings
static ShapeItem total_id = 0
the next unique instance_id
Private Member Functions
void * operator new[] (size_t size)
prevent accidental allocation
void operator delete[] (void *)
prevent accidental de-allocation
basic_string< Unicode > & erase (size_type pos, size_type len)
prevent accidental usage of the rather dangerous default len parameter in basic_strng::erase(pos, len = npos)
Detailed Description
A string of Unicode characters (32-bit)
Definition at line 47 of file UCS_string.hh.
Constructor & Destructor Documentation
UCS_string() [1/13]
UCS_string::UCS_string ()
default constructor: empty string
Definition at line 41 of file UCS_string.cc.
References create().
Referenced by drop(), from_uint(), to_vector(), and unique().
UCS_string() [2/13]
UCS_string::UCS_string (Unicode uni)
constructor: one-element string
Definition at line 46 of file UCS_string.cc.
References create().
UCS_string() [3/13]
UCS_string::UCS_string (const Unicode * data, size_t len)
constructor: len Unicode characters, starting at data
Definition at line 52 of file UCS_string.cc.
References create().
UCS_string() [4/13]
UCS_string::UCS_string (size_t len, Unicode uni)
constructor: len times uni
Definition at line 58 of file UCS_string.cc.
References create().
UCS_string() [5/13]
UCS_string::UCS_string (const UCS_string & ucs)
constructor: copy of another UCS_string
Definition at line 64 of file UCS_string.cc.
References create().
UCS_string() [6/13]
UCS_string::UCS_string (const UCS_string & ucs, size_t pos, size_t len)
constructor: copy of another UCS_string ucs, starting at pos in ucs and length len
Definition at line 70 of file UCS_string.cc.
References create().
UCS_string() [7/13]
UCS_string::UCS_string (const UTF8_string & utf)
constructor: UCS_string from UTF8_string
Definition at line 100 of file UCS_string.cc.
References append(), create(), and UTF8_string::dump_hex().
UCS_string() [8/13]
UCS_string::UCS_string (const char * cstring)
constructor: UCS_string from 0-terminated C string. Do NOT use it for non-ASCII strings.
Definition at line 76 of file UCS_string.cc.
References create().
UCS_string() [9/13]
UCS_string::UCS_string (const PrintBuffer & pb, sRank rank, int quad_PW)
constructor: UCS_string from print buffer
Definition at line 378 of file UCS_string.cc.
References append(), append_UTF8(), compute_chunk_length(), create(), PrintBuffer::get_column_count(), PrintBuffer::get_line(), PrintBuffer::get_row_count(), remove_trailing_padchars(), and size().
UCS_string() [10/13]
UCS_string::UCS_string (APL_Float value, bool & scaled, const PrintContext & pctx)
constructor: UCS_string from a double with quad_pp valid digits. (eg. 3.33 has 3 digits), In standard APL format.
Definition at line 197 of file UCS_string.cc.
References append(), append_number(), append_UTF8(), back(), create(), PrintContext::get_PP(), PrintContext::get_style(), insert(), FloatCell::map_FC(), pop_back(), and size().
UCS_string() [11/13]
UCS_string::UCS_string (istream & in)
constructor: read one line from UTF8-encoded file.
Definition at line 464 of file UCS_string.cc.
References append(), create(), and UTF8_string::getc().
UCS_string() [12/13]
UCS_string::UCS_string (const Value & value)
constructor: UCS_string from simple character vector value.
constructor
Definition at line 425 of file UCS_string.cc.
References append(), and create().
UCS_string() [13/13]
UCS_string::UCS_string (const Cell & cell)
constructor: UCS_string from a pointer Cell pointing to a character vector value (Asserts if not)
constructor
Definition at line 438 of file UCS_string.cc.
References append(), create(), Value_P_Base::get(), Cell::get_char_value(), Cell::get_pointer_value(), Cell::is_character_cell(), and Cell::is_pointer_cell().
~UCS_string()
UCS_string::~UCS_string () inline
destructor
Definition at line 104 of file UCS_string.hh.
References total_count.
Member Function Documentation
all_zeroes()
bool UCS_string::all_zeroes () const inline
return true if every character in this string is the digit '0'
Definition at line 125 of file UCS_string.hh.
References size().
Referenced by Format_sub::insert_fract_commas(), and Format_sub::insert_int_commas().
append()
void UCS_string::append (const UCS_string & other) inline
append UCS_string other to this string
Definition at line 260 of file UCS_string.hh.
Referenced by PrintBuffer::add_frame(), PrintBuffer::add_outer_frame(), Bif_F12_FORMAT::add_row(), Quad_XML::add_sorted_entities(), Quad_XML::all_members(), Quad_JSON::APL_to_JSON_string(), PrintBuffer::append_aligned(), append_float(), append_hex(), append_members(), append_number(), append_quoted(), append_shape(), PrintBuffer::append_ucs(), append_UTF8(), Command::transfer_context::array_2TF(), Quad_QUOTE::assign(), UserFunction::canonical(), Token::canonical(), CharCell::character_representation(), ComplexCell::character_representation(), FloatCell::character_representation(), IntCell::character_representation(), PointerCell::character_representation(), XML_Loading_Archive::check_compatibility(), Command::cmd_COPY_ONCE(), CollatingCache::CollatingCache(), Quad_CR::compute_prolog(), copy_black(), Quad_CR::do_CR10(), Quad_CR::do_CR10_item(), Quad_CR::do_CR10_structured(), Quad_CR::do_CR10_value(), Quad_CR::do_CR35(), Quad_CR::do_CR36(), do_escape(), Quad_FX::do_quad_FX(), Quad_FIO::do_scanf(), Quad_FIO::do_sprintf(), Command::do_USERCMD(), Nabla::edit(), Token::error_info(), Quad_AT::eval_AB(), Quad_SI::eval_AB(), Quad_GTK::eval_AXB(), Quad_GTK::eval_B(), Quad_ENV::eval_B(), Quad_SI::eval_B(), Quad_ES::event_simulate(), Executable::Executable(), TabExpansion::expand_APL_command(), TabExpansion::expand_distinguished_name(), TabExpansion::expand_filename(), TabExpansion::expand_wsname(), Executable::extract_lambda_text(), Bif_F12_FORMAT::Format_LIFER::fill_data_fields(), UserFunction::fix_lambda(), Bif_F12_FORMAT::format_by_example(), Bif_F12_FORMAT::Format_LIFER::format_left_side(), Bif_F12_FORMAT::Format_LIFER::Format_LIFER(), Bif_F12_FORMAT::format_one_col_by_spec(), Bif_F12_FORMAT::Format_LIFER::format_right_side(), from_big(), from_double_to_expo(), from_double_to_fixed(), from_uint(), Doxy::fun_anchor(), Command::transfer_context::function_2TF(), StateIndicator::function_name(), Quad_CR::Picker::get(), Error::get_error_line_3(), Nabla::FunLine::get_label_and_text(), UserFunction::get_name_and_line(), Command::transfer_context::get_nrs(), Workspace::get_quad(), XML_node::get_tagname(), Value::get_UCS_ravel(), Quad_FIO::group_thousands(), init_apl(), LineLabel::insert(), LineEditContext::insert_char(), Format_sub::insert_fract_commas(), Format_sub::insert_int_commas(), Command::lib_common(), SymbolTable::list(), NativeFunction::load_emacs_library(), XML_node::merge_range(), LineLabel::next(), no_pad(), Quad_TF::no_UCS(), NativeFunction::open_so_file(), PrintBuffer::pad_fraction(), UserFunction::parse_body(), Command::parse_from_to(), Nabla::parse_lineno(), Nabla::parse_oper(), LineEditContext::paste(), PrintBuffer::pb_for_function(), LineLabel::print(), Value::print_member(), LineLabel::print_prompt(), PrintBuffer::PrintBuffer(), Command::process_line(), XML_Loading_Archive::read_Function(), TabExpansion::read_matching_filenames(), XML_Loading_Archive::read_XML_string(), remove_pad(), reverse(), UserFunction::set_locked_error_info(), Executable::setup_one_lambda(), Quad_CR::short_ravel(), TabExpansion::show_alternatives(), Bif_F12_FORMAT::split_example_into_columns(), split_ws(), Nabla::start(), Executable::statement_text(), LineEditContext::tab_expansion(), Quad_TF::tf1(), Quad_TF::tf1_inv(), Quad_TF::tf2_all_char_ravel(), Quad_TF::tf2_char_vec(), Quad_TF::tf2_fun_ucs(), Quad_TF::tf2_ravel(), Quad_TF::tf2_shape(), Quad_TF::tf2_value(), Quad_TF::tf2_var(), to_HTML(), Tokenizer::tokenize_quad(), Tokenizer::tokenize_string1(), Tokenizer::tokenize_string2(), Tokenizer::tokenize_symbol(), UCS_string(), UCS_string_vector::UCS_string_vector(), un_escape(), unique(), Error::update_error_info(), UserFunction_header::UserFunction_header(), and Symbol::write_OUT().
append_ASCII()
void UCS_string::append_ASCII (const char * ascii) inline
append 0-terminated ASCII string str to this string. str is NOT interpreted as UTF8 string (use append_UTF8() instead of append_ASCII() if such interpretation is desired)
Definition at line 266 of file UCS_string.hh.
Referenced by Quad_FIO::do_sprintf(), Doxy::fun_anchor(), Quad_FIO::group_thousands(), Command::process_line(), and to_HTML().
append_float()
void UCS_string::append_float (APL_Float num)
append number (in ASCII encoding like lf) to this string
Definition at line 967 of file UCS_string.cc.
References append().
append_hex()
void UCS_string::append_hex (ShapeItem num, bool uppercase)
append number (in ASCII encoding like X or x) to this string
Definition at line 922 of file UCS_string.cc.
References append().
append_members()
void UCS_string::append_members (const vector< const UCS_string * > & members, int m)
append members (like x.y.z) starting at members[m] and going backwards from the end of members to this string.
Definition at line 957 of file UCS_string.cc.
References append().
append_number()
void UCS_string::append_number (ShapeItem num)
append number (in ASCII encoding like d) to this string
Definition at line 910 of file UCS_string.cc.
References append().
Referenced by PrintBuffer::add_frame(), XML_node::add_member(), append_shape(), Quad_CR::compute_prolog(), Quad_CR::do_CR10_item(), Nabla::edit(), Quad_SI::eval_AB(), Quad_SI::eval_B(), TabExpansion::expand_wsname(), Quad_CR::Picker::get_indexed(), UserFunction::get_name_and_line(), XML_node::get_tagname(), SymbolTable::list(), NativeFunction::load_emacs_library(), Quad_XML::name_unsplit(), operator<<(), Regexp::pcre_error(), LineLabel::print(), LineLabel::print_prompt(), XML_Loading_Archive::read_Function(), Token::show_trace(), Quad_TF::tf1(), Quad_TF::tf2_all_char_ravel(), Quad_TF::tf2_char_vec(), Quad_TF::tf2_shape(), UCS_string(), and UserFunction_header::UserFunction_header().
append_quoted()
void UCS_string::append_quoted (const UCS_string & other)
append other in quotes, doubling quoted in other
Definition at line 897 of file UCS_string.cc.
References append(), and size().
Referenced by Command::do_USERCMD().
append_shape()
void UCS_string::append_shape (const Shape & shape)
append shape (in APL encoding tke left arg of ↑) this string
Definition at line 935 of file UCS_string.cc.
References append(), append_number(), Shape::get_rank(), and Shape::get_shape_item().
Referenced by Quad_CR::compute_prolog(), Quad_CR::do_CR10_value(), and Quad_CR::Picker::get().
append_UTF8() [1/2]
void UCS_string::append_UTF8 (const char * str) inline
same as app(const UTF8 * str)
Definition at line 280 of file UCS_string.hh.
References append_UTF8().
append_UTF8() [2/2]
void UCS_string::append_UTF8 (const UTF8 * str)
append 0-terminated UTF8 string str to this UCS_string.
append_ascii() appends one Unicode per byte (i.e. strlen(str) in total), without checking for UTF8 sequences.
append_UTF8() appends one Unicode per UTF8 sequence (which is the same if all characteras are ASCII, but less if not.
Definition at line 887 of file UCS_string.cc.
References append().
Referenced by XML_node::add_member(), Quad_XML::add_sorted_entities(), Quad_JSON::APL_to_JSON_string(), append_UTF8(), Quad_CR::close_mode(), Quad_CR::compute_prolog(), XML_node::denormalize_attribute_value(), Quad_CR::do_CR10_item(), Quad_CR::do_CR10_value(), Quad_FIO::do_sprintf(), Nabla::edit(), TabExpansion::expand_wsname(), Executable::extract_lambda_text(), Quad_CR::Picker::get(), Quad_CR::Picker::get_indexed(), InputMux::get_line(), Quad_CR::item_separator(), NativeFunction::load_emacs_library(), NativeFunction::open_so_file(), operator<<(), LineLabel::print(), LineLabel::print_prompt(), Quad_CR::short_ravel(), Token::show_trace(), Quad_TF::tf2_all_char_ravel(), Quad_TF::tf2_char_vec(), Quad_TF::tf2_fun_ucs(), NativeFunction::try_one_file(), and UCS_string().
atoi()
int UCS_string::atoi () const
return integer value for a string starting with optional whitespaces, followed by digits.
Definition at line 1175 of file UCS_string.cc.
References Avec::is_white(), and size().
Referenced by Command::cmd_BOXING(), Command::cmd_PSTAT(), and IO_Files::expect_apl_errors().
back() [1/2]
Unicode & UCS_string::back () inline
return the last character in this string
Definition at line 249 of file UCS_string.hh.
References size().
back() [2/2]
Unicode UCS_string::back () const inline
return the last character in this string
Definition at line 131 of file UCS_string.hh.
References size().
Referenced by LineHistory::add_line(), Quad_JSON::APL_to_JSON_string(), Command::cmd_USERCMD(), Quad_JSON::comma_count(), Quad_CR::do_eval_B(), Quad_FIO::do_scanf(), Token::error_info(), UserFunction::fix_lambda(), Value::get_member(), Command::parse_from_to(), Nabla::parse_oper(), Quad_XML::path_split(), remove_trailing_padchars(), remove_trailing_whitespaces(), round_last_digit(), Bif_F12_FORMAT::split_example_into_columns(), Executable::statement_text(), Quad_XML::tree(), UCS_string(), and unique().
begin()
UCS_string::iterator UCS_string::begin () const inline
an iterator set to the start of this string
Definition at line 373 of file UCS_string.hh.
Referenced by Nabla::parse_oper(), and Nabla::start().
compare()
Comp_result UCS_string::compare (const UCS_string & other) const inline
compare this with UCS_string other
Definition at line 312 of file UCS_string.hh.
Referenced by Quad_JSON::APL_to_JSON_string(), Command::cmd_DUMP(), Command::cmd_SAVE(), Symbol::compare(), compare_names(), Doxy::Doxy(), Workspace::dump_WS(), Symbol::equal(), SystemName::equal(), LineLabel::operator<(), Workspace::save_WS(), and StateIndicator::uses_function().
compare_names()
static bool UCS_string::compare_names (const UCS_string & n1, const UCS_string & n2, const void *) inline static
return true if n1 < n2
Definition at line 423 of file UCS_string.hh.
References compare().
Referenced by UCS_string_vector::sort().
compute_chunk_length()
int UCS_string::compute_chunk_length (int quad_PW, int col) const
compute the length of an output row
Definition at line 478 of file UCS_string.cc.
References size().
Referenced by PrintBuffer::print_interruptible(), and UCS_string().
contains()
bool UCS_string::contains (Unicode uni) const
return true if this string contains uni
Definition at line 1538 of file UCS_string.cc.
References size().
Referenced by Command::cmd_USERCMD(), Quad_NL::do_quad_NL(), Quad_FIO::do_scanf(), SymbolTable::erase_one_symbol(), Quad_EX::expunge(), and remove_trailing_padchars().
copy_black()
void UCS_string::copy_black (UCS_string & dest, int & idx) const
skip leading whitespaces starting at idx, append the following non-whitespaces (if any) to dest, and skip trailing whitespaces
Definition at line 601 of file UCS_string.cc.
References append(), and size().
Referenced by Command::do_APL_command(), and Command::split_arg().
create()
void UCS_string::create (const char * loc) inline
common part of all constructors
Definition at line 101 of file UCS_string.hh.
References total_count.
Referenced by UCS_string().
do_escape()
UCS_string UCS_string::do_escape (bool double_quoted) const
the inverse of un_escape().
Definition at line 1083 of file UCS_string.cc.
References append(), and size().
Referenced by Command::process_line(), UserFunction::transform_multi_line_strings(), and UserFunction::transform_multi_line_strings_3().
double_quote_count()
ShapeItem UCS_string::double_quote_count (bool in_quote2) const
return the number of unescaped and un-commented " in this string
Definition at line 778 of file UCS_string.cc.
References size().
Referenced by UserFunction::parse_body(), and UserFunction::transform_multi_line_strings().
double_quote_first()
ShapeItem UCS_string::double_quote_first () const
return the position of the first (leftmost) unescaped " in this string (if any), or else -1
Definition at line 815 of file UCS_string.cc.
References size().
double_quote_last()
ShapeItem UCS_string::double_quote_last () const
return the position of the last (rightmost) unescaped " in this string (if any), or else -1
Definition at line 851 of file UCS_string.cc.
References size().
drop()
UCS_string UCS_string::drop (int drop_count) const inline
return this string with the first drop_count characters removed
Definition at line 117 of file UCS_string.hh.
References size(), and UCS_string().
Referenced by InputFile::check_filter(), TabExpansion::expand_filename(), Quad_XML::path_split(), and Quad_INP::split_strings().
dump()
ostream & UCS_string::dump (ostream & out) const
dump this string to out (like U+nnn U+mmm ...)
Definition at line 1268 of file UCS_string.cc.
References size().
ends_with()
bool UCS_string::ends_with (const char * suffix) const
return true if this ends with suffix (ASCII, case matters).
Definition at line 663 of file UCS_string.cc.
References size().
Referenced by Command::process_line(), and UserFunction::transform_multi_line_strings_3().
erase()
void UCS_string::erase (ShapeItem pos) inline
erase 1 (!) character at pos
Definition at line 384 of file UCS_string.hh.
Referenced by Command::cmd_DUMP(), Command::cmd_SAVE(), LineEditContext::delete_char(), TabExpansion::expand_filename(), Bif_F12_FORMAT::format_float_by_spec(), and Workspace::wsid().
FNV_hash()
uint32_t UCS_string::FNV_hash () const inline
return the FNV (Fowler-Noll-Vo) hash of this_string
Definition at line 142 of file UCS_string.hh.
References size().
Referenced by SymbolTableBase< T, SYMBOL_COUNT >::compute_hash(), Value::get_member_data(), and Value::get_new_member().
from_big()
UCS_string UCS_string::from_big (APL_Float & value) static
convert the integer part of value to an UCS_string and remove it from value
Definition at line 1309 of file UCS_string.cc.
References append().
Referenced by from_double_to_fixed().
from_double_to_expo()
UCS_string UCS_string::from_double_to_expo (APL_Float value, int fract_digits) static
convert the double value to an UCS_string scaled (exponential) format (with fract_digits fractional digits).
Definition at line 1336 of file UCS_string.cc.
References append(), from_double_to_fixed(), from_int(), pop_back(), and size().
Referenced by Bif_F12_FORMAT::format_one_col_by_spec().
from_double_to_fixed()
UCS_string UCS_string::from_double_to_fixed (APL_Float value, int fract_digits) static
convert the double value to an UCS_string in fixed point format (with fract_digits fractional digits).
Definition at line 1464 of file UCS_string.cc.
References append(), from_big(), pop_back(), round_last_digit(), and size().
Referenced by Bif_F12_FORMAT::format_float_by_spec(), and from_double_to_expo().
from_int()
UCS_string UCS_string::from_int (int64_t value) static
convert a signed integer value to an UCS_string (like sprintf())
Definition at line 1280 of file UCS_string.cc.
References from_uint().
Referenced by from_double_to_expo().
from_uint()
UCS_string UCS_string::from_uint (uint64_t value) static
convert an unsigned integer value to an UCS_string (like sprintf())
Definition at line 1289 of file UCS_string.cc.
References append(), and UCS_string().
Referenced by FloatCell::character_representation(), and from_int().
get_total_count()
static ShapeItem UCS_string::get_total_count () inline static
return the total number of UCS_strings
Definition at line 419 of file UCS_string.hh.
References total_count.
Referenced by Quad_FIO::eval_B().
greater_uni()
static bool UCS_string::greater_uni (const Unicode & u1, const Unicode & u2, const void *) inline static
helper function for Heapsort<Unicode>::sort()
Definition at line 388 of file UCS_string.hh.
Referenced by sort(), and unique().
has_black()
bool UCS_string::has_black () const
return true if this string contains non-whitespace characters
Definition at line 639 of file UCS_string.cc.
References Avec::is_white(), and size().
Referenced by LineHistory::add_line(), and LineInput::edit_line().
insert()
void UCS_string::insert (ShapeItem pos, Unicode uni) inline
more intuitive insert() function
Definition at line 284 of file UCS_string.hh.
Referenced by LineEditContext::insert_char(), prepend(), round_last_digit(), and UCS_string().
is_comment_or_label()
bool UCS_string::is_comment_or_label () const
return true if this string starts with # or ⍝ or x:
Definition at line 763 of file UCS_string.cc.
References Avec::is_symbol_char(), and size().
Referenced by Quad_CR::do_CR10(), and Nabla::FunLine::print().
lexical_before()
bool UCS_string::lexical_before (const UCS_string other) const
case-sensitive comparison: return true iff this comes before other
Definition at line 1253 of file UCS_string.cc.
Referenced by Command::lib_common(), and SymbolTable::list().
LF_count()
ShapeItem UCS_string::LF_count () const
return the number of LF characters in this string
Definition at line 609 of file UCS_string.cc.
References size().
map_pad()
void UCS_string::map_pad ()
replace pad chars in this string by spaces
Definition at line 733 of file UCS_string.cc.
References size().
Referenced by Bif_F12_FORMAT::eval_B().
no_pad()
UCS_string UCS_string::no_pad () const
return a string like this, but with pad chars mapped to spaces
Definition at line 719 of file UCS_string.cc.
References append(), and size().
Referenced by Quad_QUOTE::assign(), Bif_F1_EXECUTE::execute_statement(), Quad_QUOTE::get_apl_value(), LineEditContext::LineEditContext(), and Token::show_trace().
operator+()
UCS_string UCS_string::operator+ (const UCS_string & other) const inline
return this string and other concatenated
Definition at line 292 of file UCS_string.hh.
operator<<() [1/4]
UCS_string & UCS_string::operator<< (const char * str) inline
append C-string str
Definition at line 296 of file UCS_string.hh.
References append_UTF8().
operator<<() [2/4]
UCS_string & UCS_string::operator<< (const UCS_string & other) inline
append UCS_string other
Definition at line 308 of file UCS_string.hh.
operator<<() [3/4]
UCS_string & UCS_string::operator<< (ShapeItem num) inline
append number num
Definition at line 300 of file UCS_string.hh.
References append_number().
operator<<() [4/4]
UCS_string & UCS_string::operator<< (Unicode uni) inline
append character uni
Definition at line 304 of file UCS_string.hh.
pop_back()
void UCS_string::pop_back () inline
remove the last character in this string
Definition at line 256 of file UCS_string.hh.
References size().
Referenced by LineHistory::add_line(), Quad_JSON::comma_count(), LineEditContext::delete_char(), Quad_CR::do_eval_B(), Executable::extract_lambda_text(), UserFunction::fix_lambda(), from_double_to_expo(), from_double_to_fixed(), InputMux::get_line(), Nabla::parse_oper(), Quad_XML::path_split(), Command::process_line(), remove_trailing_padchars(), remove_trailing_whitespaces(), round_last_digit(), Executable::statement_text(), Quad_XML::tree(), and UCS_string().
prepend()
void UCS_string::prepend (Unicode uni) inline
prepend character uni
Definition at line 288 of file UCS_string.hh.
References insert().
Referenced by Command::process_line(), and Workspace::wsid().
raw()
template<typename T > const T * UCS_string::raw () const inline
cast to an array of items with the same size as Unicode. This is for interfacing to libraries that have typedef'ed Unicodes differently.
Definition at line 110 of file UCS_string.hh.
remove_leading_and_trailing_whitespaces()
void UCS_string::remove_leading_and_trailing_whitespaces () inline
remove leading and trailing whitespaces
Definition at line 238 of file UCS_string.hh.
References remove_leading_whitespaces(), and remove_trailing_whitespaces().
Referenced by InputFile::check_filter(), Symbol::dump(), Nabla::edit_body_line(), Bif_F1_EXECUTE::execute_statement(), TabExpansion::expand_tab(), Doxy::functions_table(), UserFunction::help(), SymbolTable::list_symbol(), Quad_PLOT::parse_attributes(), Quad_Quad::resolve(), split_ws(), UserFunction::UserFunction(), and Workspace::wsid().
remove_leading_whitespaces()
void UCS_string::remove_leading_whitespaces ()
remove leading blanks, tabs, etc
Definition at line 568 of file UCS_string.cc.
References size().
Referenced by Command::cmd_DUMP(), Command::cmd_SAVE(), TabExpansion::expand_help_topics(), Bif_F12_FORMAT::format_one_col_by_spec(), Command::process_line(), remove_leading_and_trailing_whitespaces(), and Workspace::wsid().
remove_pad()
UCS_string UCS_string::remove_pad () const
return a string like this, but with pad chars removed
Definition at line 742 of file UCS_string.cc.
References append(), and size().
Referenced by Token::error_info().
remove_trailing_padchars()
void UCS_string::remove_trailing_padchars ()
remove trailing pad characters
Definition at line 510 of file UCS_string.cc.
References back(), contains(), pop_back(), and size().
Referenced by PrintBuffer::print_interruptible(), and UCS_string().
remove_trailing_whitespaces()
void UCS_string::remove_trailing_whitespaces ()
remove trailing blanks, tabs, etc
Definition at line 562 of file UCS_string.cc.
References back(), pop_back(), and size().
Referenced by Nabla::edit(), Executable::Executable(), and remove_leading_and_trailing_whitespaces().
reverse()
UCS_string UCS_string::reverse () const
return this string reversed (i.e. characters from back to front).
Definition at line 755 of file UCS_string.cc.
References append(), and size().
Referenced by Format_sub::insert_int_commas().
round_last_digit()
void UCS_string::round_last_digit ()
round last digit and discard it. Note that this is always expected to be in floating point format and never in exponential format
Definition at line 1494 of file UCS_string.cc.
References back(), insert(), pop_back(), and size().
Referenced by from_double_to_fixed().
size()
ShapeItem UCS_string::size () const inline
overload basic_string::size() so that it returns a signed length
Definition at line 339 of file UCS_string.hh.
Referenced by PrintBuffer::add_frame(), SystemSymTab::add_fun_or_var(), LineHistory::add_line(), Bif_F12_FORMAT::add_row(), Quad_XML::add_sorted_entities(), all_zeroes(), Quad_JSON::APL_to_JSON(), Quad_JSON::APL_to_JSON_string(), Quad_XML::APL_to_XML(), PrintBuffer::append_aligned(), append_quoted(), PrintBuffer::append_ucs(), Command::transfer_context::array_2TF(), Quad_PR::assign(), atoi(), back(), CharCell::character_representation(), ComplexCell::character_representation(), FloatCell::character_representation(), IntCell::character_representation(), XML_Loading_Archive::check_compatibility(), InputFile::check_filter(), Command::check_name_conflict(), Command::check_params(), Command::cmd_BOXING(), Command::cmd_COPY_ONCE(), Command::cmd_HELP(), Command::cmd_HISTORY(), Command::cmd_LIBS(), Command::cmd_PSTAT(), Command::cmd_USERCMD(), Command::cmd_XTERM(), CollatingCache::CollatingCache(), Quad_JSON::comma_count(), compute_chunk_length(), SymbolTableBase< T, SYMBOL_COUNT >::compute_hash(), contains(), copy_black(), LineEditContext::cursor_DOWN(), LineEditContext::cursor_END(), LineEditContext::cursor_RIGHT(), LineEditContext::cursor_SEARCH(), LineEditContext::cursor_UP(), LineEditContext::cut_to_EOL(), LineEditContext::delete_char(), XML_node::denormalize_attribute_value(), Command::do_APL_command(), Quad_CR::do_CR10(), Quad_CR::do_CR10_value(), Quad_CR::do_CR35(), do_escape(), Quad_CR::do_eval_B(), Quad_FX::do_native_FX(), PrintBuffer::do_PrintBuffer(), Quad_FIO::do_printf(), Quad_NL::do_quad_NL(), Quad_FIO::do_scanf(), Quad_FIO::do_sprintf(), Tokenizer::do_tokenize(), Quad_QUOTE::done(), double_quote_count(), double_quote_first(), double_quote_last(), Doxy::Doxy(), drop(), Symbol::dump(), dump(), Nabla::edit(), LineInput::edit_line(), ends_with(), Value::equal_string(), Error::Error(), Token::error_info(), Bif_F1_EXECUTE::eval_B(), Quad_GTK::eval_B(), Executable::Executable(), Nabla::execute_edit(), Bif_F1_EXECUTE::execute_statement(), TabExpansion::expand_APL_command(), TabExpansion::expand_distinguished_name(), TabExpansion::expand_filename(), TabExpansion::expand_help_topics(), TabExpansion::expand_tab(), TabExpansion::expand_user_name(), TabExpansion::expand_wsname(), Quad_EX::expunge(), Executable::extract_lambda_text(), Bif_F12_FORMAT::Format_LIFER::fill_data_fields(), Quad_RE::Flags::Flags(), FNV_hash(), Bif_F12_FORMAT::format_by_example(), Bif_F12_FORMAT::Format_LIFER::format_example(), Bif_F12_FORMAT::format_float_by_spec(), Bif_F12_FORMAT::Format_LIFER::format_left_side(), Bif_F12_FORMAT::Format_LIFER::Format_LIFER(), Bif_F12_FORMAT::format_one_col_by_spec(), Bif_F12_FORMAT::Format_LIFER::format_right_side(), from_double_to_expo(), from_double_to_fixed(), Command::transfer_context::function_2TF(), Doxy::functions_table(), UCS_string::iterator::get(), Quad_QUOTE::get_apl_value(), Quad_INP::get_esc(), IO_Files::get_file_line(), InputMux::get_line(), UserFunction::get_name_and_line(), Quad_NC::get_NC(), File_or_String::get_next(), Workspace::get_quad(), XML_node::get_taglen(), LineEditContext::get_total_length(), has_black(), UserFunction::help(), init_apl(), LineEditContext::insert_char(), Format_sub::insert_fract_commas(), Format_sub::insert_int_commas(), is_comment_or_label(), LineLabel::is_header_line_number(), Quad_TF::is_inverse(), Command::is_lib_ref(), Quad_JSON::JSON_to_APL(), LF_count(), Command::lib_common(), LineEditContext::LineEditContext(), Symbol::list(), SymbolTable::list(), StateIndicator::list(), SymbolTable::list_symbol(), Stop_Trace::locate_fun(), Workspace::lookup_existing_name(), Workspace::lookup_existing_symbol(), SymbolTable::lookup_symbol(), FloatCell::map_FC(), Format_sub::map_field(), map_pad(), UCS_string::iterator::more(), LineLabel::next(), UCS_string::iterator::next(), no_pad(), Quad_TF::no_UCS(), XML_node::normalize_attribute_value(), LineEditContext::on_bad_col(), Command::open_LIB_dir(), PrintBuffer::pad_fraction(), Quad_PLOT::parse_attributes(), UserFunction::parse_body(), Command::parse_from_to(), Nabla::parse_oper(), LineEditContext::paste(), Quad_XML::path_split(), pop_back(), FunctionStatistics::print(), CellFunctionStatistics::print(), LineLabel::print(), PrintBuffer::print_interruptible(), Value::print_member(), LineLabel::print_prompt(), UCS_string_vector::print_table(), PrintBuffer::PrintBuffer(), Command::process_line(), XML_Loading_Archive::read_Cells(), Quad_GTK::read_fd(), Quad_INP::read_strings(), XML_Loading_Archive::read_Symbol(), LineEditContext::refresh_from_cursor(), Regexp::Regexp(), remove_leading_whitespaces(), remove_pad(), remove_trailing_padchars(), remove_trailing_whitespaces(), reverse(), round_last_digit(), XML_Saving_Archive::save_UCS(), Plot_window_properties::set_attribute(), LineEditContext::set_cursor(), UserFunction::set_locked_error_info(), Quad_CR::short_ravel(), TabExpansion::show_alternatives(), Token::show_trace(), Doxy::SI_table(), Format_sub::size(), Quad_XML::skip_pos_prefix(), Quad_JSON::skip_string(), sort(), Command::split_arg(), Bif_F12_FORMAT::split_example_into_columns(), Quad_INP::split_strings(), split_ws(), Nabla::start(), starts_iwith(), starts_with(), Executable::statement_text(), substr_pos(), LineEditContext::tab_expansion(), Quad_TF::tf1(), Quad_TF::tf1_inv(), Quad_TF::tf2_char_vec(), Quad_TF::tf2_var(), Error::throw_define_error(), Nabla::throw_edit_error(), Error::throw_symbol_error(), to_HTML(), to_vector(), Tokenizer::tokenize_string1(), Tokenizer::tokenize_symbol(), UserFunction::transform_multi_line_strings_3(), Quad_XML::tree(), NativeFunction::try_one_file(), UCS_string(), un_escape(), Unicode_source::Unicode_source(), unique(), Error::update_error_info(), UserFunction_header::UserFunction_header(), UTF8_string::UTF8_string(), Value::Value(), Symbol::write_OUT(), and Workspace::wsid().
sort()
UCS_string UCS_string::sort () const
sort the characters in this string by their Unicode
Definition at line 1545 of file UCS_string.cc.
References greater_uni(), size(), and sort().
Referenced by Command::cmd_CHECK(), Bif_F2_INTER::eval_AB(), Quad_MAP::eval_AB(), Bif_F12_UNION::eval_B(), Doxy::gen(), Bif_F12_WITHOUT::large_eval_AB(), XML_Saving_Archive::save(), UCS_string_vector::sort(), sort(), Bif_F12_SORT::sort_collating(), Cell::sorted_indices(), and unique().
split_ws()
void UCS_string::split_ws (UCS_string & rest)
this is a command with optional args. Remove leading and trailing whitespaces, append args to rest, and remove args from this.
Definition at line 583 of file UCS_string.cc.
References append(), Avec::is_white(), remove_leading_and_trailing_whitespaces(), and size().
Referenced by TabExpansion::expand_APL_command().
starts_iwith() [1/2]
bool UCS_string::starts_iwith (const char * prefix) const
return true if this starts with prefix (ASCII, case insensitive).
Definition at line 684 of file UCS_string.cc.
References size().
Referenced by Command::cmd_BOXING(), Command::cmd_HISTORY(), Command::cmd_PSTAT(), Command::cmd_XTERM(), Command::do_APL_command(), Bif_F1_EXECUTE::execute_command(), XML_Loading_Archive::read_Variable(), and Output::toggle_color().
starts_iwith() [2/2]
bool UCS_string::starts_iwith (const UCS_string & prefix) const
return true if this starts with prefix (case insensitive).
Definition at line 702 of file UCS_string.cc.
References size().
starts_with() [1/2]
bool UCS_string::starts_with (const char * prefix) const
return true if this starts with prefix (ASCII, case matters).
Definition at line 646 of file UCS_string.cc.
References size().
Referenced by TabExpansion::expand_help_topics(), and TabExpansion::expand_user_name().
starts_with() [2/2]
bool UCS_string::starts_with (const UCS_string & prefix) const
return true if this starts with prefix (case sensitive).
Definition at line 674 of file UCS_string.cc.
References size().
substr_pos()
ShapeItem UCS_string::substr_pos (const UCS_string & sub) const
return the start position of sub in this string or -1 if sub is not contained in this string
Definition at line 617 of file UCS_string.cc.
References size().
Referenced by Quad_INP::eval_XB(), Quad_INP::read_strings(), and Quad_INP::split_strings().
to_HTML()
UCS_string UCS_string::to_HTML (int offset, bool preserve_ws) const
return this string HTML-escaped, starting at offset, and using for blanks
Definition at line 1572 of file UCS_string.cc.
References append(), append_ASCII(), and size().
Referenced by Doxy::function_page(), Doxy::functions_table(), and Doxy::SI_table().
to_vector()
size_t UCS_string::to_vector (UCS_string_vector & result) const
split this multi-line string into individual lines, removing the CR and NL chars in this string.
Definition at line 1141 of file UCS_string.cc.
References size(), and UCS_string().
Referenced by Quad_CR::do_eval_B(), Symbol::dump(), Nabla::open_existing_function(), Quad_TF::tf1(), and Quad_TF::tf2_fun_ucs().
un_escape()
UCS_string UCS_string::un_escape (bool double_quoted, bool keep_LF) const
return this string with "escape sequences" replaced by their real characters ('' → ' if single quoted and \r, \n, \xNNN etc. otherwise.
Definition at line 979 of file UCS_string.cc.
References append(), and size().
unique()
UCS_string UCS_string::unique () const
return the characters in this string (sorted and duplicates removed)
Definition at line 1553 of file UCS_string.cc.
References append(), back(), greater_uni(), size(), sort(), and UCS_string().
Referenced by CollatingCache::CollatingCache().
Member Data Documentation
total_count
ShapeItem UCS_string::total_count = 0 static protected
the total number of UCS_strings
Definition at line 429 of file UCS_string.hh.
Referenced by create(), get_total_count(), and ~UCS_string().
total_id
ShapeItem UCS_string::total_id = 0 static protected
the next unique instance_id
Definition at line 432 of file UCS_string.hh.
The documentation for this class was generated from the following files:
src/UCS_string.hh
src/UCS_string.cc