GNU APL: Statistics_record Class Reference
Statistics_record Class Reference
one statistics for computing the mean and the variance of samples
#include <Performance.hh>
Public Member Functions
Statistics_record ()
constructor
Statistics_record (uint64_t cnt, uint64_t da, double da2)
constructor
void reset ()
reset record to count 0, mean 0, variance 0
void add_sample (uint64_t val)
add one sample
void print (ostream &out)
print count, data, and data2
void save_record (ostream &outf)
write count, data, and data2 to file
uint64_t get_count () const
return the number of samples
uint64_t get_sum () const
return the sum of samples
uint64_t get_average () const
return the average
double get_sum2 () const
return the sum of squares
Static Public Member Functions
static uint64_t average (uint64_t sum, uint64_t count)
the average of count items with sum sum
static void print5 (ostream &out, uint64_t num)
print num as 5 characters (digits, dot, and multiplier (k, m, g, ...)
Protected Attributes
uint64_t count
number of samples
uint64_t data
sum of sample values
double data2
sum of squares of sample values
Detailed Description
one statistics for computing the mean and the variance of samples
Definition at line 90 of file Performance.hh.
Constructor & Destructor Documentation
Statistics_record() [1/2]
Statistics_record::Statistics_record () inline
constructor
Definition at line 94 of file Performance.hh.
References reset().
Statistics_record() [2/2]
Statistics_record::Statistics_record (uint64_t cnt, uint64_t da, double da2) inline
constructor
Definition at line 97 of file Performance.hh.
Member Function Documentation
add_sample()
void Statistics_record::add_sample (uint64_t val) inline
add one sample
Definition at line 112 of file Performance.hh.
References count, data, and data2.
Referenced by FunctionStatistics::add_sample(), and CellFunctionStatistics::add_sample().
average()
static uint64_t Statistics_record::average (uint64_t sum, uint64_t count) inline static
the average of count items with sum sum
Definition at line 142 of file Performance.hh.
References count.
Referenced by get_average(), and Performance::print().
get_average()
uint64_t Statistics_record::get_average () const inline
return the average
Definition at line 134 of file Performance.hh.
References average(), count, and data.
Referenced by FunctionStatistics::print().
get_count()
uint64_t Statistics_record::get_count () const inline
return the number of samples
Definition at line 126 of file Performance.hh.
References count.
Referenced by Quad_FIO::eval_XB(), CellFunctionStatistics::get_count(), CellFunctionStatistics::get_count1(), CellFunctionStatistics::get_countN(), and FunctionStatistics::print().
get_sum()
uint64_t Statistics_record::get_sum () const inline
return the sum of samples
Definition at line 130 of file Performance.hh.
References data.
Referenced by Quad_FIO::eval_XB(), CellFunctionStatistics::get_sum(), and FunctionStatistics::print().
get_sum2()
double Statistics_record::get_sum2 () const inline
return the sum of squares
Definition at line 138 of file Performance.hh.
References data2.
Referenced by Quad_FIO::eval_XB(), and CellFunctionStatistics::get_sum2().
print()
void Statistics_record::print (ostream & out)
print count, data, and data2
Definition at line 258 of file Performance.cc.
References count, data, data2, and print5().
Referenced by CellFunctionStatistics::print().
print5()
void Statistics_record::print5 (ostream & out, uint64_t num) static
print num as 5 characters (digits, dot, and multiplier (k, m, g, ...)
Definition at line 293 of file Performance.cc.
Referenced by print(), FunctionStatistics::print(), and Performance::print().
reset()
void Statistics_record::reset () inline
reset record to count 0, mean 0, variance 0
Definition at line 104 of file Performance.hh.
References count, data, and data2.
Referenced by FunctionStatistics::reset(), CellFunctionStatistics::reset(), and Statistics_record().
save_record()
void Statistics_record::save_record (ostream & outf)
write count, data, and data2 to file
Definition at line 277 of file Performance.cc.
References count, data, and data2.
Referenced by FunctionStatistics::save_data(), and CellFunctionStatistics::save_data().
Member Data Documentation
count
uint64_t Statistics_record::count protected
number of samples
Definition at line 150 of file Performance.hh.
Referenced by add_sample(), average(), get_average(), get_count(), print(), reset(), and save_record().
data
uint64_t Statistics_record::data protected
sum of sample values
Definition at line 153 of file Performance.hh.
Referenced by add_sample(), get_average(), get_sum(), print(), reset(), and save_record().
data2
double Statistics_record::data2 protected
sum of squares of sample values
Definition at line 156 of file Performance.hh.
Referenced by add_sample(), get_sum2(), print(), reset(), and save_record().
The documentation for this class was generated from the following files:
src/Performance.hh
src/Performance.cc