GNU APL: XML_Loading_Archive Class Reference
XML_Loading_Archive Class Reference
a helper class for loading an APL workspace
#include <Archive.hh>
Classes
struct _derived_todo
properties of a derived function
struct _vid_pvid
a value ID and the ID of its parent
struct fun_map
one mapping from an fid in the old (SAVEed) workspace to the function address in the new (LOADing) workspace
Public Member Functions
XML_Loading_Archive (ostream &_out, const char *_filename, int &dump_fd)
constructor: remember file name and workspace
~XML_Loading_Archive ()
destructor (unmap()s file).
bool is_open () const
return true iff constructor could open the file
void read_Workspace (bool silent)
read an entire workspace, throw DOMAIN_ERROR on failure
void check_compatibility ()
check compatibility information in the workspace and maybe warn the user
void set_protection (bool prot, const UCS_string_vector &allowed)
set copying and maybe set protection
void reset ()
reset archive to the start position
bool skip_to_tag (const char *tag)
skip to tag tag, return EOF if end of file
void read_vids ()
read vids of top-level variables
bool next_tag (const char *loc)
move to next tag, return true if EOF
Protected Types
enum Vid { NO_VID = int(-1) }
a value ID in a)SAVEd workspace
enum Fid { NO_FID = int(-1) }
the address of a function in a)SAVEd workspace
Protected Types inherited from XML_Archive
enum ArchiveSyntax {
ASX_MAJOR = 1 ,
ASX_MINOR = 2 ,
ASX_OTHER = 2
}
Protected Member Functions
void read_Value ()
read next Value element
const UTF8 * read_Cells (Value &Z, const UTF8 *input)
read one or more Cell(s) from input into the ravel of Z; return the UTF8 * after the cells.
const UTF8 * read_XML_string (UCS_string &ucs, const UTF8 *input)
input is a UTF8-encoded sequence of bytes, terminated with ". UTF8-decode the sequence, thereby removing the escape tagging with ⁰ (aka. UNI_PAD_U0), ¹ (UNI_PAD_U1), ²(UNI_PAD_U2), and \n. return the UTF8 * pointing to the terminating ".
void read_Ravel ()
read next Ravel element
void read_unused_name (int d, Symbol &symbol)
read next unused-name element
void read_Variable (int d, Symbol &symbol)
read next Variable element
void read_Function ()
read next Function element
void read_Function (int d, Symbol &symbol)
read next Function element
void read_Derived (StateIndicator &si, int lev)
read next derived function
void read_Label (int d, Symbol &symbol)
read next Label element
void read_Shared_Variable (int d, Symbol &symbol)
read next Shared-Variable element
void read_SymbolTable ()
read next Symbol element
void read_Symbol ()
read next Symbol element
void read_Commands ()
read all user-defined commands
void read_Command ()
read next Command element
void read_StateIndicator ()
read next StateIndicator element
void read_SI_entry (int level)
read next StateIndicator entry
void read_Parser (StateIndicator &si, int lev)
read parsers in SI entry
const Executable * read_Execute ()
read ⍎ Executable
const Executable * read_Statement ()
read ◊ Executable
const Executable * read_UserFunction ()
read a user defined Executable
Executable * read_lambda (const UTF8 *lambda_name)
read a lambda
UCS_string read_UCS ()
read an UCS string
bool read_Token (Token_loc &tloc)
read a token
Function_P read_Function_name ()
read a system function with attribute id_prefix-id or a user defined functions with attributes 'ufun_prefix-ufun' and 'level_prefix-prefix'
Function_P find_lambda (const UCS_string &lambda)
find a lambda in the current SI entry
bool more () const
return true iff there is more data in the file
void where (ostream &out)
show some characters starting at the current position
void where_att (ostream &out)
show attributes of current tag
bool get_uni ()
set current_char to next (UTF-8 encoded) char, return true if EOF
bool is_tag (const char *prefix) const
return true iff tagname starts with prefix
void expect_tag (const char *prefix, const char *loc) const
check that is_tag(prefix) is true and print error info if not
void print_tag (ostream &out) const
print current tag
const UTF8 * find_attr (const char *att_name, bool optional)
find attribute att_name and return: a pointer to its value if found, 0 if optional is true, and throw DOMAIN ERROR if optional is false.
const UTF8 * find_mandatory_attr (const char *att_name)
find mandatory attribute att_name. Return a pointer to its value if found and throw DOMAIN ERROR if not.
const UTF8 * find_optional_attr (const char *att_name)
find optional attribute att_name. Return a pointer to its value if found and 0 if not.
int64_t find_int_attr (const char *att_name, bool optional, int base)
return integer value of attribute att_name
Fid find_Fid_attr (const char *att_name, bool optional, int base)
return Fid value of attribute att_name
Vid find_Vid_attr (const char *att_name, bool optional, int base)
return Fid value of attribute att_name
APL_Float find_float_attr (const char *att_name)
return floating point value of attribute att_name
fun_map * find_fun_map (Fid fid)
return fun_map for fid, or 0 if not found.
Function_P find_function (Fid fid)
return function for fid, or 0 if not found.
void add_fid_function (Fid fid, Function_P new_fun, const char *loc)
add fid and function to find_fun_map. Either fid must be new, or else an existing fid must have its new_fun == 0 (forward declaration).
void instantiate_derived_functions (bool allocate)
instantiate the derived functions in derived_todos
Protected Attributes
ostream & out
where to send the "SAVED..." message
int fd
the file descriptor for the mmap()ed workspace.xml file
void * map_start
the start of the file (for mmap())
size_t map_length
the length of the file (for mmap())
const char * file_start
the start of the file
const UTF8 * line_start
the start of the current line
int line_no
the current line
Unicode current_char
the current char
const UTF8 * data
the next char
const UTF8 * tag_name
the name of the current tag, e.g. "Symbol" or "/Symbol"
const UTF8 * attributes
the attributes of the current tag
const UTF8 * end_attr
the end of attributes
const UTF8 * file_end
the end of the file
std::vector< Value_P > values
all values in the workspace
bool copying
true for)COPY and)PCOPY, false for)LOAD
bool protection
true for)PCOPY, false for)COPY and)LOAD
bool reading_vids
true if reading vids (preparation for)COPY or)PCOPY)
std::vector< Vid > vids_COPY
the vids to be copied (empty if all)
UCS_string_vector allowed_objects
the names of objects (empty if all)
bool have_allowed_objects
true for selective copy (COPY with symbol names)
std::vector< Vid > parents
parents[vid] is the parent of vid, or NO_VID if vid is a top-level value
const char * filename
the file name from which this archive was read
bool file_is_complete
true if file contains a <\/Workspace> tag at the end
std::vector< fun_map > fid_to_function
all mappings from fids to functions
vector< _derived_todo > derived_todos
derived functions that need to be instantiated
Detailed Description
a helper class for loading an APL workspace
Definition at line 236 of file Archive.hh.
Member Enumeration Documentation
Fid
enum XML_Loading_Archive::Fid protected
the address of a function in a)SAVEd workspace
Definition at line 280 of file Archive.hh.
Vid
enum XML_Loading_Archive::Vid protected
a value ID in a)SAVEd workspace
Definition at line 277 of file Archive.hh.
Constructor & Destructor Documentation
XML_Loading_Archive()
XML_Loading_Archive::XML_Loading_Archive (ostream & _out, const char * _filename, int & dump_fd)
constructor: remember file name and workspace
Definition at line 1180 of file Archive.cc.
References fd, file_end, file_start, filename, map_length, map_start, and reset().
~XML_Loading_Archive()
XML_Loading_Archive::~XML_Loading_Archive ()
destructor (unmap()s file).
Definition at line 1252 of file Archive.cc.
References fd, map_length, and map_start.
Member Function Documentation
add_fid_function()
void XML_Loading_Archive::add_fid_function (Fid fid, Function_P new_fun, const char * loc) protected
add fid and function to find_fun_map. Either fid must be new, or else an existing fid must have its new_fun == 0 (forward declaration).
Definition at line 2901 of file Archive.cc.
References fid_to_function, and find_fun_map().
Referenced by read_Derived(), and read_Function().
check_compatibility()
void XML_Loading_Archive::check_compatibility ()
check compatibility information in the workspace and maybe warn the user
Definition at line 1645 of file Archive.cc.
References UCS_string::append(), XML_Archive::ASX_MAJOR, XML_Archive::ASX_MINOR, XML_Archive::ASX_OTHER, copying, find_optional_attr(), and UCS_string::size().
expect_tag()
void XML_Loading_Archive::expect_tag (const char * prefix, const char * loc) const protected
check that is_tag(prefix) is true and print error info if not
Definition at line 1332 of file Archive.cc.
References is_tag(), line_no, and print_tag().
Referenced by read_Command(), read_Commands(), read_Execute(), read_Function(), read_lambda(), read_Parser(), read_StateIndicator(), read_Statement(), read_Symbol(), read_SymbolTable(), read_Token(), and read_Value().
find_attr()
const UTF8 * XML_Loading_Archive::find_attr (const char * att_name, bool optional) protected
find attribute att_name and return: a pointer to its value if found, 0 if optional is true, and throw DOMAIN ERROR if optional is false.
Definition at line 1351 of file Archive.cc.
References attributes, end_attr, filename, line_no, and line_start.
Referenced by find_mandatory_attr(), and find_optional_attr().
find_Fid_attr()
Fid XML_Loading_Archive::find_Fid_attr (const char * att_name, bool optional, int base) inline protected
return Fid value of attribute att_name
Definition at line 404 of file Archive.hh.
References find_int_attr().
Referenced by read_Derived(), and read_Function().
find_fun_map()
XML_Loading_Archive::fun_map * XML_Loading_Archive::find_fun_map (Fid fid) protected
return fun_map for fid, or 0 if not found.
Definition at line 2883 of file Archive.cc.
References fid_to_function.
Referenced by add_fid_function(), and find_function().
find_function()
Function_P XML_Loading_Archive::find_function (Fid fid) protected
return function for fid, or 0 if not found.
Definition at line 2894 of file Archive.cc.
References find_fun_map().
Referenced by instantiate_derived_functions(), and read_Function().
find_lambda()
Function_P XML_Loading_Archive::find_lambda (const UCS_string & lambda) protected
find a lambda in the current SI entry
Definition at line 3000 of file Archive.cc.
References Executable::get_body(), StateIndicator::get_executable(), UserFunction::get_func_ufun(), ValueStackItem::get_function(), Token::get_function(), StateIndicator::get_level(), UserFunction::get_name(), ValueStackItem::get_NC(), Token::get_sym_ptr(), Token::get_ValueType(), Workspace::SI_top(), and Symbol::value_stack_size().
Referenced by read_Function_name().
find_mandatory_attr()
const UTF8 * XML_Loading_Archive::find_mandatory_attr (const char * att_name) inline protected
find mandatory attribute att_name. Return a pointer to its value if found and throw DOMAIN ERROR if not.
Definition at line 392 of file Archive.hh.
References find_attr().
Referenced by read_Command(), read_Execute(), read_Function(), read_Ravel(), read_Statement(), read_Symbol(), read_Token(), read_UCS(), read_UserFunction(), and read_Value().
find_optional_attr()
const UTF8 * XML_Loading_Archive::find_optional_attr (const char * att_name) inline protected
find optional attribute att_name. Return a pointer to its value if found and 0 if not.
Definition at line 397 of file Archive.hh.
References find_attr().
Referenced by check_compatibility(), read_Function(), read_Function_name(), read_Ravel(), and read_UserFunction().
find_Vid_attr()
Vid XML_Loading_Archive::find_Vid_attr (const char * att_name, bool optional, int base) inline protected
return Fid value of attribute att_name
Definition at line 408 of file Archive.hh.
References find_int_attr().
Referenced by read_Derived(), read_Function(), read_Symbol(), and read_Value().
get_uni()
bool XML_Loading_Archive::get_uni () protected
set current_char to next (UTF-8 encoded) char, return true if EOF
Definition at line 1314 of file Archive.cc.
References current_char, data, file_end, line_no, line_start, and UTF8_string::toUni().
instantiate_derived_functions()
void XML_Loading_Archive::instantiate_derived_functions (bool allocate) protected
instantiate the derived functions in derived_todos
Definition at line 2933 of file Archive.cc.
References XML_Loading_Archive::_derived_todo::AXIS_vid, XML_Loading_Archive::_derived_todo::cache, derived_todos, XML_Loading_Archive::_derived_todo::fid, find_function(), XML_Loading_Archive::_derived_todo::LO_fid, XML_Loading_Archive::_derived_todo::OPER_fid, XML_Loading_Archive::_derived_todo::RO_fid, XML_Loading_Archive::_derived_todo::symptr, and values.
Referenced by read_StateIndicator().
is_open()
bool XML_Loading_Archive::is_open () const inline
return true iff constructor could open the file
Definition at line 246 of file Archive.hh.
References fd.
Referenced by Workspace::copy_WS(), and Workspace::load_WS().
is_tag()
bool XML_Loading_Archive::is_tag (const char * prefix) const protected
return true iff tagname starts with prefix
Definition at line 1326 of file Archive.cc.
References tag_name.
Referenced by expect_tag(), read_Parser(), read_SI_entry(), read_Symbol(), and skip_to_tag().
more()
bool XML_Loading_Archive::more () const inline protected
return true iff there is more data in the file
Definition at line 366 of file Archive.hh.
References data, and file_end.
print_tag()
void XML_Loading_Archive::print_tag (ostream & out) const protected
print current tag
Definition at line 1345 of file Archive.cc.
References attributes, out, and tag_name.
Referenced by expect_tag().
read_Cells()
const UTF8 * XML_Loading_Archive::read_Cells (Value & Z, const UTF8 * input) protected
read one or more Cell(s) from input into the ravel of Z; return the UTF8 * after the cells.
Definition at line 1787 of file Archive.cc.
References Value::get_wravel(), Value::is_packed(), line_no, Value::next_ravel_Byte(), Value::next_ravel_Char(), Value::next_ravel_Complex(), Value::next_ravel_Float(), Value::next_ravel_Int(), Value::next_ravel_Lval(), Value::next_ravel_Value(), read_XML_string(), UCS_string::size(), UTF8_string::toUni(), and values.
Referenced by read_Ravel().
read_Command()
void XML_Loading_Archive::read_Command () protected
read next Command element
Definition at line 2476 of file Archive.cc.
References expect_tag(), find_int_attr(), find_mandatory_attr(), and Workspace::get_user_commands().
Referenced by read_Commands().
read_Commands()
void XML_Loading_Archive::read_Commands () protected
read all user-defined commands
Definition at line 2459 of file Archive.cc.
References expect_tag(), find_int_attr(), next_tag(), and read_Command().
read_Derived()
void XML_Loading_Archive::read_Derived (StateIndicator & si, int lev) protected
read next derived function
Definition at line 2241 of file Archive.cc.
References add_fid_function(), derived_todos, find_Fid_attr(), find_Vid_attr(), StateIndicator::fun_oper_cache, and DerivedFunctionCache::get().
Referenced by read_Parser().
read_Execute()
const Executable * XML_Loading_Archive::read_Execute () protected
read ⍎ Executable
Definition at line 2579 of file Archive.cc.
References expect_tag(), find_mandatory_attr(), ExecuteList::fix(), next_tag(), and read_XML_string().
Referenced by read_SI_entry().
read_Function() [1/2]
void XML_Loading_Archive::read_Function () protected
read next Function element
Definition at line 2103 of file Archive.cc.
References add_fid_function(), find_Fid_attr(), find_int_attr(), and ID::get_system_function().
Referenced by read_Symbol().
read_Function() [2/2]
void XML_Loading_Archive::read_Function (int d, Symbol & symbol) protected
read next Function element
Definition at line 2114 of file Archive.cc.
References add_fid_function(), UCS_string::append(), UCS_string::append_number(), derived_todos, expect_tag(), filename, find_Fid_attr(), find_function(), find_int_attr(), find_mandatory_attr(), find_optional_attr(), find_Vid_attr(), NativeFunction::fix(), UserFunction::fix(), UserFunction::fix_lambda(), ValueStackItem::get_function_P(), Macro::get_macro(), Symbol::get_name(), ID::get_system_function(), Executable::increment_refcount(), line_no, Workspace::more_error(), next_tag(), Symbol::pop(), Symbol::push(), Symbol::push_function(), read_XML_string(), Function::set_creation_time(), UserFunction::set_exec_properties(), and Symbol::top_of_stack().
read_Function_name()
Function_P XML_Loading_Archive::read_Function_name () protected
read a system function with attribute id_prefix-id or a user defined functions with attributes 'ufun_prefix-ufun' and 'level_prefix-prefix'
Definition at line 2841 of file Archive.cc.
References find_int_attr(), find_lambda(), find_optional_attr(), ValueStackItem::get_function(), ID::get_name_UCS(), ValueStackItem::get_NC(), ID::get_system_function(), Workspace::lookup_symbol(), and Symbol::value_stack_size().
Referenced by read_Token().
read_Label()
void XML_Loading_Archive::read_Label (int d, Symbol & symbol) protected
read next Label element
Definition at line 2095 of file Archive.cc.
References find_int_attr(), Symbol::pop(), and Symbol::push_label().
Referenced by read_Symbol().
read_lambda()
Executable * XML_Loading_Archive::read_lambda (const UTF8 * lambda_name) protected
read a lambda
Definition at line 2644 of file Archive.cc.
References expect_tag(), UserFunction::fix_lambda(), Executable::increment_refcount(), next_tag(), and read_UCS().
Referenced by read_UserFunction().
read_Parser()
void XML_Loading_Archive::read_Parser (StateIndicator & si, int lev) protected
read parsers in SI entry
Definition at line 2669 of file Archive.cc.
References StateIndicator::current_stack, expect_tag(), find_int_attr(), is_tag(), next_tag(), read_Derived(), and read_Token().
Referenced by read_SI_entry().
read_Ravel()
void XML_Loading_Archive::read_Ravel () protected
read next Ravel element
Definition at line 2005 of file Archive.cc.
References find_int_attr(), find_mandatory_attr(), find_optional_attr(), read_Cells(), reading_vids, and values.
read_Shared_Variable()
void XML_Loading_Archive::read_Shared_Variable (int d, Symbol & symbol) protected
read next Shared-Variable element
Definition at line 2265 of file Archive.cc.
References Symbol::get_name(), and Symbol::push().
Referenced by read_Symbol().
read_SI_entry()
void XML_Loading_Archive::read_SI_entry (int level) protected
read next StateIndicator entry
Definition at line 2546 of file Archive.cc.
References find_int_attr(), is_tag(), next_tag(), Workspace::push_SI(), read_Execute(), read_Parser(), read_Statement(), read_UserFunction(), StateIndicator::set_PC(), and Workspace::SI_top().
Referenced by read_StateIndicator().
read_StateIndicator()
void XML_Loading_Archive::read_StateIndicator () protected
read next StateIndicator element
Definition at line 2499 of file Archive.cc.
References copying, expect_tag(), find_int_attr(), instantiate_derived_functions(), next_tag(), read_SI_entry(), and skip_to_tag().
read_Statement()
const Executable * XML_Loading_Archive::read_Statement () protected
read ◊ Executable
Definition at line 2596 of file Archive.cc.
References expect_tag(), find_mandatory_attr(), StatementList::fix(), next_tag(), and read_XML_string().
Referenced by read_SI_entry().
read_Symbol()
void XML_Loading_Archive::read_Symbol () protected
read next Symbol element
Definition at line 2295 of file Archive.cc.
References allowed_objects, UCS_string_vector::contains(), copying, expect_tag(), filename, find_int_attr(), find_mandatory_attr(), find_Vid_attr(), ID::get_name_UCS(), have_allowed_objects, is_tag(), line_no, Workspace::lookup_existing_symbol(), Workspace::lookup_symbol(), next_tag(), protection, read_Function(), read_Label(), read_Shared_Variable(), read_unused_name(), read_Variable(), reading_vids, UCS_string::size(), skip_to_tag(), Symbol::value_stack_size(), and vids_COPY.
Referenced by read_SymbolTable().
read_SymbolTable()
void XML_Loading_Archive::read_SymbolTable () protected
read next Symbol element
Definition at line 2278 of file Archive.cc.
References expect_tag(), find_int_attr(), next_tag(), and read_Symbol().
read_Token()
bool XML_Loading_Archive::read_Token (Token_loc & tloc) protected
read a token
Definition at line 2725 of file Archive.cc.
References IndexExpr::add_index(), expect_tag(), find_float_attr(), find_int_attr(), find_mandatory_attr(), Avec::is_quad(), Workspace::lookup_existing_symbol(), Workspace::lookup_symbol(), Token_loc::pc, read_Function_name(), Token_loc::tok, and values.
Referenced by read_Parser().
read_UCS()
UCS_string XML_Loading_Archive::read_UCS () protected
read an UCS string
Definition at line 2659 of file Archive.cc.
References find_mandatory_attr(), read_XML_string(), and skip_to_tag().
Referenced by read_lambda().
read_unused_name()
void XML_Loading_Archive::read_unused_name (int d, Symbol & symbol) protected
read next unused-name element
Definition at line 2044 of file Archive.cc.
References Symbol::push().
Referenced by read_Symbol().
read_UserFunction()
const Executable * XML_Loading_Archive::read_UserFunction () protected
read a user defined Executable
Definition at line 2613 of file Archive.cc.
References find_int_attr(), find_mandatory_attr(), find_optional_attr(), UserFunction::get_func_ufun(), ValueStackItem::get_function(), Macro::get_macro(), ValueStackItem::get_NC(), Workspace::lookup_symbol(), and read_lambda().
Referenced by read_SI_entry().
read_Value()
void XML_Loading_Archive::read_Value () protected
read next Value element
Definition at line 1704 of file Archive.cc.
References Shape::add_shape_item(), copying, expect_tag(), find_int_attr(), find_mandatory_attr(), find_Vid_attr(), parents, reading_vids, values, and vids_COPY.
read_Variable()
void XML_Loading_Archive::read_Variable (int d, Symbol & symbol) protected
read next Variable element
Definition at line 2054 of file Archive.cc.
References Symbol::assign(), find_int_attr(), NamedObject::get_Id(), Symbol::get_name(), Symbol::is_readonly(), Symbol::push(), UCS_string::starts_iwith(), Symbol::value_stack_size(), and values.
Referenced by read_Symbol().
read_vids()
void XML_Loading_Archive::read_vids ()
read vids of top-level variables
Definition at line 1279 of file Archive.cc.
References read_Workspace(), reading_vids, and reset().
Referenced by Workspace::copy_WS().
read_XML_string()
const UTF8 * XML_Loading_Archive::read_XML_string (UCS_string & ucs, const UTF8 * input) protected
input is a UTF8-encoded sequence of bytes, terminated with ". UTF8-decode the sequence, thereby removing the escape tagging with ⁰ (aka. UNI_PAD_U0), ¹ (UNI_PAD_U1), ²(UNI_PAD_U2), and \n. return the UTF8 * pointing to the terminating ".
Definition at line 1927 of file Archive.cc.
References UCS_string::append(), and UTF8_string::toUni().
Referenced by read_Cells(), read_Execute(), read_Function(), read_Statement(), and read_UCS().
reset()
void XML_Loading_Archive::reset ()
reset archive to the start position
Definition at line 1259 of file Archive.cc.
References data, file_start, line_no, line_start, and next_tag().
Referenced by read_vids(), and XML_Loading_Archive().
set_protection()
void XML_Loading_Archive::set_protection (bool prot, const UCS_string_vector & allowed) inline
set copying and maybe set protection
Definition at line 256 of file Archive.hh.
References allowed_objects, copying, have_allowed_objects, and protection.
Referenced by Workspace::copy_WS().
skip_to_tag()
bool XML_Loading_Archive::skip_to_tag (const char * tag)
skip to tag tag, return EOF if end of file
Definition at line 1267 of file Archive.cc.
References is_tag(), and next_tag().
Referenced by read_StateIndicator(), read_Symbol(), and read_UCS().
where()
void XML_Loading_Archive::where (ostream & out) protected
show some characters starting at the current position
Definition at line 1290 of file Archive.cc.
References data, line_no, line_start, and out.
where_att()
void XML_Loading_Archive::where_att (ostream & out) protected
show attributes of current tag
Definition at line 1299 of file Archive.cc.
References attributes, end_attr, line_no, line_start, and out.
Member Data Documentation
allowed_objects
UCS_string_vector XML_Loading_Archive::allowed_objects protected
the names of objects (empty if all)
Definition at line 466 of file Archive.hh.
Referenced by read_Symbol(), and set_protection().
attributes
const UTF8* XML_Loading_Archive::attributes protected
the attributes of the current tag
Definition at line 442 of file Archive.hh.
Referenced by find_attr(), print_tag(), and where_att().
copying
bool XML_Loading_Archive::copying protected
true for)COPY and)PCOPY, false for)LOAD
Definition at line 454 of file Archive.hh.
Referenced by check_compatibility(), read_StateIndicator(), read_Symbol(), read_Value(), and set_protection().
current_char
Unicode XML_Loading_Archive::current_char protected
the current char
Definition at line 433 of file Archive.hh.
Referenced by get_uni().
data
const UTF8* XML_Loading_Archive::data protected
the next char
Definition at line 436 of file Archive.hh.
Referenced by get_uni(), more(), reset(), and where().
derived_todos
vector<_derived_todo> XML_Loading_Archive::derived_todos protected
derived functions that need to be instantiated
Definition at line 523 of file Archive.hh.
Referenced by instantiate_derived_functions(), read_Derived(), and read_Function().
end_attr
const UTF8* XML_Loading_Archive::end_attr protected
the end of attributes
Definition at line 445 of file Archive.hh.
Referenced by find_attr(), and where_att().
fd
int XML_Loading_Archive::fd protected
the file descriptor for the mmap()ed workspace.xml file
Definition at line 415 of file Archive.hh.
Referenced by is_open(), XML_Loading_Archive(), and ~XML_Loading_Archive().
fid_to_function
std::vector<fun_map> XML_Loading_Archive::fid_to_function protected
all mappings from fids to functions
Definition at line 497 of file Archive.hh.
Referenced by add_fid_function(), and find_fun_map().
file_end
const UTF8* XML_Loading_Archive::file_end protected
the end of the file
Definition at line 448 of file Archive.hh.
Referenced by get_uni(), more(), and XML_Loading_Archive().
file_is_complete
bool XML_Loading_Archive::file_is_complete protected
true if file contains a <\/Workspace> tag at the end
Definition at line 485 of file Archive.hh.
file_start
const char* XML_Loading_Archive::file_start protected
the start of the file
Definition at line 424 of file Archive.hh.
Referenced by reset(), and XML_Loading_Archive().
filename
const char* XML_Loading_Archive::filename protected
the file name from which this archive was read
Definition at line 482 of file Archive.hh.
Referenced by find_attr(), read_Function(), read_Symbol(), and XML_Loading_Archive().
have_allowed_objects
bool XML_Loading_Archive::have_allowed_objects protected
true for selective copy (COPY with symbol names)
Definition at line 469 of file Archive.hh.
Referenced by read_Symbol(), and set_protection().
line_no
int XML_Loading_Archive::line_no protected
the current line
Definition at line 430 of file Archive.hh.
Referenced by expect_tag(), find_attr(), get_uni(), read_Cells(), read_Function(), read_Symbol(), reset(), where(), and where_att().
line_start
const UTF8* XML_Loading_Archive::line_start protected
the start of the current line
Definition at line 427 of file Archive.hh.
Referenced by find_attr(), get_uni(), reset(), where(), and where_att().
map_length
size_t XML_Loading_Archive::map_length protected
the length of the file (for mmap())
Definition at line 421 of file Archive.hh.
Referenced by XML_Loading_Archive(), and ~XML_Loading_Archive().
map_start
void* XML_Loading_Archive::map_start protected
the start of the file (for mmap())
Definition at line 418 of file Archive.hh.
Referenced by XML_Loading_Archive(), and ~XML_Loading_Archive().
out
ostream& XML_Loading_Archive::out protected
where to send the "SAVED..." message
Definition at line 274 of file Archive.hh.
Referenced by print_tag(), where(), and where_att().
parents
std::vector<Vid> XML_Loading_Archive::parents protected
parents[vid] is the parent of vid, or NO_VID if vid is a top-level value
Definition at line 479 of file Archive.hh.
Referenced by read_Value().
protection
bool XML_Loading_Archive::protection protected
true for)PCOPY, false for)COPY and)LOAD
Definition at line 457 of file Archive.hh.
Referenced by read_Symbol(), and set_protection().
reading_vids
bool XML_Loading_Archive::reading_vids protected
true if reading vids (preparation for)COPY or)PCOPY)
Definition at line 460 of file Archive.hh.
Referenced by read_Ravel(), read_Symbol(), read_Value(), and read_vids().
tag_name
const UTF8* XML_Loading_Archive::tag_name protected
the name of the current tag, e.g. "Symbol" or "/Symbol"
Definition at line 439 of file Archive.hh.
Referenced by is_tag(), and print_tag().
values
std::vector<Value_P> XML_Loading_Archive::values protected
all values in the workspace
Definition at line 451 of file Archive.hh.
Referenced by instantiate_derived_functions(), read_Cells(), read_Ravel(), read_Token(), read_Value(), and read_Variable().
vids_COPY
std::vector<Vid> XML_Loading_Archive::vids_COPY protected
the vids to be copied (empty if all)
Definition at line 463 of file Archive.hh.
Referenced by read_Symbol(), and read_Value().
The documentation for this class was generated from the following files:
src/Archive.hh
src/Archive.cc