GNU APL: Probe Class Reference
Probe Class Reference
CPU cycle counter for performance measurements.
#include <Common.hh>
Classes
struct measurement
one time measurement, measuring cCPU cycles spent between ttw points in the source code
Public Types
enum {
PROBE_COUNT = 100 ,
PROBE_LEN = 20
}
some Proble related parameters
Public Member Functions
Probe ()
constructor
void init ()
initialize this probe
void start ()
start time measurement
void stop ()
stop time measurement
int64_t get_time (int m) const
get the m'th time (from P1 to P2) of this probe
int64_t get_start (int m) const
get the m'th start time of this probe
int64_t get_stop (int m) const
get the m'th stop time of this probe
Static Public Member Functions
static int init (int p)
init the p'th probe
static void init_all ()
initialize all probes
static int get_time (int p, int m)
get the m'th time of the p'th probe
static int get_start (int p, int m)
get the m'th start time of the p'th probe
static int get_stop (int p, int m)
get the m'th stop time of the p'th probe
static int get_length (int p)
get the number of times int the p'th probe
Static Public Attributes
static Probe & P0 = probes[0]
start of vector probes
static Probe & P_1 = probes[Probe::PROBE_COUNT - 1]
individual probe 1
static Probe & P_2 = probes[Probe::PROBE_COUNT - 2]
individual probe 2
static Probe & P_3 = probes[Probe::PROBE_COUNT - 3]
individual probe 3
static Probe & P_4 = probes[Probe::PROBE_COUNT - 4]
individual probe 4
static Probe & P_5 = probes[Probe::PROBE_COUNT - 5]
individual probe 5
Protected Attributes
measurement measurements [PROBE_LEN]
all measurements
int idx
index into probes
int64_t * start_p
start time
int64_t * stop_p
end time
Static Protected Attributes
static int64_t dummy = 0
a dummy used when idx exceeds probes
static Probe probes []
all probes
Detailed Description
CPU cycle counter for performance measurements.
Software probes. A probe is a measurement of CPU cycles executed between two points P1 and P2 in the source code.
Definition at line 191 of file Common.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
some Proble related parameters
Enumerator
PROBE_COUNT
the number of probes
PROBE_LEN
the number of measurements in each probe
Definition at line 195 of file Common.hh.
Constructor & Destructor Documentation
Probe()
Probe::Probe () inline
constructor
Definition at line 200 of file Common.hh.
References init().
Member Function Documentation
get_length()
static int Probe::get_length (int p) inline static
get the number of times int the p'th probe
Definition at line 296 of file Common.hh.
References idx, PROBE_COUNT, and probes.
get_start() [1/2]
int64_t Probe::get_start (int m) const inline
get the m'th start time of this probe
Definition at line 272 of file Common.hh.
References Probe::measurement::cycles_from, idx, and measurements.
Referenced by get_start().
get_start() [2/2]
static int Probe::get_start (int p, int m) inline static
get the m'th start time of the p'th probe
Definition at line 278 of file Common.hh.
References get_start(), PROBE_COUNT, and probes.
get_stop() [1/2]
int64_t Probe::get_stop (int m) const inline
get the m'th stop time of this probe
Definition at line 284 of file Common.hh.
References Probe::measurement::cycles_to, idx, and measurements.
Referenced by get_stop().
get_stop() [2/2]
static int Probe::get_stop (int p, int m) inline static
get the m'th stop time of the p'th probe
Definition at line 290 of file Common.hh.
References get_stop(), PROBE_COUNT, and probes.
get_time() [1/2]
int64_t Probe::get_time (int m) const inline
get the m'th time (from P1 to P2) of this probe
Definition at line 257 of file Common.hh.
References Probe::measurement::cycles_from, Probe::measurement::cycles_to, idx, and measurements.
Referenced by Quad_FIO::eval_AB(), and get_time().
get_time() [2/2]
static int Probe::get_time (int p, int m) inline static
get the m'th time of the p'th probe
Definition at line 266 of file Common.hh.
References get_time(), PROBE_COUNT, and probes.
init() [1/2]
void Probe::init () inline
initialize this probe
Definition at line 204 of file Common.hh.
References dummy, idx, start_p, and stop_p.
Referenced by Quad_FIO::eval_AB(), init(), init_all(), and Probe().
init() [2/2]
static int Probe::init (int p) inline static
init the p'th probe
Definition at line 212 of file Common.hh.
References init(), PROBE_COUNT, and probes.
init_all()
static void Probe::init_all () inline static
initialize all probes
Definition at line 219 of file Common.hh.
References init(), and PROBE_COUNT.
Referenced by Quad_FIO::eval_B().
start()
void Probe::start () inline
start time measurement
Definition at line 223 of file Common.hh.
References dummy, idx, measurements, PROBE_LEN, start_p, and stop_p.
stop()
void Probe::stop () inline
stop time measurement
Definition at line 248 of file Common.hh.
References idx, and stop_p.
Member Data Documentation
dummy
int64_t Probe::dummy = 0 static protected
a dummy used when idx exceeds probes
Definition at line 330 of file Common.hh.
Referenced by init(), and start().
idx
int Probe::idx protected
index into probes
Definition at line 321 of file Common.hh.
Referenced by get_length(), get_start(), get_stop(), get_time(), init(), start(), and stop().
measurements
measurement Probe::measurements[PROBE_LEN] protected
all measurements
Definition at line 318 of file Common.hh.
Referenced by get_start(), get_stop(), get_time(), and start().
P0
Probe & Probe::P0 = probes[0] static
start of vector probes
Definition at line 301 of file Common.hh.
P_1
Probe & Probe::P_1 = probes[Probe::PROBE_COUNT - 1] static
individual probe 1
Definition at line 302 of file Common.hh.
P_2
Probe & Probe::P_2 = probes[Probe::PROBE_COUNT - 2] static
individual probe 2
Definition at line 303 of file Common.hh.
P_3
Probe & Probe::P_3 = probes[Probe::PROBE_COUNT - 3] static
individual probe 3
Definition at line 304 of file Common.hh.
P_4
Probe & Probe::P_4 = probes[Probe::PROBE_COUNT - 4] static
individual probe 4
Definition at line 305 of file Common.hh.
P_5
Probe & Probe::P_5 = probes[Probe::PROBE_COUNT - 5] static
individual probe 5
Definition at line 306 of file Common.hh.
probes
Probe Probe::probes static protected
all probes
Definition at line 333 of file Common.hh.
Referenced by get_length(), get_start(), get_stop(), get_time(), and init().
start_p
int64_t* Probe::start_p protected
start time
Definition at line 324 of file Common.hh.
Referenced by init(), and start().
stop_p
int64_t* Probe::stop_p protected
end time
Definition at line 327 of file Common.hh.
Referenced by init(), start(), and stop().
The documentation for this class was generated from the following files:
src/Common.hh
src/Common.cc