GNU APL: IntCell Class Reference
IntCell Class Reference
A cell containing a single Integer value.
#include <IntCell.hh>
Public Member Functions
IntCell ()
Construct an integer cell with value 0.
IntCell (APL_Integer i)
Construct an integer cell with value i.
virtual void init_other (void *other, Value &cell_owner, const char *loc) const
overloaded Cell::init_other
virtual bool is_integer_cell () const
overloaded Cell::is_integer_cell()
virtual ErrorCode bif_near_int64_t (Cell *Z) const
overloaded Cell::bif_near_int64_t()
virtual ErrorCode bif_within_quad_CT (Cell *Z) const
overloaded Cell::bif_within_quad_CT()
virtual bool greater (const Cell &other) const
overloaded Cell::greater()
virtual bool equal (const Cell &other, double qct) const
overloaded Cell::equal()
virtual ErrorCode bif_add (Cell *Z, const Cell *A) const
overloaded Cell::bif_add()
virtual ErrorCode bif_ceiling (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual ErrorCode bif_conjugate (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual ErrorCode bif_direction (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual ErrorCode bif_divide (Cell *Z, const Cell *A) const
overloaded Cell::bif_divide()
virtual ErrorCode bif_exponential (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual ErrorCode bif_factorial (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual ErrorCode bif_floor (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual ErrorCode bif_magnitude (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual ErrorCode bif_multiply (Cell *Z, const Cell *A) const
overloaded Cell::bif_multiply()
virtual ErrorCode bif_power (Cell *Z, const Cell *A) const
overloaded Cell::bif_power()
virtual ErrorCode bif_nat_log (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual ErrorCode bif_negative (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual ErrorCode bif_pi_times (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual ErrorCode bif_pi_times_inverse (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual ErrorCode bif_reciprocal (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual ErrorCode bif_roll (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual ErrorCode bif_subtract (Cell *Z, const Cell *A) const
overloaded Cell::bif_subtract()
virtual Comp_result compare (const Cell &other) const
compare this with other, throw DOMAIN ERROR on illegal comparisons
virtual ErrorCode bif_maximum (Cell *Z, const Cell *A) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual ErrorCode bif_minimum (Cell *Z, const Cell *A) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual ErrorCode bif_residue (Cell *Z, const Cell *A) const
overloaded from the corresponding Cell:: function (see class Cell)
virtual PrintBuffer character_representation (const PrintContext &pctx) const
the Quad_CR representation of this cell
virtual bool need_scaling (const PrintContext &pctx) const
return true iff this cell needs scaling (exponential format) in pctx According to lrm p. 13, integer cells ignore ⎕PP an never use scaling
virtual ErrorCode bif_add_inverse (Cell *Z, const Cell *A) const
overloaded Cell::bif_add_inverse()
virtual ErrorCode bif_multiply_inverse (Cell *Z, const Cell *A) const
overloaded Cell::bif_multiply_inverse()
void Hswap (IntCell &other)
swap this Intcell and other (for Heapsort<IntCell>)
virtual APL_Integer get_int_value () const
overloaded Cell::get_int_value()
void set_int_value (APL_Integer val)
set the integer value of this IntCell
virtual const IntCell & cIntlCell () const
downcast to const IntCell
virtual IntCell & wIntCell ()
downcast to IntCell
virtual int get_byte_value () const
overloaded Cell::get_byte_value()
Public Member Functions inherited from Cell
Cell ()
Construct an un-initialized Cell.
void init (const Cell &other, Value &this_owner, const char *loc)
init this Cell from a (possibly deep) copy of other
virtual void init_other (void *other, Value &other_owner, const char *loc) const
init (uninitialized) Cell other from this initialized cell
void init_from_value (Value *value, Value &cell_owner, const char *loc)
init this Cell from value. If value is a scalar then its first element is used (and value is erased). Otherwise a PointerCell is created.
virtual bool greater (const Cell &other) const
Return true if this cell is greater than other, with:
virtual bool equal (const Cell &other, double qct) const
return true if this cell is equal to other
Value_P to_value (const char *loc) const
return pointer value of a PointerCell or create a scalar with a copy of this cell.
void init_type (const Cell &other, Value &cell_owner, const char *loc)
init this cell to be the type of other
virtual Unicode get_char_value () const
Return the character value of a cell.
virtual int get_byte_value () const
Return the byte value (-128..255 incl) of a cell.
virtual APL_Integer get_int_value () const
Return the integer value of a cell.
virtual APL_Float get_real_value () const
Return the real part of a cell.
virtual APL_Float get_imag_value () const
Return the imaginary part of a cell.
virtual APL_Complex get_complex_value () const
Return the complex value of a cell.
virtual Value_P get_pointer_value () const
Return the APL value of a cell (Asserts for non-pointer cells)
virtual Cell * get_lval_value () const
Return the APL value of a cell (Asserts for non-lval cells)
virtual PrintBuffer character_representation (const PrintContext &pctx) const
the Quad_CR representation of this cell
virtual bool need_scaling (const PrintContext &pctx) const
return true if this cell needs scaling (exponential format) in pctx
virtual bool get_near_bool () const
Return value if it is close to boolean, or else throw DOMAIN_ERROR.
virtual APL_Integer get_near_int () const
Return value if it is close to int, or else throw DOMAIN_ERROR.
virtual APL_Integer get_checked_near_int () const
Return value if it is (known to be) close to int, or else Assert()
virtual bool is_near_zero () const
return true iff value is numeric and close to 0
virtual bool is_near_one () const
return true iff value is numeric and close to 1
bool is_near_bool () const
return true iff value is numeric and close to 0 or 1
virtual bool is_near_int () const
True iff value is numeric and close to an int.
virtual bool is_near_int64_t () const
True iff value is numeric and close to an int.
virtual bool is_near_real () const
return true iff value is numeric and close to a real number
virtual int CDR_size () const
return the minimum number of data bytes to store this cell in CDR format. The actual number of data bytes can be bigger if other cells need more bytes,
virtual void release (const char *loc)
Release content pointed to (complex, APL value)
virtual bool is_integer_cell () const
Return true iff this cell is an integer cell.
bool is_simple_cell () const
Return true iff this cell is a numeric cor character cell.
virtual bool is_float_cell () const
Return true iff this cell is a floating point cell.
virtual bool is_character_cell () const
Return true iff this cell is a character cell.
virtual bool is_pointer_cell () const
Return true iff this cell is a pointer (to a sub-array) cell.
virtual bool is_lval_cell () const
Return true iff this cell is a pointer to a cell.
virtual bool is_picked_lval_cell () const
Return true iff this cell is a pointer to a cell from pick()
virtual bool is_complex_cell () const
Return true iff this cell is a complex number cell.
virtual bool is_numeric () const
Return true iff this cell is an integer, float, or complex cell.
virtual bool is_real_cell () const
Return true iff this cell is an integer or float cell.
virtual bool is_finite () const
Return true unless this cell contains infinity or NaN.
virtual bool is_example_field () const
Return true iff this cell is an example field character cell.
virtual bool is_member_anchor () const
Return true iff this is a PointerCell which pouints to a member value.
virtual CellType get_cell_type () const
return the type of this cell
virtual CellType get_cell_subtype () const
return the subtype of this cell. The subtype is the set of containers that can store the cell (only for Int and Char cells).
virtual const char * get_classname () const
return the name of the class
virtual ErrorCode bif_ceiling (Cell *Z) const
round the value of this Cell up and store the result in Z
virtual ErrorCode bif_conjugate (Cell *Z) const
conjugate the value of this Cell and store the result in Z
virtual ErrorCode bif_direction (Cell *Z) const
store the direction (sign) of this Cell in Z
virtual ErrorCode bif_exponential (Cell *Z) const
store e to the power of the value of this Cell in Z
virtual ErrorCode bif_factorial (Cell *Z) const
store the factorial (N!) of the value of this Cell in Z
virtual ErrorCode bif_floor (Cell *Z) const
Round the value of this Cell down and store the result in Z.
virtual ErrorCode bif_magnitude (Cell *Z) const
store the absolute value of this Cell in Z
virtual ErrorCode bif_nat_log (Cell *Z) const
store the base e logarithm of the value of this Cell in Z
virtual ErrorCode bif_negative (Cell *Z) const
store the negative of the value of this Cell in Z
virtual ErrorCode bif_not (Cell *Z) const
store the logical complement of the value of this Cell in Z
virtual ErrorCode bif_not_bitwise (Cell *Z) const
store the bitwise complement of the value of this Cell in Z
virtual ErrorCode bif_near_int64_t (Cell *Z) const
store the nearby integer of the value of this Cell in Z
virtual ErrorCode bif_within_quad_CT (Cell *Z) const
store the nearby integer of the value of this Cell in Z
virtual ErrorCode bif_pi_times (Cell *Z) const
store pi times the value of this Cell in Z
virtual ErrorCode bif_pi_times_inverse (Cell *Z) const
store pi times the value of this Cell in Z
virtual ErrorCode bif_reciprocal (Cell *Z) const
store the reciprocal of the value of this Cell in Z
virtual ErrorCode bif_roll (Cell *Z) const
store a random number between 1 and the value of this Cell in Z
virtual ErrorCode bif_add (Cell *Z, const Cell *A) const
store the sum of A and this cell in Z
virtual ErrorCode bif_and (Cell *Z, const Cell *A) const
store the logical and of A and this cell in Z
virtual ErrorCode bif_and_bitwise (Cell *Z, const Cell *A) const
store the bitwise and of A and this cell in Z
virtual ErrorCode bif_binomial (Cell *Z, const Cell *A) const
store the binomial (n over k) of A and this cell in Z
virtual ErrorCode bif_subtract (Cell *Z, const Cell *A) const
store the difference between A and this cell in Z
virtual ErrorCode bif_divide (Cell *Z, const Cell *A) const
store the quotient between A and this cell in Z
virtual Comp_result compare (const Cell &other) const
compare this with other, throw DOMAIN ERROR on illegal comparisons
ErrorCode bif_equal (Cell *Z, const Cell *A) const
store 1 in Z if A == the value of this cell in Z, else 0
virtual ErrorCode bif_equal_bitwise (Cell *Z, const Cell *A) const
bitwise comparison of *this and A
virtual ErrorCode bif_not_equal_bitwise (Cell *Z, const Cell *A) const
bitwise comparison of *this and A
ErrorCode bif_not_equal (Cell *Z, const Cell *A) const
store 1 in Z if A != the value of this cell in Z, else 0
ErrorCode bif_greater_than (Cell *Z, const Cell *A) const
store 1 in Z if A > the value of this cell in Z, else 0
ErrorCode bif_less_eq (Cell *Z, const Cell *A) const
store 1 in Z if A <= the value of this cell in Z, else 0
ErrorCode bif_less_than (Cell *Z, const Cell *A) const
store 1 in Z if A < the value of this cell in Z, else 0
ErrorCode bif_greater_eq (Cell *Z, const Cell *A) const
store 1 in Z if A is >= the value of this cell in Z, else 0
virtual ErrorCode bif_logarithm (Cell *Z, const Cell *A) const
store the base A logarithm of this cell in Z
virtual ErrorCode bif_maximum (Cell *Z, const Cell *A) const
store the larger of A and of this cell in Z
virtual ErrorCode bif_minimum (Cell *Z, const Cell *A) const
store the smaller of A and of this cell in Z
virtual ErrorCode bif_multiply (Cell *Z, const Cell *A) const
store the product of A and this cell in Z
virtual ErrorCode bif_nand (Cell *Z, const Cell *A) const
store the logical nand of A and this cell in Z
virtual ErrorCode bif_nand_bitwise (Cell *Z, const Cell *A) const
store the bitwise nand of A and this cell in Z
virtual ErrorCode bif_nor (Cell *Z, const Cell *A) const
store the logical NOR of A and this cell in Z
virtual ErrorCode bif_nor_bitwise (Cell *Z, const Cell *A) const
store the bitwise NOR of A and this cell in Z
virtual ErrorCode bif_or (Cell *Z, const Cell *A) const
store the logical OR of A and this cell in Z
virtual ErrorCode bif_or_bitwise (Cell *Z, const Cell *A) const
store the bitwise or of A and this cell in Z
virtual ErrorCode bif_power (Cell *Z, const Cell *A) const
store A to the power of this cell in Z
virtual ErrorCode bif_residue (Cell *Z, const Cell *A) const
store A modulo this cell in Z
virtual ErrorCode bif_circle_fun (Cell *Z, const Cell *A) const
store a circle function (according to A) of this cell in Z
virtual ErrorCode bif_circle_fun_inverse (Cell *Z, const Cell *A) const
store a circle function (according to A) of this cell in Z
virtual ErrorCode bif_add_inverse (Cell *Z, const Cell *A) const
the inverse of bif_add
virtual ErrorCode bif_multiply_inverse (Cell *Z, const Cell *A) const
the inverse of bif_bif_multiply
void * operator new (std::size_t, void *)
placement new
const void * get_u0 () const
raw pointer to the primary value (for 27 ⎕CR)
const void * get_u1 () const
raw pointer to the secondary value (for 28 ⎕CR)
Static Public Attributes
static const IntCell boolean_FALSE
false (for packed Cells)
static const IntCell boolean_TRUE
true (for packed Cells)
Protected Member Functions
virtual CellType get_cell_type () const
overloaded Cell::get_cell_type()
virtual CellType get_cell_subtype () const
overloaded Cell::get_cell_subtype()
virtual APL_Float get_real_value () const
overloaded Cell::get_real_value()
virtual APL_Float get_imag_value () const
overloaded Cell::get_imag_value()
virtual APL_Complex get_complex_value () const
overloaded Cell::get_complex_value()
virtual bool get_near_bool () const
overloaded Cell::get_near_bool()
virtual APL_Integer get_near_int () const
overloaded Cell::get_near_int()
virtual APL_Integer get_checked_near_int () const
overloaded Cell::get_checked_near_int()
virtual bool is_near_zero () const
overloaded Cell::is_near_zero()
virtual bool is_near_one () const
overloaded Cell::is_near_one()
virtual bool is_near_int () const
overloaded Cell::is_near_int()
virtual bool is_near_int64_t () const
overloaded Cell::is_near_int64_t()
virtual bool is_near_real () const
overloaded Cell::is_near_real()
virtual const char * get_classname () const
overloaded Cell::get_classname()
virtual int CDR_size () const
overloaded Cell::CDR_size()
Protected Member Functions inherited from RealCell
virtual bool is_real_cell () const
overloaded Cell::is_real_cell().
virtual ErrorCode bif_circle_fun (Cell *Z, const Cell *A) const
overloaded Cell::bif_circle_fun().
virtual ErrorCode bif_circle_fun_inverse (Cell *Z, const Cell *A) const
overloaded Cell::bif_circle_fun_inverse().
ErrorCode do_bif_circle_fun (Cell *Z, int fun) const
compute circle function fun
virtual ErrorCode bif_logarithm (Cell *Z, const Cell *A) const
overloaded Cell::bif_logarithm().
virtual const char * get_classname () const
overloaded Cell::get_classname().
Protected Member Functions inherited from NumericCell
virtual bool is_numeric () const
overloaded Cell::is_numeric()
virtual ErrorCode bif_not (Cell *Z) const
overloaded Cell::bif_not()
virtual ErrorCode bif_not_bitwise (Cell *Z) const
overloaded Cell::bif_not_bitwise()
virtual ErrorCode bif_and (Cell *Z, const Cell *A) const
overloaded Cell::bif_and()
virtual ErrorCode bif_and_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_and_bitwise()
virtual ErrorCode bif_equal_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_equal_bitwise()
virtual ErrorCode bif_not_equal_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_not_equal_bitwise()
virtual ErrorCode bif_binomial (Cell *Z, const Cell *A) const
overloaded Cell::bif_binomial()
virtual ErrorCode bif_nand (Cell *Z, const Cell *A) const
overloaded Cell::bif_nand()
virtual ErrorCode bif_nand_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_nand_bitwise()
virtual ErrorCode bif_nor (Cell *Z, const Cell *A) const
overloaded Cell::bif_nor()
virtual ErrorCode bif_nor_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_nor_bitwise()
virtual ErrorCode bif_or (Cell *Z, const Cell *A) const
overloaded Cell::bif_or()
virtual ErrorCode bif_or_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_or_bitwise()
virtual const char * get_classname () const
overloaded Cell::get_classname()
ErrorCode complex_binomial (Cell *Z, const Cell *A) const
N over K for complex A and/or B.
ErrorCode real_binomial (Cell *Z, const Cell *A) const
N over K for non-integer A and/or B.
Static Protected Member Functions
static ErrorCode zI (Cell *Z, APL_Integer aint)
initialize Z to APL_Integer v
static ErrorCode z0 (Cell *Z)
initialize the (un-initialized) Cell *Z to integer 0
static ErrorCode z1 (Cell *Z)
initialize the (un-initialized) Cell *Z to integer 1
static ErrorCode z_1 (Cell *Z)
initialize the (un-initialized) Cell *Z to integer ¯1
Static Protected Member Functions inherited from NumericCell
static ErrorCode K33_binomial (Cell *Z, APL_Integer N, APL_Integer K, bool negate)
compute binomial funtion for integers a and b
static ErrorCode int_gcd (APL_Integer &z, APL_Integer a, APL_Integer b)
return the greatest common divisor of integers a and b
static ErrorCode flt_gcd (APL_Float &z, APL_Float a, APL_Float b, double qct)
return the greatest common divisor of real a and b
static ErrorCode integer_binomial (Cell *Z, APL_Integer N, APL_Integer K, bool negate)
N over K for positive integers N and K.
static ErrorCode cpx_gcd (APL_Complex &z, APL_Complex a, APL_Complex b, double qct)
return the greatest common divisor of complex a and b
static APL_Complex cpx_max_real (APL_Complex a)
multiply a by 1, -1, i, or -i so that a.real is maximal
Friends
class Cell
class ComplexCell
class FloatCell
class NumericCell
class PointerCell
class RealCell
class Quad_EX
class Value
Additional Inherited Members
Static Public Member Functions inherited from NumericCell
static ErrorCode zV (Cell *Z, APL_Float flt)
initialize the (un-initialized) Cell *Z to (if possible) an IntCell or else to a FloatCell with value flt.
static ErrorCode zV (Cell *Z, APL_Complex cpx)
initialize the (un-initialized) Cell *Z to (if possible) an IntCell, a FloatCell, or a ComplexCell with value cpx.
static ErrorCode zV (Cell *Z, APL_Float real, APL_Float imag)
initialize the (un-initialized) Cell *Z to (if possible) an IntCell, a FloatCell, or a ComplexCell with value cpx.
Static Public Member Functions inherited from Cell
static bool A_greater_B (const Cell *const &A, const Cell *const &B, const void *unused_comp_arg)
like greater() but static
static bool same_half_plane (APL_Complex A, APL_Complex B)
ISO p.15: return true if A and B are on the same half-plane.
static bool tolerantly_equal (APL_Float A, APL_Float B, double qct)
ISO p.19: return true if real A is tolerantly equal to real B within C.
static bool tolerantly_equal (APL_Complex A, APL_Complex B, double qct)
ISO p. 19: return true if complex A and B are tolerantly equal within real qct.
static bool integral_within (APL_Float A, double qct)
ISO p. 19: A is integral (close to a Gaussian Integer) within qct.
static bool sum_overflow (APL_Integer z, APL_Integer a, APL_Integer b)
return true if z = a + b had an overflow.
static bool diff_overflow (APL_Integer z, APL_Integer a, APL_Integer b)
return true if z = a - b had an overflow.
static bool prod_overflow (int64_t a, int64_t b)
return true if multiplying a and b will (probably) overflow. For some huge a or b the result may incorrectly return true. a or b the result may incorrectly return true.
static void copy (Cell *&dst, const Cell *&src, ShapeItem count, Value &cell_owner)
copy (deep) count cells from src to dest)
static void copy (Value &val, const Cell *&src, ShapeItem count)
copy (deep) count cells from src to val (which is under construction))
static bool is_near_int (APL_Float value)
true iff value is close to an int (within +- qct)
static bool is_near_int64_t (APL_Float value)
true iff value is close to an int64_t (i.e. fots into an int64_t
static bool is_near_zero (APL_Float value)
true iff value is close to 0 (within +- qct)
static APL_Integer near_int (APL_Float value)
return value if it is close to int, or else throw DOMAIN_ERROR
static bool greater_cp (const ShapeItem &a, const ShapeItem &b, const void *cells)
compare cells[a] and cells[b] ascendingly
static bool smaller_cp (const ShapeItem &a, const ShapeItem &b, const void *cells)
compare cells[a] and cells[b] descendingly
static bool compare_stable (const Cell *const &A, const Cell *const &B, const void *comp_arg)
a stable compare function to be used with Heapsort. Equal cells are compared by their address. Return true iff A > B or A = B and &A > &B.
static bool compare_ptr (const Cell *const &A, const Cell *const &B, const void *comp_arg)
a stable compare function to be used with Heapsort. The cell contents are ignored and only the cell addresses are being compared. Return true iff &A > &B.
static ShapeItem * sorted_indices (const Cell *ravel, ShapeItem length, Sort_order order, ShapeItem comp_len)
return length indices i1, i2, ... iN so that ravel[i1] < ravel[i2] < ... < ravel[iN]. The indices are 0-based and the caller must delete[] the result. Returns 0 on error (= WS FULL).
static const char * get_cell_type_name (CellType ct)
the name of ct
Protected Attributes inherited from Cell
SomeValue value
the primary value of this cell
Detailed Description
A cell containing a single Integer value.
A cell containing a single APL integer. This class essentially overloads certain functions in class Cell with integer specific implementations.
Definition at line 34 of file IntCell.hh.
Constructor & Destructor Documentation
IntCell() [1/2]
IntCell::IntCell () inline
Construct an integer cell with value 0.
Definition at line 47 of file IntCell.hh.
References Cell::SomeValue::ival, and Cell::value.
Referenced by init_other(), z0(), z1(), z_1(), and zI().
IntCell() [2/2]
IntCell::IntCell (APL_Integer i) inline
Construct an integer cell with value i.
Definition at line 51 of file IntCell.hh.
References Cell::SomeValue::ival, and Cell::value.
Member Function Documentation
bif_add()
ErrorCode IntCell::bif_add (Cell * Z, const Cell * A) const virtual
overloaded Cell::bif_add()
Reimplemented from Cell.
Definition at line 470 of file IntCell.cc.
References get_int_value(), Cell::sum_overflow(), FloatCell::zF(), and zI().
bif_add_inverse()
ErrorCode IntCell::bif_add_inverse (Cell * Z, const Cell * A) const virtual
overloaded Cell::bif_add_inverse()
Reimplemented from Cell.
Definition at line 491 of file IntCell.cc.
bif_ceiling()
ErrorCode IntCell::bif_ceiling (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 429 of file IntCell.cc.
References Cell::SomeValue::ival, Cell::value, and zI().
bif_conjugate()
ErrorCode IntCell::bif_conjugate (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 355 of file IntCell.cc.
References Cell::SomeValue::ival, Cell::value, and zI().
bif_direction()
ErrorCode IntCell::bif_direction (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 369 of file IntCell.cc.
References Cell::SomeValue::ival, Cell::value, and zI().
bif_divide()
ErrorCode IntCell::bif_divide (Cell * Z, const Cell * A) const virtual
overloaded Cell::bif_divide()
Reimplemented from Cell.
Definition at line 520 of file IntCell.cc.
References bif_reciprocal(), FloatCell::gcd(), get_int_value(), z1(), FloatCell::zF(), and zI().
bif_exponential()
ErrorCode IntCell::bif_exponential (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 441 of file IntCell.cc.
References Cell::SomeValue::ival, Cell::value, and FloatCell::zF().
bif_factorial()
ErrorCode IntCell::bif_factorial (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 330 of file IntCell.cc.
References Cell::SomeValue::ival, Cell::value, FloatCell::zF(), and zI().
bif_floor()
ErrorCode IntCell::bif_floor (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 435 of file IntCell.cc.
References Cell::SomeValue::ival, Cell::value, and zI().
bif_magnitude()
ErrorCode IntCell::bif_magnitude (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 378 of file IntCell.cc.
References bif_negative(), Cell::SomeValue::ival, Cell::value, and zI().
bif_maximum()
ErrorCode IntCell::bif_maximum (Cell * Z, const Cell * A) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 793 of file IntCell.cc.
References Cell::SomeValue::ival, Cell::value, and zI().
bif_minimum()
ErrorCode IntCell::bif_minimum (Cell * Z, const Cell * A) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 808 of file IntCell.cc.
References Cell::SomeValue::ival, Cell::value, and zI().
bif_multiply()
ErrorCode IntCell::bif_multiply (Cell * Z, const Cell * A) const virtual
overloaded Cell::bif_multiply()
Reimplemented from Cell.
Definition at line 565 of file IntCell.cc.
References get_int_value(), FloatCell::zF(), and zI().
bif_multiply_inverse()
ErrorCode IntCell::bif_multiply_inverse (Cell * Z, const Cell * A) const virtual
overloaded Cell::bif_multiply_inverse()
Reimplemented from Cell.
Definition at line 587 of file IntCell.cc.
bif_nat_log()
ErrorCode IntCell::bif_nat_log (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 449 of file IntCell.cc.
References Cell::SomeValue::ival, Cell::value, ComplexCell::zC(), and FloatCell::zF().
bif_near_int64_t()
ErrorCode IntCell::bif_near_int64_t (Cell * Z) const virtual
overloaded Cell::bif_near_int64_t()
Reimplemented from Cell.
Definition at line 824 of file IntCell.cc.
References Cell::SomeValue::ival, Cell::value, and zI().
bif_negative()
ErrorCode IntCell::bif_negative (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 361 of file IntCell.cc.
References Cell::SomeValue::ival, Cell::value, and zI().
Referenced by bif_magnitude(), and bif_subtract().
bif_pi_times()
ErrorCode IntCell::bif_pi_times (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 417 of file IntCell.cc.
References Cell::SomeValue::ival, Cell::value, and FloatCell::zF().
bif_pi_times_inverse()
ErrorCode IntCell::bif_pi_times_inverse (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 423 of file IntCell.cc.
References Cell::SomeValue::ival, Cell::value, and FloatCell::zF().
bif_power()
ErrorCode IntCell::bif_power (Cell * Z, const Cell * A) const virtual
overloaded Cell::bif_power()
Reimplemented from Cell.
Definition at line 593 of file IntCell.cc.
References get_int_value(), ComplexCell::mag2(), z0(), z1(), z_1(), ComplexCell::zC(), FloatCell::zF(), and zI().
bif_reciprocal()
ErrorCode IntCell::bif_reciprocal (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 386 of file IntCell.cc.
References Cell::SomeValue::ival, Cell::value, z1(), z_1(), and FloatCell::zF().
Referenced by bif_divide().
bif_residue()
ErrorCode IntCell::bif_residue (Cell * Z, const Cell * A) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 722 of file IntCell.cc.
References FloatCell::bif_residue(), Workspace::get_CT(), Cell::is_near_zero(), Cell::SomeValue::ival, Cell::value, z0(), FloatCell::zF(), and zI().
Referenced by Bif_F12_ENCODE::encode_Int().
bif_roll()
ErrorCode IntCell::bif_roll (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell)
Reimplemented from Cell.
Definition at line 406 of file IntCell.cc.
References Workspace::get_IO(), Workspace::get_RL(), Cell::SomeValue::ival, Cell::value, and zI().
bif_subtract()
ErrorCode IntCell::bif_subtract (Cell * Z, const Cell * A) const virtual
overloaded Cell::bif_subtract()
Reimplemented from Cell.
Definition at line 497 of file IntCell.cc.
References bif_negative(), Cell::diff_overflow(), get_int_value(), FloatCell::zF(), and zI().
bif_within_quad_CT()
ErrorCode IntCell::bif_within_quad_CT (Cell * Z) const virtual
overloaded Cell::bif_within_quad_CT()
Reimplemented from Cell.
Definition at line 832 of file IntCell.cc.
References Cell::SomeValue::ival, Cell::value, and zI().
CDR_size()
int IntCell::CDR_size () const protected virtual
overloaded Cell::CDR_size()
Reimplemented from Cell.
Definition at line 945 of file IntCell.cc.
References get_int_value().
character_representation()
PrintBuffer IntCell::character_representation (const PrintContext & pctx) const virtual
the Quad_CR representation of this cell
Reimplemented from Cell.
Definition at line 897 of file IntCell.cc.
References UCS_string::append(), FloatCell::character_representation(), ColInfo::flags, get_int_value(), PrintContext::get_scaled(), ColInfo::int_len, Cell::SomeValue::ival, ColInfo::real_len, UCS_string::size(), and Cell::value.
cIntlCell()
virtual const IntCell & IntCell::cIntlCell () const inline virtual
downcast to const IntCell
Definition at line 180 of file IntCell.hh.
compare()
Comp_result IntCell::compare (const Cell & other) const virtual
compare this with other, throw DOMAIN ERROR on illegal comparisons
Reimplemented from Cell.
Definition at line 845 of file IntCell.cc.
References Cell::compare(), Cell::get_int_value(), Cell::is_character_cell(), Cell::is_integer_cell(), Cell::is_numeric(), Cell::is_pointer_cell(), Cell::SomeValue::ival, and Cell::value.
Referenced by greater().
equal()
bool IntCell::equal (const Cell & other, double qct) const virtual
overloaded Cell::equal()
Reimplemented from Cell.
Definition at line 114 of file IntCell.cc.
References Cell::equal(), Cell::get_int_value(), Cell::is_integer_cell(), Cell::is_numeric(), Cell::SomeValue::ival, and Cell::value.
get_byte_value()
int IntCell::get_byte_value () const virtual
overloaded Cell::get_byte_value()
Reimplemented from Cell.
Definition at line 925 of file IntCell.cc.
References Cell::SomeValue::ival, and Cell::value.
get_cell_subtype()
CellType IntCell::get_cell_subtype () const protected virtual
overloaded Cell::get_cell_subtype()
Reimplemented from Cell.
Definition at line 47 of file IntCell.cc.
References Cell::SomeValue::ival, and Cell::value.
get_cell_type()
virtual CellType IntCell::get_cell_type () const inline protected virtual
overloaded Cell::get_cell_type()
Reimplemented from Cell.
Definition at line 216 of file IntCell.hh.
get_checked_near_int()
virtual APL_Integer IntCell::get_checked_near_int () const inline protected virtual
overloaded Cell::get_checked_near_int()
Reimplemented from Cell.
Definition at line 245 of file IntCell.hh.
References Cell::SomeValue::ival, and Cell::value.
get_classname()
virtual const char * IntCell::get_classname () const inline protected virtual
overloaded Cell::get_classname()
Reimplemented from RealCell.
Definition at line 269 of file IntCell.hh.
get_complex_value()
virtual APL_Complex IntCell::get_complex_value () const inline protected virtual
overloaded Cell::get_complex_value()
Reimplemented from Cell.
Definition at line 231 of file IntCell.hh.
References Cell::SomeValue::ival, and Cell::value.
get_imag_value()
virtual APL_Float IntCell::get_imag_value () const inline protected virtual
overloaded Cell::get_imag_value()
Reimplemented from Cell.
Definition at line 227 of file IntCell.hh.
get_int_value()
virtual APL_Integer IntCell::get_int_value () const inline virtual
overloaded Cell::get_int_value()
Reimplemented from Cell.
Definition at line 173 of file IntCell.hh.
References Cell::SomeValue::ival, and Cell::value.
Referenced by bif_add(), bif_divide(), bif_multiply(), bif_power(), bif_subtract(), CDR_size(), character_representation(), greater(), CollatingCache::greater_vec(), and CollatingCache::smaller_vec().
get_near_bool()
virtual bool IntCell::get_near_bool () const inline protected virtual
overloaded Cell::get_near_bool()
Reimplemented from Cell.
Definition at line 235 of file IntCell.hh.
References Cell::SomeValue::ival, and Cell::value.
get_near_int()
virtual APL_Integer IntCell::get_near_int () const inline protected virtual
overloaded Cell::get_near_int()
Reimplemented from Cell.
Definition at line 241 of file IntCell.hh.
References Cell::SomeValue::ival, and Cell::value.
get_real_value()
virtual APL_Float IntCell::get_real_value () const inline protected virtual
overloaded Cell::get_real_value()
Reimplemented from Cell.
Definition at line 223 of file IntCell.hh.
References Cell::SomeValue::ival, and Cell::value.
greater()
bool IntCell::greater (const Cell & other) const virtual
overloaded Cell::greater()
Reimplemented from Cell.
Definition at line 864 of file IntCell.cc.
References compare(), Cell::get_cell_type(), Cell::get_int_value(), get_int_value(), and Cell::get_real_value().
Hswap()
void IntCell::Hswap (IntCell & other) inline
swap this Intcell and other (for Heapsort<IntCell>)
Definition at line 165 of file IntCell.hh.
References Cell::SomeValue::ival, and Cell::value.
init_other()
virtual void IntCell::init_other (void * other, Value & cell_owner, const char * loc) const inline virtual
overloaded Cell::init_other
Reimplemented from Cell.
Definition at line 55 of file IntCell.hh.
References IntCell(), Cell::SomeValue::ival, and Cell::value.
is_integer_cell()
virtual bool IntCell::is_integer_cell () const inline virtual
overloaded Cell::is_integer_cell()
Reimplemented from Cell.
Definition at line 59 of file IntCell.hh.
is_near_int()
virtual bool IntCell::is_near_int () const inline protected virtual
overloaded Cell::is_near_int()
Reimplemented from Cell.
Definition at line 257 of file IntCell.hh.
is_near_int64_t()
virtual bool IntCell::is_near_int64_t () const inline protected virtual
overloaded Cell::is_near_int64_t()
Reimplemented from Cell.
Definition at line 261 of file IntCell.hh.
is_near_one()
virtual bool IntCell::is_near_one () const inline protected virtual
overloaded Cell::is_near_one()
Reimplemented from Cell.
Definition at line 253 of file IntCell.hh.
References Cell::SomeValue::ival, and Cell::value.
is_near_real()
virtual bool IntCell::is_near_real () const inline protected virtual
overloaded Cell::is_near_real()
Reimplemented from Cell.
Definition at line 265 of file IntCell.hh.
is_near_zero()
virtual bool IntCell::is_near_zero () const inline protected virtual
overloaded Cell::is_near_zero()
Reimplemented from Cell.
Definition at line 249 of file IntCell.hh.
References Cell::SomeValue::ival, and Cell::value.
need_scaling()
virtual bool IntCell::need_scaling (const PrintContext & pctx) const inline virtual
return true iff this cell needs scaling (exponential format) in pctx According to lrm p. 13, integer cells ignore ⎕PP an never use scaling
Reimplemented from Cell.
Definition at line 145 of file IntCell.hh.
set_int_value()
void IntCell::set_int_value (APL_Integer val) inline
set the integer value of this IntCell
Definition at line 176 of file IntCell.hh.
References Cell::SomeValue::ival, and Cell::value.
Referenced by Value::explode().
wIntCell()
virtual IntCell & IntCell::wIntCell () inline virtual
downcast to IntCell
Definition at line 183 of file IntCell.hh.
z0()
static ErrorCode IntCell::z0 (Cell * Z) inline static protected
initialize the (un-initialized) Cell *Z to integer 0
Definition at line 204 of file IntCell.hh.
References IntCell().
Referenced by NumericCell::bif_and(), NumericCell::bif_binomial(), ComplexCell::bif_circle_fun(), RealCell::bif_circle_fun(), ComplexCell::bif_circle_fun_inverse(), RealCell::bif_circle_fun_inverse(), ComplexCell::bif_direction(), FloatCell::bif_direction(), Cell::bif_equal(), ComplexCell::bif_equal(), NumericCell::bif_nand(), NumericCell::bif_nor(), NumericCell::bif_not(), NumericCell::bif_or(), ComplexCell::bif_power(), FloatCell::bif_power(), bif_power(), ComplexCell::bif_residue(), FloatCell::bif_residue(), bif_residue(), Value::double_ravel(), Quad_EX::expunge(), Value::init_ravel(), NumericCell::integer_binomial(), Value::print_member(), PointerCell::release(), and Value::Value().
z1()
static ErrorCode IntCell::z1 (Cell * Z) inline static protected
initialize the (un-initialized) Cell *Z to integer 1
Definition at line 208 of file IntCell.hh.
References IntCell().
Referenced by NumericCell::bif_and(), FloatCell::bif_direction(), ComplexCell::bif_divide(), FloatCell::bif_divide(), bif_divide(), ComplexCell::bif_equal(), ComplexCell::bif_logarithm(), RealCell::bif_logarithm(), NumericCell::bif_nand(), NumericCell::bif_nor(), NumericCell::bif_not(), Cell::bif_not_equal(), NumericCell::bif_or(), ComplexCell::bif_power(), FloatCell::bif_power(), bif_power(), and bif_reciprocal().
z_1()
static ErrorCode IntCell::z_1 (Cell * Z) inline static protected
initialize the (un-initialized) Cell *Z to integer ¯1
Definition at line 212 of file IntCell.hh.
References IntCell().
Referenced by FloatCell::bif_direction(), bif_power(), and bif_reciprocal().
zI()
static ErrorCode IntCell::zI (Cell * Z, APL_Integer aint) inline static protected
initialize Z to APL_Integer v
Definition at line 199 of file IntCell.hh.
References IntCell().
Referenced by FloatCell::bif_add(), bif_add(), NumericCell::bif_and(), NumericCell::bif_and_bitwise(), FloatCell::bif_ceiling(), bif_ceiling(), bif_conjugate(), FloatCell::bif_direction(), bif_direction(), bif_divide(), Cell::bif_equal(), NumericCell::bif_equal_bitwise(), bif_factorial(), FloatCell::bif_floor(), bif_floor(), Cell::bif_greater_eq(), Cell::bif_greater_than(), Cell::bif_less_eq(), Cell::bif_less_than(), bif_magnitude(), ComplexCell::bif_maximum(), FloatCell::bif_maximum(), bif_maximum(), ComplexCell::bif_minimum(), FloatCell::bif_minimum(), bif_minimum(), FloatCell::bif_multiply(), bif_multiply(), NumericCell::bif_nand_bitwise(), FloatCell::bif_near_int64_t(), bif_near_int64_t(), bif_negative(), NumericCell::bif_nor_bitwise(), NumericCell::bif_not_bitwise(), Cell::bif_not_equal(), NumericCell::bif_not_equal_bitwise(), NumericCell::bif_or(), NumericCell::bif_or_bitwise(), bif_power(), FloatCell::bif_reciprocal(), bif_residue(), ComplexCell::bif_roll(), FloatCell::bif_roll(), bif_roll(), FloatCell::bif_subtract(), bif_subtract(), bif_within_quad_CT(), Value::init_ravel(), NumericCell::integer_binomial(), and NumericCell::K33_binomial().
Friends And Related Function Documentation
Cell
friend class Cell friend
Definition at line 36 of file IntCell.hh.
ComplexCell
friend class ComplexCell friend
Definition at line 37 of file IntCell.hh.
FloatCell
friend class FloatCell friend
Definition at line 38 of file IntCell.hh.
NumericCell
friend class NumericCell friend
Definition at line 39 of file IntCell.hh.
PointerCell
friend class PointerCell friend
Definition at line 40 of file IntCell.hh.
Quad_EX
friend class Quad_EX friend
Definition at line 42 of file IntCell.hh.
RealCell
friend class RealCell friend
Definition at line 41 of file IntCell.hh.
Value
friend class Value friend
Definition at line 43 of file IntCell.hh.
Member Data Documentation
boolean_FALSE
const IntCell IntCell::boolean_FALSE static
false (for packed Cells)
Definition at line 189 of file IntCell.hh.
Referenced by Value::packed_fetcher().
boolean_TRUE
const IntCell IntCell::boolean_TRUE static
true (for packed Cells)
Definition at line 192 of file IntCell.hh.
Referenced by Value::packed_fetcher().
The documentation for this class was generated from the following files:
src/IntCell.hh
src/IntCell.cc