GNU APL: DerivedFunction Class Reference
DerivedFunction Class Reference
An APL operator bound to its function operand(s)
#include <DerivedFunction.hh>
Public Member Functions
DerivedFunction ()
Constructor for DerivedFunctionCache.
DerivedFunction (Token &lf, Function_P dyop, Token &rf, const char *loc)
Constructor (dyadic operator)
DerivedFunction (Token &lf, Function_P dyop, Value_P X, Token &rval, const char *loc)
Constructor (dyadic operator with axis: fun ⍤[] rval)
DerivedFunction (Token &lfun, Function_P monop, const char *loc)
Constructor (monadic operator, no axis)
DerivedFunction (Token &lf, Function_P monop, Value_P X, const char *loc)
Constructor (monadic operator, with axis)
DerivedFunction (Function_P func, Value_P X, const char *loc)
Constructor (function with axis)
void destroy_derived (const char *loc)
deallocate resources held by this DerivedFunction
virtual ostream & print (ostream &out) const
overloaded Function::print();
virtual bool is_derived () const
overloaded Function::is_derived();
Function_P get_LO () const
return the left operand of this derived function
Value_P get_bound_LO_value () const
return the value (if any) bound to an operator (that allows it)
Function_P get_OPER () const
return the operator of this derived function
Function_P get_RO () const
return the right operand (or 0) of this derived function
const Value * get_AXIS () const
return the axis argument (or 0 if none) of this derived function
virtual bool has_result () const
Overloaded Function::has_result();.
void unmark_all_values () const
clear the marked bit in values bound to this derived functions (if any).
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Protected Member Functions
virtual void print_properties (ostream &out, int indent) const
Overloaded Function::print_properties()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B();
virtual Token eval_XB (Value_P X, Value_P B) const
overloaded Function::eval_XB();
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB();
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
overloaded Function::eval_AXB()
virtual bool may_push_SI () const
overloaded Function::may_push_SI()
virtual Value_P * locate_X () const
overloaded Function::locate_X()
Protected Attributes
Token left_arg
the function (to the left of the operator)
Function_P oper
the monadic operator (to the right of the function)
Token right_fun
the (normally) function on the right of the (dyadic) operator (if any).
Value_P axis
the axis for mon_oper, or 0 if no axis
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Private Member Functions
~DerivedFunction ()
destructor
Additional Inherited Members
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Detailed Description
An APL operator bound to its function operand(s)
an operator bound to its left and (in the case of a dyadic operator) to its right operand.
Definition at line 33 of file DerivedFunction.hh.
Constructor & Destructor Documentation
DerivedFunction() [1/6]
DerivedFunction::DerivedFunction () inline
Constructor for DerivedFunctionCache.
Definition at line 37 of file DerivedFunction.hh.
DerivedFunction() [2/6]
DerivedFunction::DerivedFunction (Token & lf, Function_P dyop, Token & rf, const char * loc)
Constructor (dyadic operator)
Definition at line 30 of file DerivedFunction.cc.
References oper, and print().
DerivedFunction() [3/6]
DerivedFunction::DerivedFunction (Token & lf, Function_P dyop, Value_P X, Token & rval, const char * loc)
Constructor (dyadic operator with axis: fun ⍤[] rval)
Definition at line 47 of file DerivedFunction.cc.
DerivedFunction() [4/6]
DerivedFunction::DerivedFunction (Token & lfun, Function_P monop, const char * loc)
Constructor (monadic operator, no axis)
Definition at line 57 of file DerivedFunction.cc.
References oper, and print().
DerivedFunction() [5/6]
DerivedFunction::DerivedFunction (Token & lf, Function_P monop, Value_P X, const char * loc)
Constructor (monadic operator, with axis)
Definition at line 73 of file DerivedFunction.cc.
References oper, and print().
DerivedFunction() [6/6]
DerivedFunction::DerivedFunction (Function_P func, Value_P X, const char * loc)
Constructor (function with axis)
Definition at line 90 of file DerivedFunction.cc.
References print().
~DerivedFunction()
DerivedFunction::~DerivedFunction () private
destructor
Definition at line 106 of file DerivedFunction.cc.
Member Function Documentation
destroy_derived()
void DerivedFunction::destroy_derived (const char * loc)
deallocate resources held by this DerivedFunction
Definition at line 115 of file DerivedFunction.cc.
References axis, Token::clear(), Value_P_Base::clear(), NamedObject::get_name(), left_arg, and right_fun.
Referenced by DerivedFunctionCache::reset().
eval_AB()
Token DerivedFunction::eval_AB (Value_P A, Value_P B) const protected virtual
overloaded Function::eval_AB();
Reimplemented from Function.
Definition at line 199 of file DerivedFunction.cc.
References axis, Token::get_apl_val(), Token::get_tag(), Token::is_function(), left_arg, oper, print(), and right_fun.
eval_AXB()
Token DerivedFunction::eval_AXB (Value_P A, Value_P X, Value_P B) const protected virtual
overloaded Function::eval_AXB()
Reimplemented from Function.
Definition at line 237 of file DerivedFunction.cc.
References Token::get_tag(), left_arg, oper, print(), and right_fun.
eval_B()
Token DerivedFunction::eval_B (Value_P B) const protected virtual
overloaded Function::eval_B();
Reimplemented from Function.
Definition at line 128 of file DerivedFunction.cc.
References axis, Token::get_apl_val(), Token::get_tag(), Token::is_function(), left_arg, oper, print(), and right_fun.
eval_XB()
Token DerivedFunction::eval_XB (Value_P X, Value_P B) const protected virtual
overloaded Function::eval_XB();
Reimplemented from Function.
Definition at line 166 of file DerivedFunction.cc.
References axis, Token::get_apl_val(), Token::get_tag(), Token::is_function(), left_arg, oper, print(), and right_fun.
get_AXIS()
const Value * DerivedFunction::get_AXIS () const inline
return the axis argument (or 0 if none) of this derived function
Definition at line 86 of file DerivedFunction.hh.
References axis, and Value_P_Base::get().
Referenced by XML_Saving_Archive::save_Function().
get_bound_LO_value()
Value_P DerivedFunction::get_bound_LO_value () const inline
return the value (if any) bound to an operator (that allows it)
Definition at line 70 of file DerivedFunction.hh.
References Token::get_apl_val(), Token::is_apl_val(), and left_arg.
Referenced by Bif_OPER1_COMMUTE::eval_LB().
get_LO()
Function_P DerivedFunction::get_LO () const inline
return the left operand of this derived function
Definition at line 66 of file DerivedFunction.hh.
References Token::get_function(), and left_arg.
Referenced by XML_Saving_Archive::save_Function().
get_OPER()
Function_P DerivedFunction::get_OPER () const inline
return the operator of this derived function
Definition at line 76 of file DerivedFunction.hh.
References oper.
Referenced by Bif_OPER1_COMMUTE::eval_LB(), and XML_Saving_Archive::save_Function().
get_RO()
Function_P DerivedFunction::get_RO () const inline
return the right operand (or 0) of this derived function
Definition at line 80 of file DerivedFunction.hh.
References Token::get_function(), Token::get_tag(), and right_fun.
Referenced by XML_Saving_Archive::save_Function().
has_result()
bool DerivedFunction::has_result () const virtual
Overloaded Function::has_result();.
Implements Function.
Definition at line 280 of file DerivedFunction.cc.
References Token::get_function(), Token::is_function(), left_arg, and oper.
is_derived()
virtual bool DerivedFunction::is_derived () const inline virtual
overloaded Function::is_derived();
Reimplemented from Function.
Definition at line 62 of file DerivedFunction.hh.
locate_X()
virtual Value_P * DerivedFunction::locate_X () const inline protected virtual
overloaded Function::locate_X()
Reimplemented from Function.
Definition at line 119 of file DerivedFunction.hh.
References axis.
may_push_SI()
virtual bool DerivedFunction::may_push_SI () const inline protected virtual
overloaded Function::may_push_SI()
Reimplemented from Function.
Definition at line 112 of file DerivedFunction.hh.
References Token::get_function(), Token::is_function(), left_arg, oper, and right_fun.
print()
ostream & DerivedFunction::print (ostream & out) const virtual
overloaded Function::print();
Implements Function.
Definition at line 259 of file DerivedFunction.cc.
References axis, Token::get_function(), Token::get_tag(), Token::is_function(), left_arg, oper, and right_fun.
Referenced by DerivedFunction(), eval_AB(), eval_AXB(), eval_B(), and eval_XB().
print_properties()
void DerivedFunction::print_properties (ostream & out, int indent) const protected virtual
Overloaded Function::print_properties()
Implements Function.
Definition at line 295 of file DerivedFunction.cc.
References axis, Token::get_function(), Token::get_tag(), Token::is_function(), left_arg, oper, and right_fun.
unmark_all_values()
void DerivedFunction::unmark_all_values () const
clear the marked bit in values bound to this derived functions (if any).
Definition at line 288 of file DerivedFunction.cc.
References axis, Token::get_apl_val(), Token::is_apl_val(), and left_arg.
Referenced by DerivedFunctionCache::unmark_all_values().
Member Data Documentation
axis
Value_P DerivedFunction::axis protected
the axis for mon_oper, or 0 if no axis
Definition at line 134 of file DerivedFunction.hh.
Referenced by destroy_derived(), eval_AB(), eval_B(), eval_XB(), get_AXIS(), locate_X(), print(), print_properties(), and unmark_all_values().
left_arg
Token DerivedFunction::left_arg protected
the function (to the left of the operator)
Definition at line 123 of file DerivedFunction.hh.
Referenced by destroy_derived(), eval_AB(), eval_AXB(), eval_B(), eval_XB(), get_bound_LO_value(), get_LO(), has_result(), may_push_SI(), print(), print_properties(), and unmark_all_values().
oper
Function_P DerivedFunction::oper protected
the monadic operator (to the right of the function)
Definition at line 126 of file DerivedFunction.hh.
Referenced by DerivedFunction(), eval_AB(), eval_AXB(), eval_B(), eval_XB(), get_OPER(), has_result(), may_push_SI(), print(), and print_properties().
right_fun
Token DerivedFunction::right_fun protected
the (normally) function on the right of the (dyadic) operator (if any).
Definition at line 131 of file DerivedFunction.hh.
Referenced by destroy_derived(), eval_AB(), eval_AXB(), eval_B(), eval_XB(), get_RO(), may_push_SI(), print(), and print_properties().
The documentation for this class was generated from the following files:
src/DerivedFunction.hh
src/DerivedFunction.cc