GNU APL: ValueStackItem Class Reference
ValueStackItem Class Reference
One entry in the value stack of a Symbol.
#include <Symbol.hh>
Classes
union _sym_val
the possible "values" of a symbol
Public Types
enum VS_flags {
VSF_NONE = 0 ,
VSF_COW = 0x01
}
flags of this ValueStackItem
Public Member Functions
NameClass get_NC () const
return the name class for this ValueStackItem
void set_NC (NameClass nc)
set the name class for this ValueStackItem
void set_apl_value (Value_P new_value)
set this ValueStackItem to APL value new_value
void reset_apl_value ()
reset (clear) the APL value in this ValueStackItem
const Function_Line get_label () const
return the line number of a label (caller must have checked NC_LABEL)
Function_P get_function () const
return the function (caller must have checked NC_FUNOPER).
void set_function (Function_P fun)
set function to fun
void clear_function ()
delete the function
Function_P * get_function_P ()
return the address of function (caller must have checked NC_FUNOPER).
SV_key get_key () const
return the shared variable key (caller must have checked NC_SYSTEM_VAR).
void set_key (SV_key key)
set the shared variable key
const Value * get_val_cptr () const
return the APL value of this ValueStackItem, or 0 if it has none. Only used to iterate over the ValueStack in Doxy.cc and in Quad_RL to quickly access the current ⎕RL
Value * get_val_wptr ()
return the APL value of this ValueStackItem, or 0 if it has none Only used in ⎕RL for quick in-place uopdate of the current ⎕RL.
VS_flags get_vs_flags () const
return the flags of this ValueStackItem
void set_vs_flags (VS_flags flg)
set the flags of this ValueStackItem
void isolate (const char *loc)
make apl_val the sole owner of apl_val.value
Protected Member Functions
ValueStackItem ()
constructor: ValueStackItem for an unused symbol
ValueStackItem (Function_Line lab)
constructor: ValueStackItem for a label (function line)
ValueStackItem (Value_P val)
constructor: ValueStackItem for a variable
ValueStackItem (SV_key key)
constructor: ValueStackItem for a shared variable
void clear ()
reset this ValueStackItem to being unused
Protected Attributes
_sym_val sym_val
the (current) value of this symbol (unless variable)
Value_P apl_val
the (current) value of this symbol (if variable)
NameClass name_class
the (current) name class (like ⎕NC, unless shared variable)
VS_flags flags
flags of this ValueStackItem
Friends
class Symbol
Detailed Description
One entry in the value stack of a Symbol.
One entry in the value stack of a symbol. The value stack is pushed/poped when the symbol is localized on entry/return of a user defined function.
Definition at line 43 of file Symbol.hh.
Member Enumeration Documentation
VS_flags
enum ValueStackItem::VS_flags
flags of this ValueStackItem
Enumerator
VSF_NONE
no flags
VSF_COW
Clone On Write.
Definition at line 113 of file Symbol.hh.
Constructor & Destructor Documentation
ValueStackItem() [1/4]
ValueStackItem::ValueStackItem () inline protected
constructor: ValueStackItem for an unused symbol
Definition at line 133 of file Symbol.hh.
References sym_val.
ValueStackItem() [2/4]
ValueStackItem::ValueStackItem (Function_Line lab) inline protected
constructor: ValueStackItem for a label (function line)
Definition at line 139 of file Symbol.hh.
References ValueStackItem::_sym_val::label, and sym_val.
ValueStackItem() [3/4]
ValueStackItem::ValueStackItem (Value_P val) inline protected
constructor: ValueStackItem for a variable
Definition at line 145 of file Symbol.hh.
ValueStackItem() [4/4]
ValueStackItem::ValueStackItem (SV_key key) inline protected
constructor: ValueStackItem for a shared variable
Definition at line 152 of file Symbol.hh.
References ValueStackItem::_sym_val::sv_key, and sym_val.
Member Function Documentation
clear()
void ValueStackItem::clear () inline protected
reset this ValueStackItem to being unused
Definition at line 158 of file Symbol.hh.
References apl_val, flags, name_class, Value_P_Base::reset(), sym_val, and VSF_NONE.
Referenced by Symbol::expunge().
clear_function()
void ValueStackItem::clear_function () inline
delete the function
Definition at line 83 of file Symbol.hh.
References ValueStackItem::_sym_val::function, name_class, and sym_val.
Referenced by SymbolTable::erase_one_symbol(), and Symbol::set_NC().
get_function()
Function_P ValueStackItem::get_function () const inline
return the function (caller must have checked NC_FUNOPER).
Definition at line 72 of file Symbol.hh.
References ValueStackItem::_sym_val::function, and sym_val.
Referenced by Symbol::assign_named_lambda(), Symbol::clear_vs(), Symbol::dump(), SymbolTable::erase_one_symbol(), Symbol::expunge(), XML_Loading_Archive::find_lambda(), Symbol::get_attributes(), Symbol::get_exec_ufun_depth(), Symbol::get_function(), Symbol::get_SI_level(), Symbol::print_verbose(), XML_Loading_Archive::read_Function_name(), XML_Loading_Archive::read_UserFunction(), Symbol::resolve(), XML_Saving_Archive::save_vstack_item(), Symbol::show_owners(), and Symbol::unmark_all_values().
get_function_P()
Function_P * ValueStackItem::get_function_P () inline
return the address of function (caller must have checked NC_FUNOPER).
Definition at line 90 of file Symbol.hh.
References ValueStackItem::_sym_val::function, and sym_val.
Referenced by XML_Loading_Archive::read_Function().
get_key()
SV_key ValueStackItem::get_key () const inline
return the shared variable key (caller must have checked NC_SYSTEM_VAR).
Definition at line 94 of file Symbol.hh.
References ValueStackItem::_sym_val::sv_key, and sym_val.
Referenced by XML_Saving_Archive::save_vstack_item().
get_label()
const Function_Line ValueStackItem::get_label () const inline
return the line number of a label (caller must have checked NC_LABEL)
Definition at line 68 of file Symbol.hh.
References ValueStackItem::_sym_val::label, and sym_val.
Referenced by Symbol::assign(), Command::cmd_HELP(), Symbol::print_verbose(), Symbol::resolve(), and XML_Saving_Archive::save_vstack_item().
get_NC()
NameClass ValueStackItem::get_NC () const inline
return the name class for this ValueStackItem
Definition at line 49 of file Symbol.hh.
References name_class.
Referenced by Symbol::assign(), Symbol::assign_named_lambda(), Symbol::clear_vs(), Command::cmd_HELP(), Symbol::dump(), SymbolTable::dump(), SymbolTable::erase_one_symbol(), Symbol::expunge(), XML_Loading_Archive::find_lambda(), Symbol::get_attributes(), Symbol::get_exec_ufun_depth(), Symbol::get_function(), Symbol::pop(), Symbol::print_verbose(), XML_Loading_Archive::read_Function_name(), XML_Loading_Archive::read_UserFunction(), Symbol::resolve(), XML_Saving_Archive::save_vstack_item(), Symbol::set_NC(), Symbol::share_var(), Symbol::show_owners(), Symbol::unmark_all_values(), and Symbol::unshare_var().
get_val_cptr()
const Value * ValueStackItem::get_val_cptr () const inline
return the APL value of this ValueStackItem, or 0 if it has none. Only used to iterate over the ValueStack in Doxy.cc and in Quad_RL to quickly access the current ⎕RL
Definition at line 104 of file Symbol.hh.
References apl_val, and Value_P_Base::get().
Referenced by Symbol::assign(), Symbol::dump(), Symbol::get_SI_level(), Symbol::print_verbose(), XML_Saving_Archive::save_vstack_item(), Symbol::show_owners(), and Symbol::unmark_all_values().
get_val_wptr()
Value * ValueStackItem::get_val_wptr () inline
return the APL value of this ValueStackItem, or 0 if it has none Only used in ⎕RL for quick in-place uopdate of the current ⎕RL.
Definition at line 109 of file Symbol.hh.
References apl_val, and Value_P_Base::get().
get_vs_flags()
VS_flags ValueStackItem::get_vs_flags () const inline
return the flags of this ValueStackItem
Definition at line 120 of file Symbol.hh.
References flags.
isolate()
void ValueStackItem::isolate (const char * loc) inline
make apl_val the sole owner of apl_val.value
Definition at line 128 of file Symbol.hh.
References apl_val, and Value_P_Base::isolate().
reset_apl_value()
void ValueStackItem::reset_apl_value () inline
reset (clear) the APL value in this ValueStackItem
Definition at line 64 of file Symbol.hh.
References apl_val, and Value_P_Base::reset().
Referenced by Symbol::clear_vs(), and Symbol::expunge().
set_apl_value()
void ValueStackItem::set_apl_value (Value_P new_value) inline
set this ValueStackItem to APL value new_value
Definition at line 57 of file Symbol.hh.
References apl_val, and name_class.
Referenced by Symbol::assign().
set_function()
void ValueStackItem::set_function (Function_P fun) inline
set function to fun
Definition at line 76 of file Symbol.hh.
References ValueStackItem::_sym_val::function, name_class, and sym_val.
Referenced by Symbol::assign_named_lambda(), Symbol::push_function(), and Symbol::set_NC().
set_key()
void ValueStackItem::set_key (SV_key key) inline
set the shared variable key
Definition at line 98 of file Symbol.hh.
References name_class, ValueStackItem::_sym_val::sv_key, and sym_val.
set_NC()
void ValueStackItem::set_NC (NameClass nc) inline
set the name class for this ValueStackItem
Definition at line 53 of file Symbol.hh.
References name_class.
Referenced by Symbol::clear_vs(), Symbol::expunge(), Symbol::set_NC(), and Symbol::unshare_var().
set_vs_flags()
void ValueStackItem::set_vs_flags (VS_flags flg) inline
set the flags of this ValueStackItem
Definition at line 124 of file Symbol.hh.
References flags.
Friends And Related Function Documentation
Symbol
friend class Symbol friend
Definition at line 45 of file Symbol.hh.
Member Data Documentation
apl_val
Value_P ValueStackItem::apl_val protected
the (current) value of this symbol (if variable)
Definition at line 179 of file Symbol.hh.
Referenced by clear(), get_val_cptr(), get_val_wptr(), isolate(), reset_apl_value(), and set_apl_value().
flags
VS_flags ValueStackItem::flags protected
flags of this ValueStackItem
Definition at line 185 of file Symbol.hh.
Referenced by clear(), get_vs_flags(), and set_vs_flags().
name_class
NameClass ValueStackItem::name_class protected
the (current) name class (like ⎕NC, unless shared variable)
Definition at line 182 of file Symbol.hh.
Referenced by clear(), clear_function(), get_NC(), set_apl_value(), set_function(), set_key(), and set_NC().
sym_val
_sym_val ValueStackItem::sym_val protected
the (current) value of this symbol (unless variable)
Definition at line 176 of file Symbol.hh.
Referenced by clear(), clear_function(), get_function(), get_function_P(), get_key(), get_label(), set_function(), set_key(), and ValueStackItem().
The documentation for this class was generated from the following file:
src/Symbol.hh