GNU APL: FunctionStatistics Class Reference
FunctionStatistics Class Reference
Performance counters for an entire APL system function.
#include <Performance.hh>
Public Member Functions
FunctionStatistics (Pfstat_ID id)
constructor: FunctionStatistics with ID id
virtual void reset ()
overloaded Statistics::print()
virtual void print (ostream &out)
overloaded Statistics::print()
virtual void save_data (ostream &outf, const char *perf_name)
overloaded Statistics::save_data()
virtual const Statistics_record * get_record () const
return the (CPU-)cycles statistics
const Statistics_record & get_data () const
return the (CPU-)cycles statistics
void add_sample (uint64_t cycles, uint64_t veclen)
add a sample
Public Member Functions inherited from Statistics
Statistics (Pfstat_ID _id)
constructor
virtual ~Statistics ()
destructor
virtual void print (ostream &out)=0
print statistics
virtual void save_data (ostream &outf, const char *perf_name)=0
write statistics to file
virtual void reset ()=0
reset this statistics
virtual const Statistics_record * get_first_record () const
return the statistics for the first passes
virtual const Statistics_record * get_record () const
return the statistics for the subsequent passes
const char * get_name () const
return the name of this statistics
Protected Attributes
Statistics_record vec_lengths
a statistics of vector lengths
Statistics_record vec_cycles
the cycles executed
Protected Attributes inherited from Statistics
const Pfstat_ID id
the ID of this statistics
Additional Inherited Members
Static Public Member Functions inherited from Statistics
static const char * get_name (Pfstat_ID id)
return the name of the statistics with ID id
Detailed Description
Performance counters for an entire APL system function.
Definition at line 201 of file Performance.hh.
Constructor & Destructor Documentation
FunctionStatistics()
FunctionStatistics::FunctionStatistics (Pfstat_ID id) inline
constructor: FunctionStatistics with ID id
Definition at line 205 of file Performance.hh.
References reset().
Member Function Documentation
add_sample()
void FunctionStatistics::add_sample (uint64_t cycles, uint64_t veclen) inline
add a sample
Definition at line 231 of file Performance.hh.
References Statistics_record::add_sample(), vec_cycles, and vec_lengths.
get_data()
const Statistics_record & FunctionStatistics::get_data () const inline
return the (CPU-)cycles statistics
Definition at line 227 of file Performance.hh.
References vec_cycles.
get_record()
virtual const Statistics_record * FunctionStatistics::get_record () const inline virtual
return the (CPU-)cycles statistics
Reimplemented from Statistics.
Definition at line 223 of file Performance.hh.
References vec_cycles.
print()
void FunctionStatistics::print (ostream & out) virtual
overloaded Statistics::print()
Implements Statistics.
Definition at line 321 of file Performance.cc.
References Statistics_record::get_average(), Statistics_record::get_count(), Statistics::get_name(), Statistics_record::get_sum(), Statistics_record::print5(), UCS_string::size(), vec_cycles, and vec_lengths.
reset()
virtual void FunctionStatistics::reset () inline virtual
overloaded Statistics::print()
Implements Statistics.
Definition at line 210 of file Performance.hh.
References Statistics_record::reset(), vec_cycles, and vec_lengths.
Referenced by FunctionStatistics().
save_data()
void FunctionStatistics::save_data (ostream & outf, const char * perf_name) virtual
overloaded Statistics::save_data()
Implements Statistics.
Definition at line 339 of file Performance.cc.
References Statistics_record::save_record(), and vec_cycles.
Member Data Documentation
vec_cycles
Statistics_record FunctionStatistics::vec_cycles protected
the cycles executed
Definition at line 242 of file Performance.hh.
Referenced by add_sample(), get_data(), get_record(), print(), reset(), and save_data().
vec_lengths
Statistics_record FunctionStatistics::vec_lengths protected
a statistics of vector lengths
Definition at line 239 of file Performance.hh.
Referenced by add_sample(), print(), and reset().
The documentation for this class was generated from the following files:
src/Performance.hh
src/Performance.cc