GNU APL: NumericCell Class Reference
NumericCell Class Reference
Base class for RealCell and ComplexCell.
#include <NumericCell.hh>
Static Public Member Functions
static ErrorCode zV (Cell *Z, APL_Float flt)
initialize the (un-initialized) Cell *Z to (if possible) an IntCell or else to a FloatCell with value flt.
static ErrorCode zV (Cell *Z, APL_Complex cpx)
initialize the (un-initialized) Cell *Z to (if possible) an IntCell, a FloatCell, or a ComplexCell with value cpx.
static ErrorCode zV (Cell *Z, APL_Float real, APL_Float imag)
initialize the (un-initialized) Cell *Z to (if possible) an IntCell, a FloatCell, or a ComplexCell with value cpx.
Static Public Member Functions inherited from Cell
static bool A_greater_B (const Cell *const &A, const Cell *const &B, const void *unused_comp_arg)
like greater() but static
static bool same_half_plane (APL_Complex A, APL_Complex B)
ISO p.15: return true if A and B are on the same half-plane.
static bool tolerantly_equal (APL_Float A, APL_Float B, double qct)
ISO p.19: return true if real A is tolerantly equal to real B within C.
static bool tolerantly_equal (APL_Complex A, APL_Complex B, double qct)
ISO p. 19: return true if complex A and B are tolerantly equal within real qct.
static bool integral_within (APL_Float A, double qct)
ISO p. 19: A is integral (close to a Gaussian Integer) within qct.
static bool sum_overflow (APL_Integer z, APL_Integer a, APL_Integer b)
return true if z = a + b had an overflow.
static bool diff_overflow (APL_Integer z, APL_Integer a, APL_Integer b)
return true if z = a - b had an overflow.
static bool prod_overflow (int64_t a, int64_t b)
return true if multiplying a and b will (probably) overflow. For some huge a or b the result may incorrectly return true. a or b the result may incorrectly return true.
static void copy (Cell *&dst, const Cell *&src, ShapeItem count, Value &cell_owner)
copy (deep) count cells from src to dest)
static void copy (Value &val, const Cell *&src, ShapeItem count)
copy (deep) count cells from src to val (which is under construction))
static bool is_near_int (APL_Float value)
true iff value is close to an int (within +- qct)
static bool is_near_int64_t (APL_Float value)
true iff value is close to an int64_t (i.e. fots into an int64_t
static bool is_near_zero (APL_Float value)
true iff value is close to 0 (within +- qct)
static APL_Integer near_int (APL_Float value)
return value if it is close to int, or else throw DOMAIN_ERROR
static bool greater_cp (const ShapeItem &a, const ShapeItem &b, const void *cells)
compare cells[a] and cells[b] ascendingly
static bool smaller_cp (const ShapeItem &a, const ShapeItem &b, const void *cells)
compare cells[a] and cells[b] descendingly
static bool compare_stable (const Cell *const &A, const Cell *const &B, const void *comp_arg)
a stable compare function to be used with Heapsort. Equal cells are compared by their address. Return true iff A > B or A = B and &A > &B.
static bool compare_ptr (const Cell *const &A, const Cell *const &B, const void *comp_arg)
a stable compare function to be used with Heapsort. The cell contents are ignored and only the cell addresses are being compared. Return true iff &A > &B.
static ShapeItem * sorted_indices (const Cell *ravel, ShapeItem length, Sort_order order, ShapeItem comp_len)
return length indices i1, i2, ... iN so that ravel[i1] < ravel[i2] < ... < ravel[iN]. The indices are 0-based and the caller must delete[] the result. Returns 0 on error (= WS FULL).
static const char * get_cell_type_name (CellType ct)
the name of ct
Protected Member Functions
virtual bool is_numeric () const
overloaded Cell::is_numeric()
virtual ErrorCode bif_not (Cell *Z) const
overloaded Cell::bif_not()
virtual ErrorCode bif_not_bitwise (Cell *Z) const
overloaded Cell::bif_not_bitwise()
virtual ErrorCode bif_and (Cell *Z, const Cell *A) const
overloaded Cell::bif_and()
virtual ErrorCode bif_and_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_and_bitwise()
virtual ErrorCode bif_equal_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_equal_bitwise()
virtual ErrorCode bif_not_equal_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_not_equal_bitwise()
virtual ErrorCode bif_binomial (Cell *Z, const Cell *A) const
overloaded Cell::bif_binomial()
virtual ErrorCode bif_nand (Cell *Z, const Cell *A) const
overloaded Cell::bif_nand()
virtual ErrorCode bif_nand_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_nand_bitwise()
virtual ErrorCode bif_nor (Cell *Z, const Cell *A) const
overloaded Cell::bif_nor()
virtual ErrorCode bif_nor_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_nor_bitwise()
virtual ErrorCode bif_or (Cell *Z, const Cell *A) const
overloaded Cell::bif_or()
virtual ErrorCode bif_or_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_or_bitwise()
virtual const char * get_classname () const
overloaded Cell::get_classname()
ErrorCode complex_binomial (Cell *Z, const Cell *A) const
N over K for complex A and/or B.
ErrorCode real_binomial (Cell *Z, const Cell *A) const
N over K for non-integer A and/or B.
Static Protected Member Functions
static ErrorCode K33_binomial (Cell *Z, APL_Integer N, APL_Integer K, bool negate)
compute binomial funtion for integers a and b
static ErrorCode int_gcd (APL_Integer &z, APL_Integer a, APL_Integer b)
return the greatest common divisor of integers a and b
static ErrorCode flt_gcd (APL_Float &z, APL_Float a, APL_Float b, double qct)
return the greatest common divisor of real a and b
static ErrorCode integer_binomial (Cell *Z, APL_Integer N, APL_Integer K, bool negate)
N over K for positive integers N and K.
static ErrorCode cpx_gcd (APL_Complex &z, APL_Complex a, APL_Complex b, double qct)
return the greatest common divisor of complex a and b
static APL_Complex cpx_max_real (APL_Complex a)
multiply a by 1, -1, i, or -i so that a.real is maximal
Additional Inherited Members
Public Member Functions inherited from Cell
Cell ()
Construct an un-initialized Cell.
void init (const Cell &other, Value &this_owner, const char *loc)
init this Cell from a (possibly deep) copy of other
virtual void init_other (void *other, Value &other_owner, const char *loc) const
init (uninitialized) Cell other from this initialized cell
void init_from_value (Value *value, Value &cell_owner, const char *loc)
init this Cell from value. If value is a scalar then its first element is used (and value is erased). Otherwise a PointerCell is created.
virtual bool greater (const Cell &other) const
Return true if this cell is greater than other, with:
virtual bool equal (const Cell &other, double qct) const
return true if this cell is equal to other
Value_P to_value (const char *loc) const
return pointer value of a PointerCell or create a scalar with a copy of this cell.
void init_type (const Cell &other, Value &cell_owner, const char *loc)
init this cell to be the type of other
virtual Unicode get_char_value () const
Return the character value of a cell.
virtual int get_byte_value () const
Return the byte value (-128..255 incl) of a cell.
virtual APL_Integer get_int_value () const
Return the integer value of a cell.
virtual APL_Float get_real_value () const
Return the real part of a cell.
virtual APL_Float get_imag_value () const
Return the imaginary part of a cell.
virtual APL_Complex get_complex_value () const
Return the complex value of a cell.
virtual Value_P get_pointer_value () const
Return the APL value of a cell (Asserts for non-pointer cells)
virtual Cell * get_lval_value () const
Return the APL value of a cell (Asserts for non-lval cells)
virtual PrintBuffer character_representation (const PrintContext &pctx) const
the Quad_CR representation of this cell
virtual bool need_scaling (const PrintContext &pctx) const
return true if this cell needs scaling (exponential format) in pctx
virtual bool get_near_bool () const
Return value if it is close to boolean, or else throw DOMAIN_ERROR.
virtual APL_Integer get_near_int () const
Return value if it is close to int, or else throw DOMAIN_ERROR.
virtual APL_Integer get_checked_near_int () const
Return value if it is (known to be) close to int, or else Assert()
virtual bool is_near_zero () const
return true iff value is numeric and close to 0
virtual bool is_near_one () const
return true iff value is numeric and close to 1
bool is_near_bool () const
return true iff value is numeric and close to 0 or 1
virtual bool is_near_int () const
True iff value is numeric and close to an int.
virtual bool is_near_int64_t () const
True iff value is numeric and close to an int.
virtual bool is_near_real () const
return true iff value is numeric and close to a real number
virtual int CDR_size () const
return the minimum number of data bytes to store this cell in CDR format. The actual number of data bytes can be bigger if other cells need more bytes,
virtual void release (const char *loc)
Release content pointed to (complex, APL value)
virtual bool is_integer_cell () const
Return true iff this cell is an integer cell.
bool is_simple_cell () const
Return true iff this cell is a numeric cor character cell.
virtual bool is_float_cell () const
Return true iff this cell is a floating point cell.
virtual bool is_character_cell () const
Return true iff this cell is a character cell.
virtual bool is_pointer_cell () const
Return true iff this cell is a pointer (to a sub-array) cell.
virtual bool is_lval_cell () const
Return true iff this cell is a pointer to a cell.
virtual bool is_picked_lval_cell () const
Return true iff this cell is a pointer to a cell from pick()
virtual bool is_complex_cell () const
Return true iff this cell is a complex number cell.
virtual bool is_numeric () const
Return true iff this cell is an integer, float, or complex cell.
virtual bool is_real_cell () const
Return true iff this cell is an integer or float cell.
virtual bool is_finite () const
Return true unless this cell contains infinity or NaN.
virtual bool is_example_field () const
Return true iff this cell is an example field character cell.
virtual bool is_member_anchor () const
Return true iff this is a PointerCell which pouints to a member value.
virtual CellType get_cell_type () const
return the type of this cell
virtual CellType get_cell_subtype () const
return the subtype of this cell. The subtype is the set of containers that can store the cell (only for Int and Char cells).
virtual const char * get_classname () const
return the name of the class
virtual ErrorCode bif_ceiling (Cell *Z) const
round the value of this Cell up and store the result in Z
virtual ErrorCode bif_conjugate (Cell *Z) const
conjugate the value of this Cell and store the result in Z
virtual ErrorCode bif_direction (Cell *Z) const
store the direction (sign) of this Cell in Z
virtual ErrorCode bif_exponential (Cell *Z) const
store e to the power of the value of this Cell in Z
virtual ErrorCode bif_factorial (Cell *Z) const
store the factorial (N!) of the value of this Cell in Z
virtual ErrorCode bif_floor (Cell *Z) const
Round the value of this Cell down and store the result in Z.
virtual ErrorCode bif_magnitude (Cell *Z) const
store the absolute value of this Cell in Z
virtual ErrorCode bif_nat_log (Cell *Z) const
store the base e logarithm of the value of this Cell in Z
virtual ErrorCode bif_negative (Cell *Z) const
store the negative of the value of this Cell in Z
virtual ErrorCode bif_not (Cell *Z) const
store the logical complement of the value of this Cell in Z
virtual ErrorCode bif_not_bitwise (Cell *Z) const
store the bitwise complement of the value of this Cell in Z
virtual ErrorCode bif_near_int64_t (Cell *Z) const
store the nearby integer of the value of this Cell in Z
virtual ErrorCode bif_within_quad_CT (Cell *Z) const
store the nearby integer of the value of this Cell in Z
virtual ErrorCode bif_pi_times (Cell *Z) const
store pi times the value of this Cell in Z
virtual ErrorCode bif_pi_times_inverse (Cell *Z) const
store pi times the value of this Cell in Z
virtual ErrorCode bif_reciprocal (Cell *Z) const
store the reciprocal of the value of this Cell in Z
virtual ErrorCode bif_roll (Cell *Z) const
store a random number between 1 and the value of this Cell in Z
virtual ErrorCode bif_add (Cell *Z, const Cell *A) const
store the sum of A and this cell in Z
virtual ErrorCode bif_and (Cell *Z, const Cell *A) const
store the logical and of A and this cell in Z
virtual ErrorCode bif_and_bitwise (Cell *Z, const Cell *A) const
store the bitwise and of A and this cell in Z
virtual ErrorCode bif_binomial (Cell *Z, const Cell *A) const
store the binomial (n over k) of A and this cell in Z
virtual ErrorCode bif_subtract (Cell *Z, const Cell *A) const
store the difference between A and this cell in Z
virtual ErrorCode bif_divide (Cell *Z, const Cell *A) const
store the quotient between A and this cell in Z
virtual Comp_result compare (const Cell &other) const
compare this with other, throw DOMAIN ERROR on illegal comparisons
ErrorCode bif_equal (Cell *Z, const Cell *A) const
store 1 in Z if A == the value of this cell in Z, else 0
virtual ErrorCode bif_equal_bitwise (Cell *Z, const Cell *A) const
bitwise comparison of *this and A
virtual ErrorCode bif_not_equal_bitwise (Cell *Z, const Cell *A) const
bitwise comparison of *this and A
ErrorCode bif_not_equal (Cell *Z, const Cell *A) const
store 1 in Z if A != the value of this cell in Z, else 0
ErrorCode bif_greater_than (Cell *Z, const Cell *A) const
store 1 in Z if A > the value of this cell in Z, else 0
ErrorCode bif_less_eq (Cell *Z, const Cell *A) const
store 1 in Z if A <= the value of this cell in Z, else 0
ErrorCode bif_less_than (Cell *Z, const Cell *A) const
store 1 in Z if A < the value of this cell in Z, else 0
ErrorCode bif_greater_eq (Cell *Z, const Cell *A) const
store 1 in Z if A is >= the value of this cell in Z, else 0
virtual ErrorCode bif_logarithm (Cell *Z, const Cell *A) const
store the base A logarithm of this cell in Z
virtual ErrorCode bif_maximum (Cell *Z, const Cell *A) const
store the larger of A and of this cell in Z
virtual ErrorCode bif_minimum (Cell *Z, const Cell *A) const
store the smaller of A and of this cell in Z
virtual ErrorCode bif_multiply (Cell *Z, const Cell *A) const
store the product of A and this cell in Z
virtual ErrorCode bif_nand (Cell *Z, const Cell *A) const
store the logical nand of A and this cell in Z
virtual ErrorCode bif_nand_bitwise (Cell *Z, const Cell *A) const
store the bitwise nand of A and this cell in Z
virtual ErrorCode bif_nor (Cell *Z, const Cell *A) const
store the logical NOR of A and this cell in Z
virtual ErrorCode bif_nor_bitwise (Cell *Z, const Cell *A) const
store the bitwise NOR of A and this cell in Z
virtual ErrorCode bif_or (Cell *Z, const Cell *A) const
store the logical OR of A and this cell in Z
virtual ErrorCode bif_or_bitwise (Cell *Z, const Cell *A) const
store the bitwise or of A and this cell in Z
virtual ErrorCode bif_power (Cell *Z, const Cell *A) const
store A to the power of this cell in Z
virtual ErrorCode bif_residue (Cell *Z, const Cell *A) const
store A modulo this cell in Z
virtual ErrorCode bif_circle_fun (Cell *Z, const Cell *A) const
store a circle function (according to A) of this cell in Z
virtual ErrorCode bif_circle_fun_inverse (Cell *Z, const Cell *A) const
store a circle function (according to A) of this cell in Z
virtual ErrorCode bif_add_inverse (Cell *Z, const Cell *A) const
the inverse of bif_add
virtual ErrorCode bif_multiply_inverse (Cell *Z, const Cell *A) const
the inverse of bif_bif_multiply
void * operator new (std::size_t, void *)
placement new
const void * get_u0 () const
raw pointer to the primary value (for 27 ⎕CR)
const void * get_u1 () const
raw pointer to the secondary value (for 28 ⎕CR)
Protected Attributes inherited from Cell
SomeValue value
the primary value of this cell
Detailed Description
Base class for RealCell and ComplexCell.
A cell that is either an integer cell, a floating point cell, or a complex number cell. This class contains all cell functions for which the detailed type makes no difference.
Definition at line 32 of file NumericCell.hh.
Member Function Documentation
bif_and()
ErrorCode NumericCell::bif_and (Cell * Z, const Cell * A) const protected virtual
overloaded Cell::bif_and()
Reimplemented from Cell.
Definition at line 1412 of file NumericCell.cc.
References cpx_gcd(), flt_gcd(), Cell::get_checked_near_int(), Cell::get_complex_value(), Workspace::get_CT(), Cell::get_real_value(), int_gcd(), Cell::is_complex_cell(), Cell::is_near_int(), Cell::is_near_one(), Cell::is_near_real(), Cell::is_near_zero(), IntCell::z0(), IntCell::z1(), ComplexCell::zC(), FloatCell::zF(), and IntCell::zI().
bif_and_bitwise()
ErrorCode NumericCell::bif_and_bitwise (Cell * Z, const Cell * A) const protected virtual
overloaded Cell::bif_and_bitwise()
Reimplemented from Cell.
Definition at line 1476 of file NumericCell.cc.
References Cell::get_near_int(), Cell::is_near_int64_t(), and IntCell::zI().
bif_binomial()
ErrorCode NumericCell::bif_binomial (Cell * Z, const Cell * A) const protected virtual
overloaded Cell::bif_binomial()
Reimplemented from Cell.
Definition at line 1271 of file NumericCell.cc.
References complex_binomial(), Cell::get_checked_near_int(), Cell::get_real_value(), Cell::is_near_int(), Cell::is_near_real(), K33_binomial(), real_binomial(), and IntCell::z0().
bif_equal_bitwise()
ErrorCode NumericCell::bif_equal_bitwise (Cell * Z, const Cell * A) const protected virtual
overloaded Cell::bif_equal_bitwise()
Reimplemented from Cell.
Definition at line 1485 of file NumericCell.cc.
References Cell::get_near_int(), Cell::is_near_int64_t(), and IntCell::zI().
bif_nand()
ErrorCode NumericCell::bif_nand (Cell * Z, const Cell * A) const protected virtual
overloaded Cell::bif_nand()
Reimplemented from Cell.
Definition at line 1503 of file NumericCell.cc.
References Cell::get_near_bool(), Cell::is_near_bool(), IntCell::z0(), and IntCell::z1().
bif_nand_bitwise()
ErrorCode NumericCell::bif_nand_bitwise (Cell * Z, const Cell * A) const protected virtual
overloaded Cell::bif_nand_bitwise()
Reimplemented from Cell.
Definition at line 1513 of file NumericCell.cc.
References Cell::get_near_int(), Cell::is_near_int64_t(), and IntCell::zI().
bif_nor()
ErrorCode NumericCell::bif_nor (Cell * Z, const Cell * A) const protected virtual
overloaded Cell::bif_nor()
Reimplemented from Cell.
Definition at line 1522 of file NumericCell.cc.
References Cell::get_near_bool(), Cell::is_near_bool(), IntCell::z0(), and IntCell::z1().
bif_nor_bitwise()
ErrorCode NumericCell::bif_nor_bitwise (Cell * Z, const Cell * A) const protected virtual
overloaded Cell::bif_nor_bitwise()
Reimplemented from Cell.
Definition at line 1532 of file NumericCell.cc.
References Cell::get_near_int(), Cell::is_near_int64_t(), and IntCell::zI().
bif_not()
ErrorCode NumericCell::bif_not (Cell * Z) const protected virtual
overloaded Cell::bif_not()
Reimplemented from Cell.
Definition at line 34 of file NumericCell.cc.
References Cell::get_near_bool(), Cell::is_near_bool(), IntCell::z0(), and IntCell::z1().
bif_not_bitwise()
ErrorCode NumericCell::bif_not_bitwise (Cell * Z) const protected virtual
overloaded Cell::bif_not_bitwise()
Reimplemented from Cell.
Definition at line 44 of file NumericCell.cc.
References Cell::get_near_int(), Cell::is_near_int64_t(), and IntCell::zI().
bif_not_equal_bitwise()
ErrorCode NumericCell::bif_not_equal_bitwise (Cell * Z, const Cell * A) const protected virtual
overloaded Cell::bif_not_equal_bitwise()
Reimplemented from Cell.
Definition at line 1494 of file NumericCell.cc.
References Cell::get_near_int(), Cell::is_near_int64_t(), and IntCell::zI().
bif_or()
ErrorCode NumericCell::bif_or (Cell * Z, const Cell * A) const protected virtual
overloaded Cell::bif_or()
Reimplemented from Cell.
Definition at line 1541 of file NumericCell.cc.
References cpx_gcd(), flt_gcd(), Cell::get_checked_near_int(), Cell::get_complex_value(), Workspace::get_CT(), Cell::get_near_bool(), Cell::get_real_value(), int_gcd(), Cell::is_near_bool(), Cell::is_near_int(), Cell::is_near_real(), Cell::is_near_zero(), IntCell::z0(), IntCell::z1(), ComplexCell::zC(), FloatCell::zF(), and IntCell::zI().
bif_or_bitwise()
ErrorCode NumericCell::bif_or_bitwise (Cell * Z, const Cell * A) const protected virtual
overloaded Cell::bif_or_bitwise()
Reimplemented from Cell.
Definition at line 1601 of file NumericCell.cc.
References Cell::get_near_int(), Cell::is_near_int64_t(), and IntCell::zI().
complex_binomial()
ErrorCode NumericCell::complex_binomial (Cell * Z, const Cell * A) const protected
N over K for complex A and/or B.
Definition at line 1326 of file NumericCell.cc.
References ComplexCell::gamma(), Cell::get_imag_value(), Cell::get_real_value(), and ComplexCell::zC().
Referenced by bif_binomial().
cpx_gcd()
ErrorCode NumericCell::cpx_gcd (APL_Complex & z, APL_Complex a, APL_Complex b, double qct) static protected
return the greatest common divisor of complex a and b
Definition at line 1667 of file NumericCell.cc.
References flt_gcd(), Cell::is_near_int(), and Cell::is_near_zero().
Referenced by bif_and(), and bif_or().
cpx_max_real()
APL_Complex NumericCell::cpx_max_real (APL_Complex a) static protected
multiply a by 1, -1, i, or -i so that a.real is maximal
Definition at line 1611 of file NumericCell.cc.
flt_gcd()
ErrorCode NumericCell::flt_gcd (APL_Float & z, APL_Float a, APL_Float b, double qct) static protected
return the greatest common divisor of real a and b
Definition at line 1644 of file NumericCell.cc.
References Cell::is_near_zero().
Referenced by bif_and(), bif_or(), and cpx_gcd().
get_classname()
virtual const char * NumericCell::get_classname () const inline protected virtual
overloaded Cell::get_classname()
Reimplemented from Cell.
Reimplemented in ComplexCell, FloatCell, IntCell, and RealCell.
Definition at line 96 of file NumericCell.hh.
int_gcd()
ErrorCode NumericCell::int_gcd (APL_Integer & z, APL_Integer a, APL_Integer b) static protected
return the greatest common divisor of integers a and b
Definition at line 1635 of file NumericCell.cc.
References FloatCell::gcd().
Referenced by bif_and(), and bif_or().
integer_binomial()
ErrorCode NumericCell::integer_binomial (Cell * Z, APL_Integer N, APL_Integer K, bool negate) static protected
N over K for positive integers N and K.
Definition at line 1370 of file NumericCell.cc.
References Cell::is_near_int64_t(), Cell::near_int(), IntCell::z0(), FloatCell::zF(), and IntCell::zI().
Referenced by K33_binomial().
is_numeric()
virtual bool NumericCell::is_numeric () const inline protected virtual
overloaded Cell::is_numeric()
Reimplemented from Cell.
Definition at line 49 of file NumericCell.hh.
K33_binomial()
ErrorCode NumericCell::K33_binomial (Cell * Z, APL_Integer N, APL_Integer K, bool negate) static protected
compute binomial funtion for integers a and b
Definition at line 1175 of file NumericCell.cc.
References integer_binomial(), and IntCell::zI().
Referenced by bif_binomial().
real_binomial()
ErrorCode NumericCell::real_binomial (Cell * Z, const Cell * A) const protected
N over K for non-integer A and/or B.
Definition at line 1344 of file NumericCell.cc.
References Cell::get_real_value(), Cell::is_near_int(), and FloatCell::zF().
Referenced by bif_binomial().
The documentation for this class was generated from the following files:
src/NumericCell.hh
src/NumericCell.cc