GNU APL: SystemName Class Reference
SystemName Class Reference
a distinguished name (i.e. ⎕xx)
#include <SymbolTable.hh>
Public Member Functions
SystemName (const UCS_string &var_name, Id var_id, QuadFunction *fun, SystemVariable *var)
constructor: system variable or function
UCS_string get_name () const
return the distinguished name
bool is_erased () const
system variables are never erased
bool equal (const UCS_string &ucs) const
Compare the name of this Symbol with ucs.
SystemVariable * get_variable () const
return the variable (if any) that this name represents
QuadFunction * get_function () const
return the function (if any) that this name represents
Id get_id () const
return the ID of this name
Public Attributes
SystemName * next
The next name with the same hash value as this SystemName.
Protected Attributes
const UCS_string name
the name (including ⎕). Eg. ⎕IO
const Id id
the Id of the variable or function
QuadFunction * function
the function if the name refers to a system function, or 0 if not
SystemVariable * sysvar
the variable if the name refers to a system variable, or 0 if not
Detailed Description
a distinguished name (i.e. ⎕xx)
Definition at line 177 of file SymbolTable.hh.
Constructor & Destructor Documentation
SystemName()
SystemName::SystemName (const UCS_string & var_name, Id var_id, QuadFunction * fun, SystemVariable * var) inline
constructor: system variable or function
Definition at line 181 of file SymbolTable.hh.
Member Function Documentation
equal()
bool SystemName::equal (const UCS_string & ucs) const inline
Compare the name of this Symbol with ucs.
Definition at line 197 of file SymbolTable.hh.
References UCS_string::compare(), and name.
get_function()
QuadFunction * SystemName::get_function () const inline
return the function (if any) that this name represents
Definition at line 205 of file SymbolTable.hh.
References function.
Referenced by Workspace::get_quad().
get_id()
Id SystemName::get_id () const inline
return the ID of this name
Definition at line 209 of file SymbolTable.hh.
References id.
get_name()
UCS_string SystemName::get_name () const inline
return the distinguished name
Definition at line 190 of file SymbolTable.hh.
References name.
get_variable()
SystemVariable * SystemName::get_variable () const inline
return the variable (if any) that this name represents
Definition at line 201 of file SymbolTable.hh.
References sysvar.
Referenced by Workspace::get_quad().
is_erased()
bool SystemName::is_erased () const inline
system variables are never erased
Definition at line 194 of file SymbolTable.hh.
Member Data Documentation
function
QuadFunction* SystemName::function protected
the function if the name refers to a system function, or 0 if not
Definition at line 223 of file SymbolTable.hh.
Referenced by get_function().
id
const Id SystemName::id protected
the Id of the variable or function
Definition at line 220 of file SymbolTable.hh.
Referenced by get_id().
name
const UCS_string SystemName::name protected
the name (including ⎕). Eg. ⎕IO
Definition at line 217 of file SymbolTable.hh.
Referenced by equal(), and get_name().
next
SystemName* SystemName::next
The next name with the same hash value as this SystemName.
Definition at line 213 of file SymbolTable.hh.
Referenced by SystemSymTab::clear_slot().
sysvar
SystemVariable* SystemName::sysvar protected
the variable if the name refers to a system variable, or 0 if not
Definition at line 226 of file SymbolTable.hh.
Referenced by get_variable().
The documentation for this class was generated from the following file:
src/SymbolTable.hh