GNU APL: Nabla Class Reference
Nabla Class Reference
The Nabla editor.
#include <Nabla.hh>
Classes
struct FunLine
a line label and program text, e.g. [1.1] TEXT←TEXT
Public Member Functions
UCS_string get_label_and_text (int line, bool &is_current) const
return the line label (sucah as [1]) and the line text, Set is_current iff line is the current line of the editor.
int get_line_count () const
return the number of lines
Static Public Member Functions
static void edit_function (const UCS_string &cmd)
edit the function specified in cmd (e.g. cmd = "∇FUN")
Protected Types
enum Ecmd {
ECMD_NOP ,
ECMD_SHOW ,
ECMD_EDIT ,
ECMD_DELETE ,
ECMD_ESCAPE
}
editor commands
Protected Member Functions
Nabla (const UCS_string &cmd)
constructor
void throw_edit_error (const char *loc)
throw a DEFN error with some additional information
void edit ()
edit this function
const char * start ()
start editing, return source location if first_command is bad.
const char * parse_oper (UCS_string &oper, bool initial)
parse an operation (something like [...], e.g. [⎕3])
const char * execute_oper ()
execute an edit operation
const char * execute_show ()
show function
const char * execute_delete ()
delete function
const char * execute_edit ()
edit function line
const char * edit_header_line ()
edit function header
const char * edit_body_line ()
edit body line
const char * execute_escape ()
restore function
const char * open_new_function ()
create a new function.
const char * open_existing_function ()
open an existing function, or create a new one.
LineLabel parse_lineno (UCS_string::iterator &c)
parse [nn.mm] into a LineLabel;
int find_line (const LineLabel &lab) const
return index of line with label lab, or -1 if not found.
bool line_exists (const LineLabel &lab) const
true if line with label lab exists
Protected Attributes
const int defn_line_no
the line number (in a .apl script file) of the ∇ that started the editor
UCS_string fun_header
the header of the function being edited
Symbol * fun_symbol
the symbol for the function being edited
vector< FunLine > lines
the lines of the function.
Ecmd ecmd
the current editor command
LineLabel edit_from
optional start of a range for an editor command
LineLabel edit_to
optional end of a range for an editor command
bool got_minus
true if user has entered a range, i.e. edit_from - edit_to, - edit_to, edit_from -
bool function_existed
true iff this function existed before opening it
bool modified
true if the function was modified
bool do_close
true iff this function shall be closed
bool locked
true iff this function shall be locked
LineLabel current_line
the line number for the currently edited line
const UCS_string first_command
the command used to open the function
UCS_string current_text
the text for line current_line
Detailed Description
The Nabla editor.
Definition at line 80 of file Nabla.hh.
Member Enumeration Documentation
Ecmd
enum Nabla::Ecmd protected
editor commands
Enumerator
ECMD_NOP
do nothing
ECMD_SHOW
show function line(s) idx_from ... idx_to
ECMD_EDIT
edit function line edit_from
ECMD_DELETE
delete function line(s) edit_from ... idx_to
ECMD_ESCAPE
abort editing (discard changes made so far)
Definition at line 196 of file Nabla.hh.
Constructor & Destructor Documentation
Nabla()
Nabla::Nabla (const UCS_string & cmd) protected
constructor
Definition at line 43 of file Nabla.cc.
References Workspace::more_error().
Member Function Documentation
edit()
void Nabla::edit () protected
edit this function
Definition at line 76 of file Nabla.cc.
References LineInput::add_history_line(), UCS_string::append(), UCS_string::append_number(), UCS_string::append_UTF8(), UTF8_string::c_str(), Command::cmd_OFF(), Output::COLM_INPUT, InputFile::current_filename(), current_line, defn_line_no, do_close, execute_oper(), first_command, UserFunction::fix(), fun_header, StateIndicator::get_line(), lines, locked, modified, Workspace::more_error(), UserPreferences::nabla_to_history, parse_oper(), LineLabel::print_prompt(), UserPreferences::raw_cin, UCS_string::remove_trailing_whitespaces(), LineInput::replace_history_line(), InputFile::running_script(), Output::set_color_mode(), UserFunction::set_exec_properties(), UserFunction::set_trace_stop(), UCS_string::size(), start(), and throw_edit_error().
edit_body_line()
const char * Nabla::edit_body_line () protected
edit body line
Definition at line 854 of file Nabla.cc.
References current_line, current_text, UserPreferences::discard_indentation, edit_from, find_line(), lines, modified, Workspace::more_error(), UserPreferences::multi_line_strings, LineLabel::next(), and UCS_string::remove_leading_and_trailing_whitespaces().
Referenced by execute_edit().
edit_function()
void Nabla::edit_function (const UCS_string & cmd) static
edit the function specified in cmd (e.g. cmd = "∇FUN")
Definition at line 37 of file Nabla.cc.
Referenced by Command::process_line().
edit_header_line()
const char * Nabla::edit_header_line () protected
edit function header
Definition at line 810 of file Nabla.cc.
References current_line, current_text, fun_symbol, UserFunction_header::get_error(), Symbol::get_name(), UserFunction_header::get_name(), NamedObject::get_NC(), lines, Workspace::lookup_symbol(), modified, and LineLabel::next().
Referenced by execute_edit().
execute_delete()
const char * Nabla::execute_delete () protected
delete function
Definition at line 764 of file Nabla.cc.
References current_line, edit_from, edit_to, find_line(), lines, and modified.
Referenced by execute_oper().
execute_edit()
const char * Nabla::execute_edit () protected
edit function line
Definition at line 791 of file Nabla.cc.
References current_line, current_text, edit_body_line(), edit_from, edit_header_line(), LineLabel::is_header_line_number(), LineLabel::ln_major, and UCS_string::size().
Referenced by execute_oper().
execute_escape()
const char * Nabla::execute_escape () protected
restore function
Definition at line 912 of file Nabla.cc.
References fun_header, fun_symbol, Function::get_func_ufun(), Symbol::get_function(), Executable::get_text(), Executable::get_text_size(), and lines.
Referenced by execute_oper().
execute_oper()
const char * Nabla::execute_oper () protected
execute an edit operation
Definition at line 682 of file Nabla.cc.
References ecmd, ECMD_DELETE, ECMD_EDIT, ECMD_ESCAPE, ECMD_NOP, ECMD_SHOW, edit_from, edit_to, execute_delete(), execute_edit(), execute_escape(), execute_show(), lines, and LineLabel::ln_major.
Referenced by edit(), and start().
execute_show()
const char * Nabla::execute_show () protected
show function
Definition at line 713 of file Nabla.cc.
References current_line, edit_from, edit_to, find_line(), LineLabel::insert(), line_exists(), lines, LineLabel::next(), and LineLabel::valid().
Referenced by execute_oper().
find_line()
int Nabla::find_line (const LineLabel & lab) const protected
return index of line with label lab, or -1 if not found.
Definition at line 937 of file Nabla.cc.
References lines, and LineLabel::ln_major.
Referenced by edit_body_line(), execute_delete(), execute_show(), and line_exists().
get_label_and_text()
UCS_string Nabla::get_label_and_text (int line, bool & is_current) const
return the line label (sucah as [1]) and the line text, Set is_current iff line is the current line of the editor.
Definition at line 1042 of file Nabla.cc.
References current_line, Nabla::FunLine::get_label_and_text(), Nabla::FunLine::label, and lines.
get_line_count()
int Nabla::get_line_count () const inline
return the number of lines
Definition at line 91 of file Nabla.hh.
References lines.
line_exists()
bool Nabla::line_exists (const LineLabel & lab) const inline protected
true if line with label lab exists
Definition at line 180 of file Nabla.hh.
References find_line().
Referenced by execute_show().
open_existing_function()
const char * Nabla::open_existing_function () protected
open an existing function, or create a new one.
Definition at line 609 of file Nabla.cc.
References Symbol::cant_be_defined(), current_line, fun_header, fun_symbol, Symbol::get_function(), Symbol::get_name(), UserFunction::get_stop_lines(), UserFunction::get_trace_lines(), Workspace::is_called(), lines, InputFile::running_script(), Nabla::FunLine::stop_flag, UCS_string::to_vector(), and Nabla::FunLine::trace_flag.
Referenced by start().
open_new_function()
const char * Nabla::open_new_function () protected
create a new function.
Definition at line 598 of file Nabla.cc.
References fun_header, fun_symbol, Symbol::get_name(), and lines.
Referenced by start().
parse_lineno()
LineLabel Nabla::parse_lineno (UCS_string::iterator & c) protected
parse [nn.mm] into a LineLabel;
Definition at line 578 of file Nabla.cc.
References UCS_string::append(), Avec::is_digit(), LineLabel::ln_major, and LineLabel::ln_minor.
Referenced by parse_oper().
parse_oper()
const char * Nabla::parse_oper (UCS_string & oper, bool initial) protected
parse an operation (something like [...], e.g. [⎕3])
Definition at line 379 of file Nabla.cc.
References UCS_string::append(), UCS_string::back(), UCS_string::begin(), LineLabel::clear(), current_line, current_text, do_close, ecmd, ECMD_DELETE, ECMD_EDIT, ECMD_ESCAPE, ECMD_NOP, ECMD_SHOW, edit_from, edit_to, got_minus, Avec::is_digit(), Avec::is_white(), locked, parse_lineno(), UCS_string::pop_back(), and UCS_string::size().
Referenced by edit(), and start().
start()
const char * Nabla::start () protected
start editing, return source location if first_command is bad.
Definition at line 234 of file Nabla.cc.
References UCS_string::append(), UCS_string::begin(), do_close, ecmd, ECMD_NOP, ECMD_SHOW, execute_oper(), first_command, fun_header, fun_symbol, function_existed, UserFunction_header::get_error(), UserFunction_header::get_error_info(), UserFunction_header::get_name(), NamedObject::get_NC(), UserFunction_header::has_vars(), Avec::is_first_symbol_char(), Avec::is_white(), Workspace::lookup_symbol(), modified, open_existing_function(), open_new_function(), parse_oper(), InputFile::running_script(), and UCS_string::size().
Referenced by edit().
throw_edit_error()
void Nabla::throw_edit_error (const char * loc) protected
throw a DEFN error with some additional information
Definition at line 60 of file Nabla.cc.
References first_command, fun_header, Workspace::more_error(), UCS_string::size(), and Error::throw_define_error().
Referenced by edit().
Member Data Documentation
current_line
LineLabel Nabla::current_line protected
the line number for the currently edited line
Definition at line 231 of file Nabla.hh.
Referenced by edit(), edit_body_line(), edit_header_line(), execute_delete(), execute_edit(), execute_show(), get_label_and_text(), open_existing_function(), and parse_oper().
current_text
UCS_string Nabla::current_text protected
the text for line current_line
Definition at line 237 of file Nabla.hh.
Referenced by edit_body_line(), edit_header_line(), execute_edit(), and parse_oper().
defn_line_no
const int Nabla::defn_line_no protected
the line number (in a .apl script file) of the ∇ that started the editor
Definition at line 184 of file Nabla.hh.
Referenced by edit().
do_close
bool Nabla::do_close protected
true iff this function shall be closed
Definition at line 225 of file Nabla.hh.
Referenced by edit(), parse_oper(), and start().
ecmd
Ecmd Nabla::ecmd protected
the current editor command
Definition at line 206 of file Nabla.hh.
Referenced by execute_oper(), parse_oper(), and start().
edit_from
LineLabel Nabla::edit_from protected
optional start of a range for an editor command
Definition at line 209 of file Nabla.hh.
Referenced by edit_body_line(), execute_delete(), execute_edit(), execute_oper(), execute_show(), and parse_oper().
edit_to
LineLabel Nabla::edit_to protected
optional end of a range for an editor command
Definition at line 212 of file Nabla.hh.
Referenced by execute_delete(), execute_oper(), execute_show(), and parse_oper().
first_command
const UCS_string Nabla::first_command protected
the command used to open the function
Definition at line 234 of file Nabla.hh.
Referenced by edit(), start(), and throw_edit_error().
fun_header
UCS_string Nabla::fun_header protected
the header of the function being edited
Definition at line 187 of file Nabla.hh.
Referenced by edit(), execute_escape(), open_existing_function(), open_new_function(), start(), and throw_edit_error().
fun_symbol
Symbol* Nabla::fun_symbol protected
the symbol for the function being edited
Definition at line 190 of file Nabla.hh.
Referenced by edit_header_line(), execute_escape(), open_existing_function(), open_new_function(), and start().
function_existed
bool Nabla::function_existed protected
true iff this function existed before opening it
Definition at line 219 of file Nabla.hh.
Referenced by start().
got_minus
bool Nabla::got_minus protected
true if user has entered a range, i.e. edit_from - edit_to, - edit_to, edit_from -
Definition at line 216 of file Nabla.hh.
Referenced by parse_oper().
lines
vector<FunLine> Nabla::lines protected
the lines of the function.
Definition at line 193 of file Nabla.hh.
Referenced by edit(), edit_body_line(), edit_header_line(), execute_delete(), execute_escape(), execute_oper(), execute_show(), find_line(), get_label_and_text(), get_line_count(), open_existing_function(), and open_new_function().
locked
bool Nabla::locked protected
true iff this function shall be locked
Definition at line 228 of file Nabla.hh.
Referenced by edit(), and parse_oper().
modified
bool Nabla::modified protected
true if the function was modified
Definition at line 222 of file Nabla.hh.
Referenced by edit(), edit_body_line(), edit_header_line(), execute_delete(), and start().
The documentation for this class was generated from the following files:
src/Nabla.hh
src/Nabla.cc