GNU APL: PrintBuffer Class Reference
PrintBuffer Class Reference
A two-dimensional Unicode character buffer.
#include <PrintBuffer.hh>
Public Member Functions
PrintBuffer ()
contructor: empty PrintBuffer
PrintBuffer (const UCS_string &ucs, const ColInfo &ci)
contructor: a single row PrintBuffer
PrintBuffer (const Value &value, const PrintContext &pctx, ostream *out)
contructor: a PrintBuffer from an APL value
void do_PrintBuffer (const Value &value, const PrintContext &pctx, ostream *out, PrintStyle outer_style, std::vector< bool > &scaling, std::vector< PrintBuffer > &pcols, PrintBuffer *item_matrix)
helper for non-trivial PrintBuffer(const Value & ...) constructor
void pb_for_function (const Value &value, PrintContext pctx, PrintStyle outer_style)
PrintBuffer from an APL value in function-style.
void pb_empty (const Value &value, PrintContext pctx, PrintStyle outer_style)
PrintBuffer from an empty APL value.
int get_row_count () const
return the number of rows
UCS_string l1 () const
return the first (and only) line
UCS_string get_line (int y) const
return line y
void print_interruptible (ostream &out, sRank rank, int quad_pw)
print this buffer, interruptible with ^C
int get_column_count () const
return the number of columns
int get_column_count (int y) const
return the number of columns in row y
void set_char (int x, int y, Unicode uc)
Set the char in column x and row y to uc.
Unicode get_char (int x, int y) const
Return the char in column x and row y.
void pad_l (Unicode pad, ShapeItem count)
prepend buffer with count characters pad
void pad_r (Unicode pad, ShapeItem count)
append count charactera pad to buffer
void pad_height (Unicode pad, ShapeItem height)
append lines to reach height
void pad_height_above (Unicode pad, ShapeItem height)
prepend lines to reach height
void pad_to_spaces ()
replace pad chars by spaces
void add_frame (PrintStyle style, const Shape &shape, int depth)
add a decorator frame around this buffer
void add_outer_frame (PrintStyle style)
add an outer frame around this buffer
ostream & debug (ostream &out, const char *title=0) const
print properties of this PrintBuffer
void append_col (const PrintBuffer &pb1)
append PrintBuffer pb1 to this PrintBuffer
void append_ucs (const UCS_string &ucs)
append UCS_string ucs to this PrintBuffer
void append_aligned (const UCS_string &ucs, Unicode align)
append ucs, aligned at char align.
void add_column (Unicode pad, int32_t pad_count, const PrintBuffer &pb)
add padding and a column pb to this PrintBuffer
void add_row (const PrintBuffer &row)
add PrintBuffer row to this PrintBuffer
void add_empty_rows (ShapeItem count)
add empty rows to this PrintBuffer
const ColInfo & get_info () const
return the ColInfo of this PrintBuffer
void update_info ()
update col_info after a change of buffer
ColInfo & get_info ()
return the ColInfo of this PrintBuffer
bool is_rectangular () const
return true iff all strings have the same size.
Static Public Member Functions
static void get_frame_chars (PrintStyle pst, Unicode &HORI, Unicode &VERT, Unicode &NW, Unicode &NE, Unicode &SE, Unicode &SW)
return the characters for style pst
Protected Member Functions
void align (ColInfo &col)
align this PrintBuffer to col
void align_left (ColInfo &col)
align this char-only PrintBuffer to col
void align_dot (ColInfo &col)
align this real-only PrintBuffer to col
void align_j (ColInfo &col)
align this complex PrintBuffer to col
void pad_fraction (int wanted_fract_len, bool want_expo)
pad the fraction part to wanted_fract_len with '0'
Static Protected Member Functions
static ShapeItem separator_rows (ShapeItem y, const Value &value, bool nested, sRank rk1, sRank rk2)
return the number of separator rows before row y in a value with shape shape
Protected Attributes
UCS_string_vector buffer
the character buffer.
ColInfo col_info
column properties
bool complete
true if completely constructed (as opposed to interrupted by ^C)
Detailed Description
A two-dimensional Unicode character buffer.
Definition at line 86 of file PrintBuffer.hh.
Constructor & Destructor Documentation
PrintBuffer() [1/3]
PrintBuffer::PrintBuffer ()
contructor: empty PrintBuffer
Definition at line 43 of file PrintBuffer.cc.
Referenced by do_PrintBuffer(), pb_empty(), pb_for_function(), and PrintBuffer().
PrintBuffer() [2/3]
PrintBuffer::PrintBuffer (const UCS_string & ucs, const ColInfo & ci)
contructor: a single row PrintBuffer
Definition at line 48 of file PrintBuffer.cc.
References buffer.
PrintBuffer() [3/3]
PrintBuffer::PrintBuffer (const Value & value, const PrintContext & pctx, ostream * out)
contructor: a PrintBuffer from an APL value
Definition at line 55 of file PrintBuffer.cc.
References add_outer_frame(), UCS_string::append(), append_ucs(), Cell::character_representation(), complete, do_PrintBuffer(), PrintContext::get_PW(), PrintContext::get_style(), Cell::need_scaling(), pad_l(), pad_r(), pb_empty(), pb_for_function(), PrintBuffer(), PrintContext::set_scaled(), UCS_string::size(), and update_info().
Member Function Documentation
add_column()
void PrintBuffer::add_column (Unicode pad, int32_t pad_count, const PrintBuffer & pb)
add padding and a column pb to this PrintBuffer
Definition at line 1079 of file PrintBuffer.cc.
References buffer, debug(), and get_row_count().
Referenced by Quad_CR::do_CR31_32().
add_empty_rows()
void PrintBuffer::add_empty_rows (ShapeItem count) inline
add empty rows to this PrintBuffer
Definition at line 183 of file PrintBuffer.hh.
References buffer.
add_frame()
void PrintBuffer::add_frame (PrintStyle style, const Shape & shape, int depth)
add a decorator frame around this buffer
Definition at line 744 of file PrintBuffer.cc.
References UCS_string::append(), UCS_string::append_number(), buffer, get_column_count(), get_frame_chars(), Shape::get_last_shape_item(), Shape::get_rank(), get_row_count(), Shape::get_shape_item(), UCS_string_vector::insert(), is_rectangular(), set_char(), and UCS_string::size().
Referenced by PointerCell::character_representation().
add_outer_frame()
void PrintBuffer::add_outer_frame (PrintStyle style)
add an outer frame around this buffer
Definition at line 851 of file PrintBuffer.cc.
References UCS_string::append(), buffer, get_column_count(), get_frame_chars(), get_row_count(), UCS_string_vector::insert(), is_rectangular(), and set_char().
Referenced by do_PrintBuffer(), pb_empty(), pb_for_function(), and PrintBuffer().
add_row()
void PrintBuffer::add_row (const PrintBuffer & row)
add PrintBuffer row to this PrintBuffer
Definition at line 1098 of file PrintBuffer.cc.
References buffer, and get_row_count().
Referenced by do_PrintBuffer().
align()
void PrintBuffer::align (ColInfo & col) protected
align this PrintBuffer to col
Definition at line 1105 of file PrintBuffer.cc.
References align_dot(), align_j(), align_left(), ColInfo::flags, and is_rectangular().
Referenced by append_aligned(), and do_PrintBuffer().
align_dot()
void PrintBuffer::align_dot (ColInfo & col) protected
align this real-only PrintBuffer to col
Definition at line 1126 of file PrintBuffer.cc.
References buffer, col_info, debug(), ColInfo::denom_len, ColInfo::flags, ColInfo::fract_len, ColInfo::have_expo(), ColInfo::int_len, pad_fraction(), pad_l(), pad_r(), ColInfo::real_len, and ColInfo::total_len().
Referenced by align().
align_j()
void PrintBuffer::align_j (ColInfo & col) protected
align this complex PrintBuffer to col
Definition at line 1227 of file PrintBuffer.cc.
References buffer, col_info, debug(), ColInfo::flags, ColInfo::fract_len, ColInfo::imag_len, ColInfo::int_len, pad_l(), pad_r(), and ColInfo::real_len.
Referenced by align().
align_left()
void PrintBuffer::align_left (ColInfo & col) protected
align this char-only PrintBuffer to col
Definition at line 1337 of file PrintBuffer.cc.
References buffer, col_info, debug(), ColInfo::fract_len, ColInfo::int_len, pad_r(), and ColInfo::real_len.
Referenced by align().
append_aligned()
void PrintBuffer::append_aligned (const UCS_string & ucs, Unicode align)
append ucs, aligned at char align.
Definition at line 976 of file PrintBuffer.cc.
References align(), UCS_string::append(), buffer, get_column_count(), is_rectangular(), pad_l(), pad_r(), and UCS_string::size().
Referenced by Bif_F12_FORMAT::add_row().
append_col()
void PrintBuffer::append_col (const PrintBuffer & pb1)
append PrintBuffer pb1 to this PrintBuffer
Definition at line 942 of file PrintBuffer.cc.
References buffer, and get_row_count().
Referenced by Bif_F12_FORMAT::format_by_specification().
append_ucs()
void PrintBuffer::append_ucs (const UCS_string & ucs)
append UCS_string ucs to this PrintBuffer
Definition at line 950 of file PrintBuffer.cc.
References UCS_string::append(), buffer, get_column_count(), get_row_count(), and UCS_string::size().
Referenced by Bif_F12_FORMAT::add_row(), do_PrintBuffer(), Quad_EC::eoc(), Bif_F12_FORMAT::format_one_col_by_spec(), Quad_EM::get_apl_value(), pb_empty(), and PrintBuffer().
debug()
ostream & PrintBuffer::debug (ostream & out, const char * title = 0) const
print properties of this PrintBuffer
Definition at line 906 of file PrintBuffer.cc.
References buffer, col_info, ColInfo::denom_len, ColInfo::flags, ColInfo::fract_len, get_column_count(), get_row_count(), ColInfo::int_len, and ColInfo::real_len.
Referenced by add_column(), align_dot(), align_j(), align_left(), and Value::debug().
do_PrintBuffer()
void PrintBuffer::do_PrintBuffer (const Value & value, const PrintContext & pctx, ostream * out, PrintStyle outer_style, std::vector< bool > & scaling, std::vector< PrintBuffer > & pcols, PrintBuffer * item_matrix)
helper for non-trivial PrintBuffer(const Value & ...) constructor
Definition at line 177 of file PrintBuffer.cc.
References add_outer_frame(), add_row(), align(), append_ucs(), buffer, Cell::character_representation(), complete, ColInfo::consider(), ColInfo::denom_len, get_column_count(), get_info(), get_line(), Cell::get_pointer_value(), PrintContext::get_PW(), get_row_count(), ColInfo::int_len, Cell::is_pointer_cell(), is_rectangular(), pad_height(), pad_l(), pad_r(), print_interruptible(), PrintBuffer(), ColInfo::real_len, separator_rows(), PrintContext::set_scaled(), UCS_string::size(), and update_info().
Referenced by PrintBuffer().
get_char()
Unicode PrintBuffer::get_char (int x, int y) const
Return the char in column x and row y.
Definition at line 624 of file PrintBuffer.cc.
References buffer.
Referenced by Bif_F12_FORMAT::format_by_specification(), Bif_F12_FORMAT::monadic_format(), pad_to_spaces(), and Value::Value().
get_column_count() [1/2]
int PrintBuffer::get_column_count () const inline
return the number of columns
Definition at line 129 of file PrintBuffer.hh.
References get_column_count().
Referenced by add_frame(), add_outer_frame(), Bif_F12_FORMAT::add_row(), append_aligned(), append_ucs(), PointerCell::character_representation(), debug(), do_PrintBuffer(), Bif_F12_FORMAT::eval_B(), Bif_F12_FORMAT::format_by_specification(), Bif_F12_FORMAT::format_one_col_by_spec(), get_column_count(), is_rectangular(), Bif_F12_FORMAT::monadic_format(), pad_fraction(), pad_height(), pad_height_above(), pad_to_spaces(), print_interruptible(), UCS_string::UCS_string(), and Value::Value().
get_column_count() [2/2]
int PrintBuffer::get_column_count (int y) const inline
return the number of columns in row y
Definition at line 133 of file PrintBuffer.hh.
References buffer, and get_row_count().
get_frame_chars()
void PrintBuffer::get_frame_chars (PrintStyle pst, Unicode & HORI, Unicode & VERT, Unicode & NW, Unicode & NE, Unicode & SE, Unicode & SW) static
return the characters for style pst
Definition at line 689 of file PrintBuffer.cc.
Referenced by add_frame(), and add_outer_frame().
get_info() [1/2]
ColInfo & PrintBuffer::get_info () inline
return the ColInfo of this PrintBuffer
Definition at line 195 of file PrintBuffer.hh.
References col_info.
get_info() [2/2]
const ColInfo & PrintBuffer::get_info () const inline
return the ColInfo of this PrintBuffer
Definition at line 187 of file PrintBuffer.hh.
References col_info.
Referenced by ComplexCell::character_representation(), PointerCell::character_representation(), and do_PrintBuffer().
get_line()
UCS_string PrintBuffer::get_line (int y) const inline
return line y
Definition at line 122 of file PrintBuffer.hh.
References buffer, and get_row_count().
Referenced by Quad_QUOTE::assign(), do_PrintBuffer(), Bif_F12_FORMAT::eval_B(), Bif_F12_FORMAT::format_one_col_by_spec(), print_interruptible(), Token::show_trace(), and UCS_string::UCS_string().
get_row_count()
int PrintBuffer::get_row_count () const inline
return the number of rows
Definition at line 114 of file PrintBuffer.hh.
References buffer.
Referenced by add_column(), add_frame(), add_outer_frame(), add_row(), append_col(), append_ucs(), Quad_QUOTE::assign(), Token::canonical(), debug(), Quad_CR::do_CR31_32(), do_PrintBuffer(), Bif_F12_FORMAT::eval_B(), Bif_F12_FORMAT::format_by_specification(), get_column_count(), get_line(), is_rectangular(), l1(), Bif_F12_FORMAT::monadic_format(), pad_fraction(), pad_height(), pad_height_above(), pad_l(), pad_r(), pad_to_spaces(), print_interruptible(), Token::show_trace(), UCS_string::UCS_string(), and Value::Value().
is_rectangular()
bool PrintBuffer::is_rectangular () const
return true iff all strings have the same size.
Definition at line 1365 of file PrintBuffer.cc.
References get_column_count(), and get_row_count().
Referenced by add_frame(), add_outer_frame(), align(), append_aligned(), do_PrintBuffer(), and Bif_F12_FORMAT::eval_B().
l1()
UCS_string PrintBuffer::l1 () const inline
return the first (and only) line
Definition at line 118 of file PrintBuffer.hh.
References buffer, and get_row_count().
Referenced by Quad_QUOTE::assign(), Token::canonical(), Quad_CR::do_CR31_32(), and Quad_TF::tf2_ravel().
pad_fraction()
void PrintBuffer::pad_fraction (int wanted_fract_len, bool want_expo) protected
pad the fraction part to wanted_fract_len with '0'
Definition at line 1283 of file PrintBuffer.cc.
References UCS_string::append(), buffer, col_info, ColInfo::fract_len, get_column_count(), get_row_count(), ColInfo::int_len, ColInfo::real_len, and UCS_string::size().
Referenced by align_dot().
pad_height()
void PrintBuffer::pad_height (Unicode pad, ShapeItem height)
append lines to reach height
Definition at line 661 of file PrintBuffer.cc.
References buffer, get_column_count(), and get_row_count().
Referenced by Quad_CR::do_CR31_32(), and do_PrintBuffer().
pad_height_above()
void PrintBuffer::pad_height_above (Unicode pad, ShapeItem height)
prepend lines to reach height
Definition at line 679 of file PrintBuffer.cc.
References buffer, get_column_count(), get_row_count(), and UCS_string_vector::insert().
Referenced by Quad_CR::do_CR31_32().
pad_l()
void PrintBuffer::pad_l (Unicode pad, ShapeItem count)
prepend buffer with count characters pad
Definition at line 640 of file PrintBuffer.cc.
References buffer, and get_row_count().
Referenced by Bif_F12_FORMAT::add_row(), align_dot(), align_j(), append_aligned(), ComplexCell::character_representation(), LvalCell::character_representation(), do_PrintBuffer(), Bif_F12_FORMAT::format_by_specification(), Bif_F12_FORMAT::format_one_col_by_spec(), and PrintBuffer().
pad_r()
void PrintBuffer::pad_r (Unicode pad, ShapeItem count)
append count charactera pad to buffer
Definition at line 654 of file PrintBuffer.cc.
References buffer, and get_row_count().
Referenced by Bif_F12_FORMAT::add_row(), align_dot(), align_j(), align_left(), append_aligned(), LvalCell::character_representation(), do_PrintBuffer(), and PrintBuffer().
pad_to_spaces()
void PrintBuffer::pad_to_spaces ()
replace pad chars by spaces
Definition at line 671 of file PrintBuffer.cc.
References get_char(), get_column_count(), get_row_count(), and set_char().
Referenced by Quad_EM::get_apl_value().
pb_empty()
void PrintBuffer::pb_empty (const Value & value, PrintContext pctx, PrintStyle outer_style)
PrintBuffer from an empty APL value.
Definition at line 513 of file PrintBuffer.cc.
References add_outer_frame(), append_ucs(), buffer, Shape::get_rank(), Shape::get_shape_item(), PrintContext::get_style(), Shape::get_volume(), and PrintBuffer().
Referenced by PrintBuffer().
pb_for_function()
void PrintBuffer::pb_for_function (const Value & value, PrintContext pctx, PrintStyle outer_style)
PrintBuffer from an APL value in function-style.
Definition at line 564 of file PrintBuffer.cc.
References add_outer_frame(), UCS_string::append(), PrintContext::get_PW(), and PrintBuffer().
Referenced by PrintBuffer().
print_interruptible()
void PrintBuffer::print_interruptible (ostream & out, sRank rank, int quad_pw)
print this buffer, interruptible with ^C
Definition at line 442 of file PrintBuffer.cc.
References UCS_string::compute_chunk_length(), get_column_count(), get_line(), get_row_count(), UCS_string::remove_trailing_padchars(), and UCS_string::size().
Referenced by do_PrintBuffer().
separator_rows()
ShapeItem PrintBuffer::separator_rows (ShapeItem y, const Value & value, bool nested, sRank rk1, sRank rk2) static protected
return the number of separator rows before row y in a value with shape shape
Definition at line 598 of file PrintBuffer.cc.
References Shape::get_rank(), and Shape::get_shape_item().
Referenced by do_PrintBuffer().
set_char()
void PrintBuffer::set_char (int x, int y, Unicode uc)
Set the char in column x and row y to uc.
Definition at line 632 of file PrintBuffer.cc.
References buffer.
Referenced by add_frame(), add_outer_frame(), and pad_to_spaces().
update_info()
void PrintBuffer::update_info () inline
update col_info after a change of buffer
append UCS_string ucs to this PrintBuffer
Definition at line 190 of file PrintBuffer.hh.
References buffer, col_info, ColInfo::int_len, and ColInfo::real_len.
Referenced by do_PrintBuffer(), and PrintBuffer().
Member Data Documentation
buffer
UCS_string_vector PrintBuffer::buffer protected
the character buffer.
Definition at line 226 of file PrintBuffer.hh.
Referenced by add_column(), add_empty_rows(), add_frame(), add_outer_frame(), add_row(), align_dot(), align_j(), align_left(), append_aligned(), append_col(), append_ucs(), debug(), do_PrintBuffer(), get_char(), get_column_count(), get_line(), get_row_count(), l1(), pad_fraction(), pad_height(), pad_height_above(), pad_l(), pad_r(), pb_empty(), PrintBuffer(), set_char(), and update_info().
col_info
ColInfo PrintBuffer::col_info protected
column properties
Definition at line 229 of file PrintBuffer.hh.
Referenced by align_dot(), align_j(), align_left(), debug(), get_info(), pad_fraction(), and update_info().
complete
bool PrintBuffer::complete protected
true if completely constructed (as opposed to interrupted by ^C)
Definition at line 232 of file PrintBuffer.hh.
Referenced by do_PrintBuffer(), and PrintBuffer().
The documentation for this class was generated from the following files:
src/PrintBuffer.hh
src/PrintBuffer.cc