GNU APL: NativeFunction Class Reference
NativeFunction Class Reference
A defined function written in C++.
#include <NativeFunction.hh>
Public Types
enum NativeCategory {
NCAT_F0 ,
NCAT_F12 ,
NCAT_OP1 ,
NCAT_OP2
}
kind of native function
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Member Functions
const UCS_string & get_so_path () const
return the name of the .so library that implements this function
bool is_valid () const
return true if the .so library was successfully loaded
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Static Public Member Functions
static NativeFunction * fix (const UCS_string &so_name, const UCS_string &apl_name)
⎕FX a native funtion from a shared library (dlopen) handle
static void cleanup ()
close all shared libs
static UCS_string load_emacs_library (const char *emacs_arg)
load shared lib for emacs mode, return error info on failure
Protected Types
typedef Value_P Vr
shortcut for Value_P
typedef const Function & Fr
shortcut for const Function &
Protected Member Functions
NativeFunction (const UCS_string &so_name, const UCS_string &apl_name)
constructor (only fix() may call it)
~NativeFunction ()
destructor: close so_handle
virtual bool is_defined () const
overloaded Function::is_defined()
virtual bool is_native () const
overloaded Function::is_native()
virtual bool has_result () const
overloaded Function::has_result()
virtual bool is_operator () const
overloaded Function::is_operator()
virtual void print_properties (ostream &out, int indent) const
Overloaded Function::print_properties()
virtual ostream & print (std::ostream &) const
Overloaded Function::print()
virtual UCS_string canonical (bool with_lines) const
Overloaded Function::canonical()
virtual Token eval_ () const
Overloaded Function::eval_()
virtual Token eval_B (Value_P B) const
Overloaded Function::eval_B()
virtual Token eval_AB (Value_P A, Value_P B) const
Overloaded Function::eval_AB()
virtual Token eval_LB (Token &LO, Value_P B) const
Overloaded Function::eval_LB()
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
Overloaded Function::eval_ALB()
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
Overloaded Function::eval_LRB()
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
Overloaded Function::eval_ALRB()
virtual Token eval_XB (Value_P X, Value_P B) const
Overloaded Function::eval_XB()
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
Overloaded Function::eval_AXB()
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
Overloaded Function::eval_LXB()
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
Overloaded Function::eval_ALXB()
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
Overloaded Function::eval_LRXB()
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
Overloaded Function::eval_ALRXB()
virtual Token eval_fill_B (Value_P B) const
Overloaded Function::eval_fill_B()
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Overloaded Function::eval_fill_AB()
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
Overloaded Function::eval_identity_fun()
virtual void destroy ()
Overloaded Function::destroy()
UCS_string get_name () const
return the name of the named object
Static Protected Member Functions
static void * open_so_file (UCS_string &t4, UCS_string &so_path)
open .so file in one of several directories. On success set handle and update so_path.
static void * try_one_file (const char *filename, UCS_string &t4)
try to open one .so file
Protected Attributes
void * handle
dl_open() handle of shared library
UCS_string name
APL name of the function.
UCS_string original_so_path
the right argument B of of A ⎕FX B before expanding it to a path
UCS_string so_path
library file path of the function
bool valid
true if the shared lib was successfully opened
Fun_signature signature
type of function (niladic / nomadic / moadic operator / dyadic operator)
Token(* f_eval_)(const NativeFunction *)
pointer to function eval_() in shared library
Token(* f_eval_B)(Vr B, const NativeFunction *)
pointer to function eval_B() in shared library
Token(* f_eval_AB)(Vr A, Vr B, const NativeFunction *)
pointer to function eval_AB() in shared library
Token(* f_eval_LB)(Fr LO, Vr B, const NativeFunction *)
pointer to function eval_LB() in shared library
Token(* f_eval_ALB)(Vr A, Fr LO, Vr B, const NativeFunction *)
pointer to function eval_ALB() in shared library
Token(* f_eval_LRB)(Fr LO, Fr RO, Vr B, const NativeFunction *)
pointer to function eval_LRB() in shared library
Token(* f_eval_ALRB)(Vr A, Fr LO, Fr RO, Vr B, const NativeFunction *)
pointer to function eval_ALRB() in shared library
Token(* f_eval_XB)(Vr X, Vr B, const NativeFunction *)
pointer to function eval_XB() in shared library
Token(* f_eval_AXB)(Vr A, Vr X, Vr B, const NativeFunction *)
pointer to function eval_AXB() in shared library
Token(* f_eval_LXB)(Fr LO, Vr X, Vr B, const NativeFunction *)
pointer to function eval_LXB() in shared library
Token(* f_eval_ALXB)(Vr A, Fr LO, Vr X, Vr B, const NativeFunction *)
pointer to function eval_() in shared library
Token(* f_eval_LRXB)(Fr LO, Fr RO, Vr X, Vr B, const NativeFunction *)
pointer to function eval_LRXB() in shared library
Token(* f_eval_ALRXB)(Vr A, Fr LO, Fr RO, Vr X, Vr B, const NativeFunction *)
pointer to function eval_ALRXB() in shared library
Token(* f_eval_fill_B)(Vr B, const NativeFunction *)
pointer to function eval_fill_B() in shared library
Token(* f_eval_fill_AB)(Vr A, Vr B, const NativeFunction *)
pointer to function eval_fill_AB() in shared library
Token(* f_eval_ident_Bx)(Vr B, sAxis x, const NativeFunction *)
pointer to function eval_identity_fun() in shared library
bool(* close_fun)(Cause cause, const NativeFunction *caller)
callback before library is closed
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Static Protected Attributes
static std::vector< NativeFunction * > valid_functions
all native functions currently active
Friends
class Doxy
Additional Inherited Members
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Detailed Description
A defined function written in C++.
A defined function written in C++.
Definition at line 35 of file NativeFunction.hh.
Member Typedef Documentation
Fr
typedef const Function& NativeFunction::Fr protected
shortcut for const Function &
Definition at line 179 of file NativeFunction.hh.
Vr
typedef Value_P NativeFunction::Vr protected
shortcut for Value_P
Definition at line 177 of file NativeFunction.hh.
Member Enumeration Documentation
NativeCategory
enum NativeFunction::NativeCategory
kind of native function
Enumerator
NCAT_F0
niladic function
NCAT_F12
nomadic (monadic or dyadic) function
NCAT_OP1
monadic operator
NCAT_OP2
dyadic operator
Definition at line 56 of file NativeFunction.hh.
Constructor & Destructor Documentation
NativeFunction()
NativeFunction::NativeFunction (const UCS_string & so_name, const UCS_string & apl_name) protected
constructor (only fix() may call it)
read function pointers...
Definition at line 35 of file NativeFunction.cc.
References Symbol::cant_be_defined(), close_fun, eval_(), eval_AB(), eval_ALB(), eval_ALRB(), eval_ALRXB(), eval_ALXB(), eval_AXB(), eval_B(), eval_fill_AB(), eval_fill_B(), eval_LB(), eval_LRB(), eval_LRXB(), eval_LXB(), eval_XB(), handle, is_operator(), Workspace::lookup_symbol(), Workspace::more_error(), open_so_file(), Symbol::set_NC(), signature, so_path, Function::tag, valid, and valid_functions.
~NativeFunction()
NativeFunction::~NativeFunction () protected
destructor: close so_handle
Definition at line 154 of file NativeFunction.cc.
References get_name(), and valid_functions.
Member Function Documentation
canonical()
UCS_string NativeFunction::canonical (bool with_lines) const protected virtual
Overloaded Function::canonical()
Reimplemented from Function.
Definition at line 431 of file NativeFunction.cc.
References original_so_path.
cleanup()
void NativeFunction::cleanup () static
close all shared libs
Definition at line 309 of file NativeFunction.cc.
References close_fun, handle, and valid_functions.
destroy()
void NativeFunction::destroy () protected virtual
Overloaded Function::destroy()
Reimplemented from Function.
Definition at line 334 of file NativeFunction.cc.
References close_fun, and handle.
eval_()
Token NativeFunction::eval_ () const protected virtual
Overloaded Function::eval_()
Reimplemented from Function.
Definition at line 482 of file NativeFunction.cc.
References f_eval_.
Referenced by NativeFunction().
eval_AB()
Token NativeFunction::eval_AB (Value_P A, Value_P B) const protected virtual
Overloaded Function::eval_AB()
Reimplemented from Function.
Definition at line 498 of file NativeFunction.cc.
References f_eval_AB.
Referenced by eval_AXB(), and NativeFunction().
eval_ALB()
Token NativeFunction::eval_ALB (Value_P A, Token & LO, Value_P B) const protected virtual
Overloaded Function::eval_ALB()
Reimplemented from Function.
Definition at line 514 of file NativeFunction.cc.
References f_eval_ALB, and Token::get_function().
Referenced by eval_ALXB(), and NativeFunction().
eval_ALRB()
Token NativeFunction::eval_ALRB (Value_P A, Token & LO, Token & RO, Value_P B) const protected virtual
Overloaded Function::eval_ALRB()
Reimplemented from Function.
Definition at line 531 of file NativeFunction.cc.
References f_eval_ALRB, and Token::get_function().
Referenced by eval_ALRXB(), and NativeFunction().
eval_ALRXB()
Token NativeFunction::eval_ALRXB (Value_P A, Token & LO, Token & RO, Value_P X, Value_P B) const protected virtual
Overloaded Function::eval_ALRXB()
Reimplemented from Function.
Definition at line 586 of file NativeFunction.cc.
References eval_ALRB(), f_eval_ALRXB, and Token::get_function().
Referenced by NativeFunction().
eval_ALXB()
Token NativeFunction::eval_ALXB (Value_P A, Token & LO, Value_P X, Value_P B) const protected virtual
Overloaded Function::eval_ALXB()
Reimplemented from Function.
Definition at line 567 of file NativeFunction.cc.
References eval_ALB(), f_eval_ALXB, and Token::get_function().
Referenced by NativeFunction().
eval_AXB()
Token NativeFunction::eval_AXB (Value_P A, Value_P X, Value_P B) const protected virtual
Overloaded Function::eval_AXB()
Reimplemented from Function.
Definition at line 549 of file NativeFunction.cc.
References eval_AB(), and f_eval_AXB.
Referenced by NativeFunction().
eval_B()
Token NativeFunction::eval_B (Value_P B) const protected virtual
Overloaded Function::eval_B()
Reimplemented from Function.
Definition at line 490 of file NativeFunction.cc.
References f_eval_B.
Referenced by eval_XB(), and NativeFunction().
eval_fill_AB()
Token NativeFunction::eval_fill_AB (Value_P A, Value_P B) const protected virtual
Overloaded Function::eval_fill_AB()
Reimplemented from Function.
Definition at line 604 of file NativeFunction.cc.
References f_eval_fill_AB.
Referenced by NativeFunction().
eval_fill_B()
Token NativeFunction::eval_fill_B (Value_P B) const protected virtual
Overloaded Function::eval_fill_B()
Reimplemented from Function.
Definition at line 596 of file NativeFunction.cc.
References f_eval_fill_B.
Referenced by NativeFunction().
eval_identity_fun()
Token NativeFunction::eval_identity_fun (Value_P B, sAxis axis) const protected virtual
Overloaded Function::eval_identity_fun()
Reimplemented from Function.
Definition at line 612 of file NativeFunction.cc.
References f_eval_ident_Bx.
eval_LB()
Token NativeFunction::eval_LB (Token & LO, Value_P B) const protected virtual
Overloaded Function::eval_LB()
Reimplemented from Function.
Definition at line 506 of file NativeFunction.cc.
References f_eval_LB, and Token::get_function().
Referenced by eval_LXB(), and NativeFunction().
eval_LRB()
Token NativeFunction::eval_LRB (Token & LO, Token & RO, Value_P B) const protected virtual
Overloaded Function::eval_LRB()
Reimplemented from Function.
Definition at line 522 of file NativeFunction.cc.
References f_eval_LRB, and Token::get_function().
Referenced by eval_LRXB(), and NativeFunction().
eval_LRXB()
Token NativeFunction::eval_LRXB (Token & LO, Token & RO, Value_P X, Value_P B) const protected virtual
Overloaded Function::eval_LRXB()
Reimplemented from Function.
Definition at line 576 of file NativeFunction.cc.
References eval_LRB(), f_eval_LRXB, and Token::get_function().
Referenced by NativeFunction().
eval_LXB()
Token NativeFunction::eval_LXB (Token & LO, Value_P X, Value_P B) const protected virtual
Overloaded Function::eval_LXB()
Reimplemented from Function.
Definition at line 558 of file NativeFunction.cc.
References eval_LB(), f_eval_LXB, and Token::get_function().
Referenced by NativeFunction().
eval_XB()
Token NativeFunction::eval_XB (Value_P X, Value_P B) const protected virtual
Overloaded Function::eval_XB()
Reimplemented from Function.
Definition at line 540 of file NativeFunction.cc.
References eval_B(), and f_eval_XB.
Referenced by NativeFunction().
fix()
NativeFunction * NativeFunction::fix (const UCS_string & so_name, const UCS_string & apl_name) static
⎕FX a native funtion from a shared library (dlopen) handle
Definition at line 356 of file NativeFunction.cc.
References Symbol::cant_be_defined(), get_name(), is_operator(), Workspace::lookup_symbol(), Symbol::set_NC(), so_path, valid, and valid_functions.
Referenced by Quad_FX::do_native_FX(), and XML_Loading_Archive::read_Function().
get_name()
UCS_string NativeFunction::get_name () const inline protected virtual
return the name of the named object
Reimplemented from NamedObject.
Definition at line 153 of file NativeFunction.hh.
References name.
Referenced by fix(), and ~NativeFunction().
get_so_path()
const UCS_string & NativeFunction::get_so_path () const inline
return the name of the .so library that implements this function
Definition at line 41 of file NativeFunction.hh.
References so_path.
Referenced by Command::cmd_HELP(), and Doxy::native_page().
has_result()
bool NativeFunction::has_result () const protected virtual
overloaded Function::has_result()
Implements Function.
Definition at line 402 of file NativeFunction.cc.
References signature.
Referenced by Doxy::native_page().
is_defined()
virtual bool NativeFunction::is_defined () const inline protected virtual
overloaded Function::is_defined()
Reimplemented from Function.
Definition at line 82 of file NativeFunction.hh.
is_native()
virtual bool NativeFunction::is_native () const inline protected virtual
overloaded Function::is_native()
Reimplemented from Function.
Definition at line 85 of file NativeFunction.hh.
is_operator()
bool NativeFunction::is_operator () const protected virtual
overloaded Function::is_operator()
Reimplemented from Function.
Definition at line 408 of file NativeFunction.cc.
References f_eval_ALB, f_eval_ALRB, f_eval_ALRXB, f_eval_ALXB, f_eval_LB, f_eval_LRB, f_eval_LRXB, and f_eval_LXB.
Referenced by fix(), NativeFunction(), and print().
is_valid()
bool NativeFunction::is_valid () const inline
return true if the .so library was successfully loaded
Definition at line 45 of file NativeFunction.hh.
References valid.
Referenced by Command::cmd_HELP().
load_emacs_library()
UCS_string NativeFunction::load_emacs_library (const char * emacs_arg) static
load shared lib for emacs mode, return error info on failure
Definition at line 446 of file NativeFunction.cc.
References UCS_string::append(), UCS_string::append_number(), UCS_string::append_UTF8(), UTF8_string::c_str(), handle, open_so_file(), and so_path.
Referenced by init_apl().
open_so_file()
void * NativeFunction::open_so_file (UCS_string & t4, UCS_string & so_path) static protected
open .so file in one of several directories. On success set handle and update so_path.
Definition at line 200 of file NativeFunction.cc.
References UCS_string::append(), UCS_string::append_UTF8(), UTF8_string::append_UTF8(), UTF8_string::c_str(), handle, so_path, and try_one_file().
Referenced by load_emacs_library(), and NativeFunction().
print()
ostream & NativeFunction::print (std::ostream & out) const protected virtual
Overloaded Function::print()
Definition at line 437 of file NativeFunction.cc.
References is_operator(), and name.
print_properties()
void NativeFunction::print_properties (ostream & out, int indent) const protected virtual
Overloaded Function::print_properties()
Implements Function.
Definition at line 424 of file NativeFunction.cc.
try_one_file()
void * NativeFunction::try_one_file (const char * filename, UCS_string & t4) static protected
try to open one .so file
Definition at line 169 of file NativeFunction.cc.
References UCS_string::append_UTF8(), handle, and UCS_string::size().
Referenced by open_so_file().
Friends And Related Function Documentation
Doxy
friend class Doxy friend
Definition at line 37 of file NativeFunction.hh.
Member Data Documentation
close_fun
bool(* NativeFunction::close_fun) (Cause cause, const NativeFunction *caller) protected
callback before library is closed
Definition at line 234 of file NativeFunction.hh.
Referenced by cleanup(), destroy(), and NativeFunction().
f_eval_
Token(* NativeFunction::f_eval_) (const NativeFunction *) protected
pointer to function eval_() in shared library
Definition at line 184 of file NativeFunction.hh.
Referenced by eval_(), and Doxy::native_page().
f_eval_AB
Token(* NativeFunction::f_eval_AB) (Vr A, Vr B, const NativeFunction *) protected
pointer to function eval_AB() in shared library
Definition at line 190 of file NativeFunction.hh.
Referenced by eval_AB(), and Doxy::native_page().
f_eval_ALB
Token(* NativeFunction::f_eval_ALB) (Vr A, Fr LO, Vr B, const NativeFunction *) protected
pointer to function eval_ALB() in shared library
Definition at line 196 of file NativeFunction.hh.
Referenced by eval_ALB(), is_operator(), and Doxy::native_page().
f_eval_ALRB
Token(* NativeFunction::f_eval_ALRB) (Vr A, Fr LO, Fr RO, Vr B, const NativeFunction *) protected
pointer to function eval_ALRB() in shared library
Definition at line 202 of file NativeFunction.hh.
Referenced by eval_ALRB(), is_operator(), and Doxy::native_page().
f_eval_ALRXB
Token(* NativeFunction::f_eval_ALRXB) (Vr A, Fr LO, Fr RO, Vr X, Vr B, const NativeFunction *) protected
pointer to function eval_ALRXB() in shared library
Definition at line 220 of file NativeFunction.hh.
Referenced by eval_ALRXB(), is_operator(), and Doxy::native_page().
f_eval_ALXB
Token(* NativeFunction::f_eval_ALXB) (Vr A, Fr LO, Vr X, Vr B, const NativeFunction *) protected
pointer to function eval_() in shared library
Definition at line 214 of file NativeFunction.hh.
Referenced by eval_ALXB(), is_operator(), and Doxy::native_page().
f_eval_AXB
Token(* NativeFunction::f_eval_AXB) (Vr A, Vr X, Vr B, const NativeFunction *) protected
pointer to function eval_AXB() in shared library
Definition at line 208 of file NativeFunction.hh.
Referenced by eval_AXB(), and Doxy::native_page().
f_eval_B
Token(* NativeFunction::f_eval_B) (Vr B, const NativeFunction *) protected
pointer to function eval_B() in shared library
Definition at line 187 of file NativeFunction.hh.
Referenced by eval_B(), and Doxy::native_page().
f_eval_fill_AB
Token(* NativeFunction::f_eval_fill_AB) (Vr A, Vr B, const NativeFunction *) protected
pointer to function eval_fill_AB() in shared library
Definition at line 227 of file NativeFunction.hh.
Referenced by eval_fill_AB().
f_eval_fill_B
Token(* NativeFunction::f_eval_fill_B) (Vr B, const NativeFunction *) protected
pointer to function eval_fill_B() in shared library
Definition at line 224 of file NativeFunction.hh.
Referenced by eval_fill_B().
f_eval_ident_Bx
Token(* NativeFunction::f_eval_ident_Bx) (Vr B, sAxis x, const NativeFunction *) protected
pointer to function eval_identity_fun() in shared library
Definition at line 230 of file NativeFunction.hh.
Referenced by eval_identity_fun().
f_eval_LB
Token(* NativeFunction::f_eval_LB) (Fr LO, Vr B, const NativeFunction *) protected
pointer to function eval_LB() in shared library
Definition at line 193 of file NativeFunction.hh.
Referenced by eval_LB(), is_operator(), and Doxy::native_page().
f_eval_LRB
Token(* NativeFunction::f_eval_LRB) (Fr LO, Fr RO, Vr B, const NativeFunction *) protected
pointer to function eval_LRB() in shared library
Definition at line 199 of file NativeFunction.hh.
Referenced by eval_LRB(), is_operator(), and Doxy::native_page().
f_eval_LRXB
Token(* NativeFunction::f_eval_LRXB) (Fr LO, Fr RO, Vr X, Vr B, const NativeFunction *) protected
pointer to function eval_LRXB() in shared library
Definition at line 217 of file NativeFunction.hh.
Referenced by eval_LRXB(), is_operator(), and Doxy::native_page().
f_eval_LXB
Token(* NativeFunction::f_eval_LXB) (Fr LO, Vr X, Vr B, const NativeFunction *) protected
pointer to function eval_LXB() in shared library
Definition at line 211 of file NativeFunction.hh.
Referenced by eval_LXB(), is_operator(), and Doxy::native_page().
f_eval_XB
Token(* NativeFunction::f_eval_XB) (Vr X, Vr B, const NativeFunction *) protected
pointer to function eval_XB() in shared library
Definition at line 205 of file NativeFunction.hh.
Referenced by eval_XB(), and Doxy::native_page().
handle
void* NativeFunction::handle protected
dl_open() handle of shared library
Definition at line 157 of file NativeFunction.hh.
Referenced by cleanup(), destroy(), load_emacs_library(), NativeFunction(), open_so_file(), and try_one_file().
name
UCS_string NativeFunction::name protected
APL name of the function.
Definition at line 160 of file NativeFunction.hh.
Referenced by get_name(), and print().
original_so_path
UCS_string NativeFunction::original_so_path protected
the right argument B of of A ⎕FX B before expanding it to a path
Definition at line 163 of file NativeFunction.hh.
Referenced by canonical().
signature
Fun_signature NativeFunction::signature protected
type of function (niladic / nomadic / moadic operator / dyadic operator)
Definition at line 172 of file NativeFunction.hh.
Referenced by has_result(), and NativeFunction().
so_path
UCS_string NativeFunction::so_path protected
library file path of the function
Definition at line 166 of file NativeFunction.hh.
Referenced by fix(), get_so_path(), load_emacs_library(), NativeFunction(), and open_so_file().
valid
bool NativeFunction::valid protected
true if the shared lib was successfully opened
Definition at line 169 of file NativeFunction.hh.
Referenced by fix(), is_valid(), and NativeFunction().
valid_functions
std::vector< NativeFunction * > NativeFunction::valid_functions static protected
all native functions currently active
Definition at line 175 of file NativeFunction.hh.
Referenced by cleanup(), fix(), NativeFunction(), and ~NativeFunction().
The documentation for this class was generated from the following files:
src/NativeFunction.hh
src/NativeFunction.cc