GNU APL: UTF8_string Class Reference
UTF8_string Class Reference
an UTF8 encoded Unicode (RFC 3629) string
#include <UTF8_string.hh>
Public Member Functions
UTF8_string ()
constructor: empty UTF8_string
UTF8_string (const char *str)
constructor: UTF8_string from 0-terminated C string.
UTF8_string (const UTF8 *str, size_t len)
constructor: copy of C string, but at most len bytes
UTF8_string (const UCS_string &ucs)
constructor: copy of UCS string. The Unicodes in ucs will be UTF8-encoded
bool operator== (const UTF8_string &other) const
return true iff this is equal to other
const char * c_str () const
return this string as a 0-terminated C string
void erase (size_t pos)
prevent basic_string::erase() with its dangerous default value for the number of erased character.
UTF8 back () const
return the last byte in this string
void pop_back ()
discard the last byte in this string
void append_ASCII (const char *ascii)
append a 0-terminated C string
void append_UTF8 (const UTF8_string &suffix)
append the UTF8_string suffix
ostream & dump_hex (ostream &out, int max_bytes) const
display bytes in this UTF string
bool ends_with (const char *ext) const
return true iff string ends with ext (usually a file name extension)
bool starts_with (const char *path) const
return true iff string starts with path (usually a file path)
int un_HTML (int in_HTML)
skip over < ... > and expand < and friends
bool round_0_1 ()
round a digit string is the fractional part of a number between 0.0... and 0.9... up or down according to its last digit, return true if the exponent shall be increased (because 1.0 -> 0.1)
Static Public Member Functions
static Unicode toUni (const UTF8 *string, int &len, bool verbose)
convert the first char in UTF8-encoded string to Unicode, setting len to the number of bytes in the UTF8 encoding of the char
static Unicode getc (istream &in)
return the next UTF8 encoded char from an input file
Detailed Description
an UTF8 encoded Unicode (RFC 3629) string
Definition at line 55 of file UTF8_string.hh.
Constructor & Destructor Documentation
UTF8_string() [1/4]
UTF8_string::UTF8_string () inline
constructor: empty UTF8_string
Definition at line 59 of file UTF8_string.hh.
UTF8_string() [2/4]
UTF8_string::UTF8_string (const char * str) inline
constructor: UTF8_string from 0-terminated C string.
Definition at line 63 of file UTF8_string.hh.
UTF8_string() [3/4]
UTF8_string::UTF8_string (const UTF8 * str, size_t len) inline
constructor: copy of C string, but at most len bytes
Definition at line 67 of file UTF8_string.hh.
UTF8_string() [4/4]
UTF8_string::UTF8_string (const UCS_string & ucs)
constructor: copy of UCS string. The Unicodes in ucs will be UTF8-encoded
Definition at line 56 of file UTF8_string.cc.
References UCS_string::size().
Member Function Documentation
append_ASCII()
void UTF8_string::append_ASCII (const char * ascii) inline
append a 0-terminated C string
Definition at line 105 of file UTF8_string.hh.
Referenced by Workspace::backup_existing_file(), Doxy::Doxy(), Doxy::function_page(), Doxy::gen(), LibPaths::get_lib_filename(), LibPaths::maybe_warn_ambiguous(), Doxy::native_page(), Quad_FIO::Quad_FIO(), UserPreferences::read_config_file(), Quad_PNG::read_PNG_file(), save_file(), Doxy::write_call_graph(), and Doxy::write_css().
append_UTF8()
void UTF8_string::append_UTF8 (const UTF8_string & suffix) inline
append the UTF8_string suffix
Definition at line 109 of file UTF8_string.hh.
Referenced by Doxy::Doxy(), Doxy::function_page(), Doxy::gen(), LibPaths::get_lib_dir(), LibPaths::get_lib_filename(), Command::is_directory(), Doxy::native_page(), Command::open_LIB_dir(), NativeFunction::open_so_file(), Tokenizer::tokenize_real(), and Doxy::write_call_graph().
back()
UTF8 UTF8_string::back () const inline
return the last byte in this string
Definition at line 97 of file UTF8_string.hh.
Referenced by Bif_F1_EXECUTE::execute_command(), UserFunction::load(), round_0_1(), and Tokenizer::tokenize_real().
c_str()
const char * UTF8_string::c_str () const inline
return this string as a 0-terminated C string
Definition at line 87 of file UTF8_string.hh.
Referenced by Workspace::backup_existing_file(), Command::cmd_DROP(), Command::cmd_HELP(), Command::cmd_HOST(), Command::cmd_IN(), Command::cmd_KEYB(), Command::cmd_LIBS(), Command::cmd_OUT(), XML_node::collect(), LibPaths::compute_bin_path(), Quad_JSON::convert_file(), Quad_XML::convert_file(), Workspace::copy_WS(), Quad_FIO::do_FIO_57(), Quad_FIO::do_printf(), Doxy::Doxy(), Workspace::dump_WS(), Nabla::edit(), Quad_CR::eval_AB(), Quad_PNG::eval_AB(), Quad_FIO::eval_AXB(), Quad_FIO::eval_XB(), Quad_ES::event_simulate(), TabExpansion::expand_filename(), TabExpansion::expand_wsname(), Doxy::function_page(), Doxy::gen(), IO_Files::get_file_line(), LibPaths::get_lib_filename(), InputMux::get_line(), init_apl(), Command::is_directory(), LibPaths::is_present(), LineInput::LineInput(), NativeFunction::load_emacs_library(), Workspace::load_WS(), LibPaths::maybe_warn_ambiguous(), Doxy::native_page(), Command::open_LIB_dir(), NativeFunction::open_so_file(), Quad_GTK::open_window(), DiffOut::overflow(), Quad_PLOT::parse_attributes(), XML_node::parse_tag(), InputFile::randomize_files(), TabExpansion::read_matching_filenames(), Quad_PNG::read_PNG_file(), Quad_GTK::resolve_fun_name(), save_file(), Workspace::save_WS(), Plot_window_properties::set_attribute(), Executable::set_error_info(), Error::set_error_line_2(), UserFunction::set_locked_error_info(), Quad_CR::subfun_to_axis(), Quad_FIO::subfun_to_axis(), Error::throw_define_error(), Error::throw_symbol_error(), un_HTML(), Error::update_error_info(), Doxy::write_call_graph(), Doxy::write_css(), and LineInput::~LineInput().
dump_hex()
ostream & UTF8_string::dump_hex (ostream & out, int max_bytes) const
display bytes in this UTF string
Definition at line 135 of file UTF8_string.cc.
Referenced by UCS_string::UCS_string().
ends_with()
bool UTF8_string::ends_with (const char * ext) const
return true iff string ends with ext (usually a file name extension)
Definition at line 256 of file UTF8_string.cc.
Referenced by LibPaths::get_lib_filename(), Command::lib_common(), TabExpansion::read_matching_filenames(), Quad_PNG::read_PNG_file(), and save_file().
erase()
void UTF8_string::erase (size_t pos) inline
prevent basic_string::erase() with its dangerous default value for the number of erased character.
Definition at line 93 of file UTF8_string.hh.
Referenced by InputMux::get_line(), and Tokenizer::tokenize_real().
getc()
Unicode UTF8_string::getc (istream & in) static
return the next UTF8 encoded char from an input file
Definition at line 200 of file UTF8_string.cc.
Referenced by UCS_string::UCS_string().
operator==()
bool UTF8_string::operator== (const UTF8_string & other) const inline
return true iff this is equal to other
Definition at line 79 of file UTF8_string.hh.
pop_back()
void UTF8_string::pop_back () inline
discard the last byte in this string
Definition at line 101 of file UTF8_string.hh.
Referenced by UserFunction::load(), round_0_1(), and Tokenizer::tokenize_real().
round_0_1()
bool UTF8_string::round_0_1 ()
round a digit string is the fractional part of a number between 0.0... and 0.9... up or down according to its last digit, return true if the exponent shall be increased (because 1.0 -> 0.1)
Definition at line 362 of file UTF8_string.cc.
References back(), and pop_back().
Referenced by Tokenizer::tokenize_real().
starts_with()
bool UTF8_string::starts_with (const char * path) const
return true iff string starts with path (usually a file path)
Definition at line 242 of file UTF8_string.cc.
Referenced by LibPaths::get_lib_filename(), and IO_Files::read_file_line().
toUni()
Unicode UTF8_string::toUni (const UTF8 * string, int & len, bool verbose) static
convert the first char in UTF8-encoded string to Unicode, setting len to the number of bytes in the UTF8 encoding of the char
Definition at line 149 of file UTF8_string.cc.
Referenced by DiffOut::different(), XML_Loading_Archive::get_uni(), XML_Loading_Archive::read_Cells(), and XML_Loading_Archive::read_XML_string().
un_HTML()
int UTF8_string::un_HTML (int in_HTML)
skip over < ... > and expand < and friends
Definition at line 270 of file UTF8_string.cc.
References c_str().
Referenced by IO_Files::read_file_line().
The documentation for this class was generated from the following files:
src/UTF8_string.hh
src/UTF8_string.cc