GNU APL: LineInput Class Reference
LineInput Class Reference
a class for obtaining one line of input from the user (editable)
#include <LineInput.hh>
Static Public Member Functions
static void get_terminal_line (LineInputMode mode, const UCS_string &prompt, UCS_string &line, bool &eof, LineHistory &hist)
get a line from the user
static void edit_line (LineInputMode mode, const UCS_string &prompt, UCS_string &user_line, bool &eof, LineHistory &hist)
get a line from from user
static void init (bool do_read_history)
initialize the input subsystem
static void close (bool do_not_write_hist)
close this line input, maybe updating the history
static void clear_history (ostream &out)
clear history
static void print_history (ostream &out)
print history to out
static void add_history_line (const UCS_string &line)
add a line to the history
static void replace_history_line (const UCS_string &line)
replace the last line of the history
static LineHistory & get_history ()
return the history
Protected Member Functions
LineInput (bool do_read_history)
constructor
~LineInput ()
destructor
Static Protected Member Functions
static int safe_fgetc ()
interrupt-safe fgetc()
static Unicode get_uni ()
get one character from user
Protected Attributes
LineHistory history
lines previously entered
struct termios initial_termios
the stdin termios at startup of the interpreter. Will be restored when the interpreter exits.
struct termios current_termios
the current stdin termios.
int initial_termios_errno
the first tcgetattr() errno (or 0 if none)
bool write_history
write history when done
Static Protected Attributes
static LineInput * the_line_input = 0
single LineInput instance that restores stdin termios on destruction
Detailed Description
a class for obtaining one line of input from the user (editable)
Definition at line 309 of file LineInput.hh.
Constructor & Destructor Documentation
LineInput()
LineInput::LineInput (bool do_read_history) protected
constructor
Definition at line 702 of file LineInput.cc.
References UTF8_string::c_str(), current_termios, history, initial_termios, initial_termios_errno, UserPreferences::line_history_path, LineHistory::read_history(), and write_history.
~LineInput()
LineInput::~LineInput () protected
destructor
Definition at line 738 of file LineInput.cc.
References UTF8_string::c_str(), history, initial_termios, initial_termios_errno, UserPreferences::line_history_path, LineHistory::save_history(), and write_history.
Member Function Documentation
add_history_line()
static void LineInput::add_history_line (const UCS_string & line) inline static
add a line to the history
Definition at line 340 of file LineInput.hh.
References LineHistory::add_line(), history, and the_line_input.
Referenced by Nabla::edit().
clear_history()
static void LineInput::clear_history (ostream & out) inline static
clear history
Definition at line 332 of file LineInput.hh.
References LineHistory::clear_history(), history, and the_line_input.
Referenced by Command::cmd_HISTORY().
close()
static void LineInput::close (bool do_not_write_hist) inline static
close this line input, maybe updating the history
Definition at line 326 of file LineInput.hh.
References the_line_input, and write_history.
edit_line()
void LineInput::edit_line (LineInputMode mode, const UCS_string & prompt, UCS_string & user_line, bool & eof, LineHistory & hist) static
get a line from from user
Definition at line 946 of file LineInput.cc.
References LineHistory::add_line(), LineEditContext::backspc(), LineEditContext::clear(), current_termios, LineEditContext::cursor_CLEAR_SEARCH(), LineEditContext::cursor_DOWN(), LineEditContext::cursor_END(), LineEditContext::cursor_HOME(), LineEditContext::cursor_LEFT(), LineEditContext::cursor_RIGHT(), LineEditContext::cursor_SEARCH(), LineEditContext::cursor_UP(), LineEditContext::cut_to_EOL(), LineEditContext::delete_char(), Workspace::get_PW(), get_uni(), LineEditContext::get_user_line(), UCS_string::has_black(), LineEditContext::insert_char(), InputFile::is_validating(), LineEditContext::paste(), UCS_string::size(), LineEditContext::tab_expansion(), the_line_input, LineEditContext::toggle_ins_mode(), and LineEditContext::update_SEARCH().
Referenced by get_terminal_line().
get_history()
static LineHistory & LineInput::get_history () inline static
return the history
Definition at line 348 of file LineInput.hh.
References history, and the_line_input.
Referenced by Command::process_line().
get_terminal_line()
void LineInput::get_terminal_line (LineInputMode mode, const UCS_string & prompt, UCS_string & line, bool & eof, LineHistory & hist) static
get a line from the user
Definition at line 919 of file LineInput.cc.
References Output::COLM_INPUT, edit_line(), and Output::set_color_mode().
Referenced by InputMux::get_line().
get_uni()
Unicode LineInput::get_uni () static protected
get one character from user
Definition at line 1124 of file LineInput.cc.
References ESCmap::need_more(), safe_fgetc(), ESCmap::the_ESCmap, and ESCmap::uni.
Referenced by edit_line().
init()
void LineInput::init (bool do_read_history) static
initialize the input subsystem
Definition at line 752 of file LineInput.cc.
References the_line_input.
print_history()
static void LineInput::print_history (ostream & out) inline static
print history to out
Definition at line 336 of file LineInput.hh.
References history, LineHistory::print_history(), and the_line_input.
Referenced by Command::cmd_HISTORY().
replace_history_line()
static void LineInput::replace_history_line (const UCS_string & line) inline static
replace the last line of the history
Definition at line 344 of file LineInput.hh.
References history, LineHistory::replace_line(), and the_line_input.
Referenced by Nabla::edit().
safe_fgetc()
int LineInput::safe_fgetc () static protected
interrupt-safe fgetc()
Definition at line 1105 of file LineInput.cc.
Referenced by get_uni().
Member Data Documentation
current_termios
struct termios LineInput::current_termios protected
the current stdin termios.
Definition at line 366 of file LineInput.hh.
Referenced by edit_line(), and LineInput().
history
LineHistory LineInput::history protected
lines previously entered
Definition at line 359 of file LineInput.hh.
Referenced by add_history_line(), clear_history(), get_history(), LineInput(), print_history(), replace_history_line(), and ~LineInput().
initial_termios
struct termios LineInput::initial_termios protected
the stdin termios at startup of the interpreter. Will be restored when the interpreter exits.
Definition at line 363 of file LineInput.hh.
Referenced by LineInput(), and ~LineInput().
initial_termios_errno
int LineInput::initial_termios_errno protected
the first tcgetattr() errno (or 0 if none)
Definition at line 369 of file LineInput.hh.
Referenced by LineInput(), and ~LineInput().
the_line_input
LineInput * LineInput::the_line_input = 0 static protected
single LineInput instance that restores stdin termios on destruction
Definition at line 381 of file LineInput.hh.
Referenced by add_history_line(), clear_history(), close(), edit_line(), get_history(), init(), print_history(), and replace_history_line().
write_history
bool LineInput::write_history protected
write history when done
Definition at line 372 of file LineInput.hh.
Referenced by close(), LineInput(), and ~LineInput().
The documentation for this class was generated from the following files:
src/LineInput.hh
src/LineInput.cc