GNU APL: CDR Class Reference
CDR Class Reference
The class implementing CDR (IBM's Common Data Representation)
#include <CDR.hh>
Static Public Member Functions
static void to_CDR (CDR_string &result, const Value *value)
convert value into a CDR_string
static Value_P from_CDR (const CDR_string &cdr, const char *loc)
create a value from a CDR_string, throwing DOMAIN ERROR if cdr is ill-formed
static uint32_t get_2_be (const uint8_t *data)
return 2 bytes starting at data in network byte order
static uint32_t get_4_be (const uint8_t *data)
return 4 bytes starting at data in network byte order
static uint64_t get_8_be (const uint8_t *data)
return 8 bytes starting at data in network byte order
Static Protected Member Functions
static void fill (CDR_string &result, int type, int len, const Value &val)
fill result with the bytes of the CDR of value
Detailed Description
The class implementing CDR (IBM's Common Data Representation)
a class for creating the Common Data Representation of an APL value.
Definition at line 34 of file CDR.hh.
Member Function Documentation
fill()
void CDR::fill (CDR_string & result, int type, int len, const Value & val) static protected
fill result with the bytes of the CDR of value
Definition at line 43 of file CDR.cc.
References Value::element_count(), fill(), Value::get_CDR_type(), Cell::get_char_value(), Value::get_cravel(), Cell::get_imag_value(), Cell::get_int_value(), Cell::get_pointer_value(), Value::get_rank(), Cell::get_real_value(), Value::get_shape_item(), Cell::is_pointer_cell(), Cell::is_simple_cell(), and Value::total_CDR_size_brutto().
Referenced by fill(), and to_CDR().
from_CDR()
Value_P CDR::from_CDR (const CDR_string & cdr, const char * loc) static
create a value from a CDR_string, throwing DOMAIN ERROR if cdr is ill-formed
Definition at line 302 of file CDR.cc.
References Shape::add_shape_item(), from_CDR(), Value_P_Base::get(), get_4_be(), Workspace::get_IO(), CDR_string::get_items(), and Shape::get_volume().
Referenced by Quad_CR::do_CR12(), Quad_CR::do_CR15(), from_CDR(), and Symbol::resolve_shared_variable().
get_2_be()
static uint32_t CDR::get_2_be (const uint8_t * data) inline static
return 2 bytes starting at data in network byte order
Definition at line 45 of file CDR.hh.
get_4_be()
static uint32_t CDR::get_4_be (const uint8_t * data) inline static
return 4 bytes starting at data in network byte order
Definition at line 52 of file CDR.hh.
References CDR_header::get_be32().
Referenced by from_CDR(), and get_8_be().
get_8_be()
static uint64_t CDR::get_8_be (const uint8_t * data) inline static
return 8 bytes starting at data in network byte order
Definition at line 56 of file CDR.hh.
References get_4_be().
to_CDR()
void CDR::to_CDR (CDR_string & result, const Value * value) static
convert value into a CDR_string
Definition at line 32 of file CDR.cc.
References fill().
Referenced by Symbol::assign_shared_variable(), Quad_CR::do_CR11(), Quad_CR::do_CR14(), and Quad_TF::tf3().
The documentation for this class was generated from the following files:
src/CDR.hh
src/CDR.cc