GNU APL: UserFunction Class Reference
UserFunction Class Reference
One user-defined function.
#include <UserFunction.hh>
Public Member Functions
UserFunction (Fun_signature sig, int lambda_num, const UCS_string &text, Token_string &body)
constructor for a lambda
~UserFunction ()
Destructor.
virtual bool is_lambda () const
overloaded Function::is_lambda()
virtual bool is_defined () const
overloaded Function::is_defined()
virtual int get_macnum () const
return the macro number (if this function is one) or -1
virtual const UserFunction * get_exec_ufun () const
overloaded Executable::get_exec_ufun()
virtual const UserFunction * get_func_ufun () const
overloaded Function::get_func_ufun()
virtual UserFunction * get_exec_ufun ()
overloaded Executable::get_exec_ufun()
virtual int get_fun_valence () const
overloaded Function::get_fun_valence()
virtual int get_oper_valence () const
overloaded Function::get_oper_valence()
virtual bool has_result () const
overloaded Function::has_result()
virtual bool has_axis () const
overloaded Function::has_axis()
bool localizes (const Symbol *sym) const
return true if this function localizes sym
void pop_local_vars () const
pop all
void print_local_vars (ostream &out) const
print the local variables for command)SINL
ShapeItem local_var_count () const
return the number of local variables
const Symbol * get_local_var (ShapeItem idx) const
return the idx'th local variable
virtual bool is_operator () const
Overloaded Function::is_operator.
void add_label (Symbol *sym, Function_Line line)
add a label
virtual const int * get_exec_properties () const
return the execution properties (dyadic ⎕FX) of this defined function
virtual bool cannot_suspend () const
ovewrloaded Executable::cannot_suspend
void set_exec_properties (const int *props)
set execution properties (as per A ⎕FX)
virtual ostream & print (ostream &out) const
overloaded Executable::print()
virtual UCS_string get_name () const
return the name of this function
UCS_string get_name_and_line (Function_PC pc) const
return e.g. 'FOO[10]'
virtual void print_properties (ostream &out, int indent) const
Overloaded Function::print_properties()
void save (const char *workspace, const char *function)
)SAVE this function in the workspace named workspace (in the file system).
virtual void destroy ()
overloaded Function::destroy()
virtual bool pushes_sym (const Symbol *sym) const
overloaded Executable::pushes_sym() const
void help (ostream &out) const
print help for this function on out (for the)HELP command)
Function_PC pc_for_line (Function_Line line) const
return the pc of the first token in line l (valid line), or the pc of the last token in the function (invalid line)
virtual bool has_alpha () const
Overloaded Function::has_alpha()
virtual Symbol * get_sym_Z () const
overloaded Executable::get_sym_Z()
Function_Line get_line (Function_PC pc) const
overloaded Executable::get_line()
virtual Token eval_ () const
Overloaded Function::eval_()
virtual Token eval_B (Value_P B) const
Overloaded Function::eval_B()
virtual Token eval_XB (Value_P X, Value_P B) const
Overloaded Function::eval_XB()
virtual Token eval_AB (Value_P A, Value_P B) const
Overloaded Function::eval_AB()
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
Overloaded Function::eval_AXB()
virtual Token eval_LB (Token &LO, Value_P B) const
Overloaded Function::eval_LB.
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
Overloaded Function::eval_LXB()
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
Overloaded Function::eval_ALB.
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
Overloaded Function::eval_ALXB()
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
Overloaded Function::eval_LRB()
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
Overloaded Function::eval_LRXB()
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
Overloaded Function::eval_ALRB()
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
Overloaded Function::eval_ALRXB()
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Function_PC line_start (Function_Line line) const
overloaded Executable::line_start()
virtual void adjust_line_starts ()
overloaded Executable::adjust_line_starts
void set_locked_error_info (Error &error) const
compute lines 2 and 3 in error
const UTF8_string get_creator () const
return the entity that has created the function
void set_trace_stop (std::vector< Function_Line > &lines, bool stop)
set trace or stop vector
ErrorCode transform_multi_line_strings ()
transform a function body containing (old-style) multi-lines into a standard function body
ErrorCode transform_multi_line_strings_3 ()
transform a function body containing (new-style) multi-lines into a standard function body
void parse_body (const char *loc, bool tolerant, bool macro)
recompile the body
const std::vector< Function_Line > & get_stop_lines () const
return stop lines (from S∆fun ← lines)
const std::vector< Function_Line > & get_trace_lines () const
return trace lines (from S∆fun ← lines)
const UserFunction_header & get_header () const
return the header object (return value name, argument names, local vars, and function name) for this function
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Public Member Functions inherited from Executable
Executable (const UCS_string &ucs, bool multi_line, ParseMode pm, const char *loc)
constructor
Executable (Fun_signature sig, int lambda_num, const UCS_string &lambda_text, const char *loc)
constructor for lambdas
virtual ~Executable ()
destructor: release values held by the body
ParseMode get_parse_mode () const
the parse mode of this Executable
void clear_body ()
delete values in body and (maybe) remove lambdas
virtual UCS_string get_name () const =0
return the name of this function, or ◊ or ⍎
virtual bool cannot_suspend () const
return true iff this Executable cannot be suspended
virtual Symbol * get_sym_Z () const
return the result symbol iff this is a user defined function or operator that returns a value
virtual const UserFunction * get_exec_ufun () const
return a UserFunction * (if this is one) or else 0.
virtual bool pushes_sym (const Symbol *sym) const
return true if this Executable localizes Symbol sym
virtual UserFunction * get_exec_ufun ()
return a UserFunction * (if this is one) or else 0.
virtual Function_Line get_line (Function_PC pc) const
get the line number for pc
virtual ostream & print (ostream &out) const
print this user defined executable to out
void print_token (ostream &out) const
print this user defined executable to out
void print_text (ostream &out) const
print the text of this user defined executable to out
Token execute_body () const
execute the body of this executable
const Token_string & get_body () const
return the body of this executable
const int get_text_size () const
return number of function lines (including header line 0)
const UCS_string & get_text (int l) const
return function line n (0 = header line)
void clear_text (int l)
clear the text of line n (0 = header line)
void set_text (int l, const UCS_string &new_line)
set the text of line n (0 = header line)
UCS_string statement_text (Function_PC pc) const
return the text of statement at pc
virtual Function_PC line_start (Function_Line line) const
return the first PC of the line
virtual void adjust_line_starts ()
adjust line starts before calling Parser::remove_void_token(body)
void set_error_info (Error &error, Function_PC2 range) const
compute lines 2 and 3 in error
Function_PC get_statement_start (int pc) const
return the start of the statement to which pc belongs
void unmark_all_values () const
clear marked flag in all body token
int show_owners (const char *prefix, ostream &out, const Value &value) const
print all owners of value
const char * get_loc () const
say where this SI entry was allocated
void increment_refcount (const char *loc)
increment the reference counter
void decrement_refcount (const char *loc)
decrement the reference counter
Static Public Member Functions
static UserFunction * load (const char *workspace, const char *function)
)LOAD this function into the workspace named workspace. Return a pounter to this newly created function (or 0 on error).
static void load (const char *workspace, const char *function, UserFunction *&fun)
Load this function into the workspace named workspace.
static UserFunction * fix (const UCS_string &text, int &err_line, bool keep_existing, const char *loc, const UTF8_string &creator, bool tolerant)
create a user defined function according to data of length len in workspace w.
static UserFunction * fix_lambda (Symbol &var, const UCS_string &text)
(re-)create a lambda
Protected Member Functions
UserFunction (const UCS_string txt, const char *loc, const UTF8_string &_creator, bool tolerant, bool macro)
constructor for a normal (i.e. non-lambda) user defined function
virtual bool may_push_SI () const
overladed Function::may_push_SI()
virtual Token eval_fill_B (Value_P B) const
Overloaded Function::eval_fill_B()
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Overloaded Function::eval_fill_AB()
int get_error_line () const
return the line number where an error has occurred (-1 if none)
const char * get_error_info () const
return information about an error (if any)
UCS_string line_prefix (Function_Line l) const
"[nn] " prefix
Protected Member Functions inherited from Executable
void setup_lambdas ()
extract all lambda expressions from body and store them in lambdas
ShapeItem setup_one_lambda (ShapeItem b, ShapeItem end, int lambda_num)
extract one lambda expressions from body and store it in lambdas
Fun_signature compute_lambda_body (Token_string &rev_lambda_body, ShapeItem b, ShapeItem bend)
body[b ... bend] is a lambda. Move these token from this body to the body of the lambda and clear them in this body.
UCS_string extract_lambda_text (Fun_signature signature, int skip) const
extract the skip'th { ... } from the function text
ErrorCode parse_body_line (Function_Line line, const UCS_string &ucs, bool trace, bool tolerant, const char *loc, bool macro)
parse the body line number line of this function
ErrorCode parse_body_line (Function_Line line, const Token_string &tos, bool trace, bool tolerant, const char *loc)
parse the body line number line of this function
Static Protected Member Functions
static ostream & print_val_or_fun (ostream &out, Token &tok)
helper function to print token with Function or Value content
Static Protected Member Functions inherited from Executable
static void reverse_statement_token (Token_string &tos)
reverse the token order in every statement of tos
static void reverse_all_token (Token_string &tos)
reverse the token order of the entire Token_string
Protected Attributes
UserFunction_header header
the header (line [0]) of the user-defined function
std::vector< Function_PC > line_starts
std::vector< Function_Line > stop_lines
stop lines (from S∆fun ← lines)
std::vector< Function_Line > trace_lines
trace lines (from S∆fun ← lines)
int exec_properties [4]
execution properties as per 3⎕AT
const UTF8_string creator
the entity (∇ editor, ⎕FX, or filename) that has created this function
int error_line
the line number where an error has occurred (-1 if none)
const char * error_info
information about an error (if any)
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Protected Attributes inherited from Executable
const char * alloc_loc
where this SI entry was allocated
const ParseMode pmode
the mode this Executable
UCS_string_vector text
the program text from which body was created
Token_string body
The token to be executed. They are organized line by line and statement by statement, but the token within a statement reversed due to the right-to-left execution of APL.
int refcount
reference counter (for lambdas)
Additional Inherited Members
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Detailed Description
One user-defined function.
Definition at line 36 of file UserFunction.hh.
Constructor & Destructor Documentation
UserFunction() [1/2]
UserFunction::UserFunction (Fun_signature sig, int lambda_num, const UCS_string & text, Token_string & body)
constructor for a lambda
Definition at line 102 of file UserFunction.cc.
References UserFunction_header::A(), UserFunction_header::add_local_var(), UserFunction_header::B(), error_info, error_line, exec_properties, UserFunction_header::get_error(), UserFunction_header::get_error_info(), header, line_starts, UserFunction_header::LO(), Executable::parse_body_line(), UserFunction_header::reverse_local_vars(), UserFunction_header::RO(), Function::set_creation_time(), Executable::setup_lambdas(), and Function::tag.
~UserFunction()
UserFunction::~UserFunction ()
Destructor.
Definition at line 151 of file UserFunction.cc.
References get_name().
UserFunction() [2/2]
UserFunction::UserFunction (const UCS_string txt, const char * loc, const UTF8_string & _creator, bool tolerant, bool macro) protected
constructor for a normal (i.e. non-lambda) user defined function
Definition at line 42 of file UserFunction.cc.
References UserFunction_header::A(), UserFunction_header::B(), UserPreferences::discard_indentation, error_info, error_line, exec_properties, UserFunction_header::get_error(), UserFunction_header::get_error_info(), Executable::get_text(), Executable::get_text_size(), header, line_starts, UserFunction_header::LO(), parse_body(), UCS_string::remove_leading_and_trailing_whitespaces(), UserFunction_header::RO(), Function::set_creation_time(), Executable::set_text(), and Function::tag.
Member Function Documentation
add_label()
void UserFunction::add_label (Symbol * sym, Function_Line line) inline
add a label
Definition at line 111 of file UserFunction.hh.
References UserFunction_header::add_label(), and header.
Referenced by Executable::parse_body_line().
adjust_line_starts()
void UserFunction::adjust_line_starts () virtual
overloaded Executable::adjust_line_starts
Reimplemented from Executable.
Definition at line 1367 of file UserFunction.cc.
References Executable::body, Function::get_tag(), and line_starts.
cannot_suspend()
virtual bool UserFunction::cannot_suspend () const inline virtual
ovewrloaded Executable::cannot_suspend
Reimplemented from Executable.
Definition at line 119 of file UserFunction.hh.
References exec_properties.
canonical()
UCS_string UserFunction::canonical (bool with_lines) const virtual
Quad_CR of this function.
Reimplemented from Function.
Definition at line 1353 of file UserFunction.cc.
References UCS_string::append(), line_prefix(), and Executable::text.
Referenced by Symbol::dump(), and XML_Saving_Archive::save_SI_entry().
destroy()
void UserFunction::destroy () virtual
overloaded Function::destroy()
Reimplemented from Function.
Definition at line 1211 of file UserFunction.cc.
References Executable::decrement_refcount(), and is_lambda().
eval_()
Token UserFunction::eval_ () const virtual
Overloaded Function::eval_()
Reimplemented from Function.
Definition at line 158 of file UserFunction.cc.
References UserFunction_header::B(), UserFunction_header::eval_common(), get_name(), header, Symbol::push(), Workspace::push_SI(), and UserFunction_header::Z().
eval_AB()
Token UserFunction::eval_AB (Value_P A, Value_P B) const virtual
Overloaded Function::eval_AB()
Reimplemented from Function.
Definition at line 221 of file UserFunction.cc.
References UserFunction_header::A(), UserFunction_header::B(), UserFunction_header::eval_common(), get_name(), header, UserFunction_header::LO(), Symbol::push(), Workspace::push_SI(), Symbol::push_value(), UserFunction_header::X(), and UserFunction_header::Z().
Referenced by Quad_EA::eval_AB(), and Quad_EB::eval_AB().
eval_ALB()
Token UserFunction::eval_ALB (Value_P A, Token & LO, Value_P B) const virtual
Overloaded Function::eval_ALB.
Reimplemented from Function.
Definition at line 326 of file UserFunction.cc.
References UserFunction_header::A(), UserFunction_header::B(), UserFunction_header::eval_common(), Token::get_apl_val(), Token::get_function(), get_name(), header, Token::is_function(), UserFunction_header::LO(), print_val_or_fun(), Symbol::push(), Symbol::push_function(), Workspace::push_SI(), Symbol::push_value(), UserFunction_header::RO(), UserFunction_header::X(), and UserFunction_header::Z().
Referenced by Bif_OPER1_EACH::eval_ALB(), and Bif_OPER2_OUTER::eval_ALRB().
eval_ALRB()
Token UserFunction::eval_ALRB (Value_P A, Token & LO, Token & RO, Value_P B) const virtual
Overloaded Function::eval_ALRB()
Reimplemented from Function.
Definition at line 446 of file UserFunction.cc.
References UserFunction_header::A(), UserFunction_header::B(), UserFunction_header::eval_common(), Token::get_apl_val(), Token::get_function(), get_name(), header, Token::is_function(), UserFunction_header::LO(), print_val_or_fun(), Symbol::push(), Symbol::push_function(), Workspace::push_SI(), Symbol::push_value(), UserFunction_header::RO(), UserFunction_header::X(), and UserFunction_header::Z().
Referenced by Bif_OPER2_INNER::eval_ALRB(), Bif_OPER2_POWER::eval_form_1(), and Bif_OPER2_POWER::eval_form_2().
eval_ALRXB()
Token UserFunction::eval_ALRXB (Value_P A, Token & LO, Token & RO, Value_P X, Value_P B) const virtual
Overloaded Function::eval_ALRXB()
Reimplemented from Function.
Definition at line 478 of file UserFunction.cc.
References UserFunction_header::A(), UserFunction_header::B(), UserFunction_header::eval_common(), Token::get_apl_val(), Token::get_function(), get_name(), header, Token::is_function(), UserFunction_header::LO(), print_val_or_fun(), Symbol::push(), Symbol::push_function(), Workspace::push_SI(), Symbol::push_value(), UserFunction_header::RO(), UserFunction_header::X(), and UserFunction_header::Z().
eval_ALXB()
Token UserFunction::eval_ALXB (Value_P A, Token & LO, Value_P X, Value_P B) const virtual
Overloaded Function::eval_ALXB()
Reimplemented from Function.
Definition at line 355 of file UserFunction.cc.
References UserFunction_header::A(), UserFunction_header::B(), UserFunction_header::eval_common(), Token::get_apl_val(), Token::get_function(), get_name(), header, Token::is_function(), UserFunction_header::LO(), print_val_or_fun(), Symbol::push(), Symbol::push_function(), Workspace::push_SI(), Symbol::push_value(), UserFunction_header::RO(), UserFunction_header::X(), and UserFunction_header::Z().
Referenced by Bif_OPER2_RANK::do_ALyXB(), and Bif_REDUCE::reduce_n_wise().
eval_AXB()
Token UserFunction::eval_AXB (Value_P A, Value_P X, Value_P B) const virtual
Overloaded Function::eval_AXB()
Reimplemented from Function.
Definition at line 246 of file UserFunction.cc.
References UserFunction_header::A(), UserFunction_header::B(), UserFunction_header::eval_common(), get_name(), header, UserFunction_header::LO(), Symbol::push(), Workspace::push_SI(), Symbol::push_value(), UserFunction_header::X(), and UserFunction_header::Z().
eval_B()
Token UserFunction::eval_B (Value_P B) const virtual
Overloaded Function::eval_B()
Reimplemented from Function.
Definition at line 174 of file UserFunction.cc.
References UserFunction_header::A(), UserFunction_header::B(), UserFunction_header::eval_common(), get_name(), header, UserFunction_header::LO(), Symbol::push(), Workspace::push_SI(), Symbol::push_value(), UserFunction_header::X(), and UserFunction_header::Z().
Referenced by Bif_OPER1_EACH::do_eval_LB(), and Quad_INP::eval_AB().
eval_fill_AB()
Token UserFunction::eval_fill_AB (Value_P A, Value_P B) const protected virtual
Overloaded Function::eval_fill_AB()
Reimplemented from Function.
Definition at line 518 of file UserFunction.cc.
eval_fill_B()
Token UserFunction::eval_fill_B (Value_P B) const protected virtual
Overloaded Function::eval_fill_B()
Reimplemented from Function.
Definition at line 511 of file UserFunction.cc.
eval_LB()
Token UserFunction::eval_LB (Token & LO, Value_P B) const virtual
Overloaded Function::eval_LB.
Reimplemented from Function.
Definition at line 272 of file UserFunction.cc.
References UserFunction_header::A(), UserFunction_header::B(), UserFunction_header::eval_common(), Token::get_apl_val(), Token::get_function(), get_name(), header, Token::is_function(), UserFunction_header::LO(), print_val_or_fun(), Symbol::push(), Symbol::push_function(), Workspace::push_SI(), Symbol::push_value(), UserFunction_header::RO(), UserFunction_header::X(), and UserFunction_header::Z().
Referenced by Bif_OPER1_EACH::do_eval_LB().
eval_LRB()
Token UserFunction::eval_LRB (Token & LO, Token & RO, Value_P B) const virtual
Overloaded Function::eval_LRB()
Reimplemented from Function.
Definition at line 385 of file UserFunction.cc.
References UserFunction_header::A(), UserFunction_header::B(), UserFunction_header::eval_common(), Token::get_apl_val(), Token::get_function(), get_name(), header, Token::is_function(), UserFunction_header::LO(), print_val_or_fun(), Symbol::push(), Symbol::push_function(), Workspace::push_SI(), Symbol::push_value(), UserFunction_header::RO(), UserFunction_header::X(), and UserFunction_header::Z().
Referenced by Bif_OPER2_POWER::eval_form_1(), and Bif_OPER2_POWER::eval_form_2().
eval_LRXB()
Token UserFunction::eval_LRXB (Token & LO, Token & RO, Value_P X, Value_P B) const virtual
Overloaded Function::eval_LRXB()
Reimplemented from Function.
Definition at line 415 of file UserFunction.cc.
References UserFunction_header::A(), UserFunction_header::B(), UserFunction_header::eval_common(), Token::get_apl_val(), Token::get_function(), get_name(), header, Token::is_function(), UserFunction_header::LO(), print_val_or_fun(), Symbol::push(), Symbol::push_function(), Workspace::push_SI(), Symbol::push_value(), UserFunction_header::RO(), UserFunction_header::X(), and UserFunction_header::Z().
eval_LXB()
Token UserFunction::eval_LXB (Token & LO, Value_P X, Value_P B) const virtual
Overloaded Function::eval_LXB()
Reimplemented from Function.
Definition at line 298 of file UserFunction.cc.
References UserFunction_header::A(), UserFunction_header::B(), UserFunction_header::eval_common(), Token::get_apl_val(), Token::get_function(), get_name(), header, Token::is_function(), UserFunction_header::LO(), print_val_or_fun(), Symbol::push(), Symbol::push_function(), Workspace::push_SI(), Symbol::push_value(), UserFunction_header::RO(), UserFunction_header::X(), and UserFunction_header::Z().
Referenced by Bif_OPER2_RANK::do_LyXB(), Bif_REDUCE::reduce(), and Bif_SCAN::scan().
eval_XB()
Token UserFunction::eval_XB (Value_P X, Value_P B) const virtual
Overloaded Function::eval_XB()
Reimplemented from Function.
Definition at line 197 of file UserFunction.cc.
References UserFunction_header::A(), UserFunction_header::B(), UserFunction_header::eval_common(), get_name(), header, UserFunction_header::LO(), Symbol::push(), Workspace::push_SI(), Symbol::push_value(), UserFunction_header::X(), and UserFunction_header::Z().
fix()
UserFunction * UserFunction::fix (const UCS_string & text, int & err_line, bool keep_existing, const char * loc, const UTF8_string & creator, bool tolerant) static
create a user defined function according to data of length len in workspace w.
Definition at line 1029 of file UserFunction.cc.
References Symbol::cant_be_defined(), creator, UserFunction_header::FUN(), get_error_info(), get_error_line(), get_func_ufun(), Symbol::get_function(), UserFunction_header::get_name(), Executable::get_text(), Executable::get_text_size(), header, UserFunction_header::LO(), Workspace::lookup_symbol(), print(), Symbol::set_NC(), and Executable::text.
Referenced by Quad_FX::do_quad_FX(), Nabla::edit(), load(), and XML_Loading_Archive::read_Function().
fix_lambda()
UserFunction * UserFunction::fix_lambda (Symbol & var, const UCS_string & text) static
(re-)create a lambda
Definition at line 1133 of file UserFunction.cc.
References UCS_string::append(), UCS_string::back(), Executable::body, UCS_string::pop_back(), and Executable::text.
Referenced by XML_Loading_Archive::read_Function(), and XML_Loading_Archive::read_lambda().
get_creator()
const UTF8_string UserFunction::get_creator () const inline
return the entity that has created the function
Definition at line 235 of file UserFunction.hh.
References creator.
Referenced by print_properties().
get_error_info()
const char * UserFunction::get_error_info () const inline protected
return information about an error (if any)
Definition at line 284 of file UserFunction.hh.
References error_info.
Referenced by fix().
get_error_line()
int UserFunction::get_error_line () const inline protected
return the line number where an error has occurred (-1 if none)
Definition at line 280 of file UserFunction.hh.
References error_line.
Referenced by fix().
get_exec_properties()
virtual const int * UserFunction::get_exec_properties () const inline virtual
return the execution properties (dyadic ⎕FX) of this defined function
Reimplemented from Function.
Definition at line 115 of file UserFunction.hh.
References exec_properties.
Referenced by Symbol::dump(), StateIndicator::statement_result(), and Error::update_error_info().
get_exec_ufun() [1/2]
virtual UserFunction * UserFunction::get_exec_ufun () inline virtual
overloaded Executable::get_exec_ufun()
Reimplemented from Executable.
Definition at line 67 of file UserFunction.hh.
get_exec_ufun() [2/2]
virtual const UserFunction * UserFunction::get_exec_ufun () const inline virtual
overloaded Executable::get_exec_ufun()
Reimplemented from Executable.
Definition at line 59 of file UserFunction.hh.
Referenced by Quad_ES::event_simulate().
get_fun_valence()
virtual int UserFunction::get_fun_valence () const inline virtual
overloaded Function::get_fun_valence()
Reimplemented from Function.
Definition at line 71 of file UserFunction.hh.
References UserFunction_header::get_fun_valence(), and header.
get_func_ufun()
virtual const UserFunction * UserFunction::get_func_ufun () const inline virtual
overloaded Function::get_func_ufun()
Reimplemented from Function.
Definition at line 63 of file UserFunction.hh.
Referenced by Doxy::add_fun_to_call_graph(), Symbol::assign_named_lambda(), Executable::clear_body(), Command::cmd_HELP(), Symbol::dump(), XML_Loading_Archive::find_lambda(), fix(), Doxy::functions_table(), Stop_Trace::locate_fun(), Doxy::make_call_graph(), XML_Loading_Archive::read_UserFunction(), and Executable::unmark_all_values().
get_header()
const UserFunction_header & UserFunction::get_header () const inline
return the header object (return value name, argument names, local vars, and function name) for this function
Definition at line 262 of file UserFunction.hh.
References header.
Referenced by Doxy::bold_name().
get_line()
Function_Line UserFunction::get_line (Function_PC pc) const virtual
overloaded Executable::get_line()
Reimplemented from Executable.
Definition at line 1337 of file UserFunction.cc.
References line_starts.
Referenced by get_name_and_line().
get_local_var()
const Symbol * UserFunction::get_local_var (ShapeItem idx) const inline
return the idx'th local variable
Definition at line 103 of file UserFunction.hh.
References UserFunction_header::get_local_var(), and header.
Referenced by Symbol::dump(), help(), and pushes_sym().
get_macnum()
virtual int UserFunction::get_macnum () const inline virtual
return the macro number (if this function is one) or -1
Reimplemented in Macro.
Definition at line 55 of file UserFunction.hh.
Referenced by XML_Saving_Archive::save_Function(), and XML_Saving_Archive::save_SI_entry().
get_name()
virtual UCS_string UserFunction::get_name () const inline virtual
return the name of this function
Implements Executable.
Definition at line 130 of file UserFunction.hh.
References UserFunction_header::get_name(), and header.
Referenced by Workspace::cleanup_expunged(), Quad_CR::do_eval_B(), eval_(), eval_AB(), eval_ALB(), eval_ALRB(), eval_ALRXB(), eval_ALXB(), eval_AXB(), eval_B(), eval_LB(), eval_LRB(), eval_LRXB(), eval_LXB(), eval_XB(), Quad_ES::event_simulate(), XML_Loading_Archive::find_lambda(), Doxy::functions_table(), Workspace::pop_SI(), XML_Saving_Archive::save_Function_name(), XML_Saving_Archive::save_SI_entry(), StateIndicator::statement_result(), StateIndicator::uses_function(), and ~UserFunction().
get_name_and_line()
UCS_string UserFunction::get_name_and_line (Function_PC pc) const
return e.g. 'FOO[10]'
Definition at line 1315 of file UserFunction.cc.
References UCS_string::append(), UCS_string::append_number(), Executable::body, Workspace::find_lambda_name(), get_line(), UserFunction_header::get_name(), header, and UCS_string::size().
Referenced by StateIndicator::list(), StateIndicator::print(), Doxy::SI_table(), and Error::update_error_info().
get_oper_valence()
virtual int UserFunction::get_oper_valence () const inline virtual
overloaded Function::get_oper_valence()
Reimplemented from Function.
Definition at line 75 of file UserFunction.hh.
References UserFunction_header::get_oper_valence(), and header.
get_stop_lines()
const std::vector< Function_Line > & UserFunction::get_stop_lines () const inline
return stop lines (from S∆fun ← lines)
Definition at line 253 of file UserFunction.hh.
References stop_lines.
Referenced by Quad_STOP::eval_AB(), Quad_STOP::eval_B(), and Nabla::open_existing_function().
get_sym_Z()
virtual Symbol * UserFunction::get_sym_Z () const inline virtual
overloaded Executable::get_sym_Z()
Reimplemented from Executable.
Definition at line 177 of file UserFunction.hh.
References header, and UserFunction_header::Z().
get_trace_lines()
const std::vector< Function_Line > & UserFunction::get_trace_lines () const inline
return trace lines (from S∆fun ← lines)
Definition at line 257 of file UserFunction.hh.
References trace_lines.
Referenced by Quad_TRACE::eval_AB(), Quad_TRACE::eval_B(), and Nabla::open_existing_function().
has_alpha()
virtual bool UserFunction::has_alpha () const inline virtual
Overloaded Function::has_alpha()
Reimplemented from Function.
Definition at line 174 of file UserFunction.hh.
has_axis()
virtual bool UserFunction::has_axis () const inline virtual
overloaded Function::has_axis()
Reimplemented from Function.
Definition at line 83 of file UserFunction.hh.
References UserFunction_header::has_axis(), and header.
has_result()
virtual bool UserFunction::has_result () const inline virtual
overloaded Function::has_result()
Implements Function.
Definition at line 79 of file UserFunction.hh.
References UserFunction_header::has_result(), and header.
help()
void UserFunction::help (ostream & out) const
print help for this function on out (for the)HELP command)
Definition at line 1238 of file UserFunction.cc.
References Executable::body, get_local_var(), Symbol::get_name(), Executable::get_text(), Executable::get_text_size(), is_lambda(), local_var_count(), UCS_string::remove_leading_and_trailing_whitespaces(), and UCS_string::size().
Referenced by Command::cmd_HELP().
is_defined()
virtual bool UserFunction::is_defined () const inline virtual
overloaded Function::is_defined()
Reimplemented from Function.
Definition at line 51 of file UserFunction.hh.
is_lambda()
virtual bool UserFunction::is_lambda () const inline virtual
overloaded Function::is_lambda()
Reimplemented from Function.
Definition at line 47 of file UserFunction.hh.
References UserFunction_header::get_name(), and header.
Referenced by Executable::clear_body(), Executable::decrement_refcount(), destroy(), Symbol::dump(), help(), XML_Saving_Archive::save_SI_entry(), and Executable::unmark_all_values().
is_operator()
virtual bool UserFunction::is_operator () const inline virtual
Overloaded Function::is_operator.
Reimplemented from Function.
Definition at line 107 of file UserFunction.hh.
References header, and UserFunction_header::is_operator().
line_prefix()
UCS_string UserFunction::line_prefix (Function_Line l) const protected
"[nn] " prefix
Definition at line 1423 of file UserFunction.cc.
References Executable::text.
Referenced by canonical().
line_start()
Function_PC UserFunction::line_start (Function_Line line) const virtual
overloaded Executable::line_start()
Reimplemented from Executable.
Definition at line 1399 of file UserFunction.cc.
References line_starts.
load() [1/2]
UserFunction * UserFunction::load (const char * workspace, const char * function) static
)LOAD this function into the workspace named workspace. Return a pounter to this newly created function (or 0 on error).
Definition at line 938 of file UserFunction.cc.
References load(), and Error::print().
Referenced by load(), and save().
load() [2/2]
void UserFunction::load (const char * workspace, const char * function, UserFunction *& fun) static
Load this function into the workspace named workspace.
Definition at line 963 of file UserFunction.cc.
References UTF8_string::back(), error_line, fix(), load(), and UTF8_string::pop_back().
local_var_count()
ShapeItem UserFunction::local_var_count () const inline
return the number of local variables
Definition at line 99 of file UserFunction.hh.
References header, and UserFunction_header::local_var_count().
Referenced by Symbol::dump(), help(), and pushes_sym().
localizes()
bool UserFunction::localizes (const Symbol * sym) const inline
return true if this function localizes sym
Definition at line 87 of file UserFunction.hh.
References header, and UserFunction_header::localizes().
Referenced by Doxy::add_fun_to_call_graph().
may_push_SI()
virtual bool UserFunction::may_push_SI () const inline protected virtual
overladed Function::may_push_SI()
Reimplemented from Function.
Definition at line 271 of file UserFunction.hh.
parse_body()
void UserFunction::parse_body (const char * loc, bool tolerant, bool macro)
recompile the body
Definition at line 806 of file UserFunction.cc.
References UCS_string::append(), Executable::body, Executable::clear_body(), UCS_string::double_quote_count(), error_line, UserFunction_header::get_name(), Executable::get_text(), Executable::get_text_size(), header, line_starts, UserPreferences::multi_line_strings, UserPreferences::multi_line_strings_3, Executable::parse_body_line(), Executable::setup_lambdas(), UCS_string::size(), stop_lines, Executable::text, trace_lines, transform_multi_line_strings(), transform_multi_line_strings_3(), and UserFunction_header::Z().
Referenced by set_trace_stop(), and UserFunction().
pc_for_line()
Function_PC UserFunction::pc_for_line (Function_Line line) const
return the pc of the first token in line l (valid line), or the pc of the last token in the function (invalid line)
Definition at line 1020 of file UserFunction.cc.
References Executable::body, and line_starts.
Referenced by StateIndicator::goon(), and StateIndicator::jump().
pop_local_vars()
void UserFunction::pop_local_vars () const inline
pop all
Definition at line 91 of file UserFunction.hh.
References header, and UserFunction_header::pop_local_vars().
Referenced by StateIndicator::~StateIndicator().
print()
ostream & UserFunction::print (ostream & out) const virtual
overloaded Executable::print()
Reimplemented from Executable.
Definition at line 1287 of file UserFunction.cc.
References UserFunction_header::get_name(), and header.
Referenced by fix().
print_local_vars()
void UserFunction::print_local_vars (ostream & out) const inline
print the local variables for command)SINL
Definition at line 95 of file UserFunction.hh.
References header, and UserFunction_header::print_local_vars().
Referenced by StateIndicator::list(), and Doxy::SI_table().
print_properties()
void UserFunction::print_properties (ostream & out, int indent) const virtual
Overloaded Function::print_properties()
Implements Function.
Definition at line 1305 of file UserFunction.cc.
References Executable::body, get_creator(), header, line_starts, and UserFunction_header::print_properties().
print_val_or_fun()
ostream & UserFunction::print_val_or_fun (ostream & out, Token & tok) static protected
helper function to print token with Function or Value content
Definition at line 1412 of file UserFunction.cc.
References Token::get_function(), Token::is_apl_val(), Token::is_function(), and Token::is_void().
Referenced by eval_ALB(), eval_ALRB(), eval_ALRXB(), eval_ALXB(), eval_LB(), eval_LRB(), eval_LRXB(), and eval_LXB().
pushes_sym()
bool UserFunction::pushes_sym (const Symbol * sym) const virtual
overloaded Executable::pushes_sym() const
Reimplemented from Executable.
Definition at line 1220 of file UserFunction.cc.
References UserFunction_header::A(), UserFunction_header::B(), get_local_var(), header, UserFunction_header::LO(), local_var_count(), UserFunction_header::RO(), UserFunction_header::X(), and UserFunction_header::Z().
set_exec_properties()
void UserFunction::set_exec_properties (const int * props) inline
set execution properties (as per A ⎕FX)
Definition at line 123 of file UserFunction.hh.
References exec_properties.
Referenced by Nabla::edit(), and XML_Loading_Archive::read_Function().
set_locked_error_info()
void UserFunction::set_locked_error_info (Error & error) const
compute lines 2 and 3 in error
Definition at line 525 of file UserFunction.cc.
References UserFunction_header::A(), UCS_string::append(), UserFunction_header::B(), UTF8_string::c_str(), Symbol::get_apl_value(), Symbol::get_name(), UserFunction_header::get_name(), header, and UCS_string::size().
Referenced by Error::update_error_info().
set_trace_stop()
void UserFunction::set_trace_stop (std::vector< Function_Line > & lines, bool stop)
set trace or stop vector
Definition at line 575 of file UserFunction.cc.
References line_starts, parse_body(), stop_lines, and trace_lines.
Referenced by Stop_Trace::assign(), and Nabla::edit().
transform_multi_line_strings()
ErrorCode UserFunction::transform_multi_line_strings ()
transform a function body containing (old-style) multi-lines into a standard function body
Definition at line 612 of file UserFunction.cc.
References Executable::clear_text(), UCS_string::do_escape(), UCS_string::double_quote_count(), Executable::get_text(), Executable::get_text_size(), Executable::set_text(), and Executable::text.
Referenced by parse_body().
transform_multi_line_strings_3()
ErrorCode UserFunction::transform_multi_line_strings_3 ()
transform a function body containing (new-style) multi-lines into a standard function body
Definition at line 702 of file UserFunction.cc.
References Executable::clear_text(), UCS_string::do_escape(), UCS_string::ends_with(), Executable::get_text(), Executable::get_text_size(), Executable::set_text(), UCS_string::size(), and Executable::text.
Referenced by parse_body().
Member Data Documentation
creator
const UTF8_string UserFunction::creator protected
the entity (∇ editor, ⎕FX, or filename) that has created this function
Definition at line 329 of file UserFunction.hh.
Referenced by fix(), and get_creator().
error_info
const char* UserFunction::error_info protected
information about an error (if any)
Definition at line 335 of file UserFunction.hh.
Referenced by get_error_info(), Macro::Macro(), and UserFunction().
error_line
int UserFunction::error_line protected
the line number where an error has occurred (-1 if none)
Definition at line 332 of file UserFunction.hh.
Referenced by get_error_line(), load(), Macro::Macro(), parse_body(), and UserFunction().
exec_properties
int UserFunction::exec_properties[4] protected
execution properties as per 3⎕AT
Definition at line 326 of file UserFunction.hh.
Referenced by cannot_suspend(), get_exec_properties(), set_exec_properties(), and UserFunction().
header
UserFunction_header UserFunction::header protected
the header (line [0]) of the user-defined function
Definition at line 294 of file UserFunction.hh.
Referenced by add_label(), eval_(), eval_AB(), eval_ALB(), eval_ALRB(), eval_ALRXB(), eval_ALXB(), eval_AXB(), eval_B(), eval_LB(), eval_LRB(), eval_LRXB(), eval_LXB(), eval_XB(), fix(), get_fun_valence(), get_header(), get_local_var(), get_name(), get_name_and_line(), get_oper_valence(), get_sym_Z(), has_axis(), has_result(), is_lambda(), is_operator(), local_var_count(), localizes(), parse_body(), pop_local_vars(), print(), print_local_vars(), print_properties(), pushes_sym(), set_locked_error_info(), and UserFunction().
line_starts
std::vector<Function_PC> UserFunction::line_starts protected
Offsets to the first token in every line (for jumps). lines[0] points to the last line, which is automatically added and is TOK_RETURN_VOID for void functions and TOK_RETURN_VALUET for functions returning a value.
An N line function:
[0] R←A FOO B [1] L1: xxx ... [N-1] yyy
will, for example, have a N+1 element jump vector:
[0] goto end of function -----------—+ [1] L1: xxx | ... | [N-1] yyy | [N] TOK_RETURN_SYMBOL or TOK_RETURN_VOID <–+
Definition at line 317 of file UserFunction.hh.
Referenced by adjust_line_starts(), get_line(), line_start(), parse_body(), pc_for_line(), print_properties(), set_trace_stop(), and UserFunction().
stop_lines
std::vector<Function_Line> UserFunction::stop_lines protected
stop lines (from S∆fun ← lines)
Definition at line 320 of file UserFunction.hh.
Referenced by get_stop_lines(), parse_body(), and set_trace_stop().
trace_lines
std::vector<Function_Line> UserFunction::trace_lines protected
trace lines (from S∆fun ← lines)
Definition at line 323 of file UserFunction.hh.
Referenced by get_trace_lines(), parse_body(), and set_trace_stop().
The documentation for this class was generated from the following files:
src/UserFunction.hh
src/UserFunction.cc