GNU APL: CollatingCache Class Reference
CollatingCache Class Reference
A cache for speeding up dyadic ⍋ and ⍒
#include <Bif_F12_SORT.hh>
Public Member Functions
CollatingCache (const Value &A, const Cell *base, ShapeItem clen)
constructor: cache of rank r and comparison length clen
sRank get_rank () const
return the number of dimensions of the collating sequence
ShapeItem get_comp_len () const
return the number of items to compare
ShapeItem find_entry (Unicode uni) const
find (the index of) the entry for uni
Static Public Member Functions
static bool greater_vec (const IntCell &ia, const IntCell &ib, const void *comp_arg)
compare cache items ia and ib ascendingly. comp_arg is a CollatingCache pointer
static bool smaller_vec (const IntCell &ia, const IntCell &ib, const void *comp_arg)
compare cache items ia and ib descendingly. comp_arg is a CollatingCache pointer
Protected Attributes
const sRank rank
the rank of the collating sequence
const Cell * base_B1
start of B.s ravel, ⎕IO adjusted
const ShapeItem comp_len
the number of items to compare
Detailed Description
A cache for speeding up dyadic ⍋ and ⍒
A collating cache which is the internal representation of the left argument A of dydic A⍋B or A⍒B
Definition at line 93 of file Bif_F12_SORT.hh.
Constructor & Destructor Documentation
CollatingCache()
CollatingCache::CollatingCache (const Value & A, const Cell * base, ShapeItem clen)
constructor: cache of rank r and comparison length clen
Definition at line 36 of file Bif_F12_SORT.cc.
References UCS_string::append(), CollatingCacheEntry::ce_shape, find_entry(), Shape::get_rank(), Shape::get_shape_item(), Shape::set_shape_item(), UCS_string::size(), and UCS_string::unique().
Member Function Documentation
find_entry()
ShapeItem CollatingCache::find_entry (Unicode uni) const
find (the index of) the entry for uni
Definition at line 138 of file Bif_F12_SORT.cc.
References CollatingCacheEntry::compare_chars().
Referenced by CollatingCache(), and Bif_F12_SORT::sort_collating().
get_comp_len()
ShapeItem CollatingCache::get_comp_len () const inline
return the number of items to compare
Definition at line 103 of file Bif_F12_SORT.hh.
References comp_len.
Referenced by greater_vec(), and smaller_vec().
get_rank()
sRank CollatingCache::get_rank () const inline
return the number of dimensions of the collating sequence
Definition at line 100 of file Bif_F12_SORT.hh.
References rank.
Referenced by greater_vec(), and smaller_vec().
greater_vec()
bool CollatingCache::greater_vec (const IntCell & ia, const IntCell & ib, const void * comp_arg) static
compare cache items ia and ib ascendingly. comp_arg is a CollatingCache pointer
Definition at line 87 of file Bif_F12_SORT.cc.
References base_B1, comp_len, get_comp_len(), Cell::get_int_value(), IntCell::get_int_value(), get_rank(), and rank.
Referenced by Bif_F12_SORT::sort_collating().
smaller_vec()
bool CollatingCache::smaller_vec (const IntCell & ia, const IntCell & ib, const void * comp_arg) static
compare cache items ia and ib descendingly. comp_arg is a CollatingCache pointer
Definition at line 113 of file Bif_F12_SORT.cc.
References base_B1, comp_len, get_comp_len(), Cell::get_int_value(), IntCell::get_int_value(), get_rank(), and rank.
Referenced by Bif_F12_SORT::sort_collating().
Member Data Documentation
base_B1
const Cell* CollatingCache::base_B1 protected
start of B.s ravel, ⎕IO adjusted
Definition at line 124 of file Bif_F12_SORT.hh.
Referenced by greater_vec(), and smaller_vec().
comp_len
const ShapeItem CollatingCache::comp_len protected
the number of items to compare
Definition at line 127 of file Bif_F12_SORT.hh.
Referenced by get_comp_len(), greater_vec(), and smaller_vec().
rank
const sRank CollatingCache::rank protected
the rank of the collating sequence
Definition at line 120 of file Bif_F12_SORT.hh.
Referenced by get_rank(), greater_vec(), and smaller_vec().
The documentation for this class was generated from the following files:
src/Bif_F12_SORT.hh
src/Bif_F12_SORT.cc