GNU APL: Quad_SVx Class Reference
Quad_SVx Class Reference
Base class for ⎕SVC, ⎕SVE, ⎕SVO, ⎕SVQ, ⎕SVR, and ⎕SVS.
#include <Quad_SVx.hh>
Static Public Member Functions
static void start_AP (AP_num proc)
start the auxiliary processor proc
Static Protected Member Functions
static bool is_executable (const char *filename)
return true iff filename is executable by everybody
static void disconnect (AP_num proc)
disconnect from auxiliary processor proc if connected.
Detailed Description
Base class for ⎕SVC, ⎕SVE, ⎕SVO, ⎕SVQ, ⎕SVR, and ⎕SVS.
some helper functions to start auxiliary processors
Definition at line 30 of file Quad_SVx.hh.
Member Function Documentation
is_executable()
bool Quad_SVx::is_executable (const char * file_and_args) static protected
return true iff filename is executable by everybody
return true iff filename is an executable file
Definition at line 77 of file Quad_SVx.cc.
Referenced by Quad_SVQ::get_processors(), and start_AP().
start_AP()
void Quad_SVx::start_AP (AP_num proc) static
start the auxiliary processor proc
Definition at line 87 of file Quad_SVx.cc.
References LibPaths::get_APL_bin_path(), ProcessorID::get_own_ID(), ProcessorID::get_parent_ID(), is_executable(), UserPreferences::system_do_svars, and UserPreferences::user_do_svars.
Referenced by Quad_SVO::share_one_variable().
The documentation for this class was generated from the following files:
src/Quad_SVx.hh
src/Quad_SVx.cc