GNU APL: DZ Class Reference
DZ Class Reference
A single double or complex number.
#include <LApack.hh>
Static Public Member Functions
static bool is_ZZ (DD x)
return true if the template argument (DD or ZZ) is complex (i.e. ZZ)
static bool is_ZZ (ZZ z)
return true if the template argument (DD or ZZ) is complex (i.e. ZZ)
static APL_Float get_real (DD x)
return the real part of x
static APL_Float get_imag (DD x)
return the imaginary part of x
static APL_Float get_real (ZZ z)
return the real part of x
static APL_Float get_imag (ZZ z)
return the imaginary part of x
static void set_real (DD &y, DD x)
set the real part of x
static void set_imag (DD &y, DD x)
set the imaginary part of x
static void set_real (ZZ &y, DD x)
set the real part of x
static void set_imag (ZZ &y, DD x)
set the imaginary part of x
static void conjugate (DD x)
conjugate x
static void conjugate (ZZ &z)
conjugate z
static DD CONJ (DD x)
return x conjugated
static ZZ CONJ (const ZZ &z)
return z conjugated
static DD inv (DD dd)
return the inverse of dd
static ZZ inv (const ZZ &zz)
return the inverse of zz
Detailed Description
A single double or complex number.
a single double or complex number. This class contains wrappers to double or complex numbers so that they can be used in templates.
Definition at line 170 of file LApack.hh.
Member Function Documentation
CONJ() [1/2]
static ZZ DZ::CONJ (const ZZ & z) inline static
return z conjugated
Definition at line 212 of file LApack.hh.
References ZZ::imag(), and ZZ::real().
CONJ() [2/2]
static DD DZ::CONJ (DD x) inline static
return x conjugated
Definition at line 209 of file LApack.hh.
conjugate() [1/2]
static void DZ::conjugate (DD x) inline static
conjugate x
Definition at line 203 of file LApack.hh.
conjugate() [2/2]
static void DZ::conjugate (ZZ & z) inline static
conjugate z
Definition at line 206 of file LApack.hh.
References ZZ::conjugate().
get_imag() [1/2]
static APL_Float DZ::get_imag (DD x) inline static
return the imaginary part of x
Definition at line 182 of file LApack.hh.
get_imag() [2/2]
static APL_Float DZ::get_imag (ZZ z) inline static
return the imaginary part of x
Definition at line 188 of file LApack.hh.
References ZZ::imag().
get_real() [1/2]
static APL_Float DZ::get_real (DD x) inline static
return the real part of x
Definition at line 179 of file LApack.hh.
Referenced by Matrix< T >::max_norm().
get_real() [2/2]
static APL_Float DZ::get_real (ZZ z) inline static
return the real part of x
Definition at line 185 of file LApack.hh.
References ZZ::real().
inv() [1/2]
static ZZ DZ::inv (const ZZ & zz) inline static
return the inverse of zz
Definition at line 218 of file LApack.hh.
References ZZ::imag(), and ZZ::real().
inv() [2/2]
static DD DZ::inv (DD dd) inline static
return the inverse of dd
Definition at line 215 of file LApack.hh.
is_ZZ() [1/2]
static bool DZ::is_ZZ (DD x) inline static
return true if the template argument (DD or ZZ) is complex (i.e. ZZ)
Definition at line 174 of file LApack.hh.
is_ZZ() [2/2]
static bool DZ::is_ZZ (ZZ z) inline static
return true if the template argument (DD or ZZ) is complex (i.e. ZZ)
Definition at line 176 of file LApack.hh.
set_imag() [1/2]
static void DZ::set_imag (DD & y, DD x) inline static
set the imaginary part of x
Definition at line 194 of file LApack.hh.
set_imag() [2/2]
static void DZ::set_imag (ZZ & y, DD x) inline static
set the imaginary part of x
Definition at line 200 of file LApack.hh.
set_real() [1/2]
static void DZ::set_real (DD & y, DD x) inline static
set the real part of x
Definition at line 191 of file LApack.hh.
set_real() [2/2]
static void DZ::set_real (ZZ & y, DD x) inline static
set the real part of x
Definition at line 197 of file LApack.hh.
The documentation for this class was generated from the following file:
src/LApack.hh