GNU APL: Value_P_Base Class Reference
Value_P_Base Class Reference
A Value smart * and access functions (except constructors)
#include <Value_P.hh>
Public Member Functions
void reset ()
decrement owner-count and reset pointer to 0
void clear (const char *loc)
reset and add value event
bool operator+ () const
return true if the pointer is valid
bool operator! () const
return true if the pointer is invalid
const Value * operator-> () const
return a const pointer to the Value (overloaded *)
Value * operator-> ()
return a pointer to the Value (overloaded ->)
const Value & operator* () const
return a const reference to the Value
Value & operator* ()
return a reference to the Value
const Value * get () const
return a const pointer to the Value
Value * get ()
return a pointer to the Value
void clear_pointer (const char *loc)
clear the pointer (and possibly add an event)
void isolate (const char *loc)
clone value if more than one Value_P points to it
Static Public Member Functions
static void decrement_owner_count (Value *&val, const char *loc)
decrement the owner count of val. The function body of this function requires Value.hh and is therefore implemented in Value.icc.
static void increment_owner_count (Value *val, const char *loc)
increment the owner count of val. The function body of this function requires Value.hh and is therefore implemented in Value.icc.
Protected Attributes
Value * value_p
pointer to the value
Friends
class PointerCell
Detailed Description
A Value smart * and access functions (except constructors)
Definition at line 38 of file Value_P.hh.
Member Function Documentation
get() [1/2]
Value * Value_P_Base::get () inline
return a pointer to the Value
Definition at line 78 of file Value_P.hh.
References value_p.
get() [2/2]
const Value * Value_P_Base::get () const inline
return a const pointer to the Value
Definition at line 74 of file Value_P.hh.
References value_p.
Referenced by Quad_XML::all_members(), Quad_JSON::APL_to_JSON_string(), Bif_COMMA::append_scalar(), Symbol::assign(), Value::assign_cellrefs(), Symbol::assign_indexed(), Symbol::assign_shared_variable(), Bif_COMMA::catenate(), PointerCell::character_representation(), Command::cmd_CHECK(), XML_node::collect(), Bif_F12_PICK::compute_item_shape(), Token::copy_1(), Parser::create_vector_value(), Bif_F12_PICK::disclose_with_axis(), Bif_OPER2_RANK::do_ALyXB(), Quad_CR::do_CR10(), Quad_CR::do_CR10_structured(), Quad_CR::do_CR10_value(), Quad_CR::do_CR26(), Quad_CR::do_CR27_28(), Quad_CR::do_CR31_32(), Quad_CR::do_CR35(), Quad_CR::do_CR39(), Quad_DLX::do_DLX(), Bif_F12_PARTITION::do_eval_B(), Bif_OPER1_EACH::do_eval_LB(), Bif_OPER2_RANK::do_LyXB(), Quad_MAP::do_map(), ScalarFunction::do_scalar_AB(), ScalarFunction::do_scalar_B(), Quad_FIO::do_sprintf(), XML_Saving_Archive::emit_cell(), XML_Saving_Archive::emit_token_val(), Bif_F12_PARTITION::enclose_with_axes(), Quad_EC::eoc(), Bif_F12_INDEX_OF::eval_AB(), Bif_F2_INDEX::eval_AB(), Quad_INP::eval_AB(), Bif_OPER1_EACH::eval_ALB(), Bif_OPER2_INNER::eval_ALRB(), Bif_OPER1_REDUCE::eval_ALXB(), Bif_OPER1_REDUCE1::eval_ALXB(), Bif_F12_PARTITION::eval_AXB(), Bif_OPER1_REDUCE::eval_AXB(), Bif_OPER1_REDUCE1::eval_AXB(), Bif_OPER1_SCAN::eval_AXB(), Bif_OPER1_SCAN1::eval_AXB(), Bif_F2_INDEX::eval_AXB(), Bif_F12_ROTATE::eval_AXB(), Bif_F12_ROTATE1::eval_AXB(), Quad_FX::eval_AXB(), Quad_GTK::eval_AXB(), Quad_RE::eval_AXB(), Quad_GTK::eval_B(), Quad_EC::eval_B(), Quad_ENV::eval_B(), Quad_SI::eval_B(), Quad_EC::eval_fill_B(), Bif_OPER1_REDUCE::eval_LXB(), Bif_OPER1_REDUCE1::eval_LXB(), Bif_OPER1_SCAN::eval_LXB(), Bif_OPER1_SCAN1::eval_LXB(), ScalarFunction::eval_scalar_AXB(), Bif_F12_PARTITION::eval_XB(), Bif_F12_PICK::eval_XB(), Bif_F12_ROTATE::eval_XB(), Bif_F12_ROTATE1::eval_XB(), Quad_FIO::eval_XB(), Quad_GTK::eval_XB(), Quad_INP::eval_XB(), ScalarFunction::expand_nested(), Token::extract_and_keep(), Bif_OPER2_INNER::fill(), Bif_F12_TAKE::first(), CDR::from_CDR(), Quad_ARG::get_apl_value(), DerivedFunction::get_AXIS(), IndexExpr::get_axis_value(), Value::get_member(), Value::get_new_member(), PointerCell::get_pointer_value(), ValueStackItem::get_val_cptr(), ValueStackItem::get_val_wptr(), Value::index(), PointerCell::init_other(), Cell::init_type(), Bif_COMMA::laminate(), XML_node::merge_range(), Token::move_1(), Token::move_2(), Quad_XML::name_split(), Quad_XML::name_unsplit(), Quad_XML::next_member(), paint_data(), Quad_JSON::parse_array(), Quad_PLOT::parse_attributes(), Quad_JSON::parse_literal(), Quad_JSON::parse_object(), Quad_JSON::parse_string(), XML_node::parse_tag(), Quad_XML::path_split(), Bif_COMMA::prepend_scalar(), Value::print_member(), Token::print_value(), Bif_F12_DOMINO::QR_factorization(), Quad_RVAL::random_nested(), Bif_REDUCE::reduce_n_wise(), Quad_RE::regex_results(), Prefix::replace_AB(), XML_Saving_Archive::save(), Executable::show_owners(), Prefix::show_owners(), Quad_TF::tf1_inv(), Quad_TF::tf2_inverse(), Quad_TF::tf3(), UCS_string::UCS_string(), Doxy::variables_table(), and Quad_XML::XML_to_APL().
operator!()
bool Value_P_Base::operator! () const inline
return true if the pointer is invalid
Definition at line 54 of file Value_P.hh.
References value_p.
operator*() [1/2]
Value & Value_P_Base::operator* () inline
return a reference to the Value
Definition at line 70 of file Value_P.hh.
References value_p.
operator*() [2/2]
const Value & Value_P_Base::operator* () const inline
return a const reference to the Value
Definition at line 66 of file Value_P.hh.
References value_p.
operator+()
bool Value_P_Base::operator+ () const inline
return true if the pointer is valid
Definition at line 50 of file Value_P.hh.
References value_p.
operator->() [1/2]
Value * Value_P_Base::operator-> () inline
return a pointer to the Value (overloaded ->)
Definition at line 62 of file Value_P.hh.
References value_p.
operator->() [2/2]
const Value * Value_P_Base::operator-> () const inline
return a const pointer to the Value (overloaded *)
Definition at line 58 of file Value_P.hh.
References value_p.
Friends And Related Function Documentation
PointerCell
friend class PointerCell friend
Definition at line 40 of file Value_P.hh.
Member Data Documentation
value_p
Value* Value_P_Base::value_p protected
pointer to the value
Definition at line 97 of file Value_P.hh.
Referenced by get(), PointerCell::is_member_anchor(), operator!(), operator*(), operator+(), operator->(), and Value_P::Value_P().
The documentation for this class was generated from the following file:
src/Value_P.hh