GNU APL: Shape3 Class Reference
Shape3 Class Reference
a shape of rank 3
#include <Shape.hh>
Public Member Functions
Shape3 (const Shape &shape, ShapeItem axis)
construct a 3-dimensional shape from a n-dimensional shape
Shape3 (ShapeItem _h, ShapeItem _m, ShapeItem _l)
construct a 3-dimensional shape from three explicit dimensions
ShapeItem h () const
the dimensions above r the axis
ShapeItem hml (ShapeItem hh, ShapeItem mm, ShapeItem ll) const
return the offset of ravel item [hh;mm;ll] (from [0;0;0])
ShapeItem m () const
the axis dimension
ShapeItem l () const
the dimensions below the axis
Public Member Functions inherited from Shape
Shape ()
constructor: shape of a scalar.
Shape (ShapeItem len)
constructor: shape of a vector of length len
Shape (ShapeItem rows, ShapeItem cols)
constructor: shape of a matrix with rows rows and cols columns
Shape (ShapeItem height, ShapeItem rows, ShapeItem cols)
constructor: shape of a cube
Shape (uRank rk, const ShapeItem *sh)
constructor: arbitrary shape
Shape (const Shape &other)
constructor: shape of another shape
Shape (const Value &A, int qio_A)
constructor: shape defined by the ravel of an APL value A throw RANK or LENGTH error where needed. Negative values are allowed in order to support e.g. ¯4 ↑ B
Shape abs () const
return a shape like this, but with negative elements made positive
Shape high_shape (uRank cnt) const
return a shape with the upper cnt dimensions of this shape
Shape low_shape (uRank cnt) const
return a shape with the lower cnt dimensions of this shape
Shape operator+ (const Shape &lower) const
catenate two shapes, this shape provides the higher dimensions while lower provides the lower dimensions of the shape returned
bool operator== (const Shape &other) const
return true iff this shape equals other
bool operator!= (const Shape &other) const
return true iff this shape is different from other
uRank get_rank () const
return the rank
ShapeItem get_shape_item (sAxis r) const
return the length of dimension r
ShapeItem get_transposed_shape_item (sAxis r) const
return the length of dimension r
ShapeItem get_first_shape_item () const
return the length of the first axis, or 1 for scalars
ShapeItem get_last_shape_item () const
return the length of the last axis, or 1 for scalars
ShapeItem get_cols () const
return the length of the last axis, or 1 for scalars
ShapeItem get_rows () const
return the product of all but the the last dimension, or 1 for scalars
void set_shape_item (sAxis r, ShapeItem sh)
modify dimension r
void recompute_volume ()
recompute volume (after changing a dimension of len 0)
void increment_shape_item (sRank r)
increment length of axis r by 1
void set_last_shape_item (ShapeItem sh)
set last dimension to sh
void add_shape_item (ShapeItem len)
add a dimension of length len at the end
void expand_rank (sRank new_rank)
possibly increase rank by prepending axes of length 1
void expand (const Shape &B)
possibly expand rank and increase axes so that B fits into this shape
Shape insert_axis (sAxis axis, ShapeItem len) const
return a shape like this, but with a new dimension of length len inserted so that Shape[axis] == len in the returned shape.
Shape without_axis (sAxis axis) const
return a shape like this, but with axis axis removed
Shape without_first_axis () const
return a shape like this, but with the first axis (↑⍴) removed
Shape without_last_axis () const
return a shape like this, but with the last axis (¯1↑⍴) removed
ShapeItem get_volume () const
return the number of ravel elements (1 for scalars,i else product of shapes)
ShapeItem get_nz_volume () const
return the number of ravel elements, but at least 1 (for empty values and scalars) else product of shapes)
bool contains_axis (sAxis ax) const
return true iff one of the shape elements is (axis) ax
bool contains (const Shape &value) const
return true iff the items of value are at most the items of this
Shape get_weights () const
return ⌽ ×\ ⍴ ⌽ this
void check_same (const Shape &B, ErrorCode rank_err, ErrorCode len_err, const char *loc) const
throw an APL error if this shape differs from shape B
bool is_empty () const
return true iff this shape is empty (some dimension is 0).
bool is_permutation () const
return reue iff this shape is a permutation of 0, 1, ... rank-1
ShapeItem ravel_pos (const Shape &idx) const
return the position of idx in the ravel.
Shape offset_to_index (ShapeItem offset, int quad_io) const
the inverse of ravel_pos()
Additional Inherited Members
Protected Attributes inherited from Shape
sRank rho_rho
the rank (number of valid shape items)
ShapeItem rho [MAX_RANK]
the shape
ShapeItem volume
+/rho
Detailed Description
a shape of rank 3
Definition at line 266 of file Shape.hh.
Constructor & Destructor Documentation
Shape3() [1/2]
Shape3::Shape3 (const Shape & shape, ShapeItem axis) inline
construct a 3-dimensional shape from a n-dimensional shape
Definition at line 270 of file Shape.hh.
References Shape::get_rank(), Shape::get_shape_item(), and Shape::rho.
Shape3() [2/2]
Shape3::Shape3 (ShapeItem _h, ShapeItem _m, ShapeItem _l) inline
construct a 3-dimensional shape from three explicit dimensions
Definition at line 282 of file Shape.hh.
Member Function Documentation
h()
ShapeItem Shape3::h () const inline
the dimensions above r the axis
Definition at line 287 of file Shape.hh.
References Shape::rho.
Referenced by Bif_COMMA::append_scalar(), Bif_COMMA::catenate(), Bif_SCAN::expand(), Bif_COMMA::laminate(), Bif_F12_PARTITION::partition(), Bif_COMMA::prepend_scalar(), Bif_REDUCE::reduce(), Bif_REDUCE::replicate(), Bif_ROTATE::reverse(), Bif_ROTATE::rotate(), and Bif_SCAN::scan().
hml()
ShapeItem Shape3::hml (ShapeItem hh, ShapeItem mm, ShapeItem ll) const inline
return the offset of ravel item [hh;mm;ll] (from [0;0;0])
Definition at line 291 of file Shape.hh.
References l(), and m().
Referenced by Bif_REDUCE::replicate(), and Bif_ROTATE::rotate().
l()
ShapeItem Shape3::l () const inline
the dimensions below the axis
Definition at line 299 of file Shape.hh.
References Shape::rho.
Referenced by Bif_COMMA::append_scalar(), Bif_COMMA::catenate(), Bif_SCAN::expand(), hml(), Bif_COMMA::laminate(), Bif_F12_PARTITION::partition(), Bif_COMMA::prepend_scalar(), Bif_REDUCE::reduce(), Bif_REDUCE::replicate(), Bif_ROTATE::reverse(), Bif_ROTATE::rotate(), and Bif_SCAN::scan().
m()
ShapeItem Shape3::m () const inline
the axis dimension
Definition at line 295 of file Shape.hh.
References Shape::rho.
Referenced by Bif_REDUCE::do_reduce(), hml(), Bif_COMMA::laminate(), Bif_F12_PARTITION::partition(), Bif_REDUCE::reduce(), Bif_REDUCE::replicate(), Bif_ROTATE::reverse(), Bif_ROTATE::rotate(), and Bif_SCAN::scan().
The documentation for this class was generated from the following file:
src/Shape.hh