GNU APL: PrintContext Class Reference
PrintContext Class Reference
Attributes that control how APL values are being printed.
#include <PrintContext.hh>
Public Member Functions
PrintContext (PrintStyle st)
constructor from another style
PrintContext (PrintStyle st, int qpp, int qpw)
constructor for given values
PrintStyle get_style () const
return the print style to be used
void set_style (PrintStyle ps)
set the print style to be used
bool get_scaled () const
return true iff exponential format shall be used
void set_scaled ()
request scaled (exponential) format
int get_PP () const
return the print precision to be used
int get_PW () const
return the print width to be used
Protected Attributes
PrintStyle style
the print style to be used
int precision
the print precision to be used
int width
the print width to be used
Detailed Description
Attributes that control how APL values are being printed.
Definition at line 28 of file PrintContext.hh.
Constructor & Destructor Documentation
PrintContext() [1/2]
PrintContext::PrintContext (PrintStyle st) inline
constructor from another style
Definition at line 32 of file PrintContext.hh.
PrintContext() [2/2]
PrintContext::PrintContext (PrintStyle st, int qpp, int qpw) inline
constructor for given values
Definition at line 39 of file PrintContext.hh.
Member Function Documentation
get_PP()
int PrintContext::get_PP () const inline
return the print precision to be used
Definition at line 58 of file PrintContext.hh.
References precision.
Referenced by ComplexCell::character_representation(), ComplexCell::need_scaling(), FloatCell::need_scaling(), and UCS_string::UCS_string().
get_PW()
int PrintContext::get_PW () const inline
return the print width to be used
Definition at line 61 of file PrintContext.hh.
References width.
Referenced by PrintBuffer::do_PrintBuffer(), PrintBuffer::pb_for_function(), and PrintBuffer::PrintBuffer().
get_scaled()
bool PrintContext::get_scaled () const inline
return true iff exponential format shall be used
Definition at line 52 of file PrintContext.hh.
References style.
Referenced by ComplexCell::character_representation(), FloatCell::character_representation(), and IntCell::character_representation().
get_style()
PrintStyle PrintContext::get_style () const inline
return the print style to be used
Definition at line 46 of file PrintContext.hh.
References style.
Referenced by CharCell::character_representation(), PointerCell::character_representation(), Quad_CR::do_CR31_32(), PrintBuffer::pb_empty(), Value::print(), Value::print1(), PrintBuffer::PrintBuffer(), Token::show_trace(), and UCS_string::UCS_string().
set_scaled()
void PrintContext::set_scaled () inline
request scaled (exponential) format
Definition at line 55 of file PrintContext.hh.
References style.
Referenced by PrintBuffer::do_PrintBuffer(), and PrintBuffer::PrintBuffer().
set_style()
void PrintContext::set_style (PrintStyle ps) inline
set the print style to be used
Definition at line 49 of file PrintContext.hh.
References style.
Referenced by Quad_CR::do_CR31_32(), Value::print(), Value::print1(), and Token::show_trace().
Member Data Documentation
precision
int PrintContext::precision protected
the print precision to be used
Definition at line 68 of file PrintContext.hh.
Referenced by get_PP().
style
PrintStyle PrintContext::style protected
the print style to be used
Definition at line 65 of file PrintContext.hh.
Referenced by get_scaled(), get_style(), set_scaled(), and set_style().
width
int PrintContext::width protected
the print width to be used
Definition at line 71 of file PrintContext.hh.
Referenced by get_PW().
The documentation for this class was generated from the following file:
src/PrintContext.hh