GNU APL: Signal_base Class Reference
Signal_base Class Reference abstract
the base class for all signal classes
#include <Svar_signals.hh>
Public Member Functions
virtual ~Signal_base ()
destructor
virtual void store (string &buffer) const =0
store (encode) the signal into buffer
virtual ostream & print (ostream &out) const =0
print the signal
virtual Signal_id get_sigID () const =0
return the ID of the signal
virtual const char * get_sigName () const =0
return the name of the ID of the signal
void bad_get (const char *signal, const char *member) const
get function for an item that is not defined for the signal
virtual uint64_t get__MAKE_OFFER__key () const
APserver request: ⎕SVO access functions for signal MAKE_OFFER...
virtual uint64_t get__RETRACT_OFFER__key () const
APserver request: ⎕SVR access functions for signal RETRACT_OFFER...
virtual uint64_t get__RETRACT_VAR__key () const
APserver request: ⎕SVR access functions for signal RETRACT_VAR...
virtual uint64_t get__SET_STATE__key () const
APserver request: set state of shared var key access functions for signal SET_STATE...
virtual uint8_t get__SET_STATE__new_state () const
< dito
virtual string get__SET_STATE__sloc () const
< dito
virtual uint64_t get__SET_CONTROL__key () const
APserver request: set control of shared var key access functions for signal SET_CONTROL...
virtual uint8_t get__SET_CONTROL__new_control () const
< dito
virtual uint64_t get__GET_VALUE__key () const
APserver request: X←SVAR access functions for signal GET_VALUE...
virtual uint64_t get__VALUE_IS__key () const
APserver result for: X←SVAR access functions for signal VALUE_IS...
virtual uint32_t get__VALUE_IS__error () const
< dito
virtual string get__VALUE_IS__error_loc () const
< dito
virtual string get__VALUE_IS__cdr_value () const
< dito
virtual uint64_t get__ASSIGN_VALUE__key () const
APserver request: SVAR←X access functions for signal ASSIGN_VALUE...
virtual string get__ASSIGN_VALUE__cdr_value () const
< dito
virtual uint64_t get__SVAR_ASSIGNED__key () const
APserver result for: SVAR←X access functions for signal SVAR_ASSIGNED...
virtual uint32_t get__SVAR_ASSIGNED__error () const
< dito
virtual string get__SVAR_ASSIGNED__error_loc () const
< dito
virtual uint64_t get__MAY_USE__key () const
APserver request: Can svar key be referenced ? access functions for signal MAY_USE...
virtual int32_t get__MAY_USE__attempt () const
< dito
virtual uint64_t get__MAY_SET__key () const
APserver request: Can svar key be assigned ? access functions for signal MAY_SET...
virtual int32_t get__MAY_SET__attempt () const
< dito
virtual uint64_t get__READ_SVAR_RECORD__key () const
APserver request: read SVAR database record from APserver.
virtual string get__SVAR_RECORD_IS__record () const
APserver result (record) for: read SVAR database record from APserver access functions for signal SVAR_RECORD_IS...
virtual uint32_t get__IS_REGISTERED_ID__proc () const
APserver request: is ID registered ? access functions for signal IS_REGISTERED_ID...
virtual uint32_t get__IS_REGISTERED_ID__parent () const
< dito
virtual uint32_t get__IS_REGISTERED_ID__grand () const
< dito
virtual uint8_t get__YES_NO__yes () const
APserver result: yes (1) or no (0) access functions for signal YES_NO...
virtual uint32_t get__REGISTER_PROCESSOR__proc () const
APserver request: register processor proc in APserver access functions for signal REGISTER_PROCESSOR...
virtual uint32_t get__REGISTER_PROCESSOR__parent () const
< dito
virtual uint32_t get__REGISTER_PROCESSOR__grand () const
< dito
virtual uint8_t get__REGISTER_PROCESSOR__evconn () const
< dito
virtual string get__REGISTER_PROCESSOR__progname () const
< dito
virtual string get__MATCH_OR_MAKE__varname () const
APserver request: match offered shared variable or make a new offer access functions for signal MATCH_OR_MAKE...
virtual uint32_t get__MATCH_OR_MAKE__to_proc () const
< dito
virtual uint32_t get__MATCH_OR_MAKE__to_parent () const
< dito
virtual uint32_t get__MATCH_OR_MAKE__to_grand () const
< dito
virtual uint32_t get__MATCH_OR_MAKE__from_proc () const
< dito
virtual uint32_t get__MATCH_OR_MAKE__from_parent () const
< dito
virtual uint32_t get__MATCH_OR_MAKE__from_grand () const
< dito
virtual uint64_t get__MATCH_OR_MAKE_RESULT__key () const
APserver result for: match or make access functions for signal MATCH_OR_MAKE_RESULT...
virtual uint64_t get__FIND_OFFERING_ID__key () const
APserver request: find processor ID that offers key access functions for signal FIND_OFFERING_ID...
virtual uint32_t get__OFFERING_ID_IS__proc () const
APserver result for: find processor ID that offers key access functions for signal OFFERING_ID_IS...
virtual uint32_t get__OFFERING_ID_IS__parent () const
< dito
virtual uint32_t get__OFFERING_ID_IS__grand () const
< dito
virtual uint32_t get__GET_OFFERING_PROCS__offered_to_proc () const
APserver request: get offering processors (⎕SVQ) access functions for signal GET_OFFERING_PROCS...
virtual string get__OFFERING_PROCS_ARE__offering_procs () const
APserver result for: get offering processors (⎕SVQ) access functions for signal OFFERING_PROCS_ARE...
virtual uint32_t get__GET_OFFERED_VARS__offered_to_proc () const
APserver request: get offered variables (⎕SVQ) access functions for signal GET_OFFERED_VARS...
virtual uint32_t get__GET_OFFERED_VARS__accepted_by_proc () const
< dito
virtual string get__OFFERED_VARS_ARE__offered_vars () const
APserver result for: get offered variables (⎕SVQ) access functions for signal OFFERED_VARS_ARE...
virtual uint64_t get__FIND_PAIRING_KEY__key () const
APserver request: find pairing key (CTL vs. DAT or Cnnn vs. Dnnn) for AP210 access functions for signal FIND_PAIRING_KEY...
virtual uint64_t get__PAIRING_KEY_IS__pairing_key () const
APserver result for: find pairing key access functions for signal PAIRING_KEY_IS...
virtual uint32_t get__GET_EVENTS__proc () const
APserver result for: find pairing key (CTL vs. DAT or Cnnn vs. Dnnn) for AP210 get events for one processor (first shared var with an event) access functions for signal GET_EVENTS...
virtual uint32_t get__GET_EVENTS__parent () const
< dito
virtual uint32_t get__GET_EVENTS__grand () const
< dito
virtual uint32_t get__CLEAR_ALL_EVENTS__proc () const
APserver request: clear all events for one processor access functions for signal CLEAR_ALL_EVENTS...
virtual uint32_t get__CLEAR_ALL_EVENTS__parent () const
< dito
virtual uint32_t get__CLEAR_ALL_EVENTS__grand () const
< dito
virtual uint64_t get__EVENTS_ARE__key () const
APserver result for: clear all events for one processor (first cleared svar access functions for signal EVENTS_ARE...
virtual uint32_t get__EVENTS_ARE__events () const
< dito
virtual uint64_t get__ADD_EVENT__key () const
APserver request: add an event for key access functions for signal ADD_EVENT...
virtual uint32_t get__ADD_EVENT__proc () const
< dito
virtual uint32_t get__ADD_EVENT__parent () const
< dito
virtual uint32_t get__ADD_EVENT__grand () const
< dito
virtual uint32_t get__ADD_EVENT__event () const
< dito
virtual uint64_t get__ASSIGN_WSWS_VAR__key () const
APserver request: ws-ws SVAR←X access functions for signal ASSIGN_WSWS_VAR...
virtual string get__ASSIGN_WSWS_VAR__cdr_value () const
< dito
virtual uint64_t get__READ_WSWS_VAR__key () const
APserver request: X←ws-ws SVAR access functions for signal READ_WSWS_VAR...
virtual string get__WSWS_VALUE_IS__cdr_value () const
APserver result for: X←ws-ws SVAR access functions for signal WSWS_VALUE_IS...
virtual string get__SVAR_DB_PRINTED__printout () const
APserver request: print the entire database (for command ]SVARS) access functions for signal PRINT_SVAR_DB...
Static Public Member Functions
static Signal_base * recv_TCP (int tcp_sock, char *buffer, int bufsize, char *&del, ostream *debug, const char **loc)
receive a signal (TCP)
Protected Member Functions
ssize_t send_TCP (int tcp_sock) const
send this signal on TCP (or AF_UNIX) socket tcp_sock
Detailed Description
the base class for all signal classes
Definition at line 344 of file Svar_signals.hh.
Constructor & Destructor Documentation
~Signal_base()
virtual Signal_base::~Signal_base () inline virtual
destructor
Definition at line 348 of file Svar_signals.hh.
Member Function Documentation
bad_get()
void Signal_base::bad_get (const char * signal, const char * member) const inline
get function for an item that is not defined for the signal
Definition at line 363 of file Svar_signals.hh.
References get_sigName().
Referenced by get__ADD_EVENT__event(), get__ADD_EVENT__grand(), get__ADD_EVENT__key(), get__ADD_EVENT__parent(), get__ADD_EVENT__proc(), get__ASSIGN_VALUE__cdr_value(), get__ASSIGN_VALUE__key(), get__ASSIGN_WSWS_VAR__cdr_value(), get__ASSIGN_WSWS_VAR__key(), get__CLEAR_ALL_EVENTS__grand(), get__CLEAR_ALL_EVENTS__parent(), get__CLEAR_ALL_EVENTS__proc(), get__EVENTS_ARE__events(), get__EVENTS_ARE__key(), get__FIND_OFFERING_ID__key(), get__FIND_PAIRING_KEY__key(), get__GET_EVENTS__grand(), get__GET_EVENTS__parent(), get__GET_EVENTS__proc(), get__GET_OFFERED_VARS__accepted_by_proc(), get__GET_OFFERED_VARS__offered_to_proc(), get__GET_OFFERING_PROCS__offered_to_proc(), get__GET_VALUE__key(), get__IS_REGISTERED_ID__grand(), get__IS_REGISTERED_ID__parent(), get__IS_REGISTERED_ID__proc(), get__MAKE_OFFER__key(), get__MATCH_OR_MAKE__from_grand(), get__MATCH_OR_MAKE__from_parent(), get__MATCH_OR_MAKE__from_proc(), get__MATCH_OR_MAKE__to_grand(), get__MATCH_OR_MAKE__to_parent(), get__MATCH_OR_MAKE__to_proc(), get__MATCH_OR_MAKE__varname(), get__MATCH_OR_MAKE_RESULT__key(), get__MAY_SET__attempt(), get__MAY_SET__key(), get__MAY_USE__attempt(), get__MAY_USE__key(), get__OFFERED_VARS_ARE__offered_vars(), get__OFFERING_ID_IS__grand(), get__OFFERING_ID_IS__parent(), get__OFFERING_ID_IS__proc(), get__OFFERING_PROCS_ARE__offering_procs(), get__PAIRING_KEY_IS__pairing_key(), get__READ_SVAR_RECORD__key(), get__READ_WSWS_VAR__key(), get__REGISTER_PROCESSOR__evconn(), get__REGISTER_PROCESSOR__grand(), get__REGISTER_PROCESSOR__parent(), get__REGISTER_PROCESSOR__proc(), get__REGISTER_PROCESSOR__progname(), get__RETRACT_OFFER__key(), get__RETRACT_VAR__key(), get__SET_CONTROL__key(), get__SET_CONTROL__new_control(), get__SET_STATE__key(), get__SET_STATE__new_state(), get__SET_STATE__sloc(), get__SVAR_ASSIGNED__error(), get__SVAR_ASSIGNED__error_loc(), get__SVAR_ASSIGNED__key(), get__SVAR_DB_PRINTED__printout(), get__SVAR_RECORD_IS__record(), get__VALUE_IS__cdr_value(), get__VALUE_IS__error(), get__VALUE_IS__error_loc(), get__VALUE_IS__key(), get__WSWS_VALUE_IS__cdr_value(), and get__YES_NO__yes().
get__ADD_EVENT__event()
virtual uint32_t Signal_base::get__ADD_EVENT__event () const inline virtual
< dito
Reimplemented in ADD_EVENT_c.
Definition at line 623 of file Svar_signals.hh.
References bad_get().
get__ADD_EVENT__grand()
virtual uint32_t Signal_base::get__ADD_EVENT__grand () const inline virtual
< dito
Reimplemented in ADD_EVENT_c.
Definition at line 621 of file Svar_signals.hh.
References bad_get().
get__ADD_EVENT__key()
virtual uint64_t Signal_base::get__ADD_EVENT__key () const inline virtual
APserver request: add an event for key access functions for signal ADD_EVENT...
< dito
Reimplemented in ADD_EVENT_c.
Definition at line 615 of file Svar_signals.hh.
References bad_get().
get__ADD_EVENT__parent()
virtual uint32_t Signal_base::get__ADD_EVENT__parent () const inline virtual
< dito
Reimplemented in ADD_EVENT_c.
Definition at line 619 of file Svar_signals.hh.
References bad_get().
get__ADD_EVENT__proc()
virtual uint32_t Signal_base::get__ADD_EVENT__proc () const inline virtual
< dito
Reimplemented in ADD_EVENT_c.
Definition at line 617 of file Svar_signals.hh.
References bad_get().
get__ASSIGN_VALUE__cdr_value()
virtual string Signal_base::get__ASSIGN_VALUE__cdr_value () const inline virtual
< dito
Reimplemented in ASSIGN_VALUE_c.
Definition at line 430 of file Svar_signals.hh.
References bad_get().
get__ASSIGN_VALUE__key()
virtual uint64_t Signal_base::get__ASSIGN_VALUE__key () const inline virtual
APserver request: SVAR←X access functions for signal ASSIGN_VALUE...
< dito
Reimplemented in ASSIGN_VALUE_c.
Definition at line 428 of file Svar_signals.hh.
References bad_get().
get__ASSIGN_WSWS_VAR__cdr_value()
virtual string Signal_base::get__ASSIGN_WSWS_VAR__cdr_value () const inline virtual
< dito
Reimplemented in ASSIGN_WSWS_VAR_c.
Definition at line 631 of file Svar_signals.hh.
References bad_get().
get__ASSIGN_WSWS_VAR__key()
virtual uint64_t Signal_base::get__ASSIGN_WSWS_VAR__key () const inline virtual
APserver request: ws-ws SVAR←X access functions for signal ASSIGN_WSWS_VAR...
< dito
Reimplemented in ASSIGN_WSWS_VAR_c.
Definition at line 629 of file Svar_signals.hh.
References bad_get().
get__CLEAR_ALL_EVENTS__grand()
virtual uint32_t Signal_base::get__CLEAR_ALL_EVENTS__grand () const inline virtual
< dito
Reimplemented in CLEAR_ALL_EVENTS_c.
Definition at line 600 of file Svar_signals.hh.
References bad_get().
get__CLEAR_ALL_EVENTS__parent()
virtual uint32_t Signal_base::get__CLEAR_ALL_EVENTS__parent () const inline virtual
< dito
Reimplemented in CLEAR_ALL_EVENTS_c.
Definition at line 598 of file Svar_signals.hh.
References bad_get().
get__CLEAR_ALL_EVENTS__proc()
virtual uint32_t Signal_base::get__CLEAR_ALL_EVENTS__proc () const inline virtual
APserver request: clear all events for one processor access functions for signal CLEAR_ALL_EVENTS...
< dito
Reimplemented in CLEAR_ALL_EVENTS_c.
Definition at line 596 of file Svar_signals.hh.
References bad_get().
get__EVENTS_ARE__events()
virtual uint32_t Signal_base::get__EVENTS_ARE__events () const inline virtual
< dito
Reimplemented in EVENTS_ARE_c.
Definition at line 609 of file Svar_signals.hh.
References bad_get().
Referenced by Svar_DB::clear_all_events(), and Svar_DB::get_events().
get__EVENTS_ARE__key()
virtual uint64_t Signal_base::get__EVENTS_ARE__key () const inline virtual
APserver result for: clear all events for one processor (first cleared svar access functions for signal EVENTS_ARE...
< dito
Reimplemented in EVENTS_ARE_c.
Definition at line 607 of file Svar_signals.hh.
References bad_get().
Referenced by Svar_DB::get_events().
get__FIND_OFFERING_ID__key()
virtual uint64_t Signal_base::get__FIND_OFFERING_ID__key () const inline virtual
APserver request: find processor ID that offers key access functions for signal FIND_OFFERING_ID...
< dito
Reimplemented in FIND_OFFERING_ID_c.
Definition at line 531 of file Svar_signals.hh.
References bad_get().
get__FIND_PAIRING_KEY__key()
virtual uint64_t Signal_base::get__FIND_PAIRING_KEY__key () const inline virtual
APserver request: find pairing key (CTL vs. DAT or Cnnn vs. Dnnn) for AP210 access functions for signal FIND_PAIRING_KEY...
< dito
Reimplemented in FIND_PAIRING_KEY_c.
Definition at line 573 of file Svar_signals.hh.
References bad_get().
get__GET_EVENTS__grand()
virtual uint32_t Signal_base::get__GET_EVENTS__grand () const inline virtual
< dito
Reimplemented in GET_EVENTS_c.
Definition at line 590 of file Svar_signals.hh.
References bad_get().
get__GET_EVENTS__parent()
virtual uint32_t Signal_base::get__GET_EVENTS__parent () const inline virtual
< dito
Reimplemented in GET_EVENTS_c.
Definition at line 588 of file Svar_signals.hh.
References bad_get().
get__GET_EVENTS__proc()
virtual uint32_t Signal_base::get__GET_EVENTS__proc () const inline virtual
APserver result for: find pairing key (CTL vs. DAT or Cnnn vs. Dnnn) for AP210 get events for one processor (first shared var with an event) access functions for signal GET_EVENTS...
< dito
Reimplemented in GET_EVENTS_c.
Definition at line 586 of file Svar_signals.hh.
References bad_get().
get__GET_OFFERED_VARS__accepted_by_proc()
virtual uint32_t Signal_base::get__GET_OFFERED_VARS__accepted_by_proc () const inline virtual
< dito
Reimplemented in GET_OFFERED_VARS_c.
Definition at line 561 of file Svar_signals.hh.
References bad_get().
get__GET_OFFERED_VARS__offered_to_proc()
virtual uint32_t Signal_base::get__GET_OFFERED_VARS__offered_to_proc () const inline virtual
APserver request: get offered variables (⎕SVQ) access functions for signal GET_OFFERED_VARS...
< dito
Reimplemented in GET_OFFERED_VARS_c.
Definition at line 559 of file Svar_signals.hh.
References bad_get().
get__GET_OFFERING_PROCS__offered_to_proc()
virtual uint32_t Signal_base::get__GET_OFFERING_PROCS__offered_to_proc () const inline virtual
APserver request: get offering processors (⎕SVQ) access functions for signal GET_OFFERING_PROCS...
< dito
Reimplemented in GET_OFFERING_PROCS_c.
Definition at line 547 of file Svar_signals.hh.
References bad_get().
get__GET_VALUE__key()
virtual uint64_t Signal_base::get__GET_VALUE__key () const inline virtual
APserver request: X←SVAR access functions for signal GET_VALUE...
< dito
Reimplemented in GET_VALUE_c.
Definition at line 410 of file Svar_signals.hh.
References bad_get().
get__IS_REGISTERED_ID__grand()
virtual uint32_t Signal_base::get__IS_REGISTERED_ID__grand () const inline virtual
< dito
Reimplemented in IS_REGISTERED_ID_c.
Definition at line 480 of file Svar_signals.hh.
References bad_get().
get__IS_REGISTERED_ID__parent()
virtual uint32_t Signal_base::get__IS_REGISTERED_ID__parent () const inline virtual
< dito
Reimplemented in IS_REGISTERED_ID_c.
Definition at line 478 of file Svar_signals.hh.
References bad_get().
get__IS_REGISTERED_ID__proc()
virtual uint32_t Signal_base::get__IS_REGISTERED_ID__proc () const inline virtual
APserver request: is ID registered ? access functions for signal IS_REGISTERED_ID...
< dito
Reimplemented in IS_REGISTERED_ID_c.
Definition at line 476 of file Svar_signals.hh.
References bad_get().
get__MAKE_OFFER__key()
virtual uint64_t Signal_base::get__MAKE_OFFER__key () const inline virtual
APserver request: ⎕SVO access functions for signal MAKE_OFFER...
< dito
Reimplemented in MAKE_OFFER_c.
Definition at line 376 of file Svar_signals.hh.
References bad_get().
get__MATCH_OR_MAKE__from_grand()
virtual uint32_t Signal_base::get__MATCH_OR_MAKE__from_grand () const inline virtual
< dito
Reimplemented in MATCH_OR_MAKE_c.
Definition at line 518 of file Svar_signals.hh.
References bad_get().
get__MATCH_OR_MAKE__from_parent()
virtual uint32_t Signal_base::get__MATCH_OR_MAKE__from_parent () const inline virtual
< dito
Reimplemented in MATCH_OR_MAKE_c.
Definition at line 516 of file Svar_signals.hh.
References bad_get().
get__MATCH_OR_MAKE__from_proc()
virtual uint32_t Signal_base::get__MATCH_OR_MAKE__from_proc () const inline virtual
< dito
Reimplemented in MATCH_OR_MAKE_c.
Definition at line 514 of file Svar_signals.hh.
References bad_get().
get__MATCH_OR_MAKE__to_grand()
virtual uint32_t Signal_base::get__MATCH_OR_MAKE__to_grand () const inline virtual
< dito
Reimplemented in MATCH_OR_MAKE_c.
Definition at line 512 of file Svar_signals.hh.
References bad_get().
get__MATCH_OR_MAKE__to_parent()
virtual uint32_t Signal_base::get__MATCH_OR_MAKE__to_parent () const inline virtual
< dito
Reimplemented in MATCH_OR_MAKE_c.
Definition at line 510 of file Svar_signals.hh.
References bad_get().
get__MATCH_OR_MAKE__to_proc()
virtual uint32_t Signal_base::get__MATCH_OR_MAKE__to_proc () const inline virtual
< dito
Reimplemented in MATCH_OR_MAKE_c.
Definition at line 508 of file Svar_signals.hh.
References bad_get().
get__MATCH_OR_MAKE__varname()
virtual string Signal_base::get__MATCH_OR_MAKE__varname () const inline virtual
APserver request: match offered shared variable or make a new offer access functions for signal MATCH_OR_MAKE...
< dito
Reimplemented in MATCH_OR_MAKE_c.
Definition at line 506 of file Svar_signals.hh.
References bad_get().
get__MATCH_OR_MAKE_RESULT__key()
virtual uint64_t Signal_base::get__MATCH_OR_MAKE_RESULT__key () const inline virtual
APserver result for: match or make access functions for signal MATCH_OR_MAKE_RESULT...
< dito
Reimplemented in MATCH_OR_MAKE_RESULT_c.
Definition at line 524 of file Svar_signals.hh.
References bad_get().
Referenced by Svar_DB::match_or_make().
get__MAY_SET__attempt()
virtual int32_t Signal_base::get__MAY_SET__attempt () const inline virtual
< dito
Reimplemented in MAY_SET_c.
Definition at line 455 of file Svar_signals.hh.
References bad_get().
get__MAY_SET__key()
virtual uint64_t Signal_base::get__MAY_SET__key () const inline virtual
APserver request: Can svar key be assigned ? access functions for signal MAY_SET...
< dito
Reimplemented in MAY_SET_c.
Definition at line 453 of file Svar_signals.hh.
References bad_get().
get__MAY_USE__attempt()
virtual int32_t Signal_base::get__MAY_USE__attempt () const inline virtual
< dito
Reimplemented in MAY_USE_c.
Definition at line 447 of file Svar_signals.hh.
References bad_get().
get__MAY_USE__key()
virtual uint64_t Signal_base::get__MAY_USE__key () const inline virtual
APserver request: Can svar key be referenced ? access functions for signal MAY_USE...
< dito
Reimplemented in MAY_USE_c.
Definition at line 445 of file Svar_signals.hh.
References bad_get().
get__OFFERED_VARS_ARE__offered_vars()
virtual string Signal_base::get__OFFERED_VARS_ARE__offered_vars () const inline virtual
APserver result for: get offered variables (⎕SVQ) access functions for signal OFFERED_VARS_ARE...
< dito
Reimplemented in OFFERED_VARS_ARE_c.
Definition at line 567 of file Svar_signals.hh.
References bad_get().
Referenced by Svar_DB::get_offered_variables().
get__OFFERING_ID_IS__grand()
virtual uint32_t Signal_base::get__OFFERING_ID_IS__grand () const inline virtual
< dito
Reimplemented in OFFERING_ID_IS_c.
Definition at line 541 of file Svar_signals.hh.
References bad_get().
Referenced by Svar_DB::find_offering_id().
get__OFFERING_ID_IS__parent()
virtual uint32_t Signal_base::get__OFFERING_ID_IS__parent () const inline virtual
< dito
Reimplemented in OFFERING_ID_IS_c.
Definition at line 539 of file Svar_signals.hh.
References bad_get().
Referenced by Svar_DB::find_offering_id().
get__OFFERING_ID_IS__proc()
virtual uint32_t Signal_base::get__OFFERING_ID_IS__proc () const inline virtual
APserver result for: find processor ID that offers key access functions for signal OFFERING_ID_IS...
< dito
Reimplemented in OFFERING_ID_IS_c.
Definition at line 537 of file Svar_signals.hh.
References bad_get().
Referenced by Svar_DB::find_offering_id().
get__OFFERING_PROCS_ARE__offering_procs()
virtual string Signal_base::get__OFFERING_PROCS_ARE__offering_procs () const inline virtual
APserver result for: get offering processors (⎕SVQ) access functions for signal OFFERING_PROCS_ARE...
< dito
Reimplemented in OFFERING_PROCS_ARE_c.
Definition at line 553 of file Svar_signals.hh.
References bad_get().
Referenced by Svar_DB::get_offering_processors().
get__PAIRING_KEY_IS__pairing_key()
virtual uint64_t Signal_base::get__PAIRING_KEY_IS__pairing_key () const inline virtual
APserver result for: find pairing key access functions for signal PAIRING_KEY_IS...
< dito
Reimplemented in PAIRING_KEY_IS_c.
Definition at line 579 of file Svar_signals.hh.
References bad_get().
Referenced by Svar_DB::find_pairing_key().
get__READ_SVAR_RECORD__key()
virtual uint64_t Signal_base::get__READ_SVAR_RECORD__key () const inline virtual
APserver request: read SVAR database record from APserver.
apl/APnnn   --> READ_SVAR_RECORD        APserver
        <-- SVAR_RECORD_IS
access functions for signal READ_SVAR_RECORD... < dito
Reimplemented in READ_SVAR_RECORD_c.
Definition at line 465 of file Svar_signals.hh.
References bad_get().
get__READ_WSWS_VAR__key()
virtual uint64_t Signal_base::get__READ_WSWS_VAR__key () const inline virtual
APserver request: X←ws-ws SVAR access functions for signal READ_WSWS_VAR...
< dito
Reimplemented in READ_WSWS_VAR_c.
Definition at line 636 of file Svar_signals.hh.
References bad_get().
get__REGISTER_PROCESSOR__evconn()
virtual uint8_t Signal_base::get__REGISTER_PROCESSOR__evconn () const inline virtual
< dito
Reimplemented in REGISTER_PROCESSOR_c.
Definition at line 498 of file Svar_signals.hh.
References bad_get().
get__REGISTER_PROCESSOR__grand()
virtual uint32_t Signal_base::get__REGISTER_PROCESSOR__grand () const inline virtual
< dito
Reimplemented in REGISTER_PROCESSOR_c.
Definition at line 496 of file Svar_signals.hh.
References bad_get().
get__REGISTER_PROCESSOR__parent()
virtual uint32_t Signal_base::get__REGISTER_PROCESSOR__parent () const inline virtual
< dito
Reimplemented in REGISTER_PROCESSOR_c.
Definition at line 494 of file Svar_signals.hh.
References bad_get().
get__REGISTER_PROCESSOR__proc()
virtual uint32_t Signal_base::get__REGISTER_PROCESSOR__proc () const inline virtual
APserver request: register processor proc in APserver access functions for signal REGISTER_PROCESSOR...
< dito
Reimplemented in REGISTER_PROCESSOR_c.
Definition at line 492 of file Svar_signals.hh.
References bad_get().
get__REGISTER_PROCESSOR__progname()
virtual string Signal_base::get__REGISTER_PROCESSOR__progname () const inline virtual
< dito
Reimplemented in REGISTER_PROCESSOR_c.
Definition at line 500 of file Svar_signals.hh.
References bad_get().
get__RETRACT_OFFER__key()
virtual uint64_t Signal_base::get__RETRACT_OFFER__key () const inline virtual
APserver request: ⎕SVR access functions for signal RETRACT_OFFER...
< dito
Reimplemented in RETRACT_OFFER_c.
Definition at line 381 of file Svar_signals.hh.
References bad_get().
get__RETRACT_VAR__key()
virtual uint64_t Signal_base::get__RETRACT_VAR__key () const inline virtual
APserver request: ⎕SVR access functions for signal RETRACT_VAR...
< dito
Reimplemented in RETRACT_VAR_c.
Definition at line 386 of file Svar_signals.hh.
References bad_get().
get__SET_CONTROL__key()
virtual uint64_t Signal_base::get__SET_CONTROL__key () const inline virtual
APserver request: set control of shared var key access functions for signal SET_CONTROL...
< dito
Reimplemented in SET_CONTROL_c.
Definition at line 402 of file Svar_signals.hh.
References bad_get().
get__SET_CONTROL__new_control()
virtual uint8_t Signal_base::get__SET_CONTROL__new_control () const inline virtual
< dito
Reimplemented in SET_CONTROL_c.
Definition at line 404 of file Svar_signals.hh.
References bad_get().
get__SET_STATE__key()
virtual uint64_t Signal_base::get__SET_STATE__key () const inline virtual
APserver request: set state of shared var key access functions for signal SET_STATE...
< dito
Reimplemented in SET_STATE_c.
Definition at line 392 of file Svar_signals.hh.
References bad_get().
get__SET_STATE__new_state()
virtual uint8_t Signal_base::get__SET_STATE__new_state () const inline virtual
< dito
Reimplemented in SET_STATE_c.
Definition at line 394 of file Svar_signals.hh.
References bad_get().
get__SET_STATE__sloc()
virtual string Signal_base::get__SET_STATE__sloc () const inline virtual
< dito
Reimplemented in SET_STATE_c.
Definition at line 396 of file Svar_signals.hh.
References bad_get().
get__SVAR_ASSIGNED__error()
virtual uint32_t Signal_base::get__SVAR_ASSIGNED__error () const inline virtual
< dito
Reimplemented in SVAR_ASSIGNED_c.
Definition at line 437 of file Svar_signals.hh.
References bad_get().
Referenced by Symbol::assign_shared_variable().
get__SVAR_ASSIGNED__error_loc()
virtual string Signal_base::get__SVAR_ASSIGNED__error_loc () const inline virtual
< dito
Reimplemented in SVAR_ASSIGNED_c.
Definition at line 439 of file Svar_signals.hh.
References bad_get().
Referenced by Symbol::assign_shared_variable().
get__SVAR_ASSIGNED__key()
virtual uint64_t Signal_base::get__SVAR_ASSIGNED__key () const inline virtual
APserver result for: SVAR←X access functions for signal SVAR_ASSIGNED...
< dito
Reimplemented in SVAR_ASSIGNED_c.
Definition at line 435 of file Svar_signals.hh.
References bad_get().
get__SVAR_DB_PRINTED__printout()
virtual string Signal_base::get__SVAR_DB_PRINTED__printout () const inline virtual
APserver request: print the entire database (for command ]SVARS) access functions for signal PRINT_SVAR_DB...
APserver result for: print the entire database access functions for signal SVAR_DB_PRINTED... < dito
Reimplemented in SVAR_DB_PRINTED_c.
Definition at line 650 of file Svar_signals.hh.
References bad_get().
Referenced by Svar_DB::print().
get__SVAR_RECORD_IS__record()
virtual string Signal_base::get__SVAR_RECORD_IS__record () const inline virtual
APserver result (record) for: read SVAR database record from APserver access functions for signal SVAR_RECORD_IS...
< dito
Reimplemented in SVAR_RECORD_IS_c.
Definition at line 470 of file Svar_signals.hh.
References bad_get().
Referenced by Svar_record_P::Svar_record_P().
get__VALUE_IS__cdr_value()
virtual string Signal_base::get__VALUE_IS__cdr_value () const inline virtual
< dito
Reimplemented in VALUE_IS_c.
Definition at line 422 of file Svar_signals.hh.
References bad_get().
Referenced by Symbol::resolve_shared_variable().
get__VALUE_IS__error()
virtual uint32_t Signal_base::get__VALUE_IS__error () const inline virtual
< dito
Reimplemented in VALUE_IS_c.
Definition at line 418 of file Svar_signals.hh.
References bad_get().
Referenced by Symbol::resolve_shared_variable().
get__VALUE_IS__error_loc()
virtual string Signal_base::get__VALUE_IS__error_loc () const inline virtual
< dito
Reimplemented in VALUE_IS_c.
Definition at line 420 of file Svar_signals.hh.
References bad_get().
Referenced by Symbol::resolve_shared_variable().
get__VALUE_IS__key()
virtual uint64_t Signal_base::get__VALUE_IS__key () const inline virtual
APserver result for: X←SVAR access functions for signal VALUE_IS...
< dito
Reimplemented in VALUE_IS_c.
Definition at line 416 of file Svar_signals.hh.
References bad_get().
get__WSWS_VALUE_IS__cdr_value()
virtual string Signal_base::get__WSWS_VALUE_IS__cdr_value () const inline virtual
APserver result for: X←ws-ws SVAR access functions for signal WSWS_VALUE_IS...
< dito
Reimplemented in WSWS_VALUE_IS_c.
Definition at line 641 of file Svar_signals.hh.
References bad_get().
Referenced by Symbol::resolve_shared_variable().
get__YES_NO__yes()
virtual uint8_t Signal_base::get__YES_NO__yes () const inline virtual
APserver result: yes (1) or no (0) access functions for signal YES_NO...
< dito
Reimplemented in YES_NO_c.
Definition at line 486 of file Svar_signals.hh.
References bad_get().
Referenced by Svar_DB::is_registered_id(), Svar_DB::may_set(), and Svar_DB::may_use().
get_sigID()
virtual Signal_id Signal_base::get_sigID () const pure virtual
return the ID of the signal
Implemented in MAKE_OFFER_c, RETRACT_OFFER_c, RETRACT_VAR_c, SET_STATE_c, SET_CONTROL_c, GET_VALUE_c, VALUE_IS_c, ASSIGN_VALUE_c, SVAR_ASSIGNED_c, MAY_USE_c, MAY_SET_c, READ_SVAR_RECORD_c, SVAR_RECORD_IS_c, IS_REGISTERED_ID_c, YES_NO_c, REGISTER_PROCESSOR_c, MATCH_OR_MAKE_c, MATCH_OR_MAKE_RESULT_c, FIND_OFFERING_ID_c, OFFERING_ID_IS_c, GET_OFFERING_PROCS_c, OFFERING_PROCS_ARE_c, GET_OFFERED_VARS_c, OFFERED_VARS_ARE_c, FIND_PAIRING_KEY_c, PAIRING_KEY_IS_c, GET_EVENTS_c, CLEAR_ALL_EVENTS_c, EVENTS_ARE_c, ADD_EVENT_c, ASSIGN_WSWS_VAR_c, READ_WSWS_VAR_c, WSWS_VALUE_IS_c, PRINT_SVAR_DB_c, and SVAR_DB_PRINTED_c.
get_sigName()
virtual const char * Signal_base::get_sigName () const pure virtual
return the name of the ID of the signal
Implemented in MAKE_OFFER_c, RETRACT_OFFER_c, RETRACT_VAR_c, SET_STATE_c, SET_CONTROL_c, GET_VALUE_c, VALUE_IS_c, ASSIGN_VALUE_c, SVAR_ASSIGNED_c, MAY_USE_c, MAY_SET_c, READ_SVAR_RECORD_c, SVAR_RECORD_IS_c, IS_REGISTERED_ID_c, YES_NO_c, REGISTER_PROCESSOR_c, MATCH_OR_MAKE_c, MATCH_OR_MAKE_RESULT_c, FIND_OFFERING_ID_c, OFFERING_ID_IS_c, GET_OFFERING_PROCS_c, OFFERING_PROCS_ARE_c, GET_OFFERED_VARS_c, OFFERED_VARS_ARE_c, FIND_PAIRING_KEY_c, PAIRING_KEY_IS_c, GET_EVENTS_c, CLEAR_ALL_EVENTS_c, EVENTS_ARE_c, ADD_EVENT_c, ASSIGN_WSWS_VAR_c, READ_WSWS_VAR_c, WSWS_VALUE_IS_c, PRINT_SVAR_DB_c, and SVAR_DB_PRINTED_c.
Referenced by bad_get().
print()
virtual ostream & Signal_base::print (ostream & out) const pure virtual
print the signal
Implemented in MAKE_OFFER_c, RETRACT_OFFER_c, RETRACT_VAR_c, SET_STATE_c, SET_CONTROL_c, GET_VALUE_c, VALUE_IS_c, ASSIGN_VALUE_c, SVAR_ASSIGNED_c, MAY_USE_c, MAY_SET_c, READ_SVAR_RECORD_c, SVAR_RECORD_IS_c, IS_REGISTERED_ID_c, YES_NO_c, REGISTER_PROCESSOR_c, MATCH_OR_MAKE_c, MATCH_OR_MAKE_RESULT_c, FIND_OFFERING_ID_c, OFFERING_ID_IS_c, GET_OFFERING_PROCS_c, OFFERING_PROCS_ARE_c, GET_OFFERED_VARS_c, OFFERED_VARS_ARE_c, FIND_PAIRING_KEY_c, PAIRING_KEY_IS_c, GET_EVENTS_c, CLEAR_ALL_EVENTS_c, EVENTS_ARE_c, ADD_EVENT_c, ASSIGN_WSWS_VAR_c, READ_WSWS_VAR_c, WSWS_VALUE_IS_c, PRINT_SVAR_DB_c, and SVAR_DB_PRINTED_c.
Referenced by recv_TCP().
recv_TCP()
Signal_base * Signal_base::recv_TCP (int tcp_sock, char * buffer, int bufsize, char *& del, ostream * debug, const char ** loc) inline static
receive a signal (TCP)
APserver request: ⎕SVO
APserver request: ⎕SVR
APserver request: ⎕SVR
APserver request: set state of shared var key
APserver request: set control of shared var key
APserver request: X←SVAR
APserver result for: X←SVAR
APserver request: SVAR←X
APserver result for: SVAR←X
APserver request: Can svar key be referenced ?
APserver request: Can svar key be assigned ?
APserver request: read SVAR database record from APserver
apl/APnnn   --> READ_SVAR_RECORD        APserver
        <-- SVAR_RECORD_IS
APserver result (record) for: read SVAR database record from APserver
APserver request: is ID registered ?
APserver result: yes (1) or no (0)
APserver request: register processor proc in APserver
APserver request: match offered shared variable or make a new offer
APserver result for: match or make
APserver request: find processor ID that offers key
APserver result for: find processor ID that offers key
APserver request: get offering processors (⎕SVQ)
APserver result for: get offering processors (⎕SVQ)
APserver request: get offered variables (⎕SVQ)
APserver result for: get offered variables (⎕SVQ)
APserver request: find pairing key (CTL vs. DAT or Cnnn vs. Dnnn) for AP210
APserver result for: find pairing key
APserver result for: find pairing key (CTL vs. DAT or Cnnn vs. Dnnn) for AP210 get events for one processor (first shared var with an event)
APserver request: clear all events for one processor
APserver result for: clear all events for one processor (first cleared svar
APserver request: add an event for key
APserver request: ws-ws SVAR←X
APserver request: X←ws-ws SVAR
APserver result for: X←ws-ws SVAR
APserver request: print the entire database (for command ]SVARS)
APserver result for: print the entire database
Definition at line 2840 of file Svar_signals.hh.
References Sig_item_int< T, bytes >::get_svalue(), and print().
Referenced by Symbol::assign_shared_variable(), Svar_DB::clear_all_events(), Svar_DB::find_offering_id(), Svar_DB::find_pairing_key(), Svar_DB::get_events(), Svar_DB::get_offered_variables(), Svar_DB::get_offering_processors(), Svar_DB::is_registered_id(), Svar_DB::match_or_make(), Svar_DB::may_set(), Svar_DB::may_use(), Svar_DB::print(), Symbol::resolve_shared_variable(), and Svar_record_P::Svar_record_P().
send_TCP()
ssize_t Signal_base::send_TCP (int tcp_sock) const inline protected
send this signal on TCP (or AF_UNIX) socket tcp_sock
Definition at line 663 of file Svar_signals.hh.
References store().
Referenced by ADD_EVENT_c::ADD_EVENT_c(), ASSIGN_VALUE_c::ASSIGN_VALUE_c(), ASSIGN_WSWS_VAR_c::ASSIGN_WSWS_VAR_c(), CLEAR_ALL_EVENTS_c::CLEAR_ALL_EVENTS_c(), EVENTS_ARE_c::EVENTS_ARE_c(), FIND_OFFERING_ID_c::FIND_OFFERING_ID_c(), FIND_PAIRING_KEY_c::FIND_PAIRING_KEY_c(), GET_EVENTS_c::GET_EVENTS_c(), GET_OFFERED_VARS_c::GET_OFFERED_VARS_c(), GET_OFFERING_PROCS_c::GET_OFFERING_PROCS_c(), GET_VALUE_c::GET_VALUE_c(), IS_REGISTERED_ID_c::IS_REGISTERED_ID_c(), MAKE_OFFER_c::MAKE_OFFER_c(), MATCH_OR_MAKE_c::MATCH_OR_MAKE_c(), MATCH_OR_MAKE_RESULT_c::MATCH_OR_MAKE_RESULT_c(), MAY_SET_c::MAY_SET_c(), MAY_USE_c::MAY_USE_c(), OFFERED_VARS_ARE_c::OFFERED_VARS_ARE_c(), OFFERING_ID_IS_c::OFFERING_ID_IS_c(), OFFERING_PROCS_ARE_c::OFFERING_PROCS_ARE_c(), PAIRING_KEY_IS_c::PAIRING_KEY_IS_c(), PRINT_SVAR_DB_c::PRINT_SVAR_DB_c(), READ_SVAR_RECORD_c::READ_SVAR_RECORD_c(), READ_WSWS_VAR_c::READ_WSWS_VAR_c(), REGISTER_PROCESSOR_c::REGISTER_PROCESSOR_c(), RETRACT_OFFER_c::RETRACT_OFFER_c(), RETRACT_VAR_c::RETRACT_VAR_c(), SET_CONTROL_c::SET_CONTROL_c(), SET_STATE_c::SET_STATE_c(), SVAR_ASSIGNED_c::SVAR_ASSIGNED_c(), SVAR_DB_PRINTED_c::SVAR_DB_PRINTED_c(), SVAR_RECORD_IS_c::SVAR_RECORD_IS_c(), VALUE_IS_c::VALUE_IS_c(), WSWS_VALUE_IS_c::WSWS_VALUE_IS_c(), and YES_NO_c::YES_NO_c().
store()
virtual void Signal_base::store (string & buffer) const pure virtual
store (encode) the signal into buffer
Implemented in MAKE_OFFER_c, RETRACT_OFFER_c, RETRACT_VAR_c, SET_STATE_c, SET_CONTROL_c, GET_VALUE_c, VALUE_IS_c, ASSIGN_VALUE_c, SVAR_ASSIGNED_c, MAY_USE_c, MAY_SET_c, READ_SVAR_RECORD_c, SVAR_RECORD_IS_c, IS_REGISTERED_ID_c, YES_NO_c, REGISTER_PROCESSOR_c, MATCH_OR_MAKE_c, MATCH_OR_MAKE_RESULT_c, FIND_OFFERING_ID_c, OFFERING_ID_IS_c, GET_OFFERING_PROCS_c, OFFERING_PROCS_ARE_c, GET_OFFERED_VARS_c, OFFERED_VARS_ARE_c, FIND_PAIRING_KEY_c, PAIRING_KEY_IS_c, GET_EVENTS_c, CLEAR_ALL_EVENTS_c, EVENTS_ARE_c, ADD_EVENT_c, ASSIGN_WSWS_VAR_c, READ_WSWS_VAR_c, WSWS_VALUE_IS_c, PRINT_SVAR_DB_c, and SVAR_DB_PRINTED_c.
Referenced by send_TCP().
The documentation for this class was generated from the following file:
src/Svar_signals.hh