GNU APL: Unicode_source Class Reference
Unicode_source Class Reference
An iterator for UCS_string.
#include <Tokenizer.hh>
Public Member Functions
Unicode_source (const UCS_string &s)
constructor: iterate over the entire string.
Unicode_source (const Unicode_source &src, int32_t from, int32_t to)
constructor: iterate from from to to
int32_t rest () const
return the number of remaining items
const Unicode & operator[] (int32_t i) const
lookup next item
const Unicode & get ()
get next item
const Unicode & operator* () const
lookup next item without removing it
void operator++ ()
skip the first element
void operator-- ()
undo skip of the current element
void set_rest (int32_t new_rest)
shrink the source to rest new_rest
void skip (int32_t count)
skip count elements
Protected Attributes
const UCS_string & str
the source string
int32_t idx
the current position
int32_t end
the end position (excluding)
Detailed Description
An iterator for UCS_string.
Definition at line 31 of file Tokenizer.hh.
Constructor & Destructor Documentation
Unicode_source() [1/2]
Unicode_source::Unicode_source (const UCS_string & s) inline
constructor: iterate over the entire string.
Definition at line 35 of file Tokenizer.hh.
Unicode_source() [2/2]
Unicode_source::Unicode_source (const Unicode_source & src, int32_t from, int32_t to) inline
constructor: iterate from from to to
Definition at line 42 of file Tokenizer.hh.
References end, idx, UCS_string::size(), and str.
Member Function Documentation
get()
const Unicode & Unicode_source::get () inline
get next item
Definition at line 60 of file Tokenizer.hh.
References end, idx, and str.
Referenced by Tokenizer::tokenize_function(), Tokenizer::tokenize_quad(), Tokenizer::tokenize_string1(), Tokenizer::tokenize_string2(), and Tokenizer::tokenize_symbol().
operator*()
const Unicode & Unicode_source::operator* () const inline
lookup next item without removing it
Definition at line 64 of file Tokenizer.hh.
References end, idx, and str.
operator++()
void Unicode_source::operator++ () inline
skip the first element
Definition at line 68 of file Tokenizer.hh.
References end, and idx.
operator--()
void Unicode_source::operator-- () inline
undo skip of the current element
Definition at line 72 of file Tokenizer.hh.
References idx.
operator[]()
const Unicode & Unicode_source::operator[] (int32_t i) const inline
lookup next item
Definition at line 56 of file Tokenizer.hh.
References end, idx, and str.
rest()
int32_t Unicode_source::rest () const inline
return the number of remaining items
Definition at line 52 of file Tokenizer.hh.
References end, and idx.
Referenced by Tokenizer::do_tokenize(), set_rest(), Tokenizer::tokenize_number(), Tokenizer::tokenize_quad(), Tokenizer::tokenize_string1(), Tokenizer::tokenize_string2(), and Tokenizer::tokenize_symbol().
set_rest()
void Unicode_source::set_rest (int32_t new_rest) inline
shrink the source to rest new_rest
Definition at line 76 of file Tokenizer.hh.
References end, idx, and rest().
skip()
void Unicode_source::skip (int32_t count) inline
skip count elements
Definition at line 80 of file Tokenizer.hh.
References end, and idx.
Referenced by Tokenizer::tokenize_quad().
Member Data Documentation
end
int32_t Unicode_source::end protected
the end position (excluding)
Definition at line 91 of file Tokenizer.hh.
Referenced by get(), operator*(), operator++(), operator[](), rest(), set_rest(), skip(), and Unicode_source().
idx
int32_t Unicode_source::idx protected
the current position
Definition at line 88 of file Tokenizer.hh.
Referenced by get(), operator*(), operator++(), operator--(), operator[](), rest(), set_rest(), skip(), and Unicode_source().
str
const UCS_string& Unicode_source::str protected
the source string
Definition at line 85 of file Tokenizer.hh.
Referenced by get(), operator*(), operator[](), and Unicode_source().
The documentation for this class was generated from the following file:
src/Tokenizer.hh