GNU APL: Regexp Class Reference
Regexp Class Reference
Helper class for ⎕RE.
#include <Regexp.hh>
Public Member Functions
Regexp (const UCS_string &pattern, int flags)
constructor
virtual ~Regexp ()
destructor
const RegexpMatch * match (const UCS_string &match, PCRE2_SIZE size) const
return a new match
int expression_count () const
return the number of matches
pcre2_code * get_code () const
returned the compiled regular expression
Static Public Member Functions
static UCS_string pcre_error (int ec)
return a description for error code eec
Protected Attributes
pcre2_code * code
compiled regular expression
Detailed Description
Helper class for ⎕RE.
Definition at line 74 of file Regexp.hh.
Constructor & Destructor Documentation
Regexp()
Regexp::Regexp (const UCS_string & pattern, int flags)
constructor
Definition at line 95 of file Regexp.cc.
References code, pcre_error(), and UCS_string::size().
~Regexp()
Regexp::~Regexp () virtual
destructor
Definition at line 120 of file Regexp.cc.
References code.
Member Function Documentation
expression_count()
int Regexp::expression_count () const
return the number of matches
Definition at line 132 of file Regexp.cc.
References code.
get_code()
pcre2_code * Regexp::get_code () const inline
returned the compiled regular expression
Definition at line 90 of file Regexp.hh.
References code.
match()
const RegexpMatch * Regexp::match (const UCS_string & match, PCRE2_SIZE size) const
return a new match
Definition at line 126 of file Regexp.cc.
References code, and match().
Referenced by match().
pcre_error()
UCS_string Regexp::pcre_error (int ec) static
return a description for error code eec
Definition at line 141 of file Regexp.cc.
References UCS_string::append_number().
Referenced by Regexp(), and RegexpMatch::RegexpMatch().
Member Data Documentation
code
pcre2_code* Regexp::code protected
compiled regular expression
Definition at line 98 of file Regexp.hh.
Referenced by expression_count(), get_code(), match(), Regexp(), and ~Regexp().
The documentation for this class was generated from the following files:
src/Regexp.hh
src/Regexp.cc