GNU APL: Svar_record_P Class Reference
Svar_record_P Class Reference
a pointer to one record (one shared variable) of the shared Svar_DB_memory
#include <Svar_DB.hh>
Public Member Functions
Svar_record_P (SV_key key)
constructor: fetch record with key key from APserver
const Svar_record * operator-> () const
return pointer to the record (overloaded -> operator)
Static Protected Attributes
static Svar_record cache
the last fetched record
Private Member Functions
Svar_record_P (const Svar_record_P &other)
don't copy...
Svar_record_P & operator= (const Svar_record_P &other)
don't copy...
Detailed Description
a pointer to one record (one shared variable) of the shared Svar_DB_memory
Definition at line 41 of file Svar_DB.hh.
Constructor & Destructor Documentation
Svar_record_P()
Svar_record_P::Svar_record_P (SV_key key)
constructor: fetch record with key key from APserver
Definition at line 321 of file Svar_DB.cc.
References Svar_DB::APserver_available(), cache, Svar_record::clear(), Signal_base::get__SVAR_RECORD_IS__record(), Svar_DB::get_DB_tcp(), and Signal_base::recv_TCP().
Member Function Documentation
operator->()
const Svar_record * Svar_record_P::operator-> () const inline
return pointer to the record (overloaded -> operator)
Definition at line 48 of file Svar_DB.hh.
References cache.
Member Data Documentation
cache
Svar_record Svar_record_P::cache static protected
the last fetched record
Definition at line 53 of file Svar_DB.hh.
Referenced by operator->(), and Svar_record_P().
The documentation for this class was generated from the following files:
src/Svar_DB.hh
src/Svar_DB.cc