GNU APL: Parallel_job_list< T, has_destructor > Class Template Reference
Parallel_job_list< T, has_destructor > Class Template Reference
A linked list of parallel jobs.
#include <PJob.hh>
Public Member Functions
Parallel_job_list ()
constructor: empty job list
void start (const T &first_job, const char *loc)
start execution of jobs
void cancel_jobs ()
cancel the entire job list
T * next_job ()
set current job. CAUTION: jobs may be modified by the execution of current_job. Therefore we copy current_job from jobs (and can then safely use current_job *).
T & get_current_job ()
return the current job
size_t get_size ()
return the current size
void add_job (const T &job)
add job to jobs
bool busy ()
return true if not all jobs are done yet
const char * get_started_loc ()
where joblist was started (also an indicator if all jobs were done)
Protected Attributes
std::vector< T > jobs
jobs to be performed
T current_job
the currently executed worklist item
Additional Inherited Members
Static Public Attributes inherited from Parallel_job_list_base
static const char * started_loc = 0
from where the joblist was started
Detailed Description
template<class T, bool has_destructor>
class Parallel_job_list< T, has_destructor >
A linked list of parallel jobs.
a list of parallel jobs. It is used to control the parallel computation of nested results. Initially the Parallel_job_list is created with one job. If nested values are encountered they are not computed immediately but added to the joblist for later execution.
Definition at line 188 of file PJob.hh.
Constructor & Destructor Documentation
Parallel_job_list()
template<class T , bool has_destructor> Parallel_job_list< T, has_destructor >::Parallel_job_list () inline
constructor: empty job list
Definition at line 192 of file PJob.hh.
Member Function Documentation
add_job()
template<class T , bool has_destructor> void Parallel_job_list< T, has_destructor >::add_job (const T & job) inline
add job to jobs
Definition at line 246 of file PJob.hh.
References Parallel_job_list< T, has_destructor >::jobs.
Referenced by ScalarFunction::do_scalar_AB(), and ScalarFunction::do_scalar_B().
busy()
template<class T , bool has_destructor> bool Parallel_job_list< T, has_destructor >::busy () inline
return true if not all jobs are done yet
Definition at line 250 of file PJob.hh.
References Parallel_job_list_base::started_loc.
cancel_jobs()
template<class T , bool has_destructor> void Parallel_job_list< T, has_destructor >::cancel_jobs () inline
cancel the entire job list
Definition at line 215 of file PJob.hh.
References Parallel_job_list< T, has_destructor >::jobs, and Parallel_job_list_base::started_loc.
Referenced by Thread_context::cancel_all_dyadic_jobs(), and Thread_context::cancel_all_monadic_jobs().
get_current_job()
template<class T , bool has_destructor> T & Parallel_job_list< T, has_destructor >::get_current_job () inline
return the current job
Definition at line 238 of file PJob.hh.
References Parallel_job_list< T, has_destructor >::current_job.
get_size()
template<class T , bool has_destructor> size_t Parallel_job_list< T, has_destructor >::get_size () inline
return the current size
Definition at line 242 of file PJob.hh.
References Parallel_job_list< T, has_destructor >::jobs.
get_started_loc()
template<class T , bool has_destructor> const char * Parallel_job_list< T, has_destructor >::get_started_loc () inline
where joblist was started (also an indicator if all jobs were done)
Definition at line 254 of file PJob.hh.
References Parallel_job_list_base::started_loc.
next_job()
template<class T , bool has_destructor> T * Parallel_job_list< T, has_destructor >::next_job () inline
set current job. CAUTION: jobs may be modified by the execution of current_job. Therefore we copy current_job from jobs (and can then safely use current_job *).
Definition at line 224 of file PJob.hh.
References Parallel_job_list< T, has_destructor >::current_job, Parallel_job_list< T, has_destructor >::jobs, and Parallel_job_list_base::started_loc.
Referenced by ScalarFunction::do_scalar_AB(), and ScalarFunction::do_scalar_B().
start()
template<class T , bool has_destructor> void Parallel_job_list< T, has_destructor >::start (const T & first_job, const char * loc) inline
start execution of jobs
Definition at line 196 of file PJob.hh.
References Parallel_job_list< T, has_destructor >::jobs, and Parallel_job_list_base::started_loc.
Referenced by ScalarFunction::do_scalar_AB(), and ScalarFunction::do_scalar_B().
Member Data Documentation
current_job
template<class T , bool has_destructor> T Parallel_job_list< T, has_destructor >::current_job protected
the currently executed worklist item
Definition at line 262 of file PJob.hh.
Referenced by Parallel_job_list< T, has_destructor >::get_current_job(), and Parallel_job_list< T, has_destructor >::next_job().
jobs
template<class T , bool has_destructor> std::vector<T> Parallel_job_list< T, has_destructor >::jobs protected
jobs to be performed
Definition at line 259 of file PJob.hh.
Referenced by Parallel_job_list< T, has_destructor >::add_job(), Parallel_job_list< T, has_destructor >::cancel_jobs(), Parallel_job_list< T, has_destructor >::get_size(), Parallel_job_list< T, has_destructor >::next_job(), and Parallel_job_list< T, has_destructor >::start().
The documentation for this class was generated from the following file:
src/PJob.hh