GNU APL: Symbol Class Reference
Symbol Class Reference
Base class for variables, defined functions, and distinguished names.
#include <Symbol.hh>
Public Member Functions
Symbol (Id id)
create a system symbol with Id id
Symbol (const UCS_string &ucs, Id id)
create a symbol with name ucs
virtual ~Symbol ()
destructor
ostream & list (ostream &out) const
List this Symbol (for)VARS,)FNS)
void write_OUT (FILE *out, uint64_t &seq) const
write this symbol in)OUT format to file out
virtual void resolve (Token &token, bool left)
set token according to the current NC/sym_val of this Symbol
void resolve_shared_variable (Token &token)
set token according to the current NC/sym_val of this shared var
virtual Token resolve_lv (const char *loc)
resolve a variable name for an assignment
TokenClass resolve_class (bool left)
return the token class of this Symbol WITHOUT calling resolve()
virtual int expunge ()
set current NameClass of this Symbol to NC_UNUSED_USER_NAME and remove any values associated with this symbol
void set_NC (NameClass nc)
Set current NameClass of this Symbol to nc.
void set_NC (NameClass nc, Function_P fun)
Set current NameClass of this Symbol to nc and function fun.
void share_var (SV_key key)
share variable with proc
SV_Coupling unshare_var ()
unshare a shared variable
void clear_vs ()
clear the value stack of this symbol
int compare (const Symbol &other) const
Compare name of this value with other.
virtual bool is_readonly () const
return true iff this variable is read-only (overloaded by RO_SystemVariable)
virtual void assign (Value_P value, bool clone, const char *loc)
Assign value to this Symbol.
void assign_shared_variable (Value_P value, const char *loc)
Assign value to this Symbol (which is a shared variable)
virtual void assign_indexed (const IndexExpr &index, Value_P value)
Indexed (multi-dimensional) assign value to this Symbol.
virtual void assign_indexed (const Value *X, Value_P value)
Indexed (one-dimensional) assign value to this Symbol.
virtual bool assign_named_lambda (Function_P lambda, const char *loc)
assign lambda, eg. V←{ ... }
virtual ostream & print (ostream &out) const
Print this Symbol to out.
ostream & print_verbose (ostream &out) const
Print this Symbol and its stack to out.
virtual void pop ()
Pop latest entry from the stack of this Symbol.
virtual void push ()
Push an undefined entry onto the stack of this Symbol.
virtual void push_label (Function_Line label)
push a label onto the stack of this Symbol
virtual void push_function (Function_P function)
push a function onto the stack of this Symbol
virtual void push_value (Value_P value)
Push an APL value onto the stack of this Symbol.
int get_exec_ufun_depth (const UserFunction *ufun)
return the depth (global == 0) of ufun on the stack. Use the largest depth if ufun is pushed multiple times
virtual Value_P get_apl_value () const
return the current APL value (or throw a VALUE_ERROR)
const Cell * get_first_cell () const
return the first Cell of this value without creating a value
bool can_be_assigned () const
return true, iff this Symbol can be assigned
SV_key get_SV_key () const
return the current SV_key (or throw a VALUE_ERROR)
void set_SV_key (SV_key key)
set the current SV_key
bool is_erased () const
return true, iff this Symbol is not used (i.e. erased)
virtual const Function * get_function () const
Return the current function (or throw a VALUE_ERROR)
Function_P get_function (unsigned int si) const
Return the function at SI level si, or 0 if none.
virtual UCS_string get_name () const
The name of this Symbol.
const UCS_string * get_name_ptr () const
overloaded NamedObject::get_name_ptr()
virtual Function_P get_function ()
overloaded NamedObject::get_function()
virtual Value_P get_value ()
overloaded NamedObject::get_value()
const Value * get_val_cptr () const
return a const pointer to the current APL value
Value * get_val_wptr ()
return a pointer to the current APL value
const char * cant_be_defined () const
return a reason why this symbol cant become a defined function
virtual Symbol * get_symbol ()
overloaded NamedObject::get_symbol()
virtual const Symbol * get_symbol () const
overloaded NamedObject::get_symbol()
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z...
const int value_stack_size () const
return the size of the value stack
const ValueStackItem * top_of_stack () const
return the top-most item on the value stack
ValueStackItem * top_of_stack ()
return the top-most item on the value stack
const ValueStackItem & operator[] (int idx) const
return the idx'th item on stack (higher index = newer item)
ValueStackItem & operator[] (int idx)
return the idx'th item on stack (higher index = newer item)
void set_monitor_callback (void(*callback)(const Symbol &, Symbol_Event))
set a callback function for symbol events
void unmark_all_values () const
clear the marked flag of all entries
int show_owners (ostream &out, const Value &value) const
print variables owning value
void dump (ostream &out) const
dump this symbol to out
void call_monitor_callback (Symbol_Event ev)
call the monitor callback function (if any) with event ev
bool equal (const UCS_string &ucs) const
Compare the name of this Symbol with ucs.
int get_SI_level (Function_P fun) const
return the level of fun on the stack of this Symbol) on the SI stack
int get_SI_level (const Value &val) const
return the SI stack level of val on the stack of this Symbol)
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Static Public Member Functions
static void vector_assignment (std::vector< Symbol * > &symbols, Value_P values)
perform a vector assignment (like (A B C)←1 2 3) for variables in symbols with values values
Public Attributes
Symbol * next
The next Symbol with the same hash value as this Symbol.
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Attributes
UCS_string name
the name of this Symbol
void(* monitor_callback)(const Symbol &, Symbol_Event sev)
called on symbol events (if non-0)
std::vector< ValueStackItem > value_stack
the value stack of this Symbol
Friends
class SymbolTable
Detailed Description
Base class for variables, defined functions, and distinguished names.
Definition at line 189 of file Symbol.hh.
Constructor & Destructor Documentation
Symbol() [1/2]
Symbol::Symbol (Id id)
create a system symbol with Id id
Definition at line 44 of file Symbol.cc.
References push().
Symbol() [2/2]
Symbol::Symbol (const UCS_string & ucs, Id id)
create a symbol with name ucs
Definition at line 53 of file Symbol.cc.
References push().
~Symbol()
virtual Symbol::~Symbol () inline virtual
destructor
Definition at line 201 of file Symbol.hh.
References clear_vs().
Member Function Documentation
assign()
void Symbol::assign (Value_P value, bool clone, const char * loc) virtual
Assign value to this Symbol.
Reimplemented in SystemVariable, RO_SystemVariable, Quad_CT, Quad_FC, Quad_IO, Quad_L, Quad_LX, Quad_PP, Quad_PR, Quad_PS, Quad_PW, Quad_Quad, Quad_QUOTE, Quad_R, Quad_SYL, Quad_TZ, Quad_X, Quad_RL, Quad_SVE, LAMBDA, ALPHA, ALPHA_U, CHI, OMEGA, and OMEGA_U.
Definition at line 123 of file Symbol.cc.
References assign_shared_variable(), Value_P_Base::get(), ValueStackItem::get_label(), get_name(), ValueStackItem::get_NC(), ValueStackItem::get_val_cptr(), monitor_callback, VH_entry::print_history(), ValueStackItem::set_apl_value(), and value_stack.
Referenced by Quad_CT::assign(), Quad_FC::assign(), Quad_IO::assign(), Quad_LX::assign(), Quad_PP::assign(), Quad_PR::assign(), Quad_PS::assign(), Quad_PW::assign(), Quad_SYL::assign(), Quad_TZ::assign(), Quad_RL::assign(), LAMBDA::assign(), ALPHA::assign(), ALPHA_U::assign(), CHI::assign(), OMEGA::assign(), OMEGA_U::assign(), Quad_FC::assign_indexed(), Quad_PS::assign_indexed(), Command::transfer_context::chars_1TF(), Command::transfer_context::numeric_1TF(), Quad_CT::push(), Quad_FC::push(), Quad_IO::push(), Quad_PP::push(), Quad_PR::push(), Quad_PS::push(), Quad_PW::push(), Quad_TZ::push(), push_value(), Quad_AI::Quad_AI(), Quad_AV::Quad_AV(), Quad_CT::Quad_CT(), Quad_FC::Quad_FC(), Quad_IO::Quad_IO(), Quad_L::Quad_L(), Quad_LC::Quad_LC(), Quad_LX::Quad_LX(), Quad_PP::Quad_PP(), Quad_PR::Quad_PR(), Quad_PS::Quad_PS(), Quad_PW::Quad_PW(), Quad_QUOTE::Quad_QUOTE(), Quad_R::Quad_R(), Quad_RL::Quad_RL(), Quad_SVE::Quad_SVE(), Quad_TC::Quad_TC(), Quad_TS::Quad_TS(), Quad_TZ::Quad_TZ(), Quad_UL::Quad_UL(), Quad_WA::Quad_WA(), Quad_X::Quad_X(), XML_Loading_Archive::read_Variable(), share_var(), and vector_assignment().
assign_indexed() [1/2]
void Symbol::assign_indexed (const IndexExpr & index, Value_P value) virtual
Indexed (multi-dimensional) assign value to this Symbol.
Reimplemented in Quad_SYL, and Quad_FC.
Definition at line 263 of file Symbol.cc.
References Shape::add_shape_item(), assign_indexed(), Value::element_count(), Value_P_Base::get(), get_apl_value(), IndexExpr::get_rank(), Shape::get_rank(), Value::get_rank(), Value::get_shape_item(), Cell::init(), IndexExpr::is_axis(), monitor_callback, MultiIndexIterator::more(), Cell::release(), value_stack, and IndexExpr::values.
Referenced by assign_indexed().
assign_indexed() [2/2]
void Symbol::assign_indexed (const Value * X, Value_P value) virtual
Indexed (one-dimensional) assign value to this Symbol.
Reimplemented in SystemVariable, RO_SystemVariable, Quad_FC, Quad_LX, Quad_PS, and Quad_SYL.
Definition at line 170 of file Symbol.cc.
References Value::element_count(), get_apl_value(), Value::get_cfirst(), Workspace::get_IO(), get_name(), Cell::get_near_int(), Cell::get_pointer_value(), Cell::init(), Cell::init_from_value(), Cell::is_pointer_cell(), Value::is_scalar(), monitor_callback, name, Cell::release(), and value_stack.
assign_named_lambda()
bool Symbol::assign_named_lambda (Function_P lambda, const char * loc) virtual
assign lambda, eg. V←{ ... }
Definition at line 348 of file Symbol.cc.
References UserFunction::get_func_ufun(), ValueStackItem::get_function(), get_name(), ValueStackItem::get_NC(), StateIndicator::get_parent(), monitor_callback, ValueStackItem::set_function(), Workspace::SI_top(), and value_stack.
assign_shared_variable()
void Symbol::assign_shared_variable (Value_P value, const char * loc)
Assign value to this Symbol (which is a shared variable)
Definition at line 1260 of file Symbol.cc.
References Error::error_name(), Value_P_Base::get(), Signal_base::get__SVAR_ASSIGNED__error(), Signal_base::get__SVAR_ASSIGNED__error_loc(), Svar_DB::get_DB_tcp(), CDR_string::get_items(), get_name(), get_SV_key(), Svar_record::get_svar_name(), Svar_record::is_ws_to_ws(), Svar_DB::may_set(), Signal_base::recv_TCP(), Svar_DB::set_state(), and CDR::to_CDR().
Referenced by assign().
call_monitor_callback()
void Symbol::call_monitor_callback (Symbol_Event ev) inline
call the monitor callback function (if any) with event ev
Definition at line 389 of file Symbol.hh.
References monitor_callback.
Referenced by SymbolTable::clear_slot(), and expunge().
can_be_assigned()
bool Symbol::can_be_assigned () const
return true, iff this Symbol can be assigned
Definition at line 560 of file Symbol.cc.
References value_stack.
cant_be_defined()
const char * Symbol::cant_be_defined () const
return a reason why this symbol cant become a defined function
Definition at line 529 of file Symbol.cc.
References Workspace::is_called(), name, and value_stack.
Referenced by NativeFunction::fix(), UserFunction::fix(), NativeFunction::NativeFunction(), and Nabla::open_existing_function().
clear_vs()
void Symbol::clear_vs ()
clear the value stack of this symbol
Definition at line 1219 of file Symbol.cc.
References ValueStackItem::get_function(), ValueStackItem::get_NC(), pop(), ValueStackItem::reset_apl_value(), ValueStackItem::set_NC(), and value_stack.
Referenced by SymbolTable::erase_one_symbol(), and ~Symbol().
compare()
int Symbol::compare (const Symbol & other) const inline
Compare name of this value with other.
Definition at line 242 of file Symbol.hh.
References UCS_string::compare(), and name.
dump()
void Symbol::dump (ostream & out) const
dump this symbol to out
Definition at line 1093 of file Symbol.cc.
References UserFunction::canonical(), Quad_CR::do_CR10_variable(), UserFunction::get_exec_properties(), UserFunction::get_func_ufun(), ValueStackItem::get_function(), UserFunction::get_local_var(), get_name(), ValueStackItem::get_NC(), ValueStackItem::get_val_cptr(), UserFunction::is_lambda(), UserFunction::local_var_count(), UCS_string::remove_leading_and_trailing_whitespaces(), UCS_string::size(), UCS_string::to_vector(), and value_stack.
Referenced by SymbolTable::dump().
equal()
bool Symbol::equal (const UCS_string & ucs) const inline
Compare the name of this Symbol with ucs.
Definition at line 393 of file Symbol.hh.
References UCS_string::compare(), and name.
expunge()
int Symbol::expunge () virtual
set current NameClass of this Symbol to NC_UNUSED_USER_NAME and remove any values associated with this symbol
Reimplemented in SystemVariable.
Definition at line 770 of file Symbol.cc.
References Workspace::add_expunged_function(), call_monitor_callback(), ValueStackItem::clear(), ValueStackItem::get_function(), ValueStackItem::get_NC(), Workspace::oldest_exec(), ValueStackItem::reset_apl_value(), ValueStackItem::set_NC(), and value_stack.
Referenced by SymbolTable::erase_one_symbol(), and Quad_EX::expunge().
get_apl_value()
Value_P Symbol::get_apl_value () const virtual
return the current APL value (or throw a VALUE_ERROR)
Reimplemented in Quad_SVE, Quad_WA, Quad_AI, Quad_ARG, Quad_EM, Quad_ET, Quad_L, Quad_LC, Quad_Quad, Quad_QUOTE, Quad_R, Quad_SYL, Quad_TS, Quad_UL, and Quad_X.
Definition at line 542 of file Symbol.cc.
References get_name(), Error::throw_symbol_error(), and value_stack.
Referenced by Quad_FC::assign_indexed(), assign_indexed(), Command::cmd_HELP(), Quad_FC::current(), Quad_PR::current(), Quad_CR::do_CR10(), SystemVariable::get_attributes(), Quad_TZ::pop(), resolve(), RO_SystemVariable::resolve(), UserFunction::set_locked_error_info(), share_var(), Quad_TF::tf2(), and Quad_TF::tf3().
get_attributes()
void Symbol::get_attributes (int mode, Value & Z) const virtual
store the attributes (as per ⎕AT) of symbol in Z...
Reimplemented in SystemVariable.
Definition at line 610 of file Symbol.cc.
References Value::CDR_data_size(), Value::element_count(), Value::get_CDR_type(), ValueStackItem::get_function(), ValueStackItem::get_NC(), get_val_cptr(), Value::next_ravel_0(), Value::next_ravel_Int(), Value::total_CDR_size_brutto(), and value_stack.
Referenced by Quad_AT::eval_AB().
get_exec_ufun_depth()
int Symbol::get_exec_ufun_depth (const UserFunction * ufun)
return the depth (global == 0) of ufun on the stack. Use the largest depth if ufun is pushed multiple times
Definition at line 496 of file Symbol.cc.
References ValueStackItem::get_function(), ValueStackItem::get_NC(), value_stack, and value_stack_size().
Referenced by XML_Saving_Archive::save_Function_name(), and XML_Saving_Archive::save_SI_entry().
get_first_cell()
const Cell * Symbol::get_first_cell () const
return the first Cell of this value without creating a value
Definition at line 552 of file Symbol.cc.
References value_stack.
Referenced by Quad_CT::current(), Quad_IO::current(), Quad_PP::current(), and Quad_PW::current().
get_function() [1/3]
Function_P Symbol::get_function () virtual
overloaded NamedObject::get_function()
Definition at line 600 of file Symbol.cc.
References ValueStackItem::get_function(), ValueStackItem::get_NC(), and value_stack.
get_function() [2/3]
Function_P Symbol::get_function () const virtual
Return the current function (or throw a VALUE_ERROR)
Reimplemented from NamedObject.
Definition at line 582 of file Symbol.cc.
References value_stack.
Referenced by Doxy::add_fun_to_call_graph(), Command::cmd_HELP(), Quad_CR::do_CR10(), Nabla::execute_escape(), UserFunction::fix(), Command::transfer_context::function_2TF(), Doxy::functions_table(), Workspace::is_called(), Prefix::is_value_parenthesis(), Stop_Trace::locate_fun(), Workspace::lookup_existing_name(), Doxy::make_call_graph(), Nabla::open_existing_function(), and Doxy::set_call_graph_root().
get_function() [3/3]
Function_P Symbol::get_function (unsigned int si) const
Return the function at SI level si, or 0 if none.
Definition at line 591 of file Symbol.cc.
References NamedObject::get_NC(), and value_stack.
get_name()
virtual UCS_string Symbol::get_name () const inline virtual
The name of this Symbol.
Reimplemented from NamedObject.
Definition at line 317 of file Symbol.hh.
References name.
Referenced by Doxy::add_fun_to_call_graph(), assign(), assign_indexed(), assign_named_lambda(), assign_shared_variable(), Doxy::bold_name(), SymbolTable::clear_slot(), Quad_CR::do_CR10(), Quad_NL::do_quad_NL(), dump(), Nabla::edit_header_line(), XML_Saving_Archive::emit_token_val(), TabExpansion::expand_help_topics(), TabExpansion::expand_user_name(), Doxy::functions_table(), Doxy::gen(), get_apl_value(), UserFunction::help(), UserFunction_header::init_signature(), Nabla::open_existing_function(), Nabla::open_new_function(), pop(), XML_Loading_Archive::read_Function(), XML_Loading_Archive::read_Shared_Variable(), XML_Loading_Archive::read_Variable(), Prefix::reduce_statements(), resolve(), resolve_lv(), resolve_shared_variable(), XML_Saving_Archive::save_SI_entry(), XML_Saving_Archive::save_Symbol(), UserFunction::set_locked_error_info(), show_owners(), StateIndicator::uses_function(), Doxy::variables_table(), and write_OUT().
get_name_ptr()
const UCS_string * Symbol::get_name_ptr () const inline
overloaded NamedObject::get_name_ptr()
Definition at line 320 of file Symbol.hh.
References name.
get_SI_level() [1/2]
int Symbol::get_SI_level (const Value & val) const
return the SI stack level of val on the stack of this Symbol)
Definition at line 1205 of file Symbol.cc.
References ValueStackItem::get_val_cptr(), StateIndicator::nth_push(), Workspace::SI_top(), and value_stack.
get_SI_level() [2/2]
int Symbol::get_SI_level (Function_P fun) const
return the level of fun on the stack of this Symbol) on the SI stack
Definition at line 1191 of file Symbol.cc.
References ValueStackItem::get_function(), StateIndicator::nth_push(), Workspace::SI_top(), and value_stack.
Referenced by Doxy::functions_table(), and Doxy::variables_table().
get_SV_key()
SV_key Symbol::get_SV_key () const
return the current SV_key (or throw a VALUE_ERROR)
Definition at line 566 of file Symbol.cc.
References value_stack.
Referenced by assign_shared_variable(), Quad_SVC::eval_AB(), Quad_SVO::eval_AB(), Quad_SVC::eval_B(), Quad_SVO::eval_B(), Quad_SVS::eval_B(), resolve_shared_variable(), and unshare_var().
get_symbol() [1/2]
virtual Symbol * Symbol::get_symbol () inline virtual
overloaded NamedObject::get_symbol()
Reimplemented from NamedObject.
Definition at line 340 of file Symbol.hh.
get_symbol() [2/2]
virtual const Symbol * Symbol::get_symbol () const inline virtual
overloaded NamedObject::get_symbol()
Reimplemented from NamedObject.
Definition at line 344 of file Symbol.hh.
get_val_cptr()
const Value * Symbol::get_val_cptr () const inline
return a const pointer to the current APL value
Definition at line 329 of file Symbol.hh.
References value_stack.
Referenced by get_attributes(), pop(), Doxy::variables_table(), and write_OUT().
get_val_wptr()
Value * Symbol::get_val_wptr () inline
return a pointer to the current APL value
Definition at line 333 of file Symbol.hh.
References value_stack.
get_value()
Value_P Symbol::get_value () virtual
overloaded NamedObject::get_value()
Definition at line 518 of file Symbol.cc.
References NamedObject::get_NC(), and value_stack.
Referenced by Quad_EX::expunge(), push_value(), Prefix::reduce_statements(), and resolve_lv().
is_erased()
bool Symbol::is_erased () const inline
return true, iff this Symbol is not used (i.e. erased)
Definition at line 305 of file Symbol.hh.
References value_stack, and value_stack_size().
Referenced by Command::cmd_HELP(), Quad_NL::do_quad_NL(), SymbolTable::erase_one_symbol(), TabExpansion::expand_help_topics(), TabExpansion::expand_user_name(), Doxy::gen(), list(), and XML_Saving_Archive::save_symtab().
is_readonly()
virtual bool Symbol::is_readonly () const inline virtual
return true iff this variable is read-only (overloaded by RO_SystemVariable)
Reimplemented in RO_SystemVariable.
Definition at line 247 of file Symbol.hh.
Referenced by XML_Loading_Archive::read_Variable(), and Quad_TF::tf1_inv().
list()
ostream & Symbol::list (ostream & out) const
List this Symbol (for)VARS,)FNS)
Definition at line 903 of file Symbol.cc.
References is_erased(), name, UCS_string::size(), and value_stack.
operator[]() [1/2]
ValueStackItem & Symbol::operator[] (int idx) inline
return the idx'th item on stack (higher index = newer item)
Definition at line 367 of file Symbol.hh.
References value_stack.
operator[]() [2/2]
const ValueStackItem & Symbol::operator[] (int idx) const inline
return the idx'th item on stack (higher index = newer item)
Definition at line 363 of file Symbol.hh.
References value_stack.
pop()
void Symbol::pop () virtual
Pop latest entry from the stack of this Symbol.
Reimplemented in Quad_RL, NL_SystemVariable, and Quad_TZ.
Definition at line 396 of file Symbol.cc.
References Value::get_flags(), get_name(), NamedObject::get_NC(), ValueStackItem::get_NC(), get_val_cptr(), monitor_callback, name, and value_stack.
Referenced by clear_vs(), Quad_RL::pop(), Quad_TZ::pop(), UserFunction_header::pop_local_vars(), XML_Loading_Archive::read_Function(), and XML_Loading_Archive::read_Label().
print()
ostream & Symbol::print (ostream & out) const virtual
Print this Symbol to out.
Reimplemented in SystemVariable.
Definition at line 63 of file Symbol.cc.
References name.
Referenced by Token::print_value(), and print_verbose().
print_verbose()
ostream & Symbol::print_verbose (ostream & out) const
Print this Symbol and its stack to out.
Definition at line 69 of file Symbol.cc.
References ValueStackItem::get_function(), ValueStackItem::get_label(), ValueStackItem::get_NC(), ValueStackItem::get_val_cptr(), print(), Value::print_properties(), and value_stack.
Referenced by SymbolTable::list_symbol().
push()
void Symbol::push () virtual
Push an undefined entry onto the stack of this Symbol.
Reimplemented in Quad_RL, NL_SystemVariable, Quad_CT, Quad_FC, Quad_IO, Quad_PP, Quad_PR, Quad_PS, Quad_PW, and Quad_TZ.
Definition at line 435 of file Symbol.cc.
References monitor_callback, name, and value_stack.
Referenced by UserFunction::eval_(), UserFunction::eval_AB(), UserFunction::eval_ALB(), UserFunction::eval_ALRB(), UserFunction::eval_ALRXB(), UserFunction::eval_ALXB(), UserFunction::eval_AXB(), UserFunction::eval_B(), UserFunction::eval_LB(), UserFunction::eval_LRB(), UserFunction::eval_LRXB(), UserFunction::eval_LXB(), UserFunction::eval_XB(), Quad_CT::push(), Quad_FC::push(), Quad_IO::push(), Quad_PP::push(), Quad_PR::push(), Quad_PS::push(), Quad_PW::push(), Quad_TZ::push(), XML_Loading_Archive::read_Function(), XML_Loading_Archive::read_Shared_Variable(), XML_Loading_Archive::read_unused_name(), XML_Loading_Archive::read_Variable(), and Symbol().
push_function()
void Symbol::push_function (Function_P function) virtual
push a function onto the stack of this Symbol
Reimplemented in NL_SystemVariable.
Definition at line 463 of file Symbol.cc.
References monitor_callback, name, ValueStackItem::set_function(), and value_stack.
Referenced by UserFunction::eval_ALB(), UserFunction::eval_ALRB(), UserFunction::eval_ALRXB(), UserFunction::eval_ALXB(), UserFunction::eval_LB(), UserFunction::eval_LRB(), UserFunction::eval_LRXB(), UserFunction::eval_LXB(), and XML_Loading_Archive::read_Function().
push_label()
void Symbol::push_label (Function_Line label) virtual
push a label onto the stack of this Symbol
Reimplemented in NL_SystemVariable.
Definition at line 449 of file Symbol.cc.
References monitor_callback, name, and value_stack.
Referenced by XML_Loading_Archive::read_Label().
push_value()
void Symbol::push_value (Value_P value) virtual
Push an APL value onto the stack of this Symbol.
Reimplemented in NL_SystemVariable.
Definition at line 479 of file Symbol.cc.
References assign(), get_value(), monitor_callback, name, and value_stack.
Referenced by UserFunction::eval_AB(), UserFunction::eval_ALB(), UserFunction::eval_ALRB(), UserFunction::eval_ALRXB(), UserFunction::eval_ALXB(), UserFunction::eval_AXB(), UserFunction::eval_B(), UserFunction::eval_LB(), UserFunction::eval_LRB(), UserFunction::eval_LRXB(), UserFunction::eval_LXB(), UserFunction::eval_XB(), and Quad_RL::push().
resolve()
void Symbol::resolve (Token & token, bool left) virtual
set token according to the current NC/sym_val of this Symbol
Reimplemented in RO_SystemVariable, and Quad_Quad.
Definition at line 659 of file Symbol.cc.
References get_apl_value(), ValueStackItem::get_function(), ValueStackItem::get_label(), get_name(), ValueStackItem::get_NC(), Token::move_1(), Token::move_2(), resolve_shared_variable(), Error::throw_symbol_error(), and value_stack.
Referenced by Prefix::reduce_statements().
resolve_class()
TokenClass Symbol::resolve_class (bool left)
return the token class of this Symbol WITHOUT calling resolve()
Definition at line 738 of file Symbol.cc.
References value_stack.
Referenced by Prefix::is_value_bracket(), and Prefix::reduce_statements().
resolve_lv()
Token Symbol::resolve_lv (const char * loc) virtual
resolve a variable name for an assignment
Reimplemented in SystemVariable.
Definition at line 716 of file Symbol.cc.
References get_name(), get_value(), and value_stack.
resolve_shared_variable()
void Symbol::resolve_shared_variable (Token & token)
set token according to the current NC/sym_val of this shared var
Definition at line 1360 of file Symbol.cc.
References Error::error_name(), CDR::from_CDR(), Signal_base::get__VALUE_IS__cdr_value(), Signal_base::get__VALUE_IS__error(), Signal_base::get__VALUE_IS__error_loc(), Signal_base::get__WSWS_VALUE_IS__cdr_value(), Svar_DB::get_DB_tcp(), ProcessorID::get_id(), get_name(), get_SV_key(), Svar_record::get_svar_name(), Svar_record::is_ws_to_ws(), Svar_DB::may_use(), Signal_base::recv_TCP(), and Svar_DB::set_state().
Referenced by resolve().
set_monitor_callback()
void Symbol::set_monitor_callback (void(*)(const Symbol &, Symbol_Event) callback) inline
set a callback function for symbol events
Definition at line 371 of file Symbol.hh.
References monitor_callback.
set_NC() [1/2]
void Symbol::set_NC (NameClass nc)
Set current NameClass of this Symbol to nc.
Definition at line 821 of file Symbol.cc.
References ValueStackItem::get_NC(), ValueStackItem::set_NC(), and value_stack.
Referenced by NativeFunction::fix(), UserFunction::fix(), and NativeFunction::NativeFunction().
set_NC() [2/2]
void Symbol::set_NC (NameClass nc, Function_P fun)
Set current NameClass of this Symbol to nc and function fun.
Definition at line 886 of file Symbol.cc.
References ValueStackItem::clear_function(), ValueStackItem::get_NC(), ValueStackItem::set_function(), and value_stack.
set_SV_key()
void Symbol::set_SV_key (SV_key key)
set the current SV_key
Definition at line 576 of file Symbol.cc.
References value_stack.
Referenced by share_var(), and unshare_var().
share_var()
void Symbol::share_var (SV_key key)
share variable with proc
Definition at line 837 of file Symbol.cc.
References assign(), get_apl_value(), ValueStackItem::get_NC(), set_SV_key(), and value_stack.
Referenced by Quad_SVO::eval_AB().
show_owners()
int Symbol::show_owners (ostream & out, const Value & value) const
print variables owning value
Definition at line 1023 of file Symbol.cc.
References ValueStackItem::get_function(), get_name(), ValueStackItem::get_NC(), ValueStackItem::get_val_cptr(), Value::is_or_contains(), Executable::show_owners(), and value_stack.
Referenced by Workspace::show_owners().
top_of_stack() [1/2]
ValueStackItem * Symbol::top_of_stack () inline
return the top-most item on the value stack
Definition at line 359 of file Symbol.hh.
References value_stack.
top_of_stack() [2/2]
const ValueStackItem * Symbol::top_of_stack () const inline
return the top-most item on the value stack
Definition at line 355 of file Symbol.hh.
References value_stack.
Referenced by Command::cmd_HELP(), Quad_SVO::eval_AB(), and XML_Loading_Archive::read_Function().
unmark_all_values()
void Symbol::unmark_all_values () const
clear the marked flag of all entries
Definition at line 991 of file Symbol.cc.
References ValueStackItem::get_function(), ValueStackItem::get_NC(), ValueStackItem::get_val_cptr(), Value::unmark(), and value_stack.
Referenced by Workspace::unmark_all_values().
unshare_var()
SV_Coupling Symbol::unshare_var ()
unshare a shared variable
Definition at line 867 of file Symbol.cc.
References Svar_record::get_coupling(), ValueStackItem::get_NC(), get_SV_key(), Svar_DB::retract_var(), ValueStackItem::set_NC(), set_SV_key(), and value_stack.
Referenced by Quad_SVR::eval_B().
value_stack_size()
const int Symbol::value_stack_size () const inline
return the size of the value stack
Definition at line 351 of file Symbol.hh.
References value_stack.
Referenced by Doxy::add_fun_to_call_graph(), LAMBDA::assign(), ALPHA::assign(), ALPHA_U::assign(), CHI::assign(), OMEGA::assign(), OMEGA_U::assign(), XML_Loading_Archive::find_lambda(), Doxy::functions_table(), Doxy::gen(), get_exec_ufun_depth(), is_erased(), Doxy::make_call_graph(), XML_Loading_Archive::read_Function_name(), XML_Loading_Archive::read_Symbol(), XML_Loading_Archive::read_Variable(), XML_Saving_Archive::save_Symbol(), and Doxy::variables_table().
vector_assignment()
void Symbol::vector_assignment (std::vector< Symbol * > & symbols, Value_P values) static
perform a vector assignment (like (A B C)←1 2 3) for variables in symbols with values values
Definition at line 1065 of file Symbol.cc.
References assign(), Cell::get_pointer_value(), and Cell::is_pointer_cell().
write_OUT()
void Symbol::write_OUT (FILE * out, uint64_t & seq) const
write this symbol in)OUT format to file out
Definition at line 927 of file Symbol.cc.
References UCS_string::append(), YMDhmsu::day, Token::get_apl_val(), get_name(), NamedObject::get_NC(), get_val_cptr(), YMDhmsu::hour, YMDhmsu::micro, YMDhmsu::minute, YMDhmsu::month, YMDhmsu::second, UCS_string::size(), Quad_TF::tf2_fun_ucs(), Quad_TF::tf2_var(), Avec::unicode_to_cp(), value_stack, and YMDhmsu::year.
Referenced by Workspace::write_OUT().
Friends And Related Function Documentation
SymbolTable
friend class SymbolTable friend
Definition at line 191 of file Symbol.hh.
Member Data Documentation
monitor_callback
void(* Symbol::monitor_callback) (const Symbol &, Symbol_Event sev) protected
called on symbol events (if non-0)
Definition at line 410 of file Symbol.hh.
Referenced by assign(), assign_indexed(), assign_named_lambda(), call_monitor_callback(), pop(), push(), push_function(), push_label(), push_value(), and set_monitor_callback().
name
UCS_string Symbol::name protected
the name of this Symbol
Definition at line 407 of file Symbol.hh.
Referenced by assign_indexed(), cant_be_defined(), compare(), equal(), get_name(), get_name_ptr(), list(), pop(), print(), push(), push_function(), push_label(), and push_value().
next
Symbol* Symbol::next
The next Symbol with the same hash value as this Symbol.
Definition at line 403 of file Symbol.hh.
Referenced by SymbolTable::clear_slot(), SymbolTable::dump(), SymbolTable::find_lambda_name(), SymbolTable::get_all_symbols(), SymbolTable::list(), SymbolTable::lookup_symbol(), SymbolTable::show_owners(), SymbolTable::unmark_all_values(), and SymbolTable::write_all_symbols().
value_stack
std::vector<ValueStackItem> Symbol::value_stack protected
the value stack of this Symbol
Definition at line 413 of file Symbol.hh.
Referenced by assign(), assign_indexed(), assign_named_lambda(), can_be_assigned(), cant_be_defined(), clear_vs(), dump(), SymbolTable::erase_one_symbol(), expunge(), get_apl_value(), get_attributes(), get_exec_ufun_depth(), get_first_cell(), get_function(), Quad_RL::get_random(), get_SI_level(), get_SV_key(), get_val_cptr(), get_val_wptr(), get_value(), is_erased(), list(), operator[](), Quad_RL::pop(), pop(), print_verbose(), push(), push_function(), push_label(), push_value(), resolve(), resolve_class(), resolve_lv(), set_NC(), set_SV_key(), share_var(), show_owners(), top_of_stack(), unmark_all_values(), unshare_var(), value_stack_size(), and write_OUT().
The documentation for this class was generated from the following files:
src/Symbol.hh
src/Symbol.cc