GNU APL: UserFunction_header Class Reference
UserFunction_header Class Reference
The (symbols in the) header of a defined function.
#include <UserFunction_header.hh>
Public Member Functions
UserFunction_header (const UCS_string &txt, bool macro)
constructor from first line in txt (for proper defined functions)
UserFunction_header (Fun_signature sig, int lambda_num)
constructor from signature (for lambdas)
int get_fun_valence () const
return the number of value arguments
int get_oper_valence () const
return the number of operator arguments
const char * get_error_info () const
return source location where error was detected
bool has_result () const
return true if the header indicates a result (Z←)
bool has_vars () const
return true if the header contains variables (result, arguments, or local variables
int has_axis () const
return true iff the function returns a value
bool is_operator () const
return true if this defined function header is an operator
UCS_string get_name () const
return the name of the function
Symbol * Z () const
return the Symbol for the function result
Symbol * A () const
return the Symbol for the left argument
Symbol * LO () const
return the Symbol for the left function argument
Symbol * FUN () const
return the Symbol for the left function argument
Symbol * X () const
return the Symbol for the right argument
Symbol * RO () const
return the Symbol for the right function argument
Symbol * B () const
return the Symbol for the right argument
ErrorCode get_error () const
return error if header was not parsed successfully
bool localizes (const Symbol *sym) const
return true if this function localizes sym
void print_properties (ostream &out, int indent) const
print local vars etc.
void add_local_var (Symbol *sym)
add a local variable
void pop_local_vars () const
pop all local vars, labels, and parameters
void print_local_vars (ostream &out) const
print the local variables for command)SINL
void reverse_local_vars ()
reverse the order of the local vars (if parsed back-to-front)
void add_label (Symbol *sym, Function_Line line)
add a label
void remove_duplicate_local_variables ()
Check that all function params, local vars. and labels are unique.
void eval_common () const
push Z (if defined), local variables, and labels.
ShapeItem local_var_count () const
return the number of local variables
const Symbol * get_local_var (ShapeItem idx) const
return the idx'th local variable
Static Public Member Functions
static UCS_string lambda_header (Fun_signature sig, int lambda_num)
the header (as per SIG_xxx and local_vars)
Protected Member Functions
const char * init_signature (const UCS_string &text, bool macro)
init the signature from text
const char * init_local_vars (const UCS_string &text, bool macro)
init the local variables from text
void remove_duplicate_local_var (const Symbol *sym, size_t pos)
remove sym from local_vars if it occurs at pos or above
Static Protected Member Functions
static bool signature_is_valid (Fun_signature sig)
return true iff bitmap sig is a valid funvtion signature
Protected Attributes
ErrorCode error
error if header was not parsed successfully
const char * error_info
source location where error was detected
UCS_string function_name
the name of this function. In most cases function_name is sym_FUN->get_name(), but for lambdas it is not.
Symbol * sym_Z
optional result
Symbol * sym_A
optional left function arg
Symbol * sym_LO
optional left operator function
Symbol * sym_FUN
optional symbol for function name (0 for lambdas)
Symbol * sym_RO
optional right operator function
Symbol * sym_X
optional right operator function axis
Symbol * sym_B
optional right function arg
std::vector< Symbol * > local_vars
The local variables of this function.
std::vector< labVal > label_values
The labels of this function.
Detailed Description
The (symbols in the) header of a defined function.
Definition at line 35 of file UserFunction_header.hh.
Constructor & Destructor Documentation
UserFunction_header() [1/2]
UserFunction_header::UserFunction_header (const UCS_string & txt, bool macro)
constructor from first line in txt (for proper defined functions)
Definition at line 40 of file UserFunction_header.cc.
References UCS_string::append(), error, error_info, init_local_vars(), init_signature(), and UCS_string::size().
UserFunction_header() [2/2]
UserFunction_header::UserFunction_header (Fun_signature sig, int lambda_num)
constructor from signature (for lambdas)
Definition at line 87 of file UserFunction_header.cc.
References UCS_string::append(), UCS_string::append_number(), error, error_info, function_name, signature_is_valid(), sym_A, sym_B, sym_LO, sym_RO, sym_X, and sym_Z.
Member Function Documentation
A()
Symbol * UserFunction_header::A () const inline
return the Symbol for the left argument
Definition at line 85 of file UserFunction_header.hh.
References sym_A.
Referenced by Doxy::bold_name(), UserFunction::eval_AB(), UserFunction::eval_ALB(), UserFunction::eval_ALRB(), UserFunction::eval_ALRXB(), UserFunction::eval_ALXB(), UserFunction::eval_AXB(), UserFunction::eval_B(), UserFunction::eval_LB(), UserFunction::eval_LRB(), UserFunction::eval_LRXB(), UserFunction::eval_LXB(), UserFunction::eval_XB(), UserFunction::pushes_sym(), UserFunction::set_locked_error_info(), and UserFunction::UserFunction().
add_label()
void UserFunction_header::add_label (Symbol * sym, Function_Line line) inline
add a label
Definition at line 125 of file UserFunction_header.hh.
References label_values.
Referenced by UserFunction::add_label().
add_local_var()
void UserFunction_header::add_local_var (Symbol * sym) inline
add a local variable
Definition at line 112 of file UserFunction_header.hh.
References local_vars.
Referenced by UserFunction::UserFunction().
B()
Symbol * UserFunction_header::B () const inline
return the Symbol for the right argument
Definition at line 100 of file UserFunction_header.hh.
References sym_B.
Referenced by Doxy::bold_name(), UserFunction::eval_(), UserFunction::eval_AB(), UserFunction::eval_ALB(), UserFunction::eval_ALRB(), UserFunction::eval_ALRXB(), UserFunction::eval_ALXB(), UserFunction::eval_AXB(), UserFunction::eval_B(), UserFunction::eval_LB(), UserFunction::eval_LRB(), UserFunction::eval_LRXB(), UserFunction::eval_LXB(), UserFunction::eval_XB(), UserFunction::pushes_sym(), UserFunction::set_locked_error_info(), and UserFunction::UserFunction().
eval_common()
void UserFunction_header::eval_common () const
push Z (if defined), local variables, and labels.
Definition at line 515 of file UserFunction_header.cc.
References label_values, and local_vars.
Referenced by UserFunction::eval_(), UserFunction::eval_AB(), UserFunction::eval_ALB(), UserFunction::eval_ALRB(), UserFunction::eval_ALRXB(), UserFunction::eval_ALXB(), UserFunction::eval_AXB(), UserFunction::eval_B(), UserFunction::eval_LB(), UserFunction::eval_LRB(), UserFunction::eval_LRXB(), UserFunction::eval_LXB(), and UserFunction::eval_XB().
FUN()
Symbol * UserFunction_header::FUN () const inline
return the Symbol for the left function argument
Definition at line 91 of file UserFunction_header.hh.
References sym_FUN.
Referenced by UserFunction::fix().
get_error()
ErrorCode UserFunction_header::get_error () const inline
return error if header was not parsed successfully
Definition at line 103 of file UserFunction_header.hh.
References error.
Referenced by Quad_L::assign(), Quad_R::assign(), Quad_X::assign(), Workspace::clear_error(), Nabla::edit_header_line(), Quad_EC::eoc(), Quad_SI::eval_AB(), Quad_SI::eval_B(), Quad_ES::event_simulate(), Command::finish_context(), Quad_EM::get_apl_value(), Quad_ET::get_apl_value(), Workspace::get_error(), Doxy::SI_table(), Workspace::SI_top_error(), Nabla::start(), Error::update_error_info(), and UserFunction::UserFunction().
get_error_info()
const char * UserFunction_header::get_error_info () const inline
return source location where error was detected
Definition at line 61 of file UserFunction_header.hh.
References error_info.
Referenced by Nabla::start(), and UserFunction::UserFunction().
get_fun_valence()
int UserFunction_header::get_fun_valence () const inline
return the number of value arguments
Definition at line 45 of file UserFunction_header.hh.
References sym_A, and sym_B.
Referenced by UserFunction::get_fun_valence().
get_local_var()
const Symbol * UserFunction_header::get_local_var (ShapeItem idx) const inline
return the idx'th local variable
Definition at line 145 of file UserFunction_header.hh.
References local_vars.
Referenced by UserFunction::get_local_var().
get_name()
UCS_string UserFunction_header::get_name () const inline
return the name of the function
Definition at line 79 of file UserFunction_header.hh.
References function_name.
Referenced by Doxy::bold_name(), InputFile::check_filter(), Nabla::edit_header_line(), UserFunction::fix(), UserFunction::get_name(), UserFunction::get_name_and_line(), UserFunction::is_lambda(), UserFunction::parse_body(), UserFunction::print(), UserFunction::set_locked_error_info(), and Nabla::start().
get_oper_valence()
int UserFunction_header::get_oper_valence () const inline
return the number of operator arguments
Definition at line 53 of file UserFunction_header.hh.
References sym_LO, and sym_RO.
Referenced by UserFunction::get_oper_valence().
has_axis()
int UserFunction_header::has_axis () const inline
return true iff the function returns a value
Definition at line 73 of file UserFunction_header.hh.
References sym_X.
Referenced by UserFunction::has_axis().
has_result()
bool UserFunction_header::has_result () const inline
return true if the header indicates a result (Z←)
Definition at line 64 of file UserFunction_header.hh.
References sym_Z.
Referenced by UserFunction::has_result().
has_vars()
bool UserFunction_header::has_vars () const inline
return true if the header contains variables (result, arguments, or local variables
Definition at line 68 of file UserFunction_header.hh.
References local_vars, sym_A, sym_B, sym_LO, sym_RO, sym_X, and sym_Z.
Referenced by Nabla::start().
init_local_vars()
const char * UserFunction_header::init_local_vars (const UCS_string & text, bool macro) protected
init the local variables from text
Definition at line 312 of file UserFunction_header.cc.
References error, local_vars, remove_duplicate_local_variables(), and Tokenizer::tokenize().
Referenced by UserFunction_header().
init_signature()
const char * UserFunction_header::init_signature (const UCS_string & text, bool macro) protected
init the signature from text
Definition at line 150 of file UserFunction_header.cc.
References error, function_name, Symbol::get_name(), sym_A, sym_B, sym_FUN, sym_LO, sym_RO, sym_X, sym_Z, and Tokenizer::tokenize().
Referenced by UserFunction_header().
is_operator()
bool UserFunction_header::is_operator () const inline
return true if this defined function header is an operator
Definition at line 76 of file UserFunction_header.hh.
References sym_LO.
Referenced by UserFunction::is_operator(), and print_properties().
lambda_header()
UCS_string UserFunction_header::lambda_header (Fun_signature sig, int lambda_num) static
the header (as per SIG_xxx and local_vars)
Definition at line 447 of file UserFunction_header.cc.
Referenced by Executable::Executable(), and Executable::setup_one_lambda().
LO()
Symbol * UserFunction_header::LO () const inline
return the Symbol for the left function argument
Definition at line 88 of file UserFunction_header.hh.
References sym_LO.
Referenced by Doxy::bold_name(), UserFunction::eval_AB(), UserFunction::eval_ALB(), UserFunction::eval_ALRB(), UserFunction::eval_ALRXB(), UserFunction::eval_ALXB(), UserFunction::eval_AXB(), UserFunction::eval_B(), UserFunction::eval_LB(), UserFunction::eval_LRB(), UserFunction::eval_LRXB(), UserFunction::eval_LXB(), UserFunction::eval_XB(), UserFunction::fix(), UserFunction::pushes_sym(), and UserFunction::UserFunction().
local_var_count()
ShapeItem UserFunction_header::local_var_count () const inline
return the number of local variables
Definition at line 141 of file UserFunction_header.hh.
References local_vars.
Referenced by UserFunction::local_var_count().
localizes()
bool UserFunction_header::localizes (const Symbol * sym) const
return true if this function localizes sym
Definition at line 466 of file UserFunction_header.cc.
References label_values, local_vars, sym_A, sym_B, sym_LO, sym_RO, sym_X, and sym_Z.
Referenced by UserFunction::localizes().
pop_local_vars()
void UserFunction_header::pop_local_vars () const
pop all local vars, labels, and parameters
Definition at line 367 of file UserFunction_header.cc.
References label_values, local_vars, Symbol::pop(), sym_A, sym_B, sym_LO, sym_RO, sym_X, and sym_Z.
Referenced by UserFunction::pop_local_vars().
print_local_vars()
void UserFunction_header::print_local_vars (ostream & out) const
print the local variables for command)SINL
Definition at line 382 of file UserFunction_header.cc.
References local_vars, sym_A, sym_B, sym_LO, sym_RO, and sym_Z.
Referenced by UserFunction::print_local_vars().
print_properties()
void UserFunction_header::print_properties (ostream & out, int indent) const
print local vars etc.
Definition at line 482 of file UserFunction_header.cc.
References function_name, is_operator(), label_values, local_vars, sym_A, sym_B, sym_LO, sym_RO, and sym_Z.
Referenced by UserFunction::print_properties().
remove_duplicate_local_var()
void UserFunction_header::remove_duplicate_local_var (const Symbol * sym, size_t pos) protected
remove sym from local_vars if it occurs at pos or above
Definition at line 427 of file UserFunction_header.cc.
References local_vars.
Referenced by remove_duplicate_local_variables().
remove_duplicate_local_variables()
void UserFunction_header::remove_duplicate_local_variables ()
Check that all function params, local vars. and labels are unique.
Definition at line 406 of file UserFunction_header.cc.
References label_values, local_vars, remove_duplicate_local_var(), sym_A, sym_B, sym_X, and sym_Z.
Referenced by init_local_vars().
reverse_local_vars()
void UserFunction_header::reverse_local_vars ()
reverse the order of the local vars (if parsed back-to-front)
Definition at line 394 of file UserFunction_header.cc.
References local_vars.
Referenced by UserFunction::UserFunction().
RO()
Symbol * UserFunction_header::RO () const inline
return the Symbol for the right function argument
Definition at line 97 of file UserFunction_header.hh.
References sym_RO.
Referenced by Doxy::bold_name(), UserFunction::eval_ALB(), UserFunction::eval_ALRB(), UserFunction::eval_ALRXB(), UserFunction::eval_ALXB(), UserFunction::eval_LB(), UserFunction::eval_LRB(), UserFunction::eval_LRXB(), UserFunction::eval_LXB(), UserFunction::pushes_sym(), and UserFunction::UserFunction().
signature_is_valid()
bool UserFunction_header::signature_is_valid (Fun_signature sig) static protected
return true iff bitmap sig is a valid funvtion signature
Definition at line 119 of file UserFunction_header.cc.
Referenced by UserFunction_header().
X()
Symbol * UserFunction_header::X () const inline
return the Symbol for the right argument
Definition at line 94 of file UserFunction_header.hh.
References sym_X.
Referenced by UserFunction::eval_AB(), UserFunction::eval_ALB(), UserFunction::eval_ALRB(), UserFunction::eval_ALRXB(), UserFunction::eval_ALXB(), UserFunction::eval_AXB(), UserFunction::eval_B(), UserFunction::eval_LB(), UserFunction::eval_LRB(), UserFunction::eval_LRXB(), UserFunction::eval_LXB(), UserFunction::eval_XB(), and UserFunction::pushes_sym().
Z()
Symbol * UserFunction_header::Z () const inline
return the Symbol for the function result
Definition at line 82 of file UserFunction_header.hh.
References sym_Z.
Referenced by Doxy::bold_name(), UserFunction::eval_(), UserFunction::eval_AB(), UserFunction::eval_ALB(), UserFunction::eval_ALRB(), UserFunction::eval_ALRXB(), UserFunction::eval_ALXB(), UserFunction::eval_AXB(), UserFunction::eval_B(), UserFunction::eval_LB(), UserFunction::eval_LRB(), UserFunction::eval_LRXB(), UserFunction::eval_LXB(), UserFunction::eval_XB(), UserFunction::get_sym_Z(), UserFunction::parse_body(), and UserFunction::pushes_sym().
Member Data Documentation
error
ErrorCode UserFunction_header::error protected
error if header was not parsed successfully
Definition at line 162 of file UserFunction_header.hh.
Referenced by get_error(), init_local_vars(), init_signature(), and UserFunction_header().
error_info
const char* UserFunction_header::error_info protected
source location where error was detected
Definition at line 165 of file UserFunction_header.hh.
Referenced by get_error_info(), and UserFunction_header().
function_name
UCS_string UserFunction_header::function_name protected
the name of this function. In most cases function_name is sym_FUN->get_name(), but for lambdas it is not.
Definition at line 169 of file UserFunction_header.hh.
Referenced by get_name(), init_signature(), print_properties(), and UserFunction_header().
label_values
std::vector<labVal> UserFunction_header::label_values protected
The labels of this function.
Definition at line 196 of file UserFunction_header.hh.
Referenced by add_label(), eval_common(), localizes(), pop_local_vars(), print_properties(), and remove_duplicate_local_variables().
local_vars
std::vector<Symbol *> UserFunction_header::local_vars protected
The local variables of this function.
Definition at line 193 of file UserFunction_header.hh.
Referenced by add_local_var(), eval_common(), get_local_var(), has_vars(), init_local_vars(), local_var_count(), localizes(), pop_local_vars(), print_local_vars(), print_properties(), remove_duplicate_local_var(), remove_duplicate_local_variables(), and reverse_local_vars().
sym_A
Symbol* UserFunction_header::sym_A protected
optional left function arg
Definition at line 175 of file UserFunction_header.hh.
Referenced by A(), get_fun_valence(), has_vars(), init_signature(), localizes(), pop_local_vars(), print_local_vars(), print_properties(), remove_duplicate_local_variables(), and UserFunction_header().
sym_B
Symbol* UserFunction_header::sym_B protected
optional right function arg
Definition at line 190 of file UserFunction_header.hh.
Referenced by B(), get_fun_valence(), has_vars(), init_signature(), localizes(), pop_local_vars(), print_local_vars(), print_properties(), remove_duplicate_local_variables(), and UserFunction_header().
sym_FUN
Symbol* UserFunction_header::sym_FUN protected
optional symbol for function name (0 for lambdas)
Definition at line 181 of file UserFunction_header.hh.
Referenced by FUN(), and init_signature().
sym_LO
Symbol* UserFunction_header::sym_LO protected
optional left operator function
Definition at line 178 of file UserFunction_header.hh.
Referenced by get_oper_valence(), has_vars(), init_signature(), is_operator(), LO(), localizes(), pop_local_vars(), print_local_vars(), print_properties(), and UserFunction_header().
sym_RO
Symbol* UserFunction_header::sym_RO protected
optional right operator function
Definition at line 184 of file UserFunction_header.hh.
Referenced by get_oper_valence(), has_vars(), init_signature(), localizes(), pop_local_vars(), print_local_vars(), print_properties(), RO(), and UserFunction_header().
sym_X
Symbol* UserFunction_header::sym_X protected
optional right operator function axis
Definition at line 187 of file UserFunction_header.hh.
Referenced by has_axis(), has_vars(), init_signature(), localizes(), pop_local_vars(), remove_duplicate_local_variables(), UserFunction_header(), and X().
sym_Z
Symbol* UserFunction_header::sym_Z protected
optional result
Definition at line 172 of file UserFunction_header.hh.
Referenced by has_result(), has_vars(), init_signature(), localizes(), pop_local_vars(), print_local_vars(), print_properties(), remove_duplicate_local_variables(), UserFunction_header(), and Z().
The documentation for this class was generated from the following files:
src/UserFunction_header.hh
src/UserFunction_header.cc