GNU APL: Prefix Class Reference
Prefix Class Reference
a class for reducing all statements of an Executable
#include <Prefix.hh>
Public Types
enum {
MAX_CONTENT = 10*MAX_REDUCTION_LEN ,
MAX_CONTENT_1 = MAX_CONTENT - 1
}
max. number of lookahead token
Public Member Functions
Prefix (StateIndicator &_si, const Token_string &_body)
constructor
void clean_up ()
destructor
bool uses_function (const UserFunction *ufun) const
return true if ufun is on the stack
bool has_quad_LRX () const
return true if the state of this Prefix has ⎕R (and maybe ⎕L or ⎕X).
void print (ostream &out, int indent) const
print the state of this parser
void syntax_error (const char *loc)
throw an E_LEFT_SYNTAX_ERROR or an E_SYNTAX_ERROR
void lock_values (bool lock)
prevent or allow erase() of values on vstacks
void unmark_all_values () const
clear the mark flag of all values in this Prefix
int show_owners (const char *prfx, ostream &out, const Value &value) const
print all owners of value
Function_PC get_range_high () const
highest PC in current statement
Function_PC get_range_low () const
lowest PC in current statement
bool value_expected ()
lookahead is a complete index. return true if it belongs to a value and is not a function axis.
void print_range (ostream &out) const
print the current range (PC from - PC to) on out
bool replace_AB (Value_P old_value, Value_P new_value)
replace the left or right argument of a function (for retry) and return true on success
Value_P * locate_L (UCS_string &function)
return the left argument of a failed primitive function (if any)
Value_P * locate_X (UCS_string &function)
return the axis argument of a failed primitive function (if any)
Value_P * locate_R (UCS_string &function)
return the right argument of a failed primitive function (if any)
const Function * get_dyadic_fun () const
return the current monadic function (if any)
const Function * get_monadic_fun () const
return the current dyadic function (if any)
Token reduce_statements ()
execute one context (user defined function or operator, execute, or immediate execution)
int size () const
return the number of token currently in the FIFO
const Token & _at0 () const
return the leftmost token (e.g. A in A←B)
const Token & at0 () const
return the leftmost token (e.g. A in A←B)
Token & at0 ()
return the leftmost token (e.g. A in A←B)
const Token & at1 () const
return the second token from the left (e.g. ← in A←B)
Token & at1 ()
return the second token from the left (e.g. ← in A←B)
Token & at2 ()
return the third token from the left (e.g. B in A←B)
Token & at3 ()
return the fourth token from the left (e.g. B in A+/B)
bool dont_reduce (TokenClass next) const
return true if the next token binds stronger than the best match
Assign_state get_assign_state () const
return the current assignment state
void set_assign_state (Assign_state new_state)
set the current assignment state
Function_PC get_lookahead_high () const
return the highest PC seen in the current statement
Token_loc lookahead ()
read one more token (don't store yet)
void push (const Token_loc &tl)
store one more token
void pop_args_push_result (const Token &result)
pop prefix_len items and push result
Token_loc & pop ()
remove the leftmost token (e,g, A in A←B) from the stack and return it
void pop_and_discard ()
discard the leftmost token (e,g, A in A←B) from the stack
int vector_ass_count () const
the number of TOK_LSYMB2 tokens ahead (excluding the leftmost one already read into content)
void reset (const char *loc)
reset statement to empty state (e.g. after →N)
void print_stack (ostream &out, const char *loc) const
print the current stack
void set_PC (Function_PC new_pc)
set a new PC
Function_PC get_PC () const
return the current PC
Function_PC get_error_PC () const
return the PC that has caused an error
void set_action (R_action ra)
set the prefix parser action
void set_action (const Token &result)
set the prefix parser action according to (result-) Token type
bool is_value_bracket () const
read and resolve the token class left of [ ... ], PC is at ]
bool is_value_parenthesis (int pc) const
read and resolve the token class left of)
Token_loc & tos ()
return the leftmost (top-of-stack) Token_loc (at put position)
Token_loc & at (int idx)
return the idx'th Token_loc (from put position)
const Token_loc & at (int idx) const
return the idx'th Token_loc (from put position)
Protected Member Functions
bool MM_is_FM (Function_PC PC)
return true if the left (back-)slash in M M means F M.
Protected Attributes
const uint64_t instance
a unique identifier
StateIndicator & si
the StateIndicator that contains this parser
int put
put pointer (for the next token at PC)
Token_loc content [MAX_CONTENT]
the lookahead tokens (tokens that were read but not yet reduced)
Token_loc saved_lookahead
the X token (leftmost token in MISC phrase, if any)
const Token_string & body
the function body. This parser parses tokens body[pc_from] ...
Function_PC PC
the current pc (+1)
Assign_state assign_state
assignment state
Function_PC lookahead_high
the highest PC seen in the current statement
int prefix_len
length of matched prefix (before calling a reduce_XXX() function)
R_action action
the action to be taken after returning from a reduce_XXX() function
const Phrase * best
the phrase being reduced (only valid if a phrase was matched)
Static Protected Attributes
static uint64_t instance_counter = 0
a generator for unique identifiers
Friends
class XML_Loading_Archive
class XML_Saving_Archive
Detailed Description
a class for reducing all statements of an Executable
Definition at line 57 of file Prefix.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
max. number of lookahead token
Definition at line 70 of file Prefix.hh.
Constructor & Destructor Documentation
Prefix()
Prefix::Prefix (StateIndicator & _si, const Token_string & _body)
constructor
Definition at line 38 of file Prefix.cc.
Member Function Documentation
_at0()
const Token & Prefix::_at0 () const inline
return the leftmost token (e.g. A in A←B)
Definition at line 137 of file Prefix.hh.
References content, put, size(), and Token_loc::tok.
at() [1/2]
Token_loc & Prefix::at (int idx) inline
return the idx'th Token_loc (from put position)
Definition at line 288 of file Prefix.hh.
References content, and put.
Referenced by clean_up(), get_range_high(), get_range_low(), has_quad_LRX(), print(), print_stack(), reduce_statements(), replace_AB(), XML_Saving_Archive::save_Parser(), show_owners(), syntax_error(), unmark_all_values(), and uses_function().
at() [2/2]
const Token_loc & Prefix::at (int idx) const inline
return the idx'th Token_loc (from put position)
Definition at line 292 of file Prefix.hh.
References content, and put.
at0() [1/2]
Token & Prefix::at0 () inline
return the leftmost token (e.g. A in A←B)
Definition at line 145 of file Prefix.hh.
References content, put, size(), and Token_loc::tok.
at0() [2/2]
const Token & Prefix::at0 () const inline
return the leftmost token (e.g. A in A←B)
Definition at line 141 of file Prefix.hh.
References content, put, size(), and Token_loc::tok.
Referenced by dont_reduce(), Command::finish_context(), get_monadic_fun(), locate_L(), locate_R(), and reduce_statements().
at1() [1/2]
Token & Prefix::at1 () inline
return the second token from the left (e.g. ← in A←B)
Definition at line 153 of file Prefix.hh.
References content, put, size(), and Token_loc::tok.
at1() [2/2]
const Token & Prefix::at1 () const inline
return the second token from the left (e.g. ← in A←B)
Definition at line 149 of file Prefix.hh.
References content, put, size(), and Token_loc::tok.
Referenced by get_dyadic_fun(), has_quad_LRX(), locate_L(), locate_R(), and reduce_statements().
at2()
Token & Prefix::at2 () inline
return the third token from the left (e.g. B in A←B)
Definition at line 157 of file Prefix.hh.
References content, put, size(), and Token_loc::tok.
Referenced by reduce_statements().
at3()
Token & Prefix::at3 () inline
return the fourth token from the left (e.g. B in A+/B)
Definition at line 161 of file Prefix.hh.
References content, put, size(), and Token_loc::tok.
Referenced by reduce_statements().
clean_up()
void Prefix::clean_up ()
destructor
Definition at line 52 of file Prefix.cc.
References at(), Token::extract_apl_val(), Token::get_Class(), Token::get_index_val(), Token::get_ValueType(), put, size(), Token_loc::tok, and IndexExpr::~IndexExpr().
Referenced by reset(), and StateIndicator::~StateIndicator().
dont_reduce()
bool Prefix::dont_reduce (TokenClass next) const
return true if the next token binds stronger than the best match
Definition at line 796 of file Prefix.cc.
References at0(), best, is_value_parenthesis(), PC, and Phrase::prio.
Referenced by reduce_statements().
get_assign_state()
Assign_state Prefix::get_assign_state () const inline
return the current assignment state
Definition at line 168 of file Prefix.hh.
References assign_state.
Referenced by is_value_bracket(), reduce_statements(), XML_Saving_Archive::save_Parser(), and syntax_error().
get_dyadic_fun()
const Function * Prefix::get_dyadic_fun () const inline
return the current monadic function (if any)
Definition at line 121 of file Prefix.hh.
References at1(), Token::get_function(), and Token::get_ValueType().
Referenced by Bif_F12_RHO::eval_AB().
get_error_PC()
Function_PC Prefix::get_error_PC () const inline
return the PC that has caused an error
Definition at line 234 of file Prefix.hh.
References content, Token_loc::pc, and put.
Referenced by Doxy::SI_table().
get_lookahead_high()
Function_PC Prefix::get_lookahead_high () const inline
return the highest PC seen in the current statement
Definition at line 176 of file Prefix.hh.
References lookahead_high.
Referenced by XML_Saving_Archive::save_Parser().
get_monadic_fun()
const Function * Prefix::get_monadic_fun () const inline
return the current dyadic function (if any)
Definition at line 125 of file Prefix.hh.
References at0(), Token::get_function(), and Token::get_ValueType().
Referenced by Bif_F12_COMMA::eval_B(), and Bif_F12_COMMA1::eval_B().
get_PC()
Function_PC Prefix::get_PC () const inline
return the current PC
Definition at line 230 of file Prefix.hh.
References PC.
Referenced by StateIndicator::get_PC().
get_range_high()
Function_PC Prefix::get_range_high () const
highest PC in current statement
Definition at line 311 of file Prefix.cc.
References at(), best, lookahead_high, Phrase::misc, PC, Token_loc::pc, and size().
Referenced by Error::update_error_info().
get_range_low()
Function_PC Prefix::get_range_low () const
lowest PC in current statement
Definition at line 332 of file Prefix.cc.
References at(), lookahead_high, PC, Token_loc::pc, and size().
Referenced by Error::update_error_info().
has_quad_LRX()
bool Prefix::has_quad_LRX () const
return true if the state of this Prefix has ⎕R (and maybe ⎕L or ⎕X).
... ⎕R
Definition at line 135 of file Prefix.cc.
References at(), at1(), and size().
is_value_bracket()
bool Prefix::is_value_bracket () const
read and resolve the token class left of [ ... ], PC is at ]
Definition at line 236 of file Prefix.cc.
References body, get_assign_state(), Token::get_Class(), Token::get_sym_ptr(), PC, and Symbol::resolve_class().
Referenced by reduce_statements().
is_value_parenthesis()
bool Prefix::is_value_parenthesis (int pc) const
read and resolve the token class left of)
Definition at line 160 of file Prefix.cc.
References body, Symbol::get_function(), NamedObject::get_NC(), Function::get_oper_valence(), Function::is_operator(), and is_value_parenthesis().
Referenced by dont_reduce(), and is_value_parenthesis().
locate_L()
Value_P * Prefix::locate_L (UCS_string & function)
return the left argument of a failed primitive function (if any)
Definition at line 860 of file Prefix.cc.
References at0(), at1(), Token::get_apl_valp(), Token::get_function(), and size().
Referenced by StateIndicator::get_L(), and StateIndicator::set_L().
locate_R()
Value_P * Prefix::locate_R (UCS_string & function)
return the right argument of a failed primitive function (if any)
Definition at line 926 of file Prefix.cc.
References at0(), at1(), content, Token::get_apl_valp(), Token::get_Class(), prefix_len, size(), and Token_loc::tok.
Referenced by StateIndicator::get_R(), and StateIndicator::set_R().
locate_X()
Value_P * Prefix::locate_X (UCS_string & function)
return the axis argument of a failed primitive function (if any)
Definition at line 895 of file Prefix.cc.
References content, Token::get_apl_valp(), size(), and Token_loc::tok.
Referenced by StateIndicator::get_X(), and StateIndicator::set_X().
lookahead()
Token_loc Prefix::lookahead () inline
read one more token (don't store yet)
Definition at line 180 of file Prefix.hh.
References body, and PC.
Referenced by reduce_statements().
MM_is_FM()
bool Prefix::MM_is_FM (Function_PC PC) protected
return true if the left (back-)slash in M M means F M.
Definition at line 1306 of file Prefix.cc.
References body, Token::get_Class(), Token::get_function(), NamedObject::get_NC(), Token::get_sym_ptr(), and syntax_error().
pop()
Token_loc & Prefix::pop () inline
remove the leftmost token (e,g, A in A←B) from the stack and return it
Definition at line 205 of file Prefix.hh.
References content, put, and size().
Referenced by reduce_statements().
pop_and_discard()
void Prefix::pop_and_discard () inline
discard the leftmost token (e,g, A in A←B) from the stack
Definition at line 209 of file Prefix.hh.
References put, and size().
pop_args_push_result()
void Prefix::pop_args_push_result (const Token & result) inline
pop prefix_len items and push result
Definition at line 196 of file Prefix.hh.
References content, Token::copy_1(), Token_loc::pc, prefix_len, put, size(), and Token_loc::tok.
print()
void Prefix::print (ostream & out, int indent) const
print the state of this parser
Definition at line 950 of file Prefix.cc.
References at(), size(), and Token_loc::tok.
print_stack()
void Prefix::print_stack (ostream & out, const char * loc) const
print the current stack
Definition at line 272 of file Prefix.cc.
References at(), Token::class_name(), Token::get_Class(), StateIndicator::get_level(), PC, si, size(), and Token_loc::tok.
Referenced by reduce_statements().
push()
void Prefix::push (const Token_loc & tl) inline
store one more token
Definition at line 189 of file Prefix.hh.
References content, Token_loc::copy(), put, and size().
Referenced by reduce_statements().
reduce_statements()
Token Prefix::reduce_statements ()
execute one context (user defined function or operator, execute, or immediate execution)
Definition at line 431 of file Prefix.cc.
References action, at(), at0(), at1(), at2(), at3(), best, body, Token::class_name(), Token::clear(), Token_loc::copy(), dont_reduce(), get_assign_state(), Token::get_Class(), StateIndicator::get_level(), Symbol::get_name(), NamedObject::get_NC(), StateIndicator::get_prefix(), Token::get_sym_ptr(), Token::get_tag(), Symbol::get_value(), instance, is_value_bracket(), lookahead(), lookahead_high, Phrase::misc, Token::move_1(), PC, Token_loc::pc, Phrase::phrase_hash, Phrase::phrase_len, Phrase::phrase_name, pop(), prefix_len, print_stack(), Phrase::prio, push(), Phrase::reduce_fun, Phrase::reduce_name, Symbol::resolve(), Symbol::resolve_class(), saved_lookahead, set_assign_state(), si, Workspace::SI_top(), size(), syntax_error(), and Token_loc::tok.
Referenced by StateIndicator::run().
replace_AB()
bool Prefix::replace_AB (Value_P old_value, Value_P new_value)
replace the left or right argument of a function (for retry) and return true on success
Definition at line 841 of file Prefix.cc.
References at(), Value_P_Base::get(), Token::get_apl_val(), Token::get_Class(), Token::get_tag(), size(), and Token_loc::tok.
reset()
void Prefix::reset (const char * loc) inline
reset statement to empty state (e.g. after →N)
Definition at line 217 of file Prefix.hh.
References assign_state, clean_up(), Token::clear(), lookahead_high, put, saved_lookahead, and Token_loc::tok.
Referenced by StateIndicator::goon(), and set_PC().
set_action() [1/2]
void Prefix::set_action (const Token & result) inline
set the prefix parser action according to (result-) Token type
Definition at line 244 of file Prefix.hh.
References action, Token::get_Class(), and Token::get_tag().
set_action() [2/2]
void Prefix::set_action (R_action ra) inline
set the prefix parser action
Definition at line 238 of file Prefix.hh.
References action.
set_assign_state()
void Prefix::set_assign_state (Assign_state new_state) inline
set the current assignment state
Definition at line 172 of file Prefix.hh.
References assign_state.
Referenced by reduce_statements().
set_PC()
void Prefix::set_PC (Function_PC new_pc) inline
set a new PC
Definition at line 226 of file Prefix.hh.
References PC, and reset().
Referenced by StateIndicator::set_PC().
show_owners()
int Prefix::show_owners (const char * prfx, ostream & out, const Value & value) const
print all owners of value
Definition at line 289 of file Prefix.cc.
References at(), Value_P_Base::get(), Token::get_apl_val(), Token::get_ValueType(), Value::is_or_contains(), size(), and Token_loc::tok.
Referenced by StateIndicator::show_owners().
size()
int Prefix::size () const inline
return the number of token currently in the FIFO
Definition at line 133 of file Prefix.hh.
References put.
Referenced by _at0(), at0(), at1(), at2(), at3(), clean_up(), get_range_high(), get_range_low(), has_quad_LRX(), locate_L(), locate_R(), locate_X(), pop(), pop_and_discard(), pop_args_push_result(), print(), print_stack(), push(), reduce_statements(), replace_AB(), XML_Saving_Archive::save_Parser(), show_owners(), syntax_error(), unmark_all_values(), and uses_function().
syntax_error()
void Prefix::syntax_error (const char * loc)
throw an E_LEFT_SYNTAX_ERROR or an E_SYNTAX_ERROR
Definition at line 71 of file Prefix.cc.
References at(), body, Token::get_apl_val(), get_assign_state(), Token::get_Class(), Token::get_function(), PC, size(), and Token_loc::tok.
Referenced by MM_is_FM(), and reduce_statements().
tos()
Token_loc & Prefix::tos () inline
return the leftmost (top-of-stack) Token_loc (at put position)
Definition at line 284 of file Prefix.hh.
References content, and put.
Referenced by Command::finish_context().
unmark_all_values()
void Prefix::unmark_all_values () const
clear the mark flag of all values in this Prefix
Definition at line 411 of file Prefix.cc.
References at(), Token::get_apl_val(), Token::get_ValueType(), size(), and Token_loc::tok.
Referenced by StateIndicator::unmark_all_values().
uses_function()
bool Prefix::uses_function (const UserFunction * ufun) const
return true if ufun is on the stack
Definition at line 119 of file Prefix.cc.
References at(), Token::get_function(), Token::get_ValueType(), saved_lookahead, size(), and Token_loc::tok.
value_expected()
bool Prefix::value_expected ()
lookahead is a complete index. return true if it belongs to a value and is not a function axis.
Definition at line 347 of file Prefix.cc.
References body, Token::get_Class(), Token::get_int_val2(), NamedObject::get_NC(), Token::get_sym_ptr(), Token::get_ValueType(), PC, Token_loc::pc, saved_lookahead, and Token_loc::tok.
vector_ass_count()
int Prefix::vector_ass_count () const
the number of TOK_LSYMB2 tokens ahead (excluding the leftmost one already read into content)
Definition at line 252 of file Prefix.cc.
References body, and PC.
Friends And Related Function Documentation
XML_Loading_Archive
friend class XML_Loading_Archive friend
Definition at line 59 of file Prefix.hh.
XML_Saving_Archive
friend class XML_Saving_Archive friend
Definition at line 60 of file Prefix.hh.
Member Data Documentation
action
R_action Prefix::action protected
the action to be taken after returning from a reduce_XXX() function
Definition at line 332 of file Prefix.hh.
Referenced by reduce_statements(), XML_Saving_Archive::save_Parser(), and set_action().
assign_state
Assign_state Prefix::assign_state protected
assignment state
Definition at line 323 of file Prefix.hh.
Referenced by get_assign_state(), reset(), and set_assign_state().
best
const Phrase* Prefix::best protected
the phrase being reduced (only valid if a phrase was matched)
Definition at line 335 of file Prefix.hh.
Referenced by dont_reduce(), get_range_high(), and reduce_statements().
body
const Token_string& Prefix::body protected
the function body. This parser parses tokens body[pc_from] ...
Definition at line 317 of file Prefix.hh.
Referenced by is_value_bracket(), is_value_parenthesis(), lookahead(), MM_is_FM(), reduce_statements(), syntax_error(), value_expected(), and vector_ass_count().
content
Token_loc Prefix::content[MAX_CONTENT] protected
the lookahead tokens (tokens that were read but not yet reduced)
Definition at line 311 of file Prefix.hh.
Referenced by _at0(), at(), at0(), at1(), at2(), at3(), get_error_PC(), locate_R(), locate_X(), pop(), pop_args_push_result(), push(), and tos().
instance
const uint64_t Prefix::instance protected
a unique identifier
Definition at line 300 of file Prefix.hh.
Referenced by reduce_statements().
instance_counter
uint64_t Prefix::instance_counter = 0 static protected
a generator for unique identifiers
Definition at line 338 of file Prefix.hh.
lookahead_high
Function_PC Prefix::lookahead_high protected
the highest PC seen in the current statement
Definition at line 326 of file Prefix.hh.
Referenced by get_lookahead_high(), get_range_high(), get_range_low(), reduce_statements(), and reset().
PC
Function_PC Prefix::PC protected
the current pc (+1)
Definition at line 320 of file Prefix.hh.
Referenced by dont_reduce(), get_PC(), get_range_high(), get_range_low(), is_value_bracket(), lookahead(), print_stack(), reduce_statements(), set_PC(), syntax_error(), value_expected(), and vector_ass_count().
prefix_len
int Prefix::prefix_len protected
length of matched prefix (before calling a reduce_XXX() function)
Definition at line 329 of file Prefix.hh.
Referenced by locate_R(), pop_args_push_result(), and reduce_statements().
put
int Prefix::put protected
put pointer (for the next token at PC)
Definition at line 308 of file Prefix.hh.
Referenced by _at0(), at(), at0(), at1(), at2(), at3(), clean_up(), get_error_PC(), pop(), pop_and_discard(), pop_args_push_result(), push(), reset(), size(), and tos().
saved_lookahead
Token_loc Prefix::saved_lookahead protected
the X token (leftmost token in MISC phrase, if any)
Definition at line 314 of file Prefix.hh.
Referenced by reduce_statements(), reset(), XML_Saving_Archive::save_Parser(), uses_function(), and value_expected().
si
StateIndicator& Prefix::si protected
the StateIndicator that contains this parser
Definition at line 303 of file Prefix.hh.
Referenced by print_stack(), and reduce_statements().
The documentation for this class was generated from the following files:
src/Prefix.hh
src/Prefix.cc