GNU APL: DynamicObject Class Reference
DynamicObject Class Reference
A Value or an IndexExpr.
#include <DynamicObject.hh>
Public Member Functions
DynamicObject (const char *loc, DynamicObject *anchor)
constructor: a DynamicObject allocated at source location loc
DynamicObject (const char *loc)
a special constructor for the statically allocated anchors
DynamicObject * get_next ()
return the next DynamicObject in its list
const DynamicObject * get_next () const
return the next DynamicObject in its list
DynamicObject * get_prev ()
return the previous DynamicObject in its list
const DynamicObject * get_prev () const
return the previous DynamicObject in its list
void unlink ()
unlink this DynamicObject from its list
const IndexExpr * pIndexExpr () const
cast to IndexExpr *. Caller must check that this cast is valid.
IndexExpr * pIndexExpr ()
cast to IndexExpr *. Caller must check that this cast is valid.
void print (ostream &out) const
print this object
void print_new (ostream &out, const char *loc) const
print new object message
void print_chain (ostream &out) const
print the list of objects starting at this object
const char * where_allocated () const
where this value was allocated.
Static Public Member Functions
static const DynamicObject * get_all_values ()
return a pointer to all allocated Values
Protected Member Functions
const Value & rValue () const
downcast to const Value &. Caller must check that this cast is valid.
Value & rValue ()
down cast to Value &. Caller must check that this cast is valid.
Protected Attributes
const char * alloc_loc
where this value was allocated or deleted.
DynamicObject * next
the next DynamicObject (of all objects) in this's list
DynamicObject * prev
the previous DynamicObject (of all objects) in this's list
Static Protected Attributes
static DynamicObject all_values
the anchor for all dynamic Value instances
static DynamicObject all_index_exprs
the anchor for all dynamic IndexExpr instances
Friends
class Value
Detailed Description
A Value or an IndexExpr.
Definition at line 41 of file DynamicObject.hh.
Constructor & Destructor Documentation
DynamicObject() [1/2]
DynamicObject::DynamicObject (const char * loc, DynamicObject * anchor) inline
constructor: a DynamicObject allocated at source location loc
Definition at line 47 of file DynamicObject.hh.
References next, prev, and print_new().
DynamicObject() [2/2]
DynamicObject::DynamicObject (const char * loc) inline
a special constructor for the statically allocated anchors
Definition at line 60 of file DynamicObject.hh.
Member Function Documentation
get_all_values()
static const DynamicObject * DynamicObject::get_all_values () inline static
return a pointer to all allocated Values
Definition at line 112 of file DynamicObject.hh.
References all_values.
Referenced by Command::cmd_CHECK(), and XML_Saving_Archive::save().
get_next() [1/2]
DynamicObject * DynamicObject::get_next () inline
return the next DynamicObject in its list
Definition at line 67 of file DynamicObject.hh.
References next.
Referenced by Value::erase_all(), IndexExpr::erase_stale(), Value::erase_stale(), and IndexExpr::print_stale().
get_next() [2/2]
const DynamicObject * DynamicObject::get_next () const inline
return the next DynamicObject in its list
Definition at line 70 of file DynamicObject.hh.
References next.
get_prev() [1/2]
DynamicObject * DynamicObject::get_prev () inline
return the previous DynamicObject in its list
Definition at line 73 of file DynamicObject.hh.
References prev.
Referenced by Value::check_all_Cells(), Value::list_all(), Value::mark_all_dynamic_values(), Value::print_incomplete(), and Value::print_stale().
get_prev() [2/2]
const DynamicObject * DynamicObject::get_prev () const inline
return the previous DynamicObject in its list
Definition at line 76 of file DynamicObject.hh.
References prev.
pIndexExpr() [1/2]
IndexExpr * DynamicObject::pIndexExpr ()
cast to IndexExpr *. Caller must check that this cast is valid.
cast DynamicObject to derived class Value.
Definition at line 104 of file DynamicObject.cc.
pIndexExpr() [2/2]
const IndexExpr * DynamicObject::pIndexExpr () const
cast to IndexExpr *. Caller must check that this cast is valid.
cast DynamicObject to derived class IndexExpr.
Definition at line 96 of file DynamicObject.cc.
Referenced by IndexExpr::erase_stale(), and IndexExpr::print_stale().
print()
void DynamicObject::print (ostream & out) const
print this object
Definition at line 60 of file DynamicObject.cc.
References next, prev, and where_allocated().
Referenced by Value::print_properties().
print_chain()
void DynamicObject::print_chain (ostream & out) const
print the list of objects starting at this object
Definition at line 37 of file DynamicObject.cc.
Referenced by Value::erase_stale().
print_new()
void DynamicObject::print_new (ostream & out, const char * loc) const
print new object message
Definition at line 54 of file DynamicObject.cc.
Referenced by DynamicObject().
rValue() [1/2]
Value & DynamicObject::rValue () protected
down cast to Value &. Caller must check that this cast is valid.
cast DynamicObject to derived class Value. This only works properly after including Value.hh !
Definition at line 72 of file DynamicObject.cc.
rValue() [2/2]
const Value & DynamicObject::rValue () const protected
downcast to const Value &. Caller must check that this cast is valid.
cast DynamicObject to derived class Value. This only works properly after including Value.hh !
Definition at line 84 of file DynamicObject.cc.
Referenced by Value::erase_stale(), and Value::print_stale_info().
unlink()
void DynamicObject::unlink () inline
unlink this DynamicObject from its list
Definition at line 79 of file DynamicObject.hh.
References next, and prev.
Referenced by IndexExpr::erase_stale(), and Value::~Value().
where_allocated()
const char * DynamicObject::where_allocated () const inline
where this value was allocated.
Definition at line 108 of file DynamicObject.hh.
References alloc_loc.
Referenced by Value::erase_stale(), print(), IndexExpr::print_stale(), Value::print_stale_info(), and Value::print_structure().
Friends And Related Function Documentation
Value
friend class Value friend
Definition at line 43 of file DynamicObject.hh.
Member Data Documentation
all_index_exprs
DynamicObject DynamicObject::all_index_exprs static protected
the anchor for all dynamic IndexExpr instances
Definition at line 135 of file DynamicObject.hh.
Referenced by IndexExpr::erase_stale(), and IndexExpr::print_stale().
all_values
DynamicObject DynamicObject::all_values static protected
the anchor for all dynamic Value instances
Some objects must be constructed before others, because the latter rely on the former. This file contains all static objects with such requirements on the order of construction.
See also 3.6.2 of "ISO standard Programming Languages — C++"
Definition at line 132 of file DynamicObject.hh.
Referenced by Value::check_all_Cells(), Value::erase_all(), Value::erase_stale(), get_all_values(), Value::list_all(), Value::mark_all_dynamic_values(), Value::print_incomplete(), and Value::print_stale().
alloc_loc
const char* DynamicObject::alloc_loc protected
where this value was allocated or deleted.
Definition at line 123 of file DynamicObject.hh.
Referenced by IndexExpr::erase_stale(), Value::init_ravel(), Value::rollback(), and where_allocated().
next
DynamicObject* DynamicObject::next protected
the next DynamicObject (of all objects) in this's list
Definition at line 126 of file DynamicObject.hh.
Referenced by DynamicObject(), get_next(), Value::operator delete(), print(), and unlink().
prev
DynamicObject* DynamicObject::prev protected
the previous DynamicObject (of all objects) in this's list
Definition at line 129 of file DynamicObject.hh.
Referenced by DynamicObject(), get_prev(), print(), and unlink().
The documentation for this class was generated from the following files:
src/DynamicObject.hh
src/DynamicObject.cc
src/static_Objects.cc
src/StaticObjects.cc