GNU APL: XML_node Class Reference
XML_node Class Reference
a helper class (doubly linked list) for parsing XML
#include <Quad_XML.hh>
Public Types
enum Node_type {
NT_error = -1 ,
NT_text = 1 ,
NT_leaf_tag = 2 ,
NT_start_tag = 3 ,
NT_end_tag = 4 ,
NT_comment = 5 ,
NT_declaration = 6 ,
NT_doctype = 7
}
the type of an XML_node
Public Member Functions
XML_node (XML_node *anchor, const UCS_string &src, ShapeItem spos, ShapeItem slen)
constructor
~XML_node ()
destructor
const XML_node * get_next () const
return the next XML node in the document
XML_node * get_next ()
return the next XML node in the document
const XML_node * get_prev () const
return the previous XML node in the document
XML_node * get_prev ()
return the previous XML node in the document
Node_type get_node_type () const
return the type of this node
UCS_string get_item () const
return the (source-) string for this node
size_t get_src_pos () const
return the start position of this node in src
size_t get_src_len () const
return the number of characters in this node
UCS_string get_tagname () const
return the tagname of this node. Starts with a valid XML name, thus no leading <, /m or _.
bool is_parsed () const
return true iff this XML_node was parsed (and has produced an APL value)
XML_node * unlink ()
unlink this node from the doubly-linked list that contains it
void append (XML_node *garbage)
append garbage to this garbage can (for later deletion)
void print (ostream &out) const
(debug-) print this node
bool parse_tag ()
parse an XML start or leaf tag, store result in this->APL_value On error set MORE_ERROR() and return true
const char * get_node_type_name () const
return the type of this node as string
Static Public Member Functions
static void print_all (ostream &out, const XML_node &anchor)
(debug-) print all nodes·
static bool translate (XML_node &anchor, XML_node &garbage)
reduce nodes starting at start, return true on error
static bool collect (XML_node &anchor, XML_node &garbage, Value *Z)
collect nodes starting at anchor, return true on error
static void add_member (Value *Z, Unicode first, const char *name, int number, Value *value)
add member name with value value to structured value Z
static bool merge_range (XML_node &start, XML_node &end, XML_node &garbage_can)
merge the items from start(-tag) to (end(-tag) into start tag
static bool is_name_char (Unicode uni)
return true if uni is a validchar
static bool is_XML_char (Unicode uni)
return true if uni is a valid char in an XML tag name
static bool is_first_name_char (Unicode uni)
return true if uni is a valid first char in an XML tag name
static ShapeItem get_taglen (const UCS_string &string_B, ShapeItem offset)
return the length of the tag at string_B + offset...
static bool normalize_attribute_value (UCS_string &attval)
perform an in-place attribute value normalization (XML standard 3.3.3). On error set MORE_ERROR() and return true
static UCS_string denormalize_attribute_value (const UCS_string &UCS_string, bool quoted)
return the inverse of normalize_attribute_value()
Protected Member Functions
bool matches (const XML_node *end_tag) const
return true iff end_tag matches this start tag
Protected Attributes
const UCS_string & src
the source string of the entire xml document
const ShapeItem src_pos
the start of this node in src
ShapeItem src_len
the length of this node in src
XML_node * next
the next XML node in the document
XML_node * prev
the previous XML node in the document
Node_type node_type
the type of this node
Value_P APL_value
the APL value for this node
const char * err_loc
the error location (if any) when constructing this node
int level
the level of this node in the document (top-level = 0)
int position
the position of this node (at its level)
Detailed Description
a helper class (doubly linked list) for parsing XML
Definition at line 28 of file Quad_XML.hh.
Member Enumeration Documentation
Node_type
enum XML_node::Node_type
the type of an XML_node
Definition at line 39 of file Quad_XML.hh.
Constructor & Destructor Documentation
XML_node()
XML_node::XML_node (XML_node * anchor, const UCS_string & src, ShapeItem spos, ShapeItem slen)
constructor
Definition at line 38 of file Quad_XML.cc.
References err_loc, is_first_name_char(), next, node_type, prev, src, src_len, and src_pos.
~XML_node()
XML_node::~XML_node ()
destructor
Definition at line 195 of file Quad_XML.cc.
Member Function Documentation
add_member()
void XML_node::add_member (Value * Z, Unicode first, const char * name, int number, Value * value) static
add member name with value value to structured value Z
Definition at line 733 of file Quad_XML.cc.
References Value::add_member(), UCS_string::append_number(), and UCS_string::append_UTF8().
Referenced by collect(), merge_range(), and parse_tag().
append()
void XML_node::append (XML_node * garbage) inline
append garbage to this garbage can (for later deletion)
Definition at line 104 of file Quad_XML.hh.
References next, and prev.
Referenced by collect(), merge_range(), and translate().
collect()
bool XML_node::collect (XML_node & anchor, XML_node & garbage, Value * Z) static
collect nodes starting at anchor, return true on error
Definition at line 598 of file Quad_XML.cc.
References add_member(), APL_value, append(), UTF8_string::c_str(), Value_P_Base::get(), Workspace::get_IO(), get_item(), get_next(), get_tagname(), matches(), merge_range(), and position.
Referenced by Quad_XML::XML_to_APL().
denormalize_attribute_value()
UCS_string XML_node::denormalize_attribute_value (const UCS_string & UCS_string, bool quoted) static
return the inverse of normalize_attribute_value()
Definition at line 996 of file Quad_XML.cc.
References UCS_string::append_UTF8(), and UCS_string::size().
Referenced by Quad_XML::add_sorted_entities().
get_item()
UCS_string XML_node::get_item () const inline
return the (source-) string for this node
Definition at line 72 of file Quad_XML.hh.
References src, src_len, and src_pos.
Referenced by collect(), and get_tagname().
get_next() [1/2]
XML_node * XML_node::get_next () inline
return the next XML node in the document
Definition at line 56 of file Quad_XML.hh.
References next.
get_next() [2/2]
const XML_node * XML_node::get_next () const inline
return the next XML node in the document
Definition at line 52 of file Quad_XML.hh.
References next.
Referenced by collect(), merge_range(), print_all(), translate(), and Quad_XML::XML_to_APL().
get_node_type()
Node_type XML_node::get_node_type () const inline
return the type of this node
Definition at line 68 of file Quad_XML.hh.
References node_type.
Referenced by merge_range().
get_node_type_name()
const char * XML_node::get_node_type_name () const
return the type of this node as string
Definition at line 218 of file Quad_XML.cc.
References node_type.
Referenced by get_tagname(), and print().
get_prev() [1/2]
XML_node * XML_node::get_prev () inline
return the previous XML node in the document
Definition at line 64 of file Quad_XML.hh.
References prev.
get_prev() [2/2]
const XML_node * XML_node::get_prev () const inline
return the previous XML node in the document
Definition at line 60 of file Quad_XML.hh.
References prev.
get_src_len()
size_t XML_node::get_src_len () const inline
return the number of characters in this node
Definition at line 80 of file Quad_XML.hh.
References src_len.
get_src_pos()
size_t XML_node::get_src_pos () const inline
return the start position of this node in src
Definition at line 76 of file Quad_XML.hh.
References src_pos.
get_taglen()
ShapeItem XML_node::get_taglen (const UCS_string & string_B, ShapeItem offset) static
return the length of the tag at string_B + offset...
Definition at line 487 of file Quad_XML.cc.
References level, and UCS_string::size().
Referenced by Quad_XML::XML_to_APL().
get_tagname()
UCS_string XML_node::get_tagname () const
return the tagname of this node. Starts with a valid XML name, thus no leading <, /m or _.
Definition at line 1050 of file Quad_XML.cc.
References UCS_string::append(), UCS_string::append_number(), get_item(), get_node_type_name(), is_first_name_char(), is_name_char(), node_type, position, src, and src_pos.
Referenced by collect(), and merge_range().
is_first_name_char()
bool XML_node::is_first_name_char (Unicode uni) static
return true if uni is a valid first char in an XML tag name
Definition at line 1136 of file Quad_XML.cc.
Referenced by get_tagname(), is_name_char(), parse_tag(), and XML_node().
is_name_char()
bool XML_node::is_name_char (Unicode uni) static
return true if uni is a validchar
Definition at line 1107 of file Quad_XML.cc.
References is_first_name_char().
Referenced by get_tagname(), matches(), and parse_tag().
is_parsed()
bool XML_node::is_parsed () const inline
return true iff this XML_node was parsed (and has produced an APL value)
Definition at line 88 of file Quad_XML.hh.
References APL_value.
is_XML_char()
bool XML_node::is_XML_char (Unicode uni) static
return true if uni is a valid char in an XML tag name
Definition at line 1086 of file Quad_XML.cc.
Referenced by Quad_XML::XML_to_APL().
matches()
bool XML_node::matches (const XML_node * end_tag) const protected
return true iff end_tag matches this start tag
Definition at line 1035 of file Quad_XML.cc.
References is_name_char(), node_type, src, and src_pos.
Referenced by collect().
merge_range()
bool XML_node::merge_range (XML_node & start, XML_node & end, XML_node & garbage_can) static
merge the items from start(-tag) to (end(-tag) into start tag
Definition at line 744 of file Quad_XML.cc.
References add_member(), APL_value, UCS_string::append(), append(), Value_P_Base::get(), Workspace::get_IO(), get_next(), get_node_type(), get_tagname(), position, and unlink().
Referenced by collect().
normalize_attribute_value()
bool XML_node::normalize_attribute_value (UCS_string & attval) static
perform an in-place attribute value normalization (XML standard 3.3.3). On error set MORE_ERROR() and return true
Definition at line 883 of file Quad_XML.cc.
References Avec::digit_value(), UCS_string::size(), and src.
Referenced by parse_tag().
parse_tag()
bool XML_node::parse_tag ()
parse an XML start or leaf tag, store result in this->APL_value On error set MORE_ERROR() and return true
Definition at line 805 of file Quad_XML.cc.
References add_member(), APL_value, UTF8_string::c_str(), Value_P_Base::get(), Workspace::get_IO(), is_first_name_char(), is_name_char(), normalize_attribute_value(), src, src_len, and src_pos.
print()
void XML_node::print (ostream & out) const
(debug-) print this node
Definition at line 200 of file Quad_XML.cc.
References err_loc, get_node_type_name(), level, src, src_len, and src_pos.
print_all()
void XML_node::print_all (ostream & out, const XML_node & anchor) static
(debug-) print all nodes·
Definition at line 209 of file Quad_XML.cc.
References get_next().
translate()
bool XML_node::translate (XML_node & anchor, XML_node & garbage) static
reduce nodes starting at start, return true on error
Definition at line 547 of file Quad_XML.cc.
References append(), get_next(), and level.
Referenced by Quad_XML::XML_to_APL().
unlink()
XML_node * XML_node::unlink () inline
unlink this node from the doubly-linked list that contains it
Definition at line 92 of file Quad_XML.hh.
References next, and prev.
Referenced by merge_range(), and Quad_XML::XML_to_APL().
Member Data Documentation
APL_value
Value_P XML_node::APL_value protected
the APL value for this node
Definition at line 185 of file Quad_XML.hh.
Referenced by collect(), is_parsed(), merge_range(), and parse_tag().
err_loc
const char* XML_node::err_loc protected
the error location (if any) when constructing this node
Definition at line 188 of file Quad_XML.hh.
Referenced by print(), and XML_node().
level
int XML_node::level protected
the level of this node in the document (top-level = 0)
Definition at line 191 of file Quad_XML.hh.
Referenced by get_taglen(), print(), and translate().
next
XML_node* XML_node::next protected
the next XML node in the document
Definition at line 176 of file Quad_XML.hh.
Referenced by append(), get_next(), unlink(), and XML_node().
node_type
Node_type XML_node::node_type protected
the type of this node
Definition at line 182 of file Quad_XML.hh.
Referenced by get_node_type(), get_node_type_name(), get_tagname(), matches(), and XML_node().
position
int XML_node::position protected
the position of this node (at its level)
Definition at line 194 of file Quad_XML.hh.
Referenced by collect(), get_tagname(), and merge_range().
prev
XML_node* XML_node::prev protected
the previous XML node in the document
Definition at line 179 of file Quad_XML.hh.
Referenced by append(), get_prev(), unlink(), and XML_node().
src
const UCS_string& XML_node::src protected
the source string of the entire xml document
Definition at line 167 of file Quad_XML.hh.
Referenced by get_item(), get_tagname(), matches(), normalize_attribute_value(), parse_tag(), print(), and XML_node().
src_len
ShapeItem XML_node::src_len protected
the length of this node in src
Definition at line 173 of file Quad_XML.hh.
Referenced by get_item(), get_src_len(), parse_tag(), print(), and XML_node().
src_pos
const ShapeItem XML_node::src_pos protected
the start of this node in src
Definition at line 170 of file Quad_XML.hh.
Referenced by get_item(), get_src_pos(), get_tagname(), matches(), parse_tag(), print(), and XML_node().
The documentation for this class was generated from the following files:
src/Quad_XML.hh
src/Quad_XML.cc