GNU APL: Quad_CR Class Reference
Quad_CR Class Reference
The class implementing ⎕CR.
#include <Quad_CR.hh>
Classes
struct _sub_fun
a mapping between function names and function numbers
class Picker
the left argument of Pick (⊃) which selects a sub-item of a variable being constructed
Public Member Functions
Quad_CR ()
Constructor.
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B()
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB()
virtual Token eval_XB (Value_P X, Value_P B) const
overloaded Function::eval_XB()
virtual bool has_subfuns () const
overloaded Function::has_subfuns()
virtual sAxis subfun_to_axis (const UCS_string &name) const
overloaded Function::subfun_to_axis()
Public Member Functions inherited from QuadFunction
QuadFunction (TokenTag tag)
Constructor.
virtual bool has_alpha () const
overloaded Function::has_alpha()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B().
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB().
virtual bool has_result () const
overloaded Function::has_result()
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
virtual bool has_result () const
overloaded Function::has_result()
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Static Public Member Functions
static Value_P do_CR (APL_Integer a, const Value *B, PrintContext pctx)
compute a ⎕CR B
static bool figure_default (const Value *value, Unicode &default_char, APL_Integer &default_int)
compute a good default type and value for the top-level ⍴ of 10 ⎕CR. Return true for INT and false for CHAR.
static UCS_string compute_prolog (int pick_level, const UCS_string &left, const Value *value)
compute the prolog (e,g, ((⎕IO+2)⊃X)←) for the pick of left
static void do_CR10_variable (UCS_string_vector &result, const UCS_string &var_name, const Value *value)
portable variable encoding of value name (varname or varname ⊂)
static Value_P do_CR35 (const Value *B)
compute 35 ⎕CR B
Static Public Attributes
static Quad_CR * fun = &Quad_CR ::_fun
Built-in function.
static Quad_CR _fun
Built-in function.
Protected Types
enum V_mode {
Vm_NONE ,
Vm_NUM ,
Vm_QUOT ,
Vm_UCS
}
the state of the current output line
Static Protected Member Functions
static int fun_compare (const void *key, const void *sf)
compare two axis strings (function names)
static Token list_functions (ostream &out, bool mapping)
list all ⎕CR functions
static Token do_eval_B (const Value *B, bool remove_extra_spaces)
do eval_B() with extra spaces removed
static Value_P do_CR5_6 (int A56, const Value *B)
compute 5 ⎕CR B or 6 ⎕CR B
static Value_P do_CR10 (const Value *B)
compute 10 ⎕CR B
static Value_P do_CR11 (const Value *B)
compute 11 ⎕CR B
static Value_P do_CR12 (const Value *B)
compute 12 ⎕CR B
static Value_P do_CR13 (const Value *B)
compute 13 ⎕CR B
static Value_P do_CR14 (const Value *B)
compute 14 ⎕CR B
static Value_P do_CR15 (const Value *B)
compute 15 ⎕CR B
static Value_P do_CR16 (const Value *B)
compute 16 ⎕CR B
static Value_P do_CR17 (const Value *B)
compute 17 ⎕CR B
static Value_P do_CR18 (const Value *B)
compute 18 ⎕CR B
static Value_P do_CR19 (const Value *B)
compute 19 ⎕CR B
static Value_P do_CR26 (const Value *B)
compute 26 ⎕CR B
static Value_P do_CR27_28 (int A_27_28, const Value *B)
compute 27 ⎕CR B or 28 ⎕CR B
static Value_P do_CR30 (const Value *B)
compute 30 ⎕CR B
static Value_P do_CR31_32 (int A_31_32, const Value *B)
compute 31 ⎕CR B or 32 ⎕CR B
static Value_P do_CR33 (const Value *B)
compute 33 ⎕CR B
static Value_P do_CR34 (const Value *B)
compute 34 ⎕CR B
static Value_P do_CR36 (const Value *B)
compute 36 ⎕CR B
static Value_P do_CR37 (const Value *B)
compute 37 ⎕CR B
static Value_P do_CR38 (const Value *B)
compute 38 ⎕CR B
static Value_P do_CR39 (const Value *B)
compute 39 ⎕CR B
static Value_P do_CR40 (const Value *B)
compute 40 ⎕CR B
static Value_P do_CR41 (const Value *B)
compute 41 ⎕CR B
static void do_CR10_value (UCS_string_vector &result, const Value *value, Picker &picker, ShapeItem pidx)
compute 10 ⎕CR recursively
static const char * do_CR10_structured (UCS_string_vector &result, const UCS_string &varname, const Value *value)
compute 10 ⎕CR recursively (structured variable)
static bool short_ravel (UCS_string_vector &result, bool &nested, const Value *value, const Picker &picker, const UCS_string &left, const UCS_string &shape_rho)
try to emit value in short format. Retrun true if that is not possible.
static void do_CR10 (UCS_string_vector &result, const Value *symbol_name)
10 ⎕CR symbol_name (variable or function name). Also used for)OUT
static V_mode do_CR10_item (UCS_string &item, const Cell &cell, V_mode mode, bool may_quote)
one ravel item in 10 ⎕CR symbol_name
static bool use_quote (V_mode mode, const Value *value, ShapeItem pos)
decide if 'xxx' or ⎕UCS(xxx) shall be used
static void close_mode (UCS_string &line, V_mode mode)
close current mode (ending ' for '' or) for ⎕UCS())
static void item_separator (UCS_string &line, V_mode from_mode, V_mode to_mode)
print item separator
Static Protected Attributes
static _sub_fun sub_functions []
a mapping between function names and function numbers
Additional Inherited Members
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
The class implementing ⎕CR.
The system function ⎕CR (Character Representation).
Definition at line 32 of file Quad_CR.hh.
Member Enumeration Documentation
V_mode
enum Quad_CR::V_mode protected
the state of the current output line
Enumerator
Vm_NONE
initial state
Vm_NUM
in numeric vector. e.g. 1 2 3
Vm_QUOT
in quoted character vector, e.g. 'abc'
Vm_UCS
in ⎕UCS(), e.g. ⎕UCS(97 98 99)
Definition at line 230 of file Quad_CR.hh.
Constructor & Destructor Documentation
Quad_CR()
Quad_CR::Quad_CR () inline
Constructor.
Definition at line 36 of file Quad_CR.hh.
Member Function Documentation
close_mode()
void Quad_CR::close_mode (UCS_string & line, V_mode mode) static protected
close current mode (ending ' for '' or) for ⎕UCS())
Definition at line 1448 of file Quad_CR.cc.
References UCS_string::append_UTF8(), Vm_QUOT, and Vm_UCS.
Referenced by do_CR10_value(), item_separator(), and short_ravel().
compute_prolog()
UCS_string Quad_CR::compute_prolog (int pick_level, const UCS_string & left, const Value * value) static
compute the prolog (e,g, ((⎕IO+2)⊃X)←) for the pick of left
Definition at line 789 of file Quad_CR.cc.
References UCS_string::append(), UCS_string::append_number(), UCS_string::append_shape(), UCS_string::append_UTF8(), and figure_default().
Referenced by do_CR10_value().
do_CR()
Value_P Quad_CR::do_CR (APL_Integer a, const Value * B, PrintContext pctx) static
compute a ⎕CR B
a local shortcut for the various frame variants of ⎕CR
Definition at line 268 of file Quad_CR.cc.
References do_CR10(), do_CR11(), do_CR12(), do_CR13(), do_CR14(), do_CR15(), do_CR16(), do_CR17(), do_CR18(), do_CR19(), do_CR26(), do_CR27_28(), do_CR30(), do_CR31_32(), do_CR33(), do_CR34(), do_CR35(), do_CR36(), do_CR37(), do_CR38(), do_CR39(), do_CR40(), do_CR41(), and do_CR5_6().
Referenced by eval_AB(), Value::print_boxed(), Value::print_stale_info(), and StateIndicator::statement_result().
do_CR10() [1/2]
Value_P Quad_CR::do_CR10 (const Value * B) static protected
compute 10 ⎕CR B
Definition at line 414 of file Quad_CR.cc.
References do_CR10(), and Value_P_Base::get().
Referenced by do_CR(), and do_CR10().
do_CR10() [2/2]
void Quad_CR::do_CR10 (UCS_string_vector & result, const Value * symbol_name) static protected
10 ⎕CR symbol_name (variable or function name). Also used for)OUT
Definition at line 435 of file Quad_CR.cc.
References UCS_string::append(), Function::canonical(), do_CR10_variable(), Value_P_Base::get(), Symbol::get_apl_value(), Function::get_exec_properties(), Symbol::get_function(), Symbol::get_name(), NamedObject::get_NC(), UCS_string::is_comment_or_label(), Function::is_lambda(), Workspace::lookup_existing_symbol(), and UCS_string::size().
do_CR10_item()
Quad_CR::V_mode Quad_CR::do_CR10_item (UCS_string & item, const Cell & cell, V_mode mode, bool may_quote) static protected
one ravel item in 10 ⎕CR symbol_name
Definition at line 896 of file Quad_CR.cc.
References UCS_string::append(), UCS_string::append_number(), UCS_string::append_UTF8(), Cell::get_char_value(), Cell::get_imag_value(), Cell::get_int_value(), Cell::get_real_value(), Cell::is_character_cell(), Cell::is_complex_cell(), Cell::is_float_cell(), Cell::is_integer_cell(), Cell::is_pointer_cell(), Vm_NUM, Vm_QUOT, and Vm_UCS.
Referenced by do_CR10_value(), and short_ravel().
do_CR10_structured()
const char * Quad_CR::do_CR10_structured (UCS_string_vector & result, const UCS_string & varname, const Value * value) static protected
compute 10 ⎕CR recursively (structured variable)
Definition at line 683 of file Quad_CR.cc.
References UCS_string::append(), do_CR10_structured(), do_CR10_value(), Value_P_Base::get(), Cell::get_pointer_value(), Value::is_char_string(), Cell::is_member_anchor(), and Cell::is_pointer_cell().
Referenced by do_CR10_structured(), and do_CR10_variable().
do_CR10_value()
void Quad_CR::do_CR10_value (UCS_string_vector & result, const Value * value, Picker & picker, ShapeItem pidx) static protected
compute 10 ⎕CR recursively
Definition at line 534 of file Quad_CR.cc.
References UCS_string::append(), UCS_string::append_shape(), UCS_string::append_UTF8(), close_mode(), compute_prolog(), do_CR10_item(), do_CR10_value(), Value_P_Base::get(), Quad_CR::Picker::get(), Quad_CR::Picker::get_indexed(), Quad_CR::Picker::get_level(), Cell::get_pointer_value(), Cell::is_pointer_cell(), item_separator(), Quad_CR::Picker::pop(), Quad_CR::Picker::push(), short_ravel(), UCS_string::size(), use_quote(), and Vm_NONE.
Referenced by do_CR10_structured(), do_CR10_value(), and do_CR10_variable().
do_CR10_variable()
void Quad_CR::do_CR10_variable (UCS_string_vector & result, const UCS_string & var_name, const Value * value) static
portable variable encoding of value name (varname or varname ⊂)
Definition at line 510 of file Quad_CR.cc.
References do_CR10_structured(), and do_CR10_value().
Referenced by do_CR10(), and Symbol::dump().
do_CR11()
Value_P Quad_CR::do_CR11 (const Value * B) static protected
compute 11 ⎕CR B
Definition at line 962 of file Quad_CR.cc.
References CDR::to_CDR().
Referenced by do_CR().
do_CR12()
Value_P Quad_CR::do_CR12 (const Value * B) static protected
compute 12 ⎕CR B
Definition at line 978 of file Quad_CR.cc.
References CDR::from_CDR().
Referenced by do_CR().
do_CR13()
Value_P Quad_CR::do_CR13 (const Value * B) static protected
compute 13 ⎕CR B
Definition at line 991 of file Quad_CR.cc.
References Shape::set_shape_item().
Referenced by do_CR().
do_CR14()
Value_P Quad_CR::do_CR14 (const Value * B) static protected
compute 14 ⎕CR B
Definition at line 1016 of file Quad_CR.cc.
References CDR::to_CDR().
Referenced by do_CR().
do_CR15()
Value_P Quad_CR::do_CR15 (const Value * B) static protected
compute 15 ⎕CR B
Definition at line 1037 of file Quad_CR.cc.
References CDR::from_CDR().
Referenced by do_CR().
do_CR16()
Value_P Quad_CR::do_CR16 (const Value * B) static protected
compute 16 ⎕CR B
Definition at line 1057 of file Quad_CR.cc.
References Cell::get_char_value().
Referenced by do_CR().
do_CR17()
Value_P Quad_CR::do_CR17 (const Value * B) static protected
compute 17 ⎕CR B
Definition at line 1135 of file Quad_CR.cc.
Referenced by do_CR().
do_CR18()
Value_P Quad_CR::do_CR18 (const Value * B) static protected
compute 18 ⎕CR B
Definition at line 1196 of file Quad_CR.cc.
Referenced by do_CR().
do_CR19()
Value_P Quad_CR::do_CR19 (const Value * B) static protected
compute 19 ⎕CR B
Definition at line 1205 of file Quad_CR.cc.
Referenced by do_CR().
do_CR26()
Value_P Quad_CR::do_CR26 (const Value * B) static protected
compute 26 ⎕CR B
Definition at line 1221 of file Quad_CR.cc.
References do_CR26(), Value_P_Base::get(), Cell::get_cell_type(), Cell::get_pointer_value(), and Cell::is_pointer_cell().
Referenced by do_CR(), and do_CR26().
do_CR27_28()
Value_P Quad_CR::do_CR27_28 (int A_27_28, const Value * B) static protected
compute 27 ⎕CR B or 28 ⎕CR B
Definition at line 1245 of file Quad_CR.cc.
References do_CR27_28(), Value_P_Base::get(), LvalCell::get_cell_owner(), Cell::get_cell_type(), Cell::get_char_value(), Cell::get_lval_value(), Cell::get_pointer_value(), Cell::get_u0(), Cell::get_u1(), and Cell::is_pointer_cell().
Referenced by do_CR(), and do_CR27_28().
do_CR30()
Value_P Quad_CR::do_CR30 (const Value * B) static protected
compute 30 ⎕CR B
Definition at line 1303 of file Quad_CR.cc.
References Shape::add_shape_item(), Bif_F12_TAKE::do_take(), Shape::expand_rank(), Cell::get_pointer_value(), Shape::get_rank(), Shape::get_shape_item(), Shape::get_volume(), Cell::is_lval_cell(), and Cell::is_pointer_cell().
Referenced by do_CR().
do_CR31_32()
Value_P Quad_CR::do_CR31_32 (int A_31_32, const Value * B) static protected
compute 31 ⎕CR B or 32 ⎕CR B
Definition at line 1368 of file Quad_CR.cc.
References PrintBuffer::add_column(), Value_P_Base::get(), Workspace::get_PrintContext(), PrintBuffer::get_row_count(), PrintContext::get_style(), PrintBuffer::l1(), PrintBuffer::pad_height(), PrintBuffer::pad_height_above(), and PrintContext::set_style().
Referenced by do_CR().
do_CR33()
Value_P Quad_CR::do_CR33 (const Value * B) static protected
compute 33 ⎕CR B
Definition at line 1473 of file Quad_CR.cc.
References Cell::get_byte_value(), and Function::tag.
Referenced by do_CR().
do_CR34()
Value_P Quad_CR::do_CR34 (const Value * B) static protected
compute 34 ⎕CR B
Definition at line 1503 of file Quad_CR.cc.
References Cell::get_byte_value(), and Function::tag.
Referenced by do_CR().
do_CR35()
Value_P Quad_CR::do_CR35 (const Value * B) static
compute 35 ⎕CR B
Definition at line 1537 of file Quad_CR.cc.
References UCS_string::append(), Value_P_Base::get(), and UCS_string::size().
Referenced by do_CR(), and Value::print_member().
do_CR36()
Value_P Quad_CR::do_CR36 (const Value * B) static protected
compute 36 ⎕CR B
Definition at line 1592 of file Quad_CR.cc.
References UCS_string::append(), Value::element_count(), and Value::get_rank().
Referenced by do_CR().
do_CR37()
static Value_P Quad_CR::do_CR37 (const Value * B) inline static protected
compute 37 ⎕CR B
Definition at line 153 of file Quad_CR.hh.
References do_eval_B(), and Token::get_apl_val().
Referenced by do_CR().
do_CR38()
Value_P Quad_CR::do_CR38 (const Value * B) static protected
compute 38 ⎕CR B
Definition at line 1620 of file Quad_CR.cc.
References Cell::get_char_value(), Cell::get_pointer_value(), Cell::init(), Cell::is_character_cell(), and Cell::is_pointer_cell().
Referenced by do_CR().
do_CR39()
Value_P Quad_CR::do_CR39 (const Value * B) static protected
compute 39 ⎕CR B
Definition at line 1699 of file Quad_CR.cc.
References do_CR39(), Value_P_Base::get(), Cell::get_pointer_value(), Cell::is_integer_cell(), and Cell::is_pointer_cell().
Referenced by do_CR(), and do_CR39().
do_CR40()
Value_P Quad_CR::do_CR40 (const Value * B) static protected
compute 40 ⎕CR B
Definition at line 1744 of file Quad_CR.cc.
References Cell::get_near_int(), and Cell::is_near_bool().
Referenced by do_CR().
do_CR41()
Value_P Quad_CR::do_CR41 (const Value * B) static protected
compute 41 ⎕CR B
Definition at line 1789 of file Quad_CR.cc.
Referenced by do_CR().
do_CR5_6()
Value_P Quad_CR::do_CR5_6 (int A56, const Value * B) static protected
compute 5 ⎕CR B or 6 ⎕CR B
Definition at line 383 of file Quad_CR.cc.
References Shape::add_shape_item(), Cell::get_byte_value(), Shape::get_rank(), and Shape::set_shape_item().
Referenced by do_CR().
do_eval_B()
Token Quad_CR::do_eval_B (const Value * B, bool remove_extra_spaces) static protected
do eval_B() with extra spaces removed
Definition at line 143 of file Quad_CR.cc.
References Shape::add_shape_item(), UCS_string::back(), NamedObject::get_function(), Macro::get_macro(), UserFunction::get_name(), NamedObject::is_user_defined(), Workspace::lookup_existing_name(), UCS_string::pop_back(), UCS_string::size(), and UCS_string::to_vector().
Referenced by do_CR37(), and eval_B().
eval_AB()
Token Quad_CR::eval_AB (Value_P A, Value_P B) const virtual
overloaded Function::eval_AB()
Reimplemented from QuadFunction.
Definition at line 237 of file Quad_CR.cc.
References UTF8_string::c_str(), do_CR(), Workspace::get_PrintContext(), and subfun_to_axis().
Referenced by eval_XB().
eval_B()
Token Quad_CR::eval_B (Value_P B) const virtual
overloaded Function::eval_B()
Reimplemented from QuadFunction.
Definition at line 129 of file Quad_CR.cc.
References do_eval_B(), and list_functions().
eval_XB()
virtual Token Quad_CR::eval_XB (Value_P X, Value_P B) const inline virtual
overloaded Function::eval_XB()
Reimplemented from Function.
Definition at line 45 of file Quad_CR.hh.
References eval_AB().
figure_default()
bool Quad_CR::figure_default (const Value * value, Unicode & default_char, APL_Integer & default_int) static
compute a good default type and value for the top-level ⍴ of 10 ⎕CR. Return true for INT and false for CHAR.
Definition at line 811 of file Quad_CR.cc.
References Cell::get_char_value(), Cell::get_int_value(), Cell::is_character_cell(), and Cell::is_integer_cell().
Referenced by compute_prolog().
fun_compare()
int Quad_CR::fun_compare (const void * key, const void * sf) static protected
compare two axis strings (function names)
Definition at line 37 of file Quad_CR.cc.
Referenced by subfun_to_axis().
has_subfuns()
virtual bool Quad_CR::has_subfuns () const inline virtual
overloaded Function::has_subfuns()
Reimplemented from Function.
Definition at line 49 of file Quad_CR.hh.
item_separator()
void Quad_CR::item_separator (UCS_string & line, V_mode from_mode, V_mode to_mode) static protected
print item separator
Definition at line 1455 of file Quad_CR.cc.
References UCS_string::append_UTF8(), close_mode(), Vm_NONE, Vm_NUM, Vm_QUOT, and Vm_UCS.
Referenced by do_CR10_value(), and short_ravel().
list_functions()
Token Quad_CR::list_functions (ostream & out, bool mapping) static protected
list all ⎕CR functions
Definition at line 44 of file Quad_CR.cc.
References Quad_CR::_sub_fun::key, sub_functions, and Quad_CR::_sub_fun::val.
Referenced by eval_B().
short_ravel()
bool Quad_CR::short_ravel (UCS_string_vector & result, bool & nested, const Value * value, const Picker & picker, const UCS_string & left, const UCS_string & shape_rho) static protected
try to emit value in short format. Retrun true if that is not possible.
Definition at line 730 of file Quad_CR.cc.
References UCS_string::append(), UCS_string::append_UTF8(), close_mode(), do_CR10_item(), Quad_CR::Picker::get_level(), Cell::is_character_cell(), Cell::is_complex_cell(), Cell::is_integer_cell(), Cell::is_pointer_cell(), item_separator(), UCS_string::size(), use_quote(), and Vm_NONE.
Referenced by do_CR10_value().
subfun_to_axis()
sAxis Quad_CR::subfun_to_axis (const UCS_string & name) const virtual
overloaded Function::subfun_to_axis()
Reimplemented from Function.
Definition at line 220 of file Quad_CR.cc.
References UTF8_string::c_str(), fun_compare(), sub_functions, and Quad_CR::_sub_fun::val.
Referenced by eval_AB().
use_quote()
bool Quad_CR::use_quote (V_mode mode, const Value * value, ShapeItem pos) static protected
decide if 'xxx' or ⎕UCS(xxx) shall be used
Definition at line 1418 of file Quad_CR.cc.
References Vm_QUOT.
Referenced by do_CR10_value(), and short_ravel().
Member Data Documentation
_fun
Quad_CR Quad_CR::_fun static
Built-in function.
Definition at line 68 of file Quad_CR.hh.
Referenced by Workspace::Workspace().
fun
Quad_CR * Quad_CR::fun = &Quad_CR ::_fun static
Built-in function.
Definition at line 67 of file Quad_CR.hh.
Referenced by Workspace::Workspace().
sub_functions
Quad_CR::_sub_fun Quad_CR::sub_functions static protected
Initial value:
=
{
#define crdef(N, name)
}
a mapping between function names and function numbers
Definition at line 87 of file Quad_CR.hh.
Referenced by list_functions(), and subfun_to_axis().
The documentation for this class was generated from the following files:
src/Quad_CR.hh
src/Quad_CR.cc
src/static_Objects.cc