GNU APL: ID Class Reference
ID Class Reference
Identifier of an internal object of the APL interpreter.
#include <Id.hh>
Static Public Member Functions
static const UTF8 * get_name (Id id)
return the printable name for id as UTF8 *
static UCS_string get_name_UCS (Id id)
return the printable name for id as UCS_string
static Function_P get_system_function (Id id)
If id is the ID of primitive function, primitive operator, or quad function, then return a pointer to it. Otherwise return 0.
static Function_P get_system_function (TokenTag tag)
If tag is the tag of primitive function, primitive operator, or quad function, then return a pointer to it. Otherwise return 0.
static Symbol * get_system_variable (Id id)
If id is the ID of a quad variable, then return a pointer to its symbol. Otherwise return 0.
static TokenTag get_token_tag (Id id)
return the TokenTag for id
static void cleanup ()
release UCS_strings with ID names
Detailed Description
Identifier of an internal object of the APL interpreter.
An Identifier for each internal object (primitives, Quad-symbols, and more). The ID can be derived in different ways:
from a (user0defined) name, e.g. ID_APL_VALUE or ID_CHARACTER
from a distinguished var name, e.g. ID_Quad_AI or ID_Quad_AV
from a distinguished fun name, e.g. ID_Quad_AT or ID_Quad_EM
from a special token (apl symbol) e.g. ID_L_PARENT1 or ID_ASSIGN
This is controlled by 5 corresponding macros: pp() qv() qf() resp. st()
Definition at line 48 of file Id.hh.
Member Function Documentation
cleanup()
void ID::cleanup () static
release UCS_strings with ID names
Definition at line 100 of file Id.cc.
get_name()
const UTF8 * ID::get_name (Id id) static
return the printable name for id as UTF8 *
Definition at line 105 of file Id.cc.
References Id_name::compare(), and Id_name::utf_name.
Referenced by get_name_UCS().
get_name_UCS()
UCS_string ID::get_name_UCS (Id id) static
return the printable name for id as UCS_string
Definition at line 93 of file Id.cc.
References get_name().
Referenced by Token::canonical(), NamedObject::get_name(), XML_Loading_Archive::read_Function_name(), XML_Loading_Archive::read_Symbol(), and XML_Saving_Archive::save_Function().
get_system_function() [1/2]
Function_P ID::get_system_function (Id id) static
If id is the ID of primitive function, primitive operator, or quad function, then return a pointer to it. Otherwise return 0.
Definition at line 139 of file Id.cc.
Referenced by get_system_function(), XML_Loading_Archive::read_Function(), and XML_Loading_Archive::read_Function_name().
get_system_function() [2/2]
static Function_P ID::get_system_function (TokenTag tag) inline static
If tag is the tag of primitive function, primitive operator, or quad function, then return a pointer to it. Otherwise return 0.
Definition at line 63 of file Id.hh.
References get_system_function().
get_system_variable()
Symbol * ID::get_system_variable (Id id) static
If id is the ID of a quad variable, then return a pointer to its symbol. Otherwise return 0.
Definition at line 158 of file Id.cc.
get_token_tag()
TokenTag ID::get_token_tag (Id id) static
return the TokenTag for id
Definition at line 178 of file Id.cc.
Referenced by SystemVariable::get_token().
The documentation for this class was generated from the following files:
src/Id.hh
src/Id.cc