GNU APL: IndexExpr Class Reference
IndexExpr Class Reference
The interal representation of some APL index [A1;A2;...;An].
#include <IndexExpr.hh>
Public Member Functions
IndexExpr (Assign_state ass_state, const char *loc)
constructor: empty (0-dimensional) IndexExpr
~IndexExpr ()
destructor
void add_index (Value_P val)
append a value.
uRank get_rank () const
return the number of values (= number of semicolons + 1), including elided indices
bool is_axis () const
return true iff the number of dimensions is 1 (i.e. no ; and non-empty)
sAxis get_axis (sRank max_axis) const
Return an axis (from an IndexExpr of rank 1.
Assign_state get_assign_state () const
return true iff this index is part of indexed assignment (A[]←)
Value_P extract_axis ()
return the single axis value and clear it in this IndexExpr.
void check_index_range (const Shape &shape) const
check that all indices indices of this IndexExpr are valid indices for shape, raise INDEX_ERROR if not.
const Value * get_axis_value (uAxis ax) const
return axis rk (rk in shape order as opposed to index order)
Public Member Functions inherited from DynamicObject
DynamicObject (const char *loc, DynamicObject *anchor)
constructor: a DynamicObject allocated at source location loc
DynamicObject (const char *loc)
a special constructor for the statically allocated anchors
DynamicObject * get_next ()
return the next DynamicObject in its list
const DynamicObject * get_next () const
return the next DynamicObject in its list
DynamicObject * get_prev ()
return the previous DynamicObject in its list
const DynamicObject * get_prev () const
return the previous DynamicObject in its list
void unlink ()
unlink this DynamicObject from its list
const IndexExpr * pIndexExpr () const
cast to IndexExpr *. Caller must check that this cast is valid.
IndexExpr * pIndexExpr ()
cast to IndexExpr *. Caller must check that this cast is valid.
void print (ostream &out) const
print this object
void print_new (ostream &out, const char *loc) const
print new object message
void print_chain (ostream &out) const
print the list of objects starting at this object
const char * where_allocated () const
where this value was allocated.
Static Public Member Functions
static int print_stale (ostream &out)
print stale IndexExprs, and return the number of stale IndexExprs.
static void erase_stale (const char *loc)
erase stale IndexExprs
Static Public Member Functions inherited from DynamicObject
static const DynamicObject * get_all_values ()
return a pointer to all allocated Values
Public Attributes
uint32_t quad_io
The quad-io for this index.
Value_P values [MAX_RANK]
The values (0 = elided index as in [] or [;].
Protected Attributes
uRank rank
the number of dimensions (including elided)
uRank value_count
the number of values (excluding elided)
const Assign_state assign_state
true iff this index is part of indexed assignment (A[]←)
Protected Attributes inherited from DynamicObject
const char * alloc_loc
where this value was allocated or deleted.
DynamicObject * next
the next DynamicObject (of all objects) in this's list
DynamicObject * prev
the previous DynamicObject (of all objects) in this's list
Additional Inherited Members
Protected Member Functions inherited from DynamicObject
const Value & rValue () const
downcast to const Value &. Caller must check that this cast is valid.
Value & rValue ()
down cast to Value &. Caller must check that this cast is valid.
Static Protected Attributes inherited from DynamicObject
static DynamicObject all_values
the anchor for all dynamic Value instances
static DynamicObject all_index_exprs
the anchor for all dynamic IndexExpr instances
Detailed Description
The interal representation of some APL index [A1;A2;...;An].
An array of index values.
Definition at line 33 of file IndexExpr.hh.
Constructor & Destructor Documentation
IndexExpr()
IndexExpr::IndexExpr (Assign_state ass_state, const char * loc)
constructor: empty (0-dimensional) IndexExpr
Definition at line 28 of file IndexExpr.cc.
~IndexExpr()
IndexExpr::~IndexExpr ()
destructor
Definition at line 37 of file IndexExpr.cc.
References rank, Value_P_Base::reset(), value_count, and values.
Referenced by Prefix::clean_up().
Member Function Documentation
add_index()
void IndexExpr::add_index (Value_P val) inline
append a value.
Definition at line 49 of file IndexExpr.hh.
References rank, value_count, and values.
Referenced by Bif_F2_INDEX::eval_AB(), Bif_F2_INDEX::eval_AXB(), and XML_Loading_Archive::read_Token().
check_index_range()
void IndexExpr::check_index_range (const Shape & shape) const
check that all indices indices of this IndexExpr are valid indices for shape, raise INDEX_ERROR if not.
Definition at line 58 of file IndexExpr.cc.
References get_axis_value(), Shape::get_rank(), Shape::get_shape_item(), quad_io, and rank.
Referenced by Value::index().
erase_stale()
void IndexExpr::erase_stale (const char * loc) static
erase stale IndexExprs
Definition at line 134 of file IndexExpr.cc.
References DynamicObject::all_index_exprs, DynamicObject::alloc_loc, erase_stale(), DynamicObject::get_next(), DynamicObject::pIndexExpr(), and DynamicObject::unlink().
Referenced by erase_stale().
extract_axis()
Value_P IndexExpr::extract_axis ()
return the single axis value and clear it in this IndexExpr.
Definition at line 46 of file IndexExpr.cc.
References rank, Value_P_Base::reset(), value_count, and values.
Referenced by Bif_F2_INDEX::eval_AB(), Bif_F2_INDEX::eval_AXB(), and Token::Token().
get_assign_state()
Assign_state IndexExpr::get_assign_state () const inline
return true iff this index is part of indexed assignment (A[]←)
Definition at line 67 of file IndexExpr.hh.
References assign_state.
get_axis()
sRank IndexExpr::get_axis (sRank max_axis) const
Return an axis (from an IndexExpr of rank 1.
Definition at line 90 of file IndexExpr.cc.
References Workspace::get_IO(), rank, and values.
get_axis_value()
const Value * IndexExpr::get_axis_value (uAxis ax) const inline
return axis rk (rk in shape order as opposed to index order)
Definition at line 78 of file IndexExpr.hh.
References Value_P_Base::get(), rank, and values.
Referenced by Quad_SYL::assign_indexed(), and check_index_range().
get_rank()
uRank IndexExpr::get_rank () const inline
return the number of values (= number of semicolons + 1), including elided indices
Definition at line 58 of file IndexExpr.hh.
References rank.
Referenced by Quad_SYL::assign_indexed(), Symbol::assign_indexed(), XML_Saving_Archive::emit_token_val(), Value::index(), MultiIndexIterator::MultiIndexIterator(), and Token::Token().
is_axis()
bool IndexExpr::is_axis () const inline
return true iff the number of dimensions is 1 (i.e. no ; and non-empty)
Definition at line 61 of file IndexExpr.hh.
References rank.
Referenced by Symbol::assign_indexed(), Quad_FC::assign_indexed(), Bif_F2_INDEX::eval_AB(), Bif_F2_INDEX::eval_AXB(), and Value::index().
print_stale()
int IndexExpr::print_stale (ostream & out) static
print stale IndexExprs, and return the number of stale IndexExprs.
Definition at line 111 of file IndexExpr.cc.
References DynamicObject::all_index_exprs, DynamicObject::get_next(), DynamicObject::pIndexExpr(), and DynamicObject::where_allocated().
Referenced by Command::cmd_CHECK(), and IO_Files::end_of_current_file().
Member Data Documentation
assign_state
const Assign_state IndexExpr::assign_state protected
true iff this index is part of indexed assignment (A[]←)
Definition at line 95 of file IndexExpr.hh.
Referenced by get_assign_state().
quad_io
uint32_t IndexExpr::quad_io
The quad-io for this index.
Definition at line 43 of file IndexExpr.hh.
Referenced by check_index_range(), Bif_F2_INDEX::eval_AB(), Bif_F2_INDEX::eval_AXB(), and MultiIndexIterator::MultiIndexIterator().
rank
uRank IndexExpr::rank protected
the number of dimensions (including elided)
Definition at line 89 of file IndexExpr.hh.
Referenced by add_index(), check_index_range(), extract_axis(), get_axis(), get_axis_value(), get_rank(), is_axis(), and ~IndexExpr().
value_count
uRank IndexExpr::value_count protected
the number of values (excluding elided)
Definition at line 92 of file IndexExpr.hh.
Referenced by add_index(), extract_axis(), and ~IndexExpr().
values
Value_P IndexExpr::values[MAX_RANK]
The values (0 = elided index as in [] or [;].
Definition at line 46 of file IndexExpr.hh.
Referenced by add_index(), Symbol::assign_indexed(), Quad_FC::assign_indexed(), XML_Saving_Archive::emit_token_val(), extract_axis(), get_axis(), get_axis_value(), Value::index(), MultiIndexIterator::MultiIndexIterator(), and ~IndexExpr().
The documentation for this class was generated from the following files:
src/IndexExpr.hh
src/IndexExpr.cc