GNU APL: LineHistory Class Reference
LineHistory Class Reference
the lines that the user has previously entered
#include <LineInput.hh>
Public Member Functions
LineHistory (int maxl)
constructor: empty line history
LineHistory (const Nabla &nabla)
constructor: line history from function being ∇-edited
void read_history (const char *filename)
read history from file
void save_history (const char *filename)
save history to file
void clear_history (ostream &out)
clear history
void print_history (ostream &out) const
print history to out
void next ()
start a new up/down sequence
const UCS_string * up ()
move to next older entry
const UCS_string * down ()
move to next newer entry
const void clear_search (void)
update history search substring
const void update_search (UCS_string &cur_line)
update search substring (called when current line is edited)
const UCS_string * search (UCS_string &cur_line)
find entries like current line in history
ostream & info (ostream &out) const
print relevant indices
void add_line (const UCS_string &line)
add one line to this history
void replace_line (const UCS_string &line)
replace the last line of this history
Static Public Attributes
static LineHistory quote_quad_history
the history for ⍞
static LineHistory quad_quad_history
the history for ⎕
static LineHistory quad_INP_history
the history for ⎕INP
Protected Attributes
int current_line
the current line (controlled by up()/down())
int put
the oldest line
const int max_lines
the max. history size
UCS_string cur_search_substr
the current searched-for substring
int last_search_line
the last searched-for line match
UCS_string_vector hist_lines
the history
Detailed Description
the lines that the user has previously entered
Definition at line 45 of file LineInput.hh.
Constructor & Destructor Documentation
LineHistory() [1/2]
LineHistory::LineHistory (int maxl)
constructor: empty line history
Definition at line 126 of file LineInput.cc.
References add_line().
LineHistory() [2/2]
LineHistory::LineHistory (const Nabla & nabla)
constructor: line history from function being ∇-edited
Definition at line 137 of file LineInput.cc.
References add_line(), and current_line.
Member Function Documentation
add_line()
void LineHistory::add_line (const UCS_string & line)
add one line to this history
Definition at line 243 of file LineInput.cc.
References UCS_string::back(), UCS_string::has_black(), hist_lines, max_lines, next(), UCS_string::pop_back(), put, and UCS_string::size().
Referenced by LineInput::add_history_line(), clear_history(), LineInput::edit_line(), LineHistory(), and read_history().
clear_history()
void LineHistory::clear_history (ostream & out)
clear history
Definition at line 220 of file LineInput.cc.
References add_line(), current_line, hist_lines, and put.
Referenced by LineInput::clear_history().
clear_search()
const void LineHistory::clear_search (void)
update history search substring
Definition at line 317 of file LineInput.cc.
References cur_search_substr.
Referenced by LineEditContext::cursor_CLEAR_SEARCH().
down()
const UCS_string * LineHistory::down ()
move to next newer entry
Definition at line 302 of file LineInput.cc.
References current_line, hist_lines, and put.
Referenced by LineEditContext::cursor_DOWN().
info()
ostream & LineHistory::info (ostream & out) const inline
print relevant indices
Definition at line 90 of file LineInput.hh.
References current_line, hist_lines, and put.
Referenced by LineEditContext::cursor_CLEAR_SEARCH(), LineEditContext::cursor_DOWN(), LineEditContext::cursor_SEARCH(), and LineEditContext::cursor_UP().
next()
void LineHistory::next () inline
start a new up/down sequence
Definition at line 67 of file LineInput.hh.
References current_line, hist_lines, and put.
Referenced by add_line(), and read_history().
print_history()
void LineHistory::print_history (ostream & out) const
print history to out
Definition at line 230 of file LineInput.cc.
References hist_lines, and put.
Referenced by LineInput::print_history().
read_history()
void LineHistory::read_history (const char * filename)
read history from file
Definition at line 159 of file LineInput.cc.
References add_line(), and next().
Referenced by LineInput::LineInput().
replace_line()
void LineHistory::replace_line (const UCS_string & line)
replace the last line of this history
Definition at line 283 of file LineInput.cc.
References hist_lines, and put.
Referenced by LineInput::replace_history_line().
save_history()
void LineHistory::save_history (const char * filename)
save history to file
Definition at line 191 of file LineInput.cc.
References hist_lines, and put.
Referenced by LineInput::~LineInput().
search()
const UCS_string * LineHistory::search (UCS_string & cur_line)
find entries like current line in history
Definition at line 329 of file LineInput.cc.
References cur_search_substr, current_line, hist_lines, and last_search_line.
Referenced by LineEditContext::cursor_SEARCH().
up()
const UCS_string * LineHistory::up ()
move to next older entry
Definition at line 290 of file LineInput.cc.
References current_line, hist_lines, and put.
Referenced by LineEditContext::cursor_UP().
update_search()
const void LineHistory::update_search (UCS_string & cur_line)
update search substring (called when current line is edited)
Definition at line 323 of file LineInput.cc.
References cur_search_substr.
Referenced by LineEditContext::update_SEARCH().
Member Data Documentation
cur_search_substr
UCS_string LineHistory::cur_search_substr protected
the current searched-for substring
Definition at line 121 of file LineInput.hh.
Referenced by clear_search(), search(), and update_search().
current_line
int LineHistory::current_line protected
the current line (controlled by up()/down())
Definition at line 112 of file LineInput.hh.
Referenced by clear_history(), down(), info(), LineHistory(), next(), search(), and up().
hist_lines
UCS_string_vector LineHistory::hist_lines protected
the history
Definition at line 127 of file LineInput.hh.
Referenced by add_line(), clear_history(), down(), info(), next(), print_history(), replace_line(), save_history(), search(), and up().
last_search_line
int LineHistory::last_search_line protected
the last searched-for line match
Definition at line 124 of file LineInput.hh.
Referenced by search().
max_lines
const int LineHistory::max_lines protected
the max. history size
Definition at line 118 of file LineInput.hh.
Referenced by add_line().
put
int LineHistory::put protected
the oldest line
Definition at line 115 of file LineInput.hh.
Referenced by add_line(), clear_history(), down(), info(), next(), print_history(), replace_line(), save_history(), and up().
quad_INP_history
LineHistory LineHistory::quad_INP_history static
the history for ⎕INP
Definition at line 108 of file LineInput.hh.
Referenced by Quad_INP::eval_XB(), and Quad_INP::read_strings().
quad_quad_history
LineHistory LineHistory::quad_quad_history static
the history for ⎕
Definition at line 105 of file LineInput.hh.
Referenced by Quad_Quad::resolve().
quote_quad_history
LineHistory LineHistory::quote_quad_history static
the history for ⍞
Definition at line 102 of file LineInput.hh.
Referenced by Quad_QUOTE::get_apl_value().
The documentation for this class was generated from the following files:
src/LineInput.hh
src/LineInput.cc