GNU APL: Bif_F12_PICK Class Reference
Bif_F12_PICK Class Reference
The class implementing ⊃
#include <Bif_F12_PARTITION_PICK.hh>
Public Member Functions
Bif_F12_PICK ()
Constructor.
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B()
virtual Token eval_XB (Value_P X, Value_P B) const
overloaded Function::eval_XB()
Public Member Functions inherited from NonscalarFunction
NonscalarFunction (TokenTag tag)
Constructor.
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
virtual bool has_result () const
overloaded Function::has_result()
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Static Public Member Functions
static Value_P disclose (Value_P B, bool rank_tolerant)
⊃B
static void disclose_item (Value &Z, ShapeItem b, const Shape &item_shape, ShapeItem item_len, const Cell &B_item)
create a copy of B_item, pad as needed to have item_shape, and store it in Z, starteding at Z_start.
static Value_P disclose_with_axis (const Shape &axes_X, Value_P B)
⊃[X]B
Static Public Attributes
static Bif_F12_PICK * fun = &Bif_F12_PICK ::_fun
Built-in function.
static Bif_F12_PICK _fun
Built-in function.
Static Protected Member Functions
static Shape compute_item_shape (Value_P B, bool rank_tolerant)
the shape of the items being disclosed
static ShapeItem pick_offset (const Cell *const A0, ShapeItem idx_A, ShapeItem len_A, Value_P B, APL_Integer qio)
compute the offset of the Cell in B that shall be picked.
static Value_P pick (const Cell *const A0, ShapeItem idx_A, ShapeItem len_A, Value_P B, APL_Integer qio)
Pick from B according to cA and len_A. cell_owner is non-zero if a left-vlues is picked, (e.g (2 1⊃B)←'TR')
Additional Inherited Members
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
The class implementing ⊃
primitive functions pick and disclose
Definition at line 89 of file Bif_F12_PARTITION_PICK.hh.
Constructor & Destructor Documentation
Bif_F12_PICK()
Bif_F12_PICK::Bif_F12_PICK () inline
Constructor.
Definition at line 93 of file Bif_F12_PARTITION_PICK.hh.
Member Function Documentation
compute_item_shape()
Shape Bif_F12_PICK::compute_item_shape (Value_P B, bool rank_tolerant) static protected
the shape of the items being disclosed
Definition at line 439 of file Bif_F12_PARTITION_PICK.cc.
References Value_P_Base::get(), Cell::get_lval_value(), Cell::get_pointer_value(), Value::get_rank(), Value::get_shape_item(), Cell::is_lval_cell(), and Cell::is_pointer_cell().
Referenced by disclose().
disclose()
Value_P Bif_F12_PICK::disclose (Value_P B, bool rank_tolerant) static
⊃B
Definition at line 262 of file Bif_F12_PARTITION_PICK.cc.
References compute_item_shape(), disclose(), disclose_item(), CellFunctionStatistics::first, Cell::get_pointer_value(), Shape::get_volume(), and Cell::is_pointer_cell().
Referenced by disclose(), disclose_with_axis(), eval_B(), and Value::print_member().
disclose_item()
void Bif_F12_PICK::disclose_item (Value & Z, ShapeItem b, const Shape & item_shape, ShapeItem item_len, const Cell & B_item) static
create a copy of B_item, pad as needed to have item_shape, and store it in Z, starteding at Z_start.
Definition at line 317 of file Bif_F12_PARTITION_PICK.cc.
References CDR_header::fill, Cell::get_lval_value(), Cell::get_pointer_value(), Cell::is_character_cell(), Cell::is_lval_cell(), Cell::is_pointer_cell(), Value::next_ravel_0(), Value::next_ravel_Cell(), Value::next_ravel_Char(), and Value::next_ravel_Lval().
Referenced by disclose().
disclose_with_axis()
Value_P Bif_F12_PICK::disclose_with_axis (const Shape & axes_X, Value_P B) static
⊃[X]B
Definition at line 391 of file Bif_F12_PARTITION_PICK.cc.
References Shape::add_shape_item(), disclose(), Value_P_Base::get(), Workspace::get_IO(), Shape::get_rank(), Shape::get_shape_item(), and Bif_F12_TRANSPOSE::transpose().
Referenced by eval_XB().
eval_AB()
Token Bif_F12_PICK::eval_AB (Value_P A, Value_P B) const virtual
overloaded Function::eval_AB()
Reimplemented from Function.
Definition at line 243 of file Bif_F12_PARTITION_PICK.cc.
References Workspace::get_IO(), and pick().
eval_B()
virtual Token Bif_F12_PICK::eval_B (Value_P B) const inline virtual
overloaded Function::eval_B()
Reimplemented from Function.
Definition at line 101 of file Bif_F12_PARTITION_PICK.hh.
References disclose().
eval_XB()
virtual Token Bif_F12_PICK::eval_XB (Value_P X, Value_P B) const inline virtual
overloaded Function::eval_XB()
Reimplemented from Function.
Definition at line 114 of file Bif_F12_PARTITION_PICK.hh.
References disclose_with_axis(), Value_P_Base::get(), and Value::to_shape().
pick()
Value_P Bif_F12_PICK::pick (const Cell *const A0, ShapeItem idx_A, ShapeItem len_A, Value_P B, APL_Integer qio) static protected
Pick from B according to cA and len_A. cell_owner is non-zero if a left-vlues is picked, (e.g (2 1⊃B)←'TR')
Definition at line 609 of file Bif_F12_PARTITION_PICK.cc.
References Cell::get_lval_value(), Cell::get_pointer_value(), Cell::is_lval_cell(), Cell::is_pointer_cell(), pick(), and pick_offset().
Referenced by eval_AB(), and pick().
pick_offset()
ShapeItem Bif_F12_PICK::pick_offset (const Cell *const A0, ShapeItem idx_A, ShapeItem len_A, Value_P B, APL_Integer qio) static protected
compute the offset of the Cell in B that shall be picked.
Definition at line 525 of file Bif_F12_PARTITION_PICK.cc.
References Cell::get_near_int(), Cell::get_pointer_value(), Shape::get_shape_item(), and Cell::is_pointer_cell().
Referenced by pick().
Member Data Documentation
_fun
Bif_F12_PICK Bif_F12_PICK::_fun static
Built-in function.
Definition at line 124 of file Bif_F12_PARTITION_PICK.hh.
fun
Bif_F12_PICK * Bif_F12_PICK::fun = &Bif_F12_PICK ::_fun static
Built-in function.
Definition at line 123 of file Bif_F12_PARTITION_PICK.hh.
The documentation for this class was generated from the following files:
src/Bif_F12_PARTITION_PICK.hh
src/Bif_F12_PARTITION_PICK.cc