GNU APL: SystemVariable Class Reference
SystemVariable Class Reference
Base class for all APL system variables.
#include <SystemVariable.hh>
Public Member Functions
SystemVariable (Id id)
Construct a SystemVariable with Id id.
Token get_token ()
return the TokenTag for this system variable
virtual ostream & print (ostream &out) const
overloaded Symbol::print().
virtual void assign (Value_P B, bool clone, const char *loc)
overloaded Symbol::assign().
virtual void assign_indexed (const Value *X, Value_P B)
overloaded Symbol::assign_indexed().
virtual void get_attributes (int mode, Value &Z) const
overloaded Symbol::get_attributes().
virtual int expunge ()
system vars cannot be expunged.
virtual Token resolve_lv (const char *loc)
do not allow (...⎕xxx)←...
Public Member Functions inherited from Symbol
Symbol (Id id)
create a system symbol with Id id
Symbol (const UCS_string &ucs, Id id)
create a symbol with name ucs
virtual ~Symbol ()
destructor
ostream & list (ostream &out) const
List this Symbol (for)VARS,)FNS)
void write_OUT (FILE *out, uint64_t &seq) const
write this symbol in)OUT format to file out
virtual void resolve (Token &token, bool left)
set token according to the current NC/sym_val of this Symbol
void resolve_shared_variable (Token &token)
set token according to the current NC/sym_val of this shared var
virtual Token resolve_lv (const char *loc)
resolve a variable name for an assignment
TokenClass resolve_class (bool left)
return the token class of this Symbol WITHOUT calling resolve()
virtual int expunge ()
set current NameClass of this Symbol to NC_UNUSED_USER_NAME and remove any values associated with this symbol
void set_NC (NameClass nc)
Set current NameClass of this Symbol to nc.
void set_NC (NameClass nc, Function_P fun)
Set current NameClass of this Symbol to nc and function fun.
void share_var (SV_key key)
share variable with proc
SV_Coupling unshare_var ()
unshare a shared variable
void clear_vs ()
clear the value stack of this symbol
int compare (const Symbol &other) const
Compare name of this value with other.
virtual bool is_readonly () const
return true iff this variable is read-only (overloaded by RO_SystemVariable)
virtual void assign (Value_P value, bool clone, const char *loc)
Assign value to this Symbol.
void assign_shared_variable (Value_P value, const char *loc)
Assign value to this Symbol (which is a shared variable)
virtual void assign_indexed (const IndexExpr &index, Value_P value)
Indexed (multi-dimensional) assign value to this Symbol.
virtual void assign_indexed (const Value *X, Value_P value)
Indexed (one-dimensional) assign value to this Symbol.
virtual bool assign_named_lambda (Function_P lambda, const char *loc)
assign lambda, eg. V←{ ... }
virtual ostream & print (ostream &out) const
Print this Symbol to out.
ostream & print_verbose (ostream &out) const
Print this Symbol and its stack to out.
virtual void pop ()
Pop latest entry from the stack of this Symbol.
virtual void push ()
Push an undefined entry onto the stack of this Symbol.
virtual void push_label (Function_Line label)
push a label onto the stack of this Symbol
virtual void push_function (Function_P function)
push a function onto the stack of this Symbol
virtual void push_value (Value_P value)
Push an APL value onto the stack of this Symbol.
int get_exec_ufun_depth (const UserFunction *ufun)
return the depth (global == 0) of ufun on the stack. Use the largest depth if ufun is pushed multiple times
virtual Value_P get_apl_value () const
return the current APL value (or throw a VALUE_ERROR)
const Cell * get_first_cell () const
return the first Cell of this value without creating a value
bool can_be_assigned () const
return true, iff this Symbol can be assigned
SV_key get_SV_key () const
return the current SV_key (or throw a VALUE_ERROR)
void set_SV_key (SV_key key)
set the current SV_key
bool is_erased () const
return true, iff this Symbol is not used (i.e. erased)
virtual const Function * get_function () const
Return the current function (or throw a VALUE_ERROR)
Function_P get_function (unsigned int si) const
Return the function at SI level si, or 0 if none.
virtual UCS_string get_name () const
The name of this Symbol.
const UCS_string * get_name_ptr () const
overloaded NamedObject::get_name_ptr()
virtual Function_P get_function ()
overloaded NamedObject::get_function()
virtual Value_P get_value ()
overloaded NamedObject::get_value()
const Value * get_val_cptr () const
return a const pointer to the current APL value
Value * get_val_wptr ()
return a pointer to the current APL value
const char * cant_be_defined () const
return a reason why this symbol cant become a defined function
virtual Symbol * get_symbol ()
overloaded NamedObject::get_symbol()
virtual const Symbol * get_symbol () const
overloaded NamedObject::get_symbol()
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z...
const int value_stack_size () const
return the size of the value stack
const ValueStackItem * top_of_stack () const
return the top-most item on the value stack
ValueStackItem * top_of_stack ()
return the top-most item on the value stack
const ValueStackItem & operator[] (int idx) const
return the idx'th item on stack (higher index = newer item)
ValueStackItem & operator[] (int idx)
return the idx'th item on stack (higher index = newer item)
void set_monitor_callback (void(*callback)(const Symbol &, Symbol_Event))
set a callback function for symbol events
void unmark_all_values () const
clear the marked flag of all entries
int show_owners (ostream &out, const Value &value) const
print variables owning value
void dump (ostream &out) const
dump this symbol to out
void call_monitor_callback (Symbol_Event ev)
call the monitor callback function (if any) with event ev
bool equal (const UCS_string &ucs) const
Compare the name of this Symbol with ucs.
int get_SI_level (Function_P fun) const
return the level of fun on the stack of this Symbol) on the SI stack
int get_SI_level (const Value &val) const
return the SI stack level of val on the stack of this Symbol)
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Additional Inherited Members
Static Public Member Functions inherited from Symbol
static void vector_assignment (std::vector< Symbol * > &symbols, Value_P values)
perform a vector assignment (like (A B C)←1 2 3) for variables in symbols with values values
Public Attributes inherited from Symbol
Symbol * next
The next Symbol with the same hash value as this Symbol.
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Attributes inherited from Symbol
UCS_string name
the name of this Symbol
void(* monitor_callback)(const Symbol &, Symbol_Event sev)
called on symbol events (if non-0)
std::vector< ValueStackItem > value_stack
the value stack of this Symbol
Detailed Description
Base class for all APL system variables.
Base class for all system variables (Quad variables).
Definition at line 36 of file SystemVariable.hh.
Constructor & Destructor Documentation
SystemVariable()
SystemVariable::SystemVariable (Id id) inline
Construct a SystemVariable with Id id.
Definition at line 40 of file SystemVariable.hh.
Member Function Documentation
assign()
void SystemVariable::assign (Value_P B, bool clone, const char * loc) virtual
overloaded Symbol::assign().
Reimplemented from Symbol.
Reimplemented in RO_SystemVariable, Quad_CT, Quad_FC, Quad_IO, Quad_L, Quad_LX, Quad_PP, Quad_PR, Quad_PS, Quad_PW, Quad_Quad, Quad_QUOTE, Quad_R, Quad_SYL, Quad_TZ, Quad_X, Quad_RL, and Quad_SVE.
Definition at line 63 of file SystemVariable.cc.
References NamedObject::get_Id().
assign_indexed()
void SystemVariable::assign_indexed (const Value * X, Value_P B) virtual
overloaded Symbol::assign_indexed().
Reimplemented from Symbol.
Reimplemented in RO_SystemVariable, Quad_FC, Quad_LX, Quad_PS, and Quad_SYL.
Definition at line 71 of file SystemVariable.cc.
References NamedObject::get_Id().
expunge()
virtual int SystemVariable::expunge () inline virtual
system vars cannot be expunged.
Reimplemented from Symbol.
Definition at line 61 of file SystemVariable.hh.
get_attributes()
void SystemVariable::get_attributes (int mode, Value & Z) const virtual
overloaded Symbol::get_attributes().
Reimplemented from Symbol.
Definition at line 85 of file SystemVariable.cc.
References Symbol::get_apl_value(), Value::next_ravel_0(), Value::next_ravel_1(), and Value::next_ravel_Int().
get_token()
Token SystemVariable::get_token () inline
return the TokenTag for this system variable
Definition at line 45 of file SystemVariable.hh.
References NamedObject::get_Id(), and ID::get_token_tag().
Referenced by Workspace::get_quad().
print()
ostream & SystemVariable::print (ostream & out) const virtual
overloaded Symbol::print().
Reimplemented from Symbol.
Definition at line 79 of file SystemVariable.cc.
References NamedObject::get_Id().
resolve_lv()
virtual Token SystemVariable::resolve_lv (const char * loc) inline virtual
do not allow (...⎕xxx)←...
Reimplemented from Symbol.
Definition at line 64 of file SystemVariable.hh.
The documentation for this class was generated from the following files:
src/SystemVariable.hh
src/SystemVariable.cc