GNU APL: LineEditContext Class Reference
LineEditContext Class Reference
a context for one user-input line
#include <LineInput.hh>
Public Member Functions
LineEditContext (LineInputMode mode, int rows, int cols, LineHistory &hist, const UCS_string &prmt)
constructor
~LineEditContext ()
destructor
void clear ()
clear (after ^C)
int get_screen_rows () const
return the number of screen rows
int get_screen_cols () const
return the number of screen columns
int get_total_length () const
total length (prompt + user_line)
bool on_bad_col (int offset) const
return true if prompt + offset is on column 0
void refresh_wrapped_cursor ()
refresh cursor if its position may be wrong (due to forward or backward wraparound being enabled or not)
void move_idx (int new_idx)
move the cursor
int get_idx (void)
get current cursor column
void set_cursor ()
set the cursor (writing the appropriate ESC sequence to CIN)
void adjust_allocated_height ()
adjust (increment) the allocated height (long lines)
void refresh_from_cursor ()
refresh screen from cursor onwards
void refresh_all ()
refresh screen from prompt (including) onwards
void delete_char ()
delete char at cursor position
void insert_char (Unicode uni)
insert uni at cursor position
void toggle_ins_mode ()
toggle the insert mode
void cut_to_EOL ()
cut from cursor to end of line
void paste ()
paste to cursor position
void cursor_HOME ()
move cursor home
void cursor_END ()
move cursor to end
void cursor_LEFT ()
move cursor left
void cursor_RIGHT ()
move cursor right
void backspc ()
move cursor left and delete char
void tab_expansion (LineInputMode mode)
tab expansion
void cursor_CLEAR_SEARCH ()
reset search substring
void cursor_UP ()
move backwards in history
void cursor_DOWN ()
move forward in history
void update_SEARCH ()
shortcut calling update_search() of member history with argument user_line
void cursor_SEARCH ()
search line history
const UCS_string & get_user_line () const
return current user input
Protected Attributes
int screen_rows
the number of screen rows
int screen_cols
the number of screen columns
int allocated_height
the number of screen rows used for editing
UCS_string prompt
the prompt
int uidx
current offset into user_line
bool ins_mode
true if input is in insert mode (as opposed to replace mode)
UCS_string user_line
the line being edited
LineHistory history
the line history
bool history_entered
true if history was entered
UCS_string user_line_before_history
ditto
Static Protected Attributes
static UCS_string cut_buffer
a buffer for ^K/^Y
Detailed Description
a context for one user-input line
Definition at line 131 of file LineInput.hh.
Constructor & Destructor Documentation
LineEditContext()
LineEditContext::LineEditContext (LineInputMode mode, int rows, int cols, LineHistory & hist, const UCS_string & prmt)
constructor
Definition at line 366 of file LineInput.cc.
References UCS_string::no_pad(), prompt, refresh_all(), UCS_string::size(), uidx, and user_line.
~LineEditContext()
LineEditContext::~LineEditContext ()
destructor
Definition at line 392 of file LineInput.cc.
References ins_mode.
Member Function Documentation
adjust_allocated_height()
void LineEditContext::adjust_allocated_height ()
adjust (increment) the allocated height (long lines)
Definition at line 400 of file LineInput.cc.
References allocated_height, CIN_ostream::can_clear_EOS(), CIN_ostream::clear_EOL(), CIN_ostream::clear_EOS(), get_total_length(), refresh_all(), screen_cols, and CIN_ostream::set_cursor().
Referenced by cursor_DOWN(), cursor_SEARCH(), cursor_UP(), insert_char(), refresh_from_cursor(), and tab_expansion().
backspc()
void LineEditContext::backspc () inline
move cursor left and delete char
Definition at line 218 of file LineInput.hh.
References delete_char(), move_idx(), and uidx.
Referenced by LineInput::edit_line().
clear()
void LineEditContext::clear () inline
clear (after ^C)
Definition at line 142 of file LineInput.hh.
References user_line.
Referenced by LineInput::edit_line().
cursor_CLEAR_SEARCH()
void LineEditContext::cursor_CLEAR_SEARCH ()
reset search substring
Definition at line 607 of file LineInput.cc.
References LineHistory::clear_search(), history, and LineHistory::info().
Referenced by LineInput::edit_line().
cursor_DOWN()
void LineEditContext::cursor_DOWN ()
move forward in history
Definition at line 642 of file LineInput.cc.
References adjust_allocated_height(), LineHistory::down(), history, history_entered, LineHistory::info(), move_idx(), refresh_from_cursor(), UCS_string::size(), uidx, user_line, and user_line_before_history.
Referenced by LineInput::edit_line().
cursor_END()
void LineEditContext::cursor_END () inline
move cursor to end
Definition at line 209 of file LineInput.hh.
References move_idx(), UCS_string::size(), uidx, and user_line.
Referenced by LineInput::edit_line().
cursor_HOME()
void LineEditContext::cursor_HOME () inline
move cursor home
Definition at line 206 of file LineInput.hh.
References move_idx(), and uidx.
Referenced by LineInput::edit_line().
cursor_LEFT()
void LineEditContext::cursor_LEFT () inline
move cursor left
Definition at line 212 of file LineInput.hh.
References move_idx(), and uidx.
Referenced by LineInput::edit_line().
cursor_RIGHT()
void LineEditContext::cursor_RIGHT () inline
move cursor right
Definition at line 215 of file LineInput.hh.
References move_idx(), UCS_string::size(), uidx, and user_line.
Referenced by LineInput::edit_line().
cursor_SEARCH()
void LineEditContext::cursor_SEARCH ()
search line history
Definition at line 680 of file LineInput.cc.
References adjust_allocated_height(), history, history_entered, LineHistory::info(), move_idx(), refresh_from_cursor(), LineHistory::search(), UCS_string::size(), uidx, user_line, and user_line_before_history.
Referenced by LineInput::edit_line().
cursor_UP()
void LineEditContext::cursor_UP ()
move backwards in history
Definition at line 614 of file LineInput.cc.
References adjust_allocated_height(), history, history_entered, LineHistory::info(), move_idx(), refresh_from_cursor(), UCS_string::size(), uidx, LineHistory::up(), user_line, and user_line_before_history.
Referenced by LineInput::edit_line().
cut_to_EOL()
void LineEditContext::cut_to_EOL ()
cut from cursor to end of line
Definition at line 526 of file LineInput.cc.
References cut_buffer, refresh_from_cursor(), UCS_string::size(), uidx, and user_line.
Referenced by LineInput::edit_line().
delete_char()
void LineEditContext::delete_char ()
delete char at cursor position
Definition at line 481 of file LineInput.cc.
References UCS_string::erase(), get_total_length(), UCS_string::pop_back(), refresh_from_cursor(), screen_cols, set_cursor(), UCS_string::size(), uidx, and user_line.
Referenced by backspc(), and LineInput::edit_line().
get_idx()
int LineEditContext::get_idx (void) inline
get current cursor column
Definition at line 172 of file LineInput.hh.
References uidx.
get_screen_cols()
int LineEditContext::get_screen_cols () const inline
return the number of screen columns
Definition at line 150 of file LineInput.hh.
References screen_cols.
get_screen_rows()
int LineEditContext::get_screen_rows () const inline
return the number of screen rows
Definition at line 146 of file LineInput.hh.
References screen_rows.
get_total_length()
int LineEditContext::get_total_length () const inline
total length (prompt + user_line)
Definition at line 154 of file LineInput.hh.
References prompt, UCS_string::size(), and user_line.
Referenced by adjust_allocated_height(), and delete_char().
get_user_line()
const UCS_string & LineEditContext::get_user_line () const inline
return current user input
Definition at line 241 of file LineInput.hh.
References user_line.
Referenced by LineInput::edit_line().
insert_char()
void LineEditContext::insert_char (Unicode uni)
insert uni at cursor position
Definition at line 498 of file LineInput.cc.
References adjust_allocated_height(), UCS_string::append(), ins_mode, UCS_string::insert(), move_idx(), refresh_from_cursor(), refresh_wrapped_cursor(), UCS_string::size(), uidx, and user_line.
Referenced by LineInput::edit_line().
move_idx()
void LineEditContext::move_idx (int new_idx) inline
move the cursor
Definition at line 168 of file LineInput.hh.
References set_cursor(), and uidx.
Referenced by backspc(), cursor_DOWN(), cursor_END(), cursor_HOME(), cursor_LEFT(), cursor_RIGHT(), cursor_SEARCH(), cursor_UP(), insert_char(), paste(), refresh_all(), refresh_from_cursor(), and tab_expansion().
on_bad_col()
bool LineEditContext::on_bad_col (int offset) const inline
return true if prompt + offset is on column 0
Definition at line 158 of file LineInput.hh.
References prompt, screen_cols, and UCS_string::size().
Referenced by refresh_wrapped_cursor().
paste()
void LineEditContext::paste ()
paste to cursor position
Definition at line 536 of file LineInput.cc.
References UCS_string::append(), cut_buffer, move_idx(), refresh_from_cursor(), UCS_string::size(), uidx, and user_line.
Referenced by LineInput::edit_line().
refresh_all()
void LineEditContext::refresh_all ()
refresh screen from prompt (including) onwards
Definition at line 469 of file LineInput.cc.
References allocated_height, move_idx(), prompt, refresh_from_cursor(), CIN_ostream::set_cursor(), uidx, and user_line.
Referenced by adjust_allocated_height(), LineEditContext(), and tab_expansion().
refresh_from_cursor()
void LineEditContext::refresh_from_cursor ()
refresh screen from cursor onwards
Definition at line 433 of file LineInput.cc.
References adjust_allocated_height(), allocated_height, CIN_ostream::can_clear_EOS(), CIN_ostream::clear_EOL(), CIN_ostream::clear_EOS(), move_idx(), refresh_wrapped_cursor(), set_cursor(), CIN_ostream::set_cursor(), UCS_string::size(), uidx, and user_line.
Referenced by cursor_DOWN(), cursor_SEARCH(), cursor_UP(), cut_to_EOL(), delete_char(), insert_char(), paste(), refresh_all(), and tab_expansion().
refresh_wrapped_cursor()
void LineEditContext::refresh_wrapped_cursor () inline
refresh cursor if its position may be wrong (due to forward or backward wraparound being enabled or not)
Definition at line 164 of file LineInput.hh.
References on_bad_col(), set_cursor(), and uidx.
Referenced by insert_char(), and refresh_from_cursor().
set_cursor()
void LineEditContext::set_cursor () inline
set the cursor (writing the appropriate ESC sequence to CIN)
Definition at line 176 of file LineInput.hh.
References allocated_height, prompt, screen_cols, CIN_ostream::set_cursor(), UCS_string::size(), and uidx.
Referenced by delete_char(), move_idx(), refresh_from_cursor(), and refresh_wrapped_cursor().
tab_expansion()
void LineEditContext::tab_expansion (LineInputMode mode)
tab expansion
Definition at line 574 of file LineInput.cc.
References adjust_allocated_height(), allocated_height, UCS_string::append(), TabExpansion::expand_tab(), move_idx(), refresh_all(), refresh_from_cursor(), UCS_string::size(), uidx, and user_line.
Referenced by LineInput::edit_line().
toggle_ins_mode()
void LineEditContext::toggle_ins_mode ()
toggle the insert mode
Definition at line 557 of file LineInput.cc.
References ins_mode.
Referenced by LineInput::edit_line().
update_SEARCH()
void LineEditContext::update_SEARCH (void)
shortcut calling update_search() of member history with argument user_line
Definition at line 674 of file LineInput.cc.
References history, LineHistory::update_search(), and user_line.
Referenced by LineInput::edit_line().
Member Data Documentation
allocated_height
int LineEditContext::allocated_height protected
the number of screen rows used for editing
Definition at line 252 of file LineInput.hh.
Referenced by adjust_allocated_height(), refresh_all(), refresh_from_cursor(), set_cursor(), and tab_expansion().
cut_buffer
UCS_string LineEditContext::cut_buffer static protected
a buffer for ^K/^Y
Definition at line 276 of file LineInput.hh.
Referenced by cut_to_EOL(), and paste().
history
LineHistory LineEditContext::history protected
the line history
Definition at line 267 of file LineInput.hh.
Referenced by cursor_CLEAR_SEARCH(), cursor_DOWN(), cursor_SEARCH(), cursor_UP(), and update_SEARCH().
history_entered
bool LineEditContext::history_entered protected
true if history was entered
Definition at line 270 of file LineInput.hh.
Referenced by cursor_DOWN(), cursor_SEARCH(), and cursor_UP().
ins_mode
bool LineEditContext::ins_mode protected
true if input is in insert mode (as opposed to replace mode)
Definition at line 261 of file LineInput.hh.
Referenced by insert_char(), toggle_ins_mode(), and ~LineEditContext().
prompt
UCS_string LineEditContext::prompt protected
the prompt
Definition at line 255 of file LineInput.hh.
Referenced by get_total_length(), LineEditContext(), on_bad_col(), refresh_all(), and set_cursor().
screen_cols
int LineEditContext::screen_cols protected
the number of screen columns
Definition at line 249 of file LineInput.hh.
Referenced by adjust_allocated_height(), delete_char(), get_screen_cols(), on_bad_col(), and set_cursor().
screen_rows
int LineEditContext::screen_rows protected
the number of screen rows
Definition at line 246 of file LineInput.hh.
Referenced by get_screen_rows().
uidx
int LineEditContext::uidx protected
current offset into user_line
Definition at line 258 of file LineInput.hh.
Referenced by backspc(), cursor_DOWN(), cursor_END(), cursor_HOME(), cursor_LEFT(), cursor_RIGHT(), cursor_SEARCH(), cursor_UP(), cut_to_EOL(), delete_char(), get_idx(), insert_char(), LineEditContext(), move_idx(), paste(), refresh_all(), refresh_from_cursor(), refresh_wrapped_cursor(), set_cursor(), and tab_expansion().
user_line
UCS_string LineEditContext::user_line protected
the line being edited
Definition at line 264 of file LineInput.hh.
Referenced by clear(), cursor_DOWN(), cursor_END(), cursor_RIGHT(), cursor_SEARCH(), cursor_UP(), cut_to_EOL(), delete_char(), get_total_length(), get_user_line(), insert_char(), LineEditContext(), paste(), refresh_all(), refresh_from_cursor(), tab_expansion(), and update_SEARCH().
user_line_before_history
UCS_string LineEditContext::user_line_before_history protected
ditto
Definition at line 273 of file LineInput.hh.
Referenced by cursor_DOWN(), cursor_SEARCH(), and cursor_UP().
The documentation for this class was generated from the following files:
src/LineInput.hh
src/LineInput.cc