GNU APL: CellFunctionStatistics Class Reference
CellFunctionStatistics Class Reference
Performance counters for one cell level function.
#include <Performance.hh>
Public Member Functions
CellFunctionStatistics (Pfstat_ID _id)
constructor: reset this statistics
virtual void reset ()
reset this statistics: clear first and subsequent records
void add_sample (uint64_t val, bool subseq)
add a sample to this statistics
virtual void print (ostream &out)
overloaded Statistics::print()
virtual void save_data (ostream &outf, const char *perf_name)
overloaded Statistics::save_data()
virtual const Statistics_record * get_first_record () const
return the record for the first executions
virtual const Statistics_record * get_record () const
return the record for subsequent executions
uint64_t get_sum () const
return the cycles sum
double get_sum2 () const
return the square of cycles sums
uint64_t get_count1 () const
return the number of first executions
uint64_t get_countN () const
return the number of subsequent executions
uint64_t get_count () const
return the number of all executions
Public Member Functions inherited from Statistics
Statistics (Pfstat_ID _id)
constructor
virtual ~Statistics ()
destructor
virtual void print (ostream &out)=0
print statistics
virtual void save_data (ostream &outf, const char *perf_name)=0
write statistics to file
virtual void reset ()=0
reset this statistics
virtual const Statistics_record * get_first_record () const
return the statistics for the first passes
virtual const Statistics_record * get_record () const
return the statistics for the subsequent passes
const char * get_name () const
return the name of this statistics
Protected Attributes
Statistics_record first
statistics for first executions
Statistics_record subsequent
statistics for subsequent executions
Protected Attributes inherited from Statistics
const Pfstat_ID id
the ID of this statistics
Additional Inherited Members
Static Public Member Functions inherited from Statistics
static const char * get_name (Pfstat_ID id)
return the name of the statistics with ID id
Detailed Description
Performance counters for one cell level function.
Definition at line 246 of file Performance.hh.
Constructor & Destructor Documentation
CellFunctionStatistics()
CellFunctionStatistics::CellFunctionStatistics (Pfstat_ID _id) inline
constructor: reset this statistics
Definition at line 250 of file Performance.hh.
References reset().
Member Function Documentation
add_sample()
void CellFunctionStatistics::add_sample (uint64_t val, bool subseq) inline
add a sample to this statistics
Definition at line 262 of file Performance.hh.
References Statistics_record::add_sample(), first, and subsequent.
get_count()
uint64_t CellFunctionStatistics::get_count () const inline
return the number of all executions
Definition at line 299 of file Performance.hh.
References first, Statistics_record::get_count(), and subsequent.
get_count1()
uint64_t CellFunctionStatistics::get_count1 () const inline
return the number of first executions
Definition at line 291 of file Performance.hh.
References first, and Statistics_record::get_count().
get_countN()
uint64_t CellFunctionStatistics::get_countN () const inline
return the number of subsequent executions
Definition at line 295 of file Performance.hh.
References Statistics_record::get_count(), and subsequent.
get_first_record()
virtual const Statistics_record * CellFunctionStatistics::get_first_record () const inline virtual
return the record for the first executions
Reimplemented from Statistics.
Definition at line 275 of file Performance.hh.
References first.
get_record()
virtual const Statistics_record * CellFunctionStatistics::get_record () const inline virtual
return the record for subsequent executions
Reimplemented from Statistics.
Definition at line 279 of file Performance.hh.
References subsequent.
get_sum()
uint64_t CellFunctionStatistics::get_sum () const inline
return the cycles sum
Definition at line 283 of file Performance.hh.
References first, Statistics_record::get_sum(), and subsequent.
get_sum2()
double CellFunctionStatistics::get_sum2 () const inline
return the square of cycles sums
Definition at line 287 of file Performance.hh.
References first, Statistics_record::get_sum2(), and subsequent.
print()
void CellFunctionStatistics::print (ostream & out) virtual
overloaded Statistics::print()
Implements Statistics.
Definition at line 349 of file Performance.cc.
References first, Statistics::get_name(), Statistics_record::print(), UCS_string::size(), and subsequent.
reset()
virtual void CellFunctionStatistics::reset () inline virtual
reset this statistics: clear first and subsequent records
Implements Statistics.
Definition at line 255 of file Performance.hh.
References first, Statistics_record::reset(), and subsequent.
Referenced by CellFunctionStatistics().
save_data()
void CellFunctionStatistics::save_data (ostream & outf, const char * perf_name) virtual
overloaded Statistics::save_data()
Implements Statistics.
Definition at line 364 of file Performance.cc.
References first, Statistics_record::save_record(), and subsequent.
Member Data Documentation
first
Statistics_record CellFunctionStatistics::first protected
statistics for first executions
Definition at line 304 of file Performance.hh.
Referenced by add_sample(), Bif_F12_PICK::disclose(), Bif_OPER2_RANK::do_ALyXB(), Bif_OPER1_EACH::do_eval_LB(), Bif_OPER2_RANK::do_LyXB(), Bif_OPER1_EACH::eval_ALB(), Bif_OPER2_OUTER::eval_ALRB(), Bif_OPER2_INNER::fill(), get_count(), get_count1(), get_first_record(), get_sum(), get_sum2(), print(), reset(), save_data(), and Doxy::variables_table().
subsequent
Statistics_record CellFunctionStatistics::subsequent protected
statistics for subsequent executions
Definition at line 307 of file Performance.hh.
Referenced by add_sample(), get_count(), get_countN(), get_record(), get_sum(), get_sum2(), print(), reset(), and save_data().
The documentation for this class was generated from the following files:
src/Performance.hh
src/Performance.cc