GNU APL: ComplexCell Class Reference
ComplexCell Class Reference
A cell containing one complex number.
#include <ComplexCell.hh>
Public Member Functions
ComplexCell (APL_Complex c)
Construct an complex number cell from a complex number.
ComplexCell (APL_Float r, APL_Float i)
Construct an complex number cell from real part r and imag part i.
virtual void init_other (void *other, Value &cell_owner, const char *loc) const
overloaded Cell::init_other
virtual bool is_complex_cell () const
overloaded Cell::is_complex_cell().
virtual bool is_finite () const
Overloaded Cell::is_finite().
virtual bool greater (const Cell &other) const
overloaded Cell::greater().
virtual bool equal (const Cell &other, double qct) const
overloaded Cell::equal().
virtual Comp_result compare (const Cell &other) const
overloaded Cell::compare()
virtual ErrorCode bif_ceiling (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_conjugate (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_direction (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_exponential (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_factorial (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_floor (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_magnitude (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_nat_log (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_negative (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_pi_times (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_pi_times_inverse (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_reciprocal (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_roll (Cell *Z) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_add (Cell *Z, const Cell *A) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_subtract (Cell *Z, const Cell *A) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_divide (Cell *Z, const Cell *A) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_equal (Cell *Z, const Cell *A) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_logarithm (Cell *Z, const Cell *A) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_multiply (Cell *Z, const Cell *A) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_power (Cell *Z, const Cell *A) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_maximum (Cell *Z, const Cell *A) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_minimum (Cell *Z, const Cell *A) const
Overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_residue (Cell *Z, const Cell *A) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_circle_fun (Cell *Z, const Cell *A) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual ErrorCode bif_circle_fun_inverse (Cell *Z, const Cell *A) const
overloaded from the corresponding Cell:: function (see class Cell).
virtual PrintBuffer character_representation (const PrintContext &pctx) const
the Quad_CR representation of this cell.
virtual bool need_scaling (const PrintContext &pctx) const
return true iff this cell needs scaling (exponential format) in pctx.
virtual ErrorCode bif_add_inverse (Cell *Z, const Cell *A) const
overloaded Cell::bif_add_inverse()
virtual ErrorCode bif_multiply_inverse (Cell *Z, const Cell *A) const
overloaded Cell::bif_multiply_inverse()
APL_Float mag2 () const
the square of the magnitude of aJb (= a² + b²)
Public Member Functions inherited from Cell
Cell ()
Construct an un-initialized Cell.
void init (const Cell &other, Value &this_owner, const char *loc)
init this Cell from a (possibly deep) copy of other
virtual void init_other (void *other, Value &other_owner, const char *loc) const
init (uninitialized) Cell other from this initialized cell
void init_from_value (Value *value, Value &cell_owner, const char *loc)
init this Cell from value. If value is a scalar then its first element is used (and value is erased). Otherwise a PointerCell is created.
virtual bool greater (const Cell &other) const
Return true if this cell is greater than other, with:
virtual bool equal (const Cell &other, double qct) const
return true if this cell is equal to other
Value_P to_value (const char *loc) const
return pointer value of a PointerCell or create a scalar with a copy of this cell.
void init_type (const Cell &other, Value &cell_owner, const char *loc)
init this cell to be the type of other
virtual Unicode get_char_value () const
Return the character value of a cell.
virtual int get_byte_value () const
Return the byte value (-128..255 incl) of a cell.
virtual APL_Integer get_int_value () const
Return the integer value of a cell.
virtual APL_Float get_real_value () const
Return the real part of a cell.
virtual APL_Float get_imag_value () const
Return the imaginary part of a cell.
virtual APL_Complex get_complex_value () const
Return the complex value of a cell.
virtual Value_P get_pointer_value () const
Return the APL value of a cell (Asserts for non-pointer cells)
virtual Cell * get_lval_value () const
Return the APL value of a cell (Asserts for non-lval cells)
virtual PrintBuffer character_representation (const PrintContext &pctx) const
the Quad_CR representation of this cell
virtual bool need_scaling (const PrintContext &pctx) const
return true if this cell needs scaling (exponential format) in pctx
virtual bool get_near_bool () const
Return value if it is close to boolean, or else throw DOMAIN_ERROR.
virtual APL_Integer get_near_int () const
Return value if it is close to int, or else throw DOMAIN_ERROR.
virtual APL_Integer get_checked_near_int () const
Return value if it is (known to be) close to int, or else Assert()
virtual bool is_near_zero () const
return true iff value is numeric and close to 0
virtual bool is_near_one () const
return true iff value is numeric and close to 1
bool is_near_bool () const
return true iff value is numeric and close to 0 or 1
virtual bool is_near_int () const
True iff value is numeric and close to an int.
virtual bool is_near_int64_t () const
True iff value is numeric and close to an int.
virtual bool is_near_real () const
return true iff value is numeric and close to a real number
virtual int CDR_size () const
return the minimum number of data bytes to store this cell in CDR format. The actual number of data bytes can be bigger if other cells need more bytes,
virtual void release (const char *loc)
Release content pointed to (complex, APL value)
virtual bool is_integer_cell () const
Return true iff this cell is an integer cell.
bool is_simple_cell () const
Return true iff this cell is a numeric cor character cell.
virtual bool is_float_cell () const
Return true iff this cell is a floating point cell.
virtual bool is_character_cell () const
Return true iff this cell is a character cell.
virtual bool is_pointer_cell () const
Return true iff this cell is a pointer (to a sub-array) cell.
virtual bool is_lval_cell () const
Return true iff this cell is a pointer to a cell.
virtual bool is_picked_lval_cell () const
Return true iff this cell is a pointer to a cell from pick()
virtual bool is_complex_cell () const
Return true iff this cell is a complex number cell.
virtual bool is_numeric () const
Return true iff this cell is an integer, float, or complex cell.
virtual bool is_real_cell () const
Return true iff this cell is an integer or float cell.
virtual bool is_finite () const
Return true unless this cell contains infinity or NaN.
virtual bool is_example_field () const
Return true iff this cell is an example field character cell.
virtual bool is_member_anchor () const
Return true iff this is a PointerCell which pouints to a member value.
virtual CellType get_cell_type () const
return the type of this cell
virtual CellType get_cell_subtype () const
return the subtype of this cell. The subtype is the set of containers that can store the cell (only for Int and Char cells).
virtual const char * get_classname () const
return the name of the class
virtual ErrorCode bif_ceiling (Cell *Z) const
round the value of this Cell up and store the result in Z
virtual ErrorCode bif_conjugate (Cell *Z) const
conjugate the value of this Cell and store the result in Z
virtual ErrorCode bif_direction (Cell *Z) const
store the direction (sign) of this Cell in Z
virtual ErrorCode bif_exponential (Cell *Z) const
store e to the power of the value of this Cell in Z
virtual ErrorCode bif_factorial (Cell *Z) const
store the factorial (N!) of the value of this Cell in Z
virtual ErrorCode bif_floor (Cell *Z) const
Round the value of this Cell down and store the result in Z.
virtual ErrorCode bif_magnitude (Cell *Z) const
store the absolute value of this Cell in Z
virtual ErrorCode bif_nat_log (Cell *Z) const
store the base e logarithm of the value of this Cell in Z
virtual ErrorCode bif_negative (Cell *Z) const
store the negative of the value of this Cell in Z
virtual ErrorCode bif_not (Cell *Z) const
store the logical complement of the value of this Cell in Z
virtual ErrorCode bif_not_bitwise (Cell *Z) const
store the bitwise complement of the value of this Cell in Z
virtual ErrorCode bif_near_int64_t (Cell *Z) const
store the nearby integer of the value of this Cell in Z
virtual ErrorCode bif_within_quad_CT (Cell *Z) const
store the nearby integer of the value of this Cell in Z
virtual ErrorCode bif_pi_times (Cell *Z) const
store pi times the value of this Cell in Z
virtual ErrorCode bif_pi_times_inverse (Cell *Z) const
store pi times the value of this Cell in Z
virtual ErrorCode bif_reciprocal (Cell *Z) const
store the reciprocal of the value of this Cell in Z
virtual ErrorCode bif_roll (Cell *Z) const
store a random number between 1 and the value of this Cell in Z
virtual ErrorCode bif_add (Cell *Z, const Cell *A) const
store the sum of A and this cell in Z
virtual ErrorCode bif_and (Cell *Z, const Cell *A) const
store the logical and of A and this cell in Z
virtual ErrorCode bif_and_bitwise (Cell *Z, const Cell *A) const
store the bitwise and of A and this cell in Z
virtual ErrorCode bif_binomial (Cell *Z, const Cell *A) const
store the binomial (n over k) of A and this cell in Z
virtual ErrorCode bif_subtract (Cell *Z, const Cell *A) const
store the difference between A and this cell in Z
virtual ErrorCode bif_divide (Cell *Z, const Cell *A) const
store the quotient between A and this cell in Z
virtual Comp_result compare (const Cell &other) const
compare this with other, throw DOMAIN ERROR on illegal comparisons
ErrorCode bif_equal (Cell *Z, const Cell *A) const
store 1 in Z if A == the value of this cell in Z, else 0
virtual ErrorCode bif_equal_bitwise (Cell *Z, const Cell *A) const
bitwise comparison of *this and A
virtual ErrorCode bif_not_equal_bitwise (Cell *Z, const Cell *A) const
bitwise comparison of *this and A
ErrorCode bif_not_equal (Cell *Z, const Cell *A) const
store 1 in Z if A != the value of this cell in Z, else 0
ErrorCode bif_greater_than (Cell *Z, const Cell *A) const
store 1 in Z if A > the value of this cell in Z, else 0
ErrorCode bif_less_eq (Cell *Z, const Cell *A) const
store 1 in Z if A <= the value of this cell in Z, else 0
ErrorCode bif_less_than (Cell *Z, const Cell *A) const
store 1 in Z if A < the value of this cell in Z, else 0
ErrorCode bif_greater_eq (Cell *Z, const Cell *A) const
store 1 in Z if A is >= the value of this cell in Z, else 0
virtual ErrorCode bif_logarithm (Cell *Z, const Cell *A) const
store the base A logarithm of this cell in Z
virtual ErrorCode bif_maximum (Cell *Z, const Cell *A) const
store the larger of A and of this cell in Z
virtual ErrorCode bif_minimum (Cell *Z, const Cell *A) const
store the smaller of A and of this cell in Z
virtual ErrorCode bif_multiply (Cell *Z, const Cell *A) const
store the product of A and this cell in Z
virtual ErrorCode bif_nand (Cell *Z, const Cell *A) const
store the logical nand of A and this cell in Z
virtual ErrorCode bif_nand_bitwise (Cell *Z, const Cell *A) const
store the bitwise nand of A and this cell in Z
virtual ErrorCode bif_nor (Cell *Z, const Cell *A) const
store the logical NOR of A and this cell in Z
virtual ErrorCode bif_nor_bitwise (Cell *Z, const Cell *A) const
store the bitwise NOR of A and this cell in Z
virtual ErrorCode bif_or (Cell *Z, const Cell *A) const
store the logical OR of A and this cell in Z
virtual ErrorCode bif_or_bitwise (Cell *Z, const Cell *A) const
store the bitwise or of A and this cell in Z
virtual ErrorCode bif_power (Cell *Z, const Cell *A) const
store A to the power of this cell in Z
virtual ErrorCode bif_residue (Cell *Z, const Cell *A) const
store A modulo this cell in Z
virtual ErrorCode bif_circle_fun (Cell *Z, const Cell *A) const
store a circle function (according to A) of this cell in Z
virtual ErrorCode bif_circle_fun_inverse (Cell *Z, const Cell *A) const
store a circle function (according to A) of this cell in Z
virtual ErrorCode bif_add_inverse (Cell *Z, const Cell *A) const
the inverse of bif_add
virtual ErrorCode bif_multiply_inverse (Cell *Z, const Cell *A) const
the inverse of bif_bif_multiply
void * operator new (std::size_t, void *)
placement new
const void * get_u0 () const
raw pointer to the primary value (for 27 ⎕CR)
const void * get_u1 () const
raw pointer to the secondary value (for 28 ⎕CR)
Static Public Member Functions
static APL_Float mag2 (APL_Complex A)
the square of the magnitude (a² + b² for aJb)
static APL_Complex gamma (APL_Float x, const APL_Float &y)
the lanczos approximation for gamma(x + iy)
static ErrorCode do_bif_circle_fun (Cell *Z, int fun, APL_Complex b)
compute circle function fun
Static Public Member Functions inherited from NumericCell
static ErrorCode zV (Cell *Z, APL_Float flt)
initialize the (un-initialized) Cell *Z to (if possible) an IntCell or else to a FloatCell with value flt.
static ErrorCode zV (Cell *Z, APL_Complex cpx)
initialize the (un-initialized) Cell *Z to (if possible) an IntCell, a FloatCell, or a ComplexCell with value cpx.
static ErrorCode zV (Cell *Z, APL_Float real, APL_Float imag)
initialize the (un-initialized) Cell *Z to (if possible) an IntCell, a FloatCell, or a ComplexCell with value cpx.
Static Public Member Functions inherited from Cell
static bool A_greater_B (const Cell *const &A, const Cell *const &B, const void *unused_comp_arg)
like greater() but static
static bool same_half_plane (APL_Complex A, APL_Complex B)
ISO p.15: return true if A and B are on the same half-plane.
static bool tolerantly_equal (APL_Float A, APL_Float B, double qct)
ISO p.19: return true if real A is tolerantly equal to real B within C.
static bool tolerantly_equal (APL_Complex A, APL_Complex B, double qct)
ISO p. 19: return true if complex A and B are tolerantly equal within real qct.
static bool integral_within (APL_Float A, double qct)
ISO p. 19: A is integral (close to a Gaussian Integer) within qct.
static bool sum_overflow (APL_Integer z, APL_Integer a, APL_Integer b)
return true if z = a + b had an overflow.
static bool diff_overflow (APL_Integer z, APL_Integer a, APL_Integer b)
return true if z = a - b had an overflow.
static bool prod_overflow (int64_t a, int64_t b)
return true if multiplying a and b will (probably) overflow. For some huge a or b the result may incorrectly return true. a or b the result may incorrectly return true.
static void copy (Cell *&dst, const Cell *&src, ShapeItem count, Value &cell_owner)
copy (deep) count cells from src to dest)
static void copy (Value &val, const Cell *&src, ShapeItem count)
copy (deep) count cells from src to val (which is under construction))
static bool is_near_int (APL_Float value)
true iff value is close to an int (within +- qct)
static bool is_near_int64_t (APL_Float value)
true iff value is close to an int64_t (i.e. fots into an int64_t
static bool is_near_zero (APL_Float value)
true iff value is close to 0 (within +- qct)
static APL_Integer near_int (APL_Float value)
return value if it is close to int, or else throw DOMAIN_ERROR
static bool greater_cp (const ShapeItem &a, const ShapeItem &b, const void *cells)
compare cells[a] and cells[b] ascendingly
static bool smaller_cp (const ShapeItem &a, const ShapeItem &b, const void *cells)
compare cells[a] and cells[b] descendingly
static bool compare_stable (const Cell *const &A, const Cell *const &B, const void *comp_arg)
a stable compare function to be used with Heapsort. Equal cells are compared by their address. Return true iff A > B or A = B and &A > &B.
static bool compare_ptr (const Cell *const &A, const Cell *const &B, const void *comp_arg)
a stable compare function to be used with Heapsort. The cell contents are ignored and only the cell addresses are being compared. Return true iff &A > &B.
static ShapeItem * sorted_indices (const Cell *ravel, ShapeItem length, Sort_order order, ShapeItem comp_len)
return length indices i1, i2, ... iN so that ravel[i1] < ravel[i2] < ... < ravel[iN]. The indices are 0-based and the caller must delete[] the result. Returns 0 on error (= WS FULL).
static const char * get_cell_type_name (CellType ct)
the name of ct
Protected Member Functions
APL_Complex cval () const
return the complex value of this cell
virtual CellType get_cell_type () const
overloaded Cell::get_cell_type().
virtual APL_Float get_real_value () const
overloaded Cell::get_real_value().
virtual APL_Float get_imag_value () const
overloaded Cell::get_imag_value().
virtual APL_Complex get_complex_value () const
overloaded Cell::get_complex_value()
virtual bool get_near_bool () const
overloaded Cell::get_near_bool()
virtual APL_Integer get_near_int () const
overloaded Cell::get_near_int()
virtual APL_Integer get_checked_near_int () const
overloaded Cell::get_checked_near_int()
virtual bool is_near_int () const
overloaded Cell::is_near_int()
virtual bool is_near_int64_t () const
overloaded Cell::is_near_int64_t()
virtual ErrorCode bif_near_int64_t (Cell *Z) const
overloaded Cell::bif_near_int64_t()
virtual ErrorCode bif_within_quad_CT (Cell *Z) const
overloaded Cell::bif_within_quad_CT()
virtual bool is_near_zero () const
overloaded Cell::is_near_zero()
virtual bool is_near_one () const
overloaded Cell::is_near_one()
virtual bool is_near_real () const
overloaded Cell::is_near_real()
virtual const char * get_classname () const
overloaded Cell::get_classname()
virtual int CDR_size () const
overloaded Cell::CDR_size()
Protected Member Functions inherited from NumericCell
virtual bool is_numeric () const
overloaded Cell::is_numeric()
virtual ErrorCode bif_not (Cell *Z) const
overloaded Cell::bif_not()
virtual ErrorCode bif_not_bitwise (Cell *Z) const
overloaded Cell::bif_not_bitwise()
virtual ErrorCode bif_and (Cell *Z, const Cell *A) const
overloaded Cell::bif_and()
virtual ErrorCode bif_and_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_and_bitwise()
virtual ErrorCode bif_equal_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_equal_bitwise()
virtual ErrorCode bif_not_equal_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_not_equal_bitwise()
virtual ErrorCode bif_binomial (Cell *Z, const Cell *A) const
overloaded Cell::bif_binomial()
virtual ErrorCode bif_nand (Cell *Z, const Cell *A) const
overloaded Cell::bif_nand()
virtual ErrorCode bif_nand_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_nand_bitwise()
virtual ErrorCode bif_nor (Cell *Z, const Cell *A) const
overloaded Cell::bif_nor()
virtual ErrorCode bif_nor_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_nor_bitwise()
virtual ErrorCode bif_or (Cell *Z, const Cell *A) const
overloaded Cell::bif_or()
virtual ErrorCode bif_or_bitwise (Cell *Z, const Cell *A) const
overloaded Cell::bif_or_bitwise()
virtual const char * get_classname () const
overloaded Cell::get_classname()
ErrorCode complex_binomial (Cell *Z, const Cell *A) const
N over K for complex A and/or B.
ErrorCode real_binomial (Cell *Z, const Cell *A) const
N over K for non-integer A and/or B.
Static Protected Member Functions
static ErrorCode zC (Cell *Z, APL_Float r, APL_Float j)
initialize the (un-initialized) Cell *Z to complex r + ij
static ErrorCode zC (Cell *Z, APL_Complex cpx)
initialize the (un-initialized) Cell *Z to complex cpx
static APL_Complex ONE ()
1.0
static APL_Complex PLUS_i ()
i
static APL_Complex MINUS_i ()
-i
Static Protected Member Functions inherited from NumericCell
static ErrorCode K33_binomial (Cell *Z, APL_Integer N, APL_Integer K, bool negate)
compute binomial funtion for integers a and b
static ErrorCode int_gcd (APL_Integer &z, APL_Integer a, APL_Integer b)
return the greatest common divisor of integers a and b
static ErrorCode flt_gcd (APL_Float &z, APL_Float a, APL_Float b, double qct)
return the greatest common divisor of real a and b
static ErrorCode integer_binomial (Cell *Z, APL_Integer N, APL_Integer K, bool negate)
N over K for positive integers N and K.
static ErrorCode cpx_gcd (APL_Complex &z, APL_Complex a, APL_Complex b, double qct)
return the greatest common divisor of complex a and b
static APL_Complex cpx_max_real (APL_Complex a)
multiply a by 1, -1, i, or -i so that a.real is maximal
Friends
class IntCell
class FloatCell
class NumericCell
class RealCell
class Value
Additional Inherited Members
Protected Attributes inherited from Cell
SomeValue value
the primary value of this cell
Detailed Description
A cell containing one complex number.
A cell containing a single APL complex value. This class essentially overloads certain functions in class Cell with complex number specific implementations.
Definition at line 34 of file ComplexCell.hh.
Constructor & Destructor Documentation
ComplexCell() [1/2]
ComplexCell::ComplexCell (APL_Complex c)
Construct an complex number cell from a complex number.
Definition at line 39 of file ComplexCell.cc.
References Cell::SomeValue::cval, and Cell::value.
ComplexCell() [2/2]
ComplexCell::ComplexCell (APL_Float r, APL_Float i)
Construct an complex number cell from real part r and imag part i.
Definition at line 45 of file ComplexCell.cc.
References Cell::SomeValue::cval, and Cell::value.
Member Function Documentation
bif_add()
ErrorCode ComplexCell::bif_add (Cell * Z, const Cell * A) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 322 of file ComplexCell.cc.
References get_complex_value(), and zC().
bif_add_inverse()
ErrorCode ComplexCell::bif_add_inverse (Cell * Z, const Cell * A) const virtual
overloaded Cell::bif_add_inverse()
Reimplemented from Cell.
Definition at line 328 of file ComplexCell.cc.
bif_ceiling()
ErrorCode ComplexCell::bif_ceiling (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 261 of file ComplexCell.cc.
References Cell::SomeValue::cval, Cell::value, and NumericCell::zV().
bif_circle_fun()
ErrorCode ComplexCell::bif_circle_fun (Cell * Z, const Cell * A) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 542 of file ComplexCell.cc.
References cval(), do_bif_circle_fun(), Cell::is_finite(), and IntCell::z0().
bif_circle_fun_inverse()
ErrorCode ComplexCell::bif_circle_fun_inverse (Cell * Z, const Cell * A) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 555 of file ComplexCell.cc.
References cval(), do_bif_circle_fun(), Cell::is_finite(), and IntCell::z0().
bif_conjugate()
ErrorCode ComplexCell::bif_conjugate (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 183 of file ComplexCell.cc.
References cval(), and zC().
bif_direction()
ErrorCode ComplexCell::bif_direction (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 195 of file ComplexCell.cc.
References cval(), get_imag_value(), get_real_value(), IntCell::z0(), and zC().
bif_divide()
ErrorCode ComplexCell::bif_divide (Cell * Z, const Cell * A) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 356 of file ComplexCell.cc.
References cval(), get_complex_value(), IntCell::z1(), and zC().
bif_equal()
ErrorCode ComplexCell::bif_equal (Cell * Z, const Cell * A) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Definition at line 449 of file ComplexCell.cc.
References get_complex_value(), Workspace::get_CT(), get_imag_value(), get_real_value(), IntCell::z0(), and IntCell::z1().
bif_exponential()
ErrorCode ComplexCell::bif_exponential (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 308 of file ComplexCell.cc.
References cval(), and zC().
Referenced by RealCell::do_bif_circle_fun(), and do_bif_circle_fun().
bif_factorial()
ErrorCode ComplexCell::bif_factorial (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 168 of file ComplexCell.cc.
References FloatCell::bif_factorial(), gamma(), get_imag_value(), get_real_value(), is_near_real(), and zC().
bif_floor()
ErrorCode ComplexCell::bif_floor (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 281 of file ComplexCell.cc.
References Cell::SomeValue::cval, Workspace::get_CT(), Cell::value, and NumericCell::zV().
bif_logarithm()
ErrorCode ComplexCell::bif_logarithm (Cell * Z, const Cell * A) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 507 of file ComplexCell.cc.
References cval(), Cell::SomeValue::cval, get_imag_value(), get_real_value(), Cell::value, IntCell::z1(), and zC().
bif_magnitude()
ErrorCode ComplexCell::bif_magnitude (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 204 of file ComplexCell.cc.
References cval(), and FloatCell::zF().
bif_maximum()
ErrorCode ComplexCell::bif_maximum (Cell * Z, const Cell * A) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 401 of file ComplexCell.cc.
References get_real_value(), is_near_real(), FloatCell::zF(), and IntCell::zI().
bif_minimum()
ErrorCode ComplexCell::bif_minimum (Cell * Z, const Cell * A) const virtual
Overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 425 of file ComplexCell.cc.
References get_real_value(), is_near_real(), FloatCell::zF(), and IntCell::zI().
bif_multiply()
ErrorCode ComplexCell::bif_multiply (Cell * Z, const Cell * A) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 340 of file ComplexCell.cc.
References cval(), and zC().
bif_multiply_inverse()
ErrorCode ComplexCell::bif_multiply_inverse (Cell * Z, const Cell * A) const virtual
overloaded Cell::bif_multiply_inverse()
Reimplemented from Cell.
Definition at line 350 of file ComplexCell.cc.
bif_nat_log()
ErrorCode ComplexCell::bif_nat_log (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 314 of file ComplexCell.cc.
References cval(), and zC().
bif_near_int64_t()
ErrorCode ComplexCell::bif_near_int64_t (Cell * Z) const protected virtual
overloaded Cell::bif_near_int64_t()
Reimplemented from Cell.
Definition at line 78 of file ComplexCell.cc.
References Cell::SomeValue::cval, is_near_int64_t(), Cell::value, zC(), and FloatCell::zF().
bif_negative()
ErrorCode ComplexCell::bif_negative (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 189 of file ComplexCell.cc.
References cval(), and zC().
bif_pi_times()
ErrorCode ComplexCell::bif_pi_times (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 246 of file ComplexCell.cc.
References Cell::SomeValue::cval, Cell::value, and zC().
bif_pi_times_inverse()
ErrorCode ComplexCell::bif_pi_times_inverse (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 254 of file ComplexCell.cc.
References Cell::SomeValue::cval, Cell::value, and zC().
bif_power()
ErrorCode ComplexCell::bif_power (Cell * Z, const Cell * A) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 477 of file ComplexCell.cc.
References cval(), IntCell::z0(), IntCell::z1(), and zC().
bif_reciprocal()
ErrorCode ComplexCell::bif_reciprocal (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 210 of file ComplexCell.cc.
References Cell::SomeValue::cval, is_near_real(), is_near_zero(), mag2(), Cell::value, zC(), and FloatCell::zF().
bif_residue()
ErrorCode ComplexCell::bif_residue (Cell * Z, const Cell * A) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 369 of file ComplexCell.cc.
References Cell::bif_add(), Cell::bif_divide(), Cell::bif_equal(), Cell::bif_floor(), Cell::bif_multiply(), Cell::bif_subtract(), get_complex_value(), IntCell::z0(), and zC().
Referenced by Bif_F12_ENCODE::encode_Cpx().
bif_roll()
ErrorCode ComplexCell::bif_roll (Cell * Z) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 233 of file ComplexCell.cc.
References get_checked_near_int(), Workspace::get_IO(), Workspace::get_RL(), is_near_int(), and IntCell::zI().
bif_subtract()
ErrorCode ComplexCell::bif_subtract (Cell * Z, const Cell * A) const virtual
overloaded from the corresponding Cell:: function (see class Cell).
Reimplemented from Cell.
Definition at line 334 of file ComplexCell.cc.
References get_complex_value(), and zC().
bif_within_quad_CT()
ErrorCode ComplexCell::bif_within_quad_CT (Cell * Z) const protected virtual
overloaded Cell::bif_within_quad_CT()
Reimplemented from Cell.
Definition at line 95 of file ComplexCell.cc.
References Cell::SomeValue::cval, Workspace::get_CT(), Cell::value, and zC().
CDR_size()
virtual int ComplexCell::CDR_size () const inline protected virtual
overloaded Cell::CDR_size()
Reimplemented from Cell.
Definition at line 247 of file ComplexCell.hh.
character_representation()
PrintBuffer ComplexCell::character_representation (const PrintContext & pctx) const virtual
the Quad_CR representation of this cell.
Reimplemented from Cell.
Definition at line 869 of file ComplexCell.cc.
References UCS_string::append(), FloatCell::character_representation(), Cell::SomeValue::cval, ColInfo::flags, ColInfo::fract_len, PrintBuffer::get_info(), PrintContext::get_PP(), PrintContext::get_scaled(), ColInfo::imag_len, ColInfo::int_len, is_near_real(), PrintBuffer::pad_l(), ColInfo::real_len, UCS_string::size(), and Cell::value.
compare()
Comp_result ComplexCell::compare (const Cell & other) const virtual
overloaded Cell::compare()
Reimplemented from Cell.
Definition at line 843 of file ComplexCell.cc.
References equal(), Workspace::get_CT(), Cell::get_imag_value(), get_imag_value(), Cell::get_real_value(), get_real_value(), Cell::is_character_cell(), Cell::is_numeric(), Cell::is_pointer_cell(), and Cell::tolerantly_equal().
Referenced by greater().
cval()
APL_Complex ComplexCell::cval () const inline protected
return the complex value of this cell
Definition at line 184 of file ComplexCell.hh.
References Cell::SomeValue::cval, and Cell::value.
Referenced by bif_circle_fun(), bif_circle_fun_inverse(), bif_conjugate(), bif_direction(), bif_divide(), bif_exponential(), bif_logarithm(), bif_magnitude(), bif_multiply(), bif_nat_log(), bif_negative(), bif_power(), and get_complex_value().
do_bif_circle_fun()
ErrorCode ComplexCell::do_bif_circle_fun (Cell * Z, int fun, APL_Complex b) static
compute circle function fun
Definition at line 589 of file ComplexCell.cc.
References bif_exponential(), do_bif_circle_fun(), Cell::get_complex_value(), Cell::is_near_zero(), mag2(), MINUS_i(), ONE(), and zC().
Referenced by bif_circle_fun(), bif_circle_fun_inverse(), RealCell::do_bif_circle_fun(), and do_bif_circle_fun().
equal()
bool ComplexCell::equal (const Cell & other, double qct) const virtual
overloaded Cell::equal().
Reimplemented from Cell.
Definition at line 159 of file ComplexCell.cc.
References get_complex_value(), and Cell::tolerantly_equal().
Referenced by compare().
gamma()
APL_Complex ComplexCell::gamma (APL_Float x, const APL_Float & y) static
the lanczos approximation for gamma(x + iy)
Definition at line 734 of file ComplexCell.cc.
References gamma().
Referenced by bif_factorial(), NumericCell::complex_binomial(), and gamma().
get_cell_type()
virtual CellType ComplexCell::get_cell_type () const inline protected virtual
overloaded Cell::get_cell_type().
Reimplemented from Cell.
Definition at line 197 of file ComplexCell.hh.
get_checked_near_int()
virtual APL_Integer ComplexCell::get_checked_near_int () const inline protected virtual
overloaded Cell::get_checked_near_int()
Reimplemented from Cell.
Definition at line 216 of file ComplexCell.hh.
References Cell::SomeValue::cval, and Cell::value.
Referenced by bif_roll().
get_classname()
virtual const char * ComplexCell::get_classname () const inline protected virtual
overloaded Cell::get_classname()
Reimplemented from NumericCell.
Definition at line 244 of file ComplexCell.hh.
get_complex_value()
virtual APL_Complex ComplexCell::get_complex_value () const inline protected virtual
overloaded Cell::get_complex_value()
Reimplemented from Cell.
Definition at line 207 of file ComplexCell.hh.
References cval().
Referenced by bif_add(), bif_divide(), bif_equal(), bif_residue(), bif_subtract(), and equal().
get_imag_value()
APL_Float ComplexCell::get_imag_value () const protected virtual
overloaded Cell::get_imag_value().
Reimplemented from Cell.
Definition at line 58 of file ComplexCell.cc.
References Cell::SomeValue::cval, and Cell::value.
Referenced by bif_direction(), bif_equal(), bif_factorial(), bif_logarithm(), and compare().
get_near_bool()
bool ComplexCell::get_near_bool () const protected virtual
overloaded Cell::get_near_bool()
Reimplemented from Cell.
Definition at line 790 of file ComplexCell.cc.
References Cell::SomeValue::cval, and Cell::value.
get_near_int()
APL_Integer ComplexCell::get_near_int () const protected virtual
overloaded Cell::get_near_int()
Reimplemented from Cell.
Definition at line 809 of file ComplexCell.cc.
References Cell::SomeValue::cval, and Cell::value.
get_real_value()
APL_Float ComplexCell::get_real_value () const protected virtual
overloaded Cell::get_real_value().
Reimplemented from Cell.
Definition at line 52 of file ComplexCell.cc.
References Cell::SomeValue::cval, and Cell::value.
Referenced by bif_direction(), bif_equal(), bif_factorial(), bif_logarithm(), bif_maximum(), bif_minimum(), and compare().
greater()
bool ComplexCell::greater (const Cell & other) const virtual
overloaded Cell::greater().
Reimplemented from Cell.
Definition at line 824 of file ComplexCell.cc.
References compare(), and Cell::get_cell_type().
init_other()
virtual void ComplexCell::init_other (void * other, Value & cell_owner, const char * loc) const inline virtual
overloaded Cell::init_other
Reimplemented from Cell.
Definition at line 50 of file ComplexCell.hh.
References Cell::SomeValue::cval, and Cell::value.
is_complex_cell()
virtual bool ComplexCell::is_complex_cell () const inline virtual
overloaded Cell::is_complex_cell().
Reimplemented from Cell.
Definition at line 54 of file ComplexCell.hh.
is_finite()
virtual bool ComplexCell::is_finite () const inline virtual
Overloaded Cell::is_finite().
Reimplemented from Cell.
Definition at line 57 of file ComplexCell.hh.
References Cell::SomeValue::cval, and Cell::value.
is_near_int()
bool ComplexCell::is_near_int () const protected virtual
overloaded Cell::is_near_int()
Reimplemented from Cell.
Definition at line 64 of file ComplexCell.cc.
References Cell::SomeValue::cval, Cell::is_near_int(), and Cell::value.
Referenced by bif_roll().
is_near_int64_t()
bool ComplexCell::is_near_int64_t () const protected virtual
overloaded Cell::is_near_int64_t()
Reimplemented from Cell.
Definition at line 71 of file ComplexCell.cc.
References Cell::SomeValue::cval, Cell::is_near_int64_t(), and Cell::value.
Referenced by bif_near_int64_t().
is_near_one()
bool ComplexCell::is_near_one () const protected virtual
overloaded Cell::is_near_one()
Reimplemented from Cell.
Definition at line 137 of file ComplexCell.cc.
References Cell::SomeValue::cval, and Cell::value.
is_near_real()
bool ComplexCell::is_near_real () const protected virtual
overloaded Cell::is_near_real()
Reimplemented from Cell.
Definition at line 147 of file ComplexCell.cc.
References Cell::SomeValue::cval, and Cell::value.
Referenced by bif_factorial(), bif_maximum(), bif_minimum(), bif_reciprocal(), character_representation(), and need_scaling().
is_near_zero()
bool ComplexCell::is_near_zero () const protected virtual
overloaded Cell::is_near_zero()
Reimplemented from Cell.
Definition at line 127 of file ComplexCell.cc.
References Cell::SomeValue::cval, and Cell::value.
Referenced by bif_reciprocal().
mag2() [1/2]
APL_Float ComplexCell::mag2 () const inline
the square of the magnitude of aJb (= a² + b²)
Definition at line 157 of file ComplexCell.hh.
References Cell::SomeValue::cval, and Cell::value.
Referenced by IntCell::bif_power(), bif_reciprocal(), and do_bif_circle_fun().
mag2() [2/2]
static APL_Float ComplexCell::mag2 (APL_Complex A) inline static
the square of the magnitude (a² + b² for aJb)
Definition at line 161 of file ComplexCell.hh.
MINUS_i()
static APL_Complex ComplexCell::MINUS_i () inline static protected
-i
Definition at line 194 of file ComplexCell.hh.
Referenced by do_bif_circle_fun().
need_scaling()
bool ComplexCell::need_scaling (const PrintContext & pctx) const virtual
return true iff this cell needs scaling (exponential format) in pctx.
Reimplemented from Cell.
Definition at line 957 of file ComplexCell.cc.
References Cell::SomeValue::cval, PrintContext::get_PP(), is_near_real(), FloatCell::need_scaling(), and Cell::value.
ONE()
static APL_Complex ComplexCell::ONE () inline static protected
1.0
Definition at line 188 of file ComplexCell.hh.
Referenced by do_bif_circle_fun().
PLUS_i()
static APL_Complex ComplexCell::PLUS_i () inline static protected
i
Definition at line 191 of file ComplexCell.hh.
zC() [1/2]
static ErrorCode ComplexCell::zC (Cell * Z, APL_Complex cpx) inline static protected
initialize the (un-initialized) Cell *Z to complex cpx
Definition at line 180 of file ComplexCell.hh.
zC() [2/2]
static ErrorCode ComplexCell::zC (Cell * Z, APL_Float r, APL_Float j) inline static protected
initialize the (un-initialized) Cell *Z to complex r + ij
Definition at line 175 of file ComplexCell.hh.
Referenced by bif_add(), NumericCell::bif_and(), bif_conjugate(), bif_direction(), bif_divide(), FloatCell::bif_divide(), bif_exponential(), bif_factorial(), bif_logarithm(), RealCell::bif_logarithm(), bif_multiply(), FloatCell::bif_multiply(), bif_nat_log(), FloatCell::bif_nat_log(), IntCell::bif_nat_log(), bif_near_int64_t(), bif_negative(), NumericCell::bif_or(), bif_pi_times(), bif_pi_times_inverse(), bif_power(), FloatCell::bif_power(), IntCell::bif_power(), bif_reciprocal(), bif_residue(), bif_subtract(), FloatCell::bif_subtract(), bif_within_quad_CT(), NumericCell::complex_binomial(), RealCell::do_bif_circle_fun(), and do_bif_circle_fun().
Friends And Related Function Documentation
FloatCell
friend class FloatCell friend
Definition at line 37 of file ComplexCell.hh.
IntCell
friend class IntCell friend
Definition at line 36 of file ComplexCell.hh.
NumericCell
friend class NumericCell friend
Definition at line 38 of file ComplexCell.hh.
RealCell
friend class RealCell friend
Definition at line 39 of file ComplexCell.hh.
Value
friend class Value friend
Definition at line 40 of file ComplexCell.hh.
The documentation for this class was generated from the following files:
src/ComplexCell.hh
src/ComplexCell.cc