GNU APL: CPU_pool Class Reference
CPU_pool Class Reference
#include <Parallel.hh>
Public Member Functions
CPU_pool ()
constructor
Static Public Member Functions
static void init (bool logit)
initialize the pool
static void add_CPU (CPU_Number cpu)
add a CPU to the pool
static CPU_Number get_CPU (size_t idx)
get the idx;th CPU
static CoreCount get_count ()
get the number of (active) CPUs
static void resize (CoreCount new_size)
resize the pool
static bool change_core_count (CoreCount new_count, bool logit)
set new active core count, return true on error
static void lock_pool (bool logit)
make all pool members lock on their pool_sema
static void unlock_pool (bool logit)
unlock all pool members from their pool_sema
Static Protected Attributes
static std::vector< CPU_Number > the_CPUs
the CPU numbers that can be used
Detailed Description
Multi-core GNU APL uses a pool of threads numbered 0, 1, ... core_count()-1
(master-) thread 0 is the interpreter (which also performs parallel work), while (worker-) threads 1 ... are only activated when some parallel work is available.
The worker threads 1... are either working, or busy-waiting for work, or blocked on a semaphore:
   init
    ↓
 blocked ←→ busy-waiting ←→ working
The transitions
blocked ←→ busy-waiting
occur before and after the master thread waits for terminal input or when the number of cores is being changed (with ⎕SYL[26;2]). The workers are blocked while the master thread waits for terminal input. The reason for this is that a busy-waiting worker is consuming power for no reason (to the extent that the CPU fan turns on even though there is no useful work in sight).
The transitions
  busy-waiting ←→ working
occurs when the execution of APL primitives, primarily scalar functions, suggests to execute in parallel (i.e. if the vectors involved are sufficiently long). The set of CPUs (= hyper-threads) over which the computational load is being distrinuted.
Definition at line 210 of file Parallel.hh.
Member Function Documentation
add_CPU()
static void CPU_pool::add_CPU (CPU_Number cpu) inline static
add a CPU to the pool
Definition at line 220 of file Parallel.hh.
References the_CPUs.
Referenced by Parallel::init().
change_core_count()
bool CPU_pool::change_core_count (CoreCount new_count, bool logit) static
set new active core count, return true on error
Definition at line 125 of file Parallel.cc.
References Thread_context::get_active_core_count(), Thread_context::get_context(), get_count(), Thread_context::get_master(), Thread_context::job_number, lock_pool(), Thread_context::print_all(), Parallel::run_parallel, Thread_context::set_active_core_count(), and unlock_pool().
Referenced by Quad_SYL::assign_indexed(), and Parallel::init().
get_count()
static CoreCount CPU_pool::get_count () inline static
get the number of (active) CPUs
Definition at line 228 of file Parallel.hh.
References the_CPUs.
Referenced by change_core_count(), and Parallel::init().
get_CPU()
static CPU_Number CPU_pool::get_CPU (size_t idx) inline static
get the idx;th CPU
Definition at line 224 of file Parallel.hh.
References the_CPUs.
Referenced by Parallel::init().
init()
void CPU_pool::init (bool logit) static
initialize the pool
Definition at line 307 of file Parallel.cc.
lock_pool()
void CPU_pool::lock_pool (bool logit) static
make all pool members lock on their pool_sema
Definition at line 316 of file Parallel.cc.
Referenced by change_core_count(), and InputMux::get_line().
resize()
static void CPU_pool::resize (CoreCount new_size) inline static
resize the pool
Definition at line 232 of file Parallel.hh.
References the_CPUs.
unlock_pool()
void CPU_pool::unlock_pool (bool logit) static
unlock all pool members from their pool_sema
Definition at line 332 of file Parallel.cc.
Referenced by change_core_count(), and InputMux::get_line().
Member Data Documentation
the_CPUs
std::vector< CPU_Number > CPU_pool::the_CPUs static protected
the CPU numbers that can be used
Definition at line 246 of file Parallel.hh.
Referenced by add_CPU(), get_count(), get_CPU(), and resize().
The documentation for this class was generated from the following files:
src/Parallel.hh
src/Parallel.cc
src/static_Objects.cc