GNU APL: SymbolTable Class Reference
SymbolTable Class Reference
The table containing all user defined symbols.
#include <SymbolTable.hh>
Public Member Functions
Symbol * lookup_symbol (const UCS_string &ucs)
Return or create a Symbol with name ucs in this SymbolTable.
UCS_string find_lambda_name (const UserFunction *lambda)
return the name to which lambda ia assigned (empty if not found)
void list (ostream &out, ListCategory which, UCS_string from_to) const
List all symbols in this SymbolTable (for)VARS,)FNS etc.)
void unmark_all_values () const
clear the marked flag of all symbols
int show_owners (ostream &out, const Value &value) const
print variables owning value
void clear (ostream &out)
clear this symbol table (remove all user-defined symbols)
void clear_slot (ostream &out, int hash)
clear one slot (hash) in this symbol table
void erase_symbols (ostream &out, const UCS_string_vector &symbols)
erase symbols from this SymbolTable
ostream & list_symbol (ostream &out, const UCS_string &buf) const
List details of single symbol in buf.
void write_all_symbols (FILE *out, uint64_t &seq) const
write all symbols in)OUT format to file out
std::vector< const Symbol * > get_all_symbols () const
return all symbols (including erased symbols)
void dump (ostream &out, int &fcount, int &vcount) const
dump symbols to out
Public Member Functions inherited from SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >
SymbolTableBase ()
Construct an empty SymbolTable.
Symbol * lookup_existing_symbol (const UCS_string &name)
return a Symbol with name name in this SymbolTable.
const Symbol * lookup_existing_symbol (const UCS_string &name) const
return a Symbol with name name in this SymbolTable.
UCS_string find_lambda_name (const UserFunction *lambda)
return the name to which lambda ia assigned (empty if not found)
void add_symbol (Symbol *sym)
add sym to the symbol table. The caller has checked that new_name does not yet exist in the symbol table
Protected Member Functions
bool erase_one_symbol (const UCS_string &sym)
erase one symbol, return true on error, false on success
Additional Inherited Members
Public Types inherited from SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >
enum
Static Public Member Functions inherited from SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >
static uint32_t compute_hash (const UCS_string &name)
compute a 16-bit hash for name
Protected Attributes inherited from SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >
Symbol * symbol_table [SYMBOL_COUNT]
Hash table for all symbols.
Detailed Description
The table containing all user defined symbols.
Definition at line 129 of file SymbolTable.hh.
Member Function Documentation
clear()
void SymbolTable::clear (ostream & out)
clear this symbol table (remove all user-defined symbols)
Definition at line 305 of file SymbolTable.cc.
References clear_slot(), and Workspace::SI_entry_count().
Referenced by Workspace::clear_WS().
clear_slot()
void SymbolTable::clear_slot (ostream & out, int hash)
clear one slot (hash) in this symbol table
Definition at line 315 of file SymbolTable.cc.
References Symbol::call_monitor_callback(), Symbol::get_name(), NamedObject::is_user_defined(), Symbol::next, and SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >::symbol_table.
Referenced by clear().
dump()
void SymbolTable::dump (ostream & out, int & fcount, int & vcount) const
dump symbols to out
Definition at line 458 of file SymbolTable.cc.
References Symbol::dump(), ValueStackItem::get_NC(), Symbol::next, and SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >::symbol_table.
Referenced by Workspace::dump_WS().
erase_one_symbol()
bool SymbolTable::erase_one_symbol (const UCS_string & sym) protected
erase one symbol, return true on error, false on success
Definition at line 343 of file SymbolTable.cc.
References ValueStackItem::clear_function(), Symbol::clear_vs(), UCS_string::contains(), Symbol::expunge(), ValueStackItem::get_function(), ValueStackItem::get_NC(), Workspace::is_called(), Symbol::is_erased(), SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >::lookup_existing_symbol(), Workspace::oldest_exec(), and Symbol::value_stack.
Referenced by erase_symbols().
erase_symbols()
void SymbolTable::erase_symbols (ostream & out, const UCS_string_vector & symbols)
erase symbols from this SymbolTable
Definition at line 286 of file SymbolTable.cc.
References erase_one_symbol().
Referenced by Workspace::erase_symbols().
find_lambda_name()
UCS_string SymbolTable::find_lambda_name (const UserFunction * lambda)
return the name to which lambda ia assigned (empty if not found)
Definition at line 88 of file SymbolTable.cc.
References Symbol::next, and SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >::symbol_table.
Referenced by Workspace::find_lambda_name().
get_all_symbols()
std::vector< const Symbol * > SymbolTable::get_all_symbols () const
return all symbols (including erased symbols)
Definition at line 441 of file SymbolTable.cc.
References Symbol::next, and SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >::symbol_table.
Referenced by Doxy::gen(), Workspace::get_all_symbols(), and XML_Saving_Archive::save_symtab().
list()
void SymbolTable::list (ostream & out, ListCategory which, UCS_string from_to) const
List all symbols in this SymbolTable (for)VARS,)FNS etc.)
Definition at line 130 of file SymbolTable.cc.
References UCS_string::append(), UCS_string::append_number(), UCS_string_vector::compute_column_width(), UCS_string::lexical_before(), list(), Symbol::next, Command::parse_from_to(), UCS_string::size(), UCS_string_vector::sort(), and SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >::symbol_table.
Referenced by Workspace::list(), and list().
list_symbol()
ostream & SymbolTable::list_symbol (ostream & out, const UCS_string & buf) const
List details of single symbol in buf.
Definition at line 103 of file SymbolTable.cc.
References Workspace::lookup_existing_symbol(), Symbol::print_verbose(), UCS_string::remove_leading_and_trailing_whitespaces(), and UCS_string::size().
Referenced by Workspace::list_symbol().
lookup_symbol()
Symbol * SymbolTable::lookup_symbol (const UCS_string & ucs)
Return or create a Symbol with name ucs in this SymbolTable.
Definition at line 41 of file SymbolTable.cc.
References SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >::add_symbol(), SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >::compute_hash(), Avec::is_quad(), Symbol::next, UCS_string::size(), and SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >::symbol_table.
Referenced by Workspace::lookup_symbol().
show_owners()
int SymbolTable::show_owners (ostream & out, const Value & value) const
print variables owning value
Definition at line 260 of file SymbolTable.cc.
References Symbol::next, and SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >::symbol_table.
Referenced by Workspace::show_owners().
unmark_all_values()
void SymbolTable::unmark_all_values () const
clear the marked flag of all symbols
Definition at line 248 of file SymbolTable.cc.
References Symbol::next, and SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >::symbol_table.
Referenced by Workspace::unmark_all_values().
write_all_symbols()
void SymbolTable::write_all_symbols (FILE * out, uint64_t & seq) const
write all symbols in)OUT format to file out
Definition at line 274 of file SymbolTable.cc.
References Symbol::next, and SymbolTableBase< Symbol, SYMBOL_HASH_TABLE_SIZE >::symbol_table.
Referenced by Workspace::write_OUT().
The documentation for this class was generated from the following files:
src/SymbolTable.hh
src/SymbolTable.cc