GNU APL: Token_string Class Reference
Token_string Class Reference
A sequence of Token.
#include <Token.hh>
Public Member Functions
Token_string ()
construct an empty string
Token_string (const Token *data, ShapeItem len)
construct a string of len Token, starting at data.
Token_string (const Token_string &other, uint32_t pos, uint32_t len)
construct a string of len Token from another token string
void reverse_from_to (ShapeItem from, ShapeItem to)
reversde the token order from from to to (including)
void print (ostream &out, bool details) const
print this token string
Private Member Functions
Token_string & operator= (const Token_string &other)
prevent accidental copying
Detailed Description
A sequence of Token.
Definition at line 320 of file Token.hh.
Constructor & Destructor Documentation
Token_string() [1/3]
Token_string::Token_string () inline
construct an empty string
Definition at line 324 of file Token.hh.
Token_string() [2/3]
Token_string::Token_string (const Token * data, ShapeItem len) inline
construct a string of len Token, starting at data.
Definition at line 327 of file Token.hh.
Token_string() [3/3]
Token_string::Token_string (const Token_string & other, uint32_t pos, uint32_t len) inline
construct a string of len Token from another token string
Definition at line 331 of file Token.hh.
Member Function Documentation
print()
void Token_string::print (ostream & out, bool details) const
print this token string
Definition at line 856 of file Token.cc.
References Token::get_flt_val(), and Token::get_ValueType().
Referenced by Parser::collect_constants(), Parser::collect_groups(), Parser::create_value(), Parser::create_vector_value(), Parser::parse(), Executable::parse_body_line(), Parser::parse_statement(), Executable::print_token(), Quad_TF::tf2_inverse(), and Quad_TF::tf2_reduce().
reverse_from_to()
void Token_string::reverse_from_to (ShapeItem from, ShapeItem to)
reversde the token order from from to to (including)
Definition at line 844 of file Token.cc.
References Token::Hswap().
Referenced by Executable::reverse_statement_token().
The documentation for this class was generated from the following files:
src/Token.hh
src/Token.cc