GNU APL: XML_Saving_Archive Class Reference
XML_Saving_Archive Class Reference
a helper class for saving an APL workspace
#include <Archive.hh>
Classes
struct _val_par
a value and its parent (if the parent is nested)
Public Types
enum Vid { INVALID_VID = -1 }
an index for values
Public Member Functions
XML_Saving_Archive (ofstream &of)
constructor: remember output stream and workspace
~XML_Saving_Archive ()
destructor
void save_Function (const Function &fun)
write user-defined function fun
int save_Function_name (const Function &fun)
write either the name and SI-level of user-defined function or the id of a system function. Return number of attribute= items written
void save_Parser (const StateIndicator &si)
write the Prefix parser of si (and its derived functions)
void save_Derived (const DerivedFunctionCache &fns)
write derived functions cache
void save_Symbol (const Symbol &sym)
write Symbol sym
void save_functions ()
write all function
void save_user_commands (const std::vector< Command::user_command > &cmds)
write all user defined commands
void save_symtab (const SymbolTable &symtab)
write SymbolTable symtab
void save_SI_entry (const StateIndicator &si)
write StateIndicator entry si
void save_token_loc (const Token_loc &tloc)
write Token_loc tloc
void save_vstack_item (const ValueStackItem &vsi)
write ValueStackItem vsi
void save_UCS (const UCS_string &str)
write UCS_string str
XML_Saving_Archive & save_shape (Vid vid)
write Value v except its ravel
XML_Saving_Archive & save_Ravel (Vid vid)
write ravel of Value v
XML_Saving_Archive & save ()
write entire workspace
Protected Types
enum { INDENT_LEN = 2 }
width of one indentation level
Protected Types inherited from XML_Archive
enum ArchiveSyntax {
ASX_MAJOR = 1 ,
ASX_MINOR = 2 ,
ASX_OTHER = 2
}
Protected Member Functions
int do_indent ()
indent by indent levels, return space left on line
Vid find_vid (const Value *val)
return the index of val in values
void emit_unicode (Unicode uni, int &space)
emit one unicode character (inside "...")
void emit_cell (const Cell &cell, int &space)
emit one ravel cell cell
void emit_token_val (const Token &tok)
emit a token value up to (excluding) the '>' of the end token
int enter_char_mode ()
enter char mode. maybe print ² and return the number of chars printed
int leave_char_mode ()
leave char mode. maybe print ⁰ and return the number of chars printed
bool is_saved (const Function *fun) const
return true iff (the definition of) fun was already saved.
Static Protected Member Functions
static const char * decr (int &space, const char *str)
decrement space by length of str and return str
static bool xml_allowed (Unicode uni)
return true if uni prints nicely and is allowed in XML "..." strings
Protected Attributes
int indent
current indentation level
std::ofstream & out
output XML file
_val_par * values
a value and the Vid of its parent (if value is a sub-value of a nested parent) all values in the workspace
ShapeItem value_count
the number of (non-stale) values
bool char_mode
true iff ² is pending
vector< const Function * > saved_Functions
functions saved so far
Detailed Description
a helper class for saving an APL workspace
Definition at line 73 of file Archive.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
width of one indentation level
Definition at line 172 of file Archive.hh.
Vid
enum XML_Saving_Archive::Vid
an index for values
Definition at line 89 of file Archive.hh.
Constructor & Destructor Documentation
XML_Saving_Archive()
XML_Saving_Archive::XML_Saving_Archive (ofstream & of) inline
constructor: remember output stream and workspace
Definition at line 77 of file Archive.hh.
~XML_Saving_Archive()
XML_Saving_Archive::~XML_Saving_Archive () inline
destructor
Definition at line 86 of file Archive.hh.
References out, and values.
Member Function Documentation
decr()
const char * XML_Saving_Archive::decr (int & space, const char * str) static protected
decrement space by length of str and return str
Definition at line 112 of file Archive.cc.
Referenced by emit_cell(), emit_unicode(), save_Ravel(), and save_UCS().
do_indent()
int XML_Saving_Archive::do_indent () protected
indent by indent levels, return space left on line
Definition at line 119 of file Archive.cc.
References indent, and out.
Referenced by emit_unicode(), save(), save_Function(), save_functions(), save_Parser(), save_Ravel(), save_shape(), save_SI_entry(), save_Symbol(), save_symtab(), save_token_loc(), save_UCS(), save_user_commands(), and save_vstack_item().
emit_cell()
void XML_Saving_Archive::emit_cell (const Cell & cell, int & space) protected
emit one ravel cell cell
Definition at line 256 of file Archive.cc.
References decr(), emit_unicode(), find_vid(), Value_P_Base::get(), LvalCell::get_cell_owner(), Cell::get_cell_type(), Cell::get_char_value(), Cell::get_imag_value(), Cell::get_int_value(), LvalCell::get_lval_value(), Value::get_offset(), Cell::get_pointer_value(), Cell::get_real_value(), and leave_char_mode().
Referenced by save_Ravel().
emit_token_val()
void XML_Saving_Archive::emit_token_val (const Token & tok) protected
emit a token value up to (excluding) the '>' of the end token
Definition at line 698 of file Archive.cc.
References find_vid(), Value_P_Base::get(), Token::get_apl_val(), Token::get_char_val(), Token::get_cpx_imag(), Token::get_cpx_real(), Token::get_flt_val(), Token::get_fun_line(), Token::get_function(), Token::get_index_val(), Token::get_int_val(), Symbol::get_name(), IndexExpr::get_rank(), Token::get_sym_ptr(), Token::get_ValueType(), out, save_Function_name(), and IndexExpr::values.
Referenced by save_token_loc().
emit_unicode()
void XML_Saving_Archive::emit_unicode (Unicode uni, int & space) protected
emit one unicode character (inside "...")
Definition at line 137 of file Archive.cc.
References decr(), do_indent(), enter_char_mode(), leave_char_mode(), out, and xml_allowed().
Referenced by emit_cell(), and save_UCS().
enter_char_mode()
int XML_Saving_Archive::enter_char_mode () inline protected
enter char mode. maybe print ² and return the number of chars printed
Definition at line 190 of file Archive.hh.
References char_mode, and out.
Referenced by emit_unicode().
find_vid()
XML_Saving_Archive::Vid XML_Saving_Archive::find_vid (const Value * val) protected
return the index of val in values
Definition at line 128 of file Archive.cc.
References XML_Saving_Archive::_val_par::compare_val_par1(), value_count, and values.
Referenced by emit_cell(), emit_token_val(), save(), save_Function(), and save_vstack_item().
is_saved()
bool XML_Saving_Archive::is_saved (const Function * fun) const protected
return true iff (the definition of) fun was already saved.
Definition at line 426 of file Archive.cc.
References saved_Functions.
Referenced by save_Function().
leave_char_mode()
int XML_Saving_Archive::leave_char_mode () inline protected
leave char mode. maybe print ⁰ and return the number of chars printed
Definition at line 195 of file Archive.hh.
References char_mode, and out.
Referenced by emit_cell(), emit_unicode(), save_Ravel(), and save_UCS().
save()
XML_Saving_Archive & XML_Saving_Archive::save ()
write entire workspace
Definition at line 828 of file Archive.cc.
References XML_Saving_Archive::_val_par::_par, XML_Saving_Archive::_val_par::_val, XML_Archive::ASX_MAJOR, XML_Archive::ASX_MINOR, XML_Archive::ASX_OTHER, Command::cmd_CHECK(), XML_Saving_Archive::_val_par::compare_val_par(), do_indent(), find_vid(), Value_P_Base::get(), DynamicObject::get_all_values(), StateIndicator::get_parent(), Cell::get_pointer_value(), Workspace::get_symbol_table(), Workspace::get_user_commands(), Workspace::get_WS_name(), indent, Cell::is_lval_cell(), Value::is_marked(), Cell::is_pointer_cell(), Value::mark_all_dynamic_values(), out, save_functions(), save_Ravel(), save_shape(), save_SI_entry(), save_symtab(), save_user_commands(), Workspace::SI_entry_count(), Workspace::SI_top(), UCS_string::sort(), Value::unmark(), Workspace::unmark_all_values(), value_count, and values.
Referenced by Workspace::save_WS().
save_Derived()
void XML_Saving_Archive::save_Derived (const DerivedFunctionCache & fns)
write derived functions cache
Definition at line 506 of file Archive.cc.
References save_Function(), and DerivedFunctionCache::size().
Referenced by save_Parser().
save_Function()
void XML_Saving_Archive::save_Function (const Function & fun)
write user-defined function fun
Definition at line 351 of file Archive.cc.
References Function::canonical(), do_indent(), find_vid(), DerivedFunction::get_AXIS(), Function::get_creation_time(), Function::get_exec_properties(), Function::get_func_ufun(), NamedObject::get_Id(), DerivedFunction::get_LO(), UserFunction::get_macnum(), ID::get_name_UCS(), DerivedFunction::get_OPER(), DerivedFunction::get_RO(), Function::get_tag(), indent, Function::is_defined(), Function::is_derived(), Function::is_macro(), Function::is_native(), is_saved(), out, save_UCS(), and saved_Functions.
Referenced by save_Derived(), and save_vstack_item().
save_Function_name()
int XML_Saving_Archive::save_Function_name (const Function & fun)
write either the name and SI-level of user-defined function or the id of a system function. Return number of attribute= items written
Definition at line 435 of file Archive.cc.
References Symbol::get_exec_ufun_depth(), Function::get_func_ufun(), NamedObject::get_Id(), UserFunction::get_name(), Function::is_derived(), Workspace::lookup_symbol(), and out.
Referenced by emit_token_val().
save_functions()
void XML_Saving_Archive::save_functions ()
write all function
Definition at line 337 of file Archive.cc.
References do_indent(), and out.
Referenced by save().
save_Parser()
void XML_Saving_Archive::save_Parser (const StateIndicator & si)
write the Prefix parser of si (and its derived functions)
Definition at line 470 of file Archive.cc.
References Prefix::action, Prefix::at(), StateIndicator::current_stack, do_indent(), StateIndicator::fun_oper_cache, Prefix::get_assign_state(), Prefix::get_lookahead_high(), indent, out, save_Derived(), save_token_loc(), Prefix::saved_lookahead, and Prefix::size().
Referenced by save_SI_entry().
save_Ravel()
XML_Saving_Archive & XML_Saving_Archive::save_Ravel (Vid vid)
write ravel of Value v
Definition at line 198 of file Archive.cc.
References XML_Saving_Archive::_val_par::_val, decr(), do_indent(), emit_cell(), Value::get_cfirst(), indent, Value::is_packed(), leave_char_mode(), Value::nz_element_count(), out, and values.
Referenced by save().
save_shape()
XML_Saving_Archive & XML_Saving_Archive::save_shape (Vid vid)
write Value v except its ravel
Definition at line 177 of file Archive.cc.
References XML_Saving_Archive::_val_par::_par, XML_Saving_Archive::_val_par::_val, do_indent(), Value::get_flags(), Value::get_rank(), Value::get_shape_item(), out, and values.
Referenced by save().
save_SI_entry()
void XML_Saving_Archive::save_SI_entry (const StateIndicator & si)
write StateIndicator entry si
Definition at line 569 of file Archive.cc.
References UserFunction::canonical(), do_indent(), Executable::get_exec_ufun(), Symbol::get_exec_ufun_depth(), StateIndicator::get_executable(), StateIndicator::get_level(), Executable::get_line(), UserFunction::get_macnum(), Symbol::get_name(), UserFunction::get_name(), Executable::get_name(), Executable::get_parse_mode(), StateIndicator::get_PC(), Executable::get_text(), indent, UserFunction::is_lambda(), Function::is_macro(), Workspace::lookup_symbol(), out, save_Parser(), and save_UCS().
Referenced by save().
save_Symbol()
void XML_Saving_Archive::save_Symbol (const Symbol & sym)
write Symbol sym
Definition at line 644 of file Archive.cc.
References do_indent(), Symbol::get_name(), indent, out, save_vstack_item(), and Symbol::value_stack_size().
Referenced by save_symtab().
save_symtab()
void XML_Saving_Archive::save_symtab (const SymbolTable & symtab)
write SymbolTable symtab
Definition at line 516 of file Archive.cc.
References do_indent(), SymbolTable::get_all_symbols(), indent, Symbol::is_erased(), out, and save_Symbol().
Referenced by save().
save_token_loc()
void XML_Saving_Archive::save_token_loc (const Token_loc & tloc)
write Token_loc tloc
Definition at line 687 of file Archive.cc.
References do_indent(), emit_token_val(), Token::get_tag(), out, Token_loc::pc, and Token_loc::tok.
Referenced by save_Parser().
save_UCS()
void XML_Saving_Archive::save_UCS (const UCS_string & str)
write UCS_string str
Definition at line 163 of file Archive.cc.
References char_mode, decr(), do_indent(), emit_unicode(), indent, leave_char_mode(), out, and UCS_string::size().
Referenced by save_Function(), and save_SI_entry().
save_user_commands()
void XML_Saving_Archive::save_user_commands (const std::vector< Command::user_command > & cmds)
write all user defined commands
Definition at line 662 of file Archive.cc.
References Command::user_command::apl_function, do_indent(), indent, Command::user_command::mode, out, and Command::user_command::prefix.
Referenced by save().
save_vstack_item()
void XML_Saving_Archive::save_vstack_item (const ValueStackItem & vsi)
write ValueStackItem vsi
Definition at line 776 of file Archive.cc.
References do_indent(), find_vid(), ValueStackItem::get_function(), ValueStackItem::get_key(), ValueStackItem::get_label(), ValueStackItem::get_NC(), ValueStackItem::get_val_cptr(), out, and save_Function().
Referenced by save_Symbol().
xml_allowed()
bool XML_Saving_Archive::xml_allowed (Unicode uni) static protected
return true if uni prints nicely and is allowed in XML "..." strings
Definition at line 90 of file Archive.cc.
References Avec::find_char(), and Avec::map_alternative_char().
Referenced by emit_unicode().
Member Data Documentation
char_mode
bool XML_Saving_Archive::char_mode protected
true iff ² is pending
Definition at line 220 of file Archive.hh.
Referenced by enter_char_mode(), leave_char_mode(), and save_UCS().
indent
int XML_Saving_Archive::indent protected
current indentation level
Definition at line 206 of file Archive.hh.
Referenced by do_indent(), save(), save_Function(), save_Parser(), save_Ravel(), save_SI_entry(), save_Symbol(), save_symtab(), save_UCS(), and save_user_commands().
out
std::ofstream& XML_Saving_Archive::out protected
output XML file
Definition at line 209 of file Archive.hh.
Referenced by do_indent(), emit_token_val(), emit_unicode(), enter_char_mode(), leave_char_mode(), save(), save_Function(), save_Function_name(), save_functions(), save_Parser(), save_Ravel(), save_shape(), save_SI_entry(), save_Symbol(), save_symtab(), save_token_loc(), save_UCS(), save_user_commands(), save_vstack_item(), and ~XML_Saving_Archive().
saved_Functions
vector<const Function *> XML_Saving_Archive::saved_Functions protected
functions saved so far
Definition at line 223 of file Archive.hh.
Referenced by is_saved(), and save_Function().
value_count
ShapeItem XML_Saving_Archive::value_count protected
the number of (non-stale) values
Definition at line 217 of file Archive.hh.
Referenced by find_vid(), and save().
values
_val_par* XML_Saving_Archive::values protected
a value and the Vid of its parent (if value is a sub-value of a nested parent) all values in the workspace
Definition at line 214 of file Archive.hh.
Referenced by find_vid(), save(), save_Ravel(), save_shape(), and ~XML_Saving_Archive().
The documentation for this class was generated from the following files:
src/Archive.hh
src/Archive.cc