GNU APL: Function Class Reference
Function Class Reference abstract
Base class for all APL functions and operators (system or defined)
#include <Function.hh>
Public Types
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Member Functions
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Public Attributes
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Attributes
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
Base class for all APL functions and operators (system or defined)
The base class for all functions (user defined or system functions).
Definition at line 49 of file Function.hh.
Member Typedef Documentation
assoc_f2
typedef ErrorCode(Cell::* Function::assoc_f2) (Cell *, const Cell *) const
an associative cell function
Definition at line 191 of file Function.hh.
bool_f1
typedef bool(* Function::bool_f1) (const Cell &B)
a monadic Cell function that returns bool
Definition at line 90 of file Function.hh.
bool_f1_bool
typedef uint64_t(* Function::bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
Definition at line 96 of file Function.hh.
bool_f2
typedef bool(* Function::bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
Definition at line 93 of file Function.hh.
bool_f2_bool
typedef uint64_t(* Function::bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
Definition at line 99 of file Function.hh.
Constructor & Destructor Documentation
Function() [1/2]
Function::Function (TokenTag _tag) inline
constructor for most functions
Definition at line 53 of file Function.hh.
References parallel_thresholds.
Function() [2/2]
Function::Function (Id id, TokenTag _tag) inline
constructor for functions whose Id does not match their tag
Definition at line 60 of file Function.hh.
References parallel_thresholds.
~Function()
virtual Function::~Function () inline virtual
destructor
Definition at line 67 of file Function.hh.
Member Function Documentation
canonical()
virtual UCS_string Function::canonical (bool with_lines) const inline virtual
Quad_CR of this function.
Reimplemented in NativeFunction, and UserFunction.
Definition at line 268 of file Function.hh.
Referenced by Quad_CR::do_CR10(), XML_Saving_Archive::save_Function(), Quad_TF::tf1(), and Quad_TF::tf2_fun_ucs().
destroy()
virtual void Function::destroy () inline virtual
Delete this function (do nothing, overloaded by UserFunction).
Reimplemented in NativeFunction, and UserFunction.
Definition at line 265 of file Function.hh.
eval_()
Token Function::eval_ () const virtual
plain function, 0 arguments
Reimplemented in NativeFunction, Bif_F0_ZILDE, and UserFunction.
Definition at line 77 of file Function.cc.
References NamedObject::get_name().
eval_AB()
Token Function::eval_AB (Value_P A, Value_P B) const virtual
plain function, 2 arguments
Reimplemented in Bif_F12_COMMA, Bif_F12_COMMA1, Bif_F12_DOMINO, Bif_F12_FORMAT, Bif_F12_INDEX_OF, Bif_F12_INTERVAL_INDEX, Bif_F12_PARTITION, Bif_F12_PICK, Bif_F12_SORT_ASC, Bif_F12_SORT_DES, Bif_F12_TAKE, Bif_F12_DROP, Bif_OPER1_REDUCE, Bif_OPER1_REDUCE1, Bif_OPER1_SCAN, Bif_OPER1_SCAN1, DerivedFunction, NativeFunction, Bif_F2_INDEX, Bif_F12_ELEMENT, Bif_F12_EQUIV, Bif_F12_NEQUIV, Bif_F12_ENCODE, Bif_F12_DECODE, Bif_F12_ROTATE, Bif_F12_ROTATE1, Bif_F12_TRANSPOSE, Bif_F12_RHO, Bif_F12_UNION, Bif_F2_INTER, Bif_F2_LEFT, Bif_F2_RIGHT, Quad_CR, Quad_DLX, Quad_FFT, Quad_FIO, Quad_FX, Quad_GTK, Quad_JSON, Quad_MAP, Quad_PLOT, Quad_PNG, Quad_RE, Quad_RVAL, Quad_SQL, Quad_SVC, Quad_SVO, Quad_TF, Quad_XML, QuadFunction, Quad_AT, Quad_EA, Quad_EB, Quad_ES, Quad_INP, Quad_NA, Quad_NL, Quad_SI, Quad_STOP, Quad_TRACE, Bif_F12_BINOM, Bif_F2_LESS, Bif_F2_EQUAL, Bif_F2_EQUAL_B, Bif_F2_UNEQ_B, Bif_F2_GREATER, Bif_F2_AND, Bif_F2_AND_B, Bif_F2_OR, Bif_F2_OR_B, Bif_F2_LEQU, Bif_F2_MEQU, Bif_F2_UNEQU, Bif_F2_FIND, Bif_F2_NOR, Bif_F2_NOR_B, Bif_F2_NAND, Bif_F2_NAND_B, Bif_F12_POWER, Bif_F12_PLUS, Bif_F12_MINUS, Bif_F12_ROLL, Bif_F12_WITHOUT, Bif_F12_TIMES, Bif_F12_DIVIDE, Bif_F12_CIRCLE, Bif_F12_RND_UP, Bif_F12_RND_DN, Bif_F12_STILE, Bif_F12_LOGA, and UserFunction.
Definition at line 93 of file Function.cc.
References NamedObject::get_name().
Referenced by PrimitiveFunction::eval_fill_AB().
eval_ALB()
Token Function::eval_ALB (Value_P A, Token & LO, Value_P B) const virtual
monadic operator, 2 arguments
Reimplemented in Bif_OPER1_COMMUTE, Bif_OPER1_EACH, Bif_OPER1_REDUCE, Bif_OPER1_REDUCE1, NativeFunction, and UserFunction.
Definition at line 109 of file Function.cc.
References NamedObject::get_name().
eval_ALRB()
Token Function::eval_ALRB (Value_P A, Token & LO, Token & RO, Value_P B) const virtual
dyadic operator, 2 arguments
Reimplemented in Bif_OPER2_INNER, Bif_OPER2_OUTER, Bif_OPER2_POWER, Bif_OPER2_RANK, NativeFunction, and UserFunction.
Definition at line 125 of file Function.cc.
References NamedObject::get_name().
eval_ALRXB()
virtual Token Function::eval_ALRXB (Value_P A, Token & LO, Token & RO, Value_P X, Value_P B) const inline virtual
dyadic operator, 2 arguments, with axis
Reimplemented in Bif_OPER2_RANK, NativeFunction, and UserFunction.
Definition at line 225 of file Function.hh.
eval_ALXB()
virtual Token Function::eval_ALXB (Value_P A, Token & LO, Value_P X, Value_P B) const inline virtual
monadic operator, 2 arguments, with axis
Reimplemented in Bif_OPER1_COMMUTE, Bif_OPER1_REDUCE, Bif_OPER1_REDUCE1, NativeFunction, Quad_FIO, and UserFunction.
Definition at line 221 of file Function.hh.
eval_AXB()
virtual Token Function::eval_AXB (Value_P A, Value_P X, Value_P B) const inline virtual
plain function, 2 arguments, with axis
Reimplemented in Bif_F12_COMMA, Bif_F12_COMMA1, Bif_F12_DOMINO, Bif_F12_PARTITION, Bif_F12_TAKE, Bif_F12_DROP, Bif_OPER1_REDUCE, Bif_OPER1_REDUCE1, Bif_OPER1_SCAN, Bif_OPER1_SCAN1, DerivedFunction, NativeFunction, Bif_F2_INDEX, Bif_F12_ROTATE, Bif_F12_ROTATE1, Bif_F2_RIGHT, Quad_FIO, Quad_FX, Quad_GTK, Quad_RE, Quad_SQL, Bif_F12_BINOM, Bif_F2_LESS, Bif_F2_EQUAL, Bif_F2_EQUAL_B, Bif_F2_UNEQ_B, Bif_F2_GREATER, Bif_F2_AND, Bif_F2_AND_B, Bif_F2_OR, Bif_F2_OR_B, Bif_F2_LEQU, Bif_F2_MEQU, Bif_F2_UNEQU, Bif_F2_NOR, Bif_F2_NOR_B, Bif_F2_NAND, Bif_F2_NAND_B, Bif_F12_POWER, Bif_F12_PLUS, Bif_F12_MINUS, Bif_F12_TIMES, Bif_F12_DIVIDE, Bif_F12_RND_UP, Bif_F12_RND_DN, Bif_F12_STILE, Bif_F12_LOGA, and UserFunction.
Definition at line 214 of file Function.hh.
eval_B()
Token Function::eval_B (Value_P B) const virtual
plain function, 1 argument
Reimplemented in Bif_F12_COMMA, Bif_F12_COMMA1, Bif_F12_DOMINO, Bif_F12_FORMAT, Bif_F12_INDEX_OF, Bif_F12_INTERVAL_INDEX, Bif_F12_PARTITION, Bif_F12_PICK, Bif_F12_SORT_ASC, Bif_F12_SORT_DES, Bif_F12_TAKE, DerivedFunction, NativeFunction, Bif_F1_EXECUTE, Bif_F12_ELEMENT, Bif_F12_EQUIV, Bif_F12_NEQUIV, Bif_F12_ROTATE, Bif_F12_ROTATE1, Bif_F12_TRANSPOSE, Bif_F12_RHO, Bif_F12_UNION, Bif_F2_LEFT, Bif_F2_RIGHT, Quad_CR, Quad_DLX, Quad_FFT, Quad_FIO, Quad_FX, Quad_GTK, Quad_JSON, Quad_PLOT, Quad_PNG, Quad_RE, Quad_RVAL, Quad_SQL, Quad_SVC, Quad_SVO, Quad_SVQ, Quad_SVR, Quad_SVS, Quad_XML, QuadFunction, Quad_AF, Quad_DL, Quad_EC, Quad_ENV, Quad_ES, Quad_EX, Quad_INP, Quad_NA, Quad_NC, Quad_NL, Quad_SI, Quad_UCS, Quad_STOP, Quad_TRACE, Bif_F12_BINOM, Bif_F2_AND_B, Bif_F2_OR_B, Bif_F2_NOR_B, Bif_F12_POWER, Bif_F12_PLUS, Bif_F12_MINUS, Bif_F12_ROLL, Bif_F12_WITHOUT, Bif_F12_TIMES, Bif_F12_DIVIDE, Bif_F12_CIRCLE, Bif_F12_RND_UP, Bif_F12_RND_DN, Bif_F12_STILE, Bif_F12_LOGA, and UserFunction.
Definition at line 85 of file Function.cc.
References NamedObject::get_name().
Referenced by PrimitiveFunction::eval_fill_B().
eval_fill_AB()
Token Function::eval_fill_AB (Value_P A, Value_P B) const virtual
Evaluate the fill function.
Reimplemented in Bif_F12_DOMINO, NativeFunction, PrimitiveFunction, ScalarFunction, and UserFunction.
Definition at line 148 of file Function.cc.
References NamedObject::get_name().
eval_fill_B()
virtual Token Function::eval_fill_B (Value_P B) const inline virtual
Evaluate the fill function.
Reimplemented in Bif_F12_DOMINO, NativeFunction, PrimitiveFunction, Quad_EC, ScalarFunction, and UserFunction.
Definition at line 250 of file Function.hh.
eval_identity_fun()
Token Function::eval_identity_fun (Value_P B, sAxis axis) const virtual
Evaluate the identity function. B is empty and the result is a / value f/B0 with (B0 f ↑B) ≡ B for all B (and f is this function). / If such a B0 does not exist then raise a DOMAIN ERROR.
   NOTE that eval_identity_fun() returns f/B0 and not B0 !!!
Reimplemented in NativeFunction, NonscalarFunction_default_identity, Bif_F12_BINOM, Bif_F2_LESS, Bif_F2_EQUAL, Bif_F2_EQUAL_B, Bif_F2_UNEQ_B, Bif_F2_GREATER, Bif_F2_AND, Bif_F2_AND_B, Bif_F2_OR, Bif_F2_OR_B, Bif_F2_LEQU, Bif_F2_MEQU, Bif_F2_UNEQU, Bif_F12_POWER, Bif_F12_PLUS, Bif_F12_MINUS, Bif_F12_WITHOUT, Bif_F12_TIMES, Bif_F12_DIVIDE, Bif_F12_RND_UP, Bif_F12_RND_DN, and Bif_F12_STILE.
Definition at line 155 of file Function.cc.
References NamedObject::get_name().
eval_LB()
Token Function::eval_LB (Token & LO, Value_P B) const virtual
monadic operator, 1 argument
Reimplemented in Bif_OPER1_COMMUTE, Bif_OPER1_EACH, Bif_OPER1_REDUCE, Bif_OPER1_REDUCE1, Bif_OPER1_SCAN, Bif_OPER1_SCAN1, NativeFunction, and UserFunction.
Definition at line 101 of file Function.cc.
References NamedObject::get_name().
eval_LRB()
Token Function::eval_LRB (Token & LO, Token & RO, Value_P B) const virtual
dyadic operator, 1 arguments
Reimplemented in Bif_OPER2_POWER, Bif_OPER2_RANK, NativeFunction, and UserFunction.
Definition at line 117 of file Function.cc.
References NamedObject::get_name().
eval_LRXB()
virtual Token Function::eval_LRXB (Token & LO, Token & RO, Value_P X, Value_P B) const inline virtual
dyadic operator, 1 arguments, with axis
Reimplemented in Bif_OPER2_RANK, NativeFunction, and UserFunction.
Definition at line 246 of file Function.hh.
eval_LXB()
virtual Token Function::eval_LXB (Token & LO, Value_P X, Value_P B) const inline virtual
monadic operator, 1 arguments, with axis
Reimplemented in Bif_OPER1_COMMUTE, Bif_OPER1_REDUCE, Bif_OPER1_REDUCE1, Bif_OPER1_SCAN, Bif_OPER1_SCAN1, NativeFunction, Quad_FIO, and UserFunction.
Definition at line 239 of file Function.hh.
eval_XB()
virtual Token Function::eval_XB (Value_P X, Value_P B) const inline virtual
plain function, 1 arguments, with axis
Reimplemented in Bif_F12_COMMA, Bif_F12_COMMA1, Bif_F12_DOMINO, Bif_F12_PARTITION, Bif_F12_PICK, Bif_F12_TAKE, DerivedFunction, NativeFunction, Bif_F12_ROTATE, Bif_F12_ROTATE1, Quad_CR, Quad_FIO, Quad_GTK, Quad_RE, Quad_SQL, Quad_INP, and UserFunction.
Definition at line 235 of file Function.hh.
get_assoc()
virtual assoc_f2 Function::get_assoc () const inline virtual
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Reimplemented in Bif_F2_AND, Bif_F2_AND_B, Bif_F2_OR, Bif_F2_OR_B, Bif_F12_PLUS, Bif_F12_TIMES, Bif_F12_RND_UP, and Bif_F12_RND_DN.
Definition at line 195 of file Function.hh.
get_attributes()
void Function::get_attributes (int mode, Value & Z) const virtual
store the attributes (as per ⎕AT) of symbol in Z, ...
Definition at line 37 of file Function.cc.
References YMDhmsu::day, get_creation_time(), get_exec_properties(), get_fun_valence(), get_oper_valence(), has_result(), YMDhmsu::hour, YMDhmsu::micro, YMDhmsu::minute, YMDhmsu::month, Value::next_ravel_0(), Value::next_ravel_Int(), YMDhmsu::second, and YMDhmsu::year.
get_bool_f1()
virtual bool_f1 Function::get_bool_f1 () const inline virtual
return a bool_f1() (if any), otherwise 0.
Definition at line 102 of file Function.hh.
get_bool_f1_bool()
virtual bool_f1_bool Function::get_bool_f1_bool () const inline virtual
return a bool_f1() (if any), otherwise 0.
Definition at line 110 of file Function.hh.
get_bool_f2()
virtual bool_f2 Function::get_bool_f2 () const inline virtual
return a bool_f2() (if any), otherwise 0.
Definition at line 106 of file Function.hh.
get_bool_f2_bool()
virtual bool_f2_bool Function::get_bool_f2_bool () const inline virtual
return a bool_f2() (if any), otherwise 0.
Definition at line 114 of file Function.hh.
get_creation_time()
APL_time_us Function::get_creation_time () const inline
GMT when this function was created; 0 for system functions.
Definition at line 159 of file Function.hh.
References creation_time.
Referenced by get_attributes(), and XML_Saving_Archive::save_Function().
get_dyadic_inverse()
virtual Function_P Function::get_dyadic_inverse () const inline virtual
the dyadic inverse function of this function (if any)
Reimplemented in Bif_F12_POWER, Bif_F12_PLUS, Bif_F12_MINUS, Bif_F12_TIMES, Bif_F12_DIVIDE, Bif_F12_CIRCLE, and Bif_F12_LOGA.
Definition at line 156 of file Function.hh.
get_dyadic_threshold()
ShapeItem Function::get_dyadic_threshold () const inline
return break-even point for dyadic parallel execution
Definition at line 297 of file Function.hh.
References parallel_thresholds.
Referenced by ScalarFunction::do_scalar_AB(), Quad_FIO::eval_AXB(), Quad_FIO::eval_XB(), Bif_OPER2_INNER::scalar_inner_product(), and Bif_OPER2_OUTER::scalar_outer_product().
get_exec_properties()
virtual const int * Function::get_exec_properties () const inline virtual
return the execution properties (3 ⎕AT) for this function
Reimplemented in UserFunction.
Definition at line 167 of file Function.hh.
Referenced by Quad_CR::do_CR10(), get_attributes(), and XML_Saving_Archive::save_Function().
get_fun_valence()
virtual int Function::get_fun_valence () const inline virtual
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
Reimplemented in PrimitiveOperator, Quad_FIO, and UserFunction.
Definition at line 129 of file Function.hh.
References tag.
Referenced by get_attributes(), and get_signature().
get_func_ufun()
virtual const UserFunction * Function::get_func_ufun () const inline virtual
return a pointer to this UserFunction (if it is one)
Reimplemented in UserFunction.
Definition at line 177 of file Function.hh.
Referenced by Nabla::execute_escape(), Workspace::is_called(), XML_Saving_Archive::save_Function(), and XML_Saving_Archive::save_Function_name().
get_function()
virtual const Function * Function::get_function () const inline virtual
overloaded NamedObject::get_function()
Reimplemented from NamedObject.
Definition at line 150 of file Function.hh.
get_monadic_inverse()
virtual Function_P Function::get_monadic_inverse () const inline virtual
the monadic inverse function of this function (if any)
Reimplemented in Bif_F12_POWER, Bif_F12_MINUS, Bif_F12_DIVIDE, Bif_F12_CIRCLE, and Bif_F12_LOGA.
Definition at line 153 of file Function.hh.
get_monadic_threshold()
ShapeItem Function::get_monadic_threshold () const inline
return break-even point for monadic parallel execution
Definition at line 289 of file Function.hh.
References parallel_thresholds.
Referenced by ScalarFunction::do_scalar_B(), Quad_FIO::eval_AXB(), and Quad_FIO::eval_XB().
get_oper_valence()
virtual int Function::get_oper_valence () const inline virtual
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
Reimplemented in Bif_JOT, PrimitiveOperator, Quad_FIO, and UserFunction.
Definition at line 139 of file Function.hh.
Referenced by get_attributes(), get_signature(), and Prefix::is_value_parenthesis().
get_scalar_f2()
virtual prim_f2 Function::get_scalar_f2 () const inline virtual
return the dyadic scalar primitive if this function
Reimplemented in Bif_F12_BINOM, Bif_F2_LESS, Bif_F2_EQUAL, Bif_F2_EQUAL_B, Bif_F2_UNEQ_B, Bif_F2_GREATER, Bif_F2_AND, Bif_F2_AND_B, Bif_F2_OR, Bif_F2_OR_B, Bif_F2_LEQU, Bif_F2_MEQU, Bif_F2_UNEQU, Bif_F2_FIND, Bif_F2_NOR, Bif_F2_NOR_B, Bif_F2_NAND, Bif_F2_NAND_B, Bif_F12_POWER, Bif_F12_PLUS, Bif_F12_MINUS, Bif_F12_ROLL, Bif_F12_WITHOUT, Bif_F12_TIMES, Bif_F12_DIVIDE, Bif_F12_CIRCLE, Bif_F12_RND_UP, Bif_F12_RND_DN, Bif_F12_STILE, Bif_F12_LOGA, and ScalarFunction.
Definition at line 187 of file Function.hh.
get_signature()
Fun_signature Function::get_signature () const
return the signature of this function (currently only valid for user-defined functions)
Definition at line 133 of file Function.cc.
References get_fun_valence(), get_oper_valence(), has_axis(), and has_result().
get_tag()
TokenTag Function::get_tag () const inline
return the Token Tag for this function.
Definition at line 202 of file Function.hh.
References tag.
Referenced by UserFunction::adjust_line_starts(), XML_Saving_Archive::save_Function(), Quad_TF::tf2_inverse(), and Quad_TF::tf2_reduce_COMMA().
get_token()
Token Function::get_token () const inline
return a Token for this function.
Definition at line 199 of file Function.hh.
References tag.
Referenced by Workspace::get_quad(), and Executable::setup_one_lambda().
has_alpha()
virtual bool Function::has_alpha () const inline virtual
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
Reimplemented in QuadFunction, and UserFunction.
Definition at line 181 of file Function.hh.
has_axis()
virtual bool Function::has_axis () const inline virtual
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
Reimplemented in UserFunction.
Definition at line 147 of file Function.hh.
Referenced by get_signature().
has_result()
virtual bool Function::has_result () const pure virtual
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
Implemented in Bif_REDUCE, DerivedFunction, NativeFunction, PrimitiveFunction, QuadFunction, ScalarFunction, and UserFunction.
Referenced by get_attributes(), and get_signature().
has_subfuns()
virtual bool Function::has_subfuns () const inline virtual
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
Reimplemented in Quad_CR, and Quad_FIO.
Definition at line 277 of file Function.hh.
is_bool_bool()
virtual bool Function::is_bool_bool () const inline virtual
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
Definition at line 120 of file Function.hh.
is_defined()
virtual bool Function::is_defined () const inline virtual
return true iff this function is defined (= has an APL body)
Reimplemented in NativeFunction, and UserFunction.
Definition at line 83 of file Function.hh.
Referenced by XML_Saving_Archive::save_Function().
is_derived()
virtual bool Function::is_derived () const inline virtual
return true iff this function is a derived function
Reimplemented in DerivedFunction.
Definition at line 86 of file Function.hh.
Referenced by XML_Saving_Archive::save_Function(), and XML_Saving_Archive::save_Function_name().
is_lambda()
virtual bool Function::is_lambda () const inline virtual
return true iff this function is a lambda
Reimplemented in UserFunction.
Definition at line 77 of file Function.hh.
Referenced by Quad_CR::do_CR10().
is_macro()
virtual bool Function::is_macro () const inline virtual
return true iff this function is a macro
Reimplemented in Macro.
Definition at line 80 of file Function.hh.
Referenced by XML_Saving_Archive::save_Function(), and XML_Saving_Archive::save_SI_entry().
is_native()
virtual bool Function::is_native () const inline virtual
return true iff this is a native function
Reimplemented in NativeFunction.
Definition at line 74 of file Function.hh.
Referenced by Doxy::add_fun_to_call_graph(), Doxy::functions_table(), XML_Saving_Archive::save_Function(), and Quad_TF::tf2_fun_ucs().
is_operator()
virtual bool Function::is_operator () const inline virtual
return true iff this is an operator.
Reimplemented in NativeFunction, PrimitiveOperator, Quad_FIO, and UserFunction.
Definition at line 71 of file Function.hh.
Referenced by Prefix::is_value_parenthesis().
locate_X()
virtual Value_P * Function::locate_X () const inline virtual
return axis (non-0 only for derived functions)
Reimplemented in DerivedFunction.
Definition at line 272 of file Function.hh.
may_push_SI()
virtual bool Function::may_push_SI () const inline virtual
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
Reimplemented in Bif_OPER1_EACH, Bif_REDUCE, Bif_OPER1_SCAN, Bif_OPER2_INNER, Bif_JOT, Bif_OPER2_POWER, Bif_OPER2_RANK, DerivedFunction, Bif_F0_ZILDE, Bif_F1_EXECUTE, Quad_EA, Quad_EB, Quad_EC, and UserFunction.
Definition at line 125 of file Function.hh.
print()
virtual ostream & Function::print (ostream & out) const pure virtual
Print this function.
Implemented in DerivedFunction, PrimitiveFunction, and UserFunction.
print_properties()
virtual void Function::print_properties (ostream & out, int indent) const pure virtual
print the properties of this function
Implemented in DerivedFunction, NativeFunction, PrimitiveFunction, and UserFunction.
set_creation_time()
void Function::set_creation_time (APL_time_us t) inline
set the time when the function was created (0 for built-in functions)
Definition at line 163 of file Function.hh.
References creation_time.
Referenced by Command::transfer_context::function_2TF(), XML_Loading_Archive::read_Function(), and UserFunction::UserFunction().
set_dyadic_threshold()
void Function::set_dyadic_threshold (ShapeItem new_threshold) inline
set the break-even point for dyadic parallel execution
Definition at line 301 of file Function.hh.
References parallel_thresholds.
Referenced by Quad_FIO::eval_AXB(), and ScalarFunction::ScalarFunction().
set_monadic_threshold()
void Function::set_monadic_threshold (ShapeItem new_threshold) inline
set the break-even point for monadic parallel execution
Definition at line 293 of file Function.hh.
References parallel_thresholds.
Referenced by Quad_FIO::eval_AXB(), and ScalarFunction::ScalarFunction().
subfun_to_axis()
virtual sAxis Function::subfun_to_axis (const UCS_string & name) const inline virtual
return a (pseudo-) axis number for subfunction name
Reimplemented in Quad_CR, and Quad_FIO.
Definition at line 281 of file Function.hh.
Member Data Documentation
creation_time
APL_time_us Function::creation_time
when this function was created (0.0 for system functions)
Definition at line 305 of file Function.hh.
Referenced by get_creation_time(), and set_creation_time().
parallel_thresholds
ShapeItem Function::parallel_thresholds[2] protected
the thresholds for parallel execution
Definition at line 312 of file Function.hh.
Referenced by Function(), get_dyadic_threshold(), get_monadic_threshold(), set_dyadic_threshold(), and set_monadic_threshold().
tag
TokenTag Function::tag protected
the tag for token pointing to this function
Definition at line 309 of file Function.hh.
Referenced by Quad_CR::do_CR33(), Quad_CR::do_CR34(), get_fun_valence(), get_tag(), get_token(), NativeFunction::NativeFunction(), Quad_GTK::poll_response(), Quad_GTK::read_fd(), Quad_TF::tf1_inv(), UserFunction::UserFunction(), Quad_GTK::write_TL0(), and Quad_GTK::write_TLV().
The documentation for this class was generated from the following files:
src/Function.hh
src/Function.cc