GNU APL: Quad_PNG Class Reference
Quad_PNG Class Reference
The class implementing ⎕PNG.
#include <Quad_PNG.hh>
Classes
struct filter_info
the type and compressed length of a PNG filter
Public Member Functions
Quad_PNG ()
Constructor.
Public Member Functions inherited from QuadFunction
QuadFunction (TokenTag tag)
Constructor.
virtual bool has_alpha () const
overloaded Function::has_alpha()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B().
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB().
virtual bool has_result () const
overloaded Function::has_result()
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
virtual bool has_result () const
overloaded Function::has_result()
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Static Public Attributes
static Quad_PNG * fun = &Quad_PNG::_fun
Built-in function.
static Quad_PNG _fun
Built-in function.
static sem_t * PNG_window_sema = &__PNG_window_sema
a semaphore blocking until gtk_widget_show_all() was called
static sem_t * PNG_threads_sema = &__PNG_threads_sema
a semaphore waiting from pthread_create() until the thread has started.
Protected Types
enum Type_Depth {
GRAY_1 = 0x0001 ,
GRAY_2 = 0x0002 ,
GRAY_4 = 0x0004 ,
GRAY_8 = 0x0008 ,
GRAY_16 = 0x0010 ,
RGB_8 = 0x0208 ,
RGB_16 = 0x0210 ,
PALE_1 = 0x0301 ,
PALE_2 = 0x0302 ,
PALE_4 = 0x0304 ,
PALE_8 = 0x0308 ,
GRAY_8A = 0x0408 ,
GRAY_16A = 0x0410 ,
RGB_8A = 0x0608 ,
RGB_16A = 0x0610
}
valid type/depth combinations for PNG files (not yet used, though)
Protected Member Functions
~Quad_PNG ()
Destructor.
Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB()
Token eval_B (Value_P B) const
overloaded Function::eval_B()
Value_P window_control (APL_Integer B) const
control logging etc. of ⎕PNG
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Static Protected Member Functions
static Value_P read_PNG_file (const UTF8_string &filename)
read PNG file filename and return its pixels as 4×N×M matrix
static APL_Integer display_PNG (Value &B)
display an RGB matrix
static APL_Integer display_PNG_main (Value_P B)
display an RGB matrix (interpreter code)
static bool valid_type_and_bits (int color_type, int bit_depth)
return true iff the combination of color_type and bit_depth is valid in the PNG standard AND supported by ⎕PNG.
static void write_PNG_file (const char *filename, int bit_depth, const Value &B)
write APL pixel matrix B PNG file filename
Additional Inherited Members
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
The class implementing ⎕PNG.
Definition at line 31 of file Quad_PNG.hh.
Member Enumeration Documentation
Type_Depth
enum Quad_PNG::Type_Depth protected
valid type/depth combinations for PNG files (not yet used, though)
Enumerator
GRAY_1
1-bit grayscale
GRAY_2
2-bit grayscale
GRAY_4
4-bit grayscale
GRAY_8
8-bit grayscale
GRAY_16
16-bit grayscale
RGB_8
8-bit R/G/B
RGB_16
16-bit R/G/B
PALE_1
1-bit palette
PALE_2
2-bit palette
PALE_4
4-bit palette
PALE_8
8-bit palette
GRAY_8A
8-bit grayscale with ⍺
GRAY_16A
16-bit grayscale with ⍺
RGB_8A
8-bit R/G/B with ⍺
RGB_16A
16-bit R/G/B with ⍺
Definition at line 59 of file Quad_PNG.hh.
Constructor & Destructor Documentation
Quad_PNG()
Quad_PNG::Quad_PNG ()
Constructor.
Definition at line 119 of file Quad_PNG.cc.
References PNG_threads_sema, and PNG_window_sema.
~Quad_PNG()
Quad_PNG::~Quad_PNG () protected
Destructor.
Definition at line 126 of file Quad_PNG.cc.
References PNG_threads_sema, and PNG_window_sema.
Member Function Documentation
display_PNG_main()
APL_Integer Quad_PNG::display_PNG_main (Value_P B) static protected
display an RGB matrix (interpreter code)
Definition at line 806 of file Quad_PNG.cc.
References all_PNG_contexts, PNG_context::drawing_area, PNG_context::get_total_height(), PNG_context::get_total_width(), gtk_main_wrapper(), PNG_context::handle, plot_window_count, PNG_draw_callback(), PNG_plot_destroyed(), PNG_window_sema, and PNG_context::window.
Referenced by eval_B().
eval_AB()
Token Quad_PNG::eval_AB (Value_P A, Value_P B) const protected virtual
overloaded Function::eval_AB()
Reimplemented from QuadFunction.
Definition at line 583 of file Quad_PNG.cc.
References UTF8_string::c_str(), and write_PNG_file().
eval_B()
Token Quad_PNG::eval_B (Value_P B) const protected virtual
overloaded Function::eval_B()
Reimplemented from QuadFunction.
Definition at line 304 of file Quad_PNG.cc.
References display_PNG_main(), PNG_threads_sema, PNG_window_sema, read_PNG_file(), and window_control().
read_PNG_file()
Value_P Quad_PNG::read_PNG_file (const UTF8_string & filename) static protected
read PNG file filename and return its pixels as 4×N×M matrix
Definition at line 148 of file Quad_PNG.cc.
References UTF8_string::append_ASCII(), UTF8_string::c_str(), UTF8_string::ends_with(), PNG_err(), PNG_warn(), and verbosity.
Referenced by eval_B().
valid_type_and_bits()
bool Quad_PNG::valid_type_and_bits (int color_type, int bit_depth) static protected
return true iff the combination of color_type and bit_depth is valid in the PNG standard AND supported by ⎕PNG.
Definition at line 405 of file Quad_PNG.cc.
Referenced by write_PNG_file().
window_control()
Value_P Quad_PNG::window_control (APL_Integer B) const protected
control logging etc. of ⎕PNG
Definition at line 340 of file Quad_PNG.cc.
References all_PNG_contexts, PNG_context::handle, verbosity, and PNG_context::window.
Referenced by eval_B().
write_PNG_file()
void Quad_PNG::write_PNG_file (const char * filename, int bit_depth, const Value & B) static protected
write APL pixel matrix B PNG file filename
Definition at line 427 of file Quad_PNG.cc.
References PNG_err(), PNG_warn(), valid_type_and_bits(), and verbosity.
Referenced by eval_AB().
Member Data Documentation
_fun
Quad_PNG Quad_PNG::_fun static
Built-in function.
Definition at line 38 of file Quad_PNG.hh.
fun
Quad_PNG * Quad_PNG::fun = &Quad_PNG::_fun static
Built-in function.
Definition at line 37 of file Quad_PNG.hh.
PNG_threads_sema
sem_t * Quad_PNG::PNG_threads_sema = &__PNG_threads_sema static
a semaphore waiting from pthread_create() until the thread has started.
Definition at line 44 of file Quad_PNG.hh.
Referenced by eval_B(), Quad_PNG(), and ~Quad_PNG().
PNG_window_sema
sem_t * Quad_PNG::PNG_window_sema = &__PNG_window_sema static
a semaphore blocking until gtk_widget_show_all() was called
Definition at line 41 of file Quad_PNG.hh.
Referenced by display_PNG_main(), eval_B(), Quad_PNG(), and ~Quad_PNG().
The documentation for this class was generated from the following files:
src/Quad_PNG.hh
src/Quad_PNG.cc