GNU APL: IO_Files Class Reference
IO_Files Class Reference
a sequence of files that are still to be executed
#include <IO_Files.hh>
Static Public Member Functions
static void reset_errors ()
count an error
static int error_count ()
return the total number of errors
static void syntax_error ()
count and report a parse error
static void expect_apl_errors (const UCS_string &arg)
reset APL errors, expecting cnt
static void apl_error (const char *loc)
count an APL error
static void assert_error ()
count a failed assertion
static void diff_error ()
count a output diff error
static void get_file_line (UTF8_string &line, bool &eof)
get one line from the current file, open the next file if necceessary
static void open_next_file ()
open the next test file
static void next_file ()
close current testcase file (prematurely) and opem mext one
static ofstream & get_current_testreport ()
return the current test report
static void read_file_line (UTF8_string &file_line, bool &eof)
read one line from the current input file with CR and LF removed
Protected Types
enum TestMode {
TM_EXIT_AFTER_LAST_FILE = 1 << 0 ,
TM_EXIT_AFTER_LAST_FILE_IF_OK = 1 << 1 ,
TM_STAY_AFTER_LAST_FILE = 1 << 2 ,
TM_STOP_AFTER_FILE_ERROR = 1 << 3 ,
TM_EXIT_AFTER_FILE_ERROR = 1 << 4 ,
TM_EXIT_AFTER_LINE_ERROR = 1 << 5 ,
TM_STOP_AFTER_LINE_ERROR = 1 << 6 ,
TM_DONE_AFTER_LINE_ERROR
}
how to handle test results
Static Protected Member Functions
static bool end_of_current_file ()
dito (close files, print errors, summary etc).
static void print_summary ()
write testcases summary file
Static Protected Attributes
static enum IO_Files::TestMode test_mode = TM_EXIT_AFTER_LAST_FILE
the desired test mode as per –TM n
static bool need_total = false
true until total error count is printed.
static int testcase_count = 0
the number of testcases provided
static int testcases_done = 0
the number of testcases executed
static int parse_errors = 0
the number of parse errors when executing test file
static int total_errors = 0
the tital number of errors in all test files
static int apl_errors = 0
the number of APL errors when executing in current file
static const char * last_apl_error_loc = ""
the source location where the last APL error was thrown
static int last_apl_error_line = -1
the testcase file line that has triggered the last APL error
static int diff_errors = 0
the number of output differences when executing test file
static int assert_errors = 0
the number of failed assertions when executing test file
static ofstream current_testreport
the current test report
Friends
struct UserPreferences
int main (int argc, const char *argv[])
dito.
Detailed Description
a sequence of files that are still to be executed
handling of Input files. IO_Files reads lines from files until they are all executed. The output of the APL interpreter is compared against the testcase files and mismatches are recorded.
Definition at line 70 of file IO_Files.hh.
Member Enumeration Documentation
TestMode
enum IO_Files::TestMode protected
how to handle test results
Enumerator
TM_EXIT_AFTER_LAST_FILE
exit() after the last testcase file was processed.
TM_EXIT_AFTER_LAST_FILE_IF_OK
exit() after the last testcase file was processed and no error was detected.
TM_STAY_AFTER_LAST_FILE
remain in APL interpreter after the last testcase file was processed.
TM_STOP_AFTER_FILE_ERROR
stop test execution after the first testcase file failed (but remain in the APL interpreter)
TM_EXIT_AFTER_FILE_ERROR
exit() after the first testcase file failed
TM_EXIT_AFTER_LINE_ERROR
exit() after the first comparison (= testcase file line) failed
TM_STOP_AFTER_LINE_ERROR
stop test execution after the first testcase line failed (but
TM_DONE_AFTER_LINE_ERROR
done if the first testcase line has failed
Definition at line 125 of file IO_Files.hh.
Member Function Documentation
apl_error()
void IO_Files::apl_error (const char * loc) static
count an APL error
Definition at line 426 of file IO_Files.cc.
References apl_errors, InputFile::current_file(), InputFile::current_line_no(), last_apl_error_line, and last_apl_error_loc.
Referenced by Command::cmd_CHECK(), end_of_current_file(), and Workspace::immediate_execution().
assert_error()
void IO_Files::assert_error () static
count a failed assertion
Definition at line 440 of file IO_Files.cc.
References assert_errors, and InputFile::current_file().
Referenced by signal_SEGV_handler().
diff_error()
void IO_Files::diff_error () static
count a output diff error
Definition at line 451 of file IO_Files.cc.
References InputFile::close_current_file(), Command::cmd_OFF(), InputFile::current_file(), diff_errors, InputFile::files_todo, test_mode, testcases_done, TM_DONE_AFTER_LINE_ERROR, TM_EXIT_AFTER_LINE_ERROR, and total_errors.
Referenced by DiffOut::overflow().
end_of_current_file()
bool IO_Files::end_of_current_file () static protected
dito (close files, print errors, summary etc).
Definition at line 176 of file IO_Files.cc.
References apl_error(), apl_errors, assert_errors, UserPreferences::auto_OFF, InputFile::close_current_file(), Command::cmd_OFF(), InputFile::current_filename(), current_testreport, diff_errors, error_count(), InputFile::files_todo, InputFile::is_validating(), last_apl_error_line, last_apl_error_loc, Workspace::list_SI(), parse_errors, Value::print_incomplete(), IndexExpr::print_stale(), Value::print_stale(), Output::reset_dout(), reset_errors(), Workspace::SI_entry_count(), test_mode, testcases_done, TM_EXIT_AFTER_FILE_ERROR, TM_STOP_AFTER_FILE_ERROR, and total_errors.
Referenced by get_file_line(), and next_file().
error_count()
static int IO_Files::error_count () inline static
return the total number of errors
Definition at line 86 of file IO_Files.hh.
References apl_errors, assert_errors, diff_errors, and parse_errors.
Referenced by end_of_current_file(), and get_file_line().
expect_apl_errors()
void IO_Files::expect_apl_errors (const UCS_string & arg) static
reset APL errors, expecting cnt
Definition at line 391 of file IO_Files.cc.
References apl_errors, UCS_string::atoi(), last_apl_error_line, and last_apl_error_loc.
get_current_testreport()
static ofstream & IO_Files::get_current_testreport () inline static
return the current test report
Definition at line 114 of file IO_Files.hh.
References current_testreport.
Referenced by DiffOut::overflow().
get_file_line()
void IO_Files::get_file_line (UTF8_string & line, bool & eof) static
get one line from the current file, open the next file if necceessary
Definition at line 48 of file IO_Files.cc.
References UTF8_string::c_str(), Command::cmd_OFF(), InputFile::current_file(), current_testreport, InputFile::echo, end_of_current_file(), error_count(), Workspace::get_LX(), need_total, open_next_file(), print_summary(), Command::process_line(), read_file_line(), UCS_string::size(), test_mode, TM_EXIT_AFTER_LAST_FILE, TM_EXIT_AFTER_LAST_FILE_IF_OK, total_errors, and InputFile::with_LX.
Referenced by InputMux::get_line().
next_file()
void IO_Files::next_file () static
close current testcase file (prematurely) and opem mext one
Definition at line 161 of file IO_Files.cc.
References InputFile::current_file(), end_of_current_file(), and open_next_file().
open_next_file()
void IO_Files::open_next_file () static
open the next test file
Definition at line 311 of file IO_Files.cc.
References InputFile::current_file(), InputFile::current_filename(), current_testreport, InputFile::files_todo, InputFile::open_current_file(), Output::reset_dout(), reset_errors(), and InputFile::set_pushed_pending().
Referenced by get_file_line(), and next_file().
print_summary()
void IO_Files::print_summary () static protected
write testcases summary file
Definition at line 289 of file IO_Files.cc.
References testcase_count, testcases_done, and total_errors.
Referenced by get_file_line().
read_file_line()
void IO_Files::read_file_line (UTF8_string & file_line, bool & eof) static
read one line from the current input file with CR and LF removed
Definition at line 108 of file IO_Files.cc.
References InputFile::check_filter(), InputFile::current_file(), InputFile::current_line_no(), InputFile::file, InputFile::get_html(), InputFile::has_object_filter(), InputFile::set_html(), UTF8_string::starts_with(), and UTF8_string::un_HTML().
Referenced by get_file_line(), and DiffOut::overflow().
reset_errors()
static void IO_Files::reset_errors () inline static
count an error
Definition at line 77 of file IO_Files.hh.
References apl_errors, assert_errors, diff_errors, and parse_errors.
Referenced by end_of_current_file(), and open_next_file().
syntax_error()
void IO_Files::syntax_error () static
count and report a parse error
Definition at line 412 of file IO_Files.cc.
References InputFile::current_file(), current_testreport, and parse_errors.
Friends And Related Function Documentation
main
int main (int argc, const char * argv[]) friend
dito.
Definition at line 611 of file main.cc.
UserPreferences
friend struct UserPreferences friend
Definition at line 73 of file IO_Files.hh.
Member Data Documentation
apl_errors
int IO_Files::apl_errors = 0 static protected
the number of APL errors when executing in current file
Definition at line 174 of file IO_Files.hh.
Referenced by apl_error(), end_of_current_file(), error_count(), expect_apl_errors(), and reset_errors().
assert_errors
int IO_Files::assert_errors = 0 static protected
the number of failed assertions when executing test file
Definition at line 186 of file IO_Files.hh.
Referenced by assert_error(), end_of_current_file(), error_count(), and reset_errors().
current_testreport
ofstream IO_Files::current_testreport static protected
the current test report
Definition at line 189 of file IO_Files.hh.
Referenced by end_of_current_file(), get_current_testreport(), get_file_line(), open_next_file(), and syntax_error().
diff_errors
int IO_Files::diff_errors = 0 static protected
the number of output differences when executing test file
Definition at line 183 of file IO_Files.hh.
Referenced by diff_error(), end_of_current_file(), error_count(), and reset_errors().
last_apl_error_line
int IO_Files::last_apl_error_line = -1 static protected
the testcase file line that has triggered the last APL error
Definition at line 180 of file IO_Files.hh.
Referenced by apl_error(), end_of_current_file(), and expect_apl_errors().
last_apl_error_loc
const char * IO_Files::last_apl_error_loc = "" static protected
the source location where the last APL error was thrown
Definition at line 177 of file IO_Files.hh.
Referenced by apl_error(), end_of_current_file(), and expect_apl_errors().
need_total
bool IO_Files::need_total = false static protected
true until total error count is printed.
Definition at line 159 of file IO_Files.hh.
Referenced by get_file_line(), and UserPreferences::parse_argv_2().
parse_errors
int IO_Files::parse_errors = 0 static protected
the number of parse errors when executing test file
Definition at line 168 of file IO_Files.hh.
Referenced by end_of_current_file(), error_count(), reset_errors(), and syntax_error().
test_mode
IO_Files::TestMode IO_Files::test_mode = TM_EXIT_AFTER_LAST_FILE static protected
the desired test mode as per –TM n
Definition at line 42 of file IO_Files.cc.
Referenced by diff_error(), end_of_current_file(), get_file_line(), and UserPreferences::parse_argv_2().
testcase_count
int IO_Files::testcase_count = 0 static protected
the number of testcases provided
Definition at line 162 of file IO_Files.hh.
Referenced by UserPreferences::parse_argv_2(), and print_summary().
testcases_done
int IO_Files::testcases_done = 0 static protected
the number of testcases executed
Definition at line 165 of file IO_Files.hh.
Referenced by diff_error(), end_of_current_file(), and print_summary().
total_errors
int IO_Files::total_errors = 0 static protected
the tital number of errors in all test files
Definition at line 171 of file IO_Files.hh.
Referenced by diff_error(), end_of_current_file(), get_file_line(), and print_summary().
The documentation for this class was generated from the following files:
src/IO_Files.hh
src/IO_Files.cc