GNU APL: ConstRavel_P Class Reference
ConstRavel_P Class Reference
a "smart" Cell *, remembering its owner and allowing only a subset of what a normal Cell * is capable of.
#include <ConstCell_P.hh>
Public Member Functions
ConstRavel_P (const Value &_owner, bool _inc)
constructor from the owner of the Cell
ConstRavel_P (Value_P _owner, bool _inc)
constructor from pointer to the owner of the Cell
bool operator+ () const
return true iff offset is valid (and then *() != 0). For this to work, increment needs to be true
Cell_offset operator() () const
return the ravel offset of the current Cell
const Cell & operator* () const
return a reference to the current Cell
const Cell * operator-> () const
return a pointer to the current Cell (or 0 at the end)
void operator++ ()
move to the next Cell
const Cell_offset get_length () const
return the lengths of the Cells
const Value & get_owner () const
return the owner of the Cells
Protected Attributes
const Value & owner
the owner of the ravel
const Cell_offset end
position of the first Cell after the ravel
Cell_offset offset
the current offset
const bool increment
whether operator ++() shall increment offset
Detailed Description
a "smart" Cell *, remembering its owner and allowing only a subset of what a normal Cell * is capable of.
Definition at line 120 of file ConstCell_P.hh.
Constructor & Destructor Documentation
ConstRavel_P() [1/2]
ConstRavel_P::ConstRavel_P (const Value & _owner, bool _inc) inline
constructor from the owner of the Cell
Definition at line 124 of file ConstCell_P.hh.
ConstRavel_P() [2/2]
ConstRavel_P::ConstRavel_P (Value_P _owner, bool _inc) inline
constructor from pointer to the owner of the Cell
Definition at line 132 of file ConstCell_P.hh.
Member Function Documentation
get_length()
const Cell_offset ConstRavel_P::get_length () const inline
return the lengths of the Cells
Definition at line 161 of file ConstCell_P.hh.
References end.
Referenced by Bif_F12_ENCODE::encode_Cpx(), Bif_F12_ENCODE::encode_Flt(), and Bif_F12_ENCODE::encode_Int().
get_owner()
const Value & ConstRavel_P::get_owner () const inline
return the owner of the Cells
Definition at line 165 of file ConstCell_P.hh.
References owner.
operator()()
Cell_offset ConstRavel_P::operator() () const inline
return the ravel offset of the current Cell
Definition at line 145 of file ConstCell_P.hh.
References offset.
operator*()
const Cell & ConstRavel_P::operator* () const inline
return a reference to the current Cell
Definition at line 149 of file ConstCell_P.hh.
References Value::get_cravel(), offset, and owner.
operator+()
bool ConstRavel_P::operator+ () const inline
return true iff offset is valid (and then *() != 0). For this to work, increment needs to be true
Definition at line 141 of file ConstCell_P.hh.
References end, increment, and offset.
Referenced by operator->().
operator++()
void ConstRavel_P::operator++ () inline
move to the next Cell
Definition at line 157 of file ConstCell_P.hh.
References increment, and offset.
operator->()
const Cell * ConstRavel_P::operator-> () const inline
return a pointer to the current Cell (or 0 at the end)
Definition at line 153 of file ConstCell_P.hh.
References Value::get_cravel(), offset, operator+(), and owner.
Member Data Documentation
end
const Cell_offset ConstRavel_P::end protected
position of the first Cell after the ravel
Definition at line 173 of file ConstCell_P.hh.
Referenced by get_length(), and operator+().
increment
const bool ConstRavel_P::increment protected
whether operator ++() shall increment offset
Definition at line 179 of file ConstCell_P.hh.
Referenced by operator+(), and operator++().
offset
Cell_offset ConstRavel_P::offset protected
the current offset
Definition at line 176 of file ConstCell_P.hh.
Referenced by operator()(), operator*(), operator+(), operator++(), and operator->().
owner
const Value& ConstRavel_P::owner protected
the owner of the ravel
Definition at line 170 of file ConstCell_P.hh.
Referenced by get_owner(), operator*(), and operator->().
The documentation for this class was generated from the following file:
src/ConstCell_P.hh