GNU APL: Quad_FIO Class Reference
Quad_FIO Class Reference
The class implementing ⎕FIO.
#include <Quad_FIO.hh>
Classes
struct _sub_fun
a mapping between function names and function numbers
struct file_entry
one file (openend with open(), fopen(), or fdopen()). : handle == fd, and FILE * may or may not exist for fd
Public Types
enum { SMALL_BUF = 5000 }
the default buffer size if the user does not provide one
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Member Functions
Quad_FIO ()
Constructor.
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB().
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
overloaded Function::eval_AXB().
virtual Token eval_XB (Value_P X, Value_P B) const
overloaded Function::eval_AXB().
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B().
Public Member Functions inherited from QuadFunction
QuadFunction (TokenTag tag)
Constructor.
virtual bool has_alpha () const
overloaded Function::has_alpha()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B().
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB().
virtual bool has_result () const
overloaded Function::has_result()
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
virtual bool has_result () const
overloaded Function::has_result()
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Static Public Member Functions
static int close_handle (int handle)
close a file descriptor (and its FILE * if any)
static int do_FIO_57 (const UCS_string &B, char *const *envp)
fork(), execve(), and return a connection to fd 3 of forked process
static Unicode fget_utf8 (FILE *file, ShapeItem &fget_count)
get one Unicode from file
static void clear ()
close all open files
Static Public Attributes
static Quad_FIO * fun = &Quad_FIO::_fun
Built-in function.
static Quad_FIO _fun
Built-in function.
static uint64_t benchmark_cycles_from = 0
cycle counter at start of a benchmark (⎕FIO[-1])
Protected Member Functions
virtual bool is_operator () const
overloaded Function::is_operator()
virtual int get_fun_valence () const
overloaded Function::get_fun_valence()
virtual int get_oper_valence () const
overloaded Function::get_oper_valence().
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
overloaded Function::eval_ALXB().
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
overloaded Function::eval_LXB().
virtual bool has_subfuns () const
overloaded Function::has_subfuns()
virtual sAxis subfun_to_axis (const UCS_string &name) const
overloaded Function::subfun_to_axis
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Static Protected Member Functions
static Value_P get_random (APL_Integer mode, APL_Integer len)
return one or more random values
static FILE * get_FILE (int handle)
return the open FILE * for (APL integer) handle
static file_entry & get_file_entry (int handle)
return the open file for (APL integer) handle
static file_entry & get_file_entry (const Value &handle)
return the open file for (APL integer) handle
static FILE * get_FILE (const Value &handle)
return the open FILE * (APL integer) handle
static int get_fd (const Value &value)
return the open file descriptor for (APL integer) handle
static void group_thousands (UCS_string &dest, char *buffer, bool flt)
append ASCII-buffer buffer to dest, inserting thousands' separators. Note: buffer may be modified.
static void UNSAFE (const char *funname, int funnum)
throw a DOMAIN error if the interpreter runs in safe mode.
static Token list_functions (ostream &out, bool mapping)
list all ⎕IO functions to out
static Value_P fds_to_val (fd_set *fds, int max_fd)
convert bits set in fds to an APL integer vector
static Token do_printf (FILE *out, Value_P A)
printf A to out
static void do_sprintf (UCS_string &UZ, const UCS_string &A_format, const Value *B, int B_start)
sprintf with format string A and Data items B
static Token do_scanf (File_or_String &input, const UCS_string &format, int function_number)
perform an fscanf() from file
static int axis_compare (const void *key, const void *sf)
compare two axis strings (function names)
static int function_name_to_int (const char *function_name)
find function number for function name, -1 if not found
Static Protected Attributes
static _sub_fun sub_functions []
a mapping between function names and function numbers
static std::vector< file_entry > open_files
the open files
Additional Inherited Members
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
The class implementing ⎕FIO.
The system function Quad-FIO (File I/O)
Definition at line 41 of file Quad_FIO.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
the default buffer size if the user does not provide one
Definition at line 48 of file Quad_FIO.hh.
Constructor & Destructor Documentation
Quad_FIO()
Quad_FIO::Quad_FIO ()
Constructor.
Definition at line 122 of file Quad_FIO.cc.
References UTF8_string::append_ASCII(), open_files, and Quad_FIO::file_entry::path.
Member Function Documentation
axis_compare()
int Quad_FIO::axis_compare (const void * key, const void * sf) static protected
compare two axis strings (function names)
Definition at line 84 of file Quad_FIO.cc.
Referenced by function_name_to_int().
clear()
void Quad_FIO::clear () static
close all open files
Definition at line 146 of file Quad_FIO.cc.
References Quad_FIO::file_entry::fe_fd, Quad_FIO::file_entry::fe_FILE, open_files, and Quad_FIO::file_entry::path.
Referenced by Workspace::clear_WS().
close_handle()
int Quad_FIO::close_handle (int handle) static
close a file descriptor (and its FILE * if any)
Definition at line 175 of file Quad_FIO.cc.
References Quad_FIO::file_entry::fe_fd, Quad_FIO::file_entry::fe_FILE, and open_files.
Referenced by Quad_GTK::close_window(), and Quad_GTK::open_window().
do_FIO_57()
int Quad_FIO::do_FIO_57 (const UCS_string & B, char *const * envp) static
fork(), execve(), and return a connection to fd 3 of forked process
Definition at line 2282 of file Quad_FIO.cc.
References UTF8_string::c_str(), Quad_FIO::file_entry::fe_fd, Quad_FIO::file_entry::fe_may_read, Quad_FIO::file_entry::fe_may_write, and open_files.
Referenced by eval_XB(), and Quad_GTK::open_window().
do_printf()
Token Quad_FIO::do_printf (FILE * out, Value_P A) static protected
printf A to out
Definition at line 243 of file Quad_FIO.cc.
References UTF8_string::c_str(), do_sprintf(), and UCS_string::size().
Referenced by eval_AXB().
do_scanf()
Token Quad_FIO::do_scanf (File_or_String & input, const UCS_string & format, int function_number) static protected
perform an fscanf() from file
Definition at line 701 of file Quad_FIO.cc.
References UCS_string::append(), UCS_string::back(), UCS_string::contains(), File_or_String::get_count(), File_or_String::get_next(), File_or_String::scanf_double(), File_or_String::scanf_long_long(), UCS_string::size(), and File_or_String::unget().
Referenced by eval_AXB().
do_sprintf()
void Quad_FIO::do_sprintf (UCS_string & UZ, const UCS_string & A_format, const Value * B, int B_start) static protected
sprintf with format string A and Data items B
Definition at line 259 of file Quad_FIO.cc.
References UCS_string::append(), UCS_string::append_ASCII(), UCS_string::append_UTF8(), Value_P_Base::get(), Workspace::get_FC(), Cell::get_int_value(), Cell::get_real_value(), group_thousands(), Cell::is_integer_cell(), and UCS_string::size().
Referenced by do_printf(), and eval_AXB().
eval_AB()
Token Quad_FIO::eval_AB (Value_P A, Value_P B) const virtual
overloaded Function::eval_AB().
Reimplemented from QuadFunction.
Definition at line 1299 of file Quad_FIO.cc.
References ConstCell_P::get_length(), Probe::get_time(), Probe::init(), list_functions(), and Probe::PROBE_COUNT.
Referenced by eval_ALXB().
eval_ALXB()
Token Quad_FIO::eval_ALXB (Value_P A, Token & LO, Value_P X, Value_P B) const protected virtual
overloaded Function::eval_ALXB().
Reimplemented from Function.
Definition at line 1349 of file Quad_FIO.cc.
References benchmark_cycles_from, eval_AB(), fun, Token::get_function(), Token::get_tag(), StateIndicator::set_safe_execution(), and Workspace::SI_top().
eval_AXB()
Token Quad_FIO::eval_AXB (Value_P A, Value_P X, Value_P B) const virtual
overloaded Function::eval_AXB().
Reimplemented from Function.
Definition at line 2360 of file Quad_FIO.cc.
References SockAddr::addr, UTF8_string::c_str(), do_printf(), do_scanf(), do_sprintf(), Quad_FIO::file_entry::fe_fd, Quad_FIO::file_entry::fe_may_read, Quad_FIO::file_entry::fe_may_write, Bif_OPER2_INNER::fun, fun, function_name_to_int(), Function::get_dyadic_threshold(), get_fd(), get_FILE(), Token::get_function(), Function::get_monadic_threshold(), Cell::get_pointer_value(), get_random(), SockAddr::inet, Token::is_function(), Cell::is_pointer_cell(), list_functions(), open_files, Quad_FIO::file_entry::path, Function::set_dyadic_threshold(), Function::set_monadic_threshold(), and Tokenizer::tokenize_function().
eval_B()
Token Quad_FIO::eval_B (Value_P B) const virtual
overloaded Function::eval_B().
Reimplemented from QuadFunction.
Definition at line 1120 of file Quad_FIO.cc.
References Value::fast_new_count, StateIndicator::get_parent(), UCS_string::get_total_count(), Avec::IBM_quad_AV(), Probe::init_all(), list_functions(), open_files, Workspace::SI_top(), and Value::slow_new_count.
Referenced by eval_LXB().
eval_LXB()
Token Quad_FIO::eval_LXB (Token & LO, Value_P X, Value_P B) const protected virtual
overloaded Function::eval_LXB().
Reimplemented from Function.
Definition at line 1386 of file Quad_FIO.cc.
References benchmark_cycles_from, Token::ChangeTag(), StateIndicator::clear_safe_execution(), Bif_OPER1_EACH::do_eval_LB(), eval_B(), eval_XB(), fun, Token::get_apl_val(), Token::get_function(), Token::get_tag(), StateIndicator::set_safe_execution(), and Workspace::SI_top().
eval_XB()
Token Quad_FIO::eval_XB (Value_P X, Value_P B) const virtual
overloaded Function::eval_AXB().
Reimplemented from Function.
Definition at line 1445 of file Quad_FIO.cc.
References Shape::add_shape_item(), SockAddr::addr, UTF8_string::c_str(), do_FIO_57(), fds_to_val(), Quad_FIO::file_entry::fe_errno, Quad_FIO::file_entry::fe_fd, Quad_FIO::file_entry::fe_FILE, Quad_FIO::file_entry::fe_may_read, Quad_FIO::file_entry::fe_may_write, Bif_OPER2_INNER::fun, Bif_OPER2_OUTER::fun, fun, function_name_to_int(), Value_P_Base::get(), Statistics_record::get_count(), Function::get_dyadic_threshold(), get_fd(), get_FILE(), get_file_entry(), Statistics::get_first_record(), Token::get_function(), Function::get_monadic_threshold(), Statistics::get_name(), get_random(), Statistics::get_record(), Performance::get_statistics(), Performance::get_statistics_type(), Statistics_record::get_sum(), Statistics_record::get_sum2(), SockAddr::inet, Token::is_function(), list_functions(), open_files, Quad_FIO::file_entry::path, Statistics::reset(), Tokenizer::tokenize_function(), and UNSAFE().
Referenced by eval_LXB().
fds_to_val()
Value_P Quad_FIO::fds_to_val (fd_set * fds, int max_fd) static protected
convert bits set in fds to an APL integer vector
Definition at line 224 of file Quad_FIO.cc.
Referenced by eval_XB().
fget_utf8()
Unicode Quad_FIO::fget_utf8 (FILE * file, ShapeItem & fget_count) static
get one Unicode from file
Definition at line 506 of file Quad_FIO.cc.
Referenced by File_or_String::get_next().
function_name_to_int()
int Quad_FIO::function_name_to_int (const char * function_name) static protected
find function number for function name, -1 if not found
Definition at line 91 of file Quad_FIO.cc.
References axis_compare(), and sub_functions.
Referenced by eval_AXB(), eval_XB(), and subfun_to_axis().
get_fd()
static int Quad_FIO::get_fd (const Value & value) inline static protected
return the open file descriptor for (APL integer) handle
Definition at line 166 of file Quad_FIO.hh.
References Quad_FIO::file_entry::fe_fd, and get_file_entry().
Referenced by eval_AXB(), and eval_XB().
get_FILE() [1/2]
static FILE * Quad_FIO::get_FILE (const Value & handle) inline static protected
return the open FILE * (APL integer) handle
Definition at line 162 of file Quad_FIO.hh.
References Value::get_cscalar(), get_FILE(), and Cell::get_near_int().
get_FILE() [2/2]
FILE * Quad_FIO::get_FILE (int handle) static protected
return the open FILE * for (APL integer) handle
Definition at line 202 of file Quad_FIO.cc.
References Quad_FIO::file_entry::fe_fd, Quad_FIO::file_entry::fe_FILE, Quad_FIO::file_entry::fe_may_read, Quad_FIO::file_entry::fe_may_write, and get_file_entry().
Referenced by eval_AXB(), eval_XB(), and get_FILE().
get_file_entry() [1/2]
static file_entry & Quad_FIO::get_file_entry (const Value & handle) inline static protected
return the open file for (APL integer) handle
Definition at line 158 of file Quad_FIO.hh.
References Value::get_cscalar(), get_file_entry(), and Cell::get_near_int().
get_file_entry() [2/2]
Quad_FIO::file_entry & Quad_FIO::get_file_entry (int handle) static protected
return the open file for (APL integer) handle
Definition at line 162 of file Quad_FIO.cc.
References open_files.
Referenced by eval_XB(), get_fd(), get_FILE(), and get_file_entry().
get_fun_valence()
virtual int Quad_FIO::get_fun_valence () const inline protected virtual
overloaded Function::get_fun_valence()
Reimplemented from Function.
Definition at line 85 of file Quad_FIO.hh.
get_oper_valence()
virtual int Quad_FIO::get_oper_valence () const inline protected virtual
overloaded Function::get_oper_valence().
Reimplemented from Function.
Definition at line 88 of file Quad_FIO.hh.
get_random()
Value_P Quad_FIO::get_random (APL_Integer mode, APL_Integer len) static protected
return one or more random values
Definition at line 467 of file Quad_FIO.cc.
Referenced by eval_AXB(), and eval_XB().
group_thousands()
void Quad_FIO::group_thousands (UCS_string & dest, char * buffer, bool flt) static protected
append ASCII-buffer buffer to dest, inserting thousands' separators. Note: buffer may be modified.
Definition at line 430 of file Quad_FIO.cc.
References UCS_string::append(), UCS_string::append_ASCII(), Workspace::get_FC(), and group_thousands().
Referenced by do_sprintf(), and group_thousands().
has_subfuns()
virtual bool Quad_FIO::has_subfuns () const inline protected virtual
overloaded Function::has_subfuns()
Reimplemented from Function.
Definition at line 97 of file Quad_FIO.hh.
is_operator()
virtual bool Quad_FIO::is_operator () const inline protected virtual
overloaded Function::is_operator()
Reimplemented from Function.
Definition at line 82 of file Quad_FIO.hh.
list_functions()
Token Quad_FIO::list_functions (ostream & out, bool mapping) static protected
list all ⎕IO functions to out
Definition at line 976 of file Quad_FIO.cc.
References Quad_FIO::_sub_fun::key, sub_functions, and Quad_FIO::_sub_fun::val.
Referenced by eval_AB(), eval_AXB(), eval_B(), and eval_XB().
subfun_to_axis()
sAxis Quad_FIO::subfun_to_axis (const UCS_string & name) const protected virtual
overloaded Function::subfun_to_axis
Reimplemented from Function.
Definition at line 116 of file Quad_FIO.cc.
References UTF8_string::c_str(), and function_name_to_int().
UNSAFE()
static void Quad_FIO::UNSAFE (const char * funname, int funnum) inline static protected
throw a DOMAIN error if the interpreter runs in safe mode.
Definition at line 177 of file Quad_FIO.hh.
References UserPreferences::safe_mode.
Referenced by eval_XB().
Member Data Documentation
_fun
Quad_FIO Quad_FIO::_fun static
Built-in function.
Definition at line 69 of file Quad_FIO.hh.
benchmark_cycles_from
uint64_t Quad_FIO::benchmark_cycles_from = 0 static
cycle counter at start of a benchmark (⎕FIO[-1])
Definition at line 78 of file Quad_FIO.hh.
Referenced by eval_ALXB(), eval_LXB(), and Command::finish_context().
fun
Quad_FIO * Quad_FIO::fun = &Quad_FIO::_fun static
Built-in function.
Definition at line 68 of file Quad_FIO.hh.
Referenced by eval_ALXB(), eval_AXB(), eval_LXB(), and eval_XB().
open_files
std::vector< Quad_FIO::file_entry > Quad_FIO::open_files static protected
the open files
Definition at line 211 of file Quad_FIO.hh.
Referenced by clear(), close_handle(), do_FIO_57(), eval_AXB(), eval_B(), eval_XB(), get_file_entry(), and Quad_FIO().
sub_functions
Quad_FIO::_sub_fun Quad_FIO::sub_functions static protected
Initial value:
=
{
#define fiodef(N, name)
}
a mapping between function names and function numbers
Definition at line 117 of file Quad_FIO.hh.
Referenced by function_name_to_int(), and list_functions().
The documentation for this class was generated from the following files:
src/Quad_FIO.hh
src/Quad_FIO.cc