GNU APL: Quad_CR::Picker Class Reference
Quad_CR::Picker Class Reference
the left argument of Pick (⊃) which selects a sub-item of a variable being constructed
#include <Quad_CR.hh>
Public Member Functions
Picker (const UCS_string &vname)
constructor: Picket at top (= variable) level
void push (const Shape &sh, ShapeItem pidx)
push sh on shapes stack and pidx on indices stack
void pop ()
pop shapes and indices
void get (UCS_string &result)
varname or pick of varname
void get_indexed (UCS_string &result, ShapeItem pos, ShapeItem len)
indexed varname or pick of varname
int get_level () const
the pick depth (⍴A for A⊃B)
Protected Attributes
const UCS_string & var_name
the name of the variable from which we pick
std::vector< Shape > shapes
the shapes along the pick
std::vector< ShapeItem > indices
the indices along the pick
Detailed Description
the left argument of Pick (⊃) which selects a sub-item of a variable being constructed
Definition at line 170 of file Quad_CR.hh.
Constructor & Destructor Documentation
Picker()
Quad_CR::Picker::Picker (const UCS_string & vname) inline
constructor: Picket at top (= variable) level
Definition at line 174 of file Quad_CR.hh.
Member Function Documentation
get()
void Quad_CR::Picker::get (UCS_string & result)
varname or pick of varname
Definition at line 833 of file Quad_CR.cc.
References UCS_string::append(), UCS_string::append_shape(), UCS_string::append_UTF8(), Shape::get_rank(), indices, shapes, and var_name.
Referenced by Quad_CR::do_CR10_value().
get_indexed()
void Quad_CR::Picker::get_indexed (UCS_string & result, ShapeItem pos, ShapeItem len)
indexed varname or pick of varname
Definition at line 869 of file Quad_CR.cc.
References UCS_string::append_number(), and UCS_string::append_UTF8().
Referenced by Quad_CR::do_CR10_value().
get_level()
int Quad_CR::Picker::get_level () const inline
the pick depth (⍴A for A⊃B)
Definition at line 199 of file Quad_CR.hh.
References shapes.
Referenced by Quad_CR::do_CR10_value(), and Quad_CR::short_ravel().
pop()
void Quad_CR::Picker::pop () inline
pop shapes and indices
Definition at line 186 of file Quad_CR.hh.
References indices, and shapes.
Referenced by Quad_CR::do_CR10_value().
push()
void Quad_CR::Picker::push (const Shape & sh, ShapeItem pidx) inline
push sh on shapes stack and pidx on indices stack
Definition at line 179 of file Quad_CR.hh.
References indices, and shapes.
Referenced by Quad_CR::do_CR10_value().
Member Data Documentation
indices
std::vector<ShapeItem> Quad_CR::Picker::indices protected
the indices along the pick
Definition at line 210 of file Quad_CR.hh.
Referenced by get(), pop(), and push().
shapes
std::vector<Shape> Quad_CR::Picker::shapes protected
the shapes along the pick
Definition at line 207 of file Quad_CR.hh.
Referenced by get(), get_level(), pop(), and push().
var_name
const UCS_string& Quad_CR::Picker::var_name protected
the name of the variable from which we pick
Definition at line 204 of file Quad_CR.hh.
Referenced by get().
The documentation for this class was generated from the following files:
src/Quad_CR.hh
src/Quad_CR.cc