GNU APL: StateIndicator Class Reference
StateIndicator Class Reference
One entry of the state indicator (SI) of the APL interpreter.
#include <StateIndicator.hh>
Public Member Functions
StateIndicator (const Executable *exec, StateIndicator *_par)
constructor
~StateIndicator ()
destructor
void goon (Function_Line N, const char *loc)
continue this StateIndicator (to line N after →N back into it)
void retry (const char *loc)
retry this StateIndicator (after →'')
bool uses_function (const UserFunction *ufun) const
return true iff (1) this SI entry is executing funname, or (2) has resolved funname on its prefix parser stack
UCS_string function_name () const
Return the function name, or "*" for an immediate execution context.
void list (ostream &out, SI_mode mode) const
list the stack entry (for commands ]SI,)SI, and)SIS)
void print (ostream &out) const
list the stack entry (for command ]SI)
ostream & indent (ostream &out) const
print spaces according to level
const Executable * get_executable () const
return pointer to the current user function, statements, or execute
Unicode get_parse_mode_name () const
return the name of the parse mode
Function_PC get_PC () const
return the current PC
void set_PC (Function_PC new_pc)
set the current PC
ParseMode get_parse_mode () const
return the mode of this entry
Token jump (Value_P val)
evaluate a →N statement. Update pc, return true iff context has changed
SI_level get_level () const
return the nesting level (oldest SI has level 0, next has level 1, ...)
Function_Line get_line () const
return the current line number
void statement_result (Token &result, bool trace)
Maybe print B (according to tag) and erase B.
void escape ()
Escape from user function (exit from each invocation until immediate execution is reached)
Token run ()
execute token in body...
void unmark_all_values () const
clear the marked bit in the executable, in the fun_oper_cache, and in all parsers
int show_owners (ostream &out, const Value &value) const
print all owners of value
void info (ostream &out, const char *loc) const
print a short debug info
Value_P get_L (UCS_string &function)
return left arg (and set function)
void set_L (Value_P value)
change left arg
Value_P get_R (UCS_string &function)
return right arg (and set function)
void set_R (Value_P value)
change right arg
Value_P get_X (UCS_string &function)
return axis arg (and set function)
void set_X (Value_P value)
change axis arg
bool is_safe_execution_start () const
return true if this SI entry has entered safe execution mode (via ⎕EC)
int get_safe_execution () const
return the number of pending ⎕ECs (or other safe execution contexts)
void set_safe_execution ()
set safe_execution mode
void clear_safe_execution ()
clear safe_execution mode
Prefix & get_prefix ()
get the current prefix parser
const Prefix & get_prefix () const
get the current prefix parser
StateIndicator * get_parent () const
return the SI that has called this one
SI_level nth_push (const Symbol *sym, int from_tos) const
return the level at which sym is pushed for the nth. time
Static Public Member Functions
static Error & get_error (StateIndicator *si)
return the error related info in this context
static const Error & get_error (const StateIndicator *si)
return the error related info in this context
static const StateIndicator * find_child (const StateIndicator *parent)
return the child SI (if any) that parent has called
Public Attributes
DerivedFunctionCache fun_oper_cache
a small storage for DerivedFunction objects.
Static Public Attributes
static Error top_level_error
error when)SI is empty
Protected Attributes
const Executable * executable
the user function that is being executed
int safe_execution_count
the number of pending ⎕EC calles
const SI_level level
The nesting level (of sub-executions)
Error error
details of the last error in this context.
Prefix current_stack
the current-stack of this context.
StateIndicator * parent
the StateIndicator that has called this one
Friends
class XML_Loading_Archive
class XML_Saving_Archive
Detailed Description
One entry of the state indicator (SI) of the APL interpreter.
One entry of the state indicator (SI) of the APL interpreter. Compared to e.g. C++, the state indicator is (one element of) the function call stack of the interpreter.
Definition at line 40 of file StateIndicator.hh.
Constructor & Destructor Documentation
StateIndicator()
StateIndicator::StateIndicator (const Executable * exec, StateIndicator * _par)
constructor
Definition at line 35 of file StateIndicator.cc.
~StateIndicator()
StateIndicator::~StateIndicator ()
destructor
Definition at line 45 of file StateIndicator.cc.
References Prefix::clean_up(), current_stack, executable, fun_oper_cache, Executable::get_exec_ufun(), get_executable(), get_parse_mode(), UserFunction::pop_local_vars(), and DerivedFunctionCache::reset().
Member Function Documentation
clear_safe_execution()
void StateIndicator::clear_safe_execution () inline
clear safe_execution mode
Definition at line 167 of file StateIndicator.hh.
References parent, and safe_execution_count.
Referenced by Quad_EC::eoc(), and Quad_FIO::eval_LXB().
escape()
void StateIndicator::escape ()
Escape from user function (exit from each invocation until immediate execution is reached)
Definition at line 350 of file StateIndicator.cc.
Referenced by Workspace::clear_SI(), Command::do_APL_expression(), and Command::finish_context().
find_child()
const StateIndicator * StateIndicator::find_child (const StateIndicator * parent) static
return the child SI (if any) that parent has called
Definition at line 443 of file StateIndicator.cc.
References get_parent(), parent, and Workspace::SI_top().
Referenced by Quad_SI::eval_B().
function_name()
UCS_string StateIndicator::function_name () const
Return the function name, or "*" for an immediate execution context.
Definition at line 137 of file StateIndicator.cc.
References UCS_string::append(), executable, Executable::get_name(), and get_parse_mode().
get_error() [1/2]
static const Error & StateIndicator::get_error (const StateIndicator * si) inline static
return the error related info in this context
Definition at line 128 of file StateIndicator.hh.
References error, and top_level_error.
get_error() [2/2]
static Error & StateIndicator::get_error (StateIndicator * si) inline static
return the error related info in this context
Definition at line 124 of file StateIndicator.hh.
References error, and top_level_error.
get_executable()
const Executable * StateIndicator::get_executable () const inline
return pointer to the current user function, statements, or execute
Definition at line 76 of file StateIndicator.hh.
References executable.
Referenced by Quad_SI::eval_AB(), Quad_SI::eval_B(), XML_Loading_Archive::find_lambda(), Command::finish_context(), goon(), jump(), nth_push(), Workspace::pop_SI(), Workspace::push_SI(), XML_Saving_Archive::save_SI_entry(), Doxy::SI_table(), Error::update_error_info(), and ~StateIndicator().
get_L()
Value_P StateIndicator::get_L (UCS_string & function)
return left arg (and set function)
Definition at line 401 of file StateIndicator.cc.
References current_stack, and Prefix::locate_L().
get_level()
SI_level StateIndicator::get_level () const inline
return the nesting level (oldest SI has level 0, next has level 1, ...)
Definition at line 98 of file StateIndicator.hh.
References level.
Referenced by Quad_SI::eval_AB(), XML_Loading_Archive::find_lambda(), nth_push(), Workspace::pop_SI(), Prefix::print_stack(), Workspace::push_SI(), Prefix::reduce_statements(), XML_Saving_Archive::save_SI_entry(), Workspace::SI_entry_count(), and Doxy::SI_table().
get_line()
Function_Line StateIndicator::get_line () const
return the current line number
Definition at line 482 of file StateIndicator.cc.
References executable, Executable::get_line(), and get_PC().
Referenced by Nabla::edit(), Quad_INP::eval_XB(), Quad_QUOTE::get_apl_value(), goon(), Command::process_line(), Quad_INP::read_strings(), and Quad_Quad::resolve().
get_parent()
StateIndicator * StateIndicator::get_parent () const inline
return the SI that has called this one
Definition at line 182 of file StateIndicator.hh.
References parent.
Referenced by Symbol::assign_named_lambda(), Workspace::clear_error(), Quad_SI::eval_AB(), Quad_FIO::eval_B(), find_child(), Command::finish_context(), Quad_EM::get_apl_value(), Quad_ET::get_apl_value(), Quad_LC::get_apl_value(), Workspace::is_called(), Workspace::list_SI(), nth_push(), Workspace::oldest_exec(), Workspace::pop_SI(), XML_Saving_Archive::save(), Workspace::show_owners(), Doxy::SI_table(), Workspace::SI_top_error(), Workspace::SI_top_fun(), Workspace::unmark_all_values(), Error::update_error_info(), and uses_function().
get_parse_mode()
ParseMode StateIndicator::get_parse_mode () const inline
return the mode of this entry
Definition at line 91 of file StateIndicator.hh.
References executable, and Executable::get_parse_mode().
Referenced by Command::do_APL_expression(), Command::finish_context(), function_name(), get_parse_mode_name(), jump(), list(), print(), Doxy::SI_table(), and ~StateIndicator().
get_parse_mode_name()
Unicode StateIndicator::get_parse_mode_name () const
return the name of the parse mode
Definition at line 612 of file StateIndicator.cc.
References get_parse_mode().
Referenced by info(), Workspace::pop_SI(), Doxy::SI_table(), and statement_result().
get_PC()
Function_PC StateIndicator::get_PC () const inline
return the current PC
Definition at line 83 of file StateIndicator.hh.
References current_stack, and Prefix::get_PC().
Referenced by Quad_SI::eval_AB(), Quad_SI::eval_B(), get_line(), info(), list(), print(), XML_Saving_Archive::save_SI_entry(), statement_result(), and Error::update_error_info().
get_prefix() [1/2]
Prefix & StateIndicator::get_prefix () inline
get the current prefix parser
Definition at line 174 of file StateIndicator.hh.
References current_stack.
Referenced by Bif_F12_RHO::eval_AB(), Bif_F12_COMMA::eval_B(), Bif_F12_COMMA1::eval_B(), Command::finish_context(), Prefix::reduce_statements(), Doxy::SI_table(), and Error::update_error_info().
get_prefix() [2/2]
const Prefix & StateIndicator::get_prefix () const inline
get the current prefix parser
Definition at line 178 of file StateIndicator.hh.
References current_stack.
get_R()
Value_P StateIndicator::get_R (UCS_string & function)
return right arg (and set function)
Definition at line 408 of file StateIndicator.cc.
References current_stack, and Prefix::locate_R().
get_safe_execution()
int StateIndicator::get_safe_execution () const inline
return the number of pending ⎕ECs (or other safe execution contexts)
Definition at line 156 of file StateIndicator.hh.
References safe_execution_count.
Referenced by Command::finish_context().
get_X()
Value_P StateIndicator::get_X (UCS_string & function)
return axis arg (and set function)
Definition at line 415 of file StateIndicator.cc.
References current_stack, and Prefix::locate_X().
goon()
void StateIndicator::goon (Function_Line N, const char * loc)
continue this StateIndicator (to line N after →N back into it)
Definition at line 70 of file StateIndicator.cc.
References current_stack, Executable::get_exec_ufun(), get_executable(), get_line(), level, UserFunction::pc_for_line(), Prefix::reset(), and set_PC().
Referenced by Command::finish_context().
indent()
ostream & StateIndicator::indent (ostream & out) const
print spaces according to level
Definition at line 295 of file StateIndicator.cc.
References level.
info()
void StateIndicator::info (ostream & out, const char * loc) const
print a short debug info
Definition at line 392 of file StateIndicator.cc.
References executable, Executable::get_loc(), get_parse_mode_name(), get_PC(), Executable::get_text(), and level.
Referenced by Bif_F1_EXECUTE::execute_statement().
is_safe_execution_start()
bool StateIndicator::is_safe_execution_start () const inline
return true if this SI entry has entered safe execution mode (via ⎕EC)
Definition at line 150 of file StateIndicator.hh.
References parent, and safe_execution_count.
Referenced by Command::finish_context().
jump()
Token StateIndicator::jump (Value_P val)
evaluate a →N statement. Update pc, return true iff context has changed
Definition at line 314 of file StateIndicator.cc.
References Executable::get_exec_ufun(), get_executable(), get_parse_mode(), UserFunction::pc_for_line(), and set_PC().
list()
void StateIndicator::list (ostream & out, SI_mode mode) const
list the stack entry (for commands ]SI,)SI, and)SIS)
Definition at line 211 of file StateIndicator.cc.
References error, executable, Error::get_error_code(), Error::get_error_line_2(), Error::get_error_line_3(), Executable::get_exec_ufun(), UserFunction::get_name_and_line(), get_parse_mode(), get_PC(), print(), UserFunction::print_local_vars(), UCS_string::size(), and Executable::statement_text().
nth_push()
int StateIndicator::nth_push (const Symbol * sym, int from_tos) const
return the level at which sym is pushed for the nth. time
Definition at line 455 of file StateIndicator.cc.
References get_executable(), get_level(), get_parent(), Executable::pushes_sym(), and Workspace::SI_top().
Referenced by Symbol::get_SI_level().
print()
void StateIndicator::print (ostream & out) const
list the stack entry (for command ]SI)
Definition at line 166 of file StateIndicator.cc.
References error, executable, Executable::get_body(), Error::get_error_code(), Error::get_error_line_1(), Error::get_error_line_2(), Error::get_error_line_3(), Executable::get_exec_ufun(), UserFunction::get_name_and_line(), get_parse_mode(), get_PC(), Executable::get_text(), Error::get_throw_loc(), level, safe_execution_count, and Executable::statement_text().
Referenced by list().
retry()
void StateIndicator::retry (const char * loc)
retry this StateIndicator (after →'')
Definition at line 96 of file StateIndicator.cc.
Referenced by Command::finish_context().
run()
Token StateIndicator::run ()
execute token in body...
Definition at line 355 of file StateIndicator.cc.
References current_stack, level, and Prefix::reduce_statements().
Referenced by Executable::execute_body().
set_L()
void StateIndicator::set_L (Value_P value)
change left arg
Definition at line 422 of file StateIndicator.cc.
References current_stack, and Prefix::locate_L().
Referenced by Quad_L::assign().
set_PC()
void StateIndicator::set_PC (Function_PC new_pc) inline
set the current PC
Definition at line 87 of file StateIndicator.hh.
References current_stack, and Prefix::set_PC().
Referenced by goon(), jump(), and XML_Loading_Archive::read_SI_entry().
set_R()
void StateIndicator::set_R (Value_P value)
change right arg
Definition at line 429 of file StateIndicator.cc.
References current_stack, and Prefix::locate_R().
Referenced by Quad_R::assign().
set_safe_execution()
void StateIndicator::set_safe_execution () inline
set safe_execution mode
Definition at line 160 of file StateIndicator.hh.
References parent, and safe_execution_count.
Referenced by Quad_FIO::eval_ALXB(), Quad_EC::eval_B(), and Quad_FIO::eval_LXB().
set_X()
void StateIndicator::set_X (Value_P value)
change axis arg
Definition at line 436 of file StateIndicator.cc.
References current_stack, and Prefix::locate_X().
Referenced by Quad_X::assign().
show_owners()
int StateIndicator::show_owners (ostream & out, const Value & value) const
print all owners of value
Definition at line 376 of file StateIndicator.cc.
References current_stack, executable, level, Executable::show_owners(), and Prefix::show_owners().
statement_result()
void StateIndicator::statement_result (Token & result, bool trace)
Maybe print B (according to tag) and erase B.
Definition at line 500 of file StateIndicator.cc.
References Quad_CR::do_CR(), Bif_F12_TAKE::do_take(), TakeDropIterator::done, executable, fun_oper_cache, Token::get_apl_val(), Command::get_boxing_format(), UserFunction::get_exec_properties(), Executable::get_exec_ufun(), Executable::get_line(), UserFunction::get_name(), get_parse_mode_name(), get_PC(), Workspace::get_PrintContext(), Workspace::get_PW(), Shape::get_rank(), Shape::get_shape_item(), Token::get_tag(), Token::get_ValueType(), Shape::get_volume(), Quad_SYL::print_length_limit, DerivedFunctionCache::reset(), Shape::set_shape_item(), and Token::show_trace().
unmark_all_values()
void StateIndicator::unmark_all_values () const
clear the marked bit in the executable, in the fun_oper_cache, and in all parsers
Definition at line 366 of file StateIndicator.cc.
References current_stack, executable, fun_oper_cache, DerivedFunctionCache::unmark_all_values(), Executable::unmark_all_values(), and Prefix::unmark_all_values().
uses_function()
bool StateIndicator::uses_function (const UserFunction * ufun) const
return true iff (1) this SI entry is executing funname, or (2) has resolved funname on its prefix parser stack
Definition at line 103 of file StateIndicator.cc.
References UCS_string::compare(), Executable::get_body(), Symbol::get_name(), UserFunction::get_name(), get_parent(), Token::get_sym_ptr(), and Token::get_tag().
Friends And Related Function Documentation
XML_Loading_Archive
friend class XML_Loading_Archive friend
Definition at line 42 of file StateIndicator.hh.
XML_Saving_Archive
friend class XML_Saving_Archive friend
Definition at line 43 of file StateIndicator.hh.
Member Data Documentation
current_stack
Prefix StateIndicator::current_stack protected
the current-stack of this context.
Definition at line 211 of file StateIndicator.hh.
Referenced by get_L(), get_PC(), get_prefix(), get_R(), get_X(), goon(), XML_Loading_Archive::read_Parser(), run(), XML_Saving_Archive::save_Parser(), set_L(), set_PC(), set_R(), set_X(), show_owners(), unmark_all_values(), and ~StateIndicator().
error
Error StateIndicator::error protected
details of the last error in this context.
Definition at line 208 of file StateIndicator.hh.
Referenced by get_error(), list(), and print().
executable
const Executable* StateIndicator::executable protected
the user function that is being executed
Definition at line 199 of file StateIndicator.hh.
Referenced by function_name(), get_executable(), get_line(), get_parse_mode(), info(), list(), print(), show_owners(), statement_result(), unmark_all_values(), and ~StateIndicator().
fun_oper_cache
DerivedFunctionCache StateIndicator::fun_oper_cache
a small storage for DerivedFunction objects.
Definition at line 192 of file StateIndicator.hh.
Referenced by XML_Loading_Archive::read_Derived(), XML_Saving_Archive::save_Parser(), statement_result(), unmark_all_values(), and ~StateIndicator().
level
const SI_level StateIndicator::level protected
The nesting level (of sub-executions)
Definition at line 205 of file StateIndicator.hh.
Referenced by get_level(), goon(), indent(), info(), print(), run(), and show_owners().
parent
StateIndicator* StateIndicator::parent protected
the StateIndicator that has called this one
Definition at line 214 of file StateIndicator.hh.
Referenced by clear_safe_execution(), find_child(), get_parent(), is_safe_execution_start(), and set_safe_execution().
safe_execution_count
int StateIndicator::safe_execution_count protected
the number of pending ⎕EC calles
Definition at line 202 of file StateIndicator.hh.
Referenced by clear_safe_execution(), get_safe_execution(), is_safe_execution_start(), print(), and set_safe_execution().
top_level_error
Error StateIndicator::top_level_error static
error when)SI is empty
Definition at line 195 of file StateIndicator.hh.
Referenced by get_error().
The documentation for this class was generated from the following files:
src/StateIndicator.hh
src/StateIndicator.cc
src/static_Objects.cc