GNU APL: SymbolTableBase< T, SYMBOL_COUNT > Class Template Reference
SymbolTableBase< T, SYMBOL_COUNT > Class Template Reference
common part of user-defined names and distinguished names
#include <SymbolTable.hh>
Public Types
enum { max_symbol_count = SYMBOL_COUNT }
Public Member Functions
SymbolTableBase ()
Construct an empty SymbolTable.
T * lookup_existing_symbol (const UCS_string &name)
return a Symbol with name name in this SymbolTable.
const T * lookup_existing_symbol (const UCS_string &name) const
return a Symbol with name name in this SymbolTable.
UCS_string find_lambda_name (const UserFunction *lambda)
return the name to which lambda ia assigned (empty if not found)
void add_symbol (T *sym)
add sym to the symbol table. The caller has checked that new_name does not yet exist in the symbol table
Static Public Member Functions
static uint32_t compute_hash (const UCS_string &name)
compute a 16-bit hash for name
Protected Attributes
T * symbol_table [SYMBOL_COUNT]
Hash table for all symbols.
Detailed Description
template<typename T, size_t SYMBOL_COUNT>
class SymbolTableBase< T, SYMBOL_COUNT >
common part of user-defined names and distinguished names
Definition at line 32 of file SymbolTable.hh.
Member Enumeration Documentation
anonymous enum
template<typename T , size_t SYMBOL_COUNT> anonymous enum
Definition at line 35 of file SymbolTable.hh.
Constructor & Destructor Documentation
SymbolTableBase()
template<typename T , size_t SYMBOL_COUNT> SymbolTableBase< T, SYMBOL_COUNT >::SymbolTableBase () inline
Construct an empty SymbolTable.
Definition at line 38 of file SymbolTable.hh.
References SymbolTableBase< T, SYMBOL_COUNT >::symbol_table.
~SymbolTableBase()
template<typename T , size_t SYMBOL_COUNT> SymbolTableBase< T, SYMBOL_COUNT >::~SymbolTableBase () inline
Definition at line 41 of file SymbolTable.hh.
Member Function Documentation
add_symbol()
template<typename T , size_t SYMBOL_COUNT> void SymbolTableBase< T, SYMBOL_COUNT >::add_symbol (T * sym) inline
add sym to the symbol table. The caller has checked that new_name does not yet exist in the symbol table
Definition at line 83 of file SymbolTable.hh.
References SymbolTableBase< T, SYMBOL_COUNT >::compute_hash(), and SymbolTableBase< T, SYMBOL_COUNT >::symbol_table.
compute_hash()
template<typename T , size_t SYMBOL_COUNT> static uint32_t SymbolTableBase< T, SYMBOL_COUNT >::compute_hash (const UCS_string & name) inline static
compute a 16-bit hash for name
Definition at line 105 of file SymbolTable.hh.
References UCS_string::FNV_hash(), and UCS_string::size().
Referenced by SymbolTableBase< T, SYMBOL_COUNT >::add_symbol(), and SymbolTableBase< T, SYMBOL_COUNT >::lookup_existing_symbol().
lookup_existing_symbol() [1/2]
template<typename T , size_t SYMBOL_COUNT> T * SymbolTableBase< T, SYMBOL_COUNT >::lookup_existing_symbol (const UCS_string & name) inline
return a Symbol with name name in this SymbolTable.
Definition at line 53 of file SymbolTable.hh.
References SymbolTableBase< T, SYMBOL_COUNT >::compute_hash(), and SymbolTableBase< T, SYMBOL_COUNT >::symbol_table.
Referenced by Workspace::get_quad(), Workspace::lookup_existing_name(), and Workspace::lookup_existing_symbol().
lookup_existing_symbol() [2/2]
template<typename T , size_t SYMBOL_COUNT> const T * SymbolTableBase< T, SYMBOL_COUNT >::lookup_existing_symbol (const UCS_string & name) const inline
return a Symbol with name name in this SymbolTable.
Definition at line 66 of file SymbolTable.hh.
References SymbolTableBase< T, SYMBOL_COUNT >::compute_hash(), and SymbolTableBase< T, SYMBOL_COUNT >::symbol_table.
Member Data Documentation
symbol_table
template<typename T , size_t SYMBOL_COUNT> T* SymbolTableBase< T, SYMBOL_COUNT >::symbol_table[SYMBOL_COUNT] protected
Hash table for all symbols.
Definition at line 122 of file SymbolTable.hh.
Referenced by SymbolTableBase< T, SYMBOL_COUNT >::add_symbol(), SymbolTableBase< T, SYMBOL_COUNT >::lookup_existing_symbol(), and SymbolTableBase< T, SYMBOL_COUNT >::SymbolTableBase().
The documentation for this class was generated from the following file:
src/SymbolTable.hh