GNU APL: RegexpMatch Class Reference
RegexpMatch Class Reference
A Regular expression match.
#include <Regexp.hh>
Public Member Functions
RegexpMatch (pcre2_code *code, const UCS_string &B, PCRE2_SIZE start)
constructor
virtual ~RegexpMatch ()
destructor
uint32_t get_ovector_count () const
return the number of offset pairs in a match
const PCRE2_SIZE * get_ovector () const
return the offset pairs in a match
bool is_match () const
return true if there was a match
int num_matches () const
return the number of matches
UCS_string matched_string () const
return the matched string
Protected Attributes
PCRE2_SIZE * ovector
the offset pairs
uint32_t ovector_count
the number of offset pairs
pcre2_match_data * match_data
the data related to a match
int match_result
the result of a match
const UCS_string & matched_B
the right argument B of ⎕RE
Detailed Description
A Regular expression match.
Definition at line 30 of file Regexp.hh.
Constructor & Destructor Documentation
RegexpMatch()
RegexpMatch::RegexpMatch (pcre2_code * code, const UCS_string & B, PCRE2_SIZE start)
constructor
Definition at line 38 of file Regexp.cc.
References match_data, match_result, ovector, ovector_count, and Regexp::pcre_error().
~RegexpMatch()
RegexpMatch::~RegexpMatch () virtual
destructor
Definition at line 64 of file Regexp.cc.
References match_data.
Member Function Documentation
get_ovector()
const PCRE2_SIZE * RegexpMatch::get_ovector () const inline
return the offset pairs in a match
Definition at line 44 of file Regexp.hh.
References ovector.
Referenced by Quad_RE::index_result(), matched_string(), Quad_RE::partition_result(), and Quad_RE::string_result().
get_ovector_count()
uint32_t RegexpMatch::get_ovector_count () const inline
return the number of offset pairs in a match
Definition at line 40 of file Regexp.hh.
References ovector_count.
Referenced by Quad_RE::index_result(), and Quad_RE::string_result().
is_match()
bool RegexpMatch::is_match () const
return true if there was a match
Definition at line 70 of file Regexp.cc.
References match_result.
Referenced by Quad_RE::index_result(), Quad_RE::partition_result(), and Quad_RE::string_result().
matched_string()
UCS_string RegexpMatch::matched_string () const
return the matched string
Definition at line 88 of file Regexp.cc.
References get_ovector(), matched_B, and ovector.
num_matches()
int RegexpMatch::num_matches () const
return the number of matches
Definition at line 76 of file Regexp.cc.
References match_result.
Referenced by Quad_RE::index_result(), and Quad_RE::string_result().
Member Data Documentation
match_data
pcre2_match_data* RegexpMatch::match_data protected
the data related to a match
Definition at line 64 of file Regexp.hh.
Referenced by RegexpMatch(), and ~RegexpMatch().
match_result
int RegexpMatch::match_result protected
the result of a match
Definition at line 67 of file Regexp.hh.
Referenced by is_match(), num_matches(), and RegexpMatch().
matched_B
const UCS_string& RegexpMatch::matched_B protected
the right argument B of ⎕RE
Definition at line 70 of file Regexp.hh.
Referenced by matched_string().
ovector
PCRE2_SIZE* RegexpMatch::ovector protected
the offset pairs
Definition at line 58 of file Regexp.hh.
Referenced by get_ovector(), matched_string(), and RegexpMatch().
ovector_count
uint32_t RegexpMatch::ovector_count protected
the number of offset pairs
Definition at line 61 of file Regexp.hh.
Referenced by get_ovector_count(), and RegexpMatch().
The documentation for this class was generated from the following files:
src/Regexp.hh
src/Regexp.cc