GNU APL: Sig_item_string Class Reference
Sig_item_string Class Reference
a string signal item of size bytes
#include <Svar_signals.hh>
Public Member Functions
Sig_item_string (const string &str)
construct an item with value v
Sig_item_string (const uint8_t *&buffer)
construct (deserialize) this item from a (received) buffer
const string get_svalue () const
return the value of the item
void store (string &buffer) const
store (aka. serialize) this item into a buffer
ostream & print (ostream &out) const
print the item
Protected Attributes
string value
the value of the item
Detailed Description
a string signal item of size bytes
Definition at line 174 of file Svar_signals.hh.
Constructor & Destructor Documentation
Sig_item_string() [1/2]
Sig_item_string::Sig_item_string (const string & str) inline
construct an item with value v
Definition at line 178 of file Svar_signals.hh.
Sig_item_string() [2/2]
Sig_item_string::Sig_item_string (const uint8_t *& buffer) inline
construct (deserialize) this item from a (received) buffer
Definition at line 183 of file Svar_signals.hh.
References Sig_item_int< T, bytes >::get_svalue(), and value.
Member Function Documentation
get_svalue()
const string Sig_item_string::get_svalue () const inline
return the value of the item
Definition at line 191 of file Svar_signals.hh.
References value.
Referenced by ASSIGN_VALUE_c::get__ASSIGN_VALUE__cdr_value(), ASSIGN_WSWS_VAR_c::get__ASSIGN_WSWS_VAR__cdr_value(), MATCH_OR_MAKE_c::get__MATCH_OR_MAKE__varname(), OFFERED_VARS_ARE_c::get__OFFERED_VARS_ARE__offered_vars(), OFFERING_PROCS_ARE_c::get__OFFERING_PROCS_ARE__offering_procs(), REGISTER_PROCESSOR_c::get__REGISTER_PROCESSOR__progname(), SET_STATE_c::get__SET_STATE__sloc(), SVAR_ASSIGNED_c::get__SVAR_ASSIGNED__error_loc(), SVAR_DB_PRINTED_c::get__SVAR_DB_PRINTED__printout(), SVAR_RECORD_IS_c::get__SVAR_RECORD_IS__record(), VALUE_IS_c::get__VALUE_IS__cdr_value(), VALUE_IS_c::get__VALUE_IS__error_loc(), and WSWS_VALUE_IS_c::get__WSWS_VALUE_IS__cdr_value().
print()
ostream & Sig_item_string::print (ostream & out) const inline
print the item
Definition at line 202 of file Svar_signals.hh.
References value.
Referenced by SET_STATE_c::print(), VALUE_IS_c::print(), ASSIGN_VALUE_c::print(), SVAR_ASSIGNED_c::print(), SVAR_RECORD_IS_c::print(), REGISTER_PROCESSOR_c::print(), MATCH_OR_MAKE_c::print(), OFFERING_PROCS_ARE_c::print(), OFFERED_VARS_ARE_c::print(), ASSIGN_WSWS_VAR_c::print(), WSWS_VALUE_IS_c::print(), and SVAR_DB_PRINTED_c::print().
store()
void Sig_item_string::store (string & buffer) const inline
store (aka. serialize) this item into a buffer
Definition at line 194 of file Svar_signals.hh.
References Sig_item_int< T, bytes >::store(), and value.
Referenced by SET_STATE_c::store(), VALUE_IS_c::store(), ASSIGN_VALUE_c::store(), SVAR_ASSIGNED_c::store(), SVAR_RECORD_IS_c::store(), REGISTER_PROCESSOR_c::store(), MATCH_OR_MAKE_c::store(), OFFERING_PROCS_ARE_c::store(), OFFERED_VARS_ARE_c::store(), ASSIGN_WSWS_VAR_c::store(), WSWS_VALUE_IS_c::store(), and SVAR_DB_PRINTED_c::store().
Member Data Documentation
value
string Sig_item_string::value protected
the value of the item
Definition at line 224 of file Svar_signals.hh.
Referenced by get_svalue(), print(), Sig_item_string(), and store().
The documentation for this class was generated from the following file:
src/Svar_signals.hh