GNU APL: Error Class Reference
Error Class Reference
An APL error and information related to it.
#include <Error.hh>
Public Member Functions
Error (ErrorCode ec, const char *loc)
constructor: error with error code ec
bool is_known () const
return true iff error_code is known (as opposed to an arbitrary error code constructed by ⎕ES)
bool is_syntax_or_value_error () const
return true iff error_code is some SYNTAX ERROR or VALUE ERROR
const ErrorCode get_error_code () const
return the error code of this error
const char * get_error_line_1 () const
return ⎕EM[1;]. This is the first of 3 error lines. It contains the error name (like SYNTAX ERROR, DOMAIN ERROR, etc) and is subject to translation
void clear_error_line_1 ()
clear error line 1
const char * get_error_line_2 () const
return error_message_2. This is the second of 3 error lines. It contains the failed statement and is NOT subject to translation.
const char * get_print_loc () const
return source file location where this error was printed (0 if not)
UCS_string get_error_line_3 () const
compute the caret line. This is the third of the 3 error lines. It contains the failure position the statement and is NOT subject to translation.
const char * get_throw_loc () const
return the source code location where the error was thrown
int get_left_caret () const
return the left caret (^) position in the third error line
int get_right_caret () const
return the right caret (^) position in the third error line
bool get_show_locked () const
return the show_locked flag
void print (ostream &out, const char *loc) const
print the error and its related information
void set_error_line_1 (const char *msg_1)
set the first error line
void set_error_line_2 (const char *msg_2)
set the second error line
void set_error_line_2 (const UCS_string &ucs, int lcaret, int rcaret)
set error line 2, left caret, and right caret
void print_em (ostream &out, const char *loc)
print the 3 error message lines as per ⎕EM
void clear_error_code ()
set the error code
void set_show_locked (bool on)
set the show_locked flag
void set_left_caret (int col)
set the left caret (^) position in the third error line
void set_right_caret (int col)
set the right caret (^) position in the third error line
void set_parser_loc (const char *loc)
set the source code line where a parse error was thrown
void update_error_info (StateIndicator *si)
update error information in this and copy it to si
Static Public Member Functions
static int error_major (ErrorCode err)
return the major class (⎕ET) of the error
static int error_minor (ErrorCode err)
return the category (⎕ET) of the error
static void throw_symbol_error (const UCS_string &symbol, const char *loc)
throw an Error related to Symbol symbol
static void throw_parse_error (ErrorCode code, const char *par_loc, const char *loc)
throw a error with a parser location
static void throw_define_error (const UCS_string &fun, const UCS_string &cmd, const char *loc)
throw a DEFN ERROR for function fun
static const char * error_name (ErrorCode err)
return a string describing the error
Protected Attributes
ErrorCode error_code
the error code
const char * throw_loc
the mandatory source file location where the error was thrown
char symbol_name [60]
an optional symbol related to (i.e. triggering) the error
const char * parser_loc
an optional source file location (for parse errors)
char error_message_1 [60]
an optional error text. this text is provided for non-APL errors,
char error_message_2 [60]
second line of error message (only valid if error_code != _NO_ERROR)
bool show_locked
display user function and line rather than ⎕ES instruction
int left_caret
the left caret position (-1 if none) for the error display
int right_caret
the right caret position (-1 if none) for the error display
const char * print_loc
where this error was printed (0 if not)
Private Member Functions
Error ()
constructor (not implemented): prevent construction without error code
Detailed Description
An APL error and information related to it.
The exception that is thrown when errors occur. The primary item is the error_code; the other items are only valid if error_code != NO_ERROR
Definition at line 44 of file Error.hh.
Constructor & Destructor Documentation
Error()
Error::Error (ErrorCode ec, const char * loc)
constructor: error with error code ec
Definition at line 31 of file Error.cc.
References error_code, error_message_1, error_message_2, error_name(), Workspace::more_error(), UCS_string::size(), and symbol_name.
Member Function Documentation
clear_error_code()
void Error::clear_error_code () inline
set the error code
Definition at line 129 of file Error.hh.
References error_code.
clear_error_line_1()
void Error::clear_error_line_1 () inline
clear error line 1
Definition at line 68 of file Error.hh.
References error_message_1.
error_major()
static int Error::error_major (ErrorCode err) inline static
return the major class (⎕ET) of the error
Definition at line 77 of file Error.hh.
Referenced by Quad_EC::eoc(), Quad_EC::eval_B(), Quad_ET::get_apl_value(), and is_syntax_or_value_error().
error_minor()
static int Error::error_minor (ErrorCode err) inline static
return the category (⎕ET) of the error
Definition at line 81 of file Error.hh.
Referenced by Quad_EC::eoc(), Quad_EC::eval_B(), and Quad_ET::get_apl_value().
error_name()
const char * Error::error_name (ErrorCode err) static
return a string describing the error
the cases
Definition at line 99 of file Error.cc.
Referenced by Symbol::assign_shared_variable(), Command::do_APL_expression(), Tokenizer::do_tokenize(), Quad_EC::eoc(), Error(), Quad_EC::eval_B(), ExecuteList::fix(), Workspace::immediate_execution(), VH_entry::print(), print(), Symbol::resolve_shared_variable(), Doxy::SI_table(), and throw_parse_error().
get_error_code()
const ErrorCode Error::get_error_code () const inline
return the error code of this error
Definition at line 58 of file Error.hh.
References error_code.
Referenced by Command::do_APL_expression(), Executable::execute_body(), ExecuteList::fix(), Workspace::immediate_execution(), StateIndicator::list(), StateIndicator::print(), and Tokenizer::tokenize().
get_error_line_1()
const char * Error::get_error_line_1 () const inline
return ⎕EM[1;]. This is the first of 3 error lines. It contains the error name (like SYNTAX ERROR, DOMAIN ERROR, etc) and is subject to translation
Definition at line 64 of file Error.hh.
References error_message_1.
Referenced by Quad_EM::get_apl_value(), StateIndicator::print(), and print_em().
get_error_line_2()
const char * Error::get_error_line_2 () const inline
return error_message_2. This is the second of 3 error lines. It contains the failed statement and is NOT subject to translation.
Definition at line 73 of file Error.hh.
References error_message_2.
Referenced by Command::do_APL_expression(), Quad_EC::eoc(), Quad_EM::get_apl_value(), StateIndicator::list(), StateIndicator::print(), and print_em().
get_error_line_3()
UCS_string Error::get_error_line_3 () const
compute the caret line. This is the third of the 3 error lines. It contains the failure position the statement and is NOT subject to translation.
Definition at line 145 of file Error.cc.
References UCS_string::append(), error_code, left_caret, and right_caret.
Referenced by Command::do_APL_expression(), Quad_EC::eoc(), Quad_EM::get_apl_value(), StateIndicator::list(), StateIndicator::print(), and print_em().
get_left_caret()
int Error::get_left_caret () const inline
return the left caret (^) position in the third error line
Definition at line 98 of file Error.hh.
References left_caret.
get_print_loc()
const char * Error::get_print_loc () const inline
return source file location where this error was printed (0 if not)
Definition at line 85 of file Error.hh.
References print_loc.
Referenced by Workspace::immediate_execution().
get_right_caret()
int Error::get_right_caret () const inline
return the right caret (^) position in the third error line
Definition at line 102 of file Error.hh.
References right_caret.
get_show_locked()
bool Error::get_show_locked () const inline
return the show_locked flag
Definition at line 106 of file Error.hh.
References show_locked.
Referenced by update_error_info().
get_throw_loc()
const char * Error::get_throw_loc () const inline
return the source code location where the error was thrown
Definition at line 94 of file Error.hh.
References throw_loc.
Referenced by StateIndicator::print().
is_known()
bool Error::is_known () const
return true iff error_code is known (as opposed to an arbitrary error code constructed by ⎕ES)
the cases
Definition at line 114 of file Error.cc.
References error_code.
is_syntax_or_value_error()
bool Error::is_syntax_or_value_error () const
return true iff error_code is some SYNTAX ERROR or VALUE ERROR
Definition at line 137 of file Error.cc.
References error_code, and error_major().
print()
void Error::print (ostream & out, const char * loc) const
print the error and its related information
Definition at line 49 of file Error.cc.
References error_code, error_message_1, error_name(), Workspace::more_error(), parser_loc, print_loc, symbol_name, and throw_loc.
Referenced by Command::do_APL_expression(), Command::finish_context(), and UserFunction::load().
print_em()
void Error::print_em (ostream & out, const char * loc)
print the 3 error message lines as per ⎕EM
Definition at line 164 of file Error.cc.
References get_error_line_1(), get_error_line_2(), get_error_line_3(), and print_loc.
Referenced by Workspace::immediate_execution(), and update_error_info().
set_error_line_1()
void Error::set_error_line_1 (const char * msg_1) inline
set the first error line
Definition at line 113 of file Error.hh.
References error_message_1.
set_error_line_2() [1/2]
void Error::set_error_line_2 (const char * msg_2) inline
set the second error line
Definition at line 118 of file Error.hh.
References error_message_2.
Referenced by Tokenizer::tokenize(), and update_error_info().
set_error_line_2() [2/2]
void Error::set_error_line_2 (const UCS_string & ucs, int lcaret, int rcaret)
set error line 2, left caret, and right caret
Definition at line 127 of file Error.cc.
References UTF8_string::c_str(), error_message_2, left_caret, and right_caret.
set_left_caret()
void Error::set_left_caret (int col) inline
set the left caret (^) position in the third error line
Definition at line 137 of file Error.hh.
References left_caret.
Referenced by update_error_info().
set_parser_loc()
void Error::set_parser_loc (const char * loc) inline
set the source code line where a parse error was thrown
Definition at line 145 of file Error.hh.
References parser_loc.
Referenced by ExecuteList::fix().
set_right_caret()
void Error::set_right_caret (int col) inline
set the right caret (^) position in the third error line
Definition at line 141 of file Error.hh.
References right_caret.
Referenced by update_error_info().
set_show_locked()
void Error::set_show_locked (bool on) inline
set the show_locked flag
Definition at line 133 of file Error.hh.
References show_locked.
throw_define_error()
void Error::throw_define_error (const UCS_string & fun, const UCS_string & cmd, const char * loc) static
throw a DEFN ERROR for function fun
Definition at line 260 of file Error.cc.
References UTF8_string::c_str(), Workspace::get_error(), left_caret, Workspace::SI_top(), and UCS_string::size().
Referenced by Nabla::throw_edit_error().
throw_parse_error()
void Error::throw_parse_error (ErrorCode code, const char * par_loc, const char * loc) static
throw a error with a parser location
Definition at line 217 of file Error.cc.
References error_name().
Referenced by Tokenizer::do_tokenize(), Executable::parse_body_line(), Tokenizer::tokenize_number(), Tokenizer::tokenize_string1(), and Tokenizer::tokenize_string2().
throw_symbol_error()
void Error::throw_symbol_error (const UCS_string & symbol, const char * loc) static
throw an Error related to Symbol symbol
Definition at line 238 of file Error.cc.
References UTF8_string::c_str(), Workspace::SI_top(), and UCS_string::size().
Referenced by Quad_SVC::eval_AB(), Quad_AT::eval_AB(), Quad_SVC::eval_B(), Quad_SVS::eval_B(), Symbol::get_apl_value(), and Symbol::resolve().
update_error_info()
void Error::update_error_info (StateIndicator * si)
update error information in this and copy it to si
Definition at line 286 of file Error.cc.
References UCS_string::append(), UTF8_string::c_str(), UserFunction_header::get_error(), UserFunction::get_exec_properties(), Executable::get_exec_ufun(), StateIndicator::get_executable(), UserFunction::get_name_and_line(), StateIndicator::get_parent(), StateIndicator::get_PC(), StateIndicator::get_prefix(), Prefix::get_range_high(), Prefix::get_range_low(), get_show_locked(), print_em(), Executable::set_error_info(), set_error_line_2(), set_left_caret(), UserFunction::set_locked_error_info(), set_right_caret(), and UCS_string::size().
Member Data Documentation
error_code
ErrorCode Error::error_code protected
the error code
Definition at line 169 of file Error.hh.
Referenced by clear_error_code(), Error(), get_error_code(), get_error_line_3(), is_known(), is_syntax_or_value_error(), and print().
error_message_1
char Error::error_message_1[60] protected
an optional error text. this text is provided for non-APL errors,
Definition at line 182 of file Error.hh.
Referenced by clear_error_line_1(), Error(), get_error_line_1(), print(), and set_error_line_1().
error_message_2
char Error::error_message_2[60] protected
second line of error message (only valid if error_code != _NO_ERROR)
Definition at line 185 of file Error.hh.
Referenced by Error(), get_error_line_2(), and set_error_line_2().
left_caret
int Error::left_caret protected
the left caret position (-1 if none) for the error display
Definition at line 191 of file Error.hh.
Referenced by get_error_line_3(), get_left_caret(), set_error_line_2(), set_left_caret(), and throw_define_error().
parser_loc
const char* Error::parser_loc protected
an optional source file location (for parse errors)
Definition at line 178 of file Error.hh.
Referenced by print(), and set_parser_loc().
print_loc
const char* Error::print_loc protected
where this error was printed (0 if not)
Definition at line 197 of file Error.hh.
Referenced by get_print_loc(), print(), and print_em().
right_caret
int Error::right_caret protected
the right caret position (-1 if none) for the error display
Definition at line 194 of file Error.hh.
Referenced by get_error_line_3(), get_right_caret(), set_error_line_2(), and set_right_caret().
show_locked
bool Error::show_locked protected
display user function and line rather than ⎕ES instruction
Definition at line 188 of file Error.hh.
Referenced by get_show_locked(), and set_show_locked().
symbol_name
char Error::symbol_name[60] protected
an optional symbol related to (i.e. triggering) the error
Definition at line 175 of file Error.hh.
Referenced by Error(), and print().
throw_loc
const char* Error::throw_loc protected
the mandatory source file location where the error was thrown
Definition at line 172 of file Error.hh.
Referenced by get_throw_loc(), and print().
The documentation for this class was generated from the following files:
src/Error.hh
src/Error.cc