GNU APL: Quad_INP Class Reference
Quad_INP Class Reference
The class implementing ⎕INP.
#include <QuadFunction.hh>
Public Member Functions
Quad_INP ()
constructor.
Public Member Functions inherited from QuadFunction
QuadFunction (TokenTag tag)
Constructor.
virtual bool has_alpha () const
overloaded Function::has_alpha()
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B().
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB().
virtual bool has_result () const
overloaded Function::has_result()
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
virtual bool has_result () const
overloaded Function::has_result()
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Static Public Attributes
static Quad_INP * fun = &Quad_INP ::_fun
Built-in function.
static Quad_INP _fun
Built-in function.
Protected Member Functions
virtual Token eval_AB (Value_P A, Value_P B) const
overloaded Function::eval_AB().
virtual Token eval_B (Value_P B) const
overloaded Function::eval_B().
virtual Token eval_XB (Value_P X, Value_P B) const
overloaded Function::eval_XB().
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Static Protected Member Functions
static void get_esc (Value_P A, UCS_string &esc1, UCS_string &esc2)
extract the esc1 and esc2 strings from A
static void read_strings ()
read raw_lines from stdin or file, stop at end_marker
static void split_strings ()
split raw_lines into prefixes, escapes, and suffixes
Static Protected Attributes
static UCS_string esc1
the end merker for APL escapes (dyadic ⎕INP only) the start merker for APL escapes (dyadic ⎕INP only)
static UCS_string esc2
the end merker for APL escapes (dyadic ⎕INP only)
static UCS_string end_marker
the end merker for the entire ⎕INP input
static UCS_string_vector raw_lines
the raw lines read from stdin
static UCS_string_vector prefixes
the line parts left of the escapes
static UCS_string_vector escapes
the line parts to exe executed
static UCS_string_vector suffixes
the line parts right of the escapes
static bool Quad_INP_running = false
bool to prevent recursive ⎕INP calls
Additional Inherited Members
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
The class implementing ⎕INP.
The system function ⎕INP (input from script, aka. HERE document)
Definition at line 242 of file QuadFunction.hh.
Constructor & Destructor Documentation
Quad_INP()
Quad_INP::Quad_INP () inline
constructor.
Definition at line 246 of file QuadFunction.hh.
References Quad_INP_running.
Member Function Documentation
eval_AB()
Token Quad_INP::eval_AB (Value_P A, Value_P B) const protected virtual
overloaded Function::eval_AB().
Reimplemented from QuadFunction.
Definition at line 761 of file QuadFunction.cc.
References end_marker, esc1, esc2, escapes, UserFunction::eval_B(), Value_P_Base::get(), get_esc(), Macro::get_macro(), Token::get_tag(), prefixes, Quad_INP_running, raw_lines, read_strings(), split_strings(), and suffixes.
eval_B()
Token Quad_INP::eval_B (Value_P B) const protected virtual
overloaded Function::eval_B().
Reimplemented from QuadFunction.
Definition at line 840 of file QuadFunction.cc.
References end_marker, Quad_INP_running, raw_lines, and read_strings().
Referenced by eval_XB().
eval_XB()
Token Quad_INP::eval_XB (Value_P X, Value_P B) const protected virtual
overloaded Function::eval_XB().
Reimplemented from Function.
Definition at line 871 of file QuadFunction.cc.
References end_marker, eval_B(), Value_P_Base::get(), Token::get_Class(), StateIndicator::get_line(), Token::get_tag(), LineHistory::quad_INP_history, and UCS_string::substr_pos().
get_esc()
void Quad_INP::get_esc (Value_P A, UCS_string & esc1, UCS_string & esc2) static protected
extract the esc1 and esc2 strings from A
Definition at line 963 of file QuadFunction.cc.
References esc1, esc2, Cell::get_pointer_value(), Cell::is_pointer_cell(), and UCS_string::size().
Referenced by eval_AB().
read_strings()
void Quad_INP::read_strings () static protected
read raw_lines from stdin or file, stop at end_marker
Definition at line 1000 of file QuadFunction.cc.
References end_marker, StateIndicator::get_line(), LineHistory::quad_INP_history, raw_lines, UCS_string::size(), and UCS_string::substr_pos().
Referenced by eval_AB(), and eval_B().
split_strings()
void Quad_INP::split_strings () static protected
split raw_lines into prefixes, escapes, and suffixes
Definition at line 1028 of file QuadFunction.cc.
References UCS_string::drop(), esc1, esc2, escapes, prefixes, raw_lines, UCS_string::size(), UCS_string::substr_pos(), and suffixes.
Referenced by eval_AB().
Member Data Documentation
_fun
Quad_INP Quad_INP::_fun static
Built-in function.
Definition at line 253 of file QuadFunction.hh.
end_marker
UCS_string Quad_INP::end_marker static protected
the end merker for the entire ⎕INP input
Definition at line 282 of file QuadFunction.hh.
Referenced by eval_AB(), eval_B(), eval_XB(), and read_strings().
esc1
UCS_string Quad_INP::esc1 static protected
the end merker for APL escapes (dyadic ⎕INP only) the start merker for APL escapes (dyadic ⎕INP only)
Definition at line 276 of file QuadFunction.hh.
Referenced by eval_AB(), get_esc(), and split_strings().
esc2
UCS_string Quad_INP::esc2 static protected
the end merker for APL escapes (dyadic ⎕INP only)
Definition at line 279 of file QuadFunction.hh.
Referenced by eval_AB(), get_esc(), and split_strings().
escapes
UCS_string_vector Quad_INP::escapes static protected
the line parts to exe executed
Definition at line 291 of file QuadFunction.hh.
Referenced by eval_AB(), and split_strings().
fun
Quad_INP * Quad_INP::fun = &Quad_INP ::_fun static
Built-in function.
Definition at line 252 of file QuadFunction.hh.
prefixes
UCS_string_vector Quad_INP::prefixes static protected
the line parts left of the escapes
Definition at line 288 of file QuadFunction.hh.
Referenced by eval_AB(), and split_strings().
Quad_INP_running
bool Quad_INP::Quad_INP_running = false static protected
bool to prevent recursive ⎕INP calls
Definition at line 297 of file QuadFunction.hh.
Referenced by eval_AB(), eval_B(), and Quad_INP().
raw_lines
UCS_string_vector Quad_INP::raw_lines static protected
the raw lines read from stdin
Definition at line 285 of file QuadFunction.hh.
Referenced by eval_AB(), eval_B(), read_strings(), and split_strings().
suffixes
UCS_string_vector Quad_INP::suffixes static protected
the line parts right of the escapes
Definition at line 294 of file QuadFunction.hh.
Referenced by eval_AB(), and split_strings().
The documentation for this class was generated from the following files:
src/QuadFunction.hh
src/QuadFunction.cc