GNU APL: Bif_F12_FORMAT Class Reference
Bif_F12_FORMAT Class Reference
The class implementing ⍕
#include <Bif_F12_FORMAT.hh>
Classes
struct Format_LIFER
An entire format field (LIFER = Left-Int-Fract-Expo-Right.
Public Member Functions
Bif_F12_FORMAT ()
constructor
Public Member Functions inherited from NonscalarFunction
NonscalarFunction (TokenTag tag)
Constructor.
Public Member Functions inherited from PrimitiveFunction
PrimitiveFunction (TokenTag tag, CellFunctionStatistics *stat_AB=0, CellFunctionStatistics *stat_B=0)
Construct a PrimitiveFunction with TokenTag tag.
virtual bool has_result () const
overloaded Function::has_result()
CellFunctionStatistics * get_statistics_AB () const
return the dyadic cell statistics of this (scalar) function
CellFunctionStatistics * get_statistics_B () const
return the monadic cell statistics of this (scalar) function
virtual Token eval_fill_AB (Value_P A, Value_P B) const
overloaded Function::eval_fill_AB()
Public Member Functions inherited from Function
Function (TokenTag _tag)
constructor for most functions
Function (Id id, TokenTag _tag)
constructor for functions whose Id does not match their tag
virtual ~Function ()
destructor
virtual bool is_operator () const
return true iff this is an operator.
virtual bool is_native () const
return true iff this is a native function
virtual bool is_lambda () const
return true iff this function is a lambda
virtual bool is_macro () const
return true iff this function is a macro
virtual bool is_defined () const
return true iff this function is defined (= has an APL body)
virtual bool is_derived () const
return true iff this function is a derived function
virtual bool_f1 get_bool_f1 () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2 get_bool_f2 () const
return a bool_f2() (if any), otherwise 0.
virtual bool_f1_bool get_bool_f1_bool () const
return a bool_f1() (if any), otherwise 0.
virtual bool_f2_bool get_bool_f2_bool () const
return a bool_f2() (if any), otherwise 0.
virtual bool is_bool_bool () const
return true iff this function returns a (possibly nested) boolean result and takes (only) boolean arguments. For example: ∧, ∨, ∼, ...
virtual bool may_push_SI () const
return true if eval_XXX may push the SI. True for ⍎, user defined functions, and operators derived from user defined functions
virtual int get_fun_valence () const
return the number of value arguments (0, 1, or 2) of a user defined function, For non-user defined functions, throw DOMAIN_ERROR.
virtual int get_oper_valence () const
return the number of function arguments (1 or 2) of an operator, or 0 for a "normal" function that isn't an operator.
virtual bool has_result () const =0
return 1 if the function returns a result, otherwise 0. For non-user defined functions, throw DOMAIN_ERROR.
virtual bool has_axis () const
return true iff the function has and axis (system defined functions always have an axis even thogh most of them ignore it).
virtual const Function * get_function () const
overloaded NamedObject::get_function()
virtual Function_P get_monadic_inverse () const
the monadic inverse function of this function (if any)
virtual Function_P get_dyadic_inverse () const
the dyadic inverse function of this function (if any)
APL_time_us get_creation_time () const
GMT when this function was created; 0 for system functions.
void set_creation_time (APL_time_us t)
set the time when the function was created (0 for built-in functions)
virtual const int * get_exec_properties () const
return the execution properties (3 ⎕AT) for this function
virtual void print_properties (ostream &out, int indent) const =0
print the properties of this function
virtual void get_attributes (int mode, Value &Z) const
store the attributes (as per ⎕AT) of symbol in Z, ...
virtual const UserFunction * get_func_ufun () const
return a pointer to this UserFunction (if it is one)
virtual bool has_alpha () const
return true if this function has a name with alphabetic chars, i.e. the function is user defined or a quad function
virtual ostream & print (ostream &out) const =0
Print this function.
virtual prim_f2 get_scalar_f2 () const
return the dyadic scalar primitive if this function
virtual assoc_f2 get_assoc () const
if this function is an associative scalar function then return its associative cell function, otherwise 0.
Token get_token () const
return a Token for this function.
TokenTag get_tag () const
return the Token Tag for this function.
virtual Token eval_ () const
plain function, 0 arguments
virtual Token eval_AB (Value_P A, Value_P B) const
plain function, 2 arguments
virtual Token eval_ALB (Value_P A, Token &LO, Value_P B) const
monadic operator, 2 arguments
virtual Token eval_AXB (Value_P A, Value_P X, Value_P B) const
plain function, 2 arguments, with axis
virtual Token eval_ALRB (Value_P A, Token &LO, Token &RO, Value_P B) const
dyadic operator, 2 arguments
virtual Token eval_ALXB (Value_P A, Token &LO, Value_P X, Value_P B) const
monadic operator, 2 arguments, with axis
virtual Token eval_ALRXB (Value_P A, Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 2 arguments, with axis
virtual Token eval_B (Value_P B) const
plain function, 1 argument
virtual Token eval_LB (Token &LO, Value_P B) const
monadic operator, 1 argument
virtual Token eval_XB (Value_P X, Value_P B) const
plain function, 1 arguments, with axis
virtual Token eval_LXB (Token &LO, Value_P X, Value_P B) const
monadic operator, 1 arguments, with axis
virtual Token eval_LRB (Token &LO, Token &RO, Value_P B) const
dyadic operator, 1 arguments
virtual Token eval_LRXB (Token &LO, Token &RO, Value_P X, Value_P B) const
dyadic operator, 1 arguments, with axis
virtual Token eval_fill_B (Value_P B) const
Evaluate the fill function.
virtual Token eval_fill_AB (Value_P A, Value_P B) const
Evaluate the fill function.
virtual Token eval_identity_fun (Value_P B, sAxis axis) const
virtual void destroy ()
Delete this function (do nothing, overloaded by UserFunction).
virtual UCS_string canonical (bool with_lines) const
Quad_CR of this function.
virtual Value_P * locate_X () const
return axis (non-0 only for derived functions)
virtual bool has_subfuns () const
return true if this function has (named) sub-functions, i.e. this function is either ⎕FIO or ⎕CR.
virtual sAxis subfun_to_axis (const UCS_string &name) const
return a (pseudo-) axis number for subfunction name
Fun_signature get_signature () const
return the signature of this function (currently only valid for user-defined functions)
ShapeItem get_monadic_threshold () const
return break-even point for monadic parallel execution
void set_monadic_threshold (ShapeItem new_threshold)
set the break-even point for monadic parallel execution
ShapeItem get_dyadic_threshold () const
return break-even point for dyadic parallel execution
void set_dyadic_threshold (ShapeItem new_threshold)
set the break-even point for dyadic parallel execution
Public Member Functions inherited from NamedObject
NamedObject (Id i)
constructor from Id
virtual UCS_string get_name () const
return the name of the named object
virtual const Function * get_function () const
return the function for this Id (if any) or 0 if this Id does (currently) represent a function.
virtual Symbol * get_symbol ()
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
virtual const Symbol * get_symbol () const
return the symbol for this user defined symbol (if any) or 0 if this Id refers to a system name
Id get_Id () const
return the Id of this object (ID_USER_SYMBOL for user defined objects)
bool is_user_defined () const
return true, iff this object is user-defined
NameClass get_NC () const
Get current NameClass of this name.
Static Public Member Functions
static Value_P format_by_specification (Value_P A, Value_P B)
A character array with B formatted by specification.
static bool is_control_char (Unicode uni)
Return true iff uni is '0' .. '9', comma, or full-stop.
static Value_P monadic_format (Value_P B)
A character array with the display of B.
Static Public Attributes
static Bif_F12_FORMAT * fun = &Bif_F12_FORMAT::_fun
Built-in function.
static Bif_F12_FORMAT _fun
Built-in function.
Protected Member Functions
virtual Token eval_B (Value_P B) const
Overloaded Function::eval_B()
virtual Token eval_AB (Value_P A, Value_P B) const
Overloaded Function::eval_AB()
Protected Member Functions inherited from PrimitiveFunction
virtual void print_properties (ostream &out, int indent) const
overloaded Function::print_properties()
virtual Token eval_fill_B (Value_P B) const
overloaded Function::eval_fill_B()
virtual ostream & print (ostream &out) const
Print the name of this PrimitiveFunction to out.
Static Protected Member Functions
static Value_P format_by_example (Value_P A, Value_P B)
A character array with B formatted by example.
static void split_example_into_columns (const UCS_string &format, std::vector< UCS_string > &col_formats)
split entire format string string into column format strings
static PrintBuffer format_one_col_by_spec (int width, int precision, const Cell *cB, ShapeItem cols, ShapeItem rows)
A character array with one column of B formatted by specification.
static void add_row (PrintBuffer &ret, int row, bool has_char, bool has_num, Unicode align_char, UCS_string &data)
add a row (consisting of data) to PrintBuffer ret
static UCS_string format_float_by_spec (APL_Float value, int precision)
format value with precision mantissa digits (floating format)
Additional Inherited Members
Public Types inherited from Function
typedef bool(* bool_f1) (const Cell &B)
a monadic Cell function that returns bool
typedef bool(* bool_f2) (const Cell &A, const Cell &B)
a dyadic Cell function that returns bool
typedef uint64_t(* bool_f1_bool) (uint64_t A)
a monadic function that returns packed bool for packed A
typedef uint64_t(* bool_f2_bool) (uint64_t A, uint64_t B)
a dyadic function that returns packed bool for packed A and packed B
typedef ErrorCode(Cell::* assoc_f2) (Cell *, const Cell *) const
an associative cell function
Public Attributes inherited from Function
APL_time_us creation_time
when this function was created (0.0 for system functions)
Public Attributes inherited from NamedObject
const Id id
the object's id
Protected Attributes inherited from PrimitiveFunction
CellFunctionStatistics * statistics_AB
performance statistics for eval_B()
CellFunctionStatistics * statistics_B
performance statistics for dyadic calls
Protected Attributes inherited from Function
TokenTag tag
the tag for token pointing to this function
ShapeItem parallel_thresholds [2]
the thresholds for parallel execution
Detailed Description
The class implementing ⍕
System function format
Definition at line 87 of file Bif_F12_FORMAT.hh.
Constructor & Destructor Documentation
Bif_F12_FORMAT()
Bif_F12_FORMAT::Bif_F12_FORMAT () inline
constructor
Definition at line 91 of file Bif_F12_FORMAT.hh.
Member Function Documentation
add_row()
void Bif_F12_FORMAT::add_row (PrintBuffer & ret, int row, bool has_char, bool has_num, Unicode align_char, UCS_string & data) static protected
add a row (consisting of data) to PrintBuffer ret
Definition at line 1150 of file Bif_F12_FORMAT.cc.
References UCS_string::append(), PrintBuffer::append_aligned(), PrintBuffer::append_ucs(), PrintBuffer::get_column_count(), PrintBuffer::pad_l(), PrintBuffer::pad_r(), and UCS_string::size().
Referenced by format_one_col_by_spec().
eval_AB()
Token Bif_F12_FORMAT::eval_AB (Value_P A, Value_P B) const protected virtual
Overloaded Function::eval_AB()
Reimplemented from Function.
Definition at line 167 of file Bif_F12_FORMAT.cc.
References format_by_example(), and format_by_specification().
eval_B()
Token Bif_F12_FORMAT::eval_B (Value_P B) const protected virtual
Overloaded Function::eval_B()
Reimplemented from Function.
Definition at line 37 of file Bif_F12_FORMAT.cc.
References Shape::add_shape_item(), PrintBuffer::get_column_count(), PrintBuffer::get_line(), Workspace::get_PrintContext(), PrintBuffer::get_row_count(), Shape::get_volume(), PrintBuffer::is_rectangular(), UCS_string::map_pad(), monadic_format(), and Shape::set_last_shape_item().
format_by_example()
Value_P Bif_F12_FORMAT::format_by_example (Value_P A, Value_P B) static protected
A character array with B formatted by example.
Definition at line 222 of file Bif_F12_FORMAT.cc.
References Shape::add_shape_item(), UCS_string::append(), Cell::get_real_value(), Cell::is_real_cell(), Shape::set_last_shape_item(), UCS_string::size(), and split_example_into_columns().
Referenced by eval_AB().
format_by_specification()
Value_P Bif_F12_FORMAT::format_by_specification (Value_P A, Value_P B) static
A character array with B formatted by specification.
Definition at line 929 of file Bif_F12_FORMAT.cc.
References Shape::add_shape_item(), PrintBuffer::append_col(), format_one_col_by_spec(), PrintBuffer::get_char(), Shape::get_cols(), PrintBuffer::get_column_count(), PrintBuffer::get_row_count(), Shape::get_rows(), Shape::get_volume(), PrintBuffer::pad_l(), Shape::set_last_shape_item(), and Shape::without_last_axis().
Referenced by Bif_F12_DOMINO::Matrix< cplx >::debug(), and eval_AB().
format_float_by_spec()
UCS_string Bif_F12_FORMAT::format_float_by_spec (APL_Float value, int precision) static protected
format value with precision mantissa digits (floating format)
Definition at line 1178 of file Bif_F12_FORMAT.cc.
References UCS_string::erase(), UCS_string::from_double_to_fixed(), and UCS_string::size().
Referenced by format_one_col_by_spec().
format_one_col_by_spec()
PrintBuffer Bif_F12_FORMAT::format_one_col_by_spec (int width, int precision, const Cell * cB, ShapeItem cols, ShapeItem rows) static protected
A character array with one column of B formatted by specification.
Definition at line 1008 of file Bif_F12_FORMAT.cc.
References add_row(), UCS_string::append(), PrintBuffer::append_ucs(), format_float_by_spec(), format_one_col_by_spec(), UCS_string::from_double_to_expo(), Cell::get_char_value(), PrintBuffer::get_column_count(), Workspace::get_FC(), Cell::get_imag_value(), PrintBuffer::get_line(), Cell::get_pointer_value(), Cell::get_real_value(), Cell::is_character_cell(), Cell::is_complex_cell(), Cell::is_numeric(), Cell::is_pointer_cell(), Cell::is_real_cell(), PrintBuffer::pad_l(), UCS_string::remove_leading_whitespaces(), and UCS_string::size().
Referenced by format_by_specification(), and format_one_col_by_spec().
is_control_char()
bool Bif_F12_FORMAT::is_control_char (Unicode uni) static
Return true iff uni is '0' .. '9', comma, or full-stop.
Definition at line 921 of file Bif_F12_FORMAT.cc.
References Avec::is_digit().
Referenced by Quad_FC::assign(), Quad_FC::assign_indexed(), and Bif_F12_FORMAT::Format_LIFER::Format_LIFER().
monadic_format()
Value_P Bif_F12_FORMAT::monadic_format (Value_P B) static
A character array with the display of B.
Definition at line 189 of file Bif_F12_FORMAT.cc.
References PrintBuffer::get_char(), PrintBuffer::get_column_count(), Workspace::get_PrintContext(), and PrintBuffer::get_row_count().
Referenced by eval_B().
split_example_into_columns()
void Bif_F12_FORMAT::split_example_into_columns (const UCS_string & format, std::vector< UCS_string > & col_formats) static protected
split entire format string string into column format strings
Definition at line 322 of file Bif_F12_FORMAT.cc.
References UCS_string::append(), UCS_string::back(), Avec::is_digit(), and UCS_string::size().
Referenced by format_by_example().
Member Data Documentation
_fun
Bif_F12_FORMAT Bif_F12_FORMAT::_fun static
Built-in function.
Definition at line 99 of file Bif_F12_FORMAT.hh.
fun
Bif_F12_FORMAT * Bif_F12_FORMAT::fun = &Bif_F12_FORMAT::_fun static
Built-in function.
Definition at line 98 of file Bif_F12_FORMAT.hh.
The documentation for this class was generated from the following files:
src/Bif_F12_FORMAT.hh
src/Bif_F12_FORMAT.cc