GNU APL: Plot_data Class Reference
Plot_data Class Reference
the data to be plotted
#include <Plot_data.hh>
Public Member Functions
Plot_data (uint32_t rows)
constructor
~Plot_data ()
destructor
uint32_t get_row_count () const
return the number of plot lines
void get_XY (double &X, double &Y, uint32_t row, uint32_t col) const
return the X and Y values of the data matrix row/col
double get_min_X () const
return the smallest X value in the data matrix
double get_max_X () const
return the largest X value in the data matrix
double get_min_Y () const
return the smallest Y value in the data matrix
double get_max_Y () const
return the largest Y value in the data matrix
double get_min_Z () const
return the smallest Z value in the data matrix
double get_max_Z () const
return the largest Z value in the data matrix
double get_X (uint32_t row, uint32_t col) const
return the X coordinate at row and col
double get_Y (uint32_t row, uint32_t col) const
return the Y coordinate at row and col
double get_Z (uint32_t row, uint32_t col) const
return the Z coordinate at row and col
bool is_surface_plot () const
return true for surface plots
void add_row (const Plot_data_row *row)
add a row to the data matrix
const Plot_data_row & operator[] (ShapeItem idx) const
return the idx'th row
Static Public Member Functions
static const char * uint32_t_to_str (uint32_t val)
convert integer to a string
static const char * Pixel_X_to_str (Pixel_X val)
val as string with unit 'pixel'
static const char * Pixel_Y_to_str (Pixel_Y val)
val as string with unit 'pixel'
static const char * double_to_str (double val)
convert a double to a string
static const char * Color_to_str (Color val)
convert a Color to a string
static String String_to_str (String val)
convert a String to a string
static Pixel_X Pixel_X_from_str (const char *str, const char *&error)
convert a string to a Pixel
static Pixel_Y Pixel_Y_from_str (const char *str, const char *&error)
convert a string to a Pixel
static double double_from_str (const char *str, const char *&error)
convert a string to a double
static Color Color_from_str (const char *str, const char *&error)
convert a string like "#RGB" or "#RRGGB" to a color
static uint32_t uint32_t_from_str (const char *str, const char *&error)
convert a string to a uint32_t
static String String_from_str (const char *str, const char *&error)
convert a string to a String
Public Attributes
bool surface
true for surface plots
Protected Attributes
const Plot_data_row ** data_rows
the rows of the data matrix (0-terminated)
const uint32_t row_count
the number of rows in the data matrix
uint32_t idx
the current number of columns in the data matrix
double min_X
the smallest value in X
double max_X
the largest value in X
double min_Y
the smallest value in Y
double max_Y
the largest value in Y
double min_Z
the smallest value in Z
double max_Z
the largest value in Z
Detailed Description
the data to be plotted
Definition at line 190 of file Plot_data.hh.
Constructor & Destructor Documentation
Plot_data()
Plot_data::Plot_data (uint32_t rows) inline
constructor
Definition at line 194 of file Plot_data.hh.
References data_rows, and row_count.
~Plot_data()
Plot_data::~Plot_data () inline
destructor
Definition at line 203 of file Plot_data.hh.
References data_rows, and idx.
Member Function Documentation
add_row()
void Plot_data::add_row (const Plot_data_row * row) inline
add a row to the data matrix
Definition at line 261 of file Plot_data.hh.
References data_rows, Plot_data_row::get_max_X(), get_max_X(), Plot_data_row::get_max_Y(), get_max_Y(), Plot_data_row::get_max_Z(), get_max_Z(), Plot_data_row::get_min_X(), Plot_data_row::get_min_Y(), Plot_data_row::get_min_Z(), idx, max_X, max_Y, max_Z, min_X, min_Y, min_Z, and row_count.
Referenced by Quad_PLOT::setup_data_2D(), Quad_PLOT::setup_data_2D_2b(), and Quad_PLOT::setup_data_3D().
Color_from_str()
Color Plot_data::Color_from_str (const char * str, const char *& error) static
convert a string like "#RGB" or "#RRGGB" to a color
Definition at line 25 of file Plot_data.cc.
Referenced by Plot_window_properties::set_attribute().
Color_to_str()
static const char * Plot_data::Color_to_str (Color val) inline static
convert a Color to a string
Definition at line 322 of file Plot_data.hh.
Referenced by Plot_window_properties::print().
double_from_str()
static double Plot_data::double_from_str (const char * str, const char *& error) inline static
convert a string to a double
Definition at line 350 of file Plot_data.hh.
double_to_str()
static const char * Plot_data::double_to_str (double val) inline static
convert a double to a string
Definition at line 313 of file Plot_data.hh.
get_max_X()
double Plot_data::get_max_X () const inline
return the largest X value in the data matrix
Definition at line 226 of file Plot_data.hh.
References max_X.
Referenced by add_row(), and Plot_window_properties::update().
get_max_Y()
double Plot_data::get_max_Y () const inline
return the largest Y value in the data matrix
Definition at line 234 of file Plot_data.hh.
References max_Y.
Referenced by add_row(), and Plot_window_properties::update().
get_max_Z()
double Plot_data::get_max_Z () const inline
return the largest Z value in the data matrix
Definition at line 242 of file Plot_data.hh.
References max_Z.
Referenced by add_row(), and Plot_window_properties::update().
get_min_X()
double Plot_data::get_min_X () const inline
return the smallest X value in the data matrix
Definition at line 222 of file Plot_data.hh.
References min_X.
Referenced by Plot_window_properties::update().
get_min_Y()
double Plot_data::get_min_Y () const inline
return the smallest Y value in the data matrix
Definition at line 230 of file Plot_data.hh.
References min_Y.
Referenced by Plot_window_properties::update().
get_min_Z()
double Plot_data::get_min_Z () const inline
return the smallest Z value in the data matrix
Definition at line 238 of file Plot_data.hh.
References min_Z.
Referenced by Plot_window_properties::update().
get_row_count()
uint32_t Plot_data::get_row_count () const inline
return the number of plot lines
Definition at line 210 of file Plot_data.hh.
References row_count.
Referenced by draw_plot_lines(), and draw_surface_lines().
get_X()
double Plot_data::get_X (uint32_t row, uint32_t col) const inline
return the X coordinate at row and col
Definition at line 246 of file Plot_data.hh.
References data_rows, and Plot_data_row::get_X().
Referenced by draw_surface_lines().
get_XY()
void Plot_data::get_XY (double & X, double & Y, uint32_t row, uint32_t col) const inline
return the X and Y values of the data matrix row/col
Definition at line 214 of file Plot_data.hh.
References data_rows, Plot_data_row::get_X(), Plot_data_row::get_Y(), and idx.
Referenced by draw_plot_lines().
get_Y()
double Plot_data::get_Y (uint32_t row, uint32_t col) const inline
return the Y coordinate at row and col
Definition at line 250 of file Plot_data.hh.
References data_rows, and Plot_data_row::get_Y().
Referenced by draw_surface_lines().
get_Z()
double Plot_data::get_Z (uint32_t row, uint32_t col) const inline
return the Z coordinate at row and col
Definition at line 254 of file Plot_data.hh.
References data_rows, and Plot_data_row::get_Z().
Referenced by draw_surface_lines().
is_surface_plot()
bool Plot_data::is_surface_plot () const inline
return true for surface plots
Definition at line 258 of file Plot_data.hh.
References surface.
Referenced by do_plot().
operator[]()
const Plot_data_row & Plot_data::operator[] (ShapeItem idx) const inline
return the idx'th row
Definition at line 338 of file Plot_data.hh.
References data_rows, idx, and row_count.
Pixel_X_from_str()
static Pixel_X Plot_data::Pixel_X_from_str (const char * str, const char *& error) inline static
convert a string to a Pixel
Definition at line 342 of file Plot_data.hh.
Pixel_X_to_str()
static const char * Plot_data::Pixel_X_to_str (Pixel_X val) inline static
val as string with unit 'pixel'
Definition at line 295 of file Plot_data.hh.
Pixel_Y_from_str()
static Pixel_Y Plot_data::Pixel_Y_from_str (const char * str, const char *& error) inline static
convert a string to a Pixel
Definition at line 346 of file Plot_data.hh.
Pixel_Y_to_str()
static const char * Plot_data::Pixel_Y_to_str (Pixel_Y val) inline static
val as string with unit 'pixel'
Definition at line 304 of file Plot_data.hh.
String_from_str()
static String Plot_data::String_from_str (const char * str, const char *& error) inline static
convert a string to a String
Definition at line 361 of file Plot_data.hh.
String_to_str()
static String Plot_data::String_to_str (String val) inline static
convert a String to a string
Definition at line 332 of file Plot_data.hh.
uint32_t_from_str()
static uint32_t Plot_data::uint32_t_from_str (const char * str, const char *& error) inline static
convert a string to a uint32_t
Definition at line 357 of file Plot_data.hh.
uint32_t_to_str()
static const char * Plot_data::uint32_t_to_str (uint32_t val) inline static
convert integer to a string
Definition at line 286 of file Plot_data.hh.
Member Data Documentation
data_rows
const Plot_data_row** Plot_data::data_rows protected
the rows of the data matrix (0-terminated)
Definition at line 369 of file Plot_data.hh.
Referenced by add_row(), get_X(), get_XY(), get_Y(), get_Z(), operator[](), Plot_data(), and ~Plot_data().
idx
uint32_t Plot_data::idx protected
the current number of columns in the data matrix
Definition at line 375 of file Plot_data.hh.
Referenced by add_row(), get_XY(), operator[](), and ~Plot_data().
max_X
double Plot_data::max_X protected
the largest value in X
Definition at line 381 of file Plot_data.hh.
Referenced by add_row(), and get_max_X().
max_Y
double Plot_data::max_Y protected
the largest value in Y
Definition at line 387 of file Plot_data.hh.
Referenced by add_row(), and get_max_Y().
max_Z
double Plot_data::max_Z protected
the largest value in Z
Definition at line 393 of file Plot_data.hh.
Referenced by add_row(), and get_max_Z().
min_X
double Plot_data::min_X protected
the smallest value in X
Definition at line 378 of file Plot_data.hh.
Referenced by add_row(), and get_min_X().
min_Y
double Plot_data::min_Y protected
the smallest value in Y
Definition at line 384 of file Plot_data.hh.
Referenced by add_row(), and get_min_Y().
min_Z
double Plot_data::min_Z protected
the smallest value in Z
Definition at line 390 of file Plot_data.hh.
Referenced by add_row(), and get_min_Z().
row_count
const uint32_t Plot_data::row_count protected
the number of rows in the data matrix
Definition at line 372 of file Plot_data.hh.
Referenced by add_row(), get_row_count(), operator[](), and Plot_data().
surface
bool Plot_data::surface
true for surface plots
Definition at line 365 of file Plot_data.hh.
Referenced by is_surface_plot(), Plot_window_properties::Plot_window_properties(), and Quad_PLOT::setup_data_3D().
The documentation for this class was generated from the following files:
src/Plot_data.hh
src/Plot_data.cc