GNU APL: Sig_item_int< T, bytes > Class Template Reference
Sig_item_int< T, bytes > Class Template Reference
an integer signal item of size bytes
#include <Svar_signals.hh>
Public Member Functions
Sig_item_int (T v)
construct an item with value v
Sig_item_int (const uint8_t *&buffer)
construct (deserialize) this item from a (received) buffer
T get_svalue () const
return the value of the item
void store (string &buffer) const
store (aka. serialize) this item into a string
ostream & print (ostream &out) const
print the item
Static Public Member Functions
static uint64_t get_mask ()
return the mask of the item, e.g. 0x00FFFFFF for a 3-byte integer
Public Attributes
T value
the value of the item
Detailed Description
template<typename T, int bytes>
class Sig_item_int< T, bytes >
an integer signal item of size bytes
Definition at line 91 of file Svar_signals.hh.
Constructor & Destructor Documentation
Sig_item_int() [1/2]
template<typename T , int bytes> Sig_item_int< T, bytes >::Sig_item_int (T v) inline
construct an item with value v
Definition at line 95 of file Svar_signals.hh.
Sig_item_int() [2/2]
template<typename T , int bytes> Sig_item_int< T, bytes >::Sig_item_int (const uint8_t *& buffer) inline
construct (deserialize) this item from a (received) buffer
Definition at line 98 of file Svar_signals.hh.
References Sig_item_int< T, bytes >::value.
Member Function Documentation
get_mask()
template<typename T , int bytes> static uint64_t Sig_item_int< T, bytes >::get_mask () inline static
return the mask of the item, e.g. 0x00FFFFFF for a 3-byte integer
Definition at line 124 of file Svar_signals.hh.
get_svalue()
template<typename T , int bytes> T Sig_item_int< T, bytes >::get_svalue () const inline
return the value of the item
Definition at line 109 of file Svar_signals.hh.
References Sig_item_int< T, bytes >::value.
Referenced by ADD_EVENT_c::get__ADD_EVENT__grand(), ADD_EVENT_c::get__ADD_EVENT__key(), ADD_EVENT_c::get__ADD_EVENT__parent(), ADD_EVENT_c::get__ADD_EVENT__proc(), ASSIGN_VALUE_c::get__ASSIGN_VALUE__key(), ASSIGN_WSWS_VAR_c::get__ASSIGN_WSWS_VAR__key(), CLEAR_ALL_EVENTS_c::get__CLEAR_ALL_EVENTS__grand(), CLEAR_ALL_EVENTS_c::get__CLEAR_ALL_EVENTS__parent(), CLEAR_ALL_EVENTS_c::get__CLEAR_ALL_EVENTS__proc(), EVENTS_ARE_c::get__EVENTS_ARE__events(), EVENTS_ARE_c::get__EVENTS_ARE__key(), FIND_OFFERING_ID_c::get__FIND_OFFERING_ID__key(), FIND_PAIRING_KEY_c::get__FIND_PAIRING_KEY__key(), GET_EVENTS_c::get__GET_EVENTS__grand(), GET_EVENTS_c::get__GET_EVENTS__parent(), GET_EVENTS_c::get__GET_EVENTS__proc(), GET_OFFERED_VARS_c::get__GET_OFFERED_VARS__accepted_by_proc(), GET_OFFERED_VARS_c::get__GET_OFFERED_VARS__offered_to_proc(), GET_OFFERING_PROCS_c::get__GET_OFFERING_PROCS__offered_to_proc(), GET_VALUE_c::get__GET_VALUE__key(), IS_REGISTERED_ID_c::get__IS_REGISTERED_ID__grand(), IS_REGISTERED_ID_c::get__IS_REGISTERED_ID__parent(), IS_REGISTERED_ID_c::get__IS_REGISTERED_ID__proc(), MAKE_OFFER_c::get__MAKE_OFFER__key(), MATCH_OR_MAKE_c::get__MATCH_OR_MAKE__from_grand(), MATCH_OR_MAKE_c::get__MATCH_OR_MAKE__from_parent(), MATCH_OR_MAKE_c::get__MATCH_OR_MAKE__from_proc(), MATCH_OR_MAKE_c::get__MATCH_OR_MAKE__to_grand(), MATCH_OR_MAKE_c::get__MATCH_OR_MAKE__to_parent(), MATCH_OR_MAKE_c::get__MATCH_OR_MAKE__to_proc(), MATCH_OR_MAKE_RESULT_c::get__MATCH_OR_MAKE_RESULT__key(), MAY_SET_c::get__MAY_SET__attempt(), MAY_SET_c::get__MAY_SET__key(), MAY_USE_c::get__MAY_USE__attempt(), MAY_USE_c::get__MAY_USE__key(), OFFERING_ID_IS_c::get__OFFERING_ID_IS__grand(), OFFERING_ID_IS_c::get__OFFERING_ID_IS__parent(), OFFERING_ID_IS_c::get__OFFERING_ID_IS__proc(), PAIRING_KEY_IS_c::get__PAIRING_KEY_IS__pairing_key(), READ_SVAR_RECORD_c::get__READ_SVAR_RECORD__key(), READ_WSWS_VAR_c::get__READ_WSWS_VAR__key(), REGISTER_PROCESSOR_c::get__REGISTER_PROCESSOR__evconn(), REGISTER_PROCESSOR_c::get__REGISTER_PROCESSOR__grand(), REGISTER_PROCESSOR_c::get__REGISTER_PROCESSOR__parent(), REGISTER_PROCESSOR_c::get__REGISTER_PROCESSOR__proc(), RETRACT_OFFER_c::get__RETRACT_OFFER__key(), RETRACT_VAR_c::get__RETRACT_VAR__key(), SET_CONTROL_c::get__SET_CONTROL__key(), SET_CONTROL_c::get__SET_CONTROL__new_control(), SET_STATE_c::get__SET_STATE__key(), SET_STATE_c::get__SET_STATE__new_state(), SVAR_ASSIGNED_c::get__SVAR_ASSIGNED__error(), SVAR_ASSIGNED_c::get__SVAR_ASSIGNED__key(), VALUE_IS_c::get__VALUE_IS__error(), VALUE_IS_c::get__VALUE_IS__key(), YES_NO_c::get__YES_NO__yes(), Signal_base::recv_TCP(), and Sig_item_string::Sig_item_string().
print()
template<typename T , int bytes> ostream & Sig_item_int< T, bytes >::print (ostream & out) const inline
print the item
Definition at line 118 of file Svar_signals.hh.
References Sig_item_int< T, bytes >::value.
Referenced by SET_STATE_c::print(), SET_CONTROL_c::print(), VALUE_IS_c::print(), SVAR_ASSIGNED_c::print(), MAY_USE_c::print(), MAY_SET_c::print(), IS_REGISTERED_ID_c::print(), YES_NO_c::print(), REGISTER_PROCESSOR_c::print(), MATCH_OR_MAKE_c::print(), OFFERING_ID_IS_c::print(), GET_OFFERING_PROCS_c::print(), GET_OFFERED_VARS_c::print(), GET_EVENTS_c::print(), CLEAR_ALL_EVENTS_c::print(), EVENTS_ARE_c::print(), and ADD_EVENT_c::print().
store()
template<typename T , int bytes> void Sig_item_int< T, bytes >::store (string & buffer) const inline
store (aka. serialize) this item into a string
Definition at line 112 of file Svar_signals.hh.
References Sig_item_int< T, bytes >::value.
Referenced by Sig_item_string::store(), MAKE_OFFER_c::store(), RETRACT_OFFER_c::store(), RETRACT_VAR_c::store(), SET_STATE_c::store(), SET_CONTROL_c::store(), GET_VALUE_c::store(), VALUE_IS_c::store(), ASSIGN_VALUE_c::store(), SVAR_ASSIGNED_c::store(), MAY_USE_c::store(), MAY_SET_c::store(), READ_SVAR_RECORD_c::store(), SVAR_RECORD_IS_c::store(), IS_REGISTERED_ID_c::store(), YES_NO_c::store(), REGISTER_PROCESSOR_c::store(), MATCH_OR_MAKE_c::store(), MATCH_OR_MAKE_RESULT_c::store(), FIND_OFFERING_ID_c::store(), OFFERING_ID_IS_c::store(), GET_OFFERING_PROCS_c::store(), OFFERING_PROCS_ARE_c::store(), GET_OFFERED_VARS_c::store(), OFFERED_VARS_ARE_c::store(), FIND_PAIRING_KEY_c::store(), PAIRING_KEY_IS_c::store(), GET_EVENTS_c::store(), CLEAR_ALL_EVENTS_c::store(), EVENTS_ARE_c::store(), ADD_EVENT_c::store(), ASSIGN_WSWS_VAR_c::store(), READ_WSWS_VAR_c::store(), WSWS_VALUE_IS_c::store(), PRINT_SVAR_DB_c::store(), and SVAR_DB_PRINTED_c::store().
Member Data Documentation
value
template<typename T , int bytes> T Sig_item_int< T, bytes >::value
the value of the item
Definition at line 131 of file Svar_signals.hh.
Referenced by Sig_item_int< T, bytes >::get_svalue(), Sig_item_int< T, bytes >::print(), Sig_item_int< T, bytes >::Sig_item_int(), and Sig_item_int< T, bytes >::store().
The documentation for this class was generated from the following file:
src/Svar_signals.hh