GNUAPL: src/Common.cc File Reference
Common.cc File Reference
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
#include <time.h>
#include "Common.hh"
#include "LineInput.hh"
#include "LibPaths.hh"
#include "NativeFunction.hh"
#include "Output.hh"
#include "Parallel.hh"
#include "ProcessorID.hh"
#include "Quad_WA.hh"
#include "Svar_DB.hh"
#include "Symbol.hh"
#include "StateIndicator.hh"
#include "Thread_context.hh"
#include "Token.hh"
#include "Value.hh"
#include "UserFunction.hh"
#include "UserPreferences.hh"
#include "ValueHistory.hh"
Functions
void set_attention_raised (const char *loc)
set the attention_raised flag
void clear_attention_raised (const char *loc)
clear the attention_raised flag
bool attention_is_raised ()
true if Control-C was hit (once)
void set_interrupt_raised (const char *loc)
set the interrupt_raised flag
void clear_interrupt_raised (const char *loc)
clear the interrupt_raised flag
bool interrupt_is_raised ()
true if Control-C was hit twice within 500 ms
void init_1 (const char *argv0, bool log_startup)
initialize
void init_2 (bool log_startup)
initialize subsystems that depend on argv[]
void cleanup (bool soft)
the opposite of init()
void control_C (int)
signal handler for ^C
void * common_new (size_t size)
void common_delete (void *p)
APL_time_us now ()
current time as microseconds since epoch
ostream & operator<< (ostream &out, const Function_PC2 &ft)
ostream & print_flags (ostream &out, ValueFlags flags)
int nibble (Unicode uni)
value 0-15 of hex digit, or -1 if uni not in "023456789ABCDEFabcdef"
int sixbit (Unicode uni)
value 0-63 of base64 digit, or -1 if uni not base64 (RFC 4648)
Variables
bool got_WINCH = false
true when a WINCH (window size changed) signal was received
static bool attention_raised = false
static uint64_t attention_count = 0
APL_time_us interrupt_when = 0
time when ^C was hit last
uint64_t interrupt_count = 0
the number of Control-C signals received
static bool interrupt_raised = false
Function Documentation
attention_is_raised()
bool attention_is_raised ()
true if Control-C was hit (once)
Definition at line 61 of file Common.cc.
References attention_raised.
Referenced by Quad_DL::eval_B(), Command::finish_context(), Prefix::reduce_END_B__(), Prefix::reduce_END_GOTO_B_(), Prefix::reduce_END_VOID__(), and DLX_Root_Node::solve().
cleanup()
void cleanup (bool soft)
the opposite of init()
clean up
Definition at line 162 of file Common.cc.
References NativeFunction::cleanup(), ID::cleanup(), Thread_context::cleanup(), LineInput::close(), ProcessorID::disconnect(), and Output::reset_colors().
Referenced by Command::cmd_OFF(), Quad_EX::expunge(), IO_Files::get_file_line(), signal_HUP_handler(), signal_TERM_handler(), and Quad_XML::XML_to_APL().
clear_attention_raised()
void clear_attention_raised (const char * loc)
clear the attention_raised flag
Definition at line 57 of file Common.cc.
References attention_raised.
Referenced by PrintBuffer::do_PrintBuffer(), Bif_OPER2_POWER::eval_form_2(), Command::finish_context(), PrintBuffer::print_interruptible(), Prefix::reduce_END_B__(), Prefix::reduce_END_GOTO_B_(), Prefix::reduce_END_VOID__(), and DLX_Root_Node::solve().
clear_interrupt_raised()
void clear_interrupt_raised (const char * loc)
clear the interrupt_raised flag
Definition at line 73 of file Common.cc.
References interrupt_raised.
Referenced by PrintBuffer::do_PrintBuffer(), Bif_OPER2_POWER::eval_form_2(), Command::finish_context(), PrintBuffer::print_interruptible(), Prefix::reduce_END_B__(), Prefix::reduce_END_GOTO_B_(), Prefix::reduce_END_VOID__(), and DLX_Root_Node::solve().
common_delete()
void common_delete (void * p)
Definition at line 230 of file Common.cc.
References CERR, and HEX.
common_new()
void* common_new (size_t size)
Definition at line 220 of file Common.cc.
References CERR, and HEX.
control_C()
void control_C (int)
signal handler for ^C
Definition at line 188 of file Common.cc.
References attention_count, attention_raised, CIN, Probe::dummy, interrupt_count, interrupt_raised, interrupt_when, now(), Probe::P0, Probe::P_1, Probe::P_2, Probe::P_3, Probe::P_4, Probe::P_5, Probe::PROBE_COUNT, and Probe::probes.
Referenced by LineInput::edit_line(), and init_apl().
init_1()
void init_1 (const char * argv0, bool log_startup)
initialize
Definition at line 83 of file Common.cc.
References CERR, Avec::init(), Quad_WA::init(), VH_entry::init(), LibPaths::init(), Value::init(), RLIM_INFINITY, Quad_WA::total_memory, and Value.
Referenced by do_init(), init_apl(), init_libapl(), and Unicode_to_UTF8().
init_2()
void init_2 (bool log_startup)
initialize subsystems that depend on argv[]
Definition at line 147 of file Common.cc.
References UserPreferences::emacs_mode, LibPaths::get_APL_bin_name(), LibPaths::get_APL_bin_path(), Svar_DB::init(), Output::init(), Parallel::init(), LineInput::init(), UserPreferences::system_do_svars, and uprefs.
Referenced by do_init(), init_apl(), init_libapl(), and Unicode_to_UTF8().
interrupt_is_raised()
bool interrupt_is_raised ()
true if Control-C was hit twice within 500 ms
Definition at line 77 of file Common.cc.
References interrupt_raised.
Referenced by Quad_DL::eval_B(), Bif_OPER2_POWER::eval_form_2(), Quad_QUOTE::get_apl_value(), PrintBuffer::print_interruptible(), Prefix::reduce_END_B__(), Prefix::reduce_END_GOTO_B_(), Prefix::reduce_END_VOID__(), and DLX_Root_Node::solve().
nibble()
int nibble (Unicode uni)
value 0-15 of hex digit, or -1 if uni not in "023456789ABCDEFabcdef"
Definition at line 294 of file Common.cc.
References UNI_0, UNI_9, UNI_A, UNI_a, UNI_F, and UNI_f.
Referenced by Quad_CR::do_CR13(), and Quad_CR::do_CR15().
now()
APL_time_us now ()
current time as microseconds since epoch
Definition at line 237 of file Common.cc.
Referenced by Quad_SVE::assign(), Command::cmd_DROP(), Quad_TZ::compute_offset(), control_C(), Workspace::dump_WS(), Quad_DL::eval_B(), Quad_SVE::get_apl_value(), Quad_AI::get_apl_value(), Quad_TS::get_apl_value(), InputMux::get_line(), Command::transfer_context::process_record(), InputFile::randomize_files(), XML_Saving_Archive::save(), Workspace::save_WS(), and UserFunction::UserFunction().
operator<<()
ostream& operator<< (ostream & out, const Function_PC2 & ft)
Definition at line 281 of file Common.cc.
References Function_PC2::high, and Function_PC2::low.
print_flags()
ostream& print_flags (ostream & out, ValueFlags flags)
Definition at line 287 of file Common.cc.
References VF_complete, and VF_marked.
Referenced by operator<<(), and Symbol::push_value().
set_attention_raised()
void set_attention_raised (const char * loc)
set the attention_raised flag
Definition at line 53 of file Common.cc.
References attention_raised.
Referenced by Value::init_ravel(), and Workspace::push_SI().
set_interrupt_raised()
void set_interrupt_raised (const char * loc)
set the interrupt_raised flag
Definition at line 69 of file Common.cc.
References interrupt_raised.
Referenced by Value::init_ravel(), and Workspace::push_SI().
sixbit()
int sixbit (Unicode uni)
value 0-63 of base64 digit, or -1 if uni not base64 (RFC 4648)
Definition at line 308 of file Common.cc.
References UNI_0, UNI_9, UNI_A, UNI_a, UNI_EQUAL, UNI_MINUS, UNI_PLUS, UNI_SLASH, UNI_UNDERSCORE, UNI_Z, and UNI_z.
Referenced by Quad_CR::do_CR17().
Variable Documentation
attention_count
uint64_t attention_count = 0 static
Definition at line 51 of file Common.cc.
Referenced by control_C().
attention_raised
bool attention_raised = false static
Definition at line 50 of file Common.cc.
Referenced by attention_is_raised(), clear_attention_raised(), control_C(), and set_attention_raised().
got_WINCH
bool got_WINCH = false
true when a WINCH (window size changed) signal was received
Definition at line 47 of file Common.cc.
Referenced by LineInput::safe_fgetc(), and signal_WINCH_handler().
interrupt_count
uint64_t interrupt_count = 0
the number of Control-C signals received
Definition at line 67 of file Common.cc.
Referenced by control_C(), and PrintBuffer::do_PrintBuffer().
interrupt_raised
bool interrupt_raised = false static
Definition at line 68 of file Common.cc.
Referenced by clear_interrupt_raised(), control_C(), interrupt_is_raised(), and set_interrupt_raised().
interrupt_when
APL_time_us interrupt_when = 0
time when ^C was hit last
Definition at line 66 of file Common.cc.
Referenced by control_C().