GNUAPL: src/Error.cc File Reference
Error.cc File Reference
#include "Common.hh"
#include "Error.hh"
#include "Output.hh"
#include "PrintOperator.hh"
#include "Symbol.hh"
#include "StateIndicator.hh"
#include "UserFunction.hh"
#include "Workspace.hh"
#include "Error.def"
Macros
#define err_def(c, txt, _maj, _min) case E_ ## c: return txt;
#define err_def(c, _txt, _maj, _min) case E_ ## c: return true;
Functions
void throw_apl_error (ErrorCode code, const char *loc)
throw an Error with code only (typically a standard APL error)
Macro Definition Documentation
err_def [1/2]
#define err_def (c, txt, _maj, _min) case E_ ## c: return txt;
err_def [2/2]
#define err_def (c, _txt, _maj, _min) case E_ ## c: return true;
Function Documentation
throw_apl_error()
void throw_apl_error (ErrorCode code, const char * loc)
throw an Error with code only (typically a standard APL error)
Definition at line 183 of file Error.cc.
References ADD_EVENT, BACKTRACE, CERR, E_DOMAIN_ERROR, error, Error::error_name(), UserFunction::get_exec_properties(), Executable::get_exec_ufun(), StateIndicator::get_executable(), StateIndicator::get_safe_execution(), Log, Workspace::SI_top(), Error::update_error_info(), and VHE_Error.
Referenced by Symbol::assign_shared_variable(), Shape::check_same(), Bif_REDUCE::do_reduce(), Quad_PLOT::eval_AB(), Bif_F12_ROLL::eval_AB(), Bif_OPER2_INNER::eval_ALRB(), Bif_OPER2_OUTER::eval_ALRB(), ScalarFunction::eval_scalar_AB(), ScalarFunction::eval_scalar_B(), Quad_INP::eval_XB(), Bif_F1_EXECUTE::execute_command(), Value::init_ravel(), UserFunction::load(), Symbol::resolve_lv(), Symbol::resolve_shared_variable(), and Prefix::syntax_error().