GNUAPL: src/FloatCell.cc File Reference
FloatCell.cc File Reference
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <complex>
#include "Common.hh"
#include "ComplexCell.hh"
#include "Error.hh"
#include "FloatCell.hh"
#include "IntCell.hh"
#include "UTF8_string.hh"
#include "Workspace.hh"
#include "Cell.icc"
#include "Value.hh"
Functions
double p_modulo_q (double P, double Q)
Function Documentation
p_modulo_q()
double p_modulo_q (double P, double Q) inline
Definition at line 647 of file FloatCell.cc.
References floor(), Workspace::get_CT(), Cell::integral_within(), isfinite(), and Q.
Referenced by FloatCell::bif_residue().