GNUAPL: src/LApack.hh File Reference
LApack.hh File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
Classes
class ZZ
a complex number
class DZ
A single double or complex number.
class Vector< T >
A vector of real numbers or a vector of complex numbers.
class Matrix< T >
A double or complex matrix.
Macros
#define assert(x)
#define MAX(x, y) ((x) >= (y) ? (x) : (y))
the maximum of x and y
#define MIN(x, y) ((x) <= (y) ? (x) : (y))
the minimum of x and y
#define dlamch_E 1.11022e-16
#define dlamch_S 2.22507e-308
#define dlamch_P 2.22045e-16
Typedefs
typedef APL_Float DD
a real number
Functions
template<typename T >
APL_Float REAL (T x)
return the real part of x
template<typename T >
APL_Float IMAG (T x)
return the imaginary part of x
template<typename T >
void SREAL (T &y, APL_Float x)
set the real part of x
template<typename T >
void SIMAG (T &y, APL_Float x)
set the imaginary part of x
template<typename T >
void Sri (T &y, APL_Float xr, APL_Float xi)
set the real and imaginary parts of y
template<typename T >
void Sri (T &y, APL_Float xr)
set the real part of y and clear its imaginary part
DD ABS (DD a)
return the absolute value of a
DD ABS_2 (DD a)
return the square of the absolute value of a
DD ABS (ZZ z)
return the absolute value of z
DD ABS_2 (ZZ z)
return the square of the absolute value of z
APL_Float SIGN (APL_Float a, APL_Float b)
return abs(a) with the sign of b
template<typename T >
void exchange (T &x, T &y)
swap x and y
ShapeItem max_pos (const APL_Float *vec, ShapeItem len)
return the offset of the largest element in vec
template<typename T >
T larfg (ShapeItem N, T &ALPHA, Vector< T > &x)
LApack function larfg.
template<typename T >
void trsm (int M, int N, const Matrix< T > &A, Matrix< T > &B)
LApack function trsm.
template<typename T >
int ila_lc (ShapeItem M, ShapeItem N, const Matrix< T > &A)
LApack function ila_lc.
template<typename T >
void gemv (int M, int N, const Matrix< T > &A, const Vector< T > &x, Vector< T > &y)
LApack function gemv.
template<typename T >
void gerc (int M, int N, T ALPHA, const Vector< T > &x, const Vector< T > &y, Matrix< T > &A)
LApack function gerc.
template<typename T >
void larf (Vector< T > &v, T tau, Matrix< T > &c)
LApack function larf.
template<typename T >
void laqp2 (Matrix< T > &A, ShapeItem *pivot, T *tau, APL_Float *vn1)
LApack function laqp2.
template<typename T >
void laic1_max (APL_Float SEST, T alpha, T GAMMA, APL_Float &SESTPR, T &S, T &C)
LApack function laic1 (maximum case)
template<typename T >
void laic1_min (APL_Float SEST, T alpha, T GAMMA, APL_Float &SESTPR, T &S, T &C)
LApack function laic1 (minimum case)
template<typename T >
void unm2r (ShapeItem K, Matrix< T > &A, const T *tau, Matrix< T > &c)
LApack function unm2r.
template<typename T >
void geqp3 (Matrix< T > &A, ShapeItem *pivot, T *tau)
LApack function geqp3.
template<typename T >
int estimate_rank (const Matrix< T > &A, APL_Float rcond)
LApack function estimating the rank of A.
template<typename T >
int scaled_gelsy (Matrix< T > &A, Matrix< T > &B, double rcond)
template<typename T >
int gelsy (Matrix< T > &A, Matrix< T > &B, APL_Float rcond)
Variables
static const APL_Float small_number = 2.22507e-308 / 2.22045e-16
static const APL_Float big_number = 1.0 / small_number
static const APL_Float safe_min = 2.22507e-308 / 1.11022e-16
static const APL_Float inv_safe_min = 1.0 / safe_min
static const APL_Float tol3z = sqrt(1.11022e-16)
Macro Definition Documentation
assert
#define assert (x)
Definition at line 70 of file LApack.hh.
Referenced by Vector< T >::add(), Vector< T >::at(), Matrix< T >::at(), Signal_base::bad_get(), Matrix< T >::diag(), Quad_SVO::eval_AB(), Matrix< T >::exchange_columns(), larfg(), Matrix< T >::Matrix(), Backtrace::open_lines_file(), DZ::set_imag(), Vector< T >::sub_len(), Matrix< T >::sub_len(), Vector< T >::sub_off(), Vector< T >::sub_off_len(), and Matrix< T >::sub_yx().
dlamch_E
#define dlamch_E 1.11022e-16
Definition at line 574 of file LApack.hh.
Referenced by laic1_max(), and laic1_min().
dlamch_P
#define dlamch_P 2.22045e-16
Definition at line 576 of file LApack.hh.
dlamch_S
#define dlamch_S 2.22507e-308
Definition at line 575 of file LApack.hh.
MAX
#define MAX (x, y) ((x) >= (y) ? (x) : (y))
the maximum of x and y
Definition at line 161 of file LApack.hh.
Referenced by laic1_max(), laic1_min(), laqp2(), and Doxy::set_call_graph_root().
MIN
#define MIN (x, y) ((x) <= (y) ? (x) : (y))
the minimum of x and y
Definition at line 164 of file LApack.hh.
Typedef Documentation
DD
typedef APL_Float DD
a real number
Definition at line 78 of file LApack.hh.
Function Documentation
ABS() [1/2]
DD ABS (DD a) inline
return the absolute value of a
Definition at line 246 of file LApack.hh.
References a.
Referenced by estimate_rank(), laic1_max(), laic1_min(), laqp2(), larfg(), max_pos(), and SIGN().
ABS() [2/2]
DD ABS (ZZ z) inline
return the absolute value of z
Definition at line 252 of file LApack.hh.
References ZZ::imag(), ZZ::real(), and sqrt().
ABS_2() [1/2]
DD ABS_2 (DD a) inline
return the square of the absolute value of a
Definition at line 249 of file LApack.hh.
References a.
Referenced by laic1_max(), laic1_min(), and Matrix< T >::max_norm().
ABS_2() [2/2]
DD ABS_2 (ZZ z) inline
return the square of the absolute value of z
Definition at line 255 of file LApack.hh.
References ZZ::imag(), and ZZ::real().
estimate_rank()
template<typename T > int estimate_rank (const Matrix< T > & A, APL_Float rcond)
LApack function estimating the rank of A.
Definition at line 1161 of file LApack.hh.
References ABS(), Matrix< T >::at(), DZ::CONJ(), Matrix< T >::diag(), Matrix< T >::get_column_count(), loop, and N.
Referenced by scaled_gelsy().
exchange()
template<typename T > void exchange (T & x, T & y) inline
swap x and y
Definition at line 266 of file LApack.hh.
References y.
Referenced by Matrix< T >::exchange_columns(), and laqp2().
gelsy()
template<typename T > int gelsy (Matrix< T > & A, Matrix< T > & B, APL_Float rcond)
Definition at line 1296 of file LApack.hh.
References Matrix< T >::get_column_count(), Matrix< T >::get_row_count(), M, Matrix< T >::max_norm(), N, Matrix< T >::scale(), scaled_gelsy(), and Matrix< T >::sub_len().
gemv()
template<typename T > void gemv (int M, int N, const Matrix< T > & A, const Vector< T > & x, Vector< T > & y) inline
LApack function gemv.
Definition at line 695 of file LApack.hh.
References Vector< T >::at(), Matrix< T >::at(), DZ::CONJ(), i, and loop.
geqp3()
template<typename T > void geqp3 (Matrix< T > & A, ShapeItem * pivot, T * tau)
LApack function geqp3.
Definition at line 1126 of file LApack.hh.
References A, Matrix< T >::at(), Matrix< T >::get_column_count(), Matrix< T >::get_row_count(), loop, M, N, and Vector< T >::norm().
gerc()
template<typename T > void gerc (int M, int N, T ALPHA, const Vector< T > & x, const Vector< T > & y, Matrix< T > & A)
LApack function gerc.
Definition at line 708 of file LApack.hh.
References Vector< T >::at(), Matrix< T >::at(), DZ::conjugate(), i, and loop.
ila_lc()
template<typename T > int ila_lc (ShapeItem M, ShapeItem N, const Matrix< T > & A)
LApack function ila_lc.
Definition at line 672 of file LApack.hh.
References Matrix< T >::get_column(), and Vector< T >::is_zero().
IMAG()
template<typename T > APL_Float IMAG (T x)
return the imaginary part of x
Definition at line 229 of file LApack.hh.
References DZ::get_imag().
Referenced by Vector< T >::is_zero(), larfg(), and Vector< T >::norm().
laic1_max()
template<typename T > void laic1_max (APL_Float SEST, T alpha, T GAMMA, APL_Float & SESTPR, T & S, T & C)
LApack function laic1 (maximum case)
Definition at line 851 of file LApack.hh.
References ABS(), ABS_2(), dlamch_E, MAX, and sqrt().
laic1_min()
template<typename T > void laic1_min (APL_Float SEST, T alpha, T GAMMA, APL_Float & SESTPR, T & S, T & C)
LApack function laic1 (minimum case)
Definition at line 959 of file LApack.hh.
References ABS(), ABS_2(), DZ::CONJ(), dlamch_E, MAX, and sqrt().
laqp2()
template<typename T > void laqp2 (Matrix< T > & A, ShapeItem * pivot, T * tau, APL_Float * vn1)
LApack function laqp2.
Definition at line 762 of file LApack.hh.
References ABS(), Vector< T >::at(), Matrix< T >::at(), c, DZ::CONJ(), Matrix< T >::diag(), exchange(), Matrix< T >::exchange_columns(), Matrix< T >::get_column_count(), Matrix< T >::get_row_count(), loop, M, MAX, max_pos(), N, sqrt(), and Matrix< T >::sub_yx().
larf()
template<typename T > void larf (Vector< T > & v, T tau, Matrix< T > & c)
LApack function larf.
Definition at line 727 of file LApack.hh.
References Vector< T >::at(), c, Matrix< T >::get_column_count(), Matrix< T >::get_row_count(), M, and N.
larfg()
template<typename T > T larfg (ShapeItem N, T & ALPHA, Vector< T > & x)
LApack function larfg.
Definition at line 600 of file LApack.hh.
References ABS(), assert, IMAG(), DZ::inv(), inv_safe_min, k, loop, Vector< T >::norm(), REAL(), safe_min, Vector< T >::scale(), SIGN(), and sqrt().
max_pos()
ShapeItem max_pos (const APL_Float * vec, ShapeItem len) inline
return the offset of the largest element in vec
Definition at line 586 of file LApack.hh.
References ABS().
Referenced by laqp2().
REAL()
template<typename T > APL_Float REAL (T x)
return the real part of x
Definition at line 226 of file LApack.hh.
References DZ::get_real().
Referenced by Vector< T >::is_zero(), larfg(), and Vector< T >::norm().
scaled_gelsy()
template<typename T > int scaled_gelsy (Matrix< T > & A, Matrix< T > & B, double rcond)
Definition at line 1224 of file LApack.hh.
References A, Matrix< T >::at(), B, estimate_rank(), Matrix< T >::get_column_count(), Matrix< T >::get_dx(), loop, N, and Matrix< T >::sub_len().
Referenced by gelsy().
SIGN()
APL_Float SIGN (APL_Float a, APL_Float b) inline
return abs(a) with the sign of b
Definition at line 258 of file LApack.hh.
References ABS().
Referenced by larfg().
SIMAG()
template<typename T > void SIMAG (T & y, APL_Float x)
set the imaginary part of x
Definition at line 235 of file LApack.hh.
References DZ::set_imag().
SREAL()
template<typename T > void SREAL (T & y, APL_Float x)
set the real part of x
Definition at line 232 of file LApack.hh.
References DZ::set_real().
Sri() [1/2]
template<typename T > void Sri (T & y, APL_Float xr, APL_Float xi)
set the real and imaginary parts of y
Definition at line 238 of file LApack.hh.
References y.
Sri() [2/2]
template<typename T > void Sri (T & y, APL_Float xr)
set the real part of y and clear its imaginary part
Definition at line 242 of file LApack.hh.
References y.
trsm()
template<typename T > void trsm (int M, int N, const Matrix< T > & A, Matrix< T > & B)
LApack function trsm.
Definition at line 647 of file LApack.hh.
References Matrix< T >::at(), Matrix< T >::diag(), and loop.
unm2r()
template<typename T > void unm2r (ShapeItem K, Matrix< T > & A, const T * tau, Matrix< T > & c)
LApack function unm2r.
Definition at line 1097 of file LApack.hh.
References DZ::CONJ(), Matrix< T >::diag(), Matrix< T >::get_row_count(), loop, M, and Matrix< T >::sub_yx().
Variable Documentation
big_number
const APL_Float big_number = 1.0 / small_number static
Definition at line 578 of file LApack.hh.
inv_safe_min
const APL_Float inv_safe_min = 1.0 / safe_min static
Definition at line 580 of file LApack.hh.
Referenced by larfg().
safe_min
const APL_Float safe_min = 2.22507e-308 / 1.11022e-16 static
Definition at line 579 of file LApack.hh.
Referenced by larfg().
small_number
const APL_Float small_number = 2.22507e-308 / 2.22045e-16 static
Definition at line 577 of file LApack.hh.
tol3z
const APL_Float tol3z = sqrt(1.11022e-16) static
Definition at line 581 of file LApack.hh.