GNUAPL: src/LApack.cc File Reference
LApack.cc File Reference
#include <stdlib.h>
#include <iostream>
#include "Common.hh"
#include "ComplexCell.hh"
#include "FloatCell.hh"
#include "Output.hh"
#include "Value.hh"
#include "Workspace.hh"
#include "LApack.hh"
Functions
void divide_matrix (Value &Z, bool need_complex, ShapeItem rows, ShapeItem cols_A, const Cell *cA, ShapeItem cols_B, const Cell *cB)
a macro to enable debug printouts
Function Documentation
divide_matrix()
void divide_matrix (Value & Z, bool need_complex, ShapeItem rows, ShapeItem cols_A, const Cell * cA, ShapeItem cols_B, const Cell * cB)
a macro to enable debug printouts
Definition at line 39 of file LApack.cc.
References A, a, B, c, DOMAIN_ERROR, Workspace::get_CT(), Cell::get_imag_value(), Cell::get_real_value(), loop, Value::set_ravel_Complex(), Value::set_ravel_Float(), and WS_FULL.
Referenced by Bif_F12_DOMINO::eval_AB().