GNUAPL: src/libapl.cc File Reference
libapl.cc File Reference
#include <cstring>
#include <sstream>
#include <ostream>
#include <Command.hh>
#include <ComplexCell.hh>
#include <DiffOut.hh>
#include <Error.hh>
#include <FloatCell.hh>
#include <LineInput.hh>
#include <PointerCell.hh>
#include <Tokenizer.hh>
#include <UserPreferences.hh>
#include <Workspace.hh>
#include "libapl.h"
Macros
#define __LIBAPL__ 1
Functions
APL_value int_scalar (int64_t val, const char *loc)
A new integer scalar.
APL_value double_scalar (APL_Float val, const char *loc)
A new floating point scalar.
APL_value complex_scalar (APL_Float real, APL_Float imag, const char *loc)
A new complex scalar.
APL_value char_scalar (int uni, const char *loc)
A new character scalar.
APL_value apl_value (int rank, const int64_t *shape, const char *loc)
A new APL value with given rank and shape. All ravel elements are initialized to integer 0.
APL_value char_vector (const char *str, const char *loc)
A new character vector.
void release_value (const APL_value val, const char *loc)
int get_rank (const APL_value val)
return ⍴⍴val
int64_t get_axis (const APL_value val, unsigned int axis)
return (⍴val)[axis]
uint64_t get_element_count (const APL_value val)
return ×/⍴val
int get_type (const APL_value val, uint64_t idx)
return the type of (,val)[idx]
int is_string (const APL_value val)
return non-0 if val is a simple character vector.
int get_char (const APL_value val, uint64_t idx)
return the character val[idx] (after having checked is_char())
int64_t get_int (const APL_value val, uint64_t idx)
return the integer val[idx] (after having checked is_int())
APL_Float get_real (const APL_value val, uint64_t idx)
return the real part of val[idx] (after having checked is_numeric())
APL_Float get_imag (const APL_value val, uint64_t idx)
return the imag part of val[idx] (after having checked is_numeric())
APL_value get_value (const APL_value val, uint64_t idx)
return the (nested) value val[idx] (after having checked is_value()). The APL_value returned must be released with release_value() later on.
APL_value assign_var (const unsigned int *var_name_ucs, int rank, uint64_t *shape)
void set_char (int new_char, APL_value val, uint64_t idx)
val[idx]←unicode
void set_int (int64_t new_int, APL_value val, uint64_t idx)
val[idx]←new_int
void set_double (APL_Float new_double, APL_value val, uint64_t idx)
val[idx]←new_double
void set_complex (APL_Float new_real, APL_Float new_imag, APL_value val, uint64_t idx)
val[idx]←new_complex
void set_value (APL_value new_value, APL_value val, uint64_t idx)
LIBAPL_error apl_exec (const char *line)
LIBAPL_error apl_exec_ucs (const unsigned int *line_ucs)
const char * apl_command (const char *command)
const unsigned int * apl_command_ucs (const unsigned int *command)
int get_owner_count (APL_value val)
APL_function get_function_ucs (const unsigned int *name, APL_function *L, APL_function *R)
void print_ucs (FILE *out, const unsigned int *string_ucs)
APL_value get_var_value (const char *var_name, const char *loc)
int set_var_value (const char *var_name, const APL_value new_value, const char *loc)
void print_value (const APL_value value, FILE *file)
char * print_value_to_string (const APL_value value)
ostream & print_value (const APL_value value, ostream &out)
int UTF8_to_Unicode (const char *utf, int *length)
void Unicode_to_UTF8 (int uni, char *dest, int *length)
void init_1 (const char *argv0, bool log_startup)
initialize
void init_2 (bool log_startup)
initialize subsystems that depend on argv[]
void init_libapl (const char *progname, int log_startup)
int expand_LF_to_CRLF (int on)
void libapl_glfu (LineInputMode mode, const UCS_string &prompt, UCS_string &line, bool &eof, LineHistory &hist)
get_line_from_user_cb * install_get_line_from_user_cb (get_line_from_user_cb *new_callback)
APL_value eval__fun (APL_function fun)
APL_value eval__A_fun_B (APL_value vA, APL_function fun, APL_value vB)
APL_value eval__A_L_oper_B (APL_value vA, APL_function fL, APL_function fun, APL_value vB)
APL_value eval__A_fun_X_B (APL_value vA, APL_function fun, APL_value vX, APL_value vB)
APL_value eval__A_L_oper_R_B (APL_value vA, APL_function fL, APL_function fun, APL_function fR, APL_value vB)
APL_value eval__A_L_oper_X_B (APL_value vA, APL_function fL, APL_function fun, APL_value vX, APL_value vB)
APL_value eval__A_L_oper_R_X_B (APL_value vA, APL_function fL, APL_function fun, APL_function fR, APL_value vX, APL_value vB)
APL_value eval__fun_B (APL_function fun, APL_value vB)
APL_value eval__L_oper_B (APL_function L, APL_function oper, APL_value vB)
APL_value eval__fun_X_B (APL_function fun, APL_value vX, APL_value vB)
APL_value eval__L_oper_R_B (APL_function fL, APL_function fun, APL_function fR, APL_value vB)
APL_value eval__L_oper_X_B (APL_function fL, APL_function fun, APL_value vX, APL_value vB)
APL_value eval__L_oper_R_X_B (APL_function fL, APL_function fun, APL_function fR, APL_value vX, APL_value vB)
Variables
DiffOut DOUT_filebuf
DiffOut UERR_filebuf
ErrOut CERR_filebuf
a filebuf for CERR
get_line_from_user_cb * glfu = 0
Macro Definition Documentation
__LIBAPL__
#define __LIBAPL__ 1
Definition at line 25 of file libapl.cc.
Function Documentation
apl_command()
const char* apl_command (const char * command)
Definition at line 388 of file libapl.cc.
References Command::do_APL_command().
apl_command_ucs()
const unsigned int* apl_command_ucs (const unsigned int * command)
Definition at line 400 of file libapl.cc.
References UCS_string::append(), Command::do_APL_command(), loop, and UCS_string::size().
apl_exec()
LIBAPL_error apl_exec (const char * line)
Definition at line 358 of file libapl.cc.
References StateIndicator::get_error(), Command::process_line(), Workspace::SI_top(), and Workspace::SI_top_error().
apl_exec_ucs()
LIBAPL_error apl_exec_ucs (const unsigned int * line_ucs)
Definition at line 372 of file libapl.cc.
References UCS_string::append(), StateIndicator::get_error(), Command::process_line(), Workspace::SI_top(), and Workspace::SI_top_error().
apl_value()
APL_value apl_value (int rank, const int64_t * shape, const char * loc)
A new APL value with given rank and shape. All ravel elements are initialized to integer 0.
Definition at line 91 of file libapl.cc.
References Value_P_Base::get(), Value::increment_owner_count(), LOC, and loop.
assign_var()
APL_value assign_var (const unsigned int * var_name_ucs, int rank, uint64_t * shape)
Definition at line 220 of file libapl.cc.
References Shape::add_shape_item(), UCS_string::append(), Symbol::assign(), Symbol::can_be_assigned(), Value_P_Base::get(), Value::increment_owner_count(), Avec::is_first_symbol_char(), Avec::is_symbol_char(), LOC, Workspace::lookup_symbol(), loop, and symbol.
char_scalar()
APL_value char_scalar (int uni, const char * loc)
A new character scalar.
Definition at line 79 of file libapl.cc.
References Value_P_Base::get(), and Value::increment_owner_count().
char_vector()
APL_value char_vector (const char * str, const char * loc)
A new character vector.
Definition at line 105 of file libapl.cc.
References Value_P_Base::get(), and Value::increment_owner_count().
complex_scalar()
APL_value complex_scalar (APL_Float real, APL_Float imag, const char * loc)
A new complex scalar.
Definition at line 69 of file libapl.cc.
References Value_P_Base::get(), and Value::increment_owner_count().
double_scalar()
APL_value double_scalar (APL_Float val, const char * loc)
A new floating point scalar.
Definition at line 59 of file libapl.cc.
References Value_P_Base::get(), and Value::increment_owner_count().
eval__A_fun_B()
APL_value eval__A_fun_B (APL_value vA, APL_function fun, APL_value vB)
Definition at line 689 of file libapl.cc.
References A, B, Token::extract_and_keep(), Token::get_tag(), LOC, StateIndicator::run(), Workspace::SI_top(), and TOK_SI_PUSHED.
eval__A_fun_X_B()
APL_value eval__A_fun_X_B (APL_value vA, APL_function fun, APL_value vX, APL_value vB)
Definition at line 716 of file libapl.cc.
References A, B, Token::extract_and_keep(), Token::get_tag(), LOC, StateIndicator::run(), Workspace::SI_top(), and TOK_SI_PUSHED.
eval__A_L_oper_B()
APL_value eval__A_L_oper_B (APL_value vA, APL_function fL, APL_function fun, APL_value vB)
Definition at line 702 of file libapl.cc.
References A, B, Token::extract_and_keep(), Token::get_tag(), LOC, StateIndicator::run(), Workspace::SI_top(), and TOK_SI_PUSHED.
eval__A_L_oper_R_B()
APL_value eval__A_L_oper_R_B (APL_value vA, APL_function fL, APL_function fun, APL_function fR, APL_value vB)
Definition at line 730 of file libapl.cc.
References A, B, Token::extract_and_keep(), Token::get_tag(), LOC, StateIndicator::run(), Workspace::SI_top(), and TOK_SI_PUSHED.
eval__A_L_oper_R_X_B()
APL_value eval__A_L_oper_R_X_B (APL_value vA, APL_function fL, APL_function fun, APL_function fR, APL_value vX, APL_value vB)
Definition at line 762 of file libapl.cc.
References A, B, Token::extract_and_keep(), Token::get_tag(), LOC, StateIndicator::run(), Workspace::SI_top(), and TOK_SI_PUSHED.
eval__A_L_oper_X_B()
APL_value eval__A_L_oper_X_B (APL_value vA, APL_function fL, APL_function fun, APL_value vX, APL_value vB)
Definition at line 746 of file libapl.cc.
References A, B, Token::extract_and_keep(), Token::get_tag(), LOC, StateIndicator::run(), Workspace::SI_top(), and TOK_SI_PUSHED.
eval__fun()
APL_value eval__fun (APL_function fun)
Definition at line 678 of file libapl.cc.
References Token::extract_and_keep(), Token::get_tag(), LOC, StateIndicator::run(), Workspace::SI_top(), and TOK_SI_PUSHED.
eval__fun_B()
APL_value eval__fun_B (APL_function fun, APL_value vB)
Definition at line 779 of file libapl.cc.
References B, Token::extract_and_keep(), Token::get_tag(), LOC, StateIndicator::run(), Workspace::SI_top(), and TOK_SI_PUSHED.
eval__fun_X_B()
APL_value eval__fun_X_B (APL_function fun, APL_value vX, APL_value vB)
Definition at line 804 of file libapl.cc.
References B, Token::extract_and_keep(), Token::get_tag(), LOC, StateIndicator::run(), Workspace::SI_top(), and TOK_SI_PUSHED.
eval__L_oper_B()
APL_value eval__L_oper_B (APL_function L, APL_function oper, APL_value vB)
Definition at line 791 of file libapl.cc.
References B, Token::extract_and_keep(), Token::get_tag(), LOC, StateIndicator::run(), Workspace::SI_top(), TOK_FUN2, and TOK_SI_PUSHED.
eval__L_oper_R_B()
APL_value eval__L_oper_R_B (APL_function fL, APL_function fun, APL_function fR, APL_value vB)
Definition at line 817 of file libapl.cc.
References B, Token::extract_and_keep(), Token::get_tag(), LOC, StateIndicator::run(), Workspace::SI_top(), and TOK_SI_PUSHED.
eval__L_oper_R_X_B()
APL_value eval__L_oper_R_X_B (APL_function fL, APL_function fun, APL_function fR, APL_value vX, APL_value vB)
Definition at line 846 of file libapl.cc.
References B, Token::extract_and_keep(), Token::get_tag(), LOC, StateIndicator::run(), Workspace::SI_top(), and TOK_SI_PUSHED.
eval__L_oper_X_B()
APL_value eval__L_oper_X_B (APL_function fL, APL_function fun, APL_value vX, APL_value vB)
Definition at line 832 of file libapl.cc.
References B, Token::extract_and_keep(), Token::get_tag(), LOC, StateIndicator::run(), Workspace::SI_top(), and TOK_SI_PUSHED.
expand_LF_to_CRLF()
int expand_LF_to_CRLF (int on)
Definition at line 639 of file libapl.cc.
References DiffOut::LF_to_CRLF(), and ErrOut::LF_to_CRLF().
get_axis()
int64_t get_axis (const APL_value val, unsigned int axis)
return (⍴val)[axis]
Definition at line 143 of file libapl.cc.
get_char()
int get_char (const APL_value val, uint64_t idx)
return the character val[idx] (after having checked is_char())
Definition at line 174 of file libapl.cc.
Referenced by PrintBuffer::get_column_count().
get_element_count()
uint64_t get_element_count (const APL_value val)
return ×/⍴val
Definition at line 151 of file libapl.cc.
get_function_ucs()
APL_function get_function_ucs (const unsigned int * name, APL_function * L, APL_function * R)
Definition at line 428 of file libapl.cc.
References UCS_string::append(), E_NO_ERROR, LOC, PM_EXECUTE, Symbol::resolve(), UCS_string::size(), TC_FUN0, TC_FUN12, TC_FUN2, TC_OPER1, TC_OPER2, Tokenizer::tokenize(), and TV_SYM.
get_imag()
APL_Float get_imag (const APL_value val, uint64_t idx)
return the imag part of val[idx] (after having checked is_numeric())
Definition at line 198 of file libapl.cc.
get_int()
int64_t get_int (const APL_value val, uint64_t idx)
return the integer val[idx] (after having checked is_int())
Definition at line 182 of file libapl.cc.
get_owner_count()
int get_owner_count (APL_value val)
Definition at line 422 of file libapl.cc.
get_rank()
int get_rank (const APL_value val)
return ⍴⍴val
Definition at line 135 of file libapl.cc.
Referenced by CDR_string::check(), Bif_F12_COMMA::eval_AB(), Quad_CR::Picker::get(), Value::get_sole_integer(), Value::is_char_scalar(), Value::is_char_string(), Value::is_char_vector(), Value::is_int_scalar(), Value::is_int_vector(), Value::is_scalar_or_vector(), Value::is_vector(), CDR_string::ravel(), Value::same_rank(), and Value::same_shape().
get_real()
APL_Float get_real (const APL_value val, uint64_t idx)
return the real part of val[idx] (after having checked is_numeric())
Definition at line 190 of file libapl.cc.
get_type()
int get_type (const APL_value val, uint64_t idx)
return the type of (,val)[idx]
Definition at line 158 of file libapl.cc.
Referenced by CDR_string::check(), CDR_string::is_character(), and CDR_string::is_integer().
get_value()
APL_value get_value (const APL_value val, uint64_t idx)
return the (nested) value val[idx] (after having checked is_value()). The APL_value returned must be released with release_value() later on.
Definition at line 208 of file libapl.cc.
References Value_P_Base::get(), Value::increment_owner_count(), and LOC.
Referenced by Symbol::get_name_ptr().
get_var_value()
APL_value get_var_value (const char * var_name, const char * loc)
Definition at line 524 of file libapl.cc.
References Value_P_Base::get(), NamedObject::get_NC(), Symbol::get_value(), Value::increment_owner_count(), Workspace::lookup_existing_symbol(), NC_VARIABLE, and symbol.
init_1()
void init_1 (const char * argv0, bool log_startup)
initialize
Definition at line 83 of file Common.cc.
Referenced by init_libapl(), and Unicode_to_UTF8().
init_2()
void init_2 (bool log_startup)
initialize subsystems that depend on argv[]
Definition at line 147 of file Common.cc.
Referenced by init_libapl(), and Unicode_to_UTF8().
init_libapl()
void init_libapl (const char * progname, int log_startup)
Definition at line 619 of file libapl.cc.
References CERR_filebuf, DOUT_filebuf, init_1(), init_2(), UserPreferences::read_config_file(), UserPreferences::requested_id, UserPreferences::safe_mode, UserPreferences::system_do_svars, UERR_filebuf, uprefs, and UserPreferences::user_do_svars.
install_get_line_from_user_cb()
get_line_from_user_cb* install_get_line_from_user_cb (get_line_from_user_cb * new_callback)
Definition at line 668 of file libapl.cc.
References glfu, InputMux::install_get_line_callback(), and libapl_glfu().
int_scalar()
APL_value int_scalar (int64_t val, const char * loc)
A new integer scalar.
Definition at line 49 of file libapl.cc.
References Value_P_Base::get(), and Value::increment_owner_count().
is_string()
int is_string (const APL_value val)
return non-0 if val is a simple character vector.
Definition at line 166 of file libapl.cc.
libapl_glfu()
void libapl_glfu (LineInputMode mode, const UCS_string & prompt, UCS_string & line, bool & eof, LineHistory & hist)
Definition at line 651 of file libapl.cc.
References UTF8_string::c_str(), and glfu.
Referenced by install_get_line_from_user_cb().
print_ucs()
void print_ucs (FILE * out, const unsigned int * string_ucs)
Definition at line 513 of file libapl.cc.
References UCS_string::append(), and UTF8_string::c_str().
print_value() [1/2]
void print_value (const APL_value value, FILE * file)
Definition at line 570 of file libapl.cc.
References st.
Referenced by StateIndicator::statement_result().
print_value() [2/2]
ostream& print_value (const APL_value value, ostream & out)
Definition at line 590 of file libapl.cc.
print_value_to_string()
char* print_value_to_string (const APL_value value)
Definition at line 580 of file libapl.cc.
References st.
release_value()
void release_value (const APL_value val, const char * loc)
Definition at line 121 of file libapl.cc.
References Value::decrement_owner_count().
set_char()
void set_char (int new_char, APL_value val, uint64_t idx)
val[idx]←unicode
Definition at line 267 of file libapl.cc.
References Value::decrement_owner_count(), Value_P_Base::get(), Cell::get_pointer_value(), Cell::is_pointer_cell(), LOC, and CharCell::zU().
Referenced by PrintBuffer::get_column_count().
set_complex()
void set_complex (APL_Float new_real, APL_Float new_imag, APL_value val, uint64_t idx)
val[idx]←new_complex
Definition at line 312 of file libapl.cc.
References Value::decrement_owner_count(), Value_P_Base::get(), Cell::get_pointer_value(), Cell::is_pointer_cell(), LOC, and ComplexCell::zC().
set_double()
void set_double (APL_Float new_double, APL_value val, uint64_t idx)
val[idx]←new_double
Definition at line 297 of file libapl.cc.
References Value::decrement_owner_count(), Value_P_Base::get(), Cell::get_pointer_value(), Cell::is_pointer_cell(), LOC, and FloatCell::zF().
set_int()
void set_int (int64_t new_int, APL_value val, uint64_t idx)
val[idx]←new_int
Definition at line 282 of file libapl.cc.
References Value::decrement_owner_count(), Value_P_Base::get(), Cell::get_pointer_value(), Cell::is_pointer_cell(), LOC, and IntCell::zI().
set_value()
void set_value (APL_value new_value, APL_value val, uint64_t idx)
Definition at line 326 of file libapl.cc.
References CLONE, Value::decrement_owner_count(), DOMAIN_ERROR, Value_P_Base::get(), Cell::get_pointer_value(), Cell::init(), Cell::is_pointer_cell(), and LOC.
set_var_value()
int set_var_value (const char * var_name, const APL_value new_value, const char * loc)
Definition at line 540 of file libapl.cc.
References Symbol::assign(), B, NamedObject::get_NC(), Avec::is_first_symbol_char(), Avec::is_quad(), Avec::is_symbol_char(), Workspace::lookup_symbol(), loop, NC_UNUSED_USER_NAME, NC_VARIABLE, s, UCS_string::size(), and symbol.
Unicode_to_UTF8()
void Unicode_to_UTF8 (int uni, char * dest, int * length)
Definition at line 606 of file libapl.cc.
References init_1(), and init_2().
UTF8_to_Unicode()
int UTF8_to_Unicode (const char * utf, int * length)
Definition at line 597 of file libapl.cc.
References UTF8_string::toUni(), and utf8P().
Variable Documentation
CERR_filebuf
ErrOut CERR_filebuf
a filebuf for CERR
Definition at line 45 of file Output.cc.
Referenced by init_libapl().
DOUT_filebuf
ostream COUT & DOUT_filebuf
Definition at line 56 of file Output.cc.
Referenced by init_libapl(), and Output::reset_dout().
glfu
get_line_from_user_cb* glfu = 0
Definition at line 648 of file libapl.cc.
Referenced by install_get_line_from_user_cb(), and libapl_glfu().
UERR_filebuf
ostream UERR & UERR_filebuf
Definition at line 58 of file Output.cc.
Referenced by init_libapl().