GNUAPL: src/Logging.def File Reference
Logging.def File Reference
Functions
log_def (0, SHOW_AV, "AV details ") log_def(0
new and delete calls log_def (0, get_line, "input from user or testcase file ") log_def(0
new and delete calls function find_closing () ") log_def(0
new and delete calls function tokenization log_def (0, collect_constants, " ... function collect_constants()") log_def(0
new and delete calls function tokenization create value () ") log_def(0
new and delete calls function tokenization create defined set_line () ") log_def(0
new and delete calls function tokenization create defined load () ") log_def(0
new and delete calls function tokenization create defined execute () ") log_def(0
new and delete calls function tokenization create defined enter leave log_def (0, StateIndicator__enter_leave, "State indicator: enter/leave ") log_def(0
new and delete calls function tokenization create defined enter leave push pop log_def (0, SYMBOL_lookup_symbol, "Symbol: lookup ") log_def(0
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE log_def (0, SYMBOL_resolve, " ... resolve ") log_def(0
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE erase_stale () ") log_def(0
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format log_def (0, char_conversion, "character conversions ") log_def(0
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX log_def (0, command_IN, "commands)LOAD,)SAVE,)IN, and)OUT") log_def(0
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors log_def (0, error_throw, "details of error throwing ") log_def(0
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor log_def (0, execute_goto, "execute(): state changes ") log_def(0
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution log_def (0, prefix_parser, "Prefix parser ") log_def(0
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information log_def (0, FunOperX, "FunOper1 and FunOper2 functions ") log_def(0
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations log_def (0, argc_argv, "command line arguments (argc/argv) ") log_def(0
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages log_def (0, optimization, "optimization messages ") log_def(0
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details log_def (0, Svar_DB_signals, "Svar_DB signals ") log_def(0
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details Parallel (multi-core) execution ") log_def(0
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details EOC handler functionality log_def (0, Quad_DLX, "⎕DLX details ") log_def(0
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details EOC handler functionality command DOXY log_def (0, Value_alloc, "details of Value allocation ") log_def(0
Variables
delete
new and delete calls parse
new and delete calls parser
new and delete calls find_closing
new and delete calls function tokenize
new and delete calls function tokenization create_value
new and delete calls function tokenization create UserFunction__fix
new and delete calls function tokenization create defined function
new and delete calls function tokenization create defined UserFunction__set_line
new and delete calls function tokenization create defined UserFunction__load
new and delete calls function tokenization create defined UserFunction__execute
new and delete calls function tokenization create defined UserFunction__enter_leave
new and delete calls function tokenization create defined enter leave StateIndicator__push_pop
new and delete calls function tokenization create defined enter leave push pop SYMBOL_push_pop
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE glue
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE Value
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE Value__erase_stale
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE Bif_F12_FORMAT
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format quad_FX
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX verbose_error
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor printbuf_align
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor PrintBuffer
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor cork
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Output
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor test_execution
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution prefix__location_info
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information shared_variables
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations startup
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages archive
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details Parallel
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details EOC_handlers
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details EOC handler functionality command_DOXY
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details EOC handler functionality command DOXY Quad_TF
Function Documentation
erase_stale()
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE erase_stale ()
Referenced by Value::total_CDR_size_brutto().
execute()
new and delete calls function tokenization create defined execute ()
find_closing()
new and delete calls function find_closing ()
load()
new and delete calls function tokenization create defined load ()
log_def() [1/17]
log_def (0 , SHOW_AV , "AV details ")
log_def() [2/17]
new and delete calls log_def (0 , get_line , "input from user or testcase file ")
log_def() [3/17]
new and delete calls function tokenization log_def (0 , collect_constants , " ... function collect_constants()")
log_def() [4/17]
new and delete calls function tokenization create defined enter leave log_def (0 , StateIndicator__enter_leave , "State indicator: enter/leave ")
log_def() [5/17]
new and delete calls function tokenization create defined enter leave push pop log_def (0 , SYMBOL_lookup_symbol , "Symbol: lookup ")
log_def() [6/17]
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE log_def (0 , SYMBOL_resolve , " ... resolve ")
log_def() [7/17]
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format log_def (0 , char_conversion , "character conversions ")
log_def() [8/17]
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX log_def (0 , command_IN , " commands)
log_def() [9/17]
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors log_def (0 , error_throw , "details of error throwing ")
log_def() [10/17]
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor log_def (0 , execute_goto , "execute(): state changes ")
log_def() [11/17]
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution log_def (0 , prefix_parser , "Prefix parser ")
log_def() [12/17]
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information log_def (0 , FunOperX , "FunOper1 and FunOper2 functions ")
log_def() [13/17]
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations log_def (0 , argc_argv , "command line arguments (argc/argv) ")
log_def() [14/17]
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages log_def (0 , optimization , "optimization messages ")
log_def() [15/17]
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details log_def (0 , Svar_DB_signals , "Svar_DB signals ")
log_def() [16/17]
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details EOC handler functionality log_def (0 , Quad_DLX , "⎕DLX details ")
log_def() [17/17]
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details EOC handler functionality command DOXY log_def (0 , Value_alloc , "details of Value allocation ")
Parallel()
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details Parallel (multi- core)
set_line()
new and delete calls function tokenization create defined set_line ()
value()
new and delete calls function tokenization create value ()
Referenced by Executable::adjust_line_starts(), apl_get_ravel(), apl_get_shape(), apl_get_value(), apl_set_value(), XML_node::append(), Value::check_all_Cells(), Value::current_ravel(), Bif_F12_DECODE::decode_int(), Quad_CR::do_CR10(), Quad_CR::do_CR10_value(), Symbol::dump(), Value::erase_all(), XML_Loading_Archive::find_float_attr(), XML_Loading_Archive::find_int_attr(), Workspace::find_lambda_name(), Bif_F12_FORMAT::format_by_example(), Bif_F12_FORMAT::Format_LIFER::format_example(), Bif_F12_FORMAT::format_one_col_by_spec(), UCS_string::from_big(), StateIndicator::get_level(), Sig_item_int< int32_t, 4 >::get_svalue(), Sig_item_string::get_svalue(), Quad_CR::has_subfuns(), UCS_string_vector::insert(), Symbol::is_readonly(), Bif_F12_FORMAT::Format_LIFER::out_size(), Sig_item_int< int32_t, 4 >::print(), Sig_item_string::print(), Value::print_incomplete(), Value::print_stale(), XML_Loading_Archive::read_Label(), Quad_WA::read_meminfo(), UserPreferences::read_threshold_file(), Quad_RL::reset_seed(), Symbol::resolve(), Symbol::resolve_shared_variable(), run_generic_one_query(), Plot_window_properties::set_attribute(), Prefix::show_owners(), Executable::show_owners(), Symbol::show_owners(), show_tables(), Sig_item_int< int32_t, 4 >::Sig_item_int(), Sig_item_string::Sig_item_string(), Sig_item_int< int32_t, 4 >::store(), Sig_item_string::store(), Quad_TF::tf1(), Quad_TF::tf2(), Quad_TF::tf3(), UCS_string::UCS_string(), UCS_string::un_escape(), Prefix::unmark_all_values(), Executable::unmark_all_values(), UTF8_string::UTF8_string(), Doxy::variables_table(), and VH_entry::VH_entry().
Variable Documentation
archive
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages archive
Definition at line 59 of file Logging.def.
Bif_F12_FORMAT
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE Bif_F12_FORMAT
Definition at line 41 of file Logging.def.
command_DOXY
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details EOC handler functionality command_DOXY
Definition at line 64 of file Logging.def.
cork
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor cork
Definition at line 49 of file Logging.def.
create_value
new and delete calls function tokenization create_value
Definition at line 28 of file Logging.def.
delete
delete
Definition at line 22 of file Logging.def.
EOC_handlers
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details EOC_handlers
Definition at line 62 of file Logging.def.
find_closing
new and delete calls find_closing
Definition at line 24 of file Logging.def.
function
new and delete calls function tokenization create defined function
Definition at line 29 of file Logging.def.
Referenced by Quad_CR::do_eval_B(), and Nabla::open_existing_function().
glue
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE glue
Definition at line 39 of file Logging.def.
Referenced by Value::packed_fetcher().
nabla
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla
Definition at line 47 of file Logging.def.
Referenced by Nabla::edit_function().
Output
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Output
Definition at line 49 of file Logging.def.
Parallel
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details Parallel
Definition at line 61 of file Logging.def.
parse
new and delete calls parse
Definition at line 24 of file Logging.def.
parser
new and delete calls parser
Definition at line 24 of file Logging.def.
Referenced by Nabla::edit_body_line(), Quad_INP::eval_XB(), UserFunction::fix_lambda(), Executable::parse_body_line(), XML_Loading_Archive::read_Parser(), and Quad_TF::tf2_inverse().
prefix__location_info
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution prefix__location_info
Definition at line 53 of file Logging.def.
printbuf_align
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor printbuf_align
Definition at line 49 of file Logging.def.
PrintBuffer
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor PrintBuffer
Definition at line 49 of file Logging.def.
Referenced by CharCell::character_representation(), PointerCell::character_representation(), IntCell::character_representation(), ComplexCell::character_representation(), and FloatCell::character_representation().
quad_FX
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format quad_FX
Definition at line 43 of file Logging.def.
Quad_TF
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations interpreter start up messages LOAD and SAVE details EOC handler functionality command DOXY Quad_TF
Definition at line 66 of file Logging.def.
shared_variables
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information shared_variables
Definition at line 55 of file Logging.def.
startup
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor Details of test execution location information Shared Variable operations startup
Definition at line 57 of file Logging.def.
StateIndicator__push_pop
new and delete calls function tokenization create defined enter leave StateIndicator__push_pop
Definition at line 35 of file Logging.def.
SYMBOL_push_pop
new and delete calls function tokenization create defined enter leave push pop SYMBOL_push_pop
Definition at line 37 of file Logging.def.
test_execution
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX more verbose errors nabla editor test_execution
Definition at line 49 of file Logging.def.
tokenize
new and delete calls function tokenize
Definition at line 26 of file Logging.def.
Referenced by Tokenizer::Tokenizer().
UserFunction__enter_leave
new and delete calls function tokenization create defined UserFunction__enter_leave
Definition at line 33 of file Logging.def.
UserFunction__execute
new and delete calls function tokenization create defined UserFunction__execute
Definition at line 32 of file Logging.def.
UserFunction__fix
new and delete calls function tokenization create UserFunction__fix
Definition at line 29 of file Logging.def.
UserFunction__load
new and delete calls function tokenization create defined UserFunction__load
Definition at line 31 of file Logging.def.
UserFunction__set_line
new and delete calls function tokenization create defined UserFunction__set_line
Definition at line 29 of file Logging.def.
Value
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE Value
Definition at line 39 of file Logging.def.
Referenced by init_1(), and UserPreferences::show_configure_options().
Value__erase_stale
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE Value__erase_stale
Definition at line 39 of file Logging.def.
verbose_error
new and delete calls function tokenization create defined enter leave push pop push pop and ERASE APL primitive function format APL system function Quad FX verbose_error
Definition at line 45 of file Logging.def.