GNU APL: src/main.cc File Reference
main.cc File Reference
#include <pthread.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <signal.h>
#include <string.h>
#include <termios.h>
#include <netinet/in.h>
#include <sys/ioctl.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/types.h>
#include "buildtag.hh"
#include "Command.hh"
#include "Common.hh"
#include "IO_Files.hh"
#include "LibPaths.hh"
#include "Macro.hh"
#include "Output.hh"
#include "NativeFunction.hh"
#include "Workspace.hh"
#include "UserPreferences.hh"
Functions
static void signal_SEGV_handler (int)
signal handler for segfaults
static void signal_WINCH_handler (int)
signal handler for SIGWINCH
static void signal_USR1_handler (int)
signal handler for SIGUSR1
static void signal_TERM_handler (int)
signal handler for SIGTERM
static void signal_HUP_handler (int)
new signal handler for SIGHUP
static void show_argv (int argc, const char **argv)
print argc and argv[]
static void show_welcome (ostream &out, const char *argv0)
print a welcome message (copyright notice)
void remap_stdio ()
maybe remap stdin, stdout, and stderr to an incoming TCP connection to port uprefs.tcp_port on localhost
int init_apl (int argc, const char *argv[])
initialize the interpreter
int main (int argc, const char *argv[])
dito.
Variables
static const char * build_tag [] = { BUILDTAG, 0 }
when this file was built
static struct sigaction old_control_C_action
old sigaction argument for ^C
static struct sigaction new_control_C_action
new sigaction argument for ^C
static struct sigaction old_SEGV_action
old sigaction argument for segfaults
static struct sigaction new_SEGV_action
new sigaction argument for segfaults
static struct sigaction old_WINCH_action
old sigaction argument for SIGWINCH
static struct sigaction new_WINCH_action
new sigaction argument for SIGWINCH
static struct sigaction old_USR1_action
old sigaction argument for SIGUSR1
static struct sigaction new_USR1_action
new sigaction argument for SIGUSR1
static struct sigaction old_TERM_action
old sigaction argument for SIGTERM
static struct sigaction new_TERM_action
new sigaction argument for SIGTERM
static struct sigaction old_HUP_action
old sigaction argument for SIGHUP
static struct sigaction new_HUP_action
new sigaction argument for SIGHUP
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 22 of file main.cc.
Function Documentation
init_apl()
int init_apl (int argc, const char * argv[])
initialize the interpreter
Definition at line 369 of file main.cc.
References UCS_string::append(), UTF8_string::c_str(), Output::clear_EOL, Output::color_CERR, Output::color_CIN, Output::color_COUT, Output::color_UERR, Quad_TZ::compute_offset(), UserPreferences::CPU_limit_secs, UserPreferences::daemon, UserPreferences::do_Color, UserPreferences::do_CONT, UserPreferences::emacs_arg, UserPreferences::emacs_mode, UserPreferences::expand_argv(), UserPreferences::expanded_argv, LibPaths::get_lib_filename(), Avec::init(), UserPreferences::initial_pw, UserPreferences::initial_workspace, UserPreferences::latent_expression, NativeFunction::load_emacs_library(), new_control_C_action, new_HUP_action, new_SEGV_action, new_TERM_action, new_USR1_action, new_WINCH_action, old_control_C_action, old_HUP_action, old_SEGV_action, old_TERM_action, old_USR1_action, old_WINCH_action, UserPreferences::parse_argv_0(), UserPreferences::parse_argv_1(), UserPreferences::parse_argv_2(), Command::process_line(), UserPreferences::read_config_file(), UserPreferences::read_threshold_file(), remap_stdio(), Workspace::set_PW(), show_argv(), show_welcome(), signal_HUP_handler(), signal_SEGV_handler(), signal_TERM_handler(), signal_USR1_handler(), signal_WINCH_handler(), UserPreferences::silent, UCS_string::size(), Output::toggle_color(), UserPreferences::wait_ms, and UserPreferences::WINCH_sets_pw.
main()
int main (int argc, const char * argv[])
dito.
Definition at line 611 of file main.cc.
Referenced by Backtrace::open_lines_file().
remap_stdio()
void remap_stdio ()
maybe remap stdin, stdout, and stderr to an incoming TCP connection to port uprefs.tcp_port on localhost
Definition at line 274 of file main.cc.
References UserPreferences::tcp_port.
Referenced by init_apl().
show_argv()
static void show_argv (int argc, const char ** argv) static
print argc and argv[]
Definition at line 194 of file main.cc.
Referenced by init_apl().
show_welcome()
static void show_welcome (ostream & out, const char * argv0) static
print a welcome message (copyright notice)
Definition at line 216 of file main.cc.
References build_tag.
Referenced by init_apl().
signal_HUP_handler()
static void signal_HUP_handler (int) static
new signal handler for SIGHUP
Definition at line 185 of file main.cc.
References old_HUP_action.
Referenced by init_apl().
signal_SEGV_handler()
static void signal_SEGV_handler (int) static
signal handler for segfaults
Definition at line 86 of file main.cc.
References IO_Files::assert_error(), Command::cmd_OFF(), and Thread_context::print_all().
Referenced by init_apl().
signal_TERM_handler()
static void signal_TERM_handler (int) static
signal handler for SIGTERM
Definition at line 154 of file main.cc.
References old_TERM_action.
Referenced by init_apl().
signal_USR1_handler()
static void signal_USR1_handler (int) static
signal handler for SIGUSR1
Definition at line 141 of file main.cc.
Referenced by init_apl().
signal_WINCH_handler()
static void signal_WINCH_handler (int) static
signal handler for SIGWINCH
Definition at line 114 of file main.cc.
References Workspace::set_PW().
Referenced by init_apl().
Variable Documentation
build_tag
const char* build_tag[] = { BUILDTAG, 0 } static
when this file was built
Definition at line 67 of file main.cc.
Referenced by UserPreferences::show_version(), and show_welcome().
new_control_C_action
struct sigaction new_control_C_action static
new sigaction argument for ^C
Definition at line 75 of file main.cc.
Referenced by init_apl().
new_HUP_action
struct sigaction new_HUP_action static
new sigaction argument for SIGHUP
Definition at line 181 of file main.cc.
Referenced by init_apl().
new_SEGV_action
struct sigaction new_SEGV_action static
new sigaction argument for segfaults
Definition at line 82 of file main.cc.
Referenced by init_apl().
new_TERM_action
struct sigaction new_TERM_action static
new sigaction argument for SIGTERM
Definition at line 150 of file main.cc.
Referenced by init_apl().
new_USR1_action
struct sigaction new_USR1_action static
new sigaction argument for SIGUSR1
Definition at line 137 of file main.cc.
Referenced by init_apl().
new_WINCH_action
struct sigaction new_WINCH_action static
new sigaction argument for SIGWINCH
Definition at line 110 of file main.cc.
Referenced by init_apl().
old_control_C_action
struct sigaction old_control_C_action static
old sigaction argument for ^C
Definition at line 72 of file main.cc.
Referenced by init_apl().
old_HUP_action
struct sigaction old_HUP_action static
old sigaction argument for SIGHUP
Definition at line 178 of file main.cc.
Referenced by init_apl(), and signal_HUP_handler().
old_SEGV_action
struct sigaction old_SEGV_action static
old sigaction argument for segfaults
Definition at line 79 of file main.cc.
Referenced by init_apl().
old_TERM_action
struct sigaction old_TERM_action static
old sigaction argument for SIGTERM
Definition at line 147 of file main.cc.
Referenced by init_apl(), and signal_TERM_handler().
old_USR1_action
struct sigaction old_USR1_action static
old sigaction argument for SIGUSR1
Definition at line 134 of file main.cc.
Referenced by init_apl().
old_WINCH_action
struct sigaction old_WINCH_action static
old sigaction argument for SIGWINCH
Definition at line 107 of file main.cc.
Referenced by init_apl().