GNUAPL: src/main.hh File Reference
main.hh File Reference
Functions
void cleanup (bool soft)
clean up
void control_C (int)
signal handler for ^C
const char * prog_name ()
Variables
bool attention_raised
true if Control-C was hit
uint64_t attention_count
bool interrupt_raised
true if Control-C was hit twice within 500 ms
uint64_t interrupt_count
the number of Control-C signals received
APL_time_us interrupt_when
time when ^C was hit last
Function Documentation
cleanup()
void cleanup (bool soft)
clean up
clean up
Definition at line 162 of file Common.cc.
References NativeFunction::cleanup(), ID::cleanup(), Thread_context::cleanup(), LineInput::close(), ProcessorID::disconnect(), and Output::reset_colors().
Referenced by Command::cmd_OFF(), Quad_EX::expunge(), IO_Files::get_file_line(), signal_HUP_handler(), signal_TERM_handler(), and Quad_XML::XML_to_APL().
control_C()
void control_C (int)
signal handler for ^C
Definition at line 188 of file Common.cc.
References attention_count, attention_raised, CIN, Probe::dummy, interrupt_count, interrupt_raised, interrupt_when, now(), Probe::P0, Probe::P_1, Probe::P_2, Probe::P_3, Probe::P_4, Probe::P_5, Probe::PROBE_COUNT, and Probe::probes.
Referenced by LineInput::edit_line(), and init_apl().
prog_name()
const char* prog_name ()
Definition at line 62 of file Quad_SVx.cc.
Variable Documentation
attention_count
uint64_t attention_count
attention_raised
bool attention_raised
true if Control-C was hit
interrupt_count
uint64_t interrupt_count
the number of Control-C signals received
Definition at line 67 of file Common.cc.
Referenced by control_C(), and PrintBuffer::do_PrintBuffer().
interrupt_raised
bool interrupt_raised
true if Control-C was hit twice within 500 ms
interrupt_when
APL_time_us interrupt_when
time when ^C was hit last
Definition at line 66 of file Common.cc.
Referenced by control_C().