GNUAPL: src/Missing_Libraries.cc File Reference
Missing_Libraries.cc File Reference
#include "Common.hh"
#include "Error_macros.hh"
#include "Quad_FFT.hh"
#include "Quad_GTK.hh"
#include "Quad_RE.hh"
#include "Token.hh"
Functions
Token missing_files (const char *qfun, const char **libs, const char **hdrs, const char **pkgs)
a generic function for all ⎕XXX errors. Declared extern (rather than static) to avoid -Wunused-function warnings.
Function Documentation
missing_files()
Token missing_files (const char * qfun, const char ** libs, const char ** hdrs, const char ** pkgs)
a generic function for all ⎕XXX errors. Declared extern (rather than static) to avoid -Wunused-function warnings.
Definition at line 46 of file Missing_Libraries.cc.
References MORE_ERROR(), and SYNTAX_ERROR.
Referenced by Quad_FFT::eval_AB(), Quad_GTK::eval_AB(), Quad_RE::eval_AXB(), Quad_GTK::eval_AXB(), Quad_FFT::eval_B(), Quad_GTK::eval_B(), and Quad_GTK::eval_XB().