GNUAPL: src/Output.cc File Reference
Output.cc File Reference
#include "Common.hh"
#include "Command.hh"
#include "DiffOut.hh"
#include "InputFile.hh"
#include "LineInput.hh"
#include "Output.hh"
#include "Performance.hh"
#include "PrintOperator.hh"
#include "Svar_DB.hh"
#include "UserPreferences.hh"
Macros
#define CSI "\x1B["
CSI sequence for ANSI/VT100 escape sequences (ESC [)
Functions
ostream CERR (CERR_filebuf.use())
ostream & get_CERR ()
Variables
ErrOut CERR_filebuf
a filebuf for CERR
DiffOut DOUT_filebuf (false)
DiffOut UERR_filebuf (true)
CinOut CIN_filebuf
CIN_ostream CIN
Macro Definition Documentation
CSI
#define CSI "\x1B["
CSI sequence for ANSI/VT100 escape sequences (ESC [)
Definition at line 72 of file Output.cc.
Referenced by CIN_ostream::set_cursor().
Function Documentation
CERR()
ostream CERR (CERR_filebuf. use())
Referenced by get_CERR(), and Output::init().
get_CERR()
ostream& get_CERR ()
Definition at line 63 of file Output.cc.
References CERR(), Output::color_mode, UserPreferences::output_to_cout, uprefs, and ErrOut::used.
Referenced by Svar_record::bad_proc(), CPU_pool::change_core_count(), Svar_DB::connect_to_APserver(), Svar_DB::DB_tcp_error(), do_Assert(), Svar_DB::get_Svar_DB_tcp(), Svar_DB::init(), Backtrace::open_lines_file(), Thread_context::set_active_core_count(), Svar_record::set_control(), Svar_record::set_state(), Svar_DB::start_APserver(), Svar_record_P::Svar_record_P(), and NativeFunction::~NativeFunction().
Variable Documentation
CERR_filebuf
ErrOut CERR_filebuf
a filebuf for CERR
Definition at line 45 of file Output.cc.
Referenced by init_libapl().
CIN
CIN_ostream CIN
Definition at line 54 of file Output.cc.
Referenced by LineEditContext::adjust_allocated_height(), CIN_ostream::clear_EOS(), control_C(), LineEditContext::delete_char(), LineInput::edit_line(), TabExpansion::expand_command_arg(), TabExpansion::expand_distinguished_name(), TabExpansion::expand_filename(), TabExpansion::expand_help_topics(), TabExpansion::expand_wsname(), InputMux::get_line(), LineEditContext::insert_char(), LineEditContext::refresh_all(), LineEditContext::refresh_from_cursor(), LineEditContext::set_cursor(), TabExpansion::show_alternatives(), LineEditContext::toggle_ins_mode(), and LineEditContext::~LineEditContext().
CIN_filebuf
CinOut CIN_filebuf
Definition at line 53 of file Output.cc.
DOUT_filebuf
ostream COUT& DOUT_filebuf
Definition at line 56 of file Output.cc.
Referenced by init_libapl(), and Output::reset_dout().
UERR_filebuf
ostream UERR& UERR_filebuf
Definition at line 58 of file Output.cc.
Referenced by init_libapl().