GNUAPL: src/Parallel.hh File Reference
Parallel.hh File Reference
#include <pthread.h>
#include "Common.hh"
#include <ostream>
#include <semaphore.h>
#include "Cell.hh"
Classes
class CPU_pool
class Parallel
Parallel APL execution.
Macros
#define PRINT_LOCKED(x) x;
#define LOCK_INITIALIZER 0
Typedefs
typedef int _Atomic_word
Functions
int atomic_fetch_add (volatile _Atomic_word &counter, int increment)
int atomic_read (volatile _Atomic_word &counter)
read counter
void atomic_add (volatile _Atomic_word &counter, int increment)
add to counter
Macro Definition Documentation
LOCK_INITIALIZER
#define LOCK_INITIALIZER 0
Definition at line 265 of file Parallel.hh.
PRINT_LOCKED
#define PRINT_LOCKED (x) x;
Definition at line 57 of file Parallel.hh.
Referenced by CPU_pool::lock_pool(), Thread_context::M_lock_pool(), Thread_context::print(), Thread_context::print_all(), Thread_context::set_active_core_count(), Parallel_job_list< PJob_scalar_B, false >::start(), CPU_pool::unlock_pool(), and Parallel::worker_main().
Typedef Documentation
_Atomic_word
typedef int _Atomic_word
Definition at line 67 of file Parallel.hh.
Function Documentation
atomic_add()
void atomic_add (volatile _Atomic_word & counter, int increment) inline
add to counter
Definition at line 77 of file Parallel.hh.
References atomic_fetch_add(), atomic_read(), and CERR.
Referenced by Parallel::acquire_lock(), Thread_context::M_fork(), Thread_context::PF_join(), and Parallel::release_lock().
atomic_fetch_add()
int atomic_fetch_add (volatile _Atomic_word & counter, int increment) inline
Definition at line 69 of file Parallel.hh.
Referenced by Parallel::acquire_lock(), and atomic_add().
atomic_read()
int atomic_read (volatile _Atomic_word & counter) inline
read counter
Definition at line 73 of file Parallel.hh.
Referenced by atomic_add(), Thread_context::M_join(), and Thread_context::PF_join().