GNU APL: src/Plot_xcb.cc File Reference
Plot_xcb.cc File Reference
#include <errno.h>
#include "Common.hh"
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <xcb/xcb.h>
#include <xcb/xproto.h>
#include "ComplexCell.hh"
#include "FloatCell.hh"
#include "Quad_PLOT.hh"
#include "Workspace.hh"
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <iostream>
#include <iomanip>
#include "Plot_data.hh"
#include "Plot_line_properties.hh"
#include "Plot_window_properties.hh"
Classes
struct Plot_context
Some xcb IDs (returned from the X server)
struct string_width_height
the supposed width and the height of a string (in pixels)
Macros
#define XCB_WINDOWS_WITH_UTF8_CAPTIONS 0
undefined → 0
#define I1616(x, y) int16_t(x), int16_t(y)
two int16_t
#define ITEMS(x) sizeof(x)/sizeof(*x), x
the number of items in x
#define LE2(x) uint8_t((x)), uint8_t((x) >> 8)
2 byte little endian
#define LE4(x) LE2((x)), LE2((x >> 16))
4 byte little endian
#define XFT 0
#define PANGO 0
Functions
void * plot_main (void *vp_props)
the pthread that handles one plot window.
void testCookie (xcb_void_cookie_t cookie, xcb_connection_t *conn, const char *errMessage)
test obtaining of a cookie
xcb_gcontext_t setup_font_gc (Plot_context &pctx, const char *font_name, Color canvas_color)
return a xcb_gcontext_t for font font_name
void draw_text (const Plot_context &pctx, const char *label, const Pixel_XY &xy)
draw text label at position xy
char * format_tick (double val)
return the text of a grid tick with value val
void draw_line (const Plot_context &pctx, xcb_gcontext_t gc, const Pixel_XY &P0, const Pixel_XY &P1)
draw a line from P0 to P1
void pv_swap (Pixel_XY &P0, double &Y0, Pixel_XY &P1, double &Y1)
swap pixels at P0 (with value Y0) and P1 (with value Y1) and
double intersection (double Ax, double Ay, double Bx, double By, double Cx, double Cy, double Dx, double Dy)
void set_GC_attr (const Plot_context &pctx, xcb_gcontext_t gc, xcb_gc_t mask, uint32_t value)
set the an attribute of a xcb_gcontext_t
void set_GC_foreground (const Plot_context &pctx, xcb_gcontext_t gc, Color color)
set the foreground color of a xcb_gcontext_t
void set_GC_line_width (const Plot_context &pctx, xcb_gcontext_t gc, int width)
set the line width of a xcb_gcontext_t
void draw_triangle (const Plot_context &pctx, int verbosity, Pixel_XY P0, double H0, Pixel_XY P1, Pixel_XY P2, double H12)
draw a triangular area of a 3D plot
void draw_triangle (const Plot_context &pctx, int verbosity, Pixel_XY P0, double H0, Pixel_XY P1, double H1, Pixel_XY P2, double H2)
draw a triangular plot point (∆ or ∇)
void draw_point (const Plot_context &pctx, const Pixel_XY &xy, Color canvas_color, const Plot_line_properties &l_props)
draw a plot point (representing one data value) at position xy
void draw_legend (const Plot_context &pctx, const Plot_window_properties &w_props)
draw the legend
void draw_X_grid (const Plot_context &pctx, const Plot_window_properties &w_props, bool surface)
draw the (vertical) grid lines that start at the X axis
void draw_Y_grid (const Plot_context &pctx, const Plot_window_properties &w_props, bool surface)
draw the (horizontal) grid lines that start at the Y axis
void draw_Z_grid (const Plot_context &pctx, const Plot_window_properties &w_props)
draw the grid lines that start at the Z axis
void draw_plot_lines (const Plot_context &pctx, const Plot_window_properties &w_props, const Plot_data &data)
draw the plot lines
void draw_surface_lines (const Plot_context &pctx, const Plot_window_properties &w_props, const Plot_data &data)
draw the surface plot lines
void do_plot (const Plot_context &pctx, const Plot_window_properties &w_props, const Plot_data &data)
draw the content of a plot window
xcb_atom_t get_atom_ID (xcb_connection_t *conn, int only_existing, const char *name)
obtain an ID for name
void save_file (const char *outfile, Display *dpy, int window, const Plot_context &pctx)
save plot window to file named outfile
Macro Definition Documentation
I1616
#define I1616 (x, y) int16_t(x), int16_t(y)
two int16_t
Definition at line 73 of file Plot_xcb.cc.
ITEMS
#define ITEMS (x) sizeof(x)/sizeof(*x), x
the number of items in x
Definition at line 75 of file Plot_xcb.cc.
LE2
#define LE2 (x) uint8_t((x)), uint8_t((x) >> 8)
2 byte little endian
Definition at line 78 of file Plot_xcb.cc.
LE4
#define LE4 (x) LE2((x)), LE2((x >> 16))
4 byte little endian
Definition at line 81 of file Plot_xcb.cc.
PANGO
#define PANGO 0
draw text with pango
Definition at line 182 of file Plot_xcb.cc.
XCB_WINDOWS_WITH_UTF8_CAPTIONS
#define XCB_WINDOWS_WITH_UTF8_CAPTIONS 0
undefined → 0
Definition at line 45 of file Plot_xcb.cc.
XFT
#define XFT 0
draw text with Xdt
Definition at line 181 of file Plot_xcb.cc.
Function Documentation
do_plot()
void do_plot (const Plot_context & pctx, const Plot_window_properties & w_props, const Plot_data & data)
draw the content of a plot window
Definition at line 1040 of file Plot_xcb.cc.
References Plot_context::conn, draw_legend(), draw_plot_lines(), draw_surface_lines(), draw_X_grid(), draw_Y_grid(), draw_Z_grid(), Plot_window_properties::get_window_height(), Plot_window_properties::get_window_width(), Plot_data::is_surface_plot(), Plot_context::line, set_GC_attr(), and Plot_context::window.
Referenced by plot_main().
draw_legend()
void draw_legend (const Plot_context & pctx, const Plot_window_properties & w_props)
draw the legend
Definition at line 631 of file Plot_xcb.cc.
References Plot_context::conn, draw_line(), draw_point(), draw_text(), Plot_context::fill, Plot_window_properties::get_line_count(), Plot_window_properties::get_line_properties(), Plot_context::line, Plot_context::point, set_GC_foreground(), set_GC_line_width(), string_width_height::width, and Plot_context::window.
Referenced by do_plot().
draw_line()
void draw_line (const Plot_context & pctx, xcb_gcontext_t gc, const Pixel_XY & P0, const Pixel_XY & P1)
draw a line from P0 to P1
Definition at line 307 of file Plot_xcb.cc.
References Plot_context::conn, I1616, Plot_context::window, Pixel_XY::x, and Pixel_XY::y.
Referenced by draw_legend(), draw_plot_lines(), draw_surface_lines(), draw_triangle(), draw_X_grid(), draw_Y_grid(), and draw_Z_grid().
draw_plot_lines()
void draw_plot_lines (const Plot_context & pctx, const Plot_window_properties & w_props, const Plot_data & data)
draw the plot lines
Definition at line 825 of file Plot_xcb.cc.
References draw_line(), draw_point(), Plot_window_properties::get_line_properties(), Plot_window_properties::get_min_X(), Plot_window_properties::get_min_Y(), Plot_data::get_row_count(), Plot_data::get_XY(), Plot_context::line, Plot_context::point, set_GC_foreground(), set_GC_line_width(), Plot_window_properties::valX2pixel(), and Plot_window_properties::valY2pixel().
Referenced by do_plot().
draw_point()
void draw_point (const Plot_context & pctx, const Pixel_XY & xy, Color canvas_color, const Plot_line_properties & l_props)
draw a plot point (representing one data value) at position xy
Definition at line 490 of file Plot_xcb.cc.
References Plot_context::conn, I1616, ITEMS, Plot_context::point, set_GC_foreground(), Plot_context::window, Pixel_XY::x, and Pixel_XY::y.
Referenced by draw_legend(), draw_plot_lines(), and draw_surface_lines().
draw_surface_lines()
void draw_surface_lines (const Plot_context & pctx, const Plot_window_properties & w_props, const Plot_data & data)
draw the surface plot lines
Definition at line 867 of file Plot_xcb.cc.
References Pixel_XY::distance2(), draw_line(), draw_point(), draw_triangle(), Plot_window_properties::get_gradient(), Plot_window_properties::get_line_properties(), Plot_window_properties::get_max_Y(), Plot_window_properties::get_min_Y(), Plot_data::get_row_count(), Plot_window_properties::get_verbosity(), Plot_data::get_X(), Plot_data::get_Y(), Plot_data::get_Z(), intersection(), Plot_context::line, Plot_context::point, set_GC_foreground(), set_GC_line_width(), Plot_window_properties::valXYZ2pixelXY(), and verbosity.
Referenced by do_plot().
draw_text()
void draw_text (const Plot_context & pctx, const char * label, const Pixel_XY & xy)
draw text label at position xy
Definition at line 189 of file Plot_xcb.cc.
References Plot_context::conn, Plot_context::display, testCookie(), Plot_context::text, Plot_context::window, Pixel_XY::x, and Pixel_XY::y.
Referenced by draw_legend(), draw_X_grid(), draw_Y_grid(), and draw_Z_grid().
draw_triangle() [1/2]
void draw_triangle (const Plot_context & pctx, int verbosity, Pixel_XY P0, double H0, Pixel_XY P1, double H1, Pixel_XY P2, double H2)
draw a triangular plot point (∆ or ∇)
Definition at line 443 of file Plot_xcb.cc.
References draw_triangle(), pv_swap(), verbosity, Pixel_XY::x, and Pixel_XY::y.
draw_triangle() [2/2]
void draw_triangle (const Plot_context & pctx, int verbosity, Pixel_XY P0, double H0, Pixel_XY P1, Pixel_XY P2, double H12)
draw a triangular area of a 3D plot
Definition at line 409 of file Plot_xcb.cc.
References Pixel_XY::distance2(), draw_line(), Plot_context::fill, Plot_window_properties::get_color(), set_GC_foreground(), verbosity, Plot_context::w_props, Pixel_XY::x, and Pixel_XY::y.
Referenced by draw_surface_lines(), and draw_triangle().
draw_X_grid()
void draw_X_grid (const Plot_context & pctx, const Plot_window_properties & w_props, bool surface)
draw the (vertical) grid lines that start at the X axis
Definition at line 691 of file Plot_xcb.cc.
References draw_line(), draw_text(), format_tick(), Plot_window_properties::get_gridX_last(), Plot_window_properties::get_max_Y(), Plot_window_properties::get_min_X(), Plot_window_properties::get_min_Y(), Plot_window_properties::get_value_per_tile_X(), string_width_height::height, Plot_context::line, set_GC_foreground(), set_GC_line_width(), Plot_window_properties::valX2pixel(), Plot_window_properties::valY2pixel(), and string_width_height::width.
Referenced by do_plot().
draw_Y_grid()
void draw_Y_grid (const Plot_context & pctx, const Plot_window_properties & w_props, bool surface)
draw the (horizontal) grid lines that start at the Y axis
Definition at line 739 of file Plot_xcb.cc.
References draw_line(), draw_text(), format_tick(), Plot_window_properties::get_gridY_last(), Plot_window_properties::get_max_X(), Plot_window_properties::get_min_X(), Plot_window_properties::get_min_Y(), Plot_window_properties::get_value_per_tile_Y(), string_width_height::height, Plot_context::line, set_GC_foreground(), set_GC_line_width(), Plot_window_properties::valX2pixel(), Plot_window_properties::valY2pixel(), and string_width_height::width.
Referenced by do_plot().
draw_Z_grid()
void draw_Z_grid (const Plot_context & pctx, const Plot_window_properties & w_props)
draw the grid lines that start at the Z axis
Definition at line 789 of file Plot_xcb.cc.
References draw_line(), draw_text(), format_tick(), Plot_window_properties::get_gridZ_last(), Plot_window_properties::get_max_X(), Plot_window_properties::get_max_Y(), Plot_window_properties::get_min_X(), Plot_window_properties::get_min_Y(), Plot_window_properties::get_min_Z(), Plot_window_properties::get_value_per_tile_Z(), string_width_height::height, Plot_context::line, set_GC_foreground(), set_GC_line_width(), Plot_window_properties::valX2pixel(), Plot_window_properties::valXYZ2pixelXY(), Plot_window_properties::valY2pixel(), Pixel_XY::x, and Pixel_XY::y.
Referenced by do_plot().
format_tick()
char * format_tick (double val)
return the text of a grid tick with value val
Definition at line 255 of file Plot_xcb.cc.
Referenced by draw_X_grid(), draw_Y_grid(), and draw_Z_grid().
get_atom_ID()
xcb_atom_t get_atom_ID (xcb_connection_t * conn, int only_existing, const char * name)
obtain an ID for name
Definition at line 1073 of file Plot_xcb.cc.
Referenced by plot_main().
intersection()
double intersection (double Ax, double Ay, double Bx, double By, double Cx, double Cy, double Dx, double Dy) inline
given 4 points A=(Ax, Ay), B=(Bx, By), C=(Cx, Cy), and D=(Dx, Dy) in the plane, return the factor beta so that the intersection point M=(Mx, My) of the lines A-C and B-D is given by
M = (Mx, My) == A + alpha*(D-A) == B + beta*(C - B). Note that:
A \ B \ / M / \ / \ C D Ax + alpha*(Dx-Ax) == Bx + beta*(Cx-Bx) Ay + alpha*(Dy-Ay) == By + beta*(Cy-By)
Definition at line 323 of file Plot_xcb.cc.
Referenced by draw_surface_lines().
plot_main()
void * plot_main (void * vp_props)
the pthread that handles one plot window.
the main() program of the thread that handles one plot window.
Definition at line 1235 of file Plot_xcb.cc.
References Plot_context::conn, Plot_context::display, do_plot(), Plot_context::fill, Plot_context::font, get_atom_ID(), Plot_window_properties::get_plot_data(), Plot_window_properties::get_verbosity(), Plot_window_properties::get_window_height(), Plot_window_properties::get_window_width(), Plot_context::line, Quad_PLOT::plot_threads, Quad_PLOT::plot_threads_sema, Quad_PLOT::plot_window_sema, Plot_context::point, save_file(), Plot_context::screen, Plot_window_properties::set_window_size(), setup_font_gc(), testCookie(), Plot_context::text, and Plot_context::window.
pv_swap()
void pv_swap (Pixel_XY & P0, double & Y0, Pixel_XY & P1, double & Y1) inline
swap pixels at P0 (with value Y0) and P1 (with value Y1) and
Definition at line 316 of file Plot_xcb.cc.
Referenced by draw_triangle().
save_file()
void save_file (const char * outfile, Display * dpy, int window, const Plot_context & pctx)
save plot window to file named outfile
Definition at line 1083 of file Plot_xcb.cc.
References UTF8_string::append_ASCII(), UTF8_string::c_str(), UTF8_string::ends_with(), LE2, LE4, and Plot_context::screen.
Referenced by plot_main().
set_GC_attr()
void set_GC_attr (const Plot_context & pctx, xcb_gcontext_t gc, xcb_gc_t mask, uint32_t value) inline
set the an attribute of a xcb_gcontext_t
Definition at line 387 of file Plot_xcb.cc.
References Plot_context::conn.
Referenced by do_plot(), set_GC_foreground(), and set_GC_line_width().
set_GC_foreground()
void set_GC_foreground (const Plot_context & pctx, xcb_gcontext_t gc, Color color) inline
set the foreground color of a xcb_gcontext_t
Definition at line 395 of file Plot_xcb.cc.
References set_GC_attr().
Referenced by draw_legend(), draw_plot_lines(), draw_point(), draw_surface_lines(), draw_triangle(), draw_X_grid(), draw_Y_grid(), and draw_Z_grid().
set_GC_line_width()
void set_GC_line_width (const Plot_context & pctx, xcb_gcontext_t gc, int width) inline
set the line width of a xcb_gcontext_t
Definition at line 402 of file Plot_xcb.cc.
References set_GC_attr().
Referenced by draw_legend(), draw_plot_lines(), draw_surface_lines(), draw_X_grid(), draw_Y_grid(), and draw_Z_grid().
setup_font_gc()
xcb_gcontext_t setup_font_gc (Plot_context & pctx, const char * font_name, Color canvas_color)
return a xcb_gcontext_t for font font_name
Definition at line 165 of file Plot_xcb.cc.
References Plot_context::conn, Plot_context::font, testCookie(), and Plot_context::window.
Referenced by plot_main().
testCookie()
void testCookie (xcb_void_cookie_t cookie, xcb_connection_t * conn, const char * errMessage)
test obtaining of a cookie
Definition at line 152 of file Plot_xcb.cc.
Referenced by draw_text(), plot_main(), and setup_font_gc().