GNUAPL: src/PrintOperator.hh File Reference
PrintOperator.hh File Reference
#include <iostream>
#include "Common.hh"
#include "Id.hh"
#include "TokenEnums.hh"
#include "Unicode.hh"
Functions
ostream & operator<< (ostream &, const AP_num3 &)
ostream & operator<< (ostream &, const Format_sub &)
ostream & operator<< (ostream &, const Function &)
ostream & operator<< (ostream &, const Function_PC2 &)
ostream & operator<< (ostream &, const Cell &)
ostream & operator<< (ostream &, const DynamicObject &)
ostream & operator<< (ostream &, Id id)
ostream & operator<< (ostream &, const IndexExpr &)
ostream & operator<< (ostream &, const LineLabel &)
ostream & operator<< (ostream &, const PrintBuffer &)
ostream & operator<< (ostream &, const Shape &)
ostream & operator<< (ostream &, const Symbol &)
ostream & operator<< (ostream &, const Token &)
ostream & operator<< (ostream &, const Token_string &)
ostream & operator<< (ostream &, TokenTag)
ostream & operator<< (ostream &, TokenClass)
ostream & operator<< (ostream &, const UCS_string &)
ostream & operator<< (ostream &, Unicode)
ostream & operator<< (ostream &, const UTF8_string &)
ostream & operator<< (ostream &, const Value &)
ostream & operator<< (ostream &out, ValueFlags flags)
ostream & operator<< (ostream &out, const labVal &lv)
Function Documentation
operator<<() [1/22]
ostream& operator<< (ostream & , const AP_num3 &)
Definition at line 3015 of file Value.cc.
References AP_num3::grand, AP_num3::parent, and AP_num3::proc.
operator<<() [2/22]
ostream& operator<< (ostream & , const Format_sub &)
Definition at line 1204 of file Bif_F12_FORMAT.cc.
References Format_sub::print().
operator<<() [3/22]
ostream& operator<< (ostream & , const Function &)
Definition at line 163 of file Function.cc.
References Function::print().
operator<<() [4/22]
ostream& operator<< (ostream & , const Function_PC2 &)
Definition at line 281 of file Common.cc.
References Function_PC2::high, and Function_PC2::low.
operator<<() [5/22]
ostream& operator<< (ostream & , const Cell &)
Definition at line 247 of file Cell.cc.
References Cell::character_representation(), Workspace::get_PW(), and PR_BOXED_GRAPHIC.
operator<<() [6/22]
ostream& operator<< (ostream & , const DynamicObject &)
Definition at line 30 of file DynamicObject.cc.
References DynamicObject::print().
operator<<() [7/22]
ostream& operator<< (ostream & , Id id)
Definition at line 132 of file Id.cc.
References ID::get_name().
operator<<() [8/22]
ostream& operator<< (ostream & , const IndexExpr &)
Definition at line 157 of file IndexExpr.cc.
References IndexExpr::get_axis_value(), Workspace::get_PrintContext(), Workspace::get_PW(), IndexExpr::get_rank(), i, loop, and PR_APL_MIN.
operator<<() [9/22]
ostream& operator<< (ostream & , const LineLabel &)
Definition at line 1026 of file Nabla.cc.
References LineLabel::print().
operator<<() [10/22]
ostream& operator<< (ostream & , const PrintBuffer &)
Definition at line 1418 of file PrintBuffer.cc.
References PrintBuffer::debug().
operator<<() [11/22]
ostream& operator<< (ostream & , const Shape &)
Definition at line 177 of file Shape.cc.
References Shape::get_rank(), Shape::get_shape_item(), and loop.
operator<<() [12/22]
ostream& operator<< (ostream & , const Symbol &)
Definition at line 1254 of file Symbol.cc.
References Symbol::print().
operator<<() [13/22]
ostream& operator<< (ostream & , const Token &)
Definition at line 138 of file Token.cc.
References Error::error_name(), FIXME, Token::get_apl_val(), Token::get_axes(), Token::get_char_val(), Token::get_Class(), Token::get_fun_line(), Token::get_Id(), Token::get_index_val(), Token::get_int_val(), PrintBuffer::get_line(), PrintBuffer::get_row_count(), Token::get_sym_ptr(), Token::get_tag(), ID_No_ID2, UCS_string::no_pad(), PR_APL, Symbol::print(), Token::print_function(), Token::print_value(), UCS_string::size(), TC_END, TC_FUN0, TC_FUN12, TC_INDEX, TC_LINE, TC_NEWLINE, TC_NUMERIC, TC_OPER1, TC_OPER2, TC_PINDEX, TC_RETURN, TC_SYMBOL, TC_VALUE, TOK_APL_VALUE1, TOK_APL_VALUE2, TOK_APL_VALUE3, TOK_AXIS, TOK_BRANCH, TOK_CHARACTER, TOK_ERROR, TOK_INDEX, TOK_LSYMB, TOK_LSYMB2, TOK_NOBRANCH, TOK_RETURN_EXEC, TOK_RETURN_STATS, TOK_RETURN_SYMBOL, TOK_RETURN_VOID, UNI_LEFT_ARROW, and Token::value.
operator<<() [14/22]
ostream& operator<< (ostream & , const Token_string &)
Definition at line 711 of file Token.cc.
References CERR, and loop.
operator<<() [15/22]
ostream& operator<< (ostream & , TokenTag)
Definition at line 88 of file Token.cc.
References HEX, and HEX4.
operator<<() [16/22]
ostream& operator<< (ostream & , TokenClass)
Definition at line 97 of file Token.cc.
References TC_ASSIGN, TC_COLON, TC_DIAMOND, TC_END, TC_FUN0, TC_FUN12, TC_INDEX, TC_INVALID, TC_L_BRACK, TC_L_PARENT, TC_LINE, TC_NEWLINE, TC_NUMERIC, TC_OFF, TC_OPER1, TC_OPER2, TC_PINDEX, TC_QUOTE, TC_R_ARROW, TC_R_BRACK, TC_R_PARENT, TC_RETURN, TC_SI_LEAVE, TC_SPACE, TC_SYMBOL, TC_VALUE, TC_VOID, and tcc.
operator<<() [17/22]
ostream& operator<< (ostream & , const UCS_string &)
Definition at line 1234 of file UCS_string.cc.
References loop, UCS_string::size(), and u.
operator<<() [18/22]
ostream& operator<< (ostream & , Unicode)
Definition at line 1203 of file UCS_string.cc.
operator<<() [19/22]
ostream& operator<< (ostream & , const UTF8_string &)
Definition at line 401 of file UTF8_string.cc.
References c, and loop.
operator<<() [20/22]
ostream& operator<< (ostream & , const Value &)
Definition at line 2910 of file Value.cc.
References Value::print().
operator<<() [21/22]
ostream& operator<< (ostream & out, ValueFlags flags) inline
Definition at line 69 of file PrintOperator.hh.
References print_flags().
operator<<() [22/22]
ostream& operator<< (ostream & out, const labVal & lv) inline
Definition at line 72 of file PrintOperator.hh.
References labVal::line.