GNUAPL: src/python_apl.cc File Reference
python_apl.cc File Reference
#include <Python.h>
#include "Command.hh"
#include "ComplexCell.hh"
#include "DiffOut.hh"
#include "Error.hh"
#include "FloatCell.hh"
#include "LineInput.hh"
#include "Macro.hh"
#include "PointerCell.hh"
#include "Tokenizer.hh"
#include "UserPreferences.hh"
#include "Workspace.hh"
Macros
#define PY_SSIZE_T_CLEAN
Functions
void init_1 (const char *argv0, bool log_startup)
initialize
void init_2 (bool log_startup)
initialize subsystems that depend on argv[]
void do_init ()
void init_if_necessary ()
static PyObject * apl_command (PyObject *self, PyObject *args)
static PyObject * apl_to_python (const Value *value)
bool python_result_callback (Token &result)
static PyObject * apl_exec (PyObject *self, PyObject *args)
static const Value * apl_get_var_value (PyObject *args)
static PyObject * make_shape (const Shape &shape)
static PyObject * apl_get_shape (PyObject *self, PyObject *args)
static PyObject * make_ravel (const Value *value)
static PyObject * apl_get_ravel (PyObject *self, PyObject *args)
static PyObject * apl_get_value (PyObject *self, PyObject *args)
static Shape list_to_shape (PyObject *shape)
Shape shape_for_item (PyObject *item)
static Value_P python_to_apl (PyObject *ravel, PyObject *shape)
static Value_P python_to_apl (PyObject *ravel, const Shape &shape)
static PyObject * apl_set_value (PyObject *self, PyObject *args)
static PyObject * apl_fix_function (PyObject *self, PyObject *args)
static PyObject * apl_set_display (PyObject *self, PyObject *args)
static PyObject * apl_help (PyObject *self, PyObject *args)
PyMODINIT_FUNC PyInit_gnu_apl (void)
Variables
static int display_mode = 1
static PyObject * exec_result = 0
const char * DESCR_help
const char * DESCR_command
const char * DESCR_exec
const char * DESCR_fix_function
const char * DESCR_get_ravel
const char * DESCR_get_shape
const char * DESCR_get_value
const char * DESCR_set_display
const char * DESCR_values
const char * DESCR_set_value
static PyMethodDef AplMethods []
static struct PyModuleDef apl_module
Macro Definition Documentation
PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
Definition at line 2 of file python_apl.cc.
Function Documentation
apl_command()
static PyObject* apl_command (PyObject * self, PyObject * args) static
Definition at line 53 of file python_apl.cc.
References CERR, command, Command::do_APL_command(), and init_if_necessary().
apl_exec()
static PyObject* apl_exec (PyObject * self, PyObject * args) static
Definition at line 164 of file python_apl.cc.
References CERR, error, exec_result, StateIndicator::get_error(), Error::get_error_code(), init_if_necessary(), Command::process_line(), and Workspace::SI_top_error().
apl_fix_function()
static PyObject* apl_fix_function (PyObject * self, PyObject * args) static
Definition at line 483 of file python_apl.cc.
References CERR, UserFunction::fix(), init_if_necessary(), and LOC.
apl_get_ravel()
static PyObject* apl_get_ravel (PyObject * self, PyObject * args) static
Definition at line 294 of file python_apl.cc.
References apl_get_var_value(), make_ravel(), and value().
apl_get_shape()
static PyObject* apl_get_shape (PyObject * self, PyObject * args) static
Definition at line 257 of file python_apl.cc.
References apl_get_var_value(), Value::get_shape(), make_shape(), and value().
apl_get_value()
static PyObject* apl_get_value (PyObject * self, PyObject * args) static
Definition at line 302 of file python_apl.cc.
References apl_get_var_value(), Value::get_shape(), make_ravel(), make_shape(), and value().
apl_get_var_value()
static const Value* apl_get_var_value (PyObject * args) static
Definition at line 216 of file python_apl.cc.
References CERR, ValueStackItem::get_NC(), ValueStackItem::get_val_cptr(), init_if_necessary(), Workspace::lookup_existing_symbol(), NC_VARIABLE, and Symbol::top_of_stack().
Referenced by apl_get_ravel(), apl_get_shape(), and apl_get_value().
apl_help()
static PyObject* apl_help (PyObject * self, PyObject * args) static
Definition at line 741 of file python_apl.cc.
References CERR, DESCR_command, DESCR_exec, DESCR_fix_function, DESCR_get_ravel, DESCR_get_shape, DESCR_get_value, DESCR_help, DESCR_set_display, DESCR_set_value, and DESCR_values.
apl_set_display()
static PyObject* apl_set_display (PyObject * self, PyObject * args) static
Definition at line 511 of file python_apl.cc.
References CERR, and display_mode.
apl_set_value()
static PyObject* apl_set_value (PyObject * self, PyObject * args) static
Definition at line 420 of file python_apl.cc.
References Symbol::assign(), CERR, init_if_necessary(), LOC, Workspace::lookup_symbol(), python_to_apl(), and value().
apl_to_python()
static PyObject* apl_to_python (const Value * value) static
Definition at line 74 of file python_apl.cc.
References CERR, Value_P_Base::get(), Cell::get_char_value(), Value::get_cravel(), Cell::get_imag_value(), Cell::get_int_value(), Cell::get_pointer_value(), Value::get_rank(), Cell::get_real_value(), Value::get_shape_item(), i, Cell::is_character_cell(), Cell::is_complex_cell(), Cell::is_float_cell(), Cell::is_integer_cell(), Cell::is_pointer_cell(), LOC, loop, and Value::nz_element_count().
Referenced by python_result_callback().
do_init()
void do_init ()
Definition at line 28 of file python_apl.cc.
References init_1(), init_2(), UserPreferences::read_config_file(), UserPreferences::requested_id, UserPreferences::system_do_svars, uprefs, and UserPreferences::user_do_svars.
Referenced by init_if_necessary().
init_1()
void init_1 (const char * argv0, bool log_startup)
initialize
Definition at line 83 of file Common.cc.
References CERR, Avec::init(), Quad_WA::init(), VH_entry::init(), LibPaths::init(), Value::init(), RLIM_INFINITY, Quad_WA::total_memory, and Value.
Referenced by do_init(), and init_apl().
init_2()
void init_2 (bool log_startup)
initialize subsystems that depend on argv[]
Definition at line 147 of file Common.cc.
References UserPreferences::emacs_mode, LibPaths::get_APL_bin_name(), LibPaths::get_APL_bin_path(), Svar_DB::init(), Output::init(), Parallel::init(), LineInput::init(), UserPreferences::system_do_svars, and uprefs.
Referenced by do_init(), and init_apl().
init_if_necessary()
void init_if_necessary () inline
Definition at line 46 of file python_apl.cc.
References do_init().
Referenced by apl_command(), apl_exec(), apl_fix_function(), apl_get_var_value(), and apl_set_value().
list_to_shape()
static Shape list_to_shape (PyObject * shape) static
Definition at line 313 of file python_apl.cc.
References Shape::add_shape_item(), CERR, LOC, and loop.
Referenced by python_to_apl(), and shape_for_item().
make_ravel()
static PyObject* make_ravel (const Value * value) static
Definition at line 266 of file python_apl.cc.
References CERR, Value::get_cravel(), Cell::get_int_value(), Cell::get_real_value(), Cell::is_float_cell(), Cell::is_integer_cell(), loop, and Value::nz_element_count().
Referenced by apl_get_ravel(), and apl_get_value().
make_shape()
static PyObject* make_shape (const Shape & shape) static
Definition at line 247 of file python_apl.cc.
References Shape::get_rank(), Shape::get_shape_item(), and loop.
Referenced by apl_get_shape(), and apl_get_value().
PyInit_gnu_apl()
PyMODINIT_FUNC PyInit_gnu_apl (void)
Definition at line 816 of file python_apl.cc.
References apl_module.
python_result_callback()
bool python_result_callback (Token & result)
Definition at line 118 of file python_apl.cc.
References apl_to_python(), CERR, display_mode, exec_result, FIXME, Value_P_Base::get(), Token::get_apl_val(), Token::get_int_val(), Token::get_tag(), LOC, TOK_APL_VALUE1, TOK_APL_VALUE2, TOK_APL_VALUE3, TOK_BRANCH, TOK_ESCAPE, TOK_NOBRANCH, and TOK_VOID.
Referenced by StateIndicator::get_line(), and StateIndicator::statement_result().
python_to_apl() [1/2]
static Value_P python_to_apl (PyObject * ravel, PyObject * shape) static
Definition at line 413 of file python_apl.cc.
References list_to_shape(), and shape_for_item().
Referenced by apl_set_value(), python_to_apl(), and shape_for_item().
python_to_apl() [2/2]
static Value_P python_to_apl (PyObject * ravel, const Shape & shape) static
Definition at line 355 of file python_apl.cc.
References CERR, FIXME, Value_P_Base::get(), LOC, loop, python_to_apl(), and UCS_string::size().
shape_for_item()
Shape shape_for_item (PyObject * item)
Definition at line 332 of file python_apl.cc.
References CERR, list_to_shape(), LOC, and python_to_apl().
Referenced by python_to_apl().
Variable Documentation
apl_module
struct PyModuleDef apl_module static
Initial value:
=
{
  PyModuleDef_HEAD_INIT,
  "gnu_apl",
  0,
  -1,
  AplMethods
}
Definition at line 805 of file python_apl.cc.
Referenced by PyInit_gnu_apl().
AplMethods
PyMethodDef AplMethods[] static
Initial value:
=
{
  { "help",         apl_help,         METH_VARARGS, DESCR_help         },
  { "command",      apl_command,      METH_VARARGS, DESCR_command      },
  { "exec",         apl_exec,         METH_VARARGS, DESCR_exec         },
  { "fix_function", apl_fix_function, METH_VARARGS, DESCR_fix_function },
  { "get_ravel",    apl_get_ravel,    METH_VARARGS, DESCR_get_ravel    },
  { "get_shape",    apl_get_shape,    METH_VARARGS, DESCR_get_shape    },
  { "get_value",    apl_get_value,    METH_VARARGS, DESCR_get_value    },
  { "set_value",    apl_set_value,    METH_VARARGS, DESCR_set_value    },
  { "set_display",  apl_set_display,  METH_VARARGS, DESCR_set_display  },
  { NULL,           0,                0,            0 }
}
Definition at line 791 of file python_apl.cc.
DESCR_command
const char* DESCR_command
Initial value:
=
"gnu_apl.command() : execute an APL command.\n"
"\n"
"Synopsis: Result = gnu_apl.command(cmd)\n"
"   cmd is an UTF8 string containing a valid APL expression\n"
"\n"
"Result:\n"
"   a UTF8 string that contains the output of the command (which depends on\n"
"   the command that was executed).\n"
Definition at line 553 of file python_apl.cc.
Referenced by apl_help().
DESCR_exec
const char* DESCR_exec
Initial value:
=
"gnu_apl.exec() : execute an APL expression.\n"
"\n"
"Synopsis: Result = gnu_apl.exec(expr)\n"
"   expr is an UTF8 string containing a valid APL expression\n"
"\n"
"Result:\n"
"    tuple(0, error_code)   if the expression caused an error\n"
"    tuple(1, value)        if the expression returned an uncommitted value\n"
"    tuple(2, value)        if the expression returned a committed value\n"
"    tuple(3, None)         if the expression returned no value\n"
"    tuple(4, value)        if the expression returned a branch (e.g. →N)\n"
"    tuple(5, value)        if the expression returned branch escape (→)\n"
"\n"
"Note: Result has the same format as ⎕EC (execute controlled)\n"
Definition at line 564 of file python_apl.cc.
Referenced by apl_help().
DESCR_fix_function
const char* DESCR_fix_function
Initial value:
=
"gnu_apl.fix_function() : create (aka. ⎕FX) a new defined APL function, or\n"
"                         change the definition of an existing definition.\n"
"\n"
"Synopsis: Result = gnu_apl.fix_function(text)\n"
"    text is a UTF8 string containing the function lines (separated by \\n).\n"
"    The first line in text is the function signature, e.g. Z←A myfun B\n"
"    The subsequent lines in text comprise the function body.\n"
"\n"
"Result:\n"
"    None       if the function could be created,\n"
"    int(0)     if the function signature was incorrect, \n"
"    int(N)     if the body line N ≥ 1 was incorrect.\n"
"    int(-1)    if something else went wrong.\n"
"\n"
"NOTE: creating or modifying defined APL functions with ⎕FX (in APL) or by\n"
"    gnu_apl.fix_function() (in Python) is not the usual way of creating or\n"
"    modifying defined APL functions. Most APL programmers will prefer to use\n"
"    the standard APL ∇-editor (in interactive APL sessions) or to write APL\n"
"    scripts in order to create an APL workspace that contains the desired\n"
"    defined functions. The workspace is then loaded with APL commands\n"
")LOAD or)COPY (in APL) resp. gnu_apl.command(')LOAD ...') or\n"
"    gnu_apl.command(')COPY ...') in Python."
Definition at line 581 of file python_apl.cc.
Referenced by apl_help().
DESCR_get_ravel
const char* DESCR_get_ravel
Initial value:
=
"gnu_apl.get_cravel() : get the ravel of an APL variable.\n"
"\n"
"Synopsis: Result = gnu_apl.get_cravel(text)\n"
"    varname is a string containing the name of an APL variable.\n"
"\n"
"Result:\n"
"   on sucess:   list [ i₁, i₂, ... iN ] where N is the length of the\n"
"                ravel (aka, ,varname in APL) of the value of the variable,\n"
"                and iK is the K'th ravel element:\n"
"                    int(iK):       an APL integer\n"
"                    float(iK):     an APL float\n"
"                    complex(iK):   an APL complex value\n"
"                    chr(iK):       an APL character (Unicode)\n"
"                    list(iK):      a nested APL sub-value\n"
"                    tuple(R, S):   a nested APL sub-value with ravel R\n"
"                                   and shape S\n"
"   otherwise:   int(error_code)\n"
"\n"
"Example:\n"
"    gnu_apl.exec('Var←4 4⍴⍳16')\n"
"(2, ([4, 4], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]))\n"
"    gnu_apl.get_cravel('Var')\n"
"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]\n"
Definition at line 606 of file python_apl.cc.
Referenced by apl_help().
DESCR_get_shape
const char* DESCR_get_shape
Initial value:
=
"gnu_apl.get_shape() : get the shape of an APL variable.\n"
"\n"
"Synopsis: Result = gnu_apl.get_shape(text)\n"
"    varname is a string containing the name of an APL variable.\n"
"\n"
"Result:\n"
"    on sucess:   list [ r₁, r₂, ... rR ] where R is the number of axes\n"
"                 (aka. the rank in APL) of the value of the variable and\n"
"                 rK is the length of the Kth axis.\n"
"    otherwise:   int(error_code)\n"
"\n"
"Example:\n"
"    gnu_apl.exec('Var←4 4⍴⍳16')\n"
"(2, ([4, 4], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]))\n"
"    gnu_apl.get_shape('Var')\n"
"[4, 4]\n"
Definition at line 632 of file python_apl.cc.
Referenced by apl_help().
DESCR_get_value
const char* DESCR_get_value
Initial value:
=
"gnu_apl.get_value() : get the value of an APL variable.\n"
"\n"
"Synopsis: Result = gnu_apl.get_value(varname)\n"
"    varname is a string containing the name of an APL variable.\n"
"\n"
"Result:\n"
"    on sucess:   tuple(get_cravel(varname), get_shape(varname))\n"
"    otherwise:   int(error_code)\n"
"\n"
"Example:\n"
"    gnu_apl.exec('Var←4 4⍴⍳16')\n"
"(2, ([4, 4], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]))\n"
"    gnu_apl.get_value('Var')\n"
"([4, 4], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])\n"
Definition at line 651 of file python_apl.cc.
Referenced by apl_help().
DESCR_help
const char* DESCR_help
Initial value:
=
"gnu_apl.help() : print help for a topic.\n"
"\n"
"Synopsis: gnu_apl.help(topic)\n"
"   topic is an UTF8 string containing a help topic.\n"
"\n"
"Examples:\n"
"    gnu_apl.help()           (this text)\n"
"    gnu_apl.help('all')      (long)\n"
"    gnu_apl.help('help')\n"
"    gnu_apl.help('command')\n"
"    gnu_apl.help('exec')\n"
"    gnu_apl.help('fix_function')\n"
"    gnu_apl.help('get_ravel')\n"
"    gnu_apl.help('get_shape')\n"
"    gnu_apl.help('get_value')\n"
"    gnu_apl.help('set_value')\n"
"    gnu_apl.help('APL-values')\n"
"\n"
Definition at line 532 of file python_apl.cc.
Referenced by apl_help().
DESCR_set_display
const char* DESCR_set_display
Initial value:
=
"gnu_apl.set_display() : set the APL display mode.\n"
"\n"
"Synopsis: Result = gnu_apl.set_display(mode)\n"
"    mode is an integer:\n"
"        0:     display neither committed values nor not committed values\n"
"        1:     display only not committed values (standard APL behavior)\n"
"        2:     display both committed values and not committed values\n"
"\n"
"Result: the previous display mode\n"
Definition at line 668 of file python_apl.cc.
Referenced by apl_help().
DESCR_set_value
const char* DESCR_set_value
Initial value:
=
"gnu_apl.set_value() : set the value of an APL variable.\n"
"                      The variable is created if necessary.\n"
"\n"
"Synopsis: gnu_apl.set_value(varname, value)\n"
"    varname is a UTF8 string containing the name of an APL variable.\n"
"    value is the new value of the variable, see gnu_apl.help('APL-values').\n"
"\n"
"Examples:\n"
"    gnu_apl.set_value('Var', 65)                # Var ← 65\n"
"    gnu_apl.set_value('Var', 6.5)               # Var ← 6.5\n"
"    gnu_apl.set_value('Var', 6J5)               # Var ← 6J5\n"
"    gnu_apl.set_value('Var', [6, 5, 'A'])       # Var ← 6 5 'A'\n"
"    gnu_apl.set_value('Var', [1, [2, 3], 4])    # Var ← 1 (2 3) 4\n"
Definition at line 723 of file python_apl.cc.
Referenced by apl_help().
DESCR_values
const char* DESCR_values
Definition at line 680 of file python_apl.cc.
Referenced by apl_help().
display_mode
int display_mode = 1 static
Definition at line 19 of file python_apl.cc.
Referenced by apl_set_display(), and python_result_callback().
exec_result
PyObject* exec_result = 0 static
Definition at line 115 of file python_apl.cc.
Referenced by apl_exec(), and python_result_callback().