GNUAPL: src/Quad_SQL.cc File Reference
Quad_SQL.cc File Reference
#include <string.h>
#include <typeinfo>
#include <vector>
#include "Common.hh"
#include "sql/apl-sqlite.hh"
#include "sql/Connection.hh"
#include "sql/Provider.hh"
#include "Quad_SQL.hh"
#include "Security.hh"
Functions
void init_provider_map ()
static Token list_functions (ostream &out)
static int find_free_connection (void)
Token open_database (Value_P A, Value_P B)
static void throw_illegal_db_id (void)
static Connection * db_id_to_connection (int db_id)
static Connection * value_to_db_id (Value_P value)
static Token close_database (Value_P B)
static Value_P run_generic_one_query (ArgListBuilder *arg_list, Value_P B, int start, int num_args, bool ignore_result)
static Value_P run_generic (Connection *conn, Value_P A, Value_P B, bool query)
static Token run_query (Connection *conn, Value_P A, Value_P B)
static Token run_update (Connection *conn, Value_P A, Value_P B)
static Token run_transaction_begin (Value_P B)
static Token run_transaction_commit (Value_P B)
static Token run_transaction_rollback (Value_P B)
static Token show_tables (Value_P B)
static Token show_cols (Value_P A, Value_P B)
static Connection * param_to_db (Value_P X)
static const UCS_string ucs_string_from_string (const std::string &string)
Value_P make_string_cell (const std::string &string, const char *loc)
Variables
static std::vector< Provider * > providers
static std::vector< Connection * > connections
Function Documentation
close_database()
static Token close_database (Value_P B) static
Definition at line 169 of file Quad_SQL.cc.
References connections, DOMAIN_ERROR, LOC, MORE_ERROR(), Str0(), throw_illegal_db_id(), and TOK_APL_VALUE1.
Referenced by Quad_SQL::eval_XB().
db_id_to_connection()
static Connection* db_id_to_connection (int db_id) static
Definition at line 143 of file Quad_SQL.cc.
References connections, and throw_illegal_db_id().
Referenced by param_to_db(), and value_to_db_id().
find_free_connection()
static int find_free_connection (void) static
Definition at line 103 of file Quad_SQL.cc.
References connections, and i.
Referenced by open_database().
init_provider_map()
void init_provider_map () inline
Definition at line 54 of file Quad_SQL.cc.
References providers.
Referenced by Quad_SQL::Quad_SQL().
list_functions()
static Token list_functions (ostream & out) static
Definition at line 87 of file Quad_SQL.cc.
References LOC, Str0(), and TOK_APL_VALUE1.
Referenced by Quad_SQL::eval_AB(), Quad_SQL::eval_AXB(), Quad_SQL::eval_B(), and Quad_SQL::eval_XB().
make_string_cell()
Value_P make_string_cell (const std::string & string, const char * loc)
Definition at line 455 of file Quad_SQL.cc.
References i, s, UCS_string::size(), and ucs_string_from_string().
Referenced by show_cols(), and show_tables().
open_database()
Token open_database (Value_P A, Value_P B)
Definition at line 114 of file Quad_SQL.cc.
References connections, find_free_connection(), NamedObject::get_name(), IntScalar(), LOC, loop, MORE_ERROR(), providers, TOK_APL_VALUE1, and VALUE_ERROR.
Referenced by Quad_SQL::eval_AXB().
param_to_db()
static Connection* param_to_db (Value_P X) static
Definition at line 406 of file Quad_SQL.cc.
References db_id_to_connection(), Shape::get_volume(), MORE_ERROR(), and RANK_ERROR.
Referenced by Quad_SQL::eval_AXB().
run_generic()
static Value_P run_generic (Connection * conn, Value_P A, Value_P B, bool query) static
Definition at line 228 of file Quad_SQL.cc.
References Assert_fatal, Shape::get_cols(), Shape::get_rank(), Shape::get_rows(), Shape::get_volume(), Idx0(), LOC, loop, MORE_ERROR(), RANK_ERROR, run_generic_one_query(), and VALUE_ERROR.
Referenced by run_query(), and run_update().
run_generic_one_query()
static Value_P run_generic_one_query (ArgListBuilder * arg_list, Value_P B, int start, int num_args, bool ignore_result) static
Definition at line 197 of file Quad_SQL.cc.
References Cell::get_int_value(), Cell::get_real_value(), i, Cell::is_float_cell(), Cell::is_integer_cell(), LOC, MORE_ERROR(), Cell::to_value(), value(), and VALUE_ERROR.
Referenced by run_generic().
run_query()
static Token run_query (Connection * conn, Value_P A, Value_P B) static
Definition at line 276 of file Quad_SQL.cc.
References run_generic(), and TOK_APL_VALUE1.
Referenced by Quad_SQL::eval_AXB().
run_transaction_begin()
static Token run_transaction_begin (Value_P B) static
Definition at line 286 of file Quad_SQL.cc.
References Idx0(), LOC, TOK_APL_VALUE1, and value_to_db_id().
Referenced by Quad_SQL::eval_XB().
run_transaction_commit()
static Token run_transaction_commit (Value_P B) static
Definition at line 293 of file Quad_SQL.cc.
References Idx0(), LOC, TOK_APL_VALUE1, and value_to_db_id().
Referenced by Quad_SQL::eval_XB().
run_transaction_rollback()
static Token run_transaction_rollback (Value_P B) static
Definition at line 300 of file Quad_SQL.cc.
References Idx0(), LOC, TOK_APL_VALUE1, and value_to_db_id().
Referenced by Quad_SQL::eval_XB().
run_update()
static Token run_update (Connection * conn, Value_P A, Value_P B) static
Definition at line 281 of file Quad_SQL.cc.
References run_generic(), and TOK_APL_VALUE1.
Referenced by Quad_SQL::eval_AXB().
show_cols()
static Token show_cols (Value_P A, Value_P B) static
Definition at line 331 of file Quad_SQL.cc.
References Value_P_Base::get(), i, Idx0(), LOC, make_string_cell(), MORE_ERROR(), Str0(), TOK_APL_VALUE1, VALUE_ERROR, and value_to_db_id().
Referenced by Quad_SQL::eval_AXB().
show_tables()
static Token show_tables (Value_P B) static
Definition at line 307 of file Quad_SQL.cc.
References i, Idx0(), LOC, make_string_cell(), TOK_APL_VALUE1, value(), and value_to_db_id().
Referenced by Quad_SQL::eval_XB().
throw_illegal_db_id()
static void throw_illegal_db_id (void) static
Definition at line 136 of file Quad_SQL.cc.
References DOMAIN_ERROR, and MORE_ERROR().
Referenced by close_database(), db_id_to_connection(), and value_to_db_id().
ucs_string_from_string()
static const UCS_string ucs_string_from_string (const std::string & string) static
Definition at line 446 of file Quad_SQL.cc.
References UCS_string::size(), and utf8P().
Referenced by make_string_cell().
value_to_db_id()
static Connection* value_to_db_id (Value_P value) static
Definition at line 159 of file Quad_SQL.cc.
References db_id_to_connection(), and throw_illegal_db_id().
Referenced by run_transaction_begin(), run_transaction_commit(), run_transaction_rollback(), show_cols(), and show_tables().
Variable Documentation
connections
std::vector<Connection *> connections static
Definition at line 36 of file Quad_SQL.cc.
Referenced by close_database(), db_id_to_connection(), find_free_connection(), and open_database().
providers
std::vector<Provider *> providers static
Definition at line 35 of file Quad_SQL.cc.
Referenced by init_provider_map(), open_database(), and Quad_SQL::~Quad_SQL().