GNU APL: src/Quad_PNG.cc File Reference
Quad_PNG.cc File Reference
#include "config.h"
#include "Quad_PNG.hh"
#include <stdio.h>
#include <zlib.h>
#include <png.h>
#include "Common.hh"
#include <X11/Xlib.h>
#include <gtk/gtk.h>
Classes
struct PNG_context
a context binding window properties and data for one ⎕PNG window
Enumerations
enum {
SHOW_NONE = 0 ,
SHOW_EVENTS = 1 ,
SHOW_DATA = 2 ,
SHOW_DRAW = 4 ,
SHOW_ALL = SHOW_EVENTS | SHOW_DATA | SHOW_DRAW
}
⎕PNG verbosity bitmap
Functions
void * plot_PNG_main (void *vp_props)
the main() program of the thread that handles one PNG display window.
static void PNG_warn (png_structp png_ptr, png_const_charp reason)
callback for libpng warnings
static void PNG_err (png_structp png_ptr, png_const_charp reason)
callback for libpng errors
static void * gtk_main_wrapper (void *w_props)
make gtk_main() suitable for pthread_create() and maybe tell when it is finished. Executed in the thread named apl/⎕PNG.
gboolean PNG_plot_destroyed (GtkWidget *top_level)
callback when the plot window is destroyed
static cairo_surface_t * paint_data (const PNG_context &pctx)
convert APL pixel data to a Gtk/Cairo surface
gboolean PNG_draw_callback (GtkWidget *drawing_area, cairo_t *cr, gpointer user_data)
Gtk callback to draw the ⎕PNG window.
Variables
sem_t __PNG_threads_sema
thread start-up semaphore
sem_t __PNG_window_sema
window exposed semaphore
int verbosity = SHOW_NONE
(Debug-) verbosity of ⎕PNG
static int plot_window_count = 0
the number of open plot windows (to see when the last one was closed).
static vector< PNG_context * > all_PNG_contexts
all PNG_contexts (= all open windows) for ⎕PNG
Enumeration Type Documentation
anonymous enum
anonymous enum
⎕PNG verbosity bitmap
Enumerator
SHOW_EVENTS
show nothing
show X events
SHOW_DATA
show APL data
SHOW_DRAW
show draw details
Definition at line 52 of file Quad_PNG.cc.
Function Documentation
gtk_main_wrapper()
static void * gtk_main_wrapper (void * w_props) static
make gtk_main() suitable for pthread_create() and maybe tell when it is finished. Executed in the thread named apl/⎕PNG.
Definition at line 628 of file Quad_PNG.cc.
References all_PNG_contexts, plot_window_count, SHOW_EVENTS, and verbosity.
paint_data()
static cairo_surface_t * paint_data (const PNG_context & pctx) static
convert APL pixel data to a Gtk/Cairo surface
Definition at line 688 of file Quad_PNG.cc.
References Value_P_Base::get(), and PNG_context::get_APL_value().
Referenced by PNG_draw_callback().
PNG_draw_callback()
gboolean PNG_draw_callback (GtkWidget * drawing_area, cairo_t * cr, gpointer user_data)
Gtk callback to draw the ⎕PNG window.
Definition at line 763 of file Quad_PNG.cc.
References all_PNG_contexts, paint_data(), SHOW_EVENTS, and verbosity.
Referenced by Quad_PNG::display_PNG_main().
PNG_err()
static void PNG_err (png_structp png_ptr, png_const_charp reason) static
callback for libpng errors
Definition at line 141 of file Quad_PNG.cc.
Referenced by Quad_PNG::read_PNG_file(), and Quad_PNG::write_PNG_file().
PNG_plot_destroyed()
gboolean PNG_plot_destroyed (GtkWidget * top_level)
callback when the plot window is destroyed
Definition at line 650 of file Quad_PNG.cc.
References all_PNG_contexts, SHOW_EVENTS, verbosity, and PNG_context::window.
Referenced by Quad_PNG::display_PNG_main().
PNG_warn()
static void PNG_warn (png_structp png_ptr, png_const_charp reason) static
callback for libpng warnings
Definition at line 134 of file Quad_PNG.cc.
Referenced by Quad_PNG::read_PNG_file(), and Quad_PNG::write_PNG_file().
Variable Documentation
__PNG_threads_sema
sem_t __PNG_threads_sema
thread start-up semaphore
Definition at line 44 of file Quad_PNG.cc.
__PNG_window_sema
sem_t __PNG_window_sema
window exposed semaphore
Definition at line 48 of file Quad_PNG.cc.
all_PNG_contexts
vector<PNG_context *> all_PNG_contexts static
all PNG_contexts (= all open windows) for ⎕PNG
Definition at line 117 of file Quad_PNG.cc.
Referenced by Quad_PNG::display_PNG_main(), gtk_main_wrapper(), PNG_draw_callback(), PNG_plot_destroyed(), and Quad_PNG::window_control().
plot_window_count
int plot_window_count = 0 static
the number of open plot windows (to see when the last one was closed).
Definition at line 66 of file Quad_PNG.cc.
Referenced by gtk_main_wrapper().
verbosity
int verbosity = SHOW_NONE
(Debug-) verbosity of ⎕PNG
Definition at line 60 of file Quad_PNG.cc.
Referenced by gtk_main_wrapper(), PNG_draw_callback(), and PNG_plot_destroyed().