GNUAPL: src/Regexp.cc File Reference
Regexp.cc File Reference
#include "Workspace.hh"
#include "Regexp.hh"
Functions
static const PCRE2_UCHAR32 * ucs_to_codepoints (const UCS_string &string)
Function Documentation
ucs_to_codepoints()
static const PCRE2_UCHAR32* ucs_to_codepoints (const UCS_string & string) static
Definition at line 26 of file Regexp.cc.
References i, UCS_string::iterator::more(), and UCS_string::iterator::next().
Referenced by Regexp::Regexp().