var ScalarFunction_8hh =
[
    [ "ScalarFunction", "classScalarFunction.html", "classScalarFunction" ],
    [ "Bif_F12_BINOM", "classBif__F12__BINOM.html", "classBif__F12__BINOM" ],
    [ "Bif_F2_LESS", "classBif__F2__LESS.html", "classBif__F2__LESS" ],
    [ "Bif_F2_EQUAL", "classBif__F2__EQUAL.html", "classBif__F2__EQUAL" ],
    [ "Bif_F2_EQUAL_B", "classBif__F2__EQUAL__B.html", "classBif__F2__EQUAL__B" ],
    [ "Bif_F2_UNEQ_B", "classBif__F2__UNEQ__B.html", "classBif__F2__UNEQ__B" ],
    [ "Bif_F2_GREATER", "classBif__F2__GREATER.html", "classBif__F2__GREATER" ],
    [ "Bif_F2_AND", "classBif__F2__AND.html", "classBif__F2__AND" ],
    [ "Bif_F2_AND_B", "classBif__F2__AND__B.html", "classBif__F2__AND__B" ],
    [ "Bif_F2_OR", "classBif__F2__OR.html", "classBif__F2__OR" ],
    [ "Bif_F2_OR_B", "classBif__F2__OR__B.html", "classBif__F2__OR__B" ],
    [ "Bif_F2_LEQU", "classBif__F2__LEQU.html", "classBif__F2__LEQU" ],
    [ "Bif_F2_MEQU", "classBif__F2__MEQU.html", "classBif__F2__MEQU" ],
    [ "Bif_F2_UNEQU", "classBif__F2__UNEQU.html", "classBif__F2__UNEQU" ],
    [ "Bif_F2_FIND", "classBif__F2__FIND.html", "classBif__F2__FIND" ],
    [ "Bif_F2_NOR", "classBif__F2__NOR.html", "classBif__F2__NOR" ],
    [ "Bif_F2_NOR_B", "classBif__F2__NOR__B.html", "classBif__F2__NOR__B" ],
    [ "Bif_F2_NAND", "classBif__F2__NAND.html", "classBif__F2__NAND" ],
    [ "Bif_F2_NAND_B", "classBif__F2__NAND__B.html", "classBif__F2__NAND__B" ],
    [ "Bif_F12_POWER", "classBif__F12__POWER.html", "classBif__F12__POWER" ],
    [ "Bif_F12_PLUS", "classBif__F12__PLUS.html", "classBif__F12__PLUS" ],
    [ "Bif_F12_MINUS", "classBif__F12__MINUS.html", "classBif__F12__MINUS" ],
    [ "Bif_F12_ROLL", "classBif__F12__ROLL.html", "classBif__F12__ROLL" ],
    [ "Bif_F12_WITHOUT", "classBif__F12__WITHOUT.html", "classBif__F12__WITHOUT" ],
    [ "Bif_F12_TIMES", "classBif__F12__TIMES.html", "classBif__F12__TIMES" ],
    [ "Bif_F12_DIVIDE", "classBif__F12__DIVIDE.html", "classBif__F12__DIVIDE" ],
    [ "Bif_F12_CIRCLE", "classBif__F12__CIRCLE.html", "classBif__F12__CIRCLE" ],
    [ "Bif_F12_RND_UP", "classBif__F12__RND__UP.html", "classBif__F12__RND__UP" ],
    [ "Bif_F12_RND_DN", "classBif__F12__RND__DN.html", "classBif__F12__RND__DN" ],
    [ "Bif_F12_STILE", "classBif__F12__STILE.html", "classBif__F12__STILE" ],
    [ "Bif_F12_LOGA", "classBif__F12__LOGA.html", "classBif__F12__LOGA" ],
    [ "PERF_A", "ScalarFunction_8hh.html#ad9406362278205d7c499555b0a4c6be2", null ],
    [ "PERF_AB", "ScalarFunction_8hh.html#ac6cf92f323320007e038c6b1bf90e28d", null ],
    [ "PERF_B", "ScalarFunction_8hh.html#a251ae94639628801943313a7d95d3b88", null ]
];