GNU APL: Format_sub Struct Reference
Format_sub Struct Reference
A helper for Bif_F12_FORMAT (sizes of the fields in a number)
#include <Bif_F12_FORMAT.hh>
Public Member Functions
int size () const
return the number of characters in format
int map_field (int type)
set flt_mask according to the digits in member format return the number of digits from '1' to '4' (including)
ostream & print (ostream &out) const
a debug function for printing this Format_sub
bool no_float () const
return true iff format contains a '4' (i.e. counteract the effect of 1, 2, or 3) or none of 1 (float if negative), 2 (float if positive), or 3 (always float) was given
bool do_float (bool value_is_negative) const
return true if the decorator is floating floating
Unicode pad_char (Unicode qfc) const
return the pad character (default: space, otherwise controlled by ⎕FC)
UCS_string insert_int_commas (const UCS_string &data, bool &overflow) const
Fill buf at position x,y with data according to fmt.
UCS_string insert_fract_commas (const UCS_string &data) const
Fill buf at position x,y with data according to fmt.
Public Attributes
UCS_string format
the format ('0'...'9' and comma)
int out_len
the length in the output
uint32_t flt_mask
decorator floating mode
int min_len
the minimum length in the output
Detailed Description
A helper for Bif_F12_FORMAT (sizes of the fields in a number)
A helper struct for Bif_F12_FORMAT It represents a sub-field (int part, fract part, or exponent) of the format field
Definition at line 33 of file Bif_F12_FORMAT.hh.
Constructor & Destructor Documentation
Format_sub()
Format_sub::Format_sub () inline
Definition at line 35 of file Bif_F12_FORMAT.hh.
Member Function Documentation
do_float()
bool Format_sub::do_float (bool value_is_negative) const inline
return true if the decorator is floating floating
Definition at line 66 of file Bif_F12_FORMAT.hh.
References flt_mask.
insert_fract_commas()
UCS_string Format_sub::insert_fract_commas (const UCS_string & data) const
Fill buf at position x,y with data according to fmt.
Definition at line 891 of file Bif_F12_FORMAT.cc.
References UCS_string::all_zeroes(), UCS_string::append(), flt_mask, format, Workspace::get_FC(), Avec::is_digit(), and UCS_string::size().
insert_int_commas()
UCS_string Format_sub::insert_int_commas (const UCS_string & data, bool & overflow) const
Fill buf at position x,y with data according to fmt.
Definition at line 814 of file Bif_F12_FORMAT.cc.
References UCS_string::all_zeroes(), UCS_string::append(), flt_mask, format, Workspace::get_FC(), Avec::is_digit(), UCS_string::reverse(), and UCS_string::size().
map_field()
int Format_sub::map_field (int type)
set flt_mask according to the digits in member format return the number of digits from '1' to '4' (including)
Definition at line 649 of file Bif_F12_FORMAT.cc.
References flt_mask, format, min_len, and UCS_string::size().
Referenced by Bif_F12_FORMAT::Format_LIFER::Format_LIFER().
no_float()
bool Format_sub::no_float () const inline
return true iff format contains a '4' (i.e. counteract the effect of 1, 2, or 3) or none of 1 (float if negative), 2 (float if positive), or 3 (always float) was given
Definition at line 60 of file Bif_F12_FORMAT.hh.
References flt_mask.
pad_char()
Unicode Format_sub::pad_char (Unicode qfc) const inline
return the pad character (default: space, otherwise controlled by ⎕FC)
Definition at line 73 of file Bif_F12_FORMAT.hh.
References flt_mask.
print()
ostream & Format_sub::print (ostream & out) const
a debug function for printing this Format_sub
Definition at line 688 of file Bif_F12_FORMAT.cc.
References flt_mask, format, min_len, and out_len.
size()
int Format_sub::size () const inline
return the number of characters in format
Definition at line 47 of file Bif_F12_FORMAT.hh.
References format, and UCS_string::size().
Referenced by Bif_F12_FORMAT::Format_LIFER::fill_data_fields(), Bif_F12_FORMAT::Format_LIFER::Format_LIFER(), and Bif_F12_FORMAT::Format_LIFER::format_size().
Member Data Documentation
flt_mask
uint32_t Format_sub::flt_mask
decorator floating mode
Definition at line 43 of file Bif_F12_FORMAT.hh.
Referenced by do_float(), Bif_F12_FORMAT::Format_LIFER::Format_LIFER(), insert_fract_commas(), insert_int_commas(), map_field(), no_float(), pad_char(), and print().
format
UCS_string Format_sub::format
the format ('0'...'9' and comma)
Definition at line 41 of file Bif_F12_FORMAT.hh.
Referenced by Bif_F12_FORMAT::Format_LIFER::Format_LIFER(), insert_fract_commas(), insert_int_commas(), map_field(), print(), and size().
min_len
int Format_sub::min_len
the minimum length in the output
Definition at line 44 of file Bif_F12_FORMAT.hh.
Referenced by Bif_F12_FORMAT::Format_LIFER::fill_data_fields(), map_field(), and print().
out_len
int Format_sub::out_len
the length in the output
Definition at line 42 of file Bif_F12_FORMAT.hh.
Referenced by Bif_F12_FORMAT::Format_LIFER::fill_data_fields(), Bif_F12_FORMAT::Format_LIFER::format_example(), Bif_F12_FORMAT::Format_LIFER::Format_LIFER(), Bif_F12_FORMAT::Format_LIFER::out_size(), and print().
The documentation for this struct was generated from the following files:
src/Bif_F12_FORMAT.hh
src/Bif_F12_FORMAT.cc