GNU APL: CollatingCacheEntry Struct Reference
CollatingCacheEntry Struct Reference
One item in a CollatingCache.
#include <Bif_F12_SORT.hh>
Public Member Functions
CollatingCacheEntry ()
constructor: an invalid entry (for allocatingi vector<CollatingCacheEntry> items)
CollatingCacheEntry (Unicode uni, const Shape &shape_A)
constructor: an entry with character c and shape shape
void operator= (const CollatingCacheEntry &other)
assignment (to allow const ce_char)
int compare_axis (const CollatingCacheEntry &other, sAxis axis) const
compare this entry with other at axis
Static Public Member Functions
static int compare_chars (const Unicode &key, const CollatingCacheEntry &entry, const void *unused_ctx)
compare key with entry (for Heapsort::search())
Public Attributes
const Unicode ce_char
the character
Shape ce_shape
the shape
Detailed Description
One item in a CollatingCache.
one item of a CollatingCache. Every character in A (of A⍋B or A⍒B gets one CollatingCacheEntry; if the same character occurs multiple times in A, then the first one (in row-major order) creates the entry and the remaining copies of the character use the same CollatingCacheEntry.
Later on, f two Unicodes c1 and c2 shall be compared, then the ce_shapes (which are actually indices into A) of the CollatingCacheEntry for c1 and c2 are used for the comparison and the lowest dimansion wins.
Definition at line 44 of file Bif_F12_SORT.hh.
Constructor & Destructor Documentation
CollatingCacheEntry() [1/2]
CollatingCacheEntry::CollatingCacheEntry () inline
constructor: an invalid entry (for allocatingi vector<CollatingCacheEntry> items)
Definition at line 48 of file Bif_F12_SORT.hh.
Referenced by operator=().
CollatingCacheEntry() [2/2]
CollatingCacheEntry::CollatingCacheEntry (Unicode uni, const Shape & shape_A) inline
constructor: an entry with character c and shape shape
Definition at line 54 of file Bif_F12_SORT.hh.
Member Function Documentation
compare_axis()
int CollatingCacheEntry::compare_axis (const CollatingCacheEntry & other, sAxis axis) const inline
compare this entry with other at axis
Definition at line 70 of file Bif_F12_SORT.hh.
References ce_shape, and Shape::get_shape_item().
compare_chars()
static int CollatingCacheEntry::compare_chars (const Unicode & key, const CollatingCacheEntry & entry, const void * unused_ctx) inline static
compare key with entry (for Heapsort::search())
Definition at line 77 of file Bif_F12_SORT.hh.
References ce_char.
Referenced by CollatingCache::find_entry().
operator=()
void CollatingCacheEntry::operator= (const CollatingCacheEntry & other) inline
assignment (to allow const ce_char)
Definition at line 66 of file Bif_F12_SORT.hh.
References CollatingCacheEntry().
Member Data Documentation
ce_char
const Unicode CollatingCacheEntry::ce_char
the character
Definition at line 60 of file Bif_F12_SORT.hh.
Referenced by compare_chars().
ce_shape
Shape CollatingCacheEntry::ce_shape
the shape
Definition at line 63 of file Bif_F12_SORT.hh.
Referenced by CollatingCache::CollatingCache(), and compare_axis().
The documentation for this struct was generated from the following file:
src/Bif_F12_SORT.hh