GNU APL: Nabla::FunLine Struct Reference
Nabla::FunLine Struct Reference
a line label and program text, e.g. [1.1] TEXT←TEXT
#include <Nabla.hh>
Public Member Functions
FunLine ()
empty constructor
FunLine (LineLabel lab, const UCS_string &tx)
constructor
void print (ostream &out) const
print the line
UCS_string get_label_and_text () const
return the line label (sucah as [1]) and the line text
Public Attributes
LineLabel label
the label (like [1.2] of the line
UCS_string text
the function text of the line
bool stop_flag
true if the line has a stop flag (existing function with ∆S)
bool trace_flag
true if the line has a trace flag (existing function with ∆T)
Detailed Description
a line label and program text, e.g. [1.1] TEXT←TEXT
Definition at line 105 of file Nabla.hh.
Constructor & Destructor Documentation
FunLine() [1/2]
Nabla::FunLine::FunLine () inline
empty constructor
Definition at line 108 of file Nabla.hh.
FunLine() [2/2]
Nabla::FunLine::FunLine (LineLabel lab, const UCS_string & tx) inline
constructor
Definition at line 114 of file Nabla.hh.
Member Function Documentation
get_label_and_text()
UCS_string Nabla::FunLine::get_label_and_text () const
return the line label (sucah as [1]) and the line text
Definition at line 1033 of file Nabla.cc.
References UCS_string::append(), label, LineLabel::print_prompt(), and text.
Referenced by Nabla::get_label_and_text().
print()
void Nabla::FunLine::print (ostream & out) const
print the line
Definition at line 947 of file Nabla.cc.
References UCS_string::is_comment_or_label(), label, LineLabel::print(), and text.
Member Data Documentation
label
LineLabel Nabla::FunLine::label
the label (like [1.2] of the line
Definition at line 128 of file Nabla.hh.
Referenced by get_label_and_text(), Nabla::get_label_and_text(), and print().
stop_flag
bool Nabla::FunLine::stop_flag
true if the line has a stop flag (existing function with ∆S)
Definition at line 134 of file Nabla.hh.
Referenced by Nabla::open_existing_function().
text
UCS_string Nabla::FunLine::text
the function text of the line
Definition at line 131 of file Nabla.hh.
Referenced by get_label_and_text(), and print().
trace_flag
bool Nabla::FunLine::trace_flag
true if the line has a trace flag (existing function with ∆T)
Definition at line 137 of file Nabla.hh.
Referenced by Nabla::open_existing_function().
The documentation for this struct was generated from the following files:
src/Nabla.hh
src/Nabla.cc