GNU APL: Command::transfer_context Struct Reference
Command::transfer_context Struct Reference
a helper struct for the)IN command
#include <Command.hh>
Public Member Functions
transfer_context (bool prot)
constructor
void process_record (const UTF8 *record, const UCS_string_vector &objects)
process one record of a workspace file
uint32_t get_nrs (UCS_string &name, Shape &shape) const
get the name, rank, and shape of a 1 ⎕TF record
void array_2TF (const UCS_string_vector &objects) const
process a 'A' (array in 2 ⎕TF format) item.
void chars_1TF (const UCS_string_vector &objects) const
process a 'C' (character, in 1 ⎕TF format) item.
void function_2TF (const UCS_string_vector &objects) const
process an 'F' (function in 2 ⎕TF format) item.
void numeric_1TF (const UCS_string_vector &objects) const
process an 'N' (numeric in 1 ⎕TF format) item.
void add (const UTF8 *str, int len)
add len UTF8 bytes to this transfer_context
Public Attributes
bool new_record
true if a new record has started
bool is_ebcdic
true if record is EBCDIC (not yet supported)
int recnum
the record number
int item_type
the record type ('A', 'C', 'N', or 'F')
APL_time_us timestamp
the last timestamp (if any)
bool protection
true if)IN shall not iverride existing objects
UCS_string data
accumulator for data of different records
Detailed Description
a helper struct for the)IN command
Definition at line 235 of file Command.hh.
Constructor & Destructor Documentation
transfer_context()
Command::transfer_context::transfer_context (bool prot) inline
constructor
Definition at line 238 of file Command.hh.
Member Function Documentation
add()
void Command::transfer_context::add (const UTF8 * str, int len)
add len UTF8 bytes to this transfer_context
Definition at line 2614 of file Command.cc.
References Avec::IBM_quad_AV(), and Avec::print_inverse_IBM_quad_AV().
Referenced by process_record().
array_2TF()
void Command::transfer_context::array_2TF (const UCS_string_vector & objects) const
process a 'A' (array in 2 ⎕TF format) item.
Definition at line 2539 of file Command.cc.
References UCS_string::append(), UCS_string_vector::contains(), UCS_string::size(), and Quad_TF::tf2_inverse().
Referenced by process_record().
chars_1TF()
void Command::transfer_context::chars_1TF (const UCS_string_vector & objects) const
process a 'C' (character, in 1 ⎕TF format) item.
Definition at line 2484 of file Command.cc.
References Symbol::assign(), UCS_string_vector::contains(), Workspace::get_quad(), Token::get_sym_ptr(), Token::get_ValueType(), Avec::is_quad(), and Workspace::lookup_symbol().
Referenced by process_record().
function_2TF()
void Command::transfer_context::function_2TF (const UCS_string_vector & objects) const
process an 'F' (function in 2 ⎕TF format) item.
chars 1...' ' are the function name
Definition at line 2570 of file Command.cc.
References UCS_string::append(), UCS_string_vector::contains(), YMDhmsu::day, Symbol::get_function(), YMDhmsu::hour, Workspace::lookup_existing_symbol(), YMDhmsu::micro, YMDhmsu::minute, YMDhmsu::month, YMDhmsu::second, Function::set_creation_time(), UCS_string::size(), Quad_TF::tf2_inverse(), and YMDhmsu::year.
Referenced by process_record().
get_nrs()
uint32_t Command::transfer_context::get_nrs (UCS_string & name, Shape & shape) const
get the name, rank, and shape of a 1 ⎕TF record
Definition at line 2387 of file Command.cc.
References Shape::add_shape_item(), and UCS_string::append().
numeric_1TF()
void Command::transfer_context::numeric_1TF (const UCS_string_vector & objects) const
process an 'N' (numeric in 1 ⎕TF format) item.
Definition at line 2425 of file Command.cc.
References Symbol::assign(), UCS_string_vector::contains(), Token::get_cpx_imag(), Token::get_cpx_real(), Token::get_flt_val(), Token::get_int_val(), Workspace::get_quad(), Shape::get_rank(), Token::get_sym_ptr(), Token::get_tag(), Token::get_ValueType(), Shape::get_volume(), Avec::is_quad(), Workspace::lookup_symbol(), and Tokenizer::tokenize().
Referenced by process_record().
process_record()
void Command::transfer_context::process_record (const UTF8 * record, const UCS_string_vector & objects)
process one record of a workspace file
Definition at line 2308 of file Command.cc.
References add(), array_2TF(), chars_1TF(), data, YMDhmsu::day, function_2TF(), YMDhmsu::get(), YMDhmsu::hour, item_type, YMDhmsu::micro, YMDhmsu::minute, YMDhmsu::month, new_record, numeric_1TF(), recnum, YMDhmsu::second, timestamp, and YMDhmsu::year.
Referenced by Command::cmd_IN().
Member Data Documentation
data
UCS_string Command::transfer_context::data
accumulator for data of different records
Definition at line 286 of file Command.hh.
Referenced by process_record().
is_ebcdic
bool Command::transfer_context::is_ebcdic
true if record is EBCDIC (not yet supported)
Definition at line 271 of file Command.hh.
Referenced by Command::cmd_IN().
item_type
int Command::transfer_context::item_type
the record type ('A', 'C', 'N', or 'F')
Definition at line 277 of file Command.hh.
Referenced by process_record().
new_record
bool Command::transfer_context::new_record
true if a new record has started
Definition at line 268 of file Command.hh.
Referenced by process_record().
protection
bool Command::transfer_context::protection
true if)IN shall not iverride existing objects
Definition at line 283 of file Command.hh.
recnum
int Command::transfer_context::recnum
the record number
Definition at line 274 of file Command.hh.
Referenced by Command::cmd_IN(), and process_record().
timestamp
APL_time_us Command::transfer_context::timestamp
the last timestamp (if any)
Definition at line 280 of file Command.hh.
Referenced by process_record().
The documentation for this struct was generated from the following files:
src/Command.hh
src/Command.cc