GNU APL: XML_Saving_Archive::_val_par Struct Reference
XML_Saving_Archive::_val_par Struct Reference
a value and its parent (if the parent is nested)
#include <Archive.hh>
Public Member Functions
_val_par ()
default constructor
_val_par (const Value *v, Vid par)
constructor
void operator= (const _val_par &other)
assign other
Static Public Member Functions
static bool compare_val_par (const _val_par &A, const _val_par &B, const void *)
compare function for Heapsort::sort()
static int compare_val_par1 (const void *key, const void *B)
compare function for bsearch()
Public Attributes
const Value * _val
the value
Vid _par
the optional parent
Detailed Description
a value and its parent (if the parent is nested)
Definition at line 138 of file Archive.hh.
Constructor & Destructor Documentation
_val_par() [1/2]
XML_Saving_Archive::_val_par::_val_par () inline
default constructor
Definition at line 141 of file Archive.hh.
Referenced by operator=().
_val_par() [2/2]
XML_Saving_Archive::_val_par::_val_par (const Value * v, Vid par) inline
constructor
Definition at line 147 of file Archive.hh.
Member Function Documentation
compare_val_par()
bool XML_Saving_Archive::_val_par::compare_val_par (const _val_par & A, const _val_par & B, const void *) static
compare function for Heapsort::sort()
Definition at line 814 of file Archive.cc.
Referenced by XML_Saving_Archive::save().
compare_val_par1()
int XML_Saving_Archive::_val_par::compare_val_par1 (const void * key, const void * B) static
compare function for bsearch()
Definition at line 821 of file Archive.cc.
Referenced by XML_Saving_Archive::find_vid().
operator=()
void XML_Saving_Archive::_val_par::operator= (const _val_par & other) inline
assign other
Definition at line 159 of file Archive.hh.
References _par, _val, and _val_par().
Member Data Documentation
_par
Vid XML_Saving_Archive::_val_par::_par
the optional parent
Definition at line 156 of file Archive.hh.
Referenced by operator=(), XML_Saving_Archive::save(), and XML_Saving_Archive::save_shape().
_val
const Value* XML_Saving_Archive::_val_par::_val
the value
Definition at line 153 of file Archive.hh.
Referenced by operator=(), XML_Saving_Archive::save(), XML_Saving_Archive::save_Ravel(), and XML_Saving_Archive::save_shape().
The documentation for this struct was generated from the following files:
src/Archive.hh
src/Archive.cc