GNU APL: Bif_F12_FORMAT::Format_LIFER Struct Reference
Bif_F12_FORMAT::Format_LIFER Struct Reference
An entire format field (LIFER = Left-Int-Fract-Expo-Right.
#include <Bif_F12_FORMAT.hh>
Public Member Functions
Format_LIFER ()
empty constructor
Format_LIFER (UCS_string fmt)
constructor
int format_size () const
return the size of the format
int out_size () const
return the size of the output
UCS_string format_example (APL_Float value)
format value by example
UCS_string format_left_side (const UCS_string data_int, bool negative, bool &overflow)
format the left decorator and integer part (everything left of the decimal dot)
UCS_string format_right_side (const UCS_string data_fract, bool negative, const UCS_string data_expo)
format the fract part, exponent, and right decorator (everything left of the decimal dot)
void fill_data_fields (APL_Float value, UCS_string &data_int, UCS_string &data_fract, UCS_string &data_expo, bool &overflow)
Print value into int, fract, and expo fields.
Public Attributes
Format_sub left_deco
the left decorator
Format_sub int_part
the integer part
Format_sub fract_part
the fractional part
Format_sub expo_deco
the exponent decorator
Format_sub exponent
the exponent
Format_sub right_deco
the left decorator
Unicode exponent_char
the exponent char to be used
bool expo_negative
true if the exponent is negative
Detailed Description
An entire format field (LIFER = Left-Int-Fract-Expo-Right.
Definition at line 105 of file Bif_F12_FORMAT.hh.
Constructor & Destructor Documentation
Format_LIFER() [1/2]
Bif_F12_FORMAT::Format_LIFER::Format_LIFER () inline
empty constructor
Definition at line 108 of file Bif_F12_FORMAT.hh.
Format_LIFER() [2/2]
Bif_F12_FORMAT::Format_LIFER::Format_LIFER (UCS_string fmt)
constructor
the right decorator
Definition at line 502 of file Bif_F12_FORMAT.cc.
References UCS_string::append(), expo_deco, exponent, exponent_char, Format_sub::flt_mask, Format_sub::format, fract_part, int_part, Bif_F12_FORMAT::is_control_char(), left_deco, Format_sub::map_field(), Format_sub::out_len, right_deco, Format_sub::size(), and UCS_string::size().
Member Function Documentation
fill_data_fields()
void Bif_F12_FORMAT::Format_LIFER::fill_data_fields (APL_Float value, UCS_string & data_int, UCS_string & data_fract, UCS_string & data_expo, bool & overflow)
Print value into int, fract, and expo fields.
Definition at line 697 of file Bif_F12_FORMAT.cc.
References UCS_string::append(), expo_negative, exponent, fract_part, Workspace::get_FC(), int_part, Format_sub::min_len, Format_sub::out_len, Format_sub::size(), and UCS_string::size().
Referenced by format_example().
format_example()
UCS_string Bif_F12_FORMAT::Format_LIFER::format_example (APL_Float value)
format value by example
Definition at line 370 of file Bif_F12_FORMAT.cc.
References expo_deco, exponent, fill_data_fields(), format_left_side(), format_right_side(), fract_part, Workspace::get_FC(), int_part, left_deco, Format_sub::out_len, out_size(), right_deco, and UCS_string::size().
format_left_side()
UCS_string Bif_F12_FORMAT::Format_LIFER::format_left_side (const UCS_string data_int, bool negative, bool & overflow)
format the left decorator and integer part (everything left of the decimal dot)
Definition at line 400 of file Bif_F12_FORMAT.cc.
References UCS_string::append(), Workspace::get_FC(), and UCS_string::size().
Referenced by format_example().
format_right_side()
UCS_string Bif_F12_FORMAT::Format_LIFER::format_right_side (const UCS_string data_fract, bool negative, const UCS_string data_expo)
format the fract part, exponent, and right decorator (everything left of the decimal dot)
Definition at line 433 of file Bif_F12_FORMAT.cc.
References UCS_string::append(), Workspace::get_FC(), and UCS_string::size().
Referenced by format_example().
format_size()
int Bif_F12_FORMAT::Format_LIFER::format_size () const inline
return the size of the format
Definition at line 114 of file Bif_F12_FORMAT.hh.
References expo_deco, exponent, fract_part, int_part, left_deco, right_deco, and Format_sub::size().
out_size()
int Bif_F12_FORMAT::Format_LIFER::out_size () const inline
return the size of the output
Definition at line 119 of file Bif_F12_FORMAT.hh.
References expo_deco, exponent, fract_part, int_part, left_deco, Format_sub::out_len, and right_deco.
Referenced by format_example().
Member Data Documentation
expo_deco
Format_sub Bif_F12_FORMAT::Format_LIFER::expo_deco
the exponent decorator
Definition at line 144 of file Bif_F12_FORMAT.hh.
Referenced by format_example(), Format_LIFER(), format_size(), and out_size().
expo_negative
bool Bif_F12_FORMAT::Format_LIFER::expo_negative
true if the exponent is negative
Definition at line 152 of file Bif_F12_FORMAT.hh.
Referenced by fill_data_fields().
exponent
Format_sub Bif_F12_FORMAT::Format_LIFER::exponent
the exponent
Definition at line 145 of file Bif_F12_FORMAT.hh.
Referenced by fill_data_fields(), format_example(), Format_LIFER(), format_size(), and out_size().
exponent_char
Unicode Bif_F12_FORMAT::Format_LIFER::exponent_char
the exponent char to be used
Definition at line 149 of file Bif_F12_FORMAT.hh.
Referenced by Format_LIFER().
fract_part
Format_sub Bif_F12_FORMAT::Format_LIFER::fract_part
the fractional part
Definition at line 143 of file Bif_F12_FORMAT.hh.
Referenced by fill_data_fields(), format_example(), Format_LIFER(), format_size(), and out_size().
int_part
Format_sub Bif_F12_FORMAT::Format_LIFER::int_part
the integer part
Definition at line 142 of file Bif_F12_FORMAT.hh.
Referenced by fill_data_fields(), format_example(), Format_LIFER(), format_size(), and out_size().
left_deco
Format_sub Bif_F12_FORMAT::Format_LIFER::left_deco
the left decorator
Definition at line 141 of file Bif_F12_FORMAT.hh.
Referenced by format_example(), Format_LIFER(), format_size(), and out_size().
right_deco
Format_sub Bif_F12_FORMAT::Format_LIFER::right_deco
the left decorator
Definition at line 146 of file Bif_F12_FORMAT.hh.
Referenced by format_example(), Format_LIFER(), format_size(), and out_size().
The documentation for this struct was generated from the following files:
src/Bif_F12_FORMAT.hh
src/Bif_F12_FORMAT.cc