GNU APL: InputFile Struct Reference
InputFile Struct Reference
A single input file to be executed by the interpreter.
#include <InputFile.hh>
Public Member Functions
InputFile ()
empty constructor
InputFile (const UTF8_string &_filename, FILE *_file, bool _test, bool _echo, bool _is_script, LX_mode LX)
Normal constructor.
void set_COPY ()
set the from_COPY flag
void set_pushed_IE ()
set the pushed_IE flag
void set_pushed_pending (bool on_off)
set the pushed_pending flag
void set_line_no (int num)
set the current line number
void set_html (int html)
set the current HTML mode
int get_html () const
return the current HTML mode
void add_filter_object (UCS_string &object)
add object to object_filter
bool has_object_filter () const
return true if this file as an oject filter (from)COPY file names...)
bool check_filter (const UTF8_string &line)
check the current line and return true if the line is permitted by the object_filter. This function also updates in_function and in_variable
Static Public Member Functions
static InputFile * current_file ()
the current file
static const char * current_filename ()
the name of the currrent file
static int current_line_no ()
the line number of the currrent file
static void increment_current_line_no ()
increment the line number of the current file
static bool running_script ()
return true iff input comes from a script (as opposed to running interactively)
static bool is_validating ()
return true iff the current input file exists and is a test file
static bool pushed_file ()
return true iff the current input file exists and is a pushed immediate execution
static bool is_pushed_pending ()
return true iff the current input file exists and is a pushed immediate execution
static int testcase_file_count ()
the number of testcase (.tc) files
static bool echo_current_file ()
true if echo (of the input) is on for the current file
static void open_current_file ()
open current file unless already open
static void close_current_file ()
close the current file and perform some cleanup
static void randomize_files ()
randomize the order of test_file_names
Public Attributes
FILE * file
FILE * from fopen (or 0 if file is closed)
UTF8_string filename
the file name
Static Public Attributes
static std::vector< InputFile > files_todo
files that need to be processed
static std::vector< InputFile > files_orig
the initial set of files provided on the command line
Protected Attributes
bool test
true for -T testfile, false for -f APL file
bool pushed_IE
true for ]PUSHFILE child
bool pushed_pending
true for ]PUSHFILE parent
bool echo
echo stdin
bool is_script
script (override existing functions)
LX_mode with_LX
execute ⎕LX at the end
int line_no
line number in file
int in_html
0: no HTML, 1: in HTML file 2: in HTML header
UCS_string_vector object_filter
functions and vars that shoule be)COPIED
bool in_function
true if current line belongs to a function. Cleared at final ∇
bool in_variable
return true if current line belongs to a variable. Cleared by empty line
bool in_matched
true if current function or variable was mentioned in object_filter
bool from_COPY
true if this file comes from a)COPY XXX.apl (but not XXX.xml
Static Protected Attributes
static int stdin_line_no = 1
line number in stdin
Friends
class IO_Files
Detailed Description
A single input file to be executed by the interpreter.
an input file and its properties. The file can be an apl script(.apl) file or a testcase (.tc) file. The file names initially come from the command line, but can be extended by)COPY commands
Definition at line 34 of file InputFile.hh.
Constructor & Destructor Documentation
InputFile() [1/2]
InputFile::InputFile () inline
empty constructor
Definition at line 39 of file InputFile.hh.
InputFile() [2/2]
InputFile::InputFile (const UTF8_string & _filename, FILE * _file, bool _test, bool _echo, bool _is_script, LX_mode LX) inline
Normal constructor.
Definition at line 42 of file InputFile.hh.
Member Function Documentation
add_filter_object()
void InputFile::add_filter_object (UCS_string & object) inline
add object to object_filter
Definition at line 131 of file InputFile.hh.
References object_filter.
Referenced by Workspace::load_DUMP().
check_filter()
bool InputFile::check_filter (const UTF8_string & line)
check the current line and return true if the line is permitted by the object_filter. This function also updates in_function and in_variable
Definition at line 135 of file InputFile.cc.
References UCS_string::drop(), UserFunction_header::get_name(), in_function, in_matched, in_variable, Avec::is_first_symbol_char(), Avec::is_quad(), object_filter, UCS_string::remove_leading_and_trailing_whitespaces(), and UCS_string::size().
Referenced by IO_Files::read_file_line().
close_current_file()
void InputFile::close_current_file () static
close the current file and perform some cleanup
Definition at line 55 of file InputFile.cc.
References Bif_F1_EXECUTE::copy_pending, file, files_todo, and from_COPY.
Referenced by IO_Files::diff_error(), and IO_Files::end_of_current_file().
current_file()
static InputFile * InputFile::current_file () inline static
the current file
Definition at line 85 of file InputFile.hh.
References files_todo.
Referenced by IO_Files::apl_error(), IO_Files::assert_error(), IO_Files::diff_error(), IO_Files::get_file_line(), IO_Files::next_file(), IO_Files::open_next_file(), IO_Files::read_file_line(), and IO_Files::syntax_error().
current_filename()
static const char * InputFile::current_filename () inline static
the name of the currrent file
Definition at line 89 of file InputFile.hh.
References files_todo.
Referenced by Nabla::edit(), IO_Files::end_of_current_file(), open_current_file(), IO_Files::open_next_file(), and VH_entry::VH_entry().
current_line_no()
static int InputFile::current_line_no () inline static
the line number of the currrent file
Definition at line 93 of file InputFile.hh.
References files_todo, and stdin_line_no.
Referenced by IO_Files::apl_error(), IO_Files::read_file_line(), and VH_entry::VH_entry().
echo_current_file()
bool InputFile::echo_current_file () static
true if echo (of the input) is on for the current file
Definition at line 128 of file InputFile.cc.
References UserPreferences::do_not_echo, UserPreferences::echo_CIN, and files_todo.
Referenced by CinOut::overflow().
get_html()
int InputFile::get_html () const inline
return the current HTML mode
Definition at line 81 of file InputFile.hh.
References in_html.
Referenced by IO_Files::read_file_line().
has_object_filter()
bool InputFile::has_object_filter () const inline
return true if this file as an oject filter (from)COPY file names...)
Definition at line 137 of file InputFile.hh.
References object_filter.
Referenced by IO_Files::read_file_line().
increment_current_line_no()
static void InputFile::increment_current_line_no () inline static
increment the line number of the current file
Definition at line 97 of file InputFile.hh.
References files_todo, and stdin_line_no.
Referenced by InputMux::get_line().
is_pushed_pending()
static bool InputFile::is_pushed_pending () inline static
return true iff the current input file exists and is a pushed immediate execution
Definition at line 116 of file InputFile.hh.
References files_todo.
is_validating()
static bool InputFile::is_validating () inline static
return true iff the current input file exists and is a test file
Definition at line 106 of file InputFile.hh.
References files_todo.
Referenced by LineInput::edit_line(), IO_Files::end_of_current_file(), InputMux::get_line(), and DiffOut::overflow().
open_current_file()
void InputFile::open_current_file () static
open current file unless already open
Definition at line 39 of file InputFile.cc.
References current_filename(), and files_todo.
Referenced by IO_Files::open_next_file().
pushed_file()
static bool InputFile::pushed_file () inline static
return true iff the current input file exists and is a pushed immediate execution
Definition at line 111 of file InputFile.hh.
References files_todo.
Referenced by InputMux::get_line().
randomize_files()
void InputFile::randomize_files () static
randomize the order of test_file_names
Definition at line 78 of file InputFile.cc.
References UTF8_string::c_str(), filename, files_todo, and test.
Referenced by UserPreferences::parse_argv_2().
running_script()
static bool InputFile::running_script () inline static
return true iff input comes from a script (as opposed to running interactively)
Definition at line 102 of file InputFile.hh.
References files_todo.
Referenced by Nabla::edit(), Nabla::open_existing_function(), and Nabla::start().
set_COPY()
void InputFile::set_COPY () inline
set the from_COPY flag
Definition at line 61 of file InputFile.hh.
References from_COPY.
Referenced by Workspace::load_DUMP().
set_html()
void InputFile::set_html (int html) inline
set the current HTML mode
Definition at line 77 of file InputFile.hh.
References in_html.
Referenced by IO_Files::read_file_line().
set_line_no()
void InputFile::set_line_no (int num) inline
set the current line number
Definition at line 73 of file InputFile.hh.
References line_no.
set_pushed_IE()
void InputFile::set_pushed_IE () inline
set the pushed_IE flag
Definition at line 65 of file InputFile.hh.
References pushed_IE.
Referenced by Command::cmd_PUSHFILE().
set_pushed_pending()
void InputFile::set_pushed_pending (bool on_off) inline
set the pushed_pending flag
Definition at line 69 of file InputFile.hh.
References pushed_pending.
Referenced by IO_Files::open_next_file().
testcase_file_count()
static int InputFile::testcase_file_count () inline static
the number of testcase (.tc) files
Definition at line 120 of file InputFile.hh.
References files_todo, and test.
Referenced by UserPreferences::parse_argv_2().
Friends And Related Function Documentation
IO_Files
friend class IO_Files friend
Definition at line 36 of file InputFile.hh.
Member Data Documentation
echo
bool InputFile::echo protected
echo stdin
Definition at line 173 of file InputFile.hh.
Referenced by IO_Files::get_file_line().
file
FILE* InputFile::file
FILE * from fopen (or 0 if file is closed)
Definition at line 164 of file InputFile.hh.
Referenced by close_current_file(), and IO_Files::read_file_line().
filename
UTF8_string InputFile::filename
the file name
Definition at line 167 of file InputFile.hh.
Referenced by randomize_files().
files_orig
vector< InputFile > InputFile::files_orig static
the initial set of files provided on the command line
Definition at line 161 of file InputFile.hh.
Referenced by UserPreferences::parse_argv_2().
files_todo
vector< InputFile > InputFile::files_todo static
files that need to be processed
Definition at line 158 of file InputFile.hh.
Referenced by close_current_file(), Command::cmd_PUSHFILE(), current_file(), current_filename(), current_line_no(), IO_Files::diff_error(), echo_current_file(), IO_Files::end_of_current_file(), increment_current_line_no(), is_pushed_pending(), is_validating(), Workspace::load_DUMP(), open_current_file(), IO_Files::open_next_file(), UserPreferences::parse_argv_2(), pushed_file(), randomize_files(), running_script(), and testcase_file_count().
from_COPY
bool InputFile::from_COPY protected
true if this file comes from a)COPY XXX.apl (but not XXX.xml
Definition at line 192 of file InputFile.hh.
Referenced by close_current_file(), and set_COPY().
in_function
bool InputFile::in_function protected
true if current line belongs to a function. Cleared at final ∇
Definition at line 183 of file InputFile.hh.
Referenced by check_filter().
in_html
int InputFile::in_html protected
0: no HTML, 1: in HTML file 2: in HTML header
Definition at line 177 of file InputFile.hh.
Referenced by get_html(), and set_html().
in_matched
bool InputFile::in_matched protected
true if current function or variable was mentioned in object_filter
Definition at line 189 of file InputFile.hh.
Referenced by check_filter().
in_variable
bool InputFile::in_variable protected
return true if current line belongs to a variable. Cleared by empty line
Definition at line 186 of file InputFile.hh.
Referenced by check_filter().
is_script
bool InputFile::is_script protected
script (override existing functions)
Definition at line 174 of file InputFile.hh.
line_no
int InputFile::line_no protected
line number in file
Definition at line 176 of file InputFile.hh.
Referenced by set_line_no().
object_filter
UCS_string_vector InputFile::object_filter protected
functions and vars that shoule be)COPIED
Definition at line 180 of file InputFile.hh.
Referenced by add_filter_object(), check_filter(), and has_object_filter().
pushed_IE
bool InputFile::pushed_IE protected
true for ]PUSHFILE child
Definition at line 171 of file InputFile.hh.
Referenced by set_pushed_IE().
pushed_pending
bool InputFile::pushed_pending protected
true for ]PUSHFILE parent
Definition at line 172 of file InputFile.hh.
Referenced by set_pushed_pending().
stdin_line_no
int InputFile::stdin_line_no = 1 static protected
line number in stdin
Definition at line 195 of file InputFile.hh.
Referenced by current_line_no(), and increment_current_line_no().
test
bool InputFile::test protected
true for -T testfile, false for -f APL file
Definition at line 170 of file InputFile.hh.
Referenced by randomize_files(), and testcase_file_count().
with_LX
LX_mode InputFile::with_LX protected
execute ⎕LX at the end
Definition at line 175 of file InputFile.hh.
Referenced by IO_Files::get_file_line().
The documentation for this struct was generated from the following files:
src/InputFile.hh
src/InputFile.cc