GNU APL: Svar_record Struct Reference
Svar_record Struct Reference
one shared variable.
#include <Svar_record.hh>
Public Member Functions
bool valid () const
true if this is a valid entry.
void clear ()
invalidate this entry
void remove_accepting ()
remove accepting partner
void remove_offering ()
remove offering partner
SV_Coupling retract ()
retract the offer made by the calling ID.
bool is_ws_to_ws () const
return true iff this is a variable shared between APL interpreters as opposed to shared with an AP.
void bad_proc (const char *function, const AP_num3 &ap) const
complain about proc
bool match_name (const uint32_t *UCS_other) const
return true if UCS_other matches varname (could be a wildcard match)
SV_Coupling get_coupling () const
return the coupling of the variable
Svar_Control get_control () const
return the control bits of this variable
void set_control (Svar_Control ctl)
set the control bits of this variable
Svar_state get_state () const
return the state of this variable
const uint32_t * get_svar_name () const
return the name of the variable, or 0 if fetching it has failed
void set_state (bool used, const char *loc)
update the state when using or setting this variable, and clear events
bool may_use (int attempt)
return true iff the calling partner may use the current value
bool may_set (int attempt)
return true iff the calling partner may set the current value
void print (ostream &out) const
print the variable
ostream & print_name (ostream &out) const
print the name of this variable
Static Public Member Functions
static ostream & print_name (ostream &out, const uint32_t *name, int len=MAX_SVAR_NAMELEN)
print a name
Public Attributes
SV_key key
a key that uniquely identifies this variable
uint32_t varname [MAX_SVAR_NAMELEN+1]
name of the offered variable (UCS), 0-terminated
Svar_partner offering
the partner that has offered the variable first
Svar_partner accepting
the partner that has accepted the offer from offering
Svar_state state
state of this variable
Detailed Description
one shared variable.
Definition at line 184 of file Svar_record.hh.
Member Function Documentation
bad_proc()
void Svar_record::bad_proc (const char * function, const AP_num3 & ap) const
complain about proc
Definition at line 356 of file Svar_record.cc.
References accepting, Svar_partner::id, and offering.
Referenced by may_set(), may_use(), retract(), set_control(), and set_state().
clear()
void Svar_record::clear () inline
invalidate this entry
Definition at line 193 of file Svar_record.hh.
References accepting, Svar_partner::clear(), key, offering, state, and varname.
Referenced by retract(), and Svar_record_P::Svar_record_P().
get_control()
Svar_Control Svar_record::get_control () const
return the control bits of this variable
Definition at line 165 of file Svar_record.cc.
References accepting, Svar_partner::get_control(), ProcessorID::get_id(), Svar_partner::id, and offering.
get_coupling()
SV_Coupling Svar_record::get_coupling () const inline
return the coupling of the variable
Definition at line 222 of file Svar_record.hh.
References accepting, Svar_partner::is_active(), and offering.
Referenced by Quad_SVO::eval_AB(), Quad_SVO::eval_B(), is_ws_to_ws(), print(), retract(), set_control(), Quad_SVO::share_one_variable(), Symbol::unshare_var(), and valid().
get_state()
Svar_state Svar_record::get_state () const
return the state of this variable
Definition at line 204 of file Svar_record.cc.
References state.
Referenced by Quad_SVS::eval_B(), and print().
get_svar_name()
const uint32_t * Svar_record::get_svar_name () const inline
return the name of the variable, or 0 if fetching it has failed
Definition at line 238 of file Svar_record.hh.
References varname.
Referenced by Symbol::assign_shared_variable(), and Symbol::resolve_shared_variable().
is_ws_to_ws()
bool Svar_record::is_ws_to_ws () const
return true iff this is a variable shared between APL interpreters as opposed to shared with an AP.
Definition at line 125 of file Svar_record.cc.
References accepting, get_coupling(), Svar_partner::id, and offering.
Referenced by Symbol::assign_shared_variable(), and Symbol::resolve_shared_variable().
match_name()
bool Svar_record::match_name (const uint32_t * UCS_other) const
return true if UCS_other matches varname (could be a wildcard match)
Definition at line 134 of file Svar_record.cc.
References varname.
may_set()
bool Svar_record::may_set (int attempt)
return true iff the calling partner may set the current value
Definition at line 320 of file Svar_record.cc.
References accepting, bad_proc(), Svar_partner::events, Svar_partner::get_control(), ProcessorID::get_id(), Svar_partner::id, Svar_partner::is_active(), offering, and state.
may_use()
bool Svar_record::may_use (int attempt)
return true iff the calling partner may use the current value
Definition at line 284 of file Svar_record.cc.
References accepting, bad_proc(), Svar_partner::events, Svar_partner::get_control(), ProcessorID::get_id(), Svar_partner::id, Svar_partner::is_active(), offering, and state.
print()
void Svar_record::print (ostream & out) const
print the variable
Definition at line 364 of file Svar_record.cc.
References accepting, get_coupling(), get_state(), key, offering, Svar_partner::print(), print_name(), and varname.
print_name() [1/2]
ostream & Svar_record::print_name (ostream & out) const inline
print the name of this variable
Definition at line 258 of file Svar_record.hh.
References print_name(), and varname.
print_name() [2/2]
ostream & Svar_record::print_name (ostream & out, const uint32_t * name, int len = MAX_SVAR_NAMELEN) static
print a name
Definition at line 378 of file Svar_record.cc.
Referenced by print(), print_name(), set_control(), and set_state().
remove_accepting()
void Svar_record::remove_accepting ()
remove accepting partner
Definition at line 85 of file Svar_record.cc.
References accepting, and Svar_partner::clear().
Referenced by retract().
remove_offering()
void Svar_record::remove_offering ()
remove offering partner
Definition at line 91 of file Svar_record.cc.
References accepting, Svar_partner::clear(), Svar_partner::id, and offering.
Referenced by retract().
retract()
SV_Coupling Svar_record::retract ()
retract the offer made by the calling ID.
Definition at line 101 of file Svar_record.cc.
References accepting, bad_proc(), clear(), get_coupling(), ProcessorID::get_id(), Svar_partner::id, offering, remove_accepting(), and remove_offering().
set_control()
void Svar_record::set_control (Svar_Control ctl)
set the control bits of this variable
Definition at line 174 of file Svar_record.cc.
References accepting, bad_proc(), Svar_partner::events, get_coupling(), ProcessorID::get_id(), Svar_partner::id, offering, print_name(), and Svar_partner::set_control().
set_state()
void Svar_record::set_state (bool used, const char * loc)
update the state when using or setting this variable, and clear events
Definition at line 210 of file Svar_record.cc.
References accepting, bad_proc(), Svar_partner::events, Svar_partner::get_control(), ProcessorID::get_id(), Svar_partner::id, offering, print_name(), and state.
valid()
bool Svar_record::valid () const inline
true if this is a valid entry.
Definition at line 190 of file Svar_record.hh.
References get_coupling().
Member Data Documentation
accepting
Svar_partner Svar_record::accepting
the partner that has accepted the offer from offering
Definition at line 268 of file Svar_record.hh.
Referenced by bad_proc(), clear(), get_control(), get_coupling(), is_ws_to_ws(), may_set(), may_use(), print(), remove_accepting(), remove_offering(), retract(), set_control(), and set_state().
key
SV_key Svar_record::key
a key that uniquely identifies this variable
Definition at line 187 of file Svar_record.hh.
Referenced by clear(), and print().
offering
Svar_partner Svar_record::offering
the partner that has offered the variable first
Definition at line 265 of file Svar_record.hh.
Referenced by bad_proc(), clear(), get_control(), get_coupling(), is_ws_to_ws(), may_set(), may_use(), print(), remove_offering(), retract(), set_control(), and set_state().
state
Svar_state Svar_record::state
state of this variable
Definition at line 271 of file Svar_record.hh.
Referenced by clear(), get_state(), may_set(), may_use(), and set_state().
varname
uint32_t Svar_record::varname[MAX_SVAR_NAMELEN+1]
name of the offered variable (UCS), 0-terminated
Definition at line 262 of file Svar_record.hh.
Referenced by clear(), get_svar_name(), match_name(), print(), and print_name().
The documentation for this struct was generated from the following files:
src/Svar_record.hh
src/Svar_record.cc