GNU APL: LineLabel Struct Reference
LineLabel Struct Reference
a line number like 1.2 while editing
#include <Nabla.hh>
Public Member Functions
LineLabel ()
empty constuctor
LineLabel (int mj)
constuctor: line mj
void print (ostream &out) const
print the line number
UCS_string print_prompt (int min_size) const
print a prompt like [1.2] into buffer
bool operator== (const LineLabel &other) const
true iff two line numbers are equal
bool operator< (const LineLabel &other) const
true iff this line number is smaller than other
bool valid () const
true if tis line number is valid (i.e. the line exists)
void clear ()
invalidate the line number
bool is_header_line_number () const
return true iff this line number is the header line [0]
void next ()
increase the line number
void insert ()
increase the line number
Public Attributes
int ln_major
the integer part of the line number
UCS_string ln_minor
the fractional part of the line number
Detailed Description
a line number like 1.2 while editing
Definition at line 30 of file Nabla.hh.
Constructor & Destructor Documentation
LineLabel() [1/2]
LineLabel::LineLabel () inline
empty constuctor
Definition at line 33 of file Nabla.hh.
LineLabel() [2/2]
LineLabel::LineLabel (int mj) inline
constuctor: line mj
Definition at line 38 of file Nabla.hh.
Member Function Documentation
clear()
void LineLabel::clear () inline
invalidate the line number
Definition at line 59 of file Nabla.hh.
References ln_major, and ln_minor.
Referenced by Nabla::parse_oper().
insert()
void LineLabel::insert ()
increase the line number
Definition at line 1007 of file Nabla.cc.
References UCS_string::append(), and ln_minor.
Referenced by Nabla::execute_show().
is_header_line_number()
bool LineLabel::is_header_line_number () const inline
return true iff this line number is the header line [0]
Definition at line 63 of file Nabla.hh.
References ln_major, ln_minor, and UCS_string::size().
Referenced by Nabla::execute_edit().
next()
void LineLabel::next ()
increase the line number
Definition at line 991 of file Nabla.cc.
References UCS_string::append(), ln_major, ln_minor, and UCS_string::size().
Referenced by Nabla::edit_body_line(), Nabla::edit_header_line(), and Nabla::execute_show().
operator<()
bool LineLabel::operator< (const LineLabel & other) const
true iff this line number is smaller than other
Definition at line 1018 of file Nabla.cc.
References UCS_string::compare(), ln_major, and ln_minor.
operator==()
bool LineLabel::operator== (const LineLabel & other) const
true iff two line numbers are equal
Definition at line 1013 of file Nabla.cc.
References ln_major, and ln_minor.
print()
void LineLabel::print (ostream & out) const
print the line number
Definition at line 958 of file Nabla.cc.
References UCS_string::append(), UCS_string::append_number(), UCS_string::append_UTF8(), ln_major, ln_minor, and UCS_string::size().
Referenced by Nabla::FunLine::print().
print_prompt()
UCS_string LineLabel::print_prompt (int min_size) const
print a prompt like [1.2] into buffer
Definition at line 974 of file Nabla.cc.
References UCS_string::append(), UCS_string::append_number(), UCS_string::append_UTF8(), ln_major, ln_minor, and UCS_string::size().
Referenced by Nabla::edit(), and Nabla::FunLine::get_label_and_text().
valid()
bool LineLabel::valid () const inline
true if tis line number is valid (i.e. the line exists)
Definition at line 55 of file Nabla.hh.
References ln_major.
Referenced by Nabla::execute_show().
Member Data Documentation
ln_major
int LineLabel::ln_major
the integer part of the line number
Definition at line 73 of file Nabla.hh.
Referenced by clear(), Nabla::execute_edit(), Nabla::execute_oper(), Nabla::find_line(), is_header_line_number(), next(), operator<(), operator==(), Nabla::parse_lineno(), print(), print_prompt(), and valid().
ln_minor
UCS_string LineLabel::ln_minor
the fractional part of the line number
Definition at line 76 of file Nabla.hh.
Referenced by clear(), insert(), is_header_line_number(), next(), operator<(), operator==(), Nabla::parse_lineno(), print(), and print_prompt().
The documentation for this struct was generated from the following files:
src/Nabla.hh
src/Nabla.cc