GNU APL: CDR_header Struct Reference
CDR_header Struct Reference
the header of a CDR record
#include <CDR_string.hh>
Public Member Functions
uint32_t get_nb () const
return the number of bytes in host endian
uint32_t get_nelm () const
return the number of elements in host endian
Static Public Member Functions
static uint32_t get_be32 (const uint8_t *data)
convert big endian 32 bit value to 32 bit host value (== ntohl())
Public Attributes
uint32_t be_ptr
a value to figure the endian of the machine
uint32_t be_nb
number of bytes in big endian
int32_t be_nelm
number of elements in big endian
uint8_t type
CDR_type.
uint8_t rank
rank of the value
uint8_t fill [2]
fill bytes
Detailed Description
the header of a CDR record
Definition at line 29 of file CDR_string.hh.
Member Function Documentation
get_be32()
static uint32_t CDR_header::get_be32 (const uint8_t * data) inline static
convert big endian 32 bit value to 32 bit host value (== ntohl())
Definition at line 52 of file CDR_string.hh.
Referenced by CDR_string::get_4(), CDR::get_4_be(), get_nb(), and get_nelm().
get_nb()
uint32_t CDR_header::get_nb () const inline
return the number of bytes in host endian
Definition at line 44 of file CDR_string.hh.
References be_nb, and get_be32().
Referenced by CDR_string::check().
get_nelm()
uint32_t CDR_header::get_nelm () const inline
return the number of elements in host endian
Definition at line 48 of file CDR_string.hh.
References be_nelm, and get_be32().
Referenced by CDR_string::check().
Member Data Documentation
be_nb
uint32_t CDR_header::be_nb
number of bytes in big endian
Definition at line 32 of file CDR_string.hh.
Referenced by get_nb().
be_nelm
int32_t CDR_header::be_nelm
number of elements in big endian
Definition at line 33 of file CDR_string.hh.
Referenced by get_nelm().
be_ptr
uint32_t CDR_header::be_ptr
a value to figure the endian of the machine
Definition at line 31 of file CDR_string.hh.
fill
uint8_t CDR_header::fill[2]
fill bytes
Definition at line 36 of file CDR_string.hh.
Referenced by Bif_F12_PICK::disclose_item().
rank
uint8_t CDR_header::rank
rank of the value
Definition at line 35 of file CDR_string.hh.
Referenced by CDR_string::get_rank().
type
uint8_t CDR_header::type
CDR_type.
Definition at line 34 of file CDR_string.hh.
The documentation for this struct was generated from the following file:
src/CDR_string.hh