GNU APL: Svar_partner Struct Reference
Svar_partner Struct Reference
one of the two partners of a shared vaiable
#include <Svar_record.hh>
Public Member Functions
Svar_partner ()
constructor: unused share partner
Svar_partner (const AP_num3 _id, TCP_socket _tcp_fd)
constructor: specific share partner
void operator= (const Svar_partner &other)
copy other to
this
void clear ()
clear this partner
bool is_active () const
return true if this partner is active. Note that this can be the case even though tcp_fd is invalid.
void set_control (Svar_Control ctl)
set the control bits of this partner (as seen by the offering partner)
Svar_Control get_control () const
return the control bits of this partner (as seen by the offering
ostream & print (ostream &out) const
print this partner
Public Attributes
AP_num3 id
the processor
TCP_socket tcp_fd
the TCP socket of the server towards the partner
uint16_t flags
flags controlled by this partner. The numbers 1 and 2 in the SET_BY_1, SET_BY_2 bits refer to this partner as 1 and the other partner as 2.
Svar_event events
the events for the partner
Protected Attributes
bool active
true if this is a valid (connected) partner
Detailed Description
one of the two partners of a shared vaiable
Definition at line 110 of file Svar_record.hh.
Constructor & Destructor Documentation
Svar_partner() [1/2]
Svar_partner::Svar_partner () inline
constructor: unused share partner
Definition at line 113 of file Svar_record.hh.
Svar_partner() [2/2]
Svar_partner::Svar_partner (const AP_num3 _id, TCP_socket _tcp_fd) inline
constructor: specific share partner
Definition at line 122 of file Svar_record.hh.
Member Function Documentation
clear()
void Svar_partner::clear () inline
clear this partner
Definition at line 141 of file Svar_record.hh.
Referenced by Svar_record::clear(), Svar_record::remove_accepting(), and Svar_record::remove_offering().
get_control()
Svar_Control Svar_partner::get_control () const inline
return the control bits of this partner (as seen by the offering
Definition at line 154 of file Svar_record.hh.
References flags.
Referenced by Quad_SVC::eval_AB(), Quad_SVC::eval_B(), Svar_record::get_control(), Svar_record::may_set(), Svar_record::may_use(), and Svar_record::set_state().
is_active()
bool Svar_partner::is_active () const inline
return true if this partner is active. Note that this can be the case even though tcp_fd is invalid.
Definition at line 145 of file Svar_record.hh.
References active.
Referenced by Svar_record::get_coupling(), Svar_record::may_set(), and Svar_record::may_use().
operator=()
void Svar_partner::operator= (const Svar_partner & other) inline
copy other to
this
Definition at line 131 of file Svar_record.hh.
References active, events, flags, id, and tcp_fd.
print()
ostream & Svar_partner::print (ostream & out) const
print this partner
Definition at line 71 of file Svar_record.cc.
References flags, and tcp_fd.
Referenced by Svar_record::print().
set_control()
void Svar_partner::set_control (Svar_Control ctl) inline
set the control bits of this partner (as seen by the offering partner)
Definition at line 149 of file Svar_record.hh.
References flags.
Referenced by Svar_record::set_control().
Member Data Documentation
active
bool Svar_partner::active protected
true if this is a valid (connected) partner
Definition at line 175 of file Svar_record.hh.
Referenced by is_active(), and operator=().
events
Svar_event Svar_partner::events
the events for the partner
Definition at line 171 of file Svar_record.hh.
Referenced by Svar_record::may_set(), Svar_record::may_use(), operator=(), Svar_record::set_control(), and Svar_record::set_state().
flags
uint16_t Svar_partner::flags
flags controlled by this partner. The numbers 1 and 2 in the SET_BY_1, SET_BY_2 bits refer to this partner as 1 and the other partner as 2.
Definition at line 168 of file Svar_record.hh.
Referenced by get_control(), operator=(), print(), and set_control().
id
AP_num3 Svar_partner::id
the processor
Definition at line 161 of file Svar_record.hh.
Referenced by Svar_record::bad_proc(), Svar_record::get_control(), Svar_record::is_ws_to_ws(), Svar_DB::match_or_make(), Svar_record::may_set(), Svar_record::may_use(), operator=(), Svar_record::remove_offering(), Svar_record::retract(), Svar_record::set_control(), and Svar_record::set_state().
tcp_fd
TCP_socket Svar_partner::tcp_fd
the TCP socket of the server towards the partner
Definition at line 164 of file Svar_record.hh.
Referenced by operator=(), and print().
The documentation for this struct was generated from the following files:
src/Svar_record.hh
src/Svar_record.cc