GNUAPL: src/Svar_DB.cc File Reference
Svar_DB.cc File Reference
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <netinet/tcp.h>
#include <signal.h>
#include <string.h>
#include <stdio.h>
#include <sys/time.h>
#include "Common.hh"
#include <iomanip>
#include "Backtrace.hh"
#include "Logging.hh"
#include "Svar_DB.hh"
#include "Svar_signals.hh"
#include "UserPreferences.hh"
Classes
union SockAddr
between sockaddr and a sockaddr_in
Functions
ostream & get_CERR ()
Function Documentation
get_CERR()
ostream& get_CERR ()
Definition at line 63 of file Output.cc.
Referenced by Svar_DB::connect_to_APserver(), Svar_DB::DB_tcp_error(), Svar_DB::get_Svar_DB_tcp(), Svar_DB::init(), Svar_DB::start_APserver(), and Svar_record_P::Svar_record_P().