GNUAPL: src/Svar_record.cc File Reference
Svar_record.cc File Reference
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <string.h>
#include <stdio.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <iomanip>
#include "Backtrace.hh"
#include "Logging.hh"
#include "PrintOperator.hh"
#include "ProcessorID.hh"
#include "Svar_record.hh"
#include "Svar_signals.hh"
Functions
ostream & get_CERR ()
const char * event_name (Svar_event ev)
return the name for event ev
Svar_Control mirror (int flags)
Function Documentation
event_name()
const char* event_name (Svar_event ev)
return the name for event ev
Definition at line 48 of file Svar_record.cc.
References SVE_ACCESS_CONTROL, SVE_NO_EVENTS, SVE_OFFER_MATCHED, SVE_OFFER_MISMATCH, SVE_OFFER_RETRACT, SVE_SET_BY_ACC_FAILED, SVE_SET_BY_ACC_SUCCESS, SVE_SET_BY_OFF_FAILED, SVE_SET_BY_OFF_SUCCESS, SVE_USE_BY_ACC_FAILED, SVE_USE_BY_ACC_SUCCESS, SVE_USE_BY_OFF_FAILED, and SVE_USE_BY_OFF_SUCCESS.
get_CERR()
ostream& get_CERR ()
Definition at line 63 of file Output.cc.
References CERR(), Output::color_mode, UserPreferences::output_to_cout, uprefs, and ErrOut::used.
Referenced by Svar_record::bad_proc(), Svar_record::set_control(), and Svar_record::set_state().
mirror()
Svar_Control mirror (int flags)
Definition at line 154 of file Svar_record.cc.
References SET_BY_ACC, SET_BY_OFF, USE_BY_ACC, and USE_BY_OFF.
Referenced by Svar_record::get_control(), and Svar_record::set_control().