GNUAPL: src/Token.cc File Reference
Token.cc File Reference
#include <string.h>
#include "IndexExpr.hh"
#include "Output.hh"
#include "PrintOperator.hh"
#include "Symbol.hh"
#include "Token.hh"
#include "Workspace.hh"
#include "Token.def"
Macros
#define tcc(x) case x: out << #x; break;
#define TD(tag, _tc, _tv, _id) case tag: return UCS_string(#tag);
#define tcn(x) case x: return #x;
Functions
ostream & operator<< (ostream &out, TokenTag tag)
ostream & operator<< (ostream &out, TokenClass tc)
ostream & operator<< (ostream &out, const Token &token)
ostream & operator<< (ostream &out, const Token_string &tos)
Macro Definition Documentation
tcc
#define tcc (x) case x: out << #x; break;
Referenced by operator<<().
tcn
#define tcn (x) case x: return #x;
Referenced by Token::class_name().
TD
#define TD (tag, _tc, _tv, _id) case tag: return UCS_string(#tag);
Function Documentation
operator<<() [1/4]
ostream& operator<< (ostream & out, TokenTag tag)
Definition at line 88 of file Token.cc.
References HEX, and HEX4.
operator<<() [2/4]
ostream& operator<< (ostream & out, TokenClass tc)
Definition at line 97 of file Token.cc.
References TC_ASSIGN, TC_COLON, TC_DIAMOND, TC_END, TC_FUN0, TC_FUN12, TC_INDEX, TC_INVALID, TC_L_BRACK, TC_L_PARENT, TC_LINE, TC_NEWLINE, TC_NUMERIC, TC_OFF, TC_OPER1, TC_OPER2, TC_PINDEX, TC_QUOTE, TC_R_ARROW, TC_R_BRACK, TC_R_PARENT, TC_RETURN, TC_SI_LEAVE, TC_SPACE, TC_SYMBOL, TC_VALUE, TC_VOID, and tcc.
operator<<() [3/4]
ostream& operator<< (ostream & out, const Token & token)
Definition at line 138 of file Token.cc.
References Error::error_name(), FIXME, Token::get_apl_val(), Token::get_axes(), Token::get_char_val(), Token::get_Class(), Token::get_fun_line(), Token::get_Id(), Token::get_index_val(), Token::get_int_val(), PrintBuffer::get_line(), PrintBuffer::get_row_count(), Token::get_sym_ptr(), Token::get_tag(), ID_No_ID2, UCS_string::no_pad(), PR_APL, Symbol::print(), Token::print_function(), Token::print_value(), UCS_string::size(), TC_END, TC_FUN0, TC_FUN12, TC_INDEX, TC_LINE, TC_NEWLINE, TC_NUMERIC, TC_OPER1, TC_OPER2, TC_PINDEX, TC_RETURN, TC_SYMBOL, TC_VALUE, TOK_APL_VALUE1, TOK_APL_VALUE2, TOK_APL_VALUE3, TOK_AXIS, TOK_BRANCH, TOK_CHARACTER, TOK_ERROR, TOK_INDEX, TOK_LSYMB, TOK_LSYMB2, TOK_NOBRANCH, TOK_RETURN_EXEC, TOK_RETURN_STATS, TOK_RETURN_SYMBOL, TOK_RETURN_VOID, UNI_LEFT_ARROW, and Token::value.
operator<<() [4/4]
ostream& operator<< (ostream & out, const Token_string & tos)
Definition at line 711 of file Token.cc.
References CERR, and loop.