GNUAPL: src/TokenEnums.hh File Reference
TokenEnums.hh File Reference
#include "IdEnums.hh"
#include "Token.def"
Macros
#define TD(tok, tc, tv, id) tok = tc | tv | (id << 16),
Enumerations
enum TokenClass {
TC_ASSIGN = 0x01,
TC_R_ARROW = 0x02,
TC_L_BRACK = 0x03,
TC_R_BRACK = 0x04,
TC_END = 0x05,
TC_FUN0 = 0x06,
TC_FUN12 = 0x07,
TC_INDEX = 0x08,
TC_OPER1 = 0x09,
TC_OPER2 = 0x0A,
TC_L_PARENT = 0x0B,
TC_R_PARENT = 0x0C,
TC_RETURN = 0x0D,
TC_SYMBOL = 0x0E,
TC_VALUE = 0x0F,
TC_MAX_PERM,
TC_FUN1 = TC_FUN12,
TC_FUN2 = TC_FUN12,
TC_PINDEX = 0x10,
TC_VOID = 0x11,
TC_MAX_PHRASE,
TC_MAX_PHRASE_2 = TC_MAX_PHRASE*TC_MAX_PHRASE,
TC_MAX_PHRASE_3 = TC_MAX_PHRASE*TC_MAX_PHRASE_2,
TC_MAX_PHRASE_4 = TC_MAX_PHRASE*TC_MAX_PHRASE_3,
TC_OFF = 0x12,
TC_SI_LEAVE = 0x13,
TC_LINE = 0x14,
TC_DIAMOND = 0x15,
TC_NUMERIC = 0x16,
TC_SPACE = 0x17,
TC_NEWLINE = 0x18,
TC_COLON = 0x19,
TC_QUOTE = 0x1A,
TC_L_CURLY = 0x1B,
TC_R_CURLY = 0x1C,
TC_MASK = 0xFF,
TC_INVALID = 0xFF,
SN_A = TC_VALUE,
SN_ASS = TC_ASSIGN,
SN_B = TC_VALUE,
SN_C = TC_INDEX,
SN_D = TC_OPER2,
SN_END = TC_END,
SN_F = TC_FUN12,
SN_G = TC_FUN12,
SN_GOTO = TC_R_ARROW,
SN_I = TC_PINDEX,
SN_LBRA = TC_L_BRACK,
SN_LPAR = TC_L_PARENT,
SN_M = TC_OPER1,
SN_N = TC_FUN0,
SN_RETC = TC_RETURN,
SN_RBRA = TC_R_BRACK,
SN_RPAR = TC_R_PARENT,
SN_V = TC_SYMBOL,
SN_VOID = TC_VOID,
SN_ = TC_INVALID
}
enum Binding_Strength {
BS_ANY = 0,
BS_ASS_B = 10,
BS_F_B = 20,
BS_A_F = 30,
BS_LO_OP = 40,
BS_VAL_VAL = 50,
BS_OP_RO = 60,
BS_V_ASS = 70,
BS_ANY_BRA = 80
}
binding strengths between token classes
enum TokenValueType {
TV_MASK = 0xFF00,
TV_NONE = 0x0000,
TV_CHAR = 0x0100,
TV_INT = 0x0200,
TV_FLT = 0x0300,
TV_CPX = 0x0400,
TV_SYM = 0x0500,
TV_LIN = 0x0600,
TV_VAL = 0x0700,
TV_INDEX = 0x0800,
TV_FUN = 0x0900
}
enum TokenTag {
TOK_NEWLINE = TC_NEWLINE | TV_NONE | (ID_No_ID << 16),
TOK_LINE = TC_LINE | TV_LIN | (ID_No_ID << 16),
TOK_SYMBOL = TC_SYMBOL | TV_SYM | (ID_No_ID << 16),
TOK_LSYMB = TC_SYMBOL | TV_SYM | (ID_No_ID1 << 16),
TOK_LSYMB2 = TC_SYMBOL | TV_SYM | (ID_No_ID2 << 16),
TOK_P_SYMB = TC_SYMBOL | TV_SYM | (ID_No_ID3 << 16),
TOK_NUMERIC = TC_NUMERIC | TV_CHAR | (ID_No_ID << 16),
TOK_INDEX = TC_INDEX | TV_INDEX | (ID_No_ID << 16),
TOK_PINDEX = TC_PINDEX | TV_INDEX | (ID_No_ID << 16),
TOK_AXIS = TC_INDEX | TV_VAL | (ID_No_ID << 16),
TOK_FUN0 = TC_FUN0 | TV_FUN | (ID_No_ID << 16),
TOK_FUN2 = TC_FUN2 | TV_FUN | (ID_No_ID << 16),
TOK_OPER1 = TC_OPER1 | TV_FUN | (ID_No_ID << 16),
TOK_OPER2 = TC_OPER2 | TV_FUN | (ID_No_ID << 16),
TOK_FIRST_TIME = TC_VOID | TV_NONE | (ID_FIRST_TIME << 16),
TOK_INVALID = TC_INVALID | TV_NONE | (ID_INVALID << 16),
TOK_VOID = TC_VOID | TV_NONE | (ID_VOID << 16),
TOK_END = TC_END | TV_INT | (ID_END << 16),
TOK_ENDL = TC_END | TV_INT | (ID_ENDL << 16),
TOK_OFF = TC_OFF | TV_NONE | (ID_OFF << 16),
TOK_ESCAPE = TC_R_ARROW | TV_NONE | (ID_ESCAPE << 16),
TOK_SPACE = TC_SPACE | TV_NONE | (ID_SPACE << 16),
TOK_COLON = TC_COLON | TV_NONE | (ID_COLON << 16),
TOK_QUOTE1 = TC_QUOTE | TV_NONE | (ID_QUOTE1 << 16),
TOK_QUOTE2 = TC_QUOTE | TV_NONE | (ID_QUOTE2 << 16),
TOK_ASSIGN = TC_ASSIGN | TV_NONE | (ID_ASSIGN << 16),
TOK_ASSIGN1 = TC_ASSIGN | TV_NONE | (ID_ASSIGN1 << 16),
TOK_R_ARROW = TC_R_ARROW | TV_NONE | (ID_R_ARROW << 16),
TOK_DIAMOND = TC_DIAMOND | TV_NONE | (ID_DIAMOND << 16),
TOK_RETURN_EXEC = TC_RETURN | TV_NONE | (ID_RETURN_EXEC << 16),
TOK_RETURN_STATS = TC_RETURN | TV_NONE | (ID_RETURN_STATS << 16),
TOK_RETURN_VOID = TC_RETURN | TV_NONE | (ID_RETURN_VOID << 16),
TOK_NO_VALUE = TC_VALUE | TV_NONE | (ID_NO_VALUE << 16),
TOK_SI_PUSHED = TC_SI_LEAVE | TV_NONE | (ID_SI_PUSHED << 16),
TOK_L_BRACK = TC_L_BRACK | TV_INT | (ID_L_BRACK << 16),
TOK_SEMICOL = TC_L_BRACK | TV_NONE | (ID_SEMICOL << 16),
TOK_R_BRACK = TC_R_BRACK | TV_INT | (ID_R_BRACK << 16),
TOK_L_PARENT = TC_L_PARENT | TV_INT | (ID_L_PARENT << 16),
TOK_R_PARENT = TC_R_PARENT | TV_INT | (ID_R_PARENT << 16),
TOK_L_CURLY = TC_L_CURLY | TV_INT | (ID_L_CURLY << 16),
TOK_R_CURLY = TC_R_CURLY | TV_INT | (ID_R_CURLY << 16),
TOK_RETURN_SYMBOL = TC_RETURN | TV_SYM | (ID_RETURN_SYMBOL << 16),
TOK_Quad_Quad = TC_SYMBOL | TV_SYM | (ID_Quad_Quad << 16),
TOK_Quad_QUOTE = TC_SYMBOL | TV_SYM | (ID_QUOTE_Quad << 16),
TOK_Quad_AI = TC_SYMBOL | TV_SYM | (ID_Quad_AI << 16),
TOK_Quad_ARG = TC_SYMBOL | TV_SYM | (ID_Quad_ARG << 16),
TOK_Quad_AV = TC_SYMBOL | TV_SYM | (ID_Quad_AV << 16),
TOK_Quad_CT = TC_SYMBOL | TV_SYM | (ID_Quad_CT << 16),
TOK_Quad_EM = TC_SYMBOL | TV_SYM | (ID_Quad_EM << 16),
TOK_Quad_ET = TC_SYMBOL | TV_SYM | (ID_Quad_ET << 16),
TOK_Quad_FC = TC_SYMBOL | TV_SYM | (ID_Quad_FC << 16),
TOK_Quad_IO = TC_SYMBOL | TV_SYM | (ID_Quad_IO << 16),
TOK_Quad_LC = TC_SYMBOL | TV_SYM | (ID_Quad_LC << 16),
TOK_Quad_LX = TC_SYMBOL | TV_SYM | (ID_Quad_LX << 16),
TOK_Quad_L = TC_SYMBOL | TV_SYM | (ID_Quad_L << 16),
TOK_Quad_PP = TC_SYMBOL | TV_SYM | (ID_Quad_PP << 16),
TOK_Quad_PR = TC_SYMBOL | TV_SYM | (ID_Quad_PR << 16),
TOK_Quad_PS = TC_SYMBOL | TV_SYM | (ID_Quad_PS << 16),
TOK_Quad_PW = TC_SYMBOL | TV_SYM | (ID_Quad_PW << 16),
TOK_Quad_R = TC_SYMBOL | TV_SYM | (ID_Quad_R << 16),
TOK_Quad_RL = TC_SYMBOL | TV_SYM | (ID_Quad_RL << 16),
TOK_Quad_SVE = TC_SYMBOL | TV_SYM | (ID_Quad_SVE << 16),
TOK_Quad_SYL = TC_SYMBOL | TV_SYM | (ID_Quad_SYL << 16),
TOK_Quad_TC = TC_SYMBOL | TV_SYM | (ID_Quad_TC << 16),
TOK_Quad_TS = TC_SYMBOL | TV_SYM | (ID_Quad_TS << 16),
TOK_Quad_TZ = TC_SYMBOL | TV_SYM | (ID_Quad_TZ << 16),
TOK_Quad_UL = TC_SYMBOL | TV_SYM | (ID_Quad_UL << 16),
TOK_Quad_WA = TC_SYMBOL | TV_SYM | (ID_Quad_WA << 16),
TOK_Quad_X = TC_SYMBOL | TV_SYM | (ID_Quad_X << 16),
TOK_ALPHA = TC_SYMBOL | TV_SYM | (ID_ALPHA << 16),
TOK_ALPHA_U = TC_SYMBOL | TV_SYM | (ID_ALPHA_U << 16),
TOK_CHI = TC_SYMBOL | TV_SYM | (ID_CHI << 16),
TOK_LAMBDA = TC_SYMBOL | TV_SYM | (ID_LAMBDA << 16),
TOK_OMEGA = TC_SYMBOL | TV_SYM | (ID_OMEGA << 16),
TOK_OMEGA_U = TC_SYMBOL | TV_SYM | (ID_OMEGA_U << 16),
TOK_F0_ZILDE = TC_FUN0 | TV_FUN | (ID_F0_ZILDE << 16),
TOK_F1_EXECUTE = TC_FUN1 | TV_FUN | (ID_F1_EXECUTE << 16),
TOK_Quad_AF = TC_FUN1 | TV_FUN | (ID_Quad_AF << 16),
TOK_Quad_CR = TC_FUN2 | TV_FUN | (ID_Quad_CR << 16),
TOK_Quad_DL = TC_FUN1 | TV_FUN | (ID_Quad_DL << 16),
TOK_Quad_DLX = TC_FUN2 | TV_FUN | (ID_Quad_DLX << 16),
TOK_Quad_EC = TC_FUN1 | TV_FUN | (ID_Quad_EC << 16),
TOK_Quad_ENV = TC_FUN1 | TV_FUN | (ID_Quad_ENV << 16),
TOK_Quad_EX = TC_FUN1 | TV_FUN | (ID_Quad_EX << 16),
TOK_Quad_RE = TC_FUN2 | TV_FUN | (ID_Quad_RE << 16),
TOK_Quad_SQL = TC_FUN2 | TV_FUN | (ID_Quad_SQL << 16),
TOK_Quad_SVQ = TC_FUN1 | TV_FUN | (ID_Quad_SVQ << 16),
TOK_Quad_SVR = TC_FUN1 | TV_FUN | (ID_Quad_SVR << 16),
TOK_Quad_SVS = TC_FUN1 | TV_FUN | (ID_Quad_SVS << 16),
TOK_Quad_SI = TC_FUN1 | TV_FUN | (ID_Quad_SI << 16),
TOK_Quad_UCS = TC_FUN1 | TV_FUN | (ID_Quad_UCS << 16),
TOK_F2_AND = TC_FUN2 | TV_FUN | (ID_F2_AND << 16),
TOK_F2_AND_B = TC_FUN2 | TV_FUN | (ID_F2_AND_B << 16),
TOK_Quad_AT = TC_FUN2 | TV_FUN | (ID_Quad_AT << 16),
TOK_F2_EQUAL = TC_FUN2 | TV_FUN | (ID_F2_EQUAL << 16),
TOK_F2_EQUAL_B = TC_FUN2 | TV_FUN | (ID_F2_EQUAL_B << 16),
TOK_F2_FIND = TC_FUN2 | TV_FUN | (ID_F2_FIND << 16),
TOK_F2_GREATER = TC_FUN2 | TV_FUN | (ID_F2_GREATER << 16),
TOK_F2_INDEX = TC_FUN2 | TV_FUN | (ID_F2_INDEX << 16),
TOK_F2_INTER = TC_FUN2 | TV_FUN | (ID_F2_INTER << 16),
TOK_Quad_INP = TC_FUN2 | TV_FUN | (ID_Quad_INP << 16),
TOK_F2_LEQU = TC_FUN2 | TV_FUN | (ID_F2_LEQU << 16),
TOK_F2_LESS = TC_FUN2 | TV_FUN | (ID_F2_LESS << 16),
TOK_F2_MEQU = TC_FUN2 | TV_FUN | (ID_F2_MEQU << 16),
TOK_F2_NAND = TC_FUN2 | TV_FUN | (ID_F2_NAND << 16),
TOK_F2_NAND_B = TC_FUN2 | TV_FUN | (ID_F2_NAND_B << 16),
TOK_F2_NOR = TC_FUN2 | TV_FUN | (ID_F2_NOR << 16),
TOK_F2_NOR_B = TC_FUN2 | TV_FUN | (ID_F2_NOR_B << 16),
TOK_F2_OR = TC_FUN2 | TV_FUN | (ID_F2_OR << 16),
TOK_F2_OR_B = TC_FUN2 | TV_FUN | (ID_F2_OR_B << 16),
TOK_F2_UNEQU = TC_FUN2 | TV_FUN | (ID_F2_UNEQU << 16),
TOK_F2_UNEQ_B = TC_FUN2 | TV_FUN | (ID_F2_UNEQ_B << 16),
TOK_Quad_EA = TC_FUN2 | TV_FUN | (ID_Quad_EA << 16),
TOK_Quad_EB = TC_FUN2 | TV_FUN | (ID_Quad_EB << 16),
TOK_Quad_SVC = TC_FUN2 | TV_FUN | (ID_Quad_SVC << 16),
TOK_Quad_TF = TC_FUN2 | TV_FUN | (ID_Quad_TF << 16),
TOK_Quad_XML = TC_FUN2 | TV_FUN | (ID_Quad_XML << 16),
TOK_Quad_JSON = TC_FUN2 | TV_FUN | (ID_Quad_JSON << 16),
TOK_F12_BINOM = TC_FUN2 | TV_FUN | (ID_F12_BINOM << 16),
TOK_F12_CIRCLE = TC_FUN2 | TV_FUN | (ID_F12_CIRCLE << 16),
TOK_F12_COMMA = TC_FUN2 | TV_FUN | (ID_F12_COMMA << 16),
TOK_F12_COMMA1 = TC_FUN2 | TV_FUN | (ID_F12_COMMA1 << 16),
TOK_F12_DECODE = TC_FUN2 | TV_FUN | (ID_F12_DECODE << 16),
TOK_F12_DIVIDE = TC_FUN2 | TV_FUN | (ID_F12_DIVIDE << 16),
TOK_F12_DOMINO = TC_FUN2 | TV_FUN | (ID_F12_DOMINO << 16),
TOK_F12_DROP = TC_FUN2 | TV_FUN | (ID_F12_DROP << 16),
TOK_F12_ELEMENT = TC_FUN2 | TV_FUN | (ID_F12_ELEMENT << 16),
TOK_F12_ENCODE = TC_FUN2 | TV_FUN | (ID_F12_ENCODE << 16),
TOK_F12_EQUIV = TC_FUN2 | TV_FUN | (ID_F12_EQUIV << 16),
TOK_F12_FORMAT = TC_FUN2 | TV_FUN | (ID_F12_FORMAT << 16),
TOK_F12_INDEX_OF = TC_FUN2 | TV_FUN | (ID_F12_INDEX_OF << 16),
TOK_F12_INTERVAL_INDEX = TC_FUN2 | TV_FUN | (ID_F12_INTERVAL_INDEX << 16),
TOK_JOT = TC_FUN2 | TV_FUN | (ID_JOT << 16),
TOK_F2_LEFT = TC_FUN2 | TV_FUN | (ID_F2_LEFT << 16),
TOK_F12_LOGA = TC_FUN2 | TV_FUN | (ID_F12_LOGA << 16),
TOK_F12_MINUS = TC_FUN2 | TV_FUN | (ID_F12_MINUS << 16),
TOK_F12_NEQUIV = TC_FUN2 | TV_FUN | (ID_F12_NEQUIV << 16),
TOK_F12_PARTITION = TC_FUN2 | TV_FUN | (ID_F12_PARTITION << 16),
TOK_F12_PICK = TC_FUN2 | TV_FUN | (ID_F12_PICK << 16),
TOK_F12_PLUS = TC_FUN2 | TV_FUN | (ID_F12_PLUS << 16),
TOK_F12_POWER = TC_FUN2 | TV_FUN | (ID_F12_POWER << 16),
TOK_F12_RHO = TC_FUN2 | TV_FUN | (ID_F12_RHO << 16),
TOK_F2_RIGHT = TC_FUN2 | TV_FUN | (ID_F2_RIGHT << 16),
TOK_F12_RND_DN = TC_FUN2 | TV_FUN | (ID_F12_RND_DN << 16),
TOK_F12_RND_UP = TC_FUN2 | TV_FUN | (ID_F12_RND_UP << 16),
TOK_F12_ROLL = TC_FUN2 | TV_FUN | (ID_F12_ROLL << 16),
TOK_F12_ROTATE = TC_FUN2 | TV_FUN | (ID_F12_ROTATE << 16),
TOK_F12_ROTATE1 = TC_FUN2 | TV_FUN | (ID_F12_ROTATE1 << 16),
TOK_F12_SORT_ASC = TC_FUN2 | TV_FUN | (ID_F12_SORT_ASC << 16),
TOK_F12_SORT_DES = TC_FUN2 | TV_FUN | (ID_F12_SORT_DES << 16),
TOK_F12_STILE = TC_FUN2 | TV_FUN | (ID_F12_STILE << 16),
TOK_STOP_LINE = TC_R_ARROW | TV_NONE | (ID_STOP_LINE << 16),
TOK_Quad_STOP = TC_FUN2 | TV_FUN | (ID_Quad_STOP << 16),
TOK_F12_TAKE = TC_FUN2 | TV_FUN | (ID_F12_TAKE << 16),
TOK_F12_TIMES = TC_FUN2 | TV_FUN | (ID_F12_TIMES << 16),
TOK_F12_TRANSPOSE = TC_FUN2 | TV_FUN | (ID_F12_TRANSPOSE << 16),
TOK_Quad_TRACE = TC_FUN2 | TV_FUN | (ID_Quad_TRACE << 16),
TOK_F12_WITHOUT = TC_FUN2 | TV_FUN | (ID_F12_WITHOUT << 16),
TOK_F12_UNION = TC_FUN2 | TV_FUN | (ID_F12_UNION << 16),
TOK_Quad_ES = TC_FUN2 | TV_FUN | (ID_Quad_ES << 16),
TOK_Quad_FX = TC_FUN2 | TV_FUN | (ID_Quad_FX << 16),
TOK_Quad_FFT = TC_FUN2 | TV_FUN | (ID_Quad_FFT << 16),
TOK_Quad_FIO = TC_FUN2 | TV_FUN | (ID_Quad_FIO << 16),
TOK_Quad_GTK = TC_FUN2 | TV_FUN | (ID_Quad_GTK << 16),
TOK_Quad_MAP = TC_FUN2 | TV_FUN | (ID_Quad_MAP << 16),
TOK_Quad_NA = TC_FUN2 | TV_FUN | (ID_Quad_NA << 16),
TOK_Quad_NC = TC_FUN1 | TV_FUN | (ID_Quad_NC << 16),
TOK_Quad_NL = TC_FUN2 | TV_FUN | (ID_Quad_NL << 16),
TOK_Quad_PLOT = TC_FUN2 | TV_FUN | (ID_Quad_PLOT << 16),
TOK_Quad_RVAL = TC_FUN2 | TV_FUN | (ID_Quad_RVAL << 16),
TOK_Quad_SVO = TC_FUN2 | TV_FUN | (ID_Quad_SVO << 16),
TOK_OPER1_COMMUTE = TC_OPER1 | TV_FUN | (ID_OPER1_COMMUTE << 16),
TOK_OPER1_EACH = TC_OPER1 | TV_FUN | (ID_OPER1_EACH << 16),
TOK_OPER1_MACRO = TC_OPER1 | TV_FUN | (ID_MACRO << 16),
TOK_OPER1_REDUCE = TC_OPER1 | TV_FUN | (ID_OPER1_REDUCE << 16),
TOK_F12_COMPRESS = TC_FUN2 | TV_FUN | (ID_OPER1_REDUCE << 16),
TOK_OPER1_REDUCE1 = TC_OPER1 | TV_FUN | (ID_OPER1_REDUCE1 << 16),
TOK_F12_COMPRESS1 = TC_FUN2 | TV_FUN | (ID_OPER1_REDUCE1 << 16),
TOK_OPER1_SCAN = TC_OPER1 | TV_FUN | (ID_OPER1_SCAN << 16),
TOK_F12_EXPAND = TC_FUN2 | TV_FUN | (ID_OPER1_SCAN << 16),
TOK_OPER1_SCAN1 = TC_OPER1 | TV_FUN | (ID_OPER1_SCAN1 << 16),
TOK_F12_EXPAND1 = TC_FUN2 | TV_FUN | (ID_OPER1_SCAN1 << 16),
TOK_OPER2_INNER = TC_OPER2 | TV_FUN | (ID_OPER2_INNER << 16),
TOK_OPER2_MACRO = TC_OPER2 | TV_FUN | (ID_MACRO << 16),
TOK_OPER2_OUTER = TC_OPER2 | TV_FUN | (ID_OPER2_OUTER << 16),
TOK_OPER2_POWER = TC_OPER2 | TV_FUN | (ID_OPER2_POWER << 16),
TOK_OPER2_RANK = TC_OPER2 | TV_FUN | (ID_OPER2_RANK << 16),
TOK_VARIABLE = TC_VALUE | TV_SYM | (ID_VARIABLE << 16),
TOK_APL_VALUE1 = TC_VALUE | TV_VAL | (ID_APL_VALUE1 << 16),
TOK_APL_VALUE2 = TC_VALUE | TV_VAL | (ID_APL_VALUE2 << 16),
TOK_APL_VALUE3 = TC_VALUE | TV_VAL | (ID_APL_VALUE3 << 16),
TOK_BRANCH = TC_R_ARROW | TV_INT | (ID_BRANCH << 16),
TOK_NOBRANCH = TC_R_ARROW | TV_NONE | (ID_BRANCH << 16),
TOK_CHARACTER = TC_VALUE | TV_CHAR | (ID_CHARACTER << 16),
TOK_INTEGER = TC_VALUE | TV_INT | (ID_INTEGER << 16),
TOK_REAL = TC_VALUE | TV_FLT | (ID_REAL << 16),
TOK_COMPLEX = TC_VALUE | TV_CPX | (ID_COMPLEX << 16),
TOK_ERROR = TC_SI_LEAVE | TV_INT | (ID_ERROR << 16),
TOK_QUAD_ES_BRA = TC_SI_LEAVE | TV_VAL | (ID_ES_BRA << 16),
TOK_QUAD_ES_COM = TC_SI_LEAVE | TV_VAL | (ID_ES_COM << 16),
TOK_QUAD_ES_ERR = TC_SI_LEAVE | TV_VAL | (ID_ES_ERR << 16),
TOK_QUAD_ES_ESC = TC_SI_LEAVE | TV_VAL | (ID_ES_ESC << 16),
TOK_FUN1 = TOK_FUN2,
TOK_NONE = -1
}
Functions
void Hswap (TokenTag &t1, TokenTag &t2)
exchange TokenTags t1 and t2
bool is_SLASH_or_BACKSLASH (TokenTag tag)
return true for / ⌿ \ and ⍀
Macro Definition Documentation
TD
#define TD (tok, tc, tv, id) tok = tc | tv | (id << 16),
Definition at line 156 of file TokenEnums.hh.
Enumeration Type Documentation
Binding_Strength
enum Binding_Strength
binding strengths between token classes
Enumerator
BS_ANY
BS_ASS_B
← ANY : ← to what is on its right
BS_F_B
F ANY : function to its right argument.
BS_A_F
ANY F : function to its left argument.
BS_LO_OP
ANY OP : operator to its left function.
BS_VAL_VAL
VEC VEC : vector to vector.
BS_OP_RO
OP ANY : (dyadic) operator to its right function.
BS_V_ASS
ANY ← : ← to what is on its left.
BS_ANY_BRA
ANY [] : [] to what is on its left.
Definition at line 110 of file TokenEnums.hh.
TokenClass
enum TokenClass
The class tag of a token. Token classes < TC_MAX_PERM are permanent (e.g. used in user defined functions) while higher classes are temporary (used while parsing),
Enumerator
TC_ASSIGN
←
TC_R_ARROW
→N
TC_L_BRACK
[ or ;
TC_R_BRACK
]
TC_END
left end of statement
TC_FUN0
niladic function
TC_FUN12
ambivalent function
TC_INDEX
[...]
TC_OPER1
monadic operator
TC_OPER2
dyadic operator
TC_L_PARENT
(
TC_R_PARENT
)
TC_RETURN
return from defined function
TC_SYMBOL
user defined name
TC_VALUE
APL value.
TC_MAX_PERM
permanent token are < TC_MAX_PERM
TC_FUN1
monadic function
TC_FUN2
dyadic function
TC_PINDEX
partial index
TC_VOID
TC_MAX_PHRASE
token in phrases are < TC_MAX_PHRASE
TC_MAX_PHRASE_2
TC_MAX_PHRASE_3
TC_MAX_PHRASE_4
TC_OFF
TC_SI_LEAVE
TC_LINE
TC_DIAMOND
TC_NUMERIC
TC_SPACE
TC_NEWLINE
TC_COLON
TC_QUOTE
TC_L_CURLY
TC_R_CURLY
TC_MASK
TC_INVALID
SN_A
SN_ASS
SN_B
SN_C
SN_D
SN_END
SN_F
SN_G
SN_GOTO
SN_I
SN_LBRA
SN_LPAR
SN_M
SN_N
SN_RETC
SN_RBRA
SN_RPAR
SN_V
SN_VOID
SN_
Definition at line 30 of file TokenEnums.hh.
TokenTag
enum TokenTag
A token tag. It is comprised of 3 fields: a 16 bit Id, an 8 bit TokenValueType, and an 8 bit Token class.
Bit: 31............................16 15.............8 7-..............0 ┌────────────────────────────────┬────────────────┬────────────────┐ │ Id │ TokenValueType │ TokenClass │ └────────────────────────────────┴────────────────┴────────────────┘
Enumerator
TOK_NEWLINE
TOK_LINE
TOK_SYMBOL
TOK_LSYMB
TOK_LSYMB2
TOK_P_SYMB
TOK_NUMERIC
TOK_INDEX
TOK_PINDEX
TOK_AXIS
TOK_FUN0
TOK_FUN2
TOK_OPER1
TOK_OPER2
TOK_FIRST_TIME
TOK_INVALID
TOK_VOID
TOK_END
TOK_ENDL
TOK_OFF
TOK_ESCAPE
TOK_SPACE
TOK_COLON
TOK_QUOTE1
TOK_QUOTE2
TOK_ASSIGN
TOK_ASSIGN1
TOK_R_ARROW
TOK_DIAMOND
TOK_RETURN_EXEC
TOK_RETURN_STATS
TOK_RETURN_VOID
TOK_NO_VALUE
TOK_SI_PUSHED
TOK_L_BRACK
TOK_SEMICOL
TOK_R_BRACK
TOK_L_PARENT
TOK_R_PARENT
TOK_L_CURLY
TOK_R_CURLY
TOK_RETURN_SYMBOL
TOK_Quad_Quad
TOK_Quad_QUOTE
TOK_Quad_AI
TOK_Quad_ARG
TOK_Quad_AV
TOK_Quad_CT
TOK_Quad_EM
TOK_Quad_ET
TOK_Quad_FC
TOK_Quad_IO
TOK_Quad_LC
TOK_Quad_LX
TOK_Quad_L
TOK_Quad_PP
TOK_Quad_PR
TOK_Quad_PS
TOK_Quad_PW
TOK_Quad_R
TOK_Quad_RL
TOK_Quad_SVE
TOK_Quad_SYL
TOK_Quad_TC
TOK_Quad_TS
TOK_Quad_TZ
TOK_Quad_UL
TOK_Quad_WA
TOK_Quad_X
TOK_ALPHA
TOK_ALPHA_U
TOK_CHI
TOK_LAMBDA
TOK_OMEGA
TOK_OMEGA_U
TOK_F0_ZILDE
TOK_F1_EXECUTE
TOK_Quad_AF
TOK_Quad_CR
TOK_Quad_DL
TOK_Quad_DLX
TOK_Quad_EC
TOK_Quad_ENV
TOK_Quad_EX
TOK_Quad_RE
TOK_Quad_SQL
TOK_Quad_SVQ
TOK_Quad_SVR
TOK_Quad_SVS
TOK_Quad_SI
TOK_Quad_UCS
TOK_F2_AND
TOK_F2_AND_B
TOK_Quad_AT
TOK_F2_EQUAL
TOK_F2_EQUAL_B
TOK_F2_FIND
TOK_F2_GREATER
TOK_F2_INDEX
TOK_F2_INTER
TOK_Quad_INP
TOK_F2_LEQU
TOK_F2_LESS
TOK_F2_MEQU
TOK_F2_NAND
TOK_F2_NAND_B
TOK_F2_NOR
TOK_F2_NOR_B
TOK_F2_OR
TOK_F2_OR_B
TOK_F2_UNEQU
TOK_F2_UNEQ_B
TOK_Quad_EA
TOK_Quad_EB
TOK_Quad_SVC
TOK_Quad_TF
TOK_Quad_XML
TOK_Quad_JSON
TOK_F12_BINOM
TOK_F12_CIRCLE
TOK_F12_COMMA
TOK_F12_COMMA1
TOK_F12_DECODE
TOK_F12_DIVIDE
TOK_F12_DOMINO
TOK_F12_DROP
TOK_F12_ELEMENT
TOK_F12_ENCODE
TOK_F12_EQUIV
TOK_F12_FORMAT
TOK_F12_INDEX_OF
TOK_F12_INTERVAL_INDEX
TOK_JOT
TOK_F2_LEFT
TOK_F12_LOGA
TOK_F12_MINUS
TOK_F12_NEQUIV
TOK_F12_PARTITION
TOK_F12_PICK
TOK_F12_PLUS
TOK_F12_POWER
TOK_F12_RHO
TOK_F2_RIGHT
TOK_F12_RND_DN
TOK_F12_RND_UP
TOK_F12_ROLL
TOK_F12_ROTATE
TOK_F12_ROTATE1
TOK_F12_SORT_ASC
TOK_F12_SORT_DES
TOK_F12_STILE
TOK_STOP_LINE
TOK_Quad_STOP
TOK_F12_TAKE
TOK_F12_TIMES
TOK_F12_TRANSPOSE
TOK_Quad_TRACE
TOK_F12_WITHOUT
TOK_F12_UNION
TOK_Quad_ES
TOK_Quad_FX
TOK_Quad_FFT
TOK_Quad_FIO
TOK_Quad_GTK
TOK_Quad_MAP
TOK_Quad_NA
TOK_Quad_NC
TOK_Quad_NL
TOK_Quad_PLOT
TOK_Quad_RVAL
TOK_Quad_SVO
TOK_OPER1_COMMUTE
TOK_OPER1_EACH
TOK_OPER1_MACRO
TOK_OPER1_REDUCE
TOK_F12_COMPRESS
TOK_OPER1_REDUCE1
TOK_F12_COMPRESS1
TOK_OPER1_SCAN
TOK_F12_EXPAND
TOK_OPER1_SCAN1
TOK_F12_EXPAND1
TOK_OPER2_INNER
TOK_OPER2_MACRO
TOK_OPER2_OUTER
TOK_OPER2_POWER
TOK_OPER2_RANK
TOK_VARIABLE
TOK_APL_VALUE1
TOK_APL_VALUE2
TOK_APL_VALUE3
TOK_BRANCH
TOK_NOBRANCH
TOK_CHARACTER
TOK_INTEGER
TOK_REAL
TOK_COMPLEX
TOK_ERROR
TOK_QUAD_ES_BRA
TOK_QUAD_ES_COM
TOK_QUAD_ES_ERR
TOK_QUAD_ES_ESC
TOK_FUN1
TOK_NONE
Definition at line 153 of file TokenEnums.hh.
TokenValueType
enum TokenValueType
The value type of a token
Enumerator
TV_MASK
TV_NONE
TV_CHAR
TV_INT
TV_FLT
TV_CPX
TV_SYM
TV_LIN
TV_VAL
TV_INDEX
TV_FUN
Definition at line 126 of file TokenEnums.hh.
Function Documentation
Hswap()
void Hswap (TokenTag & t1, TokenTag & t2) inline
exchange TokenTags t1 and t2
Definition at line 165 of file TokenEnums.hh.
is_SLASH_or_BACKSLASH()
bool is_SLASH_or_BACKSLASH (TokenTag tag) inline
return true for / ⌿ \ and ⍀
Definition at line 170 of file TokenEnums.hh.
References TOK_OPER1_REDUCE, TOK_OPER1_REDUCE1, TOK_OPER1_SCAN, and TOK_OPER1_SCAN1.
Referenced by Bif_OPER1_EACH::do_eval_LB(), Prefix::reduce_A_M_B_(), Prefix::reduce_A_M_C_B(), and Prefix::reduce_M_M__().