GNUAPL: src/Unicode.hh File Reference
Unicode.hh File Reference
#include "Common.hh"
#include "Avec.def"
Macros
#define char_def(name, uni, _tag, _flags, _av_pos) UNI_ ## name = uni,
#define char_uni(name, uni, _tag, _flags) UNI_ ## name = uni,
Enumerations
enum Unicode {
UNI_NUL = 0x00,
UNI_SOH = 0x01,
UNI_STX = 0x02,
UNI_ETX = 0x03,
UNI_EOT = 0x04,
UNI_ENQ = 0x05,
UNI_ACK = 0x06,
UNI_BEL = 0x07,
UNI_BS = 0x08,
UNI_HT = 0x09,
UNI_LF = 0x0A,
UNI_VT = 0x0B,
UNI_FF = 0x0C,
UNI_CR = 0x0D,
UNI_SO = 0x0E,
UNI_SI = 0x0F,
UNI_DLE = 0x10,
UNI_DC1 = 0x11,
UNI_DC2 = 0x12,
UNI_DC3 = 0x13,
UNI_DC4 = 0x14,
UNI_NAK = 0x15,
UNI_SYN = 0x16,
UNI_ETB = 0x17,
UNI_CAN = 0x18,
UNI_EM = 0x19,
UNI_SUB = 0x1A,
UNI_ESC = 0x1B,
UNI_FS = 0x1C,
UNI_GS = 0x1D,
UNI_RS = 0x1E,
UNI_US = 0x1F,
UNI_SPACE = ' ',
UNI_EXCLAM = '!',
UNI_DOUBLE_QUOTE = '"',
UNI_NUMBER_SIGN = '#',
UNI_DOLLAR_SIGN = '$',
UNI_PERCENT = '',
UNI_AMPERSAND = '&',
UNI_SINGLE_QUOTE = '\'',
UNI_L_PARENT = '(',
UNI_R_PARENT = ')',
UNI_ASTERISK = '*',
UNI_PLUS = '+',
UNI_COMMA = ',',
UNI_MINUS = '-',
UNI_FULLSTOP = '.',
UNI_SLASH = '/',
UNI_0 = '0',
UNI_1 = '1',
UNI_2 = '2',
UNI_3 = '3',
UNI_4 = '4',
UNI_5 = '5',
UNI_6 = '6',
UNI_7 = '7',
UNI_8 = '8',
UNI_9 = '9',
UNI_COLON = ':',
UNI_SEMICOLON = ';',
UNI_LESS = '<',
UNI_EQUAL = '=',
UNI_GREATER = '>',
UNI_QUESTION = '?',
UNI_AT_SIGN = '@',
UNI_A = 'A',
UNI_B = 'B',
UNI_C = 'C',
UNI_D = 'D',
UNI_E = 'E',
UNI_F = 'F',
UNI_G = 'G',
UNI_H = 'H',
UNI_I = 'I',
UNI_J = 'J',
UNI_K = 'K',
UNI_L = 'L',
UNI_M = 'M',
UNI_N = 'N',
UNI_O = 'O',
UNI_P = 'P',
UNI_Q = 'Q',
UNI_R = 'R',
UNI_S = 'S',
UNI_T = 'T',
UNI_U = 'U',
UNI_V = 'V',
UNI_W = 'W',
UNI_X = 'X',
UNI_Y = 'Y',
UNI_Z = 'Z',
UNI_L_BRACK = '[',
UNI_BACKSLASH = '\\',
UNI_R_BRACK = ']',
UNI_CIRCUMFLEX = '^',
UNI_UNDERSCORE = '_',
UNI_ACCENT_GRAVE = '`',
UNI_a = 'a',
UNI_b = 'b',
UNI_c = 'c',
UNI_d = 'd',
UNI_e = 'e',
UNI_f = 'f',
UNI_g = 'g',
UNI_h = 'h',
UNI_i = 'i',
UNI_j = 'j',
UNI_k = 'k',
UNI_l = 'l',
UNI_m = 'm',
UNI_n = 'n',
UNI_o = 'o',
UNI_p = 'p',
UNI_q = 'q',
UNI_r = 'r',
UNI_s = 's',
UNI_t = 't',
UNI_u = 'u',
UNI_v = 'v',
UNI_w = 'w',
UNI_x = 'x',
UNI_y = 'y',
UNI_z = 'z',
UNI_L_CURLY = '{',
UNI_BAR = '|',
UNI_R_CURLY = '}',
UNI_TILDE = '~',
UNI_DELETE = 0x7F,
UNI_NO_BREAK_SPACE = 0x00A0,
UNI_INVERTED_EXCLAM = 0x00A1,
UNI_POUND = 0x00A3,
UNI_YEN = 0x00A5,
UNI_DIAERESIS = 0x00A8,
UNI_OVERBAR = 0x00AF,
UNI_PAD_U2 = 0x00B2,
UNI_PAD_U3 = 0x00B3,
UNI_PAD_U1 = 0x00B9,
UNI_MULTIPLY = 0x00D7,
UNI_DIVIDE = 0x00F7,
UNI_LAMBDA = 0x03BB,
UNI_MUE = 0x03BC,
UNI_CHI = 0x03C7,
UNI_ELEMENT = 0x03F5,
UNI_AV_MAX = 0x0461,
UNI_SINGLE_QUOTE1 = 0x2018,
UNI_SINGLE_QUOTE2 = 0x2019,
UNI_PAD_U0 = 0x2070,
UNI_PAD_U4 = 0x2074,
UNI_PAD_U5 = 0x2075,
UNI_PAD_U6 = 0x2076,
UNI_PAD_U7 = 0x2077,
UNI_PAD_U8 = 0x2078,
UNI_PAD_U9 = 0x2079,
UNI_PAD_Un = 0x207F,
UNI_PAD_L0 = 0x2080,
UNI_PAD_L1 = 0x2081,
UNI_PAD_L2 = 0x2082,
UNI_PAD_L3 = 0x2083,
UNI_PAD_L4 = 0x2084,
UNI_PAD_L5 = 0x2085,
UNI_PAD_L6 = 0x2086,
UNI_PAD_L7 = 0x2087,
UNI_PAD_L8 = 0x2088,
UNI_PAD_L9 = 0x2089,
UNI_PAD_Lk = 0x2096,
UNI_PAD_Ln = 0x2099,
UNI_EURO = 0x20AC,
UNI_LEFT_ARROW = 0x2190,
UNI_UP_ARROW = 0x2191,
UNI_RIGHT_ARROW = 0x2192,
UNI_DOWN_ARROW = 0x2193,
UNI_RIGHT_LEFT_ARROW = 0x21C4,
UNI_DOUBLE_ARROW_L = 0x21E8,
UNI_DELTA = 0x2206,
UNI_NABLA = 0x2207,
UNI_ELEMENT1 = 0x2208,
UNI_ELEMENT2 = 0x220A,
UNI_RING_OPERATOR = 0x2218,
UNI_INFINITY = 0x221E,
UNI_DIVIDES = 0x2223,
UNI_AND = 0x2227,
UNI_OR = 0x2228,
UNI_INTERSECTION = 0x2229,
UNI_UNION = 0x222A,
UNI_DOTTED_DEL = 0x2235,
UNI_TILDE_OPERATOR = 0x223C,
UNI_NOT_EQUAL = 0x2260,
UNI_EQUIVALENT = 0x2261,
UNI_NEQUIVALENT = 0x2262,
UNI_LESS_OR_EQUAL = 0x2264,
UNI_MORE_OR_EQUAL = 0x2265,
UNI_BETWEEN = 0x226C,
UNI_SUBSET = 0x2282,
UNI_SUPERSET = 0x2283,
UNI_CIRCLE_BAR = 0x2296,
UNI_RIGHT_TACK = 0x22A2,
UNI_LEFT_TACK = 0x22A3,
UNI_DOWN_TACK = 0x22A4,
UNI_UP_TACK = 0x22A5,
UNI_STAR_OPERATOR = 0x22C6,
UNI_EPSILON_UBAR = 0x22F8,
UNI_LEFT_CEILING = 0x2308,
UNI_LEFT_FLOOR = 0x230A,
UNI_I_BEAM = 0x2336,
UNI_SQUISH_Quad = 0x2337,
UNI_Quad_EQUAL = 0x2338,
UNI_Quad_DIVIDE = 0x2339,
UNI_Quad_DIAMOND = 0x233A,
UNI_Quad_JOT = 0x233B,
UNI_Quad_CIRCLE = 0x233C,
UNI_CIRCLE_STILE = 0x233D,
UNI_CIRCLE_JOT = 0x233E,
UNI_SLASH_BAR = 0x233F,
UNI_BACKSLASH_BAR = 0x2340,
UNI_Quad_SLASH = 0x2341,
UNI_Quad_BACKSLASH = 0x2342,
UNI_Quad_LESS_THAN = 0x2343,
UNI_Quad_GREATER_THAN = 0x2344,
UNI_LEFT_VANE = 0x2345,
UNI_RIGHT_VANE = 0x2346,
UNI_Quad_LEFT_ARROW = 0x2347,
UNI_Quad_RIGHT_ARROW = 0x2348,
UNI_TRANSPOSE = 0x2349,
UNI_DTACK_UNDERBAR = 0x234A,
UNI_SORT_ASCENDING = 0x234B,
UNI_Quad_DELTA = 0x234D,
UNI_EXECUTE = 0x234E,
UNI_UP_VANE = 0x234F,
UNI_Quad_UP_ARROW = 0x2350,
UNI_UP_TACK_OVERBAR = 0x2351,
UNI_SORT_DECENDING = 0x2352,
UNI_FORMAT = 0x2355,
UNI_DOWN_VANE = 0x2356,
UNI_Quad_DOWN_ARROW = 0x2357,
UNI_QUOTE_UNDERBAR = 0x2358,
UNI_DELTA_UNDERBAR = 0x2359,
UNI_DIAMOND_UNDERBAR = 0x235A,
UNI_JOT_UNDERBAR = 0x235B,
UNI_CIRCLE_UNDERBAR = 0x235C,
UNI_COMMENT = 0x235D,
UNI_QUOTE_Quad = 0x235E,
UNI_LOGARITHM = 0x235F,
UNI_Quad_COLON = 0x2360,
UNI_UTACK_DIAERESIS = 0x2361,
UNI_DEL_DIAERESIS = 0x2362,
UNI_STAR_DIAERESIS = 0x2363,
UNI_JOT_DIARESIS = 0x2364,
UNI_CIRCLE_DIARESIS = 0x2365,
UNI_DOWN_SHOE_STILE = 0x2366,
UNI_LEFT_SHOE_STILE = 0x2367,
UNI_TILDE_DIAERESIS = 0x2368,
UNI_GT_THAN_DIAERESIS = 0x2369,
UNI_COMMA_BAR = 0x236A,
UNI_DEL_TILDE = 0x236B,
UNI_ZILDE = 0x236C,
UNI_STILE_TILDE = 0x236D,
UNI_SEMICOL_UNDERBAR = 0x236E,
UNI_Quad_NOT_EQUAL = 0x236F,
UNI_Quad_QUEST_MARK = 0x2370,
UNI_NOR = 0x2371,
UNI_NAND = 0x2372,
UNI_IOTA = 0x2373,
UNI_RHO = 0x2374,
UNI_OMEGA = 0x2375,
UNI_ALPHA_UNDERBAR = 0x2376,
UNI_EPSILON_UNDERBAR = 0x2377,
UNI_INDEX_UNDERBAR = 0x2378,
UNI_OMEGA_UNDERBAR = 0x2379,
UNI_ALPHA = 0x237A,
UNI_Quad_Quad = 0x2395,
UNI_LINE_HORI = 0x2500,
UNI_LINE_HORI2 = 0x2501,
UNI_LINE_VERT = 0x2502,
UNI_LINE_VERT2 = 0x2503,
UNI_LINE_DOWN_RIGHT = 0x250C,
UNI_LINE_DOWN2_RIGHT2 = 0x250F,
UNI_LINE_DOWN_LEFT = 0x2510,
UNI_LINE_DOWN2_LEFT2 = 0x2513,
UNI_LINE_UP_RIGHT = 0x2514,
UNI_LINE_UP2_RIGHT2 = 0x2517,
UNI_LINE_UP_LEFT = 0x2518,
UNI_LINE_UP2_LEFT2 = 0x251B,
UNI_LINE_VERT_RIGHT = 0x251C,
UNI_LINE_VERT_LEFT = 0x2524,
UNI_LINE_DOWN_HORI = 0x252C,
UNI_LINE_UP_HORI = 0x2534,
UNI_LINE_VERT_HORI = 0x253C,
UNI_LINE2_HORI = 0x2550,
UNI_LINE2_VERT = 0x2551,
UNI_LINE2_DOWN_RIGHT = 0x2554,
UNI_LINE2_DOWN_LEFT = 0x2557,
UNI_LINE2_UP_RIGHT = 0x255A,
UNI_LINE2_UP_LEFT = 0x255D,
UNI_LINE2_VERT_RIGHT = 0x2560,
UNI_LINE2_VERT_LEFT = 0x2563,
UNI_LINE2_HORI_DOWN = 0x2566,
UNI_LINE2_HORI_UP = 0x2569,
UNI_LINE2_VERT_HORI = 0x256C,
UNI_UPPER_HALF_BLOCK = 0x2580,
UNI_LOWER_HALF_BLOCK = 0x2584,
UNI_FULL_BLOCK = 0x2588,
UNI_LEFT_HALF_BLOCK = 0x258C,
UNI_Quad_Quad1 = 0x25AF,
UNI_RIGHT_HALF_BLOCK = 0x2590,
UNI_DIAMOND = 0x25CA,
UNI_CIRCLE = 0x25CB,
Unicode_0 = 0,
Invalid_Unicode = 0x55AA55AA,
UNI_EOF = -1,
UNI_CursorUp = -2,
UNI_CursorDown = -3,
UNI_CursorRight = -4,
UNI_CursorLeft = -5,
UNI_CursorEnd = -6,
UNI_CursorHome = -7,
UNI_InsertMode = -8,
UNI_iPAD_U2 = 0xEEEE,
UNI_iPAD_U3 = 0xEEEF,
UNI_iPAD_U1 = 0xEEF0,
UNI_iPAD_U0 = 0xEEF1,
UNI_iPAD_U4 = 0xEEF2,
UNI_iPAD_U5 = 0xEEF3,
UNI_iPAD_U6 = 0xEEF4,
UNI_iPAD_U7 = 0xEEF5,
UNI_iPAD_U8 = 0xEEF6,
UNI_iPAD_U9 = 0xEEF7,
UNI_iPAD_L0 = 0xEEF8,
UNI_iPAD_L1 = 0xEEF9,
UNI_iPAD_L2 = 0xEEFA,
UNI_iPAD_L3 = 0xEEFB,
UNI_iPAD_L4 = 0xEEFC,
UNI_iPAD_L5 = 0xEEFD,
UNI_iPAD_L9 = 0xEEFE
}
One Unicode character.
Functions
int nibble (Unicode uni)
value 0-15 of hex digit, or -1 if uni not in "023456789ABCDEFabcdef"
int sixbit (Unicode uni)
value 0-63 of base64 digit, or -1 if uni not base64 (RFC 4648)
void Hswap (Unicode &u1, Unicode &u2)
Macro Definition Documentation
char_def
#define char_def (name, uni, _tag, _flags, _av_pos) UNI_ ## name = uni,
Definition at line 33 of file Unicode.hh.
char_uni
#define char_uni (name, uni, _tag, _flags) UNI_ ## name = uni,
Definition at line 34 of file Unicode.hh.
Enumeration Type Documentation
Unicode
enum Unicode
One Unicode character.
Enumerator
UNI_NUL
The characters used in the interpreter.
Macro char_def(, xx) defines characters in ⎕AV which have APL relevance.
Macro char_def(, 0xx) defines characters in ⎕AV without APL relevance. These characters come from the IBM APL2 Workstation ⎕AV and are subject to being removed in favour of new APL characters with APL relevance.
Macro char_uni() defines characters not in ⎕AV, have no APL relevance, but were declared as members UNI_xxx in enum Unicode so that they can be referenced with name in the C++ source files.
UNI_SOH
UNI_STX
UNI_ETX
UNI_EOT
UNI_ENQ
UNI_ACK
UNI_BEL
UNI_BS
UNI_HT
UNI_LF
UNI_VT
UNI_FF
UNI_CR
UNI_SO
UNI_SI
UNI_DLE
UNI_DC1
UNI_DC2
UNI_DC3
UNI_DC4
UNI_NAK
UNI_SYN
UNI_ETB
UNI_CAN
UNI_EM
UNI_SUB
UNI_ESC
UNI_FS
UNI_GS
UNI_RS
UNI_US
UNI_SPACE
UNI_EXCLAM
UNI_DOUBLE_QUOTE
UNI_NUMBER_SIGN
UNI_DOLLAR_SIGN
UNI_PERCENT
UNI_AMPERSAND
UNI_SINGLE_QUOTE
UNI_L_PARENT
UNI_R_PARENT
UNI_ASTERISK
UNI_PLUS
UNI_COMMA
UNI_MINUS
UNI_FULLSTOP
UNI_SLASH
UNI_0
UNI_1
UNI_2
UNI_3
UNI_4
UNI_5
UNI_6
UNI_7
UNI_8
UNI_9
UNI_COLON
UNI_SEMICOLON
UNI_LESS
UNI_EQUAL
UNI_GREATER
UNI_QUESTION
UNI_AT_SIGN
UNI_A
UNI_B
UNI_C
UNI_D
UNI_E
UNI_F
UNI_G
UNI_H
UNI_I
UNI_J
UNI_K
UNI_L
UNI_M
UNI_N
UNI_O
UNI_P
UNI_Q
UNI_R
UNI_S
UNI_T
UNI_U
UNI_V
UNI_W
UNI_X
UNI_Y
UNI_Z
UNI_L_BRACK
UNI_BACKSLASH
UNI_R_BRACK
UNI_CIRCUMFLEX
UNI_UNDERSCORE
UNI_ACCENT_GRAVE
UNI_a
UNI_b
UNI_c
UNI_d
UNI_e
UNI_f
UNI_g
UNI_h
UNI_i
UNI_j
UNI_k
UNI_l
UNI_m
UNI_n
UNI_o
UNI_p
UNI_q
UNI_r
UNI_s
UNI_t
UNI_u
UNI_v
UNI_w
UNI_x
UNI_y
UNI_z
UNI_L_CURLY
UNI_BAR
UNI_R_CURLY
UNI_TILDE
UNI_DELETE
UNI_NO_BREAK_SPACE
UNI_INVERTED_EXCLAM
UNI_POUND
UNI_YEN
UNI_DIAERESIS
UNI_OVERBAR
UNI_PAD_U2
UNI_PAD_U3
UNI_PAD_U1
UNI_MULTIPLY
UNI_DIVIDE
UNI_LAMBDA
UNI_MUE
UNI_CHI
UNI_ELEMENT
UNI_AV_MAX
UNI_SINGLE_QUOTE1
UNI_SINGLE_QUOTE2
UNI_PAD_U0
UNI_PAD_U4
UNI_PAD_U5
UNI_PAD_U6
UNI_PAD_U7
UNI_PAD_U8
UNI_PAD_U9
UNI_PAD_Un
UNI_PAD_L0
UNI_PAD_L1
UNI_PAD_L2
UNI_PAD_L3
UNI_PAD_L4
UNI_PAD_L5
UNI_PAD_L6
UNI_PAD_L7
UNI_PAD_L8
UNI_PAD_L9
UNI_PAD_Lk
UNI_PAD_Ln
UNI_EURO
UNI_LEFT_ARROW
UNI_UP_ARROW
UNI_RIGHT_ARROW
UNI_DOWN_ARROW
UNI_RIGHT_LEFT_ARROW
UNI_DOUBLE_ARROW_L
UNI_DELTA
UNI_NABLA
UNI_ELEMENT1
UNI_ELEMENT2
UNI_RING_OPERATOR
UNI_INFINITY
UNI_DIVIDES
UNI_AND
UNI_OR
UNI_INTERSECTION
UNI_UNION
UNI_DOTTED_DEL
UNI_TILDE_OPERATOR
UNI_NOT_EQUAL
UNI_EQUIVALENT
UNI_NEQUIVALENT
UNI_LESS_OR_EQUAL
UNI_MORE_OR_EQUAL
UNI_BETWEEN
UNI_SUBSET
UNI_SUPERSET
UNI_CIRCLE_BAR
UNI_RIGHT_TACK
UNI_LEFT_TACK
UNI_DOWN_TACK
UNI_UP_TACK
UNI_STAR_OPERATOR
UNI_EPSILON_UBAR
UNI_LEFT_CEILING
UNI_LEFT_FLOOR
UNI_I_BEAM
UNI_SQUISH_Quad
UNI_Quad_EQUAL
UNI_Quad_DIVIDE
UNI_Quad_DIAMOND
UNI_Quad_JOT
UNI_Quad_CIRCLE
UNI_CIRCLE_STILE
UNI_CIRCLE_JOT
UNI_SLASH_BAR
UNI_BACKSLASH_BAR
UNI_Quad_SLASH
UNI_Quad_BACKSLASH
UNI_Quad_LESS_THAN
UNI_Quad_GREATER_THAN
UNI_LEFT_VANE
UNI_RIGHT_VANE
UNI_Quad_LEFT_ARROW
UNI_Quad_RIGHT_ARROW
UNI_TRANSPOSE
UNI_DTACK_UNDERBAR
UNI_SORT_ASCENDING
UNI_Quad_DELTA
UNI_EXECUTE
UNI_UP_VANE
UNI_Quad_UP_ARROW
UNI_UP_TACK_OVERBAR
UNI_SORT_DECENDING
UNI_FORMAT
UNI_DOWN_VANE
UNI_Quad_DOWN_ARROW
UNI_QUOTE_UNDERBAR
UNI_DELTA_UNDERBAR
UNI_DIAMOND_UNDERBAR
UNI_JOT_UNDERBAR
UNI_CIRCLE_UNDERBAR
UNI_COMMENT
UNI_QUOTE_Quad
UNI_LOGARITHM
UNI_Quad_COLON
UNI_UTACK_DIAERESIS
UNI_DEL_DIAERESIS
UNI_STAR_DIAERESIS
UNI_JOT_DIARESIS
UNI_CIRCLE_DIARESIS
UNI_DOWN_SHOE_STILE
UNI_LEFT_SHOE_STILE
UNI_TILDE_DIAERESIS
UNI_GT_THAN_DIAERESIS
UNI_COMMA_BAR
UNI_DEL_TILDE
UNI_ZILDE
UNI_STILE_TILDE
UNI_SEMICOL_UNDERBAR
UNI_Quad_NOT_EQUAL
UNI_Quad_QUEST_MARK
UNI_NOR
UNI_NAND
UNI_IOTA
UNI_RHO
UNI_OMEGA
UNI_ALPHA_UNDERBAR
UNI_EPSILON_UNDERBAR
UNI_INDEX_UNDERBAR
UNI_OMEGA_UNDERBAR
UNI_ALPHA
UNI_Quad_Quad
UNI_LINE_HORI
UNI_LINE_HORI2
UNI_LINE_VERT
UNI_LINE_VERT2
UNI_LINE_DOWN_RIGHT
UNI_LINE_DOWN2_RIGHT2
UNI_LINE_DOWN_LEFT
UNI_LINE_DOWN2_LEFT2
UNI_LINE_UP_RIGHT
UNI_LINE_UP2_RIGHT2
UNI_LINE_UP_LEFT
UNI_LINE_UP2_LEFT2
UNI_LINE_VERT_RIGHT
UNI_LINE_VERT_LEFT
UNI_LINE_DOWN_HORI
UNI_LINE_UP_HORI
UNI_LINE_VERT_HORI
UNI_LINE2_HORI
UNI_LINE2_VERT
UNI_LINE2_DOWN_RIGHT
UNI_LINE2_DOWN_LEFT
UNI_LINE2_UP_RIGHT
UNI_LINE2_UP_LEFT
UNI_LINE2_VERT_RIGHT
UNI_LINE2_VERT_LEFT
UNI_LINE2_HORI_DOWN
UNI_LINE2_HORI_UP
UNI_LINE2_VERT_HORI
UNI_UPPER_HALF_BLOCK
UNI_LOWER_HALF_BLOCK
UNI_FULL_BLOCK
UNI_LEFT_HALF_BLOCK
UNI_Quad_Quad1
UNI_RIGHT_HALF_BLOCK
UNI_DIAMOND
UNI_CIRCLE
Unicode_0
End of unicode string.
Invalid_Unicode
An invalid Unicode.
UNI_EOF
UNI_CursorUp
UNI_CursorDown
UNI_CursorRight
UNI_CursorLeft
UNI_CursorEnd
UNI_CursorHome
UNI_InsertMode
UNI_iPAD_U2
internal pad characters - will be removed before printout
UNI_iPAD_U3
UNI_iPAD_U1
UNI_iPAD_U0
UNI_iPAD_U4
UNI_iPAD_U5
UNI_iPAD_U6
UNI_iPAD_U7
UNI_iPAD_U8
UNI_iPAD_U9
UNI_iPAD_L0
UNI_iPAD_L1
UNI_iPAD_L2
UNI_iPAD_L3
UNI_iPAD_L4
UNI_iPAD_L5
UNI_iPAD_L9
Definition at line 31 of file Unicode.hh.
Function Documentation
Hswap()
void Hswap (Unicode & u1, Unicode & u2) inline
Definition at line 102 of file Unicode.hh.
nibble()
int nibble (Unicode uni)
value 0-15 of hex digit, or -1 if uni not in "023456789ABCDEFabcdef"
Definition at line 294 of file Common.cc.
References UNI_0, UNI_9, UNI_A, UNI_a, UNI_F, and UNI_f.
Referenced by Quad_CR::do_CR13(), and Quad_CR::do_CR15().
sixbit()
int sixbit (Unicode uni)
value 0-63 of base64 digit, or -1 if uni not base64 (RFC 4648)
Definition at line 308 of file Common.cc.
References UNI_0, UNI_9, UNI_A, UNI_a, UNI_EQUAL, UNI_MINUS, UNI_PLUS, UNI_SLASH, UNI_UNDERSCORE, UNI_Z, and UNI_z.
Referenced by Quad_CR::do_CR17().