GNUAPL: src/UTF8_string.hh File Reference
UTF8_string.hh File Reference
#include <iostream>
#include <stdint.h>
#include <string>
#include "Common.hh"
Classes
class UTF8_string
an UTF8 encoded Unicode (RFC 3629) string
class UTF8_filebuf
A UTF8 string to be used as filebuf in UTF8_ostream.
class UTF8_ostream
a UTF8 string that can be used as ostream
Typedefs
typedef uint8_t UTF8
one byte of a UTF8 encoded Unicode (RFC 3629) string
Functions
const UTF8 * utf8P (const void *vp)
frequently used cast to const UTF8 *
UTF8 * utf8P (char *cp)
frequently used cast to UTF8 *
Typedef Documentation
UTF8
typedef uint8_t UTF8
one byte of a UTF8 encoded Unicode (RFC 3629) string
Definition at line 33 of file UTF8_string.hh.
Function Documentation
utf8P() [1/2]
const UTF8* utf8P (const void * vp) inline
frequently used cast to const UTF8 *
Definition at line 42 of file UTF8_string.hh.
Referenced by UCS_string::append_UTF8(), CDR_header::get_nb(), CDR_header::get_nelm(), UserFunction::load(), Workspace::load_WS(), DiffOut::overflow(), XML_Loading_Archive::read_Cells(), XML_Loading_Archive::read_Token(), XML_Loading_Archive::read_XML_string(), XML_Loading_Archive::reset(), ucs_string_from_string(), UTF8_to_Unicode(), and XML_Loading_Archive::XML_Loading_Archive().
utf8P() [2/2]
UTF8* utf8P (char * cp) inline
frequently used cast to UTF8 *
Definition at line 49 of file UTF8_string.hh.