GNUAPL: src/Value.hh File Reference
Value.hh File Reference
#include "CharCell.hh"
#include "ComplexCell.hh"
#include "DynamicObject.hh"
#include "FloatCell.hh"
#include "IntCell.hh"
#include "LvalCell.hh"
#include "NumericCell.hh"
#include "PointerCell.hh"
#include "Shape.hh"
#include "Value_P.hh"
#include "Value.icc"
#include "Value_P.icc"
Classes
struct _deleted_value
a linked list of deleted values
class Value
An APL Value (essentially a Shape and a ravel)
Macros
#define _LOC
maybe enable LOC for set/clear of flags
#define _loc
#define _loc_type
#define FLAG_TRACE(_f, _b)
#define set_member() SET_member(_LOC)
#define set_packed() SET_packed(_LOC)
#define clear_packed() CLEAR_packed(_LOC)
#define set_complete() SET_complete(_LOC)
#define set_marked() SET_marked(_LOC)
#define clear_marked() CLEAR_marked(_LOC)
#define NEW_CLONE
#define CLONE_P(B_P, L) (B_P)
clone, given a Value_P. Result is a Value_P.
#define CLONE(pB, L) Value_P(const_cast<Value *>(pB), L)
clone, given a const Value *. Result is a Value_P.
Functions
void print_history (ostream &out, const Value &val, const char *loc)
Value_P IntScalar (APL_Integer val, const char *loc)
integer scalar
Value_P FloatScalar (APL_Float val, const char *loc)
floating-point scalar
Value_P CharScalar (Unicode uni, const char *loc)
character scalar
Value_P ComplexScalar (APL_Complex cpx, const char *loc)
complex scalars
Value_P ComplexScalar (APL_Float real, APL_Float imag, const char *loc)
Value_P Idx0 (const char *loc)
⍳0 (aka. ⍬)
Value_P Str0 (const char *loc)
''
Value_P Str0_0 (const char *loc)
0 0⍴''
Value_P Idx0_0 (const char *loc)
0 0⍴0
Value_P EmptyStruct (const char *loc)
empty struct
Macro Definition Documentation
_LOC
#define _LOC
maybe enable LOC for set/clear of flags
Definition at line 625 of file Value.hh.
_loc
#define _loc
Definition at line 626 of file Value.hh.
_loc_type
#define _loc_type
Definition at line 627 of file Value.hh.
clear_marked
#define clear_marked () CLEAR_marked(_LOC)
Definition at line 688 of file Value.hh.
Referenced by Value::unmark().
clear_packed
#define clear_packed () CLEAR_packed(_LOC)
Definition at line 661 of file Value.hh.
Referenced by Value::explode().
CLONE
#define CLONE (pB, L) Value_P(const_cast<Value *>(pB), L)
clone, given a const Value *. Result is a Value_P.
Definition at line 736 of file Value.hh.
Referenced by Quad_CR::do_CR30(), Quad_FX::do_native_FX(), Value::index(), Quad_XML::next_member(), set_value(), and Bif_F12_TRANSPOSE::transpose().
CLONE_P
#define CLONE_P (B_P, L) (B_P)
clone, given a Value_P. Result is a Value_P.
Definition at line 733 of file Value.hh.
Referenced by Symbol::assign(), Quad_CR::do_CR30(), Quad_CR::do_CR31_32(), Bif_F12_PARTITION::do_eval_B(), ScalarFunction::do_scalar_B(), Bif_F12_TAKE::eval_AB(), Bif_F2_INDEX::eval_AB(), Bif_F12_TRANSPOSE::eval_AB(), Bif_F12_TAKE::eval_AXB(), Bif_F12_DROP::eval_AXB(), Bif_F2_INDEX::eval_AXB(), Bif_F2_RIGHT::eval_AXB(), Bif_F12_UNION::eval_B(), UserFunction::eval_fill_AB(), UserFunction::eval_fill_B(), Quad_ES::event_simulate(), Value::index(), PointerCell::init_other(), Bif_F12_PICK::pick(), Bif_COMMA::ravel_axis(), Bif_REDUCE::reduce(), Prefix::reduce_D_V__(), Bif_REDUCE::reduce_n_wise(), Symbol::resolve(), Bif_ROTATE::reverse(), Bif_ROTATE::rotate(), and Bif_SCAN::scan().
FLAG_TRACE
#define FLAG_TRACE (_f, _b)
Definition at line 633 of file Value.hh.
Referenced by Value::CLEAR_marked(), Value::CLEAR_packed(), Value::SET_complete(), Value::SET_marked(), Value::SET_member(), and Value::SET_packed().
NEW_CLONE
#define NEW_CLONE
macro NEW_CLONE selects one of two clone() schemes:
the old scheme (with # undef NEW_CLONE) clones values early, so that: 1a. Different PointerCells always point to different Sub-Values, and 1b. Arguments of defined functions are different in the caller and in the callee, and 1c. Values may be cloned without need.
the new scheme (with # define NEW_CLONE) clones Values late, so that 2a. Different PointerCells (of the same or even of different Values) may point to the same Sub-Value, and 2b. Arguments of defined functions are different in the caller and in the callee are the same as long as they are not modified, and 2c. A Value is only cloned before it is being modified and only if it has more than one owner.
Definition at line 728 of file Value.hh.
set_complete
#define set_complete () SET_complete(_LOC)
Definition at line 671 of file Value.hh.
Referenced by Value::check_value(), and Value::Value().
set_marked
#define set_marked () SET_marked(_LOC)
Definition at line 687 of file Value.hh.
set_member
#define set_member () SET_member(_LOC)
Definition at line 644 of file Value.hh.
set_packed
#define set_packed () SET_packed(_LOC)
Definition at line 660 of file Value.hh.
Function Documentation
CharScalar()
Value_P CharScalar (Unicode uni, const char * loc)
character scalar
Definition at line 2953 of file Value.cc.
Referenced by Value::operator&(), Value::prototype(), Quad_PR::push(), and Quad_PR::Quad_PR().
ComplexScalar() [1/2]
Value_P ComplexScalar (APL_Complex cpx, const char * loc)
complex scalars
Definition at line 2935 of file Value.cc.
Referenced by Parser::create_scalar_value(), and Value::operator&().
ComplexScalar() [2/2]
Value_P ComplexScalar (APL_Float real, APL_Float imag, const char * loc)
Definition at line 2944 of file Value.cc.
EmptyStruct()
Value_P EmptyStruct (const char * loc)
empty struct
Definition at line 2999 of file Value.cc.
References LOC, and loop.
Referenced by Quad_CR::do_CR38(), Value::get_member(), Value::operator&(), Quad_JSON::parse_object(), XML_node::parse_tag(), Prefix::reduce_D_V__(), and Quad_XML::XML_to_APL().
FloatScalar()
Value_P FloatScalar (APL_Float val, const char * loc)
floating-point scalar
Definition at line 2926 of file Value.cc.
References LOC.
Referenced by Quad_CT::assign(), Parser::create_scalar_value(), Quad_DL::eval_B(), Quad_SVE::get_apl_value(), Value::operator&(), Quad_CT::push(), Quad_TZ::push(), Quad_CT::Quad_CT(), and Quad_TZ::Quad_TZ().
Idx0()
Value_P Idx0 (const char * loc)
⍳0 (aka. ⍬)
Definition at line 2962 of file Value.cc.
Referenced by Quad_CR::do_CR41(), Quad_DLX::do_DLX(), Bif_F0_ZILDE::eval_(), Quad_PLOT::eval_AB(), Bif_F12_INDEX_OF::eval_B(), Quad_EC::eval_fill_B(), Value::index(), Value::operator&(), Quad_JSON::parse_array(), run_generic(), run_transaction_begin(), run_transaction_commit(), run_transaction_rollback(), show_cols(), show_tables(), Bif_F12_SORT::sort(), Bif_F12_SORT::sort_collating(), and Tokenizer::tokenize_function().
Idx0_0()
Value_P Idx0_0 (const char * loc)
0 0⍴0
Definition at line 2990 of file Value.cc.
Referenced by Quad_EC::eoc(), and Value::operator&().
IntScalar()
Value_P IntScalar (APL_Integer val, const char * loc)
integer scalar
Definition at line 2917 of file Value.cc.
References LOC.
Referenced by Quad_RL::assign(), Quad_IO::assign(), Quad_PP::assign(), Quad_PW::assign(), Quad_SYL::assign(), Parser::create_scalar_value(), Quad_FX::do_native_FX(), Quad_FIO::do_printf(), Quad_FIO::eval_AB(), Quad_PLOT::eval_AB(), Bif_F2_INDEX::eval_AB(), Bif_F12_EQUIV::eval_AB(), Bif_F12_NEQUIV::eval_AB(), Quad_FIO::eval_ALXB(), Quad_FIO::eval_AXB(), Bif_F2_INDEX::eval_AXB(), Quad_FIO::eval_B(), Bif_F12_EQUIV::eval_B(), Bif_F12_NEQUIV::eval_B(), Bif_F2_LEFT::eval_B(), Bif_OPER2_POWER::eval_form_1(), Quad_FIO::eval_LXB(), Quad_FIO::eval_XB(), Command::finish_context(), Quad_SVE::get_apl_value(), Quad_WA::get_apl_value(), Quad_FIO::get_random(), open_database(), Value::operator&(), Value::prototype(), Quad_RL::push(), Quad_IO::push(), Quad_PP::push(), Quad_PS::push(), Quad_PW::push(), Quad_TZ::push(), Quad_IO::Quad_IO(), Quad_L::Quad_L(), Quad_LC::Quad_LC(), Quad_PP::Quad_PP(), Quad_PW::Quad_PW(), Quad_R::Quad_R(), Quad_SVE::Quad_SVE(), Quad_TS::Quad_TS(), Quad_TZ::Quad_TZ(), Quad_WA::Quad_WA(), Quad_X::Quad_X(), Prefix::reduce_D_V__(), Prefix::reduce_END_A_GOTO_B(), Prefix::reduce_MISC_F_B_(), Bif_REDUCE::reduce_n_wise(), Symbol::resolve(), Workspace::set_PW(), and Bif_F12_SORT::sort_collating().
print_history()
void print_history (ostream & out, const Value & val, const char * loc)
Referenced by Value::operator&(), XML_Saving_Archive::save(), and VH_entry::VH_entry().
Str0()
Value_P Str0 (const char * loc)
''
Definition at line 2971 of file Value.cc.
References LOC.
Referenced by close_database(), Quad_CR::do_CR17(), Quad_CR::do_CR35(), Quad_RE::eval_AB(), list_functions(), Quad_CR::list_functions(), Quad_FIO::list_functions(), Quad_XML::next_member(), Value::operator&(), Quad_LX::Quad_LX(), show_cols(), Quad_TF::tf1(), Quad_TF::tf2(), and Quad_TF::tf3().
Str0_0()
Value_P Str0_0 (const char * loc)
0 0⍴''
Definition at line 2980 of file Value.cc.
Referenced by Quad_CR::do_eval_B(), Quad_NL::do_quad_NL(), and Value::operator&().