GNUAPL: src/Value.cc File Reference
Value.cc File Reference
#include <sys/types.h>
#include <vector>
#include "Bif_F12_PARTITION_PICK.hh"
#include "CDR_string.hh"
#include "CharCell.hh"
#include "ComplexCell.hh"
#include "Common.hh"
#include "Error.hh"
#include "FloatCell.hh"
#include "IndexExpr.hh"
#include "IndexIterator.hh"
#include "IntCell.hh"
#include "IO_Files.hh"
#include "LvalCell.hh"
#include "Macro.hh"
#include "Output.hh"
#include "PointerCell.hh"
#include "Parallel.hh"
#include "PrintOperator.hh"
#include "Quad_XML.hh"
#include "SystemVariable.hh"
#include "UCS_string.hh"
#include "UserFunction.hh"
#include "Value.hh"
#include "ValueHistory.hh"
#include "Workspace.hh"
Functions
uint64_t top_of_memory ()
our sbrk() so that it compiles under Apple OS X
ostream & operator<< (ostream &out, const Value &v)
Value_P IntScalar (APL_Integer val, const char *loc)
integer scalar
Value_P FloatScalar (APL_Float val, const char *loc)
floating-point scalar
Value_P ComplexScalar (APL_Complex val, const char *loc)
complex scalars
Value_P ComplexScalar (APL_Float real, APL_Float imag, const char *loc)
Value_P CharScalar (Unicode uni, const char *loc)
character scalar
Value_P Idx0 (const char *loc)
⍳0 (aka. ⍬)
Value_P Str0 (const char *loc)
''
Value_P Str0_0 (const char *loc)
0 0⍴''
Value_P Idx0_0 (const char *loc)
0 0⍴0
Value_P EmptyStruct (const char *loc)
empty struct
ostream & operator<< (ostream &out, const AP_num3 &ap3)
Function Documentation
CharScalar()
Value_P CharScalar (Unicode uni, const char * loc)
character scalar
Definition at line 2953 of file Value.cc.
Referenced by Value::operator&(), Value::prototype(), Quad_PR::push(), and Quad_PR::Quad_PR().
ComplexScalar() [1/2]
Value_P ComplexScalar (APL_Complex val, const char * loc)
complex scalars
Definition at line 2935 of file Value.cc.
Referenced by Parser::create_scalar_value(), and Value::operator&().
ComplexScalar() [2/2]
Value_P ComplexScalar (APL_Float real, APL_Float imag, const char * loc)
Definition at line 2944 of file Value.cc.
EmptyStruct()
Value_P EmptyStruct (const char * loc)
empty struct
Definition at line 2999 of file Value.cc.
References LOC, and loop.
Referenced by Quad_CR::do_CR38(), Value::get_member(), Value::operator&(), Quad_JSON::parse_object(), XML_node::parse_tag(), Prefix::reduce_D_V__(), and Quad_XML::XML_to_APL().
FloatScalar()
Value_P FloatScalar (APL_Float val, const char * loc)
floating-point scalar
Definition at line 2926 of file Value.cc.
References LOC.
Referenced by Quad_CT::assign(), Parser::create_scalar_value(), Quad_DL::eval_B(), Quad_SVE::get_apl_value(), Value::operator&(), Quad_CT::push(), Quad_TZ::push(), Quad_CT::Quad_CT(), and Quad_TZ::Quad_TZ().
Idx0()
Value_P Idx0 (const char * loc)
⍳0 (aka. ⍬)
Definition at line 2962 of file Value.cc.
Referenced by Quad_CR::do_CR41(), Quad_DLX::do_DLX(), Bif_F0_ZILDE::eval_(), Quad_PLOT::eval_AB(), Bif_F12_INDEX_OF::eval_B(), Quad_EC::eval_fill_B(), Value::index(), Value::operator&(), Quad_JSON::parse_array(), run_generic(), run_transaction_begin(), run_transaction_commit(), run_transaction_rollback(), show_cols(), show_tables(), Bif_F12_SORT::sort(), Bif_F12_SORT::sort_collating(), and Tokenizer::tokenize_function().
Idx0_0()
Value_P Idx0_0 (const char * loc)
0 0⍴0
Definition at line 2990 of file Value.cc.
Referenced by Quad_EC::eoc(), and Value::operator&().
IntScalar()
Value_P IntScalar (APL_Integer val, const char * loc)
integer scalar
Definition at line 2917 of file Value.cc.
References LOC.
Referenced by Quad_RL::assign(), Quad_IO::assign(), Quad_PP::assign(), Quad_PW::assign(), Quad_SYL::assign(), Parser::create_scalar_value(), Quad_FX::do_native_FX(), Quad_FIO::do_printf(), Quad_FIO::eval_AB(), Quad_PLOT::eval_AB(), Bif_F2_INDEX::eval_AB(), Bif_F12_EQUIV::eval_AB(), Bif_F12_NEQUIV::eval_AB(), Quad_FIO::eval_ALXB(), Quad_FIO::eval_AXB(), Bif_F2_INDEX::eval_AXB(), Quad_FIO::eval_B(), Bif_F12_EQUIV::eval_B(), Bif_F12_NEQUIV::eval_B(), Bif_F2_LEFT::eval_B(), Bif_OPER2_POWER::eval_form_1(), Quad_FIO::eval_LXB(), Quad_FIO::eval_XB(), Command::finish_context(), Quad_SVE::get_apl_value(), Quad_WA::get_apl_value(), Quad_FIO::get_random(), open_database(), Value::operator&(), Value::prototype(), Quad_RL::push(), Quad_IO::push(), Quad_PP::push(), Quad_PS::push(), Quad_PW::push(), Quad_TZ::push(), Quad_IO::Quad_IO(), Quad_L::Quad_L(), Quad_LC::Quad_LC(), Quad_PP::Quad_PP(), Quad_PW::Quad_PW(), Quad_R::Quad_R(), Quad_SVE::Quad_SVE(), Quad_TS::Quad_TS(), Quad_TZ::Quad_TZ(), Quad_WA::Quad_WA(), Quad_X::Quad_X(), Prefix::reduce_D_V__(), Prefix::reduce_END_A_GOTO_B(), Prefix::reduce_MISC_F_B_(), Bif_REDUCE::reduce_n_wise(), Symbol::resolve(), Workspace::set_PW(), and Bif_F12_SORT::sort_collating().
operator<<() [1/2]
ostream& operator<< (ostream & out, const Value & v)
Definition at line 2910 of file Value.cc.
References Value::print().
operator<<() [2/2]
ostream& operator<< (ostream & out, const AP_num3 & ap3)
Definition at line 3015 of file Value.cc.
References AP_num3::grand, AP_num3::parent, and AP_num3::proc.
Str0()
Value_P Str0 (const char * loc)
''
Definition at line 2971 of file Value.cc.
References LOC.
Referenced by close_database(), Quad_CR::do_CR17(), Quad_CR::do_CR35(), Quad_RE::eval_AB(), list_functions(), Quad_CR::list_functions(), Quad_FIO::list_functions(), Quad_XML::next_member(), Value::operator&(), Quad_LX::Quad_LX(), show_cols(), Quad_TF::tf1(), Quad_TF::tf2(), and Quad_TF::tf3().
Str0_0()
Value_P Str0_0 (const char * loc)
0 0⍴''
Definition at line 2980 of file Value.cc.
Referenced by Quad_CR::do_eval_B(), Quad_NL::do_quad_NL(), and Value::operator&().
top_of_memory()
uint64_t top_of_memory ()
our sbrk() so that it compiles under Apple OS X
Definition at line 35 of file sbrk.cc.
References sbrk().
Referenced by Value::catch_exception().