GNUAPL: src/Workspace.cc File Reference
Workspace.cc File Reference
#include <errno.h>
#include <string.h>
#include <sys/stat.h>
#include <fstream>
#include "Archive.hh"
#include "Command.hh"
#include "InputFile.hh"
#include "IO_Files.hh"
#include "LibPaths.hh"
#include "Output.hh"
#include "Quad_FFT.hh"
#include "Quad_FX.hh"
#include "Quad_GTK.hh"
#include "Quad_JSON.hh"
#include "Quad_MAP.hh"
#include "Quad_PLOT.hh"
#include "Quad_RVAL.hh"
#include "Quad_SQL.hh"
#include "Quad_TF.hh"
#include "Quad_XML.hh"
#include "SystemVariable.hh"
#include "UserFunction.hh"
#include "UserPreferences.hh"
#include "Workspace.hh"
#include "SystemVariable.def"
Classes
class HTML_streambuf
a streambuf that escapes certain HTML characters
class HTML_stream
a stream that escapes certain HTML characters
Macros
#define ro_sv_def(x, str, _txt)
#define rw_sv_def(x, str, _txt)
#define sf_def(x, str, _txt)
#define rw_sv_def(x, _str, _txt) the_workspace.v_ ## x.unmark_all_values();
#define ro_sv_def(x, _str, _txt) the_workspace.v_ ## x.unmark_all_values();
#define rw_sv_def(x, _str, _txt) count += get_v_ ## x().show_owners(out, value);
#define ro_sv_def(x, _str, _txt) count += get_v_ ## x().show_owners(out, value);
#define rw_sv_def(x, _str, _txt) get_v_ ## x().clear_vs();
#define ro_sv_def(x, _str, _txt)
#define rw_sv_def(x, _str, _txt) { get_v_ ##x().~x(); new (&get_v_ ##x()) x; }
#define ro_sv_def(x, _str, _txt)
#define ro_sv_def(x, _str, _txt)
#define rw_sv_def(x, _str, _txt)
Functions
UCS_string & MORE_ERROR ()
Macro Definition Documentation
ro_sv_def [1/6]
#define ro_sv_def (x, str, _txt)
Value:
if (*str) { UCS_string q(UNI_Quad_Quad);   q.append_UTF8(str); \
   distinguished_names.add_variable(q, ID_ ## x, &v_ ## x); }
ro_sv_def [2/6]
#define ro_sv_def (x, _str, _txt) the_workspace.v_ ## x.unmark_all_values();
ro_sv_def [3/6]
#define ro_sv_def (x, _str, _txt) count += get_v_ ## x().show_owners(out, value);
ro_sv_def [4/6]
#define ro_sv_def (x, _str, _txt)
ro_sv_def [5/6]
#define ro_sv_def (x, _str, _txt)
ro_sv_def [6/6]
#define ro_sv_def (x, _str, _txt)
rw_sv_def [1/6]
#define rw_sv_def (x, str, _txt)
Value:
if (*str) { UCS_string q(UNI_Quad_Quad);   q.append_UTF8(str); \
   distinguished_names.add_variable(q, ID_ ## x, &v_ ## x); }
rw_sv_def [2/6]
#define rw_sv_def (x, _str, _txt) the_workspace.v_ ## x.unmark_all_values();
rw_sv_def [3/6]
#define rw_sv_def (x, _str, _txt) count += get_v_ ## x().show_owners(out, value);
rw_sv_def [4/6]
#define rw_sv_def (x, _str, _txt) get_v_ ## x().clear_vs();
rw_sv_def [5/6]
#define rw_sv_def (x, _str, _txt) { get_v_ ##x().~x(); new (&get_v_ ##x()) x; }
rw_sv_def [6/6]
#define rw_sv_def (x, _str, _txt)
Value:
if (ID_ ## x != ID_Quad_SYL) \
   { get_v_ ## x().dump(*sout);   ++variable_count; }
sf_def
#define sf_def (x, str, _txt)
Value:
if (*str) { UCS_string q(UNI_Quad_Quad);   q.append_UTF8(str); \
   distinguished_names.add_function(q, ID_ ## x, x::fun); }
Function Documentation
MORE_ERROR()
UCS_string& MORE_ERROR ()
Definition at line 1113 of file Workspace.cc.
References Workspace::more_error().
Referenced by Value::add_member(), Quad_XML::all_members(), Quad_JSON::APL_to_JSON_string(), Symbol::assign(), Quad_PS::assign(), Symbol::assign_indexed(), Quad_PS::assign_indexed(), Quad_SYL::assign_indexed(), Symbol::assign_named_lambda(), Value::catch_ANY(), Value::catch_Error(), Value::catch_exception(), IndexExpr::check_index_range(), Value::check_lval_consistency(), Command::check_name_conflict(), Command::check_params(), Command::check_redefinition(), close_database(), Quad_FIO::close_handle(), Command::cmd_BOXING(), Command::cmd_COPY(), Command::cmd_COPY_ONCE(), Command::cmd_DROP(), Command::cmd_DUMP(), Command::cmd_OUT(), Command::cmd_SAVE(), Command::cmd_USERCMD(), XML_node::collect(), Quad_JSON::comma_count(), Executable::compute_lambda_body(), Quad_JSON::convert_file(), Quad_XML::convert_file(), Bif_F12_PICK::disclose_with_axis(), DLX_Root_Node::DLX_Root_Node(), Quad_CR::do_CR(), Quad_CR::do_CR40(), Quad_CR::do_CR41(), Quad_RVAL::do_eval_B(), Quad_FIO::do_FIO_57(), Quad_FX::do_quad_FX(), Quad_FIO::do_scanf(), Quad_FIO::do_sprintf(), Tokenizer::do_tokenize(), Workspace::dump_WS(), Cell::equal(), SymbolTable::erase_one_symbol(), Bif_F12_INTERVAL_INDEX::eval_AB(), Quad_MAP::eval_AB(), Quad_RVAL::eval_AB(), Quad_CR::eval_AB(), Quad_JSON::eval_AB(), Quad_PLOT::eval_AB(), Bif_F12_FORMAT::eval_AB(), Quad_XML::eval_AB(), Quad_INP::eval_AB(), Quad_FIO::eval_ALXB(), Quad_SQL::eval_AXB(), Quad_FIO::eval_AXB(), Bif_F2_RIGHT::eval_AXB(), Bif_F12_INTERVAL_INDEX::eval_B(), Quad_FIO::eval_B(), Quad_PLOT::eval_B(), Quad_EX::eval_B(), Quad_INP::eval_B(), Quad_UCS::eval_B(), Function::eval_fill_AB(), Function::eval_identity_fun(), Quad_FIO::eval_LXB(), Quad_SQL::eval_XB(), Quad_FIO::eval_XB(), Bif_F12_FORMAT::Format_LIFER::fill_data_fields(), XML_Loading_Archive::find_attr(), Command::finish_context(), NativeFunction::fix(), UserFunction::fix(), CDR::from_CDR(), Quad_L::get_apl_value(), Quad_R::get_apl_value(), Quad_X::get_apl_value(), CharCell::get_byte_value(), IntCell::get_byte_value(), Cell::get_char_value(), Quad_FIO::get_FILE(), Quad_FIO::get_file_entry(), Value::get_member(), Value::get_member_count(), Cell::get_pointer_value(), Quad_FIO::get_random(), XML_node::get_taglen(), XML_node::get_tagname(), Cell::greater(), Value::index(), Value::init_ravel(), Bif_F12_TRANSPOSE::inverse_permutation(), Quad_JSON::JSON_to_APL(), Command::lib_common(), SymbolTable::list(), Workspace::load_WS(), Parser::mark_lsymb(), missing_files(), Prefix::MM_is_FM(), Quad_XML::name_unsplit(), NativeFunction::NativeFunction(), Quad_XML::next_member(), XML_node::normalize_attribute_value(), not_allowed(), RegexpMatch::num_matches(), open_database(), Command::open_LIB_dir(), param_to_db(), Quad_JSON::parse_array(), Quad_JSON::parse_literal(), Quad_JSON::parse_number(), Quad_JSON::parse_object_member(), Quad_JSON::parse_string(), XML_node::parse_tag(), Quad_JSON::parse_value(), Bif_F12_PARTITION::partition(), Quad_XML::path_split(), Bif_F12_PICK::pick_offset(), DLX_Root_Node::preset(), PrintBuffer::PrintBuffer(), Workspace::push_SI(), XML_Loading_Archive::read_Workspace(), Bif_REDUCE::reduce(), Prefix::reduce_D_V__(), Prefix::reduce_END_A_GOTO_B(), Prefix::reduce_F_C_M_(), Prefix::reduce_F_C_M_C(), Prefix::reduce_F_D_C_B(), Prefix::reduce_F_M_C_(), Bif_REDUCE::reduce_n_wise(), Prefix::reduce_statements(), Prefix::reduce_V_RPAR_ASS_B(), Regexp::Regexp(), RegexpMatch::RegexpMatch(), Command::resolve_lib_wsname(), Symbol::resolve_lv(), run_generic(), run_generic_one_query(), XML_Saving_Archive::save(), Workspace::save_WS(), Bif_SCAN::scan(), Executable::setup_lambdas(), show_cols(), Quad_JSON::skip_string(), Quad_XML::split_name(), Quad_TF::tf1(), Quad_TF::tf1_inv(), Nabla::throw_edit_error(), throw_illegal_db_id(), Error::throw_parse_error(), Value::to_bitmap(), Value::to_shape(), Quad_XML::tree(), UCS_string::UCS_string(), Quad_FIO::UNSAFE(), Plot_window_properties::update(), XML_node::XML_node(), and Quad_XML::XML_to_APL().